### ISSUE TITLE
compile issues

### ISSUE THREAD

**Issue by shixinglingguihua** [BelledonneCommunications/linphone-android#10]
hello, while i exec cmd "make" in linphone-android project,linux terminal print a error .could you help me?

here is print from the terminal cmd “make” in the end
########################################################################
[ 63%] Performing configure step for 'EP_vpx'
/home/linguihua/lingugihua/projectFIle/linphone-android/WORK/android-arm64/cmake/EP_vpx_configure.sh: 41: /home/linguihua/lingugihua/projectFIle/linphone-android/WORK/android-arm64/cmake/EP_vpx_configure.sh: /home/linguihua/lingugihua/projectFIle/linphone-android/submodules/externals/libvpx/configure: **not found**
CMakeFiles/EP_vpx.dir/build.make:106: recipe for target # '/home/linguihua/lingugihua/projectFIle/linphone-android/WORK/android-arm64/Stamp/EP_vpx/EP_vpx-configure' failed
make[3]: *** [/home/linguihua/lingugihua/projectFIle/linphone-android/WORK/android-arm64/Stamp/EP_vpx/EP_vpx-configure] Error 127
make[3]: Leaving directory '/home/linguihua/lingugihua/projectFIle/linphone-android/WORK/android-arm64/cmake'
CMakeFiles/Makefile2:1276: recipe for target 'CMakeFiles/EP_vpx.dir/all' failed
make[2]: *** [CMakeFiles/EP_vpx.dir/all] Error 2
make[2]: Leaving directory '/home/linguihua/lingugihua/projectFIle/linphone-android/WORK/android-arm64/cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/linguihua/lingugihua/projectFIle/linphone-android/WORK/android-arm64/cmake'
Makefile:179: recipe for target 'arm64-build' failed
make: *** [arm64-build] Error 2
###########################################################################

**Comment by DatBewar** [comment]
Hello,
seems you submodule libvpx is not correct.
Go to this submodule:
`submodules/externals/libvpx`
and checkout it:
`git checkout .`
and try to build the project.

**Comment by shixinglingguihua** [comment]
hello, here is mine cmd lines,it mean another question. so i went to dir "/WORK/android-arm64/Stamp/EP_vpx/" to see file EP_vpx-configure,but it is dont exits. I  guess this file is created from makefile execed. howerver..........

 **cd  /home/linguihua/lingugihua/projectFIle/linphone-android/submodules/externals/libvpx/**
 **ls**

linguihua@ubuntu:~/lingugihua/projectFIle/linphone-android$ cd /home/linguihua/lingugihua/projectFIle/linphone-android/submodules/externals/libvpx/
linguihua@ubuntu:~/lingugihua/projectFIle/**linphone-android/submodules/externals/libvpx**$ ls
args.c               libs.mk         usage_cx.dox    vpx_ports
args.h               LICENSE         usage.dox       vpx_scale
AUTHORS              mainpage.dox    usage_dx.dox    vpxstats.c
build                md5_utils.c     video_common.h  vpxstats.h
CHANGELOG            md5_utils.h     video_reader.c  vpx_util
codereview.settings  PATENTS         video_reader.h  warnings.c
**configure**            rate_hist.c     video_writer.c  warnings.h
docs.mk              rate_hist.h     video_writer.h  **webmdec.cc**
examples             README          vp8             webmdec.h
examples.mk          solution.mk     vp9             webmenc.cc
ivfdec.c             test            vpx             webmenc.h
ivfdec.h             third_party     vpxdec.c        y4menc.c
ivfenc.c             tools           vpx_dsp         y4menc.h
ivfenc.h             tools_common.c  vpxenc.c        y4minput.c
keywords.dox         tools_common.h  vpxenc.h        y4minput.h
libs.doxy_template   tools.mk        vpx_mem
