### ISSUE TITLE
Error in "make" command in android-armv7  

### ISSUE THREAD

**Issue by mohitmathur1990** [BelledonneCommunications/linphone-android#100]
Hi,
I am facing this error while running the **make** command.

make[6]: Entering directory `/home/mohit/linphone-android/WORK/android-armv7/Build/sqlite3'
[ 50%] Building C object CMakeFiles/sqlite3.dir/sqlite3.c.o
/home/nowconfer/mohit/linphone-android/submodules/externals/sqlite3/sqlite3.c:23552:40: error: use of undeclared identifier 'mmap'
  { "mmap",       (sqlite3_syscall_ptr)mmap,     0 },
                                       ^
/home/mohit/linphone-android/submodules/externals/sqlite3/sqlite3.c:23587:22: error: invalid application of 'sizeof' to an incomplete type 'struct unix_syscall []'
    for(i=0; i<sizeof(aSyscall)/sizeof(aSyscall[0]); i++){
                     ^~~~~~~~~~
/home/mohit/linphone-android/submodules/externals/sqlite3/sqlite3.c:23596:22: error: invalid application of 'sizeof' to an incomplete type 'struct unix_syscall []'
    for(i=0; i<sizeof(aSyscall)/sizeof(aSyscall[0]); i++){
                     ^~~~~~~~~~
/home/mohit/linphone-android/submodules/externals/sqlite3/sqlite3.c:23623:20: error: invalid application of 'sizeof' to an incomplete type 'struct unix_syscall []'
  for(i=0; i<sizeof(aSyscall)/sizeof(aSyscall[0]); i++){
                   ^~~~~~~~~~
/home/mohit/linphone-android/submodules/externals/sqlite3/sqlite3.c:23640:16: error: invalid application of 'sizeof' to an incomplete type 'struct unix_syscall []'
    for(i=0; i<ArraySize(aSyscall)-1; i++){
               ^~~~~~~~~~~~~~~~~~~
/home/mohit/linphone-android/submodules/externals/sqlite3/sqlite3.c:8375:38: note: expanded from macro 'ArraySize'
#define ArraySize(X)    ((int)(sizeof(X)/sizeof(X[0])))
                                     ^~~
/home/mohit/linphone-android/submodules/externals/sqlite3/sqlite3.c:23644:14: error: invalid application of 'sizeof' to an incomplete type 'struct unix_syscall []'
  for(i++; i<ArraySize(aSyscall); i++){
             ^~~~~~~~~~~~~~~~~~~
/home/mohit/linphone-android/submodules/externals/sqlite3/sqlite3.c:8375:38: note: expanded from macro 'ArraySize'
#define ArraySize(X)    ((int)(sizeof(X)/sizeof(X[0])))
                                     ^~~
6 errors generated.

**Comment by DatBewar** [comment]
Hello,
did you update correctly the submodules?
`git submodule sync && git submodule update --init --recursive`

**Comment by mohitmathur1990** [comment]
Yes @DatBewar we updated the submodules correctly.

**Comment by mohitmathur1990** [comment]
Hi @DatBewar  , you can mark this issue as fixed. My mistake I took the latest ndk release for building.
Thanks for your support.
