### ISSUE TITLE
incoming video rotated 90 degrees at video phone calls

### ISSUE THREAD

**Issue by fengfeilong0529** [BelledonneCommunications/linphone-android#1001]
Hello,
I'm developing an android application by using you library;And i met a problem during video phone calls .Receiving different device's video call may display different,sometimes the video rotated 90 degrees.

I want to know if there is a method that i can get the incoming video's rotation information or video size info including video width and video height ,so i can adjust my view's degree  dynamically by these info.

Thanks for the advice!

**Comment by Viish** [comment]
Hi,
Actually it's the sender that should rotate it's video correctly before sending it to you.
That being said, you can get the received video size by getting the current params of a call and then calling callParams.getReceivedVideoDefinition().
For the rotation, you can look how we do it for the local video preview in https://gitlab.linphone.org/BC/public/mediastreamer2/blob/master/java/src/org/linphone/mediastream/video/capture/CaptureTextureView.java
Cheers,

**Comment by fengfeilong0529** [comment]
OK,I'll have a try.

Thanks very much！
