### ISSUE TITLE
Incoming call when the user is outside the application.

### ISSUE THREAD

**Issue by Strikelon** [BelledonneCommunications/linphone-android#1002]
Hello. I am studying the linphone android code in branch master to understand how the incoming call screen starts when the user is outside the application.
I’m looking at the master branch, can you tell me which classes are responsible for observing event that incoming call came in background, for launching the application from background at the time of an incoming call and showing the screen of an incoming call?
I read something about Firebase push notifications in issue, but I also put the logs in the FirebaseMessaging class in the onMessageReceived method in the master branch of linphone app, to make sure that the startup logic comes from there, but the logs from there do not show that the onMessageReceived method worked and any messages were received, but the application starts and the incoming call screen is displayed. I don’t understand how it works and which classes are responsible for this logic? Can you advice me?
Thank you!

**Comment by Viish** [comment]
Hi,
Firebase push notifications are only used when the app is killed.
If the app is alive (even in background), our SDK will receive the incoming call.  When the app is alive, the CoreContext class holds the Core object which has a listener for call state changed.
To display incoming call notification, the CoreContext calls the NotificationsManager which in turn calls Compatibility.createIncomingCallNotification() method.
Cheers,
