### ISSUE TITLE
Sound Speaker issue

### ISSUE THREAD

**Issue by Amrutha5678** [BelledonneCommunications/linphone-android#1004]
Hello Team,
Good Afternoon
I am facing an issue with speakers.
Here is the scenario. I kept a song in my phone and after that i called to userB. So after they have call (CALL finished) again my song is resumed but the sound is coming from the headphone pin. Song is not getting in speaker mode.
And when i click on numbers in dialpad song sound is going to headphone mode.
Actually this problem is in linphone 4.2. When i install in playstore this problem is not reproducing.
Could you please help me to trigger this problem in linphone 4.2?
Is there any thing to change in code?
Thank You

**Comment by Viish** [comment]
Hi,
This most probably is an audio routing issue.
Check the difference in your code and ours regarding calls to routeAudioToSpeakerHelper() method.
As you don't reproduce with the latest version I close the issue as it is not really one.
Cheers,
