### ISSUE TITLE
UPnP option is missing

### ISSUE THREAD

**Issue by lnpz** [BelledonneCommunications/linphone-android#1006]
There's no option to enable UPnP. The website claims it supports UPnP https://www.linphone.org/news/linphone-upnp

**Comment by Viish** [comment]
Indeed, thanks for pointing that out.
Actually UPnP is not maintained anymore (but should still work) in our SDK/App, so we should remove that from the website.

**Comment by lnpz** [comment]
Would it be possible to reinstate the UPnP option or add PCP/NAT-PMP? It's the only solution that works with symmetric NAT without a TURN server. Ideally it should be able to work with ICE, the external IP:port returned by UPnP is just another ICE candidate.
