### ISSUE TITLE
Questions about no audio video

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1008]
Hi,
When WiFi and Ethernet are on, A calls B, They can talk normally after receiving, at this time, unplug the Ethernet cable, and then plug it in, there is no RTP flow when A and B are talking. 
I found that the SDK version in 2015 didn't have this problem, and I don't know how to solve it now.

thanks。
[linphone-no-audiovideo.txt](https://github.com/BelledonneCommunications/linphone-android/files/4620240/linphone-no-audiovideo.txt)
[linphone-unplug-plug-eth.txt](https://github.com/BelledonneCommunications/linphone-android/files/4620242/linphone-unplug-plug-eth.txt)

**Comment by Viish** [comment]
In your logs there are no connection change and the logs for the call show from the start that the app doesn't receive any audio.
Also it seems you are using a quite old version of the app (and maybe the SDK?).

**Comment by fengqz627** [comment]
Hi,

I have add log in linphonemanager.java,  when I unplug the Ethernet cable, and then plug it in, I get  log linphone-unplug-plug-1.txt, you can see my log:
org.linphone I/mediastreamer: fqz 73 LinphoneManager.java 
org.linphone I/mediastreamer: fqz 64 LinphoneManager.java 
org.linphone I/mediastreamer: fqz 643 LinphoneManager.java 
org.linphone I/mediastreamer: fqz 646 LinphoneManager.java 
org.linphone I/mediastreamer: fqz 648 LinphoneManager.java 
org.linphone I/mediastreamer: fqz 649 LinphoneManager.ja

*****************************
[linphone-unplug-plug-1.txt](https://github.com/BelledonneCommunications/linphone-android/files/4620699/linphone-unplug-plug-1.txt)

public void connectivityChanged(ConnectivityManager cm, boolean noConnectivity) {
	Log.i("fqz 73 LinphoneManager.java ");
		updateNetworkReachability();
	}

public void updateNetworkReachability() {
		if (mConnectivityManager == null) return;

		boolean connected = false;
		NetworkInfo networkInfo = mConnectivityManager.getActiveNetworkInfo();
		connected = networkInfo != null && networkInfo.isConnected();

   Log.i("fqz 64 LinphoneManager.java ");
		if (networkInfo == null && Version.sdkAboveOrEqual(Version.API21_LOLLIPOP_50)) {
		Log.i("fqz 640 LinphoneManager.java ");
			for (Network network : mConnectivityManager.getAllNetworks()) {
				if (network != null) {
				Log.i("fqz 641 LinphoneManager.java ");
					networkInfo = mConnectivityManager.getNetworkInfo(network);
					if (networkInfo != null && networkInfo.isConnected()) {
					Log.i("fqz 642 LinphoneManager.java ");
						connected = true;
						break;
					}
				}
			}
		}

		if (networkInfo == null || !connected) {
			Log.i("No connectivity: setting network unreachable");
			mLc.setNetworkReachable(false);
		} else if (dozeModeEnabled) {
			Log.i("Doze Mode enabled: shutting down network");
			mLc.setNetworkReachable(false);
		} else if (connected){
			manageTunnelServer(networkInfo);
         Log.i("fqz 643 LinphoneManager.java ");
			boolean wifiOnly = LinphonePreferences.instance().isWifiOnlyEnabled();
			if (wifiOnly){
	   	 Log.i("fqz 644 LinphoneManager.java ");
				if (networkInfo.getType() == ConnectivityManager.TYPE_WIFI) {
					mLc.setNetworkReachable(true);
					Log.i("fqz 645 LinphoneManager.java ");
				}
				else {
					Log.i("fqz Wifi-only mode, setting network not reachable");
					mLc.setNetworkReachable(false);
				}
			} else {
				int curtype=networkInfo.getType();
            Log.i("fqz 646 LinphoneManager.java ");
				if (curtype != mLastNetworkType) {
					//if kind of network has changed, we need to notify network_reachable(false) to make sure all current connections are destroyed.
					//they will be re-created during setNetworkReachable(true).
					Log.i("fqz 647 Connectivity has changed.");
					mLc.setNetworkReachable(false);
				}
				mLc.setNetworkReachable(true);
				Log.i("fqz 648 LinphoneManager.java ");
				mLastNetworkType = curtype;
			}
		}

		if (mLc.isNetworkReachable()) {
			// When network isn't available, push informations might not be set. This should fix the issue.
			Log.i("fqz 649 LinphoneManager.java ");
			LinphonePreferences prefs = LinphonePreferences.instance();
			prefs.setPushNotificationEnabled(prefs.isPushNotificationEnabled());
		}
	}	
[linphone-no-audio-video-1.txt](https://github.com/BelledonneCommunications/linphone-android/files/4620705/linphone-no-audio-video-1.txt)
[linphone-unplug-plug-1.txt](https://github.com/BelledonneCommunications/linphone-android/files/4620706/linphone-unplug-plug-1.txt)

**Comment by Viish** [comment]
You are doing you own connectivity handler, I can't help you with that.
You should instead enable the one in our SDK: in your linphonerc configuration file, add in the [sip] section the following: auto_net_state_mon=1
