### ISSUE TITLE
is there any way to do video conferencing using linphone sdk in android?

### ISSUE THREAD

**Issue by Mukesh2310** [BelledonneCommunications/linphone-android#1009]
Actually i am searching for video conference in linphone SDK but somehow not able to achieve the results if someone have idea please share with me its great help thanks in advance as right now only single video call is there in linephone

**Comment by Viish** [comment]
We have started to introduce a "local video conferencing" mode like our "local audio conferencing".
This is not available yet on published SDK (you'd have to build the feature/5.0-videoconf branch of our SDK and use the feature/videoconf branch of the android app), but it will be part of the next release to be published (ETA this summer).

**Comment by djkskqyr3** [comment]
Hi, @Viish 
May I ask about video conference? 
Still are you working on video conference? I am very interesting about video group conference.
Thank you

**Comment by Viish** [comment]
Hi,
the local video conferencing feature is available in beta in 4.5 SDK and with feature/kotlin_rewrite branch of the app.

**Comment by djkskqyr3** [comment]
Thank you very much

**Comment by djkskqyr3** [comment]
There is no java branch for local video conferencing?

**Comment by Viish** [comment]
No we haven't implemented it in our Java application.

**Comment by djkskqyr3** [comment]
The local video conferencing means,  all video will be mix on client side? not server side, right?

**Comment by djkskqyr3** [comment]
and how many supports members for the video group call?

**Comment by djkskqyr3** [comment]
Where I can get SDK 4.5 beta? I built SDK from the source code and only I got linphone-sdk-android-4.5.0-alpha.12+be09fb0

**Comment by Viish** [comment]
> The local video conferencing means, all video will be mix on client side? not server side, right?

Yes, the "host" receives all video streams and send the "active" one to everyone and the "previously active" one to the currently active one.

> and how many supports members for the video group call? (and for the audio group call ?)

That depends of the host. During the COVID-19 lockdown we managed to do video conferencing of more than 10 people but we haven't tried more.

> Where I can get SDK 4.5 beta? I built SDK from the source code and only I got linphone-sdk-android-4.5.0-alpha.12+be09fb0

There is no 4.5 beta currently, only the alpha.

**Comment by djkskqyr3** [comment]
Thank you for your explain.
I hope you and your team are good from COVID-19,

>https://github.com/BelledonneCommunications/linphone-android/issues/1009#issuecomment-650825957
You said that local video conferencing is in 4.5 beta

**Comment by Viish** [comment]
> I hope you and your team are good from COVID-19,

Yes we're all fine, thanks.

> You said that local video conferencing is in 4.5 beta

The feature is in beta state, and is available starting the 4.5 alpha SDK

**Comment by djkskqyr3** [comment]
Sorry to bother you
This is the last question
How many members can join to audio group call?

**Comment by Viish** [comment]
Technically there is no limit, that depends on the host hardware.

**Comment by djkskqyr3** [comment]
Thank you for your help
