### ISSUE TITLE
App Launch Delay when Push Notification is Active

### ISSUE THREAD

**Issue by antongavrilenkov** [BelledonneCommunications/linphone-android#101]
I use Flexisip as a sip proxy.
There is ~50 sec delay between linphone app received push notifications from Firebase and the app launch.

Debug linphone
08-14 16:12:53.914 9348-14095/org.linphone I/FirebaseMessaging: [Push Notification] Received
08-14 16:12:53.918 9348-9348/org.linphone I/LinphoneService: ==== Phone information dump ====
08-14 16:12:53.919 9348-9348/org.linphone I/LinphoneService: DEVICE=generic_x86
MODEL=Android SDK built for x86
MANUFACTURER=Google
SDK=24
Supported ABIs=x86,
08-14 16:12:53.919 9348-9348/org.linphone I/LinphoneService: Linphone version is 3.2.8 (3280)
08-14 16:12:58.171 9348-9348/org.linphone I/LinphoneService: text: %s registered
08-14 16:13:50.839 9348-9348/org.linphone D/MediaPlayer: setSubtitleAnchor in MediaPlayer
08-14 16:13:51.005 9348-9348/org.linphone V/FA: onActivityCreated
08-14 16:13:51.005 9348-9348/org.linphone I/LinphoneService: Activity created:org.linphone.LinphoneActivity@3705c68
08-14 16:13:51.068 9348-9348/org.linphone I/LinphoneService: Activity started:org.linphone.LinphoneActivity@3705c68
08-14 16:13:51.070 9348-9348/org.linphone I/LinphoneService: Activity resumed:org.linphone.LinphoneActivity@3705c68

**Comment by DatBewar** [comment]
Hello, are you on Android emulator? I can't reproduce the delay on real device.

**Comment by antongavrilenkov** [comment]
Hello.
I've did on Android emulator and on real device.
