### ISSUE TITLE
No video display

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1010]
Hi,

Most of the time during the call, there is no video display. Do you know whether it is related to the network environment?
One of the devices used for the call is a linphone. The other side is not.  Linpone device sends video. the other devices receives video.

From log, I feel  ,u=11265.81 is not normal,Why is it so big? What does it have to do with?
[not-display-video.txt](https://github.com/BelledonneCommunications/linphone-android/files/4627028/not-display-video.txt)

RTP  audio=[d=76.24,u=79.97], video=[d=0.00,u=11265.81,ed=0.00], text=[d=0.00,u=0.00] kbits/sec

**Comment by Viish** [comment]
Hi,
From your logs you never receive video:
```
05-14 10:41:21.254  1154  1254 I tag_linphone: ===========================================================
05-14 10:41:21.254  1154  1254 I tag_linphone:              VIDEO SESSION'S RTP STATISTICS
05-14 10:41:21.254  1154  1254 I tag_linphone: -----------------------------------------------------------
05-14 10:41:21.254  1154  1254 I tag_linphone: sent                                      39482 packets
05-14 10:41:21.254  1154  1254 I tag_linphone:                                               0 duplicated packets
05-14 10:41:21.255  1154  1254 I tag_linphone:                                        49141036 bytes
05-14 10:41:21.255  1154  1254 I tag_linphone: received                                      0 packets
```

You should check the other side logs to understand why. From linphone side everything is fine. Yes the bandwidth used in upload is a bit high but we have algorithms to only use what's available so it means your network can handle it, no worries (as long as the other side receives video it means it works well).
