### ISSUE TITLE
push token send only after turn off and turn on switch button in network setting

### ISSUE THREAD

**Issue by bottookku** [BelledonneCommunications/linphone-android#1012]

**Comment by Viish** [comment]
Please attach full library logs.

**Comment by bottookku** [comment]
https://www.linphone.org:444//tmp/5ebe533fb3dc8_651f7aed8590cab1109a.gz

**Comment by Viish** [comment]
At the beginning of your logs the app is started because of a received push.
That being said, indeed even when the push token is available if doesn't show in the REGISTER contact header.
Have you made changes to the app? Also please try on a real device, not the simulator.

**Comment by bottookku** [comment]
i trying it on real phone and all the same. i edit only google-services.json

**Comment by Viish** [comment]
If the only change you did is edit the google-services.json file there shouldn't be any issue as you are the only person I know with this issue...
