### ISSUE TITLE
Set local linphone sdk not working

### ISSUE THREAD

**Issue by SarunyuPrasert** [BelledonneCommunications/linphone-android#1013]
I clone a linphone sdk branch release/4.3 and build it successfully then I clone an android project  and follwing a instruction to set local sdk by adding path to LinphoneSdkBuildDir in grandle.properties

It look like this
![Screen Shot 2563-05-15 at 16 36 40](https://user-images.githubusercontent.com/18572139/82035822-45649000-96ca-11ea-97f4-9917e35a576a.png)
and in my build-android folder
![Screen Shot 2563-05-15 at 16 37 56](https://user-images.githubusercontent.com/18572139/82035940-704ee400-96ca-11ea-96d1-ae8bdebb942d.png)

But when It register to brekeke server it show a 4.4 version
![Screen Shot 2563-05-15 at 16 38 55](https://user-images.githubusercontent.com/18572139/82036052-9c6a6500-96ca-11ea-9784-853de13c87a4.png)

Even I try to get a version from core it's still 4.4
![Screen Shot 2563-05-15 at 16 40 52](https://user-images.githubusercontent.com/18572139/82036256-df2c3d00-96ca-11ea-9653-03197fff098b.png)

**Comment by Viish** [comment]
Indeed, the release/4.3 branch of the SDK isn't compatible with this procedure (at least automatically).
After building your SDK, you need to execute the following command:
`../cmake/Android/gradlew -b upload.gradle publish`
