### ISSUE TITLE
How to start Ethernet

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1015]
Hi，
When the Ethernet and WiFi are connected, I unplug the Ethernet and plug it in， connection change , I found that in linphonemanager.java, mlc.setnetworkreachable (false) will be called first, and then mlc.setnetworkreachable (true);  However, when calling mlc.setnetworkreachable (true), it is found that the address of WiFi is obtained by tmp in linphone_core_get_local_ip(lc, AF_UNSPEC, NULL, tmp);  And the following log will be generated after connecting, which should be the reason why Ethernet is not started. How to start Ethernet and get Ethernet address?

2121-2601/system_process E/ConnectivityService: NetworkAgent not found for EVENT_NETWORK_PROPERTIES_CHANGED
2121-2601/system_process E/ConnectivityService: EVENT_NETWORK_SCORE_CHANGED from unknown NetworkAgent
2121-2601/system_process E/ConnectivityService: EVENT_NETWORK_CAPABILITIES_CHANGED from unknown NetworkAgent
2121-2601/system_process E/ConnectivityService: EVENT_NETWORK_INFO_CHANGED from unknown NetworkAgent
2121-2601/system_process E/ConnectivityService: NetworkAgent not found for EVENT_NETWORK_PROPERTIES_CHANGED
2121-2601/system_process E/ConnectivityService: EVENT_NETWORK_SCORE_CHANGED from unknown NetworkAgent
2121-2244/system_process D/EthernetNetworkFactory: updateInterface: eth0 link up
2121-2635/system_process D/EthernetNetworkFactory: sendEthernetStateChangedBroadcast: curState = CONNECTING
2121-2635/system_process E/ActivityManager: Prevent non-system code  from sending protected broadcasts
2121-15621/system_process I/EthernetNetworkFactory: dhcpThread(eth0): mNetworkInfo=[type: Ethernet[], state: DISCONNECTED/DISCONNECTED, reason: (unspecified), extra: 00:06:00:00:c3:20, roaming: false, failover: false, isAvailable: true]
2121-15621/system_process D/EthernetServiceImpl: getConfiguration
2121-15621/system_process I/EthernetNetworkFactory: get eth0 IpAssignment: DHCP
2121-15621/system_process D/NetUtils:  in to startDhcp
2121-15621/system_process D/DHCP: name :dhcp_start
2121-15621/system_process D/DHCP: wait_for_property
2121-15621/system_process D/DHCP: wait_for_property  :init.svc.dhcpcd_eth0:  7
2121-15621/system_process D/DHCP: wait_for_property: name init.svc.dhcpcd_eth0: stopped

**Comment by fengqz627** [comment]
If WiFi is manually turned off and then turned on in Android platform settings, the problem can also be solved. How to achieve the same effect in linphone.

**Comment by fengqz627** [comment]
add log:

E/Netd: netlink response contains error (No such file or directory)

...

**Comment by Viish** [comment]
Please attach full library logs showing the issue.

**Comment by fengqz627** [comment]
The debug I  added is as follows:
[plug-unplug-ethernet.txt](https://github.com/BelledonneCommunications/linphone-android/files/4643559/plug-unplug-ethernet.txt)

In linphonemanager.java:
	public void connectivityChanged(ConnectivityManager cm, boolean noConnectivity) {
	 Log.i("fqz 73 connectivityChanged ");
		updateNetworkReachability();
	}

	public void updateNetworkReachability() {
		if (mConnectivityManager == null) return;

		boolean connected = false;
		NetworkInfo networkInfo = mConnectivityManager.getActiveNetworkInfo();
		connected = networkInfo != null && networkInfo.isConnected();


           Log.i("fqz 100 LinphoneManager.java connected = "+connected);
		if (networkInfo == null && Version.sdkAboveOrEqual(Version.API21_LOLLIPOP_50)) {
		Log.i("fqz 101 LinphoneManager.java when networkInfo == null ");
			for (Network network : mConnectivityManager.getAllNetworks()) {
				if (network != null) {
				Log.i("fqz 102 LinphoneManager.java ");
					networkInfo = mConnectivityManager.getNetworkInfo(network);
					if (networkInfo != null && networkInfo.isConnected()) {
					Log.i("fqz 103 LinphoneManager.java ");
						connected = true;
						break;
					}
				}
			}
		}

		if (networkInfo == null || !connected) {
			Log.i("fqz 104 No connectivity: setting network unreachable");
			mLc.setNetworkReachable(false);
		} else if (dozeModeEnabled) {
			Log.i("fqz 105 Doze Mode enabled: shutting down network, dozeModeEnabled is true");
			mLc.setNetworkReachable(false);
		} else if (connected){
			manageTunnelServer(networkInfo);
         Log.i("fqz 106 LinphoneManager.java networkInfo.getType() = "+networkInfo.getType());
			boolean wifiOnly = LinphonePreferences.instance().isWifiOnlyEnabled();
			if (wifiOnly){
	   	 Log.i("fqz 107 LinphoneManager.java wifiOnly ");
				if (networkInfo.getType() == ConnectivityManager.TYPE_WIFI) {
					mLc.setNetworkReachable(true);
					Log.i("fqz  TYPE_WIFI LinphoneManager.java ");
				}
				else {
					Log.i("fqz Wifi-only mode, setting network not reachable");
					mLc.setNetworkReachable(false);
				}
			} else {
				int curtype=networkInfo.getType();
                          Log.i("fqz 108 LinphoneManager.java not wifiOnly, curtype = "+curtype +"  mLastNetworkType = "+mLastNetworkType);
				if (curtype != mLastNetworkType) {
					//if kind of network has changed, we need to notify network_reachable(false) to make sure all current connections are destroyed.
					//they will be re-created during setNetworkReachable(true).
					Log.i("fqz 109 Connectivity has changed. curtype != mLastNetworkType");
					mLc.setNetworkReachable(false);
				}
				mLc.setNetworkReachable(true);
				mLastNetworkType = curtype;
			}
		}

		if (mLc.isNetworkReachable()) {
			// When network isn't available, push informations might not be set. This should fix the issue.
			Log.i("fqz 111 LinphoneManager.java ");
			LinphonePreferences prefs = LinphonePreferences.instance();
			prefs.setPushNotificationEnabled(prefs.isPushNotificationEnabled());
		}
	}	

-----------------------
In linphonecore.c:

static void disable_internal_network_reachability_detection(LinphoneCore *lc){
	ms_message("fqz Disabling automatic network state monitoring auto_net_state_mon = %d",lc->auto_net_state_mon);
	if (lc->auto_net_state_mon) {
		ms_message("fqz Disabling automatic network state monitoring");
		lc->auto_net_state_mon=FALSE;
	}
}

  static void set_sip_network_reachable(LinphoneCore* lc,bool_t is_sip_reachable, time_t curtime){
	// second get the list of available proxies
	const bctbx_list_t *elem = NULL;

ms_message("fqz 1 linphonecore.c set_sip_network_reachable is_sip_reachable= [%s]",is_sip_reachable?"UP":"DOWN");
	if (lc->sip_network_reachable==is_sip_reachable) {
		ms_message("fqz 01 linphonecore.c set_sip_network_reachable");
		return; // no change, ignore.
		}
	lc->network_reachable_to_be_notified=TRUE;

	if (is_sip_reachable){
		ms_message("fqz 2 linphonecore.c SIP is_sip_reachable is ok");
		getPlatformHelpers(lc)->setDnsServers();
		if (lc->sip_conf.guess_hostname) update_primary_contact(lc);
	}

	ms_message("fqz 3 linphonecore.c SIP network reachability state is now [%s]",is_sip_reachable?"UP":"DOWN");
	for(elem=linphone_core_get_proxy_config_list(lc);elem!=NULL;elem=elem->next){
		LinphoneProxyConfig *cfg=(LinphoneProxyConfig*)elem->data;
		stop_refreshing_proxy_config(is_sip_reachable, cfg);
	}
	for(elem=lc->sip_conf.deleted_proxies;elem!=NULL;elem=elem->next){
		LinphoneProxyConfig *deleted_cfg=(LinphoneProxyConfig*)elem->data;
		stop_refreshing_proxy_config(is_sip_reachable, deleted_cfg);
	}

	lc->netup_time=curtime;
	lc->sip_network_reachable=is_sip_reachable;

	if (!lc->sip_network_reachable){
		ms_message("fqz 4 linphonecore.c SIP network reachability state is now");
		linphone_core_invalidate_friend_subscriptions(lc);
		lc->sal->resetTransports();
	}
}

static void set_media_network_reachable(LinphoneCore* lc, bool_t is_media_reachable){
	ms_message("fqz 1 Media network reachability state is now is_media_reachable= [%s]",is_media_reachable?"UP":"DOWN");
	if (lc->media_network_reachable==is_media_reachable){
		ms_message("fqz 01 set_media_network_reachable");
		return; // no change, ignore.
		}
	lc->network_reachable_to_be_notified=TRUE;

	ms_message("fqz 2 Media network reachability state is now [%s]",is_media_reachable?"UP":"DOWN");
	lc->media_network_reachable=is_media_reachable;

	if (lc->media_network_reachable){
		if (lc->bw_controller){
			ms_message("fqz 3 Media network reachability state is now");
			ms_bandwidth_controller_reset_state(lc->bw_controller);
		}
	}
} 


static void update_primary_contact(LinphoneCore *lc){
	char *guessed=NULL;
	char tmp[LINPHONE_IPADDR_SIZE];
	int port;

	LinphoneAddress *url;
	ms_message("fqz 1 update_primary_contact guessed_contact=%s",lc->sip_conf.guessed_contact);
	if (lc->sip_conf.guessed_contact!=NULL){
		ms_free(lc->sip_conf.guessed_contact);
		lc->sip_conf.guessed_contact=NULL;
		ms_message("fqz 2 update_primary_contact");
	}
	ms_message("fqz 3 update_primary_contact contact=%s",lc->sip_conf.contact);
	url=linphone_address_new(lc->sip_conf.contact);
	if (!url){
		ms_error("Could not parse identity contact !");
		ms_message("fqz 4 update_primary_contact");
		url=linphone_address_new("sip:unknown@unkwownhost");
	}
	linphone_core_get_local_ip(lc, AF_UNSPEC, NULL, tmp);
	if (strcmp(tmp,"127.0.0.1")==0 || strcmp(tmp,"::1")==0 ){
		ms_warning("Local loopback network only !");
		lc->sip_conf.loopback_only=TRUE;
		ms_message("fqz 6 update_primary_contact");
	}else lc->sip_conf.loopback_only=FALSE;
	linphone_address_set_domain(url,tmp);
	port = linphone_core_get_sip_port(lc);   
	ms_message("fqz 7 update_primary_contact port=%d",port);
	if (port > 0){
		linphone_address_set_port(url, port); /*if there is no listening socket the primary contact is somewhat useless,
		it won't work. But we prefer to return something in all cases. It at least shows username and ip address.*/
			ms_message("fqz 8 update_primary_contact");
		}
	guessed=linphone_address_as_string(url);
	lc->sip_conf.guessed_contact=guessed;
	linphone_address_unref(url);
}

**Comment by Viish** [comment]
You are using a old version of the app and of the SDK.
Please update to latest version & enable SDK network monitoring.
