### ISSUE TITLE
no video

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1016]
Hi,

A device has camera, B device has no camera，If B calls A and starts talking, but B does not receive the video, but has audio.
I found that the following RTP " video=[d=0.03,u=0.77" are so small,The video packet sent is 0, see log. Why is this?

RTP  audio=[d=18.55,u=45.05], video=[d=0.03,u=0.77,ed=0.00], text=[d=0.00,u=0.00] kbits/sec
RTCP audio=[d=0.01,u=0.00], video=[d=0.02,u=2.21], text=[d=0.00,u=0.00] kbits/sec
Thread processing load: audio=55.6859    video=5.92722   text=0
....
[log.txt](https://github.com/BelledonneCommunications/linphone-android/files/4648051/log.txt)

**Comment by fengqz627** [comment]
With the log of device B.
[B-devices-log.txt](https://github.com/BelledonneCommunications/linphone-android/files/4648064/B-devices-log.txt)

**Comment by fengqz627** [comment]
I feel that the "d=" and "u=" of video are very large and very small, and I can't receive video.
For example, there is no video in the following situation：
RTP audio=[d=76.24,u=79.97], video=[d=0.00,u=11265.81,ed=0.00], text=[d=0.00,u=0.00] kbits/sec。

**Comment by fengqz627** [comment]
In addition，this version of linphone I use is not up-to-date, because the docking of this version of linphone to our platform has been almost completed, and we need to finish the docking before switching to a new one. We don't change our linphones often because it's a lot of work.
I don't think this problem has anything to do with the linphone version.

thanks.

**Comment by Viish** [comment]
Your problem is that A isn't sending it's video to B, hence the low bandwidth in the stats (u means upload, d means download).
As B is using a static image as it doesn't have a camera, the bandwidth is quite low too but that's expected.

Please note that if you are making changes to either our SDK or our app and publishing it, you either need to follow the GPL license and publish your code source with your changes or buy a proprietary license from us (contact sales@belledonne-communications.com) that includes some advanced support for issues like this.

**Comment by fengqz627** [comment]
I see this information in the log. Is this the cause of the problem：
CameraHal: getFrame(670): getFrame(670): VIDIOC_DQBUF Failed!!! err[Invalid argument]

**Comment by Viish** [comment]
Yes, sadly it's not the first time we see issues in MediaCodec implementation of rockship devices...
You try to switch to VP8 or lower the resolution (maybe it doesn't have enough resources to encode/decode 720P).

**Comment by fengqz627** [comment]
When the above problem occurs, B calls A, and A has no video to send to B, but strangely, if A calls B (of course, using the early media function), video can be displayed.

**Comment by Viish** [comment]
In early-media there won't be any decoder on A side, so it will have more CPU resources to use for encoding, maybe that's why.

**Comment by fengqz627** [comment]
I think the encoding and decoding ability of rk3288 is good, at least much better than the allwinner we used before. Is it possible that this bug exists in rk3288 USB UVC camera

**Comment by fengqz627** [comment]
Thank you very much for your help. I admire you very much!

**Comment by fengqz627** [comment]
When B calls A, if I set it at A "params.setVideoDirection ( MediaDirection.SendOnly )", does A need not decode the video？

**Comment by Viish** [comment]
No, A doesn't decode video if it's call params are set to sendOnly.

**Comment by fengqz627** [comment]
That's equivalent to using early media when A calls B. In that case，maybe B can display video when B calls A.
