### ISSUE TITLE
No DTMF events sent

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1019]
Using the kotlin_rewrite branch, when I press numbers on the number pad while in a call, no DTMF is sent to the remote.  I do have both `SIP INFO` and `RFC 2833` enabled in the _Call_ menu.  Using a packet sniffer I could verify that no `RTP EVENT`s at all are sent during the call, and so definitely no _RFC 2833_ tone events.

**Comment by Viish** [comment]
Fixed in
```
commit 2f67a681662aa9bf431537e0f07a4cff9abf0b6d (HEAD -> feature/kotlin_rewrite, origin/feature/kotlin_rewrite)
Author: Sylvain Berfini <sylvain.berfini@belledonne-communications.com>
Date:   Wed May 20 10:30:12 2020 +0200

    Fixed DTMF not being sent in call
```

**Comment by iganev** [comment]
Can I resurrect this issue? It reappeared after the latest update.
