### ISSUE TITLE
Android SDK without video is not available

### ISSUE THREAD

**Issue by vijayaa** [BelledonneCommunications/linphone-android#102]
Please provide documentation on how to build SDK without video. Below link is throwing 404
http://linphone.org/snapshots/android/liblinphone-android-sdk-no-video-latest.zip

**Comment by vijayaa** [comment]
Can someone please reply , we need only audio call support

**Comment by chowdarynamala** [comment]
You need to build the sdk by following steps in README document of Linphone Android project. Make sure to change the Codec definitions related to Video to OFF in prepare.py script. 
For example:
-DENABLE_VIDEO=NO
-DENABLE_WEBRTC_AECM=NO
-DENABLE_WEBRTC_AEC=NO

**Comment by DatBewar** [comment]
You can find liblinphone-android-sdk--no-nonfreecodecs-no-video here:
https://www.linphone.org/snapshots/android/
