### ISSUE TITLE
Linphone-Android Unable to send Authorization Header to Server (Cant Make OutGoing Call)

### ISSUE THREAD

**Issue by Adnan-addi** [BelledonneCommunications/linphone-android#1020]
Hi @Viish 
I have been working on latest Linphone-Android I am connecting to server along Auth ID 
incoming works ok but unable to send outgoing calls

I bumped into https://github.com/BelledonneCommunications/linphone-android/issues/216 this link and found that version 4.0.1 had fixed this 

but if 4.0.1 also could not make outbound calls and i can see in server logs that no Authorization Header Received .
can you please guide what i am now doing wrong how i can send Authorization Header in Linphone android , i am facing same issue in Linphone Desktop app aswel but my target is Linphone Apps.

https://www.linphone.org:444//tmp/5ec65eda00795_459b83c53cd714e0a2fb.gz

these are the logs from my device -

kindly can you check whats wrong why i can't make outbound calls

Thank You .

**Comment by Adnan-addi** [comment]
https://www.linphone.org:444//tmp/5ec65eda00795_459b83c53cd714e0a2fb.gz

these are the logs from my device - 

kindly can you check whats wrong why i can't make outbound calls

**Comment by gabigeo** [comment]
I support Adnan. When the WWW-Authenticate header is present in a "401 Unauthorized" response Linphone should send back an INVITE including the Authorization header.

**Comment by Adnan-addi** [comment]
@Viish ?

**Comment by Viish** [comment]
I'll take a look at that on Monday.

**Comment by Adnan-addi** [comment]
ok Thank you so much for your reply .

**Comment by Adnan-addi** [comment]
@Viish 
Its Monday today , 
And we are still facing the same issue on Linphone Android , Linphone Ios seems to be working great.

Please look into the issue , i gues there will be any workaround to fix the issue . 
Waiting 
Thank You
Adnan

**Comment by Viish** [comment]
It is actually quite simple:

- You register on sip.telesonique.ch domain
- 401 asks for auth with realm "185.185.32.60"
- Linphone doesn't find any auth info for this realm ()

Check your linphonerc to see what is wrong in the auth info.
