### ISSUE TITLE
AVPF parameter

### ISSUE THREAD

**Issue by nzkar** [BelledonneCommunications/linphone-android#1022]
Hi, regarding https://wiki.linphone.org/xwiki/wiki/public/view/Linphone/Good%20practices%20for%20using%20SIP/, I enable AVPF for both of my devices. However they cannot call each other (audio call) and it gives an bad extension error. transport type is udp and media encryption is set to none. Codecs are appropriate.

Logs:
https://www.linphone.org:444//tmp/5ec782806f63d_a48c401fedd8280d9da5.gz

**Comment by Viish** [comment]
Hi,
Your call is to `sip:+90305001@90.158.24.66`. Is that expected? If not, I believe in your proxy configuration setting there is a prefix filed (like 90) which makes Linphone add it whenever you call a number. And I guess that's what causing the "Bad Extension" issue (that is issued by your server).

**Comment by nzkar** [comment]
Sorry I forgot the prefix in that log. But the problem is not about it. I just generated new logs with the same scenario. 

https://www.linphone.org:444//tmp/5ece0c5be039c_785a79670795cf503880.gz

Thank you.

**Comment by Viish** [comment]
I don't know which SIP server you are using (UserAgent KAREL-Sip-Spc v. CSK (IPG1000 xin64_csb_6)  t121 d0) but the issue probably lies in it's configuration as the error code is generated by it and there is nothing wrong in your INVITE.

**Comment by nzkar** [comment]
Thank you I will contact with the service provider. Also, I have a question. Are there any drawbacks of enabling AVPF parameter always to your knowledge? (in order to improve video calls performance)
