### ISSUE TITLE
Can't answer call after call transfer on kotlin_rewrite branch

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1025]
If I receive a call, answer it, then transfer it, a subsequent call to Linphone doesn't bring up the answer/reject screen but simply starts linphone ringing without bringing up the answer/reject screen. 
 If I change the ringing linphone to the touch-tone pad I can see it has changed the phone button on the bottom right to phone-with-a-plus-sign.

I can answer if I use the notification that an incoming call posts but of course that is an ugly work-around.

Linphone will continue to behave this way until I quit it and receive another incoming call.

**Comment by Viish** [comment]
Actually this is out of my hands.

Linphone relies (because we have to since Android 10) on pending intent feature for displaying incoming call screen (this is also used in previous releases).
We create an incoming call notification with a pending intent for the CallIncomingActivity. It's up to Android to device whether the device is "currently used" or not and if displaying the activity will disturb the user. When it detects the device as "not being used", it will start the activity.

For example on my device it almost never shows up unless screen is locked.

**Comment by Viish** [comment]
PS: https://developer.android.com/guide/components/activities/background-starts

**Comment by brianjmurrell** [comment]
Something doesn't seem to square here.

Why does this behaviour only exhibit itself after a call is transferred in Linphone?  The incoming call screen always displays correctly on incoming calls only except after Linphone was previously used to transfer a call.  That seems to indicate to me that Linphone is doing something when transferring the call that is interfering with future incoming calls from displaying the incoming call screen.

This doesn't seem like something Android should be causing.  It seems like something in the left-over state of transferring a call prevents the incoming call screen from coming up.  If I restart Linphone the problem goes away again.

This same issue does not exist on master.

**Comment by brianjmurrell** [comment]
> It's up to Android to device whether the device is "currently used" or not and if displaying the activity will disturb the user. When it detects the device as "not being used", it will start the activity.

But surely Android must understand that there are activities that should (almost?) always disturb the user, like an incoming phone call.  Surely the native dialer, for example, always pops up an incoming call screen when a call is coming in, (almost?) no matter what the user is doing, yes?

**Comment by Viish** [comment]
The transfer process does nothing that could change something linked to that (from my point of vue). Can you attach your logs?

> But surely Android must understand that there are activities that should (almost?) always disturb the user, like an incoming phone call. Surely the native dialer, for example, always pops up an incoming call screen when a call is coming in, (almost?) no matter what the user is doing, yes?

No. On my device for example, if I'm using it then I only get a heads up notification from the native phone app when I receive a GSM call.

**Comment by brianjmurrell** [comment]
[Log](http://brian.interlinx.bc.ca/linphone-no-incoming-call-screen-after-xfer.txt)

There are a couple of calls in there, at least one after doing a transfer where the incoming call screen did not light up.

No matter what I do I am unable to reproduce this on master.  Every single time a call comes in the incoming call screen lights up, after many transfers, etc.

> No. On my device for example, if I'm using it then I only get a heads up notification from the native phone app when I receive a GSM call.

Interesting.  I wonder if and how much backlash there is going to be on that.  I think people are very used to having an incoming call screen come up when they receive a call rather than having to fumble with (relatively) tiny notifications while panicking to answer the call (a) before the other party hangs up and (b) before they are admonished by those around them for allowing their phone to ring on and on while they fumble to answer it.

**Comment by Viish** [comment]
Can you try with
```
commit b4f3697550c730e74fb2b81a71e700944ed91daa (HEAD -> feature/kotlin_rewrite, origin/feature/kotlin_rewrite)
Author: Sylvain Berfini <sylvain.berfini@belledonne-communications.com>
Date:   Tue May 26 20:50:14 2020 +0200

    Trying to prevent or understand issues with incoming call activity
```
