### ISSUE TITLE
Video display 

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1026]
Hi，

Connect the linphone to the rk3288 platform. If I use the USB type camera, there is no problem with the video display during the call, but if I use the Mipi (non USB camera), there is no video display during the call, and there is a video display during the call of the public linphone. I don't know where there is a problem during the docking, or whether there is a special setting for this non USB type camera.

thanks.

**Comment by fengqz627** [comment]
[callout-novideo.txt](https://github.com/BelledonneCommunications/linphone-android/files/4681945/callout-novideo.txt)

**Comment by Viish** [comment]
Hi,
As always please attach logs from the library showing the issue.

**Comment by fengqz627** [comment]
The log of the caller has been attached. Can't this one

**Comment by fengqz627** [comment]
My public version of linphone can display video in callee, and then I copy liblinphone-sdk-debug.aar it can be used in the project, the callee can't display the video during the call , and the sound is normal，so I think the problem lies in the upper level docking. How to troubleshoot? Can you provide a step-by-step investigation method。
thanks.

**Comment by Viish** [comment]
From your logs you are using the legacy capture & display filters (AndroidVideoCapture / SurfaceView).
That could explain why you don't reproduce with our app which uses the new ones (Camera2 / TextureView). I strongly recommend you to switch to the new ones. Check our app or sample to see how to do it.

**Comment by fengqz627** [comment]
Now about 80% of the docking of rk3288 has been completed. It's not easy to switch to the latest one for the time being. After the docking, the next stage will switch to the new version of linphone

**Comment by fengqz627** [comment]
This should not be the problem that the called party shows？

**Comment by Viish** [comment]
If you want proper support, please contact our company for commercial contract. I can't help much on github without having your project specs.
