### ISSUE TITLE
No feedback on keypad press/DTMF

### ISSUE THREAD

**Issue by mvorisek** [BelledonneCommunications/linphone-android#1027]
Currently, the keyboard has no feedback like Zoiper app has.

This is a feature request to vibrate an keypad keypress to provide better feedback.

**Comment by Viish** [comment]
Indeed there is no vibration but you should hear the DTMF sound (unless you are in silent mode).

**Comment by mvorisek** [comment]
> unless you are in silent mode

It seems like a bug as silent mode should have no affect at least on DTMF presses during call. Vibrations seems to be best at both cases (for dialing keypad as well as during call/DTMF)

**Comment by Viish** [comment]
> It seems like a bug as silent mode should have no affect at least on DTMF presses during call. 

Actually it should. Check your native dialer app, it does the same. There is even a setting for that: https://developer.android.com/reference/android/provider/Settings.System#DTMF_TONE_WHEN_DIALING

**Comment by mvorisek** [comment]
> Settings.System#DTMF_TONE_WHEN_DIALING

good point, it works if enabled, for some reasons it is not silent even is the phone is set to only vibrate

if the dialpad tones are disabled, there is currently no feeedback, which is quite needed for DTMF as currently there is not DTMF history bar

So I propose:
- to vibrate if tones are not enabled
- to add DTMF presses history bar above the keypad

**Comment by Viish** [comment]
First of all, I made a lot of changes in branch feature/kotlin_rewrite that will become the next master and then release.
DTMF are generated at two places: the dialer and in the call view.

- On the dialer, DTMFs aren't played if the above setting is disabled or if there is an ongoing call. You will have feedback anyway as the digit is added to the address input field above.
- While in call, the DTMF sound will always be played, so you will also have your feedback. We haven't planned to add a history on this view, but I will submit the idea for the next design update.

Anyway it doesn't prevent to also add a vibration effect to the DTMF keys, so I will keep the issue opened with the enhancement flag.

**Comment by Viish** [comment]
commit 1d4ee533dedd9c3c1cb213346d9452fd657de5ae (HEAD -> feature/kotlin_rewrite, origin/feature/kotlin_rewrite)
Author: Sylvain Berfini <sylvain.berfini@belledonne-communications.com>
Date:   Thu Oct 15 13:57:07 2020 +0200
    Added setting to have a small vibration when pressing keypad numbers
