### ISSUE TITLE
Incoming call screen doesn't progress to in-call screen

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1028]
On the kotlin_rewrite branch, it seems there can be a case when an incoming call is received while the phone is idle/locked activates the incoming-call screen where one can swipe to answer or reject.

I swipe green to answer but that incoming call screen doesn't progress to the in-call screen, where I can choose the dialpad to enter numbers, etc.  I am stuck on that incoming call screen and cannot enter keys, etc.  I also cannot transfer the call, or hang it up without using the notification.

[Log](http://brian.interlinx.bc.ca/linphone-doesnt-progress-after-incoming-call-accepted.txt)

**Comment by Viish** [comment]
I've also seen this issue once today.
I've just pushed a commit trying to prevent that or help understand it if someone reproduces it:
```
commit b4f3697550c730e74fb2b81a71e700944ed91daa (HEAD -> feature/kotlin_rewrite, origin/feature/kotlin_rewrite)
Author: Sylvain Berfini <sylvain.berfini@belledonne-communications.com>
Date:   Tue May 26 20:50:14 2020 +0200

    Trying to prevent or understand issues with incoming call activity
```

**Comment by Viish** [comment]
I close this issue for now, tell me if it happens again.
