### ISSUE TITLE
Unresolved reference: updateParams

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1029]
Looks like bdb1722e4837937f99a352a64f66a77701832891 introduced an unresolved reference:

```
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (189, 29): Unresolved reference: updateParams
```

**Comment by Viish** [comment]
You need to update your SDK to a newer version.

**Comment by brianjmurrell** [comment]
Is this kind of new API requirement not something that the build process can detect and/or update automatically?

Is there any less of the `rm -rf ~/.gradle/caches` _sledgehammer_ for updating just the SDK?

**Comment by Viish** [comment]
You can do a gradle sync also.

**Comment by brianjmurrell** [comment]
Alright, I just wiped `~/.gradle/caches` but now am getting:

```
> Task :app:installDebug
Installing APK 'linphone-android-debug-4.3-alpha.100+51b6ea0d9.apk' on 'FRD-L04 - 8.0.0' for app:debug
Installing APK 'linphone-android-debug-4.3-alpha.100+51b6ea0d9.apk' on 'Nexus 5 - 9' for app:debug
Unable to install /home/brian/linphone-android/app/build/outputs/apk/debug/linphone-android-debug-4.3-alpha.100+51b6ea0d9.apk
com.android.ddmlib.InstallException: INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113
```

**Comment by Viish** [comment]
Do a real clean, it should fix it.

**Comment by brianjmurrell** [comment]
I did try a `./gradlew clean` before posting above.

**Comment by Viish** [comment]
Why don't you use Android Studio?

**Comment by brianjmurrell** [comment]
Because the machine I build on is a headless server.

**Comment by brianjmurrell** [comment]
No more ideas here?

I've wiped `~/.gradle/caches` and I have run `./gradlew clean`.

What else can I possibly do?

What does the error actually mean/indicate?

> Why don't you use Android Studio?

How would that help?

**Comment by Viish** [comment]
What is the CPU architecture of your device?

**Comment by brianjmurrell** [comment]
arm

**Comment by Viish** [comment]
That's why. For some reason the latest alpha AAR built by our CI system only has arm64 architecture.
I've started a new pipeline, will be fixed soon.

**Comment by Viish** [comment]
Done. You can use 4.4.0-alpha.256+a7d2c8a

**Comment by brianjmurrell** [comment]
Is there some _lag_ in that being available to gradle?  I just wiped `~/.gradle/caches` did a rebuild and got `4.4.0-alpha.255+b00e9d9`.

**Comment by Viish** [comment]
Simply set the full value in the implementation line of the build.gradle to make it download the right version then you can revert the change.
