### ISSUE TITLE
Average call quality after call ending

### ISSUE THREAD

**Issue by zhuchinskyi** [BelledonneCommunications/linphone-android#103]
Hi,

Seems like it's not possible now to get average call quality when a call is terminated by another subscriber.

When the user terminates a call from caller side, call termination initiated by app side and it's possible to get a valid LinphoneCall object with average call quality, but when the call terminates by another subscriber, I cannot get the valid LinphoneCall object and average call quality returns -1 as call object is released.

Is it possible to implement new state before call end, when the current call would be aware of average quality?

**Comment by Thucnv** [comment]
The same to me.

**Comment by astuter** [comment]
Any update on this as its been a year since reported?
