### ISSUE TITLE
No incoming call screen or notification on incoming call

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1030]
On the kotlin_rewrite branch, I received an incoming call last night that neither displayed the incoming call screen nor did it even post a notification that I could answer with.  My phone just rang with the Linphone ringtone with no way to answer it.

[Log](http://brian.interlinx.bc.ca/linphone-no-incoming-call-screen-or-notification.txt)

**Comment by Viish** [comment]
Do you reproduce it?

**Comment by brianjmurrell** [comment]
Not at the moment.  Only had it happen the one time last night, so far.

**Comment by uniruddh** [comment]
Hi @Viish ,

If we set "enable_call_notification" to false Income call screen isn't showing up no matter if app is in background or foreground. Also, If we enable call notification along with that app is showing call-id in notification bar as soon as it receives incoming call, as shown in following image.

![7ae7f3f2-ab00-4201-808f-61cd0bcc266c](https://user-images.githubusercontent.com/12004314/83022333-ffec7f00-a048-11ea-8ede-e7feb25a96e3.jpeg)

**Comment by brianjmurrell** [comment]
This just happened again.  There's nothing in particular to reproduce it.  It seems that intermittently, some calls just don't trigger either the incoming call screen or even a notification.

**Comment by brianjmurrell** [comment]
And just happened again.  And again.  My phone is currently in a state where this happens with every incoming call.

**Comment by Viish** [comment]
This would mean your device can't handle full screen intents in foreground service notifications... :sob: 
Do you also the issue with your Nexus device?

**Comment by brianjmurrell** [comment]
Yes, Nexus 5 with LineageOS (Pie) also has the same problem.  Both are also not lighting up the screen on the incoming call, but I suppose that is just another symptom of the same problem.

**Comment by brianjmurrell** [comment]
This one is pretty debilitating.  It renders Linphone useless for incoming calls.  Is there a specific commit or commits that I should revert to restore the incoming-call screen and/or notifications?

**Comment by Viish** [comment]
Try with
```
commit 0fa49191b0284ed8994cba1f4afc549972a81385 (HEAD -> feature/kotlin_rewrite, origin/feature/kotlin_rewrite)
Author: Sylvain Berfini <sylvain.berfini@belledonne-communications.com>
Date:   Wed May 27 20:39:40 2020 +0200

    Revert a change from commit b4f3697550c730e74fb2b81a71e700944ed91daa
```

**Comment by brianjmurrell** [comment]
That does seem to have resolved this issue.  I seem to be getting either an incoming-call screen or a notification I can answer.  Much thanks!

**Comment by brianjmurrell** [comment]
There are other artefacts though.  Frequently on my Nexus 5, I have to unlock the screen before I can answer an incoming call.  I think it happens when the phone is in "Daydream" mode, where the screen stays awake with a "floating clock" if the phone goes unused while charging.

Daydream mode does seem to be the reproducer.

**Comment by Viish** [comment]
Indeed, I do reproduce it sometimes.
But it seems expected sometimes according to the documentation:
```
/**
     * If the device is currently locked (see {@link #isKeyguardLocked()}, requests the Keyguard to
     * be dismissed.
     * <p>
     * If the Keyguard is not secure or the device is currently in a trusted state, calling this
     * method will immediately dismiss the Keyguard without any user interaction.
     * <p>
     * If the Keyguard is secure and the device is not in a trusted state, this will bring up the
     * UI so the user can enter their credentials.
     * <p>
     * If the value set for the {@link Activity} attr {@link android.R.attr#turnScreenOn} is true,
     * the screen will turn on when the keyguard is dismissed.
     *
     * @param activity The activity requesting the dismissal. The activity must be either visible
     *                 by using {@link LayoutParams#FLAG_SHOW_WHEN_LOCKED} or must be in a state in
     *                 which it would be visible if Keyguard would not be hiding it. If that's not
     *                 the case, the request will fail immediately and
     *                 {@link KeyguardDismissCallback#onDismissError} will be invoked.
     * @param callback The callback to be called if the request to dismiss Keyguard was successful
     *                 or {@code null} if the caller isn't interested in knowing the result. The
     *                 callback will not be invoked if the activity was destroyed before the
     *                 callback was received.
     */
```

**Comment by gitterspec** [comment]
I'm experiencing this intermittently as well with 4.3.1. Very frustrating to hear the ringing and not be able to pick up or stop it. Is there a workaround?
