### ISSUE TITLE
Where are accounts created via AccountCreator interface stored?

### ISSUE THREAD

**Issue by GeorgeMina** [BelledonneCommunications/linphone-android#1032]
I'm trying to create an account using the code below:

    accountCreator.setUsername(jsonObjSend.getString("phone"));
    accountCreator.setPhoneNumber(jsonObjSend.getString("phone"), "");
    accountCreator.setEmail(jsonObjSend.getString("email"));
    accountCreator.setDomain("myServerIP");
    accountCreator.setPassword(randomStringGenerator());
    accountCreator.createAccount();

I can then register and make calls with the new account, however, I don't see it stored in my server's users.db.txt file. I assume that the account is stored in one of Belledone's servers by default? How can I change this?

**Comment by Viish** [comment]
Hi,
Account creator can be used to create account, but for that it needs the URL of a xmlrpc server that will do the account creation on the server side.
If there isn't, a local account will be created (but won't be useful as the server won't allow it to register), but that doesn't prevent you from doing peer to peer calls.
Here's our server side: https://gitlab.linphone.org/BC/public/flexisip-account-manager
