### ISSUE TITLE
RemoteProvisioningUrl Result

### ISSUE THREAD

**Issue by cradle1001** [BelledonneCommunications/linphone-android#1033]
Is it possible to get result RemoteProvisioningUrl? How can?
Because I can't find RemoteProvisioningUrl in the master.
`

**Comment by Viish** [comment]
I don't understand your question

**Comment by cradle1001** [comment]
I want to get result when send request to RemoteProvisioningUrl.

**Comment by Viish** [comment]
The remote provisioning isn't a request.
When the Core is configured which such URL, it simply downloads it (you can't have access to what is downloaded), it applies the required changes and finish starting.
