### ISSUE TITLE
Can't get preview frame

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1035]
Hi,

In AndroidVideoApi9JniWrapper.java，Sometimes it can't enter the following process. How do I need to set up to enter the process?

public static Object startRecording(){
.....
	camera.setPreviewCallbackWithBuffer(new Camera.PreviewCallback() {	
			public void onPreviewFrame(byte[] data, Camera camera) {
//can't enter here...
.....
}

**Comment by fengqz627** [comment]
Is it possible that other apps are using the camera

**Comment by Viish** [comment]
Check your logs and open a ticket on linphone-sdk project instead.

**Comment by fengqz627** [comment]
Thanks, how to judge whether the camera is occupied?

**Comment by Viish** [comment]
Using adb logcat you should see errors saying that camera is unavailable.

**Comment by fengqz627** [comment]
Very strange, startRecording in AndroidVideoApi9JniWrapper.java, there is "Camera camera = Camera.open(cameraId);"  I get log:   camera= android.hardware.Camera@faa3833 ，  It looks like the camera can be turned on and not occupied

**Comment by Viish** [comment]
Once again it is almost certain this issue has been fixed it a more recent version of the SDK that the one you uses.

**Comment by fengqz627** [comment]
thanks. It's too late to change the latest SDK. I have to wait for the next stage to update the SDK,
This version of SDK I use supports display, but I copy  .aar  to my project and it can't be displayed. I don't know what caused it， and I don't know what this has to do with
