### ISSUE TITLE
contact server

### ISSUE THREAD

**Issue by luiz-telles** [BelledonneCommunications/linphone-android#1036]
Is it possible to add a contact server for the Linphone account and activate synchronization?

**Comment by Viish** [comment]
Can you be more specific? I don't understand your question.

**Comment by luiz-telles** [comment]
Vish, 
I would like if the linphone could sync contacts from a local server.
Yahoo example:

https://help.yahoo.com/kb/sync-yahoo-contacts-mobile-devices-sln22041.html

**Comment by Viish** [comment]
Our SDK supports CardDAV protocol on top of vCard4.
You can find a wiki page about it there: https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Vcard4%20contacts/
