### ISSUE TITLE
Issue of Green Screen during Video Call

### ISSUE THREAD

**Issue by iamsoze** [BelledonneCommunications/linphone-android#1037]
Hello All,

I am using linphone-4.2.3 (debug) and and Linphonen SDK 4.3.4-pre.36+6aa0627.
The problem I am facing during video call is I am getting green screen during video call on my mobile and custom board (TI AM5728 EVM). I have tried following scenarios -

A) Call from one board to another using either of two (VP8 or H264) codec - Local preveiw opens successfully but green screen received in video on both the boards

B) Call from mobile phone to board, mobile's preview seen on the board with both codec's (VP8 or H264) but green screen received on mobile phone (with VP8) and black screen/no video received with H264.

I am attaching logs for all of the above scenarios. Also attached is the image that with green screen during video call.

[call_between_boards_H264.txt](https://github.com/BelledonneCommunications/linphone-android/files/4716614/call_between_boards_H264.txt)

[call_between_boards_VP8.txt](https://github.com/BelledonneCommunications/linphone-android/files/4716617/call_between_boards_VP8.txt)

[call_between_mobile_and_board_H264.txt](https://github.com/BelledonneCommunications/linphone-android/files/4716618/call_between_mobile_and_board_H264.txt)

[call_between_mobile_and_board_VP8.txt](https://github.com/BelledonneCommunications/linphone-android/files/4716619/call_between_mobile_and_board_VP8.txt)

![Green_Screen_Video_Call](https://user-images.githubusercontent.com/66254213/83511994-239e4200-a4ed-11ea-91d6-f4d242fb27af.jpeg)

Please suggest what can be done.
@Viish

**Comment by Viish** [comment]
If both codecs have the issue, it would indicate an camera capture issue.
Preview is fine which means your tablets have a custom version of Android that does something specific to the camera output in order to display properly, and obviously we don't.
Without the hardware we won't be able to solve this.
If you need this fixed, consider contracting from our company a dev-assist contract and send us the device.

**Comment by iamsoze** [comment]
Hi,

Thanks for responding. 
I don't think there is an issue with the hardware.
I think there is some issue with the ImageFormat that linphone is expecting.
**The only reason** I'm saying this is the video call works fine with Zoiper VoIP Softphone. The video preview is opened successfully and received as well on both the ends. I have tested this with VP8 codec.

Please suggest.

**Comment by Viish** [comment]
Indeed that can be a possibility.
Our legacy filter expects YCbCr biplanar images from the camera which in your case may be not the case. I would recommend you to use the new capture filter (MsAndroidCamera2) but your hardware isn't compatible...
So once again I recommend you to contact us for a contract and send us your device so we can check what image format the camera captures.

**Comment by iamsoze** [comment]
Hi,

I can tell you about the image format that is used by camera for capturing.
The format is "YUV420SP" - NV21. I have checked this with help of
params.getSupportedPreviewFormats() in AndroidVideoApi9JniWrapper.java. It returns value 17.

Are you implying that NV21 format is not supported by Linphone? If not, then how is it the case that local preview gets opened successfully during video call?

Also, how are you sure that MsAndroidCamera2 capture filter is not compatible by our hardware?
Please suggest.
@Viish

**Comment by Viish** [comment]
> Also, how are you sure that MsAndroidCamera2 capture filter is not compatible by our hardware?

Yes. In the logs you provided, the MsAndroidCamera2 plugin loads but fails to detect any camera.

> Are you implying that NV21 format is not supported by Linphone? If not, then how is it the case that local preview gets opened successfully during video call?

Camera preview is handled directly by Android framework, so obviously it can display it.
Regarding the format, yes and no. We do handle images in YUV format in mediastreamer, however in this case we expect the image to be in YCbCr biplanar format and thus convert the image (in mediastreamer2 project, androidvideo.cpp file, Java_org_linphone_mediastream_video_capture_AndroidVideoApi5JniWrapper_putImage method). Since you build your own SDK, you can make the changes you want in there.

**Comment by iamsoze** [comment]
I get that YCbCr colorspace is supported by linphone.

> Regarding the format, yes and no. 
Since you said that NV21 format is not supported, can you please tell me what other Image Formats (like NV12, I420, YV12 etc.) are supported by linphone? 

I am thinking of converting the `data` received in `onPreviewFrame` function in AndroidVideoApi9JniWrapper.java to the desired Image Format supported by linphone before passing it to the `Java_org_linphone_mediastream_video_capture_AndroidVideoApi5JniWrapper_putImage method`.

**Comment by Viish** [comment]
> I am thinking of converting the data received in onPreviewFrame function in AndroidVideoApi9JniWrapper.java to the desired Image Format supported by linphone before passing it to the Java_org_linphone_mediastream_video_capture_AndroidVideoApi5JniWrapper_putImage method.

You can't do that. `Java_org_linphone_mediastream_video_capture_AndroidVideoApi5JniWrapper_putImage` method will always try to convert the image it receives. You must make the change in it and not before. In mediastreamer all images must be YUV420P (3 planes).

**Comment by iamsoze** [comment]
This means that `Java_org_linphone_mediastream_video_capture_AndroidVideoApi5JniWrapper_putImage` function tries to convert NV21 image format it receives from my camera to YCbCr biplanar format. And seems that it couldn't do that as I get green screen.

> You can't do that. `Java_org_linphone_mediastream_video_capture_AndroidVideoApi5JniWrapper_putImage` method will always try to convert the image it receives. You must make the change in it and not before. In mediastreamer all images must be YUV420P (3 planes).


Okay, I'll convert the Image into desired format inside _putImage function. But can you tell me which specific format should I convert the image to?

**Comment by Viish** [comment]
You need to convert whatever image format your camera sends to YUV420P.

**Comment by iamsoze** [comment]
Camera in android opens preview with default NV21 Image Format (which belongs to YUV420SP). YUV420SP is the default format included in my Camera HAL. If I change the default format to YUV420P, the preview never opens. 

> You need to convert whatever image format your camera sends to YUV420P.

According to this, I need to convert YUV420SP to YUV420P. And YUV420P includes I420 & YV12, so do I need to convert my NV21 format to either of these two? Will this work?

**Comment by iamsoze** [comment]
Can you comment about the conversion? @Viish

**Comment by Viish** [comment]
The difference between I420 and YV12 is which comes right after Y : U or V.
We expect the order to YUV (so I420 format).
If you use our copy_ycbcrbiplanar_to_true_yuv_with_rotation method, it has a parameter to tell it whether U is first or second.
You can also (and probably should) use our copy_yuv_with_rotation method (see msvideo.c for all available helper methods).
