### ISSUE TITLE
Video display problems

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1038]
Hi，

In the caller, for USB camera, you don't need to add the following code, but for Mipi camera, you need to add this code, so the callee  can display video. Why?
--------------------------------
mVideoView = (SurfaceView) view.findViewById(R.id.videoSurface);
		mCaptureView = (SurfaceView) view.findViewById(R.id.videoCaptureSurface);
		mCaptureView.getHolder().setType(SurfaceHolder.SURFACE_TYPE_PUSH_BUFFERS); 
		fixZOrder(mVideoView, mCaptureView);

		androidVideoWindowImpl = new AndroidVideoWindowImpl(mVideoView, mCaptureView, new AndroidVideoWindowImpl.VideoWindowListener() {
			public void onVideoRenderingSurfaceReady(AndroidVideoWindowImpl vw, SurfaceView surface) {
				mVideoView = surface;
				LinphoneManager.getLc().setNativeVideoWindowId(vw);
			}

			public void onVideoRenderingSurfaceDestroyed(AndroidVideoWindowImpl vw) {

			}

			public void onVideoPreviewSurfaceReady(AndroidVideoWindowImpl vw, SurfaceView surface) {
				mCaptureView = surface;
				LinphoneManager.getLc().setNativePreviewWindowId(mCaptureView);
				resizePreview();
			}

			public void onVideoPreviewSurfaceDestroyed(AndroidVideoWindowImpl vw) {

			}
		});

**Comment by fengqz627** [comment]
For USB camera, caller does't need add above code, but callee needs  add it , but for MIPI camera, this code needs to be added on both sides, I don't know why,

**Comment by Viish** [comment]
Android prevents capturing video from built-in cameras without it being displayed to the user (to prevent malwares from filming you without you knowing). I thought this applied to USB cameras as well but seems not.
