### ISSUE TITLE
Issue in integrating locally built linphone sdk

### ISSUE THREAD

**Issue by iamsoze** [BelledonneCommunications/linphone-android#1039]
Hello All,

I have downloaded and successfully compiled linphone-sdk using https://gitlab.linphone.org/BC/public/linphone-sdk.git.

I have imported the AARs generated (Release & Debug) from linphone-sdk to linphone-android project which I downloaded from https://github.com/BelledonneCommunications/linphone-android.git. 

I commented the following line in build.gradle (:app) -
  implementation "org.linphone:linphone-sdk-android:4.4+"

and added the AARs under dependencies
  implementation project(':linphone-sdk-android-debug')
  implementation project(':linphone-sdk-android-release')

I also added LinphoneSdkBuildDir=/home/MY_USERNAME/linphone-sdk/build path to gradle.properties.
However, I am getting errors related to some classes on building the project. The project is not a able to find classes such as PlayerListener, CoreStubListener etc. which are not present in linphone-sdk.

Is there some code in the latest AAR (org.linphone:linphone-sdk-android:4.4+) which is missing in the AAR which gets generated on compiling linphone-sdk? I want to use locally built sdk for native debugging.

Please suggest how to proceed. 

![Ss](https://user-images.githubusercontent.com/66254213/83630133-f28b4380-a5b8-11ea-9506-d2243012515d.png)

**Comment by Viish** [comment]
Hi,
It seems you haven't correctly built the SDK.
Either you didn't specified the `-DLINPHONESDK_PLATFORM=Android` option to cmake or you disabled the JAVA wrapper (`-DENABLE_JAVA_WRAPPER=ON` to enable it back).
From now on I recommend you to stick to LinphoneSdkBuildDir method instead of copy/pasting AARs, that will prevent some mistakes.
Cheers,

**Comment by iamsoze** [comment]
Hi,
I specified the LINPHONESDK_PLATFORM=Android from cmake-gui earlier.
Anyways, I did this time from command line as well. And I did not import any AARs into the project. 
I just commented the **implementation "org.linphone:linphone-sdk-android:4.4+"** from buidl.gradle (:app) and added the LinphoneSdkBuildDir path to gradle.properties of linphone-android project.

However, I am still getting the same errors. Unable to build the project.
Please help.

**Comment by Viish** [comment]
If you are using the LinphoneSdkBuildDir method, remove the 
```
implementation project(':linphone-sdk-android-debug')
implementation project(':linphone-sdk-android-release')
```
that you added and keep the `implementation "org.linphone:linphone-sdk-android:4.4+"` otherwise it won't work.

**Comment by iamsoze** [comment]
I commented the  ### implementation "org.linphone:linphone-sdk-android:4.4+" in build.gradle (:app) to make sure that the project is using libraries from locally compiled Linphone-SDK. If I undo the comment, it downloads the AAR from online repository and it doesn't use libraries from locally built SDK.

For instance, I kept the implementation ### "org.linphone:linphone-sdk-android:4.4+" and added a debug print in ### belle-sip/src/wakelock.c to check whether locally built SDK was being used. The project got built successfully but on running the app **I wasn't able to see my debug print.**

**Comment by Viish** [comment]
No, you still need the `implementation "org.linphone:linphone-sdk-android:4.4+"` even for using a locally built SDK.
If you want to be sure to use your local maven repository (the one pointed by LinphoneSdkBuildDir), comment out the `maven { url "https://linphone.org/maven_repository" }` and keep `maven { url file(LinphoneSdkBuildDir + '/maven_repository/') }`

**Comment by iamsoze** [comment]
I commented out the maven `{ url "https://linphone.org/maven_repository" }` from build.gradle (:app), now I am getting the same set of error I posted originally at the start of this issue during build. 

**https://github.com/BelledonneCommunications/linphone-android/issues/1039#issue-629908323**

I'm guessing that local maven repository doesn't contain these classes/interfaces missing in the project.

As I pointed out that the linphone-android project has some extra code (classes/interfaces) which are not present in the locally compiled linphone-sdk. I am hoping that you point me to the updated linphone-sdk repository that is compatible with latest linphone-android, in order to resolve these errors related to missing classes and interfaces.

**Comment by Viish** [comment]
That means that either the SDK is not built or the path you set in LinphoneSdkBuildDir isn't correct.

**Comment by iamsoze** [comment]
I have built the SDK. And I have set the path as -
`LinphoneSdkBuildDir=/home/username/linphone-sdk/build`
The build directory contains a maven_repository folder from where it loads the locally built aars.


Taking one of the errors - ```
error: cannot find symbol import org.linphone.core.PlayerListener;
                                                                                 ^
```
The class PlayerListener.java is present in `$LinphoneSdkBuildDir/WORK/android-armv7/Build/linphone/wrappers/java/java/org/linphone/core/PlayerListener.java` and it is not being found in linphone-android project. 

Please suggest the path to be set for LinphoneSdkBuildDir.

**Comment by Viish** [comment]
What contains your /home/username/linphone-sdk/build/maven_repository directory?

Also, the PlayerListener.java file should also exists in `$LinphoneSdkBuildDir/linphone-sdk/android-arm64/share/linphonej/java/org/linphone/core/PlayerListener.java`

**Comment by iamsoze** [comment]
Following is the structure of `/home/username/linphone-sdk/build/maven_repository` -
`
org--linphone--linphone-sdk-android -- 4.4.0-alpha.267+2e3df82
                   |-- linphone-sdk-android-debug -- 4.4.0-alpha.267+2e3df82
`
The `4.4.0-alpha.267+2e3df82` contains .aar, .jar and .pom files and their md5 and sha1 sum.

YES, I forgot to mention the PlayerListener.java file also exists in `$LinphoneSdkBuildDir/linphone-sdk/android-arm64/share/linphonej/java/org/linphone/core/PlayerListener.java`

**Comment by Viish** [comment]
Then I don't understand what is going wrong.
In Android studio, change the project view from Android to Project and check under External Libraries that you see org.linphone.linphone-sdk-android...@aar

**Comment by iamsoze** [comment]
Yes, I see org.linphone:linphone-sdk-android:4.4.0-alpha.267+2e3df82@aar under External Libraries,
But it doesn't contain Player.java file or other classes/interfaces that are shown missing in the error.

**Comment by Viish** [comment]
Please delete your build directory and start again from scratch. Then if you still have the issue please send the full logs of your build steps.

**Comment by iamsoze** [comment]
Deleted the build directory. Followed these steps -

> git clone https://gitlab.linphone.org/BC/public/linphone-sdk.git --recursive

> cd linphone-sdk

>  cmake -DLINPHONESDK_PLATFORM=Android -DENABLE_JAVA_WRAPPER=ON .

> make -j8

> Added `LinphoneSdkBuildDir=/home/username/linphone-sdk/`

> Commented `{ url "https://linphone.org/maven_repository" }` in build.gradle (:app)

> Changed `minSdkVersion 21` in build.gradle (:app) to `minSdkVersion 23` 

> Built the project. Got the same set of errors.

Fin.

**Comment by Viish** [comment]
Actually you should do this:
- git clone https://gitlab.linphone.org/BC/public/linphone-sdk.git --recursive
- cd linphone-sdk
- mkdir build
- cd build
- cmake .. -DLINPHONESDK_PLATFORM=Android
- make -j8
If it still doesn't work copy/paste your terminal output for the cmake & make commands.

**Comment by iamsoze** [comment]
Yes, just checked it now. It's working fine. I am getting my debug print from SDK as well.
I'm guessing it was because of `-DENABLE_JAVA_WRAPPER=ON` option during cmake.

Thanks.

**Comment by theodoromatheus1830** [comment]
@Viish Hi, i am also having some problems with my sdk... But i am not sure what i am doing wrong.
i followed this steps
git clone https://gitlab.linphone.org/BC/public/linphone-sdk.git --recursive
cd linphone-sdk
mkdir build
cd build

but when i try to run cmake .. -DLINPHONESDK_PLATFORM=Android, i get this error:

C:\Users\Public\linphone-sdk\build> cmake .. -DLINPHONESDK_PLATFORM=Android
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18362.
CMake Error at CMakeLists.txt:33 (include):
  include could not find load file:

    bctoolbox/cmake/BcToolboxCMakeUtils.cmake


CMake Error at CMakeLists.txt:35 (bc_compute_full_version):
  Unknown CMake command "bc_compute_full_version".


-- Configuring incomplete, errors occurred!
See also "C:/Users/Public/linphone-sdk/build/CMakeFiles/CMakeOutput.log".

Do you know what I am doing wrong?

**Comment by theodoromatheus1830** [comment]
Hi @Viish, i am having some problems building sdk....
When I run,cmake .. -DLINPHONESDK_PLATFORM=Android, i got this error:

-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18362.
CMake Error at cmake/LinphoneSdkCheckBuildToolsAndroid.cmake:27 (message):
  You need to use a Linux or Mac OS X system to build for Android
Call Stack (most recent call first):
  CMakeLists.txt:51 (include)


-- Configuring incomplete, errors occurred!
See also "C:/Users/theod/linphone-sdk/build/CMakeFiles/CMakeOutput.log".

I really need to use Linux ou Mac to build for Android ? There s another choice ?

**Comment by Viish** [comment]
@theodoromatheus1830 No, currently you can't build our SDK for Android platform on Windows. 
However you can build it using WSL (Windows Subsystem for Linux): https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by theodoromatheus1830** [comment]
Thank you very much!!! @Viish

**Comment by theodoromatheus1830** [comment]
Hi, how are you ? I'm having other problems even at WSL, but I think there is something about the NDK. Anyway, a while ago I had managed to build the linphone application for android ... But when I went to change the package name, I started having problems when starting a call. I think that the problem is with my linphone SDK ... I really need to use a local SDK ? If i just download the linphone-android app, and build, should I be able to make calls? I'm sorry if the question was a little silly, I'm a beginner with android and linphone.

**Comment by Viish** [comment]
Yes you can use a pre-built AAR from our maven repository/

**Comment by theodoromatheus1830** [comment]
Right... I cloned "linphone-android", from this repository https://github.com/BelledonneCommunications/linphone-android.git... And i opened and built at android studio. But when i try to start a call....
![image](https://user-images.githubusercontent.com/38991529/86960497-fa00b800-c135-11ea-85f5-9f08c7642a62.png)
I don´t know what i am doing wrong.
My dependencies:
dependencies {
    compileOnly 'org.jetbrains:annotations:19.0.0'
    if (firebaseEnabled()) {
        implementation 'com.google.firebase:firebase-messaging:19.0.1'
    }
    implementation 'androidx.recyclerview:recyclerview:1.0.0'
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'com.google.android:flexbox:1.1.0'
    implementation 'com.github.bumptech.glide:glide:4.9.0'
    implementation "org.linphone:linphone-sdk-android:4.4+"
}
and repositories
repositories {
    maven {
        url file(LinphoneSdkBuildDir + '/maven_repository/')
    }
    maven {
        url "https://linphone.org/maven_repository"
    }
}

**Comment by Viish** [comment]
@theodoromatheus1830 please open a new issue and attach your logs

**Comment by theodoromatheus1830** [comment]
@Viish Yes sure, thanks for your help!

**Comment by Nuclear6** [comment]
Upgrade the ide to the latest version, modify the AGP version according to the gradle error, and then use maven to build the application normally.

The project is using an incompatible version (AGP 8.7.1) of the Android Gradle plugin. Latest supported version is AGP 8.6.0
See Android Studio & AGP compatibility options.

**Comment by Abdul99Aleem** [comment]
Can anyone help me build linphone-sdk on my windows

i get errors when i try to build 
please provide me build process in steps

i have a qt project in which i need to integrate linphone
