### ISSUE TITLE
Possibility to select an outgoing account

### ISSUE THREAD

**Issue by msva** [BelledonneCommunications/linphone-android#104]
Hi there!
It will be very useful to have a possibility to choose an account that would be used for outgoing call
// for UI idea about how to perform that, you can check out the sources/screenshots of already-dead CSipSimple.
// also there was a possibility to set the names and icons for the accounts.

**Comment by muellert** [comment]
I have several SIP accounts, and it would be great if I could select any one on a per-call basis for outgoing calls. Thanks a lot!

**Comment by Viish** [comment]
Hi, you can already select which account is used by default for chat/call operations (it's the use as default option). It's not per-call basis but we won't do that.

**Comment by muellert** [comment]
I am aware of the "default" account option, but usability is bad: Firstly, it takes a long time to operate, and secondly, it leads to a disconnect and possibly lengthy re-registering of all affected accounts.

Would you accept a PR for this feature?

**Comment by Viish** [comment]
Let's say it's not the default behavior to have multiple accounts on the same domain.
If you have 2 accounts on different domains, the one on the "right" domain will be used even if it's not the default one.

**Comment by msva** [comment]
1) yes, you can call it "uncommon", but it is still legit situation when users have multiple accounts on the same domain.

For example, I've SIP connectivity from my cell-phone operator, and I've two "numbers" from different regions (and different tariffs on different kinds of outgoing numbers on both).

Or, as another example, it can be that one of my numbers is well-known for people in one region, and another one - for people in another region. And I'd very like to call peoples from the "well-known" number, but not from "default" one.

2) you're wrong in statement `the one on the "right" domain will be used even if it's not the default one`.
For the first two examples why are you - see the "1."
And one more situation:
Say, I've accounts on different domains. Let it be `domain1.tld` and `domain2.tld`. And one of them (let it be `domain1.tld`) is default. Okay.
Now, I want to call to few numbers on **another domains**: `jenny@domain3.tld` and `sam@domain4.tld`.
... And my account on `domain1.tld` would be used for both (since it's default).

And what if I supposed to call Sam from `domain2.tld` account?

**Comment by Viish** [comment]
If you have two accounts domain1 and domain2, and domain1 is default and you want to call sam@domain2 the domain2 account will be used.
If you call sam@domain3 it will use the default domain (since it's default) and if you call sam@domain1 it will use domain1 (default or not).

The "real" issue is if you have two domain1 accounts and want to call someone with the account that is not default.

**Comment by msva** [comment]
@Viish 
1) As I see, you've just simplified what I said by dropping jenny out of example, and keeping only sam. And repeated my words. The thesis is "you can't control which account should be used for exact call, irrelevant of your needs or will".

2) So, actually, the real issue is **absence of the possibility to choose source account for outgoing call on per-account basis** itself.
All the examples you've seen here is just illustration where this possibility can be helpful.

So, what you called "real issue" is main (most harmful) vector of the problem, but the case of "I want to call sam@domain3 from non-default account" is affected by that issue too :smile:

**Comment by Viish** [comment]
@msva 
The point is this issue only happens in specific use-case scenarios which aren't currently our focus.
If you want you can fork the project and add the feature yourself, you're welcome to do so and submit us a merge request.

**Comment by AdamMiltonBarker** [comment]
> @msva The point is this issue only happens in specific use-case scenarios which aren't currently our focus. If you want you can fork the project and add the feature yourself, you're welcome to do so and submit us a merge request.

It is hardly a specific use case, if you have one provider and multiple numbers/users with them, they will be on the same domain. It is a no brainer this is a valid feature, can't believe you are actually arguing it is not.

**Comment by Viish** [comment]
Support for multiple accounts is present but has never been part of our primary concerns regarding the app, as we had a lot of other features to add.
There is an "enhancement issue" open about it here (https://github.com/BelledonneCommunications/linphone-android/issues/1218), and it will be addressed in the next major UI redesign to come.
