### ISSUE TITLE
Not able to find call in core

### ISSUE THREAD

**Issue by sushilsolanki8875** [BelledonneCommunications/linphone-android#1041]
I noticed linphone core is giving me to NULL value for call object. I tried for find call with sip uri and number but I got same result. Also I'm getting the callNb count 0. So it seems linphone core is not able create the call. If I restart the app it works fine. I am not able reproduce this everytime. I **think It happens when we get the incoming call immediate after registration**. May be core is not created properly.

Can you please help me why I am getting this issue?, I using the same code for registration that given in this app.

**Comment by Viish** [comment]
Please enable logs in advanced settings, restart the app, reproduce the issue and then upload logs using the send logs button in about page.

**Comment by Viish** [comment]
No logs provided, closing.
