### ISSUE TITLE
Linphone-Android 4.3.0 InApp Purchase 

### ISSUE THREAD

**Issue by Adnan-addi** [BelledonneCommunications/linphone-android#1043]
Hi @Viish 
i hope you can guide me on this once again , 
i want to enable and configure inapp purchase for linphone android 
i am following this 
https://wiki.linphone.org/xwiki/wiki/public/view/Linphone/Using%20the%20In-App%20purchase%20service/

but this seems to be outdated , i followed the steps but unable to get google client secret now , somehow google does not provide it now.

can you tell what is latest method to enable inapp purchase , i already created product and merchant in google play console .

**Comment by Viish** [comment]
Hi,
Indeed the in-app purchase code is outdated, that's why it was removed in latest version of the app source code.
As we don't use/need it anymore, we don't have plan to restore it. And I'm not familiar with latest changes Google made regarding that, so I can't help you, sorry.

**Comment by Adnan-addi** [comment]
hi ,

i want to ask about tunnell sdk can you tell me is it available for sale,
from where i can find it , and how can i purchase it?
