### ISSUE TITLE
English voice prompt changed to Chinese

### ISSUE THREAD

**Issue by QQ986945193** [BelledonneCommunications/linphone-android#1046]
Hello, I'd like to think about, for example, how to change the English prompt to Chinese when the other party is busy. Thank you for your reply.

**Comment by Viish** [comment]
Hi,
Sorry I don't understand your question. 
Can you clarify ?

**Comment by QQ986945193** [comment]
I've found a solution to modify freeswitch, and I'm testing it. thank you

**Comment by QQ986945193** [comment]
> Hi,
> Sorry I don't understand your question.
> Can you clarify ?

I've found a solution to modify freeswitch, and I'm testing it. thank you
