### ISSUE TITLE
How to use Sample app without SIP account registration? (Peer-2-Peer)

### ISSUE THREAD

**Issue by sebastiantoro** [BelledonneCommunications/linphone-android#1049]
Hello guys,

How can I edit the sample app to allow me to make calls to different SIP endpoints without registering to a SIP server? Is this possible? Maybe by setting up a dummy account? but how do I prevent registration?

Any help will be deeply appreciated.

**Comment by Viish** [comment]
Hi,
You don't need no account to do P2P call.
Simply enter the full SIP address you want to dial, for example: `sip:<username>@<ip>`
Cheers,

**Comment by sebastiantoro** [comment]
Hi,

If I do not create an account, how then I can set transport to TCP? Because by default is UPD.

**Comment by Viish** [comment]
Use this: `<sip:<username>@<ip>;transport=tcp>`

**Comment by sebastiantoro** [comment]
It worked. Thanks a lot.

**Comment by Viish** [comment]
You're welcome :)

**Comment by sebastiantoro** [comment]
for TLS is the same?

**Comment by Viish** [comment]
Yes ;)

**Comment by Mahe2027** [comment]
> Hi, You don't need no account to do P2P call. Simply enter the full SIP address you want to dial, for example: `sip:<username>@<ip>` Cheers,

What is username? If I haven't added an account

**Comment by Viish** [comment]
You can put anything in username, and/or you can also try without it: sip:<IP>
