### ISSUE TITLE
Decline Reason on inc_timeout

### ISSUE THREAD

**Issue by sushilsolanki8875** [BelledonneCommunications/linphone-android#1050]
Hi on the inc_timeout I want to send the decline reason 480(Not Answered), Currently Linphone is sending 486 (Busy).

How can I change these settings?

**Comment by Viish** [comment]
Hi,
In the [sip] section of your config file, set the `inc_timeout_status_code` parameter to 480.
Cheers,

**Comment by sushilsolanki8875** [comment]
Hi, How can I change the decline reason header text?

**Comment by Viish** [comment]
That you can't change, its is currently hardcoded "Not Answered".

**Comment by sushilsolanki8875** [comment]
Ok, If I set inc_timeout_status_code=480, SIP sending the `SIP /2.0 480 Temporarily unavailable`

what is the status code for "Not Answered"?

**Comment by Viish** [comment]
There isn't such a status code, hence the use of 486 Busy.

**Comment by sushilsolanki8875** [comment]
Ok @Viish Thanks.

**Comment by sushilsolanki8875** [comment]
Hi @Viish, Is it possible to send "Reason" in SIP Header Like `Reason: SIP;cause=487;text="ORIGINATOR_CANCEL"` on inc_timeout?

**Comment by Viish** [comment]
The reason header should be created by the decline method already.

**Comment by sushilsolanki8875** [comment]
Hi @Viish, I checked the server logs, Server not getting the reason header. I added an image of the log. 
```
inc_timeout=15
inc_timeout_status_code=480
```
![image_logs](https://user-images.githubusercontent.com/11073493/84500951-3d047280-acd3-11ea-99ec-9bdee6e15301.png)

**Comment by sushilsolanki8875** [comment]
Hi @Viish, I think I need to decline call using `declineWithErrorInfo` method and also need to add `SubErrorInfo` to send **Reason** in the header. is it possible to send on inc_timeout?

**Comment by Viish** [comment]
Not currently, but you can fork the liblinphone project and do the change directly in it.
