### ISSUE TITLE
SIP addresses added by linphone are removed when linphone is uninstalled

### ISSUE THREAD

**Issue by gdt** [BelledonneCommunications/linphone-android#1052]
As discussed on linphone-developers, addresses added to contacts by linphone are marked as "owned" and thus are removed when linphone is removed.  There is a build setting to have this behavior (on by default) or the traditional database behavior.

Users expect database modifications made within linphone to persist even if the app is uninstalled, just as modifications made by almost all other programs persist.   Thus this configuration is a bug and should be changed.  (Perhaps, the ability to run linphone in "owned" mode should just be removed, but perhaps there are people that want this behavior.  No one has spoken up on the list in support of it.)

**Comment by Viish** [comment]
Hi,
Actually this can be discussed:

- I don't mind that when I'm using a service, changes are been made to my contacts regarding this service. When I don't use the service anymore, why not remove this information that isn't relevant anymore?

- But your point is also valid. SIP addresses don't belong to Linphone exclusively, so even if you did use our app to do SIP calls you can still want to keep SIP addresses in your addressbook to use them with another client.

I've already started changes in the feature/kotlin_rewrite branch for that. From now one the default behavior will be to store SIP addresses manually entered in a contact by the user as a SIP address in the persistent native contact but keep the "Linphone" SIP address field to store presence information (phone number aliases).
So when app will be removed, aliases from phone numbers will disappear (as tighly linked to Linphone app itself) but changes made regarding SIP addresses (sip.linphone.org or other) will stay.

I hope that solution will satisfy everyone.

Cheers,

**Comment by gdt** [comment]
Thanks, that sounds like great progress.

I think the issue is that these are not linphone: URIs, but SIP, and linphone is only one way to contact someone via sip.  And in your second point, I could want to install linphone again later, or to have it on one device but not another, and to have the address I added on device A be visible on device A next week, or device B.

I don't really follow the presence/phone-alias, and eventually I'd hope
that things like that are covered by open standards and can be stored
normally and interoperable - but that's a tall order!

**Comment by Viish** [comment]
For the presence it's a bit like WhatsApp: your phone number can be used to contact you through the app. So when the app is removed, the tag is also removed.

**Comment by gdt** [comment]
Interesting -I had seen that, but thought it was some sort of global E.164 to sip distributed database, and not specifically about linphone.

**Comment by Viish** [comment]
Ok I've finished the changes on feature/kotlin_rewrite branch, so now nothing manually entered by the user in the addressbook will get lost after app removal.
