### ISSUE TITLE
Cannot register: Phone number too short

### ISSUE THREAD

**Issue by pappou99** [BelledonneCommunications/linphone-android#1053]
In Linphone 4.2.3 its no more possible to register Linphone (Android and Linux Versions) with my phone number.
Its a German mobile number including 11 digits.

Normally the leading zero is replaced by the country code +49 but than Linphone shows an error 'phone number too short'.
Adding the leading zero ends that it shows 'a SMS-code will be sent' , but I never received one.

**Comment by Viish** [comment]
Hi,
Thanks for the report. It will be fixed for the upcoming release.
Cheers,

**Comment by Viish** [comment]
Fix has been merged in release/4.4 branch of the SDK.
