### ISSUE TITLE
DTMF dial tones do not respect silent setting

### ISSUE THREAD

**Issue by AndreKR** [BelledonneCommunications/linphone-android#1057]
The dial buttons still play DTMF tones, even with the phone set to silent and even with all volumes turned down completely.

Related (but not duplicate) to #1027

**Comment by AndreKR** [comment]
I tried looking which AudioFocus usage those tones use, but I reached a dead end because I have no idea where that `playDtmf()` function is. (JNI?)

**Comment by Viish** [comment]
Hi,
This issue has been fixed in feature/kotlin_rewrite branch.
Cheers,
