### ISSUE TITLE
Dial doesn't work in the first show

### ISSUE THREAD

**Issue by cradle1001** [BelledonneCommunications/linphone-android#1058]
Hi,
Dial doesn't work in the first show after register.
I must touch menu and going to account setting, after that dial is ok.
Why?

**Comment by Viish** [comment]
Hi,
Could you be more specific as what "doesn't work"?
Cheers,

**Comment by cradle1001** [comment]
Hi again,
My mean It is not sent to the server for dialing number.
once i must touch menu and going to account setting, after that dialing works properly.

**Comment by Viish** [comment]
Hi,
Please attach library logs (enable them in advanced settings), restart the app, reproduce the issue and then upload the logs (send logs button in about page).
Thanks.

**Comment by Viish** [comment]
No logs provided, closing.
