### ISSUE TITLE
Runnung Linphone breaks Bluetooth media audio

### ISSUE THREAD

**Issue by AndreKR** [BelledonneCommunications/linphone-android#1059]
How to reproduce:
* Force stop Linphone
* Connect a Bluetooth headset with media capabilities (A2DP, can play music)
* Make sure that "Media audio" is checked in the headsets device properties
* Play some music
* Confirm that the music is playing via the headset
* Now start Linphone

Expected result:
The music continues to play via the headset

Actual result:
The music is now playing through the phone speaker, not the headset anymore. It's not possible to play music via the headset until Linphone is force-stopped.

**Comment by Viish** [comment]
Hi,
This should be solved in feature/kotlin_rewrite branch.
Cheers,
