### ISSUE TITLE
Oversized and Truncated Call_pause request Packet received on server when sender try to pause (hold) the call

### ISSUE THREAD

**Issue by ruchiDYL** [BelledonneCommunications/linphone-android#106]
I am developing one VOIP app using Linphone android SDK, facing issue when sender(outbound call dialer) try to put call on hold/pause. 
on server we found for pause request server receive one oversized truncated packet of size 1514, which is not accepted by server & not responded back to app. 

I found same issue with Linphone Android app too, though with other VOIP service like Xlite and Zoiper works fine on same server ad same user account. 

On receiver side call pause and call resume both works fine always. 
**Here is oversized & truncated hold request packet captured :** 
`~%INVITE` sip:3107401088@192.241.238.42:5090;transport=udp SIP/2.0
Via: SIP/2.0/UDP 10.0.1.15:43671;branch=z9hG4bK.G6u9H4IFb;rport
From: <sip:19887625@sip-rg.getdyl.com>;tag=8MwwAU4u8
To: "(310) 740-1088" <sip:3107401088@sip-rg.getdyl.com>;tag=D6D1yB7ZpBXcp
CSeq: 22 INVITE
Call-ID: zlq9LBX6nO
Max-Forwards: 70
Route: <sip:107.170.224.18;ftag=8MwwAU4u8;lr=on>
Subject: Call on hold
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO, UPDATE
Content-Type: application/sdp
Content-Length: 490
Contact: <sip:19887625@38.107.163.141:35198;transport=udp>;+sip.instance="<urn:uuid:9e5f3e5a-0391-4fcb-9b45-3233f1ea01a9>"
User-Agent: LinphoneAndroid/1.1.0 (belle-sip/1.5.0)
Proxy-Authorization:  Digest realm="sip-rg.getdyl.com", nonce="WZSFg1mUgyu668fR+qsUq7y7Bsn9B7ZKzrWhn1y60Okbp0SKqxj5jg==", username="19887625",  uri="sip:3107401088@192.241.238.42:5090;transport=udp", response="1c8929075d17bdb3f6fd6eca16418dce", cnonce="~Px7q8TXC4uu88kb", nc=00000002, qop=auth
v=0
o=19887625 27 494 IN IP4 10.0.1.15
s=Talk
c=IN IP4 10.0.1.15
b=AS:380
t=0 0
a=rtcp-xr:rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics
m=audio 7076 RTP/AVP 96 97 98 99 0 8 101 100 102
a=rtpmap:96 opus/48000/2
a=fmtp:96 useinbandfec=1
a=rtpmap:97 SILK/16000
a=rtpmap:98 speex/16000
a=fmtp:98 vbr=on
a=rtpmap:99 speex/8000
a=fmtp:99 vbr=on
a=rtpmap:101 telephone-event/48000
a=rtpmap:100 telephone-event/16000
a=rtpmap:102 `telephone-e``
<img width="2473" alt="pausecall_trunctedpacket at 10 42 59 am" src="https://user-images.githubusercontent.com/25807284/29590603-88d38a72-874f-11e7-8917-0ce111bf4fb8.png">

Here is Packet received for Good hold : 

`INVITE sip:mod_sofia@192.241.238.42:5090 SIP/2.0
Via: SIP/2.0/UDP 10.0.1.15:43671;branch=z9hG4bK.H4xi2N6Gd;rport
From: <sip:114_u19882507@107.170.224.18>;tag=15aWm4h
To: "rg1" <sip:3107401088@192.241.238.42>;tag=Fr0j2186gX9HD
CSeq: 111 INVITE
Call-ID: 0a2fa1ea-82ab-11e7-9b79-e3dd8cdaaa0d
Max-Forwards: 70
Route: <sip:107.170.224.18;ftag=Fr0j2186gX9HD;lr=on>
Route: <sip:107.170.224.18;ftag=Fr0j2186gX9HD;lr=on>
Subject: Call on hold
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO, UPDATE
Content-Type: application/sdp
Content-Length: 491
Contact: <sip:19887625@38.107.163.141:39856;transport=udp>;+sip.instance="<urn:uuid:9e5f3e5a-0391-4fcb-9b45-3233f1ea01a9>"
User-Agent: LinphoneAndroid/1.1.0 (belle-sip/1.5.0)
v=0
o=19887625 397 220 IN IP4 10.0.1.15
s=Talk
c=IN IP4 10.0.1.15
b=AS:380
t=0 0
a=rtcp-xr:rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics
m=audio 7076 RTP/AVP 96 97 98 99 0 8 101 100 102
a=rtpmap:96 opus/48000/2
a=fmtp:96 useinbandfec=1
a=rtpmap:97 SILK/16000
a=rtpmap:98 speex/16000
a=fmtp:98 vbr=on
a=rtpmap:99 speex/8000
a=fmtp:99 vbr=on
a=rtpmap:101 telephone-event/48000
a=rtpmap:100 telephone-event/16000
a=rtpmap:102 telephone-event/8000
a=sendonly
`
<img width="2467" alt="goodhold10 52 35 am" src="https://user-images.githubusercontent.com/25807284/29590949-394c032e-8751-11e7-9ced-d4fd5fe08e1d.png">

Now here is Resume call request Packet after Good hold : 
`INVITE sip:mod_sofia@192.241.238.42:5090 SIP/2.0
Via: SIP/2.0/UDP 10.0.1.15:43671;branch=z9hG4bK.xZh~yKZ8m;rport
From: <sip:114_u19882507@107.170.224.18>;tag=15aWm4h
To: "rg1" <sip:3107401088@192.241.238.42>;tag=Fr0j2186gX9HD
CSeq: 112 INVITE
Call-ID: 0a2fa1ea-82ab-11e7-9b79-e3dd8cdaaa0d
Max-Forwards: 70
Route: <sip:107.170.224.18;ftag=Fr0j2186gX9HD;lr=on>
Route: <sip:107.170.224.18;ftag=Fr0j2186gX9HD;lr=on>
Subject: Call resuming
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO, UPDATE
Content-Type: application/sdp
Content-Length: 479
Contact: <sip:19887625@38.107.163.141:39856;transport=udp>;+sip.instance="<urn:uuid:9e5f3e5a-0391-4fcb-9b45-3233f1ea01a9>"
User-Agent: LinphoneAndroid/1.1.0 (belle-sip/1.5.0)
v=0
o=19887625 397 221 IN IP4 10.0.1.15
s=Talk
c=IN IP4 10.0.1.15
b=AS:380
t=0 0
a=rtcp-xr:rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics
m=audio 7076 RTP/AVP 96 97 98 99 0 8 101 100 102
a=rtpmap:96 opus/48000/2
a=fmtp:96 useinbandfec=1
a=rtpmap:97 SILK/16000
a=rtpmap:98 speex/16000
a=fmtp:98 vbr=on
a=rtpmap:99 speex/8000
a=fmtp:99 vbr=on
a=rtpmap:101 telephone-event/48000
a=rtpmap:100 telephone-event/16000
a=rtpmap:102 telephone-event/8000` 
<img width="2472" alt="goodresume10 53 10 am" src="https://user-images.githubusercontent.com/25807284/29590748-2fb1168e-8750-11e7-823b-deef14706495.png">

Can anybody help me in resolving this Call_Pause issue, how can server identify the truncated packets or is there any way I can reduce the hold request packet size. this looks Linphone SDK bug can you please resolve this. 
@BelledonneComm

**Comment by DatBewar** [comment]
Hello,
You are using transport UDP so packet are not reliable.
Please try with TCP

**Comment by ruchiDYL** [comment]
@DatBewar Thanksfor your response, I tried with TCP as well its always same.

**Comment by ghrst** [comment]
We have the same problem. Does liblinphone support SIP compact header fields?
