### ISSUE TITLE
How to judge whether the call is voice or video

### ISSUE THREAD

**Issue by kaer-dial** [BelledonneCommunications/linphone-android#1060]
I want to judge whether the call is voice or video when the call state = Call.State.IncomingReceived , how to do?

**Comment by chinext** [comment]
final CallParams remoteParams = core.getCurrentCall().getRemoteParams();
 if (remoteParams != null && remoteParams.getVideoEnabled()) {
            //answer: video true
  } else {
          //answer: video false");
  }
