### ISSUE TITLE
No ringtone when receiving call

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1061]
On latest kotlin_rewrite branch, I don't seem to be getting any ring tone when an incoming call is received any more.  This is true with _Call_->_Use device ringtone_ enabled and disabled.

I get a notification tone and vibration, but no app ring tone.

**Comment by brianjmurrell** [comment]
I can confirm this on a second device.  This is a regression in the last week or two.

**Comment by Viish** [comment]
Thanks for reporting it.
Indeed there was a small regression regarding that in master branch of the SDK.
Fixed in MR https://gitlab.linphone.org/BC/public/linphone-sdk/merge_requests/1070

**Comment by brianjmurrell** [comment]
I'm never clear on this because there never seems to be a single pattern to it, but what do I have to do to build with this new SDK?  Or is the kotlin_rewrite branch already specifying the new SDK version?

**Comment by Viish** [comment]
feature/kotlin_rewrite branch is configured to use a locally built SDK or the latest alpha from our maven (the most recent of both, using version code to know which one is the most recent).
The fix isn't in master yet until MR will be merged, so it won't be available through maven until it is merged.
If you want it now, check out the MR branch, build it (use cmake .. first to ensure version name is computed and up-to-date) and then build again the app.

**Comment by brianjmurrell** [comment]
Oh, right.  I didn't register that the URL was for an MR, not a commit.

> If you want it now, check out the MR branch, build it (use cmake .. first to ensure version name is computed and up-to-date) and then build again the app.

TBH, for as many times as I have attempted, I have never successfully built the SDK.  It always fails on something and then the can of worms opens up sucking me in, trying to fix one thing after another.

I guess I will wait.  How will I know when it's available in your maven?

And when it is, will `./gradlew installDebug` fetch the newer one or will the one that is currently in the cache satisfy linphone-android, and it will not try to fetch the newer one?

**Comment by Viish** [comment]
It has been merged, so the AAR will be available in maven in less than one hour if nothing goes wrong.
Regarding the gradle build, no it won't be updated just by using `./gradlew installDebug`.
Try with `'--refresh-dependencies'` or force the full version name in app/build.gradle: 4.4.0-alpha-287-g1ed94d7

**Comment by brianjmurrell** [comment]
Is there any reason that `app/build.gradle` doesn't specify the current minimum value of the SDK needed, on an ongoing basis to ensure that the most recently required SDK is actually used?  Not unlike specifying the minimum value of any dependent package in any of dozens of build/packaging systems.

**Comment by Viish** [comment]
We could specify the full version each time, but we want to make sure the latest version is used, and update the version in the app for each commit in the SDK would be too time consuming.

**Comment by brianjmurrell** [comment]
I'm not necessarily saying that the latest SDK version is always specified so that there is a linphone-android update for every SDK update, but just that when there is a reason to specify _at least_ some minimum version -- because the API of the SDK changes, or a serious bug is fixed in the SDK, etc., that linphone-android requires that version *or newer*, just to ensure everyone who is building is using the minimum version.

Might reduce bug reports at least.

**Comment by gennaro-arch** [comment]
I have this problem, too. Everything is updated to the playstore version.
