### ISSUE TITLE
TelephonyManager Call State Ringing

### ISSUE THREAD

**Issue by nzkar** [BelledonneCommunications/linphone-android#1062]
Hi, when a cellular call is received while on a sip call, the user is notified by phone ringtone. Is it possible to notify the user by just a beeping sound?

**Comment by Viish** [comment]
Hi,
When a linphone call is playing you can't control the GSM app behavior.
The only way to do that is to use the native GSM app also for VoIP calls like we did in this branch (a prototype): feature/use_android_native_dialer
