### ISSUE TITLE
Linphone is unreachable, how to fix it?

### ISSUE THREAD

**Issue by ck932** [BelledonneCommunications/linphone-android#1064]
Hi,

Linphone is unreachable, how to fix it? Thanks

[Jun 18 06:36:08] NOTICE[1409][C-00000001] chan_sip.c: Received AVPF profile in audio offer but AVPF is not enabled, enabling: audio 7076 RTP/AVPF 96 97 98 0 8 18 101 99 100
[Jun 18 06:36:30] NOTICE[1409][C-00000002] chan_sip.c: Received AVPF profile in audio offer but AVPF is not enabled, enabling: audio 7076 RTP/AVPF 96 97 98 0 8 18 101 99 100
[Jun 18 06:40:13] NOTICE[1409] chan_sip.c: Peer '4001' is now UNREACHABLE!  Last qualify: 1549
[Jun 18 06:42:09] NOTICE[1409] chan_sip.c: Peer '4001' is now Reachable. (169ms / 3000ms)
[Jun 18 06:42:18] NOTICE[1409][C-00000003] chan_sip.c: Received AVPF profile in audio offer but AVPF is not enabled, enabling: audio 7076 RTP/AVPF 96 97 98 0 8 18 101 99 100
[Jun 18 06:43:12] NOTICE[1409] chan_sip.c: Peer '4001' is now Lagged. (3478ms / 3000ms)
[Jun 18 06:43:23] NOTICE[1409] chan_sip.c: Peer '4001' is now Reachable. (577ms / 3000ms)
[Jun 18 06:44:51] NOTICE[1409][C-00000004] chan_sip.c: Received AVPF profile in audio offer but AVPF is not enabled, enabling: audio 7076 RTP/AVPF 96 97 98 0 8 18 101 99 100
[Jun 18 06:46:30] NOTICE[1409] chan_sip.c: Peer '4001' is now UNREACHABLE!  Last qualify: 575

**Comment by Viish** [comment]
Hi,
It doesn't look like our SDK logs.
Can you attach the full library logs?

**Comment by ck932** [comment]
hi,
I use raspberry pi 3B+ to set up a sip server(Asterisk 16.2), and use Linphone Android 4.2.3 (release) as a sip client.
The connection is unstable. I don't know what to do.
Could you tell me how to fix it, Thnaks.

**Comment by Viish** [comment]
Start by attaching your Linphone logs (enable them in advanced settings, restart the app, reproduce the issue and then upload them using the send logs button in about page).

**Comment by ck932** [comment]
hi,
I have turned on the Debug mode already, do you receive the data?
And any suggestions?
Thanks

**Comment by Viish** [comment]
Did you do the logs upload & sent an email with the link ? Because I didn't received anything.

**Comment by ck932** [comment]
The Logs upload server is :
https://www.linphone.org:444/lft.php

But there is no "send logs button" in the page

**Comment by Viish** [comment]
In the about page, if you enabled debug logs, there are two buttons: send logs & reset logs.

**Comment by ck932** [comment]
no
no "send logs & reset logs"

**Comment by Viish** [comment]
Send a screenshot of the about page & advanced settings page.

**Comment by ck932** [comment]
give me email, I send it to you.

**Comment by ck932** [comment]
hi,
it is my mistakes, the "send logs & reset logs" in ABOUT page.

**Comment by ck932** [comment]
Do you receive the data?

**Comment by Viish** [comment]
No I haven't. You did send it to linphone-android@belledonne-communications.com ?

**Comment by ck932** [comment]
I am in China, I use VPN to send it  again. I hope you can get it.Thanks

**Comment by ck932** [comment]
Do you get it?

**Comment by Viish** [comment]
Still no. Copy/paste the link here.

**Comment by ck932** [comment]
hi,
I have already email the log file to you, do you get it?

**Comment by Viish** [comment]
Hi,
Yes this time I got it.

**Comment by Viish** [comment]
There is no issue in your logs, you are correctly registered to your server.
However you use UDP, that will cause issues. You should switch to TLS or at least TCP: https://wiki.linphone.org/xwiki/wiki/public/view/Linphone/Good%20practices%20for%20using%20SIP/
