### ISSUE TITLE
SIP call go on hold automatically when an normal phone call comes on phone

### ISSUE THREAD

**Issue by vikas442** [BelledonneCommunications/linphone-android#1067]
Hi,
I'm facing an issue while on SIP call, if there is an normal phone call comes on my phone then current SIP call automatically get paused(even normal phone call is not received).
I am using latest SDK i.e. `4.3.4-pre.37+1855aec`
Please let me know if I have to add some extra checks for this.

**Comment by Viish** [comment]
Hi,
This isn't handled by the SDK (it is in master branch but not in 4.3.4 version) so it is your app that is responsible for this.
Check if you have a telephony manager somewhere.
