### ISSUE TITLE
Related to: Unable to make successful video calls #938

### ISSUE THREAD

**Issue by nzkar** [BelledonneCommunications/linphone-android#1068]
Hi, related to the previous issue I created (Unable to make successful video calls #938), I could not get any answers from both linphone-sdk and Liblinphone projects. Since this issue effects linphone-android application usage, can you please direct this issue to the related developers?

**"Hi, I'm using linphone-android downloaded from Google Play. If I register two phones to sip.linphone.org, they can make successful video calls. However if I register them to my own sip server, the call is initiated but the devices cannot send audio/video to each other. When I captured their pcap with Wireshark, I see that inside sip message "Invite", sdp's connection ip is send as local ip even though my phone is not in the local network and it registers with its nat ip. And when I disable video and only make an audio call, the sdp's connection ip is send as real ip. Can you explain the reason behind this? Probably this is the reason why I cannot make successful video calls. Audio and video cannot be transferred to the real ip.

On the other hand, I think the reason why it works with sip.linphone.org is, in sdp there are 3 connection ip's sent. First connection ip is local ip however it writes its real ip on the "Connection Information" lines right after the "Media Descryption:audio" and "Media Descryption:video" lines. These 2 lines are never sent in invite messages to my own sip server. I guess you behave differently when linphone sip server is used."**

**Comment by Viish** [comment]
Hi,
I'm sorry but I can't help much on that, not really my area.
Check you the 4.4 version of the SDK or a master version to see if it hasn't bee fixed.
