### ISSUE TITLE
Top mic doesn't work in spearker mode on Samsung s10e

### ISSUE THREAD

**Issue by qw1nzup** [BelledonneCommunications/linphone-android#1070]
bottom mic is turned on when we turn on speaker mode 

excepted results:
Top mic should be tunred on when we turn on speaker mode  - it is a default behaviour of skeaker mode.

[MediaRecorder.AudioSource.MIC](https://developer.android.com/reference/android/media/MediaRecorder.AudioSource#MIC) - bottom mic
[MediaRecorder.AudioSource.CAMCORDER](https://developer.android.com/reference/android/media/MediaRecorder.AudioSource#CAMCORDER) - top mic

**Comment by Viish** [comment]
If that's whay you want, add the DEVICE_USE_ANDROID_CAMCORDER flag for your device before the Core starts using `core.mediastreamerFactory.setDeviceInfo()` method

**Comment by qw1nzup** [comment]
@Viish you best!
Could you provide link to the doc that I can to find desctiption about these method and flag?

**Comment by Viish** [comment]
We don't really have documentation but check those 2 files:
https://github.com/BelledonneCommunications/mediastreamer2/blob/master/src/audiofilters/devices.c#L225
https://github.com/BelledonneCommunications/mediastreamer2/blob/master/java/src/org/linphone/mediastream/Factory.java#L48

**Comment by gitterspec** [comment]
I'm experiencing the same on OnePlus 6T. Is this supposed to be the default behavior? It makes it so that I am extremely quiet to the other side when on speaker. Please let me know if there's a workaround.
