### ISSUE TITLE
Names from phone book are not displayed if saved with country-prefix

### ISSUE THREAD

**Issue by Elendil211** [BelledonneCommunications/linphone-android#1071]
Names from the phone book are not displayed if saved with country-prefix and call comes without.
It might be, that this is only the case if you are in a different country than your number is based in.

Example:
Phone book-Entry: _Mom: +12 3456 7890_
If I get called from _03456 7890_ "Mom" is not shown on the display.

Suggestion to fix: Make a setting for "default-prefix" and check if the number occurs in the phone book with or without the prefix.

**Comment by Viish** [comment]
There already is a setting for prefix (in the account settings).

**Comment by Viish** [comment]
I have added a linphone_core_find_friend_by_phone_number method that will check no matter the phone format and that should solve your issue (if your prefix setting is set).
