### ISSUE TITLE
Per-account rewrite rules

### ISSUE THREAD

**Issue by roaima** [BelledonneCommunications/linphone-android#1073]
I have three SIP accounts. One of them expects numbers formatted according to UK standards with local numbers extended to include an area code, and international numbers starting with 00. The other two expect all numbers to be formatted in the international format starting with an explicit country code.

I would like to be able to enter a number in my UK usual format, for example, 020abcdefgh or maybe +4420abcdefgh and have that rewritten to fit the format required by the SIP provider.

For provider 1, your existing "Replace initial + with 00" is sufficient. For the other providers I would need a series of rules. Perhaps

- If matching "0 not-0", replace initial 0 with 0044
- Replace initial + with 00

Or if the condition/action pair is complicated

- Replace initial 0 with 0044    (try to internationalise a national number)
- Replace initial 00440 with 00    (undo incorrect internationalisation)
- Replace initial + with 00

If it helps, the now-defunct opensource CSip Simple project had rules like these.

**Comment by Viish** [comment]
Hi,
All those settings already exists in the account settings list (at the bottom), so you can configure them as you wish for each account.
Cheers,

**Comment by roaima** [comment]
I'm using the release version 4.2.3 from the Play Store. There is no feature for rewrite rules. Are you considering a different version?

**Comment by Viish** [comment]
There isn't a "rewrite rule" feature but there is the prefix and "replace + by 00" settings.

**Comment by roaima** [comment]
In that case please would you consider reopening this ticket as an enhancement request.

**Comment by Viish** [comment]
If we were considering doing that enhancement, we wouldn't do it in the app code but in the SDK instead.
Please open such "issue" to the linphone-sdk or liblinphone repository.
