### ISSUE TITLE
SIP accounts (wrongly) share authentication data

### ISSUE THREAD

**Issue by roaima** [BelledonneCommunications/linphone-android#1074]
I have three SIP accounts. It appears that accounts 2 and 3 wrongly share some authentication details.

I enter user2 as the auth userid for account 2, and user3 as the auth userid for account 3.

Reviewing account 2 I can see that the auth userid has been updated to user3 and the account will not connect. When I update the account details once more to user2, I find that account 3 disconnects and that upon inspection the auth userid has also been updated to user2.

Version 4.3.0 from your nightlies.

**Comment by Viish** [comment]
Hi,
I can't reproduce your issue. Can you install a debug version and send me your .linphonerc file of your device using `adb shell run-as org.linphone.debug cat files/.linphonerc > linphonerc` command after reproducing your issue please ?
