### ISSUE TITLE
Question about debug the file log!!

### ISSUE THREAD

**Issue by firebase1** [BelledonneCommunications/linphone-android#1075]
Hello
I want to get debug the file log in local storage without download from linphone.org:444 and how can I disable upload the file log to linphone.org:444?

**Comment by Viish** [comment]
Hi,

First of all, linphone logs aren't uploaded unless you ask the Core to do so. Even if you do, you can change the URL where the file is posted by changing the `log_collection_upload_server_url` property in the `[misc]` section of your config file or by calling `core.setLogCollectionUploadServerUrl()`.

The log file itself is stored in the files/ directory of the app data (usually /data/data/<package name>/) and when the app is built in debug mode you can access it with `adb shell run-as <package name> cat files/linphone1.log` for example.

Finally if you want to disable the log file completely, use `Factory.instance().enableLogCollection(LogCollectionState.Disabled);` before creating the Core.

Cheers,
