### ISSUE TITLE
Contacts order/sorting

### ISSUE THREAD

**Issue by ovari** [BelledonneCommunications/linphone-android#1077]
https://github.com/BelledonneCommunications/linphone-desktop/issues/393

**Comment by Viish** [comment]
Indeed, for some reason the compareTo() method of Strings doesn't handle this well.
I fixed it in feature/kotlin_rewrite branch.
Thanks for the report.

**Comment by ovari** [comment]
Can you please advise when this will be available in the Google Play Store version? Thank you

**Comment by Viish** [comment]
It will be part of the next release, probably August or September

**Comment by ovari** [comment]
Will the Linphone beta channel on Android have this fix sooner? Thank you
https://wiki.linphone.org/xwiki/wiki/public/view/Linphone/Enter%20the%20public%20beta%20test/

**Comment by Viish** [comment]
Yes, the 4.3.1 will have the fix.
