### ISSUE TITLE
The linphone library has stopped connecting to the Android project today

### ISSUE THREAD

**Issue by Strikelon** [BelledonneCommunications/linphone-android#1078]
Hello. Please give some advice. The linphone library has stopped connecting to the project today. Everything worked yesterday.

I used 
        maven { url "https://linphone.org/releases/maven_repository/" }
or
        maven {  url "https://linphone.org/snapshots/maven_repository" }
and 
    implementation "org.linphone:linphone-sdk-android:4.3+"

And everythig worked? but today I see the error when building the project

Failed to resolve: org.linphone:linphone-sdk-android:4.3+

Can you advice, what can i do to fix this?

Here the screenshots:
https://prnt.sc/t9n4i4
https://prnt.sc/t9n4m2

**Comment by Viish** [comment]
Hi,

This means you were using the legacy maven repository.
The new one is https://linphone.org/maven_repository/

Cheers,
