### ISSUE TITLE
Accepting TLS self signed certificates 

### ISSUE THREAD

**Issue by sebastiantoro** [BelledonneCommunications/linphone-android#1080]
Hello,

I am making P2P to video.domain.com dialing to the following uri: `sip:virtual_room@video.domain.com;transport=tls`. but it doesn't connect and throw me the following error:

```
Channel [0x79791ca300]: SSL handshake failed : X509 - Certificate verification failed, e.g. CRL, CA or signature check failed
Cannot connect to [TLS://video.domain.com:5061]
```

The server is using a self signed certificate. How can I accept self signed certificates?

**Comment by Viish** [comment]
Hi,
You can disable certificate check by setting the verify_server_certs=0 in the [sip] section of your config file.
You can also embed your own rootca.pem in the app and set it's path using the [sip] root_ca=<path> property.
Finally you can install your server certificate somewhere and configure the path to it with [misc] user_certificates_path=<path> property or linphone_core_set_user_certificates_path() method which is definitively the best option of the 3.

**Comment by sebastiantoro** [comment]
@Viish, as always, thanks a lot for your valuable response.

**Comment by merry37** [comment]
@sebastiantoro plz guide me as i am implementing that, and i didn't find a way.
