### ISSUE TITLE
echo

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1081]
Hi,
Do not understand the differences and functions of the following interfaces, can you explain it？ 
 void enableEchoCancellation(boolean var1);
void setEchoCancellerFilterName(String var1);
void enableEchoLimiter(boolean var1);

thanks.

**Comment by fengqz627** [comment]
In addition, why sometimes getting echoes fails. The code is as follows:
ublic void onEcCalibrationResult(Core lc, EcCalibratorStatus status, int delayMs) {
                        lc.removeListener(mListener);
                        LinphoneManager.getInstance().routeAudioToSpeaker();
                        XLog.d("save testEcho result: %s, and delay_ms: %d ", status, delayMs);

I get EcCalibratorStatus Failed: “save testEcho result: Failed”

**Comment by Viish** [comment]
Hi,
Echo canceller calibration might fail, specially if you aren't on speaker at the time of the test.
enableEchoCancellation() enables or disables the software echo canceller (you might have multiple implementation possible hence the setEchoCancellerFilterName() but you shoudln't have to use it).
Echo limiter is a different feature and shouldn't be used as it is less good than the echo canceller.
