### ISSUE TITLE
CallIncomingActivity sometimes not bring to front when phone is locked Android 9 & 10

### ISSUE THREAD

**Issue by JitainSharma** [BelledonneCommunications/linphone-android#1084]
When phone is locked and left idle for long time, call to Android 10 or Android 9 device user, following two scenarios happened:

1. **Android 10** In-coming Call comes, device screen turns on but instantly turn off and no call screen is shown.
2. **Android 9** Call comes, but in-coming call screen shown under the lock screen or incoming call screen shown perfectly but after call accept the CallActivity goes behind the lock screen.
3. **Android 10** Sometimes the logs shows incoming call is received but no incoming call screen is trigged.

**Comment by Viish** [comment]
On Android 10 you must use fullScreenIntent notification. You can no longer start an activity from background, but instead you have to display a notification with a fullScreen intent to an activity that the OS might decide to show or not.
Regarding your Android 9 issue, check you have called activity.setShowWhenLocked(ture) in your onCreate().

**Comment by JitainSharma** [comment]
Yes, I am using the flags and methods in onCreate method in the oder:
```
window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)
activity.setTurnScreenOn(true)
activity.setShowWhenLocked(true)
```
