### ISSUE TITLE
How to start a conference call

### ISSUE THREAD

**Issue by vikas442** [BelledonneCommunications/linphone-android#1085]
Hi @Viish ,

Please let me know, if there is a way to initiate a conference call with selected contacts, instead of calling them one by one and adding them to conference call.

Also, how we can directly invite a contact to confrence call, instead of first call them and then add to conference.

**Comment by Viish** [comment]
First create a conference: https://www.linphone.org/snapshots/docs/liblinphone/multilang/reference/java/linphone_core.html#linphone.Core.createConferenceWithParams(linphone.ConferenceParams)

Then use https://www.linphone.org/snapshots/docs/liblinphone/multilang/reference/java/linphone_conference.html#linphone.Conference.inviteParticipants(linphone.Address[],%20linphone.CallParams) to add participants to your conference directly.

**Comment by touhiDroid** [comment]
> First create a conference: https://www.linphone.org/snapshots/docs/liblinphone/multilang/reference/java/linphone_core.html#linphone.Core.createConferenceWithParams(linphone.ConferenceParams)
> 
> Then use [https://www.linphone.org/snapshots/docs/liblinphone/multilang/reference/java/linphone_conference.html#linphone.Conference.inviteParticipants(linphone.Address[],%20linphone.CallParams)](https://www.linphone.org/snapshots/docs/liblinphone/multilang/reference/java/linphone_conference.html#linphone.Conference.inviteParticipants(linphone.Address%5B%5D,%20linphone.CallParams)) to add participants to your conference directly.

The provided URLs are resulting in 404. Could you please give any up-to-date guidelines / URLs here?

**Comment by Viish** [comment]
Use this link : http://linphone.org/snapshots/docs/liblinphone/latest/

**Comment by Irfanulhaq1991** [comment]
@Viish Is there any limitation on the number of participants?

**Comment by Viish** [comment]
The only limit is the number of calls your device & network bandwidth can withstand.

**Comment by Irfanulhaq1991** [comment]
@Viish  when doing one-to-one video call,  the remote texture view is set as  core.nativeVideoWindowId and remote video stream is rendered in it without any extra effort. How is the video retrieved and displayed for each individual participant in conference?

**Comment by Viish** [comment]
Video conferencing isn't available yet, we're working on it on master branch of linphone-sdk.

**Comment by Irfanulhaq1991** [comment]
@Viish Thanks for the information. Could you please let us know about the targeted version in which video conferencing will be incorporated?

**Comment by Viish** [comment]
It will be in SDK 5.2, app 4.7

**Comment by Irfanulhaq1991** [comment]
@Viish I am already on a call and I create another then add to conference, the call first is paused. I have tried to resume it before the conference but it is still paused.

`        if(state == Call.State.OutgoingInit) {
            if (core.callsNb > 1) {
                val params = core.createConferenceParams()
                val conference = core.conference ?: core.createConferenceWithParams(params)
                core.calls.forEach { it.resume() }
                conference?.addParticipants(core.calls)
                call.remoteAddress
            }
        }
`
How to create a conference properly when already on a call?

**Comment by Viish** [comment]
Take a look at our code: https://gitlab.linphone.org/BC/public/linphone-android/-/blob/release/4.6/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt#L385
