### ISSUE TITLE
Conference Call log

### ISSUE THREAD

**Issue by vikas442** [BelledonneCommunications/linphone-android#1088]
@Viish , Please let me know that how we can get conference call logs with participants detail.
From `getCallLogs()` method we are getting complete list of call logs including which we invited through conference call. Though there is a method named `wasConference()` but it always returns `false`.

**Comment by Viish** [comment]
`wasConference()` only returns true to calls made to a remote conference, not a "local" one.
Currently there is no way to know if a call log is linked to a call that was part of a client based conference.
