### ISSUE TITLE
cannot find symbol 'message.resend();'

### ISSUE THREAD

**Issue by ds0218** [BelledonneCommunications/linphone-android#1090]
linphone-android/app/src/main/java/org/linphone/chat/ChatMessagesFragment.java:541: error: cannot find symbol
            message.resend();
                   ^
  symbol:   method resend()
  location: variable message of type ChatMessage

**Comment by redoforient** [comment]
resend was deprecated for a while now so it was removed from the SDK. Use send() instead.

**Comment by Viish** [comment]
> resend was deprecated for a while now so it was removed from the SDK. Use send() instead.

Indeed.
