### ISSUE TITLE
Sound transmission is half duplex

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1096]
HI,

Does linphone now support half duplex transmission? I found that when one side is talking, the voice of the other side can't be transmitted. Do you have to wait until the other side stops talking? Can I change it to duplex?

thanks.

**Comment by Viish** [comment]
Linphone doesn't have such half-duplex feature, we always send and receive sound at the same time. 
If this is really what's happening, it means it your server that create this half duplex mode, not us.
