### ISSUE TITLE
dtmf tones

### ISSUE THREAD

**Issue by nzkar** [BelledonneCommunications/linphone-android#1097]
Hi, I don't have this issue with other devices but one of my devices does not play dtmf tones while dialing a number to call. I tried the same device with another VoIP application. It has no problem with dtmf tones. What might be the reason behind this? I also tried commenting out the playDtmf functions return statement, only leaving the playDtmf command there.

**Comment by Viish** [comment]
Hi,
On the latest release and current master we rely on a system setting to tell us whether to play sound or not when a DTMF digit is pressed: Settings.System.DTMF_TONE_WHEN_DIALING
Check your device settings to see if this is enabled or not.
Cheers,

**Comment by nzkar** [comment]
Thank you, I tried commenting out;

if (Settings.System.getInt(r, Settings.System.DTMF_TONE_WHEN_DIALING) == 0) {
                // audible touch disabled: don't play on speaker, only send in outgoing stream
                return;
            }

So, in all conditions "LinphoneManager.getCore().playDtmf(dtmf, -1);" is called. However still no dtmf tone. Do you have any other suggestions?

**Comment by Viish** [comment]
Have you checked your device sound volume?
Also do you hear audio during a call?
If issue persists please send logs.

**Comment by nzkar** [comment]
Yes I have checked the device sound volume settings. I can hear the dtmf tone in another voip app. I can also hear audio during a call. Here is the log, I just pressed the buttons, as I mentioned earlier, it works with all other devices I own.

https://linphone.org:444//tmp/5f1051fd536f5_5d10b81cc64e2daf00d9.gz

**Comment by Viish** [comment]
Everything looks fine:
```
2020-07-16 16:11:14:439 [mediastreamer] MESSAGE configuring resampler output to rate=[48000], nchannels=[1]
2020-07-16 16:11:14:440 [mediastreamer] MESSAGE ms_filter_link: MSFilePlayer:0x7f7636e400,0-->MSDtmfGen:0x7f75e98e80,0
2020-07-16 16:11:14:440 [mediastreamer] MESSAGE ms_filter_link: MSDtmfGen:0x7f75e98e80,0-->MSResample:0x7f75ff7300,0
2020-07-16 16:11:14:440 [mediastreamer] MESSAGE ms_filter_link: MSResample:0x7f75ff7300,0-->MSOpenSLESPlayer:0x7f75e98f00,0
```

What's the device that has this issue?

**Comment by nzkar** [comment]
Yes it looks like dtmf generator is working but no tone is played. It is Hytera vm780. On the contrary as I mentioned other voip apps do play dtmf tones.

**Comment by Viish** [comment]
Sorry, can't help much without the device in my hands.

**Comment by nzkar** [comment]
Right, thank you.
