### ISSUE TITLE
Gain

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1099]
Hi,

When in the connect or streamsrunning state，I want to change the gain and then call the following:
 lc.setPlaybackGainDb(playBackGain);
 lc.setMicGainDb(microphoneGain);
Do I need to call REINVITE or reinviteWithAudio after that？

thanks.

**Comment by Viish** [comment]
Hi,
No you don't need to reinvite for that.
Cheers,
