### ISSUE TITLE
Sound is turned off after a couple of seconds from receiving a Linphone call

### ISSUE THREAD

**Issue by marmistrz** [BelledonneCommunications/linphone-android#11]
(This seems a better place to report this than the mailing list. Besides, I have more information)

I'm using Linphone 3.2.4 on CM 13.0/OnePlus 3 from Play Store. I don't run Google Play Services, have microG installed though, with GCM turned off. This happened with 3.1.0-fdroid too, IIRC. 

Linphone has all permissions granted.

A few seconds after receiving a Linphone call, the phone speaker gets turned off. If I use headphones or a loudspeaker, I can hear the other person, though. Both devices record audio, which can be seen on the desktop client gauges.

The log from the Android client follows: https://paste.kde.org/p4jnkzdej

The problem doesn't seem to happen when the Android device is the one initiating the call.

**Comment by marmistrz** [comment]
The same happens on Samsung Galaxy J7 with stock Samsung ROM.

**Comment by zmk4** [comment]
Which android device?  Some curiously employ deviant changes in audio subsystems

 [see also: csipsimple & audio routing]

**Comment by zmk4** [comment]
^ which other android devices

**Comment by DatBewar** [comment]
Hello,
can you enable debug option on Linphone for the logs please?
Thank

**Comment by marmistrz** [comment]
@zmk4: the configurations were: OnePlus 3 <-> Samsung Galaxy J7, OnePlus 3 <-> Asus R556, Arch Linux
@DatBewar here you are
[linphone.txt.gz](https://github.com/BelledonneCommunications/linphone-android/files/774188/linphone.txt.gz)

**Comment by DatBewar** [comment]
Hi @marmistrz.
On logs, i didn't see any problem from network or linphone.
The problem is, i can't reproduce with phones we have.

Can you try with our last Linphone beta 3.5.2 ?
You can find it on google play if you join beta group or source [here](https://github.com/BelledonneCommunications/linphone-android/tree/beta_android)

Best regards

**Comment by marmistrz** [comment]
Hi @DatBewar 
May I ask for the .apk?
In the past there were apks provided here: https://download.savannah.gnu.org/releases/linphone/

**Comment by DatBewar** [comment]
You can found last release and last beta here: https://www.linphone.org/releases/android/

**Comment by marmistrz** [comment]
Can't reproduce on 3.2.5, thanks! :)

**Comment by marmistrz** [comment]
The same problem appears when switching back from loudspeaker to the phone speaker. Linphone 3.2.5.

**Comment by DatBewar** [comment]
Can you try with our last release?
https://www.linphone.org/releases/android/linphone-latest.apk

**Comment by DatBewar** [comment]
Any update?

**Comment by marmistrz** [comment]
Oh, sorry, I missed your previous comment.  Thanks!

I'll check that today.

**Comment by marmistrz** [comment]
I wasn't able to reproduce it when talking with an iOS user. I'll reopen this if it reappears. Thanks!
