### ISSUE TITLE
"use sip account" assistant fails silently with a * in username field

### ISSUE THREAD

**Issue by wrhite** [BelledonneCommunications/linphone-android#1100]
Linphone downloaded from the google Play store for my Samsung s10 5g running Android 10. Linphone android 4.3.0 (release) with SDK 4.4.0 (tags/4.4.0^0)

The login button when creating a sip account does nothing.

I have just discovered the login button does work if I change my username. I discovered this in my frustration of entering all the complicated login details so just put in aa for all the fields as a test. It attempted to connect on pressing login button...

My username should be 1884*005 for my voip supplier.

With the * it apparently does nothing. Take out the * and it it tries to connect but of course cannot as it is the wrong user name.

It does create the sip account though.

So I edited that by clicking on it, put the * back and corrected the username auth field too and it all works fine.

So there is a small problem on the "assistant/use sip account" screen upset by a * character in the username or something. Otherwise all is well. Thanks

**Comment by ProjectMoon** [comment]
This also happens with a `~` in the username.

**Comment by andrewliles** [comment]
The defect occurs somewhere around 146 here:
https://github.com/BelledonneCommunications/linphone-android/blob/7f9ef53039e245e35a293002cbd897e546091755/app/src/main/java/org/linphone/assistant/AssistantActivity.java#L146

The proxy is not created where there is `*`/`~` or some other special character in the username, and so at line 168 it logs an error, but doesn't alert the user.
https://github.com/BelledonneCommunications/linphone-android/blob/7f9ef53039e245e35a293002cbd897e546091755/app/src/main/java/org/linphone/assistant/AssistantActivity.java#L168

I cannot see why the proxy would not get created - parameter passing happens in a way not obvious to me

**Comment by truist85** [comment]
I have a "~" in my user name and I am experiencing the same problem. Is there someway around this?

**Comment by truist85** [comment]
Related... https://wiki.soprani.ca/FAQ/Why%20won%27t%20linphone%20accept%20my%20credentials%3F

**Comment by axel-mulder** [comment]
When the username contains an underscore ("_") it disappears upon exiting the username field. Subsequent registration then fails.

**Comment by Viish** [comment]
> When the username contains an underscore ("_") it disappears upon exiting the username field.

I don't reproduce it with latest (4.5.3) release.

And now `*` and `~` are forbidden in assistant, so no longer an issue.

**Comment by Viish** [comment]
Enable debug logs, restart app, reproduce issue and send logs please.

**Comment by axel-mulder** [comment]
https://www.linphone.org:444//tmp/623dd41b02b9b_9a650bcf7dcfa56c5575.gz

**Comment by Viish** [comment]
Thanks.
Seems it your VOIP provider issue:
```
2022-03-25 10:38:27:513 [org.linphone/belle-sip] MESSAGE channel [0x7295f3b040]: received [441] new bytes from [TLS://montreal3.voip.ms:5061]:
SIP/2.0 403 Forbidden
Via: SIP/2.0/TLS 10.0.0.157:49859;alias;branch=z9hG4bK.5DUuP3EbX;received=179.53.181.90;rport=49859
From: <sip:184486_8072429e@montreal3.voip.ms>;tag=90ztAowmG
To: sip:184486_8072429e@montreal3.voip.ms;tag=as1576f173
Call-ID: BRNG4LlT3d
CSeq: 21 REGISTER
Server: voip.ms
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Content-Length: 0
```
If password was wrong you would have received a 401 Unauthorized.
You should contact them to know why the 403.

**Comment by axel-mulder** [comment]
Ok I will check. Would you mind deleting above message since it contains account info ?

**Comment by Viish** [comment]
Done

**Comment by axel-mulder** [comment]
Thanks for your help, the voip provider fixed the issue.
