### ISSUE TITLE
Stuck on "Outging call in progress" status with video call initiating, although video packages are sending from the server

### ISSUE THREAD

**Issue by hotmule** [BelledonneCommunications/linphone-android#1101]
[calling.log](https://github.com/BelledonneCommunications/linphone-android/files/4942331/calling.log)

**Comment by hotmule** [comment]
Also, with video call initiated client don't send "Authorization" header and server responses with 401 error

**Comment by Viish** [comment]
Your problem is you are using UDP as transport but the INVITE packet is too big so it's never received by your server.
You should switch to TCP or even better TLS: https://wiki.linphone.org/xwiki/wiki/public/view/Linphone/Good%20practices%20for%20using%20SIP/

**Comment by hotmule** [comment]
But I don't have problem with official Linphone client, it is something with core settings in my app, but I don't understand what exactly

**Comment by Viish** [comment]
With the same asterisk server and using UDP as well?

**Comment by hotmule** [comment]
Yeah, tried to set settings as in your client, but without success

**Comment by hotmule** [comment]
Looks like I found the reason, I set needed codecs like
`videoPayloadTypes = arrayOf(videoPayloadTypes?.find { it.mimeType == "H264" })
audioPayloadTypes = arrayOf(audioPayloadTypes?.find { it.mimeType == "PCMA" })`
And now as
`audioPayloadTypes = audioPayloadTypes.apply {
                    this.forEach {
                        if (it.mimeType == "PCMA")
                            it.enable(true)
                        else
                            it.enable(false)
                    }
                }

                videoPayloadTypes = videoPayloadTypes.apply {
                    this.forEach {
                        if (it.mimeType == "H264")
                            it.enable(true)
                        else
                            it.enable(false)
                    }
                }`
Seems like call now works, but video is not displayed
