### ISSUE TITLE
Broadcast sip uri -Call Group ----->flexisip-warning-error while reading the static record file  (Invalid line syntax )

### ISSUE THREAD

**Issue by maxberson** [BelledonneCommunications/linphone-android#1102]
Hi, I want to make a group call or broadcast sip uri  (caller:180--->callee:182,183) .
so i tried to define a static route in /etc/flexisip/flexisip.conf

[module::Registrar]
static-records-file=/etc/flexisip/routes.conf

--------------------
routes.conf
sip:180@192.168.1.9:6060 sip:182@192.168.1.4:6060, sip:183@192.168.1.3:6060
------------------
i got this error:
      flexisip-warning-error while reading the static record file [/etc/flexisip/routes.conf:1
sip:180@192.168.1.9:6060 sip:182@192.168.1.4:6060, sip:183@192.168.1.3:6060;: invalid line syntax
----------------
Also i wrote like this topic (Call Group ) in flexisip issue category but nobody answered ,

what is correct syntax or prototype for this section?

**Comment by Viish** [comment]
Please open this issue in flexisip repository.

**Comment by Viish** [comment]
Anyway you should check this: https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/A.%20Configuration%20Reference%20Guide/2.0.0/module/Registrar
