### ISSUE TITLE
sound stuck

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1105]
Hi,

When one side speaks, the other side also says at the same time. The sound on both sides is like being stuck, intermittent. How to adjust this?

thanks.

**Comment by fengqz627** [comment]
I have tested that if side A talks first and side B continues to speak, then side A can hear the voice of side B, but it is very small. At the moment of B talking, the voice suddenly seems to be broken, and side B seems not to hear the voice of A. compared with our mobile phone conversation, when both sides talk at the same time, the sound size is the same

**Comment by Viish** [comment]
Hi,
This is not something done by our SDK. That might be a device issue or a server issue.
