### ISSUE TITLE
linphone does not connect to sipgate account

### ISSUE THREAD

**Issue by tobigehrmann** [BelledonneCommunications/linphone-android#1108]
Using latest linphone (4.2.3) from F-Droid on a HTC U11 plus with Android 9.

I haven't used the the VoIP for a while. The last working call I could verify happened 2020/06/29 and that the connection from linphone to sipgate could not be established must last for at least 3-4 days.

Appending a debug log from a connection attempt today.

Configuring the sipgate account in my router does work and was successfully verified.

[5f180ab04c598_49203b2150d80376d90f.gz](https://github.com/BelledonneCommunications/linphone-android/files/4959418/5f180ab04c598_49203b2150d80376d90f.gz)

**Comment by Viish** [comment]
It's because you are using UDP as transport protocol.
There are a lot of retransmission which means your packets gets lost. Switch to TCP or TLS.

**Comment by tobigehrmann** [comment]
Hi,

Neither TCP nor TLS does connect. Same like UDP. I could provide logs but from what I see it's not much more than timeouts indicated.

I'm running out of options here. Could this be related to DS-Lite? I'm not sure when I haven't been provided with an IPv4 address anymore. Could very well be that it was this way from the beginning. From what I know both the Fritz!Box and sipgate do speak native IPv6 and that probably could make the difference to why the router actually can connect to the account.

Best regards,

Tobi

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Viish** [comment]
Sorry but I don't have knowledge of either sipgate nor Fritzbox. All I can do is interpret logs.
