### ISSUE TITLE
Sound issue on Android 5.1.1

### ISSUE THREAD

**Issue by Jorpheus7** [BelledonneCommunications/linphone-android#1109]
Hello,
We are experiencing a sound problem using Linphone, with a very distorted and accelerated sound, like a chipmunk voice (I extracted a recording from Linphone and attached it to the issue : [linphone_sample.zip](https://github.com/BelledonneCommunications/linphone-android/files/4960954/linphone_sample.zip)).

The problem appears when the sound comes from our **Android v5.1.1 device (API 22)**. The sound arriving to this device is ok, and can be heard clearly, but the sound emitted by this device has the issue. When calling an identical device, the issue is on both ends.

We tried using a prepackaged APK from official website, or by running (from Android studio) Linphone project, or linphone sample app, and we have the issue each time (we are using v4.3.0 of Linphone project, as API 22 is not supported since v4.4)

The log file can be found here : https://www.linphone.org:444//tmp/5f1858697f2b2_e1485af090efd79b2d7b.gz

We have been struggling with this issue for 2 days now, and have tested everything that crossed our minds (tested all available codecs, with/without echo cancellation, etc.). Is it a known issue on your side? Do you know a workaround that we could use to have a clear sound?

Thanks in advance!

**Comment by Jorpheus7** [comment]
To help identify the issue, we noticed that when a bluetooth headset is enabled at the beginning of the call, then we switch back to our device audio **during the call** (and even turn of the bluetooth headset), the sound is OK both ways. But as soon as we hangup the call and start a new one, the sound issue is back.

I hope it helps!

**Comment by Viish** [comment]
Hi,
Try to add the following code right after you created your Core :
`core.mediastreamerFactory.setDeviceInfo("UBTECH", "cruiser", "rk3288", org.linphone.mediastream.Factory.DEVICE_USE_ANDROID_CAMCORDER, 0, 16000)`
Then start a call and if the issue persists please send new logs.

**Comment by Jorpheus7** [comment]
Hi, thanks a lot for your quick reply!
I tried to add the code, so now I still have this:
`mCore = Factory.instance().createCore(mPrefs.getLinphoneDefaultConfig(), mPrefs.getLinphoneFactoryConfig(), mContext);`
and right after:
`mCore.getMediastreamerFactory().setDeviceInfo("UBTECH", "cruiser", "rk3288", org.linphone.mediastream.Factory.DEVICE_USE_ANDROID_CAMCORDER, 0, 16000);`

I still have the sound issue during the call. The log file is here : [https://www.linphone.org:444//tmp/5f1965cfbf762_a8a5e15aa058f431f1a1.gz](https://www.linphone.org:444//tmp/5f1965cfbf762_a8a5e15aa058f431f1a1.gz)

Also, would it help to have a log of the weird case mentioned in the first comment? _(ie when we start the call with a Bluetooth headset and then disconnect the bluetooth headset during the call, and then we have a normal sound both ways even without the headset)_

**Comment by Viish** [comment]
> Also, would it help to have a log of the weird case mentioned in the first comment? (ie when we start the call with a Bluetooth headset and then disconnect the bluetooth headset during the call, and then we have a normal sound both ways even without the headset)

Yes please, that can't hurt.

**Comment by Jorpheus7** [comment]
Okay then, here is the log : [https://www.linphone.org:444//tmp/5f197d346b145_48409d8e7127353ade36.gz](https://www.linphone.org:444//tmp/5f197d346b145_48409d8e7127353ade36.gz)

The scenario here was:

- Had a BT headset paired and connected
- Started Linphone, started a call, **sound OK both ways**, but recorded from headset
- During call, switch from BT to Speaker _(and turn off the headset to be sure)_
- **Sound OK both ways**
- Hang up call

**Comment by Viish** [comment]
Doesn't help much...
Please try to add (instead of previous one):
`core.mediastreamerFactory.setDeviceInfo("UBTECH", "cruiser", "rk3288",  org.linphone.mediastream.Factory.DEVICE_HAS_BUILTIN_AEC, 0, 0)`

**Comment by Jorpheus7** [comment]
I changed the line, and I still have the issue.

Here is the log : [https://www.linphone.org:444//tmp/5f198ae539df9_d1b6413fbc7dab2ed3a0.gz](https://www.linphone.org:444//tmp/5f198ae539df9_d1b6413fbc7dab2ed3a0.gz)

**Comment by Viish** [comment]
My bad, I forgot to ask to to call core.reloadSoundDevices after the setDeviceInfo.

**Comment by Jorpheus7** [comment]
Yes, that did the trick! I retried with the line you wrote in your first comment, and we have a clear sound. 

Thanks a lot, we were quite struggling with this one!

**Comment by Viish** [comment]
> I retried with the line you wrote in your first comment

The `DEVICE_HAS_BUILTIN_AEC` or `DEVICE_USE_ANDROID_CAMCORDER` hack did the trick ?

**Comment by Jorpheus7** [comment]
The DEVICE_USE_ANDROID_CAMCORDER + reloadSoundDevices. But I can also retry with DEVICE_HAS_BUILTIN_AEC if it helps for next time.

**Comment by Jorpheus7** [comment]
Well, using the `DEVICE_HAS_BUILTIN_AEC` + `reloadSoundDevices` line worked too ;)

**Comment by Viish** [comment]
Good to know, thanks.
