### ISSUE TITLE
Differences in several definitions

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1110]
Hi,
What are the functions and differences of the following definitions? How do we adjust them?
el_type
el_speed
el_thres
el_force
el_sustain
el_transmit_thres
echolimiter

Besides， I see el_type is "mic" by default. Would it be better if it was set to "Full"?

thanks.

**Comment by fengqz627** [comment]
I'm sorry. There are a few more：
noisegate
ng_thres
ng_floorgain
mic_ng_thres
ng_sustain
tone_indications

**Comment by Viish** [comment]
Please open this ticket on linphone-sdk or liblinphone repository.
