### ISSUE TITLE
audio question

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1113]
HI,
 During a call, there is an occasional “GALA” sound, which will cover up the normal call，Each "GALA" sound lasts about one second. It's not regular. I don't know where the "Gala" came from.

thanks.

**Comment by fengqz627** [comment]
I try to turn off the MIC of the receiver, and the "Gala" sound is gone, which means that the "Gala" sound is caused by echo or duplex, isn't it? How to solve it?

**Comment by Viish** [comment]
I don't know what a "Gala" sound is.
