### ISSUE TITLE
Registration stuck in "Progress"

### ISSUE THREAD

**Issue by mihabogataj-eurotronik** [BelledonneCommunications/linphone-android#1115]
When I start Linphone Service and register the account, it gets stuck in "Progress". I get that by calling `LinphoneManager.getCore().getDefaultProxyConfig().getState()`

I use Linphone SDK 4.4.0.
What could I check that would give me more information about it?

**Comment by Viish** [comment]
Hi,

Did you start the core using core.start()?

Cheers,

**Comment by mihabogataj-eurotronik** [comment]
Yes, core is started. I know that because right before that line I retrieve proxy config list, which require core started (otherwise you get a null pointer).

**Comment by Viish** [comment]
Ok, do you call core.iterate() method every 20ms (or so) on the main thread?

**Comment by mihabogataj-eurotronik** [comment]
Yes I do.
`mCore.start();

            mIterateRunnable =
                    () -> {
                        if (mCore != null) {
                            mCore.iterate();
                        }
                    };
            TimerTask lTask =
                    new TimerTask() {
                        @Override
                        public void run() {
                            LinphoneUtils.dispatchOnUIThread(mIterateRunnable);
                        }
                    };
            /*use schedule instead of scheduleAtFixedRate to avoid iterate from being call in burst after cpu wake up*/
            mTimer = new Timer("Linphone scheduler");
            mTimer.schedule(lTask, 0, 20);`

**Comment by mihabogataj-eurotronik** [comment]
The issue was that I sent the request to the wrong port. However I am not sure why it kept saying "Progress", but that should solve the issue. It would probably be better if it said "Error" or "Timeout" or something like this.
