### ISSUE TITLE
Missed calls shown as incoming calls 

### ISSUE THREAD

**Issue by julhamptons** [BelledonneCommunications/linphone-android#1116]
Hi,

When I have a GSM call on my device and someone tries to call me via Linphone, the caller gets "user busy". However I don't have a missed call notification. When I launch the Linphone app, I notice that the call is marked as an incoming call. Why does this happen eventhough I never receive the call and the caller gets "user busy"?

Thanks.

**Comment by Viish** [comment]
Hi,

It's actually a behavior of the app itself, not the Sdk.
We have decided to decline any incoming call while there is a GSM call, so the call is not missed but declined with a reason busy.
Feel free to change that in your fork.

Cheers,
