### ISSUE TITLE
After the Registration to the Server ,calling activity is not generating sip INVITE with custom headers with multipart body content.

### ISSUE THREAD

**Issue by nick2601** [BelledonneCommunications/linphone-android#1118]
I was using Linphone Android 4.3.0 and SDK 4.4.1,the calling was working fine but when I upgraded the linphone source code and SDK to the latest release,My call is not generating a SIP INVITE event ,even after successful registration to server.

**Comment by Viish** [comment]
4.3.0 is the latest app release and 4.4.1 is the latest SDK release, so what upgrade did you perform?

**Comment by nick2601** [comment]
> 4.3.0 is the latest app release and 4.4.1 is the latest SDK release, so what upgrade did you perform?

![Screenshot_20200811-144448](https://user-images.githubusercontent.com/59530213/89880309-b50eec00-dbe1-11ea-9795-74bfae89be76.png)

**Comment by Viish** [comment]
Ok so you are on master branch.
I recommend you to stick to the releases for now, there are a lot of ongoing chances on master branch and it's not finished or stable yet.
