### ISSUE TITLE
CMake Error No download info given for 'EP_ortp' 

### ISSUE THREAD

**Issue by aryeharmon** [BelledonneCommunications/linphone-android#112]
CMake Error at /opt/cmake-3.9.1-Linux-x86_64/share/cmake-3.9/Modules/ExternalProject.cmake:2010 (message):
  No download info given for 'EP_ortp' and its source directory:

**Comment by DatBewar** [comment]
Hello, there are possibly a problem with Cmake 3.9.1.
Can you try with an older version of Cmake?

**Comment by aryeharmon** [comment]
I tried with multiple versions.
This issue in the end was some submodules did not install. That there was a submodule with submodules that did not install. This fixed it

**Comment by limlab** [comment]
The same problem for me.
CMake Error at /usr/local/Cellar/cmake/3.7.1/share/cmake/Modules/ExternalProject.cmake:1976 (message):
  No download info given for 'EP_ortp' and its source directory
CMake Error at /usr/local/Cellar/cmake/3.7.1/share/cmake/Modules/ExternalProject.cmake:1976 (message):
  No download info given for 'EP_ms2' and its source directory:

   /Users/glagoliev/Documents/Work/linphone-iphone_old/submodules/mediastreamer2
