### ISSUE TITLE
Linphone Android registration issue using UDP

### ISSUE THREAD

**Issue by amazaccou** [BelledonneCommunications/linphone-android#1123]
I am facing a Linphone app registration issue with Redmi Note 7S running on Android 9 and Poco F1 running on Android 10
, Linphone App is not registering with the Asterisk server. On wireshark I could see the destination port unreachable packet transmitted from the phone. The same code works perfectly on other phones. 

Linphone App installed from play store is working perfectly on these phones. But when I build using android studio app is not registering.

In order to debug the issue I installed the pcap remote on the mobile, when i enable the pcap app Linphone sample app is correctly registering. when I disable the Linphone sample app its not registering.

Attached the core logs 
[linphone_register _with_pacp_remote.log](https://github.com/BelledonneCommunications/linphone-android/files/5068367/linphone_register._with_pacp_remote.log)

[linphone_not_register.log](https://github.com/BelledonneCommunications/linphone-android/files/5068366/linphone_not_register.log)

**Comment by amazaccou** [comment]
Linphone App installed from play store is working perfectly on these phones. But when I build using android studio app is  not registering.

**Comment by Viish** [comment]
You are using UDP as transport protocol. UDP packets can get lost. I recommend you to switch to TCP or even better TLS.
Also the difference between your 2 REGISTER packets is the VIA with IP 10.1.10.1 in the scenario that works.
Check your server settings or your proxy config setting, probably something missing in the network area.

**Comment by amazaccou** [comment]
Hi Viish
Thank you for the reply.
I am testing it in a closed private network, there is no chance of packet loss and this error is only for the Redmi 7s and Oppo. I have used same server settings / proxy config setting for connecting to asterisk server. It is only failing on this two devices.
