### ISSUE TITLE
Push notification not received if app killed from background (Swipe to kill)

### ISSUE THREAD

**Issue by JitainSharma** [BelledonneCommunications/linphone-android#1124]
linphone SDK: 4.3.3 & 4.4.0
OS: Android 9 & 10

When app is swipe to kill or Clear All option is selected to kill all apps in background the INVITE push notification is never received on that device when making call from another device.

Is there something we send to the server when app killed or it's unregistered from the push?

Please help to resolve this issue.

**Comment by Viish** [comment]
Hi,
There is many possibilities. Please attach logs showing the issue please.
The most probable is you unregister your device when the app is killed. Unregistered devices don't get push notifications.
Cheers,

**Comment by JitainSharma** [comment]
Is there a way to prevent the Unregistration, so that the device will be able to get push notifications even in killed state?

**Comment by Viish** [comment]
Yes, just configure the proxy config to have push_allowed set to true (SDK 4.4 only). You can also set the network reachability in the core to 0.

**Comment by JitainSharma** [comment]
In SDK 4.3.3 `core.isNetworkReachable = false`  is set, not found any other method for setting 0. Also, `proxyConfig.isPushNotificationAllowed = true` is set as well.

As you said SDK 4.4 only, that's means this issue is on 4.3.3, and switching to 4.4 with proxy config to have push_allowed set to true will resolve it?


Below is the log file (with SDK 4.3.3), no push received after swipe to kill.

[log.txt](https://github.com/BelledonneCommunications/linphone-android/files/5075056/log.txt)

**Comment by Viish** [comment]
From your logs that's not the issue.
However I don't know how openSIPS handles push notification so maybe you have an issue with the parameters in your Contact header.
Also with an Expires value of 1 day, you won't be able to receive push after this delay. I recommend 1 year instead.
From the app everything is OK.
