### ISSUE TITLE
 push notifications in Asterisk 

### ISSUE THREAD

**Issue by lada2308** [BelledonneCommunications/linphone-android#1127]
there is a gotcha with using Linphone with push notifications in Asterisk (older versions anyhow. I’m using 11). Since the Linphone code sends the pn-tok with other tags in the contact line, it ends up being over a 255 byte character limit. This will cause an inbound call to fail to linphone since the ACK will be sending a truncated contact field out which will be invalid and cause a loss of connection 30 seconds in. It is necessary to change the Linphone code to remove unnecessary pn-type and pn-silent tags from the contact line in order to reduce the limitation of 255 bytes. Where in the linfone-android sources cut this information. Thank.

**Comment by Viish** [comment]
Currently it's set here: https://github.com/BelledonneCommunications/linphone-android/blob/master/app/src/main/java/org/linphone/settings/LinphonePreferences.java#L739
Starting next version it will be in the SDK here: https://github.com/BelledonneCommunications/liblinphone/blob/master/coreapi/linphonecore.c#L2609
I think the best solution would be to open an issue in Asterisk to remove this 255 bytes limit for the Contact header as it clearly is a bug from their side.

**Comment by lada2308** [comment]
i commented out the lines in LinphonePreferences.java#L739
String contactInfos =
                                "app-id ="
                                        // + appId
                                        // + "; pn-type ="
                                        // +
                                        // getString (R.string.push_type)
                                        // + "; pn-timeout = 0"
                                        + "pn-tok =";
                        // + regId
                        // + "; pn-silent = 1";
I rebuilt the project, but in Asterisk still this information:; pn-provider = fcm; pn-param = 205996813040; pn-prid = cCqnphyipks: APA91bHnh7o8CA97Pc9JgpkM1_xYOB5oEFFqG_Rto2OaQnB4RSh-Iz8sNOx9M6mGtKfohrpv6Ib15LE1dNG4KnNfy-YBofmQkwxUp3DX4EVJXXhR3zUrJ2QJe4w-xniNEIeTRlYtdxUI; pn-timeout = 0; pn-silent = 1

**Comment by Viish** [comment]
Yes, the proxy config has already been configured with this.
Either uninstall / reinstall the app or do some code to remove the contact uri params from your proxy config.

**Comment by lada2308** [comment]
i commented out String contactInfos =
                                 "app-id ="
                                         // + appId
                                         // + "; pn-type ="
                                         // +
                                         // getString (R.string.push_type)
                                         // + "; pn-timeout = 0"
                                         + "pn-tok =";
                         // + regId
                         // + "; pn-silent = 1";
I rebuilt the app. Reinstalled the app on a physical device. But the parameters have not changed.

**Comment by Viish** [comment]
What version of the SDK do you use?

**Comment by Viish** [comment]
Ah also if you have reinstalled the app, the unique id of your device has changed.
So it's normal in Asterisk you still see the previous device with the push params, but you should also see another device without it.

**Comment by lada2308** [comment]
![image](https://user-images.githubusercontent.com/62254504/90377507-bd06da00-e080-11ea-8ff8-2e8e97791b0a.png)

**Comment by Viish** [comment]
Not Android SDK, Linphone SDK.

**Comment by lada2308** [comment]
4.5.0-alpha.35

**Comment by Viish** [comment]
Ok so as I said above, next SDK (4.5 which is in alpha state) does the Contact Uri params. Use 4.4 release instead.

**Comment by lada2308** [comment]
I understood everything. Thank you. The topic is still closed
