### ISSUE TITLE
account stop working after change username

### ISSUE THREAD

**Issue by wkg** [BelledonneCommunications/linphone-android#1128]
If in exists account change username - it stop working, to fix need delete and create new.

**Comment by Viish** [comment]
I think you forgot to also re-enter your password, am I right?

**Comment by wkg** [comment]
Yes, but this is not obvious, it is necessary that the password is immediately cleared when the username changes ...

**Comment by Viish** [comment]
We don't store the password in plain text, only ithe result of the hash that is made from the username, which means that if the username changes the hashed password must be recomputed.
