### ISSUE TITLE
Push not working after linphone was killed (crash?).

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-android#113]
I've configured Linphone for Android to work with Firebase and most of the time it's working great. 

However, sometimes the Linphone service was killed (possible crash?). Afterwards, Linphone won't wake up by Push even though I'm sending "force-start: 1". Is this something that can be implemented?

> GCM-DMM : broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=org.linphone (has extras) }

**Comment by zgmunshi** [comment]
Hi  @driesken ,

Can you please tell me how did you configured linphone to work with firebase as i tried setting up firebase and got the token too but whenever is call is made no notification or call is received.

Would be great if you could let me know how to make the push work in linphone for incoming calls.

Thanks.

**Comment by driesken** [comment]
Hi @zgmunshi 

I did the following:

- Go to the firebase console (https://console.firebase.google.com/) and request a token for your project. Download the google-services.json and place it in the root of your project (where AndroidManifest.xml is)
- Afterwards, modify the "_push_sender_id_" in "_res/values/non_localizable_custom.xml_". You can find the required value under the "Cloud Message" tab within your Firebase Project Settings.
- Recompile project

Afterwards, you can try to send a payload using the "Notifications" option within Firebase, or use the following curl command:
_curl -X POST --header "Authorization: key=<API_ACCESS_KEY>" --Header "Content-Type: application/json" https://fcm.googleapis.com/fcm/send -d "{\"to\":\"<YOUR_DEVICE_ID_TOKEN>\",\"notification\":{\"body\":\"Testmessage.\"},\"priority\":10}"_

I've configured Asterisk (my PBX) to just send the following which wakes the device:
_curl -X POST --header "Authorization: key=<API_ACCESS_KEY>" --Header "Content-Type: application/json" https://fcm.googleapis.com/fcm/send -d "{\"to\":\"<YOUR_DEVICE_ID_TOKEN>\",\"priority\":\"high\"}"_

**Comment by zgmunshi** [comment]
Thanks @driesken ,
I already did till putting the details in non_localizable_custom.xml but curl part was missing, will  try it out & let you know

**Comment by zgmunshi** [comment]
Here is the scenario, i pushed notification from firebase its coming but its not making up the call.

App is killed & other device is calling ,at that time i fired up the notification through firebase, notification received but still incoming call not showing.

Where i am doing wrong ? any hint ?

**Comment by driesken** [comment]
The notification itself doesn't initiate an incoming call, it only wakes the device.

Linphone cannot be killed on Android (meaning that the service must remain active). It can be swiped away from the "recent applications" within Android though.

When you have Linphone in foreground, does the call then work properly?

**Comment by zgmunshi** [comment]
Yes it does work if app in foreground,It also works if i prevent linphone service from self killing on closing the app by setting "kill_service_with_task_manager" parameter to false in "non_localizable_custom.xml"

But if background service is disabled and app is killed no call is received, i was wondering how that push one works then ?

**Comment by driesken** [comment]
If Linphone was killed (for example "Force Stop" in the Android's App Settings, the push won't (unfortunately) start it again. This was addressed in my first post but unfortunately no solution yet.

**Comment by zgmunshi** [comment]
ohkk got it,thanks

What about ios then ? Any idea ?

**Comment by driesken** [comment]
In iOS it works perfect, you can swipe away - and thus kill - Linphone. When push is received, you can see the device start answering to ping and eventually receive the incoming call.

**Comment by zgmunshi** [comment]
ok,so you mean just a simple push to ios will wakeup and show the incoming call right ?

**Comment by driesken** [comment]
That's correct. After push, the incoming call will show up after a few seconds (because Linphone needs to register first).

**Comment by zgmunshi** [comment]
ok Thanks a lot @driesken

**Comment by zgmunshi** [comment]
@driesken 
Just an update you can receive the call even if the app is killed and service is also not there lying in the notification center.

What you just need to do is send 'data message' instead of 'notification message',it wakes up the devices and resumes the app with incoming call.

I tried it and its working.

**Comment by driesken** [comment]
I tried to send one of those (replaced "notification" with "data") but it doesn't start Linphone if it's force killed. I have "background mode" disabled in Linphone's Advanced Settings.

What Android version are you running?

**Comment by zgmunshi** [comment]
Yes my background mode is also disabled but i am receiving the calls once changed to 'data'.

I am testing it on 'Android M - 6.0.1'

**Comment by driesken** [comment]
Okay, thanks @zgmunshi . Must be something device specific then.

**Comment by zgmunshi** [comment]
@driesken In what format push notification to be send to IOS,any idea on this?

**Comment by driesken** [comment]
@zgmunshi For iOS, I just send an empty aps{}. Seems to wake up the device just fine. I've noticed that sending a notification with IC_MSG sometimes get delayed.

You can lock the iPhone during a pingsession. When it stops responding to ping, send the push with an empty aps{} and you can see the device responding to ping after a while.

**Comment by ravi-nimavat128** [comment]
The notification itself doesn't initiate an incoming call, it can't wakes the device.

When i make call each time show notification user not found.
Thanks.

**Comment by zgmunshi** [comment]
@ravi-nimavat128 Please open up a new ticket explaining what you did and what issue you are facing in order to get any help

**Comment by pergolafabio** [comment]
Guys, one thing is not not clear to me, how do you retrieve the token from the android device?

thnx in advance

**Comment by driesken** [comment]
> Guys, one thing is not not clear to me, how do you retrieve the token from the android device?
> 
> thnx in advance

You can see this in the contact URI when Linphone registers (pn-prid=....).

**Comment by pergolafabio** [comment]
ah, is there another way also to see it? maybe in logcat ?
Because my linphones client are registered on the free flexisip service, and in asterisk, i have setup an flexisip account as a trunk
so my outbound calls from asterisk to linphone users, are using the trunk ... i have not registered the linphone clients to my asterisk...
i have done this approach, so i dont need any port forwarding to my asterisk server , all is safe then

**Comment by pergolafabio** [comment]
hey @driesken , i have found the token
But also struggling now with the API key
what do you choose there? because i get mismatchsender ID? seems a lot of stuff is deprecated

i enabled the "legacy' , but that api key doesnt work :-)

![image](https://user-images.githubusercontent.com/43251136/173525102-387eaf67-c8cf-43ee-9d64-8cd00af10d46.png)

**Comment by pergolafabio** [comment]
i also see an api key in the google-services.json file, maybe i need to use that one?

**Comment by pergolafabio** [comment]
nm, seems i had to do a rebuild project, after changing the json file, seems it was still using the old one :-)

**Comment by pergolafabio** [comment]
@driesken  , just one more question, what is the final command you are now using in asterisk? 

`curl -X POST --header "Authorization: key=xxx" --Header "Content-Type: application/json"  -d '{"to":"xxx","priority":"high"}' https://fcm.googleapis.com/fcm/send`

I'm using now above, i see the the PUSH message being received succes in logcat, but you said , it should wake the device? what do you mean by that? Does your device turn on screen? Or does it wake up the linphone app , to make it register in background?

also, are you also using a script in your dialplan, to check if the device is registered, and then start dialing?

I also found this one:
https://github.com/brianjmurrell/Android-push-for-Asterisk/blob/master/push.sh
