### ISSUE TITLE
Activate, Deactivate account 

### ISSUE THREAD

**Issue by lada2308** [BelledonneCommunications/linphone-android#1130]
Hello, can you please tell me if there is any optimal way that activates and deactivates an account at any event (to save battery). Perhaps by means of PUSH or is there some kind of API? Tell me in which direction to go. thank.

**Comment by Viish** [comment]
Hi,
If you use a sip.linphone.org account push are already enabled. You can kill the app at any time and still receive calls & messages.
If you use another provider you will have to fork the app to configure it with the push information of your server.
Cheers,

**Comment by lada2308** [comment]
I have already configured push notifications from my firebase account in the application. The question is, can I manage my account with push notifications (activate deactivate)

**Comment by Viish** [comment]
Sorry but I don't understand what you want to do. Can you be more explicit?

**Comment by lada2308** [comment]
I have a linphone application built with SDK. I have configured push notifications from the firebase server. Everything works great. Only with an active SIP account the battery will drain quickly. To disable and enable an account, I use third-party plugins and taskers, which activate the account when a notification is received. I suspect your application has this already implemented, without different plugins.

**Comment by Viish** [comment]
No we don't have that.
Android already kills or stops the app when in background for more than a few minutes, so the app doesn't drain the battery.
When a push is received, the app is waked up or starts from scratch.
And even when the app is in foreground, it doesn't consume much battery if you don't make/receive calls/chat messages.

**Comment by lada2308** [comment]
thank. I'll try another way. Are there any console commands that activate or deactivate a specific account?

**Comment by Viish** [comment]
I don't know what you mean by "console commands" but given a ProxyConfig object you can enable/disable it's registration process to the server (which is the closest to activate/deactive an account).
