### ISSUE TITLE
playbackgain

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1131]
Hi,
When I was there “Call.State.Connected" Or "Call.State.StreamsRunning" When setting the playbackgain, I find that sometimes it doesn't work.

thanks.

**Comment by Viish** [comment]
Hi,
Yes it's too late, graph is already created.
Gain is a setting that once changed takes effect at next call.

**Comment by fengqz627** [comment]
Hi,
It's too late, But if I change playbackgain in  “Call.State.Connected", and then add setReinviteWithAudio in "Call.State.StreamsRunning", will the changed playback gain be effective?

thanks.
