### ISSUE TITLE
Compatibility Issues

### ISSUE THREAD

**Issue by john2020star** [BelledonneCommunications/linphone-android#1132]
Hi,

I found there are compatibility issues at chat_bubble.xml, wait_layout.xml. 
<ProgressBar
  android:indeterminate="true"
  android:indeterminateTint="?accentColor"
  android:layout_centerInParent="true"
  android:layout_height="wrap_content"
  android:layout_width="wrap_content"
 />
The indeterminateTint should be with indeterminateTintMode, otherwise the color will not be applied in API Level 22

**Comment by Viish** [comment]
Hi,
Indeed but our app is designed to work on API levels 23 and higher, so not 22: https://github.com/BelledonneCommunications/linphone-android/blob/master/app/build.gradle#L82
Cheers,
