### ISSUE TITLE
default values

### ISSUE THREAD

**Issue by lada2308** [BelledonneCommunications/linphone-android#1133]
Hello. help me find where the default values of all settings are stored?

**Comment by Viish** [comment]
Hi,
App settings are handled by this class: https://github.com/BelledonneCommunications/linphone-android/blob/master/app/src/main/java/org/linphone/settings/LinphonePreferences.java
SDK settings default values are dispersed across https://github.com/BelledonneCommunications/liblinphone files.
Cheers,
