### ISSUE TITLE
create account not working

### ISSUE THREAD

**Issue by alexzh16** [BelledonneCommunications/linphone-android#114]
Hi,

with last version linphone from git, not working create new account from Assistant. All time become error: MissingArguments.

can you fix?

**Comment by alexzh16** [comment]
<img width="334" alt="snimek obrazovky 2017-09-04 v 14 55 54" src="https://user-images.githubusercontent.com/13469808/30027425-3f017c2e-9181-11e7-8db9-61636beb43ea.png">

**Comment by DatBewar** [comment]
On which version? Did you have any logs?

**Comment by alexzh16** [comment]
sorry, but i deleted all. now i downloading last build from git. But, i checking all versions from dates 05.2017 to 09.2017 and all version have same mistake. in log files comping from server xml witch (ok) after send to server query, and after that, linphone not correct send to C code and become from C - only Fail.

**Comment by alexzh16** [comment]
but now, git version from yesterday:
10-11 10:44:11.387 3234-3234/org.linphone I/Linphone: channel [0xe3d3e000]: message sent to [TLS://subscribe.linphone.org:444], size: [411] bytes
                                                      POST /wizard.php HTTP/1.1
                                                      Content-Type: text/xml
                                                      Host: subscribe.linphone.org:444
                                                      Content-Length: 303
                                                      
                                                      <?xml version="1.0" encoding="UTF-8"?>
                                                      <methodCall>
                                                       <methodName>get_phone_number_for_account</methodName>
                                                       <params>
                                                        <param>
                                                         <value>
                                                          <string>+42070000000</string>
                                                         </value>
                                                        </param>
                                                        <param>
                                                         <value>
                                                          <string>sip.linphone.org</string>
                                                         </value>
                                                        </param>
                                                       </params>
                                                      </methodCall>
10-11 10:44:11.387 3234-3234/org.linphone I/Linphone: channel [0xe3d3e000]: ending send background task with id=[67e].
10-11 10:44:11.388 3234-3234/org.linphone I/Linphone: bellesip_wake_lock_release(): Android wake lock released [ref=0x67e]
10-11 10:44:11.431 3234-3234/org.linphone I/Linphone: bellesip_wake_lock_acquire(): Android wake lock acquired [ref=0x200586]
10-11 10:44:11.431 3234-3234/org.linphone I/Linphone: channel [0xe3d3e000]: starting recv background task with id=[200586].
10-11 10:44:11.431 3234-3234/org.linphone I/Linphone: channel [0xe3d3e000]: received [192] new bytes from [TLS://subscribe.linphone.org:444]:
                                                      HTTP/1.1 200 OK
                                                      Date: Wed, 11 Oct 2017 08:44:12 GMT
                                                      Server: Apache/2.2.22 (Debian)
                                                      X-Powered-By: PHP/5.4.45-0+deb7u8
                                                      Vary: Accept-Encoding
                                                      Content-Length: 185
                                                      Content-Type: text/html
10-11 10:44:11.432 3234-3234/org.linphone I/Linphone: channel [0xe3d3e000] [192] bytes parsed
10-11 10:44:11.452 3234-3234/org.linphone I/Linphone: channel [0xe3d3e000]: received [185] new bytes from [TLS://subscribe.linphone.org:444]:
                                                      <?xml version="1.0" encoding="iso-8859-1"?>
                                                      <methodResponse>
                                                      <params>
                                                       <param>
                                                        <value>
                                                         <string>ERROR_ACCOUNT_DOESNT_EXIST</string>
                                                        </value>
                                                       </param>
                                                      </params>
                                                      </methodResponse>
10-11 10:44:11.452 3234-3234/org.linphone I/Linphone: channel [0xe3d3e000] read [185] bytes of body from [subscribe.linphone.org:444]
10-11 10:44:11.465 3234-3234/org.linphone I/Linphone: channel [0xe3d3e000]: ending recv background task with id=[200586].
10-11 10:44:11.466 3234-3234/org.linphone I/Linphone: bellesip_wake_lock_release(): Android wake lock released [ref=0x200586]
10-11 10:44:11.495 3234-3257/org.linphone D/EGL_emulation: eglMakeCurrent: 0xee834d60: ver 2 0
10-11 10:44:11.537 3234-3257/org.linphone D/EGL_emulation: eglMakeCurrent: 0xee834d60: ver 2 0
10-11 10:44:16.438 3234-3234/org.linphone I/Linphone: bellesip_wake_lock_acquire(): Android wake lock acquired [ref=0x100772]
10-11 10:44:16.438 3234-3234/org.linphone I/Linphone: channel [0xe3d3e000]: starting recv background task with id=[100772].
10-11 10:44:16.438 3234-3234/org.linphone I/Linphone: channel 0xe3d3e000: state DISCONNECTED
10-11 10:44:16.439 3234-3234/org.linphone I/Linphone: channel [0xe3d3e000]: ending recv background task with id=[100772].
10-11 10:44:16.440 3234-3234/org.linphone I/Linphone: bellesip_wake_lock_release(): Android wake lock released [ref=0x100772]
10-11 10:44:16.440 3234-3234/org.linphone I/Linphone: channel [0xe3d3e000] removed from http provider.
10-11 10:44:16.442 3234-3234/org.linphone I/Linphone: Channel [0xe3d3e000] destroyed

**Comment by alexzh16** [comment]
and same a mistake. Warning with "Ok" and nothing.

**Comment by alexzh16** [comment]
?xml version="1.0" encoding="iso-8859-1"?>
                                                      <methodResponse>
                                                      <params>
                                                       <param>
                                                        <value>
                                                         <string>ERROR_ACCOUNT_DOESNT_EXIST</string>
                                                        </value>
                                                       </param>
                                                      </params>
                                                      </methodResponse>

**Comment by alexzh16** [comment]
telphonephpodddfsdf

**Comment by alexzh16** [comment]
phone number i changed in this a log.

**Comment by AdnanNeeopal** [comment]
@DatBewar how to **create account in background** in android application if I using customize server other than **sip.linphone.org** . please help thanks
