### ISSUE TITLE
notification icon is bad

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#1141]
Original:
![image](https://user-images.githubusercontent.com/14617699/91320487-4081a300-e7c6-11ea-9299-60c59d4ab101.png)
4x upscaled:
![image](https://user-images.githubusercontent.com/14617699/91320565-5e4f0800-e7c6-11ea-8a9f-c64f9fc5e1a4.png)

**Comment by Viish** [comment]
Fixed by:
```
commit 2c9c5ba125168f836586fd865a3fa936ff19b5b3 (HEAD -> feature/kotlin_rewrite, origin/feature/kotlin_rewrite)
Author: Sylvain Berfini <sylvain.berfini@belledonne-communications.com>
Date:   Wed Aug 26 17:51:03 2020 +0200
    Improved notifications + disable fullscreen mode for now, too many UI glitches
```

**Comment by 532910** [comment]
I confirm it looks nice now.
