### ISSUE TITLE
About screen contents don't scroll

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1143]
When I put a kotlin_rewrite build on my Nexus 5, the About screen is missing the Log buttons at the bottom.  But I suspect this is an issue of they are there but just not visible due to screen size.

![Screenshot](https://user-images.githubusercontent.com/559317/91593960-1697c000-e92f-11ea-9ed8-27f31b2a176c.png)

**Comment by Viish** [comment]
No it's not that.
Logs button only show up when debug mode is enabled.

**Comment by brianjmurrell** [comment]
Indeed.  I discovered yesterday that I had not enabled debug logs on this device.  Sorry for the noise.
