### ISSUE TITLE
Have to unlock screen to answer call

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1144]
To followup on #1030, on my Nexus 5 with LineageOS 17 (Android 10), I am finding I have to unlock the screen in order to answer an incoming call.

Surely this cannot be right.  Or is there a setting I am missing that allows calls to be answered without unlocking the screen?

This is on the kotlin_rewrite branch.

**Comment by Viish** [comment]
As stated in https://github.com/BelledonneCommunications/linphone-android/issues/1030#issuecomment-635187775, this can happen and there is nothing that I can do about it.

**Comment by brianjmurrell** [comment]
Why does this not affect the native dialer though?  It must be doing something that allows it to be answered without unlocking the phone, mustn't it?

**Comment by Viish** [comment]
Keep in mind that native apps have super powers other apps don't have.
I you reproduce with an app installed from the store that would be interesting.

**Comment by brianjmurrell** [comment]
Have you tried to see if the [Google Dialer](https://play.google.com/store/apps/details?id=com.google.android.dialer) suffers the same issues with having to unlock to answer incoming calls?

I would, but I don't have a phone with mobile voice service -- only data, which is why I use Linphone with my own SIP proxy.

**Comment by Viish** [comment]
Google dialer isn't a good example, as a "Google" app it most probably also has super powers...

**Comment by brianjmurrell** [comment]
Why should any app from the app store, whether written by Google or somebody else have "super powers" that no other app writer gets access to?

**Comment by Viish** [comment]
Because Google has access to some hidden APIs that common devs don't have access to.
Apps installed by the firmware have access to more permissions than any other apps so they may behave differently.
Finally some very popular apps like WhatsApp & others might be "whitelisted" by the OS and then again have a better behavior that another app.

**Comment by brianjmurrell** [comment]
How can there be "hidden APIs" in something that is open-source?

The strange thing is that this behaviour it not consistent.  There are times when I can interact with the incoming-call screen and there are times when I have to unlock my screen.

This is on LineageOS 17 (Android 10).

**Comment by Viish** [comment]
Maybe this is an issue with LineageOS that behaves differently than stock Android (even if based on it).

**Comment by brianjmurrell** [comment]
But you said [you have experienced it](https://github.com/BelledonneCommunications/linphone-android/issues/1030#issuecomment-635187775).  Were you running LineageOS when you did that?

**Comment by Viish** [comment]
No, but I only reproduced it a few times.
And for those rare cases the doc explains why.

**Comment by brianjmurrell** [comment]
Except that other apps don't seem to have the problem.  Your having experienced it proves that it's not a LineageOS-only problem.  Given that LineageOS, and, indeed, Android is an open-source project means there cannot be "hidden APIs".  Given that there are apps in the app store that (likely) don't have the same problem, it seems that something is not quite squaring.

I guess we'll just have to leave it for now, until something clarifies things in the future or somebody can come along and shed some light on it.

**Comment by zoff99** [comment]
@brianjmurrell i am having the same issues with my app (not linphone). i need to unlock the screen to see the calling screen of my app.
did you get anymore information since 2020?
this is super annoying.

**Comment by brianjmurrell** [comment]
@zoff99 no.
