### ISSUE TITLE
Receive some times "Call.State.Connected"

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1146]
Hi,

A calls B, when B pushs answer key, I find B receives some times  "Call.State.Connected", Is the linphone mechanism like this? Isn't it OK to receive this status only once。

thanks.

**Comment by fengqz627** [comment]
I find  " Dialog sending retransmission of 200Ok"  is sent in logs, When will this information be sent？

------------------------------------
09-01 16:13:30.752 10736 10736 I tag_linphone: Dialog sending retransmission of 200Ok   

09-01 16:13:30.753 10736 10736 I tag_linphone: channel [0x7f74102000]: message sent to [UDP://192.168.117.249:5060], size: [1718] bytes

09-01 16:13:30.753 10736 10736 I tag_linphone: SIP/2.0 200 Ok

09-01 16:13:30.753 10736 10736 I tag_linphone: Via: SIP/2.0/UDP 192.168.117.249:5060;branch=z9hG4bK.hFpkK8MZy;rport

09-01 16:13:30.753 10736 10736 I tag_linphone: From: "{\"devCode\":\"2420789542241c2c0750\",\"devType\":4,\"extno\":\"\",\"note\":\"16栋3单元门口机（16号楼3单元一楼）\",\"roomno\":\"\",\"sipType\":1,\"unitno\":\"1603\",\"zoneid\":\"0377\"}" <sip:linphone.android@192.168.117.249>;tag=nZxwFET3Z

09-01 16:13:30.753 10736 10736 I tag_linphone: To: <sip:outdoor@192.168.100.202>;tag=wuMerVb

09-01 16:13:30.753 10736 10736 I tag_linphone: Call-ID: Q6ZhVynhLB

09-01 16:13:30.753 10736 10736 I tag_linphone: CSeq: 20 INVITE

09-01 16:13:30.753 10736 10736 I tag_linphone: User-Agent: LinphoneAndroid/5.0.20200821144626 (belle-sip/1.6.3)

09-01 16:13:30.753 10736 10736 I tag_linphone: Supported: replaces, outbound, gruu

09-01 16:13:30.753 10736 10736 I tag_linphone: Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO, UPDATE

09-01 16:13:30.753 10736 10736 I tag_linphone: Contact: "{\"devCode\":\"8400789183005423020f\",\"devType\":1,\"extno\":\"\",\"note\":\"管理机（S5）\",\"roomno\":\"\",\"sipType\":1,\"unitno\":\"\",\"zoneid\":\"0377\"}" <sip:linphone.android@192.168.100.202;transport=udp>;+sip.instance="<urn:uuid:d1be6730-23f2-4026-af52-cf899af8527b>";+org.linphone.specs=groupchat

09-01 16:13:30.753 10736 10736 I tag_linphone: Content-Type: application/sdp

09-01 16:13:30.753 10736 10736 I tag_linphone: Content-Length: 713

09-01 16:13:30.753 10736 10736 I tag_linphone: v=0

09-01 16:13:30.753 10736 10736 I tag_linphone: o=linphone.android 460 2651 IN IP4 192.168.100.202

09-01 16:13:30.753 10736 10736 I tag_linphone: s=Talk

09-01 16:13:30.753 10736 10736 I tag_linphone: c=IN IP4 192.168.100.202

09-01 16:13:30.753 10736 10736 I tag_linphone: t=0 0

09-01 16:13:30.753 10736 10736 I tag_linphone: a=rtcp-xr:rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics

09-01 16:13:30.753 10736 10736 I tag_linphone: m=audio 7076 RTP/AVP 96 97 98 0 8 18 101 99 100

09-01 16:13:30.753 10736 10736 I tag_linphone: a=rtpmap:96 opus/48000/2

09-01 16:13:30.753 10736 10736 I tag_linphone: a=fmtp:96 useinbandfec=1

09-01 16:13:30.753 10736 10736 I tag_linphone: a=rtpmap:97 speex/16000

09-01 16:13:30.753 10736 10736 I tag_linphone: a=fmtp:97 vbr=on

09-01 16:13:30.753 10736 10736 I tag_linphone: a=rtpmap:98 speex/8000

09-01 16:13:30.753 10736 10736 I tag_linphone: a=fmtp:98 vbr=on

09-01 16:13:30.753 10736 10736 I tag_linphone: a=fmtp:18 annexb=yes

09-01 16:13:30.753 10736 10736 I tag_linphone: a=rtpmap:101 telephone-event/48000

09-01 16:13:30.753 10736 10736 I tag_linphone: a=rtpmap:99 telephone-event/16000

09-01 16:13:30.753 10736 10736 I tag_linphone: a=rtpmap:100 telephone-event/8000

09-01 16:13:30.753 10736 10736 I tag_linphone: a=rtcp-fb:* trr-int 5000

09-01 16:13:30.753 10736 10736 I tag_linphone: a=rtcp-fb:* ccm tmmbr

09-01 16:13:30.753 10736 10736 I tag_linphone: m=video 9078 RTP/AVP 96

09-01 16:13:30.753 10736 10736 I tag_linphone: a=rtpmap:96 H264/90000

09-01 16:13:30.753 10736 10736 I tag_linphone: a=fmtp:96 profile-level-id=42801F

09-01 16:13:30.753 10736 10736 I tag_linphone: a=rtcp-fb:* trr-int 5000

09-01 16:13:30.754 10736 10736 I tag_linphone: a=rtcp-fb:* ccm tmmbr

09-01 16:13:30.754 10736 10736 I tag_linphone: a=rtcp-fb:96 nack pli

09-01 16:13:30.754 10736 10736 I tag_linphone: a=rtcp-fb:96 ccm fir

09-01 16:13:30.794 10736 10736 I tag_linphone: bellesip_wake_lock_acquire(): Android wake lock [belle-sip recv channel] acquired [ref=0x200856]

09-01 16:13:30.794 10736 10736 I tag_linphone: channel [0x7f73d89000]: starting recv background task with id=[200856].

09-01 16:13:30.794 10736 10736 I tag_linphone: channel [0x7f73d89000]: ending recv background task with id=[200856].

09-01 16:13:30.795 10736 10736 I tag_linphone: bellesip_wake_lock_release(): Android wake lock released [ref=0x200856]

09-01 16:13:31.175 10736 10736 I tag_linphone: nict_on_timer_E: sending retransmission

09-01 16:13:31.176 10736 10736 I tag_linphone: channel [0x7f74102000]: message sent to [UDP://192.168.117.249:5060], size: [565] bytes

09-01 16:13:31.176 10736 10736 I tag_linphone: BYE sip:linphone.android@192.168.117.249;transport=udp SIP/2.0

09-01 16:13:31.176 10736 10736 I tag_linphone: Via: SIP/2.0/UDP 192.168.100.202:5060;branch=z9hG4bK.TL1HyWVXn;rport

09-01 16:13:31.176 10736 10736 I tag_linphone: From: <sip:outdoor@192.168.100.202>;tag=wuMerVb

09-01 16:13:31.176 10736 10736 I tag_linphone: To: "{\"devCode\":\"2420789542241c2c0750\",\"devType\":4,\"extno\":\"\",\"note\":\"16栋3单元门口机（16号楼3单元一楼）\",\"roomno\":\"\",\"sipType\":1,\"unitno\":\"1603\",\"zoneid\":\"0377\"}" <sip:linphone.android@192.168.117.249>;tag=nZxwFET3Z

09-01 16:13:31.176 10736 10736 I tag_linphone: CSeq: 111 BYE

09-01 16:13:31.176 10736 10736 I tag_linphone: Call-ID: Q6ZhVynhLB

09-01 16:13:31.176 10736 10736 I tag_linphone: Max-Forwards: 70

09-01 16:13:31.176 10736 10736 I tag_linphone: User-Agent: LinphoneAndroid/5.0.20200821144626 (belle-sip/1.6.3)

09-01 16:13:31.358 10736 10736 I tag_linphone: bellesip_wake_lock_acquire(): Android wake lock [belle-sip recv channel] acquired [ref=0x2007ee]

09-01 16:13:31.358 10736 10736 I tag_linphone: channel [0x7f7372a000]: starting recv background task with id=[2007ee].

09-01 16:13:31.359 10736 10736 I tag_linphone: channel [0x7f7372a000]: ending recv background task with id=[2007ee].

09-01 16:13:31.361 10736 10736 I tag_linphone: bellesip_wake_lock_release(): Android wake lock released [ref=0x2007ee]

09-01 16:13:31.723 10736 10736 I tag_linphone: bellesip_wake_lock_acquire(): Android wake lock [belle-sip recv channel] acquired [ref=0x2007e6]

09-01 16:13:31.724 10736 10736 I tag_linphone: channel [0x7f73456000]: starting recv background task with id=[2007e6].

09-01 16:13:31.724 10736 10736 I tag_linphone: channel [0x7f73456000]: ending recv background task with id=[2007e6].

09-01 16:13:31.725 10736 10736 I tag_linphone: bellesip_wake_lock_release(): Android wake lock released [ref=0x2007e6]

09-01 16:13:31.742 10736 10736 I tag_linphone: bellesip_wake_lock_acquire(): Android wake lock [belle-sip recv channel] acquired [ref=0x2007d6]

09-01 16:13:31.743 10736 10736 I tag_linphone: channel [0x7f74902000]: starting recv background task with id=[2007d6].

09-01 16:13:31.743 10736 10736 I tag_linphone: channel [0x7f74902000]: ending recv background task with id=[2007d6].

09-01 16:13:31.744 10736 10736 I tag_linphone: bellesip_wake_lock_release(): Android wake lock released [ref=0x2007d6]

09-01 16:13:31.802 10736 10736 I tag_linphone: bellesip_wake_lock_acquire(): Android wake lock [belle-sip recv channel] acquired [ref=0x1007d2]

09-01 16:13:31.802 10736 10736 I tag_linphone: channel [0x7f72756000]: starting recv background task with id=[1007d2].

09-01 16:13:31.802 10736 10736 I tag_linphone: channel [0x7f72756000]: ending recv background task with id=[1007d2].

09-01 16:13:31.803 10736 10736 I tag_linphone: bellesip_wake_lock_release(): Android wake lock released [ref=0x1007d2]

09-01 16:13:32.003 10736 10736 I tag_linphone: bellesip_wake_lock_acquire(): Android wake lock [belle-sip recv channel] acquired [ref=0x1007ce]

09-01 16:13:32.004 10736 10736 I tag_linphone: channel [0x7f73d66000]: starting recv background task with id=[1007ce].

09-01 16:13:32.004 10736 10736 I tag_linphone: channel [0x7f73d66000]: ending recv background task with id=[1007ce].

09-01 16:13:32.005 10736 10736 I tag_linphone: bellesip_wake_lock_release(): Android wake lock released [ref=0x1007ce]

09-01 16:13:32.165 10736 10736 I tag_linphone: bellesip_wake_lock_acquire(): Android wake lock [belle-sip recv channel] acquired [ref=0x1007ca]

09-01 16:13:32.165 10736 10736 I tag_linphone: channel [0x7f74856000]: starting recv background task with id=[1007ca].

09-01 16:13:32.165 10736 10736 I tag_linphone: channel [0x7f74856000]: ending recv background task with id=[1007ca].

09-01 16:13:32.166 10736 10736 I tag_linphone: bellesip_wake_lock_release(): Android wake lock released [ref=0x1007ca]

09-01 16:13:32.328 10736 10736 I tag_linphone: bellesip_wake_lock_acquire(): Android wake lock [belle-sip recv channel] acquired [ref=0x7c6]

09-01 16:13:32.328 10736 10736 I tag_linphone: channel [0x7f74a2a000]: starting recv background task with id=[7c6].

09-01 16:13:32.328 10736 10736 I tag_linphone: channel [0x7f74a2a000]: ending recv background task with id=[7c6].

09-01 16:13:32.329 10736 10736 I tag_linphone: bellesip_wake_lock_release(): Android wake lock released [ref=0x7c6]

09-01 16:13:32.789 10736 10736 I tag_linphone: bellesip_wake_lock_acquire(): Android wake lock [belle-sip recv channel] acquired [ref=0x1007c2]

09-01 16:13:32.789 10736 10736 I tag_linphone: channel [0x7f74f2a000]: starting recv background task with id=[1007c2].

09-01 16:13:32.789 10736 10736 I tag_linphone: channel [0x7f74f2a000]: ending recv background task with id=[1007c2].

09-01 16:13:32.790 10736 10736 I tag_linphone: bellesip_wake_lock_release(): Android wake lock released [ref=0x1007c2]

09-01 16:13:33.272 10736 10736 I tag_linphone: bellesip_wake_lock_acquire(): Android wake lock [belle-sip recv channel] acquired [ref=0x1007ba]

09-01 16:13:33.273 10736 10736 I tag_linphone: channel [0x7f74613000]: starting recv background task with id=[1007ba].

09-01 16:13:33.273 10736 10736 I tag_linphone: channel [0x7f74613000]: ending recv background task with id=[1007ba].

09-01 16:13:33.275 10736 10736 I tag_linphone: bellesip_wake_lock_release(): Android wake lock released [ref=0x1007ba]

09-01 16:13:33.654 10736 10736 I tag_linphone: bellesip_wake_lock_acquire(): Android wake lock [belle-sip recv channel] acquired [ref=0x7a2]

09-01 16:13:33.655 10736 10736 I tag_linphone: channel [0x7f733c2000]: starting recv background task with id=[7a2].

09-01 16:13:33.655 10736 10736 I tag_linphone: channel [0x7f733c2000]: ending recv background task with id=[7a2].

09-01 16:13:33.656 10736 10736 I tag_linphone: bellesip_wake_lock_release(): Android wake lock released [ref=0x7a2]

09-01 16:13:33.897 10736 10736 I tag_linphone: bellesip_wake_lock_acquire(): Android wake lock [belle-sip recv channel] acquired [ref=0x10079a]

09-01 16:13:33.897 10736 10736 I tag_linphone: channel [0x7f75da2000]: starting recv background task with id=[10079a].

09-01 16:13:33.897 10736 10736 I tag_linphone: channel [0x7f75da2000]: ending recv background task with id=[10079a].

09-01 16:13:33.898 10736 10736 I tag_linphone: bellesip_wake_lock_release(): Android wake lock released [ref=0x10079a]

**Comment by Viish** [comment]
200 OK means call is connected and will trigger the call state change to Connected.
Given that you are using UDP, packet can (and probably will) be lost and sent again, hence the retransmission.
Thus it can happen you will receive it more than once.
You should use TCP or even better TLS.

**Comment by fengqz627** [comment]
Linphone is based on UDP transmission, can also be based on TCP or TLS？

**Comment by Viish** [comment]
SIP can be sent over UDP, TCP and TLS. We've always recommended TLS or TCP instead of UDP.
UDP is only used 100% of the time for RTP packets.
