### ISSUE TITLE
can not receive calls while I use my mobile data.

### ISSUE THREAD

**Issue by sofkal** [BelledonneCommunications/linphone-android#1147]

**Comment by Viish** [comment]
Please attach SDK logs.

**Comment by sofkal** [comment]
> Please attach SDK logs.
Thank you for your response. I tried but I can not  find SDK logs..

**Comment by Viish** [comment]
Enable SDK logs in advance section of the settings, restart the app, reproduce the issue and then click on send logs button in about page.

**Comment by sofkal** [comment]
https://www.linphone.org:444//tmp/5f4e8579537d7_473ac70e52ffec628af4.gz

**Comment by Viish** [comment]
Your log isn't helpful.
Click on the clear logs button on About page, kill app & restart it, reproduce the issue and send logs again.
Also it seems you are using UDP, most probably your issue comes from this. TLS would be the best, TCP if your server doesn't support TLS.
