### ISSUE TITLE
JNI ERROR (app bug): local reference table overflow (max=512)'

### ISSUE THREAD

**Issue by astuter** [BelledonneCommunications/linphone-android#115]
Strange thing is crashing linphone all time. Here is the log:

* * * * * * * * * * * * * * * *
Build fingerprint: 'Xiaomi/kenzo/kenzo:6.0.1/MMB29M/V8.5.6.0.MHOMIED:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 26646, tid: 26646, name: net.buddyapp  >>> net.buddyapp <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'art/runtime/indirect_reference_table.cc:115] JNI ERROR (app bug): local reference table overflow (max=512)'
    x0   0000000000000000  x1   0000000000006816  x2   0000000000000006  x3   0000000000000000
    x4   0000000000000000  x5   0000000000000001  x6   0000000000000000  x7   0000000000000000
    x8   0000000000000083  x9   0000007f84148a70  x10  0000000000000003  x11  0000000000000130
    x12  00000055af3048a0  x13  00000055adf7a000  x14  0000000000000000  x15  0000000000000000
    x16  0000007f841416a8  x17  0000007f84103bdc  x18  c000000000000000  x19  0000007f845690a8
    x20  0000007f84568fe8  x21  000000000000000b  x22  0000000000000006  x23  00000055adfae650
    x24  00000055af33d390  x25  0000000000000000  x26  00000055adf90d90  x27  0000000000000000
    x28  00000055adfae650  x29  0000007fc9819c50  x30  0000007f84101378
    sp   0000007fc9819c50  pc   0000007f84103be4  pstate 0000000020000000

backtrace:
    #00 pc 000000000006abe4  /system/lib64/libc.so (tgkill+8)
    #01 pc 0000000000068374  /system/lib64/libc.so (pthread_kill+68)
    #02 pc 00000000000212f8  /system/lib64/libc.so (raise+28)
    #03 pc 000000000001ba98  /system/lib64/libc.so (abort+60)
    #04 pc 00000000004328c0  /system/lib64/libart.so (_ZN3art7Runtime5AbortEv+324)
    #05 pc 0000000000136364  /system/lib64/libart.so (_ZN3art10LogMessageD2Ev+3136)
    #06 pc 0000000000272820  /system/lib64/libart.so (_ZN3art22IndirectReferenceTable3AddEjPNS_6mirror6ObjectE+372)
    #07 pc 0000000000330df0  /system/lib64/libart.so (_ZN3art3JNI12NewStringUTFEP7_JNIEnvPKc+428)
    #08 pc 00000000001535b8  /system/lib64/libart.so (_ZN3art8CheckJNI12NewStringUTFEP7_JNIEnvPKc+500)
    #09 pc 00000000003b28b8  /data/app/net.buddyapp-1/lib/arm64/liblinphone.so (_ZN16LinphoneCoreData23registrationStateChangeEP13_LinphoneCoreP20_LinphoneProxyConfig26_LinphoneRegistrationStatePKc+152)
    #10 pc 000000000039be5c  /data/app/net.buddyapp-1/lib/arm64/liblinphone.so (linphone_core_notify_registration_state_changed+108)
    #11 pc 00000000003933c0  /data/app/net.buddyapp-1/lib/arm64/liblinphone.so (linphone_proxy_config_set_state+288)
    #12 pc 000000000037ff14  /data/app/net.buddyapp-1/lib/arm64/liblinphone.so (linphone_core_refresh_registers+72)
    #13 pc 00000000028bcd54  /data/app/net.buddyapp-1/oat/arm64/base.odex (offset 0xfaa000) (void org.linphone.core.LinphoneCoreImpl.refreshRegisters(long)+136)
    #14 pc 00000000028d2300  /data/app/net.buddyapp-1/oat/arm64/base.odex (offset 0xfaa000) (void org.linphone.core.LinphoneCoreImpl.refreshRegisters()+100)
    #15 pc 0000000002838544  /data/app/net.buddyapp-1/oat/arm64/base.odex (offset 0xfaa000) (void org.linphone.KeepAliveHandler.onReceive(android.content.Context, android.content.Intent)+216)
    #16 pc 0000000073888640  /data/dalvik-cache/arm64/system@framework@boot.oat (offset 0x249b000)

**Comment by DatBewar** [comment]
Hello,
how did you obtain that?

**Comment by astuter** [comment]
Hello @DatBewar ,

On RedMi Xiaomi devices when crash happens we get this complete crash logs. From there I have collected this logs.

**Comment by wmailn** [comment]
I also encountered this problem, when frequently setting the window, may I ask you to solve it?
