### ISSUE TITLE
Audio recording does not work on Android 11

### ISSUE THREAD

**Issue by grit96** [BelledonneCommunications/linphone-android#1150]
Using `liblinphone 4.2` on Android 11 beta, third party cannot hear audio from Android microphone.

The following errors are in the logs:

```
E/IAudioFlinger: createRecord returned error -1
E/AudioRecord: createRecord_l(0): AudioFlinger could not create record track, status: -1
E/libOpenSLES: android_audioRecorder_realize(0x7c2db3cb60) error creating AudioRecord object; status -1
W/libOpenSLES: Leaving Object::Realize (SL_RESULT_CONTENT_UNSUPPORTED)
E/RNLiblinphone::LinphoneManager: [OpenSLES] Error 9 while realizing the audio recorder
E/RNLiblinphone::LinphoneManager: [OpenSLES] Problem when initialization of opensles recorder
```

**Comment by Viish** [comment]
Do you granted RECORD_AUDIO permission ?
Also latest release is 4.4.1 and we've made tests with 4.5.0-alpha it works fine.

**Comment by grit96** [comment]
Yes the `RECORD_AUDIO` permission is granted and the app works fine on devices running Android 10.

It seems that [OpenSL ES is deprecated in Android 11](https://developer.android.com/preview/features#deprecate-opensl).

Was there a change in `liblinphone` since `4.2` that moves away from OpenSL ES?

**Comment by Viish** [comment]
Yes they were some.

**Comment by grit96** [comment]
I think I was using the old Java wrapper in `4.2` (using imports such as `import org.linphone.core.LinphoneCore;`) but when I update to `4.3+` as per https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Getting%20started/Android/ I don't seem to be able to use those imports anymore.

I found a migration article [here](https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Linphone%20%28Android%29%20Java%20wrapper/) but I'm not sure where the migration script is.

Could you point me to either the migration script or how to use the Java wrapper with the new version of the SDK?

**Comment by Viish** [comment]
Here's the doc: https://www.linphone.org/snapshots/docs/liblinphone/multilang/reference/java/index.html
The migration script is here (not maintained): https://gitlab.linphone.org/BC/public/liblinphone/blob/master/wrappers/java/migration.sh

**Comment by grit96** [comment]
Even with the latest version (4.4.1) I still get the same problem. It seems that it's related to starting the call when the app is in the background because if I focus the app again the audio will work.

**Comment by Viish** [comment]
Have you tried reproducing with our android app?

**Comment by grit96** [comment]
No, but I think it's because we're using ConnectionService to manage the calls in Android so it probably won't be a problem with the linphone app.
