### ISSUE TITLE
Classes missing for version 4.4.1 and 4.5

### ISSUE THREAD

**Issue by Emil-Suleymanli** [BelledonneCommunications/linphone-android#1151]
Hi All,

I am trying to build the linphone classes, but the only classes that exist are org.linphone.core and org.linphone.mediastream. The rest of them such as linphone.contact, linphone.R, org.linphone.util and etc do not import.

I am using .aar files for version 4.4.1 and 4.5 from linphone maven repository: https://linphone.org/maven_repository/org/linphone/linphone-sdk-android/

Does anyone know which version has the rest of the classes or how can I get all classes with any of these two versions?

Thanks.

**Comment by Viish** [comment]
Hi,
AAR only contains the SDK, so there aren't any of the classes from the app itself.
Cheers,
