### ISSUE TITLE
cannot recive calls ( app does not autostart ) on Android 10  after reboot before enter PIN to unlock smartphone

### ISSUE THREAD

**Issue by harut420** [BelledonneCommunications/linphone-android#1152]
app does not autostart on android 10 after reboot before unlock smartphone.

**Comment by Viish** [comment]
Yes, that is expected.
Apps have to be configured to be able to start in this mode, and even if they do they don't have access to the file system.
Problem is without file system our app wouldn't be able to register to the SIP proxy and thus won't be able to receive calls or chat messages anyway.
