### ISSUE TITLE
NO VIDEO

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1154]
Hi,
When A calls B, B has a camera, but occasionally A can't display B's video, Attached is the log information of B
[No-video0907.txt](https://github.com/BelledonneCommunications/linphone-android/files/5181555/No-video0907.txt)

thanks.

**Comment by Viish** [comment]
Hi,
The logs show that A doesn't receive any video packet from B, check B logs.
I won't help you anymore as you are using a old SDK. and this isn't a linphon-android issue.

**Comment by fengqz627** [comment]
The log in the attachment above is  the log information of B，from the log of B:
RTP  audio=[d=76.92,u=80.00], video=[d=0.00,u=742.47,ed=0.00], text=[d=0.00,u=0.00] kbits/sec

09-05 11:25:15.632  7640  7640 I tag_linphone: sent                                       1298 packets

Should this show the video package sent by B to A? I don't understand if you say that A has not received the video package sent by B?

**Comment by Viish** [comment]
B hasn't received any video packet but has sent some:
```
09-05 11:25:15.632  7640  7640 I tag_linphone: ===========================================================

09-05 11:25:15.632  7640  7640 I tag_linphone:              VIDEO SESSION'S RTP STATISTICS                

09-05 11:25:15.632  7640  7640 I tag_linphone: -----------------------------------------------------------

09-05 11:25:15.632  7640  7640 I tag_linphone: sent                                       1298 packets

09-05 11:25:15.632  7640  7640 I tag_linphone:                                               0 duplicated packets

09-05 11:25:15.632  7640  7640 I tag_linphone:                                         1500685 bytes  

09-05 11:25:15.632  7640  7640 I tag_linphone: received                                      0 packets

09-05 11:25:15.632  7640  7640 I tag_linphone:                                               0 duplicated packets

09-05 11:25:15.632  7640  7640 I tag_linphone:                                               0 bytes  

09-05 11:25:15.632  7640  7640 I tag_linphone: incoming delivered to the app                 0 bytes  

09-05 11:25:15.632  7640  7640 I tag_linphone: incoming cumulative lost                      0 packets

09-05 11:25:15.632  7640  7640 I tag_linphone: incoming received too late                    0 packets

09-05 11:25:15.632  7640  7640 I tag_linphone: incoming bad formatted                        0 packets

09-05 11:25:15.632  7640  7640 I tag_linphone: incoming discarded (queue overflow)           0 packets

09-05 11:25:15.633  7640  7640 I tag_linphone: sent rtcp                                     0 packets

09-05 11:25:15.633  7640  7640 I tag_linphone: received rtcp                                 4 packets

09-05 11:25:15.633  7640  7640 I tag_linphone: ===========================================================
```

**Comment by fengqz627** [comment]
Yes, in design, A doesn't have a camera, so B doesn't need to display A's video. I only need B to display the video of A. now I see that A has a video packet sent to B, but B does not display the video. In addition, I see that there is an updated byremote status in the log. Why is this status? Is this the reason for the absence of video?

**Comment by fengqz627** [comment]
Sorry, I may not have made it clear, Yes, in design, A doesn't have a camera, so B doesn't need to display A's video. I only need B to display the video of A。 In addition, I see that there is an updated byremote status in the log. Why is this status? Is this the reason for the absence of video?

**Comment by Viish** [comment]
> In addition, I see that there is an updated byremote status in the log. 

A has sent an UPDATE, hence the UpdatedByRemote status.

If you need support or dev-assist, please contact [sales@belledonne-communications.com](mailto:sales@belledonne-communications.com) for a quotation.

**Comment by fengqz627** [comment]
I'm very sorry, but I still didn't express it clearly， in design, A doesn't have a camera, so B doesn't need to display A's video。Now the key is  that B has a video to A, but A can't display the video.  In addition, I see that there is an "updatedbyremote" status in the log. Why is this status? Is this the reason for the absence of video?  I don't know if it's related to the network or the chip。

**Comment by fengqz627** [comment]
thank you very much!
