### ISSUE TITLE
The quality of the first call was poor

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1157]
Hi,

When the device is powered on for the first time call, the audio and video quality is poor, including large delay, distortion, etc,
The second time and after the audio and video are normal, the call is normal, what is the reason?

thanks.

**Comment by Viish** [comment]
Hi,
No there's no reason for this.
Cheers,

**Comment by fengqz627** [comment]
Is linphone itself having this problem or is it related to the chip platform?

**Comment by Viish** [comment]
We don't have this problem but we are using an up-to-date SDK.
