### ISSUE TITLE
Wrong color of video display

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1158]
Hi，

I use camera "DVP CSI" , When talking, the image I got with takepreviewsnapshot() is correct, but the color of the image displayed on the other side is not correct, red and blue are not correct. in AndroidVideoApi9JniWrapper.java，when startRecording(),  I will convert nv21 to nv12, and the other side can display my video correctly. However, after conversion, the red and blue images captured by takepreviewsnapshot() are wrong again.
Why does this inconsistency occur with this camera? How to change it?

thanks.

**Comment by Viish** [comment]
Hi,
I don't even know what a DVP CSI camera is.
That being said, the issue might be fixed in the more recent release of the SDK than the one you are using. If it's not we probably won't try to fix it anyway.
Cheers,
