### ISSUE TITLE
linphone lib crashes

### ISSUE THREAD

**Issue by Pokkerolli** [BelledonneCommunications/linphone-android#1159]
Hi,

We analyzed crashes in our application and as a result revealed a list of crashes that come from this library. Can we expect to fix this crashes?

Regards, Julia

[signal 11 je_free.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195210/signal.11.je_free.txt)
[signal 11 linphone_configure_op_with_proxy.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195212/signal.11.linphone_configure_op_with_proxy.txt)
[signal 11 RefBase RefBase.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195213/signal.11.RefBase.RefBase.txt)
[signal 11 RosAlloc Run.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195214/signal.11.RosAlloc.Run.txt)
[signal 11 sqlite3FindFunction.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195215/signal.11.sqlite3FindFunction.txt)
[signal 11 strcmp.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195216/signal.11.strcmp.txt)
[signal 11 TaskProcessor.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195217/signal.11.TaskProcessor.txt)
[signal 11 Thread.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195218/signal.11.Thread.txt)
[signal 11 tree_iterator.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195219/signal.11.tree_iterator.txt)
[singal 11 RegexMatcher.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195220/singal.11.RegexMatcher.txt)
[single 11 anonlibc_malloc.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195221/single.11.anonlibc_malloc.txt)
[single 11 unknown.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195222/single.11.unknown.txt)
[tgkill.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195223/tgkill.txt)
[UnsatisfiedLinkError.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195224/UnsatisfiedLinkError.txt)
[abort.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195225/abort.txt)
[signal 7 RefBase incStrong.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195226/signal.7.RefBase.incStrong.txt)
[signal 11  arena_run_reg_alloc filter_list.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195227/signal.11.arena_run_reg_alloc.filter_list.txt)
[signal 11 __memcpy.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195229/signal.11.__memcpy.txt)
[signal 11 android RefBase decStrong.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195230/signal.11.android.RefBase.decStrong.txt)
[signal 11 android_atomic_add.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195231/signal.11.android_atomic_add.txt)
[signal 11 arena_run_tree_remove.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195232/signal.11.arena_run_tree_remove.txt)
[signal 11 bctbx_iterator.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195233/signal.11.bctbx_iterator.txt)
[signal 11 belle_sip_channel_queue_message.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195234/signal.11.belle_sip_channel_queue_message.txt)
[signal 11 belle_sip_header_address_get_uri.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195235/signal.11.belle_sip_header_address_get_uri.txt)
[signal 11 belle_sip_object_cast.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195236/signal.11.belle_sip_object_cast.txt)
[signal 11 CheckNoHeldMonitors.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195237/signal.11.CheckNoHeldMonitors.txt)
[signal 11 ConcurrentCopying.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195238/signal.11.ConcurrentCopying.txt)
[signal 11 freeDataNoInit.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195240/signal.11.freeDataNoInit.txt)
[signal 11 function void.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195241/signal.11.function.void.txt)
[signal 11 getNextFrameSize() const.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195242/signal.11.getNextFrameSize.const.txt)
[signal 11 IndirectReferenceTable.txt](https://github.com/BelledonneCommunications/linphone-android/files/5195243/signal.11.IndirectReferenceTable.txt)

**Comment by Viish** [comment]
Hi,
We won't investigate crashes without symbolized stack traces & matching SDK logs.
Please open a ticket per issue following above rules.
Also some of your crashes aren't related at all with either our app or SDK (for example signal `7 RefBase incStrong.txt`).
Finally consider reaching out to [sales@belledonne-communications.com](mailto:sales@belledonne-communications.com) to purchase either support or dev-assist from our company if this is a business project.
Cheers,
