### ISSUE TITLE
H264 codec not found after download

### ISSUE THREAD

**Issue by Janos1977** [BelledonneCommunications/linphone-android#116]
Hi everybody.
I'm implementing the download of Cisco h264 codec in an android application, following this guide:

> https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Codec%20H264%20on%20Android/

but at the end of the download, if I run this statement
```
for (PayloadType p : mLinphoneManager.getLinphoneCore().getVideoCodecs()) {
       LogUtil.log_i(LinphoneUtils.TAG, "codec : " + p.getMime());
}
```
, I find only the VP8 codec.
Is there anything I forgot?
**The app is running on a device having android 4.4.2**
Can anyoune help me?
Thanks

**Comment by DatBewar** [comment]
Hello,
after the download of OpenH264 you must reboot the application.

**Comment by mu-hasan** [comment]
I got same error. I use Android Jelly Bean is work well. When I use Android Lolipop or above, I got error `codec not found`. I try to install Linphone from Play Store, I always got Force Close. And I can't open that apps anymore (only clear data or reinstall can be fix it)
