### ISSUE TITLE
Java wrapper for Linphone

### ISSUE THREAD

**Issue by Emil-Suleymanli** [BelledonneCommunications/linphone-android#1161]
Is it possible to have Linphone app (for chat functions) running from command-line on Windows or Linux instead of as an Android app with the current or any old Java wrapper? Using java classes extracted from Linphone SDK .aar file (both 3.x and 4.x) with the below tutorials throws an error for missing libc++_shared.so. Adding .so in JNI folder to java.library.path did not help. 

https://gitlab.linphone.org/BC/public/liblinphone/tree/2bc924c184e2f00f1be3f82a736bccaeacce106e/coreapi/help/examples/java/org/linphone/core/tutorials

The above tutorial takes SIP credentials as argument passed from the command line (not Android app). 

I have been able to get it working with Python wrapper where SIP address is registered with my Flexisip server and messages are exchanged (from CLI). But it seemed that Python wrapper does not support group chat features as opposed to Java wrapper which has methods to add participants to chat rooms. 

Or can Java wrapper be only used to build Android apps?

**Comment by Viish** [comment]
Hi,
No the Java wrapper can only be used for Android apps.
Cheers,

**Comment by Emil-Suleymanli** [comment]
Thanks @Viish . Is there a wrappers that works either on Windows or Linux like I said above, and has methods to work with group chat features?

**Comment by Viish** [comment]
Not a Java one.
But we have C++ and C# wrappers ready and a Python one in development.
There is also a Swift wrapper but I don't know if it can be used outside of iOS.

**Comment by Emil-Suleymanli** [comment]
To use the C++ wrapper should I use the Linphone SDK in https://github.com/BelledonneCommunications/linphone-sdk ? Building it with the option Desktop for LINPHONESDK_PLATFORM with cmake fails on Ubuntu.

The link below has few examples. I am trying to get eg: basic registration working where sip address and password are passed from the command-line.


https://www.linphone.org/snapshots/docs/liblinphone/4.5.0/multilang/samples/samples.html#basic-registration


Thank you!

**Comment by Viish** [comment]
> To use the C++ wrapper should I use the Linphone SDK in https://github.com/BelledonneCommunications/linphone-sdk

Yes. If compil fails most probably you don't have installed one of the dependencies. Check the build output for the error.

**Comment by Emil-Suleymanli** [comment]
I believe I have all the dependencies installed.

cmake >= 3.6
```
cmake --version

cmake version 3.10.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

```

python = 2.7
```
python --version
Python 2.7.17
```

pip
```
pip --version
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
```

yasm
```
yasm --version

yasm 1.3.0
Compiled on Apr  3 2018.
Copyright (c) 2001-2014 Peter Johnson and other Yasm developers.
Run yasm --license for licensing overview and summary.
```

nasm

```
nasm --version

NASM version 2.13.02
```

doxygen
```
doxygen --version

1.8.13
```

Pystache 
```
pip install pystache

Requirement already satisfied: pystache in /usr/local/lib/python2.7/dist-packages
```

six
```
pip install six

Requirement already satisfied: six in /usr/lib/python2.7/dist-packages
```

The OS is Ubuntu 18.04. Install linphone-sdk:
```
git clone https://github.com/BelledonneCommunications/linphone-sdk.git --recursive
```

Configure the project:
```
mkdir build && cd build
cmake Desktop ..
```

Build the SDK:
```
cmake --build .
```

The error is:
```
CMakeFiles/sdk.dir/build.make:106: recipe for target 'sdk-prefix/src/sdk-stamp/sdk-configure' failed
make[2]: *** [sdk-prefix/src/sdk-stamp/sdk-configure] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/sdk.dir/all' failed
make[1]: *** [CMakeFiles/sdk.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

Am I missing something? Is it supported on Ubuntu 18.04?

**Comment by Emil-Suleymanli** [comment]
SOLVED: need to install pkg-config on Ubuntu 18.04.

linphone-sdk was successfully built afterwards.

In order to use C++ wrapper (for example, basic registration program [here](https://www.linphone.org/snapshots/docs/liblinphone/4.5.0/multilang/samples/samples.html#basic-registration)), in which folder should the program be saved and run from?

For example, the above simple program uses _linphone/core.h_. But core.h itself needs to include the other headers such as ortp/ortp.h. But relative to the core.h location, there is not any of these header files in the way it is included in core.h file.

Is there any other action in order to generate the C++ wrapper? Or building linphone-sdk with cmake is sufficient?

@Viish , could you please guide on this? How should C++ wrapper be used?

**Comment by Viish** [comment]
> Is there any other action in order to generate the C++ wrapper?

Building the SDK with platform Desktop is enough.

> How should C++ wrapper be used?

It's up to you to create your app and package it so it will go find the headers & libraries at the right place when you compile it.
You can take a look at our [linphone-desktop](https://github.com/BelledonneCommunications/linphone-desktop/) app.

**Comment by Emil-Suleymanli** [comment]
Thank you, @Viish .

What I specifically meant is this:

After the build, _core.h_ file is found at **linphone-sdk/build/linphone-sdk/desktop/include /linphone** location.
_core.h_ file itself is including other header files like below:

```
#include "ortp/ortp.h"
#include "ortp/payloadtype.h"
#include "mediastreamer2/mscommon.h"
#include "mediastreamer2/msvideo.h"
#include "mediastreamer2/mediastream.h"
#include "mediastreamer2/bitratecontrol.h"

#include "linphone/defs.h"
#include "linphone/types.h"
#include "linphone/callbacks.h"
#include "linphone/sipsetup.h"

#include "linphone/account_creator.h"
#include "linphone/account_creator_service.h"

#include "linphone/buffer.h"
#include "linphone/call.h"
#include "linphone/call_log.h"

.....
```
However, at the same location that _core.h_ file is located, there is no **ortp** or **mediastreamer2** folders, for example. Therefore, it is not possible to use _core.h_ in a code.

In **linphone-sdk/build/linphone-sdk/desktop/include** folder, there are **ortp** and **mediastreamer2** folders, and respective header files. So, I tried, to move _core.h_ file into the **linphone-sdk/build/linphone-sdk/desktop/include** folder. But because they each include other header files as well in their turn, it creates a loop. Hence, it becomes impossible to use at least _core.h_ .


I am not sure where to run the code from to be able to correctly #include _core.h_ after the SDK build.

**Comment by Viish** [comment]
I won't teach you C++ here but you have to set the path to the include directory when you build.
Also you simply need to include linphone.hh in linphone++ directory for C++ wrapper.

**Comment by Emil-Suleymanli** [comment]
Sure. It is not stated in Linphone API docs or README to include linphone++/linphone.hh to be able to use the C++ wrapper.
