### ISSUE TITLE
turbojpegwriter.c

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1163]
Hi，
Can you provide me with the latest file “ mediastreamer2/src/videofilters/turbojpegwriter.c ”?  I want to make a comparison.

thanks .

**Comment by Viish** [comment]
https://github.com/BelledonneCommunications/mediastreamer2/blob/master/src/videofilters/turbojpegwriter.c

**Comment by fengqz627** [comment]
Is the conversion between nv12 and nv21 well done in this file? I don't know how to transfer data.

thanks.

**Comment by fengqz627** [comment]
The conversion method knows, but does not know what parameters to pass in the conversion
