### ISSUE TITLE
how to download linphone-sdk-android source code？？？ Where is linphone-sdk-android download address？

### ISSUE THREAD

**Issue by ChinaVolvocars** [BelledonneCommunications/linphone-android#1167]

**Comment by Viish** [comment]
There is no linphone-sdk-android, only https://github.com/BelledonneCommunications/linphone-sdk built for Android.

**Comment by ChinaVolvocars** [comment]
How to build linphone-sdk for Android armeabi-v7a and armeabi-v8a so file ？ 
Can you provide the detailed compilation steps for Android?

**Comment by Viish** [comment]
Follow the README instructions:
- create a build directory
- call cmake .. -DLINPHONESDK_PLATFORM=Android
- then build using make
