### ISSUE TITLE
leaks

### ISSUE THREAD

**Issue by lolfinger** [BelledonneCommunications/linphone-android#117]
In org.linphone1.2.8:1280.
* org.linphone.CallActivity has leaked:
* GC ROOT android.view.SurfaceView.mContext
* leaks org.linphone.CallActivity instance

* Retaining: 2.6 MB.
* Reference Key: ff624998-c5b5-4af7-a3d2-c112c467267e
* Device: samsung samsung SM-G532F grandpplteser
* Android Version: 6.0.1 API: 23 LeakCanary: 1.5.2 be6b774
* Durations: watch=35357ms, gc=169ms, heap dump=5856ms, analysis=49070ms

* Details:
* Instance of android.view.SurfaceView
|   static DEBUG = false
|   static KEEP_SCREEN_ON_MSG = 1
|   static GET_NEW_SURFACE_MSG = 2
|   static DYNAMIC_BUFFER_QUEUE_ENABLED = false
|   static DYNAMIC_COLOR_SCALING_ENABLED = false
|   static DEBUG_DCS = false
|   static TAG_DCS = java.lang.String@852122240 (0x32ca5a80)
|   static $staticOverhead = byte[72]@852561921 (0x32d11001)
|   static UPDATE_WINDOW_MSG = 3
|   static TAG = java.lang.String@1892961864 (0x70d44e48)
|   mCallbacks = java.util.ArrayList@857101472 (0x331654a0)
|   mConfiguration = android.content.res.Configuration@857104512 (0x33166080)
|   mContentInsets = android.graphics.Rect@857101504 (0x331654c0)
|   mCurrentOrientation = -1
|   mDrawListener = android.view.SurfaceView$3@857037184 (0x33155980)
|   mDrawingStopped = true
|   mFormat = 4
|   mGlobalListenersAdded = false
|   mHandler = android.view.SurfaceView$1@857101536 (0x331654e0)
|   mHaveFrame = false
|   mHeight = 218
|   mIsCreating = false
|   mIsDcsEnabledApp = false
|   mIsFixedOrientation = false
|   mIsSixteenBitApp = 0
|   mLastLockTime = 0
|   mLastSurfaceHeight = 218
|   mLastSurfaceWidth = 180
|   mLayout = android.view.WindowManager$LayoutParams@851702528 (0x32c3f300)
|   mLeft = 360
|   mLocation = int[2]@857101568 (0x33165500)
|   mNeedForceDrawAtSetFrame = false
|   mNewSurface = android.view.Surface@857029440 (0x33153b40)
|   mOutsets = android.graphics.Rect@857101600 (0x33165520)
|   mOverscanInsets = android.graphics.Rect@857101632 (0x33165540)
|   mReportDrawNeeded = false
|   mRequestedFormat = 4
|   mRequestedHeight = -1
|   mRequestedVisible = false
|   mRequestedWidth = -1
|   mRequestedX = 0
|   mRequestedY = 0
|   mSVBufferCount = -1
|   mScrollChangedListener = android.view.SurfaceView$2@857037200 (0x33155990)
|   mSession = null
|   mStableInsets = android.graphics.Rect@857101664 (0x33165560)
|   mSurface = android.view.Surface@857029504 (0x33153b80)
|   mSurfaceCreated = false
|   mSurfaceFrame = android.graphics.Rect@857101696 (0x33165580)
|   mSurfaceHolder = android.view.SurfaceView$4@857037216 (0x331559a0)
|   mSurfaceLock = java.util.concurrent.locks.ReentrantLock@857037232 (0x331559b0)
|   mTargetHeight = -1
|   mTargetWidth = -1
|   mTop = 742
|   mTranslator = null
|   mUpdateWindowNeeded = false
|   mViewVisibility = true
|   mVisible = false
|   mVisibleInsets = android.graphics.Rect@857101728 (0x331655a0)
|   mWidth = 180
|   mWinFrame = android.graphics.Rect@857101760 (0x331655c0)
|   mWindow = null
|   mWindowType = 1004
|   mWindowVisibility = false
|   isPenSideButton = false
|   mAccessibilityCursorPosition = -1
|   mAccessibilityDelegate = null
|   mAccessibilityTraversalAfterId = -1
|   mAccessibilityTraversalBeforeId = -1
|   mAccessibilityViewId = -1
|   mAirButtonImpl = null
|   mAnimator = null
|   mAttachInfo = null
|   mAttributes = null
|   mBackground = null
|   mBackgroundPath = null
|   mBackgroundRenderNode = null
|   mBackgroundResource = 0
|   mBackgroundSizeChanged = true
|   mBackgroundTint = null
|   mBottom = 924
|   mCachingFailed = false
|   mClipBounds = null
|   mContentDescription = null
|   mContext = org.linphone.CallActivity@852788704 (0x32d485e0)
|   mCurrentAnimation = null
|   mDisablePenGestureforfactorytest = true
|   mDrawableState = int[2]@1895983840 (0x71026ae0)
|   mDrawingCache = null
|   mDrawingCacheBackgroundColor = 0
|   mEnablePenGesture = false
|   mFloatingTreeObserver = null
|   mForegroundInfo = null
|   mGhostView = null
|   mHasPerformedLongPress = false
|   mHoverPopup = null
|   mHoverPopupToolTypeByApp = 0
|   mHoverPopupType = 0
|   mID = 2131624218
|   mIgnoreNextUpEvent = false
|   mInContextButtonPress = false
|   mInputEventConsistencyVerifier = null
|   mIsDetachedFromWindow = true
|   mIsInDialog = false
|   mIsSetContextMenuZOrderToTop = false
|   mIsSetFingerHovedInAppWidget = true
|   mIsWritingBuddyEnabled = false
|   mKeyedTags = null
|   mLabelForId = -1
|   mLastIsOpaque = false
|   mLayerPaint = null
|   mLayerType = 0
|   mLayoutInsets = null
|   mLayoutParams = android.widget.RelativeLayout$LayoutParams@856996848 (0x3314bbf0)
|   mLeft = 360
|   mLeftPaddingDefined = false
|   mListenerInfo = android.view.View$ListenerInfo@856996928 (0x3314bc40)
|   mMatchIdPredicate = null
|   mMatchLabelForPredicate = null
|   mMeasureCache = android.util.LongSparseLongArray@857101792 (0x331655e0)
|   mMeasuredHeight = 218
|   mMeasuredWidth = 180
|   mMinHeight = 0
|   mMinWidth = 0
|   mNeededToChangedScrollBarPosition = false
|   mNestedScrollingParent = null
|   mNextFocusDownId = -1
|   mNextFocusForwardId = -1
|   mNextFocusLeftId = -1
|   mNextFocusRightId = -1
|   mNextFocusUpId = -1
|   mOldHeightMeasureSpec = 1073742042
|   mOldWidthMeasureSpec = 1073742004
|   mOutlineProvider = android.view.ViewOutlineProvider$1@1896062952 (0x71039fe8)
|   mOverScrollMode = 1
|   mOverlay = null
|   mPaddingBottom = 0
|   mPaddingLeft = 0
|   mPaddingRight = 0
|   mPaddingTop = 0
|   mParent = android.widget.RelativeLayout@856934400 (0x3313c800)
|   mPendingCheckForLongPress = null
|   mPendingCheckForTap = null
|   mPerformClick = null
|   mPrivateFlags = 16812720
|   mPrivateFlags2 = 1610819112
|   mPrivateFlags3 = 0
|   mRecreateDisplayList = false
|   mRenderNode = android.view.RenderNode@857101824 (0x33165600)
|   mRenderNodeImageFilter = null
|   mRenderNodeImageFilterClipRects = java.util.ArrayList@857101856 (0x33165620)
|   mResources = android.content.res.Resources@852522176 (0x32d074c0)
|   mRight = 540
|   mRightPaddingDefined = false
|   mRootViewCheckForDialog = null
|   mScrollBarPositionPadding = 0
|   mScrollCache = null
|   mScrollIndicatorDrawable = null
|   mScrollX = 0
|   mScrollY = 0
|   mSendViewScrolledAccessibilityEvent = null
|   mSendViewStateChangedAccessibilityEvent = null
|   mSendingHoverAccessibilityEvents = false
|   mSkipRtlCheck = false
|   mSmartClipDataExtractionListener = null
|   mSmartClipDataTag = null
|   mStartActivityRequestWho = null
|   mStateListAnimator = null
|   mSystemUiVisibility = 0
|   mTag = null
|   mTempNestedScrollConsumed = null
|   mTop = 706
|   mTouchDelegate = null
|   mTouchSlop = 12
|   mTouchwizFlags = 0
|   mTransformationInfo = android.view.View$TransformationInfo@857101888 (0x33165640)
|   mTransientStateCount = 0
|   mTransitionName = null
|   mTwExtraPaddingBottomForPreference = 0
|   mTwHorizontalScrollbarPosition = 0
|   mTwHorizontalScrollbarRect = android.graphics.Rect@857101920 (0x33165660)
|   mTwScrollingByScrollbar = false
|   mTwScrollingVertical = true
|   mTwVerticalScrollbarRect = android.graphics.Rect@857101952 (0x33165680)
|   mUnscaledDrawingCache = null
|   mUnsetPressedState = null
|   mUserPaddingBottom = 0
|   mUserPaddingEnd = -2147483648
|   mUserPaddingLeft = 0
|   mUserPaddingLeftInitial = 0
|   mUserPaddingRight = 0
|   mUserPaddingRightInitial = 0
|   mUserPaddingStart = -2147483648
|   mVerticalScrollFactor = 0.0
|   mVerticalScrollbarPosition = 0
|   mViewFlags = 402653312
|   mWindowAttachCount = 1
|   mWritingBuddy = null
|   mXmlFilePath = null
|   shadow$_klass_ = android.view.SurfaceView
|   shadow$_monitor_ = -2134573228
* Instance of org.linphone.CallActivity
|   static SECONDS_BEFORE_DENYING_CALL_UPDATE = 30000
|   static PERMISSIONS_ENABLED_CAMERA = 203
|   static DIS = 2
|   static SECONDS_BEFORE_HIDING_CONTROLS = 4000
|   static ON = 1
|   static TimeRemind = 29921
|   static PERMISSIONS_REQUEST_CAMERA = 202
|   static $staticOverhead = byte[80]@852361217 (0x32ce0001)
|   static OFF = 0
|   static instance = null
|   static PERMISSIONS_ENABLED_MIC = 204
|   addCall = android.widget.ImageView@856936448 (0x3313d000)
|   audioCallFragment = org.linphone.CallAudioFragment@851768096 (0x32c4f320)
|   audioRoute = android.widget.ImageView@856937472 (0x3313d400)
|   avatar_layout = android.widget.RelativeLayout@856938496 (0x3313d800)
|   callInfo = android.widget.LinearLayout@856939520 (0x3313dc00)
|   callsList = android.widget.LinearLayout@856940544 (0x3313e000)
|   cameraNumber = 2
|   chat = android.widget.ImageView@856941568 (0x3313e400)
|   conference = android.widget.ImageView@856942592 (0x3313e800)
|   conferenceList = android.widget.LinearLayout@856943616 (0x3313ec00)
|   conferenceStatus = null
|   contactPicture = android.widget.ImageView@856944640 (0x3313f000)
|   container = android.widget.RelativeLayout@856945664 (0x3313f400)
|   dialer = android.widget.ImageView@856946688 (0x3313f800)
|   dialog = null
|   hangUp = android.widget.ImageView@856947712 (0x3313fc00)
|   inflater = com.android.internal.policy.PhoneLayoutInflater@857095952 (0x33163f10)
|   isConferenceRunning = false
|   isMicMuted = false
|   isSpeakerEnabled = true
|   isTransferAllowed = true
|   isVideoAsk = false
|   isVideoCallPaused = false
|   mActiveCallHeader = android.widget.RelativeLayout@856948736 (0x33140000)
|   mCallPaused = android.widget.LinearLayout@856949760 (0x33140400)
|   mControls = null
|   mControlsHandler = null
|   mControlsLayout = android.widget.LinearLayout@856950784 (0x33140800)
|   mDecoderTexts = java.util.HashMap@857096000 (0x33163f40)
|   mEncoderTexts = java.util.HashMap@857096048 (0x33163f70)
|   mHandler = android.os.Handler@857103808 (0x33165dc0)
|   mListener = org.linphone.CallActivity$1@857037600 (0x33155b20)
|   mNoCurrentCall = android.widget.LinearLayout@856951808 (0x33140c00)
|   mTask = org.linphone.CallActivity$11@856030880 (0x3305fea0)
|   mTimer = java.util.Timer@857037616 (0x33155b30)
|   micro = android.widget.ImageView@856952832 (0x33141000)
|   missedChats = android.widget.TextView@856953856 (0x33141400)
|   numpad = org.linphone.ui.Numpad@856954880 (0x33141800)
|   options = android.widget.ImageView@856955904 (0x33141c00)
|   pause = android.widget.ImageView@856956928 (0x33142000)
|   routeBluetooth = android.widget.ImageView@856957952 (0x33142400)
|   routeEarpiece = android.widget.ImageView@856958976 (0x33142800)
|   routeSpeaker = android.widget.ImageView@856960000 (0x33142c00)
|   sideMenu = android.support.v4.widget.DrawerLayout@856961024 (0x33143000)
|   sideMenuContent = android.widget.RelativeLayout@856962048 (0x33143400)
|   speaker = android.widget.ImageView@856963072 (0x33143800)
|   status = org.linphone.StatusFragment@851702912 (0x32c3f480)
|   switchCamera = android.widget.ImageView@856964096 (0x33143c00)
|   timer = null
|   transfer = android.widget.ImageView@856965120 (0x33144000)
|   video = android.widget.ImageView@856966144 (0x33144400)
|   videoCallFragment = org.linphone.CallVideoFragment@852477952 (0x32cfc800)
|   videoProgress = android.widget.ProgressBar@856967168 (0x33144800)
|   DEBUG_ELASTIC = false
|   IS_ELASTIC_ENABLED = false
|   mActionBar = null
|   mActionModeTypeStarting = 0
|   mActivityInfo = android.content.pm.ActivityInfo@857104896 (0x33166200)
|   mActivityTransitionState = android.app.ActivityTransitionState@857030528 (0x33153f80)
|   mApplication = org.linphone.LeaksDetectorApp@853510752 (0x32df8a60)
|   mCalled = true
|   mChangeCanvasToTranslucent = false
|   mChangingConfigurations = false
|   mComponent = android.content.ComponentName@857037632 (0x33155b40)
|   mConfigChangeFlags = 0
|   mCurrentConfig = android.content.res.Configuration@857105024 (0x33166280)
|   mDecor = null
|   mDefaultKeyMode = 0
|   mDefaultKeySsb = null
|   mDefinedOrientation = -2
|   mDestroyed = true
|   mDoReportFullyDrawn = false
|   mEmbeddedID = null
|   mEnableDefaultActionBarUp = false
|   mEnterTransitionListener = android.app.SharedElementCallback$1@1895938312 (0x7101b908)
|   mExitTransitionListener = android.app.SharedElementCallback$1@1895938312 (0x7101b908)
|   mExpandRequestListener = null
|   mFeatureContextMenuListener = android.app.Activity$FeatureContextMenuListener@857037648 (0x33155b50)
|   mFinished = true
|   mFlipfont = 0
|   mFragments = android.app.FragmentController@857037664 (0x33155b60)
|   mHandler = android.os.Handler@857103840 (0x33165de0)
|   mHasCurrentPermissionsRequest = false
|   mIdent = 64715370
|   mInjectionManager = null
|   mInstanceTracker = android.os.StrictMode$InstanceTracker@857037680 (0x33155b70)
|   mInstrumentation = android.app.Instrumentation@853486496 (0x32df2ba0)
|   mIntent = android.content.Intent@857099520 (0x33164d00)
|   mLastNonConfigurationInstances = null
|   mLauncherBooster = null
|   mMainThread = android.app.ActivityThread@851456256 (0x32c03100)
|   mManagedCursors = java.util.ArrayList@857103872 (0x33165e00)
|   mManagedDialogs = null
|   mMenuInflater = null
|   mMultiWindowStyle = com.samsung.android.multiwindow.MultiWindowStyle@857096096 (0x33163fa0)
|   mParent = null
|   mPolicyManager = null
|   mPreferredOrientation = -2
|   mPreventEmbeddedTabs = false
|   mReferrer = java.lang.String@857096144 (0x33163fd0)
|   mResultCode = 0
|   mResultData = null
|   mResumed = false
|   mScreenChangeListener = null
|   mSearchEvent = null
|   mSearchManager = null
|   mShrinkRequestListener = null
|   mStackedHeight = -1
|   mStartedActivity = false
|   mStopped = true
|   mSubDecor = null
|   mSubWindow = null
|   mSubWindowAdded = false
|   mSubWindowDummpy = null
|   mTemporaryPause = false
|   mTitle = java.lang.String@853488320 (0x32df32c0)
|   mTitleColor = 0
|   mTitleReady = true
|   mToken = android.os.BinderProxy@857103904 (0x33165e20)
|   mTranslucentCallback = null
|   mUiThread = java.lang.Thread@1988994456 (0x768da598)
|   mVisibleBehind = false
|   mVisibleFromClient = true
|   mVisibleFromServer = true
|   mVoiceInteractor = null
|   mWindow = com.android.internal.policy.PhoneWindow@852445360 (0x32cf48b0)
|   mWindowAdded = true
|   mWindowManager = android.view.WindowManagerImpl@857103936 (0x33165e40)
|   myName = java.lang.String@856995728 (0x3314b790)
|   mInflater = com.android.internal.policy.PhoneLayoutInflater@857095952 (0x33163f10)
|   mOverrideConfiguration = null
|   mResources = android.content.res.Resources@852522176 (0x32d074c0)
|   mTheme = android.content.res.Resources$Theme@857103968 (0x33165e60)
|   mThemeResource = 2131427330
|   mBase = android.app.ContextImpl@856843008 (0x33126300)
|   shadow$_klass_ = org.linphone.CallActivity
|   shadow$_monitor_ = -2053274804
* Excluded Refs:
| Field: android.view.inputmethod.InputMethodManager.mNextServedView
| Field: android.view.inputmethod.InputMethodManager.mServedView
| Field: android.view.inputmethod.InputMethodManager.mServedInputConnection
| Field: android.view.inputmethod.InputMethodManager.mCurRootView
| Field: android.os.UserManager.mContext
| Field: android.net.ConnectivityManager.sInstance
| Field: com.samsung.android.content.clipboard.SemClipboardManager.mContext
| Field: com.samsung.android.emergencymode.SemEmergencyManager.mContext
| Field: android.view.Choreographer$FrameDisplayEventReceiver.mMessageQueue (always)
| Thread:FinalizerWatchdogDaemon (always)
| Thread:main (always)
| Thread:LeakCanary-Heap-Dump (always)
| Class:java.lang.ref.WeakReference (always)
| Class:java.lang.ref.SoftReference (always)
| Class:java.lang.ref.PhantomReference (always)
| Class:java.lang.ref.Finalizer (always)
| Class:java.lang.ref.FinalizerReference (always)

**Comment by DatBewar** [comment]
Hello,
What's the leak?

**Comment by lolfinger** [comment]
u can add canary to your distro and check this
