### ISSUE TITLE
bluetooth mic stop working

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#1173]
Looks like after the latest update to 4.3.1 bluetooth mic stop wokring. I hear other party in bluetooth headset, by he doesn't hear me. The bluetooth headset works fine itself, and phone's mic also works fine.

**Comment by Viish** [comment]
Could you please attach logs showing the issue?

**Comment by 532910** [comment]
Log sent by e-mail.

**Comment by 532910** [comment]
4.3.0 is also broken

**Comment by Viish** [comment]
Have you tried the feature/kotlin_rewrite version?
In SDK 4.5.0-alpha we have reworked the way we handle audio routes.

**Comment by 532910** [comment]
1. I'd be happy to try kotlin_rewrite, but I have no time to setup android toolchain. Several attempts to build other android programs have failed. Do you have an apk?

2. I have the same issue on user's phone that I wouldn't want to experiment with.

**Comment by Viish** [comment]
I'll send you a nightly built APK when we will have merged the branch into master.

**Comment by Viish** [comment]
I just realized you can use our build artefact as test APK. Here's the latest one for feature/kotlin_rewrite branch: https://gitlab.linphone.org/BC/public/linphone-android/-/jobs/327197/artifacts/file/app/build/outputs/apk/debug/linphone-android-debug-4.3-alpha.246+7f9b21b5.apk
But I wouldn't recommend you to install in on any other device that yours, for tests purposes.

**Comment by 532910** [comment]
I have the same issue with kotlin rewrite.

**Comment by Viish** [comment]
Please send new logs with that version then.

**Comment by 532910** [comment]
Log sent by e-mail.

**Comment by Viish** [comment]
I don't see any issue. Bluetooth device is used and audio packets are sent & received by the app.

**Comment by 532910** [comment]
This issue is reproducible every call
1. On 3 different bt headsets (Plantronics Edge, Etymotic etyBLU2 and Xiaomi Mi Audio Receiver)
2. On 2 a bit different phones, both are OP3T running LineageOS 17.1, one with OpenGapps, the other with microG


Both https://github.com/vector-im/element-android and https://gitlab.com/axet/android-audio-recorder work fine.

**Comment by Viish** [comment]
From the logs audio is sent. Please attach logs from other end.

**Comment by 532910** [comment]
with bluetooth turned off it works fine, other end does knot nothing about bluetooth on this end

the other end can be asterisk echo test

**Comment by Viish** [comment]
Please reproduce between two devices running the APK I sent you and connected to sip.linphone.org proxy server, and send both logs. Otherwise I won't be able to help and I'll close the issue.

**Comment by 532910** [comment]
I'm agree

**Comment by Viish** [comment]
Closing until asked logs are attached.

**Comment by 532910** [comment]
4.3.1 from GPlay works fine on another phone (OP7pro) under OxygenOS based on Android 10

It looks like a LineageOS 17.1 issue, but strange that only Linphone is affected.

**Comment by 532910** [comment]
Sylvain, is there a way to investigate this issue. It affects me a lot.

Once again the facts that I have:

1. There is no issue with OP7pro with OxygenOS (Android 10)
2. This issue is reproducible only on two OP3T phones with LineageOS 17.1 (Android 10) one with microG another with OpenGAPPS.
3. All other apps work fine with bluetooth mic on both OP3T ([im.vector.app](https://github.com/vector-im/element-android), [com.github.axet.audiorecorder](https://gitlab.com/axet/android-audio-recorder), com.android.dialer, [com.grandstream.wave](https://play.google.com/store/apps/details?id=com.grandstream.wave))

**Comment by Viish** [comment]
I asked you for logs but you never sent them.
And as the issue only happens with Lineage OS and not the version of Android shipped with the device, it's really not a priority for me. You can always contact my company (Belledonne Communication) using the contact form on our website https://linphone.org/contact for a support or dev-assist contract.
