### ISSUE TITLE
Playing wav-file to the caller

### ISSUE THREAD

**Issue by Suncatcher** [BelledonneCommunications/linphone-android#1175]
Is it possible? I found some mentions about it on linphone-developers maillist (via linphonec?), but what about users?
Can it be done in GUI on PC or Android?

**Comment by Viish** [comment]
It is possible through the API, but there is no GUI way to do that in the Android app right now.

Check the doc for the Player object (you can get it using call.getPlayer()): https://linphone.org/snapshots/docs/liblinphone/4.5.0/java/

**Comment by Suncatcher** [comment]
Thx for clarification
