### ISSUE TITLE
Problem to integrate Jitsi Meet Sdk with linphone

### ISSUE THREAD

**Issue by SarfarazAhmed008** [BelledonneCommunications/linphone-android#1176]
I am using Jitsi meet api for video calling on linphone android app. I have followed jitsi meet handbook for integrating on linphone.
Here is my sample code:

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        URL serverURL;
        try {
            serverURL = new URL("https://meet.jit.si");
        } catch (MalformedURLException e) {
            e.printStackTrace();
            throw new RuntimeException("Invalid server URL!");
        }
        JitsiMeetConferenceOptions defaultOptions =
                new JitsiMeetConferenceOptions.Builder()
                        .setServerURL(serverURL)
                        .setWelcomePageEnabled(false)
                        .build();
        JitsiMeet.setDefaultConferenceOptions(defaultOptions);

        JitsiMeetConferenceOptions options =
                new JitsiMeetConferenceOptions.Builder().setRoom("linphone").build();

        //        jitsiMeetView = new JitsiMeetView(JitsiActivity.this);
        //        jitsiMeetView.join(options);

        //        setContentView(jitsiMeetView);
        JitsiMeetActivity.launch(this, options);
        finish();
    }
 
I have successfully made a call on debug mode, after making an apk on release mode, It refreshes activity when I attempt to make a video call and goes to home page. can anyone give me a guideline to solve this problem. I have tested the released apk version on Android 9,10 OS.

--After Debugging on release mode I have found this error

`
020-09-24 16:50:12.383 10364-10364/org.linphone E/AndroidRuntime: FATAL EXCEPTION: main Process: org.linphone, PID: 10364 java.lang.IllegalArgumentException: reportSizeConfigurations: ActivityRecord not found for: Token{2329006 ActivityRecord{cf5fae1 u0 org.linphone/.activities.JitsiActivity d-1 s-1 t-1 f}} at android.os.Parcel.createException(Parcel.java:1967) at android.os.Parcel.readException(Parcel.java:1931) at android.os.Parcel.readException(Parcel.java:1881) at android.app.IActivityManager$Stub$Proxy.reportSizeConfigurations(IActivityManager.java:8621) at android.app.ActivityThread.reportSizeConfigurations(ActivityThread.java:3360) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3318) at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2043) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop(Looper.java:224) at android.app.ActivityThread.main(ActivityThread.java:7096) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928) Caused by: android.os.RemoteException: Remote stack trace: at com.android.server.am.ActivityManagerService.reportSizeConfigurations(ActivityManagerService.java:10305) at android.app.IActivityManager$Stub.onTransact$reportSizeConfigurations$(IActivityManager.java:12560) at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2357) at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3841) at android.os.Binder.execTransact(Binder.java:750)
`

**Comment by Viish** [comment]
You are trying to replace calls to our Voip SDK by Jitsi's but keep using our app GUI?

**Comment by SarfarazAhmed008** [comment]
> You are trying to replace calls to our Voip SDK by Jitsi's but keep using our app GUI?

We are not trying to replace linphone Voip SDK. We want to integrate jitsi with linphone app and we are using linphone app GUI.

**Comment by Viish** [comment]
Sorry but I won't help you with that, it isn't an issue of our application (and I don't have any experience with jitsi SDK).
