### ISSUE TITLE
Peer to Peer Video Call between two Linphone on Public IP

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#1178]
@Viish ,

Hope you are doing well in this pandemic condition. 

I am facing one issue while establishing video call in P2P mode over Public IP. I am using FreeSwitch as Sip Server. Issue is that Call is getting established but no video and audio. If I try back to back call then video and audio is perfect.

For you reference I am attaching Linphone logs and SNGREP logs.

[Linphone_Peer2PeerCall_Behind_NAT_Callee.txt](https://github.com/BelledonneCommunications/linphone-android/files/5300841/Linphone_Peer2PeerCall_Behind_NAT_Callee.txt)

[3101-3104_FS_NATING.zip](https://github.com/BelledonneCommunications/linphone-android/files/5300853/3101-3104_FS_NATING.zip)

Any help would be appreciated.

Thanks in advance!

**Comment by Viish** [comment]
Hi,
I see you have enabled STUN but not ICE. Enable it, it may solve your issue.
Cheers,

**Comment by amit1576** [comment]
Hi @Viish ,

I had tried with enabling ICE but no success. I had defined "stun.linphone.org" as STUN server. 
Scenario are different with different ISP. 
For some ISP one way video, For Some ISP No audio and Video at all.

I have one doubt, is it technically possible to do a video call when end user are behind Firewall, Proxy ?

Please suggest how to solve this issue. 

Thanks,
Amit Sharma

**Comment by Viish** [comment]
Hi,
The obvious solution is not to do peer to peer call behind NAT...
Otherwise yes, it is possible to do audio & video calls as long as you are using a proxy server. I recommend you to try with our own service (https://www.linphone.org/freesip/home) which is free.
Cheers,

**Comment by amit1576** [comment]
Hi @Viish ,

I had tested calling between two user behind NAT with your service **"sip.linphone.org"** as you suggested. 

Following were the out come.

**1)** When I take two sip user connect via hot spot with my mobile network, call get established and after call establishment I stopped internet but wife of both the device were on, the calls continues to work. (means RTP was flowing P2P). So far so good. 👍 

**2)** When I take two sip user on different ISP then call is working back to back. Can I run this call also as P2P with your proxy or not. Means how can i configure that this call will run as P2P only with **sip.linphone.org.**

Logs are attached :

[BacktoBack.zip](https://github.com/BelledonneCommunications/linphone-android/files/5325872/BacktoBack.zip)

Thanks in advance.

**Comment by amit1576** [comment]
Hi @Viish ,

Any comment on this.

Thanks in advance.
Amit Sharma

**Comment by Viish** [comment]
I'm not sure I understand all you're saying but when a call is established, if ICE is enabled and a STUN server is configured, it will look for the shortest way to send packets to the remote. In your case it's directly sending the packet to the remote as they are on the same network. That's why when you shutdown your internet connection the call continues.
You can do this no matter the SIP service you are using, but this only works if both parties are on the same network.
Hope it clarifies.

**Comment by amit1576** [comment]
Hi @Viish ,

Yes, it is cleared now. Now I understood that in same network packet can be send directly to remote device but in case of different network the packet to remote party can be routed through sip server only. Means in different network call can be back to back only not peer to peer.

Thanks for clearing my doubt.

Thanks,
