### ISSUE TITLE
Native build for version 4.4.2 fails with BcToolbox

### ISSUE THREAD

**Issue by JitainSharma** [BelledonneCommunications/linphone-android#1181]
Take linphone-sdk repository from the gitlab, setup and make build native.
System OS: Ubuntu 18.x
Linphone-SDK: 4.4.2

Error:
```
Could not find a package configuration file provided by "BCTOOLBOX" with
any of the following names:
BcToolboxConfig.cmake
bctoolbox-config.cmake
```
Where, the file is generated as `bctoolboxConfig.cmake`, ho would I change the file name to be match with the above required name.

**Comment by Viish** [comment]
Check you have cloned the submodules correctly.
If you haven't, use `git submodule update --recursive --init` command.

**Comment by JitainSharma** [comment]
I have cloned the repository as:
`git clone https://gitlab.linphone.org/BC/public/linphone-sdk.git --recursive`

Should `git submodule update --recursive --init` command required to run again?

**Comment by Viish** [comment]
No, if you cloned using --recursive it shouldn't be needed, be you can do it just to be sure everything is there.
If that's not it, delete your build directory and try again.

**Comment by JitainSharma** [comment]
okay, Also I required to add H263 support, can you please share the steps to support it.

**Comment by Viish** [comment]
H263 isn't supported anymore. 
We were supporting it through FFMpeg but we no longer support it (it won't build for Android if you try to enable it in cmake params).
If you really need it, contact my company Belledonne Communications via https://linphone.typeform.com/to/RRDfNq and we will send you a quotation.
