### ISSUE TITLE
No RBT in case of G729 codec.

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#1182]
Hi @Viish ,

I am facing one more issue. When I have enabled G729 Audio codec only and call another linphone no RBT is there. But in same setup when I use other sip phone  RBT is there.

Can you suggest what can be the issue.

**Comment by Viish** [comment]
What do you mean by RBT?

**Comment by amit1576** [comment]
Hi @Viish ,

I mean to say ring back tone, while other party is ringing. In my case on G729 there remain silent till other party pick the phone.

**Comment by Viish** [comment]
Maybe your remote end doesn't send the RBT using G729 codec but another?
Please attach logs showing the issue.

**Comment by amit1576** [comment]
Hello @Viish ,

Please find attached log 

[G729_NO_RING_BACK_TONE.txt](https://github.com/BelledonneCommunications/linphone-android/files/5320192/G729_NO_RING_BACK_TONE.txt)

Thanks,
Amit Sharma

**Comment by Viish** [comment]
From your logs the remote party doesn't send a ring back tone but instead ask you to send early media.
Also note that your device never receives audio from the remote, either during early media or after the call is accepted, and ringback tone is sent by the remote as audio.

**Comment by amit1576** [comment]
Hi @Viish ,

The Ring back tone problem got resolved when I change parameter value from **"annexb=yes" to "annexb=no"** for G729 Codec. 
Can you please tell what is relevance of this parameter.

Thanks for your guidance.

**Comment by Viish** [comment]
Hi,
Check the RFC for reference: https://tools.ietf.org/html/rfc7261
Cheers,

**Comment by amit1576** [comment]
Hi @Viish ,

One more help required in this topic, How can i set **"annexb=no"** in android code.

Thanks,
Amit Sharma
