### ISSUE TITLE
No Video call on H264 on OnePlus 6T Mobile

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#1183]
Hi @Viish ,

I am facing one scenario, everything is working fine on every mobile device except one OnePlus 6T modal(Android 10). On this phone no remote video coming to me (My video is going to remote party) when I choose H264 codec else video call is working fine on VP8.

Can this issue be device specific.

Please suggest.

**Comment by Viish** [comment]
Yes this device might have a specific issue with the MediaCodec OpenH264 encoder implementation.
Please provide logs.

**Comment by JitainSharma** [comment]
Linphone SDK : 4.5
Issue : Call audio & video not working over cellular network
Devices : Samsung M21, Nokia one

Same on my side as well to all devices when switch to cellular network, where else it works fine on wifi.

**Comment by Viish** [comment]
Closing as they were no logs provided as asked. Feel free to attach them later, I'll reopen the issue.
@JitainSharma this isn't the same issue.
