### ISSUE TITLE
ChatMessage Content-Type can't be modified

### ISSUE THREAD

**Issue by fang123123** [BelledonneCommunications/linphone-android#1184]
Hi,
I am facing a problem. when I use the method of setContentType() to modify the message content type, then i check it by the method of getContentType(), it does work. But the type is still text/plain in the sip message captured by wireshark.
Could you give me some advises. I will  appreciate it!

**Comment by Viish** [comment]
Hi,
There is a mecanism in the SDK that replaces an invalid content type per 'text/plain' at sending time.
What are you trying to set? Can you attach SDK logs showing the issue?
Cheers,

**Comment by fang123123** [comment]
Thank you for reply.
I suddenly find the problem can be fixed by exchanging the code order.
before
`
message.setContentType("text/html");
message.addTextContent("<html><head></head><body>example</body></html>");
`
now
`
message.addTextContent("<html><head></head><body>example</body></html>");
message.setContentType("text/html");
`
There is a new question, When I send the message by SDK, I find that more than ten sip messages are captured by wireshark and the only different place of these is the field of identification.
I wonder why it is?

**Comment by Viish** [comment]
Hi,

SIP messages are challenged by SIP proxy. So when you send a message, it will probably send back a 401 asking for authorization and the UA will answer this 401 by sending the message again with authentication headers.
If you are using UDP as transport protocol, packet can (and probably will) be lost at some point, so the UA will send them back until it receives a ACK that the proxy has received them. So yes you can have more than 10 messages sent.
I strongly recommend you to switch to TCP or even better TLS to fix that.

Regarding the workaround you found for your issue, I just understood that you aren't using the best API for that.
Indeed addTextContent creates a Content with text/plain content type and adds it to the message. When the message is sent, it computes it's content type by looking at all contents it contains.
The best way to do that is to create a Content, fill it and then add it to the message using message.addContent().
Do not set the content type on the chat message itself.

Cheers,
