### ISSUE TITLE
App goes in hibernation and no call can be received at that time.

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#1186]
Hi @Viish ,

I am facing some issue with Linphone app, 
1) When my phone is idle the app goes in hibernation at that time if anyone try to reach my number nothing happens at my side as well as caller side.
2) When my phone reboot the app does not auto start and i need to launch it manually to function.
**3) When my network is weak or lost and somebody try to call me in between, caller will get user not reachable message but I have not received any notification that someone called me while i was not reachable.**
4) Sometime caller do not get any ring back tone but destination received call.

Please suggest how can above things be resolved.

Thanks,
Amit Sharma

**Comment by Viish** [comment]
Hi,
The only way to solve this issues is to use push notifications. 
Another possible solution is to keep a foreground service notification (see background mode in advanced settings) but some phones will kill the process anyway after some time...
Cheers,

**Comment by amit1576** [comment]
Hi @Viish ,

From following link "https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/Configuration/Push%20notifications/", I can understand that FlexiSip can push notification to app when app are un-available.  I am using FreeSwitch as Sip server, Can I implement Push notification with Free Switch to handle above problem.

Please suggest..

Thanks in advance.

**Comment by Viish** [comment]
No, to my knowledge freeswitch doesn't handle firebase push notifications.
However you can install a flexisip to act as a push notification gateway for your freeswitch: https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/HOWTOs/Push%20Gateway/

**Comment by amit1576** [comment]
Hi @Viish ,

I have used Flexisip service(I had created account on Flexisip server) with standard linphone application from app store. My expectation was that Flexisip push notification will wake up my phone from hibernation but that was not the case. My app did not wake up and caller just receive silence.

Do I need some more setting to be done to activate Push Notification with Flexisip server.

Please suggest.

**Comment by Viish** [comment]
Have you checked push are enabled in Network section & in account section of the settings?

**Comment by amit1576** [comment]
Yes @Viish, These settings are on in both caller side and called side.

**Comment by amit1576** [comment]
Hi @Viish ,

I have done one more experiment, I am using FreeSwitch as sip server and enabling option in FreeSwitch to verify that either Linphone app able to acknowledge sip server or not, but after studying Wireshark packets I came to know after sometime Linphone stop acknowledging option packet. 

Please let us know why this is happening. 

Logs is uploaded on Mega 

https://mega.nz/file/9So3yCLC#qrneim2_QyGAhI5SjxQMcFHD2sii_IYXZ7mMGr5y5Vc

Thanks in advance.

**Comment by Viish** [comment]
> [org.linphone/linphone-android] WARNING [Manager] Setting network reachability to False to prevent unregister and allow incoming push notifications

This log means the app won't listen to network events and won't send any, so yes that won't help...
Change your app code to not do that.
Please note that I won't help you develop your app, I'm only here to help if there are issue with our SDK or our app.

**Comment by amit1576** [comment]
Hi @Viish ,

I am using standard linphone app only with Flexisip server. I just want to understand that either standard Linphone works in background or not using Push notification. As you suggested that try once with Flexisip server, so I had tried with standard linphone and Flexisip but app was not able to receive call in background.

My intention was to get the clue, where i am doing wrong.

Thanks for your advice as always.

Cheers.
