### ISSUE TITLE
SIP account: can't get connection 

### ISSUE THREAD

**Issue by starbrights** [BelledonneCommunications/linphone-android#1189]
For some reason I can't get a connection. It fails every time. Is there any magic beside input of account, domain and password?
It starts with connection will be established but after (sometimes long = few sec) time it fails.
Beside the 3 items I tried different transport protocols. I tried each of it with no change.

Also there is mentioned that after each change password has to be retype? I tried that too but found this is strange as domain is typed in AFTER the password (going top to down in the list).

I used sipgate.de and freevoipdeal.com as Domains on a Samsung Oreo (8.0) device. Any help is welcome.

**Comment by Viish** [comment]
Hi,
Password is hashed using the username & domain, so when one of the two changes you have to re-type your password.
Please attach logs of the connection issue.
Cheers,

**Comment by starbrights** [comment]
I have 2 devices, one with root/microG, the other stock ROM (no root). To make sure it is not any other issue with microG I would start with stock - but how to see a log? Isn't there root needed? I see some option "Debug" but it seems to upload it to your server? Can you explain more in detail what exactly to do?

**Comment by starbrights** [comment]
Get an error: 18010 stream connect failed Network is unreachable. Cannot connect to [TLS://sipgate.de:5061]

**Comment by Viish** [comment]
> Protocol has to be UDP (but TLS is standard).

Yes TLS is way better but there are many SIP providers still using UDP only, that's a shame...

> The only drawback - call out seems to be only from "standard" account, right?

Yes, currently the Android app uses the default proxy config to make outgoing calls, unless the domain of the called URI matches another proxy config and not the default one.
