### ISSUE TITLE
getChatRooms giving null array

### ISSUE THREAD

**Issue by IshaanKr** [BelledonneCommunications/linphone-android#1191]
I am using `mCore.getChatRooms()`

But getting an array of 0 length.

but `linphone.db` when extracted from device contains many entries.

How is this possible? Is anything I am doing wrong?

**Comment by IshaanKr** [comment]
Creating chatRoom with this:
`ChatRoomParams params = core.createDefaultChatRoomParams();
            params.enableEncryption(false);
            params.enableGroup(false);

            Address[] participants = new Address[1];
            participants[0] = sRemotePartyAddress;
            
            mChatRoom =
                    core.createChatRoom(
                            params,
                            "TestChat",
                            participants);`

**Comment by IshaanKr** [comment]
`core.getChatRooms` returning array of 0 length 
BUT
`mChatRoom = core.findOneToOneChatRoom(myAddress, sRemotePartyAddress, false);`
returns a valid `ChatRoom`

**Comment by Viish** [comment]
Hi,

Please note that by default getChatRooms() doesn't return empty chat rooms.
To change that set the `hide_empty_chat_rooms` config option in the `misc` section to `0`.

Also we don't return the chat rooms for which the localAddress doesn't match a configured proxyConfig.
To change that set the `hide_chat_rooms_from_removed_proxies` config option in the `misc` section to `0`.

Cheers,

**Comment by IshaanKr** [comment]
What is an empty chat room?
ChatRoom with no participants - because my chatroom has members(me and 1 other)
ChatRoom with no history - because I also had chat in the ChatRoom - because mChatRoom.getHistory(0) gives valid list of all messages

**Comment by Viish** [comment]
> What is an empty chat room?

An empty chat room is a chat room without any message in it.

> mChatRoom.getHistory(0) gives valid list of all messages

Then you are in scenario n°2: no proxy config matching local address.

**Comment by IshaanKr** [comment]
There is a method to create ChatRoom with a particular proxy config address
`public ChatRoom createChatRoom(@Nullable ChatRoomParams params, @Nullable Address localAddr, @NonNull Address[] participants);`

but how to get ChatRooms with a particular proxy config?
Because I can find only one method with no parameters
`synchronized public ChatRoom[] getChatRooms();`

**Comment by Viish** [comment]
> but how to get ChatRooms with a particular proxy config?

You can't do that directly yet, but that's a good idea.

**Comment by IshaanKr** [comment]
I need to populate all the chatRooms for the user to select one of them and the proceed with chat with the selected one.

This method is useful if I am searching for a particular chatRoom but I need to get all the ChatRooms.

I am following linphone-android but the chatRooms are created with above method and retrieved by getChatRooms() is working fine, checked `linphonerc_factory` but didn't find any option of hide_empty_chat_rooms

**Comment by Viish** [comment]
When a rc setting isn't present in the file, the default value applies. For both settings I mentionned the default value is true.
So to disable you have to add it manually in the linphonerc_factory.
