### ISSUE TITLE
Linphone android sample works perfect on Wifi network but when I try with 4G network it doesn't work at all. No state change

### ISSUE THREAD

**Issue by swaponsust** [BelledonneCommunications/linphone-android#1192]
Linphone android sample works perfect on Wifi network but when I try with 4G network it doesn't work at all. No state change when register SIP request to server. In wifi network everything is working perfectly. Anyone having this issue? Is there any configuration issue for this error? Looking for some help.

**Comment by Viish** [comment]
Probably you try to connect to a proxy server using UDP, and your 4G network doesn't allow it (or packets get lost).
Change your proxy config to allow TLS as transport protocol and configure your account in the app using TLS, it will work.

**Comment by swaponsust** [comment]
Interesting thing is Linphone main app works for both wifi and 4G network but Linphone sample app not works.
