### ISSUE TITLE
How to listen when the state of ChatMessage change?

### ISSUE THREAD

**Issue by IshaanKr** [BelledonneCommunications/linphone-android#1193]
When a `ChatMessage.State` changes from 0(Idle) to 2(Delivered) or 7(Displayed) or whatsoever, how to listen for this state change?

ChatRoomListener doesn't have any such method `onChatMessageStateChanged` 

there is one method `onChatMessageSent` but it is only triggered once. I need to listen for state change.

**Comment by Viish** [comment]
Use this: https://linphone.org/snapshots/docs/liblinphone/4.5.0/java/org/linphone/core/ChatMessageListener.html#onMsgStateChanged-org.linphone.core.ChatMessage-org.linphone.core.ChatMessage.State-
