### ISSUE TITLE
Linphone Leaves registration after expire time in background mode.

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#1194]
Hello @Viish ,

I am facing one issue while using linphone in background mode. What I have experienced is that I have set expire time to 3600 and I checked for next 3600 second the linphone works fine in background mode, but when i try to reach it after 3600 second call not landing in background mode.

Default Expire for Linphone is 3153600 .

Logs has been attached 

[16025609152f053ac6365dfed7da08d75b4f16f03e.gz](https://github.com/BelledonneCommunications/linphone-android/files/5368988/16025609152f053ac6365dfed7da08d75b4f16f03e.gz)

Thanks,
Amit Sharma

**Comment by Viish** [comment]
Hi,

I don't know what you do but you destroy the Service. When using background mode (which means foreground service with notification) you must keep it alive to be able to receive calls & update registration.
```
2020-10-12 09:47:08:663 [org.linphone/linphone-android] MESSAGE [Service] Destroying
2020-10-12 09:47:08:663 [org.linphone/linphone-android] MESSAGE [Service] Destroying video overlay
2020-10-12 09:47:08:663 [org.linphone/linphone-android] MESSAGE [Context] Destroying
```

By the way, when using push, as you can't update the REGISTER on a regular basis you have to use very long expires like we do.

Also, I suggest you switch to feature/kotlin_rewrite branch as it is way better than the current master.

Cheers,

**Comment by amit1576** [comment]
Thanks @Viish .

**Comment by attermann** [comment]
Hi @Viish,

I am attempting to integrate linphone-android with Opensips using their new RFC 8599 implementation.  In this scenario Opensips will send a push notification when registration is about to expire, as well as when a call is received, and expects the client to re-register immediately upon receipt of the push notification.  The problem I'm having is that linphone-android doesn't seem to reliably respond to push notifications with a REGISTER, and I suspect that maybe it wasn't designed this way with RFC 8599 support.  I would really appreciate if you could explain how linphone-android (and linphone-ios) are designed to respond to push notifications, and if it's possible to make it compliant with RFC 8599.

Thanks,

Chad.
