### ISSUE TITLE
Multiple history call log for same call

### ISSUE THREAD

**Issue by JitainSharma** [BelledonneCommunications/linphone-android#1195]
Linphone SDK : 4.5+
Android OS : 6, 7, 8, 9, 10

When a call received via push, sometimes app shows multiple entry of the same call as:
Call 1 received at 11:47
Call 1 missed at 11:47
Call 2 received at 11:45
Call 2 missed at 11:45

Is there some settings or way to prevent it. The code use to get call history is
`core?.callLogs?.asList()`

**Comment by Viish** [comment]
Please attach logs, I think your problem is with the calls itself.

**Comment by JitainSharma** [comment]
It's seems that on same callId, multiple records are created and it shows duplicate.
Like, the same call has two records one with status **Success** and other with **EarlyAborted**.

To resolve it, I have applied the filter over the callId.
