### ISSUE TITLE
No sip domain in contact

### ISSUE THREAD

**Issue by dronmaxman** [BelledonneCommunications/linphone-android#1197]
Hey. 
I cannot save a contact with the sip domain in the address book.
For example sip: 5555@sipnet.ru. Only the number is saved. 

How can I call another SIP domain?

If I receive a call from the sipnet.ru domain, then I can call back from the call list. If you save this number, the domain is not saved and the domain is substituted sip.linphone.org.

**Comment by Viish** [comment]
Hi,
Don't worry it just we currently display only the username of the SIP address for visibility.
If you try to call it will call on the domain you entered. You can check using your native contact app (or any other contact app).
For next release I fixed the display issue so if you enter a SIP URI not on the default domain it will be fully displayed.
Cheers,
