### ISSUE TITLE
Alternate of Firebase Messaging 

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#1198]
Hello,

Please give me some idea what will be the best alternate of Firebase Messaging service for Push Notification. I am using FreeSwitch as sip server so . Please guide any alternate which I can use instead of Firebase Messaging.

Can socket connection between client and server be an alternate?

Please suggest ...

Thanks,

**Comment by Viish** [comment]
Hi,

To my knowledge there is only FCM (firebase cloud messaging) that can really be used on all Android devices correctly, to wake up an app from doze mode etc...
All other methods won't work if not whitelisted by the OS.
However you might find push SDK for specifics brands like Huawei, but they won't work on devices from other brands.

Cheers,

**Comment by amit1576** [comment]
Hi @Viish ,

Thanks for your suggestion. I am totally agree FCM is best way to wake up an app. But I have one situation where my linphone app can not connect to internet, my linphone app will be deployed in an intranet environment.  Means app can reach to Sip Server but can not have internet access. If that is the case what can be done to wake up linphone from doze mode.

Please suggest what best can be done in this situation.

I am planning TCP connection but it may be resource hungry and might not be accepted by OS.

Please guide what can be done in this type of environment.

Thanks in advance.

**Comment by Viish** [comment]
Your TCP socket will be killed by the DOZE mode of your app after a while, you can't do much about that.
To my knowledge there is no solution for your problem, what you want to achieve can't be done.

**Comment by amit1576** [comment]
Hi @Viish ,

Just going through Linphone Technical corner. I found this **
https://linphone.org/technical-corner/voip-tunnel**. You have developed
some commercial proprietary solution for VOIP Tunnel.

Can this solve my purpose and if yes what is the quotation.

Thanks in advance.

**Comment by Viish** [comment]
No, this isn't what the tunnel is for.
