### ISSUE TITLE
Flexisip Push gateway

### ISSUE THREAD

**Issue by dipenpatel235** [BelledonneCommunications/linphone-android#12]
i have successfully configured flexisip server.
i am also able to send push notification manually using flexisip_pusher command.

now i have do that automatic so i have not any clu how i can archive that ?
1. i have added google gcm api key in flexisip.conf
2. also added database for all user and password 

Now i don't know how communicate sip server and flexisip server ?
How Flexisip server Get token of android device and Flexisip can send push notification?
So Please give some help so any documentation link if you have...

Thanks

**Comment by DatBewar** [comment]
Hello,

If Android device have a google gcm token will give it on register to flexisip server

You can find more informations about push notification module of Flexisip here:
https://wiki-test.linphone.org/xwiki/wiki/public/view/Flexisip/Modules%20Reference%20Guide/PushNotification

Best regards

**Comment by julianprs** [comment]
Hi @dipenpatel235 are you able to share your config?

I am also trying to get it working.
