### ISSUE TITLE
centos 7 64bit compile problem

### ISSUE THREAD

**Issue by javaandme** [BelledonneCommunications/linphone-android#120]
on centos  have a problem:

CMake Error at CMakeLists.txt:44 (find_package):
  By not providing "FindBCTOOLBOX.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "BCTOOLBOX", but CMake did not find one.

  Could not find a package configuration file provided by "BCTOOLBOX" with
  any of the following names:

    BCTOOLBOXConfig.cmake
    bctoolbox-config.cmake

  Add the installation prefix of "BCTOOLBOX" to CMAKE_PREFIX_PATH or set
  "BCTOOLBOX_DIR" to a directory containing one of the above files.  If
  "BCTOOLBOX" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!

have  a long time to reslove, what's wrong this question? thanks,anyone too

**Comment by DatBewar** [comment]
Hello it's fixed 706913502df7431a970877bed06dedcb2a9e2676

**Comment by javaandme** [comment]
Ok,Thanks very much,Today,I hava compiled successfully,
