### ISSUE TITLE
SIP registration failed when network switch

### ISSUE THREAD

**Issue by swaponsust** [BelledonneCommunications/linphone-android#1202]
Android Linphone app works both Wifi and 4G network but when I switch network it stop works. Logs shows network reachable but can't able to complete the register as a result no incoming callback.

**Comment by Viish** [comment]
Please attach SDK logs showing the issue.

**Comment by swaponsust** [comment]
I don't know whether it is right approach or not but it works for me: I'm calling refreshRegisters in onRegistrationStateChanged.

**Comment by Viish** [comment]
No, you shouldn't have to do that.

What version of the SDK are you using? Do you have set the `auto_net_state_mon=1` in the `[sip]` of your config file?
Do you reproduce with our app from the Play Store?

**Comment by Viish** [comment]
Closing as no update.
