### ISSUE TITLE
Preserve Call logs after logout

### ISSUE THREAD

**Issue by JitainSharma** [BelledonneCommunications/linphone-android#1203]
Linphone SDK: 4.5

Each time I logout the user using the following code of line executed on logout:
` mCore?.clearAllAuthInfo()
        mCore?.clearProxyConfig()
        mCore?.refreshRegisters()`

It also clear the call log history as well. 
How would I preserve the call logs and handle myself when to delete it.

**Comment by Viish** [comment]
Unless you call `linphone_core_clear_call_logs()` there is no reason for the history to go away.
How do you get the call history?

Anyway what you do with your 'logout' function is wrong. You shouldn't delete auth_infos & proxy_configs for that. The proper logout way is:
```
proxyConfig.edit();
proxyConfig.enableRegister(false);
proxyConfig.done();
```
And the same with true to enable it back.

**Comment by JitainSharma** [comment]
Thanks, this is working.
Now, when I logout the user and login different user. The old user call log still shows, once the app is killed and open again, now all call logs clear.

How do I clear the call logs if different user logs in.

**Comment by Viish** [comment]
Actually mCore.clearCallLogs does work but there is a cache that isn't cleaned. I'll fix that.

**Comment by JitainSharma** [comment]
Okay, Is there way in current SDK 4.5 to clear the cache.

**Comment by Viish** [comment]
> Okay, Is there way in current SDK 4.5 to clear the cache.

No.
