### ISSUE TITLE
please make version/build copyable

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#1205]
![Screenshot_20201022-121227_Linphone_(debug)](https://user-images.githubusercontent.com/14617699/96850781-e0bf1580-145f-11eb-8265-61d30fa9f70d.png)

**Comment by Viish** [comment]
commit bfb42a44b17f517bf0e9f0a209f99379341eda74 (HEAD -> feature/kotlin_rewrite, origin/feature/kotlin_rewrite)
Author: Sylvain Berfini <sylvain.berfini@belledonne-communications.com>
Date:   Thu Oct 22 11:25:26 2020 +0200

    Allow to select & copy app/SDK version
