### ISSUE TITLE
bad design: too many horizontal dividers

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#1206]
![image](https://user-images.githubusercontent.com/14617699/96943584-443d5780-14e1-11eb-9527-c521b44b40f9.png)
![image](https://user-images.githubusercontent.com/14617699/96943860-faa13c80-14e1-11eb-94f2-66f48580ef9d.png)

compare with com.android.dialer or any other material app
![image](https://user-images.githubusercontent.com/14617699/96943872-02f97780-14e2-11eb-9075-fc29d99a2a4a.png)
![image](https://user-images.githubusercontent.com/14617699/96943882-08ef5880-14e2-11eb-98a8-e2c95228b773.png)

**Comment by Viish** [comment]
If you aren't happy feel free to make your own UI.

**Comment by 532910** [comment]
This is not about happy, unhappy, like or dislike. This is about usability and clearness.

**Comment by Viish** [comment]
Our UI is made by professional designers. You might see apps that do things differently, but you can also see apps that do like we do.

**Comment by 532910** [comment]
I'm sure you have designers, but I doubt their professionalism.

BTW on ios these lines are darker and looks less annoying.
