### ISSUE TITLE
initials are shown for contact with photo

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#1207]
![image](https://user-images.githubusercontent.com/14617699/96944057-7f8c5600-14e2-11eb-8191-83703d3022dc.png)

yep, the contact image is transparent png

**Comment by Viish** [comment]
commit 43623c50f7731d9c3658ce513502dec2aa27782c (HEAD -> feature/kotlin_rewrite, origin/feature/kotlin_rewrite)
Author: Sylvain Berfini <sylvain.berfini@belledonne-communications.com>
Date:   Fri Oct 23 10:12:28 2020 +0200

    Fixed initials being visible behind avatar if transparent
