### ISSUE TITLE
Open phone links with linphone

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#1208]
![image](https://user-images.githubusercontent.com/14617699/97121909-cbcdd500-1732-11eb-9b84-287e2cdd668a.png)

**Comment by Viish** [comment]
Linphone already registers itself for sip, tel and imto schemes.
What is the type of URI you are trying to use?

**Comment by 532910** [comment]
I don't know ):
The screenshot is the result of tapping `+7 123 456-78-90` in [Element](https://github.com/vector-im/element-android) that  shows it as a link.

Fenix and org.lineageos.jelly open tel links in com.android.dialer instantly, with no options.
For sip links fenix does nothing, org.lineageos.jelly googles it.

I have no defaults set for linphone, gs wave or android dialer.

**Comment by Viish** [comment]
Are you using the kotlin version or the release one?

**Comment by 532910** [comment]
Both are installed on the phone.

**Comment by Viish** [comment]
Ok then until I know which scheme is used I can't do more.

**Comment by 532910** [comment]
You can reproduce trying to open a link in Element.
