### ISSUE TITLE
About AndroidVideoWindowImpl problem

### ISSUE THREAD

**Issue by xavierwu824** [BelledonneCommunications/linphone-android#1210]
Hello,

I had developed one android app based on Linphone SDK and it works well until  upgrading Linphone SDK to 4.4.2. When beginning a video call will causes an exception. But when I put this line "displaytype=MSAndroidTextureDisplay" to configuration file and change local and remote view to TextureView, it works fine.

But if I use TextureView, I couldn't get the camera raw data. Due to some reasons , I will get the camera raw data and apply some effects to raw data. Besides, before upgrading to 4.4.2, what I use is 4.1.0 SDK. The 4.1.0 works fine.
I can get camera raw data from AndroidVideoApi9JniWrapper.startRecording method and apply the effect to raw data and transfer the data I modified to the other side by calling AndroidVideoApi5JniWrapper.putImage method.

The reason I don't use 4.1.0 anymore is that video quality is poor and I've  tested all Linphone SDKs, it seems that 4.4.2 is acceptable. 

So here is the thing, if I use 4.4.2, how to get camera raw data and how to transfer the data I've modiefied to the other side?

crash log is attached. 

If you can provide me with some ideas, I would appreciate it.
Thanks in advance.

[Linphone4.4.2.log](https://github.com/BelledonneCommunications/linphone-android/files/5455883/Linphone4.4.2.log)

**Comment by xavierwu824** [comment]
By the way, the setting about local preview and remote video view is as the attachment.
[androidVideoWindowImpl.log](https://github.com/BelledonneCommunications/linphone-android/files/5455921/androidVideoWindowImpl.log)

**Comment by Viish** [comment]
Hi,
If you want to alter captured images before they are sent, here's where to do it:
https://gitlab.linphone.org/BC/public/msandroidcamera2/blob/master/android-camera2-capture.cpp#L214
Cheers,

**Comment by xavierwu824** [comment]
Hi,

so, displaytype=MSAndroidOpenGLDisplay is not supported anymore?

**Comment by Viish** [comment]
No, we strongly recommend against using it, but is it still there for backward compatibility purposes.

**Comment by xavierwu824** [comment]
Hi,

But when I use 'MSAndroidOpenGLDisplay' this configuration, it will  cause an exception and seems like no backward compatibility. I had pasted my AndroidVideoWindowImpl setting before, or could you teach me how to use the 'MSAndroidOpenGLDisplay' this configuration correctly ?

**Comment by Viish** [comment]
You have the following exception:
`2020-10-29 11:29:29.989 31612-31612/co.jp.atena.wappli2 A/p.atena.wappli: java_vm_ext.cc:570] JNI DETECTED ERROR IN APPLICATION: can't call void android.graphics.SurfaceTexture.setDefaultBufferSize(int, int) on instance of org.linphone.mediastream.video.AndroidVideoWindowImpl
2020-10-29 11:29:29.989 31612-31612/co.jp.atena.wappli2 A/p.atena.wappli: java_vm_ext.cc:570]     in call to CallVoidMethodV
2020-10-29 11:29:29.989 31612-31612/co.jp.atena.wappli2 A/p.atena.wappli: java_vm_ext.cc:570]     from void org.linphone.core.CoreImpl.setNativePreviewWindowId(long, java.lang.Object)`
because you are trying to use the AndroidVideoWindowImpl legacy object but with the current camera2 capture module.

If you want to use AndroidVideoWindowImpl, disable Camera2 plugin when building the SDK: `cmake .. -DLINPHONESDK_PLATFORM=Android -DENABLE_CAMERA2=NO`

**Comment by xavierwu824** [comment]
great.  I will try this first, thanks.

**Comment by xavierwu824** [comment]
Hello,

I cloned the master branch and used the configuration you provided and builded out '4.5.0-alpha.206+bcd5a8c' sdk. Luckily, MSAndroidOpenGLDisplay works but I found that the Core.getVideoDevicesList() method only can get 'StaticImage: Static picture' this device, so I cannot see preview window. Even I enforced to pass "Android0" or "Android1" to Core.setVideoDevice() method still didn't get any luck.

Would you have any ideas about this?

The attached log is retrieved from using 4.5 sdk device.
[1106_linphone_no_preview.log](https://github.com/BelledonneCommunications/linphone-android/files/5498633/1106_linphone_no_preview.log)

Any hints or suggestions would be appreciated, thanks.

**Comment by xavierwu824** [comment]
By the way, this phone  model is "SOV37" and android OS is 10. This phone works well when I use 4.1 sdk and MSAndroidOpenGLDisplay configuration. I had also referenced the linphone-android git repository to see how to switch camera under 4.5 environment, but it seems like no difference from 4.1.

**Comment by Viish** [comment]
It's actually an issue in our SDK. I've made a fix on fix/legacy_video_capture branch, will be merged into master soon.

**Comment by xavierwu824** [comment]
You are the man! It works!! You save my time. Thanks so much!! Have a nice day!!

**Comment by Viish** [comment]
You're welcome 😁
