### ISSUE TITLE
Failed to initialize video/hevc, error 0xfffffffe

### ISSUE THREAD

**Issue by Jasperben** [BelledonneCommunications/linphone-android#1211]
10 W MediaAnalyticsItem: Unable to record: [1:codec:0:-1::0:-1:1:0:3:android.media.mediacodec.codec=OMX.MTK.VIDEO.DECODER.AVC:android.media.mediacodec.mode=video:android.media.mediacodec.secure=0:] [forcenew=0]
10-29 16:12:25.970 25610 25610 W MediaCodec-JNI: try to release MediaCodec from JMediaCodec::~JMediaCodec()...
10-29 16:12:25.970 25610 25610 W MediaCodec-JNI: done releasing MediaCodec from JMediaCodec::~JMediaCodec().
10-29 16:12:25.971 25610 25610 W System.err: java.lang.IllegalArgumentException: Failed to initialize video/hevc, error 0xfffffffe
10-29 16:12:25.972 25610 25610 W System.err: 	at android.media.MediaCodec.native_setup(Native Method)
10-29 16:12:25.972 25610 25610 W System.err: 	at android.media.MediaCodec.<init>(MediaCodec.java:1811)
10-29 16:12:25.972 25610 25610 W System.err: 	at android.media.MediaCodec.createEncoderByType(MediaCodec.java:1777)
10-29 16:12:25.972 25610 25610 W System.err: 	at org.linphone.core.FactoryImpl.createCore3(Native Method)
10-29 16:12:25.973 25610 25610 W System.err: 	at org.linphone.core.FactoryImpl.createCore(Factory.java:746)
10-29 16:12:25.973 25610 25610 W System.err: 	at org.linphone.LinphoneManager.startLibLinphone(LinphoneManager.java:356)
10-29 16:12:25.973 25610 25610 W System.err: 	at org.linphone.LinphoneContext.start(LinphoneContext.java:207)
10-29 16:12:25.974 25610 25610 W System.err: 	at org.linphone.service.LinphoneService.onStartCommand(LinphoneService.java:90)
10-29 16:12:25.974 25610 25610 W System.err: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3698)
10-29 16:12:25.974 25610 25610 W System.err: 	at android.app.ActivityThread.access$1700(ActivityThread.java:206)
10-29 16:12:25.974 25610 25610 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1709)
10-29 16:12:25.974 25610 25610 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-29 16:12:25.975 25610 25610 W System.err: 	at android.os.Looper.loop(Looper.java:193)
10-29 16:12:25.975 25610 25610 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6702)
10-29 16:12:25.975 25610 25610 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
10-29 16:12:25.975 25610 25610 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
10-29 16:12:25.975 25610 25610 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
10-29 16:12:25.983 25610 25666 I OMXClient: IOmx service obtained
10-29 16:12:25.984   398  4126 I OMXMaster: makeComponentInstance(OMX.MTK.VIDEO.DECODER.HEVC) in omx@1.

**Comment by Viish** [comment]
Hi,
This is expected on all Android OS that don't suppor H265 codec through MediaCodec.
Even if there is a crash stack trace in the logs, it's only a "warning", so there is no issue here.
Cheers,
