### ISSUE TITLE
Linphone Android push notifications

### ISSUE THREAD

**Issue by gregperezz** [BelledonneCommunications/linphone-android#1212]
Hi @Viish, I am trying to use Flexisip push gateway as a front-end server to my SIP service provider. I want to enable push notifications on my linphone android app. When the application is in background mode, Flexisip will inform the app via Firebase. For this configuration, I guess I have to register my application to the machine on which Flexisip is working. This way all my SIP messages will be directed from Flexisip to my backend server (including register message). I couldn't find from the Flexisip documentation, how should I configure my backend server to Flexisip.conf?

Thank you.

**Comment by Viish** [comment]
Hi,
Check the "Requirements for the backend sip server" of our wiki page about flexisip push gateway.
We don't have more doc than that as it depends a lot on your backend proxy server and we don't have a real experience on any of them.
Cheers,
