### ISSUE TITLE
Linphone ZRTP Clarification

### ISSUE THREAD

**Issue by jame-ux** [BelledonneCommunications/linphone-android#1219]
Hi,

I am trying to build a SIP architecture using Asterisk and Linphone. So far, I have tested it using my local machines, i.e, inside LAN. I have forked linphone-android from Github to Android Studio and built the project to make it work in two android phones. The backend SIP framework is Asterisk on Ubuntu. It has also got a self-signed TLS certificate. So, far it is working for audio calls, voice calls and instant messaging.

I have tried to enable ZRTP encryption (peer to peer) inside the android app. I am not sure how it works through I have read about ZRTP in the internet.

It would be beneficial if someone can clarify how to make ZRTP work in Linphone. 

Thank you.

**Comment by Viish** [comment]
Hi,
I recommend you to read ZRTP RFC: https://tools.ietf.org/html/rfc6189
To make it work you simply need two clients with ZRTP media encryption enabled in the settings.
Cheers,
