### ISSUE TITLE
Error compiling sqlite3 submodule.

### ISSUE THREAD

**Issue by alexiagonzalez** [BelledonneCommunications/linphone-android#122]
Hi, (and excuse my english please...)

I'm trying to mount the Linphone android project on **Android Studio** (**MAC**), and I'm getting an error that I can't resolve... I'm really stuck...

I clone the project from the repository, I try to follow the compilations instructions of the readme.md file, executing a "prepare.py" for all codecs, but in the "make" step, I always get the same error (below) about **sqlite3**.

Anyway, after the error, I try to import the project in Android Studio, but other errors like "Finish can only be called once." appears.

Could I be making something wrong in some step? or could be any missing step the reason of that error? I would love any help... I'm really desperate... Thanks in advance. 

The console error is:

> [ 37%] Performing build step for 'EP_sqlite3'
Scanning dependencies of target sqlite3
[ 50%] Building C object CMakeFiles/sqlite3.dir/sqlite3.c.o
/Users/alexgonzalez/Repositorio/Git/LA/submodules/externals/sqlite3/sqlite3.c:23552:40: error: use of undeclared identifier 'mmap'
  { "mmap",       (sqlite3_syscall_ptr)mmap,     0 },
                                       ^
/Users/alexgonzalez/Repositorio/Git/LA/submodules/externals/sqlite3/sqlite3.c:23587:22: error: invalid application of 'sizeof' to an incomplete type 'struct unix_syscall []'
    for(i=0; i<sizeof(aSyscall)/sizeof(aSyscall[0]); i++){
                     ^~~~~~~~~~
/Users/alexgonzalez/Repositorio/Git/LA/submodules/externals/sqlite3/sqlite3.c:23596:22: error: invalid application of 'sizeof' to an incomplete type 'struct unix_syscall []'
    for(i=0; i<sizeof(aSyscall)/sizeof(aSyscall[0]); i++){
                     ^~~~~~~~~~
/Users/alexgonzalez/Repositorio/Git/LA/submodules/externals/sqlite3/sqlite3.c:23623:20: error: invalid application of 'sizeof' to an incomplete type 'struct unix_syscall []'
  for(i=0; i<sizeof(aSyscall)/sizeof(aSyscall[0]); i++){
                   ^~~~~~~~~~
/Users/alexgonzalez/Repositorio/Git/LA/submodules/externals/sqlite3/sqlite3.c:23640:16: error: invalid application of 'sizeof' to an incomplete type 'struct unix_syscall []'
    for(i=0; i<ArraySize(aSyscall)-1; i++){
               ^~~~~~~~~~~~~~~~~~~
/Users/alexgonzalez/Repositorio/Git/LA/submodules/externals/sqlite3/sqlite3.c:8375:38: note: expanded from macro 'ArraySize'
#define ArraySize(X)    ((int)(sizeof(X)/sizeof(X[0])))
                                     ^~~
/Users/alexgonzalez/Repositorio/Git/LA/submodules/externals/sqlite3/sqlite3.c:23644:14: error: invalid application of 'sizeof' to an incomplete type 'struct unix_syscall []'
  for(i++; i<ArraySize(aSyscall); i++){
             ^~~~~~~~~~~~~~~~~~~
/Users/alexgonzalez/Repositorio/Git/LA/submodules/externals/sqlite3/sqlite3.c:8375:38: note: expanded from macro 'ArraySize'
#define ArraySize(X)    ((int)(sizeof(X)/sizeof(X[0])))
                                     ^~~
6 errors generated.
make[6]: *** [CMakeFiles/sqlite3.dir/sqlite3.c.o] Error 1
make[5]: *** [CMakeFiles/sqlite3.dir/all] Error 2
make[4]: *** [all] Error 2
make[3]: *** [/Users/alexgonzalez/Repositorio/Git/LA/WORK/android-armv7/Stamp/EP_sqlite3/EP_sqlite3-build] Error 2
make[2]: *** [CMakeFiles/EP_sqlite3.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [armv7-build] Error 2

**Comment by chowdarynamala** [comment]
I also faced similar issue earlier, resolved the error when I switch back the linphone module with commit id 12ad35401c228f65035afe297c6847d13a2e4fbf

**Comment by alexiagonzalez** [comment]
Thanks a lot chowdarynamala, I'll try that solution, I hope it works...

Thank you very much again.

**Comment by alexiagonzalez** [comment]
Hi again chowdarymanamala,

I can't find that commit in my Source Tree tool... could yo tell me in which branch is it? or what's its title? I'm at master branch of the Android Linphone project now...

Thanks a lot again.

**Comment by alexiagonzalez** [comment]
As the problem have been fixed, I think I should close this issue.
