### ISSUE TITLE
Unable to integrate with hikvision due to h264 profile-level-id hardcoded

### ISSUE THREAD

**Issue by martin-ducar-gd** [BelledonneCommunications/linphone-android#1220]
The desktop version of linphone has field next to h264 codec to specify the profile-level-id. I can confirm when specifying 
`profile-level-id=4D001F` it works with hikvision doorbells however it seems like in android app the default is `profile-level-id=42801F` with no option to modify. It would be great if this would be possible also on android. 

I might try to contribute but can't find any reference to h264 except for old version cisco codec download but nowhere the parameters of the codec. If you could point me to the direction it would be helpfull. Or if this is somehow different on android for whatever reason and is a limitation than that would be also very valuable information.

**Comment by martin-ducar-gd** [comment]
I found out how its done in desktop version: https://github.com/BelledonneCommunications/linphone-desktop/blob/master/linphone-app/src/components/codecs/AbstractCodecsModel.cpp#L91

**Comment by martin-ducar-gd** [comment]
Closest place i could find here is https://github.com/BelledonneCommunications/linphone-android/blob/master/app/src/main/java/org/linphone/settings/VideoSettingsFragment.java#L280 as far as I understand I would replicate that with fmtp setting for each codec in core + Ui

**Comment by Viish** [comment]
You can also define it in your config file (either by rebuilding the app or through remote provisioning).
Add the following to the [video_codec_X] entry matching H264:
`recv_fmtp=profile-level-id=4D001F`

**Comment by Viish** [comment]
I fixed this in:
```
commit 6b29ed4cdb4ac32d3256ec05e7cd7c7be7e15b1c (feature/kotlin_rewrite)
Author: Sylvain Berfini <sylvain.berfini@belledonne-communications.com>
Date:   Mon Nov 23 11:38:42 2020 +0100

    Updated video settings to allow changing recv-fmtp of codecs
```
