### ISSUE TITLE
How to judge whether there is video in earlymadia

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1221]
Hi，
I have set the earlymadia function in devices A and B, and earlymadia works normally。
However, occasionally, there is a problem with the camera, which causes A to call B and B does not display video. How can I judge whether there is video data transmitted from A terminal?  Does the upper layer have an interface to judge?

thanks.

**Comment by Viish** [comment]
Hi,
Use call.getCurrentParams().videoEnabled().
Cheers,

**Comment by fengqz627** [comment]
Hi Viish
1. When earlymedia is called, when is it in what state call.getCurrentParams ().videoEnabled()？ When I add it in status "outgoing earlymadia", the value is false, I don't know where to add that judgment。
2. Is it possible that the value is true and no video data is actually transmitted. How to judge whether there is video?

thanks.

**Comment by Viish** [comment]
> When earlymedia is called, when is it in what state call.getCurrentParams ().videoEnabled()？ When I add it in status "outgoing earlymadia", the value is false, I don't know where to add that judgment。

I don't understand.

> Is it possible that the value is true and no video data is actually transmitted. How to judge whether there is video?

Yes, on Android if you don't have a display for local camera preview you can't capture video (and thus not send it).
To be really sure if you have video packets sent/received, use the video call statistics and check used bandwidth.
