### ISSUE TITLE
Error when app receives a SIP MESSAGE

### ISSUE THREAD

**Issue by liliangeorg** [BelledonneCommunications/linphone-android#1225]
I use Linphone library release 4.4.0 for an application in order to exchange some information with a SIP server and perform calls. Registration of the user is executed properly on the SIP server. Outgoing calls are also performed well while messages are exchanged between the app and the server before the call. However before an incoming call, a SIP message with some information about the call is received in the app and at the point when the message received, an error occurs. SIP message is never answered (not 200 OK nor 606 or anything) and the application crashes with the following logs:

E/myAppLyn: fast_header_address parser error for [:]
W/myAppLyn: Cannot create Address, bad uri [:]

The message which is received and needs to be handled is: 

Message Header
    Max-Forwards: 68
    Via: SIP/2.0/UDP xx.xx.xxx.xx:xxxx;branch=z9hG4bKg3Jqkv7it8ypy2njsqtyg9r6ch33qy2g1
        Transport: UDP
        Sent-by Address: xx.xx.xxx.xx
        Sent-by port: 5060
        Branch: z9hG4bKg3Jqkv7it8ypy2njsqtyg9r6ch33qy2g1
    To: <tel:+49yyyyyyyyyyy;noifc=term>
        SIP to address: tel:+49yyyyyyyyyyy;noifc=term
    From: <tel:+49yyyyyyyyyyy>;tag=i7j4Esbg_s78540t1605620511m434448j29597k6_2822453163-37063643
        SIP from address: tel:+49yyyyyyyyyyy
        SIP from tag: i7j4Esbg_s78540t1605620511m434448j29597k6_2822453163-37063643
    Call-ID: q65540t1605620511n434448g19824s7
    [Generated Call-ID: q65540t1605620511n434448g19824s7]
    CSeq: 1 MESSAGE
        Sequence Number: 1
        Method: MESSAGE
    Accept-Contact: *;+message-channel.multi-persona;explicit;require
    Accept-Contact: *;+sip.instance="<urn:uuid:700b5347-bd84-00df-925b6-049a883ad781>";explicit;require
    P-Asserted-Identity: <tel:+49yyyyyyyyyyy>
        SIP PAI Address: tel:+49yyyyyyyyyyy
    User-Agent: SERVER - CTP1982134/1 Q17F06
    Content-Type: application/vnd.call-id-info+xml
    Content-Length: 184
    Allow: INVITE, BYE, CANCEL, ACK, INFO, PRACK, COMET, OPTIONS, SUBSCRIBE, NOTIFY, MESSAGE, REFER, REGISTER, UPDATE

I think that all fields seem OK, but apparently they are not!
Could you please provide some advice, which may be the problem?

Thank you in advance for your help,

**Comment by Viish** [comment]
Hi,
Please attach SDK logs of the issue.
Cheers,

**Comment by liliangeorg** [comment]
Please find the logs attached:
[Incoming_call_error.txt](https://github.com/BelledonneCommunications/linphone-android/files/5568448/Incoming_call_error.txt)

**Comment by Viish** [comment]
I think it's because your FROM and TO headers contains a TEL URI instead of a SIP URI:
```
I/myappLyn: bellesip_wake_lock_acquire(): Android wake lock [belle-sip recv channel] acquired [ref=0x2fd6]
    bellesip_wake_lock_acquire(): cast long of wakelock 12246
    channel [0x75e0e36cc0]: starting recv background task with id=[2fd6].
    channel [0x75e0e36cc0]: received [992] new bytes from [UDP://xx.xx.xxx.xx:5060]:
    MESSAGE sip:+xxxxxxxxxxxxx@xx.xx.xx.xxx:xxxxx;transport=udp SIP/2.0
    Max-Forwards: 68
    Via: SIP/2.0/UDP xx.xx.xxx.xx:5060;branch=z9hG4bKg3Zqkv7itwnr9i5buvt6o6zhob9hgncwv
    To: <tel:+xxxxxxxxxxxxx;noifc=term>
    From: <tel:+xxxxxxxxxxxxx>;tag=h7g4Esbg_p65540t1605278330m276964c21705s4_4238675643-558830416
    Call-ID: p65540t1605278330m276964c21705s5
    CSeq: 1 MESSAGE
    Accept-Contact: *;+message-channel.multi-persona;explicit;require
    Accept-Contact: *;+sip.instance="<urn:uuid:563c63ec-cb96-00b6-a016-de63e61736e3>";explicit;require
    P-Asserted-Identity: <tel:+xxxxxxxxxxxxx>
    User-Agent: myproject MTAS - CXP2010134/1 R17D06
I/myappLyn: Content-Type: application/vnd.call-id-info+xml
    Content-Length: 184
    Allow: INVITE, BYE, CANCEL, ACK, INFO, PRACK, COMET, OPTIONS, SUBSCRIBE, NOTIFY, MESSAGE, REFER, REGISTER, UPDATE
    <?xml version="1.0" encoding="UTF-8"?><call-id-info><calling-party>tel:+xxxxxxxxxxxxx</calling-party><called-party>tel:+xxxxxxxxxxxxx</called-party><expires>10</expires></call-id-info>
```

**Comment by liliangeorg** [comment]
Hello.
Thanks for your answer. 
Today I was able to test your proposal and indeed it worked properly with SIP URI within headers.
Many thanks for your support!

**Comment by Viish** [comment]
You're welcome :)

**Comment by liliangeorg** [comment]
Hello.

After following your advice, I have replaced "tel:" URI with "sip:" URI and this works fine in simulated environment.
However in real environment it is difficult sip URI to be handled in the actual server. Therefore I would like to ask if it is feasible either to do something in native code (java) or if there is anything to do during build of the linphone library in order tel: URI to be acceptable as well.
It has been noticed on linphone testing files like belle_sip_message_tester.c and belle_sip_headers_test.c  that **from** and **to** headers parse examples contain "tel:" suffix.

Thank you in advance for your help and support,
Lilianna.
