### ISSUE TITLE
Linphone cmake builder error while trying to build for one target

### ISSUE THREAD

**Issue by chowdarynamala** [BelledonneCommunications/linphone-android#123]
Hi All,
I am facing a strange error with cmake builder of linphone. I downloaded and successfully built latest linphone-android source code. When I modify prepare.py script to target for only one android target i.e armv7, I see following error in cmake builder when executing prepare script. When I include more than 1 target in android_targets list then there is not issue seen.

prepare.Preparator.parse_args(self)
  File "submodules/cmake-builder/prepare.py", line 235, in parse_args
    for target_name in self.args.target:
AttributeError: 'Namespace' object has no attribute 'target'

Observed in cmake builder prepare.py script following code where the target in args is added only when there are more than 1 target in the input

if len(self.targets) > 1:
            self.argparser.add_argument('target', nargs='*', action=TargetListAction, default=default_targets, targets=self.available_targets(),
                help="The target(s) to build for (default is '{0}'). Space separated targets in list: {1}.".format(' '.join(default_targets), ', '.join(self.available_targets())))

**Comment by DatBewar** [comment]
Hello,
to target a specify architecture, please use:
./prepare.py x86 x86_64 arm armv7 armv64

**Comment by chowdarynamala** [comment]
Hi,
Yes it works fine when I give multiple targets. But the failure case that I reported was when tried executing with a single Target
