### ISSUE TITLE
Garbeld in Linphone app contact menu

### ISSUE THREAD

**Issue by s099064146** [BelledonneCommunications/linphone-android#1232]
May I ask where I could change the encoding method?
I installed the app on my cell phone and it presents like this:
(Only Traditional Chinese has this problem right now.)
![1606468222288](https://user-images.githubusercontent.com/40239192/100433291-d4208380-30d5-11eb-9c0e-8facfce70f48.jpg)

Could you please give me any help? Thank you very much!

**Comment by ovari** [comment]
Linphone has other problems in addition to Traditional Chinese.

The [Evergreen Tree](https://emojipedia.org/evergreen-tree/) 🌲 emojis does not work entirely correctly either as the contact icon shows a [REPLACEMENT CHARACTER](https://en.wikipedia.org/wiki/Specials_(Unicode_block)) � instead of an [Evergreen Tree](https://emojipedia.org/evergreen-tree/) 🌲.

![image](https://user-images.githubusercontent.com/17465872/100494742-b405c880-3198-11eb-902e-b3b13e6edbb3.png)

Thank you

**Comment by s099064146** [comment]
@Viish 
Could you please help me with this?

**Comment by Viish** [comment]
Hi, I can reproduce the "tree" issue, but not the display issue in the history. I'll see what I can do.

**Comment by Viish** [comment]
@ovari Fixed emoji issue in commit d5395695da6a6451fa3f6f08ab9fafbb649ddad5
Author: Sylvain Berfini <sylvain.berfini@belledonne-communications.com>
Date:   Tue Dec 1 11:03:10 2020 +0100
    Fixed emoji display in contacts' name

@s099064146 I couldn't reproduce the display issue with chinese characters, do you have it on feature/kotlin_rewrite branch too?

**Comment by s099064146** [comment]
@Viish 
Uh, what do you mean? May I ask how to fix this problem?

**Comment by Viish** [comment]
> Do you mean I have to use the app on the feature/kotlin_rewrite branch?

Yes.

**Comment by s099064146** [comment]
@Viish 
Thanks, I will try it.

**Comment by ovari** [comment]
Thank you @Viish for fixing with d539569. Are you able to advise when an update to the Linphone beta edition will be available via the Android store which includes the fix to enable testing? Thank you

**Comment by Viish** [comment]
I'm waiting for a feature to be available in the Sdk (it is being developed for a few weeks now) and once it will be merged into master (linphone-sdk repo) I'll merge the branch into linphone-android master. From then it will becomes the next release so it will be available as beta before.
