### ISSUE TITLE
old icon is more contrast and looks better

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#1233]
![image](https://user-images.githubusercontent.com/14617699/100561387-dc411480-32c9-11eb-9c01-daba69d977ca.png)

Old: 3.26:1
https://webaim.org/resources/contrastchecker/?fcolor=EB6608&bcolor=FFFFFF

New: 3.06:1
https://webaim.org/resources/contrastchecker/?fcolor=FF5E00&bcolor=FFFFFF

Moreover, the central part of the handset is smoother in the old icon:
![image](https://user-images.githubusercontent.com/14617699/100561701-9cc6f800-32ca-11eb-96b5-f74aa95487e0.png)

What about to make it a bit darker:
![image](https://user-images.githubusercontent.com/14617699/100562114-bcaaeb80-32cb-11eb-9e6f-11fd6ff42590.png)

**Comment by Viish** [comment]
I don't know what icon you used, but the one in feature/kotlin_rewrite branch as a contrast of 3.23:1 and is quite smooth.

**Comment by 532910** [comment]
The leftmost is 4.3.1
The center one is 4.3-alpha.246+7f9b21b5
The rightmost is gimp'ed myself.
