### ISSUE TITLE
App Crash frequently

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#1236]
Hello @Viish ,

My App is getting crashed very frequently. 

[160715148191ce80b31a9b22b6e2997bfa0298544b.txt](https://github.com/BelledonneCommunications/linphone-android/files/5646663/160715148191ce80b31a9b22b6e2997bfa0298544b.txt)

Please find attached logs for your reference.

**Comment by Viish** [comment]
Hi,
Your aren't using a release version of neither the app nor the SDK.
Also your log file doesn't include the stack trace of the crash so I can't check.
Cheers,

**Comment by amit1576** [comment]
Hi,

I am getting these error 

belle-sip] ERROR fast_header_address parser error for [sip:]
liblinphone] ERROR No To: address, cannot build request

what does it mean.

Thanks in advance

**Comment by Viish** [comment]
This simply means you are trying to parse an empty string trying to build a LinphoneAddress object.
But that doesn't create a crash.
