### ISSUE TITLE
how can android linphone  send video stream to the target when caller ring the target linphone

### ISSUE THREAD

**Issue by nealkai** [BelledonneCommunications/linphone-android#1237]
Hello, Viish @Viish ,i want to that android linphone can  send video stream to the target when caller ring the target linphone, do i need to modify the liblinphone ? i can see the Call.acceptEarlyMedia() interface ,but iit does work.please help

best wish to you

**Comment by Viish** [comment]
Hi,

Try setting the following in the linphonerc config file of the Linphone that receives the call (and thus will display the early video):
```
[sip]
incoming_calls_early_media=1
```

Cheers,

**Comment by nealkai** [comment]
thanks ，





------------------ Original ------------------
