### ISSUE TITLE
Preferred Video Size and Video Preset effect

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#1238]
Hi @Viish,

I had tried to change Preferred vide size and video preset, but there is no effect in bandwidth consumption. Actually I want to use QCIF and FPS to 20 to save bandwidth while video calls. But changing these setting will not show any decrease in overall bandwidth requirement. 

Please let me know how these setting can give benefit in overall bandwidth requirement.

Thanks in advance.

**Comment by Viish** [comment]
Hi,

Video size and fps will be automatically adapted to the bandwidth available during a call, so indeed you can't do it like that.

However you can directly set a limit for bandwidth use in linphonerc:
```
[net]
download_bw=0
upload_bw=0
```
or using `linphone_core_set_upload_bandwidth` and `linphone_core_set_download_bandwidth`.

Cheers,

**Comment by amit1576** [comment]
Hello @Viish,

Actually the issue we are facing is that, when our bandwidth goes down during call, Video quality remain as it was before but voice quality suffers. How can we ensure that our voice quality remain as it was before. Video can suffer(even video turn off).

Can this be achieved.

Thanks in advance.

**Comment by Viish** [comment]
Can you attach a log of such call?

**Comment by Viish** [comment]
Also, if you know when the bandwidth will be limited, you can use callParams.enableLowBandwidth(true) which will optimize audio and disable video.

**Comment by amit1576** [comment]
Hello @Viish ,

Please find attached logs. These are the logs when Audio quality is very bad during Audio call.

[1607762119e753b65147aeff9f3682d6dea92ee19a.txt](https://github.com/BelledonneCommunications/linphone-android/files/5682743/1607762119e753b65147aeff9f3682d6dea92ee19a.txt)

One more thing if I limit bandwidth upload and download as you suggested above. What will happens if my bandwidth goes below the specified limit. Will video shut down and audio continues or both audio and video suffers.

Thanks in advance.

**Comment by Viish** [comment]
First of all, you haven't enabled AVPF (and you should): `m=audio 7078 RTP/AVP 18 101`
Another issue is packet lost, and for that there is no solution except improving the network or using another one...
Finally if you still need help improving audio quality, contact my company using the contact form on our website https://linphone.org/contact for a dev-assist contract.
