### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by jayqean** [BelledonneCommunications/linphone-android#1239]
Hello @Viish ,

My App is getting crashed for long launch. thks.

This is the log：

"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x78f40d38 self=0x7067814c00
  | sysTid=14335 nice=-10 cgrp=default sched=0/0 handle=0x70ee605548
  | state=S schedstat=( 568552522205 227439134656 2067351 ) utm=36606 stm=20249 core=6 HZ=100
  | stack=0x7fc9c65000-0x7fc9c67000 stackSize=8MB
  | held mutexes=
  kernel: __switch_to+0x90/0xe8
  kernel: futex_wait_queue_me+0xe8/0x1b0
  kernel: futex_wait+0xe4/0x204
  kernel: do_futex+0x168/0x80c
  kernel: SyS_futex+0x90/0x1b8
  kernel: cpu_switch_to+0x2ec/0x1cf8
  native: #00 pc 000000000001f2ac  /system/lib64/libc.so (syscall+28)
  native: #01 pc 00000000000228f4  /system/lib64/libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*)+140)
  native: #02 pc 0000000000093540  /system/lib64/libc.so (NonPI::MutexLockWithTimeout(pthread_mutex_internal_t*, bool, timespec const*)+216)
  native: #03 pc 00000000000c3a84  /data/app/com.meet.app-vsH3O0CLk3Npr73y6N40pA==/lib/arm64/libmediastreamer.so (ms_ticker_get_last_late_tick+68)
  native: #04 pc 00000000000fb880  /data/app/com.meet.app-vsH3O0CLk3Npr73y6N40pA==/lib/arm64/libmediastreamer.so (video_stream_iterate+104)
  native: #05 pc 000000000060e544  /data/app/com.meet.app-vsH3O0CLk3Npr73y6N40pA==/lib/arm64/liblinphone.so (LinphonePrivate::MS2Stream::handleEvents()+104)
  native: #06 pc 000000000060fe18  /data/app/com.meet.app-vsH3O0CLk3Npr73y6N40pA==/lib/arm64/liblinphone.so (???)
  native: #07 pc 000000000089bfdc  /data/app/com.meet.app-vsH3O0CLk3Npr73y6N40pA==/lib/arm64/liblinphone.so (???)
  native: #08 pc 00000000007c5620  /data/app/com.meet.app-vsH3O0CLk3Npr73y6N40pA==/lib/arm64/liblinphone.so (belle_sip_main_loop_run+980)
  native: #09 pc 00000000007c5854  /data/app/com.meet.app-vsH3O0CLk3Npr73y6N40pA==/lib/arm64/liblinphone.so (belle_sip_main_loop_sleep+68)
  native: #10 pc 00000000007422d0  /data/app/com.meet.app-vsH3O0CLk3Npr73y6N40pA==/lib/arm64/liblinphone.so (linphone_core_iterate+408)
  at org.linphone.core.CoreImpl.iterate(Native method)
  at org.linphone.core.CoreImpl.iterate(Core.java:7351)
  - locked <0x0ae07cab> (a org.linphone.core.CoreImpl)
  at org.linphone.core.tools.service.CoreManager$1.run(CoreManager.java:127)
  at android.os.Handler.handleCallback(Handler.java:873)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:243)
  at android.app.ActivityThread.main(ActivityThread.java:7172)
  at java.lang.reflect.Method.invoke(Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

**Comment by Viish** [comment]
Hi,
Please attach a symbolized stack trace using ndk-stack and the logs from before the crash.
Thanks.
