### ISSUE TITLE
Register port

### ISSUE THREAD

**Issue by gregperezz** [BelledonneCommunications/linphone-android#1241]
Hi @Viish, Linphone uses random source ports to register, is it possible to use a default sip source port to to register? 

Thank you, regards.

**Comment by Viish** [comment]
Random is used if value is -1, otherwise you can set the value you want (0 will disable it):
```
[sip]
sip_port=-1
sip_tcp_port=-1
sip_tls_port=-1
```

**Comment by gregperezz** [comment]
Thank you @Viish I can change the udp port however I cannot change the tcp or tls source ports via sip_tcp_port and sip_tls_port. They still use random ports.

**Comment by Viish** [comment]
There is no reason this works for UDP and not the others. Please check your code.
Check you don't have a `sip_random_port=1` in your config file.

**Comment by gregperezz** [comment]
Nope, I even tried sip_random_port=0. Doesn't make a difference that is weird.

**Comment by Viish** [comment]
Please attach logs.

**Comment by gregperezz** [comment]
I used to login with udp but today, I am trying to get logs for you and even though I choose udp for transport type, it registers via tls. I got the logs for that scenario. linphonerc_default is modified as below. I disabled the random port option.

sip_port=5060
sip_tcp_port=5070
sip_tls_port=5071

https://www.linphone.org:444//tmp/5fd72281d0401_b0d744491537505fff77.gz

**Comment by Viish** [comment]
Two things:

- It connects through TLS because tls is set as transport in proxy config:
`Register refresher [200] reason [Registration successful] for proxy [<sip:sip.linphone.org;transport=tls>]`
- It can't use port 5070 and 5071 because another software already uses them:
```
2020-12-14 11:26:28:760 [org.linphone.debug/belle-sip] ERROR TCP bind() failed for ::0 port 5070: Address already in use
2020-12-14 11:26:28:760 [org.linphone.debug/belle-sip] ERROR TCP bind() failed for ::0 port 5071: Address already in use
```
That's exactly why we use random local ports, to prevent conflicts.

**Comment by gregperezz** [comment]
Okay I missed that. Can you check the new logs? Here I set tls port to 5063 but it uses random ports. 
https://www.linphone.org:444//tmp/5fd73d2abcb24_9f9f759492eb795943b8.gz

**Comment by Viish** [comment]
I don't see the core starting in your logs. Please clean the logs, kill the app, restart it and send new logs.

**Comment by gregperezz** [comment]
Okay sorry for that, here it is. 5065 port is seen in the subscribe message but in register it still uses a random port.
https://www.linphone.org:444//tmp/5fd757194b34b_269429eec8a54ab0cc7f.gz

**Comment by Viish** [comment]
Can you send me the result of following command: `adb shell run-as org.linphone.debug cat files/.linphonerc` please?

**Comment by gregperezz** [comment]
Sure.

[sip]
contact="Linphone Android" <sip:linphone.android@unknown-host>
use_info=0
keepalive_period=30000
sip_port=5060
sip_tcp_port=5060
sip_tls_port=-1
media_encryption=none
guess_hostname=1
register_only_when_network_is_up=1
auto_net_state_mon=1
auto_answer_replacing_calls=1
ping_with_options=0
use_cpim=1
ipv6_migration_done=1
root_ca=/data/user/0/org.linphone.debug/files/share/linphone/rootca.pem
verify_server_certs=1
verify_server_cn=1
http_proxy_port=0
default_proxy=0
inc_timeout=45
in_call_timeout=0
delayed_timeout=4
register_only_when_upnp_is_ok=1
linphone_specs=ephemeral,groupchat/1.1,lime

[net]
#Because dynamic bitrate adaption can increase bitrate, we must allow "no limit"
download_bw=0
upload_bw=0
mtu=1300
force_ice_disablement=0
nat_policy_ref=RA-xYhxVdAZVdcM

[video]
size=vga
displaytype=MSAndroidTextureDisplay
auto_resize_preview_to_keep_ratio=1
display=1
capture=1

[app]
tunnel=disabled
push_notification=1
auto_start=1
activation_code_length=4
prefer_basic_chat_room=1
auto_download_incoming_files_max_size=-1
sender_name_hidden_in_forward_message=0
push_notification_regid=dIT2DNfz_fo:APA91bEajLvTBQWCg_Y91h9J5_rABPoW9BVcFjWI58k97k-C9KvBHODMEYhlFg3tPoMQFpV8uih1upWqCLPAcdU_7ag3cuvlmjwLBrd5upwQsqSlt_s2PRbAsJKJaYwwdnlRVEKybAs7
first_launch=0
version_check_url_last_timestamp=1633751901
random_port=0
dnd_settings_popup_enabled=0
debug=1

[tunnel]
port=443

[misc]
log_collection_upload_server_url=https://www.linphone.org:444/lft.php
file_transfer_server_url=https://www.linphone.org:444/lft.php
version_check_url_root=https://www.linphone.org/releases
max_calls=10
history_max_size=100
enable_basic_to_client_group_chat_room_migration=0
enable_simple_group_chat_message_state=0
aggregate_imdn=1
notify_each_friend_individually_when_presence_received=0
prefer_basic_chat_room=1
uuid=fef8111c-2ba1-0026-97b1-5c6041a95db5
user_certificates_path=/data/user/0/org.linphone.debug/files/user-certs
store_friends=0

[in-app-purchase]
server_url=https://subscribe.linphone.org:444/inapp.php
purchasable_items_ids=test_account_subscription

[sound]
ec_calibrator_cool_tones=1
playback_dev_id=openSLES Earpiece: GM 9 Pro
ringer_dev_id=openSLES Earpiece: GM 9 Pro
capture_dev_id=openSLES Microphone: GM 9 Pro
media_dev_id=openSLES Earpiece: GM 9 Pro
local_ring=/data/user/0/org.linphone.debug/files/share/sounds/linphone/rings/notes_of_the_optimistic.mkv
remote_ring=/data/user/0/org.linphone.debug/files/share/sounds/linphone/ringback.wav
playback_gain_db=0.000000
mic_gain_db=0.000000
disable_record_on_mute=0
#remove this property for any application that is not Linphone public version itself

[assistant]
xmlrpc_url=https://subscribe.linphone.org:444/wizard.php
algorithm=MD5
password_max_length=-1
password_min_length=0
username_length=-1
username_max_length=128
username_min_length=1
username_regex=^[a-zA-Z0-9+_.\-]*$

[lime]
lime_update_threshold=-1
last_update_time=1607951594
lime_server_url=https://lime.linphone.org/lime-server/lime-server.php

[nat_policy_0]
ref=RA-xYhxVdAZVdcM

[proxy_default_values]
avpf=0
dial_escape_plus=0
publish=0
quality_reporting_enabled=0
quality_reporting_interval=0
reg_expires=3600
reg_sendregister=1

[nat_policy_default_values]

[nat_policy_1]
ref=x5BtByV-gRXS7t7
stun_server=stun.linphone.org
protocols=stun,ice

[auth_info_0]
username=testaccountnum1
ha1=c3c5bac2066b19f6c8f6e166dd6ee9c6
realm=sip.linphone.org
domain=sip.linphone.org
algorithm=MD5
available_algorithms=MD5

[rtp]
audio_rtp_port=7078
video_rtp_port=9078
text_rtp_port=11078
audio_jitt_comp=60
video_jitt_comp=60
nortp_timeout=30
audio_adaptive_jitt_comp_enabled=1
video_adaptive_jitt_comp_enabled=1

[audio_codec_0]
mime=opus
rate=48000
channels=2
enabled=16
recv_fmtp=useinbandfec=1

[audio_codec_1]
mime=speex
rate=16000
channels=1
enabled=16
recv_fmtp=vbr=on

[audio_codec_2]
mime=speex
rate=8000
channels=1
enabled=16
recv_fmtp=vbr=on

[audio_codec_3]
mime=PCMU
rate=8000
channels=1
enabled=16

[audio_codec_4]
mime=PCMA
rate=8000
channels=1
enabled=16

[audio_codec_5]
mime=GSM
rate=8000
channels=1
enabled=0

[audio_codec_6]
mime=G722
rate=8000
channels=1
enabled=0

[audio_codec_7]
mime=iLBC
rate=8000
channels=1
enabled=0
recv_fmtp=mode=30

[audio_codec_8]
mime=iSAC
rate=16000
channels=1
enabled=0

[audio_codec_9]
mime=speex
rate=32000
channels=1
enabled=0
recv_fmtp=vbr=on

[audio_codec_10]
mime=L16
rate=44100
channels=2
enabled=0

[audio_codec_11]
mime=L16
rate=44100
channels=1
enabled=0

[video_codec_0]
mime=VP8
rate=90000
enabled=16

[video_codec_1]
mime=H264
rate=90000
enabled=16
recv_fmtp=profile-level-id=42801F

[video_codec_2]
mime=H265
rate=90000
enabled=16

[proxy_0]
reg_proxy=<sip:sip.linphone.org;transport=tls>
reg_route=<sip:sip.linphone.org;transport=tls>
reg_identity=sip:testaccountnum1@sip.linphone.org
realm=sip.linphone.org
contact_uri_parameters=app-id=929724111839;pn-type=firebase;pn-timeout=0;pn-tok=dIT2DNfz_fo:APA91bEajLvTBQWCg_Y91h9J5_rABPoW9BVcFjWI58k97k-C9KvBHODMEYhlFg3tPoMQFpV8uih1upWqCLPAcdU_7ag3cuvlmjwLBrd5upwQsqSlt_s2PRbAsJKJaYwwdnlRVEKybAs7;pn-silent=1
quality_reporting_collector=sip:voip-metrics@sip.linphone.org;transport=tls
quality_reporting_enabled=1
quality_reporting_interval=180
reg_expires=31536000
reg_sendregister=1
publish=0
avpf=1
avpf_rr_interval=1
dial_escape_plus=0
privacy=32768
push_notification_allowed=1
idkey=proxy_config_Kb4832mSDTKD7td
publish_expires=-1
nat_policy_ref=x5BtByV-gRXS7t7
conference_factory_uri=sip:conference-factory@sip.linphone.org

**Comment by Viish** [comment]
As you can see, you haven't really changed the port settings.
I guess you have edited the linphonerc file locally. This file is only installed and used on the first start of the app. After that any changes made to it won't be installed on the device and used...
Either uninstall the app or use the factory config file.

**Comment by gregperezz** [comment]
Ok I uninstalled and re-registered. Now I have the command result as below.
[sip]
contact="Linphone Android" <sip:linphone.android@unknown-host>
use_info=0
keepalive_period=30000
sip_port=5060
sip_tcp_port=5065
sip_tls_port=5063
media_encryption=none
guess_hostname=1
register_only_when_network_is_up=1
auto_net_state_mon=1
auto_answer_replacing_calls=1
ping_with_options=0
use_cpim=1
ipv6_migration_done=1
root_ca=/data/user/0/org.linphone.debug/files/share/linphone/rootca.pem
verify_server_certs=1
verify_server_cn=1
http_proxy_port=0
linphone_specs=ephemeral,groupchat/1.1,lime
default_proxy=0

but still the register port is random.
https://www.linphone.org:444//tmp/5fd76676219f4_5d11b324c65d6dcb6844.gz

**Comment by gregperezz** [comment]
I cleaned the logs, killed the app and got a cleaner log with core starting you can check this.
https://www.linphone.org:444//tmp/5fd767fa3434b_e476944ba8770e842a02.gz

**Comment by Viish** [comment]
I don't see the issue, your ports are in use:
```
2020-12-14 16:26:01:781 [org.linphone.debug/belle-sip] MESSAGE Creating listening point [0x7299f30080] on [sip:[::0]:5060;transport=UDP]
2020-12-14 16:26:01:782 [org.linphone.debug/belle-sip] MESSAGE Creating listening point [0x7299f30100] on [sip:[::0]:5065;transport=TCP]
2020-12-14 16:26:01:782 [org.linphone.debug/belle-sip] MESSAGE Creating listening point [0x7299f30200] on [sip:[::0]:5063;transport=TLS]
```

**Comment by gregperezz** [comment]
The register message has a random port. Shouldn't be the via line like Via: SIP/2.0/TLS 176.30.212.43:5063 ?

REGISTER sip:sip.linphone.org SIP/2.0
Via: SIP/2.0/TLS 176.30.212.43:43581;alias;branch=z9hG4bK.y~qDSaZuY;rport
From: <sip:testaccountnum1@sip.linphone.org>;tag=uXdEoojQr
To: sip:testaccountnum1@sip.linphone.org
CSeq: 20 REGISTER

**Comment by Viish** [comment]
Indeed, and that's because you are using TLS.
Ports you configured are "listening" ports, so for incoming packets. However in TLS, you can't use the same port for incoming and outgoing packets, so it's expected.
Also note that when using UDP or TCP, the port in the Contact header can also be different that the one used if you're behin a NAT.

**Comment by gregperezz** [comment]
Thank you @Viish. I have to more questions. Should I always disable "pref_transport_use_random_ports" when I define the Sip listening ports? Can I define a port range (not just one constant port like 5065) for sip ports?

**Comment by Viish** [comment]
> Can I define a port range (not just one constant port like 5065) for sip ports?

No, when you create a server socket it has to listen on a specific port, not a range.

> Should I always disable "pref_transport_use_random_ports" when I define the Sip listening ports?

Yes.

**Comment by gregperezz** [comment]
Thank you @Viish. Is "pref_transport_use_random_ports" same setting with "sip_random_port" in the config file? When I type sip_random_port=0 and reinstall the app, pref_transport_use_random_ports is still enabled.
