### ISSUE TITLE
Audio RTP Disturbed During Call

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#1248]
Hi @Viish ,

I have faced one issue with audio during call. I was on call, automatically some disturbance start coming. When i checked logs i found following **MESSAGE MSSimpleQosAnalyzer: rt_prop doubled.**.

Logs are attached, can you tell me what is the problem.

[7010-820-rt_prop_doubled.txt](https://github.com/BelledonneCommunications/linphone-android/files/5724740/7010-820-rt_prop_doubled.txt)

**Comment by Viish** [comment]
rt_prop means round trip propagation.
In your case, it goes for 0.05 to 0.25, probably due to some network issue.
Usually we decrease the bitrate but G729 doesn't support it, try Opus audio codec, it's the best around.
