### ISSUE TITLE
Register errors

### ISSUE THREAD

**Issue by briandowell** [BelledonneCommunications/linphone-android#1249]
Hello, I enable background mode in my Linphone app and notice that when expires time come;

1. It takes longer to send re-register messages, when I set expires to 120secs, it sends in between 105-115th seconds approximately, shouldn't it be like expires/2 seconds? Can we change this register period in the code?
2. Sometimes the register messages cannot be received by the sip server since the application cannot send them through mobile data network. I see that the app tries to send but the network is down just like battery save mode is on (but is not). Do you have any ideas what (setting) causes the mobile data network to be down until user interacts with the phone?  
3. Is there a way to wake up the network right before an expires register in the code?

**Comment by Viish** [comment]
Hi,
A few things:
- It's better to use push notifications than the background mode which is unreliable
- Yes a new REGISTER is sent at half the expire time
- Yes when in DOZE mode the app can't access network. Hence the use of push notifications with long expires.
- Yes, with a push notification. But when push are used, this isn't needed.
Conclusion: use push notifications, otherwise you won't have a reliable service.

**Comment by briandowell** [comment]
Thank you. Is doze mode enabled by default? I couldn't find it in the configuration file.

**Comment by Viish** [comment]
Actually doze mode is at Android OS level: https://medium.com/spreaker-developers/fighting-with-doze-app-standby-and-audio-streaming-234249197241

**Comment by briandowell** [comment]
Ok. I just found a parameter in the sdk code register_only_when_network_is_up. It is set to 1 by default. Will it make things better to set it to 0?

**Comment by briandowell** [comment]
lc->sip_conf.register_only_when_network_is_up=
		!!linphone_config_get_int(lc->config,"sip","register_only_when_network_is_up",**1**);

Shouldn't this be set to 0 ?

**Comment by Viish** [comment]
> Ok. I just found a parameter in the sdk code register_only_when_network_is_up. It is set to 1 by default. Will it make things better to set it to 0?

No, it won't. Our SDK has a built-in network manager that detects if network is up or not. Allowing REGISTER to be sent while network is not available won't help.

> Shouldn't this be set to 0 ?

No, by default we only send REGISTER when network is available.

**Comment by briandowell** [comment]
What about ping_with_options? Setting it to 1, I guess will keep the connection alive?

**Comment by Viish** [comment]
No, that won't help. No linphone setting can prevent an Android device to go into doze mode. Only push notification can wake up an app in this mode.

**Comment by briandowell** [comment]
I see, thank you. Can I change the register period from the SDK? I mean, for instance I want to set the register period to every expires/5 seconds rather than the default expires/2.

**Comment by disolaterX** [comment]
I have enabled option on asterisk, and it say my linphone is unreachable when checked via sip show peer, now when I send a notification what should do with that notification reregister the sip account or there is any manual way to simply refresh @Viish
