### ISSUE TITLE
toggleVideo() doesn't work properly

### ISSUE THREAD

**Issue by Erzen7** [BelledonneCommunications/linphone-android#1250]
Join a google meeting. Click disable the camera. It doesn't show as disabled, it looks like the camera is frozen because of the last frame shown.

**Comment by Viish** [comment]
What do you mean by google meeting?
Also please attach SDK logs.

**Comment by Erzen7** [comment]
I mean in a call from my android app with google meet. See [video attached.](https://we.tl/t-B1mFtGSjwS)
And also you can find SDK logs attached.

[5fe33868a57b2_a5f3bb59b675a548be7e.gz](https://github.com/BelledonneCommunications/linphone-android/files/5735348/5fe33868a57b2_a5f3bb59b675a548be7e.gz)

**Comment by Viish** [comment]
You log only contains errors so it is less helpful but it's enough to see you haven't granted the CAMERA permission.

**Comment by Erzen7** [comment]
I've granted permission as you can see in the video camera is opened . This issue is happening also in your sample app

**Comment by Viish** [comment]
Then please attach SDK logs in verbose mode.

**Comment by Erzen7** [comment]
[disable_camera_logs.txt](https://github.com/BelledonneCommunications/linphone-android/files/5735921/disable_camera_logs.txt)

**Comment by Viish** [comment]
Actually please attach them in the Mantis ticket you openned on our client bugtracker and let's keep the conversation there.
