### ISSUE TITLE
Incoming SIP SIMPLE message did not match existing contact

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1253]
I have a contact in an address book on my phone which the Google Contact app can display just fine.  That contact has a 10 digit North-American phone number in it.

I received a SIP SIMPLE message from that contact number through my voip provider but when the message appeared in linphone-android (on the kotlin_rewrite branch), the message was showing as from the 10 digit number and not the contact name.

If I try to compose a message to that contact, I can look the person up by name in linphone-android and it finds the correct contact.  I do suspect however if I were to complete composing and sending that message that linphone-android would see those as two different contacts.  Hence #1254.

I would expect that linphone-android to show the Android contact info for the incoming message.

**Comment by Viish** [comment]
Your problem is probably because the phone number is prefixed by international prefix and that you haven't configured yours in your account settings.

**Comment by brianjmurrell** [comment]
> you haven't configured yours in your account settings.

That appears to have been the problem.  But this was configured at one time and contact names were being displayed in the messages pane.  So something/somehow this has become unconfigured along the way.  I doubt we are ever going to get to the bottom of that though.

**Comment by brianjmurrell** [comment]
The problem with filling this field in is that now all phone numbers I dial from the dialpad get that number prefixed.  This is not correct for local numbers in the North American dialing plan and my provider then rejects the call.
