### ISSUE TITLE
Merge contacts

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1254]
Given the tendency of linphone-android to think that two conversations are from different contacts and keep them separate[1], it would be nice if one could tell linphone-android that they are indeed the same contact and to merge them, bringing all of the messages from the two contacts/conversations together, properly time ordered.

[1] I suspect one case of this is when I receive a SIP SIMPLE message from a contact and then try to compose (not respond to the received message) a new message to that same contact by finding them in my address book.

**Comment by Viish** [comment]
Won't do.

**Comment by brianjmurrell** [comment]
Can a better job be done of detecting duplicate contacts then?  It's particularly bad with SIP SIMPLE.

How can an end-user/administrator determine why duplicate contacts are being created for outgoing/incoming SIP SIMPLE messaging?  When I look at the message thread for a given contact, and click the contact's name at the top, the full SIP address that scrolls below it is identical for two different contacts.  So clearly that is not what is being used to determine contact address.

So what is?

**Comment by Viish** [comment]
Given you previous tickets, I'd say once again the message isn't sent to the address you configured in Linphone and that is used for outgoing messages...

**Comment by brianjmurrell** [comment]
Yes, that is understood.  What I am asking for is how do I see the difference that linphone is detecting so that I can make the necessary corrections?  As I said, everything that I have been able to see, in linphone-android shows the same address on the duplicate conversations.

**Comment by brianjmurrell** [comment]
Any ideas on the above question?

**Comment by Viish** [comment]
>  As I said, everything that I have been able to see, in linphone-android shows the same address on the duplicate conversations.

Yes, and that's normal. Given your situation, the remote may have the same address, as long as the local address is different it will create a separated conversation.
Attach log if you want me to confirm that.

**Comment by brianjmurrell** [comment]
> Attach log if you want me to confirm that.

That would be feeding a man a fish.  I'd be much more interested in learning to fish myself if you will indulge me.  :-)  Perhaps you will be teaching many people to fish at the same time.

IOW, what should I look for in the logs to understand what account name is being used for incoming and outgoing SIP SIMPLE messages?  So that I can debug these on my own in the future.

**Comment by Viish** [comment]
Simply search your log when the Core start, it will list all chat rooms loaded from database and their conference ID which is a pair or local/remote addresses.
Also when you receive / send a message, you'll see the addresses in FROM et TO headers of SIP MESSAGE.

**Comment by brianjmurrell** [comment]
Would this be the kind of discrepancy that causes this issue?

Sending a message to a contact:

```
2021-01-07 14:56:33:824 [org.linphone.debug/liblinphone] MESSAGE Insert new chat room in database: ConferenceId(peer=IdentityAddress(sip:+11235551212[redacted]@example.com), local=IdentityAddress(sip:my_sip_account@example.com)).
```

Receiving a message from the same contact:

```
2021-01-07 15:08:40:846 [org.linphone.debug/liblinphone] MESSAGE Unable to find chat room in RAM: ConferenceId(peer=IdentityAddress(sip:1235551212@pbx.example.com), local=IdentityAddress(sip:my_sip_account@pbx.example.com)).
```

The above received message comes from my ITSP as:

```
MESSAGE sip:5555551212@10.75.22.8:5060;line=alosmvd SIP/2.0
Via: SIP/2.0/UDP 3.2.7.1:5060;branch=z9hG4bK1690adb4;rport
Max-Forwards: 70
From: "1235551212" <sip:1235551212@host.itsp.com>;tag=as53a71404
To: <sip:5555551212@10.75.22.8:5060;line=alosmvd>
Contact: <sip:1235551212@23.246.247.146:5060>
Call-ID: 1b6f423150e504ce1ff767e17167e235@3.2.7.1:5060
CSeq: 102 MESSAGE
User-Agent: itsp.com
X-SMS-To: 5555551212
Content-Type: text/plain;charset=UTF-8
Content-Length: 15
```

I suppose you are of the position that the ITSP should be fully qualifying the sender by prefixing `+1` to their number, such as:

```
MESSAGE sip:5555551212@10.75.22.8:5060;line=alosmvd SIP/2.0
Via: SIP/2.0/UDP 3.2.7.1:5060;branch=z9hG4bK1690adb4;rport
Max-Forwards: 70
From: "+11235551212" <sip:+11235551212@host.itsp.com>;tag=as53a71404
To: <sip:5555551212@10.75.22.8:5060;line=alosmvd>
Contact: <sip:+11235551212@3.2.7.1:5060>
Call-ID: 1b6f423150e504ce1ff767e17167e235@3.2.7.1:5060
CSeq: 102 MESSAGE
User-Agent: itsp.com
X-SMS-To: 5555551212
Content-Type: text/plain;charset=UTF-8
Content-Length: 15
```

I suppose I could do that upon receiving such an unqualified sender from them, before forwarding to linphone.

**Comment by brianjmurrell** [comment]
Hrm.  Even with fully qualifying the phone number there seems to be a lot of room for _fuzz_ around the local/remote names for chat endpoints.

For example, my SIP server might know's canonical name is _pbx.example.com_, but it can have a CNAME record, and/or SRV records which are different, such as _example.com_ so that people's SIP address is a more general form such as _brian@example.com_, like e-mail addresses.  We don't have e-mail users tell others that their e-mail address is _brian@mail-5.example.com_, do we?  We hide the back-end implementation and give people a _stable_ address to use.

So, in such a situation where a linphone account is configured with a domain of _example.com_ and resolution of that domain results in a `SRV` result that is different than the domain, wouldn't it be more proper to use the `SRV` resolved value as the local account domain?

**Comment by Viish** [comment]
As for the emails, your account have an identity, which is generally username@domain.tld.
We don't care if domain.tld resolves to something else, exactly like for emails. That's why in account settings domain field (for account identity) is separated from SIP Proxy field.

**Comment by brianjmurrell** [comment]
Yeah, I gave this more thought last night and came to the same conclusion.  The "known address" is the identity and it doesn't matter the name of the machine providing the service for that address.
