### ISSUE TITLE
Account name with hash (#) doesn't work

### ISSUE THREAD

**Issue by and-fed** [BelledonneCommunications/linphone-android#1255]
I have sip server which has user names like: 123#1 123#2, 123#3 etc.
Full  example sip: 123#1@192.168.1.1:5060

Looks like android latest client ( windows client too) doesn't support hash in names. Windows doesn't allow to even enter, Android - doesn't connect. Noticed that android tries to encode hash to "%23" in UI.
I tried with other popular clients and these names work fine - no issues.

**Comment by Viish** [comment]
> Noticed that android tries to encode hash to "%23" in UI.

If you read the SIP RFC, '#' isn't an allowed character, it must be escaped, hence the %23.
