### ISSUE TITLE
Country prefix being prepended to outgoing calls

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1258]
If I fill in the _Prefix for your country_ field in my account settings that value is prepended to any/every call I make, including local phone numbers and in-office PBX extension calls.

Generally speaking, in North America at least, local calls are dialed without the LD/country prefix and people making what they know as an LD call, dial the 1 themselves when making the call.

**Comment by Viish** [comment]
In the 5.0 release of the SDK, we will add a setting to set the prefix for contact lookup and another setting to use it or not for calls.

**Comment by brianjmurrell** [comment]
Just so that I know when to look for this, any ETA on when this will be available in linphone-android?

**Comment by Viish** [comment]
The feature itself will be in our SDK soon and in the feature/kotlin_rewrite branch quickly after, but currently we are in the process of releasing a new version of the SDK/Linphone app, so the next release based on kotlin should be around this summer.

**Comment by brianjmurrell** [comment]
> so the next release based on kotlin should be around this summer.

But if I build from source, I should see this feature soon?  If so, what kind of timescale is _soon_?  A few weeks, a month, a few months?  Longer?

**Comment by Viish** [comment]
I expect the fix to be available in the SDK and in the feature/kotlin_rewrite branch at the end of the month.

**Comment by brianjmurrell** [comment]
> I expect the fix to be available in the SDK and in the feature/kotlin_rewrite branch at the end of the month.

Did this happen?

**Comment by Viish** [comment]
We're a bit behind schedule so no it hasn't been merged yet, but we expect to release SDK 4.5.0 this week or next week so it will happen right after.

**Comment by brianjmurrell** [comment]
Is this the _Apply prefix for outgoing calls and chat not working_ toggle that has been added to the account settings?  Is it supposed to work?

**Comment by Viish** [comment]
No I don't think it works yet.

**Comment by brianjmurrell** [comment]
Ahhh.  OK.  That matches my experience then.

**Comment by brianjmurrell** [comment]
With the 5.0.0 SDK and the path towards linphone 4.6.0, is this available yet, or still on the TODO list for that release?

**Comment by Viish** [comment]
It has been put in the roadmap for 5.1.0 SDK.

**Comment by brianjmurrell** [comment]
Is this in release/4.6 yet?

**Comment by Viish** [comment]
> Is this in release/4.6 yet?

No, and I don't think it will be in 4.6 release. Maybe 4.7 but even that isn't sure.

**Comment by brianjmurrell** [comment]
Remind me why I even need/want the _Country Prefix_ filled in?

**Comment by Viish** [comment]
To correctly match SIP URIs with contacts.

**Comment by devurandom** [comment]
Even when I remove the country prefix from the account settings page (the field is now empty), Linphone 4.6.5 says that the user does not exist when dialing an unprefixed number. Only when manually adding the service provider's domain, I can make calls.

**Comment by Viish** [comment]
Finally fixed in 1c7886ffb7e4e0b0513efa69b9a5e8ed9ffa0ccb.
