### ISSUE TITLE
Incoming calls not receiving if app killed

### ISSUE THREAD

**Issue by zgmunshi** [BelledonneCommunications/linphone-android#126]
Hi,

I have build the linphone android app and configured it with linphone sip server and its working fine till i swipe it out and close the app from taskmanager.

Once the app is closed no incoming calls are received, so i read and found that i need to integrate 'google-services.json' for firebase to work which is missing in linphone-android repo.

I added the file, i am getting the registration token and able to push notification from FCM console manually to the app. But still while calling from another device neither notification comes nor call is made.

Kindly let me know if i am doing anything wrong and what need to be done to fix this issue.

Regards,
Zeeshan.

**Comment by DatBewar** [comment]
Hi we don't provide our google-services.json for security issue, currently you couldn't use Linphone server with push notification if you build yourself the application.
