### ISSUE TITLE
Number pad not persistent when entering a phone number in messaging

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1269]
**Describe the bug**
When entering a phone number as the contact which to compose a message to, the keyboard reverts back to the alpha keys after entering each digit of the number.

**To Reproduce**
1. Open Messaging tab
2. Click compose message button
3. Click in the _Search a contact_ input box
4. When keyboard comes up, switch to number pad
5. Press a number

**Expected behavior**
Number pad should stay up for the entire time of entering a number

**Please complete the following information**
 - Device: All
 - OS: Android 8
 - Version of the App d2204b2c1
 - Version of the SDK ?

**Comment by Viish** [comment]
Indeed, it seems due to the two way data binding of the SearchView query field.

**Comment by Viish** [comment]
Fixed in f52d9ba9f6d2351b032224e6dec9ecf3b2b1ec4f
