### ISSUE TITLE
Caller App Crash in case of Serial Forking 

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#1270]
Hello @Viish ,

Scenario : In my setup I am using Kamailio as Proxy Server and FreeSwitch as Media server. The Call comes in Kamailio and in Kamailio append one branch and send it to FreeSwitch for Early Media. This whole setup is working with other phone but app is getting crashed at caller side in case of linphone. Everything working fine as soon as I stopped giving early media from FreeSwitch. Log is attached for the same.

[CallForkingCrash.txt](https://github.com/BelledonneCommunications/linphone-android/files/5791293/CallForkingCrash.txt)

Device Log : 

[DeviceLog.txt](https://github.com/BelledonneCommunications/linphone-android/files/5791303/DeviceLog.txt)

Also find .pcap for calls in this scenario

[callforking.zip](https://github.com/BelledonneCommunications/linphone-android/files/5792200/callforking.zip)

Please check logs and guide.

Thanks in advance.

**Comment by Viish** [comment]
Hi,
This issue has already been solved in a 4.5.0-beta SDK version, commit is bd59c3bec88b97cc21679049de88d147a34359b8.
Cheers,
