### ISSUE TITLE
Decline, Cancel SDP messages are not received at Receiver side and call doesn't disconnect

### ISSUE THREAD

**Issue by JitainSharma** [BelledonneCommunications/linphone-android#1278]
**Describe the bug**
Decline, Cancel SDP messages are not received at Receiver side and call doesn't disconnect.

**To Reproduce**
1. Call is made from our linux device to Android and vice versa
2. Click cancel from linux device, it sends the cancel message which never reach to Android

**Expected behavior**
The message should reach both side and call should cancel or decline gracefully.

**Please complete the following information**
 - Device: 
 - Android OS: 10
 - ANDROID SDK : 29
 - linphone-sdk : 4.5.0-alpha.62+a749d75

**Adb logcat logs**
[Android_log.txt](https://github.com/BelledonneCommunications/linphone-android/files/5835111/Android_log.txt)

**Linux device pcap logs file url**
[603_Decline_Linux_device.pcap](https://www.dropbox.com/s/32qvau7ou8yo9f0/603_Decline_Linux_device.pcap?dl=0)
[Call_Cancle_Linux_Device.pcap](https://www.dropbox.com/s/lqm6rlu6nvrihyt/Call_Cancle_Linux_Device.pcap?dl=0)

Please have a close look and suggest the fix to this.

**Comment by Viish** [comment]
First, please reproduce the issue with the latest 4.5 version, currently 4.5.0-beta.43+c927a08

**Comment by Viish** [comment]
Also, your client being configured to connect using UDP, messages can easily get lost. Switching to TCP will probably fix the issue.
And finally, if you reproduce anyway, please also attach a wireshark capture at the Android device level.

**Comment by JitainSharma** [comment]
Please find the logs at both Android and Linux Device side.
Also, the Transport Type is select to TCP at both Android app and Linux Device level.

Android App Log File:
[Android_App_Decline_Log.txt](https://github.com/BelledonneCommunications/linphone-android/files/5847455/Android_App_Decline_Log.txt)

Android packet capture pcap files:
[android_decline_ack.pacp](https://www.dropbox.com/s/ys6dpsry257z0hj/android_decline_ack.pacp?dl=0)
[android_decline.pcap](https://www.dropbox.com/s/ih4q7ahqlqglx1s/android_decline.pcap?dl=0)
[android.pcap](https://www.dropbox.com/s/f0dszuei2zx5ikz/android.pcap?dl=0)

Linux device pcap logs file url:
[pcap_decline.pcap](https://www.dropbox.com/s/6mpmdyfdzpfmukc/pcap_decline%20from_app.pcap?dl=0)
[pcap_Cancle_from_device.pacp](https://www.dropbox.com/s/hpbq1thso5j2tip/pcap_Cancle_from_nano.pcap?dl=0)

Hope this will provide more insight, and please let me know for any other requirement.

**Comment by Viish** [comment]
You have quite a complex setup with many nodes using UDP to communicate:
```
2021-01-21 12:28:51.068 8338-8338/? I/MiEntry: Via: SIP/2.0/TCP 199.7.173.181:5060;branch=z9hG4bK71c1.47647d53.1
2021-01-21 12:28:51.068 8338-8338/? I/MiEntry: Via: SIP/2.0/UDP 199.7.173.101:5060;received=199.7.173.101;rport=5060;branch=z9hG4bK71c1.c5405802.0
2021-01-21 12:28:51.068 8338-8338/? I/MiEntry: Via: SIP/2.0/UDP 199.7.173.101:5060;branch=z9hG4bK71c1.a5405802.1
2021-01-21 12:28:51.068 8338-8338/? I/MiEntry: Via: SIP/2.0/UDP 199.7.173.181:5060;branch=z9hG4bK71c1.37647d53.0
2021-01-21 12:28:51.068 8338-8338/? I/MiEntry: Via: SIP/2.0/UDP 192.168.1.100:5060;received=183.83.208.31;branch=z9hG4bKde2132cf-fafd-5b1f-962c-fcc23d083827;rport=57675
```
Also your SDK logs don't match the pcap traces which doesn't help.

It would be very time consuming for me to take a deep look at your issue, so if you need more help please contact our company for a support contract using the form available on https://linphone.org/contact.

**Comment by JitainSharma** [comment]
Can you please share what is the real problem here.

**Comment by Viish** [comment]
I don't know. If the issue is packets being lost, UDP is probably the cause, that's all I can say.

**Comment by JitainSharma** [comment]
Hi @Viish can you share the contact details for the support contract to which we can directly talk about.

**Comment by Viish** [comment]
Use the contact form button at https://linphone.org/contact#content-bottom3
