### ISSUE TITLE
Fixing chat participants

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1280]
After having spent some time looking over the (`linphone.db`) database schema in an effort to change the local contact of some chats to a different local contact, I thought this would do it:

```
update chat_room_participant set participant_sip_address_id=41 where participant_sip_address_id=7;
update conference_chat_message_event set from_sip_address_id=41 where from_sip_address_id=7;
update conference_chat_message_event set to_sip_address_id=41 where to_sip_address_id=7;
update chat_message_participant set participant_sip_address_id=41 where participant_sip_address_id=7;
```

I was able to copy the database from my phone, update it per the above and copy it back.  Repeating the copy-from operation and examining the copy confirmed that the operations of copying from and to the device were successful.

However, when I open linphone (I killed it before copying back to the device) after copying back to the device, I am still seeing multiple chats where there should be only one, per the local recipient fixing above.

Am I missing something about this procedure?

**Comment by Viish** [comment]
You forgot to update the chat_room table that contains identifies each chat room individually with the tuple peer_sip_address_id / local_sip_address_id

**Comment by brianjmurrell** [comment]
I did initially have:

```
update chat_room set local_sip_address_id=41 where local_sip_address_id=7;
```

but that violates _uniquness_ requrements, pressumably `UNIQUE (peer_sip_address_id, local_sip_address_id)` because when I try to change `7`s to `41`s in those, pressumably it creates duplicate `chat_room` records.

But perhaps that's not the change you are suggesting?  Perhaps it's updating the `last_message_id`?  Or something else even?

**Comment by Viish** [comment]
If you want to "merge" chat rooms, then you have to delete the "second one" from the chat_room table and update all references to that chat room in all other tables.

**Comment by brianjmurrell** [comment]
What does it mean when `last_message_id` is `0` in `chat_room`?

**Comment by Viish** [comment]
`last_message_id` is simply the id in the `conference_chat_message_event` of the most recent message in this chat room. If it's 0 it means the chat room is empty.
`last_update_time` is a timestamp that represents the time at which the last event in the chat room happened.
If those values aren't "right" it's no big deal, it will be corrected on the next message sent or received.

**Comment by brianjmurrell** [comment]
I think I have this.  Looking to do some verification of the results.  Wondering if you would take pity on a SQL greenie and help him come up with a query that produces:
```
sip_address.from_sip_address_id|sip_address.to_sip_address_id|chat_message_content.body
```

I can see that I need a `join` from `chat_message_content.event_id` -> `conference_chat_message_event.event_id`, but it's further joining from `conference_chat_message_event.{to,from}_sip_address_id` to `sip_address.value` that I am just not quite figuring out.

Much appreciated if you'd care to oblige.
