### ISSUE TITLE
Sources of broken chats

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1282]
As you know, I have been debugging sources of SIP SIMPLE conversations with a single contact being broken across multiple chat rooms (and a tool to reconstitute broken chat rooms, which seems to work pretty well).

One source of this problem is inconsistency in phone number formats.  A classic example of this is the free-dialed contact vs. the fully-qualified contact as you might find in a phone-book, or on some kind of global source, such as the Internet.

For example, I can free-dial a contact in the message compose window by entering (the common North American understanding of a phone number) 2345551212 and then send them a message.  All is fine.

If that contact then shows up in an address book (either by me adding it myself, or my assistant adds it, or it's added to a group or organization shared address book. etc.), but it's not in the identical same _free-dial_ format (i.e. say it's entered in it's more formal/global format of +12345551212, and I then send a message to that contact, linphone considers those different contacts and breaks the conversation.

While, yes, I can see from a programmatic perspective, `2345551212@example.com != +12345551212@example.com`, in the real world, these are the same thing.  In North America, 2345551212 and +12345551212 are the same entity.

So, I can do all kinds of tricks on the SIP server to canonicalize these different formats into a single format so that linphone's peer address is always a single consistent format.  But that doesn't do anything about linphone's local contact address and different formats (entered by humans) for what is in the real-world, the same contact.  I will still get broken conversations.

Of course the simple "won't fix" answer to this is that everyone needs to re-learn how to type phone numbers so that everyone in the world is consistent with everyone else.  I would argue that as _logical_ as that might seem, _logical_ does not always equal _practical_.  You are not going to teach grandma that phone numbers should always be dialed in +1 format.  You are not even going to get my wife, or kids, or practically anyone else to do it.

I would throw even more of a wrench into this and suggest that there are lots of places in North America where you don't even have to use the _area code_ for local area numbers.  I.e. 5551212 if it is in the same area code as the caller.

So what is the **practical** solution to this problem?

**Comment by Viish** [comment]
Yes, in the real world 2345551212 is equal to +12345551212, but only if you are located on the US. In any other country this isn't true.
Note that emails also consider that `2345551212@example.com != +12345551212@example.com`, and pretty much every internet protocol will behave this way, and for that we can't do much, it's the server responsibility to always use the same format.
That is the logical part.

Once the server is configured to always use the same format, our SDK will work just fine.
Thanks to the prefix setting, we are able to convert phone numbers like 2345551212 to +12345551212 and the other way around, so no matter the format in which the phone number is stored in your addressbook, we can match the contact correctly. We even support numbers like 234-555-1212, but we don't support numbers without area codes like 5551212 as we can't detect the correct value to prepend.
That is the practical part.

**Comment by brianjmurrell** [comment]
> Yes, in the real world 2345551212 is equal to +12345551212, but only if you are located on the US.

It's not just the US.

[The North American Numbering Plan (NANP) is a telephone numbering plan for World Zone 1, which comprises twenty-five distinct regions in twenty countries primarily in North America, including the Caribbean.](https://en.wikipedia.org/wiki/North_American_Numbering_Plan#:~:text=The%20North%20American%20Numbering%20Plan,not%20participate%20in%20the%20NANP.)

> Note that emails also consider that 2345551212@example.com != +12345551212@example.com, 

That's orthogonal.  We have been able to introduce consistency in e-mail addresses since day 1.  There is no decades of experience with to have to try to wipe out.  There is no trying to tell people that things that do actually work and that they have been doing for decades in the real world are actually wrong.  That's that you are trying to do by not making allowances in the NANP .

> and pretty much every internet protocol will behave this way,

But we are not dealing with Internet engineers here.  We are dealing with real people and a real system that has been around for 70+ years.  You can't just jump in there and tell people the way that have been doing it all of their lives and the way that it actually works in the real world is all wrong.

> and for that we can't do much, it's the server responsibility to always use the same format.
That is the logical part.

As I said, the server using the same format is achievable.  The problem is on the linphone end, where the users are in charge of the numbers they can enter into their phone and linphone using them literally instead of doing what you say the server should be (and is) doing and normalizing or canonicalizing them to allow the many legal representations of a single contact.  There is nothing the server can do about how linphone stores contacts based on what humans enter.

So linphone needs to do exactly what you are prescribing the server should do.

> Once the server is configured to always use the same format, our SDK will work just fine.

The server is configured to always use the same format.  The address as received by the server will always be of the same format.  The problem is on the linphone side where it does not understand the many forms of the remote contact where they are actually the same.

> Thanks to the prefix setting, we are able to convert phone numbers like 2345551212 to +12345551212 

But linphone doesn't actually do that.  When I enter `2345551212` into the contact input when composing a message, `2345551212@example.com` is what is is stored as the contact id.  If I then enter `12345551212` a different time, a new contact is created as `12345551212@example.com`, resulting in a new (broken) chat/conversation.

> and the other way around, so no matter the format in which the phone number is stored in your addressbook, we can match the contact correctly.

But you don't.  Per above.

It sounds like you are saying linphone is supposed to canonicalize when determining the account id.  But is not.  So this seems to now be a bug report.  Can you please re-open the ticket accordingly (assuming you don't just fix it immediately)?

> We even support numbers like 234-555-1212, but we don't support numbers without area codes like 5551212 as we can't detect the correct value to prepend.

No, you cannot _detect_.  But you could do what you already do with asking the user for the prefix setting and ask them what their area code is.  But probably more practical just have the user enter their fully qualified global phone number (+1*NPANXXXXXX* in the NANP part of the world) into their account and then linphone figured out how to canonicalize the local contact value based on what it knows and how the NANP works.  The rules for that are not at all difficult.  It's a simple masking problem which can be solved easily with a _substring_ operation:

```
canon_peer = substr(local_canon_number, 0, strlen(local_canon_number) - strlen(cleaned_up_user_dialed_number)) + canon_peer.
```

**Comment by Viish** [comment]
> When I enter 2345551212 into the contact input when composing a message, 2345551212@example.com is what is is stored as the contact id. If I then enter 12345551212 a different time, a new contact is created as 12345551212@example.com, resulting in a new (broken) chat/conversation.

Next time please explain the problem directly instead of all the fuzz above.
Issue has been fixed in latest 4.5-beta version of the SDK.

**Comment by brianjmurrell** [comment]
> Next time please explain the problem directly instead of all the fuzz above.

To be fair, from my perspective, you have been pretty resistive to listening to the problems with accounts and broken chats, so a comprehensive explanation seemed necessary to not just get a knee-jerk WONTFIX/ticket closed.  Maybe you will find that explanation unfair, but to every individual, perception is reality.

> Issue has been fixed in latest 4.5-beta version of the SDK.

Is that what I will get if I build 21a00a562?

I _think_ I am seeing what seems to be the solution.  Is it that when I type _2345551212_ into the search box, even if a contact is not found matching, the only option given to the user is to select the _+12345551212 (sip:+12345551212@example.com)_ from the list below the search box?  I.e. there is no other way to move onto composing the message without first clicking that canonicalized address?

**Comment by Viish** [comment]
> Is that what I will get if I build 21a00a5?

SDK version isn't linked to app version, but it's always best to use the latest version of the app as well. 
Just clear the gradle cache and build the app again, and check in the build logs or the About page which version of the SDK has been used. 
As long as it's 4.5.0-beta.50 or newer it will contain the fix.

>  Is it that when I type 2345551212 into the search box, even if a contact is not found matching, the only option given to the user is to select the +12345551212 (sip:+12345551212@example.com) from the list below the search box?

Yes, the prefix set in the proxy config wasn't used for the result matching the user's input in the search field.

**Comment by brianjmurrell** [comment]
> As long as it's 4.5.0-beta.50 or newer it will contain the fix.

Seems I have it: SDK 4.5.0-beta.50+c67027b.

Thanks.
