### ISSUE TITLE
While app is killed or swipe out by user and once push comes from FCM incoming call not received due to service not waked up in oreo and above devices please help me out let me out from this trouble as i struggling for this issue for week

### ISSUE THREAD

**Issue by Mukesh2310** [BelledonneCommunications/linphone-android#1286]
[PushNotificationService] Starting context
[Context] Device has been restricted by user (Android 9+), push notifications won't work !
[Context] Starting, push status is true
[Platform Helper] Device has been restricted by user (Android 9+), push notifications won't work !
We are here because of a received push notification, enter background mode before starting the Core
[Push Notification] firebase push sender id 1022373558799

**Comment by Viish** [comment]
Please attach full SDK logs.

**Comment by Viish** [comment]
By the way, per the log `[Platform Helper] Device has been restricted by user (Android 9+), push notifications won't work !`, problem lies in your device configuration. Check this: https://stackoverflow.com/questions/55226433/android-p-background-restriction-for-firebase-cloud-messaging
