### ISSUE TITLE
Linphone become unregister after 1 hour

### ISSUE THREAD

**Issue by ehsanmqn** [BelledonneCommunications/linphone-android#1287]
Hello,
We are developing a soft-phone based on liblinphone (SDK 4.4.8). We have encountered with registration problem with our application. The problem is that the account registration status changes to UNREGISTER after 1 hour. We also tried "Expire: 60" but it didn't change anything. It will be appreciate, if you guys guide us please.

**Comment by Viish** [comment]
Duplicate of https://github.com/BelledonneCommunications/liblinphone/issues/169
