### ISSUE TITLE
send sip simple message fails

### ISSUE THREAD

**Issue by rtreleaven** [BelledonneCommunications/linphone-android#129]
Linphone Android 3.2.8
Linphone Core 3.12.0-199-gddd080522

to reproduce

- tap chat button
- select correspondent
- type a message "test 1"
- tap send button

observed results

- text is not sent, nothing happens

expected results

- text is send to correspondent

**Comment by DatBewar** [comment]
Hello,
I don't have any problem with chat on master.

**Comment by rtreleaven** [comment]
I not using sip.linphone.org maybe that is the difference.

I have with 3 android linphone devices

1 nexus 6 running and 1 samsung tablet running

Linphone Android 3.2.8
Linphone Core 3.12.0-199-gddd080522

1 nexus 5 running the non beta version from google play

the nexus 6 and the tablet both fail
the nexus 5 works as expected.

I will investigate further tomorrow

**Comment by rtreleaven** [comment]
My b2bua is also dropping messages that meet this critera so that I don't send empty messages to ua's that don't support these types.

my $type = $message->getHeader('type');
if ($type =~ m/(application\/im|message\/imdn)/i) {
	my_misc::fs_log("content-type='$type'");
	my_misc::fs_log('---end of chatplan.pl---');
	return(1);
}

**Comment by rtreleaven** [comment]
verified fixed in 
Linphone Android 3.2.8
Linphone Core 3.12.0-222-g145b05ee8
