### ISSUE TITLE
Call time and duration does not display for inbound calls in call log

### ISSUE THREAD

**Issue by dln949** [BelledonneCommunications/linphone-android#1290]
LInphone 4.3.1 on my android device.  

On the main screen, when I tap on the icon that displays the call log, I see the call log.  But, when I tap on the entry for any inbound call, it does not display the time of the call, nor the duration.

How do I make the time and duration of inbound calls display?

Thanks.

**Comment by Viish** [comment]
Hi,

Please attach a screenshot of the issue.

Cheers,

**Comment by dln949** [comment]
I attach two screenshots.  One, outbound, sows time and duration of call.  The other, inbound, does not show that.  

-----Original Message-----

**Comment by Viish** [comment]
I don't see any screenshot.

**Comment by dln949** [comment]
Sorry, trying again

![Screenshot_20210213-080739](https://user-images.githubusercontent.com/8601150/107860260-0784cb80-6e04-11eb-9c13-88987bae99f7.png)

![Screenshot_20210213-080758](https://user-images.githubusercontent.com/8601150/107860265-0d7aac80-6e04-11eb-824e-eb4beca06e33.png)

**Comment by Viish** [comment]
Weird.

Can you enable the debug logs at app level, restart the app, receive a call, go to the history, go to the about page, upload logs and copy/paste the logs link here please?

Cheers,

**Comment by dln949** [comment]
[https://www.linphone.org:444//tmp/602a84d1b1754_b50520aa06b5053dbe4e.gz](url)

**Comment by Viish** [comment]
Ok I understand. It's because the call isn't made to your default proxy config identity but another one.
I've fixed the issue in release/4.4 branch.
Cheers,

**Comment by dln949** [comment]
Ok, thanks, but.....  I don't know what that means for me right now, sorry.    

Is this version 4.4 something that is available now?  If so, where?  (My android device is not telling mt that there is an update available from F-Droid.)  Or, coming soon????

**Comment by Viish** [comment]
4.4 release is currently in stabilization, when test plan will be OK we will publish it.
In the meantime, either build it yourself or join the beta channel on the Play Store.

**Comment by Viish** [comment]
Or use this APK: http://linphone.org/releases/android/linphone-android-4.4.0-beta.17+9580befc8.apk
