### ISSUE TITLE
Not acceptable then calling to freeswitch voicemail.

### ISSUE THREAD

**Issue by alex-eri** [BelledonneCommunications/linphone-android#1291]
Linphone-Android 4.3.1 SDK 4.4.2

Desktop version works, but not Android version. Calling to extension with another user works with `proxy-media=true`

SDP attached
[notacceptable.zip](https://github.com/BelledonneCommunications/linphone-android/files/5980983/notacceptable.zip)

**Comment by Viish** [comment]
Please attach logs from app (enable debug logs from advanced settings first).

**Comment by alex-eri** [comment]
https://www.linphone.org:444//tmp/602a558d38f5a_e7e9cb9bb34ea42b0fdb.gz

**Comment by Viish** [comment]
Can yo do the same of a call that works? Either incoming or outgoing?

**Comment by alex-eri** [comment]
https://www.linphone.org:444//tmp/602a7980ba9d0_55a4b7ad9d7eb1a25b84.gz

I turned off proxy media on freeswitch and vm works.

**Comment by Viish** [comment]
This means your proxy media didn't support any of the enabled audio codec in the app.

**Comment by alex-eri** [comment]
It supports: Pcma, pcmu, g722 - enabled. calling to user works too. https://www.linphone.org:444//tmp/602a7bc580480_ea9b08464e555b1db652.gz

**Comment by alex-eri** [comment]
And desktop version works in both cases
