### ISSUE TITLE
Speaker Issue from going from Call Outgoing activity to Call Activity.

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#1292]
Hello @Viish ,

I had noticed one bug while compiling source code, After compiling the speaker is misbehaving means if I switch speaker on on Call Outgoing window the speaker automatically switched off when Call window opened. The same thing is working fine if I downloaded apk from Play store.

Following happening : 

I/ViewRootImpl@6f13de1[CallOutgoingActivity]: ViewPostIme pointer 0
I/ViewRootImpl@6f13de1[CallOutgoingActivity]: ViewPostIme pointer 1
D/AudioManager: setSpeakerphoneOn true
D/.linphone.debu: PlayerBase::stop() from IPlayer
D/AudioTrack: stop(2551): called with 504000 frames delivered
D/AudioManager: setSpeakerphoneOn false
W/libOpenSLES: Conversion from OpenSL ES positional channel mask 0x4 to Android mask 0 loses channels
I/libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x4, using default mask 0x10 based on channel count of 1)
D/AudioRecord: openRecord_l() remove fast or raw flag of voip calls, source=7, flags=5

[logcat.txt](https://github.com/BelledonneCommunications/linphone-android/files/6000404/logcat.txt)

**Comment by Viish** [comment]
Hi,
Should be fixed in feature/kotlin_rewrite branch, and maybe on release/4.4 branch also.
Cheers,

**Comment by amit1576** [comment]
Hi @Viish,

Hope you are doing well.

One more interesting observation regarding speaker, if during call both party switch on their speaker the volume coming out from speaker automatically decreases and one had to take phone near to his ears, and when out of two anyone switch off his speaker, volume of other party speaker automatically increases and audible in speaker mode.

Please check this also. This is in standard .apk from play store also.

Thanks in advance.
