### ISSUE TITLE
How to set 128 bits for SRTP media encryption from app

### ISSUE THREAD

**Issue by gresakrasniqi** [BelledonneCommunications/linphone-android#1293]
Is the 128 bits for the SRTP media encryption set by default? If not, can this be changed in app level and how?

I have checked previous issues which were related to the question I had. I checked this link:
[SRTP 256 bit Encryption & TLS Version](https://github.com/BelledonneCommunications/linphone-android/issues/828
)
but wasn't able to get a clear answer as the issue was closed with no clear answer.

**Comment by Viish** [comment]
As explained in the ticket you linked, you have to edit the factory configuration file (or default one if you haven't installed the app yet or plan to uninstall/reinstall it) and add the following:
`[sip]
srtp_crypto_suites=AES_256_CM_HMAC_SHA1_80,AES_256_CM_HMAC_SHA1_32`
