### ISSUE TITLE
User data not being saved in sdk

### ISSUE THREAD

**Issue by bensadiku** [BelledonneCommunications/linphone-android#1295]
**Describe the bug**
User data is not saved in the sdk `void setUserData(Object var1);`. When i try to get the same object via `CallLog` object, It always returns null.

**If the issue is about the SDK (build, issue, etc...) open the ticket in the [linphone-sdk](https://github.com/BelledonneCommunications/linphone-sdk) repository or one of it's submodules!**

**To Reproduce**
1. Save a random object via the Address object. e.g.
```Java
String name = "1";
address.setUserData(name);
```

**Expected behavior**
I expect to have the same object when i call `getUserData`
**Please complete the following information**
 - Device: [e.g. Samsung Note 20 Ultra]
 - OS: [e.g. Android 9]
 - Version of the App [latest master]
 - Version of the SDK [lastest master]

**Comment by Viish** [comment]
Hi,
setUserData/getUserData is handled directly by java classes, which means if the Java object changes, user data is lost. It's not meant to be used for middle/long term information storage.
Cheers,
