### ISSUE TITLE
[HOW2] - Get usb headset click events

### ISSUE THREAD

**Issue by TheMasterRoot** [BelledonneCommunications/linphone-android#1296]
hello. id like to overwrite the usb headset click buttons to custom commands.
there is any place in linphone that handle mediabuttons to change the function ?
or where can i implement it ?

**Comment by Viish** [comment]
Hi,
This is currently not done, so you have to start from the beginning.
Regarding where to do it, I guess the Headset receiver or the CallManager might be a good idea but as I don't know how to do what you intend to, I can't say for sure.
Cheers,

**Comment by TheMasterRoot** [comment]
thank you. i will do a heasetreceiver . i nee dto overwrite media buttons functions to call a api that will make commands on a system. like next call or terminate current call or open a issue ticket request for that call.
