### ISSUE TITLE
Need to pause a call and resume, to hear the other side

### ISSUE THREAD

**Issue by xstable** [BelledonneCommunications/linphone-android#1297]
**Describe the bug**
If I got a call or if I call to anybody, I hear only silence if the one I've called pick up the phone. 
Then I have to click pause and resume the call to hear him.

**Expected behavior**
Sure... I don't wan't to do that ;)

**Please complete the following information**
 - Device: Xiaomi Mi A1
 - OS: Android 9
 - Version of the App  4.3.1
 - Version of the SDK 4.4.2

**Comment by Viish** [comment]
Please attach logs showing the issue.
