### ISSUE TITLE
Issues in contact management from Linphone

### ISSUE THREAD

**Issue by astuter** [BelledonneCommunications/linphone-android#130]
There are many issues in Contact section of Linphone. These have been here for a long while. Please have have a look at following cases:

> Contact list not updating right away after adding new contact from Linphone.

> Contact details are not getting updated/stored many times while editing from Linphone.

> Phone and SIP numbers are gone after updating contact from Linphone.

To reproduce all this issues test on real phone device which have 500+ contacts also synced many times or from multiple sources. 
As per my observation, this happens due to mismatch of Contact_id. When we sync or edit contacts multiple time, we face contact duplication issue in Android due to contact_id of `ContentProvider`. This can be the cause for it, but how we can solve it?

**Comment by astuter** [comment]
Hello @DatBewar 

I had updated the issue description? can you have a look at this?

**Comment by astuter** [comment]
Hello @DatBewar ,

Any thought on this? I can confirm that this issue exits even on recent sdk and apk available on play store. 

Following are the steps to produce this issue:

1) Install Linphone app from Play store.
2) Go to contact list and try to edit any contact. 
3) Go back and check if its updated with new values on contact list screen. (if its is, than great :) )
4) Now, go to native contacts app of mobile phone. 
5) Update the same contact that you have updated in step 2.
6) Go back to Linphone app and try to edit same contact.
7) Now variable if contact is updated on contact list and also on native contact app. (Its not updating now anymore)

**Comment by astuter** [comment]
Hi @DatBewar ,

Any update on this?

**Comment by asafron** [comment]
@Viish Why is this closed? All issues still appeared in latest code version

**Comment by Viish** [comment]
This issue has been fixed on master branch and will be available in the next release.

**Comment by qmontal** [comment]
Hi! for some reason I am still being affected of this on Linphone 4.2.3 for Android, my Address book is empty even though a colleague has been able to call me and I have the contact available for chat. Maybe the bug has been reintroduced in the latest releases?
