### ISSUE TITLE
Calls are paused uninten

### ISSUE THREAD

**Issue by JackWallaceU** [BelledonneCommunications/linphone-android#1301]
**Describe the bug**
Hello, I compiled linphone_sdk a few months ago. It causes an error, some of the calls I make/receive  are started at paused state. When I disable the local SDK and use 4.5+ through build.gradle instead, same error is given. If I change it to 4.4+ it doesn't fail. I have to use my locally built sdk and therefore I downloaded the sdk version 4.4. However I can't compile it. It gives the following errors.

-- Configuring incomplete, errors occurred!
See also "/Users/Desktop/linphone_sdk_01.03.21/linphone-sdk/build/android-arm64/CMakeFiles/CMakeOutput.log".
make[2]: *** [android-arm64-prefix/src/android-arm64-stamp/android-arm64-configure] Error 1
make[1]: *** [CMakeFiles/android-arm64.dir/all] Error 2
make: *** [all] Error 2

**If the issue is about the SDK (build, issue, etc...) open the ticket in the [linphone-sdk]
I open this ticket to linphone/android because I use android source code and the error is generated within the android project.

**SDK logs**
Enable debug logs in advanced section of the settings, restart the app, reproduce the issue and then go to About page, click on "Send logs" and copy/paste the link here.
https://www.linphone.org:444//tmp/603cd9c875f9d_47dcd456191699a4ed05.gz

**Comment by Viish** [comment]
Call is considered as "paused" because of the sendonly audio parameter in the SDP: `a=sendonly`
If you have a build issue, please open a ticket on linphone-sdk project.

**Comment by JackWallaceU** [comment]
Yes but I don not send a sendonly invite. I make a call or receive a call and among approximately 10 calls 1 or 2 of them send a second sendonly invite after the correct call invite. This is not an issue with sdk 4.4. When I upgrade the sdk version to 4.5+ this error occurs.

Can you help with compiling the 4.4+ sdk?

Thanks.

**Comment by Viish** [comment]
From your logs, call is being paused because of lost audio focus, which means you may have a received a GSM call or started playing music, etc...
When such situation is detected, call is being paused automatically starting SDK 4.5+.
You can disable that by setting the following in your linphonerc_factory file:
```
[audio]
android_pause_calls_when_audio_focus_lost=°
```

Regarding the build, please open an issue with the build logs.

**Comment by JackWallaceU** [comment]
I copied the following to linphonerc_factory. It still loses audio focus. In the logs, the first call is successful, the second one is paused. Is there another way to disable the audio focus property? Shall I do that on the sdk source code?

[audio]
android_pause_calls_when_audio_focus_lost=0

Regards.

**Comment by Viish** [comment]
You are using an alpha version of 4.5 SDK, and the setting has only been added in a 4.5 beta version. Update your SDK.

**Comment by JackWallaceU** [comment]
Hi @Viish is the master code alpha version? Should I try 4.5 release version?

**Comment by Viish** [comment]
Yes, master branch is alpha version. Release/4.5 branch is beta version for now, then release when it will be published.
