### ISSUE TITLE
Facing Video Call issue in linphone SDk 4.5+ in android

### ISSUE THREAD

**Issue by RaviChavada** [BelledonneCommunications/linphone-android#1304]
Hello, I am using linphone android SDK version 4.5+ and I am not able to do a video call when I  enable **Accept video incoming request** from the video setting, then it will show only my video, and after answer the call I am not able to show the video of another end,
even if I click on the video icon then do some progress and closed it. 
if I am missing something then please guide me

**Comment by Viish** [comment]
Hi,
Please attach logs & a video of the issue.
Cheers,
