### ISSUE TITLE
Port Update In Domain Field 

### ISSUE THREAD

**Issue by Adnan-addi** [BelledonneCommunications/linphone-android#1305]
Hi @Viish 

I want to update the port in the app 

but i think 

`
        mDomain.setListener(new SettingListenerBase() {
            @Override
            public void onTextValueChanged(String newValue) {
                if (newValue.isEmpty()) {
                    return;
                }
                if (newValue.contains(":")) {
                    Log.e("[Account Settings] Do not specify port information inside domain field !");
                    return;
                }
                if (mAuthInfo != null) {
                    mAuthInfo.setDomain(newValue);
                } else {
                    Log.e("[Account Settings] No auth info !");
                }
                if (mProxyConfig != null) {
                    mProxyConfig.edit();
                    Address identity = mProxyConfig.getIdentityAddress();
                    if (identity != null) {
                        identity.setDomain(newValue);
                    }
                    mProxyConfig.setIdentityAddress(identity);
                    mProxyConfig.done();
                } else {
                    Log.e("[Account Settings] No proxy config !");
                }
            }
        });
`

this code says [Account Settings] Do not specify port information inside domain field ! 
where i can change the port with domain from app interface or programatically.

UPDATE:
i can find port in Network settings and updating it doesnot update the address on sidemenuaccount address?

Thank you.

**Comment by Viish** [comment]
Hi,
Port information must be set in the serverAddress field, not the domain.
Cheers,
