### ISSUE TITLE
How to refresh the camera feed after turning off my camera.

### ISSUE THREAD

**Issue by gresakrasniqi** [BelledonneCommunications/linphone-android#1306]
The issue that I have is that when I turn off my camera from an android device, the camera feed only freezes and is not turned off completely.
I want to be able to turn off the camera feed at once while I'm on a call directly on the android device that I'm using. This issue is occurring for multiple providers (Google, Teams, Bluejeans, Zoom etc.).

Steps To Reproduce:
Login to a SIP account,
Start a google meet meeting on web
Join that meeting with SIP from the android app
Click disable the camera. It doesn't show as disabled, it looks like the camera is frozen because of the last frame shown.

This is how I tried to update the call after the user clicks on the toggleVideoButton:
```
params.enableVideo(true);
params.setVideoDirection(MediaDirection.RecvOnly);
call.update(params);
```

The reason why we're adding MediaDirection.RecvOnly is because we want to keep receiving video from other conferences such as Google meet, zoom etc.

**Comment by Viish** [comment]
TextureView won't be updated once you disable the camera, so yes the last frame will be "frozen". Simply change the visibility of the TextureView to Invisible or Gone.

**Comment by gresakrasniqi** [comment]
The problem is not occurring on the android device, I already set the visibility of the TextureView to GONE. The issue is that the camera feed on the call for the other users who are connected from the browser is frozen, and is not removed completely. That means that the participants of the call can still see my frozen camera feed.

**Comment by Viish** [comment]
As Simon answered you on the Mantis ticket, problem is in the pexip server you use. 

Please don't duplicate Mantis issues here.
