### ISSUE TITLE
Android intents

### ISSUE THREAD

**Issue by sickidolderivative** [BelledonneCommunications/linphone-android#1307]
Hello everyone

I've been successful using the intents specified in AndroidManifest.xml file (https://github.com/BelledonneCommunications/linphone-android/blob/master/app/src/main/AndroidManifest.xml) to switch directly to desired screens e.g. intent:#Intent;component=org.linphone/.chat.ChatActivity;end to go directly to my chats.

Is there a way to switch to incoming call screen or answer an incoming call by an intent? 

Sid

**Comment by Viish** [comment]
Hi,

What would be the purpose to display the incoming call screen through an intent if there is no incoming call?

Cheers,

**Comment by sickidolderivative** [comment]
I’m using Fully Kiosk Browser in kiosk mode to display a Home Assistant dashboard. All notifications are turned off. When my VTO door intercom attempts to make a call I receive a mqtt message that I can act upon e.g. switch apps to Linphone incoming call screen. 

Ideally, I would answer an incoming voice call while keeping Linphone app in the background. Is that be possible?

**Comment by Viish** [comment]
First of all I recommend to look at the [feature/kotlin_rewrite](https://github.com/BelledonneCommunications/linphone-android/blob/feature/kotlin_rewrite) branch that will soon become the new master. 

> Ideally, I would answer an incoming voice call while keeping Linphone app in the background. Is that be possible?

Yes if you use auto-answer setting. There is also a setting to prevent the app from showing up completely: https://github.com/BelledonneCommunications/linphone-android/blob/feature/kotlin_rewrite/app/src/main/java/org/linphone/core/CorePreferences.kt#L342

Other than that you will have to make your own changes in the app to get the exact behavior you expect, but that shouldn't be very hard.
