### ISSUE TITLE
Loading contacts takes ages

### ISSUE THREAD

**Issue by abdurrahmanarikan** [BelledonneCommunications/linphone-android#1308]
I have downloaded version 4.5 of linphone android. When clicks to show contacts, it takes too long to read contacts. Can you help ?

**Comment by Viish** [comment]
There is no 4.5 version of Linphone Android so I don't know what version you have.
Anyway please enable debug logs in advanced settings, restart the app, reproduce the issue and copy/paste here the link of the logs after uploading them from the About page.

**Comment by abdurrahmanarikan** [comment]
My bad, I would say using linphone SDK 4.5+. I'll try to enable logging. Thanks

**Comment by abdurrahmanarikan** [comment]
Please find below the files for logging. When the app starts, it asks permission to read the contacts then it takes too long (more than 15 mins, sometimes more) to read all the contacts. I see the progress bar circling all the time. Is there any way to make the contact read process faster? Thanks for helping me.

https://www.linphone.org:444/tmp/604becd29ca10_52202434ffbb5a98c3dd.gz
https://www.linphone.org:444/tmp/604bef22c09c9_ce7e0c5202894b1b3491.gz
https://www.linphone.org:444/tmp/604befb63a014_e5ab9c678aa70b713759.gz

**Comment by Viish** [comment]
> When the app starts, it asks permission to read the contacts then it takes too long (more than 15 mins, sometimes more) to read all the contacts.
How many contacts do you have?

I can't see in any of your logs the background task that is parsing the contacts, and I don't see the app start either.
Clean the log file, kill & restart the app and upload new logs.

Also if you are using your own built app, I recommend tou to test the feature/kotlin_rewrite branch.
