### ISSUE TITLE
Get usb headset 4 buttons control click event

### ISSUE THREAD

**Issue by TheMasterRoot** [BelledonneCommunications/linphone-android#1310]
i stoped all receivers and services from manifest of linphone project and i canot intercep a media key press event from a headset usb that im using in my cellphone.
i did a separate android project and all buttons works normaly with a receiver.
whwre in linphone project i can find the method that overwrite keypress biding functions?

**Comment by Viish** [comment]
The only one I see that could prevent that is https://github.com/BelledonneCommunications/linphone-android/blob/master/app/src/main/java/org/linphone/receivers/BluetoothReceiver.java#L112
