### ISSUE TITLE
Multiple messages from same contact

### ISSUE THREAD

**Issue by nick2601** [BelledonneCommunications/linphone-android#1311]
@Vish 
I am suppose to get multiple incoming messages from same contact and I want to store those messages in an Arraylist variable upon their arrival ,and for this I am using this code
```
@Override
                    public void onMessageReceived(
                            @NonNull Core core,
                            @NonNull ChatRoom chatRoom,
                            @NonNull ChatMessage message) {
                        super.onMessageReceived(core, chatRoom, message);
                        ArrayList<String> textMessage = new ArrayList<>();
                        String xml=null;
                        UserList userList = null;
                        {
                            for (Content c : message.getContents()) {
                                message.getChatRoom();
                                message.hasTextContent();
                                if (c.isText()) {
                                    textMessage.add(c.getUtf8text);
                                }
                                xml = textMessage.get(0);
                                android.util.Log.d(TAG, xml);
                            }
}
```
Unfortunately,I am not able to read those messages using this approach,Can you suggest some other way in storing the messages in list and retreiving values of one message at a time depending on their arrival.
Thanks in advance

_Originally posted by @nick2601 in https://github.com/BelledonneCommunications/linphone-sdk/issues/111#issuecomment-799202173_

**Comment by Viish** [comment]
Sorry I won't help you create your own app.

**Comment by nick2601** [comment]
Sorry,my bad I got it working fine ,my Issue was regarding the parsing logic.
