### ISSUE TITLE
Volume issue when both party switch on their speaker.

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#1313]
Hi @Viish,

Hope you are doing well.

One more interesting observation regarding speaker, if during call both party switch on their speaker the volume coming out from speaker automatically decreases and one had to take phone near to his ears, and when out of two anyone switch off his speaker, volume of other party speaker automatically increases and audible in speaker mode.

This issue is there in standard apk from play store also.

Thanks in advance.

**Comment by Viish** [comment]
Hi,

Please attach logs from both devices.

Cheers,

**Comment by amit1576** [comment]
Hi @Viish ,

Please find attached logs between 405 and 404. When only one party's speaker is on everything working fine but as soon as both switched on their speaker one was not able to hear anything at all.

[callee_404.txt](https://github.com/BelledonneCommunications/linphone-android/files/6189091/callee_404.txt)
[caller_405.txt](https://github.com/BelledonneCommunications/linphone-android/files/6189092/caller_405.txt)

Please check and suggest.

Thanks in advance.

**Comment by Viish** [comment]
Hi,

I don't know what you do or how you do but there is no evidence of the speaker being turned on in any of the logs files you attached.

Anyway you should first update the SDK to the latest beta version (4.5.115) or to the latest release (4.4.35). If you keep using the 4.5 beta, switch your app code to use the newly added `AudioDevice` API (see our `feature/kotlin_rewrite branch`).
I don't reproduce this issue myself.

Note that if both devices are nearby, the echo canceller might prevent audio from being heard.
If issue still persists, contact my company from premium support using our [website's contact form](https://linphone.org/contact#content-bottom3).

Cheers,
