### ISSUE TITLE
anr on android11

### ISSUE THREAD

**Issue by jayqean** [BelledonneCommunications/linphone-android#1314]
Hello @Viish ,
my app are often occur anr on android 11. Can you analyze it for me?
this is the log link. [https://github.com/jayqean/linphone-test/blob/main/linphone.log](https://github.com/jayqean/linphone-test/blob/main/linphone.log)

**Comment by Viish** [comment]
Hi,
FIrst of all you are using an alpha SDK. Please use either latest 405 beta or 4.4.x release.
Then no, without symbols in stack trace I can't say why this happens. Do you have the same issue with our app?
Cheers,

**Comment by jayqean** [comment]
How do I download the 4.5.0 beta version? This version of mine is the code that was pulled in August last year, and the crash log printing of the official android11 ​​is only synchronized later.

**Comment by jayqean** [comment]
How to pull the 4.5.0 beta version with git clone?

**Comment by Viish** [comment]
`git checkout release/4.5 && git submodule update --recursive --init`

**Comment by jayqean** [comment]
Hello, linphone wants to enable the software codec, how can I do it? Enable ffmpeg when compiling aar?

**Comment by Viish** [comment]
Depends on the codec, but ffmpeg isn't supported anymore.
