### ISSUE TITLE
network reachable issue

### ISSUE THREAD

**Issue by Cullian2017** [BelledonneCommunications/linphone-android#1315]
currently we are using linphone-sdk-android-4.4.0 for our project.

Before we make the outgoing call, we do core and network normal check as follow:
if(core == null || !core.isNetworkReachable()){
     ........
}

we got network not reachalbe error very often.  

Do we need check the network reachable before we make the outgoing call? if yes, what can we do in case that network is unreachable that monment? Does network unreachable equal to APP fial to connect to SIP server only or some other cases also can cuase network unreachable issue?

**Comment by Viish** [comment]
Hi,
You don't have to manually check for the network reachability. In case the network is down, call will fail and you will get a notification.
Yes if network is unreachable, it means the app won't be able to send packets on the network, so it won't be able to register to the proxy server.
Cheers,

**Comment by Cullian2017** [comment]
Dear Sylvain,

thank for yor prompt responose.

could you please confirm that the network unreachable is caused by internet network?

Best Regards

Jian Lu 
------------------------------------------------------------------
发件人：Sylvain Berfini ***@***.***>
发送时间：2021年3月17日(星期三) 15:21
收件人：BelledonneCommunications/linphone-android ***@***.***>
抄　送：Lu Jian ***@***.***>; Author ***@***.***>
主　题：Re: [BelledonneCommunications/linphone-android] network reachable issue (#1315)

Hi,
 You don't have to manually check for the network reachability. In case the network is down, call will fail and you will get a notification.
 Yes if network is unreachable, it means the app won't be able to send packets on the network, so it won't be able to register to the proxy server.
 Cheers,

**Comment by Viish** [comment]
> could you please confirm that the network unreachable is caused by internet network?

Yes.
