### ISSUE TITLE
Video decline error

### ISSUE THREAD

**Issue by judyklaus** [BelledonneCommunications/linphone-android#1316]
**Describe the bug**
Hi @Viish If I will decline a video call request, it still starts a video call. I use the Google Play/ Apple Store versions of Linphone.

**To Reproduce**
1. App1 calls App2 (audio)
2. App1 turns camera on and App2 accepts.
3. App1 turns camera on again, App2 declines.
4. Cameras are on.

Logs:
App1:
[linphone_log-2.zip](https://github.com/BelledonneCommunications/linphone-android/files/6164088/linphone_log-2.zip)

App2: https://www.linphone.org:444//tmp/605347c443d59_a44e33f82acd397b8f05.gz

Best regards.

**Comment by Viish** [comment]
This has already been fixed, use public beta on the Play Store.

**Comment by judyklaus** [comment]
Hi @Viish is this fixed in the SDK or in Android code?

**Comment by Viish** [comment]
Fixed in Android app, commit id afe2725d59dc8cd2d80dce324b85a8591b42e3e8
