### ISSUE TITLE
Release audiofocus?

### ISSUE THREAD

**Issue by hasanr68** [BelledonneCommunications/linphone-android#1317]
Hello all.

We are trying to make this version of the Linphone app work:

https://github.com/BelledonneCommunications/linphone-android/tree/feature/use_android_native_dialer/

Everything seems to work fine, however, when we use the native dialler to make calls - it doesn't release audio focus after we hang up. That means no notifications for other apps work and/or videos cannot be made or played. It could be issues with the TelecomManager or AndroidAudioManager. It works fine if we use Linphone without native dialer. Any thoughts please?

Thanks a lot in advance.

**Comment by Viish** [comment]
Hi,

Instead you should use feature/telecom_manager branch that is based on the new kotlin app.

Cheers,

**Comment by Viish** [comment]
By the way, starting with SDK 4.5, audio focus is handled by our library, not the app itself.

**Comment by hasanr68** [comment]
@Viish - thanks a lot for the help. We have started working with this version. Quick Q (Kotlin is new to us). We wish to switch on Native Dialler by default. However, running into some permission issue. I believe Read_Phone_State permission is required for telecom native dialer.
As telecom_manager is initialised in application class, how can we get his permission in in launcher class before initialising telecom? Because application class looks for telecom and it does not include any permission requesting Read_Phone_State hence crashes the app. 
Any idea on how to fix?
