### ISSUE TITLE
Video call error

### ISSUE THREAD

**Issue by judyklaus** [BelledonneCommunications/linphone-android#1325]
Hi @Viish, related to #1309, I downloaded 4.4 beta release of Linphone Android. The problem still continues.

App1 is an android phone and App2 is android emulator.
App1 calls App2. App1 turns cam on and then off. App2 cannot turn on camera. (No request is sent to App1)
(I muted the call intentionally)

App1: https://www.linphone.org:444//tmp/60546576e72b5_4991264d4d923c2aaabb.gz
App2: https://www.linphone.org:444//tmp/60546565917e4_efa2ab25b22c67923355.gz

Shortly, the one who turns the cam off can turn it on in the next stage. If the opposite side tries to turn the cam on, no success.

**Comment by Viish** [comment]
Have you tried with 2 real devices ? On the other way around ? It is likely this happens because App2 is on an emulator.

**Comment by judyklaus** [comment]
Hi @Viish  This test was made with two real devices.

**Comment by Viish** [comment]
> This test was made with two real devices.

No App2 is running on an emulator: `2021-03-19 11:48:05:251 [/mediastreamer] MESSAGE This device (Google/Android SDK built for x86/) says it has no built-in echo canceller.`

**Comment by judyklaus** [comment]
Sorry @Viish I copied the wrong message to this issue. I re-did the test and here are the logs of two real devices with the same scenario.

App1 logs: https://www.linphone.org:444//tmp/605b10dfae012_8d28a2a8d6d79c06358c.gz 
App2 logs: https://www.linphone.org:444//tmp/605b10deaa1ce_3a7b7f3d04e7a06daa8f.gz

**Comment by Viish** [comment]
Thanks, but there is no evidence in the logs that you are trying to turn the video on in App1 after App2 turned it on then off.
Can you record the screen of both devices to show me the issue?

**Comment by Viish** [comment]
Nevermind I found the issue.
Fix has been made in release/4.4 branch and will be part of 4.4 app release scheduled for next week.

**Comment by judyklaus** [comment]
Okay @Viish thank you.
