### ISSUE TITLE
Build issue with the Master branch

### ISSUE THREAD

**Issue by opg7371** [BelledonneCommunications/linphone-android#1326]
**Describe the bug**
After fetching the code of linphone through git in Android Studio, It is observed that the compilation of master branch fails every time.

**If the issue is about the SDK (build, issue, etc...) open the ticket in the [linphone-sdk]
The issue is with the compilation. Following issue is observed
```
/root/AndroidStudioProjects/linphone-android/app/src/main/java/org/linphone/chat/ChatMessagesFragment.java:95: error: ChatMessagesFragment is not abstract and does not override abstract method onNewEvent(ChatRoom,EventLog) in ChatRoomListener
public class ChatMessagesFragment extends Fragment
```

**To Reproduce**
1. Fetch the Linphone-android code in android studio.
2. Compile the code. 
3. See the compilation Error

**Expected behavior**
No compilation error should be observed.

**Please complete the following information**
 - Device: Ubuntu PC 
 - OS: Ubuntu 18.04
 - Version of the App [e.g. 4.3.1]   NO NEED
 - Version of the SDK [e.g 4.4.16]  NO NEED

**SDK logs**
NO NEED

**Adb logcat logs**
NO NEED

**Screenshots**
NO NEED

**Additional context**
When i checked out the branch 4.4, and compiled it, that was successful and Linphone was also working correctly after installing it. However, the problem seems to be coming with the master branch.

**Comment by Viish** [comment]
Hi,
Indeed master branch doesn't build at this time and we're aware of it, thanks anyway.
The fix is on release/4.4 branch, which will be merged on Monday into master, that's why we haven't fixed it on master yet.
Cheers,
