### ISSUE TITLE
Two registrations, in quick succession, both failing.

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1327]
Sometimes linphone registers twice in quick succession failing both registrations.

[Log](http://brian.interlinx.bc.ca/linphone-registers-twice.txt)

Any idea why?

**Comment by Viish** [comment]
In this case it's because you receive a push notification.
When this happens, we force a REGISTER if the proxy config is in a RegistrationFailed state, which is the case.
I don't know why it fails though, except it seems to be a network issue.

**Comment by brianjmurrell** [comment]
There is no network issue.  I have the network capture that shows that the two registrations go and two 401s come back and nothing else is done.

**Comment by brianjmurrell** [comment]
Do you need to see the network trace?

**Comment by Viish** [comment]
No, but attach the full log because there is no 401 in the one in your first post.

**Comment by brianjmurrell** [comment]
That is the full log and exactly the point.  The network capture shows the two REGISTERs followed by two 401s and the TCP stream is complete, with the phone ACKing the 401 packets in the stream, so they didn't "get lost".

You were not clear in your description of the problem.  Are you saying there was a push received **while** a registration was already in progress?  Is that why there are two REGISTERs so very close together?  If so, is there a bug in linphone with handling a push while in the process of doing a REGISTER?

**Comment by Viish** [comment]
Yes please attach your network capture.

>  Are you saying there was a push received while a registration was already in progress? Is that why there are two REGISTERs so very close together?

Yes.

>  If so, is there a bug in linphone with handling a push while in the process of doing a REGISTER?

This isn't a "bug", but a lack of optimization perhaps.

**Comment by brianjmurrell** [comment]
> This isn't a "bug", but a lack of optimization perhaps.

Does that mean you have been able to reproduce/confirm this behaviour?  If so, shouldn't this ticket be opened to track the _lack of optimization_?

**Comment by Viish** [comment]
We won't change this as the probability for it to happen in a real life scenario is close to zero, and even if it happens it's not problematic, you can have multiple REGISTERs sent at the same time.

**Comment by brianjmurrell** [comment]
I wouldn't care if at least one of them actually worked, but neither did and the phone missed the call.

**Comment by brianjmurrell** [comment]
Is it expected that both registrations when racing such as this will fail?

The tcpdump shows that the network delivered both REGISTERs to the SIP server and both 401s back to the the device.  Why didn't linphone-android show the 401s in the log and then send REGISTERs with the authentication response?

**Comment by Viish** [comment]
> The tcpdump shows that the network delivered both REGISTERs to the SIP server and both 401s back to the the device. Why didn't linphone-android show the 401s in the log and then send REGISTERs with the authentication response?

Still waiting for you to attach the file as I asked you...

Where did you made the capture? On the server or on the device?

**Comment by brianjmurrell** [comment]
On the server.  But the capture shows the device fully participating in the TCP stream (no network loss as you like to blame frequently), ACKing packets and handshaking the stream closed.

**Comment by brianjmurrell** [comment]
This has happened again.  When it happens it leaves the device completely unregistered and therefore unable to receive a push as there is no token to include in the push request.

Here's a [log](http://brian.interlinx.bc.ca/linphone-double-register.txt).

No network capture, but I do have logs from asterisk showing the registrations and the contacts being added and removed.
