### ISSUE TITLE
pn-provider=fcm instead of pn-type=firebase?

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1328]
Same build of linphone-android on two different phones are setting two different kind of Push parameters in their URI.

One is setting `transport=tcp;pn-type=firebase;app-id=...` and the other is setting `transport=tcp;pn-provider=fcm;pn-param=...`.

Any ideas why the difference?

**Comment by Viish** [comment]
> Any ideas why the difference?

Yes. 
`pn-type=firebase ...` was the contact uri parameters we used previously, and now there is a [push notification RFC](https://tools.ietf.org/html/rfc8599), we've updated our parameters to be compliant with it, hence the `pn-provider=fcm`.

By default our SDK will use the new format, however you can still stay on the previous one by setting the following in your config file:
```
[net]
use_legacy_push_notification_params=1
```

**Comment by brianjmurrell** [comment]
I'm fine with the new syntax.  I was just curious why it was different and if it was something I caused.

**Comment by chaoshwu** [comment]
hi,
i have a question, i try to replace the google-service.json to use my own pn-param, after rebuild the app, but it always use the old one as below? how to replace it?

pn-param=929724111839
