### ISSUE TITLE
SIP account settings not persisting

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1329]
Using up-to-date kotlin_rewrite branch, I am finding that setting changes I make in a SIP account are not persisting.

For example, I open the account, set the STUN / TURN server to a valid server, back out of the settings and then go back in and that setting is blank again.

I suspect the same thing is going on with the account password also, but since there is really no way to see it's setting, it's more difficult to be sure.

**Comment by Viish** [comment]
Yes, this is known. If you take a look at the code all the implementation of the account settings is filled with //TODO.
Settings have been implemented on another branch but before I can merge it we need to have the Linphone Account branch merged at SDK level, which isn't done yet.

**Comment by brianjmurrell** [comment]
Any ETA on this?

**Comment by Viish** [comment]
Already done in feature/kotlin_rewrite

**Comment by brianjmurrell** [comment]
So is this supposed to be fixed in master now?

**Comment by Viish** [comment]
Yes. But you should use release/4.5 branch which contains more fixes & improvements.

**Comment by Viish** [comment]
Then no. What makes the account settings stick is the switch from ProxyConfig to Account object, and that requires 5.0 SDK.

**Comment by brianjmurrell** [comment]
> But you should use release/4.5 branch which contains more fixes & improvements.

But that is using `org.linphone:linphone-sdk-android:5.0+` which is still alpha, right?

**Comment by brianjmurrell** [comment]
> Yes.

Which is still a bit unstable for daily use in my experience.  Which is fair enough.  It is still alpha after-all.

So is the `ha1` entry of section `auth_info_0` the password for the SIP account?  If so, what is the hash algorithm to get it's value?

**Comment by Viish** [comment]
> So is the ha1 entry of section auth_info_0 the password for the SIP account?

Yes.

>  If so, what is the hash algorithm to get it's value?

A simple hash (md5 or sha-256) of that: `username:realm:password`

Note that you can set you password in clear text form using the `passwd` property of auth_info_0 section, and upon the first registration it will be automatically migrated to the ha1 form.

**Comment by brianjmurrell** [comment]
Thanks.  And good to know about the clear-text option.

**Comment by brianjmurrell** [comment]
So what's the typical use-case for remote provisioning?  Does one typically protect the URL with authentication, or does one leave the account info out of the XML and expect the user to fill that in on the device once the XML file is fetched?  Or something different?

**Comment by Viish** [comment]
Depends on the use-case but yes, often provisioning is protected by digest auth using SIP account credentials.
For example: https://gitlab.linphone.org/BC/public/flexisip-account-manager/-/blob/master/src/xmlrpc/provisioning.php

**Comment by brianjmurrell** [comment]
Awesome.  Thanks for that reference.

> Note that you can set you password in clear text form using the passwd property of auth_info_0 section, and upon the first registration it will be automatically migrated to the ha1 form.

As in:
```
  <section name="auth_info_1" passwd="[redacted]">
```

or as an entry in the section such as:
```
  <section name="auth_info_1">
    <entry name="passwd" overwrite="true">[redacted]</entry>
…
```

Or something different as neither of the above seem to be working.

**Comment by Viish** [comment]
Like your second example:
```
<section name="auth_info_1">
    <entry name="passwd" overwrite="true">[redacted]</entry>
</section>
```
