### ISSUE TITLE
Enable Speaker

### ISSUE THREAD

**Issue by hammamziadeh12** [BelledonneCommunications/linphone-android#1330]
Hey,

I'm using Linphone and it seems to be working just fine, EXCEPT for one thing:

How do I enable my phone's speaker?

**Comment by Viish** [comment]
Hi,
Simply click on the speaker icon (next to mute microphone icon) while in call.
Cheers,

**Comment by hammamziadeh12** [comment]
I meant I'm using the SDK. How do I enable speaker programmatically?

**Comment by Viish** [comment]
> I meant I'm using the SDK. How do I enable speaker programmatically?

Then next time please open the ticket on linphone-sdk repository.

Anyway to enable the speaker before SDK 4.5.0 you have to use `https://developer.android.com/reference/android/media/AudioManager#setSpeakerphoneOn(boolean)`, and from 4.5.0 you need to get the audio device from the Core with Speaker type and set it as output audio device on the call,[ for example in our app](https://gitlab.linphone.org/BC/public/linphone-android/-/blob/feature/kotlin_rewrite/app/src/main/java/org/linphone/utils/AudioRouteUtils.kt#L46)
