### ISSUE TITLE
Speaker Auto Switched Off When Starting Conference.

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#1333]
Hi @Viish ,

The Speaker automatically switched off when starting Audio conference. One more scenario, if we forcefully switch on speaker in Audio conference it get Switched ON but then remain on, means no effect of Speaker Toggle.

Thanks in advance.

**Comment by Viish** [comment]
Hi,

On what version of Android app? 4.4.0 release will be published today (already available as a public beta) and shouldn't have this issue.

Cheers,

**Comment by amit1576** [comment]
Hi @Viish ,

I am using 4.4.0. Facing same issue with Speaker in Audio Conference.
Please find attached logs.

[AudioConference_Speaker_Issue.txt](https://github.com/BelledonneCommunications/linphone-android/files/6229859/AudioConference_Speaker_Issue.txt)

Thanks.

**Comment by Viish** [comment]
I don't see it in the logs. Speaker is turned off briefly at some points but that's all.
Also try on a real device, not the emulator.

**Comment by amit1576** [comment]
Hello @Viish ,

I have performed experiment on real device and same issue on real device also. There was a bug, where when user switch on the speaker in outgoing window will automatically switched off on call window, this issue and other speaker related issue has been solved in latest sdk & Android App 4.4.0, But Speaker switched off issue when I click on Add Conference button is still there. I have attached the logs for real device also.

Please suggest.

[1617168671d83599ad4204f4416cd142fa9aeca76b.txt](https://github.com/BelledonneCommunications/linphone-android/files/6234839/1617168671d83599ad4204f4416cd142fa9aeca76b.txt)

**Comment by amit1576** [comment]
Hello @Viish ,

Any comment on this.
