### ISSUE TITLE
Impossible add/change/reset password that was never set at account creation

### ISSUE THREAD

**Issue by leukimi** [BelledonneCommunications/linphone-android#1338]
It is perceived as **_very difficult_** to add/change/reset a `password` that was never set in the first place at account creation in software.

Website [https://www.linphone.org/freesip/**recover**](https://www.linphone.org/freesip/recover) is **not sending verification code** to recover/set/add/change password.

It is perceived as **_very difficult_** to add/change an `email` to a previously created `userid` in software.

It is **impossible to `delete` an account with a `userid`** in software/web site and be able to **reuse the same `userid`** with an `email` address instead.

Email address linked to `userid` is not permitted to be specified at account creation and not possible to add/change later. 

Different account creation systems on web site and in software with no possibility to change account settings.

There are [many similar stories like this one](https://lists.nongnu.org/archive/html/linphone-users/2020-06/msg00015.html) on internet about this strange behavior both in the software itself as well as the web site not permitting account management. Users are not being able to change password, add password, add email, change email using the "Account Assistant" which is supposed to handle it.

Users **wish to reuse and re-purpose `userid` previously created** in different contexts, but cannot do so without any logical explanation.

**Comment by Viish** [comment]
Your complaint has been noted.
However this isn't the place for it, so I'm gonna close the issue.
