### ISSUE TITLE
Earphones do not work with app

### ISSUE THREAD

**Issue by Marc05** [BelledonneCommunications/linphone-android#1339]
**Describe the bug**
I am not able to use my earphones (3.5mm to USB-C adapter) with the Linphone app. It used to work before, though I'm not sure which version I was on before I upgraded to 4.4.0. The earphones work with the regular phone app, as well as Discord.

**To Reproduce**
Make or receive a call. Audio/Mic will go through phone instead of being routed through the earphones.

**Expected behavior**
Audio/Mic should go through earphones.

**Please complete the following information**
 - Device: OnePlus 6t
 - OS: Android 10 / OxygenOS 10.3.9
 - Version of the App: 4.4.0

Log attached.
[log.zip](https://github.com/BelledonneCommunications/linphone-android/files/6246371/log.zip)

**Comment by Viish** [comment]
Please attach SDK logs showing the issue.

**Comment by Marc05** [comment]
I've attached the log file - name/ip has been redacted.

**Comment by Viish** [comment]
Thanks.

Looks like it's because of the AAudio soundcard. With OpenSLES the switch to the headset is made automatically, but that doesn't seem to be the same behavior for AAudio.
Either disable AAudio plugin when building the SDK or use the OutputAudioDevice API to set the earphones instead of the earpiece.

Cheers,

**Comment by Marc05** [comment]
Would you provide instructions on how to do this, or is there a mirror for older versions I can download 4.3.1 from? I'm not familiar with Android development.

**Comment by Viish** [comment]
Here's where you can download each one of our releases: http://linphone.org/releases/android/

**Comment by akjoshi009** [comment]
Guys did you solved this issue ?

**Comment by Viish** [comment]
For current Android release I disabled AAudio plugin, so yes.
Regarding the next version, I'll just have to add a new entry in the audio routes menu to choose the headset/earphones if there is one, at least when AAudio plugin is in use.

**Comment by akjoshi009** [comment]
I m using 5.0.0 version of libphone SDK

**Comment by Viish** [comment]
SDK is fine, issue was in application because there wasn't a way to ask for the headset audio route when using AAudio soundcard (Opensles works because it automatically switches earpiece to headset).
I made the fix for that in master branch yesterday, will be part of 4.5.0 release.
