### ISSUE TITLE
global reference table overflow (max=51200)

### ISSUE THREAD

**Issue by Rogueyang** [BelledonneCommunications/linphone-android#134]
09-20 09:36:23.628 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115] JNI ERROR (app bug): global reference table overflow (max=51200)
09-20 09:36:23.628 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115] global reference table dump:
09-20 09:36:23.628 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]   Last 10 entries (of 51200):
09-20 09:36:23.628 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]     51199: 0x145253e0 android.media.MediaFormat
09-20 09:36:23.628 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]     51198: 0x14525130 android.media.MediaFormat
09-20 09:36:23.628 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]     51197: 0x14523d10 android.media.MediaFormat
09-20 09:36:23.628 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]     51196: 0x14523a00 android.media.MediaFormat
09-20 09:36:23.628 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]     51195: 0x145236e0 android.media.MediaFormat
09-20 09:36:23.628 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]     51194: 0x14523380 android.media.MediaFormat
09-20 09:36:23.628 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]     51193: 0x14521fc0 android.media.MediaFormat
09-20 09:36:23.628 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]     51192: 0x14521930 android.media.MediaFormat
09-20 09:36:23.628 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]     51191: 0x14521560 android.media.MediaFormat
09-20 09:36:23.628 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]     51190: 0x14518f70 android.media.MediaFormat
09-20 09:36:23.628 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]   Summary:
09-20 09:36:23.628 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         2 of android.view.SurfaceView$MyWindow (2 unique instances)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         2 of org.linphone.LinphoneManager (1 unique instances)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         1 of org.linphone.LinphoneService$1
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         3 of android.view.ViewRootImplAO$WEx (3 unique instances)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         1 of android.view.SurfaceView
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         6 of org.linphone.core.LinphoneCoreImpl (1 unique instances)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         1 of org.linphone.core.PresenceActivityImpl
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         2 of org.linphone.core.PresenceModelImpl (2 unique instances)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         1 of org.linphone.core.LinphoneCallImpl
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]     50697 of android.media.MediaFormat (50697 unique instances)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         2 of org.linphone.mediastream.video.AndroidVideoWindowImpl (1 unique instances)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         1 of android.net.wifi.WifiManager$MulticastLock
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         1 of android.media.audiofx.AcousticEchoCanceler
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         2 of android.hardware.camera2.CameraManager$CameraManagerGlobal (1 unique instances)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         2 of org.linphone.AccountPreferencesFragment (2 unique instances)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         1 of org.linphone.assistant.AssistantActivity
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         1 of org.linphone.StatusFragment$1
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         1 of org.linphone.CallActivity$1
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]       301 of java.lang.Class (235 unique instances)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]        67 of java.lang.String (67 unique instances)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]        10 of dalvik.system.PathClassLoader (3 unique instances)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         1 of dalvik.system.VMRuntime
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         2 of java.lang.ThreadGroup (2 unique instances)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]        42 of java.lang.ref.WeakReference (42 unique instances)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         2 of java.nio.ByteOrder (1 unique instances)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         1 of byte[] (1280 elements)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         1 of byte[] (19600 elements)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         1 of byte[] (102400 elements)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         2 of byte[] (115200 elements) (2 unique instances)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         1 of byte[] (234256 elements)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         1 of byte[] (9024016 elements)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         1 of float[] (16 elements)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         2 of android.opengl.EGLDisplay (1 unique instances)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         1 of android.view.WindowManagerGlobal$1
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         1 of android.view.accessibility.AccessibilityManager$1
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         1 of android.view.inputmethod.InputMethodManager$1
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         4 of android.view.inputmethod.InputMethodManager$ControlledInputConnectionWrapper (4 unique instances)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         1 of android.app.ActivityThread$ApplicationThread
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         3 of android.app.LoadedApk$ReceiverDispatcher$InnerReceiver (3 unique instances)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         1 of android.bluetooth.BluetoothAdapter$1
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         2 of android.database.ContentObserver$Transport (2 unique instances)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         1 of android.hardware.Camera
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         1 of android.hardware.display.DisplayManagerGlobal$DisplayManagerCallback
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         1 of android.hardware.input.InputManager$InputDevicesChangedListener
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         1 of android.media.AudioManager$1
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         1 of android.media.AudioRecord
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         1 of android.net.wifi.WifiManager$WifiLock
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         2 of android.opengl.EGLContext (1 unique instances)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         2 of android.opengl.EGLSurface (1 unique instances)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         1 of android.os.PowerManager
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]        11 of android.os.Binder (11 unique instances)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115]         2 of android.media.MediaCodec (2 unique instances)
09-20 09:36:23.629 24747-445/org.linphone A/art: art/runtime/indirect_reference_table.cc:115] 
09-20 09:37:04.557 24747-24752/org.linphone E/art: Unexpected time out during dump checkpoint.
09-20 09:37:04.557 24747-24752/org.linphone A/art: art/runtime/barrier.cc:90] Check failed: count_ == 0 (count_=1, 0=0) Attempted to destroy barrier with non zero count

**Comment by Rogueyang** [comment]
after 40min calling with video,show these bug

**Comment by Rogueyang** [comment]
I checked every place where MediaFormat was created.all of that was deleted by method AMediaFormat_delete();I did not change the source code.Please give me some help.

**Comment by DatBewar** [comment]
Hello, do you have any log? I can't check just with stacktrace.

**Comment by Rogueyang** [comment]
@DatBewar Sorry,it crash on Jni,there is no more log.But I think these log is very clear to tell the reason.
"android.media.MediaFormat (50697 unique instances)" so so much MediaFormat instances in Jni did not delete

**Comment by kishanverma26** [comment]
facing this type of issue in recyclerview after 60 scrolles
