### ISSUE TITLE
log printing problem on android11

### ISSUE THREAD

**Issue by jayqean** [BelledonneCommunications/linphone-android#1340]
Hello @Viish 
After printing the linphone_core_log_collection_handler function in the linphone.c file, I found that the log output files of several modules are performed on the main thread. This will often cause ANR on android11. The crash is in the line of fflush. This problem occurs. 
Can log printing be added to the queue and another thread is opened for file output? Thank you

**Comment by Viish** [comment]
Please attach full SDK logs & symbolized stack trace.

**Comment by jayqean** [comment]
I don’t have permission to upload the log for security reasons.
very depressed.....

**Comment by Viish** [comment]
At least get the ANR tombstone from your device.
