### ISSUE TITLE
core.stop crash on Android11

### ISSUE THREAD

**Issue by jayqean** [BelledonneCommunications/linphone-android#1341]
Hello @Viish
When I close the program and open it again, core.stop occasionally crashes. 

After converting the stack information with ndk-stack, I found that the belle_sip_stream_listening_point_destroy_server_socket function of stream_listeningpoint.c, which calls belle_sip_close_socket, will cause a crash.

The sdk version is release4.5. What's a good solution to this problem? thks

**Comment by Viish** [comment]
Please attach full SDK logs & symbolized stack trace.

**Comment by jayqean** [comment]
Abort message: 'fdsan: attempted to close file descriptor 0, expected to be unowned, actually owned by unique_fd 0x7943d8e124'

**Comment by Viish** [comment]
Not what I asked for and not helpful.
