### ISSUE TITLE
fast_header_address parser error while starting audio conference

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#1342]
Hello @Viish ,

Hope you are doing well. I am facing **fast_header_address** parser error while starting conference. My assumption is that this issue is coming when push notification is on and firebase token id is the part of registration packet. When I stop or enabled/Disabled push notification everything working fine. One more thing to mention here that this issue start coming with latest SDK(5.0.0-alpha.3+2a41add).

[fast_header_address_error_conference.txt](https://github.com/BelledonneCommunications/linphone-android/files/6249450/fast_header_address_error_conference.txt)

**Comment by Viish** [comment]
Hi,

It has nothing to do with the push, simply you have a bad SIP address:
```
2021-04-02 14:34:20:069 [com.coraltele.coraluc.debug/belle-sip] ERROR fast_header_address parser error for [sip:[F[H@pbx.coraltele.com]
2021-04-02 14:34:20:069 [com.coraltele.coraluc.debug/liblinphone] WARNING Cannot create Address, bad uri [sip:[F[H@pbx.coraltele.com]
```
