### ISSUE TITLE
Native debugging

### ISSUE THREAD

**Issue by cnscns** [BelledonneCommunications/linphone-android#1343]
1.Install LLDB from SDK Tools in Android-studio.

2.In Android-studio go to Run->Edit Configurations->Debugger.

3.Select 'Dual' or 'Native' and add the path to linphone-sdk debug libraries (build/libs-debug/ for example).

4.Open native file and put your breakpoint on it.

How to include linphone-sdk source files into the linphone-android project and open native file in linphone-android project?
Is there any documents about native debug linphone-sdk in detail

**Comment by Viish** [comment]
Simply open the file like you would do for any file: File -> Open -> Choose your file.
You can also take a look at https://developer.android.com/studio/debug
