### ISSUE TITLE
DNS SRV Failover with Android App

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#1344]
Hi @Viish ,

I have tried DNS SRV Failover with linphone android app. Linphone acquire one host from SRV records and sends all registration request to that host only. When that SRV records un available linphone android is not sending registration to second SRV record.

Does linphone supports SRV DNS Failover ?

Log is also attached for the same.

[DNS_SRV_Failover_NotWorking.txt](https://github.com/BelledonneCommunications/linphone-android/files/6252454/DNS_SRV_Failover_NotWorking.txt)

Thanks in advance.

**Comment by Viish** [comment]
Hi,

> Does linphone supports SRV DNS Failover ?

Yes. I think your issue is because you are using UDP, the socket can't detect the host is unreachable and thus don't switch to the second server. Try with TCP or TLS.

**Comment by amit1576** [comment]
Hello @Viish ,

Thanks, Yes DNS Failover is working with TLS. 

But one concern is that the App check Connection only after **Expire** period. Means if I set Expire to 3600 then in this case of DNS SRV Failover, the app is only detecting after 3600 Seconds that my first IP is unreachable now.  How can I do it immediate in case of first IP failover.

Thanks.

**Comment by Viish** [comment]
> Does keepalive_period will help in this scenario.

Yes it will. Set it like this (you need both):
```
[sip]
keepalive_period=30000
tcp_tls_keepalive=30000
```
