### ISSUE TITLE
Speaker Misbehave in case of Audio Conference.

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#1346]
Hello @Viish ,

I have performed experiment on real device and same issue on real device also(As you suggested in #1333 ). There was a bug, where when user switch on the speaker in outgoing window will automatically switched off on call window, this issue and other speaker related issue has been solved in latest SDK & Android App 4.4.0.

a) Speaker auto switched off issue is still there when I click on Add Conference button.
b) One more case is that when I manually switch on the speaker in Audio Conference sound still comes from ear piece.

Please suggest.

Log is attached for the same.

1617168671d83599ad4204f4416cd142fa9aeca76b.txt

**Comment by amit1576** [comment]
Hello @Viish , 

Any comment here.

**Comment by Viish** [comment]
Not really. I'll check this for future release.

**Comment by Viish** [comment]
There is indeed an issue, we are working on it.

**Comment by Viish** [comment]
It should be working now with release/4.5 version and latest master SDK.

**Comment by amit1576** [comment]
Hi Sylvain,
Hope you are doing well.

Means, I need to take both SDK and latest release/4.5 ?
One more thing to confirm , have you discontinued the Linphone Android java
project ?

**Comment by Viish** [comment]
Yes, at least the 5.0-beta SDK, and if possible latest 5.0-beta app.
And yes, Java version will no longer be maintained.
