### ISSUE TITLE
Show dialer during a call even if linphone belives it is not answered also if linphone believes it is not answered

### ISSUE THREAD

**Issue by frankwalter1301** [BelledonneCommunications/linphone-android#1347]
It would be appropriate to show a dialer during a call to be able to emit DTMF tones for example during a call to an answering machine. It seems to me a necessary function. 

When I call an answering machine at the beginning the option to show a dialer does not appear (it is as if it remains ringing even if I hear the voice) and I am forced to do tricky things to emit DTMF tones. After I play the answering machine in this archaic way, linphone finally understands that someone has answered the call and also shows the other buttons, including the ability to show a dialer.

**Comment by Viish** [comment]
Hi,

This has been fixed in f`eature/kotlin_rewrite` branch that will soon becomes the new master.

Cheers,

**Comment by Viish** [comment]
FYI, it's because of your voicemail SIP client that keeps the call in early-media when there is no real motive for it...
