### ISSUE TITLE
isBluetoothHeadsetConnected Method not working properly

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#1351]
Hello @Viish ,

My finding is that the SDK Method "getAudioDevices()" is not giving accurate result. Issue is coming when I connected Bluetooth Headset, the SDK detects that Bluetooth device is connected and Audio started routing from Bluetooth device.  But when I disconnect  Bluetooth device the app still shows that Bluetooth device is connected and even for next subsequent calls the issue remains.

Please suggest.

Thanks,

**Comment by Viish** [comment]
Hi,
Please attach logs.
Thanks.

**Comment by amit1576** [comment]
Hello @Viish ,

Please find required logs. 

Experiment I have done : 

1) Answered a call, then take out my Bluetooth device. App automatically detect my Bluetooth device.[WORKING AS REQUIRED].
2) Shut down my Bluetooth, The App did not remove Bluetooth from device list.[ISSUE]
3) Now I disconnect the current call and start new call with my Bluetooth Device off App still showing Bluetooth Device.[ISSUE]

[Bluetooth_Device_Issue.txt](https://github.com/BelledonneCommunications/linphone-android/files/6284912/Bluetooth_Device_Issue.txt)

Thanks.

**Comment by Viish** [comment]
Please also attach logs from when the app is starting to the moment the call is received.

**Comment by amit1576** [comment]
Hello @Viish ,

Please find required logs.

_One interesting thing the above mentioned Point no 3. (Bluetooth App still visible in all next subsequent calls will remain until I cleared all app data) ._

[Bluetooth_Device_Issue.txt](https://github.com/BelledonneCommunications/linphone-android/files/6285139/Bluetooth_Device_Issue.txt)

**Comment by Viish** [comment]
Your new log file doesn't contains the logs from the core start.

> One interesting thing the above mentioned Point no 3. (Bluetooth App still visible in all next subsequent calls will remain until I cleared all app data) .

Not it's not actually. Problem is when the broadcast receiver is called when the bluetooth headset disconnects, Android's AudioManager.getDevices() API still returns the bluetooth device.

**Comment by amit1576** [comment]
Ok, I will send logs again.

**Comment by amit1576** [comment]
> Not it's not actually. Problem is when the broadcast receiver is called when the bluetooth headset disconnects, Android's AudioManager.getDevices() API still returns the bluetooth device.

Yes, this is the problem.

**Comment by Viish** [comment]
Closed until logs are provided
