### ISSUE TITLE
Unwanted connections and contacts leakage

### ISSUE THREAD

**Issue by vikilpet** [BelledonneCommunications/linphone-android#1354]
**Describe the bug**
Linphone-android makes connections to sip6.linphone.org with list of all my contacts.

**To Reproduce**
Just open the application.

**Expected behavior**
No connections except to my PBX.

**Please complete the following information**
 - Xiaomi Mi A2 Lite
 - OS: Android 10 (Android One)
 - Version of the App 4.3.1
 - Version of the SDK 4.4.2
 - From F-Droid

**Additional context**
I have never had an account on the linphone.org
Red color - phone numbers from my contact list.

![linphone_2021-04-10_16_54_35](https://user-images.githubusercontent.com/43970835/114270533-f16b4400-9a1d-11eb-9898-ab0276b058eb.png)

**Comment by Viish** [comment]
Hi,
Simply disable friendlist subscribe setting.
Cheers,
