### ISSUE TITLE
Reduce size of file when uploading while Chat. 

### ISSUE THREAD

**Issue by navin111** [BelledonneCommunications/linphone-android#1356]
Hello Team,

Is there any way to reduce the size of file before uploading it on Chat? 
We are receiving the below given message from server when uploading an image of size 5MB.

Received HTTP code response 400 for file transfer, probably meaning file is too large.

**Comment by Viish** [comment]
Hi,
No you have to do it yourself. Or increase the max file size allowed on your file transfer server.
Cheers,
