### ISSUE TITLE
ios to android call audio timeout

### ISSUE THREAD

**Issue by alqa-dash** [BelledonneCommunications/linphone-android#136]
Hello!

I'm not sure whether this was already discussed but I didn't found any corresponding topic to following situation: when a video call starts on ios and android client answered, android side can instantly hear sound from ios side but ios can hear sound from android only after several seconds. When answering part is ios as well - there is no pause in audio streams on both sides. In both cases speex 8000 has been used for audio and vp8 for video.

**Comment by DatBewar** [comment]
Hello,
I think you must ask this on the Linphone iOS repo.
https://github.com/BelledonneCommunications/linphone-iphone
