### ISSUE TITLE
After successfully configuring the SIP account, dial the phone, LinPhoneManager.getCore ().micEnabled() returns true, and the permissions are given

### ISSUE THREAD

**Issue by 15021585823** [BelledonneCommunications/linphone-android#1360]
With the latest version, after successfully configuring the SIP account, dial the phone, linPhoneManager.getCore ().micEnabled() returns true, and the permissions are given

![image](https://user-images.githubusercontent.com/15831485/114961472-a5942100-9e9b-11eb-9c11-30939fa08055.png)

![image](https://user-images.githubusercontent.com/15831485/114961049-db84d580-9e9a-11eb-819f-a456115a4e84.png)

**Comment by Viish** [comment]
And what's the issue with that?

**Comment by nealkai** [comment]
safety problem

**Comment by Viish** [comment]
I still don't understand what the issue is. Please be more explicit

**Comment by 15021585823** [comment]
> I still don't understand what the issue is. Please be more explicit

I made a call over SIP, and when the call was connected, I could hear the other person's voice, but they couldn't hear me

**Comment by Viish** [comment]
I don't see how this is a safety issue.
Also this could be caused by different problems, please attach logs.
