### ISSUE TITLE
Call State IDLE timeout

### ISSUE THREAD

**Issue by whitebeard786** [BelledonneCommunications/linphone-android#1362]
hi @Viish ,
I have a use case in my app where the connected call state should remain IDLE for more than 30 secs, but it also seems that if there is no audio transmission between 2 legs of connected call,a Sip BYE goes out from linphone thus disconnecting the connected call state.I have changed the value in linphonerc_factory file for inc_timeout value but it is not working.
So @Viish  is there a way through which I can increase the IDLE state timeout for more than 30 secs and If yes can you help me where it should be done.
Danke!

**Comment by Viish** [comment]
Hi,
`inc_timeout` is the incoming call timeout. The one you seek is `nortp_timeout` (default 30 seconds).
Cheers,
