### ISSUE TITLE
How to avoid playing tone when call terminated.

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#1363]
Hello @Viish ,

With new SDK I guess a feature introduced that whenever call get terminated by app 3 DTMF tone get played. This is helpful in many scenario, but I need to avoid it in certain scenario. 

Can you guide how can I avoid playing these 3 DTMF tone. Means is there any setting, by which this can be achieved or it will be a SDK change only.

Thanks,

**Comment by Viish** [comment]
Hi,
Simply disable tones in your factory config file:
```
[sound]
tone_indications=0
```

**Comment by amit1576** [comment]
Hello @Viish ,

Is there anyway to disable it at run time for some calls, the setting in factory will disable it for all calls.

**Comment by Viish** [comment]
No, not at the time.
