### ISSUE TITLE
Auto-answer in linphone

### ISSUE THREAD

**Issue by whitebeard786** [BelledonneCommunications/linphone-android#1365]
The incoming call with **"Answer Mode:Auto"** gets a ringer before accepting , so is the Auto Answer in Linphone App  is working or do we have implement it using the liblinphone library.

**Comment by Viish** [comment]
Hi,
If you set a delay before accepting the call then it's expected it will ring until this delay has elapsed.
If you set the app to auto answer incoming call immediately (delay = 0), then you won't hear the ringtone.
Cheers,
