### ISSUE TITLE
ERROR header_contact parser error for [Contact:

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#1366]
Hello @Viish ,

I am facing **ERROR header_contact parser error for [Contact:** in 2 device only. Unable to understand Why this message is coming. With same device **ERROR Could not parse [INVITE**. I guess reason is same for both.

Logs.

[Contact_Parser_Error.txt](https://github.com/BelledonneCommunications/linphone-android/files/6342153/Contact_Parser_Error.txt)

**Comment by Viish** [comment]
Hi,

Yes it's normal the Contact header is wrong (the value it contains doesn't follow ABNF grammar):
```
2021-04-20 13:19:43:881 [com.coraltele.coraluc.debug/belle-sip] MESSAGE channel [0x7c809f0b00]: received [1178] new bytes from [TLS://voip.coraltele.com:5090]:
SIP/2.0 200 OK
Via: SIP/2.0/TLS 26.139.141.56:60526;alias;branch=z9hG4bK.mwGGxHa1t;rport=60526;received=157.51.33.4
From: "Ananth cbe branch" <sip:1826@voip.coraltele.com>;tag=EDULmU2Pl
To: "Ananth cbe branch" <sip:1826@voip.coraltele.com>;tag=cf245f815278ca99446bdf3b5f9d966f.4b7de77d
CSeq: 21 REGISTER
Call-ID: 39-Fh1nXZH
Contact: <sip:1826@157.51.33.4:60414;app-id=108861424352;pn-type=firebase;pn-timeout=0;pn-tok=fmoXYpDb4ho:APA91bHy9idYxJY11oMROWoMdGaaFDV5p-GeRqrsj94HOKrkUlUbWo-RG2bR9DlVNdBdk7h3ts-zSS-WGUb11Zi4JhXbiDG-jhkfLSiwQInXjP5wzfljaUnQ-dvbfFFVyBRs-D60ECUg;pn-silent=1;app-imei=;transport=tls>;expires=3396;received="sip:157.51.33.4:60414;transport=tls";+sip.instance="<urn:uuid:5d5a5908-56c3-00e7-8326-a5d1ee6c8eb0>", <sip:1826@157.51.33.4:60526;app-id=108861424352;pn-type=firebase;pn-timeout=0;pn-tok=cyn-7gQlg9Y:APA91bErqzLEIFwhM4JJsJs0Xepd2k9QZ1cO5eES_bSN3n21JsD-4of7JPHd7QHLmOJMBdxNUJymER4tOSnfCEl3kQPOG3MEI5r14wbMkfIzQLU2Qzy4RFvXWmovMODkcnOkJFLsvAem;pn-silent=1;app-imei=;transport=tls>;expires=3600;received="sip:157.51.33.4:60526;transport=tls";+sip.instance="<urn:uuid:115e2d1c-c840-00d1-b6d2-182bef5e28db>"
Server:iriscloud
Content-Length: 0
```

Check either your server or the device that registered with this Contact header to see why this header is badly formatted.

Cheers,

**Comment by amit1576** [comment]
Hello @Viish,

Is this below error is also coming just because of it. 

2021-04-20 13:39:37:519 [com.coraltele.coraluc.debug/belle-sip] ERROR Could not parse [INVITE sip. In same log file I had attached in last comment.

**Comment by Viish** [comment]
Yes, except this time it's not the Contact header but the INVITE line itself which is wrong, but very likely for the same reason.
