### ISSUE TITLE
Using stale mobile network DNS on wifi

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1367]
Using 21a00a562 with 4.5.0-beta.50+c67027b SDK, I am seeing "extra" DNS servers being listed as being used in the log:

```
2021-04-20 16:14:10:586 [org.linphone.debug/belle-sip] MESSAGE Resolver is using DNS server(s):
2021-04-20 16:14:10:586 [org.linphone.debug/belle-sip] MESSAGE 	10.75.22.247
2021-04-20 16:14:10:586 [org.linphone.debug/belle-sip] MESSAGE 	2607:abcd:12:99:0:640:7125:5253
2021-04-20 16:14:10:586 [org.linphone.debug/belle-sip] MESSAGE 	2607:abcd:12:99:0:640:7125:5254
```

The latter two to be clear.  Those would be my *mobile* operator's DNS, but at the above time, I am not using mobile data but rather using wifi.  Only the first address should be in the list being used.

Using [Ping & Net](https://play.google.com/store/apps/details?id=com.ulfdittmer.android.ping) I only see the first, my wifi DNS listed as the DNS servers that are being used.  Maybe that application isn't telling the whole story?  Do you have a better app/method for examining the data that linphone-android is getting the list of DNS server to use so that I can verify and report this upstream if it really is ROM issue?

**Comment by Viish** [comment]
Yes it a choice we made to use all DNS servers from all available networks. 
But the list is ordered by active network so it shouldn't be an issue.
