### ISSUE TITLE
Cannot start a video call via Asterisk

### ISSUE THREAD

**Issue by gzozulin** [BelledonneCommunications/linphone-android#1368]
Hello Everyone,
I cannot start a video call via the Linphone app. I can make video calls via desk phones (Yealink, Grandstream) with the same server and setup. The audio call works perfectly. I traced the call in the source code with the debugger, it updates the call and reinvites (`CallManager::reinviteWithVideo`), but nothing happens.

**Logcat output** is available [here](https://github.com/BelledonneCommunications/linphone-android/files/6347070/linphone_logcat.txt)

Version: current master.
One device: Pixel 3XL (non-rooted)
Another: just Pixel (rooted)

**My Asterisk setup:**

sip.conf:
```
allow=h263p
allow=h264
allow=vp8
videosupport=yes
```
users.conf:
```
[9001]
type=friend
host=dynamic
secret=passw
allow=h263p
allow=h264
allow=h265
allow=vp8
videosupport=yes

[9002]
type=friend
host=dynamic
secret=passw
allow=h263p
allow=h264
allow=h265
allow=vp8
videosupport=yes

[9003]
type=friend
host=dynamic
secret=passw
allow=h263p
allow=h264
allow=h265
allow=vp8
videosupport=yes
```

If any additional information is needed, please ping me. Thanks!

**Comment by Viish** [comment]
Hi,

The issue seems to be caused either by the remote party.
The reinvite with video is correctly sent but the 200 OK for that invite contains a disabled video line (port set to 0), which means the other party refused it for some reason.
Check it's logs.

Cheers,

**Comment by gzozulin** [comment]
@Viish the remote party is also a Linphone app (this one is just taken from Play Store). Are you saying that the app is rejecting video or is that a result of a server setup? Maybe I am missing something in the setup of the app (Settings > Video/Advanced)?
Sorry for the misunderstanding: I am new to SIP and video conferencing...

**Comment by Viish** [comment]
Can you attach logs from both devices for the same call with this issue? This way I can tell you if the server is at fault here or not.
