### ISSUE TITLE
Adding custom header 

### ISSUE THREAD

**Issue by rexxar786** [BelledonneCommunications/linphone-android#1369]
Hi @Viish ,
Is it possible to add a custom header in the  200 OK response packet  for an  incoming Sip Invite from Linphone..
Danke sehr!

**Comment by Viish** [comment]
Hi,
Yes if you set it in the [CallParams](http://linphone.org/snapshots/docs/liblinphone/5.0/java/org/linphone/core/CallParams.html#addCustomHeader-java.lang.String-java.lang.String-) you use to accept the call.
Cheers,
