### ISSUE TITLE
Linphone don't process cancel when CANCEL and 200 OK DO "cross each other on the wire"

### ISSUE THREAD

**Issue by Thucnv** [BelledonneCommunications/linphone-android#137]
Hi, I have an issue:
When calling multiple endpoints at the same time, if one endpoint (ex: endpoint A) answers the call, a typical PBX sends a CANCEL to the other endpoints (ex:  endpoint B) that were ringing with a cause "Call completed elsewhere", at the same time endpoint B answers and send 200 OK. I see linphone don't process CANCEL and keep sending 200 Ok to server

INVITE-------> endpoint B
<----------- 100 Trying
<----------- 180 Ringing
CANCEL-----> <------ 200 OK (CSeq: xxx INVITE)
<------ 200 OK (CSeq: xxx INVITE)
....
<------ 200 OK (CSeq: xxx INVITE)
<------ timeout

How can solve it?
Thanks.

**Comment by Viish** [comment]
SDK issue, not Android
