### ISSUE TITLE
I am trying to use sample but its showing null pointer exception

### ISSUE THREAD

**Issue by akjoshi009** [BelledonneCommunications/linphone-android#1371]
Caused by: java.lang.NullPointerException: Attempt to read from field 'org.linphone.core.Core detvremote.com.linephonesimple2.LinphoneService.mCore' on a null object reference

**Comment by Viish** [comment]
Sample is no longer part of linphone-android project. 
However you can check our tutorials : https://gitlab.linphone.org/BC/public/tutorials

**Comment by akjoshi009** [comment]
hi bro can you guys have android tutorial in java ?

**Comment by Viish** [comment]
No, as the Java is slowly being replaced by Kotlin we won't take time to duplicate Kotlin tutorials in Java, but it is quite similar so you shouldn't have much troubles translating it in Java.
