### ISSUE TITLE
Delayed FCM Push delivery due to non-interaction with app?

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1372]
I'm experiencing push notification delays on an Android 11 device.  [Reading](https://firebase.google.com/docs/cloud-messaging/concept-options#setting-the-priority-of-a-message) I see:

> High priority messages generally should result in user interaction with your app or its notifications. If FCM detects a pattern in which they don't, your messages may be de-prioritized. Android P introduced app standby buckets which limit the number of FCM high priority messages you can send to your app that don't result in the user using your app or viewing a notification.

Any idea what what _user interaction_ here means in the context of linphone-android?  If I get a bunch of _SIP SIMPLE_ `MESSAGE`s, each resulting in a push, and I don't view them right away does that count as lack of _user interaction_ which may de-prioritize future **high priority** messages?

How is FCM determining if a user is interacting with notifications in any case?  Are apps supposed to phone back to the FCM service when a user interacts with a notification?

**Comment by Viish** [comment]
You can check which bucket your app is in in the logs.
Regarding interaction with notifications, there is no API for that so it's Android that does it. Most probably it means either clicking on the notification or using one of it's action.

**Comment by brianjmurrell** [comment]
> there is no API for that so it's Android that does it. Most probably it means either clicking on the notification or using one of it's action.

Indeed.  Given that push notifications to linphone-android don't actually produce notification dialogs for the user to interact with, do you have any thoughts on how that might be negatively impacting delivery given the quoted text above about notifications being de-prioritised (which I am reading to mean possibly delayed in sending from the FCM servers once they receive the push from the app server (SIP server in our case) if users don't interact with them?

**Comment by Viish** [comment]
> Given that push notifications to linphone-android don't actually produce notification dialogs for the user to interact with

That's not true. If a push is received, it means either a call or a message is received when the Core stars, and that will trigger a notification.

**Comment by brianjmurrell** [comment]
Yes, that is true.  But as I said before, if I receive a bunch of messages that I might not be able to read right away, that might start to de-prioritize the push delivery.  For a typical messaging app, this is not a problem because timely delivery is not required to be able to get the message, it comes as data with the push whenever the push does finally get sent.  At least I suspect that is the case most of the time.  I doubt most messaging apps work the way linphone does and just uses the push to wake the app up to start a fetch of a message.

But in the case of SIP SIMPLE, the SIP server is sitting there, blocking, waiting for the SIP client to come REGISTER so that it can send the message.

But this gets even worse for the incoming call situation.  The inability to respond to each incoming message in a timely manner can lead to the push for a call, which needs to be immediately delivered (obviously), from being de-prioritized and not come in as timely as is necessary to pick up a call before a caller gives up waiting.  Don't you think?

**Comment by Viish** [comment]
In the same page and same paragraph as the one you posted in your first message, you can read the following:
```
If, in response to a high priority message, a notification is displayed in a way that is visible to the user, then your app standby bucket quota will not be consumed by that message.
```
Which means it doesn't matter if the user interacts with the notification or not, right away or later, as long as it's displayed it's fine.
The only risk is for bad networks that wouldn't be able to fetch the message or call information during the 20 seconds the app is allowed to access the network when it receives a push.

**Comment by brianjmurrell** [comment]
> You can check which bucket your app is in in the logs.

What am I looking for?  In the linphone debug logs or logcat?  Or something else?

**Comment by brianjmurrell** [comment]
Ahhh.  Think I found it:

```
Device is in bucket STANDBY_BUCKET_WORKING_SET
```

But I have not seen it since 2021-04-27 10:04:38 which is about 28h ago.  How often is it put into the log?

**Comment by Viish** [comment]
> How often is it put into the log?

When the Core starts.

**Comment by brianjmurrell** [comment]
Any advise on how to diagnose/prove on-device FCM message delivery?  I.e. delays between the time the device gets the push from the FCM servers to the time that linphone-android gets the push message?
