### ISSUE TITLE
please allow (ADB) backup in AndroidManifest.xml

### ISSUE THREAD

**Issue by starbrights** [BelledonneCommunications/linphone-android#1373]
For users without root adb backup/restore is the only way to backup app+data.
Would you please be so kind to allow that in manifest? Maybe you just not aware of it.
If not - is there any special reason not to do so?
Thank you.

**Comment by Viish** [comment]
Hi,
We removed the allowBackup flag for security reasons as the data dir contains your SIP accounts, calls/chat history, etc... and that data is sensitive.
Cheers,

**Comment by starbrights** [comment]
Sure - but for this backup you 
* need physical access to device
* and it must unlocked
* you have to enable developer setting
* you have to set adb enabled in developer setting
 
 - so this is not a drive by hack. Only people who know what they do have this.
I think this could be enabled. Wouldn't you think about that again?

BTW if you request support data all that it in clear text on some FTP server. ;)

**Comment by Viish** [comment]
Actually no, a malicious app installed on your device might access the app's data.
You'll find many articles online explaining why when credentials are stored you shouldn't allow backup.
Also please note that the [doc](https://developer.android.com/guide/topics/manifest/application-element#allowbackup) says the following: 
```
Note: If your app targets Android 11 (API level 30) or higher, you cannot disable device-to-device migration of your app's files. The system automatically allows this functionality.
```

If you really want that (and as it seems you have the technical capacities) you can fork the app, make the change in the Manifest, build it and install it on your device.

**Comment by arichiardi** [comment]
Hi all, stumbled into this (sorry of closed) and wondering if there is a way to backup the app currently (wothout being root). I must be blind but cannot find it.
