### ISSUE TITLE
Speaker On By default on Every Incoming Call

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#1374]
Hello @Viish ,

Speaker is getting ON by default on every new incoming call. Even I had tried to route audio through earphone while incoming call received, but still speaker once off the on again(as per logs).

Please find attached logs.

[SpeakerByDefaultOnIncomingCall.txt](https://github.com/BelledonneCommunications/linphone-android/files/6372998/SpeakerByDefaultOnIncomingCall.txt)

**Comment by Viish** [comment]
Hi,

Check you haven't set it as default output soundcard in the settings...

**Comment by amit1576** [comment]
> Hi,
> 
> Check you haven't set it as default output soundcard in the settings...

How to set it in settings. Please tell.

**Comment by Viish** [comment]
If you don't have a setting for that, simply check the AudioDevice returned by `core.getDefaultOutputAudioDevice()`

**Comment by amit1576** [comment]
Sure.

I will check and let you know.

**Comment by amit1576** [comment]
Hi @Viish ,

Every time **core.getDefaultOutputAudioDevice()** gives : 

Device Name : AOSP on IA Emulator, Device Type : Speaker, Driver Name : openSLES.

Please suggest.

**Comment by Viish** [comment]
Then it's expected every call will start on the Speaker since you have configured it as such.
Simply call `core.setDefaultOutputAudioDevice(audioDevice)` with the audioDevice object that represents the earpiece or something else.

**Comment by amit1576** [comment]
Actually I have not configure speaker as default output. Can you please suggest how can I check default Output Device.

> Simply call `core.setDefaultOutputAudioDevice(audioDevice)` with the audioDevice object that represents the earpiece or something else.

I will try this.

**Comment by Viish** [comment]
> Can you please suggest how can I check default Output Device.

By using `core.getDefaultOutputAudioDevice()` ...

**Comment by amit1576** [comment]
> Then it's expected every call will start on the Speaker since you have configured it as such.

Actually I asked how can I found the device I have configured. Because I have not done ay such configuration.

**Comment by Viish** [comment]
Either you called `core.setDefaultOutputAudioDevice(audioDevice)` instead of `core.setOutputAudioDevice(audioDevice)` or `call.setOutputAudioDevice(audioDevice)`to change audio device during a call, or you set in your config file:
```
[sound]
playback_dev=openSLES Speaker: AOSP on IA Emulator
```
Or the speaker is simply the first device returned by Android's https://developer.android.com/reference/android/media/AudioManager#getDevices(int) API for the emulator.

**Comment by sudoGenie** [comment]
I too have this same issue but (my device defaults to Earpiece ) even though my device doesnt even have an earpiece.
how do we know which one sets up as default or to program it to reflect the currrent default. 

so if i have Bluetooth on it should go there
