### ISSUE TITLE
Direct peer to peer sip call without Registeration.

### ISSUE THREAD

**Issue by Adnan-addi** [BelledonneCommunications/linphone-android#1375]
Hi @Viish 
I come up with a task in linphone android app with making peer to peer direct call with static ip addresses of the divice and wifi mac address . 

I am unable to figure out how i can achieve this in linphone without registering to any server and just initiating direct sip call to other sip peer by bypassing registration .

Please help in this scenario how can i achieve this.

Thank you.

**Comment by Viish** [comment]
Hi,

I don't think it will work for MAC addresses, but you can call an IP directly.
Simply dial `sip:whatever@your-ip`

Cheers,

**Comment by Adnan-addi** [comment]
Hi , Appreciate your response , 
i want know is registration necessary for making peer to peer sip call , or can i bypass registration for making making peer to peer call 

how would i then set my account from calling ???
i have an task to make direct peer to peer call ? Please check the attached image for the scenario i want to achieve , 
<img width="941" alt="Screenshot 2021-04-29 at 2 39 34 AM" src="https://user-images.githubusercontent.com/25033749/116476343-88485500-a894-11eb-8690-26c37303cd6f.png">
