### ISSUE TITLE
Replace default username 'linphone.android' in linphonerc_default dynamically

### ISSUE THREAD

**Issue by Adnan-addi** [BelledonneCommunications/linphone-android#1377]
@Viish  Hi,
I am trying to direct peer to peer call 
But my username is set linphone.android@sipserip

I want to replace linphone.android with my custom username for default. i checked it is coming from linphonerc_default file i need to replace this default with my custom username dynamically at runtime at launch time. how to achieve this

**Comment by Viish** [comment]
Hi,
Use the following method: http://linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Core.html#setPrimaryContact-java.lang.String-
Note that username doesn't matter when doing peer to peer call, except for displayed name & caller address.
Cheers,
