### ISSUE TITLE
core.stop Cause a crash

### ISSUE THREAD

**Issue by joxhome-lyh** [BelledonneCommunications/linphone-android#1379]
backtrace:
 Build fingerprint: 'HUAWEI/HMA-L29/HWHMA:10/HUAWEIHMA-L29/10.1.0.298AUSC636:user/release-keys'
 Revision: '0'
 ABI: 'arm'
 Timestamp: 2021-04-29 16:50:02+0800
 pid: 30263, tid: 30317, name: FinalizerDaemon  >>> com.saetdk.uc <<<
 uid: 10535
 signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
 Abort message: 'Aborting'
     r0  00000000  r1  0000766d  r2  00000006  r3  c1bf6080
     r4  c1bf6094  r5  c1bf6078  r6  00007637  r7  0000016b
     r8  c1bf6090  r9  c1bf6080  r10 c1bf60b0  r11 c1bf60a0
     ip  0000766d  sp  c1bf6050  lr  eff61143  pc  eff61156
 backtrace:
       #00 pc 00054156  /apex/com.android.runtime/lib/bionic/libc.so (abort+166) (BuildId: 2ae2ed355dc68e7fe1e09d70518111d1)
       #01 pc 00006b2f  /system/lib/liblog.so (__android_log_assert+174) (BuildId: 89387f182c0b968d6748d9178bca77bd)
       #02 pc 00025093  /data/app/com.saetdk.uc-4zMu1V_e9qt5cr-2egEn1Q==/lib/arm/libbctoolbox.so (bctbx_logv+314) (BuildId: dd685a1844529b59143e0cac09e4a9cc7675f461)
       #03 pc 00674f2d  /data/app/com.saetdk.uc-4zMu1V_e9qt5cr-2egEn1Q==/lib/arm/liblinphone.so (BuildId: f881d2db7f8efd28955f6cac18fd773222a6aadc)
       #04 pc 00674e67  /data/app/com.saetdk.uc-4zMu1V_e9qt5cr-2egEn1Q==/lib/arm/liblinphone.so (belle_sip_object_unref_2+98) (BuildId: f881d2db7f8efd28955f6cac18fd773222a6aadc)
       #05 pc 0063c4c1  /data/app/com.saetdk.uc-4zMu1V_e9qt5cr-2egEn1Q==/lib/arm/liblinphone.so (Java_org_linphone_core_CoreImpl_unref+76) (BuildId: f881d2db7f8efd28955f6cac18fd773222a6aadc)
       #06 pc 000e5519  /apex/com.android.runtime/lib/libart.so (art_quick_generic_jni_trampoline+40) (BuildId: 2e55b99bfc5b904dcb28f4ff4b636f3a)
       #07 pc 000e0bc5  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: 2e55b99bfc5b904dcb28f4ff4b636f3a)
       #08 pc 004494fb  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub+250) (BuildId: 2e55b99bfc5b904dcb28f4ff4b636f3a)
       #09 pc 000e8ff5  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+160) (BuildId: 2e55b99bfc5b904dcb28f4ff4b636f3a)
       #10 pc 0021a63f  /apex/com.android.runtime/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+274) (BuildId: 2e55b99bfc5b904dcb28f4ff4b636f3a)
       #11 pc 002167a7  /apex/com.android.runtime/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+802) (BuildId: 2e55b99bfc5b904dcb28f4ff4b636f3a)
       #12 pc 004405af  /apex/com.android.runtime/lib/libart.so (MterpInvokeDirect+358) (BuildId: 2e55b99bfc5b904dcb28f4ff4b636f3a)
       #13 pc 000db914  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_direct+20) (BuildId: 2e55b99bfc5b904dcb28f4ff4b636f3a)
       #14 pc 0026bf70  [anon:dalvik-classes5.dex extracted in memory from /data/app/com.saetdk.uc-4zMu1V_e9qt5cr-2egEn1Q==/base.apk!classes5.dex] (org.linphone.core.CoreImpl.finalize+20)
       #15 pc 0043e909  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtual+1184) (BuildId: 2e55b99bfc5b904dcb28f4ff4b636f3a)
       #16 pc 000db814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: 2e55b99bfc5b904dcb28f4ff4b636f3a)
       #17 pc 001b8b02  /apex/com.android.runtime/javalib/core-libart.jar (java.lang.Daemons$FinalizerDaemon.doFinalize+22)
       #18 pc 0044082b  /apex/com.android.runtime/lib/libart.so (MterpInvokeDirect+994) (BuildId: 2e55b99bfc5b904dcb28f4ff4b636f3a)
       #19 pc 000db914  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_direct+20) (BuildId: 2e55b99bfc5b904dcb28f4ff4b636f3a)
       #20 pc 001b8bf4  /apex/com.android.runtime/javalib/core-libart.jar (java.lang.Daemons$FinalizerDaemon.runInternal+164)
       #21 pc 0043e909  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtual+1184) (BuildId: 2e55b99bfc5b904dcb28f4ff4b636f3a)
       #22 pc 000db814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: 2e55b99bfc5b904dcb28f4ff4b636f3a)
       #23 pc 001b88f6  /apex/com.android.runtime/javalib/core-libart.jar (java.lang.Daemons$Daemon.run+50)
       #24 pc 0043fe25  /apex/com.android.runtime/lib/libart.so (MterpInvokeInterface+1468) (BuildId: 2e55b99bfc5b904dcb28f4ff4b636f3a)
       #25 pc 000dba14  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_interface+20) (BuildId: 2e55b99bfc5b904dcb28f4ff4b636f3a)
       #26 pc 000eabdc  /apex/com.android.runtime/javalib/core-oj.jar (java.lang.Thread.run+8)
       #27 pc 001f6a93  /apex/com.android.runtime/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.16045327618246135572+194) (BuildId: 2e55b99bfc5b904dcb28f4ff4b636f3a)
       #28 pc 001fb105  /apex/com.android.runtime/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+120) (BuildId: 2e55b99bfc5b904dcb28f4ff4b636f3a)
       #29 pc 004329ed  /apex/com.android.runtime/lib/libart.so (artQuickToInterpreterBridge+832) (BuildId: 2e55b99bfc5b904dcb28f4ff4b636f3a)
       #30 pc 000e55a1  /apex/com.android.runtime/lib/libart.so (art_quick_to_interpreter_bridge+32) (BuildId: 2e55b99bfc5b904dcb28f4ff4b636f3a)
       #31 pc 000e0bc5  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: 2e55b99bfc5b904dcb28f4ff4b636f3a)
       #32 pc 004494fb  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub+250) (BuildId: 2e55b99bfc5b904dcb28f4ff4b636f3a)
       #33 pc 000e8ff5  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+160) (BuildId: 2e55b99bfc5b904dcb28f4ff4b636f3a)
       #34 pc 00389ff3  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+54) (BuildId: 2e55b99bfc5b904dcb28f4ff4b636f3a)
       #35 pc 0038acfd  /apex/com.android.runtime/lib/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+300) (BuildId: 2e55b99bfc5b904dcb28f4ff4b636f3a)
       #36 pc 003bc32b  /apex/com.android.runtime/lib/libart.so (art::Thread::CreateCallback(void*)+966) (BuildId: 2e55b99bfc5b904dcb28f4ff4b636f3a)
       #37 pc 0009c1b7  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+20) (BuildId: 2ae2ed355dc68e7fe1e09d70518111d1)
       #38 pc 00055657  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30) (BuildId: 2ae2ed355dc68e7fe1e09d70518111d1)

**Comment by joxhome-lyh** [comment]
Hello @Viish 
version is org.linphone:linphone-sdk-android:5.0+
when the app quit,core.stop cause a crash.

**Comment by Viish** [comment]
Hi,
Please attach logs from SDK from before the app stops to the moment of the crash.
Cheers,

**Comment by Viish** [comment]
Closed until logs are provided
