### ISSUE TITLE
How to set max size for logs collection.

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#1380]
Hello @Viish,

How can I fix the rollover size of Log file. I want it to be fix at max 10MB.

Please suggest.

**Comment by Viish** [comment]
http://linphone.org/snapshots/docs/liblinphone/5.0/java/org/linphone/core/Core.html#setLogCollectionMaxFileSize-int-

Please check doc by yourself before asking questions...

**Comment by amit1576** [comment]
Hello @Viish ,

I had gone through this document but not able to use **Factory.instance().setLogCollectionMaxFileSize(100);**

I only found below method . 

Factory.instance().setLogCollectionPath(basePath);
Factory.instance().enableLogCollection(LogCollectionState.Enabled);
Factory.instance().setDebugMode(true,"asd");

But I am unable to use below method as mentioned in code in my Android code.

Factory.instance().**setLogCollectionMaxFileSize**(100);

Rather I found **LinphoneManager.getCore().setLogCollectionMaxFileSize(1048576)**, Should I use it for setting Max File Size or not ?

**Comment by Viish** [comment]
Check again the link I sent you above, it is on the Core and not on the Factory...

**Comment by amit1576** [comment]
Thanks,

It worked..
