### ISSUE TITLE
4.5.0-Beta

### ISSUE THREAD

**Issue by stef204** [BelledonneCommunications/linphone-android#1384]
I am currently building release 4.4.
I see a branch `release/4.5` which is currently ahead of master by 1 commit.
There is also tag `4.5.0-beta stable`. Is it enough to try in a "quasi-production" setting?
 Which branch or tag should I use to be stay current?

**Comment by Viish** [comment]
Hi,

Yes the 4.5.0-beta version is a release candidate, so you can use it. If you encounter an issue, please report it.
4.5.x version is a complete rewrite from 4.4.x version, and from now the only version we will support.

Cheers,

**Comment by stef204** [comment]
@Viish 
Thanks.  Let me make sure I do the right thing: I actually clone from gitlab not github.
Which should I use on gitlab?
`release/4.5` or `tag 4.5.0-beta`?

**Comment by Viish** [comment]
Currently it's the same thing. Release/4.5 branch will have more commits until the 4.5.0 tag that will mark the official release. So until release is tagged, you should use the latest version in release/4.5 branch instead of the beta tag.

**Comment by stef204** [comment]
Great, thank you.

**Comment by stef204** [comment]
@Viish 
I see you've tagged 4.5.1 now.  Should I switch to that tag now?  Or am I still OK pulling from branch release/4.5?

**Comment by Viish** [comment]
4.5.1 is the latest version on release/4.5 branch, and as such it contains fixes for issues found in 4.5.0, so yes if you can update you should.

**Comment by stef204** [comment]
I can but my specific question is: 

1. do I switch to tag `4.5.1` and compile that or do I still pull `release/4.5` ?
2. then which branch do I follow to update and pull from? Go back to `master`?

**Comment by Viish** [comment]
> After upgrading as in 1. above, which branch do I follow to update and pull from? Go back to master? Or you'll open a release/4.6 for example, etc.? In other words, what's the best way to track development (but not in unstable version, beta at minimum)?

Beta versions will always be on release/X.Y branches, as well as releases. When 4.6 release time will approach, we will create a release/4.6 branch with 4.6.0-beta tag, and the day of the public release tag 4.6.0.
On master branch you will always have alpha versions.

**Comment by stef204** [comment]
Thanks for the clarification.
