### ISSUE TITLE
Latest Linphone (Kotlin) how to set default username ?

### ISSUE THREAD

**Issue by Adnan-addi** [BelledonneCommunications/linphone-android#1385]
Hi @Viish 
few days back i solved my problem of default username in Linphone preferences.java by setting primarycontact information , 

Unfortunately when we tested we experienced echo in some mobile devices it was sdk 4.3.0

for recovering this i compiled sdk 4.5.0 and successfully enable G729 codec aswel , but i could not find anywhere to set primary contact for peer to peer sip call .
how we can set primary contact or default username in kotlin code ?
or is not necessary to define the default username to replace linphone.android ?

as previous java wrapper has been removed , so i want to achieve same configurations for kotlin version and test echo . if you can help Thanks.

**Comment by Adnan-addi** [comment]
> Hi @Viish
> few days back i solved my problem of default username in Linphone preferences.java by setting primarycontact information ,
> 
> Unfortunately when we tested we experienced echo in some mobile devices it was sdk 4.3.0
> 
> for recovering this i compiled sdk 4.5.0 and successfully enable G729 codec aswel , but i could not find anywhere to set primary contact for peer to peer sip call .
> how we can set primary contact or default username in kotlin code ?
> or is not necessary to define the default username to replace linphone.android ?
> 
> as previous java wrapper has been removed , so i want to achieve same configurations for kotlin version and test echo . if you can help Thanks.

reference to this question.
https://github.com/BelledonneCommunications/linphone-android/issues/1377

**Comment by Viish** [comment]
Hi,

The JAVA wrapper we removed starting 5.0 is the legacy one, not the one we used in the 4.4.x version of our app and the ones before, so the link to the method I sent you is still right.

Cheers,

**Comment by Adnan-addi** [comment]
@Viish Thanks , 

can you provide me the link to the one you are telling me , i am trying the kotlin version but cant set default username so if 4.4.x supports sdk 4.5.0 can you share me the link to it .

**Comment by Viish** [comment]
This link you mean? http://linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Core.html#setPrimaryContact-java.lang.String-

4.4.x android version already uses 4.5.x SDK.
4.5.x android version uses 5.0.0-alpha SDK.

**Comment by Adnan-addi** [comment]
Thanks Much

**Comment by Viish** [comment]
Just so you know I've just added in Kotlin app (release/4.5 branch) the primary account settings if there are no real account configured.
