### ISSUE TITLE
Search for Specific Contact in Address Book Freezes Linphone-Android

### ISSUE THREAD

**Issue by stef204** [BelledonneCommunications/linphone-android#1388]
Just built and running `release 4-5` from gitlab
`Linphone Android 4.5.0-beta (tags/4.5.0-beta^0, release)`
`Linphone SDK 5.0.0-alpha.79+063bb85 (pipelines/28733, release)`

When inserting a name (a few characters or entire first name), Linphone Client freezes, and is extremely slow to actually find the contact.  If one clicks on the screen during that time, the popup dialog `Close App or Wait` appears.
Just waiting eventually produces the contact--but it is way too slow and a new problem not present in 4.4+

**Comment by Viish** [comment]
Hi,
Please attach debug logs showing the issue.
Thanks.

**Comment by stef204** [comment]
emailed them to linphone-android_AT_belledonne-communications.com

**Comment by stef204** [comment]
on this issue, I have uninstalled Linphone, rebuilt it, installed and configured it fresh.
the problem persists; it takes a **really** long time for the app to search/find a contact and it freezes, with the dialog box as described above.

**Comment by Viish** [comment]
How many contacts do you have?

**Comment by stef204** [comment]
I don't think that is relevant as the previous stable version 4.4 did not do this at all.  It found the contacts very quickly and never froze.  So something has changed in the kotlin rewrite which is causing this.
I cannot see the exact number, not sure how to display that but maybe 600?
Also, just found out that linphone's contact/address book is NOT displaying my contacts starting with the letter `Z`.

**Comment by Viish** [comment]
Make it generate an ANR and send the ANR tombstone please

**Comment by Viish** [comment]
Should be fixed by 6c223aae31de0ef9628a897d11dd078dae17c96d, now I can search a contact between 3k in less than a second.
