### ISSUE TITLE
When Clicking on a Call in History (to return a call), Call does not actually connect: nothing happens

### ISSUE THREAD

**Issue by stef204** [BelledonneCommunications/linphone-android#1389]
Just built and running `release 4-5` from gitlab
`Linphone Android 4.5.0-beta (tags/4.5.0-beta^0, release)`
`Linphone SDK 5.0.0-alpha.79+063bb85 (pipelines/28733, release)`

When Clicking on a Call in History (to return a call), Call does not actually connect: nothing happens.

The dialing dialog comes up and it `seems` to be dialing but never connects.

I always have to go back to Address Book, look for the name in there, and then dial from there; which does dial out AND connects.

**Comment by Viish** [comment]
Hi,
Please attach debug logs showing the issue.
Cheers,

**Comment by stef204** [comment]
emailed them at `linphone-android_AT_belledonne-communications.com`

**Comment by stef204** [comment]
@Viish 
It occurred to me you might want me to compile `assembleDebug` instead of `assembleRelease`?

**Comment by Viish** [comment]
Sorry for the late answer.
No I don't need you to use assembleDebug. However you might want to uninstall & reinstall the app, seems you have a lot of proxy configs & auth infos for the same account that might be related to your issue.
Also try with only one account before adding the other one.

**Comment by stef204** [comment]
thanks for the feedback.  i'm not sure what you are saying.  basically I used the Wizard to setup the accounts with the auth info, etc, and the modified some of the parameters to match the requirements of my SIP providers.  But I didn't configure/reconfigure, etc.
let me try to uninstall/reinstall, one account then try; and then add other account, as you suggested. will report back here.

**Comment by stef204** [comment]
no changes, issue is still there. I have to go back to the Linphone Address Book, search for the contact (and I run into the very long wait described in issue #1388 ; only then will the call actually be made.

**Comment by Viish** [comment]
Can you make me a video of the issue please?
From the moment of you click on the history entry to the call that works in the contacts.

**Comment by Viish** [comment]
Can you try with linphone-android commit id f8157043380233050c836107f3a3654b5915228a ? It should fix your issue.
