### ISSUE TITLE
INVITE with wrong SDP after a REFER if the active call is already paused or inactive

### ISSUE THREAD

**Issue by dsantomaso** [BelledonneCommunications/linphone-android#139]
Hello,
I am writing to signal this issue, which affects all the last linphone versions I've tested. The following releases have all the same behaviour:

- Linphone Android 3.2.7 - Core 3.11.1 - Belle-sip/1.6.1
- Linphone IOS 3.13.9 - Core 3.9.1
- Linphone Desktop 4.1.1 -  Core 3.12.0

We are using our SIP proxy and our desktop softphone, which in this scenario is the transfer agent. 
**A** (our softphone) is connected with **B** (linphone) and it wants to do an unattended transer to **C** (another Linphone). Sofphone A acts according to the RFC 5359. This is what happen:

1) **A** sends a reINVITE with audio inactive and puts **B** on hold
2) **A** sends a REFER to **B**
3) **B** then calls **C**, but the outgoing INVITE contains a wrong SDP without a valid audio media. **C** refuses the call.

It seems that Linphone is not able to build a valid SDP if this sequence occurs. Our softphone,  as many others (ad es. SNOM), puts  the other party on-hold before sending the REFER.  I am aware this isn't the way Linphone handles the blind transfer, but could you please fix it or suggest a workaround?
 
 Regards,
 Dario Santomaso.

[log.txt](https://github.com/BelledonneCommunications/linphone-android/files/1379484/log.txt)

**Comment by emrhio** [comment]
Hello, @dsantomaso did you find a workaround for this?
