### ISSUE TITLE
App Crash when someone try to transfer 

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#1391]
Hi @Viish ,

My app got crashed when the UA **A** try to transfer me on UA **B**. It was going ok while I was on hold but as soon as **A** press transfer button my app got crashed.

Error come : **ERROR linphone_core_invite_address_with_params(): sound are locked by another call and they cannot be freed. Call attempt is rejected.**

[ErrorWhileTransfer.txt](https://github.com/BelledonneCommunications/linphone-android/files/6445934/ErrorWhileTransfer.txt)

**Comment by amit1576** [comment]
Hello @Viish ,

Can you suggest how to attach symbolized native stack trace with app logs.  This app logs belongs to a app User.

**Comment by Viish** [comment]
Then you have to reproduce the issue yourself as there is no way to get a proper symbolized stack trace if you don't have access to the device unless you are using crashlytics
