### ISSUE TITLE
Incoming Calls Drop After 30 Seconds When Push Notifications Are Enabled

### ISSUE THREAD

**Issue by lukasubo** [BelledonneCommunications/linphone-android#1395]
**Describe the bug**
When I have push notifications enabled, incoming calls drop after 30 seconds. Disabling push notifications solves this. Similar to:

https://github.com/BelledonneCommunications/linphone-android/issues/265
https://community.asterisk.org/t/linphone-calls-drop-after-nearly-30-seconds/48910/2

Please let me know what logs, if any, would be helpful.

**To Reproduce**
1. Enable push notifications in Network and Account settings.
2. Use another phone to call the Linphone device.
3. Wait 30 seconds.

**Please complete the following information**
 - Device: Android Phone
 - OS: Android 10
 - Version of the App 4.5 Beta (if I recall correctly it occurred before too, and has been reported in past versions)
 - Version of the SDK 5.0 Alpha

**Comment by Viish** [comment]
Please attach logs from the start of the app to the end of a call that is dropped after 30 seconds.
I guess the issue is you are using UDP, try with TCP or TLS.

**Comment by lukasubo** [comment]
@Viish I'm using TLS. I'm trying to get the logs, but the "Send Logs" option does precisely nothing when I tap it.

**Comment by Viish** [comment]
After enabling logs in advanced settings, restart the app, reproduce your issue and then click on Send Logs button.
URL to logs will be copied in your clipboard, you can then attach it here or send it by mail, chat, etc... easily.

**Comment by lukasubo** [comment]
@Viish huh, for some reason that didn't work yesterday but it worked well today. I'm not really comfortable posting the logs, though. They contain a lot of private information. I think this line is cause of the drop:

> 2021-05-19 22:52:17:493 [org.linphone/belle-sip] ERROR Dialog [0x7ab99a0600] was not ACK'd within T1*64 seconds, it is going to be terminated.

Please let me know any other log info you need, and I'll anonymize it before posting.

**Comment by Viish** [comment]
You can send me logs directly: [sylvain.berfini@belledonne-communications.com](mailto:sylvain.berfini@belledonne-communications.com)

**Comment by NLLAPPS** [comment]
Just to give others some more information about this issue.
I have encountered this issue for incoming and outgoing calls for a specific old server. 
Disabling push notifications does not help.

It must be related to the server as it does not happen on other servers

**Comment by arcane47** [comment]
Not sure how disabling push notifications is an accepted solution. This is a issue that is not resolved.

**Comment by corobin** [comment]
I can reproduce this still with Linphone 5.2.3 on Android 14

with push on (no toggle in network setting, only in account setting), incoming call drops after 30s. disable it and call stays connected.

**Comment by Viish** [comment]
Enabling push notifications only adds push information to the contact info sent in SIP packets, which can be an issue regarding packet size when the transport protocol is UDP, that's all.

That's one of the reasons why we always recommend using TCP or TLS when possible.

**Comment by corobin** [comment]
I am using TLS

**Comment by Viish** [comment]
@corobin can you attach logs for a call with and without push enabled so I can check what is happening please?

**Comment by corobin** [comment]
> @corobin can you attach logs for a call with and without push enabled so I can check what is happening please?

I will work on generating that. Does the log contain personal info? How should I send it to you?

In settings there is an option for send logs and reset logs, i assume it will be best to reset log before each call (assuming that clears the log), and then there is a pre-filled URL in settings too, should i then just click send log?

**Comment by Viish** [comment]
> Does the log contain personal info? How should I send it to you?

It can. Send them to me by email at sylvain.berfini@belledonne-communications.com 

> In settings there is an option for send logs and reset logs, i assume it will be best to reset log before each call (assuming that clears the log), and then there is a pre-filled URL in settings too, should i then just click send log?

Indeed.

**Comment by corobin** [comment]
I just sent it with a description of the steps I took and some screenshots. Thanks.
