### ISSUE TITLE
surfaceView in linphone

### ISSUE THREAD

**Issue by jayqean** [BelledonneCommunications/linphone-android#1397]
Hello @Viish
How to use SurfaceView for video rendering? When I use core.nativeVideoWindowId=surfaceView, it will crash. If surfaceView is replaced with TextureView, it will be no problem. I have called core.setVideoDisplayFilter("MSAndroidTextureDisplay"). I want to try to switch from TextureView to SurfaceView.

**Comment by jayqean** [comment]
There is a wrong code above.    ==>    core.setVideoDisplayFilter("MSAndroidOpenGLDisplay");

**Comment by Viish** [comment]
Hi,
We only support Surface, SurfaceTexture and TextureView objects in core.nativeVideoWindowId methods.
You can use https://developer.android.com/reference/android/view/SurfaceView#getHolder() and https://developer.android.com/reference/android/view/SurfaceHolder#getSurface() to get a Surface object from the SurfaceView.
Cheers,

**Comment by Viish** [comment]
Sorry won't help you using a deprecated filter.
You should really stick to TextureView and MSAndroidTextureDisplay video display filter.
