### ISSUE TITLE
How to change encryption algorithm in linphone android

### ISSUE THREAD

**Issue by renukaghate** [BelledonneCommunications/linphone-android#1399]
How to change encryption algorithm in linphone android. Found a link that says search for this srtp_crypto_suites. But I am not able to find it in the latest code.

**Comment by Viish** [comment]
Simply set it like this in your factory config file (these are default values):
```
[sip]
srtp_crypto_suites=AES_CM_128_HMAC_SHA1_80, AES_CM_128_HMAC_SHA1_32, AES_256_CM_HMAC_SHA1_80, AES_256_CM_HMAC_SHA1_32
```
