### ISSUE TITLE
Issues in push notification,app can't wake up.

### ISSUE THREAD

**Issue by ravi-nimavat128** [BelledonneCommunications/linphone-android#140]
The notification itself doesn't initiate an incoming call, it can't wakes the device.

When i make call using app, receiver app can't able to wake up device.
Thanks.

**Comment by DatBewar** [comment]
Hello, what application did you use?
Linphone from Android store?
Linphone compiled by yourself?

**Comment by ravi-nimavat128** [comment]
Thanks 
i was fixed that issue.
