### ISSUE TITLE
Stun Server not being saved in config

### ISSUE THREAD

**Issue by stef204** [BelledonneCommunications/linphone-android#1401]
Android 11
Linphone4.5.0-beta-9+4dfaf7eb0 (release)

click on sip account
insert stun server in appropriate field like this:
`stun.sipprovider.com:3478`

but there is no way i can find to make it "stick"

once I use "back" to return to dialpad, for example, the uri disappears from the settings.

**Comment by stef204** [comment]
@Viish 
Update: for some reason, linphone-android started to now insert the following value in the stun serer field:
`stun.linphone.org`

I went ahead and removed that uri and replace it my the correct one (my provider) and it is now "sticking."

This is buggy though.

**Comment by Viish** [comment]
Stun field doesn't expect the port, that's why it doesn't "stick".

**Comment by stef204** [comment]
so where do I define the port? or does it automatically infer port 3478?
it is now showing stun.xxxx.com:3478 by the way,

**Comment by Viish** [comment]
3478 is the default stun port.

**Comment by stef204** [comment]
@Viish 
I compiled master, and that crashes once in use.  It then crashes at launch.
Went back to `release/4.5` and stun server still not being saved.  This issue should be re-opened.
Or you may only want to work on the `4.6 Alpha` version.
I _can_ uninstall 4.5 and try to reinstall 4.6 (which I had installed on top of 4.5) so do a fresh/clean install but not if it's going to create all sorts of problems until it is in `beta` stage.
Let me know what you suggest .  Thanks.
