### ISSUE TITLE
Linphone-android not displaying contacts properly when call comes in

### ISSUE THREAD

**Issue by stef204** [BelledonneCommunications/linphone-android#1402]
Android 11
Linphone4.5.0-beta-9+4dfaf7eb0 (release)

linphone-android has stopped displaying the contact name (stored in the main address book and shown in the contacts tab within linphone; just displaying the number of the caller.

The contact's phone number in the Android Address Book is written like this: +1xxxxxx-xxxx

I have set the country code properly in the settings, without the `+`.

Again, this seems to be a regression over last version which handled it properly and displayed the names of contacts stored when receiving calls.

**Comment by Viish** [comment]
Please attach logs

**Comment by stef204** [comment]
I've pulled and compiled again; and this problem seems to be fixed.
I don't know if it's related to code changes/commits you made or something to do with Android 11 which is really different / and much stricter (too restrictive perhaps) in terms of permissions

**Comment by stef204** [comment]
@Viish can you reopen this please?
The issue is back this morning.  I have not changed anything--except the default account.  That's the cause of the issue
In summary, when calls are **received** from the same country as is chosen as the country code in settings, contacts are displaying by name when present in Android Address Book.

When received on an account with a different country code inserted in settings than the originating call, it seems to display the number and not the name (so breaks the "called id" feature linked to Android Addres Book.)

It shouldn't do that. It should always show the name of the caller IF caller is included in Android Address Book, no matter the area code(s) involved or originating country.

**Comment by Viish** [comment]
Problem is there is no magic.
Contact matching works because of the international prefix set in your default proxy config, so if not set or if it's not the right one it doesn't work anymore and there's nothing I can do about that.

Usually it's not a problem because SIP accounts using phone number use the international prefix in the username, so no need for the prefix to be manually set, but if you receive a call from a number without prefix and that the same number is stored with the prefix in your Contact then the right prefix must be correctly set in the default proxy config.

**Comment by stef204** [comment]
It probably all depends on which account I have chosen as the `default` account at the time of receiving the call.  I don't know.
I do know that it did not do that on pre Kotlin version.  Never ran into that then.
My country codes are set properly at the appropriate places in settings.

**Comment by Viish** [comment]
Hi,
Just so you know I merged yesterday a fix for your issue, it will be available in SDK 5.0.0-alpha.106+890b9d3 and newer.
Cheers,
