### ISSUE TITLE
How to modify linphonerc_default unknown-host

### ISSUE THREAD

**Issue by Jasperben** [BelledonneCommunications/linphone-android#1404]
How to modify linphonerc_default unknown-host

**Comment by Viish** [comment]
Sorry I don't understand the question

**Comment by Jasperben** [comment]
![1621409885602](https://user-images.githubusercontent.com/15630036/118774318-466d6600-b8b8-11eb-93b8-758122325bc7.jpg)

**Comment by Jasperben** [comment]
sip from address host
sent-by address
The two addresses are inconsistent

![sss398](https://user-images.githubusercontent.com/15630036/118774940-f6db6a00-b8b8-11eb-881c-fbb9a5f404ca.jpg)

**Comment by Viish** [comment]
It seems you are doing peer to peer calls, and I guess for that you didn't configured any SIP account in the app.
However even with peer to peer calls you need to have an "identity" to fill the FROM header.
When public IP is available it is set as the domain for the default identity, hence the difference with your local network IP, but that won't prevent you from doing peer to peer calls.

**Comment by Jasperben** [comment]
yes  How to set default identity

**Comment by Viish** [comment]
http://linphone.org/snapshots/docs/liblinphone/latest/java/org/linphone/core/Core.html#setPrimaryContact-java.lang.String-

http://linphone.org/snapshots/docs/liblinphone/latest/java/org/linphone/core/Core.html#setGuessHostname-boolean-

**Comment by Jasperben** [comment]
setPrimaryContact
return -1
why????
