### ISSUE TITLE
SIP Client forces Outbound Proxy

### ISSUE THREAD

**Issue by stef204** [BelledonneCommunications/linphone-android#1405]
linphone-android 4.5.0-beta.12+3aaa8e49eb
SDK 5.0.0-alpha.100+8b8dbbb

linphone-android forces (always resets) `Outbound proxy` to `on` i.e. it toggles it to enabled constantly in spite of my disabling it.
there are other settings which behave that way in this rewrite and I think this is indicative of a problem

~~at this point, i am very tempted to go back to `tag 4.4.3` as this branch is just really buggy for me.~~
you only support `4.5` I believe?

**Comment by Viish** [comment]
I don't reproduce the issue.
Please provide logs.

**Comment by stef204** [comment]
This could be related to Android 11 and (write) permission related perhaps?

At the moment, with the latest build 4.5.0-beta.13+399233bc6 (release/4.5) it is just luck to make any settings inserted manually "stick".

All of the settings which appear by clicking individual accounts, are behaving as such, I can write "xx" in the country code field, and the only way I see to proceed from there is to hit the "back" arrow (no "enter" button).  Most of the time, that setting doesn't stick.  if I check it by clicking on the account again, the setting is now gone.

This can be the "display name" of the account, the country code, the stun server which at the moment is just **impossible** to make stick, etc. (with just the uri no port e.g. `stun.provider.com`.)

All of these are regressions from previous release versions 4.3 or 4.4 (prior to Kotlin rewrite.)

Another one: this morning, ALL of my setting were completely gone as if I had never configured the app.
At that point, I actually uninstalled it, rebuilt it and reinstalled it.  and reconfigured it.

4.5 (Kotlin rewrite) does not seem to be ready for a production environment., at the moment.

I can't provide logs at the moment as I have uninstalled, rebuilt and reinstalled.  But will do so on next occurrence.

**Comment by Viish** [comment]
When you make a setting change, try to "focus" another setting or press the "enter" key of your keyboard before leaving the account settings page, and tell me if that makes a difference.

**Comment by stef204** [comment]
I have tried that many times and unfortunately, it makes no difference.
What I do to get it to stick is try the above process (which you described) many different times, and at some point, on the nth try, it works.  But this is not reliable, obviously.

**Comment by Viish** [comment]
Can you test commit id 53b754d759e585a5f7c7e0e35fb12c58cb4010cf please and tell me if it's better ?

**Comment by Viish** [comment]
Don't mind my previous message, I've merged my changes in release/4.5 branch.
