### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for void org.linphone.core.tools.Log.setDomain(java.lang.String)

### ISSUE THREAD

**Issue by Cullian2017** [BelledonneCommunications/linphone-android#1406]
java.lang.UnsatisfiedLinkError: No implementation found for void org.linphone.core.tools.Log.setDomain(java.lang.String) (tried Java_org_linphone_core_tools_Log_setDomain and Java_org_linphone_core_tools_Log_setDomain__Ljava_lang_String_2)
        at org.linphone.core.tools.Log.setDomain(Native Method)
        at org.linphone.core.tools.Log.setLogDomain(Log.java:39)
        at org.linphone.core.tools.Log.instance(Log.java:28)
        at org.linphone.core.tools.Log.e(Log.java:64)

When i used Samsung phone, I will get the above error. while i used Huawei phone for debug, there was no such error at all.

**Comment by Viish** [comment]
Check you have build the SDK for the right architectures for all of your devices.
If yes, clean the build in Android Studio and start again.
This happens because native library isn't loaded.
