### ISSUE TITLE
4.4.3 Playing a video or audio outside of app pauses the call

### ISSUE THREAD

**Issue by UniqueActive** [BelledonneCommunications/linphone-android#1407]
Hello,

firstly thanks for your work on Linphone, it has been a great tool to have long and stable calls with my partner, we have been using it happily for years.

We were using version 4.3.1 from F-Droid and updated to 4.4.3 a few days ago when it became available. This seems to have made some changes to audio handling, and one side effect is the following:

Whenever I or my partner start a video or audio outside of Linphone, the call gets paused. I was unable to find a way to turn this off in the settings and it was not the case on previous versions. This sadly makes the app unusable for us in its current state, since we often watch or listen to things together or on the side while calling.

Please undo this part of the change or provide an option to disable this behaviour. I personally can't think of a reason why Linphone should behave this way by default.

Please also make sure that this is not the case in the upcoming rewrite. Perhaps this behaviour was not even intended and is a bug?

In any case, we would be thankful if you can solve this!

**Comment by Viish** [comment]
Hi,

Indeed starting SDK 4.5.0 (used in android app starting 4.4.0) we handle the audio focus inside our library.
Android recommends pausing calls when audio focus is lost, and thus that is what we decided to do. And of course starting a video do cause a loss of audio focus.
There is a "hidden" setting to disable that behavior that requires to edit the factory config file in the app, rebuild it and install it.
Starting next android app version (4.5.0, currently in beta) you will have a "real" setting to disable that (not yet in the beta but I will add it today).

Cheers,

**Comment by UniqueActive** [comment]
Hi @Viish ,

Thank you for the quick response! May I ask what is the value in pausing the call just because any media is playing? I understand pausing the call when another call happens, but I don't understand what value it brings to pause the call for any loss of audio focus. I also have not found any other app that handles it in this way.

I think pausing the call if another call happens is sensible, because you can hardly have two calls at the same time and there would be conflicting access to the microphone.

The same does not apply to other kinds of loss of focus though in my eyes. Pausing the call just for playing any other audio or video is more distuptive than helpful, it does not solve a problem, or at least not one that I am aware of.


For this reason I think it would make more sense to only pause the call for another call by default, but not for media. Pausing for media could be optional, but not the default because it is a lot more unexpected and disruptive than simply letting the call go on.

Does my reasoning make sense?

**Comment by Viish** [comment]
Hi,

Audio focus is request is made with the type of content we will play, the rest is Android business.
It's it that decides what to pause or not depending on the differents audio focus requests.
In the best world every app would properly handle audio focus but that is sadly not the case...

Cheers,

**Comment by UniqueActive** [comment]
So in your app you can't distinguish between losing focus because of another call or losing focus because of playing a video or audio? I am not sure if I understood correctly, I admit I don't know the Android internals too well. :)

**Comment by Viish** [comment]
Indeed.
I just know that our app has lost audio focus...

**Comment by Viish** [comment]
I'm closing this issue as I've commited the setting to disable this behavior.

**Comment by UniqueActive** [comment]
> Indeed.
> I just know that our app has lost audio focus...

I understand, thank you for taking the time to explain and implement an option to disable it. :)

**Comment by Viish** [comment]
You're very welcome :)
