### ISSUE TITLE
latest version issue

### ISSUE THREAD

**Issue by webjframework** [BelledonneCommunications/linphone-android#1411]
I am running latest version on android 10 phone.The issue is with the missed calls .When a call in linphone received the screen wake up and immediately you send the missed call notification while the screen is still on !The issue is that the notification marked as read and when the screen goes off no led blinking !!!Maby a good idea is to put some delay in sending missed call notification in order the screen to go off before !!!

thanks in advance !!!

John 

Webj Framework developer !

**Comment by Viish** [comment]
Please attach debug logs showing the issue.

**Comment by webjframework** [comment]
how you can see the not blinking led with the debug info ???

I am experienced analyst and developer .I am describing how to reproduce
the issue and i am giving a solution !!!

if you are sending the notification immediately with the no answer call you
will never get it work in android 10 at least !
if you send the notification after 10 sec problem solved !!!

**Comment by Viish** [comment]
With logs I'll see when notification is sent, when screen is turned off, which version of the app & sdk you have, which device you have tested this on, etc...
If you don't want to send logs, I'll close this issue.

**Comment by webjframework** [comment]
Ok
 there you are ...

**Comment by Viish** [comment]
There are no logs in your message...

**Comment by webjframework** [comment]
can't you get the attachment ??

**Comment by Viish** [comment]
Don't answer by email, use the web interface to attach the file or send a link please.

**Comment by webjframework** [comment]
Ok

[60ae567778347_a3ba79ab234b5635de5e.gz](https://github.com/BelledonneCommunications/linphone-android/files/6549720/60ae567778347_a3ba79ab234b5635de5e.gz)
