### ISSUE TITLE
how to use websocket in linphone android for communication

### ISSUE THREAD

**Issue by renukaghate** [BelledonneCommunications/linphone-android#1412]

**Comment by Viish** [comment]
You can't

**Comment by renukaghate** [comment]
can I use webRTC in linphone-android

**Comment by Viish** [comment]
No, you can't. But you can connect to other clients who use WebRTC (depending on your proxy server).

**Comment by renukaghate** [comment]
thanks for the quick reply.
But can I download linphone web source code and will it have webrtc support
and work both on desktop as well as android with web view.

**Comment by renukaghate** [comment]
Thank you for the clarification.
