### ISSUE TITLE
Can't hear the earphones

### ISSUE THREAD

**Issue by jayqean** [BelledonneCommunications/linphone-android#1414]
hello @Viish,
Hello, we have a headset in the meeting. Only one wired headset is normal, and the other cannot hear the sound. In addition, the headset is changed to the meeting APP or the headset is normal on another mobile phone. What is the problem? Is there a direction that can be checked? Comparing the linphone logs, I didn't see any problems.

**Comment by Viish** [comment]
Hi,
Please attach logs.
