### ISSUE TITLE
Feature request - decline call when another call is active

### ISSUE THREAD

**Issue by TijZwa** [BelledonneCommunications/linphone-android#1416]
Hi guys,

First of all, I really like Linphone. Keep up the good work!

Some of our VoIP users are members of a group/queue in which calls are routed to a free user (agent).
This works very well with fysical phone, which decline the call if the agent is busy.
In Linphone (on IOS and Android) the call is still showing up as waiting call (call waiting indication).

We would really like to be able to change this behaviour with a configuration setting.
I think this is fairly easy to implement.
We can use the same logic as gsmCallActive:
```
                if (gsmCallActive) {
                    Log.w("[Context] Refusing the call with reason busy because a GSM call is active")
                    call.decline(Reason.Busy)
                    return
                }
```
The logic would be something like this:
```
                if (corePreferences.callWaitingIndicationDisabled && core.callsNb > 0) {
                    Log.w("[Context] Refusing the call with reason busy because another call is active")
                    call.decline(Reason.Busy)
                    return
                }
```

Is this a feature you would like to add?

**Comment by Viish** [comment]
Hi,

If you want to automatically decline any incoming call after the first one with Busy reason, simply set the max_calls property in factory config file to 1:
```
[sip]
max_calls=1
```

Cheers,

**Comment by TijZwa** [comment]
@Viish, thanks, I know this option exists.
But this will also limit the outgoing calls, so calling a colleague for consultation before transferring the call becomes impossible.

**Comment by JacBra** [comment]
@Viish: can you please react on the point made by @TijZwa, being:
When max_calls=1 I cannot make attended transfers anymore. 
Result: Linphone app is not usable anymore since attended transfers are a key feature of any voip-system ;)
Possible solution: when max_calls would only apply to incoming calls, it would work.
Thanks in advance for your reply.

**Comment by Viish** [comment]
> When max_calls=1 I cannot make attended transfers anymore.

Indeed. But you can do simple transfer.

> Possible solution: when max_calls would only apply to incoming calls, it would work.

Yes, but we won't change that to not alter behavior of existing apps that would update the SDK.

If you want to decline incoming calls automatically while being able to make attended transfers then edit our app to do the call decline manually.
