### ISSUE TITLE
CLient certificate verification with different certificates for each client

### ISSUE THREAD

**Issue by renukaghate** [BelledonneCommunications/linphone-android#1418]
I want to implement client certificates in linphone android. As I understand from the documentation that if we use linphonerc then we have same client certificates for all clients. Frim the wiki link 
https://wiki.linphone.org/xwiki/wiki/public/view/Linphone/TLS%20client%20authentication/
I read that if every client has to have different certificates then we have to use, LinphoneCoreAuthInfoRequestedCb Callback . How do I do that.

**Comment by Viish** [comment]
Simply add a Core listener:
```
private val listener: CoreListenerStub = object : CoreListenerStub() {
        override fun onAuthenticationRequested(core: Core, authInfo: AuthInfo, method: AuthMethod) {
            
        }
}
core.addListener(listener)
```
