### ISSUE TITLE
Missed calls still wrongly categorized as incoming calls.

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-android#142]
I'm referring to closed issue #78 for this one, still occurs even with the latest linphone pull. Missed calls are marked as incoming calls with no missed call notification at all.

Also updated the submodules with following command: `git submodule sync && git submodule update --init --recursive`.

> Submodule path 'submodules/linphone': checked out '868c54118ff75fd8333d7727995794f639e658bd'

It appears that missing calls are only showed when the incoming call duration exceeds the value of the _"Incoming call hangup (in seconds)"_ setting. When the caller hangs up before that value is reached, the missed call is displayed as an incoming call.

**Comment by DatBewar** [comment]
Now i can't reproduce this.
Do you still have this issue?

**Comment by driesken** [comment]
I'm off work until next week so it can take me a few days. Last time I checked this issue was still occurring.

**Comment by driesken** [comment]
Sorry to reopen this again, but I'm still having this issue in build Linphone Android 3.3.1 - Linphone Core 3.12.0-284-g3b6978839.

This is the part where I hangup on the caller side:

> <--- Transmitting SIP request (844 bytes) to UDP:172.17.107.231:55060 --->
CANCEL sip:242680@172.17.107.231:55060;transport=udp;app-id=475732041065;pn-type=firebase;pn-tok=eaAPLt56A-s:APA91bGAFpecT1dq5aK_AC9hE1WvN3rYYPbSnQFsM5vm7wf7vRCXg--OjNbnF__ORnF6uvGtrMhMgB4YXvprPgOBDrTJv1bID2kQ8LxVGOQ0nMxiFEYLvLnT-CQ_hsoYaEtQ21zh1P51;pn-silent=1 SIP/2.0
Via: SIP/2.0/UDP 192.168.96.98:5060;rport;branch=z9hG4bKPjae804f2c-3371-4fbb-b596-aaffdfd8c621
From: "TESTTEST" <sip:21208@192.168.96.106>;tag=58b8b230-63b6-42a3-bd52-20f59afd9d4a
To: <sip:242680@172.17.107.231;app-id=475732041065;pn-type=firebase;pn-tok=eaAPLt56A-s:APA91bGAFpecT1dq5aK_AC9hE1WvN3rYYPbSnQFsM5vm7wf7vRCXg--OjNbnF__ORnF6uvGtrMhMgB4YXvprPgOBDrTJv1bID2kQ8LxVGOQ0nMxiFEYLvLnT-CQ_hsoYaEtQ21zh1P51;pn-silent=1>
Call-ID: abebc0af-2e82-472a-a1e5-38b98bd83d4c
CSeq: 12625 CANCEL
Reason: Q.850;cause=0
Max-Forwards: 70
User-Agent: UZPBX
Content-Length:  0

> <--- Received SIP response (635 bytes) from UDP:172.17.107.231:55060 --->
SIP/2.0 200 Ok
Via: SIP/2.0/UDP 192.168.96.98:5060;received=192.168.96.106;branch=z9hG4bKPjae804f2c-3371-4fbb-b596-aaffdfd8c621;rport=53082
From: "TESTTEST" <sip:21208@192.168.96.106>;tag=58b8b230-63b6-42a3-bd52-20f59afd9d4a
To: <sip:242680@172.17.107.231;app-id=475732041065;pn-type=firebase;pn-tok=eaAPLt56A-s:APA91bGAFpecT1dq5aK_AC9hE1WvN3rYYPbSnQFsM5vm7wf7vRCXg--OjNbnF__ORnF6uvGtrMhMgB4YXvprPgOBDrTJv1bID2kQ8LxVGOQ0nMxiFEYLvLnT-CQ_hsoYaEtQ21zh1P51;pn-silent=1>;tag=KItNuNb
Call-ID: abebc0af-2e82-472a-a1e5-38b98bd83d4c
CSeq: 12625 CANCEL
User-Agent: LinphoneAndroid/3.3.1 (belle-sip/1.6.3)
Supported: replaces, outbound

> <--- Received SIP response (651 bytes) from UDP:172.17.107.231:55060 --->
SIP/2.0 487 Request terminated
Via: SIP/2.0/UDP 192.168.96.98:5060;received=192.168.96.106;branch=z9hG4bKPjae804f2c-3371-4fbb-b596-aaffdfd8c621;rport=53082
From: "TESTTEST" <sip:21208@192.168.96.106>;tag=58b8b230-63b6-42a3-bd52-20f59afd9d4a
To: <sip:242680@172.17.107.231;app-id=475732041065;pn-type=firebase;pn-tok=eaAPLt56A-s:APA91bGAFpecT1dq5aK_AC9hE1WvN3rYYPbSnQFsM5vm7wf7vRCXg--OjNbnF__ORnF6uvGtrMhMgB4YXvprPgOBDrTJv1bID2kQ8LxVGOQ0nMxiFEYLvLnT-CQ_hsoYaEtQ21zh1P51;pn-silent=1>;tag=23z8XHX
Call-ID: abebc0af-2e82-472a-a1e5-38b98bd83d4c
CSeq: 12625 INVITE
User-Agent: LinphoneAndroid/3.3.1 (belle-sip/1.6.3)
Supported: replaces, outbound

**Comment by astuter** [comment]
Hi @DatBewar ,

Any update on this?
