### ISSUE TITLE
play  recording crash

### ISSUE THREAD

**Issue by wall3001** [BelledonneCommunications/linphone-android#1420]
SDK VERSION is 4.2
Android 10 device.
Play the recordings may cause the JNI crash.The probability is about 70 percent+.
pid: 12614, tid: 12974  >>> com.test.linphone <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0000000000000028
  x0   0000007274b1e000  x1   0000007274b310a9  x2   0000000000000000  x3   0044720000000000
  x4   8080800000000000  x5   7244000000000000  x6   000000000080c4f2  x7   fefeff71646c6064
  x8   0000007274bf3850  x9   0000000000000000  x10  0101010101010101  x11  0000000000000028
  x12  000000727b934bc0  x13  98ed659a5e46d270  x14  000000727b934c30  x15  0000d1662913fe41
  x16  000000729b7289e0  x17  00000073a38fa980  x18  00000000000006d2  x19  0000007272f9d980
  x20  0000007274b1eb57  x21  0000007274b1eb85  x22  0000007274b1ebc1  x23  00000072738fcfa0
  x24  000000727b934d50  x25  000000727b935020  x26  0000007274bf8768  x27  0000000000000000
  x28  0000000000000003  x29  000000727b934c20  x30  0000007274873564
  sp   000000727b934c10  pc   0000007274873954  pstate 0000000060000000
  v0   ffffff80ffffffc8000000727b934b80  v1   000000727b934bc0000000727b934c30
  v2   00000000000000004099933559b3d07c  v3   f04bf056f059f055f0b4f069f044f03f
  v4   0000000000000000f8eff80df763f707  v5   0000000000000000f6e6f67bf5d8f52b
  v6   0000000000000000f709f6e6f67bf5d8  v7   0000000000000000f707f709f6e6f67b
  v8   0000000000000000408f400000000000  v9   0000000000000000412e848000000000
  v10  00000000000000004059000000000000  v11  00000000000000003feccccccccccccd
  v12  00000000000000003fb9999999999998  v13  0000000000000000406475c447c30d30
  v14  00000000000000000000000000000000  v15  00000000000000000000000000000000
  v16  00000000000000000000000000000000  v17  00000000000000000000000000000000
  v18  00000000000000000000000000000000  v19  00000000020000000000000000000000
  v20  00000000000000000000000000000000  v21  00000000000000000000000000000000
  v22  00000000000000000000000000000000  v23  00000000000000000000000000000000
  v24  0000000000fdcf030000000000fd7bcf  v25  0000000000fd214f0000000000fcbf4e
  v26  00000000000000000000000000000000  v27  00000000000000000000000000000000
  v28  00000000000000000000000000000000  v29  00000000000000000000000000000000
  v30  00000000000000000000000000000000  v31  00000000000000000000000000000000
  fpsr 00000011  fpcr 00000000
    #00 pc 00000000000b1954  /data/app/com.test.linphone-ua_3z24HwpH9q3WkzzBmPA==/base.apk
    #01 pc 00000000000b1560  /data/app/com.test.linphone-ua_3z24HwpH9q3WkzzBmPA==/base.apk
    --- --- --- ---

memory near x0:
    0000007274b1dfc0 7974706d65206d6f 6f43007473696c20  om empty list.Co
    0000007274b1dfd0 6c2074276e646c75 206c6c612064616f  uldn't load all 
    0000007274b1dfe0 20736e6967756c70 007473696c206e69  plugins in list.
    0000007274b1dff0 67756c70206c6c41 6c206e6920736e69  All plugins in l
    0000007274b1e000 72726f6320747369 6f6c20796c746365  ist correctly lo
    0000007274b1e010 6e61430064656461 6e65706f20746f6e  aded.Cannot open
    0000007274b1e020 6f74636572696420 25203a7325207972   directory %s: %
    0000007274b1e030 00736d62696c0073 656d2f62696c2f2e  s.libms../lib/me
    0000007274b1e040 6165727473616964 67756c702f72656d  diastreamer/plug
    0000007274b1e050 64616f4c00736e69 7020736d20676e69  ins.Loading ms p
    0000007274b1e060 6620736e6967756c 7473696c206d6f72  lugins from list
    0000007274b1e070 676e6964616f4c00 67756c7020736d20  .Loading ms plug
    0000007274b1e080 6d6f726620736e69 6f74636572696420  ins from directo
    0000007274b1e090 005d73255b207972 6475613d65707974  ry [%s].type=aud
    0000007274b1e0a0 646f636e653b6f69 723b73253d676e69  io;encoding=%s;r
    0000007274b1e0b0 633b69253d657461 3d736c656e6e6168  ate=%i;channels=

memory near x1:
    0000007274b31068 0000000000000000 35676e69787a354e  ........N5zxing5
    0000007274b31078 4563497961727241 726f746365760045  ArrayIcEE.vector
    0000007274b31088 6552564b4d534d00 4d00726564726f63  .MSMKVRecorder.M
    0000007274b31098 20656c696620564b 726564726f636572  KV file recorder
    0000007274b310a8 6c50564b4d534d00 564b4d0072657961  .MSMKVPlayer.MKV
    0000007274b310b8 6c7020656c696620 564b4d0072657961   file player.MKV
    0000007274b310c8 726564726f636552 616974696e69203a  Recorder: initia
    0000007274b310d8 6e6f69746173696c 6f636552564b4d00  lisation.MKVReco
    0000007274b310e8 7270203a72656472 737365636f727065  rder: preprocess
    0000007274b310f8 202c726f72726520 20676e6974696177   error, waiting 
    0000007274b31108 49206e6120726f66 4d00656d6172662d  for an I-frame.M
    0000007274b31118 64726f636552564b 73726966203a7265  KVRecorder: firs
    0000007274b31128 6d6172662d492074 7669656365722065  t I-frame receiv
    0000007274b31138 6552564b4d006465 203a726564726f63  ed.MKVRecorder: 
    0000007274b31148 20676e6974696177 49206e6120726f66  waiting for an I
    0000007274b31158 4d00656d6172662d 64726f636552564b  -frame.MKVRecord

memory near x3:
    0044720000000000 ---------------- ----------------  ................

memory near x5:
    7244000000000000 ---------------- ----------------  ................

memory near x6:
    000000000080c4f0 ---------------- ----------------  ................

memory near x8:
    0000007274bf3810 0000000040010604 00000072748c91bc  ...@.......tr...
    0000007274bf3820 0000000040010704 00000072748c9204  ...@.......tr...
    0000007274bf3830 0000000040010804 00000072748c927c  ...@....|..tr...
    0000007274bf3840 0000000000000000 0000000000000000  ................
    0000007274bf3850 0000000000000077 0000007274b310a9  w..........tr...
    0000007274bf3860 0000007274b310b5 0000000000000000  ...tr...........
    0000007274bf3870 0000000000000000 0000000200000000  ................
    0000007274bf3880 00000072748c5648 0000000000000000  HV.tr...........
    0000007274bf3890 00000072748c567c 0000000000000000  |V.tr...........
    0000007274bf38a0 00000072748c5960 0000007274bf37a0  `Y.tr....7.tr...
    0000007274bf38b0 0000000080000000 0000007274bdb3a8  ...........tr...
    0000007274bf38c0 0000000000000005 0000007274bdb3a8  ...........tr...
    0000007274bf38d0 0000000000000006 0000007274bdb3a8  ...........tr...
    0000007274bf38e0 0000000000000007 0000007274bdb3a8  ...........tr...
    0000007274bf38f0 0000000000000008 0000007274bdb3a8  ...........tr...
    0000007274bf3900 0000000000000018 0000007274bdb3a8  ...........tr...

memory near x10:
    0101010101010100 ---------------- ----------------  ................

memory near x12:
    000000727b934b80 0000007273903680 0000000000000630  .6.sr...0.......
    000000727b934b90 0000000000000010 ffffffff9f456244  ........DbE.....
    000000727b934ba0 00216728db000000 7244000000000000  ....(g!.......Dr
    000000727b934bb0 00000073a611d000 000000000060d64e  ....s...N.`.....
    000000727b934bc0 000000727b934c30 000000727b934bc0  0L.{r....K.{r...
    000000727b934bd0 000000727b934b80 ffffff80ffffffc8  .K.{r...........
    000000727b934be0 000000727b934c20 000000727b934c30   L.{r...0L.{r...
    000000727b934bf0 000000727b934bc0 000000727b934b80  .K.{r....K.{r...
    000000727b934c00 ffffff80ffffffc8 98ed659a5e46d270  ........p.F^.e..
    000000727b934c10 0000007274b1eb57 0000007273903680  W..tr....6.sr...
    000000727b934c20 000000727b934cf0 0000007274873564  .L.{r...d5.tr...
    000000727b934c30 0000000000000000 0000000000007f70  ........p.......
    000000727b934c40 000000001681335b 0000000000007f70  [3......p.......
    000000727b934c50 00000000158771c6 000000003e070ad6  .q.........>....
    000000727b934c60 000000727b934c80 98ed659a5e46d270  .L.{r...p.F^.e..
    000000727b934c70 0000000000000000 0000000000000000  ................

memory near x14:
    000000727b934bf0 000000727b934bc0 000000727b934b80  .K.{r....K.{r...
    000000727b934c00 ffffff80ffffffc8 98ed659a5e46d270  ........p.F^.e..
    000000727b934c10 0000007274b1eb57 0000007273903680  W..tr....6.sr...
    000000727b934c20 000000727b934cf0 0000007274873564  .L.{r...d5.tr...
    000000727b934c30 0000000000000000 0000000000007f70  ........p.......
    000000727b934c40 000000001681335b 0000000000007f70  [3......p.......
    000000727b934c50 00000000158771c6 000000003e070ad6  .q.........>....
    000000727b934c60 000000727b934c80 98ed659a5e46d270  .L.{r...p.F^.e..
    000000727b934c70 0000000000000000 0000000000000000  ................
    000000727b934c80 0000000000000000 0000000000000000  ................
    000000727b934c90 0000000000000000 0000314600003146  ........F1..F1..
    000000727b934ca0 00000073a4e8c020 00000073a39618c4   ...s.......s...
    000000727b934cb0 000000727b935020 000000727b934d50   P.{r...PM.{r...
    000000727b934cc0 000000727b934d50 000000727b934dd8  PM.{r....M.{r...
    000000727b934cd0 000000727b935060 000000727b934d50  `P.{r...PM.{r...
    000000727b934ce0 00000073a39620ec 000000727b934d50  . ..s...PM.{r...

memory near x15:
    0000d1662913fe40 ---------------- ----------------  ................

memory near x16:
    000000729b7289a0 00000073a395d998 000000729b67330c  ....s....3g.r...
    000000729b7289b0 00000073a38fa880 000000729b69ee18  ....s.....i.r...
    000000729b7289c0 00000073a38c9240 000000729b67c39c  @...s.....g.r...
    000000729b7289d0 000000729b6a16a8 000000729b6c31a0  ..j.r....1l.r...
    000000729b7289e0 00000073a38fa980 000000729332337c  ....s...|32.r...
    000000729b7289f0 000000729b699d74 000000729b6b52ac  t.i.r....Rk.r...
    000000729b728a00 00000073a38c9344 000000729b698c98  D...s.....i.r...
    000000729b728a10 000000729b674510 000000729b6909b8  .Eg.r.....i.r...
    000000729b728a20 000000729b6ca240 000000729b693178  @.l.r...x1i.r...
    000000729b728a30 000000729b6c7b54 000000729b6714b0  T{l.r.....g.r...
    000000729b728a40 000000729b6882c8 000000729b684dc4  ..h.r....Mh.r...
    000000729b728a50 00000073a394d520 000000729b6a51bc   ...s....Qj.r...
    000000729b728a60 000000729b67c1f4 000000729b6dbf94  ..g.r.....m.r...
    000000729b728a70 00000073a394cf60 000000729b6c0ce8  `...s.....l.r...
    000000729b728a80 000000729b6d6628 000000729b6720d8  (fm.r.... g.r...
    000000729b728a90 000000729b6ca248 000000729b6d5940  H.l.r...@Ym.r...

memory near x17:
    00000073a38fa940 d1008042dac00063 f240007fdac01063  c...B...c.....@.
    00000073a38fa950 9a9f00008b430440 00000000d65f03c0  @.C......._.....
    00000073a38fa960 0000000000000000 0000000000000000  ................
    00000073a38fa970 0000000000000000 0000000000000000  ................
    00000073a38fa980 b200c3eaca010007 540003e1f24008ff  ..........@....T
    00000073a38fa990 54000241f2400807 f8408423f8408402  ..@.A..T..@.#.@.
    00000073a38fa9a0 b200d848cb0a0047 8a2800e4ca030045  G...H...E.....(.
    00000073a38fa9b0 b4ffff26aa0400a6 dac00c42dac00cc6  ....&.......B...
    00000073a38fa9c0 dac00c63dac010cb 9acb20639acb2042  ....c...B ..c ..
    00000073a38fa9d0 cb43e040d378fc42 927df000d65f03c0  B.x.@.C..._...}.
    00000073a38fa9e0 d37df0e7927df021 cb0703e7f8408402  !.}...}...@.....
    00000073a38fa9f0 92800008f8408423 aa0800429ac72508  #.@......%..B...
    00000073a38faa00 17ffffe7aa080063 54000100f240081f  c.........@....T
    00000073a38faa10 3840142338401402 7a4320407100045f  ..@8#.@8_..q@ Cz
    00000073a38faa20 f240081f540001e1 927d202754ffff41  ...T..@.A..T' }.
    00000073a38faa30 b4fffee7d27d20e7 f8408423f8408402  . }.......@.#.@.

memory near x19:
    0000007272f9d940 0000000000000000 0000000000000000  ................
    0000007272f9d950 0000000000000000 0000000000000000  ................
    0000007272f9d960 0000000000000000 0000000000000000  ................
    0000007272f9d970 0000000000000000 0000000000000000  ................
    0000007272f9d980 0000007274bf3850 0000000000000000  P8.tr...........
    0000007272f9d990 0000000000000000 0000000000000000  ................
    0000007272f9d9a0 0000000000000000 0000000000000000  ................
    0000007272f9d9b0 0000000000000000 0000007268ce40c0  .........@.hr...
    0000007272f9d9c0 0000007265240120 0000000000000000   .$er...........
    0000007272f9d9d0 00000072738bbb40 0000007273903680  @..sr....6.sr...
    0000007272f9d9e0 00000072738fcf20 0000000000000630   ..sr...0.......
    0000007272f9d9f0 0000000000000000 0000000000000000  ................
    0000007272f9da00 0000007272f64c00 0000007272f70b80  .L.rr......rr...
    0000007272f9da10 0000000000000000 0000000000000000  ................
    0000007272f9da20 0000000000000000 0000000000000000  ................
    0000007272f9da30 0000000000000000 0000000000000000  ................

memory near x20:
    0000007274b1eb10 7520646f6874656d 002e646574616470  method updated..
    0000007274b1eb20 656b6369745f736d 69745f7465735f72  ms_ticker_set_ti
    0000007274b1eb30 3a636e75665f6b63 2772656b63697420  ck_func: ticker'
    0000007274b1eb40 6d206b6369742073 707520646f687465  s tick method up
    0000007274b1eb50 57002e6465746164 543a676e696e7261  dated..Warning:T
    0000007274b1eb60 6b63697420736968 7420296425287265  his ticker(%d) t
    0000007274b1eb70 2064252073656b61 6f636573696c696d  akes %d miliseco
    0000007274b1eb80 3a7325002e73646e 6974206b63697420  nds..%s: tick ti
    0000007274b1eb90 6c2520736920656d 6b735f7661202c64  me is %ld, av_sk
    0000007274b1eba0 6625207369207765 2528746e756f6320  ew is %f count(%
    0000007274b1ebb0 6c706d6173202975 202029646c252865  u) sample(%ld)  
    0000007274b1ebc0 206557203a732500 6574616c20657261  .%s: We are late
    0000007274b1ebd0 6d20642520666f20 6e6f636573696c69   of %d milisecon
    0000007274b1ebe0 743e2d73202e7364 2520736920656d69  ds. s->time is %
    0000007274b1ebf0 735f7661202c646c 252073692077656b  ld, av_skew is %
    0000007274b1ec00 6e72657478652066 5f656d69745f6c61  f external_time_

memory near x21:
    0000007274b1eb40 6d206b6369742073 707520646f687465  s tick method up
    0000007274b1eb50 57002e6465746164 543a676e696e7261  dated..Warning:T
    0000007274b1eb60 6b63697420736968 7420296425287265  his ticker(%d) t
    0000007274b1eb70 2064252073656b61 6f636573696c696d  akes %d miliseco
    0000007274b1eb80 3a7325002e73646e 6974206b63697420  nds..%s: tick ti
    0000007274b1eb90 6c2520736920656d 6b735f7661202c64  me is %ld, av_sk
    0000007274b1eba0 6625207369207765 2528746e756f6320  ew is %f count(%
    0000007274b1ebb0 6c706d6173202975 202029646c252865  u) sample(%ld)  
    0000007274b1ebc0 206557203a732500 6574616c20657261  .%s: We are late
    0000007274b1ebd0 6d20642520666f20 6e6f636573696c69   of %d milisecon
    0000007274b1ebe0 743e2d73202e7364 2520736920656d69  ds. s->time is %
    0000007274b1ebf0 735f7661202c646c 252073692077656b  ld, av_skew is %
    0000007274b1ec00 6e72657478652066 5f656d69745f6c61  f external_time_
    0000007274b1ec10 752528746e756f63 6e65727275632029  count(%u) curren
    0000007274b1ec20 6c706d61736e5f74 2029646c25287365  t_nsamples(%ld) 
    0000007274b1ec30 7268742073250020 7469786520646165   .%s thread exit

memory near x22:
    0000007274b1eb80 3a7325002e73646e 6974206b63697420  nds..%s: tick ti
    0000007274b1eb90 6c2520736920656d 6b735f7661202c64  me is %ld, av_sk
    0000007274b1eba0 6625207369207765 2528746e756f6320  ew is %f count(%
    0000007274b1ebb0 6c706d6173202975 202029646c252865  u) sample(%ld)  
    0000007274b1ebc0 206557203a732500 6574616c20657261  .%s: We are late
    0000007274b1ebd0 6d20642520666f20 6e6f636573696c69   of %d milisecon
    0000007274b1ebe0 743e2d73202e7364 2520736920656d69  ds. s->time is %
    0000007274b1ebf0 735f7661202c646c 252073692077656b  ld, av_skew is %
    0000007274b1ec00 6e72657478652066 5f656d69745f6c61  f external_time_
    0000007274b1ec10 752528746e756f63 6e65727275632029  count(%u) curren
    0000007274b1ec20 6c706d61736e5f74 2029646c25287365  t_nsamples(%ld) 
    0000007274b1ec30 7268742073250020 7469786520646165   .%s thread exit
    0000007274b1ec40 545f534d00676e69 43535f52454b4349  ing.MS_TICKER_SC
    0000007274b1ec50 004f495250444548 75207963696c6f50  HEDPRIO.Policy u
    0000007274b1ec60 2c7325203a646573 7469726f69725020  sed: %s, Priorit
    0000007274b1ec70 203a646573752079 4445484353006425  y used: %d.SCHED

memory near x23:
    00000072738fcf60 0000000000000000 000000730919ed00  ............s...
    00000072738fcf70 0000007300000000 000000730fb097b1  ....s.......s...
    00000072738fcf80 0002000000000000 0000000800000000  ................
    00000072738fcf90 0000000000000000 0000000000000000  ................
    00000072738fcfa0 0000000000000000 0000000000000000  ................
    00000072738fcfb0 0000007272f9d980 0000000000000000  ...rr...........
    00000072738fcfc0 0000000000003dfe ffffffffffffffff  .=..............
    00000072738fcfd0 0000000000000000 00000000ffffffff  ................
    00000072738fcfe0 0000000300000002 00000072652671e0  .........q&er...
    00000072738fcff0 0000000000000000 0000000000000000  ................
    00000072738fd000 0000000000000000 0000000000000000  ................
    00000072738fd010 0000000000000000 0000000000000000  ................
    00000072738fd020 0000000000000000 0000000000000000  ................
    00000072738fd030 0000000000000000 0000000000000000  ................
    00000072738fd040 0000000000000000 0000000000000000  ................
    00000072738fd050 0000000000000000 0000000000000000  ................

memory near x24:
    000000727b934d10 000000727b934d40 00000073a3900318  @M.{r.......s...
    000000727b934d20 00000073a623eed0 0000000000000000  ..#.s...........
    000000727b934d30 00000073a4e8c020 00000073a623f188   ...s.....#.s...
    000000727b934d40 0000000000000000 0000000000000000  ................
    000000727b934d50 000000727be27d50 00000072747bdd50  P}.{r...P.{tr...
    000000727b934d60 00003146000032ae 0000000000000000  .2..F1..........
    000000727b934d70 000000727b83c000 00000000000f8d50  ...{r...P.......
    000000727b934d80 0000000000001000 0000000000000000  ................
    000000727b934d90 00000073a38c9370 0000007274b23426  p...s...&4.tr...
    000000727b934da0 0000000000000000 0000000000000000  ................
    000000727b934db0 0000007274873268 0000007273903680  h2.tr....6.sr...
    000000727b934dc0 0000000000000000 000000730f745000  .........Pt.s...
    000000727b934dd0 00000072498dc000 0000000000000001  ...Ir...........
    000000727b934de0 000000727b83c000 00000000000fd000  ...{r...........
    000000727b934df0 0000000000000000 0000000000000000  ................
    000000727b934e00 0000000000000000 0000000000000000  ................

memory near x25:
    000000727b934fe0 0000000000000000 0000000000000000  ................
    000000727b934ff0 0000000000000000 0000000000000000  ................
    000000727b935000 000000727b935060 0000000000000016  `P.{r...........
    000000727b935010 0000000000000000 000000727b935060  ........`P.{r...
    000000727b935020 00000073a38b30d0 000000727b934d50  .0..s...PM.{r...
    000000727b935030 0000000000000000 0000000000000000  ................
    000000727b935040 0000000000000000 98ed659a5e46d270  ........p.F^.e..
    000000727b935050 0000000000000000 0000000000000000  ................
    000000727b935060 0000000000000001 00000073200f4d00  .........M. s...
    000000727b935070 0000000000000000 0000000000000000  ................
    000000727b935080 0000000000000000 0000000000000000  ................
    000000727b935090 0000000000000001 0000000000000000  ................
    000000727b9350a0 0000000000000000 0000000000000000  ................
    000000727b9350b0 0000000000000000 0000000000000000  ................
    000000727b9350c0 0000000000000000 0000000000000000  ................
    000000727b9350d0 0000000000000000 0000000000000000  ................

memory near x26:
    0000007274bf8728 3f21147a606e54c7 3f0bab20377f897d  .Tn`z.!?}..7 ..?
    0000007274bf8738 3ee4f8b588e368f1 0000000000000000  .h.....>........
    0000007274bf8748 0000000000000000 0000000000000000  ................
    0000007274bf8758 0000000000000000 0000000000000000  ................
    0000007274bf8768 0000000000000000 0000000000000000  ................
    0000007274bf8778 0000000000000000 0000000000000000  ................
    0000007274bf8788 0000000000000000 0000000000000000  ................
    0000007274bf8798 0000000000000000 0000000000000000  ................
    0000007274bf87a8 0000000000000000 000000724ffd4a0c  .........J.Or...
    0000007274bf87b8 00000072931e7200 0000000000000000  .r..r...........
    0000007274bf87c8 0000000000000000 0000000000000000  ................
    0000007274bf87d8 0000000000000000 0000000000000000  ................
    0000007274bf87e8 0000000000000000 00000073200a8380  ........... s...
    0000007274bf87f8 0000001d8000001c 000000000000001d  ................
    0000007274bf8808 0000000000000000 0000000000000000  ................
    0000007274bf8818 0000000100000000 0000000000000000  ................

memory near x29:
    000000727b934be0 000000727b934c20 000000727b934c30   L.{r...0L.{r...
    000000727b934bf0 000000727b934bc0 000000727b934b80  .K.{r....K.{r...
    000000727b934c00 ffffff80ffffffc8 98ed659a5e46d270  ........p.F^.e..
    000000727b934c10 0000007274b1eb57 0000007273903680  W..tr....6.sr...
    000000727b934c20 000000727b934cf0 0000007274873564  .L.{r...d5.tr...
    000000727b934c30 0000000000000000 0000000000007f70  ........p.......
    000000727b934c40 000000001681335b 0000000000007f70  [3......p.......
    000000727b934c50 00000000158771c6 000000003e070ad6  .q.........>....
    000000727b934c60 000000727b934c80 98ed659a5e46d270  .L.{r...p.F^.e..
    000000727b934c70 0000000000000000 0000000000000000  ................
    000000727b934c80 0000000000000000 0000000000000000  ................
    000000727b934c90 0000000000000000 0000314600003146  ........F1..F1..
    000000727b934ca0 00000073a4e8c020 00000073a39618c4   ...s.......s...
    000000727b934cb0 000000727b935020 000000727b934d50   P.{r...PM.{r...
    000000727b934cc0 000000727b934d50 000000727b934dd8  PM.{r....M.{r...
    000000727b934cd0 000000727b935060 000000727b934d50  `P.{r...PM.{r...

code around pc:
    0000007274873910 a94157f6a9424ff4 d65f03c0a8c45ff8  .OB..WA.._...._.
    0000007274873920 aa1403e1f9400260 f900026097ffbea2  `.@.........`...
    0000007274873930 a9be4ff417fffff7 910043fda9017bfd  .....O...{...C..
    0000007274873940 f9403809f9400008 f0001540aa0003f3  ..@..8@.....@...
    0000007274873950 f9401522f9400501 a9409123fd400d20  ..@.".@. .@.#.@.
    0000007274873960 97fffc6e9136c000 b9402d09f9400268  ..6.n...h.@..-@.
    0000007274873970 5400018b7100053f f9401e69aa1f03f4  ?..q...T....i.@.
    0000007274873980 b4000089f8747929 97ffffeaf9408120  )yt..... .@.....
    0000007274873990 b9802d09f9400268 eb09029f91000694  h.@..-..........
    00000072748739a0 a9417bfd54fffeeb d65f03c0a8c24ff4  ...T.{A..O...._.
    00000072748739b0 a90157f6f81c0ff7 a9037bfda9024ff4  .....W...O...{..
    00000072748739c0 b94068099100c3fd 6b08013fb9407828  .....h@.(x@.?..k
    00000072748739d0 f9400009540005c0 aa0103f62a0303f5  ...T..@....*....
    00000072748739e0 b980292aaa0003f4 7100055faa0203f3  ....*)......_..q
    00000072748739f0 f9401a8b540001eb f86c796daa1f03ec  ...T..@.....myl.
    0000007274873a00 f94079adb40000ad 6b0801bfb94069ad  .....y@..i@....k

code around lr:
    0000007274873520 1e6808009e620122 1e6228001e691842  ".b...h.B.i..(b.
    0000007274873530 1e6a08021e620181 1e61184d1e612000  ..b...j.. a.M.a.
    0000007274873540 b9407a615400026d aa1403e01e780002  m..Taz@...x.....
    0000007274873550 f9402e7797fffd73 f9400ae0b40000b7  s...w.@.......@.
    0000007274873560 f94002f7940000f5 f9400348b5ffffb7  ......@.....H.@.
    0000007274873570 f9404262f9406661 fd400500aa1503e0  af@.bB@.......@.
    0000007274873580 f9400d04b9401103 fd406a6097fffd65  ..@...@.e...`j@.
    0000007274873590 aa1303e01e6c09a1 1e6028201e6b0800  ..l.......k. (`.
    00000072748735a0 97ffcc87fd006a60 f9404269b9807268  `j......hr..iB@.
    00000072748735b0 8b080121a94e026a d63f0140f9004261  j.N.!...aB..@.?.
    00000072748735c0 6b1b001f2a0003f7 b9407268540002cd  ...*...k...Thr@.
    00000072748735d0 6b0802ff0b080908 f94003485400024d  .......kM..TH.@.
    00000072748735e0 f9404263f9406661 fd400500aa1603e0  af@.cB@.......@.
    00000072748735f0 f9400d05b9401104 9400004e2a1703e2  ..@...@....*N...
    0000007274873600 aa0003f897ffbddc 97ffd8e9aa1303e0  ................
    0000007274873610 b900f277b40000d8 14000003f9007e78  ....w...x~......

stack:
    000000727b934b90:  0000000000000010 ffffffff9f456244 
    000000727b934ba0:  00216728db000000 7244000000000000 
    000000727b934bb0:  00000073a611d000 000000000060d64e 
    000000727b934bc0:  000000727b934c30 000000727b934bc0 
    000000727b934bd0:  000000727b934b80 ffffff80ffffffc8 
    000000727b934be0:  000000727b934c20 000000727b934c30 
    000000727b934bf0:  000000727b934bc0 000000727b934b80 
    000000727b934c00:  ffffff80ffffffc8 98ed659a5e46d270 
    000000727b934c10:  0000007274b1eb57 0000007273903680   #sp
    000000727b934c20:  000000727b934cf0 0000007274873564 
    000000727b934c30:  0000000000000000 0000000000007f70 
    000000727b934c40:  000000001681335b 0000000000007f70 
    000000727b934c50:  00000000158771c6 000000003e070ad6 
    000000727b934c60:  000000727b934c80 98ed659a5e46d270 
    000000727b934c70:  0000000000000000 0000000000000000 
    000000727b934c80:  0000000000000000 0000000000000000 
    000000727b934c90:  0000000000000000 0000314600003146 
    000000727b934ca0:  00000073a4e8c020 00000073a39618c4 
    000000727b934cb0:  000000727b935020 000000727b934d50 
    000000727b934cc0:  000000727b934d50 000000727b934dd8 
    000000727b934cd0:  000000727b935060 000000727b934d50 
    000000727b934ce0:  00000073a39620ec 000000727b934d50 
    000000727b934cf0:  000000727b934d10 00000073a3962114 
    000000727b934d00:  000000727b934d50 0000000000000000 
    000000727b934d10:  000000727b934d40 00000073a3900318 
    000000727b934d20:  00000073a623eed0 0000000000000000 
    000000727b934d30:  00000073a4e8c020 00000073a623f188 
    000000727b934d40:  0000000000000000 0000000000000000 
    000000727b934d50:  000000727be27d50 00000072747bdd50 
    000000727b934d60:  00003146000032ae 0000000000000000 
    000000727b934d70:  000000727b83c000 00000000000f8d50 
    000000727b934d80:  0000000000001000 0000000000000000 
    000000727b934d90:  00000073a38c9370 0000007274b23426 
    000000727b934da0:  0000000000000000 0000000000000000 
    000000727b934db0:  0000007274873268 0000007273903680 
    000000727b934dc0:  0000000000000000 000000730f745000 
    000000727b934dd0:  00000072498dc000 0000000000000001 
    000000727b934de0:  000000727b83c000 00000000000fd000 
    000000727b934df0:  0000000000000000 0000000000000000 
    000000727b934e00:  0000000000000000 0000000000000000 
    000000727b934e10:  0000000000000000 0000000000000000 
    000000727b934e20:  0000000000000000 0000000000000000 
    000000727b934e30:  0000000000000000 0000000000000000 
    000000727b934e40:  0000000000000000 0000000000000000 
    000000727b934e50:  0000000000000000 0000000000000000 
    000000727b934e60:  0000000000000000 0000000000000000 
    000000727b934e70:  0000000000000000 0000000000000000 
    000000727b934e80:  0000000000000000 0000000000000000 
    000000727b934e90:  0000000000000000 0000000000000000 
    000000727b934ea0:  0000000000000000 0000000000000000 
    000000727b934eb0:  0000000000000000 0000000000000000 
    000000727b934ec0:  0000000000000000 0000000000000000 
    000000727b934ed0:  0000000000000000 0000000000000000 
    000000727b934ee0:  0000000000000000 0000000000000000 
    000000727b934ef0:  0000000000000000 0000000000000000 
    000000727b934f00:  0000000000000000 0000000000000000 
    000000727b934f10:  0000000000000000 0000000000000000 
    000000727b934f20:  0000000000000000 0000000000000000 
    000000727b934f30:  0000000000000000 0000000000000000 
    000000727b934f40:  0000000000000000 0000000000000000 
    000000727b934f50:  0000000000000000 0000000000000000 
    000000727b934f60:  0000000000000000 0000000000000000 
[DEBUG] reach max continuously zero line count: 24!
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---

**Comment by Viish** [comment]
Two things:
- Your stack trace and other information are worthless, I need a proper backtrace with symbols
- You are using SDK 4.2 that we don't maintain anymore. Use latest 4.5.x release or 5.0-alpha SDK.
