### ISSUE TITLE
Audio Codec issue

### ISSUE THREAD

**Issue by RaviChavada** [BelledonneCommunications/linphone-android#1423]
Hello, I am using linphone SDK 4.5+ and I am facing an issue while click on the audio codec application is crashed, please suggest to me how to handle the crash

Log file
[linphone crash log.txt](https://github.com/BelledonneCommunications/linphone-android/files/6636028/linphone.crash.log.txt)

**Comment by Viish** [comment]
Please don't duplicate issue. I moved the one you previously opened there: https://github.com/BelledonneCommunications/linphone-sdk/issues/157
