### ISSUE TITLE
Cypher database 

### ISSUE THREAD

**Issue by pako1** [BelledonneCommunications/linphone-android#1424]
Hi, is it possible to encrypt the database on liphone ? And If yes then how, because I couldn't find the database in the application. 
Thanks a lot in advance for your help.

**Comment by Viish** [comment]
Hi,
Check VFS advanced setting (available starting 4.5.0 beta version).
More info about it here: https://wiki.linphone.org/xwiki/wiki/public/view/Linphone/Linphone%20file%20encryption/
Cheers,
