### ISSUE TITLE
Qr Code Reader 

### ISSUE THREAD

**Issue by pako1** [BelledonneCommunications/linphone-android#1425]
Hi once again, I was curious to know if its possible to enable the torch in the qr code reader. Thanks in advance 

P.s. if I want to contribute to the project is it possible as well?

**Comment by Viish** [comment]
Sorry but it isn't planned.
I've seen the API to do this, it requires access to the Camera object, but as we already use it in SDK that will lead to a conflict.
So to do it properly, it must be done in our SDK, which isn't as easy to do that simply adding it to the Android app.

**Comment by mwarning** [comment]
@pako1 is the question about the torch only, or QR Codes?
Btw. this is an Open Source project; everyone can contribute. But it is up to the  developers in charge to decide if a contribution is accepted. Communication is usually key.

**Comment by Viish** [comment]
Closing as we don't plan to do it.
