### ISSUE TITLE
In android 10 and above devices call notification is coming but call notification pop up not display.

### ISSUE THREAD

**Issue by prashant1137** [BelledonneCommunications/linphone-android#1426]
I have used linphone sdk 4.2.

**Comment by Viish** [comment]
First of all, I don't understand your problem.
Second, SDK 4.2 is quite old (current release is 4.5) so first update and see if issue still happens.
If it does, please provide understandable information.

**Comment by prashant1137** [comment]
The problem is this when app in the background incoming call notification is not displayed on the home screen. when I open the notification bar then the notification is visible.

**Comment by Viish** [comment]
As I said that issue has been solved a long time ago, just update the app.

**Comment by prashant1137** [comment]
Okay thanks
