### ISSUE TITLE
Lime encryption 

### ISSUE THREAD

**Issue by pako1** [BelledonneCommunications/linphone-android#1427]
I hope I'm not bothering. 
I was testing the linphone app and more specifically the chat. It appears that sometimes the x3dh server url is null and when creating a new chat the option to enable lime is not available. Is this a known issue? 

Additionally, I have set my own sip server and if I want to create a chat with e2ee,  I cant pick any contact for e2ee chat. Does it matter that I have my own sip server and I'm using the testing xd3h server? Am I missing something here ? Any tip and help would be great!! 

Thanks in advance!

**Comment by Viish** [comment]
Hi,

X3DH server URL is only set for sip.linphone.org accounts as both are deeply linked.
In the app if the default Account isn't using sip.linphone.org domain, we hide advanced features that requires a Flexisip proxy server to work such as group chat & e2ee chat.

What do you mean by testing x3dh server?
If you have deployed a flexisip proxy (+ conference & presence) server and that you also have a X3DH key server then you can edit linphone-android source code to allow advanced IM features for your domain as well.

Finally yes contacts that do not advertise advanced IM features support through presence are disabled.

Hope it clarifies.
Cheers,
