### ISSUE TITLE
linphone e Lineage os 

### ISSUE THREAD

**Issue by giulio68** [BelledonneCommunications/linphone-android#1428]
hi, i installed linphone on android lineage os 17.1 for raspberry py 4B and the microphone is not heard, I tried to raise the microphone amplification in the audio settings but it is not heard, can you help me?
thank you in advance.

**Comment by Viish** [comment]
Hi,

Can you please attach SDK logs?
I recommend you to use our current linphone-android beta version that include input audio device selection.

Cheers,

**Comment by Viish** [comment]
I'm closing since I've haven't received any update. I'll reopen if you answer.
