### ISSUE TITLE
Hello I have integrate Linphone sdk in my default project and i have try to register sip device but not getting any request on server.

### ISSUE THREAD

**Issue by prashant1137** [BelledonneCommunications/linphone-android#1429]

**Comment by prashant1137** [comment]
public void genericLogIn(
            String username,
            String userid,
            String password,
            String displayname,
            String prefix,
            String domain,
            TransportType transport) {
//        connectionTimeOut();
        Core core = LinphoneManager.getLcIfManagerNotDestroyedOrNull();

        Log.d("genericLogIn", "response: +core "+core);

        if (core == null) return;

        AuthInfo authInfo =
                Factory.instance().createAuthInfo(username, userid, password, null, null, domain);
        core.addAuthInfo(authInfo);

        ProxyConfig proxyConfig = core.createProxyConfig();

        String identity = "sip:" + username + "@" + domain;
        Address identityAddr = Factory.instance().createAddress(identity);
        if (identityAddr != null) {
            identityAddr.setDisplayName(displayname);
            proxyConfig.setIdentityAddress(identityAddr);
        } else {
            hideDialog();
            Toast.makeText(RegistrationActivity.instance(), "Invalid server URL or Domain", Toast.LENGTH_LONG).show();
            return;
        }
//      String strProxy = "gtngc1.goldtelcloud.co.za";/*"flexisip.astppbilling.org:5060";*///domain;
      String strProxy = domain;;/*"flexisip.astppbilling.org:5060";*///domain;
//        String strProxy = "flexisip.astppbilling.org:5060";/*"flexisip.astppbilling.org:5060";*///domain;
        if (checkStatusProxy) {
            strProxy = ssProxy;
        }
//      String strProxy = domain;
        String proxy = "<sip:" + strProxy + ";transport=" + transport.name().toLowerCase() + ">";
        proxyConfig.setServerAddr(proxy);
        proxyConfig.setDialPrefix(prefix);
//        try {
//            proxyConfig.setExpires(Integer.parseInt("86400"));
//        } catch (NumberFormatException nfe) {
//            org.linphone.core.tools.Log.e(nfe);
//        }

        core.addProxyConfig(proxyConfig);
        core.setDefaultProxyConfig(proxyConfig);
        mAccountCreated = true;
//        success();
    }

**Comment by Viish** [comment]
Check out our tutorials: https://gitlab.linphone.org/BC/public/tutorials/-/tree/master/android/kotlin/AccountLogin

**Comment by prashant1137** [comment]
Okay thanks i will check.
