### ISSUE TITLE
I have download shared code but how to decline sip call  mCore.declineCall(call, Reason.Busy); on sdk 5.0.

### ISSUE THREAD

**Issue by prashant1137** [BelledonneCommunications/linphone-android#1431]
**Describe the bug**

**If the issue is about the SDK (build, issue, etc...) open the ticket in the [linphone-sdk](https://github.com/BelledonneCommunications/linphone-sdk) repository or one of it's submodules!**

**To Reproduce**

**Expected behavior**

**Please complete the following information**
 - Device: [e.g. Samsung Note 20 Ultra]
 - OS: [e.g. Android 11]
 - Version of the App [e.g. 4.3.1]
 - Version of the SDK [e.g 4.4.16]

**SDK logs**
Enable debug logs in advanced section of the settings, restart the app, reproduce the issue and then go to About page, click on "Send logs" and copy/paste the link here.

**Adb logcat logs**
In case of a crash of the app, please also provide the stack trace of the crash using adb logcat.

**Screenshots**

**Additional context**

**Comment by Viish** [comment]
Please improve the description of what the issue is, I understood nothing.

**Comment by prashant1137** [comment]
My question is this First i have used 4.2 sdk and now i have upgrade with 5.0 sdk in 4.2 version.
i have decline call using 
mCore  is Core object 
mCore.declineCall(call, Reason.Busy);

but in 5.0 version i have not found   "declineCall" method so how to decline call.

**Comment by Viish** [comment]
First of all, 5.0 isn't released yet so you should stick to 4.5 release.
Anyway 4.2 was a long time ago, many changes happened since then, and you can take a look at the [CHANGELOG ](https://github.com/BelledonneCommunications/linphone-sdk/blob/master/CHANGELOG.md)file in the SDK.
Check our API reference for all available APIs: http://linphone.org/snapshots/docs/liblinphone/latest/java/

**Comment by Viish** [comment]
> but in 5.0 version i have not found "declineCall" method so how to decline call.

Simply use `call.decline();`

This is the only one time I'll answer questions like that by the way.

**Comment by prashant1137** [comment]
Okay thanks
