### ISSUE TITLE
Attended Transfer

### ISSUE THREAD

**Issue by RaviChavada** [BelledonneCommunications/linphone-android#1433]
Hello,
Can you please guide me how to achieve Attended Transfer using Linphone SDK 4.5+, i am using transferToAndother(Call dest) method but i am not able to achive it.

**Comment by Viish** [comment]
Hi,

Have you checked the doc? http://linphone.org/snapshots/docs/liblinphone/latest/java/org/linphone/core/Call.html#transferToAnother-org.linphone.core.Call-
Also, what is your issue because "i am not able to achive it" isn't helpful...

**Comment by RaviChavada** [comment]
Thanks for your support.
I found the solution.
