### ISSUE TITLE
When we have an active call, if receive incomming call from GSM or WhatsApp , linphone call automatically going on holding

### ISSUE THREAD

**Issue by allen-lotfin** [BelledonneCommunications/linphone-android#1434]
When we have an active call, if receive incomming call from GSM or WhatsApp , linphone call automatically going on holding please help

**Comment by Viish** [comment]
That is a feature actually. Android dev guidelines recommend to pause any voip call when audio focus is lost, which happens when you receive another call.
You can use the setting in call section to disable this behavior (starting 5.0-beta version).

**Comment by dishankEbizz** [comment]
Hello, Which setting needs to be disabled for disabling that feature?

**Comment by Viish** [comment]
@dishankEbizz It's the "Pause calls when audio focus is lost" setting.

**Comment by dishankEbizz** [comment]
Okay. Thanks for your quick response :)
