### ISSUE TITLE
Force upgrade check?

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1436]
Is there any way to force an upgrade check?

I have noticed:

```
    <entry name="version_check_url_last_timestamp" overwrite="true"></entry>
```

and
```
    <entry name="version_check_interval" overwrite="true"></entry>
```

in the `app` section of the _linphonerc_ provisioning file.  I have tried setting the former to 0 and the latter to a very small value (what is the unit of the latter, btw?  Looks like milliseconds.) to force an upgrade check but that doesn't seem to be doing anything.

**Comment by Viish** [comment]
Setting version_check_url_last_timestamp to 0 should be enough to trigger the version update check.
Please attach SDK logs.

**Comment by brianjmurrell** [comment]
> Setting version_check_url_last_timestamp to 0 should be enough to trigger the version update check.

On what kind of events?  Start-up, wake from doze, something else?

> Please attach SDK logs.

How far back?  To a wake up, core start up, something else?

**Comment by brianjmurrell** [comment]
That said, it would be nice to have some kind of UI widget to force an update check.

**Comment by Viish** [comment]
> That said, it would be nice to have some kind of UI widget to force an update check.

What for? Both Play Store & F-Droid have available update notifications built-in, so each app doesn't have to do this check by themselves.

> On what kind of events? Start-up, wake from doze, something else?

When you open the app and land on the dialer.

> How far back? To a wake up, core start up, something else?

As always, to the core initialization.

**Comment by brianjmurrell** [comment]
> What for? Both Play Store & F-Droid have available update notifications built-in, so each app doesn't have to do this check by themselves.

Because `misc->version_check_url_root` might point to one's own defined location to upgrade to one's own devices to one's own builds.

> When you open the app and land on the dialer.

Yeah, I don't think that is happening (consistently?).  Of course, as luck would have it, I just tried to reproduce it and it did work this time, seeing the update and offering to download it.

But being able to trigger the check, without having muck with setting `version_check_url_last_timestamp` to `0` would be useful.

> As always, to the core initialization.

Indeed.  Will attach if/when I can reproduce.

You didn't seem to answer about what units `version_check_interval` is in.  Is it MS?

**Comment by Viish** [comment]
> Because misc->version_check_url_root might point to one's own defined location to upgrade to one's own devices to one's own builds.

I'm sure you understand this only affect quite a few users, possibly only yourself. 

> Yeah, I don't think that is happening (consistently?).

As I said, it's when you open the app as it is when the Dialer is created, not resumed.

> You didn't seem to answer about what units version_check_interval is in. Is it MS?

Yes. Default value of 86400000 is 24h.
