### ISSUE TITLE
Call goes to speaker phone when its initiated

### ISSUE THREAD

**Issue by krishnak** [BelledonneCommunications/linphone-android#1439]
Android app 4.4.3 release
linphone sdk 4.5.7

Android 7.1.2

I am connecting to SIP server via UDP - this is the only supported option given by the SIP provider and PCMA - aLaw is the only supported codec.

When I make an outgoing call, the ring-back tone is heard in speaker mode (even though the speaker icon is disabled) and the call gets connected in speaker mode. 

This is occurring consistently.

**Comment by Viish** [comment]
Hi,
Please attach sdk debug logs.

**Comment by krishnak** [comment]
I think its an issue on my side, some how the default output had the speaker instead of ear piece. Closing it
