### ISSUE TITLE
Which version of the SDK does Android 4.4 use with H264?

### ISSUE THREAD

**Issue by Roger1103** [BelledonneCommunications/linphone-android#1440]
Hi,Dear! Which version of the SDK does Android 4.4 use with H264? 
best wish!

**Comment by Viish** [comment]
Hi Roger, 
Android version 4.4 uses SDK 4.3.
Cheers,

**Comment by Roger1103** [comment]
> Hi,Dear! Which version of the SDK does Android 4.4 use with H264?
> best wish!

Hi,
I used Linphone-SDK-Android 4.3 to import libopenh264.so;
But I can't find the H264 code.
Thanks.

**Comment by Viish** [comment]
We no longer use OpenH264 for H264 video codec, instead we rely on MediaCodec implementation available on all Android > 5.0

**Comment by Roger1103** [comment]
> We no longer use OpenH264 for H264 video codec, instead we rely on MediaCodec implementation available on all Android > 5.0

Hi,
My device is Android 4.4 and I use H264.Which version of the SDK should I use?
Thanks

**Comment by Viish** [comment]
Sadly we no longer support Android 4.4 for our SDK or our app, so you won't be able to use a SDK version newer than 4.3.x :-/
