### ISSUE TITLE
A few clients are unresponsive

### ISSUE THREAD

**Issue by zengyimou** [BelledonneCommunications/linphone-android#1441]
Hello, we are now using the Linphone SIP service to make voice calls on a large scale. There are cases where some SIP server requests cannot be answered or responded to by the client. Excuse me this kind of situation has what better debugging or processing method. Now we are using a relatively large magnitude, about 300 passes a day can not respond to the situation, from which aspect can we optimize

**Comment by Viish** [comment]
Hi,
Can you attach logs from app (enable them first in advanced settings) when such situation occurs?
Thanks.

**Comment by zengyimou** [comment]
> Hi,
> Can you attach logs from app (enable them first in advanced settings) when such situation occurs?
> Thanks.

I now integrate Linphone into my app. You mean I can upload through the log in the advanced Settings. Pass the problem to your own server. Then analyze the problem based on the log? Is there an upload mechanism for troubleshooting logs?

**Comment by Viish** [comment]
As you opened this issue in linphone-android repository I assume you are using linphone-android app at some point?
If yes, please use the upload logs feature inside it and copy/paste the link here, otherwise enable the logger in our SDK, collect the logs and them to me.

**Comment by Viish** [comment]
I'm closing since I've haven't received any update. I'll reopen if you answer.
