### ISSUE TITLE
App is not start while device is locked, application is killed and hangup the call

### ISSUE THREAD

**Issue by RaviChavada** [BelledonneCommunications/linphone-android#1444]
Hey,
When I killed the application and locked my device after that call is coming, answer the call and hang up the call, now unlocked the device and our application is in background mode. when I clicked on the recent button and click on our application, the application did not come to the foreground.

Please find the log file
[linphone logs.txt](https://github.com/BelledonneCommunications/linphone-android/files/6776427/linphone.logs.txt)

**Comment by Viish** [comment]
Hi,
Please enable debug logs in advanced settings, restart the app, reproduce the issue and upload logs using the button (either in About page or Advanced settings depending on the version you use).

**Comment by RaviChavada** [comment]
Hello,
Please find the attachment
is there anything missing please let me know.

[log.txt](https://github.com/BelledonneCommunications/linphone-android/files/6777654/log.txt)

**Comment by Viish** [comment]
From your logs you are on 4.4.3 release.
Can you join the beta program on the Play Store to test 4.5.0 version? You can also build it from release/4.5 branch.

**Comment by RaviChavada** [comment]
yes, it is a 4.4.3 release but the sdk is 4.5+

**Comment by Viish** [comment]
Yes, but issue is solved in 4.5.0 app release (which uses 5.0 SDK).

**Comment by RaviChavada** [comment]
So in that case, you can not provide support in 4.5+ SDK version?
In 5.0 version contains a lot many changes and also changes in some base classes, if possible provide same support of 4.5+ SDK version

**Comment by RaviChavada** [comment]
Check it in beta version also and it contains the same issue, will send the mail of log file using application please check it.

**Comment by Viish** [comment]
I didnt received it...
Can you also upload a video of the issue please ?

**Comment by RaviChavada** [comment]
Hey, please find the attachment

https://user-images.githubusercontent.com/17444917/125059226-b59d5480-e0c8-11eb-9b3f-34b4554825a0.mp4

**Comment by Viish** [comment]
Thanks for the video, it helped me understand and reproduce.
Fix has been made in master branch commit id `8c6758c4b8323dd17a03128e2d7d487a4b7f5975`
and in release/4.5 branch commit id `7e369d3a02d49d289048372aa08f5e49cc13eb05`

**Comment by RaviChavada** [comment]
Thanks for support
