### ISSUE TITLE
How to get a remote IP address

### ISSUE THREAD

**Issue by zjhcode** [BelledonneCommunications/linphone-android#1447]

**Comment by Viish** [comment]
Please be more specific.

**Comment by zjhcode** [comment]
When a call incoming，i can use call.getRemoteAddress() to get remoteAddress info，but how to get the IP address。
If this call come from ip 192.168.1.1，how to get it

**Comment by zjhcode** [comment]
> Please be more specific.

When a call incoming，i can use call.getRemoteAddress() to get remoteAddress info，but how to get the IP address。
If this call come from ip 192.168.1.1，how to get it
