### ISSUE TITLE
Initial video stream.

### ISSUE THREAD

**Issue by arm-computech** [BelledonneCommunications/linphone-android#1448]
Good day! Is it possible to organize an initial video capture before responding. How can this be organized?

**Comment by Viish** [comment]
Do you mean starting the call with video or starting the call recording at the same time as the call?

**Comment by arm-computech** [comment]
There is no initially getting a video to understand who is calling, and starting from this, for example, to pick up the phone or not. That is, get a video before picking up the phone.

**Comment by Viish** [comment]
Ah ok you want early-media video.
There is a setting in "Call" section to allow for incoming early media, but there is no setting to make the app send it when initiating a call.
You will have to implement it yourself using http://linphone.org/snapshots/docs/liblinphone/latest/java/org/linphone/core/CallParams.html#enableEarlyMediaSending-boolean-

**Comment by arm-computech** [comment]
Thank you for what you need! They helped.

**Comment by pergolafabio** [comment]
sorry to reply
but early media is interesting, linphone client is able to accept early video
but i havent found a PBX solution that is able to send early media to ring groups or follow me?
my door intercom sends early media, with linphone i see early video, if i just call a single SIP
calling multiple SIP at once, i dont see any early video anymore

any tips are welcome!!

**Comment by August1023** [comment]
I set enableEarlyMediaSending to true, but the callee did not see the early media during the call. Can you help me?
