### ISSUE TITLE
Mic volume is too low

### ISSUE THREAD

**Issue by bam80** [BelledonneCommunications/linphone-android#1449]
My correspondent on the other end can barely hear me.
I saw Mic gain in options, but does adaptive volume supported?

**Comment by Viish** [comment]
What do you mean by "adaptive volume" exactly?
Otherwise yes, if your microphone is too low, you can use the mic gain setting to increase the sent "volume".

**Comment by bam80** [comment]
I mean feature of automatic mic volume correction as many others communication apps have.
The strange thing is when I do call via cellular network the volume is better.
Do you have explanation of this?

**Comment by Viish** [comment]
> I tried to set the gain setting to 3 dB but it seems had no impact, maybe the value is too low still..

Yes there was an issue with mic gain setting in 4.5.0 release, it's now fixed in 4.5.1 (published a few hours ago on the Play Store).

**Comment by bam80** [comment]
Thanks. I also would be appreciate for corresponding issue or MR.

**Comment by bam80** [comment]
@Viish I tried new version, it had no difference at all on mic volume.
More on that - gain setting doesn't have impact (0dB or 18dB - no difference).
Let's reopen the issue, please.

**Comment by bam80** [comment]
Apparently the issue was related to my mic problems, I cleaned up the hole to the mic and now it's OK.
