### ISSUE TITLE
Pre-defined proxy

### ISSUE THREAD

**Issue by czaviar** [BelledonneCommunications/linphone-android#145]
Hello,

Is there any way to predefine my proxy, so that it's always in the code to avoid typing it manually when I create a generic account ? I was trying to put the following lines in linphonerc_default, but have not succeeded to work:

[sip]
default_proxy=0

[proxy_0]
reg_proxy=<sip:my.server:5223;transport=tls>
reg_route=<sip:my.server:5223;transport=tls>

Another issue is how to enable "Outboud proxy" by default ?

**Comment by DatBewar** [comment]
Try this with your configuration 

[proxy_default_values]
 reg_expires=600
 reg_identity=sip:?@sip.linphone.org
 reg_proxy=<sip:sip.linphone.org;transport=tls>
 reg_sendregister=1
 realm=sip.linphone.org
