### ISSUE TITLE
Linphone4.2 uses OpenH264 resolution issues on Android4.4！

### ISSUE THREAD

**Issue by Roger1103** [BelledonneCommunications/linphone-android#1450]
Hi,
The resolution set using OpenH264 on linphone4.2 is 1280*720, but the logs show 800*600 resolution.And there's a lot of video lag and latency.Give me some advice on how to handle it。
Best wishes!

07-14 10:32:35.639 17881-18188/? E/视频点名: OpenH264 decoder: DecodeFrame2 failed: 0x22
07-14 10:32:35.649 171-217/? E/CallbackNotifier: ###########SMDT######src_width:800  src_height:600
07-14 10:32:35.689 17881-18188/? E/视频点名: OpenH264 decoder: DecodeFrame2 failed: 0x20
07-14 10:32:35.729 171-217/? E/CallbackNotifier: ###########SMDT######src_width:800  src_height:600
07-14 10:32:35.739 17881-18188/? E/视频点名: OpenH264 decoder: DecodeFrame2 failed: 0x20
07-14 10:32:35.789 17881-18188/? E/视频点名: OpenH264 decoder: DecodeFrame2 failed: 0x20
07-14 10:32:35.789 17881-18188/? W/视频点名: MSVideo MSTicker: We are late of 13274 miliseconds.
07-14 10:32:35.799 17881-18188/? I/视频点名: sequence inconsistency detected (diff=7)
07-14 10:32:35.799 17881-18188/? E/视频点名: receiving FU-A start while previous FU-A is not finished
07-14 10:32:35.809 171-217/? E/CallbackNotifier: ###########SMDT######src_width:800  src_height:600
07-14 10:32:35.849 17881-18188/? E/视频点名: OpenH264 decoder: DecodeFrame2 failed: 0x20
07-14 10:32:35.849 17881-18188/? I/视频点名: OpenH264 decoder: [OpenH264] this = 0x0x70761858, Warning:referencing pictures lost due frame gaps exist, prev_frame_num: 113, curr_frame_num: 115
[linphone1.log](https://github.com/BelledonneCommunications/linphone-android/files/6813230/linphone1.log)

**Comment by Viish** [comment]
Hi,
4.2 release is very old (latest is 4.5) and we no longer support it.
We also no longer support openH264 on mobiles, we now rely exclusively on MediaCodec API.
Cheers,
