### ISSUE TITLE
Trying to add new viewmodel but import is removed on build

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1451]
I am trying to add a new viewmodel to the `AdvancedSettingsViewModel`.

So I created my new model in `app/src/main/java/org/linphone/activities/main/viewmodels/FooViewModel.kt` and then added:

```
import org.linphone.activities.main.viewmodels.FooViewModel
```

right after `import org.linphone.activities.main.viewmodels.LogsUploadViewModel` in `app/src/main/java/org/linphone/activities/main/settings/viewmodels/AdvancedSettingsViewModel.kt`.

But when I execute `./gradlew buildDebug` the build complains of an unresolved reference to a function that is in `app/src/main/java/org/linphone/activities/main/viewmodels/FooViewModel.kt` in `app/src/main/java/org/linphone/activities/main/settings/viewmodels/AdvancedSettingsViewModel.kt`.

When I look at `app/src/main/java/org/linphone/activities/main/settings/viewmodels/AdvancedSettingsViewModel.kt` the above `import` line I added is removed.

Is there some kind of source file generation or manipulation going on there that I am not aware of?

**Comment by brianjmurrell** [comment]
Hrm.  NVM.  I need to look this implementation over again.  I might have a question or two once I have taken another look at how this works.  I hope you don't mind.

**Comment by Viish** [comment]
> Is there some kind of source file generation or manipulation going on there that I am not aware of?

No, there isn't.

>  I hope you don't mind.

I don't.
