### ISSUE TITLE
How to get RemoteAddr IP

### ISSUE THREAD

**Issue by zjhcode** [BelledonneCommunications/linphone-android#1453]
i can find RemoteAddr info in log like this:
RemoteAddr: IP=192.168.0.101 PORT=7078 SSRC=1005086675
I want to know how to get this info by use api

**Comment by Viish** [comment]
Using one of the following three should work:
- http://linphone.org/snapshots/docs/liblinphone/latest/java/org/linphone/core/CallParams.html#getCustomHeader-java.lang.String-
- http://linphone.org/snapshots/docs/liblinphone/latest/java/org/linphone/core/CallParams.html#getCustomSdpAttribute-java.lang.String-
- http://linphone.org/snapshots/docs/liblinphone/latest/java/org/linphone/core/CallParams.html#getCustomSdpMediaAttribute-org.linphone.core.StreamType-java.lang.String-
