### ISSUE TITLE
Conference Call issue : 3rd party user is placed on hold when merging

### ISSUE THREAD

**Issue by mnaji88** [BelledonneCommunications/linphone-android#1454]
Hello, 
Downloaded the latest version of Linphone on Android.
There's an issue with conference merge and I need your input. I tested it on multiple android devices and they all have the same issue. The issue is not present using the iPhone app.

To reproduce:
User A call user B. User B wants to conference user C. So B dial C.
At this point B and C are talking and A is automatically placed on hold. 

User B press the merge button. Once the merge button is pressed, User A and B can talk again while user C is placed now on hold. 

Let me know if you require more info.

**Comment by Viish** [comment]
Hi,
Yes please provide app logs showing the issue.

**Comment by Viish** [comment]
Closing issue without answer, will re-open when logs will be provided.
