### ISSUE TITLE
How to silent notification sound and vibration of external application during the ongoing VOIP call?

### ISSUE THREAD

**Issue by harsh2304** [BelledonneCommunications/linphone-android#1455]
I am developing a VOIP application on android platform using Linphone. I have a requirement to silent the external app notification sound and vibration when the VOIP call is in progress. If the notification is from my own app and any incoming GSM-P call then the notification sound should come from the earpiece along with the VOIP call. Vibration should not happen at all in any of the scenarios.

I am able to get all the notification audio from the earpiece along with the VOIP call. But I am not able to silent the external application notification sound. Also I am not able to stop the vibration in all scenarios. Can you please suggest any functionality of linphone to achieve above behaviour?

**Comment by Viish** [comment]
What version of our SDK are you using? Starting from 4.5, we acquire automatically the audio focus which should prevent other apps from making sounds during a VoIP call.
If that doesn't work maybe try to do the audio focus yourself with other params, but it won't be handled by us.
