### ISSUE TITLE
No audio (ICE failure?)

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1456]
In this [log](http://brian.interlinx.bc.ca/linphone-no-audio-ice-failure.txt) there are two incoming calls, neither of which had any audio.

When I clicked the call stats icon on the top right it said that ICE connectivity was _In progress_ and never moved beyond that.

I am using **80fa401d5 - (tag: 4.6.0-alpha)** with **SDK 5.0.1-pre.6+0253a33**.

**Comment by brianjmurrell** [comment]
Any ideas on this?

**Comment by brianjmurrell** [comment]
Re-opened as BelledonneCommunications/liblinphone#185.

**Comment by Viish** [comment]
I'm closing this one since you opened it on liblinphone repository.
