### ISSUE TITLE
Auto-recording voice calls.

### ISSUE THREAD

**Issue by sensed0ff** [BelledonneCommunications/linphone-android#1457]
I'm grateful for the toggle that starts a call recording, but is there a GUI option I'm overlooking or a file in the app directory that can be configured to start a recording as soon as a call is answered?

**Comment by Viish** [comment]
Done in 8303f2e0, will be part of 4.6 release.

**Comment by sensed0ff** [comment]
Whoa, wasn't expecting that to happen. Thanks a lot!

**Comment by Viish** [comment]
You're welcome :)
