### ISSUE TITLE
Closing Contact Editor (Sliding Pane) from MasterContactsFragment leaves blank screen

### ISSUE THREAD

**Issue by JonWatson** [BelledonneCommunications/linphone-android#1459]
On Master:

- open Contacts
- click Add Contact
- sliding pane with Contact Editor opens
- close pane with Back button or X and observe blank view, which I believe is org.linphone.activities.main.fragments.EmptyFragment

**Comment by Viish** [comment]
Fixed in 8e5a1911550f47dfe1defb00811bb1d3bfa00f99
