### ISSUE TITLE
Compiling with the AMR-WB codec

### ISSUE THREAD

**Issue by vrody** [BelledonneCommunications/linphone-android#146]
Hi, I'm having a problem with the build with the ./prepare.py --all-codecs & make
after compiling, I install bin/outputs/apk/linphone-android-debug.apk
but there is no codec AMR-WB and CODEC2, but there is a codec G729
what is the problem? why is the G729 in the assembly, and AMR-WB is not?

**Comment by anmol1991** [comment]
Try the below command to get AMR-WB support
./prepare.py -DENABLE_AMRWB=ON -DENABLE_AMRNB=ON -DENABLE_NON_FREE_CODECS=ON

**Comment by vrody** [comment]
I used these parameters, but I did not get the desired result, 
after compilation, there are no codecs in the client
