### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by hdatma** [BelledonneCommunications/linphone-android#1460]
Linphone's GUI sucks, and you know it. 

Can we discuss how a softphone gui should look like, agree on it, then make it happen?

This is a photo of Linphone vs ... something else that I really like.

![softphones](https://user-images.githubusercontent.com/1321219/127748221-14fa4f69-a515-4aa7-a9a0-93136d6f87f5.jpg)

**Comment by Viish** [comment]
> Linphone's GUI sucks

That's your opinion. It was designed by UI/UX professionals. 

> Can we discuss how a softphone gui should look like, agree on it, then make it happen?

No, we are quite satisfied with current UI and there is no plan to re-design it.

> This is a photo of Linphone vs ... something else that I really like.

You may like it but I don't. And from the feedback we have not many people dislike our UI.
