### ISSUE TITLE
External USB Camera is not mentioned in Camera selection list

### ISSUE THREAD

**Issue by gzozulin** [BelledonneCommunications/linphone-android#1463]
Hello Linphone Team,

I am currently trying to access **my external USB camera** from the Linphone Android app and it doesn't show up in the selection.

I can only choose a f**orward/back-facing camera or a static image.**
Is there a way to make a video call with Linphone via an external USB Camera?

P.S. I can access it via this project: https://github.com/saki4510t/UVCCamera, could you please explain the difference?

Thanks!
Regards, Greg.

**Comment by Viish** [comment]
Hi,

Can you attach logs from the app (from the start) please?

Thanks.

**Comment by Viish** [comment]
Closing issue without answer, will re-open when logs will be provided.
