### ISSUE TITLE
AudioRouteUtils.routeAudioToEarpiece() hangs the UI thread

### ISSUE THREAD

**Issue by JonWatson** [BelledonneCommunications/linphone-android#1464]
While during a call, changing from Speaker to Earpiece Audio hangs the UI thread for about a second

This happens during the `currentCall.outputAudioDevice = audioDevice` setting in routeAudioTo()

**Please complete the following information**
 - Device: Pixel 4
 - OS: Android 11
 - Latest 7db83a3ce
 - 5.1+

**Comment by Viish** [comment]
Please attach ANR tombstone and SDK logs showing the issue.

**Comment by Viish** [comment]
Closing issue without answer, will re-open when logs will be provided.
