### ISSUE TITLE
Background mode (notification) doesn't start automatically

### ISSUE THREAD

**Issue by aljebro** [BelledonneCommunications/linphone-android#1465]
When I open application, I don't need make any call and want only receive rarely calls.
If I swipe application - registration lost, if go home registration lost after same time and application will be removed from memory. But if I call any number (for example I call to "#" and see message "User hasn't be found") notification "This is required to receive call while in background" appears immediatly.

After I can go to advanced and switch off "background mode". Result: notfication removed. Switch on: ok, I see this notification. But this is doesn't work before first any call.

Bug: background mode works correctly only after first call. Diffrent behavior in settings: depends was first call or not.

 - Device: Realme 8, Realme 8 Pro, Nokia 7.2
 - OS: Android 11, 11, 10
 - Version of the App 4.5.1

**Comment by Viish** [comment]
Thanks for reporting the issue.
Fix is in 6a76513f on master branch and 204f21d8 on release/4.5 branch.
Cheers !
