### ISSUE TITLE
Can't get to enable x264 codec

### ISSUE THREAD

**Issue by Jbrownstone** [BelledonneCommunications/linphone-android#147]
Hello,

I can't seems to enable the x264 codec when i run prepare.py, it always is listed as a disabled feature whatever the arg i pass to it.

Here is my input : 
`./prepare.py -dv -ac -DENABLE_VIDEO=ON -DENABLE_NON_FREE_CODECS=ON  -DENABLE_DEBUG_LOGS=ON -DENABLE_X264=ON
`
And under -- Disabled features i always get :
 * X264 , H.264 video encoding support with the x264 library (require license).

Is there something i'm not getting?

Thanks in advance.
Pahl.

**Comment by bkuhls** [comment]
x264 was deactivated: https://github.com/BelledonneCommunications/linphone-android/commit/9b8ab3f0029058ffe9bf4e785ac5cf7c123b142d

**Comment by DatBewar** [comment]
Hello,
x264 is no more supported, please use OpenH264.

**Comment by Jbrownstone** [comment]
Alright, thanks for the replies.
