### ISSUE TITLE
The person from Contacts is not recognized on incoming call

### ISSUE THREAD

**Issue by bam80** [BelledonneCommunications/linphone-android#1471]
I have existing SIP account linked to real telephony (non Free SIP one).
I can see persons from my Android Address book in Linphone app normally, outgoing calls through the app works OK also.
But on incoming call, I can see only the number in a popup, of the form `<number>@multifon.ru`.
No real user name matching occurs.

I see no such problems in Blink SIP client, with the same account.

**Comment by Viish** [comment]
Please attach logs showing the issue.

**Comment by bam80** [comment]
I suppose you are asking the log capability within the app, will do.

**Comment by Viish** [comment]
Closing issue without answer, will re-open when logs will be provided.
