### ISSUE TITLE
keeps sending register request

### ISSUE THREAD

**Issue by manthanPatel-android** [BelledonneCommunications/linphone-android#1472]
hey there, we have observed that linphone android sdk send register request multiple times for the same endpoints even if its already  registered this creates lots of issue in to SIP server as number of request keeps on increasing automatically as we are calling the registration function only single time , is there anything which we can do to prevent this?

**Comment by Viish** [comment]
Please attach logs showing the issue.
Also make sure you don't create the "Account" or "ProxyConfig" object multiple times.

**Comment by Viish** [comment]
Closing issue without answer, will re-open when logs will be provided.

**Comment by alien999999999** [comment]
I believe these logs contain this issue: https://www.linphone.org:444//tmp/6131f46d9cb56_f259e8d54d2e14df8b88.gz ?

**Comment by Viish** [comment]
> I believe these logs contain this issue: https://www.linphone.org:444//tmp/6131f46d9cb56_f259e8d54d2e14df8b88.gz ?

In your case it's because the expire is set to 60 seconds, so every minute it will send a new REGISTER.

**Comment by alien999999999** [comment]
it might be, but i thought i saw multiple registers at the same time, because for some reason there were multiple contacts per extension on the same device... so, i thought it was related to this issue...
