### ISSUE TITLE
Feature request: Allow to silence ringing

### ISSUE THREAD

**Issue by mvorisek** [BelledonneCommunications/linphone-android#1477]
This is a feature request to allow silence ringing.

## a) by setting, eg. to not ring at all even if phone/gsm ringing tone is enabled

when voip calls are not wanted, this feature is currently missing, the only option now is to disconnect internet, log out or disable the whole app

## b) when call is received

this seems almost a bug, as ringing can not be silenced by any way (by home button nor volume down key)

**Comment by Viish** [comment]
Hi,

What version are you using? Can you attach logs?
If do not disturb mode is enabled it won't ring, and you can lower the ringing volume like you would do for the default gsm app.

Cheers,

**Comment by mvorisek** [comment]
> What version are you using?

the latest one from G Play

> If do not disturb mode is enabled it won't ring, and you can lower the ringing volume like you would do for the default gsm app.

that is true, but this will disable all ringing incl. gsm. This issue is about allowing to "in app disturb mode", eg. silence only the app calls, not the other one from gsm or other apps, but keep linphone active, eg. log missed calls.

> b) when call is received

please try, at least on my phone, I can silence standard gsm call, but the only way to silence linphone active income call is to turn of ringing completely. Standard volume down key to silence it is currently not supported.

**Comment by Viish** [comment]
Ok if you want a "silence mode" that is only for Linphone app indeed that doesn't exists yet.

**Comment by Viish** [comment]
With 4.6.0 release (currently in beta), if you enable TelecomManager mode (done automatically if permission is granted when app starts) you will be able to silence the ringing simply by pressing a volume key, like you do for GSM calls.

**Comment by mvorisek** [comment]
Thank you for an update. Option to silence the app ringing completely, eg. silence all ringing/vibration of Linphone app but keep ringing for standard GSM active, is still a strong usecase.

**Comment by Viish** [comment]
That is still isn't planned but I'll leave this issue open with enhancement tag.

**Comment by derz00** [comment]
I'd like to bump this issue. Please add the enhancement to remove or customize the ringer. If you think this is something a complete rookie could do, give me a few pointers on getting started. I code some but haven't worked on any mobile apps before. 

Linphone works excellent for me, and this one enhancement is almost the only issue I have against it.

**Comment by Viish** [comment]
Hi @derz00,

6.0 release to come will let you choose your ringtone through Android's notification settings. 

Cheers,

**Comment by Viish** [comment]
6.0.0 alpha is now available in master branch.
