### ISSUE TITLE
Linphone crashes on use of backfacingcamera as video source

### ISSUE THREAD

**Issue by afcady** [BelledonneCommunications/linphone-android#1479]
**Describe the bug**

On some of my phones, setting Camera to BackFacingCamera causes linphone to crash when it auto-answers an incoming video call.

Restarting after the crash, the Camera setting is back to its default FrontFacingCamera, and it doesn't crash.

**Comment by Viish** [comment]
Please attach app's debug logs from start to the crash.

**Comment by afcady** [comment]
OK.  I emailed them to you directly.

**Comment by Viish** [comment]
Can you attach the crash stack trace please?

**Comment by Viish** [comment]
Closing this issue as no logs were provided.
