### ISSUE TITLE
i got this erro UnsatisfiedLinkError

### ISSUE THREAD

**Issue by rasik1010** [BelledonneCommunications/linphone-android#148]
java.lang.UnsatisfiedLinkError: Couldn't load gnustl_shared from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.linphone-2.apk"],nativeLibraryDirectories=[/data/app-lib/org.linphone-2, /vendor/lib, /system/lib]]]: findLibrary returned null

i am having troble with this error please help me if anyone can do , thanks

**Comment by AlekseyMak** [comment]
Make sure you really have your libraries in the apk. You can explore your apk right in the Android Studio(Build-> Analyze APK -> check the lib folder)

Seems there are no binary libraries there, did you compile all the *.so binaries?

**Comment by rasik1010** [comment]
thanks for reply , yes there are is libs folder, now what i did , i run in macbook and there works fine.
