### ISSUE TITLE
Export Recordings

### ISSUE THREAD

**Issue by hmnd** [BelledonneCommunications/linphone-android#1480]
I would like to be able to export the audio files from recordings, instead of them being locked into the app.

**Comment by ralienpp** [comment]
Same thing for me, I put in a substantial amount of energy to find a way to get the files out - but the UI provided no option. Various queries on the Internet yielded no results either. I am relieved to see this issue on Github, now I know that the thing I was looking for does not exist yet.

Until this feature becomes available, is there a way to extract the files by browsing the file system manually? I looked around my phone, but found nothing promising.

**Comment by hmnd** [comment]
@ralienpp I don't believe there's a way to do so manually, unless your phone is rooted :(

**Comment by hasanr68** [comment]
Oh wow.. we are looking for some way to upload the files to a server (right after the call is finished) and delete the file once done.

**Comment by Viish** [comment]
Done in master branch (61454f59230f24a970cde4270756a9b2e5af706f), will be part of next major release.
