### ISSUE TITLE
Updating SDK 3.x to 4.x

### ISSUE THREAD

**Issue by gallynero** [BelledonneCommunications/linphone-android#1482]
I have an Android app that is developed using the SDK prior to version 4.x (I don't know the specific version but the approximate date is 2017-5-15).

So far it has worked correctly, updating a few things about permissions and other things as new versions of Android have been released.

Testing with Android 12 beta, I found that the video does not work, giving an error in the mediastreamer buffer. So I start to update the SDK to version 4.5.26 to continue using the old java wrapper.

I compile the SDK without problem and I rename the changes of the classes that have been produced, but the class org.linphone.core.LinphoneCoreListenerBase doesn't exist in the new SDK and I can't find a replacement.

Is there a replacement for this class?

Is there a guide or procedure to follow to update the SDK?

Thank you very much and best regards.

**Comment by Viish** [comment]
I tried the following, it built just fine:
```
import android.os.Bundle
import android.util.Log
import androidx.appcompat.app.AppCompatActivity
import org.linphone.core.LinphoneCore
import org.linphone.core.LinphoneCoreFactory
import org.linphone.core.LinphoneCoreListenerBase

class HelloWorldActivity: AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        val factory = LinphoneCoreFactory.instance()
        val core = factory.createLinphoneCore(object: LinphoneCoreListenerBase() {
            override fun globalState(
                lc: LinphoneCore?,
                state: LinphoneCore.GlobalState?,
                message: String?
            ) {
                Log.i("Test", "Test")
            }
        }, this)
    }
}
```
With the following in app/build.gradle:
```
repositories {
    maven {
        url "https://linphone.org/maven_repository/"
    }
}

dependencies {
    implementation 'org.linphone.legacy:linphone-sdk-android:4.5.26'
}
```
