### ISSUE TITLE
Fails to find update

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1484]
Using linphone 80fa401d5 (tag: 4.6.0-alpha) with SDK 5.0.10-pre.5+4524dd5 linphone-android finds and fetches the `RELEASE` URL but fails to prompt the user to update to the newer release.

Here's the [log](http://brian.interlinx.bc.ca/linphone-fails-to-find-update.txt).

**Comment by Viish** [comment]
I'm not sure I understand but yes we always tag when we make an official release, even if it only contains a SDK update.
