### ISSUE TITLE
[Legacy wrapper] LinphoneCoreListener's callState is not triggered

### ISSUE THREAD

**Issue by gallynero** [BelledonneCommunications/linphone-android#1485]
The LinphoneCoreListener's callState method is not triggered by a change in the call, it only run when the call ends.

The same implementation is being used as in this [code](https://github.com/BelledonneCommunications/linphone-android/blob/e645ef04565b5358d03e6cead4a64ddc5399de52/src/android/org/linphone/CallActivity.java#L170) with SDK 4.5.26 and the old wrapper.

Now i am debug this [code](https://github.com/BelledonneCommunications/liblinphone/blob/4f003568044ac6185dc187027e6345a580c82b48/src/call/call.cpp#L383) but i am a noob on this.

Any tip?

Regards,

**Comment by gallynero** [comment]
I found the problem the call states enum of [C](https://github.com/BelledonneCommunications/liblinphone/blob/4f003568044ac6185dc187027e6345a580c82b48/include/linphone/enums/call-enums.h#L32) and the [java](https://github.com/BelledonneCommunications/liblinphone/blob/4f003568044ac6185dc187027e6345a580c82b48/java/common/org/linphone/core/LinphoneCall.java#L64) wrapper are different.

Regards.

**Comment by Viish** [comment]
I'm glad you found the issue.
And now you understand why we abandoned the previous Java wrapper (that was manually created) for one that is automatically generated.
