### ISSUE TITLE
From accounts settings Not able to delete account in android 

### ISSUE THREAD

**Issue by anujvats111** [BelledonneCommunications/linphone-android#1488]
Hello Guys

I am using linphone java version. But I am getting an major issue. Actually I am not able delete registered account from the settings. It's showing deleted but after login with new sip details calls still are coming on last deleted account. I have tried many ways like unregister proxy, core but result still same. Is it possible anyone can help me to fix it out please ?
Thanks 
Anuj Sharma.

**Comment by Viish** [comment]
Hi,

Please attach logs showing the issue.

Cheers,

**Comment by Viish** [comment]
Closing this issue as no logs were provided.
