### ISSUE TITLE
Not getting audio coded G729

### ISSUE THREAD

**Issue by RaviChavada** [BelledonneCommunications/linphone-android#1492]
hii,

I am not able to find audio codec G729, is there any specific way to enable or disabled it, I have linphone android SDK version 5.0+

**Comment by Viish** [comment]
Yes when you build the SDK you need to add -DENABLE_G729=ON to the cmake command line.

**Comment by RaviChavada** [comment]
is there any example or demo available in the repository?

**Comment by Viish** [comment]
No as the G729 codec isn't open-source.

**Comment by RaviChavada** [comment]
so, how can i add it in cmake file, because in GitLab repo there is no camke file, is there any other setup?

**Comment by Viish** [comment]
It's not in the app, it's in the SDK: https://github.com/BelledonneCommunications/linphone-sdk

**Comment by RaviChavada** [comment]
so, I can add linphone SDK as a module inside the project and as well as Gradle file?

**Comment by Viish** [comment]
Once the SDK will be built, you'll have to edit [this file](https://github.com/BelledonneCommunications/linphone-android/blob/master/gradle.properties#L22) and set the LinphoneSdkBuildDir parameter to the SDK build dir path, for me it's `/home/sberfini/Work/linphone-sdk/build/` for example

**Comment by RaviChavada** [comment]
I am doing something like this
LinphoneSdkBuildDir=/home/ravi/LinphoneSDK -DENABLE_G729=ON

should I go in a proper way?

**Comment by Viish** [comment]
Clone https://github.com/BelledonneCommunications/linphone-sdk somewhere, for example ~/linphone-sdk and follow README instructions to build it for Android (with the `-DENABLE_G729=ON` at the cmake step).
Then edit your gradle file so `LinphoneSdkBuildDir=~/linphone-sdk/build` and finally build app in Android Studio.

And if you still fail please read carefully all README files for all project, everything is explained.

**Comment by RaviChavada** [comment]
Hey, can you please help me to solve this error

```
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find SpanDSP (missing: SPANDSP_INCLUDE_DIRS SPANDSP_LIBRARIES
  HAVE_SPANDSP_H)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSpanDSP.cmake:43 (find_package_handle_standard_args)
  CMakeLists.txt:186 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/ravi/LinphoneSDK/demo/build/WORK/android-arm64/Build/ms2/CMakeFiles/CMakeOutput.log".
make[5]: *** [CMakeFiles/EP_ms2.dir/build.make:121: /home/ravi/LinphoneSDK/demo/build/WORK/android-arm64/Stamp/EP_ms2/EP_ms2-configure] Error 1
make[4]: *** [CMakeFiles/Makefile2:1070: CMakeFiles/EP_ms2.dir/all] Error 2
make[3]: *** [Makefile:84: all] Error 2
make[2]: *** [CMakeFiles/android-arm64.dir/build.make:114: android-arm64-prefix/src/android-arm64-stamp/android-arm64-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:196: CMakeFiles/android-arm64.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by RaviChavada** [comment]
Hey,
i am build linphone SDK and add its path in Gradle.properties file **LinphoneSdkBuildDir=/home/ravi/LinphoneSDK/build/**, after build and rund the project.

cmake .. -DLINPHONESDK_PLATFORM:STRING=Android -DLINPHONESDK_ANDROID_ARCHS="arm64, armv7, x86_64, x86" -DENABLE_G729=YES -DENABLE_G729B_CNG=YES -DENABLE_VCARD=OFF -DENABLE_ILBC=ON -DENABLE_SILK=OFF -DENABLE_ISAC=OFF -DENABLE_MKV=ON -DENABLE_GSM=ON -DENABLE_DOC=OFF -DENABLE_UNIT_TESTS=OFF -DENABLE_LIME=OFF -DENABLE_GPL_THIRD_PARTIES=ON -DENABLE_NON_FREE_CODECS=ON

so, my issue is,  I am not able to get vp8 video codec, is there any other way to enable it ?

**Comment by Viish** [comment]
Hi,

Use `-DENABLE_VPX=ON`, but it should be on by default.
