### ISSUE TITLE
linphone android with asterisk keeps getting Unreachable/Reachable in asterisk logs, missing calls

### ISSUE THREAD

**Issue by alien999999999** [BelledonneCommunications/linphone-android#1495]
debug logs:

https://www.linphone.org:444//tmp/6131f46d9cb56_f259e8d54d2e14df8b88.gz

I'm not certain it's linphone or asterisk, or just something wrong with this phone, but i'm stuck. I have already twiddled with settings both on linphone and asterisk in order to get this reduced, but i can't get it to work well...

Basically, sometimes, this phone is like a couple of minutes unreachable and so it misses calls.

I've also tested this with just doing a ping -f to the android to see if it was the wifi or whatever, but i have no dropped packets at all, even during the unreachable state.

Also, less importantly, i think i also have #1472 .

Any comment/advice on this is greatly appreciated.

**Comment by alien999999999** [comment]
i think i also have #1472 ?

**Comment by Viish** [comment]
Hi,

It's probably because your expire is way too short.
On Android, after a while, app will be put in DOZE mode which prevents the app to reach the network and thus keep the REGISTER alive.
You should enable the background mode setting to try to prevent that but the best solution is to use longer expire value along with push notifications.

Cheers,

**Comment by Viish** [comment]
> So, how does push notifications work if the app cannot reach the network

Push notifications are handled by the OS, they aren't affected by DOZE mode and they even make the app exit this mode when one is received.

> I must say this is kind of weird, some older androids are not have a problem with this DOZE mode...

DOZE mode was introduced in Android 8.

**Comment by Viish** [comment]
> I assume there is something extra needed in the asterisk to do push notifications, though?

I don't know if asterisk supports pushes or not, but you can install a flexisip as push gateway: https://www.linphone.org/technical-corner/flexisip

**Comment by alien999999999** [comment]
I see, so longer registrations, and do push notification if a call is coming in, i'm gonna read up on this flexisip and see how this works, thanks.

**Comment by Viish** [comment]
I also recommend you read this page about doze mode: https://developer.android.com/training/monitoring-device-state/doze-standby?hl=en

**Comment by alien999999999** [comment]
thanks, i looked at the flexisip code and i noticed it all went through "firebase". It's not clear to me how this works:

is it that we can freely use the firebase servers, and they will go to google servers with their app code and the google servers will then push to the device and the device wakes up the app in question... 

or, is it that the firebase servers will push the device ip adres directly without going through the google servers, thus not needing a google api key, and the linphone app has some code that listens to these alternative push notifications not from google servers?

tbh: it would be way more efficient and entirely possible if android base would monitoring :5060 for INVITEs and wake up the app that listens on :5060 ...

what if the google servers have a problem? we're not getting called? this seems to introduce an unnecessary single point of failure imho...

unless i'm not understanding this...

also, does this mean, to get this working, we need either a firebase license or a google api key or something?

**Comment by alien999999999** [comment]
huh, the DOZE does state that "enterprise VOIP apps" are allowed to be exempt... but what constitues an "enterprise" void app???
