### ISSUE TITLE
Linphone offline when phone goes into (deep) idle mode (Android Doze)

### ISSUE THREAD

**Issue by not1337** [BelledonneCommunications/linphone-android#15]
Android "Doze Mode" causes disconnectivity for Linphone when it kicks in, even though Linphone is whitelisted. For Android 6 this can be remedied by "adb dumpsys deviceidle disable" and for Android 7 with "adb dumpsys deviceidle disable deep", but this requires a debug connection after every phone reboot which is not really practical.
I don't know if UDP keepalives would solve this as for me TLS/SRTP is a requirement to be able to connect to my server.

Please see the following for the Android side:
https://developer.android.com/training/monitoring-device-state/doze-standby.html

As a hint and not verified by me, Conversations may already have a fix for their code as hinted in:
https://github.com/siacs/Conversations/issues/1624

**Comment by DatBewar** [comment]
Hello,

Normally if a push notification is received on Linphone, it's enabling network even if device was in 'Doze Mode'. So if your server has push notification, 'Doze Mode' will not be a problem. But it don't had Push, 'Doze Mode' is a problem.

Maybe we can add a way to disable 'Doze Mode' for Linphone.

Best regards

**Comment by not1337** [comment]
Would be nice if you could add a a 'Push-free' way.

The reasoning here is that I just checked google play services connectivity when wlan connected and behind a proxy (you can do this by dialling "*#*#426#*#*" on the device). The result is that the configured proxy settings (PAC url) are not respected and the device tries to connect directly (do a tcpdump for ports 5228, 5229 and 5230).

Thus no FCM/GCM connectivity while on WLAN behind a proxy and thus no 'Push' possibility even if the server would support it.

**Comment by ventrciousn** [comment]
>nice if you could add a a 'Push-free' way.

yes +

> The reasoning here is

I remove google apps. I am not a firebase fan either.

**Comment by wkg** [comment]
why this close? This do not fixed....

07-20 19:31:01.649 15731 15731 I Linphone: [Platform Helper] Doze mode enabled: true
07-20 19:31:01.649 15731 15731 I Linphone: [Platform Helper] Device idle mode: true
07-20 19:31:01.649 15731 15731 I Linphone: [Platform Helper] Device in idle mode: shutting down network
07-20 19:31:01.653 15731 15731 I Linphone: SIP network reachability state is now [DOWN]
07-20 19:31:01.655 15731 15731 I Linphone: Refresher [0x7d07fd8e40] stopped.
07-20 19:31:01.655 15731 15731 I Linphone: Destroying op [0x7d1c15ac00] of type [SalOpRegister]
07-20 19:31:01.655 15731 15731 I Linphone: Refresher [0x7d07fd8e40] stopped.
07-20 19:31:01.655 15731 15731 I Linphone: Transaction [0x7d07aa1240] deleted
07-20 19:31:01.656 15731 15731 I Linphone: Transaction [0x7d07fd9080] deleted
07-20 19:31:01.656 15731 15731 I Linphone: Proxy config [0x7d1c06ee00] for identity [sip:***@***] moving from state [LinphoneRegistrationOk] to [LinphoneRegistrationNone] on core [0x7d1c0dd800]
07-20 19:31:01.657 15731 15731 I Linphone: [Manager] New registration state [None]
07-20 19:31:01.657 15731 15731 I Linphone: Linphone core [0x7d1c0dd800] notified [registration_state_changed]
07-20 19:31:01.657 15731 15731 I Linphone: Reseting transports
07-20 19:31:01.657 15731 15731 I Linphone: Listening point destroying [1] channels
07-20 19:31:01.657 15731 15731 I Linphone: channel 0x7d07cafec0: state DISCONNECTED
07-20 19:31:01.657 15731 15731 I Linphone: Channel [0x7d07cafec0] destroyed
07-20 19:31:01.658 15731 15731 I Linphone: Media network reachability state is now [DOWN]
07-20 19:31:01.658 15731 15731 I Linphone: Linphone core [0x7d1c0dd800] notified [network_reachable]
