### ISSUE TITLE
"Operation in pgoress, please wait" shown for a long time

### ISSUE THREAD

**Issue by koppor** [BelledonneCommunications/linphone-android#1505]
**Describe the bug**

Want to register at sipgate. I try to follow the steps at https://app.sipgatebasic.de/konfiguration/207/android-softphones-samsung-huawei-google-lg-linphone. After typing in the login data and submit, following screen appears - and stays:

![grafik](https://user-images.githubusercontent.com/1366654/133497809-93e069fe-ff71-48be-885d-22d524e9f26d.png)

**Please complete the following information**
 - Device: SHIFT6m
 - OS: 8.0.0
 - Version of the App 4.5.2
 - Version of the SDK 5.0.10

**Comment by koppor** [comment]
After restarting the app, I could change the settings.

It seems that the local WLAN does not support SIP routing.

Thus, more a usability issue.

**Comment by Viish** [comment]
UDP protocol can lead to lost packets quite easily.
If you can use TCP or even better TLS.
