### ISSUE TITLE
Notification issue

### ISSUE THREAD

**Issue by RaviChavada** [BelledonneCommunications/linphone-android#1508]
Hey

I have an oppo device which has android 6 and color os 3, now I install the latest version of linphone app and configure it. now I kill the app, so I can not show background service in the status bar. i  perform all the steps of battery optimization or Autostart and still, I have faced the same issue. when I killed the app user is deregistered and not came to any call or any push notification. 
do you have any idea how to resolved it?

**Comment by Viish** [comment]
>  when I killed the app user is deregistered

That's your issue. If user is un-registered it can't receive any push notification.

**Comment by RaviChavada** [comment]
but it will specific in oppo device

**Comment by Viish** [comment]
Then attach logs from the device so I can take a look.

**Comment by RaviChavada** [comment]
we are sending push notification in oppo device and and we will get :
W/GCM: broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10000000 pkg=*** (has extras) }
any idea about this?

**Comment by Viish** [comment]
Please attach full logs

**Comment by Viish** [comment]
Also, read the following: https://stackoverflow.com/questions/39480931/error-broadcast-intent-callback-result-cancelled-forintent-act-com-google-and

**Comment by JonWatson** [comment]
@Viish Can you please briefly explain how the Push Notifications are used to "wake up" the app so it can receive a call via a Core callback like onCallStateChanged()?  If the app process is killed, and PN are not going to be received by the Core FirebaseMessaging class, how will Core wake up to receive the call?  

Thank you for your time.

**Comment by Viish** [comment]
When a push is received, Android will dispatch a broadcast. Because the app is killed, it will first create the Application object before calling the receiver.
And because we create and start a Core in our custom LinphoneApplication object when the received is called we do have a Core with callbacks ready to handle the event that generated the push (the push itself is no longer useful).

**Comment by JonWatson** [comment]
@Viish Thank you for that information.  That helps me a lot on a related issue

**Comment by JonWatson** [comment]
@Viish One more related question. From what I see, the `FirebaseMessaging` class does not get its `onMessageReceived` callback invoked if the app is "dead" (process killed or app is in the background).  This is also referenced in the StackOverflow link you posted above.  That seems to be what I see on Android 12. 

So in my tests when the process is killed, the push isn't received by `FirebaseMessaging` and thus the CoreBroadcastReceiver is never sent a Broadcast to wake up and ensure that core exists.

**Comment by JonWatson** [comment]
@Viish After digging into this more, it seems the `message` Push Notifications do _not_ wake up the app, but the `call`(data) Push Notifications do.  So the app does seem to wake up properly for calls.
