### ISSUE TITLE
stun sever 

### ISSUE THREAD

**Issue by Gari77** [BelledonneCommunications/linphone-android#1515]
stun-server is not saved and therefore ice does not work

 - Device: [e.g. Samsung Galaxy S210 Ultra]
 - OS: [e.g. Android 11]
 - Version of the App [e.g. 4.6.0]
 - Version of the SDK [e.g 5.1.0-alpha]

**Comment by Viish** [comment]
Are you sure you correctly clicked on the checkmark at the right of the field?
I just tried and it works fine on my device.

**Comment by Gari77** [comment]
> Are you sure you correctly clicked on the checkmark at the right of the field? I just tried and it works fine on my device.

yes , absolutely sure. On galaxy z-flip everything is exactly the same.

The problem is only with a clean install. If you upgrade from a previous version, then stun server value remains from the previous version.

**Comment by Viish** [comment]
> The problem is only with a clean install.

That's interesting. I'll try to reproduce this way and let you know.

**Comment by Viish** [comment]
I don't reproduce it with latest 4.6.0-beta version, so I'm closing.
