### ISSUE TITLE
Starting video call without without updating current audio call

### ISSUE THREAD

**Issue by rexxar786** [BelledonneCommunications/linphone-android#1516]
Hi @Viish ,
I am using your liblinphone library to create custom application.I want to initiate a video call and accept an incoming video request.
I have created a custom sip invite but I am not able to accept incoming video request unless I have enabled the accept video request from settings.
Also while sending sip invite request I have added `params.enableVideo(true)` still I need to enable initiate video call toggle button.
So my question to you is there any other particular api to start and accept incoming video invite.
Thanks in advance for your valuable suggestions 🙂

**Comment by Viish** [comment]
Hi,

Check outgoing call tutorial, we show how to enable video: https://gitlab.linphone.org/BC/public/tutorials/-/blob/master/android/kotlin/4-OutgoingCall

Cheers,
