### ISSUE TITLE
After Build Linphone SDK not able to get VP8 video codec

### ISSUE THREAD

**Issue by RaviChavada** [BelledonneCommunications/linphone-android#1517]
Hey,
I am building linphone SDK and add its path in Gradle.properties file: **LinphoneSdkBuildDir=/home/ravi/LinphoneSDK/build/**, after build and rund the project.

cmake .. -DLINPHONESDK_PLATFORM:STRING=Android -DLINPHONESDK_ANDROID_ARCHS="arm64, armv7, x86_64, x86" -DENABLE_G729=YES -DENABLE_G729B_CNG=YES -DENABLE_VCARD=OFF -DENABLE_ILBC=ON -DENABLE_SILK=OFF -DENABLE_ISAC=OFF -DENABLE_MKV=ON -DENABLE_GSM=ON -DENABLE_DOC=OFF -DENABLE_UNIT_TESTS=OFF -DENABLE_LIME=OFF -DENABLE_GPL_THIRD_PARTIES=ON -DENABLE_NON_FREE_CODECS=ON

so, my issue is, I am not able to get the vp8 video codec, is there any other way to enable it?

**Comment by Viish** [comment]
Hi,

Use -DENABLE_VPX=ON, but it should be on by default.

**Comment by RaviChavada** [comment]
i have found Error in VPX

Performing configure step for 'EP_vpx'

disabling shared
  enabling error_concealment
  enabling realtime_only
  enabling vp8
  disabling vp9
  disabling install_docs
  disabling debug_libs
  disabling examples
  disabling unit_tests
  disabling tools
Configuring for target 'x86-android-gcc'
  enabling x86
gcc not found as x86-linux-android-gcc
gcc not found as i686-linux-android-gcc
clang not found as x86-linux-android21-clang
Using clang at /home/ravi/Android/Sdk/ndk/22.0.7026061//toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android-clang
ar, as, strip and nm seems to have the same toolchain path than clang
ld seems to have a different path than other tools: /home/ravi/Android/Sdk/ndk/22.0.7026061//toolchains/llvm/prebuilt/linux-x86_64/bin/ld
  enabling runtime_cpu_detect
  enabling mmx
  enabling sse
  enabling sse2
  enabling sse3
  enabling ssse3
  enabling sse4_1
  enabling avx
  enabling avx2
  enabling avx512
  using yasm
  enabling postproc
  enabling webm_io
  enabling libyuv
Toolchain is unable to link executables

Configuration failed. This could reflect a misconfiguration of your
toolchains, improper options selected, or another problem. If you
don't see any useful error messages above, the next step is to look
at the configure error log file (config.log) to determine what
configure was trying to do when it died.
make[5]: *** [CMakeFiles/EP_vpx.dir/build.make:108: /home/ravi/LinphoneSDK/build/WORK/android-x86/Stamp/EP_vpx/EP_vpx-configure] Error 1
make[4]: *** [CMakeFiles/Makefile2:302: CMakeFiles/EP_vpx.dir/all] Error 2
make[3]: *** [Makefile:84: all] Error 2
make[2]: *** [CMakeFiles/android-x86.dir/build.make:114: android-x86-prefix/src/android-x86-stamp/android-x86-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:145: CMakeFiles/android-x86.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

is there anything missing?

**Comment by Viish** [comment]
NDK 22 should be working, but you can try with NDK 20 or 21e, we know these ones works.

**Comment by RaviChavada** [comment]
I am trying with NDK 20 and it's built perfectly and get all the codec
thanks for your support.
