### ISSUE TITLE
Black Screen on Incoming Call

### ISSUE THREAD

**Issue by databoy2k** [BelledonneCommunications/linphone-android#1532]
**Describe the bug**
When a call comes in, the phone turns off Always On Display and just shows a black screen. It doesn't turn on, show a prompt, or anything. I am able to accept the call by manually turning on the screen, going into the notifications shade, and clicking "accept" on the incoming call.

Note that I have Linphone installed as part of a "work profile". I'm not sure if this is related to the bug.

**If the issue is about the SDK (build, issue, etc...) open the ticket in the [linphone-sdk](https://github.com/BelledonneCommunications/linphone-sdk) repository or one of it's submodules!**

**To Reproduce**
1. Receive Call with screen off
2. Note black screen

**Expected behavior**
I thought that the screen would turn on and show a dialog box to accept or reject the call

**Please complete the following information**
 - Device: Google Pixel 3
 - OS: Android 12
 - Version of the App: 4.5.4
 - Version of the SDK: 5.0.38

**SDK logs**
https://www.linphone.org:444//tmp/61732f0a4d435_903693dd578d47cb3173.gz
(go to end; top bits are another issue altogether)

**Adb logcat logs**
N/A

**Screenshots**
N/A

**Additional context**

**Comment by databoy2k** [comment]
Hi @Viish. I'll install it on both sides and see if that works.

My problems arise when the work apps are unlocked. All other work apps are able to provide notifications (gmail, chat, WO Mic) at the time that Linphone can't.

**Comment by mvdhorst** [comment]
@Viish possibly solution, at least it worked for us, is:
In the AndroidManifest.xml set showWhenLocked and turnScreenOn to true for the IncomingCallActivity :
`        <activity android:name=".activities.call.IncomingCallActivity"
            android:launchMode="singleTask"
            android:showWhenLocked="true"
            android:turnScreenOn="true"
            android:noHistory="true" />`

**Comment by mvdhorst** [comment]
In my case the X4 A9, X4s A10 and the Myco 3 A9
Android 11 devices doesn't seem to have this issue

**Comment by Viish** [comment]
@databoy2k Can you test with a 4.7.0-alpha version and tell me if you still have the issue please?
You can find an APK here: https://download.linphone.org/snapshots/android/

**Comment by Viish** [comment]
Old issue that should be fixed now, closing it.

**Comment by juliancorrea** [comment]
Which commit has the fix?
