### ISSUE TITLE
How To Initiate A Call Using A Single Button

### ISSUE THREAD

**Issue by shdaro** [BelledonneCommunications/linphone-android#1535]
Note: This is neither a bug reporting nor an issue. 

### Description:

I am developing a VOIP android app based on linphone-android. The app should initiate a call to a specific phone number just using a single button like the hospital's panic button. On the dialer screen, there should have only a bigger button. If anyone press the button it should start a call to a specific number. 

### What I did so far:
  
First I removed all the numpad icons except numpad_9 from the dialer screen. Then, I created a speed dial to a specific number assigning 9. Then I changed the icon from numpad_9 to a help button (refer to the screenshot below). Now if someone presses the help button and then presses the dial button then it initiates a call. This way needs to press 2 buttons. But I want to dial using only one button. just press the help button goes straight to the number.

###  Version of the App: 4.3.0

How can use only one button to call a number? Please help! I am a beginner in android development.

Thanks in advance.

![sos_screenshoot](https://user-images.githubusercontent.com/36816015/139198403-cefd24e0-be0d-4981-8bee-ea2103c0c851.png)

**Comment by Viish** [comment]
Sorry but I'm closing this as it isn't an app related issue.
