### ISSUE TITLE
Call Transfer

### ISSUE THREAD

**Issue by judklaus** [BelledonneCommunications/linphone-android#1537]
Hi @Viish, Linphone transfers calls directly. I try to first pause the current call and then transfer it however the application crashes. Isn't it possible to first pause and then transfer when the transfer button on DialerActivity is clicked?

Thanks & Regards.

**Comment by Viish** [comment]
Hi, It doesn't crashes on my device.
Please attach logs & stack trace of the crash.

**Comment by judklaus** [comment]
I will as soon as I connect to my pc. Maybe I do it wrong, below is the onClick method in DialerActivity.java. Is it the right way to do it?

mTransferCall.setOnClickListener(
        new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (LinphoneManager.getCore().getCurrentCall() == null
                        || mAddress.getText().toString() == null
                        || mAddress.getText().toString().isEmpty()) {
                    return;
                }

                LinphoneManager.getCore().getCurrentCall().pause();
    
                LinphoneManager.getCore()
                        .getCurrentCall()
                        .transfer(mAddress.getText().toString());
            }
        });

**Comment by judklaus** [comment]
Hi @Viish,

I will as soon as I connect to my pc. Maybe I do it wrong, below is the onClick method in DialerActivity.java. Is it the right way to do it?

mTransferCall.setOnClickListener(
        new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (LinphoneManager.getCore().getCurrentCall() == null
                        || mAddress.getText().toString() == null
                        || mAddress.getText().toString().isEmpty()) {
                    return;
                }

                LinphoneManager.getCore().getCurrentCall().pause();
               
                LinphoneManager.getCore()
                        .getCurrentCall()
                        .transfer(mAddress.getText().toString());

                mAddress.setText("");
            }
        });

**Comment by Viish** [comment]
Yes you do it wrong.
As soon as you call `LinphoneManager.getCore().getCurrentCall().pause()` `LinphoneManager.getCore().getCurrentCall()` will then return null and thus your code will crash on a null pointer exception.

**Comment by judklaus** [comment]
Hi, @Viish now I tried to store the currentCall in a Call object and pause + transfer it. It is still not successful. Does Linphone support the transfer of a paused call?
