### ISSUE TITLE
Option to only connect when on certain wifi SSIDs

### ISSUE THREAD

**Issue by Fregf** [BelledonneCommunications/linphone-android#1538]
There is the option to connect only when on wifi. I would like to have an addition option to select on which wifi networks Linphone should connect to the SIP server.

**Comment by Viish** [comment]
I'll leave this issue opened with enhancement flag but we will probably never do it as it would require a location permission and the use-case is for our clients currently nil.

**Comment by Fregf** [comment]
An alternative would be to have Locale/Tasker integration, such as this plug-in for csipsimple: https://github.com/luklanis/csipsimple-plugin

**Comment by Viish** [comment]
I'm closing this issue as it won't be done.
