### ISSUE TITLE
Call Transfer #1537

### ISSUE THREAD

**Issue by judklaus** [BelledonneCommunications/linphone-android#1539]
Hi, @Viish related to the closed issue #1537  now I tried to store the currentCall in a Call object and pause + transfer it. It is still not successful. Does Linphone support the transfer of a paused call?

**Comment by Viish** [comment]
What version of the SDK are you using? We fixed an issue related to that in 5.0.44.

**Comment by judklaus** [comment]
I'm using the master SDK code @Viish. Am I missing something in the code?

Call currentCall = KarelManager.getCore().getCurrentCall();
currentCall.pause();
currentCall.transfer(mAddress.getText().toString());

**Comment by judklaus** [comment]
I'm using the master SDK code @Viish. Am I missing something in the code?

Call currentCall = LinphoneManager.getCore().getCurrentCall();
currentCall.pause();
currentCall.transfer(mAddress.getText().toString());

**Comment by Viish** [comment]
It seems fix wasn't made on master branch yet, hence the issue.

**Comment by judklaus** [comment]
@Viish  can you please write the commit number for this issue? Also, are there any issues with my code above?

**Comment by Viish** [comment]
Commit id is c18d3039213bd251dce31c4403ea10240d13f944.
Regarding your code I don't know, we don't transfer paused calls. Also you code might not be paused if you're not waiting for the Paused call state in listener.
