### ISSUE TITLE
Sometimes after a reboot Linphone looses all Settings

### ISSUE THREAD

**Issue by yennor** [BelledonneCommunications/linphone-android#1542]
**Describe the bug**
Sometimes (not always) when I need to reboot the device (Mostly just because I run out of battery. But once it happened when I manually rebooted), Linphone looses all settings, also the account data. When starting it, it just looks like after the first start after the application installation (Setup wizard is shown). So far I haven't been able to reproduce under what condition it looses the settings. A look into logcat also didn't show me anything obvious. While the phone is on, Linphone never looses the settings. Also not when I quit the application (Through the task manager or how ever you call that on android ;-)).
What infos would you need to debug it?
Linphone is the only application on my phone with that problem. I've also got other applications installed which automatically start after a reboot. So I guess it is a problem with linphone and not with my phone. I never had the problem before the 4.5.x version. But if I'm not completely wrong I've switched the phone when changing to 4.5.x ..
I've tried to reproduce it by rebooting or shuting down the phone several times, but I didn't manage (I managed once, but that was a few weeks ago, and I didn't had logcat running then).
Mostly I only notice it, once I want to make a call, and notice that linphone lost the settings again, and then I remember that in the morning the device was switched of (no battery)
Would the internal debug log of linphone contain any infos if activated? But I guess that also would be lost?

**To Reproduce**
1. Setup linphone
2. reboot
3. start linphone

**Expected behavior**
Well, linphone shouldn't loose the settings ;-)

**Please complete the following information**
 - Device: Poco X3
 - OS: android 11
 - Version of the App 4.5.2
 - Version of the SDK [e.g 4.4.16]

**Comment by basncy** [comment]
I just got linphone app being reset when picking up a call occasionally.
iPhone 6s, iOS 14.6 linphone 4.5.0 SDK 5.0.0

To Reproduce:
1. Setup linphone with a linphone account(user2@sip.linphone.org).
2. normal using for a while. (actually, it works many weeks).
3. making a call from user1@sip.mydomain.com to user2@sip.linphone.org
4. linphone iPhone Rings WITHOUT displaying callerid, even waiting a little bit long time. 
5. Picking up this calls at this moment(before callerid displayed), linphone app was reset and configuration lost. 

At step 4 callerid missing, it is NOT always happen, but when this happen(I mean missing callerid even waiting for some time), linphone app will be reset. I guess it might be caused by the loss of receiving the INVITE signal but not sure.

**Comment by yennor** [comment]
I've almost run out of battery on saturday, so I switched the phone off. On Sunday I've got  somewhere with electricity, so I've charged it and switched it on again. Didn't verify linphone. Monday morning my mailbox was full with a clients message which tried to reach me because of an emergency. Verifying linphone, I've noticed that all the settings were lost again.
I can give you the logcat since boot with linphone entries, they don't say anything to me. For whatever reason there are only entries from monday, from the time were I started linphone to verify my calls, but none from before. Usually after a restart there are more messages from linphone. But maybe (most probably) it even didn't try to autostart itself? 
I didn't manage to find the logcat from the previous boot (shutdown), so I can't provide those.
I've found some entries with linphone in /data/tombstones/tombstone_00 . But since there are no timestamps I can't tell if they somehow correlate.
If you tell me how to debug that, I'd happily help. I'm pretty apt with computers so I should be able to implement most steps you throw at me ;-).

That's all folks, I doesn't seem to tell anything interesting. System boot was on 2021-11-07 6:24	
```
11-08 07:03:18.646  1659  2522 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.linphone/.activities.launcher.LauncherActivity bnds=[204,2064][372,2274] (has extras)} from uid 10292
11-08 07:03:19.286  1659 15064 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cmp=org.linphone/.activities.main.MainActivity (has extras)} from uid 10307
11-08 07:03:19.324  1659  2522 I ActivityTaskManager: START u0 {cmp=org.linphone/.activities.assistant.AssistantActivity} from uid 10307
11-08 07:04:02.831  1659  2025 D ConnectivityService: releasing NetworkRequest [ TRACK_DEFAULT id=28, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10307 AdministratorUids: [] RequestorUid: 10307 RequestorPackageName: org.linphone] ] (release request)
11-08 07:04:02.925  1659  3214 I ActivityManager: Killing 3444:org.linphone/u0a307 (adj 1001): remove task
11-08 07:05:29.107  1659  3202 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.linphone/.activities.launcher.LauncherActivity bnds=[204,2064][372,2274] (has extras)} from uid 10292
11-08 07:05:29.135  1659  1744 I ActivityManager: Start proc 23464:org.linphone/u0a307 for pre-top-activity {org.linphone/org.linphone.activities.launcher.LauncherActivity}
11-08 07:05:29.966  1659  2518 D ConnectivityService: requestNetwork for uid/pid:10307/23464 NetworkRequest [ TRACK_DEFAULT id=1960, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10307 AdministratorUids: [] RequestorUid: 10307 RequestorPackageName: org.linphone] ]
11-08 07:05:30.672  1659  2518 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cmp=org.linphone/.activities.main.MainActivity (has extras)} from uid 10307
11-08 07:16:33.457  1659  2518 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.linphone/.activities.launcher.LauncherActivity bnds=[204,2064][372,2274] (has extras)} from uid 10292
11-08 07:35:59.735  1659  1742 I ActivityManager: Killing 23464:org.linphone/u0a307 (adj 920): excessive cpu 19950 during 300063 dur=1164577 limit=2
11-08 07:35:59.963  1659  1949 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=1960, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10307 AdministratorUids: [] RequestorUid: 10307 RequestorPackageName: org.linphone] ], android.os.BinderProxy@cc699b7)
11-08 07:35:59.964  1659  2025 D ConnectivityService: releasing NetworkRequest [ TRACK_DEFAULT id=1960, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10307 AdministratorUids: [] RequestorUid: 10307 RequestorPackageName: org.linphone] ] (release request)
11-08 07:35:59.964  1659 14358 I WindowManager: WIN DEATH: Window{5af0713 u0 org.linphone/org.linphone.activities.main.MainActivity}

```

**Comment by Viish** [comment]
Hi,

Did you installed the app through the Play Store or did you build it yourself?

If not the latter can you do it? By building it yourself you can install it's "debug" flavor, allowing you to list and take a look in the app's private directory, using command such as `adb shell run-as org.linphone.debug ls -lA files/` that you can't do if the "release" flavor of the app was installed (when in debug flavor linphone package name is changed).

I'm interested to see if there is a "backup" of the config file that we use to store accounts & settings. If it is, it might indicate that the device shutdown happens when the SDK is doing some operation on the config file and that might explain your situation.

Thanks in advance for your help.

**Comment by yennor** [comment]
I've got it from f-droid.
Yes, I can compile it myself, but will take a few days, until I find time to do so...
The main problem is, that it is difficult to reproduce. Once I've tried to restart it 10 times at purpose, and it didn't happen. So maybe some kind of timing issue on shutdown?

Now I've just tried it again, and it worked :-)
I've did a shutdown, and afterwards the settings were lost again.
I've took a look at /data/data/org.linphone/files and that's what I've found (But that's after I've started linphone, and the setup wizard was already showing, so that was propably too late to look at the directory...), I guess the settings would be in linphone.db ?:
```
-rw------- 1 u0_a307 u0_a307     1926 2021-11-08 08:29 assistant_default_values
-rw------- 1 u0_a307 u0_a307     2469 2021-11-08 08:29 assistant_linphone_default_values
-rw------- 1 u0_a307 u0_a307    32768 2021-11-08 08:28 call-history.db
-rw------- 1 u0_a307 u0_a307   184320 2021-09-17 09:38 linphone.db
-rw------- 1 u0_a307 u0_a307 10485834 2021-11-04 06:25 linphone1.log
-rw------- 1 u0_a307 u0_a307  6381218 2021-11-08 08:44 linphone2.log
-rw------- 1 u0_a307 u0_a307      983 2021-11-08 08:29 linphonerc
drwx------ 6 u0_a307 u0_a307     3488 2021-11-08 07:04 share
drwx------ 2 u0_a307 u0_a307     3488 2021-11-04 09:14 user-certs
-rw------- 1 u0_a307 u0_a307    81920 2021-11-08 08:28 x3dh.c25519.sqlite3
-rw------- 1 u0_a307 u0_a307    28672 2021-09-20 02:39 zrtp-secrets.db

```

Here are the shutdown logs and the reboot logs. At about 8:29:01 shutdown was iniciated. Maybe it tells you anything.
[linphone.shutdown.log](https://github.com/BelledonneCommunications/linphone-android/files/7497354/linphone.shutdown.log)
[linphone.boot.log](https://github.com/BelledonneCommunications/linphone-android/files/7497320/linphone.boot.log)

**Comment by Viish** [comment]
Thanks for the logs, I'll look into it.

However did you use the `-lA` attribute for the `ls` command? I don't see any files starting with a `.`.
And if you can check the files list before starting the app (even if you won't know at the time if the issue occurred or not) it would help a lot.

**Comment by yennor** [comment]
oh, so there are some hidden files. Ok I'll do so. Today during siesta time, I will do some restarts, "ls -lA" before I start the app, until the issue happens.

**Comment by Viish** [comment]
Thanks a lot!
By the way your linphone.shutdown.log file shows the app stopped properly, nothing that could explain the issue :'(

**Comment by Viish** [comment]
Could you also attach the `linphone1.log` and `linphone2.log` files please?

**Comment by yennor** [comment]
sorry, it took a bit longer. But all the files seem to be there:

```
-rw-rw---- 1 root everybody        0 2021-10-19 07:34 .linphone.ecstate
-rw-rw---- 1 root everybody     1503 2021-11-12 16:13 .linphonerc
-rw-rw---- 1 root everybody     1926 2021-11-12 15:29 assistant_default_values
-rw-rw---- 1 root everybody     2469 2021-11-12 15:29 assistant_linphone_default_values
-rw-rw---- 1 root everybody    36864 2021-11-12 12:25 call-history.db
-rw-rw---- 1 root everybody   184320 2021-09-17 09:38 linphone.db
-rw-rw---- 1 root everybody 10485814 2021-11-12 13:56 linphone1.log
-rw-rw---- 1 root everybody  8085472 2021-11-12 15:29 linphone2.log
-rw-rw---- 1 root everybody      983 2021-11-12 15:29 linphonerc
drwxrwx--- 6 root everybody     3488 2021-11-12 09:56 share
drwxrwx--- 2 root everybody     3488 2021-11-03 09:00 user-certs
-rw-rw---- 1 root everybody    81920 2021-11-12 15:28 x3dh.c25519.sqlite3
-rw-rw---- 1 root everybody    28672 2021-09-20 02:39 zrtp-secrets.db
```
[linphone2.log](https://github.com/BelledonneCommunications/linphone-android/files/7539536/linphone2.log)
[linphone1.log](https://github.com/BelledonneCommunications/linphone-android/files/7539537/linphone1.log)

One thing, I'm not 100% sure. But I've got the feeling, that it happens, when I restart the phone, after I've received at least one phone call in Linphone. When I didn't receive one, it doesn't seem to trigger the error (I guess that's why it was so difficult to reproduce it). Unfortunately I live in another timezone, than I work in, and when I'd have time to test that, it's already after midnight in the country where the number is registered, so it's a bit difficult to make somebody call me ;-).

I've also stored all the other files, if you need oneof them just tell me so (I can just change the password for my sip account...)

**Comment by Viish** [comment]
Thanks for the information but that doesn't help much, seems only to indicate this isn't linked to a race condition between a write in the config file at the moment the device restarts.

Is your device rooted?

**Comment by yennor** [comment]
yes it is rooted

**Comment by Viish** [comment]
Ok so that may be the reason why.
We never saw that kind of issue with a non-rooted device, and I guess it's because on non-rooted devices no one can access the app's private file system.
I'm sorry but I won't be able to provide more help about this matter.

**Comment by Viish** [comment]
Hi again,
Just something I though off: could you build the SDK yourself to disable the ShutdownReceiver broadcast receiver in it and build the app back using that SDK? Maybe that is what is causing your issue.
Cheers,

**Comment by yennor** [comment]
yes I should be able to do that. 
We are talking about: https://github.com/BelledonneCommunications/linphone-sdk ?
Just a question, taking a 5 minute look on the SDK I couldn't find any build flag to disable the mentioned receiver. Also making a search through the repository didn't reveal anything.
Could you give me a short hint how to disable it?

**Comment by Viish** [comment]
> We are talking about: https://github.com/BelledonneCommunications/linphone-sdk ?

Yes.

> Could you give me a short hint how to disable it?

Sure.
Edit the liblinphone/wrappers/java/classes/org/linphone/core/tools/service/CoreManager.java and comment out the following line:
`mContext.registerReceiver(mShutdownReceiver, shutdownIntentFilter);`

**Comment by killerbees19** [comment]
Same issue here, currently for the first time...

My phone crashed and rebooted while I was on the bicycle. After booting up again, Linphone lost all settings. It's the only app with data loss. Linphone wasn't active (nor running in the background) when the phone rebooted! (Only OpenTracks & VLC were active.)

**Comment by neilstephens** [comment]
This issue has affected me too, and my device is NOT rooted.

> Linphone Android 4.6.10 (tags/4.6.10^0, release)
> Linphone SDK 5.1.42 (tags/5.1.42^0, release)

> Nokia 7.1
 Android 10 
build 00WW_4_15C_SP18
Security patch level Nov 21

**Comment by ondrejholas** [comment]
Same here, Linphone settings are completely lost after reboot (Linphone was running).

Linphone Android 4.6.11 (tags/4.6.11^0, release)
Linphone SDK 5.1.46 (tags/5.1.46^0, release)
installed from Google Play

Samsung Galaxy A32 4G
Android 12 (SP1A.210812.016.A325FXXU2BVF1)
NOT rooted
