### ISSUE TITLE
How to get raw camera data. I will get the raw camera data to apply the effect and send it to the far end

### ISSUE THREAD

**Issue by leeyushi** [BelledonneCommunications/linphone-android#1544]
How to get raw camera data. For some reasons, I will get the raw camera data and apply some effects to the raw data and send it to the far end

**Comment by Viish** [comment]
You can't, not in our Android app.
However you can fork the [msandroidcamera2](https://github.com/BelledonneCommunications/msandroidcamera2) plugin and make the changes you want to add your effects.
