### ISSUE TITLE
Speaker error

### ISSUE THREAD

**Issue by judklaus** [BelledonneCommunications/linphone-android#1546]
Hi @Viish, when I send video request to the callee, callee's speaker is turned on immediately (before callee accepts the video request). 

Scenario
1. caller sends video request to the callee.
2. callees' speaker is turned on.
3. callee rejects the video request. Its speaker is still on however speaker image is set to default (as if it is directed to the earpiece)
4. I turn on and then off the speaker button to see if it fixes the audio problem, but it does not.

Logs
caller: https://www.linphone.org:444//tmp/618a490f924fe_ac158ddaf192d3f6edd9.gz 
callee: https://www.linphone.org:444//tmp/618a49191206f_6990c3bad3e9ae90c678.gz

**Comment by Viish** [comment]
Hi,
From your logs there is only one switch to speaker and it seems it was initiated by user.
Also nothing shows that when switched back to earpiece the audio was still on speaker.
And I don't reproduce it with 4.6.0-beta version, can you?
Cheers,

**Comment by judklaus** [comment]
Hi @Viish, I'm a beta tester and I can download version 4.5.6. How can I use 4.6.0? By the way, right after turning that phone call off, the next call I make starts with speaker on as well with version 4.5.6.

caller: https://www.linphone.org:444//tmp/618a4f2cf0f18_35f96432cb868660c8df.gz 
callee: https://www.linphone.org:444//tmp/618a4f33cfea8_ab644589a07e901066ea.gz

**Comment by Viish** [comment]
4.6.0-beta isn't available yet on the PlayStore, but you can download our nightly build here: http://linphone.org/snapshots/android/

**Comment by judklaus** [comment]
Hi @Viish , I couldn't create the same problem here with but I found another error.

Scenario
1. Caller sends video request to the callee.
2. Callee accepts it after 15 seconds. 
3. Only callee's camera turns on. and at the same time the call ends but remains on both sides' UI. (Caller in Incall view with the video trying to turn on indicator, callee in incall video view) After the timeout both sides end and turn back to Dialer View.

Callers log: 
[618b8678f4019_12551f0558c4857e5aba.gz](https://github.com/BelledonneCommunications/linphone-android/files/7511177/618b8678f4019_12551f0558c4857e5aba.gz)

Callees log: 
[618b867788dc1_21384a6641509eed799b.gz](https://github.com/BelledonneCommunications/linphone-android/files/7511179/618b867788dc1_21384a6641509eed799b.gz)

**Comment by Viish** [comment]
I'm closing as I don't reproduce.
