### ISSUE TITLE
Recording not working in case of Referred call

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#1547]
Hello @Viish ,

Hope you are doing good.

I am facing one issue. in the case of Referred call the recording button stop working as getRecordFile() is null when a new call is generated after Refer. The following error message is coming.

 **"MediaSession::startRecording(): no output file specified. Use MediaSessionParams::setRecordFilePath()"**

Please suggest what to do.

Thanks in advance.

**Comment by Viish** [comment]
Hi,

You have to set the recording file path in the call's params.
Currently it is done in CoreContext.startCall() and CoreContext.answerCall().

Hope it helps.

Cheers,

**Comment by amit1576** [comment]
Hello @Viish ,

Yes, I need to update the call param but I guess Referred call is initiated from SDK. How to update call param with in android.

Thanks.

**Comment by Viish** [comment]
Use the following:
```
val params = call.currentParams
params.recordFile = ""
call.update(params)
```

**Comment by amit1576** [comment]
I am using the same but where and when to update the call param?

**Comment by Viish** [comment]
When your referred call is starting, in a call state change listener for example.

**Comment by amit1576** [comment]
ok. Let me try

**Comment by amit1576** [comment]
Hi @Viish ,

When I update call param on state event **"OutgoingRinging"** of new call-in CoreContext, it will send a new update **_(Subject: Media change)_** to the server which will lead to 500 internal server errors. 

.pcap also attached for the same call. Please suggest what to do.

2021/11/10 05:45:02.936210 122.176.215.127:53530 -> 172.105.49.156:5060
UPDATE sip:28##@192.168.1.7:51117;transport=TCP;ob;alias=122.176.215.127~51919~2 SIP/2.0
Via: SIP/2.0/TCP 192.168.232.2:55010;branch=z9hG4bK.HyvLvu8fL;rport
From: <sip:18##@###.###.###>;tag=ubGTiIyAv
To: <sip:28##@###.###.###>;tag=be6d74d712d245d8aaab47ad3ec6b421
CSeq: 22 UPDATE
Call-ID: iic4IT62oZ
Max-Forwards: 70
Route: <sip:172.105.49.156;transport=tcp;lr;ftag=ubGTiIyAv;did=7c2.506;nat=yes>
Subject: Media change
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO, PRACK, UPDATE
Content-Type: application/sdp
Content-Length: 364
Contact: <sip:18##@122.176.215.127:53530;app-id=108861424352;app-imei=cWF3em5tTGlRc3NVdVIwRTc0a2pUYVVJSks4dFE5Q0xYVDhrWXYvd2VMRT0;pn-type=firebase;pn-prid=cqND--ydDHc:APA91bHbMoWYMMfLmdUP_f
r4FkrXvVMPPjdvUvnp4khk5d_8F5AvASqqmikvbITRQBnYZoVfyQabfkBPSnYJ_eXotZwoB3BdUBakMT1yrUGVuj4fOHLSi0OezaYZT9Tjr7zbdpAOuQ;pn-provider=fcm;pn-param=108861424352;pn-silent=1;pn-timeout=0;transport
cp>;expires=3600;received="sip:122.176.215.127:53530;transport=tcp";+sip.instance="<urn:uuid:ed7bef76-d3e8-002f-9e14-3c01e04dcebb>"
User-Agent: CoralUCAPP/4.4.52 (AOSP on IA Emulator) CoralUC SDK/5.0.0
Proxy-Authorization:  Digest realm="###.###.###", nonce="1231", username="18##",  uri="sip:28##@192.168.1.7:51117;transport=TCP;ob;alias=122.176.215.127~51
9~2", response="f4f069f40eb14d70b268692be1d96053"

v=0
o=18## 372 1036 IN IP4 192.168.232.2
s=Talk
c=IN IP4 192.168.232.2
t=0 0
a=rtcp-xr:rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics
m=audio 7080 RTP/AVPF 96 0 8 97 101
a=rtpmap:96 opus/48000/2
a=fmtp:96 useinbandfec=1
a=rtpmap:97 telephone-event/48000
a=rtpmap:101 telephone-event/8000
a=rtcp-fb:* trr-int 1000
a=rtcp-fb:* ccm tmmbr

[callupdate.zip](https://github.com/BelledonneCommunications/linphone-android/files/7508882/callupdate.zip)

**Comment by Viish** [comment]
Then wait for call state to be Connected or StreamsRunning to do the update.

**Comment by amit1576** [comment]
Ok let me check.
