### ISSUE TITLE
No Audio on outgoing call on Android 12 but OK on android 11

### ISSUE THREAD

**Issue by NLLAPPS** [BelledonneCommunications/linphone-android#1549]
Hi, I have discovered as very weird issue with a specific SIP server on Android 12.

Server: sip.ringcentral.com
Android 11: All OK
Android 12: Outgoing call has no sound whether you use speaker or earpiece. Incoming calls are OK.

Server: Any other server. For example sipgate
Android 11: All OK
Android 12: All OK

I have attached logs for an outgoing ringcentral call from android 12 for your investigation. I could not find anything in them.
https://www.linphone.org:444//tmp/618c3a2dc0055_f90c5f9f49ce8208a3a8.gz

**Comment by Viish** [comment]
Hi,

Looks like a network issue.
Try to enable STUN/ICE, it should solve your problem.

Cheers,

**Comment by NLLAPPS** [comment]
Thanks,I cannot seem to make stun proxy setting under Linphone app persist. 
I use "stun.counterpath.net" as Stun server, tap on the checkbox  and then enable ICE, when I come back it is empty and accountParams.natPolicy?.stunServer returns null

**Comment by NLLAPPS** [comment]
I have managed to apply STUN server but now I get
"ICE state is IceStateNotActivated for stream#0 [audio] in state [Running]"

**Comment by NLLAPPS** [comment]
Also, please note that same server same config work on Android 11 and Another server works on Android 12.

**Comment by Viish** [comment]
> I have managed to apply STUN server but now I get
"ICE state is IceStateNotActivated for stream#0 [audio] in state [Running]"

Have you enabled ICE?

> Also, please note that same server same config work on Android 11 and Another server works on Android 12.

Just so you know there is nothing that could explain why an Android 12 device wouldn't work when an Android 11 one does.

**Comment by NLLAPPS** [comment]
Yes it is, I double check after setting with 

` accountParams.natPolicy = core.createNatPolicy().apply {
                        stunServer = "xxxx"
                        enableIce(true)
                        enableStun(true)
                    }`

with

`accountParams.natPolicy?.iceEnabled()`

and it returns true

**Comment by Viish** [comment]
That means the other device doesn't support ICE...

**Comment by NLLAPPS** [comment]
What I am trying to explain is that, another app on same Android 12 phone can make calls without STUN server.
The other app uses PJSIP and server config is the same.

This points the issue to linphone. I might be able to share credentials in private for you to do some tests if you have Android 12 device to test.

**Comment by Viish** [comment]
And what I'm trying to explain is there is no reason an Android 11 device works while an Android 12 device with the same config on the same network won't.
You said the problem only happens with sip.ringcentral.com, so the issue is likely related to them more than us.
If you can share your credentials I can try to reproduce the issue, we do have an Android 12 device, the same as yours.

**Comment by NLLAPPS** [comment]
Thank you, how can I send you credentials privately?

**Comment by Viish** [comment]
> Is the email on your profile fine?

Yes it is.

**Comment by NLLAPPS** [comment]
Just sent you the credentials via email.

**Comment by Viish** [comment]
Got them, thanks.
I'll check when I have a bit of time available.
