### ISSUE TITLE
old versions are not working anymore

### ISSUE THREAD

**Issue by nikl125** [BelledonneCommunications/linphone-android#1550]
I used 2.5.0 , 3.0.0 on old android devices, now there is io network error. No way to fix that, it is like with skype or viber, old versions of program and os are not working?

**Comment by Viish** [comment]
Without logs it's hard to tell but I guess it's because of the root certificate embedded in the app that's outdated, preventing TLS connections.
Have you tried to use TCP instead?

**Comment by nikl125** [comment]
With tcp it works
