### ISSUE TITLE
00390xxx numbers dont work

### ISSUE THREAD

**Issue by patrickSpaceSurfer** [BelledonneCommunications/linphone-android#1551]
I am using linphone android 4.5.6 with sipgate on a oneplus 3 (android 9). When calling certain Italian numbers internationally (in my case from england) you need to dial 00390332....
The 0 after the 0039 is crucial, if you dont dial this then the number will be invalid. Linphone will sometimes (now always) replace 00390 with 0039, omitting the crucial 0 after 0039.
For years linphone has made it incredibly hard to dial such numbers (for example you couldn't use the + instead of 00, you had to put the number in manually, you couldn't call from a contact ...). However, now its simply impossible to dial 00390123456789 because linphone will remove the 0 after the 0039.

**Comment by Viish** [comment]
Hi,

It's actually not that hard.

If you have a prefix set in your account settings and you try to dial a number, it will attempt to apply said prefix to it.
So one solution is to empty the prefix field in your account settings.

Another solution is to dial a SIP URI instead of a phone number, for your example `sip:00390123456789@domain.tld`.

Just so you know I tried to dial (using the numpad) 00390123456789 and the generated SIP URI was `sip:00390123456789@sip.linphone.org`, which is why you expect (except for the domain), right?

**Comment by patrickSpaceSurfer** [comment]
Ok, so if I manually type in a number I have never called, such as, 00390123456789, then it works. It will not drop the 0. However, if I call my contact (by clicking on the contact, manually typing the number, manually typing the SIP URI...) it will replace 00390 with 0039. Note that in my contact I have the correct number (even though at some point I had the incorrect number because 0039332.. used to work many years ago). So somewhere linphone has stored the old number and it will use the old contact details, overriding manual input or even more up to date contact details, no matter what I do.
Note that in the android address book the number is correct (screenshot attached) as it is in the linphone address book (attached). However, if I look at my history (screen shot attached) and click on the ... (screen shot attached) you can see that it dialed the wrong number!
Note that I masked the full number in the attached images
![linphoneCallHistoryDetails](https://user-images.githubusercontent.com/29952889/141764559-29035a83-21b7-4eec-a632-3030d6835b46.jpg)
![androidContact](https://user-images.githubusercontent.com/29952889/141764564-557a11b0-644c-455b-a13f-496024510fe1.jpg)
![linphoneContact](https://user-images.githubusercontent.com/29952889/141764565-a37d932e-a41b-4adc-ba3e-c7027102e73b.jpg)
![linphoneCallHistory](https://user-images.githubusercontent.com/29952889/141764572-d0daf2da-e8b3-474c-9c55-8f57d0dc06da.jpg)
