### ISSUE TITLE
4.6.0-beta "make calls" permission

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1553]
When I install release/4.6.0 it wants permission to _make calls_.  Just curious why.

**Comment by Viish** [comment]
We don't require permission to make calls. 
We ask for READ_PHONE_STATE (or READ_PHONE_NUMBERS on Android 11 and newer) and for MANAGE_OWN_CALLS which are the two permissions required to use TelecomManager API which allows us to properly handle bluetooth devices and audio focus.
This isn't mandatory but it greatly improves the user experience while in call.
