### ISSUE TITLE
[enhancement] sending message by press ENTER on physical keyboard

### ISSUE THREAD

**Issue by basncy** [BelledonneCommunications/linphone-android#1554]
Can we provide an option of sending the message when pressing ENTER or Ctrl + ENTER? rather than press the button on the screen? Useful when we type with a physical keyboard.
e.g. Linphone Desktop bind "ENTER" to send a message. Telegram bind "Ctrl + ENTER" to send a message.   

Reproduce:
option 1: Connect a USB/Bluetooth keyboard to android and send a message.
option 2: Remote control android via scrcpy(https://github.com/Genymobile/scrcpy) and send messages from PC.

**Comment by Viish** [comment]
Done in 9d48a15b, will be part of 4.6.0 release
