### ISSUE TITLE
Telecom manager not aware that call has ended

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-android#1555]
I'm currently playing a bit with the Linphone master branch and I'm experiencing some problems when the telecom manager is enabled. I've noticed that when a "BYE" for some reason could not be sent to Linphone (for example other party hangs up call but SIP signalling is somewhat bad), Linphone doesn't notify the Telecom Manager afterwards that the call has ended.
Every new call attempt made with Linphone will show a warning message: "Placing this call will end your Linphone call". Also, when trying to adjust the Android volume, it still thinks that it is in call. Only way to stop this is to force stop Linphone.

If there are not active calls within Linphone, shouldn't it notify the Telecom Manager every time?

SDK version is 5.1.0-beta.18

**Comment by Viish** [comment]
Hi,

Can you attach logs showing the issue please?

**Comment by driesken** [comment]
Hi,

Please find attached logs. I've made 2 test calls and made the remote party hangup first. The BYE didn't get acknowledged by linphone so I ended each call after a few seconds. The second call attempt displayed the warning message.

[telecom_manager_issue.txt](https://github.com/BelledonneCommunications/linphone-android/files/7576823/telecom_manager_issue.txt)
.

**Comment by Viish** [comment]
Hi,

Thanks for the logs.
Indeed BYE is never received by linphone, don't know why.
However this shouldn't prevent linphone to properly destroy telecom manager connection when you end the call locally.
I've pushed a new commit in release/4.6 branch to fix and add logs regarding this issue, can you try it please?

Thanks.

**Comment by driesken** [comment]
Hi,

I've manually merged your fix and made 2 calls again. Seems to be working fine now, thanks! I've attached the new logs.
[call_manager_test_2.txt](https://github.com/BelledonneCommunications/linphone-android/files/7581153/call_manager_test_2.txt)

(The BYE is an issue with my SIP proxy)

**Comment by Viish** [comment]
Great!
