### ISSUE TITLE
Launch from Google Assistant

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1556]
I'm trying to plumb in the ability to launch linphone from Google Assistant when one asks Google Assistant to _Call \<number\>_.  I've gotten to the point of getting Linphone to be the target of the call.

In order to do so I had to add to the `AndroidManifest.xml`:

```
        <service android:name=".telecom.CallService"
            android:enabled="true"
            android:exported="true"
            android:permission="android.permission.BIND_INCALL_SERVICE">
            <meta-data
                android:name="android.telecom.IN_CALL_SERVICE_UI"
                android:value="true" />

            <intent-filter>
                <action android:name="android.telecom.InCallService" />
            </intent-filter>
        </service>
```

Then I mocked up a CallService implementation:

```
package org.linphone.telecom

import android.net.Uri
import android.os.Bundle
import android.telecom.Call
import android.telecom.InCallService
import org.linphone.LinphoneApplication.Companion.coreContext
import org.linphone.activities.navigateToDialer
import org.linphone.core.tools.Log

class CallService : InCallService() {

    private val callListener = object : Call.Callback() {
        override fun onStateChanged(call: Call, state: Int) {
            super.onStateChanged(call, state)
            Log.i("org.linphone.telecom.CallService().onStateChanged()")
            if (state != Call.STATE_DISCONNECTED) {
                Log.i("state != Call.STATE_DISCONNECTED")
            }

            if (state == Call.STATE_ACTIVE) {
                Log.i("state == Call.STATE_ACTIVE")
            } else if (state == Call.STATE_DISCONNECTED || state == Call.STATE_DISCONNECTING) {
                Log.i("state == Call.STATE_DISCONNECTED || state == Call.STATE_DISCONNECTING)")
            }
        }
    }

    private fun handleTelOrSipUri(uri: Uri) {
        Log.i("[Main Activity] Found uri: $uri to call")
        val stringUri = uri.toString()
        var addressToCall: String = stringUri

        when {
            addressToCall.startsWith("tel:") -> {
                Log.i("[Main Activity] Removing tel: prefix")
                addressToCall = addressToCall.substring("tel:".length)
            }
            addressToCall.startsWith("linphone:") -> {
                Log.i("[Main Activity] Removing linphone: prefix")
                addressToCall = addressToCall.substring("linphone:".length)
            }
            addressToCall.startsWith("sip-linphone:") -> {
                Log.i("[Main Activity] Removing linphone: sip-linphone")
                addressToCall = addressToCall.substring("sip-linphone:".length)
            }
        }

        val address = coreContext.core.interpretUrl(addressToCall)
        if (address != null) {
            addressToCall = address.asStringUriOnly()
        }

        Log.i("[Main Activity] Starting dialer with pre-filled URI $addressToCall")
        val args = Bundle()
        args.putString("URI", addressToCall)
        navigateToDialer(args)
    }

    override fun onCallAdded(call: Call) {
        super.onCallAdded(call)
        Log.i("org.linphone.telecom.CallService().onCallAdded(" + call.toString() + ")")
        Log.i(
            "org.linphone.telecom.CallService().onCallAdded() calling " +
                call.getDetails().getHandle().toString()
        )
        handleTelOrSipUri(call.getDetails().getHandle())
    }

    override fun onCallRemoved(call: Call) {
        super.onCallRemoved(call)
        Log.i("org.linphone.telecom.CallService().onCallRemoved(" + call.toString() + ")")
    }

    override fun onDestroy() {
        super.onDestroy()
        Log.i("org.linphone.telecom.CallService().onDestroy()")
    }
}
```

When I build it though I am getting:

```
> Task :app:compileDebugKotlin
e: /home/brian/linphone-android/app/src/main/java/org/linphone/telecom/CallService.kt: (67, 9): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
internal fun MainActivity.navigateToDialer(args: Bundle?): Unit defined in org.linphone.activities
internal fun DetailContactFragment.navigateToDialer(args: Bundle?): Unit defined in org.linphone.activities
internal fun TabsFragment.navigateToDialer(): Unit defined in org.linphone.activities
internal fun DetailCallLogFragment.navigateToDialer(args: Bundle?): Unit defined in org.linphone.activities
internal fun MasterCallLogsFragment.navigateToDialer(args: Bundle?): Unit defined in org.linphone.activities
```

Clearly something about the structure of the app that I am not understanding.

Any ideas?

**Comment by Viish** [comment]
You can't use `navigateToDialer(args)` and other `navigate` methods like that.
They are defined as extension of specific classes.
If you need to add some, do it in the Navigation.kt file.

**Comment by brianjmurrell** [comment]
Thanks for the suggestion.

Do you have any opinion on whether the approach is even valid or sane?  Or am I going down a rabbit-hole that leads to nowhere?

**Comment by Viish** [comment]
What you are doing seems to implement what we started to do in telecom_manager branch when using it to have default dialer replace our own UI.

I don't think this is necessary to have Google Assistant launch Linphone.
Instead take a look at https://developers.google.com/assistant/app/intents and https://developers.google.com/assistant/app/reference/built-in-intents/communications/create-call

**Comment by brianjmurrell** [comment]
> What you are doing seems to implement what we started to do in telecom_manager branch when using it to have default dialer replace our own UI.

Indeed.  It very well could be.  Looking into that branch more is on my TODO list.  I notice there are both telecom_manager and telecom_manager_5.1 (at least I have them locally).  Is one more mature than the other or are they different for other reasons?
 
> I don't think this is necessary to have Google Assistant launch Linphone. Instead take a look at https://developers.google.com/assistant/app/intents and https://developers.google.com/assistant/app/reference/built-in-intents/communications/create-call

I read over those quickly.  I think that is specifically for developing Google Assistant apps, where you can do something like "Hey Google, talk to Linphone" and then start directing commands at linphone.  Maybe I am wrong about that.  I will look more deeply.

But if that is the case, I am trying to do something more in-built and natural for the user, where they can just say "Hey Google, call ..." and whatever is set as the default dialer is invoked without them having to know that they need to ask google to call ... on linphone.  Maybe what I am trying to do is actually impossible, but I guess i'll see.

But indeed, maybe using the default dialer with the telecom_manager branch is the more correct approach.
