### ISSUE TITLE
How to Use Account class instad on ProxyConfig ?

### ISSUE THREAD

**Issue by RaviChavada** [BelledonneCommunications/linphone-android#1559]
Hii,
when I use Account class instead of Proxyconfig, my user is not registered. is there any specific way to create an account or migrate proxy config to the Account class?
please suggest me.

**Comment by Viish** [comment]
Hi,
Take a look at our tutorials: https://gitlab.linphone.org/BC/public/tutorials/-/tree/master/android/kotlin/1-AccountLogin
