### ISSUE TITLE
Update chat message on message recieved

### ISSUE THREAD

**Issue by ahmed847** [BelledonneCommunications/linphone-android#1560]
Hi,

I want to update the chat message with adding a _userData_ and save it in the chat's local storage. But when I update it  and I go to chat room again the _userData_ is null. Somehow it seems not to be permanently saved in the local storage.

Moreover the custom header are also only received once we get a message, the next time I go to chat room and see the message, the custom header is also null.

Could you please help me on this?

Code:

        onChatMessageStatusChangedListener = object : ChatMessageListenerStub() {
            override fun onMsgStateChanged(message: ChatMessage, state: ChatMessage.State) {
                if (state == ChatMessage.State.Displayed) {
                    val time = Calendar.getInstance().timeInMillis
                    message.addCustomHeader("read_time", java.lang.Long.toString(time))
                    message.contents.forEach {
                        it.userData = message.getCustomHeader("X-Filekey")
                    }
                }
            }
        }

**Comment by Viish** [comment]
Hi,

User data isn't stored in database, it's only in the app's memory.
Also once a message has been sent/received it becomes read-only, so you can't add custom header at this point either. Custom header may only be set before sending a chat message.
If you want to store information about a specific message you have to it manually in your app.

Cheers,
