### ISSUE TITLE
Using the sip.linphone.org server for Push Notifications on custom SIP server

### ISSUE THREAD

**Issue by dcowan-london** [BelledonneCommunications/linphone-android#1561]
Hi,

I'm aware that I can't use my own push notifications server with the Play Store app. I've seen reference to a public sip.linphone.org FlexiSIP server. Am I able to use this for my own SIP server? If so, how? I've tried setting sip.linphone.org as the proxy, but then I just get "Connection Failed" in Linphone and the registration just never hits my server.

Thank you in advance!

**Comment by Viish** [comment]
Hi,

Flexisip does support to be used as a "push gateway" for other proxy servers (see https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/HOWTOs/Push%20Gateway/#HSetupapushgatewaywithFlexisip), but our instance at sip.linphone.org isn't configured to do so.

Cheers,

**Comment by dcowan-london** [comment]
So there's no way to get push notifications in the stock app (on the Play Store) for my own SIP server?

**Comment by Viish** [comment]
Indeed there is currently no way of doing that.
If it's your personal use you can change the client push information in our project & rebuild the app for yourself, it's very easy.
If it's for a professional use you can contact our sales department for a quotation, that is something we can do.
