### ISSUE TITLE
How to display video before connected?

### ISSUE THREAD

**Issue by Steven1937** [BelledonneCommunications/linphone-android#1564]
Hi,  how to achieve video before answering? On Call coming side , I replaced the "linphonecore.acceptCallWithParams" with "LinphoneCore.acceptEarlyMedia() ", but no video display, Is there something I need to do for Call outgoing side ? I confused how to send video data when call SipCoreManager.getInstance().newOutgoingCall()? , or how to send video data before connected? Thanks in advance.

**Comment by Viish** [comment]
Hi,
Follow this [tutorial](https://gitlab.linphone.org/BC/public/tutorials/-/tree/master/android/kotlin/4-OutgoingCall) and enable early media in your outgoing call params.

**Comment by Steven1937** [comment]
> Hi, Follow this [tutorial](https://gitlab.linphone.org/BC/public/tutorials/-/tree/master/android/kotlin/4-OutgoingCall) and enable early media in your outgoing call params.

Hi, thanks for your demo,   Linphone I used  is java old version, I set the the outgoind call parmas and can see the listenner callback received State.IncomingEarlyMedia . On coming call side I use LinphoneCore.acceptEarlyMediaWithParams(currentCall,params) ,but still cannot display the early video,  could u pls show the demo of how to display the early video on coming call side?   I found if a call is not connected(because early media is called before connected ),  the video data cannot transfer, it seems limited from Linphone native code.
