### ISSUE TITLE
App Crashed while click on Echo canceler calibration

### ISSUE THREAD

**Issue by RaviChavada** [BelledonneCommunications/linphone-android#1565]
Hello,
I am using 5.1 SDK version, and also set LinphoneSdkBuildDir in Gradle.properties file.
  when i click on echo canceler calibration my app crashed.
 when I build the project without  LinphoneSdkBuildDir in Gradle.properties and perform same scenario app is working fine.
 
 so, my question is any other setup for echo canceler calibration while we set LinphoneSdkBuildDir in Gradle.properties?

**Comment by Viish** [comment]
Hi,

This has nothing to do about.
 LinphoneSdkBuildDir only allows you to use a locally built SDK instead of one of our artefacts in our maven repository.
This means you have an issue in the SDK you built locally but that isn't in our own SDK build.
So check your SDK changes for the reason why it crashes.

**Comment by RaviChavada** [comment]
so is there any specific tag enabled while we locally build SDK?

**Comment by Viish** [comment]
None related to echo cancellation.

**Comment by RaviChavada** [comment]
In linphone application, when set locally build linphone SDK path, the app is crashed and when I removed local linphone SDK path it's working perfectly

```
build.gradle(:app) code:

repositories {
    maven {
        name "local linphone-sdk maven repository"
        url file(LinphoneSdkBuildDir + '/maven_repository/')
        content {
            includeGroup "org.linphone"
        }
    }

    /*maven {
        name "linphone.org maven repository"
        url "https://download.linphone.org/maven_repository"
        content {
            includeGroup "org.linphone"
        }
    }*/
}

gradle.properties

LinphoneSdkBuildDir=/home/ravi/LinphoneSDKGIT/build/
```
  
please find log file and crash video

https://user-images.githubusercontent.com/17444917/144391483-9fffc5ab-f213-4f4f-b8b1-30d5166ddc90.mp4

[echocanceler_crash.txt](https://github.com/BelledonneCommunications/linphone-android/files/7640548/echocanceler_crash.txt)

so i am doing proper or anything missed?

**Comment by Viish** [comment]
Your log file doesn't include the crash stack trace, please get it using ndk-stack tool.

**Comment by RaviChavada** [comment]
@Viish thank you for your response, can you please give me link of official link to install ndk-stack, so I can gather crash stack trash.

**Comment by RaviChavada** [comment]
Please find Crash stack trace
[Crash dump.txt](https://github.com/BelledonneCommunications/linphone-android/files/7648319/Crash.dump.txt)

**Comment by Viish** [comment]
I don't understand as why you would have a crash in the video display filter while doing audio echo cancellation calibration...

**Comment by RaviChavada** [comment]
same thing i am also don't understand, let me check one more time.

**Comment by RaviChavada** [comment]
PFA
[Crash dump.txt](https://github.com/BelledonneCommunications/linphone-android/files/7649829/Crash.dump.txt)

**Comment by Viish** [comment]
It kooks better. I'll take a look at it when I'll have some time available.

**Comment by RaviChavada** [comment]
Thanks for your positive and quick reply.

**Comment by RaviChavada** [comment]
Hi @Viish, any update on this issue?

**Comment by Viish** [comment]
Not yet, I don't have time for that right now, will probably won't be able to take a look until next year.

**Comment by Viish** [comment]
I don't see why it crashes.
Please try again with latest 5.1-beta SDK but I'd recommend you to stick to 5.0 release for now.

**Comment by RaviChavada** [comment]
when I try to build with SDK 5.0+ its show error to build

```
Could not find any version that matches org.linphone:linphone-sdk-android:5.0+.
Versions that do not match:
  - 5.2.0-alpha.35+b93d894
  - 5.2.0-alpha.34+9ae2f3f
  - 5.1.0-alpha.108+c816cee
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/org/linphone/linphone-sdk-android/maven-metadata.xml
  - https://repo.maven.apache.org/maven2/org/linphone/linphone-sdk-android/maven-metadata.xml
  - https://jitpack.io/org/linphone/linphone-sdk-android/maven-metadata.xml
  - file:/home/ravi/LinphoneSDKGIT/build/maven_repository/org/linphone/linphone-sdk-android/maven-metadata.xml
Required by:
    project :app
Search in build.gradle files
```
and when i try to build 5.1+ and perform the same scenario app is crashed.

**Comment by Viish** [comment]
Somehow you have removed our maven repository from your build.gradle, or you didn't build a SDK from release/5.0 branch, or the `LinphoneSdkBuildDir` path in your gradle.properties doesn't match the directory in which you built.
