### ISSUE TITLE
org.linphone.core#openPttAudioStream

### ISSUE THREAD

**Issue by Reginer** [BelledonneCommunications/linphone-android#1566]
Has the `org.linphone.core#openPttAudioStream` been removed? 
What api is used instead?

sdk version:linphone-sdk-android-5.0.57-pre.1+e9375bf

**Comment by Viish** [comment]
I guess you mean `openRttAudioStream` ?
If yes then simply enable realtimetext in your call params: https://download.linphone.org/snapshots/docs/liblinphone/latest/java/org/linphone/core/CallParams.html#enableRealtimeText-boolean-

**Comment by Reginer** [comment]
![image](https://user-images.githubusercontent.com/12568257/144566616-33cb4364-d916-4e7a-8d3d-0b4843432f31.png)

**Comment by Reginer** [comment]
`openPttAudioStream`

**Comment by Reginer** [comment]
`openPttAudioStream` in  4.4.0-alpha-7-gf232a2b

**Comment by Viish** [comment]
`f232a2b` isn't a commit known to us, and the openPttAudioStream()` has never existed in our SDK, not even in 4.4.x releases.
