### ISSUE TITLE
Automatic Recording and Upload

### ISSUE THREAD

**Issue by hasanr68** [BelledonneCommunications/linphone-android#1569]
Hi all.

Trying to figure out if Linphone can be used in industries where call recording is a mandatory requirement. Is the following possible:

1. Record all incoming + outgoing calls automatically? (And have a Do-Not-Record list?)
2. Upload all recorded calls to a server when connected to Wi-Fi?

Anyone try this?

**Comment by Viish** [comment]
Hi,

> Record all incoming + outgoing calls automatically?

Yes, there is a setting starting 4.6.0 release (currently in public beta) for that. However there is no "do-not-record" list.

> Upload all recorded calls to a server when connected to Wi-Fi?

No, currently recorded calls are only listenable within the app, however we plan on adding an export button so you will be able to send it by any mean available.

**Comment by hasanr68** [comment]
@Viish 
Thanks a lot for the quick response. I checked out the public beta - can't seem to find the record all calls setting - could you please point out what menu it is under? Sorry for the bother.

**Comment by Viish** [comment]
It's in the call section of the settings, there is a toggle named `Automatically record calls`, under RFC2833 DTMF toggle.

**Comment by hasanr68** [comment]
Ok - thanks a lot.
