### ISSUE TITLE
> Incoming calls works the same way. But maybe you receive it before the listener is set ?

### ISSUE THREAD

**Issue by ddavud-git** [BelledonneCommunications/linphone-android#1570]
> Incoming calls works the same way. But maybe you receive it before the listener is set ?
Hello I receive the incoming call messages before the listener is set what can i do for getting these messages ?

_Originally posted by @ddavud-git in https://github.com/BelledonneCommunications/linphone-android/issues/644#issuecomment-989875624_

**Comment by ddavud-git** [comment]
Hello I receive the incoming call messages before the listener is set what can i do for getting these messages ?

**Comment by Viish** [comment]
Simply set the listener after Core is created but before it is started.

**Comment by ddavud-git** [comment]
> Simply set the listener after Core is created but before it is started.

I already did exactly the same

**Comment by ddavud-git** [comment]
By the way i use other push notification service  to start the core

**Comment by Viish** [comment]
> By the way i use other push notification service to start the core

That's irrelevant .

Attach logs I'll tell you what your problem is.

**Comment by ddavud-git** [comment]
I am afraid i cant attach logs 
i got register ok  message but INVITE not coming after registering

**Comment by ddavud-git** [comment]
It happens for first time only (istener not set). When i call second time i got invite message (listener already set)

**Comment by ddavud-git** [comment]
I dont get     
SIP/2.0 100 Trying 
.....
CSeq: 6996 INVITE
...

**Comment by Viish** [comment]
> It happens for first time only (istener not set). When i call second time i got invite message (listener already set)

As I said it is expected you won't get notified of an incoming call if you haven't set the listener.

> I am afraid i cant attach logs

Then I can't do much to help...

**Comment by ddavud-git** [comment]
is there anything like to send ack get INVITE message ?

**Comment by ddavud-git** [comment]
It means it is the lack of this library then 

> > It happens for first time only (istener not set). When i call second time i got invite message (listener already set)
> 
> As I said it is expected you won't get notified of an incoming call if you haven't set the listener.
> 
> > I am afraid i cant attach logs
> 
> Then I can't do much to help...

**Comment by ddavud-git** [comment]
And is there anything to listen to user presence  (availability )?
