### ISSUE TITLE
Error Video call between Android and Window

### ISSUE THREAD

**Issue by ngthdt777** [BelledonneCommunications/linphone-android#1571]
Hello, Im having this error where video call on Windows app you could see 2 media, but on Android app you only see one. Already testing between Android - android, Windows - windows and it worked fine. I don't know if the error including me using the Kamailio server or not. Here is the backlog and picture if neccessary. Thank you in advanced.

The device is:
Samsung galaxy A70 - Android 11
Windows 10 - 21H2

![ErrorPicture](https://user-images.githubusercontent.com/57483345/145793358-7848202e-0e83-45e8-ae89-0ea1ab30c1df.png)
[logFromWindows.txt](https://github.com/BelledonneCommunications/linphone-android/files/7702883/logFromWindows.txt)
[logFromAndroid.txt](https://github.com/BelledonneCommunications/linphone-android/files/7702885/logFromAndroid.txt)

**Comment by Viish** [comment]
Hi,
Given the `VIDEO SESSION'S RTP STATISTICS` in the Android logs it's a network issue, you don't receive any video packets but the windows app does send them.
Try to enable ICE in your NatPolicy.
Cheers,
