### ISSUE TITLE
No Audio and Video from other party

### ISSUE THREAD

**Issue by JitainSharma** [BelledonneCommunications/linphone-android#1575]
**Describe the bug**
When video call is accepted, the video and audio is not showing and not audible from other side.

Linphone SDK: LinphoneSDK/4.5.0-alpha.62+a749d75-debug ( master )
Android Version: 11
Android Device: Samsung/SM-M215F/universal9611

**To Reproduce**
1. Video Call to Android user
2. Pick up the video call
3. Call started with no incoming video or audio
4. But audio from the picking side is audible to other side

**Expected behavior**

**Please complete the following information**
 - Device: [e.g. Samsung Note 20 Ultra]
 - OS: [e.g. Android 11]
 - Version of the App [e.g. 4.3.1]
 - Version of the SDK [e.g 4.4.16]

**Adb logcat logs**
[app_logs.txt](https://github.com/BelledonneCommunications/linphone-android/files/7727100/app_logs.txt)

**Additional Notes**
It's very argent as our build is stuck which have to release before Christmas. Please help here @Viish

**Comment by Viish** [comment]
@JitainSharma If you want a real support from us with fixes delivered before deadlines then contact my company : https://linphone.org/contact
I only do support here on github on my spare time, and I certainly won't fix that before christmas.

**Comment by JitainSharma** [comment]
@Viish that's okay, pls go through my issue and if any input or suggestion pls share.

**Comment by Viish** [comment]
By the way, not only you are using an old and unstable SDK (4.5.0-alpha.62+a749d75), but your org.mircom MiEntry app doesn't seem to respect the GPLv3 opensource license, so I won't help you anymore.
