### ISSUE TITLE
Register Port List

### ISSUE THREAD

**Issue by hasanr68** [BelledonneCommunications/linphone-android#1577]
Hi all.

Some ISP's block port 5060 and the user is unable to register. I realise the "use random ports" toggle is to allow listening on the user agent. I tried changing the sip_port variable in the config file (both default and factory - and uninstalled and reinstalled the app) - however, it still registers on port 5060. Any other way to change that please?

Also - is it possible to maybe have a list of ports added to a list where the app can register and would do so automatically.

Sorry if this has been asked before, but I couldn't find any reference.

**Comment by driesken** [comment]
>  however, it still registers on port 5060
This has nothing to do with the random ports setting but with the port that the remote sip server is listening on (5060). You could try to change the SIP listening port of the remote server.

**Comment by Viish** [comment]
> This has nothing to do with the random ports setting but with the port that the remote sip server is listening on (5060). You could try to change the SIP listening port of the remote server.

That's right. Try changing the configuration of your proxy server so it listen to a different port, like 5223.

**Comment by hasanr68** [comment]
Both of you are giving conflicting statements - but agreeing :) Port on the remote server was listening on multiple ports and we manually added the port in the proxy server setting on the app and it worked. Then I've hard-coded it in the assistant_default_values file and it seems to be working. Hope that is correct.

Any possibility about the second part of the query - about adding a specific list of ports to query please?

**Comment by Viish** [comment]
No, that's not currently possible within the app, but if you are using a SRV record for your domain name you should be able to do it.

**Comment by hasanr68** [comment]
Alright - thanks a lot!
