### ISSUE TITLE
Function invocation 'registerEnabled()' expected 

### ISSUE THREAD

**Issue by SaadChaibanX** [BelledonneCommunications/linphone-android#1580]
after downloading the project from github and opening it in android studio  , when i try to build the apk the got this error here is the screenshoot and error name : 

![Capture-fix -inshallah](https://user-images.githubusercontent.com/83650988/147370657-0dfb9396-93d3-4f31-9efd-7e8abd790709.PNG)

error name :
Function invocation 'registerEnabled()' expected

**Comment by Viish** [comment]
Ensure you are on release/5.1 version of the SDK and release/4.6 branch of the app
