### ISSUE TITLE
CallLog

### ISSUE THREAD

**Issue by skotow** [BelledonneCommunications/linphone-android#1582]
How to remove single record from CallLogs ? if I want to delete only one number from calls in history . what method does that ?

**Comment by skotow** [comment]
core.removeCallLogs(core.CallLogs[index]) it is correct way ?

**Comment by Viish** [comment]
https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Core.html#removeCallLog-org.linphone.core.CallLog-
