### ISSUE TITLE
Chat entry duplication

### ISSUE THREAD

**Issue by MrutyunjayRajan** [BelledonneCommunications/linphone-android#1583]
Hello there,

I am using app latest version with my own SIP server implementation. 
When I am sending any message the address comes with sip:xyz@abc.com
and when I receive any message in reply, the address comes with sip:xyz@192.168.1.102 
i.e. private ip.
Would you please help me with this? 

I am waiting for your reply.

**Comment by Viish** [comment]
This is related to the configuration or behavior of your proxy server, there is nothing we can do about it in the library or the app.

**Comment by MrutyunjayRajan** [comment]
Hi Viish. Thank you for answering that. But, I've tested with linphone app version 2.3 it was working fine with my same proxy server as I am using in latest linphone app. I was working fine with version 2.3. Why it is that?

**Comment by Viish** [comment]
2.3 version is very old, and a that time we didn't checked the TO header to identify a conversation because we didn't supported multiple accounts. Now that we do we have to check the TO header to know to which account the received message is intended for.
