### ISSUE TITLE
Error building project

### ISSUE THREAD

**Issue by leeyushi** [BelledonneCommunications/linphone-android#1584]
Execution failed for task ':app:runKtlintFormatOverMainSourceSet'.
> A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.KtLintWorkAction
   > Failed to run Gradle Worker Daemon
      > Process 'Gradle Worker Daemon 3' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by Viish** [comment]
I don't have such issue.
You can disable ktlint tasks, they are only used for formatting code properly.
