### ISSUE TITLE
Linphone android prefix cannot be disabled

### ISSUE THREAD

**Issue by GrahamJB1** [BelledonneCommunications/linphone-android#1585]
On linphone android the prefix behaviour has changed.

You can see the change my doing the following:

1. Set in SIP Accounts: Prefix for your country=44. Dial 101. Dials: +44101 (see call history)
2. Set in SIP Accounts: Prefix for your country is empty: Dials: +0101 (see call history)

You can no longer enter an empty prefix as empty is translated to +0

Please fix entering an empty prefix in android for a SIP Account

**Comment by Viish** [comment]
What version of linphone-android are you having this issue on?
I don't reproduce it.

**Comment by GrahamJB1** [comment]
This is on Linphone Android 4.5.6 (tags/4.5.6.^0,release)
This is with a SIP account.
It is an pre-existing install where the version was upgraded. I have only just hand the chance to investigate as it broke some time ago, and we have had to rely on calling using dialling history of phone book.
It has happened on multiple handsets.
The symptom is when dialling local numbers (e.g. 102) the dial fails with "User hasn't been found"
Call history shows +0102 as the number, when 102 was typed.
Prefix for your country is set to empty.

**Comment by GrahamJB1** [comment]
When dialling 02071234 I get +002071234 in the call history
When dialling 0201241234 I get +02071241234 in the call history
so what you dial affects whether you get a + or a +0 forcibly prefixed, and there does not appear to be a way to stop this

**Comment by Viish** [comment]
Can you try with public beta version available on the Play Store please?

**Comment by GrahamJB1** [comment]
Confirmed... fixed in latest beta. Many thanks
