### ISSUE TITLE
LinphonePreferences not available in Linphone Android 4.5.5 (Kotlin)

### ISSUE THREAD

**Issue by ahmed847work** [BelledonneCommunications/linphone-android#1586]
Hi,

I was working with Linphone 4.3 which had **LinphonePreferences** class with alot of functions like

- setCodecBitrateLimit
- setAutoStart
- setTurnEnabled
- setServiceNotificationVisibility
- etc....

But now the **CorePreferences** class does not include these functions.

I want the same functions to be available for Linphone Android 4.5.5 as well.

Could you guide me on this?

**Comment by Viish** [comment]
Hi,

Most of these methods no longer exists as they are available through a SDK level API, or simply have just be renamed when I re-wrote the app in Kotlin.
If you need  some, you can simply add them back as-is in CorePreferences object.

Cheers,
