### ISSUE TITLE
Call video shows green

### ISSUE THREAD

**Issue by fengfeilong0529** [BelledonneCommunications/linphone-android#1588]
Hello, when I use linphone 4.4 & 4.2 aar to test the intercom, I found that the video will be displayed in green when there is a device intercom, please help me to see where the problem is? Are there parameters that can be set?
@Viish Help pls!

**Comment by fengfeilong0529** [comment]
I found that it is normal to use VP8 format , but the actual use scene determines the H264 format

**Comment by Viish** [comment]
Duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/1153
