### ISSUE TITLE
Native Crash on Android 8 (mostly Samsung)

### ISSUE THREAD

**Issue by hasanr68** [BelledonneCommunications/linphone-android#1590]
**Describe the bug**
We are getting native crash errors from Google Play Console, mostly on Samsung Android 8. 

**To Reproduce**
Unsure.

**Expected behavior**
App would not crash.

**Please complete the following information**
 - Samsung Galaxy S9
 - Android 8.0 (SDK 26)

**SDK logs**
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/starqlteue/starqlteue:8.0.0/R16NW/G960U1UEU1ARBG:user/release-keys'
Revision: '14'
ABI: 'arm64'
pid: 27939, tid: 27949, name: FinalizerDaemon  >>> org.linphone <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'Fatal object error encountered, aborting.'
    x0   0000000000000000  x1   0000000000006d2d  x2   0000000000000006  x3   0000000000000008
    x4   0000000000000000  x5   0000000000000000  x6   0000000000000000  x7   0000000000000080
    x8   0000000000000083  x9   6cc3ec8c91d99146  x10  0000000000000000  x11  0000000000000001
    x12  ffffffffffffffff  x13  0000000000000038  x14  ffffffffffffffff  x15  00011ee332537f4c
    x16  0000007abba242e8  x17  0000007abb9c5bdc  x18  0000000000000020  x19  0000000000006d23
    x20  0000000000006d2d  x21  0000007aaa70f780  x22  0000007a9bd47898  x23  0000000000000000
    x24  0000007aaa710588  x25  0000007a9ff97f20  x26  0000000000000000  x27  0000000000000005
    x28  0000007aaa70f860  x29  0000007aaa70f0b0  x30  0000007abb9782a4
    sp   0000007aaa70f070  pc   0000007abb9c5be4  pstate 0000000060000000
backtrace:
    #00 pc 000000000006bbe4  /system/lib64/libc.so (tgkill+8)
    #01 pc 000000000001e2a0  /system/lib64/libc.so (abort+88)
    #02 pc 0000000000007f44  /system/lib64/liblog.so (__android_log_assert+304)
    #03 pc 0000000000033310  /data/app/org.linphone-4GLpMo5JMgK2svCbkLQTww==/split_config.arm64_v8a.apk (offset 0x13000)
    #04 pc 00000000009315e4  /data/app/org.linphone-4GLpMo5JMgK2svCbkLQTww==/split_config.arm64_v8a.apk (offset 0x225000)
    #05 pc 000000000093144c  /data/app/org.linphone-4GLpMo5JMgK2svCbkLQTww==/split_config.arm64_v8a.apk (offset 0x225000)
    #06 pc 00000000008c2194  /data/app/org.linphone-4GLpMo5JMgK2svCbkLQTww==/split_config.arm64_v8a.apk (offset 0x225000)
    #07 pc 0000000000510f00  /system/lib64/libart.so (art_quick_generic_jni_trampoline+144)
    #08 pc 0000000000507b84  /system/lib64/libart.so (art_quick_invoke_stub+580)
    #09 pc 00000000000d84f4  /system/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+200)
    #10 pc 00000000002824a4  /system/lib64/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+352)
    #11 pc 000000000027cb6c  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+672)
    #12 pc 00000000004f0708  /system/lib64/libart.so (MterpInvokeDirect+504)
    #13 pc 00000000004f9694  /system/lib64/libart.so (ExecuteMterpImpl+14484)
    #14 pc 000000000025d8e8  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+444)
    #15 pc 00000000004e331c  /system/lib64/libart.so (artQuickToInterpreterBridge+1468)
    #16 pc 000000000051101c  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
    #17 pc 00000000002e7468  /system/framework/arm64/boot-core-libart.oat (offset 0xd7000) (java.lang.Daemons$FinalizerDaemon.doFinalize+104)
    #18 pc 00000000002e7714  /system/framework/arm64/boot-core-libart.oat (offset 0xd7000) (java.lang.Daemons$FinalizerDaemon.runInternal+532)
    #19 pc 00000000002e6e8c  /system/framework/arm64/boot-core-libart.oat (offset 0xd7000) (java.lang.Daemons$Daemon.run+76)
    #20 pc 00000000001fcbfc  /system/framework/arm64/boot-core-oj.oat (offset 0x1dc000) (java.lang.Thread.run+76)
    #21 pc 0000000000507b84  /system/lib64/libart.so (art_quick_invoke_stub+580)
    #22 pc 00000000000d84f4  /system/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+200)
    #23 pc 0000000000430864  /system/lib64/libart.so (_ZN3artL18InvokeWithArgArrayERKNS_33ScopedObjectAccessAlreadyRunnableEPNS_9ArtMethodEPNS_8ArgArrayEPNS_6JValueEPKc+104)
    #24 pc 00000000004319f0  /system/lib64/libart.so (_ZN3art35InvokeVirtualOrInterfaceWithJValuesERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectP10_jmethodIDP6jvalue+432)
    #25 pc 0000000000457f14  /system/lib64/libart.so (_ZN3art6Thread14CreateCallbackEPv+1140)
    #26 pc 0000000000068560  /system/lib64/libc.so (_ZL15__pthread_startPv+36)
    #27 pc 000000000001f9f4  /system/lib64/libc.so (__start_thread+68)

**Additional context**
For the time being we have excluded these phones.

**Comment by Viish** [comment]
Please add a symbolized stack trace using ndk-stack tool.
See https://gitlab.linphone.org/BC/public/linphone-android/-/tree/release/4.6#native-crash for how to do it.

**Comment by hasanr68** [comment]
Hi Viish.
Thanks a lot for the quick response. If I work with the method shared above, I would have to replicate the error locally. Would it be ok if we add native debugging symbols to the aab file to be uploaded to google play store?
Thanks

**Comment by Viish** [comment]
You can but it will make the app size bigger.
Would be best to reproduce it locally.

**Comment by Viish** [comment]
Another solution would be for you to use crashlytics.

**Comment by hasanr68** [comment]
OK - thx a lot. Will revert with updates.

**Comment by hasanr68** [comment]
Hi again.
I added debug symbols to the aab file and then rebuilt by changing minify to false and uploaded character map. The error message is exactly as in original post.

**Comment by Viish** [comment]
Use ndk-stack tool to transform stack trace to symbolized one.

**Comment by hasanr68** [comment]
Thanks a lot for your help. We updated the code base and seems to be working fine now.

**Comment by Viish** [comment]
Your issue seems unrelated to our app & SDK:
```
Abort message: 'thread.cc:2016] No pending exception expected: java.lang.NoSuchMethodError: No static method g(Landroid/content/Context;I)Landroidx/core/graphics/drawable/IconCompat; in class Landroidx/core/graphics/drawable/IconCompat; or its super classes (declaration of 'androidx.core.graphics.drawable.IconCompat' appears in /data/app/androidx.test.tools.crawler-4zvXKjGFuCjNRZocCeYyjg==/base.apk)'
```

**Comment by hasanr68** [comment]
Thanks for clarifying.
