### ISSUE TITLE
Release 4.6 Crash on Samsung J7 - Android 9

### ISSUE THREAD

**Issue by hasanr68** [BelledonneCommunications/linphone-android#1592]
**Describe the bug**
I downloaded, built v4.6 and installed on Samsung J7 (Android 9), it asks for permission(s) and I grant them. When I return to the app - it crashes.

**To Reproduce**
1. Launch app. Give permissions.
2. Exit app.
3. Launch app. 
4. Crash.

**Expected behavior**

**Please complete the following information**
 - Device: Samsung J7 Core
 - OS: Android 9
 - 4.6

**SDK logs**
https://www.linphone.org:444//tmp/61e3d56154eff_cadcfc8678f548d190ae.gz

**Comment by Viish** [comment]
Weird.
Please attach crash stack trace using adb logcat.

**Comment by hasanr68** [comment]
Hi @Viish I am trying to replicate the issue. I think it was happening on a day with bad Wi-Fi connectivity. So the Wi-Fi symbol was with an exclamation mark. I will keep trying and share the logs, if it happens again.

**Comment by Viish** [comment]
Thanks.

There are two issues:
First one is this: `java.lang.ClassNotFoundException: Didn't find class "androidx.window.sidecar.SidecarInterface$SidecarCallback"`. Did you made changes to the app?
It seems to be related to the `WindowInfoTracker` API we use for foldables devices.

The other one is `java.lang.SecurityException: Permission Denial: broadcast from android asks to run as user -1 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS` and is triggered by call to `reportFullyDrawn()` method.

If you haven't made any changes, this means there is a serious issue on your device firmware.

**Comment by hasanr68** [comment]
@Viish - thanks again. No, didn't make any changes. Just downloaded, built and installed the app.

**Comment by Viish** [comment]
Do you have the same issue if you install the beta version of the app through the PlayStore?

**Comment by hasanr68** [comment]
No, beta version from Playstore is working fine.

**Comment by Viish** [comment]
Ok so issue only happens when you build the app yourself?
I've pushed a fix anyway to catch the SecurityException if it happens, should fix your issue.

**Comment by hasanr68** [comment]
Thanks a lot.
