### ISSUE TITLE
How to change the size of the video definition in a video call

### ISSUE THREAD

**Issue by leeyushi** [BelledonneCommunications/linphone-android#1593]
It cannot be changed with the following code, a new video call must be established to take effect
VideoDefinition preferredVideoDefinition = call.getCurrentParams().getReceivedVideoDefinition();
preferredVideoDefinition.setHeight(1280);
preferredVideoDefinition.setWidth(720);
PhoneHolder.get().getCore().setPreferredVideoDefinition(preferredVideoDefinition);

**Comment by Viish** [comment]
Indeed you can't change the video size during a call.
Even if you could, there are several optimizations for bandwidth that may change it during the call automatically.
