### ISSUE TITLE
Latest kotlin Build issue

### ISSUE THREAD

**Issue by anujvats111** [BelledonneCommunications/linphone-android#1594]
Hello Team,

I am trying to build kotlin based code in android studio. But i am getting this issue. 

Found 3 data binding error(s)
Found 3 data binding error(s)
==================================================
cannot find method ephemeralEnabled() in class org.linphone.core.ChatRoom
Open File
==================================================
cannot find method ephemeralEnabled() in class org.linphone.core.ChatRoom
Open File
==================================================
cannot find method ephemeralEnabled() in class org.linphone.core.ChatRoom
Open File

**Comment by Viish** [comment]
Which branch of the app are you building? With which version of our SDK?

**Comment by anujvats111** [comment]
I am downloading from here 
https://github.com/BelledonneCommunications/linphone-android

**Comment by Viish** [comment]
Yes but which branch? You should use release/4.6 branch.

**Comment by anujvats111** [comment]
Yes working....

Thanks
