### ISSUE TITLE
Background mode (notification) doesn't open automatically

### ISSUE THREAD

**Issue by tasosb** [BelledonneCommunications/linphone-android#1595]
**Description**
The notification of "Background mode" from Advanced Settings (when setting is enabled) doesn't show up on app startup 

**To Reproduce**
Go to Settings>Advanced>Enable "Background mode"
Open the menu
Click on "Quit"
_Check: The app and notification close_
Open again Linphone
**Expected**: The notification appears on app startup
**Actual**: The notification doesn't appear,  unless you navigate to Settings>Advanced.

**Please complete the following information**
 - Device: Samsung A21s
 - OS: Android 11
 - Version of the App: 4.5.6
 - Version of the SDK: 5.0.49

**SDK logs**
https://pastebin.com/QmudMybu

**Comment by Viish** [comment]
Hi,

Thanks for the report.
Fix has been made in release/4.6 branch for next release: 81884dd218302cc41a03d17fe4f9e330132401e2

Cheers,
