### ISSUE TITLE
[enhancement] option of 1080p video call?

### ISSUE THREAD

**Issue by basncy** [BelledonneCommunications/linphone-android#1599]
Can we provide an option of 1080p definition on video call?
most mobile hardware, 4G LTE, 5G wifi could support FHD video call now.

**Comment by Viish** [comment]
This is already done in release/5.1 branch of the SDK

**Comment by basncy** [comment]
Great, thanks.
The current Linphone is 4.5.6, with SDK 5.0.49, hope it could be available on the next release.

**Comment by Viish** [comment]
You can already try 4.6.0 android app with 5.1 SDK on the Play Store by subscribing to the public beta channel.

**Comment by basncy** [comment]
Content-Type: message/cpim can't be forwared by legacy sip server like asterisk.
Although I can modify asterisk to transfer message/cpim, how about others?

The payload of message/cpim is still plain text, and other MIME headers could be used according to [https://datatracker.ietf.org/doc/html/rfc3862#section-2.1](url) can we interpret it inside linphone client like the XML interpreter? thus these rich text messages could be forwared by most sip servers as Content-Type: text/plain?

**Comment by basncy** [comment]
We can insert some advertisements in the header if the sip client doesn't interpret it, to suggest users using/upgrading linphone client to read these cpim message. e.g. send from linphone 4.6.0

**Comment by basncy** [comment]
Or provide an option of "Compatibility Mode" for message/cpim. (for none flexisip server) 
For outing messages, send as text/plain rather than message/cpim.
For incoming messages, check the message body and replace text/plain with message/cpim if keyword detected.

**Comment by Viish** [comment]
I understand that CPIM can be an issue with some proxy servers, that's why we only enable it on accounts that register on sip.linphone.org server.
I guess you have forked the app and changed the corePreferences.defaultDomain value?
If sp you can disable this behavior here: https://gitlab.linphone.org/BC/public/linphone-android/-/blob/release/4.6/app/src/main/java/org/linphone/core/CoreContext.kt#L389

**Comment by basncy** [comment]
I guess you have forked the app and changed the corePreferences.defaultDomain value? No

I download 4.6.0 from google play only.
Test case 1:  login to my asterisk account and send message to asterisk, asterisk reply with 415 Unsupported Media Type.
Test case 2:  client app data reset, login linphone account and send message to my asterisk account, asterisk reply with 415 Unsupported Media Type.

BTW, I saw 
Content-Encoding: deflate
Content-Type: message/cpim
sent to asterisk if is-composing triggered. 
Header Content-Encoding: deflate will be eaten by asterisk, some error might happen if force Content-Type to text/plain, nor let asterisk bypass message/cpim.

**Comment by Viish** [comment]
If you use a linphone account it is expected to enable CPIM for messages, but if you use your own asterisk account it shouldn't.
If it does, please attach logs.

**Comment by basncy** [comment]
To my reply of  For outing messages, send as text/plain rather than message/cpim.  I mean change the SIP MESSAGE header Content-Type: message/cpim to Content-Type: text/plain, while keeping the message boday as CPIM format.

Here is the log with my own asterisk account from app data reset.
https://www.linphone.org:444//tmp/61fcece53ce8c_dfec342ab0122df0ef29.gz

**Comment by Viish** [comment]
Thanks for the logs, everything is working as expected.

Your `ttttttttttttt` message is correctly sent out as plain/text, it's only the composing message that is sent as CPIM but this is normal, it's required. And if your proxy server doesn't understand it it's no big deal as the information isn't crucial.

**Comment by basncy** [comment]
asterisk REFUSE the SIP MESSAGE with Content-Type: message/cpim, line 921
Content-Type: text/plain, line 933, is the CPIM body, not SIP header.

**Comment by Viish** [comment]
My bad, I looked too quickly, you are right.
I'll fix the issue.

**Comment by basncy** [comment]
Great! the idea solution is sent CPIM as Content-Type:  text/plain SIP MESSAGE for none linphone account, and disable Content-Encoding: deflate for compatibility. Thus none linphone account could enjoy your app features, such as is-composing, voice-record, and attachment sending.

**Comment by basncy** [comment]
Hi. viish
i saw build an apk with your commit 
0232ae5be2426c6cb1ac9673af4dde2497faa233

Still not work if message goes between linphone account and my asterisk account. linphone acoount is isolated. I dont know how many user will go into this case.

linphone -> asterisk, SIP header is CPIM, refused by asterisk
asterisk -> linphone, SIP header is text/plain, app recieved and displayed in notification but cant display in chatroom.

my proposal is:
for outing msg, maybe simply provide an option of replacing message/cpim, line 921 with text/plain in legacy sip server environment.
for incoming msg with text/plain sip header, check the body if need to handle with CPIM format.

**Comment by Viish** [comment]
Hi,

> linphone -> asterisk, SIP header is CPIM, refused by asterisk

This is expected as we have decided to enable CPIM on linphone accounts.
Your scenario isn't the mainstream one as linphone accounts communication mainly with other linphone accounts.
Maybe you can configure your asterisk to accept CPIM messages?

> asterisk -> linphone, SIP header is text/plain, app recieved and displayed in notification but cant display in chatroom.

This is probably because of the TO header of the asterisk that doesn't match your local account SIP identity. 
This is a known issue with asterisk servers...

**Comment by basncy** [comment]
Maybe you can configure your asterisk to accept CPIM messages?
its ok in my personal case at this moment. 
If so 
1. how can i  enable CPIM in other account, except rebuild app on all platform.
2. sip message header with Content-Encoding: deflate might not handle (will be eaten) in asterisk, can you move it into message body as part of CPIM?

Regarding To header, latest asterisk sovled this issue, and it works on my linphone 4.5.

**Comment by basncy** [comment]
Content-Encoding: deflate usually composed with imdn witch triggered from app side, app could disable this encoding header.

in case of imdn report with 
Content-Encoding: deflate
Content-Type: message/cpim
togerther, and asterisk eat header deflate result in the reciever goes error.

**Comment by Viish** [comment]
Deflate is a compression algorithm, so yes if your asterisk removes it message won't be readable anymore.
Try to find a way to configure asterisk to keep this header.

**Comment by basncy** [comment]
I don't know if the asterisk team will accept this change request.

BTW, try to bring up an MVP configuration of flexisip server, but flexisip stop with
belr-error-Could not open /usr/local/share/belr/grammars/authdb-file-grammar
Could not load grammar for authdb-file from '/usr/local/share/belr/grammars/authdb-file-grammar'
How to download/build/configure/disable authdb-file-grammar?

**Comment by basncy** [comment]
Re:  Try to find a way to configure asterisk to keep this header.
Try to allow all content-type and manually append but failed. message sent out but not marked as read.
same => n,ExecIf($["${MESSAGE_DATA(Content-Type)}" = "message/imdn+xml"]?Set(MESSAGE_DATA(Content-Encoding)=deflate))

Before asterisk diaplan
CSeq: 21 MESSAGE
Call-ID: 2PqF-~ZLUX
Max-Forwards: 70
Supported: replaces, outbound, gruu
Date: Mon, 07 Feb 2022 09:47:38 GMT
Content-Encoding: deflate
Content-Type: message/imdn+xml
Content-Length: 201

After asterisk diaplan
Call-ID: 3d73e79f-5d15-4d01-b052-eda6a91d467e
CSeq: 64669 MESSAGE
Content-Encoding: deflate
Max-Forwards: 70
User-Agent: sip
Content-Type: message/imdn+xml
Content-Length:   201
===================================
Another workaround for asterisk is DROP this deflate message if I allow all CPIM. (currently it response with 415 unsupported content-type message/imdn+xml)
same => n,ExecIf($["${MESSAGE_DATA(Content-Encoding)}" = "deflate"]?Hangup())

**Comment by basncy** [comment]
Finally, add
`same => n,ExecIf($["x${MESSAGE_DATA(Content-Encoding)}" = "xdeflate"]?Hangup())`
into asterisk dialplan in all possible place to avoid imdn flood when modify asterisk code to allow all content-type.

**Comment by basncy** [comment]
> belr-error-Could not open /usr/local/share/belr/grammars/authdb-file-grammar
I use mysql to skip this error.

yet another question, how to config flexisip.conf to interact with external domain? e.g.  sip.linphone.org <---> sip.example.org, where sip.example.org is hosted with flexisip.
flexisip says 407 Proxy Authentication Required on both direction.

**Comment by Viish** [comment]
Sorry but I can't help much with that, not my area of expertise.
Feel free to open an issue in the flexisip repository if you don't find your answer on our wiki: https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/

**Comment by basncy** [comment]
I changed items in assistant_default_values then things worked. I guess it might be introduced by STUN/ICE config loss.

<entry name="nat_policy_ref" overwrite="true">nat_policy_default_values</entry>
<entry name="protocols" overwrite="true">stun,ice</entry>
