### ISSUE TITLE
[Feature request] An F-Droid-compatible repository for Linphone

### ISSUE THREAD

**Issue by marmistrz** [BelledonneCommunications/linphone-android#16]
Many privacy-focused users refuse to install Play Services and, as a consequence, the Play Store client. Their main software source is usually F-Droid. 

F-Droid itself has, on the other hand, very strict policies about building applications from source, so it doesn't contain a self-built release of Linphone 3.2+, while running outdated versions of software poses a potential security risk.

It would be great if Linphone could provide an F-Droid compatible repository, such as Antox does [1]. The instructions for setting such repo up with an existing infrastructure are not overly complex. [2]

[1] https://pkg.tox.chat/fdroid/repo/
[2] https://f-droid.org/wiki/page/Setup_an_FDroid_App_Repo

**Comment by DatBewar** [comment]
Hello,
I will see what can we do to make it.
Best regards

**Comment by DatBewar** [comment]
I have tried to make a repo, if you can try this:
https://www.linphone.org/releases/android/fdroid/repo/

Best regards

**Comment by marmistrz** [comment]
Thanks!

F-Droid recognized this repository but claims there are 0 apps there.

**Comment by DatBewar** [comment]
Ah ok, i think i forgot meta data

**Comment by DatBewar** [comment]
I made some change with metadata but i don't know if it's ok, can you try please?

**Comment by marmistrz** [comment]
Still number of apps equals zero.

**Comment by DatBewar** [comment]
My problem is, i don't know how to create Metadata for linphone apk.

**Comment by marmistrz** [comment]
I guess you could ask at the F-Droid IRC channel. The people there are pretty helpful.

**Comment by pserwylo** [comment]
There are two places to learn about metadata. One is the [server manual](https://f-droid.org/manual/fdroid.html#Metadata) (which is linked to from the https://f-droid.org/wiki/page/Setup_an_FDroid_App_Repo page linked above). The other, which I often find much more helpful is the [actual list of metadata for all the apps in the main F-Droid repo](https://gitlab.com/fdroid/fdroiddata/tree/master/metadata).

I find it easier to clone that repository, and then grep through the `metadata/` directory for anything that seems relevant to me.

Is there any specific metadata you're curious about (e.g. description/summary/etc?)

**Comment by marmistrz** [comment]
Alternatively, it may be an even better idea to simply modify the upstream git repository so that F-Droid can build it itself. This would fix another problem with the official apks that it depends on non-free Google Play Services for GCM.

Currently the problem are the jars laying here and there: https://f-droid.org/wiki/page/org.linphone
They should be built from source when building the whole Linphone apk. Currently the problem is: `antlr3/antlr-3.4-complete.jar`.

**Comment by herbsmn** [comment]
Just so that everyone is on the same page on this, here's the F-Droid issue related to updating Linphone in their main repo: https://gitlab.com/fdroid/fdroiddata/issues/588

I have found that good communication can often move mountains.

@DatBewar: Do you know what blockers still exist that prevent Linphone from being added to F-Droid? I'll ask them the same question. I'm confident that we can work this out if we all put our heads together. Also, thanks for the work you do on this wonderful app. It is very much appreciated.

**Comment by relan** [comment]
F-Droid maintainer here. I've built Linphone 3.3.0 locally with F-Droid tools, but there are a few obstacles preventing me from pushing the update:

1. Firebase and GCM libraries are proprietary software. So I removed them both. Will Linphone work properly without them?
2. `build.gradle` does not specify versions of dependencies, i.e. the latest versions will be used. This can cause various issues depending on the build date as newer versions the Support Library may introduce backward-incompatible changes. Please use specific versions.
3. The [site says](https://www.linphone.org/technical-corner/linphone/downloads) Linphone is licensed under GPLv2. It's [incompatible with Apache 2.0 license](https://www.apache.org/licenses/GPL-compatibility.html) and thus may not link against Android Support Library. Is this just a mistake and actual license is "GPLv2 or later"? GPLv3 resolved this compatibility issue.

**Comment by DatBewar** [comment]
Hi,

1. Yes Linphone will work properly without them.
2.  I will set specific versions.
3. The Linphone license is "GPLv2 or later".

**Comment by relan** [comment]
Thanks for clarifying!

Now the only issue is prebuilt Antlr3 JAR(s). Any chance to pull it from Maven Central at build time (e.g. as a Gradle dependency) or build from source code?

**Comment by herbsmn** [comment]
@DatBewar: may peace be with you. any chance you've been able to look into @relan's last question?

**Comment by DatBewar** [comment]
Sorry for the delay
You can found Antlr3 JAR on our submodule
[submodule "submodules/externals/antlr3"]
	path = submodules/externals/antlr3
	url = git://git.linphone.org/antlr3.git

**Comment by relan** [comment]
@DatBewar, no problem, thanks for answering.

Is antlr3 even needed for Android version? I've removed submodules/externals/antlr3 and compiled Linphone successfully.

**Comment by DatBewar** [comment]
Antlr3 is only used for the compilation of Linphone SDK

**Comment by relan** [comment]
Linphone 3.3.0 is finally [available on F-Droid](https://f-droid.org/wiki/page/org.linphone#3.3.0)! Thanks for answering my questions and being patient. :)

**Comment by marmistrz** [comment]
Since Linphone is on F-Droid, I think this can be closed :) Thanks a lot!
