### ISSUE TITLE
Disable incoming call

### ISSUE THREAD

**Issue by abhay222** [BelledonneCommunications/linphone-android#1600]
Is there any way in which i can disable all incoming call. 
I and not showing any call popup for incoming call but phone keeps vibrating when there is incoming call.

**Comment by basncy** [comment]
Some mobile bought from China like Huawei will behave like this unless you open the app icon manually. iOS callkit is still forbidden, go ahead.

**Comment by Viish** [comment]
There is no way to do that automatically, but feel free to fork the project and implement it.
As it seems very specific to your need you'll understand we won't add such feature into our app.
