### ISSUE TITLE
Allow automatic call recording

### ISSUE THREAD

**Issue by user01515** [BelledonneCommunications/linphone-android#1602]
Like the title says; it would be nice to have a setting that enables call recording for all calls automatically, without first having to press the record button.

**Comment by Viish** [comment]
Hi,
It's already been added, it will be part of 4.6 release (already available in public beta channel on the play store).

**Comment by user01515** [comment]
Okay, thank you. Any word when that release will be available on F-Droid?

**Comment by Viish** [comment]
Probably soon after Play Store release, but as we aren't in charge of the F-Droid build, all I can do is notify them of the new version.

**Comment by wtwangcb** [comment]
Automatic call recording not working on Android 8.0  (HUAWEI MATE 8)
Only manual recording works

**Comment by Viish** [comment]
@wtwangcb please attach logs showing the issue.
By the way, I removed your comment from "Improvement Ideas" issue.
