### ISSUE TITLE
Linphone Android background service won't exit after "Quit"

### ISSUE THREAD

**Issue by eljoest** [BelledonneCommunications/linphone-android#1603]
**Describe the bug**
Since the update to Linphone Android 4.6.0 (tags/4.6.0^0, release) the background service stays active even after going to linphone's menu and selecting quit.

Android 11

**To Reproduce**
Initial setup:
- Configure a SIP account
- Configure "Background mode" in Settings - Advanced

1. Open linphone (Android), confirm it's connected to your configured account and the "Linphone Service" icon is present in Android's tray.
2. Tap the app's menu icon (four bars upper left corner)
3. Select "Quit"
4. Linphone UI closes
5. "Linphone Service" remains

**Expected behavior**
At step 5 the linphone service should exit and stop keeping the device awake.

**Please complete the following information**
 - Device: OnePlus 8 Pro
 - OS: Android 11
 - Version of the App 4.6.0 from Play Store
 - Version of the SDK 5.1.0

**SDK logs**
https://www.linphone.org:444//tmp/6204c2b99e9ce_8fda77573f66b504c7f2.gz

**Additional context**
Used to work as expected before the app update. Not sure which version that was.

**Comment by Viish** [comment]
Hi,

Indeed this is an issue.
I'll fix it for the next release (4.6.1).

Cheers,

**Comment by Viish** [comment]
Fix is available in commit 8674a2b7
