### ISSUE TITLE
Feature request: smaller font rather than a scrolling text in menu items

### ISSUE THREAD

**Issue by twisteros** [BelledonneCommunications/linphone-android#1606]

**Comment by Viish** [comment]
Already done in 4.6.0 release.

**Comment by twisteros** [comment]
I didn't know 4.6 was released.
Are you planing to put that version on F-Droid?

**Comment by Viish** [comment]
According to https://gitlab.com/fdroid/fdroiddata/-/issues/2473#note_820930047 it should be available soon.
