### ISSUE TITLE
Improvement: The Linphone service notification bar could be shorter

### ISSUE THREAD

**Issue by twisteros** [BelledonneCommunications/linphone-android#1608]
The service notification bar takes up much space causing other notification to roll down.
I like the way they did it in the baresip project where the bar is about 30% shorter.

![image](https://user-images.githubusercontent.com/18228956/153496374-ea60fd75-f64e-4cad-8a27-428089570843.png)

**Comment by Viish** [comment]
Fixed in 6.0.0 alpha now available in master branch.
