### ISSUE TITLE
Missing core directory

### ISSUE THREAD

**Issue by 100benj** [BelledonneCommunications/linphone-android#161]
I cannot find the org.linphone.core library in this project. I am having an unresolved symbol core but I don't know how to fix it.

**Comment by JoeDD** [comment]
You need to make sure that the download fully contains submodules

**Comment by 100benj** [comment]
submodule folder does not contain 'core'

**Comment by JoeDD** [comment]
![image](https://user-images.githubusercontent.com/21697771/33009270-4c5c27da-ce11-11e7-87ee-d5aae320f8d1.png)
are you sure you added "--recursive"?

**Comment by 100benj** [comment]
Sorry. where should I enter the command?

**Comment by 100benj** [comment]
I have download the missing directories [here](http://linphone.org/technical-corner/linphone/downloads). thanks for the help @JoeDD.
