### ISSUE TITLE
Not able unregister sip

### ISSUE THREAD

**Issue by anujvats111** [BelledonneCommunications/linphone-android#1613]
Hello Guys

I am using linphone java version. But I am getting an major issue. Actually I am not able unregistered sip. All accounts are showing registered. I have tried many ways like unregister proxy, core but result still same. Is it possible anyone can help me to fix it out ?

Thanks
Anuj Sharma.

**Comment by Viish** [comment]
Hi,
To unregister an Account simply set isRegisterEnabled=false on the AccountParam object.
See https://gitlab.linphone.org/BC/public/linphone-android/-/blob/release/4.6/app/src/main/java/org/linphone/activities/main/settings/viewmodels/AccountSettingsViewModel.kt#L195
Cheers,

**Comment by anujvats111** [comment]
It's not working.
I am using sdk 4.4+  still showing same issue.

**Comment by anujvats111** [comment]
> Hi, To unregister an Account simply set isRegisterEnabled=false on the AccountParam object. See https://gitlab.linphone.org/BC/public/linphone-android/-/blob/release/4.6/app/src/main/java/org/linphone/activities/main/settings/viewmodels/AccountSettingsViewModel.kt#L195 Cheers,

It's not working.
I am using sdk 4.4+ still showing same issue.

**Comment by Viish** [comment]
4.4 SDK doesn't have AccountParam API, it's only for 5+.

**Comment by anujvats111** [comment]
Is there any other option for un register sip ?

Thanks

**Comment by Viish** [comment]
On SDK < 5.0 the only way is to use https://download.linphone.org/releases/docs/liblinphone/4.5/java/org/linphone/core/ProxyConfig.html#enableRegister-boolean-
Starting 5.0 ProxyConfig API has been deprecated (but can still be used), the proper way is to use Account & AccountParams APIs has explained above.

**Comment by anujvats111** [comment]
Okay thanks @Viish 
And how i can enable the push notification switch by default in android kotlin version ?

**Comment by Viish** [comment]
https://download.linphone.org/releases/docs/liblinphone/5.1/java/org/linphone/core/AccountParams.html#setRemotePushNotificationAllowed-boolean-
