### ISSUE TITLE
 Can't start Video after call established-4.6.1-android-9

### ISSUE THREAD

**Issue by basncy** [BelledonneCommunications/linphone-android#1614]
Reproduce: A is using linphone-android 4.6.1

    A call B voice only.
    B answer.
    A enable Video.
    error happens.
    https://www.linphone.org:444//tmp/620b44dbe96d5_84e07e193817900cc28d.gz
    http://129.146.185.197:8880/d/logcat.log  (another reproduce instance)

What works:
case 1. A place a video call to B at the beginning.
case 2. B enable video after call established.

**Comment by Viish** [comment]
The re-INVITE with video is never sent out, it seems to be due to an ICE negotiation issue.
Have you tried with two devices on sip.linphone.org or on your sip.linuxe.org server? 
Also you can try to disable ICE to see it that fixes your issue.

**Comment by basncy** [comment]
new cases, move A into LTE network, B still under a router.
non ICE works.
with ICE, video not work. http://129.146.185.197:8880/d/4.png

**Comment by basncy** [comment]
Are there any settings in assistant_linphone_default_values that impact this behavior?
I log in to a Linphone account, then change the username, password, domain, proxy server, stun server to my own server, video could start.

**Comment by Viish** [comment]
Linphone account default value are there: https://gitlab.linphone.org/BC/public/linphone-android/-/blob/release/4.6/app/src/main/assets/assistant_linphone_default_values

**Comment by basncy** [comment]
I changed items in assistant_default_values then things worked. I guess it might be introduced by STUN/ICE config loss.
`
<entry name="nat_policy_ref" overwrite="true">nat_policy_default_values</entry>
<entry name="protocols" overwrite="true">stun,ice</entry>
`

**Comment by Viish** [comment]
Thanks, I'll take a look at it tomorrow.

**Comment by Viish** [comment]
Hi,
This is fixed in ddffecb4eb75b2f1d56d20e80d2b010a63eb8296, that will be part of 4.6.2 release.
Cheers,
