### ISSUE TITLE
linphone-sdk-android:4.5+ auth check issue

### ISSUE THREAD

**Issue by anujvats111** [BelledonneCommunications/linphone-android#1615]
Hello,
I am using linphone-sdk-android:4.5+ java version. but not able to check sip valid or invalid same as koltin version. is it any way i can do in same sdk?

**Comment by Viish** [comment]
Hi,
What do you mean by `check sip valid or invalid`? Do you want to know if the credentials are valid?
If so, create your Account object with them and wait for registrationStateChanged listener to see if it fails or succeed.
Cheers,
