### ISSUE TITLE
Conference Call not working

### ISSUE THREAD

**Issue by darshanaPlusinfosys** [BelledonneCommunications/linphone-android#1616]
When doing audio conference getting 'CreationPending' result from Conference State.
I m using  core.addAllToConference() to create a conference call. Can anyone help me?

I am trying to use Linphone SDK in my app and tried to make audio conference  work since last 2 days but got no success.

**Comment by Viish** [comment]
What SDK are you using?

**Comment by darshanaPlusinfosys** [comment]
I m using 'org.linphone:linphone-sdk-android:5.1.0'

**Comment by darshanaPlusinfosys** [comment]
Conference Audio call issue is related to sdk?
I also tried with older version of sdk but got no success with that also.

**Comment by Viish** [comment]
I don't know for `addAllToConference()` method, but you can create a conference like that (like we do in linphone-android app):
```
val params = core.createConferenceParams()
val conference = core.createConferenceWithParams(params)
conference?.addParticipants(core.calls)
```

**Comment by darshanaPlusinfosys** [comment]
I m also done with above method which you have describe.
but the problem is list of users who joined a conference just get  'creationPending' state for conference audio call.

**Comment by Viish** [comment]
Can you attach logs please?

**Comment by HemangiVekaria** [comment]
Please check log. 

https://we.tl/t-7pZQ0VJUg5

**Comment by HemangiVekaria** [comment]
I m creating a conference with 2 user 1 admin.  
A calls user B
A calls user C
then A merge call with B n C.
but b n c not getting conference state.

**Comment by HemangiVekaria** [comment]
https://we.tl/t-rAueaasxy5

**Comment by Viish** [comment]
The SUBSCRIBE sent by B and C is never acknowledged by your proxy (no 200 OK) and A never receives them, so it won't send any NOTIFY, and that's why your conference creation is still pending.
Check your proxy logs and/or settings.
