### ISSUE TITLE
5.1.0 SDK: X509 - Certificate Verification Failed

### ISSUE THREAD

**Issue by jeremynorman89** [BelledonneCommunications/linphone-android#1620]
We are using the 5.1.0 SDK and have seen a significant amount of users reporting call audio not working and inspecting some logs from these users we always see this message almost immediately after a call is connected. 

```
Channel [0x78db219ec0]: SSL handshake failed : X509 - Certificate verification failed, e.g. CRL, CA or signature check failed
Cannot connect to [TLS://x.x.x.x:5061]
```

This was not happening before we upgraded to 5.1.0 (from 5.0.x), although at the same time as this upgrade we also migrated from ProxyConfigs to Accounts.

Unfortunately this is not something we can reproduce in-house and our minimum logging is _Warning_ for users so we don't have any more detailed logs.

I completely understand this is difficult to resolve based on this information so really I'm just wondering if this is possibly a known issue and/or we could be pointed in the right direction to resolve it.

**Comment by Viish** [comment]
What's your domain name so I can check whether or not this is an issue in our rootca?

**Comment by jeremynorman89** [comment]
It's `sip.encryptedsip.com`. Though my assumption would be that if it genuinely was a certificate issue, that it would happen 100% of the time.

**Comment by Viish** [comment]
SRV record is pointing to 2 servers:
```
2022-02-23 11:13:42.794 17649-17649/org.linphone.debug I/belle-sip: SRV _sips._tcp.sip.encryptedsip.com resolved to [target:sip-grq.encryptedsip.com. port:5061 prio:20 weight:0]
2022-02-23 11:13:42.794 17649-17649/org.linphone.debug I/belle-sip: SRV _sips._tcp.sip.encryptedsip.com resolved to [target:sip-ams.encryptedsip.com. port:5061 prio:10 weight:0]
```
It's possible one of them has an expired certificate and not the other.

**Comment by jeremynorman89** [comment]
I can't find any correlation between which domain was picked and the the users that have the issue, we also have other SIP clients/hardphones connecting to these without problem. And manually specifying either of these doesn't allow us to reproduce it.

So unfortunately I don't think that's it.

As some additional context, we did have a previous similar issue where certificate verification was failing when a user switched network. This seemed to be because it was attempting to verify the certificate based on the IP rather than the domain name. 

When it was successful we would see this:

```
Connected at TCP level, now doing TLS handshake with cname=sip.encryptedsip.com
```

But when it failed we would see:

```
Connected at TCP level, now doing TLS handshake with cname=195.35.114.41
```

This looked to be resolved by specifying the transport like so, which was an oversight not to include:

```
accountParams.serverAddress = sip:sip.encryptedsip.com;transport=tls
```

Could this be related? I can't confirm the same thing is happening here as I'm not able to reproduce this particular issue with debug logs as previously mentioned. The network switch was something we could reproduce easily in-house with any phone.

**Comment by Viish** [comment]
> Connected at TCP level, now doing TLS handshake with cname=195.35.114.41

This shouldn't happen. As you say you reproduce this one, can you attach debug logs please?

**Comment by Viish** [comment]
> I can't find any correlation between which domain was picked and the the users that have the issue, we also have other SIP clients/hardphones connecting to these without problem. And manually specifying either of these doesn't allow us to reproduce it.

Could it be they are connected to a network with a "bad" DNS server that sends them to an unexpected server?

**Comment by jeremynorman89** [comment]
> > Connected at TCP level, now doing TLS handshake with cname=195.35.114.41
> 
> This shouldn't happen. As you say you reproduce this one, can you attach debug logs please?

Here are the debug logs, this is for the original reproducible issue that would happen after network switching:

[linphone-logs-cert-verification-error.txt](https://github.com/BelledonneCommunications/linphone-android/files/8123722/linphone-logs-cert-verification-error.txt)

**Comment by jeremynorman89** [comment]
Interestingly I can't reproduce this error with network switching if I specify one of the SRV domains (e.g. `sip-grq.encryptedsip.com`) rather than `sip.encryptedsip.com`.

**Comment by Viish** [comment]
Closing as it isn't a linphone-android issue (it isn't a linphone-sdk issue either).
