### ISSUE TITLE
#00 pc 0003a4e4 /system/lib/libc.so (tgkill+12) [armeabi-v7a::05a6ab5701c3562bf570c82f6a188566]

### ISSUE THREAD

**Issue by Berlin-Lu** [BelledonneCommunications/linphone-android#1621]
May I ask where the error comes from and I have not found a way to solve it
1
#00 pc 0003a4e4 /system/lib/libc.so (tgkill+12) [armeabi-v7a::05a6ab5701c3562bf570c82f6a188566]
2
#01 pc 00017499 /system/lib/libc.so (pthread_kill+52) [armeabi-v7a::05a6ab5701c3562bf570c82f6a188566]
3
#02 pc 000180b7 /system/lib/libc.so (raise+10) [armeabi-v7a::05a6ab5701c3562bf570c82f6a188566]
4
#03 pc 00014855 /system/lib/libc.so (__libc_android_abort+36) [armeabi-v7a::05a6ab5701c3562bf570c82f6a188566]
5
#04 pc 0001303c /system/lib/libc.so (abort+4) [armeabi-v7a::05a6ab5701c3562bf570c82f6a188566]
6
#05 pc 00007c65 /system/lib/libcutils.so (__android_log_assert+88) [armeabi-v7a::dc4622d7d436798442e4becef9c54e86]
7
#06 pc 0006c837 /system/lib/libstagefright.so (android::ACodec::ExecutingToIdleState::onOMXEvent(OMX_EVENTTYPE, unsigned int, unsigned int)+154) [armeabi-v7a::9da96bba8ea7bc4aeca02c25debb711c]
8
#07 pc 0006cb03 /system/lib/libstagefright.so (android::ACodec::BaseState::onOMXMessage(android::sp<android::AMessage> const&)+342) [armeabi-v7a::9da96bba8ea7bc4aeca02c25debb711c]
9
#08 pc 0006cd51 /system/lib/libstagefright.so (android::ACodec::BaseState::onMessageReceived(android::sp<android::AMessage> const&)+84) [armeabi-v7a::9da96bba8ea7bc4aeca02c25debb711c]
10
#09 pc 0000b825 /system/lib/libstagefright_foundation.so (android::AHierarchicalStateMachine::handleMessage(android::sp<android::AMessage> const&)+44) [armeabi-v7a::440a9fd08de726d5075aaa173bb89a59]
11
#10 pc 00063f2b /system/lib/libstagefright.so [armeabi-v7a::9da96bba8ea7bc4aeca02c25debb711c]
12
#11 pc 0000c5ab /system/lib/libstagefright_foundation.so (android::ALooperRoster::deliverMessage(android::sp<android::AMessage> const&)+166) [armeabi-v7a::440a9fd08de726d5075aaa173bb89a59]
13
#12 pc 0000bf2d /system/lib/libstagefright_foundation.so (android::ALooper::loop()+220) [armeabi-v7a::440a9fd08de726d5075aaa173bb89a59]
14
#13 pc 00010531 /system/lib/libutils.so (android::Thread::_threadLoop(void*)+112) [armeabi-v7a::b31c3bf41add412dddf8b266167f21ea]
15
#14 pc 000100a1 /system/lib/libutils.so [armeabi-v7a::b31c3bf41add412dddf8b266167f21ea]
16
#15 pc 00016c83 /system/lib/libc.so (__pthread_start(void*)+30) [armeabi-v7a::05a6ab5701c3562bf570c82f6a188566]
17
#16 pc 00014bbf /system/lib/libc.so (__start_thread+6) [armeabi-v7a::05a6ab5701c3562bf570c82f6a188566]
18
java:
19
[Failed to get Java stack]

**Comment by Viish** [comment]
Looks like this crash isn't related to our SDK given that none of the stack entry is one of our library, so I'm sorry but I can't help much.
