### ISSUE TITLE
Having a echo for other side person in both outbound and inbound call

### ISSUE THREAD

**Issue by disolaterX** [BelledonneCommunications/linphone-android#1624]
Having a echo for other side person in both outbound and inbound call

I have tried enabling echo canceller, echo Limiter

I am on 5.0.0+ minimal Linphone

**Comment by Viish** [comment]
Did you do the echo canceller calibration?
Does your device has an hardware echo canceller?

**Comment by disolaterX** [comment]
I am on OnePlus with Android 11 and it have hardware echo canceller but it's now working correctly

**Comment by disolaterX** [comment]
So I implemented but this don't solve everything, I am still getting echo

```
     var audioManager = MyApplication.context?.getSystemService(AUDIO_SERVICE) as AudioManager
        if (inCall && audioManager?.mode == AudioManager.MODE_NORMAL)
            audioManager?.mode = AudioManager.MODE_IN_COMMUNICATION
        else audioManager?.mode = AudioManager.MODE_NORMAL
```

Make a call or receive a call.
The caller or the person on the other side hears its own echo (1-2 seconds delay). In this way it's almost impossible to communicate

**Comment by Viish** [comment]
>      var audioManager = MyApplication.context?.getSystemService(AUDIO_SERVICE) as AudioManager
        if (inCall && audioManager?.mode == AudioManager.MODE_NORMAL)
            audioManager?.mode = AudioManager.MODE_IN_COMMUNICATION
        else audioManager?.mode = AudioManager.MODE_NORMAL

This is a really bad idea anyway.

Can you attach logs from app during such a call please?

**Comment by disolaterX** [comment]
This is a really bad idea anyway.

For this please help me.

I am echo on almost every call

HERE IS THE FULL LOG FILE
https://docs.google.com/document/d/1GD7Q7RluU6h7gZA4nkmLxtU9Gbbmw1BCvphsxONZiL4/edit?usp=sharing

**Comment by Viish** [comment]
I don't know why but your recorder gets disconnected every 2 seconds, that can't help...
Also you may want to try with a better codec like Opus instead of GSM.
Other than that everything seems OK.

**Comment by disolaterX** [comment]
Any guess how to fix recorder gets disconnected every 2 seconds ??

**Comment by Viish** [comment]
No, I guess it's either a hardware issue or due to another app on your device recording audio maybe.

**Comment by disolaterX** [comment]
I don't have any thing that is recording audio

I used the linphone app on play store in that there is no such issue

**Comment by Viish** [comment]
Then try upgrading to 5.1 SDK (in your logs it says you still are on 5.0).

**Comment by disolaterX** [comment]
Is this okay 

org.linphone.minimal:linphone-sdk-android:5.1+ ?

**Comment by Viish** [comment]
> Is this okay: org.linphone.minimal:linphone-sdk-android:5.1+ ?

Yes it is.
