### ISSUE TITLE
Can't hang up call on linphone android 

### ISSUE THREAD

**Issue by hieujames** [BelledonneCommunications/linphone-android#1625]
I using transport TCP or UDP. I received incoming call. 
I get the call notification but when I want to hang up, it can't. Looks like the terminate() method sent 603 Decline but couldn't send BYE to stop the call
I am using lib linphone 4.4

**Comment by Viish** [comment]
First of all, you shouldn't use 4.4 SDK, latest release is 5.1 and this issue might be already fixed.
If it's not, please attach SDK logs showing the issue.

**Comment by hieujames** [comment]
import org.linphone.core.Address;
import org.linphone.core.AuthInfo;
import org.linphone.core.Core;
import org.linphone.core.Factory;
import org.linphone.core.NatPolicy;
import org.linphone.core.ProxyConfig;
import org.linphone.core.TransportType;
import org.linphone.core.tools.Log;


I can't import the sources when I call
org.linphone:linphone-sdk-android:5.2+ in the gradle.

**Comment by hieujames** [comment]
Hi, I've upgraded but I still can't hang up a call when a call comes in.
The call when I hit hang_up still only sends 603 Decline but not BYE

**Comment by Viish** [comment]
It's expected to send a 603 Decline to hang up a call not yet answered.
BYE is only sent when a call has been previously accepted.
