### ISSUE TITLE
Fix Android can't not send REGISTER

### ISSUE THREAD

**Issue by hieujames** [BelledonneCommunications/linphone-android#1627]
Hello,
I upgrade my app from previous library 4.4 to 5.2+ but I am having trouble getting connection signal
Specifically, I created
String server = Common.current
server = "sipproxy-01.pbx.vn:5566"
User.getProxy() + ":" + Common.currentUser.getPort();
        ProxyConfig proxyConfig = getAccountCreator().createProxyConfig();
        if (proxyConfig != null) {
            proxyConfig.setServerAddr(server);
        }

but after the unreachable signal waits for the result for a while I don't see the connected...
Please help me, I use Transport tls and JAVA programming language

**Comment by Viish** [comment]
Please follow https://gitlab.linphone.org/BC/public/tutorials/-/tree/master/android/kotlin/1-AccountLogin tutorial to learn how to properly create & configure your SIP account.
