### ISSUE TITLE
Error when Android devices call each other can't load the bandwidth on linphone 

### ISSUE THREAD

**Issue by hieujames** [BelledonneCommunications/linphone-android#1628]
Hello,
I am having problem in Linphone android, I used Stun and made a call to linphone android user.
The call is approved, but my side can neither hear nor talk to person B. I have checked the signal and found that the bandwidths are all loaded with full data, but I don't understand why the waves on the application reuse without loading

**Comment by Viish** [comment]
Hi,
Sorry but I don't understand.
Can you attach logs showing the issue?

**Comment by hieujames** [comment]
Hi @Viish,
Specifically,
When I make a call, the user picks up the phone and talks. But I don't hear what they say and I can't say anything to them, even though I'm in a wifi network environment that doesn't affect the connection drop.

**Comment by Viish** [comment]
Have you tried to enable ICE?
If yes and it still doesn't work please attach logs.
