### ISSUE TITLE
Linphone stops sending register when screen is locked or app is in background.

### ISSUE THREAD

**Issue by locofungus** [BelledonneCommunications/linphone-android#1630]
Everything is working on android 8.1.0 but on android 11 linphone doesn't stay registered unless linphone is the running app and the screen is not locked.

**To Reproduce**
I've set my asterisk server to have a expire of 90s and linphone to have an expiry of 60 seconds for these tests.

on the jellypro (android 8.1.0) there is a little green dot on the linphone app icon on the home screen and linphone says registered.

[Mar 20 12:47:53] VERBOSE[808] res_pjsip/pjsip_options.c: Contact jellypro/sip:jellypro@[2001:8b0:bfcd:5::133]:58774;transport=udp is now Reachable.  RTT: 221.568 msec

Thirty minutes later I still see:
Endpoint:  jellypro                                             Not in use    0 of inf

But on the alcatel I get:

[Mar 20 13:01:29] VERBOSE[808] res_pjsip_registrar.c: Added contact 'sip:alcatel@[2001:8b0:bfcd:5::132]:52465;transport=udp' to AOR 'alcatel' with expiration of 60 seconds
[Mar 20 13:01:29] VERBOSE[808] res_pjsip/pjsip_configuration.c: Endpoint alcatel is now Reachable
[Mar 20 13:01:29] VERBOSE[808] res_pjsip/pjsip_options.c: Contact alcatel/sip:alcatel@[2001:8b0:bfcd:5::132]:52465;transport=udp is now Reachable.  RTT: 223.652 msec

After five minutes the screen locks and then:

[Mar 20 13:07:18] VERBOSE[484] res_pjsip_registrar.c: Removed contact 'sip:alcatel@[2001:8b0:bfcd:5::132]:52465;transport=udp' from AOR 'alcatel' due to expiration
[Mar 20 13:07:18] VERBOSE[1321] res_pjsip/pjsip_options.c: Contact alcatel/sip:alcatel@[2001:8b0:bfcd:5::132]:52465;transport=udp has been deleted
[Mar 20 13:07:18] VERBOSE[1321] res_pjsip/pjsip_configuration.c: Endpoint alcatel is now Unreachable

The screen doesn't even have to be locked, just returning to the home screen is enough to cause the contact to be deleted after 90 seconds. But the notification to receive calls is still there and if I call the phone before the contact is deleted it will ring even if the screen is locked.

**Expected behavior**
Even with the screen locked, linphone should continue to send register requests. I also run OpenVPN Connect on this device and that manages to renegotiate keys periodically even while the device is locked.

When the screen is locked (or I've returned to the lock screen) but before the contact is deleted by asterisk, I can call the phone and it will ring. So the app is doing something, it's just not updating its registration.

Start app:
[Mar 20 13:20:20] VERBOSE[1321] res_pjsip/pjsip_configuration.c: Endpoint alcatel is now Reachable
[Mar 20 13:20:20] VERBOSE[1321] res_pjsip/pjsip_options.c: Contact alcatel/sip:alcatel@[2001:8b0:bfcd:5::132]:52465;transport=udp is now Reachable.  RTT: 153.378 msec

Press home button to return to home screen.
From this point onwards I didn't touch the alcatel phone.
Call the phone from another phone.
[Mar 20 13:20:42] VERBOSE[17907][C-00000018] pbx.c: Executing [6008@local_users:1] Log("PJSIP/csipsimple-0000002f", "NOTICE, call to 6001 forwarding to linphone on alcatel") in new stack

[Mar 20 13:20:42] VERBOSE[17908][C-00000018] app_dial.c: Called PJSIP/alcatel
[Mar 20 13:20:43] VERBOSE[17908][C-00000018] app_dial.c: PJSIP/alcatel-00000030 is ringing
[Mar 20 13:20:43] VERBOSE[17907][C-00000018] app_dial.c: Local/alcatel@ring_phones-0000002c;1 is ringing

Hang up.
[Mar 20 13:20:44] VERBOSE[17908][C-00000018] pbx.c: Spawn extension (ring_phones, alcatel, 2) exited non-zero on 'Local/alcatel@ring_phones-0000002c;2'

Wait for asterisk to delete the contact...
[Mar 20 13:21:48] VERBOSE[484] res_pjsip_registrar.c: Removed contact 'sip:alcatel@[2001:8b0:bfcd:5::132]:52465;transport=udp' from AOR 'alcatel' due to expiration
[Mar 20 13:21:48] VERBOSE[1321] res_pjsip/pjsip_options.c: Contact alcatel/sip:alcatel@[2001:8b0:bfcd:5::132]:52465;transport=udp has been deleted
[Mar 20 13:21:48] VERBOSE[1321] res_pjsip/pjsip_configuration.c: Endpoint alcatel is now Unreachable

**Please complete the following information**
 - Device: Alcatel 5033XR
 - OS: Android 11
 - Version of the App: 4.6.3
 - Version of the SDK: 5.1.7-pre.5+18cd243

The Jellypro is actually running an older version of the app (4.5.2) but I tried downgrading the alcatel to 4.5.2 but that didn't fix the issue.

**Comment by Viish** [comment]
Please attach logs of the app showing the issue.

**Comment by locofungus** [comment]
2022-03-21 18:10:09:736 [org.linphone/linphone-android] WARNING [Platform Helper] [Network Manager 26] Device is restricting metered network activity while application is running on background
2022-03-21 18:10:09:739 [org.linphone/linphone-android] MESSAGE [Platform Helper] Active network type is VPN, state CONNECTED / CONNECTED

Found it. Seems to be working now.

I'm not sure why the VPN is being flagged as a metered connection on Android11 but not on Android8 but now that I've said that linphone can use unrestricted data it seems to be staying registered.

**Comment by Viish** [comment]
Great!
