### ISSUE TITLE
problem with incoming messages

### ISSUE THREAD

**Issue by Tolmino** [BelledonneCommunications/linphone-android#1633]
i'm using Linphone Android 4.6.3 on andorid 11

and if i receive a message form a peer , it is listed in chat-Tab .. but if message is from asterisk, when i read it, i see all older messages received before, and the last (as i need) ..... But only if i open message from android notification popup ..... 
if i open chat-tab it is not listed there !!

**Comment by Viish** [comment]
This is because of asterisk. 
It doesn't properly set the TO header, thus we don't know this message (and the conversation that's associated) matches a currently configured account.
In chat settings, disable "Hide chat rooms from removed proxy configs" toggle.
