### ISSUE TITLE
Microphone remains disabled after starting a new call

### ISSUE THREAD

**Issue by mvdhorst** [BelledonneCommunications/linphone-android#1634]
**Describe the bug**
When you start a Linphone call, then disable the microphone in the UI.
After you end the call and start a new call, the microphone is still disabled.

**If the issue is about the SDK (build, issue, etc...) open the ticket in the [linphone-sdk](https://github.com/BelledonneCommunications/linphone-sdk) repository or one of it's submodules!**

**To Reproduce**
When you start a Linphone call, then disable the microphone in the UI.
After you end the call and start a new call, the microphone is still disabled.

**Expected behavior**
The microphone is reset to enabled state after the call.

**Please complete the following information**
 - Device: Samsung XCover 5
 - OS: Android 11
 - Version of the App 4.6.3
 - Version of the SDK 5.1.17

**Comment by Viish** [comment]
Thanks for reporting it.

Indeed the mute mic is a global "Core" setting, so it persists across calls.
I fixed it in bf4942d2 for release/4.6 and in master branch.

Cheers,
