### ISSUE TITLE
When sip call is active in the background and then accept a normal phone call, after hangup of the normal call the proximity doesn't work anymore

### ISSUE THREAD

**Issue by mvdhorst** [BelledonneCommunications/linphone-android#1635]
**Describe the bug**
When sip call is active in the background and then accept a normal phone call, after hangup of the normal call the proximity doesn't work anymore

**If the issue is about the SDK (build, issue, etc...) open the ticket in the [linphone-sdk](https://github.com/BelledonneCommunications/linphone-sdk) repository or one of it's submodules!**

**To Reproduce**
1. Start a call via Linphone
2. Press the home button, so the call is active in the background.
3. Start a normal phone call via another phone to this phone
4. Accept the phone call
5. Hang up the phone call (then wait a few seconds)
6. Move with your hand over the proximity sensor

**Expected behavior**
The proximity sensor still functions for the sip phone call

**Please complete the following information**
- Device: Samsung XCover 5
- OS: Android 11
- Version of the App 4.6.3
- Version of the SDK 5.1.17

**Comment by Viish** [comment]
This is expected, you don't even have to receive a GSM call to re-create this scenario, simply putting Linphone is background is enough.
This is because proximity-sensor is only enabled when Linphone is in foreground and if current activity is the active call one.
