### ISSUE TITLE
unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by z56402344** [BelledonneCommunications/linphone-android#1636]
A problem occurred configuring root project 'Linphone'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:7.1.1.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:7.1.1.
         > Could not get resource 'https://maven.aliyun.com/repository/public/com/android/tools/build/gradle/7.1.1/gradle-7.1.1.pom'.
            > Could not GET 'https://maven.aliyun.com/repository/public/com/android/tools/build/gradle/7.1.1/gradle-7.1.1.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.2/userguide/build_environment.html#gradle_system_properties
                  > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve com.android.tools.build:gradle:7.1.1.
         > Could not get resource 'https://maven.aliyun.com/repository/public/com/android/tools/build/gradle/7.1.1/gradle-7.1.1.pom'.
            > Could not GET 'https://maven.aliyun.com/repository/public/com/android/tools/build/gradle/7.1.1/gradle-7.1.1.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.2/userguide/build_environment.html#gradle_system_properties
                  > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve com.android.tools.build:gradle:7.1.1.
         > Could not get resource 'https://maven.aliyun.com/repository/google/com/android/tools/build/gradle/7.1.1/gradle-7.1.1.pom'.
            > Could not GET 'https://maven.aliyun.com/repository/google/com/android/tools/build/gradle/7.1.1/gradle-7.1.1.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.2/userguide/build_environment.html#gradle_system_properties
                  > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve com.android.tools.build:gradle:7.1.1.
         > Could not get resource 'https://maven.aliyun.com/repository/gradle-plugin/com/android/tools/build/gradle/7.1.1/gradle-7.1.1.pom'.
            > Could not GET 'https://maven.aliyun.com/repository/gradle-plugin/com/android/tools/build/gradle/7.1.1/gradle-7.1.1.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.2/userguide/build_environment.html#gradle_system_properties
                  > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve com.android.tools.build:gradle:7.1.1.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/7.1.1/gradle-7.1.1.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/7.1.1/gradle-7.1.1.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.2/userguide/build_environment.html#gradle_system_properties
                  > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by z56402344** [comment]
How do I get a certificate？

**Comment by yangyang-** [comment]
> How do I get a certificate？

I have the same question !

**Comment by Viish** [comment]
This isn't related to our app.

Given:
> The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: [https://docs.gradle.org/7.2/userguide](https://docs.gradle.org/7.2/userguide/build_environment.html#gradle_system_properties)

Have you considered following https://docs.gradle.org/7.2/userguide/build_environment.html#gradle_system_properties guide ? Specifically the `https.protocols` part?

Also have you check you have installed JDK 11 and not an older version?
