### ISSUE TITLE
Samsung A12 (Android 11) the sound is very low

### ISSUE THREAD

**Issue by maher-mobi-dev** [BelledonneCommunications/linphone-android#1637]
Samsung A12 (Android 11) the sound is very low in speaker mode.

 - Device: Samsung A12
 - OS: Android 11
 - Version of the App 4.7.0-alpha+bf066680a
 - Version of the SDK  5.1.2 is available: 5.2.0-alpha.81+4b9e5a6

**Comment by Viish** [comment]
Have you tried adjusting the volume?
Otherwise you can also add a gain to the playback (in audio settings) if the device default one is too low.

**Comment by maher-mobi-dev** [comment]
the volume is in the maximum 
I also add a gain to the playback, but the volume is increased in the earpiece side and it's always the same in the speaker and the sound from the earpiece become stronger than speaker (is it look like the earpiece side become the speaker)

**Comment by Viish** [comment]
Can you attach SDK logs?

**Comment by maher-mobi-dev** [comment]
You find below the two logs files with gain = 0 and gain = 5

[logs_0_gain.txt](https://github.com/BelledonneCommunications/linphone-android/files/8389062/logs_0_gain.txt)
[logs_5_gain.txt](https://github.com/BelledonneCommunications/linphone-android/files/8389064/logs_5_gain.txt)

**Comment by Viish** [comment]
Thanks. Indeed it seems gain isn't applied.
In the meantime, in the audio settings, if you switch the input & output audio device to OpenSLES instead of AAudio, does it changes anything?

**Comment by maher-mobi-dev** [comment]
I tried always the same.

**Comment by basncy** [comment]
same situation on samsung S9+(android 10), even turn on speaker.
setting [audio]
android_disable_audio_focus_requests=0
could solve this problem temproray.

**Comment by basncy** [comment]
@maher-mobi-dev 
I did the following steps to temproray solve it. you can have a try.

Goto Settings, call, SWITCH OFF Improve interactions with bluetooth devices.

**Comment by maher-mobi-dev** [comment]
I will try it, Thank you @basncy appreciate that :)

**Comment by maher-mobi-dev** [comment]
@Viish Please I have a question, what are the maximum and minimum values for the **playbackGainDb** and **micGainDb**
and it can be a negative value ?

**Comment by Viish** [comment]
@maher-mobi-dev Yes it can be negative. I don't know if there is a min/max value however.

**Comment by sureshsivalingam01** [comment]
> Have you tried adjusting the volume? Otherwise you can also add a gain to the playback (in audio settings) if the device default one is too low.
Adjusting the volume makes the ringing volume adjust. I want to stopRinging on incoming call when I click volume button.

**Comment by CRCinAU** [comment]
To try and keep things in the one spot, I'm seeing this too on a Pixel 3 with Android 13...

I wonder if its the AGC - but I don't see a way to turn the AGC off. Setting the playback gain to 6dB still doesn't seem to do anything...

App: 5.0.12
SDK: 5.2.62
