### ISSUE TITLE
anr error

### ISSUE THREAD

**Issue by 1321365765** [BelledonneCommunications/linphone-android#1638]
Repeated login and logout

[anr_2022-03-31-17-06-21-537.txt](https://github.com/BelledonneCommunications/linphone-android/files/8388330/anr_2022-03-31-17-06-21-537.txt)

**Comment by Viish** [comment]
Can you attach SDK logs from the start of the app to the ANR?

**Comment by Viish** [comment]
Closing as it doesn't concern linphone-android directly but `com.iotimc.studentphone` and no info has been provided.
