### ISSUE TITLE
Replace incoming ring tones

### ISSUE THREAD

**Issue by linyingfa** [BelledonneCommunications/linphone-android#1639]
Hello, can I replace the caller ringtone file?

**Comment by Viish** [comment]
Hi,
Do you mean your own ringtone (the sound you hear when you receive a call) or the remote ringback tone (the sound you hear will an outgoing call is ringing in your correspondent device)?

**Comment by linyingfa** [comment]
own ringtone and  remote ringback

**Comment by Viish** [comment]
You can't change the ringback tone sent by the remote, but you can configure the one you send while you ring:
https://download.linphone.org/releases/docs/liblinphone/5.1/java/org/linphone/core/Core.html#setRingback-java.lang.String-
For ringtone: https://download.linphone.org/releases/docs/liblinphone/5.1/java/org/linphone/core/Core.html#setRing-java.lang.String-

**Comment by linyingfa** [comment]
Thank！

**Comment by linyingfa** [comment]
A ringtone file exists in the raw directory

      core.isNativeRingingEnabled = true
        val basePath: String = getFilesDir().getAbsolutePath()
        val mRingSoundFile = "$basePath/pingroup_ring_tone.wav"
        val mRingBackSoundFile = "$basePath/pingroup_ring_tone.wav"
        val mPauseSoundFile = "$basePath/pingroup_ring_tone.wav"
        val mErrorToneFile = basePath + "/pingroup_ring_tone.wav";
//        core.setRemoteRingbackTone(mRingSoundFile)
        core.setTone(ToneID.CallWaiting, mRingSoundFile);
        core.setRing(mRingSoundFile)
        core.setPlayFile(mPauseSoundFile)
        core.ringback = mRingBackSoundFile
        core.setTone(ToneID.CallEnd, mErrorToneFile)

The call is still the original English alert and the original local ringtone, which does not seem to work

**Comment by Viish** [comment]
Did you copied the pingroup_ring_tone.wav to the device internal storage at $basePath/ ?

**Comment by linyingfa** [comment]
val basePath: String = filesDir.absolutePath
        val mRingSoundFile = "$basePath/oldphone_mono.wav"
        val incomingChat = "$basePath/oldphone_mono.wav"
        LinphoneUtils.copyIfNotExist(this, R.raw.oldphone_mono, mRingSoundFile)
        LinphoneUtils.copyIfNotExist(this, R.raw.oldphone_mono, incomingChat)
        Handler(Looper.getMainLooper()).postDelayed({
            core.ring = mRingSoundFile
            core.playFile = mRingSoundFile
            core.ringback = mRingSoundFile
            core.remoteRingbackTone = mRingSoundFile
            core.isNativeRingingEnabled=true
            Log.i("agaga", "222222222")
        }, 1500)

Already written, still linphone original ringtone

**Comment by Viish** [comment]
From the code you attached, you are copying oldphone_mono.wav, not pingroup_ring_tone.wav

**Comment by linyingfa** [comment]
I tried a few files, but they didn't work

**Comment by Viish** [comment]
Is you wav flle 16bits linear?

**Comment by linyingfa** [comment]
Yes, it can be played on mac misuc

**Comment by Viish** [comment]
> Yes, it can be played on mac misuc

Doesn't mean it's 16bits linear...

Also notice we do package a few different ringtones in our SDK, have you tried them?

**Comment by linyingfa** [comment]
val basePath: String = filesDir.absolutePath
        val hello16000 = "$basePath/hello16000.wav"
        LinphoneUtils.copyIfNotExist(this, R.raw.oldphone_mono, hello16000)
        Handler(Looper.getMainLooper()).postDelayed({
            core.ring = hello16000
            core.playFile = hello16000
            core.ringback = hello16000
            core.remoteRingbackTone = hello16000
        }, 1500)


Does setting this ringtone mean that it will ring when someone calls me, and does the ringtone I call others need to be the one set by the server?

**Comment by linyingfa** [comment]
val basePath: String = filesDir.absolutePath
    val hello16000 = "$basePath/hello16000.wav"
    LinphoneUtils.copyIfNotExist(this, R.raw.hello16000, hello16000)
    Handler(Looper.getMainLooper()).postDelayed({
        core.ring = hello16000
        core.playFile = hello16000
        core.ringback = hello16000
        core.remoteRingbackTone = hello16000
    }, 1500)

Does setting this ringtone mean that it will ring when someone calls me, and does the ringtone I call others need to be the one set by the server?

**Comment by Viish** [comment]
core.ring is the file played when you receive a call.
core.rinback is the file streamed to the one calling you will your device is ringing.

**Comment by linyingfa** [comment]
I call someone and the ringing file is customized, should I set that value?

**Comment by Viish** [comment]
You can't change the sound you hear while you call someone, you will here it's own ringback tone.

**Comment by linyingfa** [comment]
Thanks thanks thanks for answering my question, I'll try it tomorrow and in communication.
