### ISSUE TITLE
Push Notification Issue

### ISSUE THREAD

**Issue by kundansviet** [BelledonneCommunications/linphone-android#164]
Hello, When i implemented firebase push notification while using linphone then its always showing Registration failed in proxy state. But when i removed firebase then its working properly. How can i resolved this issue. And when i debug its showing proxy error "Unknown" . 

What i am doing is follow: 

LinphoneCore lc = getLc();
LinphoneProxyConfig proxy = LinphoneManager.getLc().getDefaultProxyConfig();
String contactInfos = "app-id=" + appId + ";pn-type=" + getString(R.string.push_type) + ";pn-tok=" + regId + ";pn-silent=1";
lpc.edit();
lpc.setContactUriParameters(contactInfos);
lpc.done();

lc.refreshRegisters();

**Comment by DatBewar** [comment]
Hello,
it's could depend of a lot of things.
Which server do you use?
