### ISSUE TITLE
Chat DeliveredToUser and Displayed states not getting during chat

### ISSUE THREAD

**Issue by TejasJayswal** [BelledonneCommunications/linphone-android#1642]
I have implement chat feature using linphone but i am not getting **DeliveredToUser** and **Displayed** states when user send message so i am not notify message read or not
I am only getting Idle , Inprogress and delivered states

So please help me...

**Comment by Viish** [comment]
Can you attach logs showing the issue?
What SDK are you using?

**Comment by TejasJayswal** [comment]
I am using this one
implementation 'org.linphone:linphone-sdk-android:5.1+'
---------------------------------
**MyCode**
--------------------------------
 private val listener = object : ChatMessageListenerStub() {
        override fun onMsgStateChanged(message: ChatMessage, state: ChatMessage.State) {
            time.value = TimestampUtils.toStringforTime(chatMessage.time)
            updateChatMessageState(state)
        }

        override fun onEphemeralMessageTimerStarted(message: ChatMessage) {
            updateEphemeralTimer()
        }
    }
    
    Inside this method i am getting ChatMessage states

**Comment by Viish** [comment]
Please attach logs from both sender & receiver for the same chat message.

**Comment by TejasJayswal** [comment]
I am implement Linphone SDK in my app also i am use my own domain  for chat message when i use **sip.linphone.org** that time it's working fine but when i used **mydomain.net** that time **DeliveredToUser** and **Displayed** State not getting in my app but when i use linphone Application that time  i am getting states
 So any solution for that
 Any changes needed in server or app? 
 
Simple Way when use **sip.linphone.org**  that time working fine but when use own server that time not working



 D: updateChatMessageState: Idle
 I: Changing [client] [MESSAGE] transaction [0x7710b95840], from state [INIT] to [TRYING]
 I: channel [0x76a6c550]: message sent to [UDP://my.domain.net:5060], size: [513] bytes
I: MESSAGE sip:74428785@my.domain.net SIP/2.0
I: Via: SIP/2.0/UDP  ….:54950;branch=z9hG4bK.fFrX5l9i7;rport
I: From: <sip:49007160@my.domain.net>;tag=8VeJ6FQfi
 I: To: sip:74428785@my.domain.net
 I: CSeq: 20 MESSAGE
 I: Call-ID: bY0jZX1VLV
 I: Max-Forwards: 70
 I: Supported: replaces, outbound, gruu
 I: Date: Tue, 05 Apr 2022 08:42:12 GMT
 I: Content-Type: text/plain
 I: Content-Length: 12
 I: User-Agent: myappAndroid/1.0 LinphoneSDK/5.1.19-pre.3+b0d9bc2 (pipelines/44890)
 I: How are you?
 I: Chat message 0x76a6bced00 of chat room ConferenceId(peer=IdentityAddress(sip:74428785@my.domain.net), local=IdentityAddress(sip:49007160@my.domain.net)) : moving from Idle to InProgress
13806-13806 I: MainDb::addEvent() of type ConferenceChatMessage (value 5)
13806-13806 D: updateChatMessageState: Idle
13806-13806 I: Changing [client] [MESSAGE] transaction [0x7710b95840], from state [INIT] to [TRYING]
13806-13806 I: channel [0x76a6c55040]: message sent to [UDP://my.domain.net:5060], size: [513] bytes
13806-13806 I: MESSAGE sip:7442878500@my.domain.net SIP/2.0
13806-13806 I: Via: SIP/2.0/UDP  ….:54950;branch=z9hG4bK.fFrX5l9i7;rport
13806-13806 I: From: <sip:4900716023@my.domain.net>;tag=8VeJ6FQfi
13806-13806 I: To: sip:7442878500@my.domain.net
13806-13806 I: CSeq: 20 MESSAGE
13806-13806 I: Call-ID: bY0jZX1VLV
13806-13806 I: Max-Forwards: 70
13806-13806 I: Supported: replaces, outbound, gruu
13806-13806 I: Date: Tue, 05 Apr 2022 08:42:12 GMT
13806-13806 I: Content-Type: text/plain
13806-13806 I: Content-Length: 12
13806-13806 I: User-Agent: myappAndroid/1.0 LinphoneSDK/5.1.19-pre.3+b0d9bc2 (pipelines/44890)
13806-13806 I: How are you?
13806-13806 I: Chat message 0x76a6bced00 of chat room ConferenceId(peer=IdentityAddress(sip:74428785@my.domain.net), local=IdentityAddress(sip:49007160@my.domain.net)) : moving from Idle to InProgress
13806-13806 D: updateChatMessageState: InProgress
13806-13806 I: MainDb::addEvent() of type ConferenceChatMessage (value 5)
13806-13806 D: updateChatMessageState: Idle
13806-13806 I: Changing [client] [MESSAGE] transaction [0x7710b95840], from state [INIT] to [TRYING]
13806-13806 I: channel [0x76a6c55040]: message sent to [UDP://my.domain.net:5060], size: [513] bytes
13806-13806 I: MESSAGE sip:74428785@my.domain.net SIP/2.0
13806-13806 I: Via: SIP/2.0/UDP  ….:54950;branch=z9hG4bK.fFrX5l9i7;rport
13806-13806 I: From: <sip:49007160@my.domain.net>;tag=8VeJ6FQfi
13806-13806 I: To: sip:74428785@my.domain.net
13806-13806 I: CSeq: 20 MESSAGE
13806-13806 I: Call-ID: bY0jZX1VLV
13806-13806 I: Max-Forwards: 70
13806-13806 I: Supported: replaces, outbound, gruu
13806-13806 I: Date: Tue, 05 Apr 2022 08:42:12 GMT
13806-13806 I: Content-Type: text/plain
13806-13806 I: Content-Length: 12
13806-13806 I: User-Agent: myappAndroid/1.0 LinphoneSDK/5.1.19-pre.3+b0d9bc2 (pipelines/44890)
13806-13806 I: How are you?
13806-13806 I: Chat message 0x76a6bced00 of chat room ConferenceId(peer=IdentityAddress(sip:74428785@my.domain.net), local=IdentityAddress(sip:49007160@my.domain.net)) : moving from Idle to InProgress
13806-13806 D: updateChatMessageState: InProgress
13806-13806 D: updateChatMessageState: Delivered

**Comment by Viish** [comment]
If it works with our server and not yours check messages aren't discarded by your proxy then.
