### ISSUE TITLE
Disable Android Check for Updates?

### ISSUE THREAD

**Issue by ZippoD** [BelledonneCommunications/linphone-android#1643]
I see in the source check for updates but it is above and beyond me to build from source without this code. Any way to disable check for updates on the current build or are there any not too old .APK that did not have that functionality?

**Comment by Viish** [comment]
Simply replace `version_check_url_root=https://www.linphone.org/releases` by `version_check_url_root=` in https://gitlab.linphone.org/BC/public/linphone-android/-/blob/master/app/src/main/assets/linphonerc_default#L33, then install the app (uninstall first).

**Comment by ZippoD** [comment]
> Simply replace `version_check_url_root=https://www.linphone.org/releases` by `version_check_url_root=` in https://gitlab.linphone.org/BC/public/linphone-android/-/blob/master/app/src/main/assets/linphonerc_default#L33, then install the app (uninstall first).

This looks like a source file of some sort (I mentioned I don't have the knowledge set to build from source). If it is a config file, where is it locate on the target device as I don't see in app data?

**Comment by Viish** [comment]
> where is it locate on the target device as I don't see in app data?

It's the .linphonerc file in app_data/files/ directory.

Otherwise you can also change that value by remote provisioning: https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Remote%20Provisioning/

Finally installing the app is quite easy: open the project in Android Studio and click on "install" button.
