### ISSUE TITLE
Incoming calls are automatically refused

### ISSUE THREAD

**Issue by andreapier** [BelledonneCommunications/linphone-android#1644]
**Describe the bug**
I am not able to receive calls. Whenever the call starts, it gets refused by the app.
It appears as missed in the notification panel, but it wasn't really missed. 

**To Reproduce**
1. Place a call
2. See error

**Expected behavior**
I expect to be able to accept or refuse the call.

**Please complete the following information**
 - Device: Samsung Tab 10.1 SM-T510
 - OS: Android 11
 - Version of the App: 4.6.3
 - Version of the SDK: 5.1.7

**SDK logs**
https://www.linphone.org:444//tmp/624c1900decbd_5cedaabf684e4206e55e.gz 

**Adb logcat logs**
-

**Screenshots**
Check this video out: it shows a missed call notification coming from nowhere. This is wxactly what is happening.
https://drive.google.com/file/d/12WhIWDXirIm-JAwGv4gq9Ef8SbRlgRKO/view?usp=sharing

**Additional context**
This used to work with previous versions. I also want to add that everything is working fine with other Android devices so I am really lost on this.

**Comment by Viish** [comment]
Hi,

Here's why:
```
2022-04-05 12:24:55:636 [org.linphone/linphone-android] MESSAGE [Context] Call state changed [IncomingReceived]
2022-04-05 12:24:55:638 [org.linphone/linphone-android] MESSAGE [Telecom Helper] Is incoming call permitted? false
2022-04-05 12:24:55:639 [org.linphone/linphone-android] WARNING [Context] Refusing the call with reason busy because Telecom Manager will reject the call
```
However I don't know why your device's TelecomManager API says it will reject the call... 
Have you tried rebooting your device? Is it's firmware up-to-date?

If both answers are yes, then either there is another app messing with TelecomManager or your device has a bug in how it implements it. 
In this case the only solution is to disable the use of this API in linphone-android call settings (toggle off the setting named `Improve interactions with bluetooth devices`).

**Comment by andreapier** [comment]
Hi, I can confirm that disabling `Improve interactions with bluetooth devices` fixes the issue.  
Thanks
