### ISSUE TITLE
Call Hangup Reason

### ISSUE THREAD

**Issue by disolaterX** [BelledonneCommunications/linphone-android#1645]
How to get the reasons why a outbound call failed or what the reason,

Like if a call failed due to Channel Unavailable

**Comment by Viish** [comment]
Use either https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Call.html#getErrorInfo-- or https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Call.html#getReason--
