### ISSUE TITLE
i18n: &appName; is not in use

### ISSUE THREAD

**Issue by glixx** [BelledonneCommunications/linphone-android#1647]
I see &appName; as a text instead of variable value. Can be reproduced in Russian locale.

**Comment by Viish** [comment]
Which version please?

**Comment by glixx** [comment]
Linphone Android 4.6.4
Linphone SDK 5.1.20

**Comment by glixx** [comment]
Splash screen is too fast.

**Comment by Viish** [comment]
Sorry but I don't understand, there is no mention of the app name on the splashscreen...
Otherwise can you record your device's screen?

**Comment by Viish** [comment]
Hi, any update?

**Comment by glixx** [comment]
I cannot reproduce.
