### ISSUE TITLE
Origin Field IPv6 Serverless call

### ISSUE THREAD

**Issue by eezeze** [BelledonneCommunications/linphone-android#165]
I am trying to make a serverless call from linphone android to linphone desktop but there are some errors in SDP packages.

IPv6 is enabled but it looks is getting IPv6 address from wrong interface.

Data below from tests in IPv4 and IPv6 SDP packages:

IPv4
    - Header
    Contact:"Linphone Android" <sip:linphone.android@192.168.2.2:5060;transport=udp>
    - Body
    Owner/Creator, Session Id (o): linphone.android 2067 2054 IN IP4 192.168.2.2
    
IPv6
    - Header
    Contact:"Linphone Android" <sip:linphone.android@[::1]:5060;transport=udp>
    - Body
    Owner/Creator, Session Id (o): linphone.android 544 1897 IN IP6 ::1

Conf    
    - wlan0
    IPv4:192.168.2.2
    IPv6:[valid IPv6]
    - lo
    IPv4:127.0.0.1
    IPv6:[::1]

Thank you

Jose

**Comment by Viish** [comment]
SDK issue, not Android
