### ISSUE TITLE
Download bandwidth getting 0.0

### ISSUE THREAD

**Issue by RaviChavada** [BelledonneCommunications/linphone-android#1653]
Hello 
Hope you are doing well.

Sometimes I am facing issues.
When i get a call from another extension and received it from my side i am not able to hear a voice. and when i open call status from the sidemenu it will display a download bandwidth of 0.0 kb

is there any specific setting to enable or start to receive download bandwidth?

**Comment by Viish** [comment]
No there isn't. It's most probably a network issue. Try to enable STUN, ICE and AVPF.

**Comment by RaviChavada** [comment]
if you don't mind can you please guide me on how to enable STUN, ICE and AVPF, or any other refrence link?

**Comment by Viish** [comment]
In linphone-android's account settings

**Comment by RaviChavada** [comment]
thank you for your reply.
I have one more query.
is there any specific scenario call's pausing method is called and the call's paused method is not called?

**Comment by Viish** [comment]
When you pause a call, state will go from StreamsRunning to Pausing to Paused.
On the other end, it will go from StreamsRunning to Pausing to PausedByRemote.
