### ISSUE TITLE
How can i setup Linphone voice call

### ISSUE THREAD

**Issue by Ankitinnovatree** [BelledonneCommunications/linphone-android#1654]
How can i setup Voice calling in my app(Any Example and complete guidelines)

Thank you..

**Comment by Viish** [comment]
https://gitlab.linphone.org/BC/public/tutorials/-/tree/master/android/kotlin

**Comment by Ankitinnovatree** [comment]
This tutorial only Video Call.

I am setup only Voice calling not video call. Please Guide.

**Comment by Viish** [comment]
Do the same as for video calling without setting video enabled property to True...

**Comment by Ankitinnovatree** [comment]
i make a voice call app like normal mobile number calling, not voice calling using through this app
