### ISSUE TITLE
Fix the sound when talking between 2 devices linphone android and iphone is shy and noisy

### ISSUE THREAD

**Issue by hieujames** [BelledonneCommunications/linphone-android#1655]
Hi,
I'm having an issue where when I call an iphone user device, me and them talk to each other and it sounds very crackling, leaking and lots of other noise.
I have reported to my server to check but they said no response in call audio is bad, everything is fine, and asked me to test it myself on the app. i don't know how to check, i'm using liblinphone 5.2+
I look forward to your help. thank you

**Comment by Viish** [comment]
Hi,
Can you attach logs from app from the start to the end of a call with the issue please?

**Comment by Viish** [comment]
Closed until logs are attached
