### ISSUE TITLE
Sound is super strong (echo of the voice / metallic noise etc ...)

### ISSUE THREAD

**Issue by maher-mobi-dev** [BelledonneCommunications/linphone-android#1657]
I found a problem with HUAWEI ANE-LX1 : the sound is super strong (echo of the voice / metallic noise etc ...)

 - Device: HUAWEI ANE-LX1
 - OS:  Android 9
- Version of the SDK 5.1.2
[log.txt](https://github.com/BelledonneCommunications/linphone-android/files/8519684/log.txt)

Note: If mediaEncryption is not added the pb of feedback disappears but the sound remains very very strong

**Comment by Viish** [comment]
Hi,

Your company has a support contract with ours, please open this issue on our mantis bugtracker instead of here.

Cheers,
