### ISSUE TITLE
Disappearing names in call history

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-android#1659]
**Describe the bug**
When a call is retrieved, the name of the remote party is logged along with their number within the call history. After restarting Linphone, only the number is displayed in the call history (unless this is a local contact on the phone).

**If the issue is about the SDK (build, issue, etc...) open the ticket in the [linphone-sdk](https://github.com/BelledonneCommunications/linphone-sdk) repository or one of it's submodules!**

**To Reproduce**
As mentioned in description. Doesn't occur when the SDK is compiled with the DB_STORAGE=NO flag.

**Please complete the following information**
 - Device: Samsung Galaxy s10e
 - OS: Android 12
 - Linphone 4.7.0-alpha.148
 - Linphone SDK 5.2.0-alpha.128

**SDK logs**
[62692c9a44679_293aadf6e24520f66786.txt](https://github.com/BelledonneCommunications/linphone-android/files/8571717/62692c9a44679_293aadf6e24520f66786.txt)

**Comment by Viish** [comment]
Hi,

Thanks for reporting it, I can reproduce the issue and will fix it.

Cheers,
