### ISSUE TITLE
Disabling SUBSCRIBE

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1660]
What causes:

```
SUBSCRIBE sip:[redacted]@example.com SIP/2.0
Via: SIP/2.0/TCP [2001:123:4567:0:1596:85e5:1402:6d4f]:44242;alias;branch=z9hG4bK.K7sYFlZrQ;rport
From: "[redacted]" <sip:my_sip_account@example.com>;tag=dHdxgRTU3
To: "House Phones" <sip:[redacted]@example.com>
CSeq: 20 SUBSCRIBE
Call-ID: W6YffylNZb
Max-Forwards: 70
Supported: replaces, outbound, gruu
Event: presence
Expires: 600
Contact: <sip:my_sip_account@[2001:123:4567:0:1596:85e5:1402:6d4f]:44242;pn-prid=[redacted];pn-provider=fcm;pn-param=[redacted];pn-silent=1;pn-timeout=0;transport=tcp>;expires=31535999;+sip.instance="<urn:uuid:312eea04-3559-00ae-9920-aac6701fd648>";+org.linphone.specs="ephemeral,ephemeral/1.1,groupchat/1.1,lime"
User-Agent: MyLinphoneAndroid/4.6.6.23.1+53a11bfa7 (FRD-L04) LinphoneSDK/5.1.24 (tags/5.1.24^0)
Content-Length: 0
```

to be sent to the `REGISTER`ed SIP server for numerous contacts?  I thought it might be Contacts->Friendlist subscribe, but I have that disabled.

**Comment by Viish** [comment]
As I said in the commit comments, I found an issue with the Contacts->FriendList Subscribe setting in the SDK.
Until I fix it, use the following:
```
[sip]
rls_uri=
```

**Comment by brianjmurrell** [comment]
Indeed.  But the Contacts->Friendlist subscribe should be moot for a non `sip.linphone.org` account with https://github.com/BelledonneCommunications/linphone-android/commit/a464e31fc27fb85e0891a6e4dd7195967fd4a82b shouldn't it?

**Comment by Viish** [comment]
Yes, but as I said this commit only prevents it for new installs, not existing ones.

**Comment by Viish** [comment]
Actually it doesn't seem to have any issue with Contacts->Friendlist subscribe setting. Have you restarted the app after toggling it off?

**Comment by brianjmurrell** [comment]
I have had it off _forever_ and have only until today, by setting `rls_uri=`, gotten `SUBSCRIBE`s to stop.
