### ISSUE TITLE
How can I receive calls when the application is completely closed?

### ISSUE THREAD

**Issue by sercan447** [BelledonneCommunications/linphone-android#1662]
How can I receive calls when the application is completely closed? ?
The foreground service is undesirable by the user.
background services are also not trusted.
In this case, the rest is connectionService.!
What can be done for this?

**Comment by Viish** [comment]
There are only 2 options : either you use push notifications or you use a foreground service to keep the app alive in background.

**Comment by sercan447** [comment]
Do I need to configure the flexisip server side to use push notifications when the application is closed?

**Comment by Viish** [comment]
Yes.
See https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/Configuration/Push%20notifications/ for flexisip push configuration and https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Push%20notifications/ for Android push configuration.
