### ISSUE TITLE
Failed to log on to the Fritz!Box

### ISSUE THREAD

**Issue by west89** [BelledonneCommunications/linphone-android#1663]
I can't get the login to work on my Fritz!Box 7490 running Fritz!OS 07.29.

![Screenshot_20220504-104758](https://user-images.githubusercontent.com/42120960/166649780-152b780b-00c4-4a31-ae88-cb753f2482ea.jpg)

![Screenshot_20220504-105802](https://user-images.githubusercontent.com/42120960/166651474-d38f434e-2666-4e78-89a4-be75f4cbff04.jpg)

**Comment by Viish** [comment]
Can you attach logs please?

**Comment by west89** [comment]
> 
https://www.linphone.org:444//tmp/627248cdbad8e_5be96a6bddab16692948.gz

**Comment by Viish** [comment]
From your logs REGISTER is sent to `192.168.178.1:5060` using UDP protocol, however we never receive any answer from your server.
I don't know anything about Fritzbox, make sure it does listen on port 5060 for UDP protocol. 
If it does support TCP or TLS I recommend you to switch to one of those.
