### ISSUE TITLE
Clean Memory[Samsung], initiate a call, SIP get registered but not getting call in onCallStateChanged for the first time

### ISSUE THREAD

**Issue by atendrasingh90** [BelledonneCommunications/linphone-android#1667]
**Describe the bug**
I am facing one issue on samsung where I am cleaning the memory and initiating a call from linphone desktop app.
Once I am getting the call push, and the app application class start the sip registration. I am getting success in onRegistrationStateChanged with OK status. As my CoreListenerStub is set already I am not getting the call in onCallStateChanged which i initiated from linphone desktop app. This is only happening for the first call.

**If the issue is about the SDK (build, issue, etc...) open the ticket in the [linphone-sdk](https://github.com/BelledonneCommunications/linphone-sdk) repository or one of it's submodules!**

**To Reproduce**
1. Clear android device memory
2. initiate a call immediately

**Expected behavior**
onCallStateChanged should get the call when it is ready

**Please complete the following information**
 - Device: [e.g. Samsung A13]
 - OS: [e.g. Android 12]
 - Version of the SDK 5.1+

**Additional context**
Is there any way to retrieve the call from server when we do not get call in onCallStateChanged listener. I also tried getting current calls but i am not getting 0 calls from core.

**Comment by Viish** [comment]
Please attach logs showing the issue.

**Comment by atendrasingh90** [comment]
[success_logs.txt](https://github.com/BelledonneCommunications/linphone-android/files/8641405/success_logs.txt)
[after_memory_clean.txt](https://github.com/BelledonneCommunications/linphone-android/files/8641407/after_memory_clean.txt)

**Comment by Viish** [comment]
I didn't check success_logs but in after_memory_clean logs you don't receive any call, that's why onCallStateChanged listener isn't called...

**Comment by atendrasingh90** [comment]
Yes, you are right i don't receive the very first call. when i make it from linphone desktop app.
But i can see the liphone desktop is still calling the device.

My point is, Is there any way we can retrieve the calls from server which we do not receive in onCallStateChanged

**Comment by Viish** [comment]
> My point is, Is there any way we can retrieve the calls from server which we do not receive in onCallStateChanged

That's not how SIP works.
When the REGISTER is sent to your server, it should send you the INVITE that's pending.
Check if you don't have a fork-late setting to enable in your server configuration.

Also you should switch from UDP to TCP or TLS for better results.

**Comment by atendrasingh90** [comment]
Thanks @Viish for the quick response and valuable information

**Comment by atendrasingh90** [comment]
Hey @Viish 
I got the exact problem why i was not able to receive the call from linphone after clearing the memory or removing my app from recents.

The problem is that when we remove our app from recent. we dont have access to change the SIP registration status and server treats our app as a registered SIP and when we make a call quickly server sends the invite immediately because it sees our app is registered and we fail to receive it. 

Server takes some time to realize that the app SIP is not responding and mark it as sleep or any other status.

I tried call an SIP immediately after removing the app from recent, My call fails.
If i wait for about a min and call, it works well.

Any Suggestions

**Comment by Viish** [comment]
@atendrasingh90 you can use a service and override onTaskRemoved method to do a proper unregister.
Otherwise simply have your proxy send a push notification each time, it works very well for us this way.

**Comment by atendrasingh90** [comment]
So you mean that after every call i should unregister and on push receive for new calls I need to re-register and get the call. I am right?

**Comment by Viish** [comment]
The best solution is to not do anything when the app is being killed and simply rely on push notifications all the time.
Otherwise if you need to clear something or do something special in your proxy, you can use the Service method.

**Comment by atendrasingh90** [comment]
Do you have an example code, where i can have more idea about the same?
