### ISSUE TITLE
issue when you compile

### ISSUE THREAD

**Issue by andresbelt** [BelledonneCommunications/linphone-android#167]
When make:

-- Build files have been written to: linphone-android/WORK/android-armv7/Build/sqlite3
[ 60%] Forcing build for 'EP_sqlite3'
[ 60%] Performing build step for 'EP_sqlite3'
Scanning dependencies of target sqlite3
[ 50%] Building C object CMakeFiles/sqlite3.dir/sqlite3.c.o
linphone-android/submodules/externals/sqlite3/sqlite3.c:30845:42: error: 
      use of undeclared identifier 'mmap'
  { "mmap",         (sqlite3_syscall_ptr)mmap,            0 },
                                         ^
linphone-android/submodules/externals/sqlite3/sqlite3.c:30925:22: error: 
      invalid application of 'sizeof' to an incomplete type
      'struct unix_syscall []'
    for(i=0; i<sizeof(aSyscall)/sizeof(aSyscall[0]); i++){
                     ^~~~~~~~~~
linphone-android/submodules/externals/sqlite3/sqlite3.c:30934:22: error: 
      invalid application of 'sizeof' to an incomplete type
      'struct unix_syscall []'
    for(i=0; i<sizeof(aSyscall)/sizeof(aSyscall[0]); i++){
                     ^~~~~~~~~~
linphone-android/submodules/externals/sqlite3/sqlite3.c:30961:20: error: 
      invalid application of 'sizeof' to an incomplete type
      'struct unix_syscall []'
  for(i=0; i<sizeof(aSyscall)/sizeof(aSyscall[0]); i++){
                   ^~~~~~~~~~
linphone-android/submodules/externals/sqlite3/sqlite3.c:30978:16: error: 
      invalid application of 'sizeof' to an incomplete type
      'struct unix_syscall []'
    for(i=0; i<ArraySize(aSyscall)-1; i++){
               ^~~~~~~~~~~~~~~~~~~
linphone-android/submodules/externals/sqlite3/sqlite3.c:13063:38: note: 
      expanded from macro 'ArraySize'
#define ArraySize(X)    ((int)(sizeof(X)/sizeof(X[0])))
                                     ^~~
linphone-android/submodules/externals/sqlite3/sqlite3.c:30982:14: error: 
      invalid application of 'sizeof' to an incomplete type
      'struct unix_syscall []'
  for(i++; i<ArraySize(aSyscall); i++){
             ^~~~~~~~~~~~~~~~~~~
linphone-android/submodules/externals/sqlite3/sqlite3.c:13063:38: note: 
      expanded from macro 'ArraySize'
#define ArraySize(X)    ((int)(sizeof(X)/sizeof(X[0])))
                                     ^~~
6 errors generated.
make[6]: *** [CMakeFiles/sqlite3.dir/sqlite3.c.o] Error 1
make[5]: *** [CMakeFiles/sqlite3.dir/all] Error 2
make[4]: *** [all] Error 2
make[3]: *** [linphone-android/WORK/android-armv7/Stamp/EP_sqlite3/EP_sqlite3-build] Error 2
make[2]: *** [CMakeFiles/EP_sqlite3.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [armv7-build] Error 2

**Comment by DatBewar** [comment]
Hello, 
Wich ndk do you use?

**Comment by andresbelt** [comment]
hi, my ndk version is android-ndk-r15c

**Comment by qiLingLingYi** [comment]
the version is too high i think, you can read the file README
