### ISSUE TITLE
Local AddressBook Crash - Android 12 Oppo Find x2 Pro

### ISSUE THREAD

**Issue by mircoiplabs** [BelledonneCommunications/linphone-android#1671]
Hello, my Linphone based app crash only with an Oppo Find x2, with Android 12.

The user just click on the local address book section and then the app crashes.

**Please complete the following information**
 - Device: Oppo Find x2 Pro
 - OS: Android 12
 - Version of the App: release/4.6
 - Version of the SDK: 5.1.23

These are logs generated in Google Play Console:

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> it.myCompany.myApp <<<

backtrace:
  #00  pc 00000000000799c8  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168)
  #00  pc 00000000006d157c  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+668)
  #00  pc 000000000001695c  /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+76)
  #00  pc 0000000000015f8c  /apex/com.android.art/lib64/libbase.so (android::base::LogMessage::~LogMessage()+364)
  #00  pc 00000000002be7fc  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::AddWeakGlobalRef(art::Thread*, art::ObjPtr<art::mirror::Object>)+2292)
  #00  pc 00000000005f2c2c  /apex/com.android.art/lib64/libart.so (art::JNI<false>::NewWeakGlobalRef(_JNIEnv*, _jobject*)+272)
  #00  pc 0000000000939b14  /data/app/~~WUtsYJSCB1HVIeFJsiBLSA==/it.myCompany.myApp-p07Psnuu9esrCE3Mbs_H2A==/split_config.arm64_v8a.apk!liblinphone.so (getAddress+224)
  #00  pc 000000000096cc14  /data/app/~~WUtsYJSCB1HVIeFJsiBLSA==/it.myCompany.myApp-p07Psnuu9esrCE3Mbs_H2A==/split_config.arm64_v8a.apk!liblinphone.so (Java_org_linphone_core_CoreImpl_interpretUrl+116)
  #00  pc 000000000201dac8  /memfd:jit-cache (art_jni_trampoline+120)
  #00  pc 000000000201f9a4  /memfd:jit-cache (org.linphone.core.CoreImpl.interpretUrl+836)
  #00  pc 000000000201bef4  /memfd:jit-cache (e9.c.v+3044)
  #00  pc 000000000201cd50  /memfd:jit-cache (e9.c.<init>+1952)
  #00  pc 0000000002004148  /memfd:jit-cache (e9.e.m+920)
  #00  pc 0000000002004d60  /memfd:jit-cache (e9.e.p+272)
  #00  pc 000000000020a0a0  /apex/com.android.art/lib64/libart.so (nterp_helper+4016)
  #00  pc 00000000003b55e6  /data/app/~~WUtsYJSCB1HVIeFJsiBLSA==/it.myCompany.myApp-p07Psnuu9esrCE3Mbs_H2A==/oat/arm64/base.vdex (org.linphone.activities.main.contact.fragments.MasterContactsFragment.onViewCreated$lambda-12+30)
  #00  pc 0000000000209124  /apex/com.android.art/lib64/libart.so (nterp_helper+52)
  #00  pc 00000000003b5190  /data/app/~~WUtsYJSCB1HVIeFJsiBLSA==/it.myCompany.myApp-p07Psnuu9esrCE3Mbs_H2A==/oat/arm64/base.vdex (org.linphone.activities.main.contact.fragments.MasterContactsFragment.i)
  #00  pc 0000000000209124  /apex/com.android.art/lib64/libart.so (nterp_helper+52)
  #00  pc 00000000003b4634  /data/app/~~WUtsYJSCB1HVIeFJsiBLSA==/it.myCompany.myApp-p07Psnuu9esrCE3Mbs_H2A==/oat/arm64/base.vdex (org.linphone.activities.main.contact.fragments.u.a+8)
  #00  pc 000000000020ae64  /apex/com.android.art/lib64/libart.so (nterp_helper+7540)
  #00  pc 00000000001e1caa  /data/app/~~WUtsYJSCB1HVIeFJsiBLSA==/it.myCompany.myApp-p07Psnuu9esrCE3Mbs_H2A==/oat/arm64/base.vdex (androidx.lifecycle.LiveData.c+58)
  #00  pc 000000000200e2f4  /memfd:jit-cache (androidx.lifecycle.LiveData.d+548)
  #00  pc 000000000200fa2c  /memfd:jit-cache (androidx.lifecycle.a0.o+124)
  #00  pc 000000000020a0a0  /apex/com.android.art/lib64/libart.so (nterp_helper+4016)
  #00  pc 00000000004e455a  /data/app/~~WUtsYJSCB1HVIeFJsiBLSA==/it.myCompany.myApp-p07Psnuu9esrCE3Mbs_H2A==/oat/arm64/base.vdex (y9.p4$a.a+62)
  #00  pc 000000000020ae64  /apex/com.android.art/lib64/libart.so (nterp_helper+7540)
  #00  pc 000000000044f132  /data/app/~~WUtsYJSCB1HVIeFJsiBLSA==/it.myCompany.myApp-p07Psnuu9esrCE3Mbs_H2A==/oat/arm64/base.vdex (s0.h$a.onTextChanged+22)
  #00  pc 000000000086c410  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (android.widget.TextView.sendOnTextChanged+288)
  #00  pc 0000000000861c30  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (android.widget.TextView.handleTextChanged+400)
  #00  pc 000000000084d388  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (android.widget.TextView$ChangeWatcher.onTextChanged+88)
  #00  pc 000000000087ea6c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (android.text.SpannableStringBuilder.replace+1228)
  #00  pc 000000000020a7c8  /apex/com.android.art/lib64/libart.so (nterp_helper+5848)
  #00  pc 00000000001cae9e  /data/app/~~WUtsYJSCB1HVIeFJsiBLSA==/it.myCompany.myApp-p07Psnuu9esrCE3Mbs_H2A==/oat/arm64/base.vdex (androidx.emoji2.text.m.replace+6)
  #00  pc 000000000087e574  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (android.text.SpannableStringBuilder.replace+292)
  #00  pc 000000000020a0a0  /apex/com.android.art/lib64/libart.so (nterp_helper+4016)
  #00  pc 00000000001cae7a  /data/app/~~WUtsYJSCB1HVIeFJsiBLSA==/it.myCompany.myApp-p07Psnuu9esrCE3Mbs_H2A==/oat/arm64/base.vdex (androidx.emoji2.text.m.replace+6)
  #00  pc 000000000020a044  /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
  #00  pc 00000000001cad94  /data/app/~~WUtsYJSCB1HVIeFJsiBLSA==/it.myCompany.myApp-p07Psnuu9esrCE3Mbs_H2A==/oat/arm64/base.vdex (androidx.emoji2.text.m.replace)
  #00  pc 00000000007e86a0  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (android.view.inputmethod.BaseInputConnection.replaceText+1248)
  #00  pc 00000000007ea184  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (android.view.inputmethod.BaseInputConnection.setComposingText+52)
  #00  pc 00000000007ec21c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (android.view.inputmethod.InputConnectionWrapper.setComposingText+76)
  #00  pc 000000000093cb64  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (com.android.internal.view.IInputConnectionWrapper.executeMessage+6532)
  #00  pc 00000000009103d4  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage+68)
  #00  pc 0000000000582aec  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (android.os.Handler.dispatchMessage+188)
  #00  pc 0000000000585b18  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (android.os.Looper.loopOnce+1384)
  #00  pc 00000000005854fc  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (android.os.Looper.loop+604)
  #00  pc 000000000034ceac  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (android.app.ActivityThread.main+732)
  #00  pc 00000000002ca9e8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568)
  #00  pc 000000000035b5d0  /apex/com.android.art/lib64/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+608)
  #00  pc 000000000035b348  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52)
  #00  pc 00000000000b2f74  /apex/com.android.art/javalib/arm64/boot.oat (art_jni_trampoline+132)
  #00  pc 00000000008c736c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+140)
  #00  pc 00000000008cfd10  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+2800)
  #00  pc 00000000002ca9e8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568)
  #00  pc 000000000044ca04  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+464)
  #00  pc 000000000062cf30  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+268)
  #00  pc 00000000000b2bf8  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+124)
  #00  pc 00000000000bf0fc  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+840)
  #00  pc 0000000000002684  /system/bin/app_process64 (main+1580)
  #00  pc 00000000000720c4  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+100)

Not a known problem with Oppo devices?
Thank you for your help.

**Comment by Viish** [comment]
Please attach a symbolized stack trace along with the SDK logs.
Do you reproduce the issue using latest linphone-android (4.6.7) release?

**Comment by Viish** [comment]
@mircoiplabs any update?

**Comment by Viish** [comment]
Ok, in the meantime I'm closing the issue.
