### ISSUE TITLE
Sound Distortion 

### ISSUE THREAD

**Issue by disolaterX** [BelledonneCommunications/linphone-android#1675]
While on call if any notification arrives on android device from any app that makes the sound quality very bad and have distortion and eventually make is worse 

Just for info we are using linphone turn nat profile

**Comment by Viish** [comment]
With which version of the app? Of the SDK?
Using TelecomManager or not?
Can you attach logs showing the issue please?

**Comment by disolaterX** [comment]
I don’t think we are using TelecomManager can you share the implementation or reference to it

We are using latest stable sdk in custom app build of our own.

and this issue is reported by my team members log is right now not possible 

And can you help me how to record all the logs in a file so that even my team members have issue i can have logs

**Comment by Viish** [comment]
> I don’t think we are using TelecomManager can you share the implementation or reference to it

Check https://gitlab.linphone.org/BC/public/linphone-android/-/tree/master/app/src/main/java/org/linphone/telecom

> And can you help me how to record all the logs in a file so that even my team members have issue i can have logs

Here's how to enable logs: https://gitlab.linphone.org/BC/public/linphone-android/-/blob/master/app/src/main/java/org/linphone/LinphoneApplication.kt#L66
Then call `core.uploadLogCollection()` (don't forget to configure a `log_collection_upload_server_url`, you can use ours if you don't have one: `https://www.linphone.org:444/lft.php`

**Comment by Viish** [comment]
core.uploadLogCollection() method will notify you of the URL in the onLogCollectionUploadStateChanged() callback of CoreListener.
Your log file will be deleted from our server after a month. Until then it's only "public" for those who know the URL, the folder content can't be listed.
Otherwise you can host your own file transfer server: https://gitlab.linphone.org/BC/public/flexisip-http-file-transfer-server

**Comment by Viish** [comment]
@disolaterX any update?

**Comment by Viish** [comment]
Closed until logs will be provided.
