### ISSUE TITLE
OTP is not delivered for a particular number

### ISSUE THREAD

**Issue by naxtreasif** [BelledonneCommunications/linphone-android#1676]
OTP is not delivered for a particular number

I am developing an app that uses linphone SDK for the calling feature, however, one of my users from a particular location did not receive OTP to verify himself.

The user has the following phone number +92-32*******9. **He also tried the Linphone app on the play store, however in that case as well, the user did not receive any OTP.**

**Comment by Viish** [comment]
Can you attach logs showing the issue please?

**Comment by naxtreasif** [comment]
Hello, I am using the linphone app from play store

**Comment by Viish** [comment]
Hi,

> I am developing an app that uses linphone SDK for the calling feature, however, one of my users from a particular location did not receive OTP to verify himself.

First of all, let me remind you that you can't use our free SIP service in your own app. sip.linphone.org accounts are solely to be used by Linphone apps.

> it does not show any specific logs for the OTP issue.

That being said, I can't check why OTP isn't received even in linphone-android's app without logs.

**Comment by naxtreasif** [comment]
I hope you can get the logs from the live app.

**Comment by Viish** [comment]
I can't, you have to send them to me...
Use the upload logs button in advanced settings and copy/paste the link here please.

**Comment by naxtreasif** [comment]
https://www.linphone.org:444//tmp/6286487139782_de0077c4eff8a949206c.gz

@Viish do checkout the log in the attached link.

**Comment by Viish** [comment]
Indeed they aren't helpful because you only have warning & error logs, and I need all of them.
Please enable message level logs and send new logs, from the start of the app to the moment you don't receive the OTP.

**Comment by naxtreasif** [comment]
How can I enable the message level Logs?

**Comment by naxtreasif** [comment]
Here is the screenshot of the advanced setting screen.
https://drive.google.com/file/d/1TXp34j6dKMDSl1fK58tqtduuP6ybOudU/view?usp=sharing

**Comment by Viish** [comment]
Try restarting the app?

**Comment by naxtreasif** [comment]
cleared my app data and restarted, first I have to enable logs, then I can request OTP right?

**Comment by naxtreasif** [comment]
https://www.linphone.org:444//tmp/628748e321bb9_30866ed0f5dd7b957b2d.gz

Latest logs after I restarted the app.

**Comment by Viish** [comment]
Thanks, this time it's helpful.
You're problem is that you are using a Pakistani phone number while you are located in India, and we don't allow that.

**Comment by naxtreasif** [comment]
Can you tell me how to resolve this problem, if I am on international roaming it won't allow me to log in?

**Comment by Viish** [comment]
You can't resolve this issue right now.
I recommend you create an account using your email instead of your phone number, you will receive a link by email to active your account instead of an OTP, and after that you will be able to login using your password.

**Comment by naxtreasif** [comment]
Alright, but in the app, I have the only option to create an account using the phone number. Also if I use the linphone SDK, do I have an option to create an account using an email address?

**Comment by Viish** [comment]
Yes you can create email account from our SDK, and even in linphone-android if it runs on a tablet.
