### ISSUE TITLE
Camera Crash - Android 12 huawei magic4 

### ISSUE THREAD

**Issue by mixiumixiu11** [BelledonneCommunications/linphone-android#1678]
Hello, my Linphone app crash only with an huawei, with Android 12.

The user just open the app crashes.

Please complete the following information

Device: huawei magic4
OS: Android 12 Magic UI: 6.0.0.155
Version of the App: master
[linphone.txt](https://github.com/BelledonneCommunications/linphone-android/files/8753572/linphone.txt)
[linphone2.txt](https://github.com/BelledonneCommunications/linphone-android/files/8753573/linphone2.txt)

**Comment by Viish** [comment]
Hi,
Thanks for the report, I'm creating a fix for it.
I'll update you when a new SDK AAR maven artefact will be available.
Cheers,

**Comment by mixiumixiu11** [comment]
It may be a huawei system problem because the previous version did not have this crash

**Comment by Viish** [comment]
Please try again with SDK 5.2.0-alpha.174+6d3659f (available on our maven repository).

**Comment by mixiumixiu11** [comment]
> Please try again with SDK 5.2.0-alpha.174+6d3659f (available on our maven repository).

Launching with a new AAR will still crash，This is the new crash log
[linphone3.txt](https://github.com/BelledonneCommunications/linphone-android/files/8754639/linphone3.txt)

**Comment by Viish** [comment]
Seems to be a firmware crash...
