### ISSUE TITLE
Encryption with ZRTP android VoIP

### ISSUE THREAD

**Issue by manujay** [BelledonneCommunications/linphone-android#168]
Hi I am working on an android VoIP application using this library (appreciate the work on it by you guys). The core purpose of this app is to provide secure communication. I wanted to know if there is a way that `linphone-android` provides out of the box security measures. 

Since we'll be using `ZRTP` for the media encryption, I was wondering if anyone can point me out to the piece of code where I can put the encryption code or if it's already there then please point to me where I can see it so that I can better understand my project.

**Comment by whitetornado** [comment]
zrtp will also work with voice? i can not see the settings or how to setup

**Comment by Ahmed50ayman** [comment]
You can use sub modules/externals/srtp this is the library used for encryption but zrtp used for key management
