### ISSUE TITLE
about "udp_channel_recv"

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1680]
Hi，Viish，

Thank you very much for your help。

In some cases, when the network is disconnected, the following information will be received continuously, but when the device is up and unplugs the network cable directly, it seems that the following information will not appear. I don't know under what circumstances these information will appear.

Could not receive UDP packet: Bad file descriptor

05-24 08:59:29.149 14825 14825 E tag_linphone: Receive error on channel [0xa0282000]

05-24 08:59:29.150 14825 14825 I tag_linphone: channel 0xa0282000: state ERROR

05-24 08:59:29.209 14825 14825 E tag_linphone: Could not receive UDP packet: Bad file descriptor

05-24 08:59:29.209 14825 14825 E tag_linphone: Receive error on channel [0xa0282000]

05-24 08:59:29.210 14825 14825 I tag_linphone: channel 0xa0282000: state ERROR

05-24 08:59:29.211 14825 14825 I tag_linphone: channel [0xa0282000]: ending recv background task with id=[2008ba].

05-24 08:59:29.214 14825 14825 I tag_linphone: bellesip_wake_lock_release(): Android wake lock released [ref=0x2008ba]

05-24 08:59:29.272 14825 14825 E tag_linphone: belle_sip_get_src_addr_for: bctbx_connect() failed: Network is unreachable

05-24 08:59:29.273 14825 14825 I tag_linphone: udp_listening_point: new channel created to 192.192.255.27:5060

05-24 08:59:29.279 14825 14825 I tag_linphone: bellesip_wake_lock_acquire(): Android wake lock [belle-sip recv channel] acquired [ref=0x2008be]

05-24 08:59:29.279 14825 14825 I tag_linphone: channel [0x9d5c2000]: starting recv background task with id=[2008be].

Best regards.

**Comment by Viish** [comment]
Hi,

I guess it will happen when the device is in "doze" mode (see https://developer.android.com/training/monitoring-device-state/doze-standby).
Doze mode is enabled when your app is in background after some time. When in doze mode, network is unreachable for the app. 
You can check our SDK logs for the following: `[Platform Helper] [Doze Receiver] Doze mode enabled:`
The only way to leave doze mode is either to receive a high priority push notification or resume the app.

Cheers,

**Comment by fengqz627** [comment]
Thank you very much.
I'd like to inquire with you, Is the linphone-desktop problem not maintained? I recently downloaded a linphone-desktop，and asked a question in https://github.com/BelledonneCommunications/linphone-desktop/issues, but no one replied?

**Comment by Viish** [comment]
linphone-desktop is still actively maintained, we are working on big changes for video conferencing like on mobiles.
It's just it's not me who's maintaining it and not everyone in my company takes as much time as I do to answer questions / issues on github, that's all.
