### ISSUE TITLE
About cross compiling

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1681]
Hi，Viish，

I want to cross compile. I try to find a random module, such as ortp, and then put it in his CMakeLists.txt plus：
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_C_COMPILER "arm-linux-gnueabi-gcc")
set(CMAKE_CXX_COMPILER "arm-linux-gnueabi-g++")
Then this module will call my cross compiled GCC, But there are too many CMakeLists.txt files in linphone. I don't need to open CMakeLists.txt one by one and add them manually. Then I have to cry. Is there any good way?

thanks,
Best Regards.

**Comment by Viish** [comment]
Hi,
You want to crosscompile linphone-sdk for Android arm platform, is that right?
If so, you don't have anything to do except giving to cmake the following param: `-DLINPHONESDK_ANDROID_ARCHS=arm`
Cheers,

**Comment by fengqz627** [comment]
Hi Viish,

Why can't I search the option “-DLINPHONESDK_ANDROID_ARCHS” in the code , in which file are these options defined?

Thanks.
Best Regards.

**Comment by Viish** [comment]
You can search for `LINPHONESDK_ANDROID_ARCHS` in linphone-sdk and linphone-cmake-builder projects
