### ISSUE TITLE
Outgoing call notification stuck after updating Linphone

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-android#1682]
**Describe the bug**
After updating to a new Linphone build, it appears that after the first outgoing call was hung up, the outgoing call (service) notification remains.
Could this have something to do with the TelecomManager not being aware that the call has ended? It does allow to receive new incoming calls though.

**To Reproduce**
Upgrade the Linphone app
Perform a call and hang up.

**Expected behavior**
Notification should dissapear after hanging up.

**Please complete the following information**
 - Device: Samsung Galaxy S10e
 - OS: Android 12
 - Version of the App: 4.7.0
 - Version of the SDK: 5.2.0-alpha.179+9ddc65c

**SDK logs**
[6290aa3762f14_6583fe0c279cb2ab009e.txt](https://github.com/BelledonneCommunications/linphone-android/files/8786070/6290aa3762f14_6583fe0c279cb2ab009e.txt)

**Comment by Viish** [comment]
I don't reproduce this issue using latest master linphone-android version.
Can you try branch `fix/foreground_service` and tell me if that improves things?

By the way, 4.7.0 isn't released yet, it's still an alpha version, and so is 5.2.0 SDK.

**Comment by driesken** [comment]
The fix seems to correctly remove the call notification! Thanks!

**Comment by Viish** [comment]
Great! I've merge the branch into master.
