### ISSUE TITLE
App reset without warning: accounts and other settings are gone

### ISSUE THREAD

**Issue by axelsimon** [BelledonneCommunications/linphone-android#1687]
**Describe the bug**
When opening Linphone today, i was greeted with the first-run account configuration assistant and discovered the accounts i had configured in the app had simply been deleted and other settings reset to zero. I can see the version i'm currently running was released to F-Droid on the 29th of May, so this may be due to my updating Linphone since.

**To Reproduce**
Steps to reproduce the behavior: unclear. Updating the app?

**Expected behavior**
User configuration shouldn't disappear.

**Please complete the following information**
 - Device: Pixel 2
 - OS: GrapheneOS RQ3A.210905.001.2021092816 (Android 11)
 - Version of the App 4.6.8
 - Version of the SDK 5.1.33

**SDK logs**
Not applicable: can't reproduce issue

**Adb logcat logs**
N/A

**Screenshots**
N/A

**Additional context**
This his happened to me in the past.

**Comment by Saphar** [comment]
I can say the same happened to us here on different devices LG Wine, Cubot King Kong Mini 2. Would there be a way to debug this? It doesn't seem to be reproducible it happens unexpected.

**Comment by UPBT** [comment]
This is a real issue, I had it too. 

If I only had one 3rd party account, I'd just chalk it up to the a "butt dial" thing where rattling around in my pocket caused me to hit the delete account in "settings" (for which I will note there is **no conformation**, and it's also **adjacent to a button I need to press regularly** to switch between accounts...)

Nope, I had three 3rd party accounts disappear. Concurrent, I had battery issues and didn't use the phone for a bit until I could get the phone battery working again. So sometime between Nov 26 and Dec 14.  Call history and phone book are untouched. For some reason I could only dial my voicemail account and was able to both leave a message as well as use a PIN to get into my voicemail. I'm going to have to check with my voip provider and see how that happened, and what the caller ID was on that.  

1643414378005  might be some kind of timestamp in the F-droid log for when I upgraded to 5.0.0, and that might have been when the trouble started. 

I really really wish there was **a manual I could fscking read** somewhere. Maybe someone might consider making a docuwiki and asking the folk on the email list to work on things like documenting how to use a QR code to provision. I could print out a QR code and have it handy when this happens by bug or by "butt-dialing" when I'm away from home.

**Comment by basncy** [comment]
I switch the sip server from asterisk to flexisip, this issue did not happen again.
So I guess, it might be caused by interaction with none flexisip compatible server, especially with MESSAGE.
