### ISSUE TITLE
Contact Too long 

### ISSUE THREAD

**Issue by skotow** [BelledonneCommunications/linphone-android#1688]
Sometimes Sip contact registering normally sometimes contact to long response from SIP server . 
If I look at request to server  contact really too long

**Comment by Viish** [comment]
Push information and IPv6 address may cause a quite long contact header indeed.
Disable push, remove gruu, force ipv4, etc...will reduce contact length.

**Comment by skotow** [comment]
THank you

**Comment by skotow** [comment]
P-Registrar-Error: Contact/received too long 
So what is the suggetion of it ?

**Comment by Viish** [comment]
Check if your proxy server configuration can be changed to allow for a longer contact or change your proxy server.
Or apply one or more suggestions I made above.

**Comment by skotow** [comment]
Thank you .
