### ISSUE TITLE
Android12 API 31  Loudspeaker

### ISSUE THREAD

**Issue by skotow** [BelledonneCommunications/linphone-android#1689]
Hi, loudspeaker not working, on API 31 android 12 , 
```
  ```
fun routeAudioToEarpiece(call: Call? = null) {
            routeAudioTo(arrayListOf(AudioDevice.Type.Earpiece), call)
        }

        fun routeAudioToSpeaker(call: Call? = null) {
            routeAudioTo(arrayListOf(AudioDevice.Type.Speaker), call)
        }
```
```

**Comment by Viish** [comment]
Please attach logs showing issue

**Comment by skotow** [comment]
Linphone: [AAudio] aaudio_player_callback_error has result: -899 / AAUDIO_ERROR_DISCONNECTED

**Comment by skotow** [comment]
When you juts lauch application , and you hit on click speaker it works but gives this error
  Linphone: [AAudio] aaudio_player_callback_error has result: -899 / AAUDIO_ERROR_DISCONNECTED
  When you trying to make other call is does nothing no loud speaker working , Issue only persits on Android12 API 31

**Comment by Viish** [comment]
First of all use latest SDK (5.1.x) and not 5.0.0.
Then try to reproduce with our Android app.
FInally attach full logs please (start of the app to the moment the issue is reproduced), one line isn't enough...

**Comment by skotow** [comment]
Thank you for you reply sound fixed , I did wrong check of true and false , after hungup i never set value to true , so is never went to condition enable speakers
