### ISSUE TITLE
Linphone is not sending public IP in REGISTER packet

### ISSUE THREAD

**Issue by jfalexvijay** [BelledonneCommunications/linphone-android#169]
Hi All,

I am using linphone library in my app. I have updated linphone this week. Now I am facing an issue.

    The issue is; linphone is not sending the public IP in REGISTER packet.

    1. channel [0x7f7d682000]: message sent to [domain], size: [855] bytes
    REGISTER sip:domain SIP/2.0
    Contact: <sip:userid@10.1.1.196:37869>;+sip.instance="<urn:uuid:xxx-xxx-xxx>"

    2. received [715] new bytes from domain
    SIP/2.0 401 Unauthorized
    Via: SIP/2.0 10.1.1.196:37869;alias;branch=z9hG4bK.qEqG926fz;rport=37869;received=PUBLIC_IP

    3. channel [0x7f7d682000]: message sent to [domain], size: [1152] bytes
    REGISTER sip:domain SIP/2.0
    Contact: <sip:userid@10.1.1.196:37869>;+sip.instance="<urn:uuid:xxx-xxx-xxx>"

It was working fine with the earlier linphone library.

**NOTE:** When I make outgoing calls, then all fine. Linphone includes the public ip in contact param.

**The problem is;** because of this public ip issue I am not able to receive any incoming calls.

Please help me to fix this issue.

**Comment by jfalexvijay** [comment]
Any idea ?

**Comment by Thucnv** [comment]
i have the same issue

**Comment by jfalexvijay** [comment]
I have verified the linphone PlayStore build. There is no public IP issue in the live build. But when I compile the linphone source code (git clone git://git.linphone.org/linphone-android.git --recursive) and run it is giving the same public IP issue.

It will be great if linphone team release this fix.

**Comment by jfalexvijay** [comment]
Any updates on this issue?

**Comment by Tangwen** [comment]
belle-sip -> provider.c -> fix_automatic_header_address
if (!belle_sip_header_address_get_automatic(addr)) return;
