### ISSUE TITLE
About cross compilation

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1690]
Hi Viish,

Can linphone-android run on the Linux arm 32-bit development board after cross compiling? I guess linphone-desktop should be able to cross compile, but I'm familiar with linphone-android, and I don't know about linphone-desktop at all.

Thanks.
Best Regards.

**Comment by Viish** [comment]
Linphone-Android app can only run on Android OS, so if your board is running Android yes it should work.
