### ISSUE TITLE
Register but not connected 

### ISSUE THREAD

**Issue by disolaterX** [BelledonneCommunications/linphone-android#1692]
**Describe the bug**
linphone SDK shows the account state registered. But when I check on asterisk it says unreachable. I think the app is not able to reply to the options. Request from asterisk

**Comment by Viish** [comment]
Please attach logs

**Comment by Viish** [comment]
`core.config.setInt("sip", "ping_with_options", 1)`

I'm closing this issue until you attach requested logs

**Comment by disolaterX** [comment]
> `core.config.setInt("sip", "ping_with_options", 1)`
> 
> I'm closing this issue until you attach requested logs

Thank you so much, can you guid me where to look more of this config any doc ? or link

**Comment by disolaterX** [comment]
https://github.com/BelledonneCommunications/linphone-android/issues/1249#issuecomment-1156340119

can you add more info on this

**Comment by disolaterX** [comment]
@Viish any thing ://

**Comment by disolaterX** [comment]
@Viish I really want to understand more on this

I have enabled option on asterisk, and it say my linphone is unreachable when checked via sip show peer, now when I send a notification what should do with that notification reregister the sip account or there is any manual way to simply refresh

**Comment by Viish** [comment]
If your proxy server sends a push notification using firebase, our SDK will receive it and will refresh the registration.
You can do the same manually using `core.refreshRegister()` method.

Note that by default linphone uses long Expires value (1 year) and some proxy server can't handle that.
If that's the case, you should adapt your client Expires value to the max your server allows.

**Comment by disolaterX** [comment]
How to change that expiration value

**Comment by disolaterX** [comment]
In code not in any config file

**Comment by Viish** [comment]
https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/AccountParams.html#setExpires-int-

**Comment by Viish** [comment]
As you can see the method is on AccountParams, so it's either when you create your account or when you edit an existing account.
I'll stop helping you here, it's no longer an issue but merely dev-assist and I don't do that. 
I recommend you to check our tutorials: https://gitlab.linphone.org/BC/public/tutorials/-/tree/master/android/kotlin

**Comment by disolaterX** [comment]
I am sorry but very thank you for the support
