### ISSUE TITLE
Opengl and WebRTC

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1695]
Hi Vissh,

Two questions：
1，If I only need the callee device to display the video of my device, and my device can take photo, but my device does not need preview, can my device close OpenGL? egl ?
2, Is the echo processing module of linphone webrtc？

thanks
Best Regards.

**Comment by Viish** [comment]
> 1，If I only need the callee device to display the video of my device, and my device can take photo, but my device does not need preview, can my device close OpenGL? egl ?

No, on Android to be able to capture an image from a camera you must display it.
This is a security inside Android to prevent malicious apps from taking pictures without user's knowing it.

> 2, Is the echo processing module of linphone webrtc？

Yes.
