### ISSUE TITLE
Broadcast a SIP voice message to all other SIP endpoints on the LAN

### ISSUE THREAD

**Issue by Adnan-addi** [BelledonneCommunications/linphone-android#1699]
Hi @Viish,
I am using sdk 'linphone-sdk-android-4.3.1'

I want to broadcast a sip voice message to all other sip endpoints available on the LAN.
Is there any way in linphone which or what is the correct way to implement it .
Thank You.

**Comment by Viish** [comment]
Hi,
No you can't do that in SIP.
