### ISSUE TITLE
Linphone android TLS client authentication with asterisk server

### ISSUE THREAD

**Issue by tougbia09** [BelledonneCommunications/linphone-android#17]
Hi
according to this tutorial https://wiki.linphone.org/xwiki/wiki/public/view/Liblinphone/TLS%20client%20authentication/   i got this error in astrisk server side

[Feb 22 12:49:46] ERROR[1944]: tcptls.c:636 handle_tcptls_connection: Problem setting up ssl connection: error:00000000:lib(0):func(0):reason(0)
[Feb 22 12:49:46] WARNING[1944]: tcptls.c:722 handle_tcptls_connection: FILE * open failed!

however with blink desktop everything works fine according to the official asterisk config https://wiki.asterisk.org/wiki/display/AST/Secure+Calling+Tutorial

Please any help to solve this problem !!!!!!!!

**Comment by tougbia09** [comment]
hello 
i'm sorry for disturbing you
issue fixed
thx   :-)

**Comment by amregbaly** [comment]
can you share how you fixed it !?
