### ISSUE TITLE
Linphone on Rockchip MPP hardware HD video call not support

### ISSUE THREAD

**Issue by yagneshshinde** [BelledonneCommunications/linphone-android#170]
Linphone Media-stream not support HD video Call on Rockchip MPP hardware.
is there any way to use hardware codec with Linphone lib? Using Multicodec (HEVC / AVC / VP8 / VP9) hardware decoder and  H264 Encoder.

**Comment by louisparks** [comment]
We have gotten Rockchip to work with had video now. Try again with latest build
