### ISSUE TITLE
App not receiving calls in background

### ISSUE THREAD

**Issue by kemalbalaban** [BelledonneCommunications/linphone-android#1706]
Hello, I can receive calls when the application is open, but when I put the application in the background, the call does not come. Closing the connection to the SIP server

thank you for responses

i use system features
ios, sdk 5.1.16

**Comment by Viish** [comment]
Hi,

Why are you opening an iOS issue in linphone-android project and not in linphone-iphone?

Also the answer is simple: push notifications.
Check our wiki on how to configure them properly.

**Comment by kemalbalaban** [comment]
Hi, 
I was confused while browsing the android and ios screens, I wanted to delete it, but I could not delete it because there was no authority. Don't worry.
