### ISSUE TITLE
When on video call,is Linphone has API to record video and take a picture?

### ISSUE THREAD

**Issue by Seejun** [BelledonneCommunications/linphone-android#171]
I want to do these in my project.Thank you.

**Comment by Ssisyphus** [comment]
Did you find the API to record video?

**Comment by lexusburn** [comment]
at the moment only record audio is implemented as i know: 
https://www.linphone.org/snapshots/docs/liblinphone/multilang/reference/csharp/linphone_call.html#method-Linphone.Call.StartRecording

I would like to record video and audio too. 
@BelledonneComm: please add video recording

**Comment by sbqingjiang** [comment]
Looks like only record audio is supported even though in mkv files

**Comment by sbqingjiang** [comment]
> at the moment only record audio is implemented as i know:
> https://www.linphone.org/snapshots/docs/liblinphone/multilang/reference/csharp/linphone_call.html#method-Linphone.Call.StartRecording
> 
> I would like to record video and audio too.
> @BelledonneComm: please add video recording
public void setRecordFile(String path)
Parameters
path – A string containing the path and filename of the file where audio/video streams are to be written. The filename must have either .mkv or .wav extention. The video stream will be written only if a MKV file is given.

Looks like  mkv files should be able to record videos
