### ISSUE TITLE
Calling with outboundProxy failed

### ISSUE THREAD

**Issue by hushmand** [BelledonneCommunications/linphone-android#1710]
When we enable outbound proxy and after 401 sip packet is sent to the phone, phone responds with ACK but it doesn’t send the second invite with authorization

**Comment by Viish** [comment]
Can you attach debug logs showing the issue please?

**Comment by hushmand** [comment]
I attached the debug log
But we found out from Sip server logs that linphone sdk does not send packets properly

[logCall.txt](https://github.com/BelledonneCommunications/linphone-android/files/8975027/logCall.txt)

**Comment by Viish** [comment]
I don't see any issue in your logs.
You send an invite, server answers 401, invite is sent again with authorization header, call is accepted, etc...
Why do you consider there is an issue?
