### ISSUE TITLE
CRITICAL: SIP Audio is transmitted before call is answered.

### ISSUE THREAD

**Issue by attie** [BelledonneCommunications/linphone-android#1711]
**Describe the bug**

When using a SIP account, and receiving an incomming call, the phone's microphone audio is relayed to the caller immediately, and without user interaction.
As soon as Linphone was aware of the call, the ringtone stopped at the other end, and local audio was heard - **before** answering the call... the app continues to ring, the vibration and local audio can be heard remotely, etc...

I initially thought this was related to echo cancellation: (this may be a bug in its own right)
- At first it was enabled, and the calibration showed "_Calibrated in -1ms_"
- After running "_Echo canceller calibration_", it changed to "_No echo detected_" and disabled echo cancellation
- The next call (only one) behaved properly - ringtone until it was answered
- All calls before and after misbehaved

I "_Force Stop_"-ed the app, cleared its data, and re-configured the account, but couldn't immediately reproduce this issue... which concerned me.

I tried the following:
- Settings -> Audio - system prompt for "_record audio_" permission... "_While using the app_" vs "_Only this time_"
- Settings -> Call -> "_Automatically start call recording_" - on/off (which doesn't seem to work... another bug?)
- Settings -> Call -> "_Auto answer incoming calls_" - on/off ... while on, the app doesn't ring, and starts the call immediately, fine
- Settings -> Call -> "_Accept early media_" - on/off... **while enabled, this issue is presented**

I don't remember enabling "_Accept early media_" originally, but this toggle seems to directly correlate with this issue.

Other details:
- The ringer stops, but vibration generally continues
- The notification is shown if the phone is on, but the "_incoming call_" display is not presented if the phone is off
- The remote end does not see the call as "_answered_" until the user has taken action, but the ring tone is replaced with local audio

... I also noticed a number of times when returning from the "_Settings_" menu, the app would often lockup and then die.

**To Reproduce**
2. Click on 'Settings'
3. Click on 'Call'
4. Enable 'Accept early media'
5. Receive a call

**Expected behavior**
Local audio is **never** transmitted to other end until the call has been answered - from a fresh install (my original case) or with "_Accept early media_" enabled (as above for reproduction).

**Please complete the following information**
 - Device: OnePlus 10 Pro
 - OS: Android 12
 - Version of the App 4.6.10
 - Version of the SDK 5.1.42

**SDK logs**
https://www.linphone.org:444//tmp/62b449cb0c50f_ef29154d27249429f708.gz

**Comment by Viish** [comment]
Hi @attie,

By default "Accept early media" setting is disabled, and it's purpose is exactly what you said it does: it causes audio to be sent even before call is being answered.
It's use is only relevant in a few scenarios, for example an intercom setup when you want to hear the person than rang the doorbell before deciding if you want to speak to him.

There it's not a bug but a feature ;-)
We are aware of the huge number of settings available, and for the next major design rework most of the settings (that are only intended for power users) will be hidden by default, and this one is clearly part of them.

Cheers,

**Comment by attie** [comment]
Thanks @Viish,

Understood - I'll retract my assertion of the behaviour when enabled!...
My main concern was that in the first instance I don't believe I turned this setting on.

Unfortunately I didn't collect any proof of this, but I will watch out for it in the future - it does indeed curently appear to be very tightly coupled with that toggle, so fingers crossed.

I'll re-open with more info if/when appropriate.

Attie
