### ISSUE TITLE
Sometimes crashes when navigating back from menu

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-android#1713]
**Describe the bug**
Sometimes Linphone seems to hang when trying to navigate back from the menu resulting in a crash.

**To Reproduce**
Hard te reproduce sinds it only occurs once in a while when navigating back from the settings.

Device: Samsung Galaxy S10e
OS: Android 12
Version of the App 4.7.0
Version of the SDK 5.2.0-alpha.211

**SDK logs**
[linphone_crash_280622.txt](https://github.com/BelledonneCommunications/linphone-android/files/8998183/linphone_crash_280622.txt)

**Comment by Viish** [comment]
Hi,

Are you having a crash or an ANR?
In your log file there is an ANR, but no stacktrace of a crash.
To get the crash's stacktrace you have to use `adb logcat` command.

Cheers,

**Comment by driesken** [comment]
Hi,

Looks like this was an ANR.
`2022-06-28 07:59:23:350 [org.linphone/linphone-android] MESSAGE REASON=ANR
2022-06-28 07:59:23:351 [org.linphone/linphone-android] MESSAGE TIMESTAMP=28-06-2022 07:59:17
2022-06-28 07:59:23:351 [org.linphone/linphone-android] MESSAGE DESCRIPTION=user request after error
2022-06-28 07:59:23:360 [org.linphone/linphone-android] WARNING TRACE=`

I've retrieved the ANR log from my device but it appears to have the same content as the Linphone SDK logs so I suppose there isn't much to analyze?

[anr_2022-06-28-07-59-03-033.txt](https://github.com/BelledonneCommunications/linphone-android/files/8998719/anr_2022-06-28-07-59-03-033.txt)

**Comment by Viish** [comment]
Ok then yes I know this ANR, sadly I don't know what to do with it, it seems related to the slidingpane widget.

**Comment by Viish** [comment]
Hi @driesken,

I've reworked how we handle back press in our app to try to prevent this issue.
I'm making more tests before merging it to ensure I haven't broken anything, but you are welcome to try it (branch feature/bumped_dependencies or commit id 4f26895c).

Cheers,

**Comment by Viish** [comment]
I've made intensive tests and I haven't found any issue yet, so I have merged the rework into master.

**Comment by driesken** [comment]
> I've made intensive tests and I haven't found any issue yet, so I have merged the rework into master.

Thanks again for your great effort(s)!
