### ISSUE TITLE
Linphone app crashes at initialization in one progam when in another it works just fine

### ISSUE THREAD

**Issue by vsmolovik** [BelledonneCommunications/linphone-android#1714]
Hello.

I experienced a huge problem when I tried to merge developed code from one project into another and it cannot work - at int of library it crashes in native library while the same code work in simplified applications.

I implemented Java app with a LinphoneService like BelledonneCommunications
 [linphone-android](https://github.com/BelledonneCommunications/linphone-android)  project or something like this [EasyLinphone](https://github.com/forever4313/EasyLinphone/).

So, my problem - my more complex app crashes in native library always. In case of linphone 5.1+, it crashes at first call Factory.instance(); If I dig deeper, at loading linphone library: System.loadLibrary("linphone"); while all others libraries are been loaded with no problems except loadOptionalLibrary("ffmpeg-linphone"); which is optional.
In case of Linphone 5.2+ it loads all libraries but crashes at core creation, something like this:
Factory.instance().createCore(null, null, getApplicationContext());

In case of 5.2+ I defined logging and debug:
            Factory.instance().setLogCollectionPath(basePath);
            Factory.instance().enableLogCollection(LogCollectionState.Enabled);

            String appName = getString(R.string.app_name);
            Factory.instance().setDebugMode(true, appName);
            Factory.instance().setLoggerDomain(appName);
            Factory.instance().enableLogcatLogs(true);

but the app crashes at createCore... quitely

Nothing to report about the crash, the Logcat gives a line as follows:
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x23 in tid 6743 (atact.thermovsn)

where thermovsn is my app name...
no log file is created so far...

I added the linphone  via maven repository as it is described in [Gettign Started wiki](https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Getting%20started/Android/) with and without release/debug :
* implementation "org.linphone:linphone-sdk-android:${Versions.linphone_sdk_version}"
* or like this:
  - debugImplementation "org.linphone:linphone-sdk-android-debug:${Versions.linphone_sdk_version}"
  - releaseImplementation "org.linphone:linphone-sdk-android:${Versions.linphone_sdk_version}"
 
I even tried to use liblinphone-sdk-android-5.1.46.aar  storing it in the lib folder.

In all case I got the same problem. I played with different libraries versions by changing libraries version in the app which works - it didn't help.

For now, I have no more ideas what can I try. Maybe some one here can give me a hint...

Thank you for sharing any useful information which can help,
Vlad.

**Comment by vsmolovik** [comment]
Libraries, I use:
- implementation "com.google.android.material:material:1.4.0"
- implementation "androidx.appcompat:appcompat:1.1.0" 
- implementation "androidx.preference:preference:1.1.1"
- implementation "androidx.constraintlayout:constraintlayout:2.1.4"
- implementation "androidx.recyclerview:recyclerview:1.2.1"
- implementation ( "com.journeyapps:zxing-android-embedded:4.2.0") { transitive = false }
- implementation "com.google.zxing:core:3.4.1"
- implementation "com.squareup.okhttp3:okhttp:4.9.3"
- implementation "org.nanohttpd:nanohttpd:2.3.1"
- implementation "org.nanohttpd:nanohttpd-nanolets:2.3.1"
- implementation "com.github.felHR85:UsbSerial:6.1.0"
- implementation "org.tinylog:tinylog-api:2.4.1"
- implementation "org.tinylog:tinylog-impl:2.4.1"
- implementation "com.sun.mail:android-mail:1.6.7" 
- implementation "com.sun.mail:android-activation:1.6.7"
- implementation "org.apache.ant:ant:1.10.11"
- implementation "com.github.badoo:android-weak-handler:1.2"
- implementation "com.google.code.gson:gson:2.8.8"
- implementation "com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.12.3"
- implementation("com.github.java-json-tools:json-schema-validator:2.2.14") {
        exclude group: "org.mozilla", module: "rhino"
        exclude group: "com.sun.mail", module: "mailapi"
    }

**Comment by Viish** [comment]
Hi,

Can you attach the crash's full stack trace please?

**Comment by vsmolovik** [comment]
Nothing more to share, just got in Logcat this:

W/FactoryImpl: Unable to load optional library ffmpeg-linphone: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.signatact.thermovsn-1/base.apk"],nativeLibraryDirectories=[/data/app/com.signatact.thermovsn-1/lib/arm, /data/app/com.signatact.thermovsn-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libffmpeg-linphone.so"
I/ThermoVSN FaceX: There is already a log collection handler, keep it
I/LinphoneService: com.signatact.thermovsn.hardware.sip.LinphoneService.onCreate():  ==== Device information dump ====
I/LinphoneService: com.signatact.thermovsn.hardware.sip.LinphoneService.dumpDeviceInformation(): LinphoneService.dumpDeviceInformation():
    DEVICE=rk3399_firefly_face
    MODEL=Face-RK3399
    MANUFACTURER=rockchip
    SDK=25
    Supported ABIs=arm64-v8a, armeabi-v7a, armeabi, 
I/LinphoneService: com.signatact.thermovsn.hardware.sip.LinphoneService.dumpInstalledLinphoneInformation(): LinphoneService: Linphone version is 2.2.14.newgui (22000)
I/ThermoVSN FaceX: Initializing LinphoneCore 5.2.0-alpha-206-g028739581
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x23 in tid 3028 (atact.thermovsn)
Disconnected from the target VM, address: 'localhost:63093', transport: 'socket'

In the linphone log there is no more info, you can see it as follows:

2022-06-30 13:17:57:699 [com.signatact.thermovsn/liblinphone] MESSAGE There is already a log collection handler, keep it
2022-06-30 13:17:57:718 [com.signatact.thermovsn/liblinphone] MESSAGE Initializing LinphoneCore 5.2.0-alpha-206-g028739581

**Comment by Viish** [comment]
Are you sure it is crashing because of linphone SDK?
Also it's weird logcat doesn't give you a full stack trace. Have you double-checked?

**Comment by vsmolovik** [comment]
Yes, if I comment the line of creating core everything works just fine.

It looks like there is some binary library conflict. In my app I use several face recognition libs, so, it looks like some of system library cause the crash. The most interesting part is when loading liblinphone.so in SDK 5.1+ crashes the app due to native lib crash at loading... So, if there is a way to see any debug message at library loading, it can help. I just have no idea how to archive this.

**Comment by Viish** [comment]
Except for a conflict between the libc++_shared.so we ship in our SDK AAR and one that may also be shipped by one of your dependencies I don't see what could happen.

**Comment by Viish** [comment]
Try building our SDK without including this shared lib.
Ssee cmake/Android/CopyLibs.cmake & cmake-builder/configs/config-android.cmake files in our SDK.

**Comment by vsmolovik** [comment]
Can you provide a link on tutorial how to build those libs.

**Comment by Viish** [comment]
https://github.com/BelledonneCommunications/linphone-sdk#build

**Comment by vsmolovik** [comment]
Hello,

just wanted to share the final reason of my original request:

> The crash  occurs due to incompatibility native libraries, I use in the project. Mostly, there are several face recognition libraries which use libc++_shared.so and libc++.so as well as libopencv_java3..so Those libraries are essential for linphone too, that is why I got the app crash at linphone initialization (loading native libraries).

_Loading linphone library at the first place in the app, fixes the crash of linphone library but it causes crashes of other libraries, which is simpler to manage in my case._

Another important fact, linphone uses Androidx camera2 library, in my case it forces me to migrate from Anroid.hardware.Camera to Androidx.camera.core and AndroidX.camera.camera2 libraries, otherwise the app crashes.

So, using linphone in complex applications needs attention and for those who start such development, please be prepares to migrate on latest libraries across the app. After the migration, linphone works like a charm, at least in my case.

Thank you for giving me ideas here, Vlad.

**Comment by teravinesekiel** [comment]
Hey @vsmolovik, did making the SDK without shared libs solve your problem? thanks

**Comment by vsmolovik** [comment]
Removing old static libraries solved the problem.

**Comment by rksnachap333** [comment]
@vsmolovik If i am using docker image to build sdk what are the steps need to generate sdk without shared library as my app also geting same crash issues.

**Comment by rksnachap333** [comment]
@vsmolovik @Viish I am getting crash in lower as well in some high end devices not in every device but for some devices app is crashing. Plz help with this issue.

**Comment by Viish** [comment]
@rksnachap333 take a look at https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Getting%20started/Android/, we provide a version of our SDK with only one shared lib (every dependency being statically linked into it).

**Comment by rksnachap333** [comment]
@Viish i build your sdk using docker image to customized thing like g729 etc. in that case what to do . In some device log is like  dlopen failed: library "libbctoolbox.so" not found. in some device working properly.

**Comment by rksnachap333** [comment]
@Viish tried building with with different architecture but sdk is not building properly . At the end some error occurs and for single architecture it is building.
