### ISSUE TITLE
F-Droid warns about "Upstream Non-Free"

### ISSUE THREAD

**Issue by tzugen** [BelledonneCommunications/linphone-android#1716]
The F-Droid build contains a warning flag ("Upstream Non-Free", "This Anti-Feature is applied to apps where the upstream source code includes proprietary software by default in their own releases.").

Normally apps include an explanation of these Anti Features. Could you provide one here?

**Comment by Viish** [comment]
To be able to wake-up the app in real time when an incoming call or chat message is being received we rely on Firebase push notifications which is why the upstream is flagged as "Non-Free".

**Comment by tzugen** [comment]
Can we add this info to the description?
https://github.com/BelledonneCommunications/linphone-android/blob/master/metadata/en-US/full_description.txt

I can make a PR
