### ISSUE TITLE
Error when adding people to confernce call

### ISSUE THREAD

**Issue by zadli** [BelledonneCommunications/linphone-android#1718]
Hi, I'm trying to create a conference, but I have that error

`linphone_core_invite_address_with_params(): sound are locked by another call and they cannot be freed. Call attempt is rejected.`

1. I'm creating conference
2. In a loop creating calls (Error here)
3. Adding calls to the conference

First call is okay, but after in loop on second call I had that error
I tried disabling audio in callParams, but I had a segfault

(And sorry for my bad English)

**Comment by Viish** [comment]
Hi,

Simply use this way: https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Conference.html#addParticipant-org.linphone.core.Address-
