### ISSUE TITLE
Successful registration but sometimes it is not possible to make a call

### ISSUE THREAD

**Issue by devjva** [BelledonneCommunications/linphone-android#1720]
**Describe the bug**

I can successfully register with the voip server but I can't make calls.
Incoming call works fine.

First registration request is successful then a registration failure.

**To Reproduce**
1.  linphone-sdk-android-5.0.71 with React Native and Asteriks 16

**SDK logs**

Log on call 

07-08 15:53:55.376 24121 24738 I Linphone: AuthRequested pushed
07-08 15:53:55.376 24121 24738 I Linphone: No auth info found for call id [2W63NglUAz]
07-08 15:53:55.376 24121 24738 I Linphone: Auth info not found for this refresh operation on [0xb7910540]
07-08 15:53:55.376 24121 24738 I Linphone: Register refresher [401] reason [Unauthorized] for proxy [sip:voip.some.domain:9060]
07-08 15:53:55.376 24121 24738 I Linphone: Op 0xb653e480 added as pending authentication
07-08 15:53:55.376 24121 24738 I Linphone: linphone_core_find_auth_info(): returning auth info username=123456, realm=voip.some.domain:9060
07-08 15:53:55.376 24121 24738 I Linphone: asterisk/123456/voip.some.domain/HttpDigest authentication fails.
07-08 15:53:55.376 24121 24738 I Linphone: AuthRequested pushed
07-08 15:53:55.376 24121 24738 I Linphone: Changing [client] [REGISTER] transaction [0xb916b0a0], from state [COMPLETED] to [TERMINATED]
07-08 15:53:55.376 24121 24738 I Linphone: Client internal REGISTER transaction [0xb916b0a0] terminated
07-08 15:53:55.376 24121 24738 I Linphone: transaction [0xb916b0a0]: ending transaction background task with id=[42f6].
07-08 15:53:55.378 24121 24738 I Linphone: bellesip_wake_lock_release(): Android wake lock released [ref=0x42f6]
07-08 15:53:55.378 24121 24738 I Linphone: channel [0xb41d7480]: ending recv background task with id=[41fa].
07-08 15:53:55.380 24121 24738 I Linphone: bellesip_wake_lock_release(): Android wake lock released [ref=0x41fa]
07-08 15:53:55.388 24121 24738 D LM_MNGR : Authentication requested
07-08 15:53:55.388 24121 24738 I Linphone: Linphone core [0xbe19a400] notified [authentication_requested]
07-08 15:53:55.388 24121 24738 D LM_MNGR : Authentication requested
07-08 15:53:55.388 24121 24738 I Linphone: Linphone core [0xbe19a400] notified [authentication_requested]
07-08 15:53:55.388 24121 24738 I Linphone: Account [0xbd217d00] for identity [sip:123456@voip.some.domain:9060] moving from state [LinphoneRegistrationProgress] to [LinphoneRegistrationFailed] on core [0xbe19a400]
07-08 15:53:55.388 24121 24738 I Linphone: updateDependentAccount(): 0xbd217d00 is registered, checking for [0xcbc00884] ->dependency=0x0

**Comment by devjva** [comment]
complete lo
[log.txt](https://github.com/BelledonneCommunications/linphone-android/files/9074892/log.txt)
g

**Comment by Viish** [comment]
First of all, please update to latest 5.1.x release.

Then, how many accounts did you created ?!
Please take a look at our tutorials (https://gitlab.linphone.org/BC/public/tutorials), clear your app data and start again fresh.

If issue persists please attach logs from start of the Core to the issue.

Do you reproduce using our app on your server?

**Comment by devjva** [comment]
thanks for answering .
  with version 5.1 same behavior

**Comment by devjva** [comment]
07-09 18:03:00.500  5004  5625 I Linphone: LinphoneAccount [0xb7f1fd80] about to register (LinphoneCore version: 5.1.48)
07-09 18:03:00.502  5004  5625 E Linphone: Couldn't compute automatic push notifications parameters on account [0xb7f1fd84] because account params do not have available push notifications
07-09 18:03:00.503  5004  5625 I Linphone: Transport is not specified, using tcp because UDP is not available.
07-09 18:03:00.506  5004  5625 I Linphone: bellesip_wake_lock_acquire(): Android wake lock [belle-sip transaction(0xecdeea00)] acquired [ref=0x124b2]
07-09 18:03:00.506  5004  5625 I Linphone: bellesip_wake_lock_acquire(): cast long of wakelock 74930
07-09 18:03:00.506  5004  5625 I Linphone: transaction [0xecdeea00]: starting transaction background task with id=[124b2].
07-09 18:03:00.506  5004  5625 I Linphone: Changing [client] [REGISTER] transaction [0xecdeea00], from state [INIT] to [TRYING]
07-09 18:03:00.506  5004  5625 I Linphone: Neither Expires header nor corresponding Contact header found, checking from original request
07-09 18:03:00.506  5004  5625 I Linphone: Refresher [0xb6871760] takes ownership of transaction [0xecdeea00]
07-09 18:03:00.506  5004  5625 I Linphone: Account [0xb7f1fd80] for identity [sip:123456@voip.some.domain:9060] moving from state [LinphoneRegistrationNone] to [LinphoneRegistrationProgress] on core [0xb9fc3400]

													##########################################

07-09 18:03:00.624  5004  5625 I Linphone: No auth info found for call id [JuK67a59qb]
07-09 18:03:00.624  5004  5625 I Linphone: Auth info not found for this refresh operation on [0xbc77ccc0]
07-09 18:03:00.624  5004  5625 I Linphone: Register refresher [401] reason [Unauthorized] for proxy [sip:voip.some.domain:9060]
07-09 18:03:00.624  5004  5625 I Linphone: Op 0xb53dc900 added as pending authentication
07-09 18:03:00.624  5004  5625 I Linphone: linphone_core_find_auth_info(): returning auth info username=123456, realm=voip.some.domain:9060
07-09 18:03:00.624  5004  5625 I Linphone: asterisk/123456/voip.some.domain/HttpDigest authentication fails.
07-09 18:03:00.624  5004  5625 I Linphone: AuthRequested pushed
07-09 18:03:00.625  5004  5625 I Linphone: Changing [client] [REGISTER] transaction [0xad68d240], from state [COMPLETED] to [TERMINATED]
07-09 18:03:00.625  5004  5625 I Linphone: Client internal REGISTER transaction [0xad68d240] terminated
07-09 18:03:00.630  5004  5625 I Linphone: transaction [0xad68d240]: ending transaction background task with id=[127fa].
07-09 18:03:00.632  5004  5625 I Linphone: bellesip_wake_lock_release(): Android wake lock released [ref=0x127fa]
07-09 18:03:00.633  5004  5625 I Linphone: Found transaction matching response.
07-09 18:03:00.633  5004  5625 I Linphone: Changing [client] [REGISTER] transaction [0xee25d7a0], from state [TRYING] to [COMPLETED]
07-09 18:03:00.638  5004  5625 I Linphone: AuthRequested pushed

**Comment by devjva** [comment]
> Em primeiro lugar, atualize para a versão 5.1.x mais recente.
> 
> Então, quantas contas você criou?! Por favor, dê uma olhada em nossos tutoriais ( https://gitlab.linphone.org/BC/public/tutorials ), limpe os dados do seu aplicativo e comece de novo.
> 
> Se o problema persistir, anexe logs desde o início do Core ao problema.
> 
> Você reproduz usando nosso aplicativo em seu servidor?

**Comment by devjva** [comment]
I will test with your APP

**Comment by devjva** [comment]
in the play store app apparently working fine 
Saved useragent "LinphoneAndroid/4.6.11 (M2101K7BL) LinphoneSDK/5.1.46 (tags/5.1.46^0)" for peer 123456

I think it's something with React Native.
cordova working fine.

**Comment by Viish** [comment]
Note that we don't officially support neither React Native nor Cordova.
