### ISSUE TITLE
About video package

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1721]
Hi Viish,

I have a question: my device is Linphone-Android, and my device calls callee(no linphone) ,and send audio and video to the callee. The processing ability of the chip of callee may be poor, there were occasional black screens and mosaics when callee decoded the video，How to solve this problem。
I set fps = 15, video is VGA

Thanks 
Best Regards.

**Comment by Viish** [comment]
Hi,

It can be caused by packet loss. Enabling AVPF might improve things.
Also if the chip performances are in cause, switch to H264 video codec, as we use hardware encoder/decoder it uses a lot less CPU than for VP8.

Cheers,
