### ISSUE TITLE
Video call not working.

### ISSUE THREAD

**Issue by pp1137** [BelledonneCommunications/linphone-android#1722]
Hello Team, 

I've send call request "videoEnbled = true" but when i receive incoming call from receiver end then getting "mCall.getRemoteParams().videoEnabled()" this param from linphone library is false and video call not working.
- Linphone  sdk version : 4.2

Can you please share solution for this.

**Comment by Viish** [comment]
Hi,

Video is only enabled if both caller & callee accept it.
If you initiate a video call but callee answers without accepting the video, call is audio only.

Also 4.2 is a very old release, please update to 5.1.

Cheers,

**Comment by pp1137** [comment]
Callee answer with after accepting as video call and caller also initiate call as video call but still goes into audio call.
It was working before using same 4.2 version but now it stop working.
Do you think this is version specific issue only ? 
We have also downloded linphone app from playstore Version 4.6.11 and checked but not working in app also.

**Comment by Viish** [comment]
Can you attach logs from linphone-android from the playstore you tried for both sides please?

**Comment by pp1137** [comment]
Caller side video is enabled still consider as audio call.

**Comment by Viish** [comment]
Then attach logs from caller side please
