### ISSUE TITLE
Own number is shown when receiving a call

### ISSUE THREAD

**Issue by Elendil211** [BelledonneCommunications/linphone-android#1723]
**Describe the bug**
When receiving a call, the own number is shown as well in the notification, as in the call history. The calling number is shown as sip.

When recalling, the own number is also shown as the number that is called, however the correct number is being called, and the called number is again shown as sip.

When initiating a call, everything is correct.

**To Reproduce**
1. Receive a call
2. Try to see who calls
3. Notice that it's always your own number
4. Look in call history
5. See that it's full with your own personal number

**Expected behavior**
The number of the calling person should be shown, not your own number.

 The issue occurs on multiple devices, and on multiple Android versions.

 - Version of the App: 4.6.10 (from F-Droid)

**Comment by Viish** [comment]
Please enable debug logs in advanced settings, restart the app, reproduce the issue, upload logs using button in advanced settings and finally copy/paste the link here.

**Comment by Viish** [comment]
@Elendil211 any update?

**Comment by Elendil211** [comment]
I don't like that logs have to be uploaded and are not stored locally. I would like to have the control about the data that is shared, and I want to be able to edit personal/identifying information. 

Where can I find the locally stored log?

**Comment by Viish** [comment]
Logs are stored in the app data folder, you won't be able to access it if your device isn't rooted.
You can upload your logs safely, download them, edit the part you don't want to share and attach the file here once you are done.
You can check our privacy policy, we don't do anything with the files (including logs) uploaded on our file transfer server: https://linphone.org/privacy-policy

**Comment by Elendil211** [comment]
Here is the log: [linphone1.log](https://github.com/BelledonneCommunications/linphone-android/files/9307015/linphone1.log)

**Comment by Viish** [comment]
Thanks for the logs but without the real values it is very less helpful, specifically for the issue you describe...

Anyway it seems the one making the call uses a display name "<phone_number2>" that is different from it's username "<phone_number1>", is that right?
And phone_number2 is equal to your own phone number? Is it the same as "<ID-1>"?

**Comment by Elendil211** [comment]
<phone_number2> is my own number. This number is displayed every time someone calls.

<phone_number1> is the number that is calling, and that should be displayed (but that is not displayed). I tried calling with several phones, and this issue is not related to this phone or phone number. When I call someone else with <phone_number1>, <phone_number1> is displayed correctly.

<ID-1> is the user name from my sip account, followed by a letter. It is different from <phone_number2> (there are no similarities), but it is related to it as it's the user name that I have to use in order to use the phone number.

**Comment by Viish** [comment]
From the logs I saw the problem is the person calling you using your identity as their own display name.
Linphone always displays the display name instead of the user name if there is one.
So the problem can be:
- a misconfiguration in the sip client of the person that calls you
- a bug in the sip client used by the person that calls you (I guess it's not linphone?)
- a bug in the sip proxy you use (I guess it's not sip.linphone.org?).
You can test using another linphone client to call you and/or our free SIP service, you won't have the issue (unless you added your identity as display name voluntarily).

**Comment by Elendil211** [comment]
No, that's not the case.

- *Every* person calling me is displayed wrong. No matter whether or not the caller uses sip, mobile phone, or anything else.
- The same persons calling me are displayed correctly when calling a different number, and is even displayed correctly when I use a client other than Linphone.
- The issue didn't appear prior to an update a couple months ago, it appears on multiple instances on multiple devices and without changing the configuration on any of these instances.

**Comment by Viish** [comment]
If you reproduce this issue with another Linphone client calling you, please attach logs from both devices, from the start to the call.

**Comment by Viish** [comment]
You can send logs to me by mail if you prefer: sylvain.berfini@belledonne-communications.com
