### ISSUE TITLE
How to disable landscape orientation

### ISSUE THREAD

**Issue by mircoiplabs** [BelledonneCommunications/linphone-android#1726]
Hello,

I'm looking for an easy way to set only portrait orientation for my Linphone app.

In the iOS version I found a "onlyPortrait" field which is satisfying.

is there a similar way in the Android Version? Thanks

**Comment by Viish** [comment]
Hi,

Add `android:screenOrientation="portrait"` to every activity in the AndroidManifest.xml file.
Note that I'm not here to give lesson on generic Android development, so this is the first and last time I answer such question.

Cheers,
