### ISSUE TITLE
How to save h264 stream to file

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1728]
Hi Viish,

How can linphone-Android save the H264 video stream before RTP transmission into a file, and also save the H264 stream received through RTP into a file, so that it can judge whether the video stream sent and received by my device is correct. Because the video is often abnormal due to network problems in the middle.

Thanks.
Best Regards.

**Comment by Viish** [comment]
Hi,

You can't save the sent video stream but it's easy to record the received video stream using the call record feature in the app.

Cheers,
