### ISSUE TITLE
Linphone-Android USB external camera support added for linphone-android app

### ISSUE THREAD

**Issue by Mahee2027** [BelledonneCommunications/linphone-android#1731]
I have added USB external camera support for linphone-android app and it's working fine with most of mobile which support legacy camera feature but problem is coming when I'm using camera2 support mobile.
video is coming but not clear.
I checked all step size and rotation but it's coming same as working mobile.

what problem will be there?
any help will be appreciated.

Thanks&Regards
Mahi

**Comment by Viish** [comment]
I can't help you without knowing what changes you made and having debug logs of our app/SDK.
Can you attach those?

**Comment by Mahee2027** [comment]
Hi,

This problem is solved OTG was the problem.

how can i add new plugin to linphoneSdk ?

what do i have to change?

**Comment by Viish** [comment]
Depends on the plugin.
Is it a native library?

**Comment by Mahee2027** [comment]
yes, i have added c++ file to linphoneSdk like android-camera2-capture.cpp file .

Do I need to add cmake file to cmake-builder/builders/ directory and lcb_dependencies to ms2plugins.cmake?

**Comment by Viish** [comment]
> Do I need to add cmake file to cmake-builder/builders/ directory and lcb_dependencies to ms2plugins.cmake?

If you make your own plugin yes. 
If you integrate it inside camera2 plugin you can simply add your C++ file to the plugin CMakeLists.

Keep in mind that you must comply with GPLv3 license by making your plugin open-source if you publish it.
