### ISSUE TITLE
Average call quality after call ending

### ISSUE THREAD

**Issue by disolaterX** [BelledonneCommunications/linphone-android#1732]
Is there a way to get the avg call quality from the call when the call ends, right now it give - Infinty

**Comment by Viish** [comment]
What gives -infinity? This API? https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/CallLog.html#getQuality--

What SDK are you using?
Please attach logs showing the issue.

**Comment by disolaterX** [comment]
Hi actually it solved this issue thanks for the resource
