### ISSUE TITLE
Will Call.State be sent many times?

### ISSUE THREAD

**Issue by August1023** [BelledonneCommunications/linphone-android#1734]
Will Call.State be sent many times? What is the purpose? How does the client handle receiving multiple Call.State?

**Comment by Viish** [comment]
Yes for a same Call it's state will change many times.
You can be notified of that change using either https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/CallListener.html#onStateChanged-org.linphone.core.Call-org.linphone.core.Call.State-java.lang.String- or https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/CoreListener.html#onCallStateChanged-org.linphone.core.Core-org.linphone.core.Call-org.linphone.core.Call.State-java.lang.String-

**Comment by August1023** [comment]
Will the same status of the same call be sent multiple times? For example: incomingreceived.

**Comment by Viish** [comment]
Not for incoming received, but streams running, updating, updated, paused etc ... may happen multiple times.
