### ISSUE TITLE
What does "Encrypt everything" do?

### ISSUE THREAD

**Issue by Peter4487** [BelledonneCommunications/linphone-android#1736]
Hi all!

1. **Describe the bug** (mandatory)

I have no idea what Settings>Advanced>Encrypt everything does. And I don't want to find out, because it says "Once enabled it can't be disabled!". There is one hit in the repo (the actual text in the code), and no hits on the wiki.

It's reproducible with the latest from F-Droid

Also, if applicable, **do you reproduce it with linphone-android latest release from the Play Store?**

2. **To Reproduce** (mandatory)

Just go to Settings>Advanced and scroll down to see "Encrypt everything"

3. **Expected behavior** (mandatory)

Documentation or wiki should tell me what this is

4. **Please complete the following information** (mandatory)

Pixel 5
Android 12
4.6.10
5.1.42
F-Droid
GrapheneOS

5. **SDK logs** (mandatory)

I actually can't get the logs, I receive an error "Failed to upload logs!". At some point I'll open a ticket for that.

6. **Adb logcat logs** (mandatory if native crash)

NA

7. **Screenshots** (optional)

NA

8. **Additional context** (optional)

Simple issue, not needed

Thank you in advance for filling bug reports properly!

**Comment by Viish** [comment]
Hi,

It uses a VFS implementation to encrypt every file in the app folder (configuration, databases, received files, logs, etc...).
Once you enable it only linphone will be able to read those files. For files received through chat you can use our in-app files viewer or export an unencrypted version of the file to use it in any other app as usual.

You're right it isn't very well documented, we'll work on that.
