### ISSUE TITLE
"Failed to upload logs!" when trying to upload logs

### ISSUE THREAD

**Issue by Peter4487** [BelledonneCommunications/linphone-android#1737]
Hello again linphone community,

1. **Describe the bug** (mandatory)

I can't seem to get logs working, which complicates reporting other issues of course. I've followed the instructions in the wiki, and when "Debug logs" is on and I hit "Reset logs", then do some stuff, then hit "Send logs", I see "Failed to upload logs!"

My first thought is, does this require a Belledonne account? I didn't go through that part of the setup flow because I don't want to share my contacts etc. 

2. **To Reproduce** (mandatory)

Go to Settings --> Advanced, furn "Debug logs" to on, click "Reset logs", then do some stuff to generate logs, then click "Send logs"
You will get a message that says, "Failed to upload logs!"

3. **Expected behavior** (mandatory)

Either the logs are uploaded and then somehow emailed to me, or, better yet, I can just have them on my device without uploading. The uploading step is a bit of a mystery...why not expose the logs to the user so I can just save them wherever I like?

4. **Please complete the following information** (mandatory)

 - Device: Pixel 5
 - OS: Android 12
 - Version of the App 4.6.10
 - Version of the SDK 5.1.42 
 - Where you did got it from F-Droid
 - GrapheneOS

5. **SDK logs** (mandatory)

It's a problem with logging

6. **Adb logcat logs** (mandatory if native crash)

No crash

7. **Screenshots** (optional)

Don't think screenshots would help explain

8. **Additional context** (optional)

I'm not sure that there's anything relevant.

Thank you for your attention!

**Comment by Viish** [comment]
Hi,

First of all, can you make sure you have the right log upload server URL in your advanced settings: `https://www.linphone.org:444/lft.php`.
If it still doesn't work please capture logs using adb logcat, our logs are also printed in logcat.
Finally you can find logs in the linphone-android app folder (if you have rights, on vanilla android you can only do that if the app flavor is debug or if you are rooted).

Cheers,

**Comment by Viish** [comment]
Any update?

**Comment by Viish** [comment]
Closing for now
