### ISSUE TITLE
Why does the video resolution change?

### ISSUE THREAD

**Issue by August1023** [BelledonneCommunications/linphone-android#1738]
Why does the video resolution change? How to set the fixed video resolution during a video call?

**Comment by Viish** [comment]
Here's why it happens: https://wiki.linphone.org/xwiki/wiki/public/view/FAQ/How%20does%20adaptive%20bitrate%20algorithm%20work%20%3F/

Disabling AVPF in your account's settings should disable that.

**Comment by August1023** [comment]
I set accountParams.setAvpfMode(AVPFMode.Disabled) in the accountparams class, but it is useless.

**Comment by August1023** [comment]
The SDK version I use is linphone-sdk-android-5.0.71.

**Comment by August1023** [comment]
Is it effective to use with flexisip server?
