### ISSUE TITLE
Call ringing but no notification displayed (black screen)

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-android#1739]
Hi,

I don't know if this has something to do with the other "black screen" issues since I'm using a Samsung device.

1. **Describe the bug** (mandatory)

Sometimes Linphone gets into a state where incoming calls are ringing, but no call notification is displayed. Even when having Linphone in the foregrond, I'm unable to pickup the call. I've enabled the improved bluetooth interaction (TelecomManager).

I'm also noticing "WARNING [Notifications Manager] No service found, waiting for it to start" in the logs during the event. I think Linphone might be waiting for the service to come up, but it is never launched.

"Appear on top" Android setting is enabled.

2. **To Reproduce** (mandatory)
Happens regularly after a few calls. Sometimes I can go back to the incoming call activity by opening Linphone, swiping it away from recents and relaunching it.

EDIT:
Receive an incoming all with notification.
Answer/hangup the call
Swipe Linphone from recents
Retrieve another call (device can be unlocked) -> no notification is shown but ringtone is heard
When call has ended (caller hangs up), missed called notification is shown.

3. **Expected behavior** (mandatory)
Should display the incoming call notification when ringing.

5. **Please complete the following information** (mandatory)

 - Device: Samsung XCover 5
 - OS: Android 12
 - Linphone 4.7.0
 - 5.2.0-alpha.257+ac38c34
 - local build
 - Stock android
 
[62ebffdebfb35_169b6a1bce54aef447c8.txt](https://github.com/BelledonneCommunications/linphone-android/files/9261957/62ebffdebfb35_169b6a1bce54aef447c8.txt)

**Comment by driesken** [comment]
This issue also occurs with the latest official Android 4.7.0-alpha.365+a08e447d3 snapshot.

[62ecbc41889e6_dd1cbc70812f2e9e5e04.txt](https://github.com/BelledonneCommunications/linphone-android/files/9266056/62ecbc41889e6_dd1cbc70812f2e9e5e04.txt)

**Comment by driesken** [comment]
Hi,

So I've done some more testing and it looks like reverting a few changes makes this more reliable:

```
      override fun onCallStateChanged(
            core: Core,
            call: Call,
            state: Call.State,
            message: String
        ) {
            Log.i("[Notifications Manager] Call state changed [$state]")

            if (corePreferences.preventInterfaceFromShowingUp) {
                Log.w("[Notifications Manager] We were asked to not show the call notifications")
                return
            }

            when (call.state) {
                /* ******* REVERTED CHANGES ******* */
		/*
                Call.State.IncomingEarlyMedia, Call.State.IncomingReceived -> {
                    if (service != null) {
                        Log.i("[Notifications Manager] Service isn't null, show incoming call notification")
                        displayIncomingCallNotification(call, false)
                    } else {
                        Log.w("[Notifications Manager] No service found, waiting for it to start")
                    }
                }
		*/

                Call.State.IncomingEarlyMedia, Call.State.IncomingReceived -> {
                    Log.i("[Notifications Manager] DDG - altijd weergeven van notificatie.")
                    displayIncomingCallNotification(call, false)
                }

                Call.State.End, Call.State.Error -> dismissCallNotification(call)
                Call.State.Released -> {
                    if (LinphoneUtils.isCallLogMissed(call.callLog)) {
                        displayMissedCallNotification(call.remoteAddress)
                    }
                }
                else -> displayCallNotification(call)
            }
        }
```

**Comment by Viish** [comment]
Hi @driesken,

Thanks for the info, I have an idea of what could happen.
I'm still on holidays but I'll try to find a way to fix that next week.

Cheers,

**Comment by Viish** [comment]
Hi @driesken,

Actually it was not what I was thinking.
In your latest log file (the one using 4.7.0-alpha version), can you tell me which call has the issue please?

**Comment by driesken** [comment]
Hi @Viish 

I think it was the one with call ID fe1b0e02-835c-4c5a-9fa8-cc643d133af8 (2022-08-05 08:41:36). 
I might have stopped the call attemps as soon as I had noticed the issue. Since I was unable to answer the call with Linphone, it resulted in a missed call.

**Comment by Viish** [comment]
Thanks @driesken 

Can you try commit e1fb4100 and tell me if it fixes your issue please?

**Comment by driesken** [comment]
Sure @Viish , thank youfor implementing that fix. Is it okay if I'll provide you some feedback in the following days?

**Comment by Viish** [comment]
Of course. Thanks @driesken !

**Comment by driesken** [comment]
Hi @Viish 
I've done some testing the last few days and I haven't noticed the problem anymore. Thanks for fixing!

**Comment by Viish** [comment]
Perfect, I'll merge the fix into master.
Thanks for your help !

**Comment by AshishPandeyBastionex** [comment]
i have facing same issue in android 14, Api level 34 in android. I have also created foreground services and notification call handling but my problem is not resolve when phone is locked or sleep mode, how to incoming call received in phone lock?

package com.bastionex.foxchat.Service;

import android.app.Notification;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.app.PendingIntent;
import android.app.Service;
import android.content.Intent;
import android.os.Build;
import android.os.IBinder;
import android.util.Log;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.core.app.NotificationCompat;

import com.bastionex.foxchat.Activity.IncomingCallActivity;
import com.bastionex.foxchat.R;

import org.linphone.core.Account;
import org.linphone.core.Address;
import org.linphone.core.AudioDevice;
import org.linphone.core.AuthInfo;
import org.linphone.core.AuthMethod;
import org.linphone.core.Call;
import org.linphone.core.CallLog;
import org.linphone.core.CallStats;
import org.linphone.core.ChatMessage;
import org.linphone.core.ChatRoom;
import org.linphone.core.Conference;
import org.linphone.core.ConfiguringState;
import org.linphone.core.Content;
import org.linphone.core.Core;
import org.linphone.core.CoreListener;
import org.linphone.core.CoreListenerStub;
import org.linphone.core.EcCalibratorStatus;
import org.linphone.core.Event;
import org.linphone.core.Factory;
import org.linphone.core.Friend;
import org.linphone.core.FriendList;
import org.linphone.core.GlobalState;
import org.linphone.core.InfoMessage;
import org.linphone.core.PresenceModel;
import org.linphone.core.ProxyConfig;
import org.linphone.core.PublishState;
import org.linphone.core.RegistrationState;
import org.linphone.core.SubscriptionState;
import org.linphone.core.VersionUpdateCheckResult;

public class CallHandlingService extends Service {
    private static final String TAG = "CallHandlingService";
    private static final String CHANNEL_ID = "CallHandlingChannel";
    private Core linphoneCore;
    private CoreListenerStub coreListener;

    @Override
    public void onCreate() {
        super.onCreate();
        Log.d(TAG, "Service onCreate");
        createNotificationChannel();
        startForegroundService();

        ///linphoneCore = ((MyApplication) getApplication()).getLinphoneCore();
        linphoneCore = Factory.instance().createCore(null, null, this);
        /*linphoneCore.addListener(new CoreListener() {
            @Override
            public void onNotifyPresenceReceivedForUriOrTel(@NonNull Core core, @NonNull Friend linphoneFriend, @NonNull String uriOrTel, @NonNull PresenceModel presenceModel) {

                Toast.makeText(CallHandlingService.this, "onNotifyPresenceReceivedForUriOrTel", Toast.LENGTH_SHORT).show();
            }

            @Override
            public void onMessageSent(@NonNull Core core, @NonNull ChatRoom chatRoom, @NonNull ChatMessage message) {

            }

            @Override
            public void onIsComposingReceived(@NonNull Core core, @NonNull ChatRoom chatRoom) {

            }

            @Override
            public void onConferenceStateChanged(@NonNull Core core, @NonNull Conference conference, Conference.State state) {

            }

            @Override
            public void onCallStatsUpdated(@NonNull Core core, @NonNull Call call, @NonNull CallStats callStats) {

            }

            @Override
            public void onChatRoomStateChanged(@NonNull Core core, @NonNull ChatRoom chatRoom, ChatRoom.State state) {

            }

            @Override
            public void onDtmfReceived(@NonNull Core core, @NonNull Call call, int dtmf) {

            }

            @Override
            public void onNotifyPresenceReceived(@NonNull Core core, @NonNull Friend linphoneFriend) {
                Toast.makeText(CallHandlingService.this, "onNotifyPresenceReceived", Toast.LENGTH_SHORT).show();
            }

            @Override
            public void onSubscribeReceived(@NonNull Core core, @NonNull Event linphoneEvent, @NonNull String subscribeEvent, @NonNull Content body) {

            }

            @Override
            public void onPublishStateChanged(@NonNull Core core, @NonNull Event linphoneEvent, PublishState state) {

            }

            @Override
            public void onEcCalibrationAudioInit(@NonNull Core core) {

            }

            @Override
            public void onEcCalibrationAudioUninit(@NonNull Core core) {

            }

            @Override
            public void onQrcodeFound(@NonNull Core core, @Nullable String result) {

            }

            @Override
            public void onNotifyReceived(@NonNull Core core, @NonNull Event linphoneEvent, @NonNull String notifiedEvent, @NonNull Content body) {
                Toast.makeText(CallHandlingService.this, "onNotifyReceived", Toast.LENGTH_SHORT).show();
            }

            @Override
            public void onTransferStateChanged(@NonNull Core core, @NonNull Call transfered, Call.State callState) {

            }

            @Override
            public void onLogCollectionUploadStateChanged(@NonNull Core core, Core.LogCollectionUploadState state, @NonNull String info) {

            }

            @Override
            public void onCallEncryptionChanged(@NonNull Core core, @NonNull Call call, boolean mediaEncryptionEnabled, @Nullable String authenticationToken) {

            }

            @Override
            public void onLastCallEnded(@NonNull Core core) {

            }

            @Override
            public void onCallLogUpdated(@NonNull Core core, @NonNull CallLog callLog) {

            }

            @Override
            public void onFriendListRemoved(@NonNull Core core, @NonNull FriendList friendList) {

            }

            @Override
            public void onImeeUserRegistration(@NonNull Core core, boolean status, @NonNull String userId, @NonNull String info) {

            }

            @Override
            public void onNetworkReachable(@NonNull Core core, boolean reachable) {

            }

            @Override
            public void onAccountRegistrationStateChanged(@NonNull Core core, @NonNull Account account, RegistrationState state, @NonNull String message) {

            }

            @Override
            public void onCallStateChanged(@NonNull Core core, @NonNull Call call, Call.State state, @NonNull String message) {

                if (state == Call.State.IncomingReceived) {
                    // Handle incoming call
                    handleIncomingCall(call);
                } else if (state == Call.State.OutgoingRinging) {
                    handleIncomingCall(call);

                }
            }

            @Override
            public void onMessageReceivedUnableDecrypt(@NonNull Core core, @NonNull ChatRoom chatRoom, @NonNull ChatMessage message) {

            }

            @Override
            public void onLogCollectionUploadProgressIndication(@NonNull Core core, int offset, int total) {

            }

            @Override
            public void onRegistrationStateChanged(@NonNull Core core, @NonNull ProxyConfig proxyConfig, RegistrationState state, @NonNull String message) {

            }

            @Override
            public void onInfoReceived(@NonNull Core core, @NonNull Call call, @NonNull InfoMessage message) {

            }

            @Override
            public void onChatRoomRead(@NonNull Core core, @NonNull ChatRoom chatRoom) {

            }

            @Override
            public void onEcCalibrationResult(@NonNull Core core, EcCalibratorStatus status, int delayMs) {

            }

            @Override
            public void onReferReceived(@NonNull Core core, @NonNull String referTo) {

            }

            @Override
            public void onSubscriptionStateChanged(@NonNull Core core, @NonNull Event linphoneEvent, SubscriptionState state) {

            }

            @Override
            public void onFirstCallStarted(@NonNull Core core) {

            }

            @Override
            public void onFriendListCreated(@NonNull Core core, @NonNull FriendList friendList) {

            }

            @Override
            public void onAudioDeviceChanged(@NonNull Core core, @NonNull AudioDevice audioDevice) {

            }

            @Override
            public void onCallCreated(@NonNull Core core, @NonNull Call call) {

            }

            @Override
            public void onChatRoomEphemeralMessageDeleted(@NonNull Core core, @NonNull ChatRoom chatRoom) {

            }

            @Override
            public void onNewSubscriptionRequested(@NonNull Core core, @NonNull Friend linphoneFriend, @NonNull String url) {

            }

            @Override
            public void onGlobalStateChanged(@NonNull Core core, GlobalState state, @NonNull String message) {

            }

            @Override
            public void onConfiguringStatus(@NonNull Core core, ConfiguringState status, @Nullable String message) {

            }

            @Override
            public void onBuddyInfoUpdated(@NonNull Core core, @NonNull Friend linphoneFriend) {

            }

            @Override
            public void onCallIdUpdated(@NonNull Core core, @NonNull String previousCallId, @NonNull String currentCallId) {

            }

            @Override
            public void onMessageReceived(@NonNull Core core, @NonNull ChatRoom chatRoom, @NonNull ChatMessage message) {

            }

            @Override
            public void onAudioDevicesListUpdated(@NonNull Core core) {

            }

            @Override
            public void onChatRoomSubjectChanged(@NonNull Core core, @NonNull ChatRoom chatRoom) {

            }

            @Override
            public void onAuthenticationRequested(@NonNull Core core, @NonNull AuthInfo authInfo, @NonNull AuthMethod method) {

            }

            @Override
            public void onVersionUpdateCheckResultReceived(@NonNull Core core, @NonNull VersionUpdateCheckResult result, String version, @Nullable String url) {

            }
        });*/

        // Configure push notifications
       /// configurePushNotifications(linphoneCore);
        coreListener = new CoreListenerStub() {
            @Override
            public void onCallStateChanged(@NonNull Core core, @NonNull Call call, @NonNull Call.State state, @NonNull String message) {
                Log.d(TAG, "onCallStateChanged: " + state + ", message: " + message);
                switch (state) {

                    case IncomingEarlyMedia:
                        handleIncomingCall(call);

                        break;
                    case IncomingReceived:
                        handleIncomingCall(call);
                        break;
                    case Connected:
                        Toast.makeText(CallHandlingService.this, "Call Connected", Toast.LENGTH_SHORT).show();
                        break;
                    case End:
                        Toast.makeText(CallHandlingService.this, "Call Ended", Toast.LENGTH_SHORT).show();
                        break;
                    default:
                        break;
                }
            }
        };
        linphoneCore.addListener(coreListener);

        linphoneCore.start();

        /*coreListener = new CoreListenerStub() {
            @Override
            public void onCallStateChanged(Core core, Call call, Call.State state, String message) {
                switch (state) {
                    case IncomingReceived:
                        handleIncomingCall(call);
                        break;
                    // Handle other call states as needed
                }
            }
        };
        linphoneCore.addListener(coreListener);*/
    }

   /* private void configurePushNotifications(Core linphoneCore) {
        ProxyConfig proxyConfig = linphoneCore.createProxyConfig();
        Address identity = linphoneCore.createAddress("sip:8uOHEvxhAaMwl8ec0ecak48zu6o1@64.227.160.117"); //Laxman
       /// Address identity = linphoneCore.createAddress("sip:OZ6n1027hNTvxMigxCJpahPZdAk1@64.227.160.117"); //IShanvi
        proxyConfig.setIdentityAddress(identity);

        // Enable push notifications
        proxyConfig.enableRegister(true);
        proxyConfig.setPushNotificationAllowed(true);

        // Configure the push notification token (you should get this token from your push notification service)
        proxyConfig.setContactUriParameters("pn-provider=FCM;pn-tok=coLYPfdKTA2is-MASm6VUv:APA91bF0V_-y_L9JM3WAgBdIRrF3xcjIW44B5ZcMIRrUkA6Bqp6tap3m-6D7jTlMAmtcguu7S8XLuI04x5JOvSObcibxiFOYR0_f5pT4zfZ5aADpYhHcd_UQTwBMRdQKONCiCFAmtMTW");
       /// proxyConfig.setContactUriParameters("pn-provider=FCM;pn-tok=cH7W6MjGQbKqOr7eC4xY8O:APA91bF1HK5h-eiDc_xlHDeVJ1cZZCj0sa0BysIhp5B8UyX0Ih18kxuHit7Cojdyvn-nHu5rDnuu-LMlrfMFC_8CbzB1QJhsYZccgTkxbhq7K2mRqelbXva-lpFo38XsOjbPuJcwnO3S");

        linphoneCore.addProxyConfig(proxyConfig);
        linphoneCore.setDefaultProxyConfig(proxyConfig);

        Log.d(TAG, "" + proxyConfig);
    }*/

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        Log.d(TAG, "Service onStartCommand");
        Notification notification = new NotificationCompat.Builder(this, CHANNEL_ID)
                .setContentTitle("VoIP Call Service")
                .setContentText("Handling incoming VoIP call")
                .setSmallIcon(R.drawable.ic_accept)
                .build();

        startForeground(1, notification);
        return START_STICKY;
    }

    @Override
    public IBinder onBind(Intent intent) {
        return null;
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        Log.d(TAG, "Service onDestroy");
       /// linphoneCore.removeListener(coreListener);

        if (linphoneCore != null) {
            linphoneCore.removeListener(coreListener);
            linphoneCore.stop();
            linphoneCore = null;
        }
    }

    private void handleIncomingCall(Call call) {
        Log.d(TAG, "handleIncomingCall");
        // Extract caller information
       /* String callerName = call.getRemoteAddress().getDisplayName();
        String callerNumber = call.getRemoteAddress().getUsername();

        Toast.makeText(this, "Handle Call....", Toast.LENGTH_SHORT).show();
        // Show incoming call notification
        NotificationHelper.showIncomingCallNotification(this, callerName, callerNumber);*/

        Toast.makeText(this, "Call Incoming...", Toast.LENGTH_SHORT).show();

        /*Intent callIntent = new Intent(this, IncomingCallActivity.class);
        callIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        startActivity(callIntent);*/

        showCallNotification(call.getCallLog().getCallId());
        openIncomingCallActivity(call.getCallLog().getCallId());
    }

    private void createNotificationChannel() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            NotificationChannel serviceChannel = new NotificationChannel(
                    CHANNEL_ID,
                    "Call Handling Service Channel",
                    NotificationManager.IMPORTANCE_HIGH
            );
            NotificationManager manager = getSystemService(NotificationManager.class);
            if (manager != null) {
                manager.createNotificationChannel(serviceChannel);
            }
        }
    }

    private void startForegroundService() {
        Log.d(TAG, "startForegroundService");
        Notification notification = new NotificationCompat.Builder(this, CHANNEL_ID)
                .setContentTitle("Linphone Service")
                .setContentText("Handling calls")
                .setSmallIcon(R.drawable.call_audio_start)
                .build();

        startForeground(1, notification);
    }


    private void showCallNotification(String callId) {
        Log.d(TAG, "showCallNotification");
        Intent notificationIntent = new Intent(this, IncomingCallActivity.class);
        notificationIntent.putExtra("CALL_ID", callId);
        notificationIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK |Intent.FLAG_ACTIVITY_SINGLE_TOP | Intent.FLAG_ACTIVITY_CLEAR_TASK);
        PendingIntent pendingIntent = PendingIntent.getActivity(this, 0, notificationIntent, PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_IMMUTABLE);

        Notification notification = new NotificationCompat.Builder(this, CHANNEL_ID)
                .setContentTitle("Incoming VoIP Call")
                .setContentText("You have an incoming call")
                .setSmallIcon(R.drawable.call_audio_start)
                .setContentIntent(pendingIntent)
                .setPriority(NotificationCompat.PRIORITY_HIGH)
                .setCategory(NotificationCompat.CATEGORY_CALL)
                .setOngoing(true)
                .setAutoCancel(true)
                /*.addAction(R.drawable.ic_accept, "Answer", answerPendingIntent)
                .addAction(R.drawable.ic_reject, "Reject", rejectPendingIntent)*/
                .build();

        NotificationManager notificationManager = (NotificationManager) getSystemService(NOTIFICATION_SERVICE);
        if (notificationManager != null) {
            notificationManager.notify(2, notification);
        } else {
            Log.e(TAG, "Notification Manager is null");
        }
    }

    private void openIncomingCallActivity(String callId) {
        Log.d(TAG, "openIncomingCallActivity");
        Intent intent = new Intent(this, IncomingCallActivity.class);
        intent.putExtra("CALL_ID", callId);
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
        startActivity(intent);
    }
}
