### ISSUE TITLE
Can you build a separate libmediastreamer2 SDK that includes the JNI interface?

### ISSUE THREAD

**Issue by wmailn** [BelledonneCommunications/linphone-android#1748]
Hello，I'm not pointing out a specific BUG, so I'm sorry for not following the standard format for asking questions.

My APP only needs to use MS2, not SIP, so I want to skip Liblinphone and use Mediastreamer2 directly.
However, since I am Android, I need to use JNI to call Mediastreamer2. I can't directly use the Mediastreamer2 interface.
I saw this quote in an old Linphone:

> `(optional) To generate a libmediastreamer2 SDK zip containing a full jar and native libraries, run make mediastreamer2-sdk`
https://gitlab.linphone.org/BC/public/linphone-android/tree/46df11cd43bdd154ed47b53046873becc9874abb

I can use the make mediastreamer2-sdk command to compile libmediastreamer2-SDK that includes the Java interface, but I can't find a similar compile command in the new version. Could someone please tell me how to compile libmediastreamer2-SDK with JNI interface separately?

**Comment by Viish** [comment]
Hi,

Indeed this build option not exists anymore with linphone-sdk cmake builder.

However even if it did you wouldn't get very far as mediastreamer's JNI interface is quite limited to only a few fonctions, you wouldn't be able to use it "for real".

What you can try anyway is to build linphone-sdk for Android the usual way and then remove liblinphone library.

Cheers,
