### ISSUE TITLE
Local conference and remote conference

### ISSUE THREAD

**Issue by August1023** [BelledonneCommunications/linphone-android#1749]
Hello,I have a doubt. Does a local conference refer to a conference within the same LAN? Is remote conference an Internet Conference?Thank you for your reply.

**Comment by Viish** [comment]
Hi, no it's not that. 
A local conference is when it's a client that merges the calls in one and act as it's own "conference server". 
A remote conference is when the task of merging the calls into one is done by a dedicated server.

**Comment by August1023** [comment]
Sorry, I still don't understand. Does the local conference refer to the conference hosted by the current client? Is a remote conference a conference that the current client joins as a remote participant?

**Comment by Viish** [comment]
> Does the local conference refer to the conference hosted by the current client? Is a remote conference a conference that the current client joins as a remote participant?

Exactly!
