### ISSUE TITLE
Make A direct Call to landline or Mobile Number

### ISSUE THREAD

**Issue by jmskef2022** [BelledonneCommunications/linphone-android#1750]
Just wondering , if I can I direct call to any mobile number  my ISP support that 
but when i made any call from linphone it's always prefix my input with "SIP:xxxxxx@myprovider.com"
how to change that 

thanks in advance

**Comment by Viish** [comment]
Hi,

If your VoIP provider allows you to call real phone numbers it is still a sip address that you will need to call, exactly such as the example you mention.
A SIP client such as linphone only knows how to dial SIP addresses. 
It's your provider PSTN gateway that will do the bridge between SIP and real world.

Check with your provider if the phone number must have or not the international phone prefix or not.

Cheers,

**Comment by roke-julian-lockhart** [comment]
@Viish, does documentation on this exist? Linphone's user guide doesn't mention it.

**Comment by Viish** [comment]
@RokeJulianLockhart what type of documentation are you talking about?

As I said it's up to the VoIP provider to tell their users how to configure their SIP clients when dialing phone numbers.

**Comment by roke-julian-lockhart** [comment]
@Viish, although this might appear absurd to someone knowledgable, to someone new to VOIP, downloading LinPhone, then expecting to call ITU-T E.164 telephone numbers, may not be unreasonable. I admit that that applied to me.

Consequently, at the start of the user guide, adding some basic resources, that explain to a user what they need to use LinPhone, might be helpful. Like how using a smartphone's telephone application requires that the user have an [e/micro]SIM installed, LinPhone *appears* to require a subscription to a VOIP provider to be useful. However, this has been a very difficult topic to research, for me. I've yet to locate any comprehensive resources.

**Comment by Viish** [comment]
@RokeJulianLockhart thanks for the feedback, I'll transmit it to our product owner and marketing team.
