### ISSUE TITLE
Call Status not available 

### ISSUE THREAD

**Issue by disolaterX** [BelledonneCommunications/linphone-android#1751]
Why Call.Status in not available on a call at the end 

https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Call.Status.html

**Comment by Viish** [comment]
What do you mean "at the end"?
When call state is End or Released?

**Comment by disolaterX** [comment]
Yes in onCallStateChanged 

I can’t access call.status

**Comment by Viish** [comment]
`call.status` doesn't exists, how do you use it?
You should use the following: `call.callLog.status == Call.Status.AcceptedElsewhere`.

**Comment by disolaterX** [comment]
Sorry My Mistake I was trying to access is using call.status
