### ISSUE TITLE
Set Linphonerc config file

### ISSUE THREAD

**Issue by hushmand** [BelledonneCommunications/linphone-android#1752]
I wanted to know how to set the config file for Linphone?
I went this way and only set the uuid value, but the linphone was not registered.

```
            val configPath: String = context.filesDir.absolutePath + "/.linphonerc"
            val factoryConfigPath: String = context.filesDir.absolutePath + "/linphonerc"
            val config = Factory.instance().createConfigWithFactory(configPath, factoryConfigPath)
            config.setString("misc", "uuid", "0")
            core = Factory.instance().createCoreWithConfig(config, context)
```

**Comment by Viish** [comment]
I don't understand your issue, can you be more explicit please?

**Comment by hushmand** [comment]
I want to change the configuration of the linphone
For example, put uuid=0
My question is, is it necessary to specify the path of the configuration file in the app to change the Linphonerc configuration file?
Or is this file created by default in a certain path?
Or is there another way to change the Linphone configuration?
Thank you for your guidance or if there is a tutorial on this issue, send it to me

**Comment by hushmand** [comment]
Is there an Api method to remove +sip.instance from request header?

**Comment by Viish** [comment]
No, in that case indeed you have to set it in the config file before Core starts.
