### ISSUE TITLE
How to connect to turn server java SDK?

### ISSUE THREAD

**Issue by JosephMourice** [BelledonneCommunications/linphone-android#1753]
I am trying to connect to my stun/turn server 
How I can write the connect details in the Java sdk code ?
Domain / username / password / port 

Also how to enable ICE and outbound proxy in the sdk Java code ?

**Comment by Viish** [comment]
Take a look at NatPolicy object: https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/NatPolicy.html#setTurnEnabled-boolean-

NatPolicy & outbound proxy are account params properties: https://gitlab.linphone.org/BC/public/linphone-android/-/blob/master/app/src/main/java/org/linphone/activities/main/settings/viewmodels/AccountSettingsViewModel.kt#L332
