### ISSUE TITLE
call not being recieved when app is closed

### ISSUE THREAD

**Issue by rr1164** [BelledonneCommunications/linphone-android#1756]
First of all, please say "Hi" or "Hello", it doesn't cost much.

1. **Describe the bug** (mandatory)
Hello, I have 2 phones (Android 12 and Android 10) and I'm trying to establish a call between them. the Android 12 phone makes the call and I only recieve the call on the other phone if the app is in the background or foreground. I don't receive a call when the app is completely closed. is this normal behaviour? I set up firebase and I do get notifications when the app is in background mode. I have firebase set-up.

Also, if applicable, **do you reproduce it with linphone-android latest release from the Play Store?**
it works normally on the linphone release from playstore (I recieve the call even if the app is closed)

2. **To Reproduce** (mandatory)

1- make a call from an Android 12 phone
2- have the app on the reciever's phone closed

3. **Expected behavior** (mandatory)
- I should get a notification with a ringing sound showing that a phone call is being recieved.

4. **Please complete the following information** (mandatory)

 - Device: [e.g. Samsung Note 20 Ultra]
 - caller ( Huawei nova y70)
 - reciever (Redmi 9)
 - OS: [e.g. Android 12]
 - caller( android 12)
 - reciever (android 10)
 - Version of the App [e.g. 4.6.11]
 - latest
 - Version of the SDK [e.g 5.1.48]
 - latest
 - Where you did got it from (Play Store, F-Droid, local build)
 - local build
 - Please tell us if your Android is a Lineage OS or another variant.
 - no

If you are using a SDK that isn't the latest release, please update first as it's likely your issue is already solved.

5. **SDK logs** (mandatory)

I can't find the settings tab.

In case of a call issue, please attach logs from both devices!

6. **Adb logcat logs** (mandatory if native crash)

here is the log of the caller: https://ideone.com/DBATuZ
here is the reciever log: https://ideone.com/mV3c34

**Comment by Viish** [comment]
Hi,

First of all please note that "latest" is meaningless, it doesn't help me at all.
Then enable debug logs, there is nothing helpful in the logs you attached.
Finally it is likely to be an issue in how you set up your own push notifications. Have you checked our tutorial (https://gitlab.linphone.org/BC/public/tutorials/-/tree/master/android/kotlin/2-PushNotifications) and our wiki page (https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Push%20notifications/)?

Cheers,

**Comment by rr1164** [comment]
I've read the latter page as I'm trying to set up push notifications using firebase. I've done all the steps and I still don't get any notification after the call gets placed.

sdk caller log: https://www.linphone.org:444//tmp/630d088acbda8_9a071065b2c249f2ebd8.gz
the reciever's app is closed so there are no logs

**Comment by Viish** [comment]
Please attach logs from the called device from the start of the app to the moment you kill it, so I can check if the setup is alright. Caller logs won't help much.

**Comment by Viish** [comment]
As you can see from the logs there is an issue with the push setup: 
```
[Core Manager] Push notifications aren't available (see push utils log)
[...]
ERROR [Push Notification] Firebase getToken failed: java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: MISSING_INSTANCEID_SERVICE
```

**Comment by Viish** [comment]
As it is a Huawei device are you sure it has Play Store Services available?

**Comment by rr1164** [comment]
I don't think it's related to the device. making the call from the huawei device to the redmi one gives me the same results (no notifications being pushed). I set up firebase using the assistant and replaced the google-services.json. test sending a notification message using FCM from firebase console works quite well so I can't really tell what the issue is here.

**Comment by Viish** [comment]
Can you attach the other device logs (from start to kill)?

**Comment by rr1164** [comment]
Redmi phone (Caller):  https://www.linphone.org:444//tmp/630f6b9465dc7_82e801b5989b452db3e2.gz
Huawei Phone (receiver): https://www.linphone.org:444//tmp/630f6bd0dbee2_3f33a1052f9fe867b698.gz

**Comment by Viish** [comment]
I confirm the Redmi has push correctly set up, there is no apparent reason that would prevent it from receiving a push.
The Huawei however clearly fails to init Firebase, for some reason. Maybe try do it manually in your app, you may have a better error log.

**Comment by rr1164** [comment]
can confirm it's related to huawei. I got the following error in the logcat: 
E/FirebaseMessaging: Google Play services missing or without correct permission.

**Comment by Viish** [comment]
Told you 😉

**Comment by rr1164** [comment]
quite weird though... I have no idea how to explain this bug when I release my app

**Comment by Viish** [comment]
Don't forget to respect the GPLv3 License when you release your app, or [contact our company](https://linphone.org/contact) to buy a proprietary license.
