### ISSUE TITLE
Enhancement: use android's native codec to enable AMR-WB and AMR by default

### ISSUE THREAD

**Issue by ivorget** [BelledonneCommunications/linphone-android#1758]
Hi, it should be possible to support AMR and AMR-WB via the MediaCodec library thereby using Android's native codec licence and so the codec could then be enabled by default.

Background: AMR-WB is the default wideband codec used by 3G/4G/5G mobiles and at least over my SIP provider, AMR-WB is already natively supported over SIP trunks when I call to mobile phones (tested with PortSIP app). So it would be great to have default support for this codec in linphone.

[Here's an encoding example (their problem is resolved further down).](https://stackoverflow.com/questions/61432575/android-amr-wb-encoding-issue) 

In any case AMR (NB) patents are expired now so the existing linphone AMR support could at least be default enabled, like baresip and other softphones have done. AMR is the default codec used by mobiles in 2G mode.

**Comment by Viish** [comment]
Hi,

Sorry but we won't do that as we already have an implementation of AMR NB & AMR WB in our SDK and that none of our clients are asking for it.
If this is something you really want, please [contact our company](https://linphone.org/contact) for a quotation.
