### ISSUE TITLE
Support for Themed Icons?

### ISSUE THREAD

**Issue by beaglesnuf** [BelledonneCommunications/linphone-android#1764]
Android 13 supports themed icons for personalization. For example, themes and alternative icon colors can be used to 1) increase or reduce the contrast of the orange/white icon against a light or dark mode background 2) adjust for other accessibility concerns such as color blindness. Is support for themed icons planned?

**Comment by Viish** [comment]
Hi @beaglesnuf,

This is already done in master branch, will be part of next public beta and the released.

**Comment by beaglesnuf** [comment]
Themed icon support is not yet available as of 4.6.14....

**Comment by Viish** [comment]
Yes, it will be in the next major release.

**Comment by Viish** [comment]
Hi @beaglesnuf,

You can try the public beta on the Play Store, it has the themed icon support.

Cheers,
