### ISSUE TITLE
Get a video stream through the process

### ISSUE THREAD

**Issue by Berlin-Lu** [BelledonneCommunications/linphone-android#1766]
How does the called party obtain video streaming data

**Comment by Viish** [comment]
What do you mean by "video stream data"?
Do you wish to know how to make a video call? How to display received video?
Have you checked our [tutorials](https://gitlab.linphone.org/BC/public/tutorials) our or [wiki](https://wiki.linphone.org/xwiki/wiki/public/view/Main/)?

**Comment by Berlin-Lu** [comment]
During a call, video streaming data can be passed to a third party (the camera data of the call)

**Comment by Viish** [comment]
You won't have a direct access of the raw video stream data in the app if that's what you ask.
If you want to do something like that, you have to do it in our SDK directly.

**Comment by Berlin-Lu** [comment]
Yes.  I want to use the SDK to get the camera data (incoming call) and send it to a third party

**Comment by Berlin-Lu** [comment]
How do I get it

**Comment by Viish** [comment]
Depends on if you want to get the encoded or decoded data, but it will be in https://github.com/BelledonneCommunications/mediastreamer2 project
