### ISSUE TITLE
Number keypad not visible on Unihertz Titan Pocket

### ISSUE THREAD

**Issue by Saphar** [BelledonneCommunications/linphone-android#1767]
Hello,

1. Using the Linphone 4.6.13 on Unihertz Titan Pocket. Due to the screen size the keypad doesn't show up in the dialer. Would be nice to have the keypad as it's cumbersome to enter numbers on this device and would be easier to use the touch screen. Attached is a screenshot.
2. Install app on Unihertz Titan Pocket go to the dialer page.
3. 
 - Device: Unihertz Titan Pocket
 - OS: Android 12 (LineageOS)
 - Version 4.6.13
 - Where you did got it from (downloaded from F-Droid)
 - Please tell us if your Android is a Lineage OS or another variant. Yes it is a LineageOS build.

4. **Expected behavior** (mandatory)
Show numbers on the dialpad screen.

5. **Screenshots** (optional)
Attached
![Screenshot_20220919-154511_Linphone](https://user-images.githubusercontent.com/43345112/191033937-347e390b-dba3-44c3-8a85-dc3786c4532f.png)

**Comment by Viish** [comment]
Our landscape layout on smartphone doesn't include the dialpad (because it usually doesn't fit).
What's weird is why your device (I checked on Google it seems to have a normal aspect ratio) believes it is in landscape?

**Comment by Saphar** [comment]
The resolution is 720x720 so there is no real portrait or landscape mode.

**Comment by Viish** [comment]
Can you test the following APK and tell me if it fixes the issue please? https://gitlab.linphone.org/BC/public/linphone-android/-/jobs/915432/artifacts/raw/app/build/outputs/apk/release/linphone-android-release-4.7.0-beta.2+30759c0b6.apk

**Comment by Saphar** [comment]
I tried it and it doesn't fix the issue. Thank you for your effort.

**Comment by Viish** [comment]
Damn it! 
I'll try to figure out something else and keep you updated.

**Comment by Viish** [comment]
Hi,
I purchased the device and I received it, I don't see the problem you have.
If the device is in portrait mode the dialer is visible. Indeed if I remove the lock orientation setting and put the device in landscape I have the landscape layout without the dialer, but rotating the device to portrait again make it appear.
Is your device up-to-date?

**Comment by Viish** [comment]
@Saphar Any update?

**Comment by Saphar** [comment]
As stated in my first comment, mine is flashed with Lineage. I tried it and using the original firmware it indeed does show the dialer properly. Still, I would like to keep using Lineage.

**Comment by Viish** [comment]
Sorry, I didn't noticed that.
As the official Android OS behaves as expected, I recommend you to notify people at Lineage working on this device version of their OS so they can fix it, as there is nothing I can do at app level, sorry.
