### ISSUE TITLE
Linphone Contacts problem

### ISSUE THREAD

**Issue by Maythemo** [BelledonneCommunications/linphone-android#1768]
Hi

1. **Describe the bug** 

Linphone contact shown only if the contact in the android contacts have "internet call" field set to the SIP URI

linphone latest playstore

2. **To Reproduce** 

1-Create contact in android contacts with sip URI in any of the phone number fields
2-The contact is not shown in linphone contacts
3-Then create contact in android contact and fill the SIP URI in "Internet Call" field then the contact is shown in linphone contact 

3. **Expected behavior** 

If there is a SIP URI in any android contact phone number fields the contact be shown in linphone contact

 - Device: Huawei
 - OS: android 8,9
 - Version of the App 4.6.13
 - Play Store
 - Android

**Comment by Viish** [comment]
Hi,

All contacts having a SIP URI or a phone number are displayed in the app, but only those having a phone number that is known by our presence server or a real SIP URI in the SIP URI field of the contact are displayed in the "SIP contact" filter on the top bar.
To my knowledge it isn't even possible to have a full SIP URI in the phone number field.

Can you attach debug logs from the app showing such case?

**Comment by Maythemo** [comment]
Actually I use Davx5 to sync my carddav contacts with my android phone so I can have SIP URI in my contacts phone number fields
![1 (2)](https://user-images.githubusercontent.com/112681744/191341167-07130752-f74c-4a62-9035-891eb02e0365.jpeg)
but these are not showing up in linphone contacts
if I add a contact with "internet call" field then it goes to linphone contact
![2](https://user-images.githubusercontent.com/112681744/191341733-4136d01e-6a8f-4a9a-a3d7-865916cbae16.jpeg)
![3](https://user-images.githubusercontent.com/112681744/191341935-2997edf9-1e48-4d01-a45d-6a4dd611f23f.jpeg)

As you can see I have two contacts one with SIP URI in mobile phone number field(Davx5 contact) and the other in "internet call" field but the one with "internet call" is shown in linphone contact. 
I expect that all contacts with SIP URI in any phone number field are shown in linphone contacts.

**Comment by Viish** [comment]
I can't reproduce your setup easily, please turn on debug logs in advanced settings, kill & restart the app, go to your contacts and finally go back to advanced settings, click on upload logs & copy/paste the link here (or send it to me by mail).

**Comment by Viish** [comment]
@Maythemo Can you test https://download.linphone.org/snapshots/android/linphone-android-debug-4.7.0-alpha.432+02304cdd1.apk and tell me if it works properly now please?
