### ISSUE TITLE
Reduce audio latency

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1769]
Hi,

When a caller is talking to a callee, what can we do to reduce the delay of the audio transmitted from the caller to the callee, even if the video transmitted from the caller to the callee becomes worse.

Thanks,

**Comment by Viish** [comment]
Hi,

I don't understand. Audio & video are played separately, so even if video is late it won't impact audio performances.
What could cause that is a network issue.
Anyway as usual it's hard to say without logs, versions, etc...

**Comment by fengqz627** [comment]
Hi Viish,
Thank you very much for your answer.
Caller is talking with callee, Caller sends aduio and video to callee , but the callee only needs to send audio to the caller at the same time.  after testing,  I find that the audio delay from the caller to the callee is much larger than that from the callee to the caller. How can I reduce the audio delay from the caller?

thanks.

**Comment by Viish** [comment]
Audio delay is related to the hardware as well as the type of soundcard used. 
For example OpenSLES has a higher delay than AAudio.
If you want more help on that, please contact our company for paid support.

**Comment by fengqz627** [comment]
Thank you for your answer.  I'm studying linphone myself. How can I get paid support? Who to contact?

thanks.

**Comment by Viish** [comment]
You can use this form from our website: https://linphone.org/contact#content-bottom3
