### ISSUE TITLE
Fatal Exception

### ISSUE THREAD

**Issue by disolaterX** [BelledonneCommunications/linphone-android#1770]
Fatal Exception: java.lang.UnsatisfiedLinkError: No implementation found for void org.linphone.core.CoreImpl.setNortpTimeout(long, int) (tried Java_org_linphone_core_CoreImpl_getConfig__J
       at org.linphone.core.CoreImpl.setNortpTimeout(Core.java)
       at org.linphone.core.CoreImpl.setNortpTimeout(Core.java:7643)
       
Coming from sdk linphone-sdk-android-5.1.38.aar

**Comment by Viish** [comment]
That's weird. 
Did you built it yoursefl?

Please try latest 5.1 SDK from our maven (5.1.62 at the time).

**Comment by disolaterX** [comment]
Yes we build it it, everything works fine just having these crash for setNortpTimeout

We tried to find this is coming from CoreImpl


**private native void setNortpTimeout(long var1, int var3);**

this function don’t have any declaration at all. and the reason of the crash  

public synchronized void setNortpTimeout(int seconds) {
        if (this._isConst) {
            try {
                throw new CoreException(this.toString() + " is const! If you want to call setNortpTimeout() on it, clone it first.");
            } catch (CoreException var7) {
                Log.e(new Object[]{var7});
                StackTraceElement[] var3 = var7.getStackTrace();
                int var4 = var3.length;

                for(int var5 = 0; var5 < var4; ++var5) {
                    StackTraceElement st = var3[var5];
                    Log.e(new Object[]{st});
                }
            }
        }

        this.setNortpTimeout(this.nativePtr, seconds);
    }
    
    
    Where as this is perfect code which works fine

**Comment by Viish** [comment]
I believe you made a mistake while building the SDK, and I invite you to build it again from scratch or to use one of our prebuilts, because this is what you should have in the Core.java file generated during the build:
```
private native void setNortpTimeout(long nativePtr, int seconds);
@Override
synchronized public void setNortpTimeout(int seconds)  {        
    if (_isConst) {
	try {
		throw new CoreException(this.toString() + " is const! If you want to call setNortpTimeout() on it, clone it first.");
	} catch (CoreException e) {
		Log.e(e);
		for (StackTraceElement st : e.getStackTrace()) {
			Log.e(st);
		}
	}
    }
    setNortpTimeout(nativePtr, seconds);
}
```

**Comment by Viish** [comment]
Note the `private native void setNortpTimeout(long nativePtr, int seconds);`
