### ISSUE TITLE
How to chang audio buffer

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1772]
Hi Viish,

How to reduce the audio buffer, I don't know where to change.

thanks.

**Comment by Viish** [comment]
Our Android's sound cards audio buffer size are using the device "best values" as per Google recommendations, and I strongly advise you against touching it: https://gitlab.linphone.org/BC/public/mediastreamer2/-/blob/master/java/src/org/linphone/mediastream/MediastreamerAndroidContext.java#L104

However you can change the jitter buffer size: https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Core.html#setAudioJittcomp-int-
