### ISSUE TITLE
Save audio to file

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1773]
Hi Viish,

Can I save the audio as a file before sending it to the other party? Similarly, can I save the other party's audio as a file after receiving it? How to save? I don't know whether there is a related interface.

thanks.

**Comment by Viish** [comment]
Hi,

Yes you can record a call into a file using
https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/CallParams.html#setRecordFile-java.lang.String-
and
https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Call.html#startRecording--

But you can't separate audio from caller & callee.

Cheers,
