### ISSUE TITLE
Codec Issue

### ISSUE THREAD

**Issue by disolaterX** [BelledonneCommunications/linphone-android#1775]
Does Linphone public sdk have g729 ?

IF not that how can I build my own sdk for having g729 I am unable to find some reference

**Comment by Viish** [comment]
Hi @disolaterX,

Indeed our SDK on maven / cocoapods doesn't include G729 support as you legally need to purchase a license from us to use it.
After that it's quite simple: simply add -DENABLE_G729=ON to the cmake command line when building the SDK.

**Comment by stef204** [comment]
@Viish 
So, to get the G729 codec, one would have to build his own sdk and then point to it while compiling `linphone-android` (with gradle not Android Studio)?
