### ISSUE TITLE
NO sound

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1779]
Hi Viish,

When talking, LOG is "RTP  audio=[d=71.69,u=0.38]"  why u=0.38?  how to set?

thanks.
Best Regards.

**Comment by Viish** [comment]
Hi @fengqz627,

This log prints the bandwidth used at the time. u=0.38 means the used upload bandwidth for audio packets is almost zero, which probably means you aren't sending any audio packet (or silence).

Cheers,
