### ISSUE TITLE
Linphone android, outgoing call works perfectly, incoming has some problems, like the app doesn't give me option to accept the call, it automatically accepts, then cut the call itself after some seconds.

### ISSUE THREAD

**Issue by SuneelGiri** [BelledonneCommunications/linphone-android#1781]
First of all, please say "Hi" or "Hello", it doesn't cost much.

1. **Describe the bug** (mandatory)
Hello everyone,  as title suggests, I am having trouble with incoming call. The app automatically picks the call, then after some seconds it terminates the call. I am using SIP account. twilio number. Outgoing call works perfectly. Windows app works perfectly for both incoming and outgoing.

Also, if applicable, **do you reproduce it with linphone-android latest release from the Play Store?**
Yes.

**If the issue is about the SDK (build, issue, etc...) open the ticket in the [linphone-sdk](https://github.com/BelledonneCommunications/linphone-sdk) repository or one of it's submodules!**
Not with sdk

2. **To Reproduce** (mandatory)
I installed the app, went to settings, set srtp as encryption type, turn on the mandatory encryption. Then went to assistant, choose sip account. Put on the details, it gets connected. 

3. **Expected behavior** (mandatory)
Call comes, I get pickup call interface, I hit pickup.

4. **Please complete the following information** (mandatory)

 - Device: [e.g. Samsung Note 20 Ultra] Samsung Galaxy a13
 - OS: [e.g. Android 12]  Android 12
 - Version of the App [e.g. 4.6.11]  4.6.14
 - Version of the SDK [e.g 5.1.48]
 - Where you did got it from (Play Store, F-Droid, local build) Play Store
 - Please tell us if your Android is a Lineage OS or another variant.

If you are using a SDK that isn't the latest release, please update first as it's likely your issue is already solved.

5. **SDK logs** (mandatory)

Enable debug logs in advanced section of the settings, restart the app, reproduce the issue and then go back to advanced settings, click on "Send logs" and copy/paste the link here.

It's also explained [in the README](https://github.com/BelledonneCommunications/linphone-android#behavior-issue).

In case of a call issue, please attach logs from both devices!

6. **Adb logcat logs** (mandatory if native crash)

In case of a crash of the app, please also provide the symbolized stack trace of the crash using adb logcat.

Here's the command for a arm64 device: `adb logcat | grep ndk-stack -sym <sdk build directory>/libs-debug/arm64-v8a/`

For more information, please refer to [this section of the README](https://github.com/BelledonneCommunications/linphone-android#native-crash) file.

7. **Screenshots** (optionnal)

8. **Additional context** (optionnal)

Thank you in advance for filling bug reports properly!

**Comment by Viish** [comment]
Hi,

Please attach logs, from the start of the app to the moment the incoming call is being terminated.
