### ISSUE TITLE
Ending call while it's pausing causes the app to crash.

### ISSUE THREAD

**Issue by mvdhorst** [BelledonneCommunications/linphone-android#1782]
Hi great Linphone developers,

We have altered the app a little, with those changes we don't want calls from certain destinations be in pause. Therefor when such a call is paused, it's ended. Now the first problem arrived, that is, the pause music of the PBX is played for a second on that device, which is not liked.
Therefor I altered our code a bit to end the call while in the state pausing, when doing so, the complete Linphone app crashes once end call is initiated.
I already altered my code to end the call just before answering the call, so I don't have a problem with this anymore, but I still found it useful to mention it.

Version 4.6.3 CLB version

2. **To Reproduce** (mandatory)

In your code: on call state change to pausing end the call.

Have an active Linphone connection
Let another SIP user call you
answer the phone call.

Expected: The first phone call is ended (works), the second phone call is started.
Actual: The first phone call is ended, Linphone crashes.

4. **Please complete the following information** (mandatory)

 - Device: Samsung XCover 4S
 - OS: Android 11
 - Version of the App 4.6.3
 - Version of the SDK 5.1.66
 - Where you did got it from: local build

5. **SDK logs** (mandatory)
https://www.linphone.org:444//tmp/635a32af3d4ad_31714ddc64d797f5c718.gz

6. **Adb logcat logs** (mandatory if native crash)
[logcat_crash_linphone_20221027.zip](https://github.com/BelledonneCommunications/linphone-android/files/9876996/logcat_crash_linphone_20221027.zip)
[ndk-stack.log](https://github.com/BelledonneCommunications/linphone-android/files/9877007/ndk-stack.log)

**Comment by AndreaGianarda** [comment]
Hi,

Can you try out branch release/5.2, please?

Thanks

**Comment by Viish** [comment]
Hi @mvdhorst,

Any update?
