### ISSUE TITLE
Use Speakerphone 

### ISSUE THREAD

**Issue by stef204** [BelledonneCommunications/linphone-android#1784]
Running 4.7 branch (on linux) self compiled.
I cannot see a way to turn on or use my phone's speakerphone while on a call.
Is this by design?  Or something wrong?

**Comment by Viish** [comment]
Hi @stef204 ,

I recommend you to read our wiki page about [Audio Devices](https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Audio%20devices/).

Cheers,

**Comment by stef204** [comment]
@Viish 
Thanks, I've read the pager but I do not really understand how to resolve my issue.
In order to have the Speakerphone button available on Android 11, I need to compile with the following?
```
[sound]
android_disable_audio_route_changes=1
```
If so, which file needs editing?

NOTE: I am trying to be able to select either Speakerphone or regular phone earpiece, as the case may be.  I need to have the choice, on a case by case basis.

**Comment by Viish** [comment]
@stef204,

Take a look at how we do it in linphone-android: https://gitlab.linphone.org/BC/public/linphone-android/-/blob/master/app/src/main/java/org/linphone/utils/AudioRouteUtils.kt#L155
Simply set the outputAudioDevice of a call to either the Speaker or the Earpiece device when user clicks on the toggle depending on it's state.
