### ISSUE TITLE
When talking, the voice is very low. Compared with the WeChat call, the underlying code log was captured, and a frameCount was found to be different

### ISSUE THREAD

**Issue by Avail0723** [BelledonneCommunications/linphone-android#1786]
Hi:
I use this app on my tablet:
When talking, the voice is very low. Compared with the WeChat call, the device‘s log was captured, and a frameCount was found to be different

can you fix voice is very low when talking ?
![通话声音小问题](https://user-images.githubusercontent.com/26058715/199642169-a3140995-0e1c-47dc-9371-570514ea6f5d.png)

**Comment by Avail0723** [comment]
How to modify the sampleRate?

**Comment by baralgin1003** [comment]
try to use 
`  core.micGainDb = 5f //(or different value)`

**Comment by Viish** [comment]
Hi @Avail0723 

Please attach logs of a call with the issue.

**Comment by Avail0723** [comment]
> 

OK，I get the device today, I will attach logs going soon

**Comment by Avail0723** [comment]
[none_voice_when_outgoing_.txt](https://github.com/BelledonneCommunications/linphone-android/files/9986204/none_voice_when_outgoing_.txt)
Hi,this is the logs that outgouing whitout void on my device.

**Comment by Avail0723** [comment]
Hi @Viish 
Now , the voice will be gone  after a moment.

**Comment by Avail0723** [comment]
@Viish Hi，We found that this problem only occurs on 32-bit systems. Is your app or SDK incompatible with 32-bit systems?

**Comment by Viish** [comment]
No, we do support 32 bits systems.

**Comment by Viish** [comment]
Regarding your issue, you are using PCMU audio codec.
Can you try with OPUS and tell me if the issue is the same please?

**Comment by Avail0723** [comment]
I try all ,  but still couldn't
how to fixed the codec on the linkphone code ?

**Comment by Viish** [comment]
You can't, codecs are negociated, so it chooses the best codec that both party have enabled.

**Comment by Avail0723** [comment]
> You can't, codecs are negociated, so it chooses the best codec that both party have enabled.

Do you mean the samplingRate agreed by both sides of the call?

**Comment by Viish** [comment]
Yes samplingRate is part of the negociated codec, but the actual codec used is also negociated.
What is the remote device? A linphone as well or a hardware device?

**Comment by Avail0723** [comment]
> 
the remote device is intelligent doorbell，so I should change the  intelligent doorbell's samplingRate?

**Comment by Viish** [comment]
If you can you may try it, but it would be better if you could change the codec itself.

**Comment by Avail0723** [comment]
> If you can you may try it, but it would be better if you could change the codec itself.

OK, it may be to hard to change it ,but thank you very much.
