### ISSUE TITLE
There is a serious coda in the speech

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1788]
Hi Viish,

Device A talks to device B,  when speak on device A's MIC,  Listen at the device B. every sentence has a serious coda. If I use the recording APP on A to record and then play, there is no coda.  and I checked that the coda sound should be produced by A, not B. I don't know how this coda came into being.   Is it possible that noise is brought in when compressing audio data ,has_Coda.txt is device A's log, and coda.mp4  is the sound heard from device B during a talk.

thanks,
Best Regards.

https://user-images.githubusercontent.com/45247821/200112153-dc23dc45-3239-440d-8211-372aff95c602.mp4

[has_Coda.txt](https://github.com/BelledonneCommunications/linphone-android/files/9943440/has_Coda.txt)

**Comment by Viish** [comment]
Hi,

Except that you are using your own app (knowing you it's not the latest SDK release), with the worst possible audio codec on an unknown device that runs the oldest supported version of Android and that I don't have the full logs for device B nor the logs for device A, I can't tell you much.

**Comment by fengqz627** [comment]
[has_Coda.txt](https://github.com/BelledonneCommunications/linphone-android/files/9947398/has_Coda.txt)
 This is A's log.

**Comment by fengqz627** [comment]
and B is linphone device or PJSIP device. This coda can still be heard at the B.

**Comment by Viish** [comment]
The logs seems fine, so I can't help you much here, sorry.
If you really need this to be working, please contact my company for paid support: https://linphone.org/contact
