### ISSUE TITLE
ndk-build missing

### ISSUE THREAD

**Issue by chelsea67** [BelledonneCommunications/linphone-android#179]
Hi. I'm trying to build this project.
Ive cloned the source.
First I tried prepare.py and it said something about submodules.
So I tried git submodule... commands.
Both run successfully. Now when i try prepare.py again it gives this error to me:
ERROR: The following binaries are missing: ndk-build. Please install them.

Android NDK 15 is installed and path is set.

So whats going wrong?

**Comment by SachinS47** [comment]
Hii chelsea67,

I also suffered from the same problem.

Please make sure you installed [yasm](https://www.howtoinstall.co/en/ubuntu/xenial/yasm), [nasm](https://www.howtoinstall.co/en/ubuntu/xenial/nasm), [python](https://www.howtoinstall.co/en/ubuntu/xenial/python), [pkg_config](https://www.howtoinstall.co/en/ubuntu/xenial/pkg-config) and [cmake](https://www.howtoinstall.co/en/ubuntu/xenial/cmake)(>=3.7)

Though cmake version >=3.7 is required, so I downloaded version 3.9.6  from [link](https://cmake.org/files/v3.9/cmake-3.9.6-Linux-x86_64.tar.gz).
and the run the following command to install version 3.9.6
_apt-get purge cmake_
and then, extract cmake-3.9.6-Linux-x86_64.tar.gz package and go to the directory made after extracting and run following commands:
_cp -r bin /usr/_
_cp -r doc /usr/share/_
_cp -r man /usr/share/_
_cp -r share /usr/_

**On 64 bits linux systems you'll need the ia32-libs package.**
and you need to install libstdc++6:i386 libgcc1:i386 zlib1g:i386 libncurses5:i386 libraries/depencies.

Cheers..

Note :- if using 64 bits linux based systems, let me know if you facing problem installing above libraries.

**Comment by chelsea67** [comment]
Hi and thank you for your answer.
base on your answer I successfully done ./prepare.py
now when I try to "make" the following error shows:

reza@ubuntu:~/AndroidStudioProjects/Linphone$ make
./gradlew clean
make: ./gradlew: Command not found
Makefile:23: recipe for target 'java-clean' failed
make: *** [java-clean] Error 127

**Comment by chelsea67** [comment]
Hi every one.
Problem solved using this command:
sudo apt-get install --reinstall coreutils

**Comment by DjToMeK27** [comment]
I was writing
sudo ./prepare.py 
and this caused sometimes to print this error and stop, so in this ccase just use ./prepare.py without sudo!

**Comment by mahekkausar** [comment]
Hi @chelsea67, I need your help
I am getting the same error
./gradlew clean make: ./gradlew: Command not found Makefile:23: recipe for target 'java-clean' failed make: *** [java-clean] Error 127
And I tried your solution. but it didn't work for me. Can you please what could be the other reason for this error
