### ISSUE TITLE
Can video resolution be fixed?

### ISSUE THREAD

**Issue by August1023** [BelledonneCommunications/linphone-android#1790]
Hello!
The video resolution will still change if I set it in the following way.
`VideoDefinition preferredVideoDefinition = mCore.getPreferredVideoDefinition().clone();
preferredVideoDefinition.setDefinition(720,1280);
core.setPreferredVideoDefinition(preferredVideoDefinition);
core.setAvpfMode(AVPFMode.Disabled);`

**Comment by Viish** [comment]
Hi,
It's RTCP TMMBRs that needs to be disabled to prevent the video definition to adapt to available bandwidth.
You can do it in your config file:
```
[rtp]
rtcp_fb_tmmbr_enabled=0
```
