### ISSUE TITLE
How do I turn on speakers in low version SDK?

### ISSUE THREAD

**Issue by August1023** [BelledonneCommunications/linphone-android#1791]
Because of the Android version limitation of the device, I use "linphone sdk android-4.3. aar". The code to turn on the speaker is as follows, but it cannot take effect.
`core.getCurrentCall().setSpeakerMuted(true);
                    core.getCurrentCall().setMicrophoneMuted(false);`

**Comment by Viish** [comment]
You can't modify output device from our APIs using such an old SDK.
You have to use Android AudioManager's APIs.

**Comment by August1023** [comment]
Thank you.
