### ISSUE TITLE
No video on linphone, while h264 is enabled and also visible in logs

### ISSUE THREAD

**Issue by pergolafabio** [BelledonneCommunications/linphone-android#1793]
Hi, i testing linphone android for door intercom purposes, at home i do have Hikvision devices, they use a propertary SIP protocol
How it works:
Door intercom runs a SIP server, the indoor device registers on the intercom... Then you can add extra indoor stations , they register as indoor extension on primary indoor (192.168.0.71:5065)
So in example below:
192.168.0.70 = intercom, i start a ring, and 192.168.0.71 is primary indoor, that is also inviting the extension 192.168.0.72
You can see i pickup with 192.168.0.72 , and video is coming from 192.168.0.70 ...
![image](https://user-images.githubusercontent.com/43251136/201736252-ca7d0c6d-2a33-462b-9597-884d9b599109.png)

I was trying to simulate this approach
N
so 192.168.0.70 is still intercom , 192.168.0.71 is still primary indoor, 192.168.0.232 = linphone
I captured logs with linphone desktop, easier to run wireshark, but on android its the same... The issue is that i can hear the person speaking at door, so two way audio is working fine, but video isnt going from 192.168.0.70 to 192.168.0.232 , codec h264 enabled, i also see in logs that the device 192.168.0.70 is sending h264 to 192.168.0.232 , but i dont see anything?

Anyone who can help me with this?

here is an logfile where it works:
[log1.txt](https://github.com/BelledonneCommunications/linphone-android/files/10006010/log1.txt) , as in screenshot above
here are sip logs where it doesnt work, where i setup linphone as the extension  (192.168.0.232)

[log 70 to 71.txt](https://github.com/BelledonneCommunications/linphone-android/files/10006027/log.70.to.71.txt)
[log 71 to 232.txt](https://github.com/BelledonneCommunications/linphone-android/files/10006028/log.71.to.232.txt)

i am missing something verry stupid, but  i dont know what... all look file in log, but the video s just not there, and have no clue why

thnx!!!!

**Comment by Viish** [comment]
Hi,

That's expected, client asks for sendonly / recvonly video:
```
SIP/2.0 200 OK
Via: SIP/2.0/UDP 192.168.0.70:5065;rport=5065;branch=z9hG4bK596384991
From: "DS-KD8003" <sip:10010100000@192.168.0.70>;tag=445330516
To: <sip:10010110001@192.168.0.71:5060>;tag=857193395
Call-ID: 2203815134@192.168.0.70
CSeq: 162 INVITE
Contact: <sip:10010110001@192.168.0.71:5060>
Content-Type: application/sdp
User-Agent: HKVS/2.0.0
Content-Length:   443

v=0
o=J55474650 0 0 IN IP4 192.168.0.71
s=Talk session
c=IN IP4 192.168.0.232
t=0 0
a=doorFloor:0
a=responseType:0
a=doorType:0
a=isSpecialType:2
a=isConfirm:0
a=version:V2.0.0
m=audio 9654 RTP/AVP 0 8 101
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=sendrecv
m=video 9654 RTP/AVP 96
a=rtpmap:96 H264/90000
a=fmtp:96 profile-level-id=42801F;packetization-mode=1
a=recvonly
ACK sip:10010110001@192.168.0.71:5060 SIP/2.0
Via: SIP/2.0/UDP 192.168.0.70:5065;rport;branch=z9hG4bK2540127386
From: "DS-KD8003" <sip:10010100000@192.168.0.70>;tag=445330516
To: <sip:10010110001@192.168.0.71:5060>;tag=857193395
Call-ID: 2203815134@192.168.0.70
CSeq: 162 ACK
Max-Forwards: 19
Contact: <sip:10010100000@192.168.0.70:5065>
User-Agent: HKVS/2.0.0
Content-Length: 0
```
and
```
SIP/2.0 200 Ok
Via: SIP/2.0/UDP 192.168.0.71:5060;rport;branch=z9hG4bK435969495
From: "DS-KD8003" <sip:10010100000@192.168.0.71>;tag=510348155
To: <sip:10000000001@192.168.0.232:5060>;tag=wYMUWA~
Call-ID: 1222059154
CSeq: 20 INVITE
User-Agent: Linphone Desktop/4.4.1 (XS-LT-335) Windows 10 Version 2009, Qt 5.15.2 LinphoneCore/5.1.19-1-g6cdd0918e
Supported: replaces, outbound, gruu
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO, PRACK, UPDATE
Contact: "10000000001" <sip:10000000001@192.168.0.232;transport=udp>;+sip.instance="<urn:uuid:545f75cb-bb91-0090-aa9c-7e48e24720e6>"
Content-Type: application/sdp
Content-Length: 273

v=0
o=10000000001 2229 3278 IN IP4 192.168.0.232
s=Talk
c=IN IP4 192.168.0.232
t=0 0
m=audio 7078 RTP/AVP 0 8 101
a=rtpmap:101 telephone-event/8000
m=video 9654 RTP/AVP 96
a=rtpmap:96 H264/90000
a=fmtp:96 profile-level-id=42801F; packetization-mode=1
a=sendonly
ACK sip:10000000001@192.168.0.232;transport=udp SIP/2.0
Via: SIP/2.0/UDP 192.168.0.71:5060;rport;branch=z9hG4bK2058465770
From: "DS-KD8003" <sip:10010100000@192.168.0.71>;tag=510348155
To: <sip:10000000001@192.168.0.232:5060>;tag=wYMUWA~
Call-ID: 1222059154
CSeq: 20 ACK
Contact: <sip:10010100000@192.168.0.71:5060>
Max-Forwards: 70
User-Agent: HKVS/2.0.0
Content-Length: 0
```
So it is expected that video stream will be one way.

**Comment by pergolafabio** [comment]
Hi @Viish , but i dont see it at all, there is no video at all on 0.232
you mean the video is one way to 0.232 , right?

**Comment by Viish** [comment]
No it seems to be the other way around.
In your logfile 71.to.232 the INVITE sent by 71 asks for recvonly video, so it means 71 wants to receive video and not send any, so it's expected that 232 won't receive anything.

**Comment by pergolafabio** [comment]
yes, but 70 needs to send it :-) , its normal, 71 doesnt have a camera/video, only the .70

In topicstart, you see the flow .70 starts the call, invites .71 , ... then .71 forwards also to .72 
when .72 accepts the video goes from .70 to .72

So i took out .72 and replaced it with .232 a lindphone user, that does the same register  as .72 normally does
the audio is working, the audio comes from .70 , but not the video

**Comment by Viish** [comment]
Please attach debug logs from 232 linphone app then, only the SIP traffic isn't enough.

**Comment by pergolafabio** [comment]
ok, will do it next time, thnx already!

**Comment by pergolafabio** [comment]
Hi @Viish , here are the logs, i can also add a wireshark if needed
as you can see in flow below, i start calling from 192.168.0.70 , it invites 0.71 , and then 0.71 invites 0.232 (linphone)

192.168.0.232 is registered as extension on 192.168.0.71:5065

The video should go from 0.70 to 0.232 (linphone)
If i setup another device indoor from hikvisiom
a device 192.168.0.72 that registers on 192.168.0.71:5065 , then video is visible, no issues there

any idea?

[linphone1.log](https://github.com/BelledonneCommunications/linphone-android/files/10015118/linphone1.log)


![image](https://user-images.githubusercontent.com/43251136/201993311-354edff5-5a72-4f39-8196-aca498a23910.png)
![image](https://user-images.githubusercontent.com/43251136/201993430-50b0b15e-e98d-4359-986e-7c38a6114d2f.png)

**Comment by Viish** [comment]
Hi,
I don't know what to tell you. Your devices asks that linphone doesn't receive video in the INVITE (even though it does send video packets to us...) and we comply with that request.
If it works with your hardware it means it doesn't respect that aspect of the negociation, but as I said above the hardware device does send video even though it's asking to be receive only, so it isn't doing proper SIP.
You can try with a 5.0-beta version of linphone-desktop but I'm quite sure it won't change anything, sorry.

**Comment by pergolafabio** [comment]
hi @Viish , no problem, ill try the beta version, thnx for investigating, appreciated

Btw, are you alsp part of the Linhome project? its verry quit there, any updates soon? i was told a new version was coming soon, that have background mode and other features...

**Comment by Viish** [comment]
Sorry but no, I haven't any info regarding linhome next release for now.
