### ISSUE TITLE
A peer-to-peer call

### ISSUE THREAD

**Issue by Berlin-Lu** [BelledonneCommunications/linphone-android#1796]
When I configured the virtual network adapter, I did not receive a notification when the other party answered the call

eth0      Link encap:Ethernet  HWaddr 00:18:FE:1D:E2:15
          inet addr:192.168.20.188  Bcast:192.168.20.255  Mask:255.255.255.0
          inet6 addr: fe80::218:feff:fe1d:e215/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:45567 errors:0 dropped:955 overruns:0 frame:0
          TX packets:646 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:2992819 (2.8 MiB)  TX bytes:59139 (57.7 KiB)
          Interrupt:87 Base address:0xc000

eth0:1    Link encap:Ethernet  HWaddr 00:18:FE:1D:E2:15
          inet addr:192.168.2.91  Bcast:192.168.31.255  Mask:255.255.224.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Interrupt:87 Base address:0xc000

**Comment by Viish** [comment]
Please attach full debug logs from linphone-android app.

**Comment by Berlin-Lu** [comment]
[log.txt](https://github.com/BelledonneCommunications/linphone-android/files/10010843/log.txt)

[please check](javascript:;)

**Comment by Viish** [comment]
Please restart the app, reproduce the issue and then send me new logs, above log file isn't helpful.

**Comment by Viish** [comment]
Hi @Berlin-Lu,

Any update?
