### ISSUE TITLE
Failed to turn on audio again

### ISSUE THREAD

**Issue by August1023** [BelledonneCommunications/linphone-android#1798]
Hi，The version I use is "linphone-sdk-android-4.3".
At the beginning, I turned off the audio because I only needed to deliver videos to the early media. I set it as follows:`callParams.enableAudio(false);`.
After the other party connected, I tried to turn on the audio. I set it as follows:`CallParams callParams = core.createCallParams(call);
                    callParams.enableAudio(true);
                    call.acceptUpdate(callParams);`.
But I checked the audio settings, and it is still false.I check it as follows:`call.getCurrentParams().audioEnabled();`.
There is no audio in the log:`RTP  audio=[d=0.00,u=0.00], video=[d=212.36,u=389.14,ed=1734.21], text=[d=0.00,u=0.00] kbits/sec
    	RTCP audio=[d=0.00,u=0.00], video=[d=0.59,u=2.03], text=[d=0.00,u=0.00] kbits/sec`.
Why can't I turn on the audio again?

**Comment by August1023** [comment]
`RTP audio=[d=0.00,u=0.00], video=[d=212.36,u=389.14,ed=1734.21], text=[d=0.00,u=0.00] kbits/sec 
RTCP audio=[d=0.00,u=0.00], video=[d=0.59,u=2.03], text=[d=0.00,u=0.00] kbits/sec`
What do d and u represent respectively?

**Comment by Viish** [comment]
D is for download, u for upload.

Regarding your issue, you are using a very old SDK. It may have been fixed in a release since, so you should consider upgrading.
Another solution would be to simply mute the microphone instead of disabling audio.

**Comment by August1023** [comment]
Hi, @Viish 
I changed the version to "linphone sdk android - 5.0.71".`callParams.enableAudio(false)` does not take effect.`call.getCurrentParams().audioEnabled()` is always true.

**Comment by Viish** [comment]
Hi @August1023,
5.0.71 isn't the latest release (currently it's 5.1.71).
Regarding `call.getCurrentParams().audioEnabled()` it's expected. `call.getParams().audioEnabled()` should be working as you expect.
getCurrentParams() are negociated params, getParams() are your local params and getRemoteParams() are the params of the remote end of the call.

**Comment by August1023** [comment]
Hi @Viish ,
Is there a problem with "5.0.71"? Can I continue to use "5.0.71"?
At the beginning, I turned off the audio because I only needed to deliver videos to the early media. I set it as follows:callParams.enableAudio(false);.
After the other party connected, I tried to turn on the audio. I set it as follows:CallParams callParams = core.createCallParams(call); callParams.enableAudio(true); call.acceptUpdate(callParams);.
But I checked the audio settings, and it is still false.I check it as follows:call.getParams().audioEnabled();.

**Comment by August1023** [comment]
What is the purpose of "call. getCurrentParams()"?
What is the difference between it and "call. getParams()"?

**Comment by Viish** [comment]
You can't use call.acceptUpdate(callParams) in this case to enable the audio if the initiator of the invite hasn't turned it on itself.
Instead you should start an update to turn it on: call.update(params);

Yes you can continue to use 5.0.71 but you won't receive any further support from myself or anyone in our team regarding SDK issues as we don't support it anymore.

I already explained to you the difference between the 3 call params getter above.

**Comment by August1023** [comment]
@Viish Thank you very much. Your answer has solved my problem. I myself used a method that did not meet my purpose.
