### ISSUE TITLE
linphone sends a wrong "nonce parameter"

### ISSUE THREAD

**Issue by Thucnv** [BelledonneCommunications/linphone-android#180]
Hi. i have a issues, linphone always send the same nonce param when receiver 401 Unauthorized respone from server.

[log.txt](https://github.com/BelledonneCommunications/linphone-android/files/1588308/log.txt)

Thanks.

**Comment by Thucnv** [comment]
![image](https://user-images.githubusercontent.com/20784964/42504429-f53dc0d8-8465-11e8-9b46-68ebaf8a0a87.png)
Any ideal, please help me!

**Comment by Viish** [comment]
SDK issue, not Android
