### ISSUE TITLE
How do I use echo cancellation?

### ISSUE THREAD

**Issue by August1023** [BelledonneCommunications/linphone-android#1801]
Hi,
Whether the echo cancellation function is successfully used by this configuration:`core.enableEchoCancellation(true);core.startEchoCancellerCalibration();`.Will startEchoCancellerCalibration() automatically configure the delay value?

**Comment by Viish** [comment]
Hi @August1023,

No, `startEchoCancellerCalibration()` will do a calibration and will give you the result in the `onEcCalibrationResult` callback of the `CoreListener`.
From there it's up to you to set the value using:
```
core.mediastreamerFactory.setDeviceInfo(android.os.Build.MANUFACTURER, android.os.Build.MODEL, android.os.Build.DEVICE, org.linphone.mediastream.Factory.DEVICE_HAS_BUILTIN_AEC_CRAPPY, <calibrated value>, 0)
core.reloadSoundDevices()
```

See https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Audio%20devices/

**Comment by August1023** [comment]
@Viish The delay value is different each time. How should I set it?

**Comment by Viish** [comment]
> The delay value is different each time. How should I set it?

Use the lowest.

**Comment by August1023** [comment]
@Viish Thank you. I have two more questions.

1. What should "recommended_rate" be set to?
2. Execute "core. reloadSoundDevices()" on the Android 7 device, and the app will exit abnormally without an error log. It is normal to execute "core. reloadSoundDevices()" on Android 4 devices. What should I do?

**Comment by August1023** [comment]
@Viish Thank you. I have two more questions.

1. What should "recommended_rate" be set to?
2. Execute "core. reloadSoundDevices()" on the Android 7 device, and the app will exit abnormally without an error log. It is normal to execute "core. reloadSoundDevices()" on Android 4 devices. What should I do?

**Comment by Viish** [comment]
> What should "recommended_rate" be set to?

Unless you know what you do, leave `0`.

> Execute "core. reloadSoundDevices()" on the Android 7 device, and the app will exit abnormally without an error log. It is normal to execute "core. reloadSoundDevices()" on Android 4 devices. What should I do?

If you are running linphone on an Android 4 means you are using a very old SDK that we don't support anymore, so there is nothing I can do for you, sorry.
If you reproduce the crash on latest SDK release (5.1) or current 5.2-beta then open a new issue and I'll take a look.
