### ISSUE TITLE
linphone-android not picking up local SDK during build

### ISSUE THREAD

**Issue by stef204** [BelledonneCommunications/linphone-android#1803]
I have followed the README instructions and cloned and built the `sdk` locally.

I have then edited the `gradle.properties` file to add the path to my `build` directory of the `sdk` .
The `sdk` version built seems to be `5.2.0-alpha.358+fe511c0` but the `'linphone-android` sdk listed in `About` in `linphone-android` is and stays `5.2.0-beta.89+635a5b9` no matter what I do, i.e. it builds `linphone-android` without recognizing the local `sdk`.

I also created a `gradle.properties` file inside the `$GRADLE_USER_HOME` dir with the LinphoneSdkBuildDir=(path-to-my)linphone-sdk/build/; and still the `sdk` is not being picked up.

I do not use Android Studio but build like this:

`gradlew clean assembleRelease`

and then

`gradlew installRelease`

What am I doing wrong?

**Comment by Viish** [comment]
Hi,

Gradle picks the most recent SDK, and in this case alpha is considered than beta (and that's good).
Two options:
- Either you hardcode the alpha SDK version value you built in the build.gradle file 
- or you disable our online maven repository in settings.gradle (comment it out or remove it completely)

By the way you really should build a SDK from release/5.2 branch instead of master to have the latest version.

**Comment by stef204** [comment]
Thanks.  So the solution is to not build `master` but `release/5.2` ?  If it is more recent than what's in the `'linphone-android` repo, it will be used, if not hardcode or disable/remove maven repo.

To disable maven in `linphone-android`, which lines in the [settings.gradle](https://github.com/BelledonneCommunications/linphone-android/blob/master/settings.gradle)?

16-22 or 8-22 ?

**Comment by Viish** [comment]
Only the only maven repo so 16-22.

**Comment by stef204** [comment]
Thanks.

**Comment by stef204** [comment]
Running into compilation issues (which I have not run into before.)
I'll post here but let me know if you want me to open a separate ticket.

Using either `java-19-openjdk` or `java-11-openjdk`

I get [these](https://paste.xinu.at/mmO4R/) errors (with `--debug`)

And this running without `--debug`

````
> Task :app:kaptReleaseKotlin
warning: ERROR: View field icon collides with a variable or import file://app/src/main/res/layout/settings_widget_basic.xml Line:29
warning: ERROR: View field dialogMessage collides with a variable or import file://app/src/main/res/layout/voip_dialog_info.xml Line:33

> Task :app:compileReleaseKotlin FAILED
e: /mnt/ssdd/Downloads/src/linphone-android/app/src/main/java/org/linphone/activities/voip/viewmodels/ConferenceViewModel.kt: (180, 9): 'onActiveSpeakerParticipantDevice' overrides nothing
e: /mnt/ssdd/Downloads/src/linphone-android/app/src/main/java/org/linphone/activities/voip/viewmodels/ConferenceViewModel.kt: (466, 60): Unresolved reference: activeSpeakerParticipantDevice

FAILURE: Build failed with an exception.
````

Can't quite figure it out.

**Comment by stef204** [comment]
Let me open a new ticket on the compilation fail issue.
