### ISSUE TITLE
Compilation Fail - "'onActiveSpeakerParticipantDevice' overrides nothing"

### ISSUE THREAD

**Issue by stef204** [BelledonneCommunications/linphone-android#1804]
Trying to build `release/4.7` with self compiled `sdk 5.2.0-beta`.

I am running into errors, which I cannot figure out:

[Here](https://paste.xinu.at/tds7w/) is the link to the error.

Basically:

````
> Task :app:compileReleaseKotlin FAILED
e: /mnt/ssdd/Downloads/src/linphone-android/app/src/main/java/org/linphone/activities/voip/viewmodels/ConferenceViewModel.kt: (180, 9): 'onActiveSpeakerParticipantDevice' overrides nothing
e: /mnt/ssdd/Downloads/src/linphone-android/app/src/main/java/org/linphone/activities/voip/viewmodels/ConferenceViewModel.kt: (466, 60): Unresolved reference: activeSpeakerParticipantDevice

FAILURE: Build failed with an exception.
````

**Comment by Viish** [comment]
Hi @stef204 

That means you are building an "old" version of the release/5.2 SDK as these methods have been added a few weeks ago.
Make sure you are building the latest version of release/5.2 branch.

**Comment by stef204** [comment]
I forgot to `git submodule update --init --recursive` after switching to `release/5.2`.
Build successful now.
