### ISSUE TITLE
Contacts with SIP address not in SIP-Contacts

### ISSUE THREAD

**Issue by tidenhub** [BelledonneCommunications/linphone-android#1807]
Hello,
currently, the Linphone App is not showing any contacts in SIP-Contacts. I can't say since which update they are not shown anymore, other than it has been a while.

**To Reproduce**
1. ) Create contact with sip details in contact app.
2. ) Open Linphone and switch to SIP-Contacts.

**Expected behavior**
See contacts with SIP address in SIP-Contacts tap.

**SDK logs**
https://www.linphone.org:444//tmp/63887e4f60adf_6670676f3354d1644bbf.gz

**Details**
 - Device: Google Pixel 6, Huawei P30
 - OS: Android 13, Android 10
 - Version of the App: 4.6.14
 - Version of the SDK: 5.1.62
 - Where you did got it from: Play Store

**Comment by Viish** [comment]
Hi,

Can you please attach debug logs?

Thanks in advance.

**Comment by tidenhub** [comment]
Done. See original post.

**Comment by Viish** [comment]
Indeed it doesn't find any SIP contacts matching `sip.tbz-pariv.de` domain name.
Are you sure your SIP contacts have the same domain as your default account (or no domain)?

**Comment by tidenhub** [comment]
Ah okay, the subdomain is different. Thanks, for pointing out.

So it only shows contacts with the exact same domain. Well, then I guess I have to change the domain for all contacts to show up.

Anyway, I would expect to see all contacts with a SIP address, and not just the ones with the same domain.

**Comment by Viish** [comment]
Another option is to store only the username in your contact's SIP address field.

**Comment by lm2lm2** [comment]
> Hello, currently, the Linphone App is not showing any contacts in SIP-Contacts. I can't say since which update they are not shown anymore, other than it has been a while.
> 
> **To Reproduce**
> 
>     1. ) Create contact with sip details in contact app.
> 
>     2. ) Open Linphone and switch to SIP-Contacts.
> 
> 
> **Expected behavior** See contacts with SIP address in SIP-Contacts tap.
> 
> **SDK logs** https://www.linphone.org:444//tmp/63887e4f60adf_6670676f3354d1644bbf.gz
> 
> **Details**
> 
>     * Device: Google Pixel 6, Huawei P30
> 
>     * OS: Android 13, Android 10
> 
>     * Version of the App: 4.6.14
> 
>     * Version of the SDK: 5.1.62
> 
>     * Where you did got it from: Play Store

hello

im wondering about a similar thing, on andro11:
when added SIP addresses to the contacts part, where, address@domain.net (we use several sip providers/domains),  from the google contacts, to the linphone app, the "@" get transformed into "%40", means address%40domain.net, where it's the issue, to do a call to alice%40provider.org, it's just impossible (instead of alice@provider.org)..

is there a way to fix it? ;)
