### ISSUE TITLE
Port Listing not working

### ISSUE THREAD

**Issue by disolaterX** [BelledonneCommunications/linphone-android#1808]
I set the below value just after I create the core.

core.config.setInt("sip", "sip_random_port", 0)
core.config.setInt("sip", "sip_port", 9080)
core.config.setInt("sip", "sip_tcp_port", 9080)

but this is what is happing

Creating listening point [0x72ca805e70] on [sip:[::0]:-2;transport=TCP]
Random TCP port is 42421

**Comment by Viish** [comment]
That's too late.
You have to set those values in the config before creating the Core.

**Comment by disolaterX** [comment]
@Viish We don't use linphonerc file 

how can we create config before creating core using method like thi s

config.setInt("sip", "sip_random_port", 0)

**Comment by disolaterX** [comment]
@Viish can you help and point to and example to use createConfigFromString

**Comment by Viish** [comment]
You can create the Core from an existing config object:
```
val config = Factory.instance().createConfigWithFactory(corePreferences.configPath, corePreferences.factoryConfigPath)
val core = Factory.instance().createCoreWithConfig(config, context)
```

See https://gitlab.linphone.org/BC/public/linphone-android/-/blob/master/app/src/main/java/org/linphone/LinphoneApplication.kt#L62 and https://gitlab.linphone.org/BC/public/linphone-android/-/blob/master/app/src/main/java/org/linphone/core/CoreContext.kt#L305
