### ISSUE TITLE
How to use AEC instead of AECM on Android？

### ISSUE THREAD

**Issue by guodongAndroid** [BelledonneCommunications/linphone-android#1809]
![image](https://user-images.githubusercontent.com/19586334/205428034-ee522853-a11f-42dc-bdc6-bf82c922cdaa.png)

Is 250ms AEC delay? But I set it to 100ms.

Set by the following way:
![image](https://user-images.githubusercontent.com/19586334/205428123-2cb1c97d-c999-4cb4-a783-6656bff23bfd.png)

**Comment by Viish** [comment]
To change the EC delay, use:
```
core.mediastreamerFactory.setDeviceInfo(android.os.Build.MANUFACTURER, android.os.Build.MODEL, android.os.Build.DEVICE, 0, 100, 0)
core.reloadSoundDevices()
```

To change from WebRTCAECM to WebRTCAEC, use the following: 
`config.setInt("sound", "ec_filter", "MSWebRTCAEC")` 
or 
`core.echoCancellerFilterName = "MSWebRTCAEC"`

**Comment by guodongAndroid** [comment]
Thank you very much.
