### ISSUE TITLE
Understanding branching

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1811]
Hi.

I'm just noticing the state of the release/4.7 branch.  It has commit 8f0f71d82 landed on it in the last 24h which appears to bump the app to 5.0.0.

While I could see how that would make sense on master I'm not sure I'm following how/why it should be on release/4.7.  I would think the next release from that branch, if there were any at all even would be 4.7.1.

Ultimately, the symptom I am seeing is that building the app from relelase/4.7 actually brands it as 5.0.0.  Surely that cannot be correct, can it?

**Comment by Viish** [comment]
Hi,

We have decided not to release the new version of the app as the 4.7.0 but instead as the 5.0.0.
To not leave the branch as-is, I've finished the commits of the release on that branch, tagged the release (5.0.0) and created a new branch for it (release/5.0) on which we will do the maintenance (release/4.7 branch won't move forward).

I hope it clarifies.

**Comment by brianjmurrell** [comment]
Oh.  I see.  Makes sense now.

Thanks for the explanation.

**Comment by Viish** [comment]
You're welcome.
