### ISSUE TITLE
locked <0x029e6db2> (a org.linphone.core.ConferenceImpl)

### ISSUE THREAD

**Issue by August1023** [BelledonneCommunications/linphone-android#1812]
Hi,
When does this error occur?
`    runtime.cc:655]   native: #46 pc 000e6974  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+100)
    runtime.cc:655]   native: #47 pc 00078567  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+71)
    runtime.cc:655]   at org.linphone.core.ConferenceImpl.inviteParticipants(Native method)
    runtime.cc:655]   at org.linphone.core.ConferenceImpl.inviteParticipants(Conference.java:780)
A/intercomandroi: runtime.cc:655]   - locked <0x029e6db2> (a org.linphone.core.ConferenceImpl)`

**Comment by Viish** [comment]
Hi,

I need more info. Can you attach full logs, the complete & symbolized stack trace, the version of the SDK, etc...

**Comment by August1023** [comment]
linphone-sdk-android-5.0.71.
Below is the log of project operation:
[locked_error_log.txt](https://github.com/BelledonneCommunications/linphone-android/files/10184221/locked_error_log.txt)

**Comment by Viish** [comment]
Please update to 5.2.0 SDK, this issue shouldn't happen anymore.
