### ISSUE TITLE
Overview of XML settings

### ISSUE THREAD

**Issue by mvdhorst** [BelledonneCommunications/linphone-android#1813]
This is more a question than a bug, I'm sorry for that.
Is there an overview of the XML settings which can be done using remote provisioning?
I've seen the [Wiki ](https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Remote%20Provisioning/) and the example: https://www.linphone.org/remote_provisioning.xml
Are there more possible settings, or is the example the complete reference?

Thanks in advance!

**Comment by Viish** [comment]
Hi @mvdhorst,

No there is no exhaustive documentation about what setting is available or not.
Any config setting from https://github.com/BelledonneCommunications/linphone-android/blob/master/app/src/main/java/org/linphone/core/CorePreferences.kt can be used, as well as any config setting from LinphoneSDK and even any key/value couple you may want.

**Comment by aniruddh-soomuch** [comment]
Hi @Viish, I am getting similar crash when we are trying to login with remote provisioning. Here are the crash logs, can you share any hint from these logs?

[bctool.txt](https://github.com/BelledonneCommunications/linphone-android/files/12909758/bctool.txt)
