### ISSUE TITLE
OPUS codec optimsziation issue

### ISSUE THREAD

**Issue by disolaterX** [BelledonneCommunications/linphone-android#1815]
Hey @Viish 

![image](https://user-images.githubusercontent.com/42447408/206836375-589cd585-94eb-4469-8187-faf26b025fa4.png)

How to force to use NB (narrowband) in opus in linphone

**Comment by terrytotalk** [comment]
just set the upload bandwidth under 30k

**Comment by disolaterX** [comment]
should I limit download bandwidth too ? how does it effects in this case

**Comment by terrytotalk** [comment]
according to my experience, no need to set download bandwidth. because the download bandwidth is just the upload bandwidth of the remote side.

**Comment by Viish** [comment]
> How to force to use NB (narrowband) in opus in linphone

You can't.

Limiting bandwidth to achieve such goal is merely a workaround as Opus adapts itself to the available bandwidth.
