### ISSUE TITLE
How do I call multiple devices at the same time

### ISSUE THREAD

**Issue by MuYiC** [BelledonneCommunications/linphone-android#1816]
How do I call multiple devices at the same time no server. When a callee accept call, others hang up automatically,i tried to use Conference like this
 public void startCalls(List<String> addressList, int port, boolean enableVideo) {
        Core core = LinphoneKnowinTalk.getInstance().getCore();

        ConferenceParams conferenceParams = core.createConferenceParams(null);
        conferenceParams.setVideoEnabled(true);
        Conference conference = core.createConferenceWithParams(conferenceParams);
        if (conference == null) {
            logger.e(TAG, "create conference failed.");
            return;
        }

        Address[] addresses = new Address[addressList.size()];
        int i = 0;
        for (String participant : addressList) {
            Address address = core.createAddress(participant);
            if (address == null) {
                logger.e(TAG, "startVideoCall: interpret url failed.");
                continue;
            }
            address.setPort(port);
            addresses[i++] = address;
        }

        CallParams params = core.createCallParams(null);
        if (params == null) {
            logger.e(TAG, "startVideoCall: create call params failed.");
            return;
        }
        params.setVideoEnabled(enableVideo);

        conference.inviteParticipants(addresses, params);
    }

But there's no video
Are there other ways to do this?

**Comment by Viish** [comment]
You can't make video conference by merging calls locally using our SDK.

**Comment by MuYiC** [comment]
> 
can you tell me the api  should be used?

**Comment by Viish** [comment]
If you want to make a video group call you need a conference server and to follow these steps: https://gitlab.linphone.org/BC/public/linphone-android/-/blob/release/5.0/app/src/main/java/org/linphone/activities/main/conference/viewmodels/ConferenceSchedulingViewModel.kt#L259
