### ISSUE TITLE
Hard to set specific session timeout

### ISSUE THREAD

**Issue by xxorax** [BelledonneCommunications/linphone-android#1817]
We have **OVH SIP account** entirely managed, and we often did not get calls. Even there is no problem when we tested it, ma,y users report issue about calls they never get (no ring, no notification , nothing).

We discovered, by trying other applications, that there is no session timeout settings in the configuration the SIP account on Linphone zpp  (last version on Android 13).

To be able to set the session timeout, he had to modify the **URI in the SIP Proxy field** ( account configuration -> Advanced > Transport ) to append  `;expire=1200` to the existing value.
So for OVH it becomes like `sip:sip.ovh.fr;transport=udp;expire=1200` 

We did not notice any missed calls since we applied this change.

In fact I do not remember where I found this parameter, and I cannot find why it's working (or fakely working ?).

This issue is to bring notice that there is only few SIP parameters in this Android App, and some are necessary to make it works on some providers. I would be great to add setting fields for them.

Thanks !

**Comment by terrytotalk** [comment]
i don't think the value of "expire" has anything to do with "incoming call".

**Comment by Viish** [comment]
@xxorax if you need to modify the expire value you can do so in the account settings of the app directly.

**Comment by bagherfathi** [comment]
@terrytotalk 
I experienced, When your tegister expire time is too long, linphone client address maybe is invalid or android force to sleep linphone, then can't get any incoming call without any reaction 
When you decrease the expire to 5 minute, every things works good
