### ISSUE TITLE
How to start videocall without local preview

### ISSUE THREAD

**Issue by KORuL** [BelledonneCommunications/linphone-android#1819]
Good afternoon
I want to initiate a call and not turn on the camera on the device but see the video of the call

```
             coreContext.core.nativeVideoWindowId = binding.remoteVideoSurface
             coreContext.core.nativePreviewWindowId = binding.localPreviewVideoSurface
             coreContext.core.usePreviewWindow(false)

             coreContext.core.isVideoDisplayEnabled = true
             coreContext.core.isVideoPreviewEnabled = false
```

like this everything works fine, but only the preview is shown, I don't want to request access to the camera and show the preview

I try to do so

```
             coreContext.core.nativeVideoWindowId = binding.remoteVideoSurface
             coreContext.core.nativePreviewWindowId = null//binding.localPreviewVideoSurface
```

- Video does not start

I try like this

`             coreContext.core.isVideoCaptureEnabled = false`

- also the video does not work

Here is the log if `nativePreviewWindowId = null`

[linphone.txt](https://github.com/BelledonneCommunications/linphone-android/files/10278725/linphone.txt)

**Comment by KORuL** [comment]
It can also be useful on tablets that do not have cameras, but they connect to the intercom video call

**Comment by Viish** [comment]
Hi,

There is no issue in the logs you attached, simply the remote end didn't sent any video packet.
Check the remote client side logs to see why.

Cheers,
