### ISSUE TITLE
GrapheneOS Notifications 

### ISSUE THREAD

**Issue by OfficialGitCub** [BelledonneCommunications/linphone-android#1821]
Hello Linphone Team!

 Thank you for all of your hard work..

1. **Describe the bug** (mandatory)

Calls going to an active SIP number with Linphone installed and running in Graphene OS unreliably trigger call incoming notification. Call notifications may work for one/two secounds then end. Picking up/waking up Pixel device while call comes in tends to help notificaiton come through. 

2. **To Reproduce** (mandatory)

Build current setup. Call voip number utilizing Linphone SIP account. Await notification. 

3. **Expected behavior** (mandatory)

All incoming calls trigger a Linphone notificaiton. 

4. **Please complete the following information** (mandatory)

 - Device: Pixel6
 - OS: GrapheneOS
 - Version of the App 5.0.0
 - Version of the SDK [NOT sure. 
 - Where you did got it from F-Droid

Not aware of SDK 

Thank you..

**Comment by Viish** [comment]
Hi,

Please attach a video recording of your screen so I can understand the issue better.
Also attach debug logs from the app please.

Cheers,

**Comment by Viish** [comment]
Any update?

**Comment by OfficialGitCub** [comment]
Confirming this is now working properly. May have been a bug with GOS - . Thank you .
