### ISSUE TITLE
Where is LinphoneRC in Android?

### ISSUE THREAD

**Issue by is-smok** [BelledonneCommunications/linphone-android#1822]
Hi folks.
I've been searching for a few days for linphonerc file and certificate store that linphone use. I've googled some informations about raw/res folder but haven't found it on my device. Where can I find config files in android 12?
TY.

**Comment by Viish** [comment]
Hi,
RC file is available in the project assets folder.
Once app is installed, the file is available in the application private folder, which you can only access if you are root or if you installed a `debuggable` version of the app.
Cheers,
