### ISSUE TITLE
[Question]: What is audio_video_conference_factory_uri used for?

### ISSUE THREAD

**Issue by basncy** [BelledonneCommunications/linphone-android#1823]
Hi, Viish
Could I get these answers from you? Thank you.

1. What is audio_video_conference_factory_uri used for?
https://github.com/BelledonneCommunications/linphone-iphone/blob/329193d2fa36666d85c01e6573d58bc2cf6a7a83/Resources/assistant_linphone_existing.rc#L21

2. Can audio_video_conference_factory_uri work independently (without LIME server)? I saw somebody try to bring up Group Chat but failed with LIME server, while linphone 5.0 makes these all settable.
https://github.com/BelledonneCommunications/flexisip/issues/104#issuecomment-690751497

3.  Can we set the value the same as conference_factory_uri? There's no flexisip sample configuration at this moment.

**Comment by Viish** [comment]
Hi,

> What is audio_video_conference_factory_uri used for?

It's the SIP URI on which the call conferencing server is configured to receive the conferences creations requests on.

> Can audio_video_conference_factory_uri work independently (without LIME server)?

Yes, you can do audio/video conferences without LIME as LIME is only for chat messages E2E encryption.

> Can we set the value the same as conference_factory_uri?

I don't think so as it would confuse the flexisip proxy as whether the received INVITE is for a chat room or a conference.

Hope it clarifies.

Cheers,

**Comment by basncy** [comment]
Thank you Viish.
Try to fill in sip:videoconference-factory2@sip.linphone.org and leave the other two settings blank, it seems to depend on LIME too to create a group first.
Well, looking forward to some sample configurations from flexisip.

**Comment by Viish** [comment]
Hi,
Video conference factory URI doesn't depends on LIME, so you can leave LIME server URL empty.

**Comment by basncy** [comment]
Can I use it on my private instance? if yes, how to config? there's only a conference server config from wiki https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/Configuration/Conference%20server%20configuration/

This feature still depends on the conference URI, https://i.imgur.com/shRqwDl.png, https://imgur.com/538L8KA
and conference URI depends on LIME. 
If I enable the conference server on flexisip, and fill in conference URI and video conference URI on the client, then launch a video conference, nothing happens.

**Comment by Viish** [comment]
Yes, video conferencing depends on having a video conference server SIP URI, but LIME isn't needed.
LIME is a closed-source server for now, so you can't install it yourself.
The video conferencing server in flexisip hasn't been released yet, it is still in beta and we don't have documentation for it yet.
The link for the conference server in our wiki is about the group chat server (which is technically a conference server), not the video conferencing server.

**Comment by basncy** [comment]
Thanks for your explanation, then I have to wait for the official stable release.

**Comment by samwell-ho** [comment]
I'm also interested in the video conferencing feature of Linphone/Flexisip.

Does anyone know if Belledonne Communications has released this feature or if we still have to use Flexisip at linphone.org?

**Comment by basncy** [comment]
> Does anyone know if Belledonne Communications has released this feature or if we still have to use Flexisip at linphone.org?

It is in beta without documentation, you can enable it manually with the help of source code. https://github.com/BelledonneCommunications/flexisip/blob/04ae879f23684e5c7179f1be1476a019fe753e6f/src/conference/conference-server.cc#L542C20-L542C30
