### ISSUE TITLE
In PCMA or PCMU, when no sound or voice comes from receiver end for 30s call drops

### ISSUE THREAD

**Issue by kalindus89** [BelledonneCommunications/linphone-android#1824]
Hi..

In Linphone-Android 4.2 java 

In PCMA or PCMU, Call drops in 30s, only when no sound or voice comes from the receiver end for 30s. Please kindly give us a solution :)

Thanks

**Comment by Viish** [comment]
Hi,

The behavior you describe is called "no rtp timeout" and it isn't related to the audio codec.
It's simply that after a given time (by default 30 secs) without having received any audio packet the call is considered broken and is automatically terminated.
You can change it's value using https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Core.html#setNortpTimeout-int- and you can even disable it using 0 value.

Cheers,

**Comment by kalindus89** [comment]
Thanks @Viish now working :)
