### ISSUE TITLE
Video Blur and Stuck

### ISSUE THREAD

**Issue by August1023** [BelledonneCommunications/linphone-android#1826]
Hi,I have some questions to ask you.
Is video blurring related to resolution? The set video resolution is 720 * 1280.
Is video blur related to "core. setStaticPictureFps()"? What are the default and recommended values for "core. setStaticPictureFps(720)"?
Is video stuck related to "core. setPreferredFramerate (60)"?

**Comment by Viish** [comment]
Hi,

What do you mean by "video blurring"? 
Can you take a screenshot of such effect?

**Comment by August1023** [comment]
@Viish 
<img width="243" alt="35489ac3de6ae58df7da48ef1c8e77b" src="https://user-images.githubusercontent.com/45287355/211231700-a80f5dab-7e7d-457a-b6df-33dbea3b78f9.png">

**Comment by August1023** [comment]
How to switch encoder and decoder? How to keep the set frame rate unchanged?
