### ISSUE TITLE
question some ringtones 

### ISSUE THREAD

**Issue by James-lyb** [BelledonneCommunications/linphone-android#1830]
Hi,
Terminate the call will play ringtones， Sounds like "doo doo doo"
What can I do to modify it or stop it
this configurations is invalid:

--------------------------------------------------------
        core.setRing(null);
        core.setRingback(null);
        core.setRemoteRingbackTone(null);
        core.setPlayFile(null);
        core.setRemoteRingbackTone(null);
        core.setTone(ToneID.CallEnd, null);
        core.setTone(ToneID.Busy, null);
        core.setTone(ToneID.CallLost, null);
        core.setTone(ToneID.CallOnHold, null);
        core.setTone(ToneID.CallWaiting, null);
        core.setTone(ToneID.Undefined, null);
        core.setRingDuringIncomingEarlyMedia(false);
        core.setNativeRingingEnabled(false);

----------------------------------------------------------

SDK Version linphone-sdk-android-5.0.72-pre.3+92ad42d

Thanks!

**Comment by Viish** [comment]
Hi,
`core.setTone(ToneID.CallEnd, null)` should do the trick and disable the end of call tone.
Try to update to latest release (5.2.X), it might fix your issue.
Cheers,
