### ISSUE TITLE
4 Party Video conference on device without server

### ISSUE THREAD

**Issue by atharvasharma31** [BelledonneCommunications/linphone-android#1833]
Dear Team,

Is it possible to do 4 party video conference on local device without server.

**Comment by Viish** [comment]
Hi,
No, video conferencing is only available through a remote conference server.
For locally based conferences we limit to audio only.
Cheers,

**Comment by atharvasharma31** [comment]
Hi @Viish,

But you have one branch where the video conference is possible, where you share Video of Active speakers to the rest of the participants. ? 

Will that still works or not ?

Thanks

**Comment by Viish** [comment]
It works thanks to the conference server.
We may had a branch that used to do video conferencing locally but that branch probably won't anymore and we don't intend to pursue that path.

**Comment by keyur-n** [comment]
@Viish  What is difference between video conferencing locally & video conferencing server?

**Comment by keyur-n** [comment]
@Viish Can you please inform, what is difference between video conferencing locally & video conferencing server?

**Comment by Viish** [comment]
You can't do local video conferencing, only audio.
In local mode, one of the client acts like a server and does the merging of the streams. In server mode, there is a dedicated server for this task.
