### ISSUE TITLE
unsupported media codec

### ISSUE THREAD

**Issue by naddika** [BelledonneCommunications/linphone-android#1834]
I have 2 Android phones, both are of different vendors and relatively new.

When trying to make a call to a wire phone, a call will immediately end with an error "unsupported media codec"

I've turned off video in the settings, and encyption is turned off as well.  I've even turned off all the codes in Audio settings, but the error will persist.

**Comment by Viish** [comment]
Hi,

In the contrary to prevent that issue you should enable all audio codecs.
This error appears when no matching codec is found between each side enabled codecs list.

Cheers,
