### ISSUE TITLE
Hearing no sound during a SIP call

### ISSUE THREAD

**Issue by ramboman** [BelledonneCommunications/linphone-android#1836]
Hi

1. **Describe the bug**

- During a SIP call, I hear no sound.
- When I press the signal strength icon, the pop up shows that the the download rate is close to 0 kbits/s.
- It was not like that in version 5.0.0. It started when I installed version 5.0.2 and it is still a problem in the newest version to date (5.0.5) in either F-Droid and Playstore.
- For now, I am back to 5.0.0.

2. **To Reproduce**

- Make a SIP call to a phone number
- Hear if there is sound.
- Press on the signal strength icon on the top left.
- See if the download rate is normal (~35 kbits/s for gsm)

3. **Expected behavior**

- Hear sound.
- Download rate is normal (~35 kbits/s for gsm)

4. **Setups that I tried where the problem occurs**

 - VoIP provider: voip.ms
 - Device: Google Pixel 6a
   OS: GrapheneOS Android 13
   versions:
   - App: 5.0.2
     SDK: 5.2.9
     sources: F-Droid
 - Device: Teracube 2e
   OS: e/OS Android 11
   versions:
   - App: 5.0.2
     SDK: 5.2.9
     sources: F-Droid
   - App: 5.0.5
     SDK: 5.2.15
     sources: F-Droid
   - App: 5.0.5
     SDK: 5.2.15
     sources: Playstore

**Comment by Viish** [comment]
Hi,

Please attach logs showing the issue.

**Comment by ramboman** [comment]
Hello Viish,

Is there a place where I can send the logs in private?

**Comment by Viish** [comment]
By mail to me: sylvain.berfini@belledonne-communications.com

**Comment by ramboman** [comment]
Log sent to the email.

**Comment by Viish** [comment]
Can you send me the logs from the other side as well please?
And also the logs with 5.0.0 that shows a working call please?

**Comment by ramboman** [comment]
Log from the working setup sent.

**Comment by Viish** [comment]
Thanks.

F-Droid has enabled G729 lately (since 5.0.2) and that seems to be the cause of your issue (G729 has always been enabled for linphone on the Play Store). 
Try to disable it in the Audio sections of the parameters and check if it works better.
If it does, it means the remote end of your call says it supports it but in fact doesn't and doesn't send you audio.

Another difference between the working & not working call is that ICE is enabled for the non working call.
You can also try to disable it and see if that improves things or not.

Cheers,

**Comment by ramboman** [comment]
Turning off the G729 did the trick.

Thank you very much

**Comment by Sysnic73** [comment]
Hello.

I have nearly the identical setup and trouble as **ramboman**.  Howerver, when I disable the G729 codec and try to make a call I get an error message; "Incompatible media parameters".

I am still searching for a solution.  I have been testing by calling 613-745-1576, a Government of Canada talking clock.  There is no audio during the call.

Any help is appreciated.
