### ISSUE TITLE
If the user is offline, does he not receive the message?

### ISSUE THREAD

**Issue by tpov** [BelledonneCommunications/linphone-android#1838]
Do your SMS messages work via sdp protocol?

**Comment by Viish** [comment]
Messages are sent as SIP messages, so if user is not known by the REGISTRAR it will trigger a 404 not found.
If user is known but not reachable, it will be kept following the PROXY configuration and delivered later (when user REGISTER) if possible.
On sip.linphone.org a push will be sent  to wake the device up, so it will receive it in a manner of seconds, unless not connected to internet. In that case, the message is being kept in a database for a month.

**Comment by tpov** [comment]
Group call is not supported via sip?
