### ISSUE TITLE
Android 12, In a call, when we lock screen from app side,  our voice is not hear after 1 minute

### ISSUE THREAD

**Issue by kalindus89** [BelledonneCommunications/linphone-android#1840]
Hi..

In Linphone-Android 4.2 java

Issue only in Android 12.  When we lock the screen(Click the power button)  while on a call( from the Linphone app side), after a 1 minute our voice is not hear to other side.. but other side voice can hear. But When we turn on the screen then call is working as normal. 

Please kindly give us a solution :)

**Comment by Viish** [comment]
Hi,
4.2 version of linphone-android isn't supported anymore (it is very old...), so it is expected to not work on recent Android releases.
Cheers,
