### ISSUE TITLE
Build fails from master : Could not find any matches for org.linphone:linphone-sdk-android:5.2+

### ISSUE THREAD

**Issue by vhartikainen** [BelledonneCommunications/linphone-android#1843]
Cloning and doing a clean build fails:

1. **Describe the bug** (mandatory)

When building from master branch (or any other I tried out just in case), build fails with following. Potentially SDK missing from all the repos defined for the app when building?

* What went wrong:
```
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find any matches for org.linphone:linphone-sdk-android:5.2+ as no versions of org.linphone:linphone-sdk-android are available.
     Required by:
         project :app
```

2. **To Reproduce** (mandatory)

* git clone https://github.com/BelledonneCommunications/linphone-android.git
* cd linphone-android
* ./gradlew assembleDebug

5. **Expected behavior** (mandatory)

Expecting the build to pass without having a local SDK built.

6. **Please complete the following information** (mandatory)

 - Device: N/A
 - OS: N/A
 - Version of the App : 5.x / master branch
 - Version of the SDK : 5.2+
 - Where you did got it from: local build
 - N/A

7. **SDK logs** (mandatory)

N/A

**Comment by Viish** [comment]
Hi,

Friday we were victim of a cyber-attack that targeted some of our servers including the one hosting the maven repository.
We are still working on getting it available again, that's why you can't find pre-built SDK binaries at the time.

I'll update this ticket when it will back online.

**Comment by nickhuangcyh** [comment]
Hi @Viish 

I have the same issue, I am using SDK "org.linphone:linphone-sdk-android:4.4.+" and "org.linphone:linphone-sdk-android:5.1.48" versions for my two projects.
Now I can't build my project because the cache of linphone SDK repo of /.gradle has been cleared.
I hope it can be fixed ASAP, Wish you all the best!

Thanks!

**Comment by lioutoung** [comment]
Hi @Viish 
We also encountered the same issue. We have an urgent project stuck on this issue. If you need more time to fix the issue, can you help provide the SDK binary first. Thank you very much.

**Comment by vhartikainen** [comment]
@Viish Apparently also your internal docker registry got a hit, as can't pull the ready-made container image for building myself.

**Comment by Viish** [comment]
Docker registry was on the same server, that's why it's also unavailable...
You can find docker files here: https://github.com/BelledonneCommunications/linphone-sdk/tree/master/docker-files

**Comment by lioutoung** [comment]
Hi @Viish 
Sorry for bothering.
May we know the progress of the repair and when it will be back. Thanks.

**Comment by vhartikainen** [comment]
This helped me, hope it works for you: 
1. https://github.com/BelledonneCommunications/linphone-sdk/tree/master/docker-files
2. docker build -f bc-dev-android-r25 -t androidbuild .
3. Then from linphone-sdk root: docker run -it --volume=$PWD:/home/bc/linphone-sdk androidbuild bash 
4. mkdir build; cd build
5. cmake .. -DLINPHONESDK_PLATFORM=Android -DLINPHONESDK_ANDROID_ARCHS=arm64
6. make
7. In linphone-android project, gradle.properties, set: LinphoneSdkBuildDir=/Users/xxx/git/linphone-sdk/build/

That should do it. I know it's a few steps, but also good insurance to keep wheels rolling in the future as well :) 

**NOTE** On my M1 Mac with Apple Silicon, the docker build kept constantly failing. Didn't bother to investigate it further, but definitely in future an arm docker image would be the only way to go to build this locally. Now just launched an x86 cloud instance and built it there.

**Comment by Viish** [comment]
> May we know the progress of the repair and when it will be back.

We expect it to be back online today.
I'll update you when it will be available again.

**Comment by Viish** [comment]
download.linphone.org is now available again, you should be able to build your app using a pre-built artefact like before.
