### ISSUE TITLE
error build apk file

### ISSUE THREAD

**Issue by tpov** [BelledonneCommunications/linphone-android#1847]
Hi, I have built a new sdk and am trying to run an old linphone project on java on it, I raised the gredle version and I had an error
![image](https://user-images.githubusercontent.com/33009369/217282843-9fc18a64-c323-4f72-b166-63606b9d772b.png)

**Comment by Viish** [comment]
That error is due to your own project, neither our Android project not our SDK.
Sorry but I can't help you on that.
