### ISSUE TITLE
Android Linphone place call got Unknown error - Forbidden

### ISSUE THREAD

**Issue by itman85** [BelledonneCommunications/linphone-android#185]
I clone linphone-android and built successfully. I installed linphone android app and register sip account to my freeswitch server successfully. But when i place a call i got toast error message on my android phone : **"Unknown error - Forbidden"**. Then I downloaded linphone app for iOS version, I did the same on android app but it worked ok. I don't know what wrong with android linphone lib. 
Thanks!

**Comment by 111usman** [comment]
Sometimes i also have this problem. But it is random and it is old problem.
