### ISSUE TITLE
Whether there are plans to support rnnoise？

### ISSUE THREAD

**Issue by wmailn** [BelledonneCommunications/linphone-android#1850]
Hi：

I tried to use the built-in noise reduction function of webrtc in linphone (implemented by myself), but the effect is not very good. 

I plan to try to integrate rnnoise. I wonder if there is an official plan to support rnnoise or is there any convenient way to integrate rnnoise

Thank you for your reply

**Comment by Viish** [comment]
Hi,

No we have no plan to integrate it.

Cheers,
