### ISSUE TITLE
ERROR MediaCodecDecoder: waiting for key frame.

### ISSUE THREAD

**Issue by basncy** [BelledonneCommunications/linphone-android#1852]
Reproduce: Just start the video call on my android device(Snapdragon 870), the video stucks.

Some essiontial findings from the log:
ERROR MediaCodecDecoder: no buffer available for queuing this frame! Decoder is too slow.
ERROR MediaCodecDecoder: waiting for key frame.

Full logs: ${HIDDEN}/63e8f2191060c_795fbd1861d79bc49daf.gz

Is it caused by the old version of openh264? As v2.3.0 fixed the Decoder bug fix to correct the B-frame order in some cases.

**Comment by Viish** [comment]
It seems you are on an old version of linphone-desktop: `Linphone Desktop/4.4.6`
Can you try again using 5.0.10 release?

**Comment by basncy** [comment]
Here are the log pair of test:
Linphone-android ${HIDDEN}/63ea3bae626dc_e0f166b67fd204451f82.gz
Linphone-desktop ${HIDDEN}/63ea3cb657df9_e17f1b5080afd2b7bd4e.gz   (I reset ~/.local/share/linphone/codecs before this test)

BTW, linphone-android(v4.6.7) on Snapdragon 660, with linphone-android(v5.0.5) on K40s do video calls, works.

**Comment by basncy** [comment]
Just correct the case, linphone-android(v4.6.7) on Snapdragon 660, with linphone-android(v5.0.5) on K40s still goes wrong.[https://i.imgur.com/Q0pHGnI.png](url)

**Comment by Viish** [comment]
Given your screen capture I wonder why the Audio (that works) is communicating using IPv6 and video (that doesn't work) is using IPv4.
Maybe that's the reason video packets aren't being received: network issue.

**Comment by basncy** [comment]
It's not a network issue(same network environment works on another device). The picture shows ipv6 on voice and ipv4 on video as one client enabled ICE, and another disabled, while flexisip servers for dual-stack.

I also tried both set ICE enabled with ipv6 direct connect and both ipv4 only with flexisip relay(ICE disabled), the fps on the sender side, the k40s, shows a very low number too. This situation happens too on calling with linphone-desktop windows 10.

I am not convenient to debug with the problem phone but I will try later.

The next cases might be: 
1. ICE enabled for ipv6 direct connection, linphone-android 5.0.5 on both sides.
2. Do video calling with another sip client on the problem device.

**Comment by basncy** [comment]
Hi, viish, new test cases logs and screen capture are packaged here  http://www.linuxe.org:8880/send/issues-1852.tar.gz please download them soon, thank you.

**Comment by Viish** [comment]
I see from your new test cases that you have the issue between two linphone clients using your SIP server.
Here's what you can do:
- Test using another network
- Test by disabling IPv6 support in network settings
- Test using sip.linphone.org accounts on both linphone-android

**Comment by basncy** [comment]
env: ice enabled, ipv4 only.
case 1: android call android, works as expected.
case 2: android call desktop, ERROR OpenH264 decoder: DecodeFrame2 failed.

screen capture and logs: http://www.linuxe.org:8880/send/issues-1852-2.tar.gz

ERROR OpenH264 decoder: DecodeFrame2 failed: 0x20
ERROR OpenH264 decoder: DecodeFrame2 failed: 0x4

**Comment by Viish** [comment]
Ok, two questions:
- Do you have the same issue if you lower the video quality of both sides to 1080p?
- Do you have the same issue with another Android device and the same desktop device?

**Comment by basncy** [comment]
> Ok, two questions:
> 
> * Do you have the same issue if you lower the video quality of both sides to 1080p?

yes, set to VGA with fps 15 can also reproduce.

> * Do you have the same issue with another Android device and the same desktop device?

No. Samsung Galaxy and this same desktop device works well. And must be reproduced between K40S and linphone-desktop(both windows and linux version).

Let me declare the timeline.
First I bought a new i5 1240p computer installed manjaro, got the video enable problem here https://github.com/BelledonneCommunications/linphone-desktop/issues/729 , then I fix it by upgrading the openh264 version.
Then weeks later I met sip.linphone.org ipv6 udp connectivity problem. https://github.com/BelledonneCommunications/linphone-android/issues/1841 but it seems works now.
Then weeks later again, My friend bought a new K40S installed linphone-android, then error happened as this issue described.

More info:

1. the error is still reproduced in this case today.   env: ice enabled, ipv4 only. case 1: android call android, works as expected.
I saw the video sender(on K40S) fps is less than 5, and sometimes 0.
2. K40S do video call to echo@asterisk-server, error reproduced.

So:
1. I guess the problem was introduced from MediaCodec En/Decoder on K40S.
2. Is this similar to https://github.com/BelledonneCommunications/linphone-android/issues/1665#issuecomment-1449776349 ? I haven't try 5.0.7 yet as all my case use 5.0.5.

**Comment by Viish** [comment]
Then indeed it is likely the K40S is to blame.

Check if there isn't a firmware update available for it that may fix that. Otherwise try using another codec such as H265 or VP8.

**Comment by basncy** [comment]
H265 not work, while vp8 works, but the fps is lower than expected, it's about 10, but acceptable as a backup solution.

BTW, is it possible to ajust the codec priority? vp8 is the highest priority by default, while I want to use h264 if both peers works well.
case 1: vp8, h264,h265 <----> vp8,h264,h265: the negotiate result is vp8(but I want to use h264, or h265 if both peers support)
case 2: vp8 <---> vp8,h264,h265: the result is vp8, which is this fallback solution(for those who doesn't support H26x well).

My proposal is to configure the priority on flexisip, if some peer doesn't support one of the codec, just disable it in the client settings. e.g. flexisip h265->h264->vp8
h264,h265 <----->vp8,h264,h265: using h265
vp8,h264,h265 <----->vp8,h264: using h264
vp8 <----->vp8,h264,h265: using vp8
vp8 <--->h264,h265: failed on video call, due to no common codec

**Comment by basncy** [comment]
Hi,

So I put samsung A9 Star, K40s, flexisip into the same LAN, making video call with H264 to reproduce this issue, here is the logs for your reference.

https://www.linphone.org:444//tmp/649abea7912be_6b773a7a6af4a35d911c.gz

https://www.linphone.org:444//tmp/649abeadda4f5_c0a5dfecb05ab768e0b9.gz

**Comment by basncy** [comment]
> Then indeed it is likely the K40S is to blame.
> 
> Check if there isn't a firmware update available for it that may fix that. Otherwise try using another codec such as H265 or VP8.

VP8 encode NOT supported on recent intel iGPU, vainfo command output "VAProfileVP8Version0_3: VAEntrypointVLD" only, so the other side can't see the video if call on Linux desktop.
VP9 hw-encode and hw-decode are supported but linphone is not supported.

So how can I and how to enable sw-encode/decode for H264 on linphone-android for compatibility?
