### ISSUE TITLE
Echo issue happening on speaker

### ISSUE THREAD

**Issue by abhay222** [BelledonneCommunications/linphone-android#1853]
Hi, Echo issue on Oneplus device on Speaker. we are using linphone SDK v5.2.18.

Echo starts when put on Speaker mode. 
Hardware Echo canceler is not working some crash happens as soon as the call starts. 
See line number 2492 in attached logs file

 - Device: [Oneplus 10 pro (NE2211)]
 - OS: [Android 13]
 
Echo issue also happens on Linphone App on playstore v5.0.5

https://drive.google.com/file/d/1rR5N7D28g--7x0gDI0WHG_DXLnxm1F5U/view?usp=sharing

**Comment by Viish** [comment]
Hi @abhay222,

If I'm not mistaken your com.superfone app is using our SDK but doesn't respect GPLv3 license as I don't see the source code anywhere, not even a mention to linphone, either in your app or your website...

Either respect the open-source license or purchase a proprietary one from our company (includes support), but in the meantime don't expect me to help you.

**Comment by abhay222** [comment]
@Viish Will add in upcoming build

**Comment by Viish** [comment]
Given that you are using our SDK for more than a year (you opened your first issue here on December 17th) it would be time...
