### ISSUE TITLE
Unable to open linphone database

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1854]
Hi Viish,

The APK of the device cannot be up. The following information is displayed. Only after the APK is removed and installed can it return to normal, What is the problem.

6 22662-22662/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-15 14:23:18.606 22662-22662/? A/DEBUG: Build fingerprint: 'gemvary/tulip_p2/tulip-p2:6.0.1/MOB30J/20210630:user/test-keys'
02-15 14:23:18.606 22662-22662/? A/DEBUG: Revision: '0'
02-15 14:23:18.606 22662-22662/? A/DEBUG: ABI: 'arm64'
02-15 14:23:18.607 22662-22662/? A/DEBUG: pid: 28565, tid: 28565, name: gemvary.manager  >>> com.gemvary.manager <<<
02-15 14:23:18.607 22662-22662/? A/DEBUG: signal 6 (SIGABRT), code 0 (SI_USER), fault addr --------
02-15 14:23:18.647 22662-22662/? A/DEBUG: Abort message: 'Unable to open linphone database.'
02-15 14:23:18.647 22662-22662/? A/DEBUG:     x0   0000000000000000  x1   0000000000006f95  x2   0000000000000006  x3   0000000000000000
02-15 14:23:18.647 22662-22662/? A/DEBUG:     x4   0000000000000000  x5   0000000000000001  x6   0000000000000000  x7   0000000000000000
02-15 14:23:18.648 22662-22662/? A/DEBUG:     x8   0000000000000083  x9   0000000000000004  x10  0000007fd4c16af0  x11  0000007fd4c16b78
02-15 14:23:18.648 22662-22662/? A/DEBUG:     x12  0000007f8c2a3000  x13  0000007faaf9d000  x14  0000000000000000  x15  0000007faaf8f000
02-15 14:23:18.648 22662-22662/? A/DEBUG:     x16  0000007faaf8f568  x17  0000007faaf2213c  x18  0000007faafa0f50  x19  0000007fab3930a8
02-15 14:23:18.648 22662-22662/? A/DEBUG:     x20  0000007fab392fe8  x21  0000000000000002  x22  0000000000000006  x23  0000000000000000
02-15 14:23:18.648 22662-22662/? A/DEBUG:     x24  0000007f8a844ba0  x25  0000000000000000  x26  000000001330d580  x27  0000000000000000
02-15 14:23:18.648 22662-22662/? A/DEBUG:     x28  0000000070aa4538  x29  0000007fd4c16b90  x30  0000007faaf1f8d8
02-15 14:23:18.648 22662-22662/? A/DEBUG:     sp   0000007fd4c16b90  pc   0000007faaf22144  pstate 0000000020000000
02-15 14:23:18.663 22662-22662/? A/DEBUG: backtrace:
02-15 14:23:18.663 22662-22662/? A/DEBUG:     #00 pc 000000000006a144  /system/lib64/libc.so (tgkill+8)
02-15 14:23:18.663 22662-22662/? A/DEBUG:     #01 pc 00000000000678d4  /system/lib64/libc.so (pthread_kill+68)
02-15 14:23:18.663 22662-22662/? A/DEBUG:     #02 pc 0000000000023838  /system/lib64/libc.so (raise+28)
02-15 14:23:18.663 22662-22662/? A/DEBUG:     #03 pc 000000000001dfd8  /system/lib64/libc.so (abort+60)
02-15 14:23:18.663 22662-22662/? A/DEBUG:     #04 pc 000000000001d8dc  /data/app/com.gemvary.manager-2/lib/arm64/libbctoolbox.so (bctbx_logv+488)
02-15 14:23:18.663 22662-22662/? A/DEBUG:     #05 pc 00000000007d0954  /data/app/com.gemvary.manager-2/lib/arm64/liblinphone.so
02-15 14:23:18.663 22662-22662/? A/DEBUG:     #06 pc 00000000007d06c0  /data/app/com.gemvary.manager-2/lib/arm64/liblinphone.so (_ZN15LinphonePrivate6LoggerD2Ev+176)
02-15 14:23:18.663 22662-22662/? A/DEBUG:     #07 pc 00000000007a8f20  /data/app/com.gemvary.manager-2/lib/arm64/liblinphone.so (_ZN15LinphonePrivate11CorePrivate4initEv+1292)
02-15 14:23:18.663 22662-22662/? A/DEBUG:     #08 pc 0000000000867860  /data/app/com.gemvary.manager-2/lib/arm64/liblinphone.so (linphone_configuring_terminated+168)
02-15 14:23:18.664 22662-22662/? A/DEBUG:     #09 pc 0000000000869348  /data/app/com.gemvary.manager-2/lib/arm64/liblinphone.so (linphone_core_start+480)
02-15 14:23:18.664 22662-22662/? A/DEBUG:     #10 pc 00000000036c0394  /data/app/com.gemvary.manager-2/oat/arm64/base.odex (offset 0x1c18000)
02-15 14:23:19.779 22662-22662/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_01

Thanks,
Best Regards.

**Comment by Viish** [comment]
Hi,

That means either your DB hasn't been installed/created properly or it has been corrupted.
It may also be that the configured path to the DB isn't the right one.

As it is your own app I can't help much more about that.

**Comment by fengqz627** [comment]
where is linphone database?

**Comment by Viish** [comment]
linphone.db file is located at the root of the app directory on the device.
