### ISSUE TITLE
AAudio Error on any click interaction 

### ISSUE THREAD

**Issue by disolaterX** [BelledonneCommunications/linphone-android#1855]
Hi @Viish 👋 ,

On any UI click action Linphone & AAudio send this error is this expected behaviour ?

10:45:11.580  9250-18482 AAudioStream     D  setState(s#106) from 4 to 13
10:45:11.580  9250-18482 Hello Linphone   E  [AAudio Player] aaudio_player_callback_error has result: -899 / AAUDIO_ERROR_DISCONNECTED
10:45:11.587  9250-16420 Hello Linphone   W  [AAudio Player] Player stream has disconnected
10:45:11.587  9250-16420 Hello Linphone   I  [AAudio Player] Closing player stream, current state is 13
10:45:11.587  9250-16420 AAudio           D  AAudioStream_close(s#106) called ---------------
10:45:11.587  9250-16420 AAudioStream     D  setState(s#106) from 13 to 11
10:45:11.588  9250-16420 AAudioStream     D  setState(s#106) from 11 to 12
10:45:11.588  9250-16420 AAudioStream     D  ~AudioStream(s#106) mPlayerBase strongCount = 2
10:45:11.588  9250-16420 AAudio           D  AAudioStream_close(s#106) returned 0 ---------
10:45:11.588  9250-16420 Hello Linphone   I  [AAudio Player] Player stream closed
10:45:11.607  9250-16420 Hello Linphone   I  [AAudio Player] Using COMMUNICATION mode
10:45:11.607  9250-16420 Hello Linphone   I  [AAudio Player] Using device ID: AAudio Speaker: ONEPLUS A5010 (3)
10:45:11.607  9250-16420 Hello Linphone   I  [AAudio Player] Player stream configured with samplerate 48000 and 1 channels
10:45:11.607  9250-16420 AAudio           I  AAudioStreamBuilder_openStream() called ----------------------------------------
10:45:11.615  9250-16420 AAudioStream     D  setState(s#107) from 0 to 2
10:45:11.616  9250-16420 AAudio           I  AAudioStreamBuilder_openStream() returns 0 = AAUDIO_OK for s#107 ----------------
10:45:11.617  9250-16420 Hello Linphone   I  [AAudio Player] Player stream opened
10:45:11.617  9250-16420 Hello Linphone   I  [AAudio Player] Expected content type 1, got 1
10:45:11.617  9250-16420 Hello Linphone   I  [AAudio Player] Expected usage 2, got 2
10:45:11.617  9250-16420 AAudio           D  AAudioStream_requestStart(s#107) called --------------
10:45:11.617  9250-16420 AAudioStream     D  setState(s#107) from 2 to 3
10:45:11.666  9250-16420 AAudio           D  AAudioStream_requestStart(s#107) returned 0 ---------
10:45:11.667  9250-16420 Hello Linphone   I  [AAudio Player] Player stream started
10:45:11.685  9250-18631 AAudioStream     D  setState(s#107) from 3 to 13
10:45:11.685  9250-18631 Hello Linphone   E  [AAudio Player] aaudio_player_callback_error has result: -899 / AAUDIO_ERROR_DISCONNECTED
10:45:11.687  9250-16420 Hello Linphone   W  [AAudio Player] Player stream has disconnected
10:45:11.687  9250-16420 Hello Linphone   I  [AAudio Player] Closing player stream, current state is 13
10:45:11.687  9250-16420 AAudio           D  AAudioStream_close(s#107) called ---------------
10:45:11.687  9250-16420 AAudioStream     D  setState(s#107) from 13 to 11
10:45:11.688  9250-16420 AAudioStream     D  setState(s#107) from 11 to 12
10:45:11.688  9250-16420 AAudioStream     D  ~AudioStream(s#107) mPlayerBase strongCount = 2
10:45:11.688  9250-16420 AAudio           D  AAudioStream_close(s#107) returned 0 ---------
10:45:11.689  9250-16420 Hello Linphone   I  [AAudio Player] Player stream closed
10:45:11.707  9250-16420 Hello Linphone   I  [AAudio Player] Using COMMUNICATION mode
10:45:11.707  9250-16420 Hello Linphone   I  [AAudio Player] Using device ID: AAudio Speaker: ONEPLUS A5010 (3)
10:45:11.707  9250-16420 Hello Linphone   I  [AAudio Player] Player stream configured with samplerate 48000 and 1 channels
10:45:11.707  9250-16420 AAudio           I  AAudioStreamBuilder_openStream() called ----------------------------------------
10:45:11.714  9250-16420 AAudioStream     D  setState(s#108) from 0 to 2
10:45:11.716  9250-16420 AAudio           I  AAudioStreamBuilder_openStream() returns 0 = AAUDIO_OK for s#108 ----------------
10:45:11.716  9250-16420 Hello Linphone   I  [AAudio Player] Player stream opened
10:45:11.716  9250-16420 Hello Linphone   I  [AAudio Player] Expected content type 1, got 1
10:45:11.716  9250-16420 Hello Linphone   I  [AAudio Player] Expected usage 2, got 2
10:45:11.716  9250-16420 AAudio           D  AAudioStream_requestStart(s#108) called --------------
10:45:11.716  9250-16420 AAudioStream     D  setState(s#108) from 2 to 3
10:45:11.755  9250-16420 AAudio           D  AAudioStream_requestStart(s#108) returned 0 ---------
10:45:11.755  9250-16420 Hello Linphone   I  [AAudio Player] Player stream started
10:45:11.757  9250-18633 AAudioStream     D  setState(s#108) from 3 to 13
10:45:11.757  9250-18633 Hello Linphone   E  [AAudio Player] aaudio_player_callback_error has result: -899 / AAUDIO_ERROR_DISCONNECTED
10:45:11.765  9250-16420 Hello Linphone   W  [AAudio Player] Player stream has disconnected
10:45:11.765  9250-16420 Hello Linphone   I  [AAudio Player] Closing player stream, current state is 13
10:45:11.765  9250-16420 AAudio           D  AAudioStream_close(s#108) called ---------------
10:45:11.765  9250-16420 AAudioStream     D  setState(s#108) from 13 to 11
10:45:11.766  9250-16420 AAudioStream     D  setState(s#108) from 11 to 12
10:45:11.766  9250-16420 AAudioStream     D  ~AudioStream(s#108) mPlayerBase strongCount = 2
10:45:11.766  9250-16420 AAudio           D  AAudioStream_close(s#108) returned 0 ---------
10:45:11.766  9250-16420 Hello Linphone   I  [AAudio Player] Player stream closed
10:45:11.767  9250-16420 Hello Linphone   I  [AAudio Player] Using COMMUNICATION mode
10:45:11.767  9250-16420 Hello Linphone   I  [AAudio Player] Using device ID: AAudio Speaker: ONEPLUS A5010 (3)
10:45:11.767  9250-16420 Hello Linphone   I  [AAudio Player] Player stream configured with samplerate 48000 and 1 channels
10:45:11.767  9250-16420 AAudio           I  AAudioStreamBuilder_openStream() called ----------------------------------------
10:45:12.047  9250-16420 AAudioStream     D  setState(s#109) from 0 to 2
10:45:12.048  9250-16420 AAudio           I  AAudioStreamBuilder_openStream() returns 0 = AAUDIO_OK for s#109 ----------------
10:45:12.048  9250-16420 Hello Linphone   I  [AAudio Player] Player stream opened
10:45:12.048  9250-16420 Hello Linphone   I  [AAudio Player] Expected content type 1, got 1
10:45:12.048  9250-16420 Hello Linphone   I  [AAudio Player] Expected usage 2, got 2
10:45:12.049  9250-16420 AAudio           D  AAudioStream_requestStart(s#109) called --------------
10:45:12.049  9250-16420 AAudioStream     D  setState(s#109) from 2 to 3
10:45:12.518  9250-16420 AAudio           D  AAudioStream_requestStart(s#109) returned 0 ---------
10:45:12.518  9250-16420 Hello Linphone   I  [AAudio Player] Player stream started
10:45:12.541  9250-18634 AAudioStream     D  setState(s#109) from 3 to 13
10:45:12.541  9250-18634 Hello Linphone   E  [AAudio Player] aaudio_player_callback_error has result: -899 / AAUDIO_ERROR_DISCONNECTED
10:45:12.582  9250-16420 Hello Linphone   W  [AAudio Player] Player stream has disconnected
10:45:12.582  9250-16420 Hello Linphone   I  [AAudio Player] Closing player stream, current state is 13
10:45:12.582  9250-16420 AAudio           D  AAudioStream_close(s#109) called ---------------
10:45:12.582  9250-16420 AAudioStream     D  setState(s#109) from 13 to 11
10:45:12.583  9250-16420 AAudioStream     D  setState(s#109) from 11 to 12
10:45:12.583  9250-16420 AAudioStream     D  ~AudioStream(s#109) mPlayerBase strongCount = 2
10:45:12.583  9250-16420 AAudio           D  AAudioStream_close(s#109) returned 0 ---------
10:45:12.583  9250-16420 Hello Linphone   I  [AAudio Player] Player stream closed
10:45:12.584  9250-16420 Hello Linphone   I  [AAudio Player] Using COMMUNICATION mode
10:45:12.584  9250-16420 Hello Linphone   I  [AAudio Player] Using device ID: AAudio Speaker: ONEPLUS A5010 (3)
10:45:12.584  9250-16420 Hello Linphone   I  [AAudio Player] Player stream configured with samplerate 48000 and 1 channels
10:45:12.584  9250-16420 AAudio           I  AAudioStreamBuilder_openStream() called ----------------------------------------
10:45:12.591  9250-16420 AAudioStream     D  setState(s#110) from 0 to 2
10:45:12.592  9250-16420 AAudio           I  AAudioStreamBuilder_openStream() returns 0 = AAUDIO_OK for s#110 ----------------
10:45:12.592  9250-16420 Hello Linphone   I  [AAudio Player] Player stream opened
10:45:12.592  9250-16420 Hello Linphone   I  [AAudio Player] Expected content type 1, got 1
10:45:12.592  9250-16420 Hello Linphone   I  [AAudio Player] Expected usage 2, got 2
10:45:12.592  9250-16420 AAudio           D  AAudioStream_requestStart(s#110) called --------------
10:45:12.592  9250-16420 AAudioStream     D  setState(s#110) from 2 to 3
10:45:12.600  9250-16420 AAudio           D  AAudioStream_requestStart(s#110) returned 0 ---------
10:45:12.600  9250-16420 Hello Linphone   I  [AAudio Player] Player stream started
10:45:12.609  9250-16420 Hello Linphone   W  Flow controlled bufferizer owned by [MSAAudioPlayer] of max 40 ms is filled with 1120 ms at the end of the 5000 ms interval, asking to drop 540 ms
10:45:12.621  9250-18640 AAudioStream     D  setState(s#110) from 3 to 4
10:45:15.127  9250-16420 Hello Linphone   I  [AAudio Recorder] sound/wall clock skew is average=5934.36 ms
10:45:17.878  9250-16420 Hello Linphone   W  Flow controlled bufferizer owned by [MSAAudioPlayer] of max 40 ms was filled with at least 320 ms in the last 5000 ms, need to drop 280 ms

**Comment by Viish** [comment]
Hi,

If your device restarts the audio streams each time you touch the screen it has a serious firmware issue...
Or you're doing something in your app that causes AAudio to loose the connection with the audio player, for example playing a sound?

Do you have the same issue on this device with linphone-android?

**Comment by disolaterX** [comment]
Checking this with linphone build

**Comment by Viish** [comment]
Any update?

**Comment by disolaterX** [comment]
Not able to reproduce this again tried this multiple time
