### ISSUE TITLE
Why are these messages repeated?

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1856]
Hi Viish,

02-16 15:11:12.617  4099  4099 I tag_linphone: Start transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.621  4099  4099 I tag_linphone: Commit transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.632  4099  4099 I tag_linphone: Start transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.636  4099  4099 I tag_linphone: Rollback transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.636  4099  4099 I tag_linphone: Start transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.641  4099  4099 I tag_linphone: Commit transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.655  4099  4099 I tag_linphone: Start transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.660  4099  4099 I tag_linphone: Rollback transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.660  4099  4099 I tag_linphone: Start transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.665  4099  4099 I tag_linphone: Commit transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.677  4099  4099 I tag_linphone: Start transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.682  4099  4099 I tag_linphone: Rollback transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.682  4099  4099 I tag_linphone: Start transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.686  4099  4099 I tag_linphone: Commit transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.701  4099  4099 I tag_linphone: Start transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.706  4099  4099 I tag_linphone: Rollback transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.706  4099  4099 I tag_linphone: Start transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.711  4099  4099 I tag_linphone: Commit transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.725  4099  4099 I tag_linphone: Start transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.729  4099  4099 I tag_linphone: Rollback transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.730  4099  4099 I tag_linphone: Start transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.734  4099  4099 I tag_linphone: Commit transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.745  4099  4099 I tag_linphone: Start transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.749  4099  4099 I tag_linphone: Rollback transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.750  4099  4099 I tag_linphone: Start transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.754  4099  4099 I tag_linphone: Commit transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.768  4099  4099 I tag_linphone: Start transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.772  4099  4099 I tag_linphone: Rollback transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.772  4099  4099 I tag_linphone: Start transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.777  4099  4099 I tag_linphone: Commit transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.789  4099  4099 I tag_linphone: Start transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.793  4099  4099 I tag_linphone: Rollback transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.793  4099  4099 I tag_linphone: Start transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.798  4099  4099 I tag_linphone: Commit transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.810  4099  4099 I tag_linphone: Start transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.814  4099  4099 I tag_linphone: Rollback transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.814  4099  4099 I tag_linphone: Start transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.819  4099  4099 I tag_linphone: Commit transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.832  4099  4099 I tag_linphone: Start transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.836  4099  4099 I tag_linphone: Rollback transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.836  4099  4099 I tag_linphone: Start transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.841  4099  4099 I tag_linphone: Commit transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.854  4099  4099 I tag_linphone: Start transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.858  4099  4099 I tag_linphone: Rollback transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.859  4099  4099 I tag_linphone: Start transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.863  4099  4099 I tag_linphone: Commit transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.878  4099  4099 I tag_linphone: Start transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.883  4099  4099 I tag_linphone: Rollback transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.883  4099  4099 I tag_linphone: Start transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.887  4099  4099 I tag_linphone: Commit transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.900  4099  4099 I tag_linphone: Start transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.904  4099  4099 I tag_linphone: Rollback transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.905  4099  4099 I tag_linphone: Start transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.909  4099  4099 I tag_linphone: Commit transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.922  4099  4099 I tag_linphone: Start transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.927  4099  4099 I tag_linphone: Rollback transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.927  4099  4099 I tag_linphone: Start transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.931  4099  4099 I tag_linphone: Commit transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.942  4099  4099 I tag_linphone: Start transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.947  4099  4099 I tag_linphone: Rollback transaction 0xbe815a28 in MainDb::getEventFromKey.
02-16 15:11:12.947  4099  4099 I tag_linphone: Start transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:12.951  4099  4099 I tag_linphone: Commit transaction 0xbe815a2c in MainDb::updateEvent.
02-16 15:11:13.005  4099  4099 I tag_linphone: channel [0x8c3034c0]: ending recv background task with id=[200a2e].
02-16 15:11:13.006  4099  4099 I tag_linphone: bellesip_wake_lock_release(): Android wake lock released [ref=0x200a2e]
02-16 15:11:13.006  4099  4099 I tag_linphone: channel [0x8c3034c0]: keep alive sent to [UDP://10.0.1.201:5060]

Why are these messages repeated?

Thanks,
Best Regards.

**Comment by Viish** [comment]
That seems related to https://github.com/BelledonneCommunications/linphone-android/issues/1854, as these logs indicates the SDK tries to do a change in DB but fails, so it rollbacks to the previous version before the transaction.
