### ISSUE TITLE
How to mute conference call's mic in linphone android java?

### ISSUE THREAD

**Issue by Mahee2027** [BelledonneCommunications/linphone-android#1858]
Hi,
we can disable mic for a single call using 'core.getCurrentCall().setMicrophoneMuted(true)".
But how can we toggle the mic when there is a conference call?

I'm using java for developing my app.

can you help me with this ?

Thanks in advance
Mahee

**Comment by Viish** [comment]
Hi,

A Conference has a Call, so you can use the same code as for single calls.
See https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Conference.html#getCall--

Cheers,

**Comment by Mahee2027** [comment]
Hi,

'mCore.get conference.get call()' always returns null during local
conference

Thanks
Mahee

**Comment by Viish** [comment]
Indeed local conferences are a bit special.

You can try to disable the mic completely at Core level: https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Core.html#setMicEnabled-boolean-

**Comment by Mahee2027** [comment]
Hi,
Yes that's what i'm doing,
Will this stop the Audio stream as well like 'call.setMicrophoneMuted' or
just disable the mic only

Thanks
Mahee
