### ISSUE TITLE
Call Stats Info

### ISSUE THREAD

**Issue by disolaterX** [BelledonneCommunications/linphone-android#1859]
Hey Team,

getReceiverLossRate()
getSenderLossRate​()

what is actually meaning or definition as the doc is confusing.

Does getReceiverLossRate means the loss of packet (in perc) at PBX while receiving the rtp

and

Does getSenderLossRate means the loss of packet (in perc) at linphone while receiving the rtp

Please help here would be greatest help
Thanks

**Comment by disolaterX** [comment]
and more is what is 

getLocalLossRate​()

**Comment by Viish** [comment]
`getReceiverLossRate()` is the remote end of the call percentage of lost packets, according to it.
`getSenderLossRate()` is the information you send to the remote end about your own percentage of lost packets.
 `getLocalLossRate()` is your own percentage of packets loss over the last second.
