### ISSUE TITLE
server is not updating state updatedByRemote

### ISSUE THREAD

**Issue by Mahee2027** [BelledonneCommunications/linphone-android#1860]
Hi,

I have a problem with video call invitations. when i am using linphone server 'sip.linphone.org'
Updating for video invites, it's working fine.
But it doesn't work properly when I'm using my FusionPbx.

video works fine if i turn on video on both sides but it doesn't send invite to remote.

Any Idea what setting should I do in my PBX ?

Thanks 
Mahee

**Comment by Viish** [comment]
Hi,

Please attach logs showing the issue with your FusionPBX proxy server.
