### ISSUE TITLE
Domain default value

### ISSUE THREAD

**Issue by exasys** [BelledonneCommunications/linphone-android#1861]
Hello 
How can I add the domain ( 10.0.0.50 ) as a fixed value and prevent users from writing in the domain field?
i tried to change 
android:text="@={viewModel.domain}" 
to
android:text="10.0.0.50"
at assistant_generic_account_login_fragment.xml
but login button still not activated

**Comment by Viish** [comment]
Hi,

It's clearly not the right way to do this "programmatically speaking" but if you want a quick fix here's how to do it:
```
android:text="@={`10.0.0.50`}"
```

Cheers,
