### ISSUE TITLE
Call is going on hold when we play audio or video

### ISSUE THREAD

**Issue by parthtrivedi287** [BelledonneCommunications/linphone-android#1863]
hello,
We are facing one issue of call hold during following case in your older version of the sdk it was working fine.

Call is running -> we are minimising android app -> Opening other app in this case we are opening YouTube app and playing video as soon as video is getting started our call is going on hold where as in earlier version of linphone-sdk call was not going on hold but it was getting remains as it is ongoing and along side we were able to play video and audio.

**Comment by Viish** [comment]
Hi @parthtrivedi287 ,

You'll find your answer on this wiki page: https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Getting%20started/Android/#HAudiofocus
