### ISSUE TITLE
No Early Media on Mobile network, Linhome does work

### ISSUE THREAD

**Issue by pergolafabio** [BelledonneCommunications/linphone-android#1864]
First of all, please say "Hi" or "Hello", it doesn't cost much.

1. **Describe the bug** (mandatory)

Hi, i have setup Linphone (Android Play Store) connected to my Asterisk (extension 6002)
When i'm local, all is working fine, also early video, when i'm connected to Mobile network, i can see also video, but not in Early Media... If i setup the same 6002 account with Linhome, all is working... So there must be a settint/issue on linphone, but what?

I have enabled show early media in linphone setting, otherwise it would work also when connected to local wifi network, below are logs....

2. **Please complete the following information** (mandatory)

 - Device: Onplus 6T
 - OS: Android 10
 - Version of the App: 5.0.5 (playstore)

3. **SDK logs** (mandatory)

[no early media.txt](https://github.com/BelledonneCommunications/linphone-android/files/10825473/no.early.media.txt)

**Comment by pergolafabio** [comment]
i also see this looks the same, but that patch is already merged?
https://github.com/BelledonneCommunications/linphone-android/issues/1668

**Comment by Viish** [comment]
Hi,
It seems to be a network issue as you don't receive any video packets.
In the logs there are multiple info about STUN, can you check your stun server? You can always use ours (stun.linphone.org) or you may want to try to disable it.
Cheers,

**Comment by pergolafabio** [comment]
Hi, thnx for feedback, i tried the linphone stun, or completely removing it from asterisk and linphone app, but still the same
when  6002 is connected to wifi (same lan as asterisk and 6002) early media works fine
when 6002 is connected to cellular, then only video after i answer the call

some new logs with stuf disabled in asterisk AND linphone on 6002, maybe you can compare?

[wifi.txt](https://github.com/BelledonneCommunications/linphone-android/files/10837919/wifi.txt)

[public.txt](https://github.com/BelledonneCommunications/linphone-android/files/10837921/public.txt)

**Comment by Viish** [comment]
Nothing jumps to my eyes.
Try to turn on ICE as it simply may be a network issue due to your cellular provider restriction.
Also you should check the other devices logs to see where it tries to send the video packets to, and make sure the destination is OK.

**Comment by pergolafabio** [comment]
ok, will do that
but if i setup 6002 with Linhome app, then everything works as expected, its only when i setup 6002 with linphone app
So that means on Asterisk / cellular side everything should be ok ?

**Comment by Viish** [comment]
Can you attach linhome logs on cellular network showing a working early media video call?

**Comment by pergolafabio** [comment]
sure, here you go...

[linhome.txt](https://github.com/BelledonneCommunications/linphone-android/files/10838997/linhome.txt)

**Comment by Viish** [comment]
When you use linhome, it seems you use a sip.linhome.org account.
But when you use linphone, you don't use a sip.linphone.org nor a sip.linhome.org account, right?

**Comment by pergolafabio** [comment]
No, i use 6002 with linhome, lemme check again maybe uploaded wrong debug file

**Comment by pergolafabio** [comment]
[linhome2.txt](https://github.com/BelledonneCommunications/linphone-android/files/10839450/linhome2.txt)


Hmm, indeed , i used 6002 to register on Linhome on port 9051, you can see that in log i actually call from 6000 to 6002 , and the invites comes froma  linhome user?

I disconnected my linhome account from the app, where is it coming from then?

**Comment by pergolafabio** [comment]
ah ok , so its possible its an ISP issue? or do you think its more a local problem/setting on asterisk side?

**Comment by Viish** [comment]
I think it's more related to your Asterisk config.
