### ISSUE TITLE
Disabling inbound calls for all accounts in the settings

### ISSUE THREAD

**Issue by nicoursi** [BelledonneCommunications/linphone-android#1865]
Hi,  as I never receive calls on thy SIP accounts, it would be nice to disable call receiving in the settings as it would consume resources uselessly in the above mentioned scenario. 

I've noticed that I can disable autostarting at boot,  but once I make a call the app remains in the background listening for calls that will never arrive.

Thanks a lot

**Comment by Viish** [comment]
Hi,
You can disable background mode in advanced settings, so when the app will be put in background, about 3 minutes later it will be killed by Android (or you can kill it manually).
Cheers,
