### ISSUE TITLE
Early Media shows black screen

### ISSUE THREAD

**Issue by dabhi86** [BelledonneCommunications/linphone-android#1866]
Hi Team Linphone,

In my android App, I am using this method to Login but by using this method, I keep getting only black screen in early media. I will mention one more method, by which I do receive early media video but then I don't get notifications properly.

Here is method 1, which causes black screen in early media.

        val account = core.createAccount(accountParams)
        core.createProxyConfig()
        core.addAuthInfo(authInfo)
        core.addAccount(account)
        core.defaultAccount = account
        account.addListener { _, state, message ->
            Log.d(TAG, "[Account] Registration state changed: $state, $message")
        }

I pass FCM token in accountParams to my OnSip server, this add notification token and notification provider info to Contact header and everything works fine except early media,
My server expects this contact header - 

Contact: <sip:tmiapp_9@49.36.181.223:55981;transport=udp>;pn-app=MiApp;pn-type=firebase;pn-tok=eKaSFwonR9iX4ZFvq25kzd:APA91bEVSSF4H41YSeSFPN5O6r28R5ZNXO0rKV6E8WoiUOayuCYsHjUk9fnztOh6fJuURLiK0Zgxlf2ma5LVN3IF52tsBjW0tKmoqqbINUEQjXho7B-STIpR_nXsBotJEJavJdzVLKPy;pn-bundle-id=org.miApp;+sip.instance="<urn:uuid:a3612fec-05f5-0076-a4f1-110e28e8bf88>

The login method mentioned above gives me a way to pass these parameters in ProxyConfig.

Here is 2nd method which shows early media properly but then I see no way to send proper Contact header this way and thus my OnSip server never receives this crucial information to deliver notifications to my App.

       fun createProxyConfig() {
               waitForServerAnswer.value = true
               coreContext.core.addListener(coreListener)
               accountCreator.username = username.value
               accountCreator.password = password.value
               accountCreator.domain = domain.value
               accountCreator.displayName = displayName.value
               accountCreator.transport = transport.value

               val proxyConfig: ProxyConfig? = accountCreator.createProxyConfig()
               proxyConfigToCheck = proxyConfig

               if (proxyConfig == null) {
                     Log.e("[Assistant] [Generic Login] Account creator couldn't create proxy config")
                     coreContext.core.removeListener(coreListener)
                     onErrorEvent.value = Event("Error: Failed to create account object")
                     waitForServerAnswer.value = false
                     return
               }

               Log.i("[Assistant] [Generic Login] Proxy config created")
        }

This method of Login doesn't let me send Contact headers in required format and causes notifications to not deliver to my App.

Please suggest a solution.

**Comment by Viish** [comment]
Hi,

The way the account is configured (Account vs ProxyConfig) doesn't matter, it's the same code in the SDK at the end.
Check your account configuration (network policy for example).

Push notification infos can be automatically set in the REGISTER by our SDK, see https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Push%20notifications/

Cheers,

**Comment by dabhi86** [comment]
Hi Viish,

Thanks for your prompt reply. I have a counter question for you. Is there any way to modify contact headers when I use AccountCreator? When I try to use accountCreator.setProxyConfig(prxCfg) then it refuses to login. It logs in only when I use accountCreator.createProxyConfig(). But this way I don't see a way to add custom parameters to Proxyconfig. My OnSip server requires that I send notification token through Contact headers in as set format which is - <sip:tmientry_9@49.36.181.103:47730;transport=udp>;pn-app=MiApp;pn-type=firebase;pn-tok=firebaseTokenWillBeInsertedHere;pn-bundle-id=org.miApp;+sip.instance="<urn:uuid:bfb2927a-5ae4-00cd-a397-8ef12258cc63>

Please suggest a way to modify contact headers when I use AccountCreator object. Your help is appreciated.

Regards

**Comment by Viish** [comment]
The `createProxyConfig()` method returns the ProxyConfig object, so you can use it to set your params:
```
val proxyConfig: ProxyConfig? = accountCreator.createProxyConfig()
proxyConfig.contactUriParameters("pn-app=MiApp;pn-type=firebase;pn-tok=firebaseTokenWillBeInsertedHere;pn-bundle-id=org.miApp;+sip.instance="urn:uuid:bfb2927a-5ae4-00cd-a397-8ef12258cc63")
```

**Comment by dabhi86** [comment]
Hi @Viish 

Thanks for your help, but even after setting proxyConfig.contactUriParameters, I still don't see any change in Contact Headers.
This is what it's sending -
`
     Contact: <sip:tmientry_9@49.36.181.103:55152;transport=udp>;expires=3366;received="sip:49.36.181.103:55152", <sip:tmientry_9@49.36.181.103:53749;transport=udp;pn-key=4d011bbfca91354fce500afd99d0bd06;received=49.36.181.103>;expires=82680, <sip:tmientry_9@49.36.181.103:33693;transport=udp>;expires=3208;received="sip:49.36.181.103:33693", <sip:tmientry_9@49.36.181.103:47730;transport=udp;pn-key=524a7660dea23b5c85f55ae5aa28d559;received=49.36.181.103>;expires=83462, <sip:tmientry_9@47.31.98.48:36276;transport=udp;pn-key=78b321fec4d8887892006f4850a4dc70>;expires=9027, <sip:tmientry_9@49.36.181.103:40026;transport=udp>;expires=1614;received="sip:49.36.181.103:40026", <sip:tmientry_9@49.36.181.103:60227;transport=udp>;expires=3600;received="sip:49.36.181.103:60227"
`

Please suggest something, i have tried numerous settings but every time I see same headers. Thanks again for your help.

Regards
