### ISSUE TITLE
some problems of video conference

### ISSUE THREAD

**Issue by August1023** [BelledonneCommunications/linphone-android#1867]
Hi,
"linphone-sdk-android-5.0.71" supports the early media of video conferencing. Is "linphone-sdk-android-4.3" supported?Using "linphone-sdk-android-4.3" to make conference calls, the early media and the video after connection cannot be displayed. Which version of sdk began to support video conferencing?

**Comment by Viish** [comment]
Hi,
Video conferencing has been added in linphone-sdk 5.2.0
Cheers,

**Comment by August1023** [comment]
When I use "linphone-sdk-android-5.0.71" to make conference calls, I can see videos in early media. Why?

**Comment by Viish** [comment]
If you simply make a call, then no matter if it's a conference on the other end or not, the callee can send you early media video. It's simply not related to conference.
Early media video has been there for a while, I can't says which version of the SDK added it, but it might have been a bug that was fixed in a later release.

**Comment by August1023** [comment]
Sorry, there may be something wrong with my description.
When I use "linphone-sdk-android-5.0.71" to make conference calls,the callee can see the early media video I send.
I need this function, but it cannot be implemented in "linphone-sdk-android-4.3".

**Comment by Viish** [comment]
What do you mean by "conference calls"?
Also, why do you want so badly to stick with an obsolete SDK that is many years old and not use the latest release?

**Comment by August1023** [comment]
> What do you mean by "conference calls"?

mCore.getConference().inviteParticipants(list.toArray(new Address[list.size()]), params);

> Also, why do you want so badly to stick with an obsolete SDK that is many years old and not use the latest release?

Because the device version is Android 4.

**Comment by Viish** [comment]
Video conferencing by locally merging calls was never meant to work, so if it does it either a bug or a happy mistake.

By the way, it's time to let go of Android 4 devices...

**Comment by August1023** [comment]
Is there a corresponding APP version for video conferencing?

> By the way, it's time to let go of Android 4 devices...

Sadly, I can't decide.

**Comment by Viish** [comment]
> It seems that the latest version of APP does not support video conferencing.

Video conferencing is available on all linphone app starting 5.0 releases.
But for it to be available, you have to use a sip.linphone.org account or to configure an account with a video conference factory URI.

> In the latest version of PC client, how should I create a video conference URI?

You have to open the conference creation dialog, but the button is only visible if the account has a video conference factory URI set.

**Comment by August1023** [comment]
> You have to open the conference creation dialog, but the button is only visible if the account has a video conference factory URI set.

How do I get the video conference factory URI? Or how can I create a video conference factory URI?

**Comment by Viish** [comment]
This information is given by the conference server (linphone ony supports remote video conferencing - using a server).
If you use flexisip it's a configuration item.
