### ISSUE TITLE
SDK fails to set AccountCreator's contactParameters

### ISSUE THREAD

**Issue by dabhi86** [BelledonneCommunications/linphone-android#1868]
Hi Team Linphone,

Why SDK is not letting me add Contact Parameters to ProxyConfig when I use Account Creator to register my account? This is the code I have tried but it doesn't work and my server never receives Contact Params is required format.

     var pConfig = accountCreator.createProxyConfig()
     pConfig?.contactParameters = tempContactsParams

I even tried this code but this also doesn't set the Contact Params.
     pConfig?.contactParameters = tempContactsParams

Please suggest a way to add Contact params when using AccountCreator. Your help is appreciated.

Regards

**Comment by Viish** [comment]
Hi,

Please note that ProxyConfig object is deprecated, it's now replaced by Account and AccountParams objects.
That being said, you have to first call `edit()` and once you have finished doing your changes you have to call `done()` on the ProxyConfig.

Cheers,
