### ISSUE TITLE
Linphone App doesn't show Early Media when Login by creating Account Object

### ISSUE THREAD

**Issue by dabhi86** [BelledonneCommunications/linphone-android#1870]
Hi Team Linphone,

I have cloned Linphone's master branch from Github and noticed that Linphone App uses AccountCreator object to login by passing xmlRpcServerUrl to createAccountCreator. This way I do see Early media when I use free linphone sip account. However when I login by using account = core.createAccount(accountParams) then I am able to Login and I do get incoming calls but I never receive Early Media, calls with early media simply show as normal calls. I am using Linphone's app and Linphone's sip account to test login functionality.

I want to know why Linphone doesn't show any early media when we use Account object to login whereas early media works absolutely fine when we use AccountCreator object?

Please provide clarification on this.

I really appreciate your help.

Regards

**Comment by Viish** [comment]
Hi,

The only difference that may happen between the AccountCreator and creating an Account manually is it's configuration.
Create your account with AccountCreator and check your config file to see how it is configured.
Then do the same by creating an Account object and compare the results.
You can see the config file in linphone-android by dialing `#1234#` and clicking on `View config file` option of popup menu.

Cheers,

**Comment by dabhi86** [comment]
Thanks for your quick response. I checked Config file in both cases but didn't see any significant change that may cause Early media to show in one case but not show in another. I am attaching both config files' data here, can you please point out which config setting decides whether or not Early Media will be displayed. I am using Linphone's Sip account in Linphone's app in both case. I really appreciate your help.

Config data when using Account Object
    [sip]
	contact="Linphone Android" <sip:linphone.android@unknown-host>
	use_info=0
	keepalive_period=30000
	sip_port=-1
	sip_tcp_port=-1
	sip_tls_port=-1
	media_encryption=srtp
	guess_hostname=1
	register_only_when_network_is_up=1
	auto_net_state_mon=1
	auto_answer_replacing_calls=1
	ping_with_options=0
	use_cpim=1
	zrtp_key_agreements_suites=MS_ZRTP_KEY_AGREEMENT_K255_KYB512
	chat_messages_aggregation_delay=1000
	chat_messages_aggregation=1
	ipv6_migration_done=1
	root_ca=/data/user/0/org.linphone.debug/files/share/linphone/rootca.pem
	verify_server_certs=1
	verify_server_cn=1
	auto_send_ringing=1
	supported=replaces, outbound, gruu, path, record-aware
	user_agent=LinphoneAndroid/5.1.0-alpha.73+083c1afa1 (Abhinav's Galaxy A6+) LinphoneSDK/5.2.28 (tags/5.2.28^0)
	http_proxy_port=0
	default_proxy=1
	use_rfc2833=1
	rls_uri=sips:rls@sip.linphone.org
	incoming_calls_early_media=1
	outgoing_calls_early_media=1
	inc_timeout=45
	in_call_timeout=0
	delayed_timeout=4
	register_only_when_upnp_is_ok=1
	linphone_specs=conference/1.0,ephemeral/1.1,groupchat/1.2,lime
[net]
	download_bw=0
	upload_bw=0
	mtu=1300
	force_ice_disablement=0
	nat_policy_ref=Oxpnr6vggPX4Umd
	friendlist_subscription_enabled=0
[video]
	size=vga
	displaytype=MSAndroidTextureDisplay
	auto_resize_preview_to_keep_ratio=1
	max_conference_size=vga
	show_local=0
	capture=1
	display=1
	preset=default
	device=FrontFacingCamera1
	automatically_initiate=1
	automatically_accept=1
[app]
	tunnel=disabled
	auto_start=1
	record_aware=1
	activation_code_length=4
	prefer_basic_chat_room=1
	auto_download_incoming_files_max_size=-1
	auto_download_incoming_voice_recordings=1
	auto_download_incoming_icalendars=1
	sender_name_hidden_in_forward_message=0
	incoming_call_vibration=0
	first_start=0
	read_and_agree_terms_and_privacy=1
	version_check_url_last_timestamp=-1535903710
	use_self_managed_telecom_manager=1
	call_overlay=1
	redirect_declined_call_to_voice_mail=1
[tunnel]
	port=443
[misc]
	log_collection_upload_server_url=https://www.linphone.org:444/lft.php
	file_transfer_server_url=https://www.linphone.org:444/lft.php
	version_check_url_root=https://www.linphone.org/releases
	max_calls=10
	history_max_size=100
	conference_layout=1
	enable_basic_to_client_group_chat_room_migration=0
	enable_simple_group_chat_message_state=0
	aggregate_imdn=1
	notify_each_friend_individually_when_presence_received=0
	empty_chat_room_deletion=1
	vibrate_on_incoming_call=1
	user_certificates_path=/data/user/0/org.linphone.debug/files/user-certs
	prefer_basic_chat_room=1
	uuid=f62b8d09-1710-0027-8514-fe5256aaf8bd
[in-app-purchase]
	server_url=https://subscribe.linphone.org:444/inapp.php
	purchasable_items_ids=test_account_subscription
[rtp]
	accept_any_encryption=1
	audio_rtp_port=-1
	video_rtp_port=-1
	text_rtp_port=-1
	audio_jitt_comp=60
	video_jitt_comp=60
	nortp_timeout=30
	audio_adaptive_jitt_comp_enabled=1
	video_adaptive_jitt_comp_enabled=1
[sound]
	ec_calibrator_cool_tones=1
	playback_dev_id=AAudio Earpiece: SM-A605G
	ringer_dev_id=AAudio Earpiece: SM-A605G
	capture_dev_id=AAudio Microphone: SM-A605G
	media_dev_id=AAudio Earpiece: SM-A605G
	remote_ring=/data/user/0/org.linphone.debug/files/share/sounds/linphone/ringback.wav
	playback_gain_db=0.000000
	mic_gain_db=0.000000
	disable_record_on_mute=0
[assistant]
	xmlrpc_url=https://subscribe.linphone.org:444/wizard.php
	algorithm=MD5
	password_max_length=-1
	password_min_length=0
	username_length=-1
	username_max_length=128
	username_min_length=1
	username_regex=^[a-zA-Z0-9+_.\-]*$
[account_creator]
	backend=0
[lime]
	lime_update_threshold=-1
	enabled=1
	last_update_time=1677796838
[proxy_default_values]
	avpf=0
	dial_escape_plus=0
	publish=0
	quality_reporting_enabled=0
	quality_reporting_interval=0
	reg_expires=3600
	reg_sendregister=1
	push_notification_allowed=0
	cpim_in_basic_chat_rooms_enabled=0
	rtp_bundle=0
[nat_policy_default_values]
[nat_policy_0]
	ref=Oxpnr6vggPX4Umd
[audio_codec_0]
	mime=opus
	rate=48000
	channels=2
	enabled=1
	recv_fmtp=useinbandfec=1
[audio_codec_1]
	mime=speex
	rate=16000
	channels=1
	enabled=1
	recv_fmtp=vbr=on
[audio_codec_2]
	mime=speex
	rate=8000
	channels=1
	enabled=1
	recv_fmtp=vbr=on
[audio_codec_3]
	mime=PCMU
	rate=8000
	channels=1
	enabled=1
[audio_codec_4]
	mime=PCMA
	rate=8000
	channels=1
	enabled=1
[audio_codec_5]
	mime=GSM
	rate=8000
	channels=1
	enabled=0
[audio_codec_6]
	mime=G722
	rate=8000
	channels=1
	enabled=0
[audio_codec_7]
	mime=iLBC
	rate=8000
	channels=1
	enabled=0
	recv_fmtp=mode=30
[audio_codec_8]
	mime=iSAC
	rate=16000
	channels=1
	enabled=0
[audio_codec_9]
	mime=speex
	rate=32000
	channels=1
	enabled=0
	recv_fmtp=vbr=on
[audio_codec_10]
	mime=L16
	rate=44100
	channels=2
	enabled=0
[audio_codec_11]
	mime=L16
	rate=44100
	channels=1
	enabled=0
[video_codec_0]
	mime=VP8
	rate=90000
	enabled=1
[video_codec_1]
	mime=H264
	rate=90000
	enabled=1
	recv_fmtp=profile-level-id=42801F
[video_codec_2]
	mime=H265
	rate=90000
	enabled=1
[audio]
	android_disable_audio_focus_requests=1
	android_pause_calls_when_audio_focus_lost=1
[auth_info_0]
	username=pmientryabhi
	userid=pmientryabhi
	ha1=121722b9e216abf4ea11c6f8669ab6d4
	realm=sip.linphone.org
	domain=sip.linphone.org
	algorithm=MD5
	available_algorithms=MD5
[proxy_0]
	reg_proxy=<sip:sip.linphone.org;transport=udp>
	reg_route=sip:sip.linphone.org;transport=udp
	reg_identity=sip:pmientryabhi@sip.linphone.org
	contact_parameters=pn-app=MiEntry;pn-type=firebase;pn-tok=drfredffffghfsdcfgdgdhgbcbvjhjfhgxfdfgncgchgvn;pn-bundle-id=org.linphone.debug
	quality_reporting_enabled=0
	quality_reporting_interval=0
	reg_expires=86400
	reg_sendregister=1
	publish=0
	avpf=1
	avpf_rr_interval=3
	dial_escape_plus=0
	use_dial_prefix_for_calls_and_chats=1
	privacy=32768
	push_notification_allowed=0
	remote_push_notification_allowed=0
	cpim_in_basic_chat_rooms_enabled=1
	idkey=proxy_config_2gQ12OPhVHeu4PV
	publish_expires=-1
	conference_factory_uri=sip:conference-factory@sip.linphone.org
	audio_video_conference_factory_uri=sip:videoconference-factory@sip.linphone.org
	rtp_bundle=1
	rtp_bundle_assumption=0
	lime_server_url=https://lime.linphone.org/lime-server/lime-server.php
[proxy_1]
	reg_proxy=<sip:sip.linphone.org;transport=udp>
	reg_route=sip:sip.linphone.org;transport=udp
	reg_identity=sip:pmientryabhi@sip.linphone.org
	contact_parameters=pn-app=MiEntry;pn-type=firebase;pn-tok=drfredffffghfsdcfgdgdhgbcbvjhjfhgxfdfgncgchgvn;pn-bundle-id=org.linphone.debug
	quality_reporting_enabled=0
	quality_reporting_interval=0
	reg_expires=86400
	reg_sendregister=1
	publish=0
	avpf=1
	avpf_rr_interval=3
	dial_escape_plus=0
	use_dial_prefix_for_calls_and_chats=1
	privacy=32768
	push_notification_allowed=0
	remote_push_notification_allowed=0
	cpim_in_basic_chat_rooms_enabled=1
	idkey=proxy_config_efiCnClkfnlgWaY
	publish_expires=-1
	conference_factory_uri=sip:conference-factory@sip.linphone.org
	audio_video_conference_factory_uri=sip:videoconference-factory@sip.linphone.org
	rtp_bundle=1
	rtp_bundle_assumption=0
	lime_server_url=https://lime.linphone.org/lime-server/lime-server.php

Config data when using AccountCreator Object

    [sip]
	contact="Linphone Android" <sip:linphone.android@unknown-host>
	use_info=0
	keepalive_period=30000
	sip_port=-1
	sip_tcp_port=-1
	sip_tls_port=-1
	media_encryption=srtp
	guess_hostname=1
	register_only_when_network_is_up=1
	auto_net_state_mon=1
	auto_answer_replacing_calls=1
	ping_with_options=0
	use_cpim=1
	zrtp_key_agreements_suites=MS_ZRTP_KEY_AGREEMENT_K255_KYB512
	chat_messages_aggregation_delay=1000
	chat_messages_aggregation=1
	ipv6_migration_done=1
	root_ca=/data/user/0/org.linphone.debug/files/share/linphone/rootca.pem
	verify_server_certs=1
	verify_server_cn=1
	auto_send_ringing=1
	supported=replaces, outbound, gruu, path, record-aware
	user_agent=LinphoneAndroid/5.1.0-alpha.73+083c1afa1 (Abhinav's Galaxy A6+) LinphoneSDK/5.2.28 (tags/5.2.28^0)
	http_proxy_port=0
	linphone_specs=conference/1.0,ephemeral/1.1,groupchat/1.2,lime
	default_proxy=0
	rls_uri=sips:rls@sip.linphone.org
	use_rfc2833=1
	incoming_calls_early_media=1
	outgoing_calls_early_media=1
[net]
	download_bw=0
	upload_bw=0
	mtu=1300
	force_ice_disablement=0
	nat_policy_ref=qEVeOhWNEAmlAfP
	friendlist_subscription_enabled=1
[video]
	size=vga
	displaytype=MSAndroidTextureDisplay
	auto_resize_preview_to_keep_ratio=1
	max_conference_size=vga
	show_local=0
	capture=1
	display=1
	preset=default
	device=FrontFacingCamera1
	automatically_initiate=1
	automatically_accept=1
[app]
	tunnel=disabled
	auto_start=1
	record_aware=1
	activation_code_length=4
	prefer_basic_chat_room=1
	auto_download_incoming_files_max_size=-1
	auto_download_incoming_voice_recordings=1
	auto_download_incoming_icalendars=1
	sender_name_hidden_in_forward_message=0
	incoming_call_vibration=0
	first_start=0
	read_and_agree_terms_and_privacy=1
	call_overlay=1
	redirect_declined_call_to_voice_mail=1
	version_check_url_last_timestamp=-1530874460
	use_self_managed_telecom_manager=1
[tunnel]
	port=443
[misc]
	log_collection_upload_server_url=https://www.linphone.org:444/lft.php
	file_transfer_server_url=https://www.linphone.org:444/lft.php
	version_check_url_root=https://www.linphone.org/releases
	max_calls=10
	history_max_size=100
	conference_layout=1
	enable_basic_to_client_group_chat_room_migration=0
	enable_simple_group_chat_message_state=0
	aggregate_imdn=1
	notify_each_friend_individually_when_presence_received=0
	empty_chat_room_deletion=1
	vibrate_on_incoming_call=1
	user_certificates_path=/data/user/0/org.linphone.debug/files/user-certs
	prefer_basic_chat_room=1
	uuid=1097fec8-647d-0020-b1bb-8af55725763a
[in-app-purchase]
	server_url=https://subscribe.linphone.org:444/inapp.php
	purchasable_items_ids=test_account_subscription
[rtp]
	accept_any_encryption=1
[sound]
	ec_calibrator_cool_tones=1
	playback_dev_id=AAudio Earpiece: SM-A605G
	ringer_dev_id=AAudio Earpiece: SM-A605G
	capture_dev_id=AAudio Microphone: SM-A605G
	media_dev_id=AAudio Earpiece: SM-A605G
[assistant]
	xmlrpc_url=https://subscribe.linphone.org:444/wizard.php
	domain=sip.linphone.org
	algorithm=SHA-256
	password_max_length=-1
	password_min_length=1
	username_length=-1
	username_max_length=64
	username_min_length=1
	username_regex=^[a-z0-9+_.\-]*$
[account_creator]
	backend=0
[lime]
	lime_update_threshold=-1
	enabled=1
	last_update_time=1677800754
[proxy_default_values]
	avpf=1
	dial_escape_plus=0
	publish=0
	quality_reporting_collector=sip:voip-metrics@sip.linphone.org;transport=tls
	quality_reporting_enabled=1
	quality_reporting_interval=180
	reg_expires=31536000
	reg_identity=sip:?@sip.linphone.org
	reg_proxy=<sip:sip.linphone.org;transport=tls>
	reg_route=<sip:sip.linphone.org;transport=tls>
	reg_sendregister=1
	nat_policy_ref=nat_policy_default_values
	realm=sip.linphone.org
	conference_factory_uri=sip:conference-factory@sip.linphone.org
	audio_video_conference_factory_uri=sip:videoconference-factory@sip.linphone.org
	push_notification_allowed=1
	cpim_in_basic_chat_rooms_enabled=1
	rtp_bundle=1
	lime_server_url=https://lime.linphone.org/lime-server/lime-server.php
[nat_policy_default_values]
	stun_server=stun.linphone.org
	protocols=stun,ice
[nat_policy_0]
	ref=qEVeOhWNEAmlAfP
[nat_policy_1]
	stun_server=stun.linphone.org
	protocols=stun,ice
[proxy_0]
	reg_proxy=<sip:sip.linphone.org;transport=tls>
	reg_route=<sip:sip.linphone.org;transport=tls>
	reg_identity=sip:pmientryabhi@sip.linphone.org
	realm=sip.linphone.org
	quality_reporting_collector=sip:voip-metrics@sip.linphone.org;transport=tls
	push_parameters=pn-prid=dKXK07Y7T5e1bWyrBz2YeP:APA91bGpY2M3gDSI-NKsgqdtSg0DTOilV8fqg7-eR7-DtS9_hjs_RHfmY6eVfQXwXfWsa9prHhrGhxDcasIVaq9rtNe7tOuqytdNYvVjhmSOvdNeNG7FZDdrpVSe05O-cR1B1piF7apU;pn-provider=fcm;pn-param=929724111839;pn-silent=1;pn-timeout=0;
	quality_reporting_enabled=1
	quality_reporting_interval=180
	reg_expires=31536000
	reg_sendregister=1
	publish=0
	avpf=1
	avpf_rr_interval=1
	dial_escape_plus=0
	dial_prefix=91
	use_dial_prefix_for_calls_and_chats=1
	privacy=32768
	push_notification_allowed=1
	remote_push_notification_allowed=0
	cpim_in_basic_chat_rooms_enabled=1
	idkey=proxy_config_KJZEDP-NpYJu4OB
	publish_expires=-1
	conference_factory_uri=sip:conference-factory@sip.linphone.org
	audio_video_conference_factory_uri=sip:videoconference-factory@sip.linphone.org
	rtp_bundle=1
	rtp_bundle_assumption=0
	lime_server_url=https://lime.linphone.org/lime-server/lime-server.php
[auth_info_0]
	username=pmientryabhi
	ha1=121722b9e216abf4ea11c6f8669ab6d4
	realm=sip.linphone.org
	domain=sip.linphone.org
	algorithm=MD5
	available_algorithms=MD5
[audio_codec_0]
	mime=opus
	rate=48000
	channels=2
	enabled=1
	recv_fmtp=useinbandfec=1
[audio_codec_1]
	mime=speex
	rate=16000
	channels=1
	enabled=1
	recv_fmtp=vbr=on
[audio_codec_2]
	mime=speex
	rate=8000
	channels=1
	enabled=1
	recv_fmtp=vbr=on
[audio_codec_3]
	mime=PCMU
	rate=8000
	channels=1
	enabled=1
[audio_codec_4]
	mime=PCMA
	rate=8000
	channels=1
	enabled=1
[audio_codec_5]
	mime=GSM
	rate=8000
	channels=1
	enabled=0
[audio_codec_6]
	mime=G722
	rate=8000
	channels=1
	enabled=0
[audio_codec_7]
	mime=iLBC
	rate=8000
	channels=1
	enabled=0
	recv_fmtp=mode=30
[audio_codec_8]
	mime=iSAC
	rate=16000
	channels=1
	enabled=0
[audio_codec_9]
	mime=speex
	rate=32000
	channels=1
	enabled=0
	recv_fmtp=vbr=on
[audio_codec_10]
	mime=L16
	rate=44100
	channels=2
	enabled=0
[audio_codec_11]
	mime=L16
	rate=44100
	channels=1
	enabled=0
[video_codec_0]
	mime=VP8
	rate=90000
	enabled=1
[video_codec_1]
	mime=H264
	rate=90000
	enabled=1
	recv_fmtp=profile-level-id=42801F
[video_codec_2]
	mime=H265
	rate=90000
	enabled=1
[audio]
	android_pause_calls_when_audio_focus_lost=1
	android_disable_audio_focus_requests=1

**Comment by dabhi86** [comment]
@Viish 

So finally I matched the configuration in both cases and still not receiving Early Media when using Account Object. Config file is 100% same and still no Early Media. I am using Linphone's SIP account in Linphone Android App.

Can you please explain why is early media video not being received?
