### ISSUE TITLE
About chat message

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1871]
Hi Viish,

1) Is chat message automatically saved to linphone.db by default?
2) I didn't find out where to handle it. What is the process?
3) What happens if too many chat messages cause the database to be full?
4) Is there any way not to save the chat message to the database?
5) Will repeatedly saving these data to linphone.db cause the database to crash?

thanks,
Best Regards.
![linphone-db-chatmeasage](https://user-images.githubusercontent.com/45247821/222613429-587dd99a-90a4-40b4-988a-54f7c99b6938.png)

**Comment by Viish** [comment]
Hi,

> Is chat message automatically saved to linphone.db by default?

Yes, it is.

> What happens if too many chat messages cause the database to be full?

We have users with dozen thousands of messages, never had a single issue.

> Is there any way not to save the chat message to the database?

Yes, there is one. Set `message.toBeStored = false` in message received callback.

> Will repeatedly saving these data to linphone.db cause the database to crash?

Not to our knowledge, no.
