### ISSUE TITLE
Voice echo during call

### ISSUE THREAD

**Issue by roked** [BelledonneCommunications/linphone-android#1876]
### 1.Bug description:

On a device with MediaTek chip we have a local build of linphone android which uses Linphone SDK 5.1 for VOIP calls. The implementation if linphone is same as per the Linphone android version 4.6 if I am not wrong. 

The problem is - the user can hear its own voice when they speak. It's like a delayed echo of the voice. If I say "Hi" I can here my own voice like 2 second later. 

I tested the problem using the latest Play Store app and i can reproduce it.

### 2. How to reproduce

There is no clear way how to reproduce it as the device I use is a custom on, but the import point is that there is a second microphone on the top of the phone near the ear peace (widely used for noise reduction). I concluded that this microphone for some reason malfunctions on the device and causes the resonating voice from the receiver side. So it is not the problem with the person who speaks but the person who listens - theirs phone resonates the sound back.

### 3. Expected behavior

Clear and no-echo call.

### 4. Device info

 - Device: NDA
 - OS: Android 11
 - Version of the App: 4.6.0
 - Version of the SDK: 5.1.0
 - Where you did got it from: local build
 - It is not Lineage OS but it is a custom android OS.

If you are using a SDK that isn't the latest release, please update first as it's likely your issue is already solved. - **tested** also with the latest SDK

### 5. Additional context

Linphone settings are as follow:

core.isEchoCancellationEnabled = true
core.isEchoLimiterEnabled = true

No custom edits on the SDK.

As I said the reason for the echo/resonating voice is the microphone on the top of the phone which can be a hardware issue, but my question is:

Is there a way I can completely ignore the second microphone by either from the linphone android or SDK side ?

**Comment by Viish** [comment]
Hi,

Can you send me logs?
But given that you are using a custom device with a custom firmware, it is likely we can't do much if the issue lies in the audio drivers.
I recommend you to contact our company and purchase a support contract so we can help you more: https://linphone.org/contact#content-bottom3

Cheers,

**Comment by roked** [comment]
Hi Viish,

I can't provide you with logs as there is not specific error or warning to track the issue by. 
I was wondering if I can modify the Linphone SDK to permanently disable the usage of Noise cancellation and reduction, and if possible to tell block linphone from using the second microphone (on the top).

Cheers

**Comment by Viish** [comment]
> I was wondering if I can modify the Linphone SDK to permanently disable the usage of Noise cancellation and reduction, and if possible to tell block linphone from using the second microphone (on the top).

That's not how Android sound system works.

> I can't provide you with logs as there is not specific error or warning to track the issue by.

I guess I'm more capable than you to check our logs and see if there is something that could be done.

Sorry but without more info there is nothing I can do for you.
