### ISSUE TITLE
Wrong Contact Header

### ISSUE THREAD

**Issue by disolaterX** [BelledonneCommunications/linphone-android#1878]
Hi @Viish 

Linphone is setting the contact header in register & invite with private IP we have even used STUN 

anything special needed to be done for correct contact header ?

Thanks

**Comment by Viish** [comment]
@disolaterX 

I moved the issue you already opened to the right project (linphone-sdk) as this has nothing to do with Android app.
Please stop opening issue here if it doesn't relate to the app specifically.

Duplicate of https://github.com/BelledonneCommunications/linphone-sdk/issues/288
