### ISSUE TITLE
Enable G711 and G729 Audio codec in Linphone Android Kotlin Version

### ISSUE THREAD

**Issue by Adnan-addi** [BelledonneCommunications/linphone-android#1879]
Hi @Viish 

I am using latest kotlin wrapper for linphone android i need to enable G729 and g711 audio codec. but i could not find it in the audio setting list .

can you please describe how i could get them enabled from aar sdk or should i go for local sdk please help .

**Comment by Viish** [comment]
Hi,

First of all, using G729 codec requires your app be compliant with GPLv3 license or for you to purchase a proprietary license from us.
That being said, you can build the SDK yourself with G729 as we don't provide pre-built binaries with it.
G711 is already part of our SDK by default, pre-built or not.

Cheers,

**Comment by Adnan-addi** [comment]
@Viish okay Thank you . I understand about G729 but strange thing is i cannot find G711 in existing list in audio settings. Is there any more settings to show it in the Audio Setting codec list ?

**Comment by Adnan-addi** [comment]
![1678854487806](https://user-images.githubusercontent.com/25033749/225206654-95cac4ab-3f18-420e-a6b9-305c2baf8f15.JPEG)
![1678854487824](https://user-images.githubusercontent.com/25033749/225206669-8fcb8da3-e30c-4d84-a1cf-6a0a464ae600.JPEG)

**Comment by Adnan-addi** [comment]
@Viish please check the screenshots and G711 cannot be found please help in this regard .

Thank You

**Comment by Viish** [comment]
G711 is named PCMU / PCMA

**Comment by Adnan-addi** [comment]
Thank You so much
