### ISSUE TITLE
Encryption issues

### ISSUE THREAD

**Issue by sestebn** [BelledonneCommunications/linphone-android#188]
Our team has updated Linphone recently and we have come to a problem with encryption.

We were using SRTP encryption for our calls and set encryption as not mandatory but after updating the library we are not receiving streams any more.
We exchange audio streams id we switch to ZRTP encryption but we never get video.
We have seen that there are new attributes for LinphoneCallParams (like Privacy) but don't know if we need to set any of them.

We also used this firewall policy but method is deprecated now:
`linphoneCore.setFirewallPolicy(LinphoneCore.FirewallPolicy.UseNatAddress);`
We don't know the proper way to replace it or if it has something to do with the problem.

Any help would be appreciated.

**Comment by SBelkaid** [comment]
Where did you set encryption not mandatory? Also are you using asterisk? If srtp not working it could also be an issue with the server
