### ISSUE TITLE
Add skip option to Assistant

### ISSUE THREAD

**Issue by mwarning** [BelledonneCommunications/linphone-android#1885]
Hi,

while trying to figure out how to call an IP address, I've found this helpful youtube video:

https://www.youtube.com/watch?v=tc6DlZ_tFaE

Add option in Assistant: "Continue to Application" or something with a similar in meaning.

**Comment by Viish** [comment]
Hi,

Thanks for the video, we didn't know about it.
I take good note of the suggestion, we are currently in the process of designing a new interface for our apps, I hope we can publish it for the end of the year.

Cheers,

**Comment by mwarning** [comment]
I was also trying to connect to an IP address and hit the same problem.

**Comment by Viish** [comment]
I'm closing this issue as we decided to promote the usage of a sip.linphone.org account and removed some features related to peer to peer.
