### ISSUE TITLE
Usability Enhancements

### ISSUE THREAD

**Issue by mwarning** [BelledonneCommunications/linphone-android#1886]
A list of usability issues:

* share contacts via QR-Code (see also https://github.com/juha-h/baresip-studio/issues/340)
* be able to select system IP addresses for own sip address (instead of picking it from some terminal)
* make it easier to skip assistent (https://github.com/BelledonneCommunications/linphone-android/issues/1885)
* do not force users to allow the Android telefone contact list for their contacts (the permissions request pops up very often)
* highlight all invalid fields in the new contact dialog. Right now, when saving the contact, the dialog closes and the entry is lost without any error.

**Comment by Viish** [comment]
- Share contacts via QR code doesn't interest us, we aren't a contacts management app. We only offer some basic contact edition to ease the process of adding SIP URI to a native contact as not all native contacts app are permitting it, that's all.
- Following on that, we do not force users to grant the read contacts permission, it is only asked in the Contacts list part of the app and when you are asked to pick participants (creating a conference or a conversation for exemple), that's all. You can always ask Android to not ask you about this permission again, and you can also disable the `enableNativeAddressBookIntegration` setting in CorePreferences on using a remote configuration.
- If you have found an issue with our contact editor, I'd like you to reproduce the issue and attach logs so I can fix it, thanks.

Regarding the IP address for doing peer to peer calls this is not something we try to encourage, as there are many features that won't be available and there are many networks on which that won't work properly.
The best way to do SIP calls is using a proxy server, even if it can work without one.

Finally for the `Skip Assistant` suggestion I already answered in ticket #1885.

**Comment by mwarning** [comment]
@Viish thank you for your reply. I will create a ticket for any specific bug I find.

As for the permissions, if I deny access to the address book, then I cannot create contacts. Doesn't Linphone have a separate contact list from Androids contact list of phone contacts?

**Comment by Viish** [comment]
@mwarning No, linphone currently only supports adding contacts to native address book.

**Comment by mwarning** [comment]
Got it, that explains why I get asked so many times.
The problem here was that the add contact form is available and then on saving linphone asks for permissions. This gives the impression that the contact will be not be stored in the phones contact list but just somewhere else. Instead if data is silently discarded.
