### ISSUE TITLE
linphone crashes on arm64 (on core restart)

### ISSUE THREAD

**Issue by Koutoulakis** [BelledonneCommunications/linphone-android#189]
Hi Everybody!

There is an issue with how remote provision is implemented. 
On every phone, if one adds a wrong provisioning url and submits it multiple times the app will end up with a native crash of the following form (recreated with linphone app from GooglePlayStore) : 

01-16 10:59:54.901  1188  1545 E HwCHRWebMonitor: HwCHRWifiPacketCnt [mTXGood=5, mTXbad=0, mRXGood=6] rssi=-60
01-16 10:59:54.903  1188  1545 E HwCHRWebMonitor: running processName=org.linphone
01-16 10:59:54.904  1188  1545 E HwCHRWebMonitor: HwCHRWifiUIDWebSpeed [appName=com.microsoft.office.outlook UID=10141  WEBSENDSEGS=3  WEBRESENDSEGS=0  WEBRECVSEGS=3  WEBERRSEGS=0  WEBOUTRSTS=0  WEBESTABLISRST=0  WEBRTTDURATION=79  WEBRTTSEGS=2  WEBSNDDUPACKS=0  suckTimes=0 recovage_times=0]
01-16 10:59:54.907 22896 22896 I HwPointEventFilter: do not support AFT because of no config
01-16 10:59:54.942 22896 22896 W IInputConnectionWrapper: beginBatchEdit on inactive InputConnection
01-16 10:59:54.942 22896 22896 W IInputConnectionWrapper: setComposingRegion on inactive InputConnection
01-16 10:59:54.942 22896 22896 W IInputConnectionWrapper: endBatchEdit on inactive InputConnection
01-16 10:59:54.942 22896 22896 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
01-16 10:59:54.943   472  1848 I gralloc : alloc_device_alloc:626: Alloc handle(0x77bb82f000): interfmt=1, stride=832, size=454656, usage=0xb00
01-16 10:59:54.943   472  1848 I gralloc : alloc_device_alloc:626: Alloc handle(0x77bb80ff00): interfmt=1, stride=832, size=454656, usage=0xb00
01-16 10:59:54.944   472  1848 I gralloc : alloc_device_alloc:626: Alloc handle(0x77b2c43600): interfmt=1, stride=832, size=454656, usage=0xb00
01-16 10:59:55.095  1592  3728 W KeyPressModelHandlerImpl: Attempted to save before layout configured.
01-16 10:59:55.109  1592  3728 W KeyPressModelHandlerImpl: Attempted to save before layout configured.
01-16 10:59:55.110  1592  3728 W KeyPressModelHandlerImpl: Attempted to save before layout configured.
01-16 10:59:55.135   472   472 I gralloc : alloc_device_free:648: Free handle(0x77bb80f300)
01-16 10:59:55.316  1188  1188 I MQoS    : onSignal: mSubId=1,currDataSubID=1
01-16 10:59:55.316  1188  1188 I MQoS    : received cell-signal:5
01-16 10:59:55.316  1188  1459 I SendBroadcastPermission: action:android.intent.action.SIG_STR, mPermissionType:0
01-16 10:59:55.320  1605  1684 I HwMobileSignalController: subId:1 phoneType:1 networktype:13 targetClass:3 masterLevel:4 slaveLevel:-1
01-16 10:59:55.411 22896 22896 I HwPointEventFilter: do not support AFT because of no config
01-16 10:59:55.421 22896 22896 I BitmapFactory: set decoder allocator to gralloc
01-16 10:59:55.423 22896 22896 I gralloc : alloc_device_alloc:626: Alloc handle(0x7ba5c99300): interfmt=1, stride=768, size=2310144, usage=0x2000003
01-16 10:59:55.433 22896 22896 I gralloc : alloc_device_alloc:626: Alloc handle(0x7ba5c99500): interfmt=1, stride=1152, size=5197824, usage=0x2000003
01-16 10:59:55.451 22896 22896 I gralloc : alloc_device_free:648: Free handle(0x7ba5c99500)
01-16 10:59:55.451 22896 22896 I gralloc : alloc_device_free:648: Free handle(0x7ba5c99300)
01-16 10:59:55.452 22896 22896 W BluetoothManager: [Bluetooth] Stopping...
01-16 10:59:55.452 22896 22896 W BluetoothManager: [Bluetooth] Stopped!
01-16 10:59:55.454 22896 22896 I AudioManager: setSpeakerphoneOn on:false
01-16 10:59:55.459 22896 22905 F libc    : Fatal signal 7 (SIGBUS), code 1, fault addr 0x3d65646f6d203b in tid 22905 (FinalizerDaemon)
01-16 10:59:55.460   386   386 W         : debuggerd: handling request: pid=22896 uid=10351 gid=10351 tid=22905
01-16 10:59:55.532 23207 23207 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-16 10:59:55.532 23207 23207 F DEBUG   : Build fingerprint: 'HUAWEI/WAS-LX1/HWWAS-H:7.0/HUAWEIWAS-LX1/C432B694:user/release-keys'
01-16 10:59:55.532 23207 23207 F DEBUG   : Revision: '0'
01-16 10:59:55.532 23207 23207 F DEBUG   : ABI: 'arm64'
01-16 10:59:55.532 23207 23207 F DEBUG   : pid: 22896, tid: 22905, name: FinalizerDaemon  >>> org.linphone <<<
01-16 10:59:55.532 23207 23207 F DEBUG   : signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0x3d65646f6d203b
01-16 10:59:55.532 23207 23207 F DEBUG   :     x0   0000007bc6cad4c0  x1   0000007ba727e340  x2   0000007ba7200000  x3   0000000000000006
01-16 10:59:55.532 23207 23207 F DEBUG   :     x4   000000000000007e  x5   0000007bc4a30b23  x6   0000000000000001  x7   0000000000000000
01-16 10:59:55.532 23207 23207 F DEBUG   :     x8   413d65646f6d203b  x9   0000007bb6e4a388  x10  000000000000007e  x11  0000000000000000
01-16 10:59:55.532 23207 23207 F DEBUG   :     x12  00000000000000c4  x13  000000000000005e  x14  0000007bb8a7f2f0  x15  de77b4c7f74223b3
01-16 10:59:55.532 23207 23207 F DEBUG   :     x16  0000007ba8ebd728  x17  0000007ba8a0387c  x18  00000000ffffffff  x19  0000007bc6cad4c0
01-16 10:59:55.532 23207 23207 F DEBUG   :     x20  0000007ba8ec8958  x21  0000007bc6cd1e00  x22  0000007bc53408ec  x23  0000007bc4a30b23
01-16 10:59:55.532 23207 23207 F DEBUG   :     x24  000000000000000c  x25  a295ff4449fc72cb  x26  0000007bc6cd1e98  x27  a295ff4449fc72cb
01-16 10:59:55.532 23207 23207 F DEBUG   :     x28  0000000000000003  x29  0000007bc53405f0  x30  0000007ba8a037f8
01-16 10:59:55.532 23207 23207 F DEBUG   :     sp   0000007bc53405e0  pc   003d65646f6d203b  pstate 0000000020000000
01-16 10:59:55.536 23207 23207 F DEBUG   : 
01-16 10:59:55.536 23207 23207 F DEBUG   : backtrace:
01-16 10:59:55.536 23207 23207 F DEBUG   :     #00 pc 003d65646f6d203b  <unknown>
01-16 10:59:55.536 23207 23207 F DEBUG   :     #01 pc 00000000003687f4  /data/app/org.linphone-1/lib/arm64/liblinphone.so
01-16 10:59:55.536 23207 23207 F DEBUG   :     #02 pc 00000000003fe06c  /data/app/org.linphone-1/lib/arm64/liblinphone.so (belle_sip_object_delete+176)
01-16 10:59:55.536 23207 23207 F DEBUG   :     #03 pc 000000000030c2b8  /data/app/org.linphone-1/oat/arm64/base.odex (offset 0x2d0000)
01-16 10:59:55.705  1188  1188 I QosMonitor: queryRtt: rtt_type = 3
01-16 10:59:55.705  1188  1188 I WifiProJNI: ######### GET RTT:3 ########

The same crash/error also happens when you try to login using a remote provisioning URL for Google Pixel 2 XL and Huawei P10 lite models **with correct credentials**!!!!
The error seems to happen when the linphone core is restarted and the crash with the debug option turned on is : 

--------- beginning of crash
01-09 11:03:18.455  8462  8472 F libc    : Fatal signal 7 (SIGBUS), code 1, fault addr 0x3d65646f6d203b in tid 8472 (FinalizerDaemon)
01-09 11:03:18.546  9241  9241 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-09 11:03:18.546  9241  9241 F DEBUG   : Build fingerprint: 'HUAWEI/WAS-LX1/HWWAS-H:7.0/HUAWEIWAS-LX1/C432B692:user/release-keys'
01-09 11:03:18.546  9241  9241 F DEBUG   : Revision: '0'
01-09 11:03:18.546  9241  9241 F DEBUG   : ABI: 'arm64'
01-09 11:03:18.546  9241  9241 F DEBUG   : pid: 8462, tid: 8472, name: FinalizerDaemon  >>> com.myapp.softphone <<<
01-09 11:03:18.546  9241  9241 F DEBUG   : signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0x3d65646f6d203b
01-09 11:03:18.546  9241  9241 F DEBUG   :     x0   000000743d6ac880  x1   000000741efe3a40  x2   000000741ee00000  x3   0000000000000006
01-09 11:03:18.547  9241  9241 F DEBUG   :     x4   00000000000001e3  x5   000000743547ff6a  x6   0000000000000001  x7   0000000000000000
01-09 11:03:18.547  9241  9241 F DEBUG   :     x8   413d65646f6d203b  x9   000000743d67cf88  x10  00000000000001e3  x11  0000000000000000
01-09 11:03:18.547  9241  9241 F DEBUG   :     x12  00000000000000c4  x13  000000000000004f  x14  0000007441139310  x15  f5cc4c44de354dc5
01-09 11:03:18.547  9241  9241 F DEBUG   :     x16  000000741dd30e80  x17  000000741d2b9f30  x18  00000000ffffffff  x19  000000743d6a2e00
01-09 11:03:18.547  9241  9241 F DEBUG   :     x20  000000743c4eb6d0  x21  000000743d6a2e00  x22  000000743bd438ec  x23  000000743547ff6a
01-09 11:03:18.547  9241  9241 F DEBUG   :     x24  000000000000000c  x25  7850437e25e01813  x26  000000743d6a2e98  x27  7850437e25e01813
01-09 11:03:18.547  9241  9241 F DEBUG   :     x28  0000000000000003  x29  000000743bd43580  x30  000000741d2b9d40
01-09 11:03:18.547  9241  9241 F DEBUG   :     sp   000000743bd43560  pc   003d65646f6d203b  pstate 0000000020000000
01-09 11:03:18.560  9241  9241 F DEBUG   : 
01-09 11:03:18.560  9241  9241 F DEBUG   : backtrace:
01-09 11:03:18.560  9241  9241 F DEBUG   :     #00 pc 003d65646f6d203b  <unknown>
01-09 11:03:18.560  9241  9241 F DEBUG   :     #01 pc 0000000000accd3c  /data/app/com.myapp.softphone-1/lib/arm64/liblinphone.so
01-09 11:03:18.560  9241  9241 F DEBUG   :     #02 pc 0000000000be5f50  /data/app/com.myapp.softphone-1/lib/arm64/liblinphone.so (belle_sip_object_delete+116)
01-09 11:03:18.560  9241  9241 F DEBUG   :     #03 pc 0000000000be5d54  /data/app/com.myapp.softphone-1/lib/arm64/liblinphone.so (belle_sip_object_unref+416)
01-09 11:03:18.560  9241  9241 F DEBUG   :     #04 pc 0000000000ac9d64  /data/app/com.myapp.softphone-1/lib/arm64/liblinphone.so (linphone_account_creator_unref+20)
01-09 11:03:18.560  9241  9241 F DEBUG   :     #05 pc 0000000000b78fbc  /data/app/com.myapp.softphone-1/lib/arm64/liblinphone.so (Java_org_linphone_core_LinphoneAccountCreatorImpl_unref+52)
01-09 11:03:18.560  9241  9241 F DEBUG   :     #06 pc 000000000031b2f8  /data/app/com.myapp.softphone-1/oat/arm64/base.odex (offset 0x2d5000)

The same behaviour is noticed for those two mobile models when I change the linphoneLoginFragment.java so that inside linphoneLogIn() instead of just calling accountCreator.isAccountUsed() we set the provisioning url, restart the core, set a listener and then calling isAccountUsed() function.
It is practically a 3 line code so I suspect that the problem is there. Probably a race condition??

Did anyone else had the same issue? Any suggestions on how it could be fixed?

I attach the log with the linphone official app crash. The crash appears at 10:59:55.459 time 

Best Regards.
[linphone_log.txt](https://github.com/BelledonneCommunications/linphone-android/files/1634901/linphone_log.txt)

**Comment by astuter** [comment]
I am also facing this issue while using Remote provisioning.

**Comment by TestWts2017** [comment]
@Koutoulakis Any solution?

**Comment by Koutoulakis** [comment]
Nop. Just hacks to obfuscate the problem.
