### ISSUE TITLE
Stopping a call while having an incoming call doesn't update the current call

### ISSUE THREAD

**Issue by mvdhorstclb** [BelledonneCommunications/linphone-android#1894]
Hi! The new UI looks great, but we found an issue in it.

1. **Describe the bug** (mandatory)

When on a call and a new call is incoming, after hanging up the first call, the UI doesn't update correctly.
Reproduced with the latest version from the Play Store.

**If the issue is about the SDK (build, issue, etc...) open the ticket in the [linphone-sdk](https://github.com/BelledonneCommunications/linphone-sdk) repository or one of it's submodules!**
Maybe the issue is in the core, because the current call isn't updated, therefor not the correct screen is shown.

2. **To Reproduce** (mandatory)

Call another number (B) with phone A.
Call phone A with C.
Hangup the call to B.

Expected: The accept/decline buttons appear
Actual, the call screen remains as is.

4. **Please complete the following information** (mandatory)

 - Device: Samsung XCover 5
 - OS: Android 12
 - Version of the App 5.0.8
 - Version of the SDK 5.2.37
 - Where you did got it from Play Store, also local build

5. **SDK logs** (mandatory)

https://www.linphone.org:444//tmp/642bcf31455d7_d09f655d3e911bcdf897.gz

In case of a call issue, please attach logs from both devices!

6. **Adb logcat logs** (mandatory if native crash)

[linphone_wrong_screen.zip](https://github.com/BelledonneCommunications/linphone-android/files/11145758/linphone_wrong_screen.zip)

https://user-images.githubusercontent.com/9461671/229718507-dea8cfb3-8fd9-4734-af90-60edb4b50a00.mp4

**Comment by Viish** [comment]
Fixed in 88f6d1bd for release/5.0 branch and b1b42638 for master branch.
