### ISSUE TITLE
503  IO error

### ISSUE THREAD

**Issue by August1023** [BelledonneCommunications/linphone-android#1896]
Hi,
    After more than ten seconds of the call, the 503 status code is returned with the message 'IO error'. May I ask why this is?

**Comment by August1023** [comment]
"ErrorPhrase" is "Media lost".

**Comment by Viish** [comment]
Hi,

Please attach logs showing the issue.

**Comment by Viish** [comment]
Why did you close the issue?

**Comment by August1023** [comment]
> Why did you close the issue?

Because I am unable to provide the log at the moment, I would like to open it later.
