### ISSUE TITLE
Frequent calls leading to program exit and restart

### ISSUE THREAD

**Issue by August1023** [BelledonneCommunications/linphone-android#1897]
Hi,
Frequent calls leading to program exit and restart. This is the log.
[log .txt](https://github.com/BelledonneCommunications/linphone-android/files/11188014/log.txt)

**Comment by Viish** [comment]
Hi,

Please attach more logs than that and the SDK version you are using.

**Comment by Viish** [comment]
Why did you close the issue?

**Comment by August1023** [comment]
> Why did you close the issue?

Because I am unable to provide the log at the moment, I would like to open it later.
