### ISSUE TITLE
IncomingCall has no video in mobile network

### ISSUE THREAD

**Issue by dante198406** [BelledonneCommunications/linphone-android#1898]
Hi,
I hava a problem with sdk 3.2.5 aar
It's normal in wifi network,but no video in mobile network.I have tried latest sdk 5.+ aar on 6 android devices,but still not work,
Please give some help,Thanks!

[log.zip](https://github.com/BelledonneCommunications/linphone-android/files/11196829/log.zip)

**Comment by Viish** [comment]
Hi,

It simply is a network issue. 
Try to enable ICE, it may fix your issue.
Another possible solution would be to use TCP (or TLS) instead of UDP.

Cheers,

**Comment by dante198406** [comment]
I'll try it.
Thanks
