### ISSUE TITLE
100rel not working correctly

### ISSUE THREAD

**Issue by dabhi86** [BelledonneCommunications/linphone-android#1899]
Hi Team Linphone,

My android app does not receive Early Media video, it only shows black screen. After speaking to my SIP service, they have enabled 100Rel for my account. Can you please suggest how I can enable it in Linphone SDK?

Your help is much appreciated.

Regards

**Comment by Viish** [comment]
Hi,

You can use https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Core.html#setTag100RelSupportLevel-org.linphone.core.SupportLevel-

Cheers,
