### ISSUE TITLE
NO video display

### ISSUE THREAD

**Issue by andy9100** [BelledonneCommunications/linphone-android#190]
I run linphone-android on Android 5.1.1,  linphone 4.1 on windows,  set 720P video call, can see video on windows, but no video on android. I using android studio from logcat getting following message:
01-01 14:09:50.245 1455-2426/org.linphone W/System.err: java.lang.IllegalArgumentException: Bad limit (capacity 1843200): 2073600
01-01 14:09:50.245 1455-2426/org.linphone W/System.err:     at java.nio.Buffer.limit(Buffer.java:298)
01-01 14:09:50.245 1455-2426/org.linphone W/System.err:     at android.media.MediaCodec$MediaImage.<init>(MediaCodec.java:1824)
01-01 14:09:50.245 1455-2426/org.linphone W/System.err:     at android.media.MediaCodec.getImage(Native Method)
01-01 14:09:50.245 1455-2426/org.linphone W/System.err:     at android.media.MediaCodec.getOutputImage(MediaCodec.java:1511)

the same version linphone-android works well on android 6.0
I tested this using linphone-lasted.apk download from linphone.org. and compile from version 3.3.1. the problem is same.

**Comment by Viish** [comment]
Should work with latest version
