### ISSUE TITLE
Set local_preview_texture to invisible,incoming video call has no video in mobile network,but normal in wifi network

### ISSUE THREAD

**Issue by dante198406** [BelledonneCommunications/linphone-android#1903]
Hi,
I set local_preview_texture to invisible,incoming video call has no video in mobile network,but normal in wifi network.
I don't need local preview,so I change it's visibility,then problem occurs as mentioned above.
I have tried  sdk from 2.3.5 to 5.+,all same results.
Why did this result occur？
Please help to check it,thanks,

Device: pixel 3
OS: Android 12

**Comment by Viish** [comment]
Duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/1898

**Comment by Viish** [comment]
If you still have the issue and need help, please continue the conversation on the original ticket, even if it is closed.

**Comment by dante198406** [comment]
Sorry for that，I found it's not just a network issue,so strange，and I'll continue the conversation on #1898.
Tanks a lot
