### ISSUE TITLE
Conference call, Received video is stretched

### ISSUE THREAD

**Issue by snower0428** [BelledonneCommunications/linphone-android#1907]
Hi, Viish:

In Conference call, the received call video is stretched.
Attatch is Log and Video, please help me. Thank you!

[64449dc0185df_bd2c069ec35c6f48351f.gz](https://github.com/BelledonneCommunications/linphone-android/files/11302737/64449dc0185df_bd2c069ec35c6f48351f.gz)

https://user-images.githubusercontent.com/2927386/233817233-19999ff2-9fe0-4063-ad41-7f2adc866011.mp4

**Comment by Viish** [comment]
Hi,

Can you send the other device logs as well please?

Thanks in advance.

**Comment by snower0428** [comment]
https://www.linphone.org:444//tmp/6445e9039c976_3e2d6cdc7b698d9e990f.gz

https://www.linphone.org:444//tmp/6445eac8b4378_031fd6e1e7fc2adc9aef.gz

Above is the other two devices logs, please help to take a look.
Thanks in advance.

1.
Device: MI9
Android version: 11

2.
Device: HUAWEI MatePad Pro
Harmony OS version: 3.0.0

**Comment by Viish** [comment]
Please reproduce the issue using linphone app and not your own fork, and specify which of the two files has the stretching issue.

**Comment by snower0428** [comment]
https://www.linphone.org:444//tmp/644636fbdc2fe_296416d3c1a032fc1fa8.gz

I reproduce the issue use linphone app, and above is linphone app's log.
Linphone SDK is 5.2.4
Please refer to the attached video.

https://user-images.githubusercontent.com/2927386/233935776-3863c97d-61d2-4104-98e5-b14543171def.mp4

**Comment by Viish** [comment]
Why do you stick to 5.2.4 SDK? 
Why not using 5.2.51 (currently the latest one)?

**Comment by Viish** [comment]
By the way, it seems the issues comes from your video server, as your device sends 640x480 video but receives 1280x720
