### ISSUE TITLE
Call log statuses/icons fine grained (enhancement)

### ISSUE THREAD

**Issue by osering** [BelledonneCommunications/linphone-android#1915]
Hi!

There are 6 possible outcomes of voice calls:

Outgoing:
(1) Answered
(2) Missed / Not answered
(3) Rejected/Dropped/Dismissed

Incoming:
(4) Answered
(5) Missed / Not answered
(6) Rejected/Dropped/Dismissed

These are usually shown by small icons (colored arrows, straight or broken) in most dialers' "Call log".

In Linphone (Linux version as well) so far noticed just 3 types (not 6) of icons: 
1) **blue** arrow for all 3 types of outgoing
2) **green** arrow for all 3 types of incoming.
3) **red** cross - in some cases (quite seldom). As it does not show direction, it is hard to intuitively understand, does it indicate incoming or outgoing call status. Probably better option would be broken arrow like here:
![incoming_missed](https://github.com/BelledonneCommunications/linphone-android/assets/62410690/f1e08e4d-b8de-4a50-b263-41699d87fad2)

### **Why not to design Linphones' call log more fine grained and effective?**
Technically it should not be too hard to differentiate these 6 conditions (even closed source Zoiper has it more advanced right now).

For example, so call log looks like in True Dialer (Android, com.hb.dialer.free):
![truephone](https://github.com/BelledonneCommunications/linphone-android/assets/62410690/8f94d570-2b82-4bfe-9e42-8bb9d8b832f4)

**Comment by Viish** [comment]
Hi,

Indeed we only show outgoing / incoming arrows & the red cross for missed incoming calls.
I keep in mind your suggestions, we are working on the new design of the applications (mobile & desktop) with our UI/UX agency, so the timing is perfect.

Cheers,

**Comment by Viish** [comment]
Hi,

I'm closing this issue as it is already solved in 6.0 version currently under development.

Cheers,

**Comment by osering** [comment]
Great!!!
It's delight to have such responsive open-source project developers. Cheers!
