### ISSUE TITLE
Problem with activating a private chat

### ISSUE THREAD

**Issue by Skretch1974** [BelledonneCommunications/linphone-android#1916]
Hi.

The app suddenly lost the ability to enable secret chat on one of the contacts. Earlier everything worked with this contact, reinstalling the application for this contact did not solve the problem. Calls with ZRTP authentication go without problems, also open chat, everything works. How can I clear the cache of this particular contact, as I assume it is a problem with the keys? I use linphone-android-debug-5.1.0-beta.23+8397debb0.apk, the phone is Android 12.1 with custom firmware.

**Comment by Viish** [comment]
Hi,

Please attach logs showing the issue.

**Comment by Viish** [comment]
Closing until logs are provided.
