### ISSUE TITLE
Peer to Peer Voice Call without SIP registering to SIP Server.

### ISSUE THREAD

**Issue by shivbuyya** [BelledonneCommunications/linphone-android#1917]
Hi,

I am trying to test voice call between two Android mobiles peer to peer, without registering to SIP server.

I have connected both the phones to same WiFi Router, DeviceA-IP: 192.168.1.9 and DeviceB-IP: 192.168.1.10.

I am trying to call from DeviceA to DeviceB by dialling  **sip:Test@192.168.1.10** but the call  is not landing on DeviceB. I have also tried by dialling  **sip:Test@192.168.1.10;transport=TCP**, but call not landing.

The same way when I try to establish call on Windows PC's without registering to SIP Server it is working.

Kindly suggest how to do peer to peer calls?

P.S: I have tried everything suggested in this issue: https://github.com/BelledonneCommunications/linphone-android/issues/1049

**Comment by Viish** [comment]
Hi,

First check that random port setting is disabled, otherwise you'll have to specify the port in the SIP URI you dial.

If it still doesn't work, please attach logs.

Cheers,

**Comment by shivbuyya** [comment]
@Viish, thanks for the response. You are right by default **Use random ports** was enabled. 

I have done following changes to resolve the issue in Linphone Android Version 5.0.11 release:
1. Disabled  the option **Use random ports** from Settings->Network. 
2. Disabled the option **Allow IPv6** from Settings->Network. 

With the above changes I could make voice call/video calls. But In case of chat messages, I have observed a bug that only notifications of message received are shown but no message thread is created in Chat window.

**Comment by Viish** [comment]
For the chat issue, toggle off the last two toggle settings in the chat section of the parameters

**Comment by shivbuyya** [comment]
Thanks, Chats are visible after disabling chat options (Hide empty chat rooms and Hide chat rooms from removed proxy configs).

How to transfer files, peer to peer through chat attach option?

is it possible to have peer to peer Video conferencing?

**Comment by Viish** [comment]
We don't currently support peer to peer file transfer, they have to be uploaded to a file transfer server. 
We support local audio conferencing (via call merging) but not video.
