### ISSUE TITLE
core.setOutputAudioDevice doesn't work

### ISSUE THREAD

**Issue by happyfsyy** [BelledonneCommunications/linphone-android#1918]
Hello, I just started using this SDK on the Android system. My Android device has a USB interface, and I plugged in a USB headset. I followed the instructions on this webpage to conduct an test: https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Audio%20devices/. 

Now I am trying to call core.setOutputAudioDevice() method to change the output device to the USB headset, but it doesn't work. Also, the onAudioDeviceChanged(core, audioDevice) callback is not triggered.

Here is my code and log

```kotlin
private fun changeInputOutputDevices(){
        factory=Factory.instance()
        core=factory.createCore(null,null,this)
        val audioDeviceList=core.extendedAudioDevices
        Log.e(tag,"list.size = ${audioDeviceList.size}")

        var usbOutputDevice:AudioDevice?=null
        for(audioDevice in audioDeviceList){
            Log.e(tag,"deviceName：${audioDevice?.deviceName},driverName：${audioDevice?.driverName}," +
                    "id：${audioDevice?.id},type：${audioDevice?.type},capabilities：${audioDevice?.capabilities}")
            if(audioDevice.type==AudioDevice.Type.Headset && audioDevice.capabilities==AudioDevice.Capabilities.CapabilityPlay){
                usbOutputDevice=audioDevice
            }
        }
        if(usbOutputDevice==null){
            Log.e(tag,"usbOutputDevice is null")
        }else{
            Log.e(tag,"usbOutputDevice is not null")
        }
        core.outputAudioDevice=usbOutputDevice
    }
```
![log](https://github.com/BelledonneCommunications/linphone-android/assets/8224607/8eecd2dd-f00a-4e7c-ac1c-374ba0723668)

**In Addtion, my Android device is not a phone , it's a dispatching desk on Android 11.**

**Comment by happyfsyy** [comment]
What's even more serious is that I connected a Bluetooth headset to my device, and then called core.getExtendedAudioDevices(), but it did not recognize the Bluetooth headset.

**Comment by Viish** [comment]
Hi, 

A couple of things :
- your Core isn't started yet, and I recommend you to start it before doing changes such as this
- as you may have seen, extended audio devices list contains AAudio devices as well as OpenSLES ones. However setting USB audio device with OpenSLES devices won't work, so you have to check the driver used is AAudio.
- your code doesn't set a CoreListener so that's why the call back isn't notified.
- how do you test the output device works ?

Regarding Bluetooth it should work fine (OpenSLES or AAudio). Can you attach full SDK logs ? Have you tried with our linphone-android app on your device ? It is possible it has a firmware issue and thus a bad AAudio support.

Cheers,

**Comment by happyfsyy** [comment]
> Hi,
> 
> A couple of things :
> 
> * your Core isn't started yet, and I recommend you to start it before doing changes such as this
> * as you may have seen, extended audio devices list contains AAudio devices as well as OpenSLES ones. However setting USB audio device with OpenSLES devices won't work, so you have to check the driver used is AAudio.
> * your code doesn't set a CoreListener so that's why the call back isn't notified.
> * how do you test the output device works ?
> 
> Regarding Bluetooth it should work fine (OpenSLES or AAudio). Can you attach full SDK logs ? Have you tried with our linphone-android app on your device ? It is possible it has a firmware issue and thus a bad AAudio support.
> 
> Cheers,

I'm sorry that the code I pasted was incomplete. I did call core.start(), but because my code is too long, about 300 lines, I deliberately copied the initialization of factory and core into the changeInputOutputDevices() method.

I am sure that I have called the core.start() method. I have also set up the coreListener and overridden the onAudioDeviceChanged() method, but it was not called.

I have tested in two ways:

When receiving a call, I called call.setOutputAudioDevice() method, but the sound did not switch from the handset to the USB headset.
In the event of a button , I called the changeInputOutputDevices() method, and then called core.getOutputAudioDevice() in the event of another button, but the result was null.

**Comment by happyfsyy** [comment]
Based on the log provided earlier, it seems that the driver for this USB device is AAudio.

**Comment by Viish** [comment]
Please enable our SDK logs and attach them:
```
Factory.instance().setLogCollectionPath(context.filesDir.absolutePath)
Factory.instance().enableLogCollection(LogCollectionState.Enabled)
Factory.instance().setLoggerDomain(appName)
Factory.instance().enableLogcatLogs(true)
Factory.instance().loggingService.setLogLevel(LogLevel.Message)
```

**Comment by happyfsyy** [comment]
Hi, @Viish 
I just tried again, but it still doesn't work. I mainly clicked the button three times. 

1. The first time, I clicked Button 1 and executed getInputOutputDevices(), which checked the current input and output devices. The specific code and log are as follows:
```kotlin
private fun getInputOutputDevices(){
    val defaultInputAudioDevice=core.defaultInputAudioDevice
    val defaultOutputAudioDevice=core.defaultOutputAudioDevice
    val currentInputAudioDevice=core.inputAudioDevice
    val currentOutputAudioDevice=core.outputAudioDevice
    printDeviceLog(defaultInputAudioDevice,"defaultInputAudioDevice ")
    printDeviceLog(defaultOutputAudioDevice,"defaultOutputAudioDevice ")
    printDeviceLog(currentInputAudioDevice,"currentInputAudioDevice ")
    printDeviceLog(currentOutputAudioDevice,"currentOutputAudioDevice ")
}
```
![log1](https://github.com/BelledonneCommunications/linphone-android/assets/8224607/d3975b54-56a6-436f-b409-86e4833a4112)


2. Then I clicked Button 2 and executed changeInputOutputDevices() mentioned earlier. The specific code and log are as follows:
```kotlin
 private fun changeInputOutputDevices(){
    val audioDeviceList=core.extendedAudioDevices
    Log.e(tag,"audioDeviceList.size：${audioDeviceList.size}")

    var usbOutputDevice:AudioDevice?=null
    for(audioDevice in audioDeviceList){
        Log.e(tag,"deviceName：${audioDevice?.deviceName},driverName：${audioDevice?.driverName}," +
                "id：${audioDevice?.id},type：${audioDevice?.type},capabilities：${audioDevice?.capabilities}")
        if(audioDevice.type==AudioDevice.Type.Headset && audioDevice.capabilities==AudioDevice.Capabilities.CapabilityPlay){
            usbOutputDevice=audioDevice
        }
    }
    if(usbOutputDevice==null){
        Log.e(tag,"usbOutputDevice is null")
    }else{
        Log.e(tag,"usbOutputDevice is not null")
    }
    core.outputAudioDevice=usbOutputDevice
}
```

![log2](https://github.com/BelledonneCommunications/linphone-android/assets/8224607/cd05cb0c-d92e-454f-944c-aeb562b88afb)


3. Finally, I clicked Button 1 again and re-executed getInputOutputDevices() method. The specific log is as follows:

![log3](https://github.com/BelledonneCommunications/linphone-android/assets/8224607/b701509c-bbe9-445d-aad8-0b7aad9b419a)

If you want to see the LinPhone log, you can start from 16:03 on May 19, 2023. Thank you for your guidance.

I'm sorry, my boss took away my previous USB headset, and this headset is different from the previous one, but don't worry about these details. Also, we don't need to worry about the Bluetooth headset issue. Right now, my main concern is why setOutputAudioDevice() is not working

**Comment by happyfsyy** [comment]
@Viish It seems like I just solved the problem. I'm not sure how it happened, but I apologize for the disturbance. I will test it again later, and if it works, I will close this issue on my own.

**Comment by happyfsyy** [comment]
```kotlin
private fun toggleSpeaker() {
  
        val currentAudioDevice = core.currentCall?.outputAudioDevice
        val speakerEnabled = currentAudioDevice?.type == AudioDevice.Type.Speaker

        for (audioDevice in core.audioDevices) {
            if (speakerEnabled && audioDevice.type == AudioDevice.Type.Earpiece) {
                core.currentCall?.outputAudioDevice = audioDevice
                return
            } else if (!speakerEnabled && audioDevice.type == AudioDevice.Type.Speaker) {
                core.currentCall?.outputAudioDevice = audioDevice
                return
            }
        }
    }
```
That's the code , I just changed **for (audioDevice in core.audioDevices)**  to **for (audioDevice in core.extendAudioDevices)**, then it works. But I don't know why.

**Comment by Viish** [comment]
Setting the output audio device in the Core merely change the default value, and if there is a call already it doesn't apply the change for it.
The best way to change the audio device for a call is to call call.setOutputAudioDevice

**Comment by happyfsyy** [comment]
> Setting the output audio device in the Core merely change the default value, and if there is a call already it doesn't apply the change for it. The best way to change the audio device for a call is to call call.setOutputAudioDevice

@Viish  I did call call.setOutputDevice(audioDevice), but it didn't work. Finally, I found out that the issue was with the audioDevice parameter. 
If audioDevice comes from core.getAudioDevices(), it won't work. However, if audioDevice comes from core.getExtendedAudioDevices(), it works.
```kotlin
for (audioDevice in core.audioDevices)
for(audioDevice in core.extendedAudioDevices)
```

**Comment by Viish** [comment]
Hum, that's weird, I'll check.

**Comment by pavan-jaju** [comment]
Any update on this. As of now I am able to have the headset working properly with `extendedAudioDevices` but bluetooth is not working.

Also if headset or bluetooth is connected before start of the call, then only they start appearing in the return value of audioDevices. 

Also switching to bluetooth device only works when device is connected before app starts, if we try to connect it later, switching to bluetooth does not work.

**Comment by gaoruiqing187** [comment]
I had the same problem。When I connect to Bluetooth before a call, the first call will go to the speaker and the second call will go to Bluetooth。
private void changeInputOutputDevices(){
        core.reloadSoundDevices();
        List<AudioDevice> AudioDevices = Arrays.asList(core.getExtendedAudioDevices());
        AudioDevice inOutputDevice = null;
        Log.e(TAG, "before == currentInputDevice: " + core.getDefaultInputAudioDevice().getType());
        Log.e(TAG, "before == currentOutDevice: " + core.getDefaultOutputAudioDevice().getType());
        AudioDeviceInfo[] inAudioDevices = audioManager.getDevices(AudioManager.GET_DEVICES_INPUTS);
        for (AudioDeviceInfo device : inAudioDevices) {
            if (device.getType() == AudioDeviceInfo.TYPE_WIRED_HEADPHONES || device.getType() == AudioDeviceInfo.TYPE_WIRED_HEADSET) {
                // 有线耳机或有线耳麦
                Log.d(TAG, "当前输出设备为有线耳机或有线耳麦");
                audioManager.setWiredHeadsetOn(true);
                break;
            } else if (device.getType() == AudioDeviceInfo.TYPE_BLUETOOTH_SCO || device.getType() == AudioDeviceInfo.TYPE_BLUETOOTH_A2DP) {
                // 蓝牙耳机或蓝牙音频设备
                Log.d(TAG, "当前输出设备为蓝牙耳机或蓝牙音频设备");
                audioManager.setBluetoothScoOn(true);
                break;
            }
        }

        for(AudioDevice audioDevice : AudioDevices){
            Log.e(TAG, "deviceName：" + audioDevice.getDeviceName() + ", driverName：" + audioDevice.getDriverName() +
                    ", id：" + audioDevice.getId() + ", type：" + audioDevice.getType() + ", capabilities：" + audioDevice.getCapabilities());
            if(audioDevice.getType()==AudioDevice.Type.Headset && audioDevice.getCapabilities()==AudioDevice.Capabilities.CapabilityAll){
                inOutputDevice=audioDevice;
                break;
            } else if (audioDevice.getType() == AudioDevice.Type.Bluetooth && audioDevice.getCapabilities()==AudioDevice.Capabilities.CapabilityAll) {
                inOutputDevice=audioDevice;
                break;
            }
        }
        if(inOutputDevice==null){
            Log.e(TAG,"usbOutputDevice is null");
        }else{
            Log.e(TAG,"usbOutputDevice is not null: type === " + inOutputDevice.getType() + " name === " + inOutputDevice.getDeviceName());
            core.setDefaultOutputAudioDevice(inOutputDevice);
        }
        Log.e(TAG, "after == currentInputDevice: " + core.getDefaultInputAudioDevice().getType());
        Log.e(TAG, "after == currentOutDevice: " + core.getDefaultOutputAudioDevice().getType());
    }
    this is my code，I don't know how to solve it。
