### ISSUE TITLE
MS_VIDEO_DECODER_DECODING_ERRORS: ERROR MediaCodecDecoder: missing parameter sets

### ISSUE THREAD

**Issue by RuslanFomin57** [BelledonneCommunications/linphone-android#1920]
Hi! At first i thought it was same [problem](https://github.com/BelledonneCommunications/linphone-android/issues/1665), but no. 
I call from intercom via sip server to my phone. 
Linphone SDK 5.2.57
Linphone android 5.0.11
The first second I see the video, then the video stops and changes one frame every 5-10 seconds. 
my [linphone_logs.txt](https://github.com/BelledonneCommunications/linphone-android/files/11533481/linphone_logs.txt)

**Comment by RuslanFomin57** [comment]
may be someone gives me an answer or talk with me

**Comment by RuslanFomin57** [comment]
i solved my issue

**Comment by agam-android7** [comment]
Hi @RuslanFomin57 ,

I am also getting same error.
Error: MediaCodecDecoder: missing parameter sets

so can you please explain about how did you solve it?
