### ISSUE TITLE
AudioSettingsFragment.initOutputAudioDevicesList() doesn't work correctly

### ISSUE THREAD

**Issue by happyfsyy** [BelledonneCommunications/linphone-android#1922]
Hello, I saw that your code supports up to Android 13. 
According to this link, https://source.android.com/docs/core/audio/combined-audio-routing, it should be possible to allow multiple USB headsets. 
Because my device is a dispatching machine with two USB ports, I need to use two SIP phones separately on each headset. 
To test it, I ran the code on a Raspberry Pi with Android 13 installed, but it didn't work. 
I plugged in two USB headsets, but Linphone-Android only recognized one USB headset. 
I looked at your code, and the specific code is as follows:
```kotlin
private fun initOutputAudioDevicesList() {
    val labels = arrayListOf<String>()
    val values = arrayListOf<AudioDevice>()
    var index = 0
    val default = core.defaultOutputAudioDevice

    for (audioDevice in core.extendedAudioDevices) {
        if (audioDevice.hasCapability(AudioDevice.Capabilities.CapabilityPlay)) {
            labels.add(audioDevice.id)
            values.add(audioDevice)
            if (audioDevice.id == default?.id) {
                outputAudioDeviceIndex.value = index
            }
            index += 1
        }
    }
    outputAudioDeviceLabels.value = labels
    outputAudioDeviceValues.value = values
}
```

**Comment by Viish** [comment]
Please attach debug logs from the app from the moment it starts.

**Comment by happyfsyy** [comment]
Hello，@Viish I uninstalled and reinstalled the LinePhone-Android client and went through the process again. 

1. First, I didn't connect any USB headsets, then I connected the first USB headset, and finally the second USB headset. 

2. When I connected the first USB headset, I could clearly see that a new device "USB-Audio-AB13X USB-Audio" was added to the default audio output device. 

3.  After connecting the second USB headset, the number of devices in the default audio output device did not change, and "USB-Audio-AB13X USB Audio" disappeared, replaced by "USB-Audio-Logi USBHeadset". 

Please see my log below:
[linphone1.log](https://github.com/BelledonneCommunications/linphone-android/files/11551961/linphone1.log)

**Comment by Viish** [comment]
Thanks.
Sadly I can't do much about this, it's Android that decides to left out the first headset and replaces it with the second one.

When you plug the new one, you can see Android detects the first one has been unplugged first:
```
2023-05-05 16:30:23:909 [org.linphone.debug/liblinphone] MESSAGE [ setInputAudioDeviceBySndCard ] on device: USB-Audio - AB13X USB Audio
2023-05-05 16:30:23:909 [org.linphone.debug/liblinphone] MESSAGE Linphone core [0x736ecb1a60] notified [audio_devices_list_updated]
2023-05-05 16:31:41:010 [org.linphone.debug/linphone-android] MESSAGE [Headset] Headset broadcast received
2023-05-05 16:31:41:010 [org.linphone.debug/linphone-android] MESSAGE [Headset] Headset disconnected: null
```

Note that in the SDK, we list all devices that Android APIs are returning with the log `[Audio Manager] Found device:` and you can see that at never both are listed.

Maybe that's an Android bug, maybe the multiple USB devices support isn't implemented in Raspberry's Android version, I can't tell, but it's worth reporting the issue on [https://issuetracker.google.com/](https://issuetracker.google.com/)
