### ISSUE TITLE
Delete default account 

### ISSUE THREAD

**Issue by Adnan-addi** [BelledonneCommunications/linphone-android#1924]
@Viish i am working on linphone-android 

i need to delete default account from outside the AccountSettingfragment
e.g some other fragment from sidemenu ...

is there any way i can delete default account outside the the setting fragment... or how can i achieve it ?

Thanks

**Comment by Viish** [comment]
Given our app no you can't remove it from outside of the AccountSettings fragment.
But using our APIs you can do that anywhere you wish.
