### ISSUE TITLE
New language addition

### ISSUE THREAD

**Issue by 2dengine** [BelledonneCommunications/linphone-android#1925]
I have completed a new language localization of the Android version of Linphone (see attached file):
[strings.txt](https://github.com/BelledonneCommunications/linphone-android/files/11612861/strings.txt)
I need to see my translation in-app in order to see the context in which the strings are used.

Also, in the English version we need to change:
    <string name="content_description_conference_participant_mic_muted">Participant has it\'s microphone muted</string>
...to the following:
    <string name="content_description_conference_participant_mic_muted">Participant has his or her microphone muted</string>

**Comment by Viish** [comment]
Hi,

To help translating linphone, please go to https://weblate.linphone.org/projects/linphone/

Thanks!

**Comment by Viish** [comment]
You can create it if it doesn't exists yet.

**Comment by 2dengine** [comment]
I managed to add my localization on Weblate, but the translation app is very primitive and does a full page reload when modifying each term. I could not find a setting to batch import the terms.
