### ISSUE TITLE
Display Actual Caller ID

### ISSUE THREAD

**Issue by llabusch93** [BelledonneCommunications/linphone-android#1927]
Greetings,

I'm currently encountering a specific issue when using Linphone with the Sipgate service (sip.sipgate.de). Specifically, when a group number is dialed (which is a common number used to simultaneously ring multiple employee phones), the caller ID that gets displayed is that of the group name, instead of the actual caller's ID. This poses a problem as it becomes difficult to identify the individual calling.

Interestingly, this issue seems to be unique to Linphone as when the same group number rings on our CRM system, the caller's ID is displayed correctly.

I also noticed that when I click on an entry within the call history (which is similarly named after the group number), I can see the actual caller's number written as `sip:<CALLER_NUMBER>@sipgate.de` .

Hence, my query is this: is there a way to modify the settings so that the actual caller's number is displayed during calls and also within the call history on Linphone?

Thank you for your time and assistance with this matter.

**Comment by Viish** [comment]
Hi, 

We use the information from the FROM header to display who has been calling.
In your system it seems the FROM is the group number and not the actual caller SIP URI.
Can you attach log so I can check if the information you seek is available and if yes under which header?

Cheers,

**Comment by llabusch93** [comment]
Hello @Viish,

Thank you very much for this prompt reply! I think the relevant part of the logs will be those (I replaced the sensitive information with *****:

```
From: "Labiso GmbH Zentrale" <sip:***********@sipgate.de>;tag=as71542b53
To: <sip:*******@sipgate.de>;tag=BHy4HDk
Call-ID: **************************@sipgate.de
CSeq: 105 BYE
User-Agent: LinphoneAndroid/5.0.12 (Pixel 7 Pro) LinphoneSDK/5.2.62 (tags/5.2.62^0)
Supported: replaces, outbound, gruu, path, record-aware
Content-Length: 0```

Especially: `From: "Labiso GmbH Zentrale" <sip:************@sipgate.de>;tag=as71542b53`

So, the FROM name is the group name. Is there a way to take what the actual address, so the actual number, is? If not, maybe a Regex option in the advanced settings for this could be helpful.

Cheers

**Comment by Viish** [comment]
Ok so the issue is the display name, what you would like to see is the ************ from <sip:************@sipgate.de>, is that right?

**Comment by llabusch93** [comment]
> Ok so the issue is the display name, what you would like to see is the ************ from sip:************@sipgate.de, is that right?

Hello @Viish 

Yes, that's correct.

**Comment by Viish** [comment]
Not so much I can do about it, the display name exists so the caller can tell how it wants to be displayed on the callee side.
Only way to override that is for you to add a contact with sip:************@sipgate.de SIP URI, so the name of the contact will be used instead of the display name of the FROM SIP URI.

**Comment by cjkarande** [comment]
@Viish , am also facing the same issue, is there a way to query the sip.linphone.org user database with sip address to retrieve the contacts Name?
This would be more like the TrueCaller App which queries its cloud DB to fetch the name associate with incoming TEL number

**Comment by Viish** [comment]
@cjkarande We don't store contact names in our database so no.

**Comment by quazgar** [comment]
I have the same problem with sipgate as VoIP provider.

Log for an incoming call:
```
From: "05...5" <sip:0123...789@sipgate.de>;tag=as12345678
To: <sip:123abcd@sipgate.de>
Contact: <sip:0123...789@123.45.67.89:5060>
```

- `05...5` is my voip number.
- `0123...789` is the calling number.
- `123abcd` is the customer account.

Consequently, my LinPhone on Android (6.0.18) shows this incoming call as "05...5" (my number) and only in the detail information, it says "sip:0123...789@sipgate.de" (the calling number).

Has anyone managed to configure their Sipgate account to not do this confusing mixup?

**Comment by Viish** [comment]
Hi @quazgar,

It's a bad idea from Sipgate to set your own number as the display name of the person calling you...
Our policy is to use that display name for identification purposes if no contact can be found using the SIP address.

**Comment by quazgar** [comment]
> Has anyone managed to configure their Sipgate account to not do this confusing mixup?

In Sipgate's settings of the receiving device, you can set "Rufnummernanzeige für einzeilige Displays" (display for one line devices).  This results in this header

```
From: "0123...789" <sip:0123...789@sipgate.de>;tag=as12345678
To: <sip:123abcd@sipgate.de>
Contact: <sip:0123...789@123.45.67.89:5060>
```

**Comment by Viish** [comment]
@quazgar that will fix your issue

**Comment by quazgar** [comment]
Yes, it does. I put it here as documentation for the future (myself and others).
