### ISSUE TITLE
Сall recording doesn't work with this SDK

### ISSUE THREAD

**Issue by tpov** [BelledonneCommunications/linphone-android#1928]
I built SDK with 729 codec, but call recording doesn't work with this build, is it because I didn't specify some build options? Or some other mistake?

**Comment by tpov** [comment]
> I built SDK with 729 codec, but call recording doesn't work with this build, is it because I didn't specify some build options? Or some other mistake?

$ cmake .. -DLINPHONESDK_PLATFORM:STRING=Android -DLINPHONESDK_ANDROID_ARCHS="arm64, armv7, x86_64, x86" -DENABLE_G729=YES -DENABLE_G729B_CNG=YES -DENABLE_VCARD=OFF -DENABLE_ILBC=OFF -DENABLE_SILK=OFF -DENABLE_ISAC=OFF -DENABLE_MKV=OFF -DENABLE_GSM=OFF -DENABLE_DOC=OFF -DENABLE_UNIT_TESTS=OFF -DENABLE_LIME=OFF -DENABLE_GPL_THIRD_PARTIES=OFF -DENABLE_NON_FREE_CODECS=OFF

**Comment by Viish** [comment]
Yes, it's because you disabled MKV feature.
Calls are recorded in .mkv files, even if there is only audio.
