### ISSUE TITLE
can't create in app account using assistant

### ISSUE THREAD

**Issue by rrr1164** [BelledonneCommunications/linphone-android#1930]
First of all, please say "Hi" or "Hello", it doesn't cost much.

1. **Describe the bug** (mandatory)
I'm trying to create an account using the assistant and I'm getting the error "your device doesn't support push notifications which is required for account creation"

Also, if applicable, **do you reproduce it with linphone-android latest release from the Play Store?**
No

logs: https://www.linphone.org:444//tmp/64821dc08b8aa_2c8fd9dd11dc677f626f.gz

**Comment by Viish** [comment]
Hi,

This means you are using the 5.1 beta version. And yes indeed, starting 5.1 release, we will only support in-app account creation for devices that supports push notifications as we are using them to ensure the request comes from a real device.
As you may have already seen, you can create your account online anyway: https://subscribe.linphone.org/

Cheers,

**Comment by rrr1164** [comment]
but my phone (redmi 9) does support push notifications

**Comment by Viish** [comment]
Your phone may support them, but if you are using a custom OS such as Lineage or if you built the app without push support you may not be able to receive them.

**Comment by Viish** [comment]
Sorry but no, I don't know about that specific FCM error.
Are you using our push certificate (google-service.json file) or yours?

**Comment by rrr1164** [comment]
I'm using your push certificate and I also tried with mine, they both give the same error logs

**Comment by Viish** [comment]
That's weird.
Anyway if FCM isn't properly setup, our app will believe push notifications aren't supported and thus you won't be able to create / connect phone account from the app directly.
Note that 5.1 beta you are using requires an account manager version that isn't currently deployed on our production server so it won't work anyway.

**Comment by eiheis** [comment]
> That's weird. Anyway if FCM isn't properly setup, our app will believe push notifications aren't supported and thus you won't be able to create / connect phone account from the app directly. Note that 5.1 beta you are using requires an account manager version that isn't currently deployed on our production server so it won't work anyway.

Hi Viish,
    I have same problem, could you please help me to solve it.
