### ISSUE TITLE
confirmation code not being sent to Saudi Arabia phone number

### ISSUE THREAD

**Issue by rrr1164** [BelledonneCommunications/linphone-android#1931]
First of all, please say "Hi" or "Hello", it doesn't cost much.

1. **Describe the bug** (mandatory)
when I use the assistant to create the account, I don't get a confirmation code on a Saudi phone number.

Also, if applicable, **do you reproduce it with linphone-android latest release from the Play Store?**
Yes

2. **To Reproduce** (mandatory)
use release 4.7, build the project using android studio and create an account using the assistant. use a Saudi phone number and wait for the confirmation code.

3. **Expected behavior** (mandatory)

a confirmation code should be sent 
4. **Please complete the following information** (mandatory)

 - Device: Xiaomi Redmi 9
 - OS: e.g. Android 10
 - Where you did got it from (Play Store, F-Droid, local build) play store 
 - Please tell us if your Android is a Lineage OS or another variant. not sure

If you are using a SDK that isn't the latest release, please update first as it's likely your issue is already solved.

5. **SDK logs** (mandatory)

Enable debug logs in advanced section of the settings, restart the app, reproduce the issue and then go back to advanced settings, click on "Send logs" and copy/paste the link here.

[It's also explained [in the README](https://github.com/BelledonneCommunications/linphone-android#behavior-issue).
](https://www.linphone.org:444//tmp/6482ed7a47262_40966d74f3f877309d31.gz)

**Comment by rrr1164** [comment]
any updates? I also tried with a US phone number and it didn't work

**Comment by rrr1164** [comment]
@Viish can you please look into it?

**Comment by Viish** [comment]
You have to be in the country the phone number is registered in for the SMS to be sent.

**Comment by rrr1164** [comment]
I live in Saudi Arabia and I didn't get the confirmation code

**Comment by Viish** [comment]
Can you send me your phone number please, so I can check in our webplatform logs ?

**Comment by rrr1164** [comment]
+966566778239
+966570719452
@Viish

**Comment by rrr1164** [comment]
what do you reckon is the solution then? try using another ISP?

**Comment by rrr1164** [comment]
I've tried using mobile data (virgin mobile) as ISP instead of wifi and I still don't get the code

**Comment by rrr1164** [comment]
@Viish i tried it on a third phone number +9665701051924 and I didn't get a confirmation code
