### ISSUE TITLE
The generic login process error

### ISSUE THREAD

**Issue by hohoiot** [BelledonneCommunications/linphone-android#1936]
Hello.

I saw the third party register issue in this community yesterday, but it was deleted.
I have the same problem as it.

When I try the generic login process, the app is crashed and ended.
Whether I use the linphone account or another account, it occurs the same.

I tested it at local build, but it is not reproduced at the latest release version from the Play Store.
I think it is a problem only at the linphone sdk sample source or because of my mistake at setting process.

 - Device: Samsung SM-A315N
 - OS: Android 12
 - Version of the App: 5.1.0
 - Version of the SDK : 5.3+
 - Local Build

**SDK logs** 

https://www.linphone.org:444//tmp/648ad7c81f3be_fb82b31ba65474693cbd.gz

**Screenshots**

![linphone_log](https://github.com/BelledonneCommunications/linphone-android/assets/61811415/60de9918-70a4-4c6d-b662-69de1ca885ee)

Thank you.

**Comment by Viish** [comment]
Hi,

I've just merged a fix for that crash in master branch of linphone-sdk.

Cheers,
