### ISSUE TITLE
unable to switch audio devices

### ISSUE THREAD

**Issue by avliet** [BelledonneCommunications/linphone-android#1937]
When a call is answered, switching to another audio device breaks outgoing audio.

For example, answering the phone on a Bluetooth headset, then attempting to switch to the built in speaker, results in no outgoing audio.  

It is not possible to switch back to the Bluetooth device to reconnect the outgoing audio either.  Once the call is answered, whatever audio device was used to answer the call must continue to be used for the duration of the call.

**Comment by Viish** [comment]
Hi,

Please follow bug report pattern and attach logs.
