### ISSUE TITLE
Do not open Linphone in foreground after a missed call

### ISSUE THREAD

**Issue by gleniu87** [BelledonneCommunications/linphone-android#1938]
Hello,

I would like to share a suggestion with you:

**Suggestion description**

It would be nice if the app didn't open after a missed call.

**Steps To Reproduce**

1. Go to the main launcher page (press home button) and turn the screen off.
2. Make a call from different phone.
3. The app shows that there is a call incoming.
4. Do not pick up the call. End it using phone that you are calling from.
5. Wait for the screen to turn off.
6. Unlock the phone.

**Actual behavior**

Linphone app is open in the foreground.

**Expected behavior**

The phone shows the screen that was active before turning the screen off in step 1 (main launcher page in that case). There is a missed call notification in notifications dropdown.

**Environment**

 - Device: Xiaomi Mi 9 Lite
 - OS: Android 13 (AlphaDroid custom ROM)
 - Version of the App: 5.0.13
 - Where you did got it from: Play Store

Thanks.

**Comment by Viish** [comment]
Hi,

Can you capture a video of the issue please and join matching debug logs?
This shouldn't happen and I don't reproduce it.

Cheers,
