### ISSUE TITLE
can't hear while a outbound call

### ISSUE THREAD

**Issue by happyfsyy** [BelledonneCommunications/linphone-android#1940]
Hello, I encountered a problem while using the Linphone SDK. I can make and receive calls with the SIP registered phone on the other end, and everything works fine. 
However, once the other phone turns on automatic answer or answers the call very quickly, the call will have issues. The other end can hear me, but I cannot hear them.

Also, I found another issue. When I click the hold button, I can suddenly hear the other end again. I don't know why this is happening and I need your help to solve it.

Here is my code for initiating a call:
```kotlin
val text=dialNumber.value!!
val serverAddress="192.168.8.223"
val remoteSipUri="sip:$text@$serverAddress"
val remoteAddress=Factory.instance().createAddress(remoteSipUri)
if(remoteAddress==null){
    errorMessage.value=MyApplication.mContext.resources.getString(R.string.call_error_wrong_number)
    return
}
val params=MyApplication.mCore.createCallParams(null)
params ?: return
params.mediaEncryption=MediaEncryption.None
MyApplication.mCore.inviteAddressWithParams(remoteAddress,params)
```

**Comment by happyfsyy** [comment]
I'm sorry, I missed a piece of information. 
My device's built-in speaker can hear the other end's voice messages, but when I use the call.setOutputAudioDevice() method to specify the output device to the headset, the headset cannot hear the other end's voice messages. 
However, when the other end calls me, I can hear their voice through the headset, and they can hear my voice as well.

**Comment by happyfsyy** [comment]
@Viish Thank you very much for your answer. However, why does this situation occur? I don't even know how to implement a send-only INVITE.

Is there something wrong with my code? Here is my code. How can I improve it?
```kotlin
val text=dialNumber.value!!
val serverAddress="192.168.8.223"
val remoteSipUri="sip:$text@$serverAddress"
val remoteAddress=Factory.instance().createAddress(remoteSipUri)
if(remoteAddress==null){
    errorMessage.value=MyApplication.mContext.resources.getString(R.string.call_error_wrong_number)
    return
}
val params=MyApplication.mCore.createCallParams(null)
params ?: return
params.mediaEncryption=MediaEncryption.None
MyApplication.mCore.inviteAddressWithParams(remoteAddress,params)
```

Also, I have a question. Why is there no problem when I use the device's built-in speaker, but there is a problem when I use a USB headset?

**Comment by happyfsyy** [comment]
Is this send-only INVITE achieved by clicking the hold button? I clicked the hold button twice after not hearing any sound. The first time I clicked it, the call was put on hold, and the second time I clicked it, the call was resumed and I could hear the other end's voice.

**Comment by happyfsyy** [comment]
Hello，
I don't know if it's related, but during the call, the log keeps printing this error message: "Error -32 during AudioTrack native read".

**Comment by happyfsyy** [comment]
Hello, @Viish 
So why does this happen? I can't only hear the other end's voice when they have auto-answer enabled. And this only happens with USB headsets, not with the built-in speaker.
 I have tried several different USB headsets, and they all have this issue.

**Comment by happyfsyy** [comment]
Also, I have noticed another error in the log: 
bctbx_file_open: Error opening '/data/user/0/com.example.shoueedemo/files/.linphone.ecstate': No such file or directory.

**Comment by happyfsyy** [comment]
Why does AudioTrack produce this error? 
I tried using another Android device, and even when the other end didn't have auto-answer enabled, the call audio was played through the built-in speaker instead of the USB headset speaker.
I am sure that I called the setOutputAudioDevice() method before this, and in the onCallStateChanged() callback, when it was OutgoingInit, I called the call.getOutputAudioDevice() method. The log clearly shows that the current audio output device for the call is the USB Headset. 
However, the voice of the other end is still played through the built-in speaker of this device.

**Comment by happyfsyy** [comment]
I'm not sure if there's a problem with my code, because I only need to save local users, so when creating the Core object, I didn't use CorePreferences in Linphone-Android, I just created a Config object. Here's my code:
```kotlin
val configPath= mContext.filesDir.absolutePath+"/linphone_config_path"
val factoryPath= mContext.filesDir.absolutePath+"/linphone_factory_path0"
mConfig= Factory.instance().createConfigWithFactory(configPath,factoryPath)
mCore=Factory.instance().createCoreWithConfig(mConfig,this)
mCore.addListener(listener)
mCore.start()
```

**Comment by happyfsyy** [comment]
Also, I found a log with an exception that occurred between Connected and StreamRunning, as shown in the following figure. 
![20230620135437](https://github.com/BelledonneCommunications/linphone-android/assets/8224607/9217d696-eb0a-4656-a287-05defbc6b932)


Additionally, I generated a new log that only includes one call, in which I couldn't hear the other side's voice at all, but they could hear mine.
[linphone1.log](https://github.com/BelledonneCommunications/linphone-android/files/11796388/linphone1.log)

**Comment by happyfsyy** [comment]
Is it possible that I'm calling setOutputDevice() too frequently, or that I'm testing back-and-forth calls too frequently?

**Comment by Viish** [comment]
> Is it possible that I'm calling setOutputDevice() too frequently, or that I'm testing back-and-forth calls too frequently?

No I don't think so.

> I'm not sure if there's a problem with my code, because I only need to save local users, so when creating the Core object, I didn't use CorePreferences in Linphone-Android, I just created a Config object.

I don't think this is related.

> Also, I have noticed another error in the log:
bctbx_file_open: Error opening '/data/user/0/com.example.shoueedemo/files/.linphone.ecstate': No such file or directory.

Don't worry this is expected.

**Comment by happyfsyy** [comment]
> Do you reproduce your issues with our app from the Play Store?

No, this only happened in my demo, USB headset works fine in Linphone-Android. 
But I don't think there's anything wrong with my code, I just set the inputAudioDevice and outputAudioDevice. 
Here's my code, which is executed in LaunchActivity:
```kotlin
val audioDeviceList= MyApplication.mCore.extendedAudioDevices
var usbOutputDevice: AudioDevice?=null
var usbInputDevice: AudioDevice?=null
for(audioDevice in audioDeviceList){
    if(audioDevice.type== AudioDevice.Type.Headset && audioDevice.hasCapability(AudioDevice.Capabilities.CapabilityPlay) && audioDevice.driverName=="AAudio"){
        usbOutputDevice=audioDevice
    }
    if(audioDevice.type== AudioDevice.Type.Headset && audioDevice.hasCapability(AudioDevice.Capabilities.CapabilityRecord) && audioDevice.driverName=="AAudio"){
        usbInputDevice=audioDevice
    }
}
MyApplication.mCore.defaultOutputAudioDevice=usbOutputDevice
MyApplication.mCore.defaultInputAudioDevice=usbInputDevice
```

> Seems this is an issue between the network and the sound player

Could it be a problem with the USB headset that prevents AudioTrack from initializing, as indicated by the log message "Error -32 during AudioTrack native read"?

**Comment by happyfsyy** [comment]
>Not enough ref samples, using zeroes
MSAudioFlowControl: too many samples to drop, dropping entire frame.

Hello, @Viish 
At the beginning, I had this log.
Then why is it that after I put the call on hold and then resume it, I can hear the other person's voice again and the bug is gone?

**Comment by happyfsyy** [comment]
Hello，@Viish
I'm sorry, I was on vacation a few days ago. After testing today, I think I have found the real problem. 
My demo includes an AudioTrack that starts listening to UDP multicast messages as soon as the program starts. Here is the code:
```kotlin
mAudioTrack=AudioTrack.Builder()
    .setAudioAttributes(AudioAttributes.Builder()
        .setUsage(AudioAttributes.USAGE_VOICE_COMMUNICATION)
        .setContentType(AudioAttributes.CONTENT_TYPE_SPEECH)
        .build())
    .setAudioFormat(AudioFormat.Builder()
        .setEncoding(AudioConfig.audioFormat)
        .setSampleRate(AudioConfig.sampleRateInHz)
        .setChannelMask(AudioConfig.outChannelConfig)
        .build())
    .setBufferSizeInBytes(bufferSizeInBytes)
    .build()
    
val audioManager=MyApplication.mContext.getSystemService(Context.AUDIO_SERVICE) as AudioManager
val outputDeviceList=audioManager.getDevices(AudioManager.GET_DEVICES_OUTPUTS)
for(outputDevice in outputDeviceList){
    if(outputDevice.type==AudioDeviceInfo.TYPE_BUILTIN_SPEAKER){
        mAudioTrack.preferredDevice=outputDevice
        break
    }
}
```

Also, because I need to listen to messages while using the SIP phone, I use the built-in speaker to play the UDP multicast audio, and the USB device to play the SIP phone audio. I suspect that this is the problem that is causing the issue with the SIP phone audio not playing.
```kotlin
val audioDeviceList= MyApplication.mCore.extendedAudioDevices
var usbOutputDevice: AudioDevice?=null
var usbInputDevice: AudioDevice?=null
for(audioDevice in audioDeviceList){
    if(audioDevice.type== AudioDevice.Type.Headset && audioDevice.hasCapability(AudioDevice.Capabilities.CapabilityPlay) && audioDevice.driverName=="AAudio"){
        usbOutputDevice=audioDevice
    }
    if(audioDevice.type== AudioDevice.Type.Headset && audioDevice.hasCapability(AudioDevice.Capabilities.CapabilityRecord) && audioDevice.driverName=="AAudio"){
        usbInputDevice=audioDevice
    }
}
MyApplication.mCore.defaultOutputAudioDevice=usbOutputDevice
MyApplication.mCore.defaultInputAudioDevice=usbInputDevice
```

I would like to know if there is any solution to this problem. How can I control the AudioTrack in the Linphone sdk?Or what changes do I need to make to my AudioTrack code?

**Comment by happyfsyy** [comment]
Hello,
I think I have solved this problem. I set the stream type of my AudioTrack to "Media" and it solved the issue.
Here is the code:
```kotlin
AudioAttributes.Builder()
   .setUsage(AudioAttributes.USAGE_MEDIA)
```
instead of 
```kotlin
AudioAttributes.Builder()
   .setUsage(AudioAttributes.USAGE_VOICE_COMMUNICATION)
```
Thank you for your answer and patience.

**Comment by Viish** [comment]
I'm glad you figured it out.
