### ISSUE TITLE
Ringtong called twice on android 13, K40s

### ISSUE THREAD

**Issue by basncy** [BelledonneCommunications/linphone-android#1943]
When receiving incoming calls, it first plays the system ringing file, and seconds later, the linphone internal ring file played overlaying.
Here is what the sounds like: http://www.linuxe.org:8880/send/ringing.wav
https://www.linphone.org:444//tmp/649ac3930ba6b_72e7c5378abbdbe16a08.gz

**Comment by Viish** [comment]
That's weird, the ringing audio focus from telecom manager should prevent that.
You can disable native ringing to workaround that issue: set
```
[sound]
use_native_ringing=0
```
in config file or use: https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Core.html#setNativeRingingEnabled-boolean-
