### ISSUE TITLE
re-download sdk

### ISSUE THREAD

**Issue by happyfsyy** [BelledonneCommunications/linphone-android#1945]
Hello, I have written the following code in build.gradle:

```
implementation 'org.linphone:linphone-sdk-android:5.3+'
```

As a result, every time I build the project, it needs to re-download the linphone-sdk. 
How should I solve this problem?

**Comment by Viish** [comment]
`5.3.+` means the latest 5.3 version available, and as it is our nightly there is a new one every day.
You need to force a specific version instead of the + to prevent that.
