### ISSUE TITLE
Chat (-button) not disabled while calling with "disable_chat_feature" configuration.

### ISSUE THREAD

**Issue by tuijldert** [BelledonneCommunications/linphone-android#1946]
Greetings,

With the `disable_chat_feature` active, a chat button is still displayed when a voice call is in progress.

2. **To Reproduce**

- Start the phone with `disable_chat_feature` active.
- Make a call (as caller or callee)
- Push the `more` button (call context)
- Observe the presence of the `chat` button.

3. **Expected behavior**

`chat` should not be present or greyed-out/unusable when `disable_chat_feature` is active.

5. **Please complete the following information**

 - Device: Several android devices, notably uOne, Samsung.
 - OS: Android 12
 - Version of the App 5.1.0
 - Version of the SDK 5.2.78
 - Where you did got it from: local build
 - Please tell us if your Android is a Lineage OS or another variant: vanilla

6. **Patch**

Please find attached a patch-proposal that attempts to correct the situation.
Review and apply at your discretion.

Thanks in advance,
    Tom.
[NoChatOnCall.patch](https://github.com/BelledonneCommunications/linphone-android/files/11936828/NoChatOnCall.patch)

**Comment by Viish** [comment]
Hi,

Thanks for reporting the issue! I've fixed it in branch fix/hide_chat_button_from_call_menu, I'll merge it in release/5.1 next week.

Cheers!

**Comment by tuijldert** [comment]
Hi Viish,

Excellent.
Branch not pushed to github (yet)?

Cheers

**Comment by Viish** [comment]
Hi,

I just merged it in release/5.1

Cheers,
