### ISSUE TITLE
Issue with switching the Mic

### ISSUE THREAD

**Issue by ThoracicStorm** [BelledonneCommunications/linphone-android#1948]
On using setInputDevice to switch the current mic, it doesn't switch to the speaker mic or the headset mic, stays on the handset mic itself.

Is this a bug, since even the audioDevices list has only one mic present.

**Comment by Viish** [comment]
Hi,
Indeed using AAudio we do see 2 microphones in the devices list but we can't know which one is each, so we stick to the first microphone.
I recommend using OpenSLES if you do want to switch the microphone when switching the earpiece/speaker (it will be done automatically).
Cheers,
