### ISSUE TITLE
Caller ID misses plus/00 in area code prefix (on call forwarding)

### ISSUE THREAD

**Issue by martin-braun** [BelledonneCommunications/linphone-android#1949]
Hi, thank you for the great app, I've been testing this for a forwarding scenario and have an issue:

1. **Describe the bug** (mandatory)

The caller ID of my internationally forwarded calls that I receive lack the `+` or `00`. They start with the area code right away, such as `49151...` (German mobile phone).

Also, if applicable, **do you reproduce it with linphone-android latest release from the Play Store?**
I don't have access Play Store right now. I'm testing with the F-Droid version.

2. **To Reproduce** (mandatory)

- SIP account at VoIP.ms with Canadian number
- Setting own mobile number (located in Germany) to call forwarding to the Canadian number
- Calling the own mobile number

3. **Expected behavior** (mandatory)

The fully qualified caller ID should appear, but the `+`/`00` is missing. (I tried to change the `00` setting, I also tried to specify `49` as "prefix for my country". Nothing works.

This is bad, because it will fail to recognize the contacts in the contact list.

4. **Please complete the following information** (mandatory)

 - Device: OnePlus 5
 - OS: DivestOS 20.0 (Android 13)
 - Version of the App 5.0.14
 - Where you did got it from: F-Droid
 - Please tell us if your Android is a Lineage OS or another variant: DivestOS is a privacy oriented LineageOS fork

If you are using a SDK that isn't the latest release, please update first as it's likely your issue is already solved.

5. **SDK logs** (mandatory)

Enable debug logs in advanced section of the settings, restart the app, reproduce the issue and then go back to advanced settings, click on "Send logs" and copy/paste the link here.

https://psitransfer.clampcloud.com/d0392ee1d355 (password is the name of this repo)

In case of a call issue, please attach logs from both devices!

6. **Adb logcat logs** (mandatory if native crash)

No native crash.

7. **Screenshots** (optional)

![PXL_20230706_200822018](https://github.com/BelledonneCommunications/linphone-android/assets/24259245/a450a199-fd86-4d34-989b-e4efc8751587)

Thank you in advance for filling bug reports properly!

**Comment by Viish** [comment]
Hi,

Thanks for reporting it.
I've fixed the issue in our SDK, it will be embedded in the next beta release I plan to publish today.

Cheers,
