### ISSUE TITLE
Screen does not turn off until call is answered.

### ISSUE THREAD

**Issue by AndySchroder** [BelledonneCommunications/linphone-android#195]
When making a call, the screen does not turn off until after the call is answered. You have to hold the phone away from your face until the call is answered (to avoid accidentally pressing something on the screen) and then the proximity sensor is used to turn off the screen. This is really impractical because when the phone is away from your face, you can't hear whether the call is answered yet.

**Comment by farahaniamir08** [comment]
yes, I have the same problem.proximity sensor does not work.
any help?

**Comment by atomicwrites** [comment]
Hi, I'm not sure why this was closed but I have the same issue.

**Comment by Viish** [comment]
This has been fixed in feature/kotlin_rewrite branch and will be part of next major release.
