### ISSUE TITLE
Call-on-hold terminates after 30 seconds.

### ISSUE THREAD

**Issue by tuijldert** [BelledonneCommunications/linphone-android#1950]
Hi,

1. **Description**

After establishing a call and putting the conversation on hold (or starting another call), music-on-hold is played but a BYE is sent after about 30 seconds.

2. **To Reproduce**

- Establish a call
- Press the "hold" button
- Wait about 30 seconds
- Observe the call being automatically terminated

3. **Expected behavior**

A BYE should be sent only when the user specifically hangs-up the call, otherwise, call and music-on-hold should last indefinitely.

4. **Additional information**

 - Device: Samsung, uOne
 - OS: Android 12,13
 - Version of the App 5.0.x, 5.1.x
 - Version of the SDK 5.1.x
 - From Play Store and local build
 - _Lineage OS or another variant_: normal

5. **SDK logs**
https://www.linphone.org:444//tmp/64a808822fe77_a4b593780443c2bf8efb.gz

8. **Additional context**

**Note** that we also tested this with a `master` alpha build, in which we couldn't reproduce this. So maybe this issue has been fixed somewhere already, we just can't find it...

**Note** that the usual culprit (AKA a missing `ACK`) does not apply here, `ACK`'s are properly sent and received by both parties, _including_ the re-`INVITE` for the held party.

Hope this helps,
    Tom.

**Comment by Viish** [comment]
Hi @AndreaGianarda,

Can you take a look please?
The call is correctly set-up as send-only but nevertheless it is terminated after 30 because of no-RTP timeout.

Thanks in advance.

**Comment by AndreaGianarda** [comment]
Hi,

The call is terminated because no RTCP packets are received.

According to the logs you sent us, the other party wishes to use port 65316 as RTP port and 65317 as RTCP port and Linphone sets up its RTP engine according to the request:
2023-07-07 14:43:01:121 [com.contactsuite.debug/ortp] MESSAGE RtpSession [0x7e2c16a800] sending to rtp [::ffff:193.178.186.107]:65316 rtcp [::ffff:193.178.186.107]:65317 

Also note the following regarding RTCP packets for sendonly streams from RFC4566 (https://www.rfc-editor.org/rfc/rfc4566):

     a=sendonly

         This specifies that the tools should be started in send-only
         mode.  An example may be where a different unicast address is
         to be used for a traffic destination than for a traffic source.
         In such a case, two media descriptions may be used, one
         sendonly and one recvonly.  It can be either a session- or
         media-level attribute, but would normally only be used as a
         media attribute.  It is not dependent on charset.  Note that
         sendonly applies only to the media, and any associated control
         protocol (e.g., RTCP) SHOULD still be received and processed as
         normal.


Hope this helps,

Andrea

**Comment by tuijldert** [comment]
Hi,

Problem is though, we re-ran the test with `rtcp_enabled` set to `false` (or `0`) and got the same issue, as can be seen in the log [OnholdRtcpIssueNotEnabled.gz](https://github.com/BelledonneCommunications/linphone-android/files/12036737/OnholdRtcpIssueNotEnabled.gz), more notably:
`2023-07-12 14:03:03:630 [com.contactsuite.debug/ortp] MESSAGE RtpSession [0x7301abbc00] sending to rtp [::ffff:193.178.186.107]:62336 `

Whereas the same test in the master-alpha version ([OnholdRtcpIssueMasterVersion.gz](https://github.com/BelledonneCommunications/linphone-android/files/12036782/OnholdRtcpIssueMasterVersion.gz) _with_ `rtcp` enabled ), we see the lack of an `rtcp`-flow not being an issue.

Also, usage of `rtcp` is not mandatory and hardly qualifies as reason to abort an ongoing call.

So, we're still looking for that fix in the master-branch...

Thanks in advance,

Tom.
