### ISSUE TITLE
Legacy PUSH notitfications on latest release

### ISSUE THREAD

**Issue by mentax007** [BelledonneCommunications/linphone-android#1951]
Hello,

I'm trying to configure and use PUSH notification with linphone-android.
I register app with firebase, download google-servies.json file and replace existing one.
The source which I use is the latest from master branch https://gitlab.linphone.org/BC/public/linphone-android
After first compile was done, I realize that **pn-tok** did not been pushed to the phone, so I include an option:
```
[net]
use_legacy_push_notification_params=1
```

However I still receiving registration with the following string:
```
sip:sk@100.77.XX.XX:7000;pn-prid=cHcBIOv0RkSga4m2XnxbhT:APA91bHqUXZxaqtzgXLWl2v5XGR6THzBFaEC6Rv8meJjqMWmCQpDsbgXXU0X1rgzyrXX_ihz4VCas_m4SQhpE0jPMbtqT6y3KhCX20x1CLiKia19IDunC9gCe1e-oC8qUbXXGpXXgvZd;pn-provider=fcm;pn-param=30390XX02XXX;pn-silent=1;pn-timeout=0;transport=udp;+sip.instance="urn:uuid:e57bb893-5474-0061-86ff-397a0d212XXX";+org.linphone.specs="ephemeral/1.1,groupchat/1.2,lime"
```
Any idea what could be wrong?

**Comment by Viish** [comment]
Hi,

Yes, it seems legacy push format support was dropped on October 28th, 2021 in our SDK, in commit ef31804524f406cf025fde00359fa5e87887c4a2.

Cheers,
