### ISSUE TITLE
OVH Timeout 408

### ISSUE THREAD

**Issue by AustralEpitech** [BelledonneCommunications/linphone-android#1952]
Hello,

1. **Describe the bug** (mandatory)

I use SIP from OVH. I can receive calls but not send them.
I tried with default settings and to tweaks them a bit, like encryption.
I also tried what I found here: #1835

2. **To Reproduce** (mandatory)

Start the app for the first time, add your ovh account and try to make a call.

3. **Expected behavior** (mandatory)

The call should work when emitted as well as when received.

4. **Please complete the following information** (mandatory)

 - Device: Samsung Galaxy S10e SM-G970F
 - OS: LineageOS  - Android 13
 - Version FDroid 5.0.14

5. **SDK logs** (mandatory)

https://www.linphone.org:444//tmp/64b4d84d09c1f_f4b599cffd1c42a60938.gz

Thanks in advance.

**Comment by Viish** [comment]
Hi,

Indeed it's due to packet being to big and getting lost due to UDP protocol.
In your case, first try to disable push notifications (as they don't work with OVH anyway).

Cheers,

**Comment by AustralEpitech** [comment]
If this can help,
On OVH manager, the codecs enabled are g711 and g729. I only use 4G networks and no IPV6.

**Comment by Viish** [comment]
>I disabled Call->"Overlay call notification" and Android notifications but this doesn't seems to change anything. I also disabled video just in case.

Push notifications is an account setting under "Delete" and above "Transport".

**Comment by AustralEpitech** [comment]
I don't have the setting there... ?

![image](https://github.com/BelledonneCommunications/linphone-android/assets/71961651/58e08d50-a26c-410f-bb88-863e1171fc3e)

But disabling opus codec appears to be working xDDD
Thanks for your help and your fast responses!
