### ISSUE TITLE
Unable to activate hands-free after a paused (SIP) call is resumed

### ISSUE THREAD

**Issue by BijleveldT** [BelledonneCommunications/linphone-android#1959]
Hi there, while working with Linphone I ran into this issue. I couldn't find it in the issues list, so I decided to add it.
Hopefully, my report is complete enough so it can be fixed and my search was complete enough so I don't bother you with something old...

If there are errors/failures in my spelling, I am sorry for that. English is not my native language.

1. **Describe the bug**

When a call is paused and thereafter resumed, hands-free cannot be activated anymore.
Happens most of the time (might have seen it work properly once or twice, but most of the time, it does not)

Reproduced with the currently latest release of the Google Play store:
Linphone Android 5.0.14 (tags/5.0.14^0,release) 
Linphone SDK 5.2.77 (tags/5.2.77^0,release)

2. **To Reproduce** (mandatory)

Our configuration uses SIP i.c.w. a PBX server (but I assume it is not the cause of the issue)
Transport: UDP

Steps to reproduce: (Phone 'B' is visible on the attached video)
1) Phone A calls Phone B
2) Phone B answers the call
3) Phone B puts the call on pause
4) Phone B resumes the call
5) Phone B presses the 'handsfree' button (multiple times on the provided video)
6) Hands-free does not activate

Note: If Phone A pauses and resumes the call (steps 3 and 4), the same behaviour can be seen on A.
Note2: Also, the video conference button seems to toggle state when the call comes out of 'pause' state. Don't know if that is related to the issue, but it is something I noticed but it might be a different issue.

3. **Expected behavior** (mandatory)
The handsfree mode can be enabled after a paused call is resumed.

4. **Please complete the following information** (mandatory)

 - Device:
 Samsung Galaxy XCover 4s (SM-G398FN)
 Samsung Galaxy XCover 5 (SM-G525F)

 - OS:
 Android 11 (XCover 4s)
 Android 13 (XCover 5)

 - Version of the App
Linphone Android 5.0.14 (tags/5.0.14^0,release) 

 - Version of the SDK
Linphone SDK 5.2.77 (tags/5.2.77^0,release)
 
 - Where you did get it from (Play Store, F-Droid, local build)
 Play Store

 - Please tell us if your Android is a Lineage OS or another variant.
'Default' OS release from Samsung incl. latest security patches (1 June 2023 for both devices)

5. **SDK logs** (mandatory)

Both logs are from the XCover 4s (device seen in the attached video)
Log 1: Logs from the period the video was recorded (Logs not cleared/reset beforehand)
Log 2: Logs from a second run. Equal to the same flow as on the video, but on a different time. (Ater a reset/clear of the logs)

Log1: https://www.linphone.org:444//tmp/64c783fc9ca57_e899729bf4163799c352.gz
Log2: https://www.linphone.org:444//tmp/64c786476a059_a477ade3c407d01a401f.gz

6. **Adb logcat logs** (mandatory if native crash)
n.a.

7. **Screenshots** (optional)
See attached video

8. **Additional context** (optional)
Video with the faulty behaviour:
https://github.com/BelledonneCommunications/linphone-android/assets/141026307/805b30bd-c4f8-4321-b71b-2b0a9c673d1f

If there is anything missing or you need extra information to reproduce/verify/fix this issue, please let me know.

Kind regards,
Thijs (NL)

**Comment by Viish** [comment]
Hi,

Can you tell me if the issue happens with the current public beta on the Play Store please?

Thanks in advance.

**Comment by BijleveldT** [comment]
Hello Sylvain,

I downloaded the latest beta version (5.1.0-beta.74+50178d40d with Linphone SDK 5.2.92) and the issues is resolved!
Thank you for your response and quick fix.

Kind regards,
Thijs

Van: Sylvain Berfini ***@***.***>
Verzonden: maandag 7 augustus 2023 14:32
Aan: BelledonneCommunications/linphone-android ***@***.***>
CC: Thijs Bijleveld ***@***.***>; Author ***@***.***>
Onderwerp: Re: [BelledonneCommunications/linphone-android] Unable to activate hands-free after a paused (SIP) call is resumed (Issue #1959)


Hi,

Can you tell me if the issue happens with the current public beta on the Play Store please?

Thanks in advance.

**Comment by Viish** [comment]
Great!
