### ISSUE TITLE
Registration problem after 401 Unauthorized

### ISSUE THREAD

**Issue by Eulnono76** [BelledonneCommunications/linphone-android#1960]
Hi everyone !

1. **Describe the bug** (mandatory)
Only when the application is killed or if the phone reboot : the registration process stop after SIP/2.0 401 Unauthorized.
So the registration fail.
At the first start of application, there is no problem.

do you reproduce it with linphone-android latest release from the Play Store?
No play store version didn't have this problem. I download the lastest version and compile it.

2. **To Reproduce** (mandatory)
 - Download the lastest version and compile it.
 - Use Android 13
 - Configure your account, the registration will success
 - Kill the application from system, or reboot the phone.
On server side, you can see Linphone doesn't respond to the authentification request SIP/2.0 401 Unauthorized from serveur when you relaunch the APP.

3. **Expected behavior** (mandatory)
It should answer to SIP/2.0 401 Unauthorized with WWW-Authenticate

4. **Please complete the following information** (mandatory)

 - Device: One plus Nord CE 5G
 - 13
 - Version of the App : LinphoneAndroid/5.1.0
 - Version of the SDK : LinphoneSDK/5.2.94
 - Where you did got it from : local build
 - Please tell us if your Android is a Lineage OS or another variant : No

5. **SDK logs** (mandatory)

Can be found here : https://dl.mcom.fr/741cee834e11

I think the problem is related to : 
`[com.testlinphone.debug/liblinphone] WARNING Non unique realm found for 2040`

Thank you in advance for filling bug reports properly!

Thanks you for your support !!!

**Comment by Viish** [comment]
Hi,

That warning log happens when you have more than 1 auth info with the same username & realm.
Can you check you don't add a new auth info each time the app is started? That would explain the problem.
You can also check the app config file on the device using `adb shell run-as org.linphone.debug cat files/.linphonerc` and see if there is more than 1 auth info.

Cheers,

**Comment by Eulnono76** [comment]
Hi @Viish ,

You're right ! Got one new line : 
Before stop the APP
`[auth_info_0]
username=2040
userid=2040
ha1=253a02a9acf76dae249cc52cdaa9c136
realm=asterisk
algorithm=MD5
available_algorithms=MD5`

After stop the APP : 
`[auth_info_0]
username=2040
userid=2040
ha1=253a02a9acf76dae249cc52cdaa9c136
realm=asterisk
algorithm=MD5
available_algorithms=MD5
**passwd=4203b6**`

But... why ?

Regards,
Arnaud

**Comment by Viish** [comment]
That's weird but that's not what I meant.
Do you also have a [auth_info_1] or do you only have [auth_info_0]?

**Comment by Eulnono76** [comment]
No only [auth_info_0].

**Comment by Eulnono76** [comment]
Found a workaround using :
```
<section name="misc">
<entry name="transient_provisioning">1</entry>
</section>
```
In my provisionning file.xml.

Regards,

**Comment by Viish** [comment]
Thanks for the update!
