### ISSUE TITLE
No ringtone heard when incoming_calls_early_media is enabled

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-android#1962]
Good afternoon Viish

1. **Describe the bug** (mandatory)

I've noticed that when the sip parameter "incoming_calls_early_media" is enabled, the device doesn't ring. Only Android's service notification sound is heard briefly. Vibration also doesn't always trigger (or doesn't keep vibrating).

**If the issue is about the SDK (build, issue, etc...) open the ticket in the [linphone-sdk](https://github.com/BelledonneCommunications/linphone-sdk) repository or one of it's submodules!**

2. **To Reproduce** (mandatory)

Set app parameter "incoming_calls_early_media" to 1 and receive a call.

3. **Expected behavior** (mandatory)

Should ring and keep vibrating. The reason I have early media is enabled is to receive a video preview if possible (for example from door intercom).

4. **Please complete the following information** (mandatory)

 - Device: Samsung Galaxy S22 as well as Samsung XCover 5
 - OS: Android 13
 - Version of the App 5.1.0
 - Version of the SDK 5.2.52-pre.1+9eb497d
 - Where you did got it from (Play Store, F-Droid, local build)
 - Please tell us if your Android is a Lineage OS or another variant.

If you are using a SDK that isn't the latest release, please update first as it's likely your issue is already solved.

5. **SDK logs** (mandatory)
[linhonelogs.txt](https://github.com/BelledonneCommunications/linphone-android/files/12260985/linhonelogs.txt)

I suppose this is the relevant part:
`
2023-08-04 14:44:27:384 [be.uzgent.uzlinphone/linphone-android] MESSAGE [Telecom Helper] Is incoming call permitted? true
2023-08-04 14:44:27:385 [be.uzgent.uzlinphone/linphone-android] MESSAGE [Telecom Helper] Is in managed call? false
2023-08-04 14:44:27:385 [be.uzgent.uzlinphone/linphone-android] MESSAGE [Telecom Helper] Call state changed: IncomingEarlyMedia
2023-08-04 14:44:27:385 [be.uzgent.uzlinphone/linphone-android] WARNING [Core Manager] Incoming call is early media and ringing is disabled, stop ringing
`

**Comment by Viish** [comment]
Hi,

Simply call `core.ringDuringIncomingEarlyMedia = true` to allow the Core to ring during an early media incoming call.
