### ISSUE TITLE
at/arobase wrongly translated from google/android contacts, to linphone app'

### ISSUE THREAD

**Issue by lm2lm2** [BelledonneCommunications/linphone-android#1963]
hi, hello, it costed me ten seconds and a new kb;)

1. **Describe the bug** (mandatory)

hello

im wondering about a similar thing, on andro11:
when added SIP addresses to the contacts part, where, address@domain.net (we use several sip providers/domains),  from the google contacts, to the linphone app, the "@" get transformed into "%40", means address%40domain.net, where it's the issue, to do a call to alice%40provider.org, it's just impossible (instead of alice@provider.org)..

is there a way to fix it? ;)
2. **To Reproduce** (mandatory)

go to android contacts, see the SIP addresses added with linphone to the android contacts ; when touching to a sip address and opening it with linphone, "@" are replaced with "%40" something
3. **Expected behavior** (mandatory)
to get the "@" survived the switch from contacts app to the linphone app

4. **Please complete the following information** (mandatory)

 - Device: android phone
 - OS: [andro 11
 - Version of the App 50.14
 - Version of the SDK 5.2.77
 - Where you did got it from (Play Store, F-Droid, local build)fdro
 - Please tell us if your Android is a Lineage OS or another variant.
stock nokia andro

If you are using a SDK that isn't the latest release, please update first as it's likely your issue is already solved.

5. **SDK logs** (mandatory)

Enable debug logs in advanced section of the settings, restart the app, reproduce the issue and then go back to advanced settings, click on "Send logs" and copy/paste the link here.

It's also explained [in the README](https://github.com/BelledonneCommunications/linphone-android#behavior-issue).

In case of a call issue, please attach logs from both devices!

6. **Adb logcat logs** (mandatory if native crash)

In case of a crash of the app, please also provide the symbolized stack trace of the crash using adb logcat.

Here's the command for a arm64 device: `adb logcat | grep ndk-stack -sym <sdk build directory>/libs-debug/arm64-v8a/`

For more information, please refer to [this section of the README](https://github.com/BelledonneCommunications/linphone-android#native-crash) file.

7. **Screenshots** (optionnal)

8. **Additional context** (optionnal)

Thank you in advance for filling bug reports properly!

**Comment by Viish** [comment]
Hi,

Thanks for reporting the issue.
I've made a fix for it here: 023f29cc, it will be part of 5.1.0 release to come.

Best regards,
