### ISSUE TITLE
Missed calls showing up in call history as regular incoming calls.

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-android#1964]
Good afternoon

1. **Describe the bug** (mandatory)

Missed incoming calls are displayed in the notification bar with the _call_missed_ icon, but appear in the call history as regular incoming calls with the _call_incoming_ icon. However, when I click the _show_missed_calls_ button, it is correctly listed there.

Also, if applicable, **do you reproduce it with linphone-android latest release from the Play Store?**
Tested with official 5.1.0-beta.74-50178d40d, Linphone SDK 5.2.92 from Google Play.

**If the issue is about the SDK (build, issue, etc...) open the ticket in the [linphone-sdk](https://github.com/BelledonneCommunications/linphone-sdk) repository or one of it's submodules!**

2. **To Reproduce** (mandatory)

- Receive incoming call but ignore it
- Missed call is shown correctly in the notifcations bar.
- Navigate to call history
- Call is shown as regular incoming call

3. **Expected behavior** (mandatory)

Should be listed with the missed call icon.

4. **Please complete the following information** (mandatory)

 - Device: S22
 - OS: Android 13
 - Version of the App - 5.1.0-beta.74-50178d40d
 - Version of the SDK - Linphone SDK 5.2.92
 - Where you did got it from - Play Store

5. **SDK logs** (mandatory)

[missed_linphone_call.txt](https://github.com/BelledonneCommunications/linphone-android/files/12280078/missed_linphone_call.txt)

Thanks in advance

Edit: I think this might be SDK related since this is happening in our Linphone for iOS version as well.

**Comment by driesken** [comment]
Hi @Viish 

On first sight, it did but I've noticed some side effects.

When there are some calls for the same number (missed/answered/missed), they are all grouped as missed calls.
![Screenshot_20230807_154648_UZ Linphone](https://github.com/BelledonneCommunications/linphone-android/assets/543522/017f6cc8-1b5a-4f03-a9ac-d17652d00992)

Each time I open the call history, the call entries are doubled.
![Screenshot_20230807_154657_UZ Linphone](https://github.com/BelledonneCommunications/linphone-android/assets/543522/ea5d3cb3-4f11-47b1-b145-e3d64268f999)
![Screenshot_20230807_154702_UZ Linphone](https://github.com/BelledonneCommunications/linphone-android/assets/543522/1e7566c9-f33d-49a4-bd91-5b442163081a)

**Comment by Viish** [comment]
Thanks for the feedback, indeed that issue seems to have been there for a while!
I've pushed a fix for it in commit id `f1cfa57f426e90b10bec80f296e06c58c33ea550`.

Regarding the grouping, it's a "feature". All call logs from/to the same person are grouped together (displayed one is the newer one) as long as they are next to each other, unless they are meeting/groups call log.

**Comment by driesken** [comment]
Okay, the behavior of that feature makes sense.

Your latest commit seems to have squashed the bug. Thanks again for the quick fix!

**Comment by Viish** [comment]
You're welcome! We're about to release 5.1.0 version, I'd like to fix all the known issues before ^^
