### ISSUE TITLE
Do't get the window for attending the call

### ISSUE THREAD

**Issue by asder78** [BelledonneCommunications/linphone-android#1967]
Hi, my name is Alfredo, spanish developer...

I think i've found a bug in Linphone 5.0.14 (SDK 5.2.77) for Android 13

Environment:
 - Using linphone downloaded from Play Store
 - using linphone accounts
 - Phone with Android 13

Steps to reproduce the bug:
1.- When i make my first call to tha APP everything is Ok, y get a window letting me attend or reject the call; the phone is also ringing; i can attend the call and everything goes OK (image001.jpg)
2.- After attending and hanging up the call, i close the APP, pushinf the "recent task" button in the phone (the square one of the navigation buttons) and swipping up the APP (image002.jpg)
3.- If i make a new call to the APP the phone rings but i don't get any window letting me attend the call (image003.jpg)
4.- If i open the APP then i can attend the call (image004.jpg)

The expected behaviour would be to get always the "attend or reject" window

 - Device: Xiaomi MI 11 5g (Model M2012K11G)
 - OS: Android 13
 - Version of the App 5.0.14
 - Version of the SDK 5.2.77
 - Where you did got it from Play Store
 - Android is based on Xioami products, with MIUI 14 over it

**SDK logs**

https://www.linphone.org:444//tmp/64d4bbb82aec3_c211e88460747c67faee.gz

**Adb logcat logs**

Not applicable

7. **Screenshots** (optionnal)

![image001](https://github.com/BelledonneCommunications/linphone-android/assets/141908486/83cd845e-af42-40ba-8c3b-300e9e635c30)
![image002](https://github.com/BelledonneCommunications/linphone-android/assets/141908486/22f70d28-638d-4e1d-a157-a943e0ef7810)
![image003](https://github.com/BelledonneCommunications/linphone-android/assets/141908486/387c6e22-0ce9-4a3d-8774-2917822d6590)
![image004](https://github.com/BelledonneCommunications/linphone-android/assets/141908486/baca2066-0055-467d-9c99-32aac7a04870)

9. **Additional context** (optionnal)

Regards

**Comment by asder78** [comment]
Seems to be related with activating "Autostart" in "App info" windows
![image005](https://github.com/BelledonneCommunications/linphone-android/assets/141908486/23a40145-c352-4795-b713-bce8eb9935ac)

**Comment by Viish** [comment]
Hi,

> Seems to be related with activating "Autostart" in "App info" windows

I don't know about that Android setting. Can you screen the whole page please?

**Comment by asder78** [comment]
It's in SETTINGS --> APPS/PERMISSIONS/BACKGROUND AUTOSTART

![image006](https://github.com/BelledonneCommunications/linphone-android/assets/141908486/d89bebee-a6fc-4f53-bda6-0f6e9d9c8801)

**Comment by Viish** [comment]
Thanks. And the issue appears when that settings is turned on or turned off?

**Comment by asder78** [comment]
> Thanks. And the issue appears when that settings is turned on or turned off?

It appears when it's turned on

**Comment by asder78** [comment]
Any news regarding this issue?

Thanks in advance

**Comment by Viish** [comment]
Hi @asder78,

Sorry I forgot to update you.

I can't reproduce it on my wife's smartphone (the only Xiaomi I have at hand), but it's not the same version as MIUI as yours because I don't find the same menus you screenshoot (it's 14.0.3).

Also I tested using the latest version on the PlayStore (5.1.4) and not the 5.0.14.

I also found under "Apps -> Linphone -> Other permissions" a toggle named "Show pop-up window during background browsing" that was disabled but it worked nonetheless.

I hope either updating your device or Linphone version will solve your issue.

Cheers,

**Comment by Viish** [comment]
Hi @asder78,

Does the issue still happens with 5.2.0 release (currently being published on Play Store, in the meantime you can use our [APK here](https://download.linphone.org/releases/android/linphone-android-5.2.0.apk))?

Thanks in advance.
