### ISSUE TITLE
 video call mosaic

### ISSUE THREAD

**Issue by wm164840228** [BelledonneCommunications/linphone-android#1969]
Hello, I am using the latest linphone android demo on my Rockchip 3399pro device

SDK version implementation 'org. linphone: linphone sdk android: 5.3.0 alpha. 265+2e9f1fc'

But there was a problem with video call mosaic, as shown in the picture, how should I make it display a normal screen
![Screenshot_20230812-070730](https://github.com/BelledonneCommunications/linphone-android/assets/42269148/38507d0d-0d00-49ee-96f3-2ff01b54b89a)

**Comment by wm164840228** [comment]
#1153  
My question seems similar to the following question   
Hi，I've tried to add {"rockchip","rk3399pro","rk3399pro"} to https://github.com/BelledonneCommunications/mediastreamer2/commit/e757ca913d87b3bbab878d3701f0bbe6e4620c78 ，and it worked fine! So, can you add it to the next version please?

**Comment by Viish** [comment]
Hi,

Sure, we'll update the table with your device info for next release, thanks for the info!

Cheers,

**Comment by wm164840228** [comment]
thank you viish

**Comment by Viish** [comment]
Hi,

I just merged the new rockchip device in master branch (commit id 8c024f9), it will be in tonight's 5.3 SDK nightly build.

Cheers,

**Comment by wm164840228** [comment]
Hi,Viish
commit id 8c024f9 Perfectly solved my problem
But the recent updates have been too bulky  
May I know how to use it in a lower version   For example, 5.3.0-alpha.194+0c0d586 is only 40M

**Comment by wm164840228** [comment]
@Viish

**Comment by Viish** [comment]
Indeed our AAR on 5.3.0-alpha SDK has gone quite heavy.
Part of that is the newly added support for AV1 codec but that only explains half of it, we'll investigate the other half and wee what we can do about it.

**Comment by wm164840228** [comment]
I wonder if it's possible to add {"rockchip", "rk3399pro", "rk3399pro"} in version 5.2, which also applies to me
5.2 sdk with smaller volume

**Comment by wm164840228** [comment]
@Viish I wonder if it's possible to add {"rockchip", "rk3399pro", "rk3399pro"} in version 5.2, which also applies to me
5.2 sdk with smaller volume

**Comment by Viish** [comment]
Hi @wm164840228,

I just merged the cherry-pick into release/5.2 branch.

Cheers,

**Comment by wm164840228** [comment]
thank you viish

**Comment by Viish** [comment]
Just so you know the size issue is fixed on master branch (5.3.0-alpha), AAR is now 51Mo for the 4 architectures.

**Comment by wm164840228** [comment]
thank you viish
