### ISSUE TITLE
Linphone Library Make Error.

### ISSUE THREAD

**Issue by SarunyuPrasert** [BelledonneCommunications/linphone-android#197]
Please help. I'm always get these error everytime when i try to run 
> make liblinphone-android-sdk

or

> make

and  i don't know how to fix it. I also try to add ndk path in a project, try to remove and clone a project, try to install the ndk r11c or r15c, try to re-install ndk. But the problem is the same. Can some one help me to fix this?

Scanning dependencies of target EP_srtp
[ 57%] Creating directories for 'EP_srtp'
[ 57%] No download step for 'EP_srtp'
[ 57%] No patch step for 'EP_srtp'
[ 58%] No update step for 'EP_srtp'
[ 59%] Performing configure step for 'EP_srtp'
loading initial cache file /Users/sarunyuprasert/Documents/Git_Sip_Linphone_Android/linphone-android/WORK/android-arm64//tmp/EP_srtp/EP_srtp-cache-RelWithDebInfo.cmake
-- Android: Targeting API '21' with architecture 'arm64', ABI 'arm64-v8a', and processor 'aarch64'
-- Android: Selected Clang toolchain 'aarch64-linux-android-clang' with GCC toolchain 'aarch64-linux-android-4.9'
-- The C compiler identification is Clang 5.0.300080
-- Check for working C compiler: /Users/sarunyuprasert/Library/Android/android-ndk-r15c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
-- Check for working C compiler: /Users/sarunyuprasert/Library/Android/android-ndk-r15c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for byteswap.h
-- Looking for byteswap.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for machine/types.h
-- Looking for machine/types.h - not found
-- Looking for sys/int_types.h
-- Looking for sys/int_types.h - not found
-- Looking for sys/socket.h
-- Looking for sys/socket.h - found
-- Looking for netinet/in.h
-- Looking for netinet/in.h - found
-- Looking for arpa/inet.h
-- Looking for arpa/inet.h - found
-- Looking for windows.h
-- Looking for windows.h - not found
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Looking for inet_aton
-- Looking for inet_aton - found
-- Looking for usleep
-- Looking for usleep - found
-- Looking for sigaction
-- Looking for sigaction - found
-- Check size of uint8_t
-- Check size of uint8_t - done
-- Check size of uint16_t
-- Check size of uint16_t - done
-- Check size of uint32_t
-- Check size of uint32_t - done
-- Check size of uint64_t
-- Check size of uint64_t - done
-- Check size of unsigned long
-- Check size of unsigned long - done
-- Check size of unsigned long long
-- Check size of unsigned long long - done
CMake Error at /Users/sarunyuprasert/Documents/Git_Sip_Linphone_Android/linphone-android/WORK/android-arm64/Build/srtp/CMakeFiles/CMakeTmp/CMakeLists.txt:14 (add_executable):
  Cannot find source file:

/Users/sarunyuprasert/Documents/Git_Sip_Linphone_Android/linphone-android/submodules/externals/srtp/test_inline.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: cmTC_75d1b
CMake Error: Cannot determine link language for target "cmTC_75d1b".
CMake Error at CMakeLists.txt:134 (try_compile):
  Failed to generate test project build system.

-- Configuring incomplete, errors occurred!
See also "/Users/sarunyuprasert/Documents/Git_Sip_Linphone_Android/linphone-android/WORK/android-arm64/Build/srtp/CMakeFiles/CMakeOutput.log".
See also "/Users/sarunyuprasert/Documents/Git_Sip_Linphone_Android/linphone-android/WORK/android-arm64/Build/srtp/CMakeFiles/CMakeError.log".
make[3]: *** [/Users/sarunyuprasert/Documents/Git_Sip_Linphone_Android/linphone-android/WORK/android-arm64/Stamp/EP_srtp/EP_srtp-configure] Error 1
make[2]: *** [CMakeFiles/EP_srtp.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [arm64-build] Error 2

**Comment by wangpeng1** [comment]
I also met this problem

**Comment by SarunyuPrasert** [comment]
Yes. Till now I can't find the solution for this error.

**Comment by wangpeng1** [comment]
i have solve the problem，i put the test_inline.c to the srtp , then compile success.

**Comment by SarunyuPrasert** [comment]
where did u find test_inline.c?

**Comment by wangpeng1** [comment]
@SarunyuPrasert  https://github.com/wlanjie/linphone-android ，you can find it

**Comment by SarunyuPrasert** [comment]
Thank you so much :). Finally I can build it.
