### ISSUE TITLE
support websocket 

### ISSUE THREAD

**Issue by moradi-morteza** [BelledonneCommunications/linphone-android#1970]
Is it possible to add a way to connect to a SIP server via WebSocket instead of the raw TCP/UDP socket.
This is defined in [RFC 7118](https://tools.ietf.org/html/rfc7118) and most popular SIP servers support it.

Reference links:

[Kamailio WebSocket Module](https://www.kamailio.org/docs/modules/stable/modules/websocket.html)
[OpenSIPS WebSocket module](https://opensips.org/docs/modules/3.1.x/proto_ws.html)
[Configuring Asterisk for WebRTC Clients](https://wiki.asterisk.org/wiki/display/AST/Configuring+Asterisk+for+WebRTC+Clients)

**Comment by Viish** [comment]
Hi,

Sorry but this isn't in our roadmap for now.

**Comment by MichaelSiddi** [comment]
Hello, any update on websocket support or at least a way to "inject" messages that arrive from a custom signalling channel (I would create my own websocket and use it to send/receive the SIP messages). Thank you

**Comment by Viish** [comment]
@MichaelSiddi you can use our SDK APis such as https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Core.html#inviteAddressWithParams(org.linphone.core.Address,org.linphone.core.CallParams,java.lang.String,org.linphone.core.Content) to do that.

**Comment by MichaelSiddi** [comment]
Hello @Viish,

Thank you for the information! I appreciate your guidance. However, I’m still a bit unclear on how to use the `inviteAddressWithParams` method, especially in a scenario where I need to handle signaling over a custom WebSocket channel.

Specifically, I’d like to understand how to:

1. Be notified when the core wants to send a SIP message (e.g. an INVITE) so I can forward it over my WebSocket to the other party.
2. Inject a received SIP message (e.g. an INVITE or response) from the WebSocket back into the core for processing.

Here’s an example to clarify:

- **A → B:** INVITE  
  - **A:** The core triggers a callback like `onINeedToSendMessage` (or similar) to notify that it wants to send an INVITE.  
  - **B:** Receives the INVITE over the WebSocket and calls a method like `receivedMessage` (or equivalent) to inject the INVITE into the core for further processing.

I attempted to configure `mydomain.com/ws` as the WebSocket URL, but as you mentioned, it seems the core doesn’t natively support WebSocket for SIP signaling yet. Therefore, I’m trying to implement this functionality manually using the SDK.

I’ve explored methods like `setParams` (for modifying call parameters) and `inviteAddressWithParams` (for initiating calls), but these don’t seem to cover intercepting or injecting generic SIP messages.  

Could you kindly point me to the methods or callbacks I should use for:
1. Sending SIP messages via a custom channel when the core triggers them.
2. Receiving and injecting SIP messages from a custom channel into the core.

Thank you very much for your support and patience!

Michael
