### ISSUE TITLE
push notification is not available

### ISSUE THREAD

**Issue by eiheis** [BelledonneCommunications/linphone-android#1971]
Hi

    After compiling and installing Linpohne using Android Studio, I found that I couldn't create an account. Upon checking the log, it was found that it was' Failed to get push notification information, showing warning install of phone based account creation '.

![image](https://github.com/BelledonneCommunications/linphone-android/assets/100825840/1fbbfdae-52a2-4103-97fb-78f11cdfdd34)

keylog:
I/Linphone: Activity started:org.linphone.activities.main.MainActivity@4b90f2e
I/Linphone: [Main Activity] Handling intent with action [android.intent.action.MAIN], type [null] and data [null]
I/Linphone: [Activity Monitor] Activity resumed:org.linphone.activities.main.MainActivity@4b90f2e
I/Linphone: [Activity Monitor] runningActivities=1
I/Linphone: [Activity Monitor] App has left background mode
I/Linphone: [Core Manager] App has left background mode
I/Linphone: [Platform Helper] Active network type is WIFI, state CONNECTED / CONNECTED
I/Linphone: [Platform Helper] [Network Manager 26] Found DNS host 2001:4860:4860::8888 from active network WIFI
I/Linphone: [Platform Helper] [Network Manager 26] Found DNS host 8.8.8.8 from active network WIFI
I/Linphone: [Platform Helper] DNS servers list updated
I/Linphone: [Platform Helper] Network reachability enabled
I/Linphone: Updating friend list [0x6e8cce52d0] subscriptions
I/Linphone: Updating friend list [0x6e8cce52d0](_default) subscriptions
I/Linphone: Updating friend list's [0x6e8cce52d0] friends subscribes
I/Linphone: [Core Manager] Restarting core.iterate() schedule with foreground timer
I/Linphone: [Core Manager] Stopping scheduling of core.iterate() every 500 ms
I/Linphone: [Core Manager] Call to core.iterate() scheduled every 20 ms
E/OpenGLRenderer: Unable to match the desired swap behavior.
I/Linphone: [Platform Helper] getDnsServers() returning 2001:4860:4860::8888, 8.8.8.8, 
I/Linphone: [Android Platform Helper] Found DNS server 2001:4860:4860::8888
I/Linphone: [Android Platform Helper] Found DNS server 8.8.8.8
I/Linphone: [Activity Monitor] Activity paused:org.linphone.activities.main.MainActivity@4b90f2e
I/Linphone: [Activity Monitor] runningActivities=0
I/Linphone: [Activity Monitor] Activity created:org.linphone.activities.assistant.AssistantActivity@7c2e75a
I/Linphone: [Generic Activity] Ensuring Core exists
I/Linphone: [Assistant] Loading linphone default values
I/Linphone: [LIME] destroy LimeX3dhEncryption engine 0x6e3ccbc2d0
I/Linphone: [LIME] instanciate a LimeX3dhEncryption engine 0x6e3ccb4410 - default server is [] and curve c25519 DB path: /data/user/0/org.linphone.debug/files/x3dh.c25519.sqlite3
I/Linphone: LinphoneAccount[0x6ebcd0a898] created with params
I/Linphone: LinphoneAccount[0x6ebcd0a898] created with proxy config
I/Linphone: Activity started:org.linphone.activities.assistant.AssistantActivity@7c2e75a
I/Linphone: [Activity Monitor] Activity resumed:org.linphone.activities.assistant.AssistantActivity@7c2e75a
I/Linphone: [Activity Monitor] runningActivities=1
E/OpenGLRenderer: Unable to match the desired swap behavior.
W/Parcel: Expecting binder but got null!
I/Linphone: [Activity Monitor] Activity stopped:org.linphone.activities.main.MainActivity@4b90f2e
E/Linphone: core.isPushNotificationAvailable = false
W/Linphone: [Assistant] Failed to get push notification info, showing warning instead of phone based account creation

**Comment by Viish** [comment]
Hi,

That means the Android you run the app on doesn't supports push notifications.
This happens when Google Play Services are unavailable or if you disabled/removed the dependency on Firebase in the build for example.

Cheers,

**Comment by eiheis** [comment]
Hi viish，

I don't think what you said is correct. I have tried the following scenarios.

1. The app I downloaded on the Linphone official website using the same device can function normally.

2. I will still report errors when installing the compiled app on devices with the Google Paly framework.

**Comment by Viish** [comment]
Hi,

> The app I downloaded on the Linphone official website using the same device can function normally.

I guess you mean the app on the Play Store works.
Problem is the current release on the Play Store doesn't currently have that requirement, so even if your device doesn't have push you won't see it with the 5.0.14 currently released. You can try using the 5.1 public beta.

> I will still report errors when installing the compiled app on devices with the Google Paly framework.

Push notifications and bug reports aren't the same things, so one can work and not the other.

Can you attach full logs of the app with debug toggle on?

Cheers,

**Comment by eiheis** [comment]
Hi viish.

[push_notification_error.txt](https://github.com/BelledonneCommunications/linphone-android/files/12393787/push_notification_error.txt)

I just want to create linphone account in  linphone app, but it is not available. And I don't know why linpone service have not started.
  
This is log file, please cheeck it, thank you.

**Comment by Viish** [comment]
Please enable debug logs in advanced settings, restart the app and then send logs (only linphone logs please, you can do it using the send logs button in advanced settings).

**Comment by eiheis** [comment]
OK, I send the log

https://www.linphone.org:444//tmp/64e4102903781_143a6e203dd635d484cc.gz

**Comment by Viish** [comment]
In your logs there is the following:
`2023-08-22 09:31:50:241 [org.linphone.debug/linphone-android] ERROR [Push Notification] Firebase getToken failed: java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: MISSING_INSTANCEID_SERVICE`
Firebase doc says that this error happens when your device doesn't support push due to lack of Google Play Services: https://developers.google.com/android/reference/com/google/android/gms/iid/InstanceID#ERROR_MISSING_INSTANCEID_SERVICE

**Comment by eiheis** [comment]
Whether have some ways to run app in no Google play service devices

**Comment by Viish** [comment]
You can use the app normally even if you don't have push notifications (even if it's highly recommended to ensure the app will properly wake up when a call or a message is being received). You simply can't create an account directly from the app, you'll have to create it on https://subscribe.linphone.org (using an email) and then log it in the app manually.

**Comment by eiheis** [comment]
I know that. But this fucking devices don`t have browser,  and it will not integrate browsers.  /(ㄒoㄒ)/~~
