### ISSUE TITLE
is private TURN supported?

### ISSUE THREAD

**Issue by davidcsi** [BelledonneCommunications/linphone-android#1972]
Is TURN with user/pass supported? I don't see anyplace to set coturn user/pass.
Linphone Android 5.0.14 SDK 5.2.77

Thanks

**Comment by Viish** [comment]
Hi,

Yes our SDK does support TURN with username/password, we just never added the feature in our apps so far.

Cheers,

**Comment by davidcsi** [comment]
does it support RFC6544? i.e.: RTP over TCP.
Will you add this to the app at some point?

**Comment by Viish** [comment]
> does it support RFC6544? i.e.: RTP over TCP.

No we won't support yet RFC6544.

> Will you add this to the app at some point?

Yes, probably in next year release.

**Comment by davidcsi** [comment]
@Viish last clarification, you will support RTP over TCP at TURN’s offer?

thanks!

**Comment by Viish** [comment]
> last clarification, you will support RTP over TCP at TURN’s offer?

Maybe someday but to my knowledge that's not currently on our roadmap.
If that's something you really want/need, you can contact our sales department for a quotation.

**Comment by basncy** [comment]
@davidcsi I set protocols=turn,ice in linphonerc file to enable private TURN server currently.

**Comment by basncy** [comment]
At this moment, it only works for private TURN servers with restricted settings.
when IPV6 is enabled on only one side, not work in most cases, plus considering VPN, incoming blocking(4G) firewall.
