### ISSUE TITLE
Change button colours

### ISSUE THREAD

**Issue by jcdutton** [BelledonneCommunications/linphone-android#1973]
First of all, please say "Hi" or "Hello", it doesn't cost much.

1. **Describe the bug** (mandatory)

I wish to change various buttons and layout of linphone so that it is easier to use on a tablet for a disabled person.
This generally means, making things look bigger, and having buttons father apart so they are easier to touch without accidentally touching a different button.
I have managed to do most things, but I cannot find how to change the dial button from Orange to Green.
They need any dial buttons that make the call to be green, and any buttons that will hang up the call to be Orange or Red.
Please can someone point me towards the lines of code that colour the button, so I can change it for my own use.

2. **To Reproduce** (mandatory)
The dial button is Orange, it needs to be Green.

3. **Expected behavior** (mandatory)

The dial button should be green.

4. **Please complete the following information** (mandatory)

- Device: Samsung Tablet.

5. **SDK logs** (mandatory)

No logs needed, just information please.

6. **Adb logcat logs** (mandatory if native crash)

No needed

7. **Screenshots** (optionnal)

No needed

8. **Additional context** (optionnal)

Not needed. I just need pointers to where in the code, so I can change it myself.

**Comment by Viish** [comment]
Hi,

Change the color reference in that file : https://github.com/BelledonneCommunications/linphone-android/blob/master/app/src/main/res/drawable/call.xml

Cheers,

**Comment by jcdutton** [comment]
Many thanks. I have a green button now.
