### ISSUE TITLE
ANR during processPushNotification

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-android#1974]
Hi @Viish 

1. **Describe the bug** (mandatory)

I've noticed several ANR's when an incoming push notification was received. When opening the Linphone app, the app indicated that it had crashed.

2. **To Reproduce** (mandatory)

Seems that it has something to do with the "force_register_on_push" option I've enabled a few days ago.

3. **Expected behavior** (mandatory)

Should not throw an ANR.

4. **Please complete the following information** (mandatory)

 - Device: Samsung Galaxy S22
 - OS: Android 13
 - Version of the App 5.1
 - Version of the SDK 5.2.95-pre.1+4938179
 - Where you did got it from local build

If you are using a SDK that isn't the latest release, please update first as it's likely your issue is already solved.

5. **SDK logs** (mandatory)
[linphone logs.txt](https://github.com/BelledonneCommunications/linphone-android/files/12393283/linphone.logs.txt)

6. **Adb logcat logs** (mandatory if native crash)
[anr_2023-08-21-08-57-02-188.log](https://github.com/BelledonneCommunications/linphone-android/files/12393289/anr_2023-08-21-08-57-02-188.log)
[anr_2023-08-21-08-33-02-888.log](https://github.com/BelledonneCommunications/linphone-android/files/12393290/anr_2023-08-21-08-33-02-888.log)

**Comment by bagherfathi** [comment]
@driesken 
how do you enabled force_register_on_push in linphone android client?

**Comment by driesken** [comment]
@bagherfathi 
Through remote provisioning
