### ISSUE TITLE
How to make a video group/conference call?

### ISSUE THREAD

**Issue by zjw1918** [BelledonneCommunications/linphone-android#1975]
Hi, any example or docs to show how to make video group calls?
I tried the official "outgoing" example, but it's a one to one call.
Specially how to set multi remote previews and local preview.
Thanks.

**Comment by Viish** [comment]
Hi,

Sorry but not currently.
You can check the code at https://github.com/BelledonneCommunications/linphone-android/blob/master/app/src/main/java/org/linphone/activities/voip/viewmodels/ConferenceViewModel.kt to get an idea.

Cheers,
