### ISSUE TITLE
Audio & Video Calls are not getting through on Xamarin Android

### ISSUE THREAD

**Issue by cjkarande** [BelledonneCommunications/linphone-android#1976]
Hi Team,

1. **Describe the bug** (mandatory)
I am using Linphone for Xamarin project from https://github.com/BelledonneCommunications/linphone-xamarin.
The github project works fine for both audio and video calls. 

However, after integrating the code in my existing Xamarin Forms project, post Registration call when I try to initiate an Audio or Video call it does not get through. The call drops with 2 beeps and I do not receive any call at the target address.

2. **To Reproduce** (mandatory)
Post User Registration, when I initiate the call (Audio or Video), I get a Call initiated state but then it ends with an Error state after 2 beeps. 

3. **Expected behavior** (mandatory)
Expecting the Calls to get through like the Original Github code (Linphone-Xamarin)

4. **Please complete the following information** (mandatory)
[0:] DEVICE=peux
[0:] MODEL=2201116PI
[0:] MANUFACTURER=Xiaomi
[0:] SDK=33
[0:] Linphone Xamarin version: 5.1.73

5. **SDK logs** (mandatory)
Logs for both Apps viz. Linphone-Xamarin (Original Github App) & Linphone-MyApp (My App) have been attached below.

Request your advice to resolve the issue.

[Linphone-MyApp.txt](https://github.com/BelledonneCommunications/linphone-android/files/12473528/Linphone-MyApp.txt)
[Linphone-Xamarin.txt](https://github.com/BelledonneCommunications/linphone-android/files/12473529/Linphone-Xamarin.txt)

**Comment by cjkarande** [comment]
Hello @Viish, request you advice on this issue.

**Comment by Viish** [comment]
Hi,

It simply seems to be you haven't properly configure your sip.linphone.org account in your app.
You can check out our tutorials if you're unsure how to do it: https://gitlab.linphone.org/BC/public/tutorials

Cheers,
