### ISSUE TITLE
toggleSpeaker button doesn't work below android 11

### ISSUE THREAD

**Issue by hohoiot** [BelledonneCommunications/linphone-android#1980]
Hello.

A toggleSpeaker button doesn't work to change from a speakerphone to an earpiece below android 11.
Above android 12, it works well.
I tested at my phone and tablet.
And, I tested on android emulator also.
And, the same error occurred in the release version from the Play Store.

Device: Samsung SM-P200
OS: Android 11
Version of the App: 5.1.0
Version of the SDK : 5.2+
Local Build and Release Version

Thank you.

**Comment by Viish** [comment]
Hi,

Thanks for the report, but please attach debug logs from linphone client showing such issue.

Cheers,

**Comment by hohoiot** [comment]
Hi,

Thank you for the reply.
I attach the log.

https://www.linphone.org:444//tmp/64f54c0dda089_ac5e54a95935446cf809.gz

Thank you.

**Comment by Viish** [comment]
Thanks.

It seems to be an issue with TelecomManager's API, as we correctly ask it to route audio to earpiece but nothing seems to be happening.
Can you try disabling the "Improve interactions with bluetooth devices" setting in Calls section and tell me if you still have the problem please?

Thanks in advance.

**Comment by hohoiot** [comment]
Hello.

I disabled the function as your comment and it still has the problem.

Thank you.

**Comment by Viish** [comment]
Hi,

That's unexpected and interesting.
Can you attach new logs with the feature disabled please?

Thanks.

**Comment by hohoiot** [comment]
Hi,

I attach the caller and callee's information.

*Caller
Device: Samsung SM-A315
OS: Android 12
Linphone Version : latest download version from google play
TogleSpeaker Button : It works well.
Log: https://www.linphone.org:444//tmp/64f6de0ca2b7c_119d781f6af106b68c85.gz

*Callee
Device: Samsung SM-P200 (Tablet)
OS: Android 11
Linphone Version : latest download version from google play
TogleSpeaker Button : It can not changed to earpiece.
Log: https://www.linphone.org:444//tmp/64f6de428696f_3058904336774e58180c.gz

According to my test result, the problem seems to depend on the android version.

Thank you.

**Comment by Viish** [comment]
Hi,

Oh I understand. Issue isn't the Android OS version, it's because it's a tablet.
Tablet devices don't have earpiece, only one speaker, that's why it "doesn't work".

Cheers,

**Comment by hohoiot** [comment]
Thank you.

Okay, I understand.

Cheers,
