### ISSUE TITLE
Incoming video shows "No Video Input"

### ISSUE THREAD

**Issue by dabhi86** [BelledonneCommunications/linphone-android#1981]
Hi Team Linphone,

My App is using latest Linphone SDK but is not getting video when receiving incoming SIP call. It shows "No Video Input" I was getting the video when I was using Linphone SDK 4.5 but now after updating the SDK to latest 5.3, I am not getting incoming video. I am attaching logs file for your consideration, please suggest what I should do in order to resolve this issue.

As Logs are too long so can't paste them here, Here is the link for logs - https://www.dropbox.com/scl/fi/i82x0ei8p9u98rfs3c8mx/logs.txt?rlkey=zhnslwo512smlbq6sm0vbe7lt&dl=0

Regards
Abhinav Srivastava

**Comment by Viish** [comment]
Hi,

The problems seems to be related to a bad INVITE packet:
```
2023-09-02 00:20:05.783 29918-29918/org.mircom I/MiEntry: [org.antlr.runtime.MismatchedTokenException]  reason [IS_TOKEN(Supported)]
2023-09-02 00:20:05.784 29918-29918/org.mircom E/MiEntry: header_supported parser error for [k:replaces]
```
Fix the issue in your server and it should be OK again.

Cheers,
