### ISSUE TITLE
GSM call is not put on hold when SIP call is initiated from Linphone

### ISSUE THREAD

**Issue by BijleveldT** [BelledonneCommunications/linphone-android#1983]
Hello!

Thank you for your ongoing development of this great app. Unfortunately, I ran into a (hopefully small) issue with the latest version of the app.

1. **Describe the bug** (mandatory)

In specific cases, an ongoing phone call (started from Android Dialer) is not put "on hold" when Linphone starts a SIP call.
I was able to reproduce this issue on a Samsung Galaxy S5 with Android 12 AND 13.
An XCover 4S with Android 11 did not have this issue.

2. **To Reproduce** (mandatory)

Have three devices (A, B and C). A and B should be able to call each other over SIP. A and C have GSM capabilities to call each other.
1) On phone A, start a GSM call from the Android Dialer to Phone C
2) On phone C, accept the incoming call (activating speaker mode makes it easier to hear what is going on)
3) On phone A, open (or navigate to) Linphone and call Phone B through SIP.
4) On phone B, accept the incoming SIP call from A
5) Make noise near phone A

3. **Expected behavior** (mandatory)
It is expected that the GSM call is put "on hold" when the SIP call is started.
Actually, the GSM call remains active and the noise made at A can be heard by C.

4. **Devices, Android versions and Linphone/SDK versions** (mandatory)

Samsung Galaxy XCover 5:
- Android 12 (sec.patch: 1 nov 2022) -> Android version is the standard version of Samsung
- Linphone 5.1.0 (tags/5.1.0^0,release) SDK 5.2.96 (tags/5.2.96^0,release)

Samsung Galaxy XCover 5:
- Android 13 (sec.patch: 1 aug 2023) -> Android version is the standard version of Samsung
- Linphone 5.1.0-beta.92+91554f99f (release/5.1,releaseWithCrashlytics) SDK 5.2.95-pre.1+4938179ac (release/5.2,release)

Both versions were acquired from the PlayStore. The Android 13 device is part of the Linphone Beta tester track.

Samsung Galaxy XCover 4s:
- Android 11 (sec.patch: 1 july 2022) -> Android version is the standard version of Samsung
- Linphone 5.1.0 (tags/5.1.0^0,release) SDK 5.2.96 (tags/5.2.9660,release)

The XCover 4s device did **NOT** encounter the issue and muted the GSM call as expected. Unfortunately, I was unable to retrieve the logs from the XCover 4s device. (Got an error in the Linphone UI that the upload failed), even after a 'reset logs' going through the 'steps to reproduce' and trying to upload again

5. **SDK logs** (mandatory)
XCover 5 Android 12: https://www.linphone.org:444//tmp/64f6dec824f51_7ef03a63d55daee7a450.gz
XCover 5 Android 13: https://www.linphone.org:444//tmp/64f6e2aab413c_7b8de150c82276f252c8.gz

6. **Adb logcat logs** (mandatory if native crash)
n.a.

7. **Screenshots** (optional)
n.a.

8. **Additional context** (optional)

**Comment by Viish** [comment]
Hi,

Thanks for the report.
Can you disable the "Improve bluetooth devices" toggle from "Calls" settings please and tell me if it still happens?

Cheers,

**Comment by BijleveldT** [comment]
Hi Viish,

Unfortunately, disabling the "Improve Bluetooth devices" setting does not change the result. The GSM call still remains active/open.

**Comment by Viish** [comment]
Can you attach a new log file with only that case in it please?

**Comment by BijleveldT** [comment]
I cleared the logs and then reran the reproduction.
These are the log files: https://www.linphone.org:444//tmp/64f715e1d906e_1d8b799b8ef824c86aac.gz

**Comment by Viish** [comment]
Thanks.

This seems to be an issue with the dialer app in the Samsung firmware that doesn't handle properly the audio focus requests.
Sorry but there isn't much I can do about it.

**Comment by BijleveldT** [comment]
Darn, that is a shame to hear. Thank you for investigating and trying to help and sorry to hear there is nothing you/we can do.
Again, thank you for your time and effort.

**Comment by Viish** [comment]
You're welcome.

Too bad it was working in Android 11 and it no longer does.
It's a shame that Android's TelecomManager APIs aren't properly implemented supported. Maybe we'll have better luck with `androidx.core:core-telecom` library (currently alpha01).
