### ISSUE TITLE
AOSP compiled apk cannot load so files correctly

### ISSUE THREAD

**Issue by zjw1918** [BelledonneCommunications/linphone-android#1984]
Hi, before 5.2.62(included), I extract so files from aar, and put them into an ASOP project and build. The apk works well.
But it fails to work from 5.2.65.
Does the so build way changed?

Here is the log:
`FATAL EXCEPTION: main
                                                                                                    Process: com.x.x, PID: 12653
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN4Json5ValueC1ERKNSt6__ndk112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE" referenced by "/system_ext/lib64/liblinphone.so"...`

Thanks

**Comment by Viish** [comment]
Hi,

That's weird.
Between 5.2.62 and 5.2.65 only changes related to yocto build were made.
Do you have the same issue with latest 5.2 release (5.2.100)?
Have you tried with a 5.3-alpha?

Cheers,

**Comment by zjw1918** [comment]
Hi @Viish 
Will try alpha later. Thanks
