### ISSUE TITLE
Pausing the current call invalidates the Core.CurrentCall object to null

### ISSUE THREAD

**Issue by cjkarande** [BelledonneCommunications/linphone-android#1987]
Hello @Viish ,

Describe the bug (mandatory)
If I try to pause the current call using Core.CurrentCall.Pause() method then for some reason Core.CurrentCall object reference becomes null and so i am not able to call  Core.CurrentCall.Resume() method to resume the current call.

For the time being, as a work around i am using Core.Calls.First() which returns a valid ref to current call.

To Reproduce (mandatory)
Same as above

Expected behavior (mandatory)
The CurrentCall object ref should stay valid to allow calling of Resume() method.

Please complete the following information (mandatory)
[0:] DEVICE=peux
[0:] MODEL=2201116PI
[0:] MANUFACTURER=Xiaomi
[0:] SDK=33
[0:] Linphone Xamarin version: 5.1.73

SDK logs (mandatory)
Logs for both Apps viz. Linphone-Xamarin (Original Github App) & Linphone-MyApp (My App) have been attached below.

**Comment by Viish** [comment]
Hi @cjkarande,

Yes, this is expected.
A paused call isn't considered "current".
I recommend you to do something like that:
```
call = if (core.currentCall != null) core.currentCall else if (core.callsNb > 0) core.calls[0] else null
```
Cheers,

**Comment by cjkarande** [comment]
@Viish , I have defined a unified CurrentCall Get Property as below.

Call CurrentCall { get { return Core.CurrentCall == null ? Core.Calls.First() : Core.CurrentCall; } }

**Comment by cjkarande** [comment]
No worries, all references to CurrentCall are within a if (core.callsNb > 0) { } block 
:)
