### ISSUE TITLE
Registration Call takes more than 60 seconds over a 4G mobile network as against a Broadband WiFi network

### ISSUE THREAD

**Issue by cjkarande** [BelledonneCommunications/linphone-android#1988]
Hello @Viish ,

Describe the bug (mandatory)
Registration call takes more 70 seconds over a 4G mobile network as against a Broadband WiFi network (< 2 secs). However once connected the subsequent call actions like Audio /Video Call, Audio/Video update requests all get through quickly on the Mobile network.

To Reproduce (mandatory)
Same as above

Expected behavior (mandatory)
Registration call should not take so long over a mobile network

Please complete the following information (mandatory)
[0:] DEVICE=peux
[0:] MODEL=2201116PI
[0:] MANUFACTURER=Xiaomi
[0:] SDK=33
[0:] Linphone Xamarin version: 5.1.73

Is there some additional config required to operate over Mobile network?

**Comment by Viish** [comment]
Hi, @cjkarande,

It's likely to be an issue with the DNS server or on that particular 4G network, but without logs I can't tell you exactly.
Feel free to add them and I'll take a look.

Cheers,

**Comment by cjkarande** [comment]
@Viish , today suddenly the registrations on Mobile network seemed work fine. Like you mentioned, it might have been a Mobile network's DNS issue.

Btw, is there a way to override the default operator DNS to Google or other DNS in linphone's android apis?

Also another question not related to this,
I am trying to get width and height of Local and Remote video streams using CallParams.SentVideoDefinition and CallParams.ReceivedVideoDefinition to set the TextureView's aspect ratio, however both the properties are returning null values. I am checking them in the OnCall callback for CallState == StreamsRunning after Video is Enabled. 

Am i doing something wrong?

**Comment by cjkarande** [comment]
@Viish 

> @cjkarande
> 
> 1. Make sure you call getSentVideoDefinition() and getReceivedVideoDefinition() on the currentParams of the call and not the params or the remoteParams?

Thanks, I will try this and get back to you.

> 2. Our SDK should detect by itself (on Android) the device orientation and correct the captured image accordingly, but if it doesn't work on your device you can call youself core.setDeviceRotation() to give it the right one.

Just to add to pt. 2, the local Device is an Android Tablet running my Linphone App while the remote Device is my Laptop running  the standard Linphone Windows App. I even tried with a Remote Android phone running Linphone app from Play store. The stream received is 90 deg rotated on the remote device.

Will core.setDeviceRotation() and let you know.
> Cheers,

I highly appreciate your prompt support

**Comment by cjkarande** [comment]
> Hi, @cjkarande,
> 
> It's likely to be an issue with the DNS server or on that particular 4G network, but without logs I can't tell you exactly. Feel free to add them and I'll take a look.
> 
> Cheers,

Hello @Viish, hope you are doing well.
I started have been facing this issue again with the Mobile network. Presuming that this would be an issue with Mobile Operators DNS servers., does the linphone library provide any API to set Custom DNS server to bypass the operator's DNS?

**Comment by Viish** [comment]
Hi @cjkarande,

You can use https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Core.html#setDnsServers-java.lang.String:A-

Cheers,

**Comment by cjkarande** [comment]
Thanks a lot @Viish for the input. 
With setDnsServers(), do i need to also call setDnsSrvEnabled()?
Also what is difference between setDnsServers() and setDnsServersApp()? Does this refer to DNS setting Mobile Apps...
Finally, can you please recommend DNS servers that work best for the domain sip.linphone.org?

**Comment by Viish** [comment]
> With setDnsServers(), do i need to also call setDnsSrvEnabled()?

No you don't have to.

> Also what is difference between setDnsServers() and setDnsServersApp()

The second one allows you to keep the original DNS servers list aside, and you can switch between them and yours using the config setting dns_set_by_app to switch between the two.

> Finally, can you please recommend DNS servers that work best for the domain sip.linphone.org?

Any one should be fine, we don't know of any DNS server not working well with our domain.

**Comment by cjkarande** [comment]
> Thanks a lot @Viish for the input. With setDnsServers(), do i need to also call setDnsSrvEnabled()? Also what is difference between setDnsServers() and setDnsServersApp()? Does this refer to DNS setting Mobile Apps... Finally, can you please recommend DNS servers that work best for the domain sip.linphone.org?

Hello @Viish 
I tried using the following DNS Server setting code in my Xamarin App, however this issue of Registration delay over 4G network still persists. I have attached the App Log for your reference. Not able to understand the cause of problem. Request your kind support.
///////////////////////////////////////
Manager = new LinphoneManager();
Manager.Init(rc_path, factory_path, context.Handle);
Core.DnsServers = new List<string> { "8.8.8.8", "8.8.4.4" };
Core.DnsSrvEnabled = true;
Core.DnsSearchEnabled = true;
///////////////////////////////////////
[Linphone-MyApp.txt](https://github.com/BelledonneCommunications/linphone-android/files/12848478/Linphone-MyApp.txt)

**Comment by cjkarande** [comment]
Hello @Viish , any luck with the attached logs.....This is a vital issue for one our use case over mobile network.
Request any tips or direction on this issue

**Comment by cjkarande** [comment]
Hello @Viish , hope you are doing well. Just a gentle reminder for this issue. Please let me know if you need any more info.

**Comment by Viish** [comment]
Hi @cjkarande,

Could you try using [setDnsServersApp](https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Core.html#setDnsServersApp-java.lang.String:A-) instead of `core.setDnsServers()`?

Cheers,

**Comment by cjkarande** [comment]
Hi @Viish ,
Tried using [setDnsServersApp](https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Core.html#setDnsServersApp-java.lang.String:A-) but no luck with that as well

**Comment by Viish** [comment]
Hi @cjkarande,

Could you add new logs with `setDnsServersApp` please?

**Comment by basncy** [comment]
These days I am estimating the matrix element client, I found it recieving messages in time.
There always a TCP link from my self-hosted server connected to official server, which used to trigger the push action, waking the iOS client to connect to self-hosted synapse server directly. This process avoid the terriable international network, reduced the cold restart time on end user app side.
Maybe you can consider implementing a flexisip-to-officialServer to wake up official linphone mobile client; or provide a limited push API usage for community product. https://github.com/BelledonneCommunications/flexisip-account-manager/issues/1

**Comment by Viish** [comment]
Closing until requests logs will be provided.
