### ISSUE TITLE
How to implement the auto-answer feature configured in FreeSwitch？

### ISSUE THREAD

**Issue by happyfsyy** [BelledonneCommunications/linphone-android#1989]
Hello, @Viish my phone communication features are all implemented through FreeSwtich. 
In order to achieve the intercom functionality, I have made the following configuration in FreeSwtich:
```xml
<action application="EXPORT" data="sip_auto_answer=true"/> 
```
This configuration is effective for Yealink phones. 
For example, when dialing from 1005 to 1006, 1006 will automatically answer the call, even if the auto-answer feature is not enabled on the 1006 phone itself. 

However, this configuration does not work for phones installed with Linphone-Android, such as the 1007 phone. 
I have to enable the auto-answer button in the settings page of Linphone-Android for it to automatically answer calls.
I don't want to keep the auto-answer button enabled in the settings page of Linphone-Android permanently. 

How can I implement this auto-answer feature?

**Comment by Viish** [comment]
Hi,

We do not support this feature, sorry.

Cheers,
