### ISSUE TITLE
Building Linphone SDK for android in Ubuntu fails everytime

### ISSUE THREAD

**Issue by abhinav-android** [BelledonneCommunications/linphone-android#1993]
Hi Support team,

I am trying to build Linphone SDK for android in Ubuntu to add H-263 video codec but every time it fails. I have added paths of SDK and NDK correctly and have installed all the required modules like Cmake as well. Can you please suggest steps that I need to take to build it successfully.

Here is what I am doing.

git clone https://gitlab.linphone.org/BC/public/linphone-sdk.git
cd linphone-sdk/
git submodule update --init --recursive
yes | rm -r cmake-builder
git clone https://github.com/DroidPulkit/linphone-cmake-builder.git cmake-builder
cd cmake-builder
git checkout ffmpeg-fix
cd ..
mkdir build && cd build
cmake .. -DLINPHONESDK_PLATFORM=Android -DENABLE_NON_FREE_CODECS=ON -DENABLE_GPL_THIRD_PARTIES=ON -DENABLE_MPEG4=ON -DENABLE_H263=ON -DENABLE_H263P=ON -DENABLE_FFMPEG=ON -DENABLE_DEBUG_LOGS=ON -DLINPHONESDK_ANDROID_ARCHS='arm64, armv7, x86, x86_64'
cd ..
cd cmake-builder/
git checkout master
git pull
cd .. && cd external/ffmpeg/
git checkout master
git pull
cd ../.. && cd build/
cmake --build . --parallel 8

**Comment by Viish** [comment]
Hi,

You're trying to use a fork of linphone-cmake-build that's 4 years old on master branch of our SDK for which we recently completely updated the cmake build process, so yes it won't work.
You may have better luck with release/5.2 branch that is still using the previous build scripts, and that is the currently latest release available.

Cheers,

**Comment by abhinav-android** [comment]
Thanks for quick reply. Can you please suggest proper steps that I need to take to build Linphone SDK for android and iOS with H263 and FFMPEG codes. Your help is much appreciated as I have been trying to build these SDKs for over a week but it keeps failing. Please help.

**Comment by Viish** [comment]
Sadly we no longer support H263 nor FFMPEG in our SDK, sorry.
