### ISSUE TITLE
TLS config problem

### ISSUE THREAD

**Issue by disolaterX** [BelledonneCommunications/linphone-android#1994]
Hi @Viish Hope you are doing awesome today.

I wanted to confirm to enable TLS in linphone is this enough. 

```
 core.config.setString("sip", "lient_cert_chain", PATH)
 core.config.setString("sip", "client_cert_key", PATH)
```

other than setting the transport to TLS and sip Server handling of TLS and It would be super great if You could point to me correct document, I am trying this with asterisk setup

Thanks

**Comment by Viish** [comment]
Hi @disolaterX,

Unless you want to do client certificate authentication you don't need to set those config option but simply the path to the root certificate used to sign your server certificate.
See https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Core.html#setRootCa-java.lang.String- or https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Core.html#setRootCaData-java.lang.String-

Cheers,

**Comment by disolaterX** [comment]
@Viish I have used tlsCert & tlsKey to setup and it was working should I be not using it
