### ISSUE TITLE
Building Local Linphone-SDK for android giving Error while building SDK for Andorid

### ISSUE THREAD

**Issue by jybin88** [BelledonneCommunications/linphone-android#1996]
NDK version: android-ndk-r20b
JAVA： 1.8
Android SDK version: android-sdk_r24

i am compiling latest source from git clone https://gitlab.linphone.org/BC/public/linphone-sdk.git --recursive
i am using ubuntu terminal :

followed these rules and having this error below :
please i need to build local native android linphone with bcg 729 enabled .?

root@fabrictest:~/linphone/linphone-sdk# mkdir build
root@fabrictest:~/linphone/linphone-sdk# cd build/
root@fabrictest:~/linphone/linphone-sdk/build# cmake .. -DLINPHONESDK_PLATFORM=Android -DLINPHONESDK_ANDROID_ARCHS=armeabi-v7a,arm64-v8a,x86,x86_64 -DENABLE_SILK=YES -DENABLE_G729==YES  -DENABLE_UNIT_TESTS=NO
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at cmake/CheckBuildToolsCommon.cmake:123 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  cmake/CheckBuildToolsAndroid.cmake:52 (include)
  CMakeLists.txt:79 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3") 
CMake Warning (dev) at cmake/CheckBuildToolsCommon.cmake:179 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  cmake/CheckBuildToolsAndroid.cmake:52 (include)
  CMakeLists.txt:79 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- 'pystache' python module found
-- 'six' python module found
**-- Setting build type to 'RelWithDebInfo' as none was specified
CMake Error at cmake/PlatformAndroid.cmake:40 (file):
  file COPY cannot find
  "/root/linphone/android-ndk-r20b/sources/cxx-stl/llvm-libc++/libs//libc++_shared.so":
  No such file or directory.
Call Stack (most recent call first):
  CMakeLists.txt:88 (include)**

-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- The ASM_NASM compiler identification is NASM
-- Found assembler: /usr/bin/nasm
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (1.7s)
-- Generating done (0.0s)
-- Build files have been written to: /root/linphone/linphone-sdk/build/Autotools
CMake Deprecation Warning at external/bv16-floatingpoint/CMakeLists.txt:23 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Package file name is BV16-2.1
CMake Deprecation Warning at external/decaf/CMakeLists.txt:8 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Warning (dev) at external/decaf/CMakeLists.txt:13 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

Generated source code in /root/linphone/linphone-sdk/build/external/decaf/src/GENERATED
Target architecture is x86_64
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.17") found components: doxygen missing components: dot
CMake Deprecation Warning at external/gsm/CMakeLists.txt:23 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- JsonCpp Version: 1.9.4
-- Looking for C++ include clocale
-- Looking for C++ include clocale - found
-- Looking for localeconv
-- Looking for localeconv - found
-- Looking for C++ include sys/types.h
-- Looking for C++ include sys/types.h - found
-- Looking for C++ include stdint.h
-- Looking for C++ include stdint.h - found
-- Looking for C++ include stddef.h
-- Looking for C++ include stddef.h - found
-- Check size of lconv
-- Check size of lconv - done
-- Performing Test HAVE_DECIMAL_POINT
-- Performing Test HAVE_DECIMAL_POINT - Success
CMake Deprecation Warning at external/libjpeg-turbo/CMakeLists.txt:23 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Using CMake's NASM integration
-- CMAKE_BUILD_TYPE = RelWithDebInfo
-- VERSION = 2.0.5, BUILD = 20230922
-- 64-bit build (x86_64)
-- 12-bit JPEG support disabled (WITH_12BIT = 0)
-- Arithmetic decoding support enabled (WITH_ARITH_DEC = 1)
-- Arithmetic encoding support enabled (WITH_ARITH_ENC = 1)
-- TurboJPEG API library enabled (WITH_TURBOJPEG = 1)
-- TurboJPEG Java wrapper disabled (WITH_JAVA = 0)
-- In-memory source/destination managers enabled (WITH_MEM_SRCDST = 1)
-- Emulating libjpeg API/ABI v6.2 (WITH_JPEG7 = 0, WITH_JPEG8 = 0)
-- libjpeg API shared library version = 62.3.0
-- Compiler flags =  -O3 -g -DNDEBUG
-- Linker flags =  
-- Check size of size_t
-- Check size of size_t - done
-- Check size of unsigned long
-- Check size of unsigned long - done
-- Performing Test HAVE_BUILTIN_CTZL
-- Performing Test HAVE_BUILTIN_CTZL - Success
-- Looking for include file locale.h
-- Looking for include file locale.h - found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Looking for memset
-- Looking for memset - found
-- Looking for memcpy
-- Looking for memcpy - found
-- Check size of unsigned char
-- Check size of unsigned char - done
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Performing Test INCOMPLETE_TYPES
-- Performing Test INCOMPLETE_TYPES - Success
-- Compiler supports pointers to undefined structures.
-- Performing Test RIGHT_SHIFT_IS_UNSIGNED
-- Performing Test RIGHT_SHIFT_IS_UNSIGNED - Failed
-- Performing Test __CHAR_UNSIGNED__
-- Performing Test __CHAR_UNSIGNED__ - Failed
-- Performing Test INLINE_WORKS
-- Performing Test INLINE_WORKS - Success
-- INLINE = __inline__ __attribute__((always_inline)) (FORCE_INLINE = 1)
-- Performing Test HAVE_THREAD_LOCAL
-- Performing Test HAVE_THREAD_LOCAL - Success
-- THREAD_LOCAL = __thread
-- Performing Test HAVE_VERSION_SCRIPT
-- Performing Test HAVE_VERSION_SCRIPT - Success
-- Linker supports GNU-style version scripts
-- CMAKE_EXECUTABLE_SUFFIX = 
-- CMAKE_ASM_NASM_COMPILER = /usr/bin/nasm
-- CMAKE_ASM_NASM_OBJECT_FORMAT = elf64
-- CMAKE_ASM_NASM_FLAGS =  -DELF -D__x86_64__ -DPIC 
-- SIMD extensions: x86_64 (WITH_SIMD = 1)
-- FLOATTEST = sse
-- RPM architecture = x86_64, DEB architecture = amd64
CMake Deprecation Warning at external/libxml2/CMakeLists.txt:23 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for poll.h
-- Looking for poll.h - found
-- Looking for sys/poll.h
-- Looking for sys/poll.h - found
-- Looking for sys/uio.h
-- Looking for sys/uio.h - found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for sys/time.h
-- Looking for sys/time.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for sys/shm.h
-- Looking for sys/shm.h - found
-- Looking for windows.h
-- Looking for windows.h - not found
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for alloca.h
-- Looking for alloca.h - found
-- Looking for ctype.h
-- Looking for ctype.h - found
-- Looking for dirent.h
-- Looking for dirent.h - found
-- Looking for errno.h
-- Looking for errno.h - found
-- Looking for malloc.h
-- Looking for malloc.h - found
-- Looking for stdarg.h
-- Looking for stdarg.h - found
-- Looking for time.h
-- Looking for time.h - found
-- Looking for ansidecl.h
-- Looking for ansidecl.h - not found
-- Looking for ieeefp.h
-- Looking for ieeefp.h - not found
-- Looking for nan.h
-- Looking for nan.h - not found
-- Looking for math.h
-- Looking for math.h - found
-- Looking for limits.h
-- Looking for limits.h - found
-- Looking for fp_class.h
-- Looking for fp_class.h - not found
-- Looking for float.h
-- Looking for float.h - found
-- Looking for sys/socket.h
-- Looking for sys/socket.h - found
-- Looking for netinet/in.h
-- Looking for netinet/in.h - found
-- Looking for arpa/inet.h
-- Looking for arpa/inet.h - found
-- Looking for netdb.h
-- Looking for netdb.h - found
-- Looking for sys/select.h
-- Looking for sys/select.h - found
-- Looking for sys/mman.h
-- Looking for sys/mman.h - found
-- Looking for sys/timeb.h
-- Looking for sys/timeb.h - found
-- Looking for signal.h
-- Looking for signal.h - found
-- Looking for arpa/nameser.h
-- Looking for arpa/nameser.h - found
-- Looking for resolv.h
-- Looking for resolv.h - found
-- Looking for dl.h
-- Looking for dl.h - not found
-- Looking for va_copy
-- Looking for va_copy - found
CMake Deprecation Warning at external/libyuv/CMakeLists.txt:5 (CMAKE_MINIMUM_REQUIRED):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Found TurboJpeg: turbojpeg  
Building ver.: 0.0.1763
Packaging for: amd-64
-- Found Python3: /usr/bin/python3.8 (found version "3.8.10") found components: Interpreter 
-- Performing Test C_COMPILER_SUPPORTS_WFORMAT_SIGNEDNESS
-- Performing Test C_COMPILER_SUPPORTS_WFORMAT_SIGNEDNESS - Success
-- Looking for byteswap.h
-- Looking for byteswap.h - found
-- Looking for machine/types.h
-- Looking for machine/types.h - not found
-- Looking for sys/int_types.h
-- Looking for sys/int_types.h - not found
-- Looking for winsock2.h
-- Looking for winsock2.h - not found
-- Looking for sigaction
-- Looking for sigaction - found
-- Looking for inet_aton
-- Looking for inet_aton - found
-- Looking for usleep
-- Looking for usleep - found
-- Check size of uint8_t
-- Check size of uint8_t - done
-- Check size of uint16_t
-- Check size of uint16_t - done
-- Check size of uint32_t
-- Check size of uint32_t - done
-- Check size of uint64_t
-- Check size of uint64_t - done
-- Check size of int32_t
-- Check size of int32_t - done
-- Check size of unsigned long
-- Check size of unsigned long - done
-- Check size of unsigned long long
-- Check size of unsigned long long - done
-- Performing Test HAVE_INLINE
-- Performing Test HAVE_INLINE - Success
Found Mbedtls targets
SRTP include Mbedtls include dirs 
CMake Deprecation Warning at external/opus/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Deprecation Warning at external/opus/opus_functions.cmake:5 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  external/opus/CMakeLists.txt:3 (include)

-- Opus library version: 0.8.0
-- Found Git: /usr/bin/git (found version "2.25.1") 
fatal: No names found, cannot describe anything.
-- Opus package version: 1.3.1
-- Opus project version: 1.3.1
CMake Deprecation Warning at external/opus/opus_functions.cmake:5 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  external/opus/opus_config.cmake:1 (include)
  external/opus/CMakeLists.txt:41 (include)

-- Looking for floor in m
-- Looking for floor in m - found
-- Looking for cpuid.h
-- Looking for cpuid.h - found
-- Check SIMD support by compiler
-- Looking for xmmintrin.h
-- Looking for xmmintrin.h - found
-- Performing Test SSE1_SUPPORTED
-- Performing Test SSE1_SUPPORTED - Success
-- Looking for emmintrin.h
-- Looking for emmintrin.h - found
-- Performing Test SSE2_SUPPORTED
-- Performing Test SSE2_SUPPORTED - Success
-- Looking for smmintrin.h
-- Looking for smmintrin.h - found
-- Performing Test SSE4_1_SUPPORTED
-- Performing Test SSE4_1_SUPPORTED - Success
-- Looking for immintrin.h
-- Looking for immintrin.h - found
-- Performing Test AVX_SUPPORTED
-- Performing Test AVX_SUPPORTED - Success
CMake Deprecation Warning at external/opus/opus_functions.cmake:5 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  external/opus/opus_sources.cmake:1 (include)
  external/opus/CMakeLists.txt:42 (include)

-- Performing Test STACK_PROTECTION_STRONG_SUPPORTED
-- Performing Test STACK_PROTECTION_STRONG_SUPPORTED - Success
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
CMake Deprecation Warning at external/sqlite3/CMakeLists.txt:23 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Deprecation Warning at external/soci/CMakeLists.txt:14 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Looking for __i386__
-- Looking for __i386__ - not found
-- Looking for __x86_64__
-- Looking for __x86_64__ - found
-- Looking for __arm__
-- Looking for __arm__ - not found
-- Configuring SOCI: 
-- SOCI_VERSION                             = 4.0.0 
-- SOCI_ABI_VERSION                         = 4.0 
-- SOCI_SHARED                              = ON 
-- SOCI_STATIC                              = OFF 
-- SOCI_FRAMEWORK                           =  
-- SOCI_TESTS                               = OFF 
-- SOCI_ASAN                                = OFF 
-- SOCI_CXX_C11                             =  
-- LIB_SUFFIX                               = 64 
-- Looking for SOCI dependencies: 
-- CMAKE_THREAD_LIBS_INIT                   = -lpthread 
-- MySQL: disabled, since WITH_MYSQL=OFF 
-- ODBC: disabled, since WITH_ODBC=OFF 
-- Oracle: disabled, since WITH_ORACLE=OFF 
-- PostgreSQL: disabled, since WITH_POSTGRESQL=OFF 
-- SQLite3: 
CMake Warning (dev) at /usr/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (SQLITE3)
  does not match the name of the calling package (SQLite3).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  external/soci/cmake/modules/FindSQLite3.cmake:67 (find_package_handle_standard_args)
  external/soci/cmake/dependencies/SQLite3.cmake:3 (find_package)
  external/soci/cmake/SociDependencies.cmake:74 (include)
  external/soci/CMakeLists.txt:93 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- SQLITE3_INCLUDE_DIR                      = $<INSTALL_INTERFACE:include> $<BUILD_INTERFACE:/root/linphone/linphone-sdk/external/sqlite3> 
-- SQLITE3_LIBRARIES                        = sqlite3 
-- Firebird: disabled, since WITH_FIREBIRD=OFF 
-- DB2: disabled, since WITH_DB2=OFF 
-- Configuring SOCI core library: 
-- SOCI_CORE_TARGET                         = soci_core 
-- SOCI_CORE_TARGET_OUTPUT_NAME             = soci_core 
-- SOCI_CORE_DEPS_LIBS                      = -lpthread /usr/lib/x86_64-linux-gnu/libdl.so 
-- SOCI_CORE_INCLUDE_DIRS                   = /root/linphone/linphone-sdk/build/external/soci /root/linphone/linphone-sdk/external/soci/include /root/linphone/linphone-sdk/build/external/soci/include /root/linphone/linphone-sdk/external/soci/include/private /root/linphone/linphone-sdk/build/external/soci/src/core 
-- WITH_BOOST                               =  
-- COMPILE_DEFINITIONS                      = SOCI_ABI_VERSION="4.0" HAVE_DL=1 SOCI_LIB_PREFIX="libsoci_" SOCI_LIB_SUFFIX=".so" SOCI_DEBUG_POSTFIX="" 
-- 
-- Configuring SOCI backend libraries: 
CMake Warning (dev) at /usr/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (SQLITE3)
  does not match the name of the calling package (SQLite3).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  external/soci/cmake/modules/FindSQLite3.cmake:67 (find_package_handle_standard_args)
  external/soci/src/backends/CMakeLists.txt:17 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- SQLite3 - SOCI backend for SQLite 3 
-- SOCI_SQLITE3                             = ON 
-- SOCI_SQLITE3_TARGET                      = soci_sqlite3 
-- SOCI_SQLITE3_OUTPUT_NAME                 = soci_sqlite3 
-- SOCI_SQLITE3_COMPILE_DEFINITIONS         = SOCI_ABI_VERSION="4.0" HAVE_DL=1 
-- SOCI_SQLITE3_INCLUDE_DIRECTORIES         = /root/linphone/linphone-sdk/build/external/soci /root/linphone/linphone-sdk/external/soci/include /root/linphone/linphone-sdk/build/external/soci/include /root/linphone/linphone-sdk/external/soci/include/private /root/linphone/linphone-sdk/external/soci/include/private $<INSTALL_INTERFACE:include> $<BUILD_INTERFACE:/root/linphone/linphone-sdk/external/sqlite3> 
-- 
-- 
-- Package file name is SOCI-4.0.0
-- Looking for getopt.h
-- Looking for getopt.h - found
-- Looking for sys/audioio.h
-- Looking for sys/audioio.h - not found
-- Looking for sys/soundcard.h
-- Looking for sys/soundcard.h - found
-- Looking for getopt_long
-- Looking for getopt_long - found
-- Performing Test VAR_ARRAYS
-- Performing Test VAR_ARRAYS - Success
-- Performing Test HAS_ALLOCA
-- Performing Test HAS_ALLOCA - Success
-- Performing Test HAS_SSE
-- Performing Test HAS_SSE - Success
-- Performing Test HAS_VISIBILITY
-- Performing Test HAS_VISIBILITY - Success
-- Check size of short
-- Check size of short - done
-- Check size of int
-- Check size of int - done
-- Check size of long
-- Check size of long - done
CMake Deprecation Warning at external/xerces-c/CMakeLists.txt:23 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Looking for langinfo.h
-- Looking for langinfo.h - found
-- Looking for nl_types.h
-- Looking for nl_types.h - found
-- Looking for sys/param.h
-- Looking for sys/param.h - found
-- Looking for wchar.h
-- Looking for wchar.h - found
-- Looking for wctype.h
-- Looking for wctype.h - found
-- Looking for CoreServices/CoreServices.h
-- Looking for CoreServices/CoreServices.h - not found
-- Looking for endian.h
-- Looking for endian.h - found
-- Looking for machine/endian.h
-- Looking for machine/endian.h - not found
-- Looking for arpa/nameser_compat.h
-- Looking for arpa/nameser_compat.h - found
-- Looking for stdio.h
-- Looking for stdio.h - found
-- Looking for C++ include stdbool.h
-- Looking for C++ include stdbool.h - found
-- Looking for getcwd
-- Looking for getcwd - found
-- Looking for pathconf
-- Looking for pathconf - found
-- Looking for realpath
-- Looking for realpath - found
-- Looking for getaddrinfo
-- Looking for getaddrinfo - found
-- Looking for gethostbyaddr
-- Looking for gethostbyaddr - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for socket
-- Looking for socket - found
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Looking for ftime
-- Looking for ftime - found
-- Looking for gettimeofday
-- Looking for gettimeofday - found
-- Looking for memmove
-- Looking for memmove - found
-- Looking for nl_langinfo
-- Looking for nl_langinfo - found
-- Looking for setlocale
-- Looking for setlocale - found
-- Looking for strcasecmp
-- Looking for strcasecmp - found
-- Looking for strncasecmp
-- Looking for strncasecmp - found
-- Looking for stricmp
-- Looking for stricmp - not found
-- Looking for strnicmp
-- Looking for strnicmp - not found
-- Looking for strchr
-- Looking for strchr - found
-- Looking for strdup
-- Looking for strdup - found
-- Looking for strrchr
-- Looking for strrchr - found
-- Looking for strstr
-- Looking for strstr - found
-- Looking for strtol
-- Looking for strtol - found
-- Looking for strtoul
-- Looking for strtoul - found
-- Looking for towupper
-- Looking for towupper - found
-- Looking for towlower
-- Looking for towlower - found
-- Looking for mblen
-- Looking for mblen - found
-- Looking for wcsupr
-- Looking for wcsupr - not found
-- Looking for wcslwr
-- Looking for wcslwr - not found
-- Looking for wcsnicmp
-- Looking for wcsnicmp - not found
-- Looking for wcsicmp
-- Looking for wcsicmp - not found
-- Check size of int
-- Check size of int - done
-- Check size of long
-- Check size of long - done
-- Check size of long long
-- Check size of long long - done
-- Check size of short
-- Check size of short - done
-- Check size of wchar_t
-- Check size of wchar_t - done
-- Check size of __int64
-- Check size of __int64 - failed
CMake Deprecation Warning at external/zlib/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Check size of off64_t
-- Check size of off64_t - done
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Performing Test COMPILER_NEEDS_FLOAT_STORE
-- Performing Test COMPILER_NEEDS_FLOAT_STORE - Success
-- Found Git: /usr/bin/git (found suitable version "2.25.1", minimum required is "1.7.10") 
-- MBEDTLS Enabled
-- Found MbedTLS: mbedtls  
-- Using mbedTLS v3
-- Found Decaf: decaf  
-- Using Decaf
-- DTLS SRTP available
-- Found BCUnit: bcunit (Required is at least version "3.0.2") 
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Looking for dladdr in dl
-- Looking for dladdr in dl - found
-- Found BCToolbox: bctoolbox (Required is at least version "5.3.0")  
-- Looking for sys/audio.h
-- Looking for sys/audio.h - not found
-- Performing Test HAVE_ATOMIC
-- Performing Test HAVE_ATOMIC - Success
-- Looking for arc4random
-- Looking for arc4random - not found
-- Looking for recvmsg
-- Looking for recvmsg - found
-- Looking for sendmsg
-- Looking for sendmsg - found
-- Looking for sqrt in m
-- Looking for sqrt in m - found
-- Found BCToolbox: bctoolbox (Required is at least version "5.3.0") found components: tester 
-- Found SQLite3: sqlite3  
-- Package file name is bcg729-1.1.1
CMake Deprecation Warning at bcmatroska2/CMakeLists.txt:23 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Found BCToolbox: bctoolbox (Required is at least version "5.3.0")  
-- Package file name is bcmatroska2-0.23
-- Looking for dlopen in dl
-- Looking for dlopen in dl - found
-- Found Ortp: ortp (Required is at least version "5.3.0")  
-- Found SRTP: srtp2 (Required is at least version "2") 
-- Found BZRTP: bzrtp (Required is at least version "5.3.0")  
-- Found GSM: gsm  
-- Found BV16: bv16  
-- Found Opus: opus  
-- Found Speex: speex  
-- Found SpeexDSP: speexdsp  
-- Could NOT find PulseAudio (missing: PulseAudio_TARGET) 
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY OPENGL_INCLUDE_DIR) 
-- Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY OPENGL_INCLUDE_DIR GLX) 
-- Found VPX: libvpx  
-- Found BCMatroska2: bcmatroska2 (Required is at least version "0.23") 

**CMake Error at mediastreamer2/CMakeLists.txt:331 (message):
  Could not find a support sound driver API.  Use -DENABLE_SOUND=NO if you
  don't care about having sound.**

**Comment by Viish** [comment]
Hi,

Lots of things, but first one is the build system changed on master.
Here's the proper cmake build commands (from README file):
```
cmake --preset=android-sdk -B build-android -DLINPHONESDK_ANDROID_ARCHS=arm64 <extra-variable-definitions>

cmake --build build-android --parallel <number of jobs>
```

That being said, you'll also need to update your java SDK to 17 and you should use NDK r25b.

Cheers,

**Comment by jybin88** [comment]
Thanks for your response.

I have update java SDK to 17 and  use NDK r25c(not found r25b).

cmake build commands:
`cmake --preset=android-sdk -B build-android -DLINPHONESDK_ANDROID_ARCHS=armeabi-v7a,arm64-v8a,x86,x86_64 -DENABLE_G729==YES -DENABLE_UNIT_TESTS=NO

cmake --build build-android --parallel 8
`
followed these rules and having this error below :

/root/linphone/linphone-sdk/mediastreamer2/src/voip/ice.c:1421:14: warning: 'rtp_session_create_packet_raw' is deprecated [-Wdeprecated-declarations]
        mblk_t *m = rtp_session_create_packet_raw((const uint8_t *)buf, len);
                    ^
/root/linphone/linphone-sdk/ortp/include/ortp/rtpsession.h:642:13: note: 'rtp_session_create_packet_raw' has been explicitly marked deprecated here
ORTP_PUBLIC ORTP_DEPRECATED mblk_t *rtp_session_create_packet_raw(const uint8_t *packet, size_t packet_size);
            ^
/root/linphone/linphone-sdk/ortp/include/ortp/port.h:29:40: note: expanded from macro 'ORTP_DEPRECATED'
#define ORTP_DEPRECATED __attribute__((deprecated))
                                       ^
/root/linphone/linphone-sdk/mediastreamer2/src/voip/ice.c:2817:35: error: assigning to 'MSTimeSpec' (aka 'struct bctoolboxTimeSpec') from incompatible type 'const ortpTimeSpec' (aka 'const struct ortpTimeSpec')
                                cl->session->gathering_end_ts = evt_data->ts;
                                                              ^ ~~~~~~~~~~~~
/root/linphone/linphone-sdk/mediastreamer2/src/voip/ice.c:3104:49: error: passing 'const ortpTimeSpec' (aka 'const struct ortpTimeSpec') to parameter of incompatible type 'MSTimeSpec' (aka 'struct bctoolboxTimeSpec')
                ice_set_transaction_response_time(cl, &tr_id, evt_data->ts);
                                                              ^~~~~~~~~~~~
/root/linphone/linphone-sdk/mediastreamer2/src/voip/ice.c:3054:91: note: passing argument to parameter 'response_time' here
static void ice_set_transaction_response_time(IceCheckList *cl, UInt96 *tr_id, MSTimeSpec response_time) {
                                                                                          ^
/root/linphone/linphone-sdk/mediastreamer2/src/voip/ice.c:3139:49: error: passing 'const ortpTimeSpec' (aka 'const struct ortpTimeSpec') to parameter of incompatible type 'MSTimeSpec' (aka 'struct bctoolboxTimeSpec')
                ice_set_transaction_response_time(cl, &tr_id, evt_data->ts);
                                                              ^~~~~~~~~~~~
/root/linphone/linphone-sdk/mediastreamer2/src/voip/ice.c:3054:91: note: passing argument to parameter 'response_time' here
static void ice_set_transaction_response_time(IceCheckList *cl, UInt96 *tr_id, MSTimeSpec response_time) {
                                                                                          ^
1 warning and 3 errors generated.
make[5]: *** [mediastreamer2/src/CMakeFiles/mediastreamer2.dir/build.make:804: mediastreamer2/src/CMakeFiles/mediastreamer2.dir/voip/ice.c.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:4152: mediastreamer2/src/CMakeFiles/mediastreamer2.dir/all] Error 2
make[3]: *** [Makefile:156: all] Error 2
make[2]: *** [CMakeFiles/android-x86_64.dir/build.make:72: CMakeFiles/android-x86_64] Error 2
make[1]: *** [CMakeFiles/Makefile2:199: CMakeFiles/android-x86_64.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by Asnais-gh** [comment]
you fix it?
