### ISSUE TITLE
How can I get the plain/clear password from the app to use it

### ISSUE THREAD

**Issue by adeshjohnson** [BelledonneCommunications/linphone-android#20]
Hello:

I need to know the clear password from a SIP account. How can I do it?

Thank you. You have a great app!!!
John.

**Comment by DatBewar** [comment]
Hello,
You can't from linphone, you can just see HA1, if you forgot your password just ask your provider for a reset.

Best regards

**Comment by adeshjohnson** [comment]
Hello:


I am needing the password for programming to use it with another app. So, if clear password is not possible to be got it but so HA1. How could I get the HA1 in the code?


Thank you DatBewar.




________________________________

**Comment by hadidez** [comment]
LinphonePreferences.instance().getAccountHa1(0)
