### ISSUE TITLE
Does not rebuild properly in Android Studio

### ISSUE THREAD

**Issue by Lucas9595** [BelledonneCommunications/linphone-android#200]
Someone please help me. I cannot for the life of me work out why Android Studio doesn't recognize so many of the modules it needs to import. I doubt that the answer is to delete every line that mentions a module it doesn't like, as there are alot of files. 

Can someone please help me understand what I need to do to get this source code working in Android Studio. Below is the FULL LOG of what I am facing

Information:Gradle tasks [clean, :assembleDebug]
/Users/lucascessford/StudioProjects/linphone-android/src/android/org/linphone/AboutFragment.java
Error:(21, 25) error: package org.linphone.core does not exist
Error:(22, 38) error: package org.linphone.core.LinphoneCore does not exist
Error:(23, 25) error: package org.linphone.core does not exist
Error:(24, 32) error: package org.linphone.mediastream does not exist
Error:(47, 2) error: cannot find symbol class LinphoneCoreListenerBase
/Users/lucascessford/StudioProjects/linphone-android/src/android/org/linphone/ui/PreferencesListFragment.java
Error:(26, 32) error: package org.linphone.mediastream does not exist
/Users/lucascessford/StudioProjects/linphone-android/src/android/org/linphone/AccountPreferencesFragment.java
Error:(26, 25) error: package org.linphone.core does not exist
Error:(27, 25) error: package org.linphone.core does not exist
Error:(28, 25) error: package org.linphone.core does not exist
Error:(29, 25) error: package org.linphone.core does not exist
Error:(30, 25) error: package org.linphone.core does not exist
Error:(31, 32) error: package org.linphone.mediastream does not exist
Error:(56, 106) error: package LinphoneAccountCreator does not exist
Error:(63, 10) error: cannot find symbol class LinphoneAccountCreator
Error:(600, 44) error: cannot find symbol class LinphoneAccountCreator
Error:(600, 105) error: package LinphoneAccountCreator does not exist
Error:(604, 45) error: cannot find symbol class LinphoneAccountCreator
Error:(604, 106) error: package LinphoneAccountCreator does not exist
Error:(609, 47) error: cannot find symbol class LinphoneAccountCreator
Error:(609, 108) error: package LinphoneAccountCreator does not exist
Error:(614, 59) error: cannot find symbol class LinphoneAccountCreator
Error:(614, 120) error: package LinphoneAccountCreator does not exist
Error:(619, 55) error: cannot find symbol class LinphoneAccountCreator
Error:(619, 116) error: package LinphoneAccountCreator does not exist
Error:(624, 49) error: cannot find symbol class LinphoneAccountCreator
Error:(624, 110) error: package LinphoneAccountCreator does not exist
Error:(629, 52) error: cannot find symbol class LinphoneAccountCreator
Error:(629, 113) error: package LinphoneAccountCreator does not exist
Error:(634, 46) error: cannot find symbol class LinphoneAccountCreator
Error:(634, 107) error: package LinphoneAccountCreator does not exist
Error:(639, 48) error: cannot find symbol class LinphoneAccountCreator
Error:(639, 109) error: package LinphoneAccountCreator does not exist
Error:(643, 46) error: cannot find symbol class LinphoneAccountCreator
Error:(643, 107) error: package LinphoneAccountCreator does not exist
/Users/lucascessford/StudioProjects/linphone-android/src/android/org/linphone/LinphonePreferences.java
Error:(27, 25) error: package org.linphone.core does not exist
Error:(28, 41) error: package org.linphone.core.LinphoneAddress does not exist
Error:(29, 25) error: package org.linphone.core does not exist
Error:(30, 25) error: package org.linphone.core does not exist
Error:(31, 38) error: package org.linphone.core.LinphoneCore does not exist
Error:(32, 38) error: package org.linphone.core.LinphoneCore does not exist
Error:(33, 38) error: package org.linphone.core.LinphoneCore does not exist
Error:(34, 38) error: package org.linphone.core.LinphoneCore does not exist
Error:(35, 25) error: package org.linphone.core does not exist
Error:(36, 25) error: package org.linphone.core does not exist
Error:(37, 25) error: package org.linphone.core does not exist
Error:(38, 25) error: package org.linphone.core does not exist
Error:(39, 25) error: package org.linphone.core does not exist
Error:(40, 25) error: package org.linphone.core does not exist
Error:(41, 32) error: package org.linphone.mediastream does not exist
Error:(81, 10) error: cannot find symbol class LinphoneCore
Error:(88, 9) error: cannot find symbol class LpConfig
Error:(151, 10) error: cannot find symbol class LinphoneProxyConfig
Error:(158, 10) error: cannot find symbol class LinphoneAuthInfo
Error:(176, 10) error: cannot find symbol class LinphoneAuthInfo
Error:(190, 28) error: cannot find symbol class LinphoneAuthInfo
Error:(433, 9) error: cannot find symbol class TransportType
Error:(1049, 10) error: cannot find symbol class LinphoneNatPolicy
Error:(1143, 9) error: cannot find symbol class MediaEncryption
Error:(1147, 33) error: cannot find symbol class MediaEncryption
Error:(1276, 10) error: cannot find symbol class TunnelConfig
Error:(1278, 9) error: cannot find symbol class TunnelConfig
Error:(1367, 9) error: cannot find symbol class AdaptiveRateAlgorithm
Error:(1371, 39) error: cannot find symbol class AdaptiveRateAlgorithm
Error:(1484, 9) error: cannot find symbol class LinphoneLimeState
Error:(1488, 32) error: cannot find symbol class LinphoneLimeState
Error:(195, 11) error: cannot find symbol class LinphoneCore
Error:(208, 11) error: cannot find symbol class TransportType
Error:(218, 25) error: cannot find symbol class LinphoneCore
Error:(222, 38) error: cannot find symbol class TransportType
Error:(326, 39) error: cannot find symbol class LinphoneCoreException
/Users/lucascessford/StudioProjects/linphone-android/src/android/org/linphone/StatusFragment.java
Error:(42, 25) error: package org.linphone.core does not exist
Error:(43, 25) error: package org.linphone.core does not exist
Error:(44, 25) error: package org.linphone.core does not exist
Error:(45, 25) error: package org.linphone.core does not exist
Error:(46, 38) error: package org.linphone.core.LinphoneCore does not exist
Error:(47, 38) error: package org.linphone.core.LinphoneCore does not exist
Error:(48, 25) error: package org.linphone.core does not exist
Error:(49, 25) error: package org.linphone.core does not exist
Error:(50, 25) error: package org.linphone.core does not exist
Error:(51, 32) error: package org.linphone.mediastream does not exist
/Users/lucascessford/StudioProjects/linphone-android/src/android/org/linphone/assistant/AssistantActivity.java
Error:(35, 25) error: package org.linphone.core does not exist
Error:(36, 25) error: package org.linphone.core does not exist
Error:(37, 25) error: package org.linphone.core does not exist
Error:(38, 41) error: package org.linphone.core.LinphoneAddress does not exist
Error:(39, 25) error: package org.linphone.core does not exist
Error:(40, 25) error: package org.linphone.core does not exist
Error:(41, 38) error: package org.linphone.core.LinphoneCore does not exist
Error:(42, 25) error: package org.linphone.core does not exist
Error:(43, 25) error: package org.linphone.core does not exist
Error:(44, 25) error: package org.linphone.core does not exist
Error:(45, 25) error: package org.linphone.core does not exist
Error:(46, 32) error: package org.linphone.mediastream does not exist
Error:(47, 32) error: package org.linphone.mediastream does not exist
Error:(48, 26) error: package org.linphone.tools does not exist
Error:(84, 150) error: package LinphoneAccountCreator does not exist
Error:(93, 10) error: cannot find symbol class LinphoneCoreListenerBase
Error:(94, 10) error: cannot find symbol class LinphoneAddress
Error:(101, 10) error: cannot find symbol class LinphoneAccountCreator
Error:(104, 9) error: cannot find symbol class DialPlan
Error:(230, 52) error: cannot find symbol class LinphoneProxyConfig
Error:Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED in 7s
Information:101 errors
Information:0 warnings
Information:See complete output in console

**Comment by ProudNoob** [comment]
Have you run ./prepare.py first then ./make?

**Comment by brijeta24** [comment]
i am having the same issue can someone help me...

**Comment by deepbhavsar** [comment]
Hello, 
`org.linphone.core` package is not resolved in Android Studio.

Followed all steps which is given in git. run **./prepare.py** and all done.

Please help. I am facing same issues.
