### ISSUE TITLE
Not able to process incoming video anymore

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-android#2002]
Hi @Viish 

1. **Describe the bug** (mandatory)

I think it is no longer possible to receive video while I'm pretty sure this has worked before. It looks like the incoming INVITE contains the video sdp map is ignored by Linphone.

Relavant part of INVITE:

> v=0
o=543210 3799 2772 IN IP4 172.17.104.153
s=Talk
c=IN IP4 172.17.104.153
t=0 0
a=rtcp-xr:rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics
a=record:off
m=audio 57939 RTP/AVP 8 96 101 97
a=rtpmap:96 opus/48000/2
a=fmtp:96 useinbandfec=1
a=rtpmap:101 telephone-event/8000
a=rtpmap:97 telephone-event/48000
a=rtcp:41326
a=rtcp-fb:* trr-int 5000
a=rtcp-fb:* ccm tmmbr
m=video 52131 RTP/AVP 96 97
a=rtpmap:96 H264/90000
a=fmtp:96 profile-level-id=42801F
a=rtpmap:97 H265/90000
a=fmtp:97 
a=rtcp:42816
a=rtcp-fb:* trr-int 5000
a=rtcp-fb:* ccm tmmbr
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 ccm fir
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 ccm fir

Processing the SDP:

> 2023-10-03 15:52:43:965 [be.uzgent.uzlinphone/liblinphone] MESSAGE Found payload PCMA/8000 fmtp=
2023-10-03 15:52:43:965 [be.uzgent.uzlinphone/liblinphone] MESSAGE Found payload telephone-event/8000 fmtp=0-16
2023-10-03 15:52:43:967 [be.uzgent.uzlinphone/liblinphone] MESSAGE Found payload (null)/0 fmtp=
2023-10-03 15:52:43:967 [be.uzgent.uzlinphone/liblinphone] MESSAGE Found payload (null)/0 fmtp=
2023-10-03 15:52:43:967 [be.uzgent.uzlinphone/liblinphone] MESSAGE Doing SDP offer/answer process of type outgoing
2023-10-03 15:52:43:967 [be.uzgent.uzlinphone/liblinphone] MESSAGE Processing for stream 0

> MESSAGE CallSession [0x73cd590498]: disabling video in our call params because the remote doesn't want it

2. **To Reproduce** (mandatory)

Receive incoming videocall while video is enabled on both sides.

3. **Expected behavior** (mandatory)

Should be able to enable video when incoming call is answered.

4. **Please complete the following information** (mandatory)

 - Device: Samsung XCover 5
 - OS: Android 13
 - Version of the App 5.1.1
 - Version of the SDK 5.2.104-pre.1/f46ee91
 - Where you did got it from local build
 - Please tell us if your Android is a Lineage OS or another variant. - stock android

If you are using a SDK that isn't the latest release, please update first as it's likely your issue is already solved.

5. **SDK logs** (mandatory)

[no video.txt](https://github.com/BelledonneCommunications/linphone-android/files/12793252/no.video.txt)

**Comment by AndreaGianarda** [comment]
Hi,

Can you please upload the logs where also the start of the core is show, please?
To get that:
1. clear the logs.
2. kill your app
3. Open your app
4. reproduce the bug
5. send us the logs

Thanks,

Andrea

**Comment by driesken** [comment]
Hi @AndreaGianarda 

I've attached a new log as requested.
[full no video log.txt](https://github.com/BelledonneCommunications/linphone-android/files/12800125/full.no.video.log.txt)

I've noticed the following behavior:

2023-10-04 08:00:16:405 -> Initial INVITE
2023-10-04 08:00:16:764 -> Video disabled
2023-10-04 08:00:22:577 -> RE-INVITE

**Comment by AndreaGianarda** [comment]
Hi,

Your server UZPBX is refusing video streams by putting the RTP port to 0:
SIP/2.0 200 OK
Via: SIP/2.0/TLS 172.17.104.153:60504;rport=60504;received=172.17.104.153;branch=z9hG4bK.gXeheS~tx
Call-ID: 400b4ce5-febe-4506-bc34-4aab2705906c
From: <sip:543210@192.168.17.144>;tag=ttpRwZv
To: "DDG TEST" <sip:54322@192.168.96.97>;tag=f5668884-51aa-49a7-8243-3039a9705bd0
CSeq: 111 INVITE
Contact: <sip:asterisk@192.168.96.97:5060;alias=192.168.96.97~50327~2;transport=TCP>
Allow: OPTIONS, REGISTER, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, MESSAGE, REFER
Supported: 100rel, timer, replaces, norefersub
Server: UZPBX
Content-Type: application/sdp
Content-Length:   280

v=0
o=- 1041424478 1041424479 IN IP4 193.191.170.56
s=Asterisk
c=IN IP4 193.191.170.56
t=0 0
m=audio 17796 RTP/AVP 8 101
a=maxptime:150
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=sendrecv
a=rtcp:17797
a=ptime:20
m=video 0 RTP/AVP 96 97

Furthermore, the SDP sent by your server sets also payloads 96 and 97 without defining them. According to RFC3551 (https://www.rfc-editor.org/rfc/rfc3551#page-32) they are dynamic, hence the logs here below from Linphone:
2023-10-03 15:52:43:967 [be.uzgent.uzlinphone/liblinphone] MESSAGE Found payload (null)/0 fmtp=
2023-10-03 15:52:43:967 [be.uzgent.uzlinphone/liblinphone] MESSAGE Found payload (null)/0 fmtp=

H264 (https://www.rfc-editor.org/rfc/rfc6184#page-57 and https://www.rfc-editor.org/rfc/rfc6190#page-75) and H265 (https://www.rfc-editor.org/rfc/rfc7798#page-64) RFCs are not followed if your server accept both H264 and H265 codecs.

Hope this helps,

Andrea
