### ISSUE TITLE
SSL cert dead

### ISSUE THREAD

**Issue by dac2020** [BelledonneCommunications/linphone-android#2003]
I'm not sure if this is the same authors or if you know the other person. 
I was trying to install but perhaps someone could contact the owner.

`
==> ERROR: Failure while downloading https://gitlab.linphone.org/BC/public/linphone-desktop/
Failed to build linphone-desktop
`

**Comment by Viish** [comment]
Hi @dac2020,

Everything is back to normal.

Cheers,
