### ISSUE TITLE
Declining an Incoming Call with Decline/Terminate/TerminateAllCalls() does not disconnect the Remote party

### ISSUE THREAD

**Issue by cjkarande** [BelledonneCommunications/linphone-android#2005]
Hello

1. **Describe the bug** (mandatory)

Declining an Incoming Call with Decline/Terminate/TerminateAllCalls() does not disconnect the call for Remote party. While the local Call gets disconnected, for the Remote party, the Dialing tone continues.

2. **To Reproduce** (mandatory)
I tried with the following 3 APIs the result was the same
a)  if (Core.CallsNb > 0)
           Core.TerminateAllCalls();

b) Call CurrentCall { get { return Core.CurrentCall == null ? Core.Calls.First() : Core.CurrentCall; } }
     if (Core.CallsNb > 0)
           CurrentCall.Decline((Reason)reason);

c) if (Core.CallsNb > 0)
          CurrentCall.Terminate();

4. **Expected behavior** (mandatory)
Calling Decline/Terminate/TerminateAllCalls()  APIs should disconnect the call for Remote party as well

5. **Please complete the following information** (mandatory)
[0:] DEVICE=peux
[0:] MODEL=2201116PI
[0:] MANUFACTURER=Xiaomi
[0:] SDK=33
[0:] Linphone Xamarin version: 5.1.73

**Comment by dabhi86** [comment]
Thanks for this thread, I am facing same problem. In some phones, Linphone doesn't send disconnect message. So remote party keeps showing call as connected.

**Comment by Viish** [comment]
Hi,

Please attach logs showing the problem.

**Comment by cjkarande** [comment]
Sorry @Viish, I have been travelling for the last 2 weeks. Will generate and attach the logs in a couple of days

**Comment by Viish** [comment]
Closing until requests logs will be provided.

**Comment by lilianjerikamau** [comment]
Hi @Viish I am experiencing this same issue with version 5.4.0 Alpha

[Image](https://github.com/user-attachments/assets/3bb54d13-aff0-4bb8-83b8-e9b1d27b9d18)
