### ISSUE TITLE
G.729 (bcg729) not enabled in F-Droid version?

### ISSUE THREAD

**Issue by bar-g** [BelledonneCommunications/linphone-android#2006]
Found several mentions of g729 in linphone (e.g. bcg729 or https://github.com/BelledonneCommunications/linphone-sdk/issues/345), but it does not seem to be part of the F-Droid build (where baresip has it).

**Comment by Viish** [comment]
Hi @bar-g,

Open that issue to F-Droid's people, they are doing the build themselves.

Cheers,

**Comment by bar-g** [comment]
Are upstream linphone-android defaults including all codecs in the build by default?

**Comment by bar-g** [comment]
Well, the particular ones interesting to have enabled would be the low-bitrate and compatibility ones: codec2, g.729, g.726.

**Comment by bar-g** [comment]
Asking because if yes, then enabling these in f-droid would also improve compat between different linphone client builds. If not, then enabling it in the upstream defaults would propagate to f-droid and improve compat with other clients and gateways in general, besides allowing for more lower bandwidth connections.
