### ISSUE TITLE
Auto-answer calling, while running in background

### ISSUE THREAD

**Issue by takuy** [BelledonneCommunications/linphone-android#2007]
Hi! Hoping this makes sense. 

1. **Describe the bug** (mandatory)
I'm trying to get Linphone running in an intercom-like fashion on an Android 12 tablet. The intent is for this to work like a kiosk but someone can speak through the kiosk if needed. I have it all configured with auto-answer, running in background, etc, all works fine. However, when the call is connected, it forces the Linphone app to the front and only displays that. 

2. **To Reproduce** (mandatory)
 - Install app
 - Register a SIP account
 - Set it to auto answer
 - Set it to run in background
 - call the number
 - the app instantly pops up once the call is connected

3. **Expected behavior** (mandatory)
The app stays in the background but connected to the call (ie no UI)

4. **Please complete the following information** (mandatory)
 - Device: AMX Varia N100
 - OS: Android 12
 - Version 5.1.3 (510303)
 - APK obtained Fdroid

5. **SDK logs** (mandatory)
Not sure if logs are truly useful in this case, but can obtain if needed.

**Comment by takuy** [comment]
Ah I do see there's a keep_app_invisible preference but it is not exposed in the UI. Is there any chance to get that exposed?

**Comment by Viish** [comment]
Hi @takuy,

No that setting won't be exposed.
Take a look at our wiki page about remote provisioning to enable it: https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Remote%20Provisioning/

Cheers,

**Comment by takuy** [comment]
> Hi @takuy,
> 
> No that setting won't be exposed. Take a look at our wiki page about remote provisioning to enable it: https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Remote%20Provisioning/
> 
> Cheers,

Thanks! Remote provisioning does seem like it'd be the right way to go. One more question... this page references the ability to look at the app's existing linphonerc file. I'm not seeing a way to export that in the Android app? Would the config need to be made on the desktop app first?

**Comment by takuy** [comment]
Right, this is fine for the current case. But if I end up having like... 30 of these... this would be a great way to standardize settings rather than manually setting on each one. No worries if exporting from Android is not an option, I think I can poke around and figure out the config names for each thing though!

**Comment by Viish** [comment]
You can dial ` #1234#` , that will show a dialog with some options such as view config file (as in format not XML but that's a good start).

**Comment by takuy** [comment]
Thank you! That's perfect.
