### ISSUE TITLE
How to automatically hang up a call when the app is forcibly closed during a call

### ISSUE THREAD

**Issue by 102401** [BelledonneCommunications/linphone-android#2008]
How to automatically hang up a call when the app is forcibly closed during a call

**Comment by Viish** [comment]
Simply call call.terminate in the `onTaskRemoved() ` method of the Service.

**Comment by 102401** [comment]
When forcibly closing the app, this method cannot be called from the app side

**Comment by 102401** [comment]
> Simply call call.terminate in the `onTaskRemoved() ` method of the Service.

When forcibly closing the app, this method cannot be called from the app side
