### ISSUE TITLE
building with codec2 and g726 by default

### ISSUE THREAD

**Issue by bar-g** [BelledonneCommunications/linphone-android#2009]
Codec2 allows to expand the supported bitrates below 3,2kbps.

G726 adds wider compatibility for reduced bandwidth usage with other sip clients and telephony gateways (i.e. those without g729 support). It should probably be placed last in the preference list by default, because its bitorder compatibility could be hit or miss.

**Comment by Viish** [comment]
Hi @bar-g,

You can enable codec2 by using `-DENABLE_CODEC2=0N` when you build our SDK.

Cheers,

**Comment by bar-g** [comment]
Um, that wasn't what I meant, sorry, for not being clear enough.

I would like to suggest adding these two codecs to linphone's default build setup, and in consequence to the app store builds.

As place for codec2 in the default codec preference list I was thinking between speex-16000 and speex-8000, but disabled by default.

This should allow for getting a reasonably usable lowest-bandwidth usage setup, by just enabling codec2 and disabling opus and speex-16000 before codec2 in the application. This way there remain enough fallback options after codec2 for compatibility. And it should work even before a working bitrate limit preference option is in place (https://github.com/BelledonneCommunications/linphone-sdk/issues/347).

I think G726 can just be put at the end of the list and enabled by default. It'll increase the chance of a connection if no other codecs match. Placed last in the list this is even true in case Linphone is not able detect and fix the possible bitorder mismatches with this codec.
