### ISSUE TITLE
contact names don't display only phone numbers

### ISSUE THREAD

**Issue by LAfricain** [BelledonneCommunications/linphone-android#201]
No name is displayed only showing number.

See also [this issue for iphone](https://github.com/BelledonneCommunications/linphone-iphone/issues/301#issuecomment-359364363)

**Comment by astuter** [comment]
Hello @DatBewar ,

Any input for this issue? It may not be an issue but any thought of making this more user friendly?

**Comment by LAfricain** [comment]
>  It may not be an issue

If it is not an issue, you may to remember all the phone numbers of your friends and family  :) Difficult...

> making this more user friendly?

Yes! I would like to convince all my Viber contacts to move to Linphone, but with this issue, it's not very attractive...

**Comment by simplenetworks** [comment]
I have the same issue, both on Android an iPhone, using a SIP Account on a custom domain. Could it be a server issue? Any advice?

**Comment by moneythumb** [comment]
In case someone else is puzzled by this, it took me a long time to figure out that when creating a contact the default name (label) for the contact is the phone number, so you just need to edit that to put in a real name.
