### ISSUE TITLE
not starting at boot, if "service notification" is not shown (hidden)

### ISSUE THREAD

**Issue by bar-g** [BelledonneCommunications/linphone-android#2010]
Dear devs,
I found that after rebooting the phone the account got only registered (online server status) once Linphone was opened manually, despite the "Start at boot time" setting being enabled.

Then found that hiding Linphone's permanent "service notification" in "Linphone->settings->calls->Android notification settings" seems to prevent Linphone from automatically starting at boot time.

It was reproducible at least on two phones. Hopfully it's possibe to fix.

OS: Android 12
Linphone 5.1.3 (f-droid)

**Comment by Viish** [comment]
Hi @bar-g,

Indeed if in the Android settings you disable the notification channel it can't work, because "start at boot time" starts the Service as Foreground (which requires a notification).

You can't have the background mode and the start at boot working if you disable the service notification.

Cheers,

**Comment by bar-g** [comment]
Hm, ok, I see.

I remember a nicely working solution to get rid of the permanent notification though, and it removes the need to fuzz with notification permission all together. The deltachat app has a handler that only shows a notification while the display is turned off, so it's effectively never visible to the user. Thus having auto start _and_ a clean notification area.

**Comment by Viish** [comment]
This isn't necessary when you use our SIP service as push notifications remove the need for that persistent icon, and it's likely how deltachat does it too.

**Comment by bar-g** [comment]
Deltachat really is free from third-party push servers, it only subscribes to imap events from one's standard email server (persistent tcp), and works well and efficient based on a foreground notification and (if I'm not confusing this) wake timer prolongation as backup.

**Comment by bar-g** [comment]
I have to say, Linphone has now also been reachable well with just a sip/tls server. Of course, with background mode and start at boot enabled, battery optimization disabled, and unrestricted data in data saving mode.

Maybe remove the "Android notification settings" from Settings->Call to not lead right into the pitfall of this issue? (And not needed anyway if you'd like to incorporate the deltachat handler.)
