### ISSUE TITLE
Accepting Video request on Android 11 and above starts only local stream. Remote stream is not received.

### ISSUE THREAD

**Issue by cjkarande** [BelledonneCommunications/linphone-android#2011]
Hello,
Describe the bug (mandatory)
Accepting Video request on Android 11 and above starts only local stream. Remote stream is not received. However Accepting Video request on Android 9 just works fine.  I have'nt test it on Android 10 though.

Code for Accepting Video request
_linphoneManager.AcceptUpdate(CurrentCall.RemoteParams);

To Reproduce (mandatory)
This issue tested and reproducible on Android 11 & Android 13.

Expected behavior (mandatory)
Registration call should not take so long over a mobile network

Please complete the following information (mandatory)
[0:] DEVICE=peux
[0:] MODEL=2201116PI
[0:] MANUFACTURER=Xiaomi
[0:] Linphone Xamarin version: 5.1.73

**Comment by Viish** [comment]
Hi @cjkarande,

As always I need logs to investigate the issue.

Cheers,

**Comment by cjkarande** [comment]
Sorry @Viish, I have been travelling for the last 2 weeks. Will generate and attach the logs in a couple of days

**Comment by Viish** [comment]
Closing until requests logs will be provided.
