### ISSUE TITLE
Screen Sharing 

### ISSUE THREAD

**Issue by HVaidehi** [BelledonneCommunications/linphone-android#2016]
Now I uses linphone to complete the function of voice conference. currently, I need to share the screen of the current device. android os has related functions of recording screen. please ask if there is any way to send the content of recording screen out in real time to complete the function of screen sharing. Thank you very much.
Looking forward to your reply.

**Comment by Viish** [comment]
Hi,

No this is currently not possible with Linphone.
We plan on adding screen sharing soon but first it will only be for desktop version of the app, I don't know when we'll do the mobile screen sharing.

Cheers,

**Comment by k-levin** [comment]
Hello!
Would you tell, is it will possible to add a screen sharing feature to the linphone?
You don't realize how Linphone is close to much success. Only few things are stopped pepole to use the Linphone as enterprise communication tool.
- screen sharing
- one-windowed call
- smooth style of numpad in Mobile version

We have a best softphone ever made. It has ldap and autoprovision, heap of codec, secure stored passwords, opensource, nice looking view with new interface. It will be nice to use it ON THE WORKPLACE)))

**Comment by Viish** [comment]
Hi @k-levin,

Screen sharing (from desktop app only but visible on all clients) will be part of 6.0 release that is planned for next month.

Cheers,

**Comment by nbh707** [comment]
What happened to 6.0? We are almost a year on now.

**Comment by Viish** [comment]
Hi @nbh707,

6.0.0 has already been released on Android (we're at 6.0.4 right now).
iOS & desktop are coming before June.

**Comment by ouyben** [comment]
Hello, friend. Does linphone support screen sharing now? If it supports it, what should I do?

**Comment by obspsr** [comment]
It seems that nobody wants to say if screen-sharing is working somewhere.
The great majority does not care about windows works. Its dead and shit.
We need only a Linphone for Linux image just working.
At the moment, beta-85 is working like a charm but, shared screen does not appear.
Problem of networked screen Id's or $DISPLAY variable ???
Thanks to comment these kind remarks.
We need Linphone after Windows-killers have destroyed our near perfect Skype ....
Thanks for coop,
Serge.

**Comment by Viish** [comment]
Hi @obspsr,

Yes screen sharing is available in our desktop version starting 6.0 release, but to work it requires a video conferencing server that supports the feature, and currently our sip.linphone.org service doesn't.
It will be available the moment we release flexisip 2.5 release.
You can also install your own flexisip-2.5 beta version to test it.

Cheers,
