### ISSUE TITLE
need of restarting the app after each single call

### ISSUE THREAD

**Issue by Simplenuity** [BelledonneCommunications/linphone-android#2017]
Hi @Viish  and thanks for the continuous development of this app! 

1. **Describe the bug**

After starting the app and making the first call it is not possible to make a second call. It fails with Error 408 / Request timeout.
The app needs to be restarted again.

3. **To Reproduce** (mandatory)

- start app
- make a call (I use sip:10005@sipgate.de)
- after pressing the # key (as advised) wait for the automatic hang-up
- try to make another call (I use sip:10005@sipgate.de) which will end with Error 408 / Request timeout

5. **Expected behavior** (mandatory)

I can make a second call without having to restart the app.

6. **Please complete the following information** (mandatory)

 - Device: Xiaomi MiMax3
 - OS: Android 10
 - Version of the App 5.1.4
 - Version of the SDK 5.2.99
 - Where you did got it from: F-Droid
 - Please tell us if your Android is a Lineage OS or another variant: stock (MIUI)

7. **SDK logs** (mandatory)

Logs hold personally identifiable information. You should not encourage people to upload them here, at least not without clearing this information!
I'll send the logs to sylvain.berfini@belledonne-communications.com

8. **Adb logcat logs** (mandatory if native crash)

n/a

9. **Screenshots** (optionnal)

n/a

10. **Additional context** (optionnal)

n/a

**Comment by Viish** [comment]
Hi @Simplenuity,

I don't see anything wrong in your logs that would explain the issue.

The only thing is that you are using UDP as transport protocol and such packets can get lost, but that wouldn't explain why the first call is OK and the ones following, nor why restarting the app would fix the issue.

It could also be a network issue, do you have the same problem on a different WiFi / cellular network?

Finally, did you build the app yourself?
5.1.4 release is supposed to be built with 5.2.110 SDK and yours is 5.2.99.

Cheers,
