### ISSUE TITLE
Issue Retrieving Unknown Chat Rooms Using getChatRooms() in Linphone SDK

### ISSUE THREAD

**Issue by Mahe2027** [BelledonneCommunications/linphone-android#2019]
Hello,

I've been experiencing an issue with the Linphone SDK related to retrieving chat rooms. While I can successfully create chat rooms and retrieve them using the `getChatRooms()` method, I've noticed a discrepancy when receiving messages from unknown chat rooms.

**Issue Details**:

1. When I receive a message from a chat room that wasn't created within my app (i.e., an "unknown" chat room), I can access the message, but the chat room itself is not listed when I call `getChatRooms()`.
2. Chat rooms that I create within my app appear as expected when using `getChatRooms()`.

**Steps to Reproduce**:

1. Receive a message from a chat room that wasn't created within the app.
2. Call `getChatRooms()` to fetch the list of chat rooms.
3. Notice that the chat room from which the message was received is not present in the list.

I wanted to ask if this is expected behavior or if there might be a specific way to retrieve such "unknown" chat rooms? Is there a separate method or approach recommended for handling incoming messages from chat rooms that haven't been previously created or accessed within the app?

Any insights or guidance on this matter would be greatly appreciated.

Thank you for your assistance and looking forward to your response.

Best regards,

**Comment by Viish** [comment]
Hi @Mahe2027,

This can happen if the chat room is created by a remote end and if your SIP proxy server is misconfigured (happens often with Asterix for example).
Problem is the FROM and TO headers of chat messages do no contains the SIP Identity but username@IP instead, which causes that (I don't have your logs so I can't say for sure it's that but it definitively looks like it).

The best fix would be to change your proxy server configuration so it properly uses SIP Identity in FROM and TO headers.
In the meantime, you can set the following item in your linphonerc config file :
```
[misc]
hide_chat_rooms_from_removed_proxies=0
```

Cheers,
