### ISSUE TITLE
Incoming call numbers in national format aren't matched to contacts saved in international format

### ISSUE THREAD

**Issue by schichtnudelauflauf** [BelledonneCommunications/linphone-android#2022]
Hi template, hi people, wish you a nice morning.

This is more a missing feature than a bug but Github didn't offer not using the template.

1. **Describe the bug** (mandatory)

I use Linphone from F-Droid with a SIP Account. Not a Belledonne Comms Account.
When someone calls me, the provider sends the origin number, if from the same country as 0<areacode><whatever> instead of +<countrycode><areacode><whatever>.
My contacts are all saved in international format.
Linphones call log does not attach the names to the numbers that way.
When I call by using a contact using international format, the name is attached in call log.

2. **To Reproduce** (mandatory)

Save a contact in international fornat through Android Contacts. In the normal phone number field. Not the SIP field. I do not want to save a number in different formats redundantly because that messes up other contact provider users data interpretation.
Use any SIP to Phone carrier with behaviour described above and get called by the saved contact.

3. **Expected behavior** (mandatory)

Linphobe, knowing which country code it is in, should match local format incoming numbers.
(It autodetected my country prefix from android region settings just fine.)

4. **Please complete the following information** (mandatory)

 - Device: Pixel
 - OS: Android 14
 - Linphone Android 5.1.4 (tags/5.1.4^0, release)
 - Linphone SDK 5.2.99 (tags/5.2.99^0, release)
 - Where you did got it from: F-Droid
 - Graphene

5. **SDK logs** (mandatory)

Not applicable because its not an error but a missing feature.

6. **Adb logcat logs** (mandatory if native crash)

Not a crash.

7. **Screenshots** (optionnal)

Not.

8. **Additional context** (optionnal)

Not.

**Comment by Viish** [comment]
Hi @schichtnudelauflauf,

Can you check your account settings and make sure the prefix has been correctly set?

This isn't a missing feature it is supposed to work. I just tried with my device and it works fine for my test case.

Cheers,

**Comment by Viish** [comment]
Can you please attach the debug logs from the app then ?

**Comment by Viish** [comment]
If you don't want to use adb logcat nor use our log upload feature that will be hard for you to get the logs...

**Comment by Viish** [comment]
You'll be happy to know we are working on a new UX/UI that is scheduled to be ready and published at the end of June, 2024.
It has been designed with the help of a specialized UX company, and the first tests with users are great!

**Comment by G10h4ck** [comment]
I am affected by this bug too

**Comment by osering** [comment]
Problem/bug alike: incoming calls (in app under account settings there is just switch for outgoing calls and chats) by contacts saved without international prefix are not recognized/matched, when local prefix - where place for only one (for just one country code) is reserved and useful just for outgoing calls (probability that identical 8 digit number calls from other jurisdiction is almost zero) - is not entered. Most phone apps recognize incoming CID# without specifying intl country code (matching last X digits of incoming number).
Looks like apps general problem: too strict rules for matching contact (addressbook) data with incoming call data (willing 100% or ideal match).

**Comment by Viish** [comment]
6.0.0 alpha is now available in master branch (public beta is pending validation from Google).

**Comment by G10h4ck** [comment]
> 6.0.0 alpha is now available in master branch (public beta is pending validation from Google).

We will get it soon on F-Droid too?
