### ISSUE TITLE
Can't use certificate from Android Keystore

### ISSUE THREAD

**Issue by User-26** [BelledonneCommunications/linphone-android#2024]
Hello! Could you add support for using certificates from the Android Keystore?

Here is a video demonstration:
https://github.com/Radiokot/photoprism-android-client/wiki/How-to-connect-to-a-library-with-mTLS-(mutual-TLS)-auth%3F

Here is the code:
https://github.com/Radiokot/photoprism-android-client/blob/610bd0967714370909e3eafb28116edc23bd0097/app/src/main/java/ua/com/radiokot/photoprism/api/util/KeyChainClientCertificateKeyManager.kt#L4

**Comment by Viish** [comment]
Hi,

We don't plan on doing it, however it shouldn't be hard for you to do it using our APIs to set the certificates.
For example : https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Core.html#setRootCaData-java.lang.String-

Cheers,
