### ISSUE TITLE
Enhancement: make keypad button touchable area fill the grid

### ISSUE THREAD

**Issue by pbrn46** [BelledonneCommunications/linphone-android#2025]
This shouldn't be too hard to implement, but I'm wondering if the keypad buttons hit box can be made larger. Currently, dialing is frustrating. If one doesn't touch the keypad number directly and presses the whitespace on the side, the number doesn't register.

Tested on the Pixel 3A.
![Screenshot_20231108-183438](https://github.com/BelledonneCommunications/linphone-android/assets/15950299/ab367d8a-c95e-4d92-aff0-dba9615d54f5)

**Comment by Viish** [comment]
Fixed in 6.0.0 alpha now available in master branch.

**Comment by eturk1** [comment]
> Fixed in 6.0.0 alpha now available in master branch.

Looks like were missing resource file: drawable/linphone_logo_tinted referenced in contacts.xml in 6.0?
I just pulled it to compile

**Comment by Viish** [comment]
Hi @eturk1,

> Looks like were missing resource file: drawable/linphone_logo_tinted referenced in contacts.xml in 6.0?

contacts.xml is a leftover from previous versions. Simply remove it using `git clean -f` for example and it will build just fine.

Cheers,

**Comment by eturk1** [comment]
> git clean -f

ah, thanks!
