### ISSUE TITLE
Color / white balance correction during SIP video call

### ISSUE THREAD

**Issue by glush** [BelledonneCommunications/linphone-android#2026]
Is it possible to make some Color / White balance / Gain correction during SIP call with video. I can make it while making photo / record video with Camera2 API using

        requestBuilder.set(
            CaptureRequest.COLOR_CORRECTION_MODE,
            CaptureRequest.COLOR_CORRECTION_MODE_TRANSFORM_MATRIX
        )
        requestBuilder.set(CaptureRequest.COLOR_CORRECTION_GAINS, <GAIN_CORRECTION_MATRIX>)

**Comment by Viish** [comment]
Hi,

If you wish you can do the change in https://github.com/BelledonneCommunications/msandroidcamera2/blob/9ccffa13543b379fd98806f1188a0f984794d7df/android-camera2-capture.cpp and re-build a SDK for your android app.

Cheers,
