### ISSUE TITLE
Network is unreachable timeout (help wanted)

### ISSUE THREAD

**Issue by sfxsfxsfxsfx** [BelledonneCommunications/linphone-android#2028]
Hello,
How can I set a timeout value if the network is unreachable certain time or Is there any callback that I can receive those updates time etc?

**Comment by Viish** [comment]
Hi @sfxsfxsfxsfx,

You can use https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/CoreListenerStub.html#onNetworkReachable-org.linphone.core.Core-boolean- to be notified of the network reachability changing.

Cheers,
