### ISSUE TITLE
Build new linphone with old ZRTP

### ISSUE THREAD

**Issue by mayjethva** [BelledonneCommunications/linphone-android#2030]
We are attempting to build the new version of Linphone for personal use.  The new version looks to be using a new ZRTP which is not compatible with what our server is using, but previous versions of linphone zrtp functioned.  Can someone point to where we can get the ZRTP switched back to the older version?

**Comment by Viish** [comment]
Hi,

Could you elaborate on which version works and which one doesn't please?

Cheers,

**Comment by Viish** [comment]
Closing until requests logs will be provided.
