### ISSUE TITLE
Disable call recording?

### ISSUE THREAD

**Issue by petervnv** [BelledonneCommunications/linphone-android#2034]
Hi,

I've been looking through the code in order to disable the new call recording feature completely.

I imagined it would be a boolean in coreconfig settings but I can't find it anywhere.

Any hints?

Thanks

**Comment by Viish** [comment]
Hi @petervnv,

Indeed we currently don't have a magic setting to completely disable the recording feature.
You'll have to hide the recording button from in call menu & maybe hide/disable the "automatically record calls" setting.

Cheers,
