### ISSUE TITLE
How to enable G.722 or G.729 as the default codec. Currently it seems to be using G.711/ulaw as the default

### ISSUE THREAD

**Issue by cjkarande** [BelledonneCommunications/linphone-android#2035]
Hi,

How to enable G.722 or G.729 as the default codec? Currently, it seems to be using G.711/ulaw as the default. 
Similarly, how do we change the default video codec?

**Comment by Viish** [comment]
Hi,

There is no such thing as default codec.
Codecs are either enabled or not, and the SIP negocitation during offer/answer part of the call will decide which codec to use depending on which codecs are enabled on both sides.
The only thing is the priority order when the same multiple codecs are enabled on both sides, but you can't configure it in the app directly, it's the order in which they are declared in the linphonerc file.

Cheers,

**Comment by cjkarande** [comment]
Thanks @Viish for your response. Appreciate if you could please point me to the linphonerc configuration documentation.
I see two linphonerc files in the Assets directory, both have different sets of configurations. I assume its linphonerc_factory that needs to be configured.
1) linphonerc_default
2) linphonerc_factory

**Comment by Viish** [comment]
Hi @cjkarande,

default & factory RC can contain the same information, the difference is the default one contains the current configuration of your app as well as the initial state. The factory RC contains forced settings, meaning at each start they will be applied again over to ensure the setting is set to this value.

We do not have a documentation yet for all possible values that can be set in the RC, you'll have to search them in liblinphone source code.

Cheers,

**Comment by cjkarande** [comment]
> The only thing is the priority order when the same multiple codecs are enabled on both sides, but you can't configure it in the app directly, it's the order in which they are declared in the linphonerc file.

Sorry @Viish , by linphonerc documentation, i meant the parameter details for codec declaration in the linphonerc file.

**Comment by Viish** [comment]
Hi @cjkarande,

Video codecs are as follow:
```
[video_codec_X]
mime=<name of codec>
rate=90000
enabled=1 (0 to disable)
recv_fmtp= (optional)
```
Audio codecs are : 
```
[audio_codec_X]
mime=<name>
rate=<sample rate>
channels=<channels>
enabled=1 (0 to disable)
```

Cheers,

**Comment by cjkarande** [comment]
Thanks a ton @Viish, highly appreciate your support.
