### ISSUE TITLE
Call logs only retrive data after second call

### ISSUE THREAD

**Issue by papijeiboi** [BelledonneCommunications/linphone-android#2037]
Hi good pm
Does anyone experience using coreContext.core.callLogs and only returns call log data after 2nd call

To reproduce just make first call after that there be no return calllog data. Then 2nd call it will return 2 data the first and second call.

Expected should be from the first it must returning a data right?

4. **Please complete the following information** (mandatory)

 - Device: [e.g. Samsung Note 20 Ultra]
 - OS: Android 14
 - 5.2.103
 - Local Build

**Comment by Viish** [comment]
Hi,

No this isn't an issue we're aware of.
Could you turn  on debug logs, reproduce the issue and then upload & copy/paste here the links to them please?

Cheers,

**Comment by Viish** [comment]
Closing until requests logs will be provided.
