### ISSUE TITLE
Notifying Core we have received a push for Call-ID []

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#2040]
I'm noticing in the logs that it appears that the push notification can include the caller-id of the call?

Specifically:

```
MyLinphone: [Push Notification] Notifying Core we have received a push for Call-ID []
```

Does that empty `[]` imply there is a way to push caller-id information in the push notification?

Any idea which FCM message field it should be in?

**Comment by Viish** [comment]
https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/D.%20Specifications/Push%20notifications/#HContentofthepushnotificationssentbyFlexisip

**Comment by brianjmurrell** [comment]
Thanks @Viish!

FWIW, that page seems to be documenting the [deprecated message format](https://firebase.google.com/docs/cloud-messaging/migrate-v1#update-the-payload-of-send-requests) that will [not be supported after June 2024](https://firebase.google.com/docs/cloud-messaging/receive-upstream) when they retire the _HTTP legacy APIs_.

**Comment by Viish** [comment]
Yes, we are in the process of switching to the new format as the previous one is no longer supported for new projects. Doc will be updated once the feature branch will be merged in Flexisip.

**Comment by brianjmurrell** [comment]
Great.  Just wanted to make sure y'all were aware.

**Comment by brianjmurrell** [comment]
Just to follow up on this, is the correct push payload now:

```
{
  "message": {
    "token": "[redacted]",
    "data": {
      "uuid": "7bc4a32e-999b-446c-ab68-04d9b65d2d04",
      "form-uri": "",
      "display-name": "",
      "call-id": "1235551212",
      "sip-from": "",
      "loc-key": "",
      "loc-args": "",
      "send-time": "02-03-24 06:56:49"
    },
    "android": {
      "priority": "high"
    }
  }
}
```

And are any of the above empty (`""`) field mandatory and need some non-empty value?

**Comment by Viish** [comment]
On Android all fields are not mandatory. Call id helps process the push faster, that's all.

**Comment by Viish** [comment]
> Did this get updated yet?

Yes, our sip.linphone.org server is using the new format since a few months now (old way doesn't work anymore).

>  Is this speeding up the push with that item documented anywhere?

No.
