### ISSUE TITLE
Linphone server restarts, serious exception BUG will occur!!!

### ISSUE THREAD

**Issue by LoyaiHai** [BelledonneCommunications/linphone-android#2045]
Hi

When my accounts were online on both devices, I restarted the linphone server. After the restart was complete, I found that the following problems occurred when the two devices made video calls to each other again:
1、When dialing, the other device does not respond;
2、when connected, one device will not receive the video source from the other device;
3、After either device hangs up, the other device does not receive the hang up callback

Could you please test immediately whether you also have such problems and serious bugs

Thanks Viish 
Cheers!

**Comment by LoyaiHai** [comment]
current use linphone veriosn:
Linphone Android 5.1.4(tags/5.1.4^0,release)
Linphone SDK 5.2.99(tags/5.2.99^0,release)

**Comment by Viish** [comment]
Hi @LoyaiHai,

Please attach debug logs from both devices when that issue occurs.

Cheers,

**Comment by LoyaiHai** [comment]
Below is the log link, please check it.
Log test process description:
1. If devices A and B log in successfully, the server restarts. Wait for 2 minutes and perform the following operations.
2. When device A calls device B: A-- >B, it can receive the call command. After the call is connected, neither device receives the remote video source. When device B executes the hang up command, device A does not receive the hang up command. Otherwise, when device A executes the hang up command, device B can receive the hang up command.
3. When device B calls device B: B-- >A, device A cannot receive call instructions.
Please refer to the provided log and process to see which step went wrong that caused the problem
Thanks Viish
Cheers!
[linphoneA.log](https://github.com/BelledonneCommunications/linphone-android/files/13608641/linphoneA.log)
[linphoneB.log](https://github.com/BelledonneCommunications/linphone-android/files/13608642/linphoneB.log)

**Comment by Viish** [comment]
@LoyaiHai,

Please enable debug logs in advanced settings first, the logs you send aren't verbose enough to understand the issue.

Cheers,

**Comment by LoyaiHai** [comment]
Okay, I've set the debug log level to：
    factory.getLoggingService().setLogLevel(LogLevel.Message);
Since today is Saturday, the server restart test can only be implemented on Monday at work, so do not set the current issue to complete.
Thanks Viish
Cheers!

**Comment by LoyaiHai** [comment]
The following is the latest log, which starts at about 12:10. Please refer to the process described above for AB.
Thanks Viish
Cheers!
[linphoneA.log](https://github.com/BelledonneCommunications/linphone-android/files/13630892/linphoneA.log)
[linphoneB.log](https://github.com/BelledonneCommunications/linphone-android/files/13630893/linphoneB.log)

**Comment by Viish** [comment]
Hi,

I don't think this is related to your server restarting and there is one call that works right after it.
I see that you are using a 5.1.0-beta SDK, please update to latest 5.2.X release, it may fix your issue.
Also you aren't using ICE which could prevent that kind of network issue.

Cheers,

**Comment by LoyaiHai** [comment]
I have installed your official latest APK, and found the same situation

Thanks Viish
Cheers!

**Comment by Viish** [comment]
@LoyaiHai Did you configured/enabled ICE in your account's params?

**Comment by LoyaiHai** [comment]
@Viish 
Hi
I did find that I didn't have ICE turned on. Another problem is that I don't know what the STUN/TURN server format is. Can you tell me, please?
Thanks Viish
Cheers!

**Comment by Viish** [comment]
@LoyaiHai,

Stun server is merely an URL like this:`stun.linphone.org`

**Comment by LoyaiHai** [comment]
@Viish 
Hi
When I logged in successfully, I wrote the following code in the login callback：

AccountParams accountParams = account.getParams().clone();
                        if (accountParams != null) {
                            DebugLogJava.e("accountParams != null");
                            NatPolicy natPolicy = accountParams.getNatPolicy();
                            if (natPolicy == null) {
                                DebugLogJava.e("natPolicy == null");

                                NatPolicy newNatPolicy = currentCore.createNatPolicy();
                                newNatPolicy.setStunEnabled(true);
                                newNatPolicy.setStunServer("stun.linphone.org");
                                newNatPolicy.setIceEnabled(true);

                                accountParams.setNatPolicy(newNatPolicy);
                                account.setParams(accountParams);
                            } 
                        } else {
                            DebugLogJava.e("accountParams == null");
                        }

When I perform video communication, I find that another device has an image, but the local device does not display the image transmitted by the other device, may I ask how this is going?

Thanks Viish
Cheers!

**Comment by Viish** [comment]
HI @LoyaiHai,

Please attach logs from both devices in call so I can see why you don't have an image to display.
Also don't forget to update to latest available SDK.

Cheers,

**Comment by LoyaiHai** [comment]
Hi
@Viish 
Here is the sdk version and log:

linphone SDK version: 5.3.0-alpha-386-g178b70ef1
log:
[linphone_ICE_A.log](https://github.com/BelledonneCommunications/linphone-android/files/13654884/linphone_ICE_A.log)

[linphone_ICE_B.log](https://github.com/BelledonneCommunications/linphone-android/files/13654886/linphone_ICE_B.log)

question:
The primary calling device cannot receive the remote video

Thanks Viish
Cheers!

**Comment by Viish** [comment]
Hi,

Seems you have a proxy server issue.
A is sending in the 200 OK it's local IP by B receives it with the server public IP.
You can see in B logs that it never manage to complete ICE setup.

Also I see you are using a 5.3.0-alpha SDK, I recommend you to either switch to the 5.3.0-beta or the current release (5.2.112).

Cheers,

**Comment by LoyaiHai** [comment]
Hi
@Viish 

Can I assume that the proxy server must be enabled to enable ICE? Project I don't have a configuration of proxy server, or the proxy server is above this: newNatPolicy. SetStunServer (" stun.linphone.org ");

ok, i try to use 5.3.0-beta or the current release (5.2.112)

Thanks Viish
Cheers!

**Comment by LoyaiHai** [comment]
Another thing I want to say, please ask if there is any description of the methods and properties of core classes, I am guessing the role and use of some methods.

Thanks Viish
Cheers!

**Comment by Viish** [comment]
@LoyaiHai,

When I say proxy server, I don't mean a configuration item inside the app but the real server: in your case Freeswitch.
The documentation is available here: https://download.linphone.org/releases/docs/liblinphone/latest/java/overview-summary.html

Cheers,

**Comment by LoyaiHai** [comment]
Hi
@Viish
Now I understand everything, thanks for the answer. Finally, I would like to ask a question: Is there a link to all configuration properties and value ranges in linphonerc_factory and linphonerc_default? I looked up a lot of linphone configuration articles, did not find the full version, and the attribute names are various, it is difficult to distinguish

PS:linphonerc_factory from: project--->src--->main--->assets--->linphonerc_factory、 linphonerc_default、assistant_default_values、assistant_linphone_default_values

Thanks Viish
Cheers!

**Comment by Viish** [comment]
Hi @LoyaiHai,

No we currently do not have any documentation that would list all available parameters and there possible values.

Cheers,
