### ISSUE TITLE
Add option to select SIP account to use when sending messages and making calls

### ISSUE THREAD

**Issue by lnpn23121** [BelledonneCommunications/linphone-android#2047]
Hello,

Currently when there're multiple SIP accounts, it uses the default account to send messages and make calls. Please add an option to select the account to use when sending messages and making calls. My use case is I want to use one account for PSTN calls, and other accounts for everything else.

Thanks.

**Comment by Viish** [comment]
Hi @lnpn23121,

Yes this is a need that we hear a lot.
We are currently developing 6.0 versions for all of our apps with a brand new UI and in which the account switching will be very easy.

This version should be available in public beta during the spring and released in the summer.
