### ISSUE TITLE
Question about bluetooth

### ISSUE THREAD

**Issue by usert-4** [BelledonneCommunications/linphone-android#2049]
Hello,

as it is stated in the AndroidManifest, BLUETOOTH_CONNECT permission is used for detecting bluetooth headset connectivity change,
could it be replaced by https://developer.android.com/reference/android/media/AudioDeviceCallback and thus remove bluetooth permission(s) ? normally this could detect also bluetooth device connect/disconnect for audio device type(headset..)

or is there any others usage unseen or for others things ?

**Comment by Viish** [comment]
It seems to work perfectly fine, I've merged the fix in release/5.2 branch for 5.2.0 release.

Thanks a lot!

**Comment by usert-4** [comment]
ok good, there are case of apps like our which does not use bluetooth except in linphone who use it just for that, and there was this possibility for avoiding it, also the "nearby device" was visible in app settings, thanks

**Comment by Viish** [comment]
Yeah I know the permission request was showing a misleading message "nearby devices detect & connect" simply for bluetooth device handling...

I'm glad to get rid of it!
