### ISSUE TITLE
Questions about voice/video conferencing

### ISSUE THREAD

**Issue by LoyaiHai** [BelledonneCommunications/linphone-android#2050]
Hi
I now want to do a voice/video conference and I see an active call here for the conference and need to fill in a meeting address. But in the demo, there is no interface related to conference call, may I ask if I want to create a video conference, what is the specific process?

Thanks Viish
Cheers!

**Comment by LoyaiHai** [comment]
I looked up questions about the meeting for which the current project had been marked as completed and found that it simply said the following to create it:
val params = core.createConferenceParams()
val conference = core.createConferenceWithParams(params)
conference? .addParticipants(core.calls)

However, it is not specified that the current code is in the coreListener callback
OnCallStateChanged () = = = = > state = = Call. State. When OutgoingProgress calls, or directly to the meeting room number to Call.
At the same time, I saw in the previous question that you said that a conference call can only be created with the consent of a third party. Is that what you mean?

**Comment by Viish** [comment]
Hi,

There are two kinds of conferences : a local conference (one participants does the merge of the calls locally) or a remote one (requires a server).
In any case a Conference object is attached to Call and follow the usual state changes.

Cheers,
