### ISSUE TITLE
Incoming calls failing/rejected

### ISSUE THREAD

**Issue by jsfrerot** [BelledonneCommunications/linphone-android#2053]
1. **Describe the bug** (mandatory)

Hi, I've installed linphone on android and setup connection with voip.ms. I followed this documentation: https://wiki.voip.ms/article/Linphone_Android

I'm able to make calls from linphone, but incoming call are not working properly. I receive the call (rings 1 time) but it gets rejected immediately and the other party gets a busy signal.

2. **To Reproduce** (mandatory)

Setup linphone android with voip.ms and follow this documentation: https://wiki.voip.ms/article/Linphone_Android
Note that I'm using TLS with SRTP.
Use an external phone and call your DID associated with the linphone configuration.

3. **Expected behavior** (mandatory)

I should be able to answer the call.

4. **Please complete the following information** (mandatory)

 - Device: Samsung S23
 - OS: Android 14
 - Version of the App: 5.1.4
 - Version of the SDK 5.2.110
 - Where you did got it from: Play Store
 - Please tell us if your Android is a Lineage OS or another variant: samsung's factory default.

If you are using a SDK that isn't the latest release, please update first as it's likely your issue is already solved.

5. **SDK logs** (mandatory)
https://www.linphone.org:444/tmp/65770f34b8318_abb0c0a090351d7bc53e.gz

6. **Adb logcat logs** (mandatory if native crash)
App doesn't crash.

7. **Screenshots** (optionnal)
Not able to take screen while it's happenning as it's to fast.

8. **Additional context** (optionnal)
N/A

**Comment by Viish** [comment]
Hi @jsfrerot,

Thanks for this well documented issue.
I don't know why the remote end of your call gets the BUSY signal, but in your logs you can see that the call is being terminated by the server itself (probably because another device replied BUSY):
```
2023-12-11 08:31:25:459 [org.linphone/belle-sip] MESSAGE channel [0x72f5eaae80]: received [870] new bytes from [TLS://montreal9.voip.ms:5061]:
CANCEL sip:120191_softphone@70.51.6.106:43552;pn-prid=eDHSQzqZSVKf-1Cx4PfeO9:APA91bGE5sYHHD3pRAJk4eSJW-okw0g2hpwWbqykc-VjfTRlPzV4IGKCcHX96o_nfDGXFOHXwm37Bh4-NmpjJUhzcvrSZgT4-bYab3d3LoRlXuntlMT_QyrIlQqAxrAk3SlyUd1wSsXS;pn-provider=fcm;pn-param=929724111839;pn-silent=1;pn-timeout=0;transport=tls SIP/2.0
Via: SIP/2.0/TLS 208.100.60.27:5061;branch=z9hG4bK635cf341;rport
Max-Forwards: 70
From: "JS FREROT" <sip:4503050750@208.100.60.27>;tag=as00b40112
To: <sip:120191_softphone@70.51.6.106:43552;pn-prid=eDHSQzqZSVKf-1Cx4PfeO9:APA91bGE5sYHHD3pRAJk4eSJW-okw0g2hpwWbqykc-VjfTRlPzV4IGKCcHX96o_nfDGXFOHXwm37Bh4-NmpjJUhzcvrSZgT4-bYab3d3LoRlXuntlMT_QyrIlQqAxrAk3SlyUd1wSsXS;pn-provider=fcm;pn-param=929724111839;pn-silent=1;pn-timeout=0;transport=tls>
Call-ID: 4c5e4ac3686f47b05a1876e827ec72e5@208.100.60.27:5061
CSeq: 102 CANCEL
User-Agent: voip.ms
Content-Length: 0
```

Check if you don't have another SIP software using the same account.

Cheers,

**Comment by jsfrerot** [comment]
I have verified that no other device is using the account or no other app on the phone is using that account too. 
so here is what I did. 
* Shutdown linphone
* checked registration on voip.ms
* tested calling with no registration (getting a message that no lines are available)
* re launched linphone
* confirmed registration on voip.ms
* tested calling, getting one ring then busy signal. On the linphone app I briefly see the popup showing the incoming call, but disappear very fast and show a missed call.

I confirm it's not a registration issue.

**Comment by Viish** [comment]
I looked at your logs again but there is nothing that explains why voip.ms server would cancel the call on is own one second after Linphone sends back the 180 Ringing.

I recommend you to contact them to understand why that happens.
Sorry I can't do more.

**Comment by jsfrerot** [comment]
well sad to say but it was a setting on my side. "Ring Time in seconds" on the provider side was set to 1s. I changed it to 20s and now it's working perfectly!
