### ISSUE TITLE
About Speaker Settings

### ISSUE THREAD

**Issue by LoyaiHai** [BelledonneCommunications/linphone-android#2055]
Hi
@Viish
Current I set the audio input and output devices, but also set up open the speaker: audioManager. SetSpeakerphoneOn (true);
But I found a problem: when I was in before entering the video on the phone and call on, tried to set up: the audioManager. SetSpeakerphoneOn (true).
However, when I check again to see if the current speaker is on, the state is off.
So may I ask, at what stage of the call was this speaker setting set?
Another question, can you explain it in detail, currentCore. GetInputAudioDevice ()
currentCore.getDefaultInputAudioDevice()
currentCall.getInputAudioDevice()
These three are useful and different

Thanks Viish
Cheers!

**Comment by Viish** [comment]
Hi @LoyaiHai,

You shouldn't use audioManager.setSpeakerphoneOn method when using our SDK, it will conflict with setOutputAudioDevice methods.

getInput/Output audio devices return the device currently in use, getDefaultInput/Output audio device return the device used by default, when a call is made or received, unless explicitly changed by user or by app.

Cheers,

**Comment by Viish** [comment]
Hi,

Check with echo canceller calibration that hardware echo canceller works, otherwise enable software echo canceller, it should prevent that.
If not, please open an issue in linphone-sdk repository, this isn't something that falls into my area of expertise.

Cheers,

**Comment by LoyaiHai** [comment]
@Viish 
Thank you very much!
I have no questions at the moment
Cheers！

**Comment by LoyaiHai** [comment]
Hi
@Viish
I printed out the properties related to echo cancellation and found that the echo still exists in my project, but when I used your official APK, I found that the echo piercing effect was not there.
Excuse me, what is this about?
Here are the interface results related to echo cancellation:
int echoCancellationCalibration = currentCore.getEchoCancellationCalibration();// echoCancellationCalibration = 0
boolean echoCancellationEnabled1 = currentCore.isEchoCancellationEnabled();// echoCancellationEnabled1 = true
String echoCancellerFilterName = currentCore.getEchoCancellerFilterName();// echoCancellerFilterName = null
boolean echoLimiterEnabled = currentCore.isEchoLimiterEnabled();// echoLimiterEnabled = true
boolean echoCancellerCalibrationRequired = currentCore.isEchoCancellerCalibrationRequired();// echoCancellerCalibrationRequired = false
boolean builtinEchoCanceller = currentCore.hasBuiltinEchoCanceller();// builtinEchoCanceller = false

Below is a video of the echo：

https://github.com/BelledonneCommunications/linphone-android/assets/32878163/41470165-5c87-46b4-a0ea-58ba4566d761


Thanks Viish
Cheers!

**Comment by Viish** [comment]
Hi,

It could be a lot of things.
This is getting really specific, so if you really need our help with that please contact us through our website https://linphone.org/contact and we'll send you a quotation for either dev-assist or support contract.

Cheers,

**Comment by LoyaiHai** [comment]
Hi
@Viish
Cooperation is easy to say, but now the problem is that the latest version of your official demo, on our equipment, there are also current sound and echo. If there are no problems with your demo, we would be happy to cooperate with you. But the official demo is also like this, and it is difficult for me to give feedback to the leader

Thanks Viish
Cheers!

**Comment by LoyaiHai** [comment]
Hi
@Viish
I really respect your determination, but here is a question I want to know, you said linphone sdk version 5.2.0, why I have seen 5.3.0-beta in the warehouse version? Which one should I use if I am integrating through.AAR?

Thanks Viish
Cheers!

**Comment by Viish** [comment]
@LoyaiHai,

5.2.0 will be the version code of the next release for the app. For the SDK the next release will be 5.3.0.
Current app release is 5.1.4 and SDK 5.2.112.

Cheers,
