### ISSUE TITLE
About keep alive sent to [UDP://linphone.service.ip:port]

### ISSUE THREAD

**Issue by LoyaiHai** [BelledonneCommunications/linphone-android#2057]
HI
@Viish 
I already know that the unit of [sip]keepalive_period=30000 in assets/linphonerc_default is milliseconds. At the same time, I also obtained the logs sent every 30 seconds through the log printing:
I/linphone: channel [0xc7aca980]: keep alive sent to [UDP://linphone_service:port]
Question: Is there any callback for this sent heartbeat packet? Because when I restart the service and disconnect the network, I will also see this heartbeat packet running, but I do not know what the result is after it is sent.

Thanks Viish
Cheers!

**Comment by Viish** [comment]
Hi,

No, there is no callback for the sent alive.

Cheers,
