### ISSUE TITLE
Conference not joining all participants

### ISSUE THREAD

**Issue by remiquezada** [BelledonneCommunications/linphone-android#2061]
Hi,

Having issues when conferencing two calls.  I place two outbound call and then hit the conference button the two remote call joins but it does not join my audio.  I get a message at the bottom that says "All other participants have left the group."  In order for me to join the group I have to go back and press the conference button again then I join the group.  Doesn't seem like this should be normal behavior having to hit the conference button twice in order to join the conference.

4. **Please complete the following information** (mandatory)

 - Device: Google Pixel 7a
 - OS: Android 14
 - Version of the App 5.1.4
 - Version of the SDK 5.2.110
 - Where you did got it from:  Play Store
 - Please tell us if your Android is a Lineage OS or another variant.

I am sending the logs that only show when I pressed the conference button the first time:

https://www.linphone.org:444//tmp/6581bc6658b5b_996f2512c63e6923dce8.gz

**Comment by LoyaiHai** [comment]
Hi
@remiquezada 
What is your specific process for initiating a video conference? Can you specify which interface was invoked?
Thank you

**Comment by remiquezada** [comment]
Hi @LoyaiHai,

This is not video conference just audio conference.  I go to the call list interface while I am on the first call and from there I add a second call.  Then once the second call answers I go back to the call list interface and press the conference icon to initiate the conference.  After that is when I get the message "All other participants have left the group" and does not join my local audio to the audio conference.

Thanks

**Comment by Viish** [comment]
Hi,

I just pushed a fix for locally merged calls in Android app.
It will be part of 5.2.2 release.

Cheers,

**Comment by mircoiplabs** [comment]
Hello,
I have the same issue, when I start the conference I receive the advice "All other participants have left the group" and the user is excluded from the conference, but the others two members are merged and working in conference...
Also, when I press the hangup button it doesn't close the conference, it seems from debugger that **_core.conference.isIn_** is "false", so it doesn't close the conference.

Version 5.2.5, SDK 5.3.60
