### ISSUE TITLE
Why phone was picked up but Call State still in "OutgoingEarlyMedia" not in "Call.State.Connected"?

### ISSUE THREAD

**Issue by fazilmuammar** [BelledonneCommunications/linphone-android#2062]
[Hi]([url](url)) @Viish  i have an issue when i'm calling and  phone was picked up and connected, but a Call State still in "OutgoingEarlyMedia" not in "Call.State.Connected" and then  after 15 or 20 seconds call is disconnected and return error message from linphone "Temporary Unavailable"

this issue happens sometimes not always.

btw i'm using linphone sdk 5.2.112.aar

thank you

**Comment by Viish** [comment]
Hi @fazilmuammar,

OutgoingEarlyMedia means the other end of the call is hearing you (and maybe even viewing you) while on your end the call is still ringing.
If the remote end of the call doesn't accept it, it won't go to Connected state in which each party can hear/see the other one.
As it is a "outgoing" call state, when the call acceptation timer triggers, if the remote end didn't accept the call by then it will be terminated like any outgoing call.

Cheers,

**Comment by fazilmuammar** [comment]
Hi @Viish 

I see. but the problem is when the remote accept the call, Call State stiil in "OutgoingEarlyMedia" not in Call State "Connected" can you help me why?
![Screenshot 2023-12-20 at 21 28 50](https://github.com/BelledonneCommunications/linphone-android/assets/27413459/ba3fe7cc-0e95-41e5-8892-caaf031ee63e)

Cheers,

**Comment by Viish** [comment]
Please attach the verbose logs from the app from the start to the moment you have the issue.

**Comment by fazilmuammar** [comment]
Okay i will send soon. thank you @Viish 

Cheers,

**Comment by fazilmuammar** [comment]
Hi @Viish 
It happens again. I attached this log
[log_linphone.txt](https://github.com/BelledonneCommunications/linphone-android/files/13734959/log_linphone.txt)

thank you

**Comment by Viish** [comment]
@fazilmuammar you are not using 5.2.112 SDK but 5.1.0-alpha, please update to 5.3.0 (just released).

Also you log file doesn't trace of any call.

**Comment by Viish** [comment]
Hi @fazilmuammar,

What I see on your video is what I already told you: the call is in OutgoingEarlyMedia state and waits for the remote end to pick it up.

Regarding the SDK, from your previous log file there is : ```
2023-12-21 10:49:01.236 26508-26508 Hello Linphone     id.co.amfs.bancassurance.uat     I Initializing LinphoneCore 5.1.0-alpha-169-gc12724d7a
``` so it wasn't using 5.2.112.
Anyway SDK 5.3.0 has been published this morning, so you should update to it as we no longer support 5.2.X anymore.

And please attach a log file showing the call SIP transaction.

Cheers,

**Comment by fazilmuammar** [comment]
hi @Viish  i was pick up the phone in video but the page still on "Outgoing Call" @Viish 

it should be like this if i pick up phone 
![photo_linphone](https://github.com/BelledonneCommunications/linphone-android/assets/27413459/ad2535b2-0795-4e4f-aa09-b2a8f640cb48)

Okay i will update sdk 5.3.0

Cheers
