### ISSUE TITLE
NAT/Public-Private issue

### ISSUE THREAD

**Issue by disolaterX** [BelledonneCommunications/linphone-android#2063]
Hi @Viish Hope you are doing good.

Hey I am having issue, 

So if I use a another client and achive this

2023/12/20 06:00:37.289646 22.71.17.9:29864 -> 10.140.0.5:5080
INVITE sip:999xxxxx499@35.00.43.32:5080;transport=tcp SIP/2.0
Via: SIP/2.0/TCP 192.168.1.7:52723;rport;branch=z9hG4bKPjzjxS6-DScBusQcFRC8k365H1kyFIpBA0
Max-Forwards: 70
From: <sip:su_999@35.00.43.32>;tag=XQhNAquAF-h5RnAH7zTtfw-63eIiveIQ
To: <sip:999xxxxx499@35.00.43.32>
Contact: <sip:s999@22.71.17.9:29864;transport=TCP>
Call-ID: PcFTMFfgKaoBdBb469kdUuJegBspCA.x
CSeq: 26796 INVITE
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
Supported: replaces, 100rel, timer, norefersub
Session-Expires: 1800
Min-SE: 90
User-Agent: ABTOLLC
Content-Type: application/sdp
Content-Length:   276

v=0
o=- 3912040835 3912040835 IN IP4 22.71.17.9
s=-
t=0 0
m=audio 7528 RTP/AVP 107 101
c=IN IP4 22.71.17.9
a=rtcp:19583 IN IP4 22.71.17.9
a=sendrecv
a=rtpmap:107 opus/48000/2
a=fmtp:107 maxplaybackrate=16000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15

in here the client  correct public ip address in contact header

but linphone is not able to do this even after stun

2023/12/20 06:15:12.093990 22.71.17.9:15383 -> 10.140.0.5:5080
INVITE sip:9999xxxx99@35.00.43.32:5080 SIP/2.0
Via: SIP/2.0/TCP 192.168.1.7:47618;branch=z9hG4bK.O05vN1PsH;rport
From: "999" <sip:999@35.00.43.32>;tag=tJCKVx2aO
To: sip:9999xxxx99@35.00.43.32
CSeq: 20 INVITE
Call-ID: wcWWdaeGNm
Max-Forwards: 70
Supported: replaces, outbound, gruu, path, record-aware
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO, PRACK, UPDATE
Content-Type: application/sdp
Content-Length: 350
Contact: <sip:999@35.00.43.32;gr=urn:uuid:11a81308-5726-0067-b8d8-fd5d8d16e987>;+sip.instance="<urn:uuid:11a81308-5726-0067-b8d8-fd5d8d16e987>";+org.linphone.specs="lime"
User-Agent: LinphoneAndroid/5.1.4 (moto g73 5G) LinphoneSDK/5.2.110 (tags/5.2.110^0)

v=0
o=999 3774 2956 IN IP4 192.168.1.7
s=Talk
c=IN IP4 192.168.1.7
t=0 0
a=rtcp-xr:rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics
a=record:off
m=audio 56915 RTP/AVP 96 101
a=rtpmap:96 opus/48000/2
a=fmtp:96 useinbandfec=1
a=rtpmap:101 telephone-event/48000
a=rtcp:60879
a=rtcp-fb:* trr-int 1000
a=rtcp-fb:* ccm tmmbr

But this is something that don't work in linphone

**Comment by Viish** [comment]
Hi @disolaterX,

Please attach the whole logs.

Cheers,

**Comment by Viish** [comment]
Closing until requests logs will be provided.
