### ISSUE TITLE
Cannot Compile Code Suddenly started showing error..

### ISSUE THREAD

**Issue by Adnan-addi** [BelledonneCommunications/linphone-android#2064]
![linphonebug](https://github.com/BelledonneCommunications/linphone-android/assets/25033749/3950d3f4-94b7-4261-bd4f-50274e0aa125)

@Viish please help

**Comment by Viish** [comment]
@Adnan-addi this is already fixed, simply use/cherry-pick commit id 01b622de from release/5.2 branch.
