### ISSUE TITLE
About screen rotation

### ISSUE THREAD

**Issue by LoyaiHai** [BelledonneCommunications/linphone-android#2065]
Hi
@Viish
When I was using the official demo, I found that there would be a pause interval when switching between horizontal and vertical screens in a video call. Is this normal?
Another question: I am currently using Java native code, and in kotlin's code, I have a hard time finding a place for screen rotation, can you tell me which class screen rotation is implemented in video calls?

Thanks Viish
Cheers!

**Comment by Viish** [comment]
HI @LoyaiHai,

> When I was using the official demo, I found that there would be a pause interval when switching between horizontal and vertical screens in a video call. Is this normal?

Yes, it takes a small amount of time to stop & restart the camera capture.

> Another question: I am currently using Java native code, and in kotlin's code, I have a hard time finding a place for screen rotation, can you tell me which class screen rotation is implemented in video calls?

There is nothing to find, as we do nothing. Android is handling the screen rotation directly, our app doesn't care of the screen orientation, there's no listener for such event.

Cheers,

**Comment by LoyaiHai** [comment]
Hi
@Viish
I'm so sorry, maybe there's something wrong with my expression, so let me reframe it.
I used device A and B to make A video call, and at this time device A and B were forced to portrait. When both devices are in portrait mode, the display is normal. When I rotate device A 90 degrees counterclockwise, the local camera display in device A also rotates 90 degrees counterclockwise. At this time, when I looked at the remote camera of device B, I found that the actual display result was inconsistent with the display effect of the local camera in device A. As shown in the picture below:

prerotation:
deviceA
![deviceA_rotate_before_F](https://github.com/BelledonneCommunications/linphone-android/assets/32878163/aa1cf4f4-47dd-46bb-82e9-af105dfbe274)
deviceB
![deviceB_before_F](https://github.com/BelledonneCommunications/linphone-android/assets/32878163/15f72cb7-dd07-444b-9dea-611a0dbee39a)

post-rotation:
deviceA
![deviceA_rotate_after_F](https://github.com/BelledonneCommunications/linphone-android/assets/32878163/d5e055b3-0a89-413a-a456-604fa7bfe40a)

deviceB
![deviceB_after_F](https://github.com/BelledonneCommunications/linphone-android/assets/32878163/19260940-2b3d-47c8-87a4-4668c22e7603)

Could you please tell me whether there is an interface to input rotation Angle to dynamically change the direction of the displayed camera?
Another question is, is there a callback interface that listens to the remote device that has rotated the screen?

Thanks Viish
Cheers!

**Comment by LoyaiHai** [comment]
Hi
@Viish
I tried using Core.setDeviceRotation(90), but this interface changes the direction of the local camera on the current device, and the direction of the remote camera seen on the other device also changes
Do you have two interfaces that can be realized: one interface controls the rotation direction of the local camera, and the other interface controls the rotation direction of the locally encoded camera?
Thanks Viish
Cheers!

**Comment by Viish** [comment]
HI @LoyaiHai,

No you don't need to do anything, everything is handled by the Core itself (computing the device rotation degrees and correcting the preview orientation) as long as you are using CaptureTextureView object from our SDK.
From your screen I'd say the issue is simply that you disabled device rotation because the status bar isn't on top when your device is in landscape mode.

Cheers,

**Comment by LoyaiHai** [comment]
Hi
@Viish
Control I use your CaptureTextureView control, then according to what you said, I disable device rotation, then how can I achieve the effect I want?

Thanks Viish
Cheers!
