### ISSUE TITLE
When using the Linphone app for a video call on Android 11, the H264 decoding is black screen and stuck

### ISSUE THREAD

**Issue by jianhui1012** [BelledonneCommunications/linphone-android#2066]
1. **Describe the bug** (mandatory)

In the Linphone demo, 1. In the network settings, close the random port and set it to the default 5060. 2. In the video settings, enable only H.264. Then device A makes a video call to device B through the IP address. Device B has a black screen and gets stuck.

2. **To Reproduce** (mandatory)

1. Enter the address of device B: sip:1002@192.168.30.xxx
2. Device A makes a video call to device B.

3. **Expected behavior** (mandatory)

Expected: normal display
Actual, Black screen.

4. **Please complete the following information** (mandatory)

 - Device: Z15 cpu:A133p
 - OS: Android 11
 - Version of the App release/5.2 branch
 - Version of the SDK 5.3.1
 -  Play Store, also local build

5. **SDK logs** (mandatory)
[log.txt](https://github.com/BelledonneCommunications/linphone-android/files/13748928/log.txt)

**Comment by Viish** [comment]
Hi,

There are a lot of `Linphone(21190): MediaCodecDecoder: output buffers has changed` logs in the file you attached.

Given the unusual device you are using it's likely it's firmware is implementing MediaCodec API differently that mainstream devices.
This is something that we can't fix or workaround without having our hands on the device directly.

If you are willing to, you can contact our company to get a quotation for this development using the contact form on our website : https://linphone.org

Cheers,
