### ISSUE TITLE
Registration impossible when network down (help wanted - question)

### ISSUE THREAD

**Issue by sfxsfxsfxsfx** [BelledonneCommunications/linphone-android#2069]
Hello,
We are starting a call after successfully logging in. Our sip server asterisk is expiring our credentials when the call is connected.
When I close the network, my account status changes immediately and shows the following logs 

`onAccountRegistrationStateChanged::None - Registration impossible (network down)`

By the way, if I connect again sip server continues the call. But I don't receive any event about the current call state change

Is there any way or config to preserve our registration state? I mean I want to keep the registration state even if the connectivity changes. I mean, Just updating the active call state without any registration change.

Currently since our credentials expired, linphone retry registration and it  fails while ongoing call
`
onAccountRegistrationStateChanged::Failed - Forbidden`

Thanks in advance

**Comment by Viish** [comment]
Hi @sfxsfxsfxsfx,

No, there are no way to do what you desire with our SDK at the moment, sorry.

Cheers,
