### ISSUE TITLE
Limited paste option in password field 

### ISSUE THREAD

**Issue by luison** [BelledonneCommunications/linphone-android#2070]
Hi, just noticed what I understand is a bug in the Android version

I noticed if I push a password to my phone and then paste it in the password field to configure an account, it does not do it correctly as it seems to limit the pasting size to some 10/12 characters.

As you can not see it after pasted, it took me hours to figure this was the issue and had to write it manually.

This applies to a SIP account on the configuration option and perhaps also the assistant, but at least the assistant has a "show password" button.

Additionally, to fixing this, it would be great to have a way to "see" the passwords in the configuration on a click or button.

 - Device: Xiaomi 12T
 - OS: Android 13 - MIUI 14
 - Version of the App 5.2.1
 - from Play Store

**Comment by Viish** [comment]
Hi @luison,

I can assure you there is nothing in our app that limits the size of a password (whether you are copying it or typing it) to 10/12 characters.
When something is copied into Android's clipboard you can see it, I recommend you to check there that the value is as expected.

Cheers,
