### ISSUE TITLE
version "Dec 23, 2023" echo cancellation not working (Xiaomi Redmi Note) 

### ISSUE THREAD

**Issue by leukimi** [BelledonneCommunications/linphone-android#2071]
Hi,

This is a positive bug report which is filed to help, although it is less than perfect.

# linphone (android) version "Dec 23, 2023" echo cancellation not working (Xiaomi Redmi Note)

The other calling party after new install had no luck to avoid hearing themselves in echo after 2 seconds. Despite trying to activate echo cancellation and both fiddling with speaker/earphone/different microphones and gains. I did not hear myself in an echo.

 Y E S  : reproduce it with linphone-android latest release from the Play Store. Tried a good half an hour to remedy it.

**Result**

... with some feedback from the other end:

Probably nothing new for you at the developing side: 

The other party does no longer want to use `linphone` for android due to severe echo issue. It literally took seconds to come to that conclusion on the other end. The user interface was considered difficult with repeated mistakes. Setting up the account first time on Android was perceived as difficult. Too many settings for some users, which maybe suggests to hide **all** settings for users who are new to `linphone` on android and enable them only if the user is interested in it. A lot more real-time automatic configuration might be needed.

**To Reproduce**

Set up a long distance call on a Xiaomi Redmi Note and check for echo cancellation. Echo cancellation is turned off, fails, and does not improve sound. Speaker off and Bluetooth earphones did not remove echo. 

**Expected behavior**

New users should not opt for uninstalling the app within seconds. Zero patience. Somehow many compare the user experience with that of Signal, which is perceived as easier. Signal hides all voice and video settings and has a perfect echo cancellation. On the other hand, Signal tends to drop words spoken in low voice with not good enough signal-to-noise ratios. Linphone transmits all that is said in low voice with very audible detail, even on low band withs.

 - Device: Xiaomi Redmi Note (Android user does not know which number)
 - OS: Android User does not know version. Two years old.
 - Version of the App: Google Play does not show version number, only "Updated version Dec 23, 2023". See [https://play.google.com/store/apps/details?id=org.linphone](https://play.google.com/store/apps/details?id=org.linphone)
 - Version of the SDK: User does not know (obviously).
 - Where User got it from: GuglPlay (obviously)
 - Please tell us if your Android is a Lineage OS: No Lineage OS. Xiaomi OS from factory. No tampering except usage on a sandy beach which was supposed to have destroyed the microphone but with Linphone it was obvious that the microphone is superb.

**SDK logs**

Android User not capable of producing logs. Sorry. Too difficult for Android User. This part is obviously nearly impossible to help out with having a non-techy user on the other end far away.

It would be a miracle if the Android User did not uninstall the app already. Hence this bug report so you know what reactions are out there and can gather some idea about how difficult it is to get some feedback from users that is usable for a bug report.

Side Note: Both `linphone-android` and `linphone-desktop` has improved it's echo cancellation capability, but it is still annoying with the "could not detect echo" message, even though users experience it. User tapping "echo cancellation button" would tell linphone that there is an echo issue on one end although not being detected by the software on that end.

**Comment by Viish** [comment]
Hi @leukimi,

If the remote end of a call hears echo, it's because your device doesn't handle it well.
What version of Linphone Android do you have and what model/brand is it?

Cheers,

**Comment by Viish** [comment]
Thanks. Could you attach logs from your app for that call please?

**Comment by Viish** [comment]
Could you enable debug logs first please?

**Comment by Viish** [comment]
Hi @leukimi,

Given your logs you have done something to disable the hardware echo canceller, so it uses a software one but it wasn't calibrated, hence the echo.
You should remove any custom flag set for your device in mediastreamer2 devices table.

Cheers,
