### ISSUE TITLE
How to Register Linphone Account on Specific Ports in SDK v5.2.107

### ISSUE THREAD

**Issue by Mahe2027** [BelledonneCommunications/linphone-android#2072]
I am currently using Linphone SDK v5.2.107 in my Android application and am facing difficulties registering a Linphone account on specific ports, particularly for UDP/TCP (5070) and TLS (5071).

Could you please provide guidance on how to achieve this using the latest SDK version? Any insights or code snippets would be greatly appreciated.

**Comment by Viish** [comment]
HI @Mahe2027,

Simply follow our [Account Login tutorial](https://gitlab.linphone.org/BC/public/tutorials/-/tree/master/android/kotlin/1-AccountLogin), but replace
```
// We also need to configure where the proxy server is located
val address = Factory.instance().createAddress("sip:$domain")
```
by 
```
// We also need to configure where the proxy server is located
val address = Factory.instance().createAddress("sip:$domain:5071")
```

Cheers,

**Comment by Mahe2027** [comment]
thanks for it
