### ISSUE TITLE
lftp not uploading

### ISSUE THREAD

**Issue by davidcsi** [BelledonneCommunications/linphone-android#2073]
Hello,

I'm trying to get the logs delivered to a custom server. In order to do this i set `log_collection_upload_server_url` to my https server. Problem is it's not uploading anything and i can't figure out what's wrong. 

Do you have maybe a sample lftp.php file?

Thanks

**Comment by Viish** [comment]
Hi @davidcsi,

Yes we have one here: https://gitlab.linphone.org/BC/public/flexisip-http-file-transfer-server

Cheers,

**Comment by davidcsi** [comment]
Awesome! Thanks @Viish !!
