### ISSUE TITLE
Create contacts without Addressbook permissions

### ISSUE THREAD

**Issue by muelli** [BelledonneCommunications/linphone-android#2074]
Hi :)

1. **Describe the bug** (mandatory)

I'm using the Linphone 5.1.4 from F-Droid and I want to add a contact without giving Linphone access to my whole addressbook but the app does not let me create any contacts :(

2. **To Reproduce** (mandatory)

Install the app, do not give Addressbook permissions, try to add a contact.

3. **Expected behavior** (mandatory)

I want to add a contact make a name appear when a certain number calls rather than the naked number.

**Comment by Viish** [comment]
Hi @muelli,

Currently you can't add a contact if the permission to add it to your native addressbook wasn't granted.
However this will change with 6.0 release of the app, as it will let you create contacts inside the app without that permission (it won't even require the WRITE_CONTACTS one anymore).
That version should be released between June and July.

Cheers,
