### ISSUE TITLE
How to make the H264 codec not rely on hardware

### ISSUE THREAD

**Issue by xiaokuang95** [BelledonneCommunications/linphone-android#2077]
hello

My device doesn't seem to support hardware encoding and decoding. The CPU of the device is mt6737m, so I need hardware independent encoding and decoding 'MH', 'S3711', 'mt6737m'

**Comment by Viish** [comment]
Hi,

All Android devices above 6.0 should implement MediaCodec APIs to have hardware accelerated H264 encoder/decoder.
If really your device doesn't have it, the only solution is to rely on OpenH264 but that comes with constraints.
Take a look at https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Android%20specifics/Codec%20H264%20on%20Android/

Cheers,

**Comment by xiaokuang95** [comment]
> Hi,
> 
> All Android devices above 6.0 should implement MediaCodec APIs to have hardware accelerated H264 encoder/decoder. If really your device doesn't have it, the only solution is to rely on OpenH264 but that comes with constraints. Take a look at https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Android%20specifics/Codec%20H264%20on%20Android/
> 
> Cheers,

OpenH264DownloadHelper cannot be found in sdk5.2, it is outdated. Is there a latest solution?
