### ISSUE TITLE
No auth info found for call id

### ISSUE THREAD

**Issue by meetVora1994** [BelledonneCommunications/linphone-android#208]
Hi,

I am trying to call a sip number, but this error appears in the DEBUG log. I have looked for packets. First INVITE packet is sent and then ACK is received. Then after this error appears. So from device side, the re-invite packet is not being sent.
Any help.

[P.S. Getting this error while my domain is on another port (9449). But I think I changes that port value everywhere. So that port value change can't be a issue.]

**Comment by Jaimin-Hodusoft** [comment]
Facing same issue it wasted my week. If you find solution please get me back.

**Comment by juha-h** [comment]
I noticed the same in Android Linphone.  I have two accounts: foo@test.tutpro.com and xxx@tutpro.com.  For some reason Linphone uses tutpro.com as auth real also for  foo@test.tutpro.com:

03-06 15:53:29.591 15421 15421 I Linphone: linphone_core_find_auth_info(): returning auth info username=foo, realm=tutpro.com

That is incorrect and could explain why auth info is not found when registrar returns 401:

03-06 15:53:31.728 15421 15421 I Linphone: channel [0x8cb0a6c0]: received [492] new bytes from [TCP://192.168.43.82:5060]:
03-06 15:53:31.728 15421 15421 I Linphone: SIP/2.0 401 Unauthorized
03-06 15:53:31.728 15421 15421 I Linphone: Via: SIP/2.0/TCP 192.168.43.1:54231;alias;branch=z9hG4bK.EZByrtb92;rport=54231;received=192.168.43.1
03-06 15:53:31.728 15421 15421 I Linphone: From: <sip:foo@test.tutpro.com>;tag=IqtbwlAim
03-06 15:53:31.728 15421 15421 I Linphone: To: sip:foo@test.tutpro.com;tag=9e905984d60e86572d442e562bb2d3a2.ac9d
03-06 15:53:31.728 15421 15421 I Linphone: CSeq: 24 REGISTER
03-06 15:53:31.728 15421 15421 I Linphone: Call-ID: eVeBJtyIHJ
03-06 15:53:31.728 15421 15421 I Linphone: WWW-Authenticate: Digest realm="test.tutpro.com", nonce="Wp4D11qeAqv9mGB16+bl/VyCUE7iK+BFkxRh8g5f7cG20pjuoeR96mBPOpGA", qop="auth"
03-06 15:53:31.728 15421 15421 I Linphone: Server: OpenSIPg SIP Proxy (5.1.1-7 (x86_64/linux))
03-06 15:53:31.728 15421 15421 I Linphone: Content-Length: 0
03-06 15:53:31.728 15421 15421 I Linphone: 
03-06 15:53:31.728 15421 15421 I Linphone: 
03-06 15:53:31.737 15421 15421 I Linphone: channel [0x8cb0a6c0] [492] bytes parsed
03-06 15:53:31.737 15421 15421 I Linphone: Found transaction matching response.
03-06 15:53:31.738 15421 15421 I Linphone: Changing [client] [REGISTER] transaction [0x8c1c76e0], from state [TRYING] to [COMPLETED]
03-06 15:53:31.738 15421 15421 I Linphone: Linphone core [0x8e51fd80] notified [authentication_requested]
03-06 15:53:31.738 15421 15421 I Linphone: Linphone core [0x8e51fd80] notified [auth_info_requested]
03-06 15:53:31.738 15421 15421 I Linphone: No auth info found for call id [eVeBJtyIHJ]

**Comment by meetVora1994** [comment]
@juha-h Thanks for the info.
I have fixed this by setting Realm same as the domain (which we provide at login)

**Comment by juha-h** [comment]
Well, the bug is still there and needs to be fixed.

**Comment by sivakg2000** [comment]
Yes. I'm also facing the issue.
