### ISSUE TITLE
Instant messaging is not working with account

### ISSUE THREAD

**Issue by Mahe2027** [BelledonneCommunications/linphone-android#2081]
when I register account using -

     val serverAddress = Factory.instance().createAddress("sip:${domain}:${port}")
        
        // Create and configure the account parameters
        val accountParams = core.createAccountParams()
        accountParams.identityAddress =
            Factory.instance().createAddress("sip:${username}@${domain}")
        accountParams.serverAddress = serverAddress
        accountParams.transport = transportType.value
        accountParams.isRegisterEnabled = true

        // Create and add the new account to the core
        val account = core.createAccount(accountParams)

        // Create and add the auth info for the account
        val authInfo =
            Factory.instance().createAuthInfo(username, null, password, null, null, domain, null)
        core.addAuthInfo(authInfo)

        core.addAccount(account)
        
        sip call outgoing and incoming both are working but sip outgoing instant messaging is not working.
        
        and when I registered using -
        
        
    private fun configureGenericAccount(displayName: String? = null) {
        // Log and load default configuration values
        coreContext.core.addListener(coreListener)
        coreContext.core.loadConfigFromXml(corePreferences.defaultValuesPath)
        // Initialize account creator
        if (!::accountCreator.isInitialized) {
            accountCreator = getAccountCreator()
        }
        // Configure the account creator with provided parameters
        accountCreator.username = username.value
        accountCreator.password = password.value
        accountCreator.domain = domain.value
        accountCreator.transport = transportType.value
        displayName?.let { accountCreator.displayName = it }

        if (accountCreator.username.isNullOrEmpty() ||
            accountCreator.password.isNullOrEmpty() ||
            accountCreator.domain.isNullOrEmpty() ||
            accountCreator.transport == null
        ) {
            Log.e("AccountCreator", "Missing required parameters")
        } else {
            val existAccount = doesAccountExist()
            if (existAccount != null) coreContext.core.removeAccount(existAccount)

            val account = accountCreator.createAccountInCore()
            if (account == null) {
                Log.e("AccountCreator", "failed to create")
            }
        }
  }
  
  Every thing is working fine.
  
  
  why outgoing instant messaging is not working with above configuration.
  
  Same Server and device I'm using for both.
  
  I want to register account with specific port that's why I want use first one.
  
  Please help with it.
  
  Thanks

**Comment by Viish** [comment]
Hi,

Please attach debug logs from SDK, I can't tell you just like that.

Cheers,
