### ISSUE TITLE
Create Account issue when using three digits country codes like Libya

### ISSUE THREAD

**Issue by rakshitchoudhary** [BelledonneCommunications/linphone-android#2084]
Hi,

I'm using linphone sdk (org.linphone:linphone-sdk-android:5.2.1) in our application.
When we are creating a new account in the app, the user enter their number and selects country code. 
In most of the cases, everything works fine but when the user selects a three digit country code like (Libya - +218).
Then the first digit of the number gets omitted automatically from the SDK side. 

Before passing the number and country code in **"accountCreator.setPhoneNumber()"**, the number is fine. But after this when we receive the number using **accountCreator.getPhoneNumber()**. The number first digit is omitted.

For example, I'm passing number - 931367399 and country code - +218 in **"accountCreator.setPhoneNumber()"** and the response which I get from **accountCreator.getPhoneNumber()** is +21831367399.

This is happening on all the android devices.

 - Device: Pixel 3
 - OS: Android 12
 - Version of the SDK - 5.2.1
 - Where you did got it from - Github
 - Android OS

Please let me know if anyone is facing same issue and how to fix this.

Thank you,

Rakshit Choudhary
![WhatsApp Image 2024-01-10 at 10 03 32 PM](https://github.com
![WhatsApp Image 2024-01-10 at 10 03 33 PM](https://github.com/BelledonneCommunications/linphone-android/assets/5500953/7e11e116-f8fb-4ecc-9252-382ca72f7053)
/BelledonneCommunications/linphone-android/assets/5500953/f5011c39-eca2-4138-9e25-81055fecdf65)

**Comment by rakshitchoudhary** [comment]
Hi, This issue is not closed. We are still facing this issue on our sdk.

**Comment by Viish** [comment]
Hi @rakshitchoudhary,

As explained in https://github.com/BelledonneCommunications/linphone-iphone/issues/911#issuecomment-1900121814, the issue has already been fixed in 5.3 version of our SDK.

That being said, let me remind you that not renewing your contacts doesn't allow you the right to update your SDK, unless you respect the GPL-v3 license in your app, which doesn't seem to be the case.
I strongly recommend you to get in touch with our sales department.

Cheers,

**Comment by rakshitchoudhary** [comment]
Hi @Viish,

Thank you for replying back on the issue. I'll update my SDK version to 5.3 and check for the issue.

Also regarding the SDK updation and GPN-v3 license part. I'm a mere developer in a big organisation and not authorised to do this and am not aware of this. I'll inform my heads about this.

Regards,
