### ISSUE TITLE
Assistant screen should be scrollable

### ISSUE THREAD

**Issue by Saphar** [BelledonneCommunications/linphone-android#2085]
First of all, please say "Hi" or "Hello", it doesn't cost much.

1. **Describe the bug** (mandatory)

If you have a device with small screen and you have your display size and font size on Large, the button is not visible to accept the terms.

2. **To Reproduce** (mandatory)

Go to Assistant, choose Use Sip Account, the next screen the accept button is not visible.

3. **Expected behavior** (mandatory)

Ability to scroll down to the bottom of the page.

4. **Please complete the following information** (mandatory)

 - Device: Cat S22 Flip
 - OS: Android 11
 - Version of the App 5.1.3
 - Version of the SDK 5.2.99
 - Where you did got it from F-droid
 - Please tell us if your Android is a Lineage OS or another variant. (Yes, running Lineage)

7. **Screenshots** (optional)

![Screenshot_20231221-140200_Linphone](https://github.com/BelledonneCommunications/linphone-android/assets/43345112/f379993e-0cd0-4236-ba0c-cf03bbadec4b)

**Comment by SB2318** [comment]
Hello @Viish, I would be delighted to give it a try! Please let me know the current status of the problem and whether it has been resolved or not.

**Comment by Saphar** [comment]
It is not fixed in 5.2.5

**Comment by Viish** [comment]
> It is not fixed in 5.2.5

@Saphar no, but it will be in 6.0.

**Comment by SB2318** [comment]
> > It is not fixed in 5.2.5
> 
> @Saphar no, but it will be in 6.0.

okay, Thanks for the information.

**Comment by Viish** [comment]
Fixed in 6.0.0 alpha now available in master branch.
