### ISSUE TITLE
No audio on outside local network with xiaomi

### ISSUE THREAD

**Issue by geramia** [BelledonneCommunications/linphone-android#2087]
Hi,
I have an odd issue only with xiaomi phones (at least I think so)

We have a kerio sip server at our company which works fine.
When I am connected to the company wifi local net every thing works fine.
But when I use my phone cellular internet my software connects and I can dial other lines but after my partner answers I cannot hear anything. Some of them have my voice but I have nothing.
This case gets even more odd when I use a VPN. In this situation the audio dies in both ways and no party hase the sound of the other one.

2. **To Reproduce** (mandatory)
I double checked everything with any of the codecs but no change.
Then double checked the case with other mobile phones and recognized that this issue only happens on xiaomi family such as me, redme and Poco phones.
Iphone and Motorola smartphones with the same config work well
Also I tried the situation between my phone (Poco x3) and a regular IP phone in office. No change 
Ut seems there is something wrong with my os or miui interface or something like that.

Device, Poco x3 pro
Android 12 skq1.211006.001
Miui gui 
Ver 5.2.1global 13.0.3
Sdk 5.3.2
Installed from Google play
Android lineage? I don't know!

5. **SDK logs** (mandatory)

Enable debug logs in advanced section of the settings, restart the app, reproduce the issue and then go back to advanced settings, click on "Send logs" and copy/paste the link here.

It's also explained [in the README](https://github.com/BelledonneCommunications/linphone-android#behavior-issue).

In case of a call issue, please attach logs from both devices!

6. **Adb logcat logs** (mandatory if native crash)

In case of a crash of the app, please also provide the symbolized stack trace of the crash using adb logcat.

Here's the command for a arm64 device: `adb logcat | grep ndk-stack -sym <sdk build directory>/libs-debug/arm64-v8a/`

For more information, please refer to [this section of the README](https://github.com/BelledonneCommunications/linphone-android#native-crash) file.

7. **Screenshots** (optionnal)

8. **Additional context** (optionnal)

Thank you in advance for filling bug reports properly!

**Comment by Viish** [comment]
Hi @geramia,

Could you turn on debug logs, reproduce the issue and then upload logs here please?

Thanks.
