### ISSUE TITLE
[Proxy/TUN] Not working with Routr Server for Local SIP Server

### ISSUE THREAD

**Issue by benyaminl** [BelledonneCommunications/linphone-android#2089]
Hi, I'm a novice user want to use linphone with SIP Server using routr, but seems even with proxy/STUN, it failed to connect. Could anyone give me some explanation why it happen? Because using other SIP Client, I can connect and call other parties. Thank you. 

1. **Describe the bug** (mandatory)

Tried to login into sip server using routr (https://routr.io/) sip server, with proxy/stun using IP and udp, but can't even connect

2. **To Reproduce** (mandatory)

1. Login with other sip account server
2. put in user/pass
3. change on advance user settings for the accounts
4. put the local sip server with proxy
5. not connected/failed

6. **Expected behavior** (mandatory)

It should work with proxy, and work as it should be like other sip client

7. **Please complete the following information** (mandatory)

 - Device: Redmi Note 12 Pro 5G
 - OS: Android 13
 - Version of the App :  5.2.2
 - Version of the SDK : Not sure, playstore
 - Where you did got it from Play Store
 - Please tell us if your Android is a Lineage OS or another variant. (normal variant of xiaomi)

8. **SDK logs** (mandatory)

https://www.linphone.org:444//tmp/65b1c82b113d3_e74bed908975c21964c3.gz

**Comment by Viish** [comment]
Hi,

Your issue is the DNS server at 192.168.1.1 doesn't know how to resolve your domain which seems to be "sip.local".

Also your STUN server at 192.168.1.109 doesn't seem to answer:
```
2024-01-25 09:19:37:743 [org.linphone/liblinphone] WARNING No STUN answer from [192.168.1.109:5060], continuing without STUN
```

Cheers,

**Comment by benyaminl** [comment]
@Viish is there anyway to set proxy on linphone? Seems I'm confused between stun and normal sip proxy. Thank you

**Comment by Viish** [comment]
Hi @benyaminl,

You can set your proxy server address in AccountParams using https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/AccountParams.html#setServerAddress(org.linphone.core.Address), and you can set one or more route(s) to it if needed using https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/AccountParams.html#setRoutesAddresses(org.linphone.core.Address%5B%5D)
