### ISSUE TITLE
Self Signed Certificates on Android

### ISSUE THREAD

**Issue by paff-9299** [BelledonneCommunications/linphone-android#2090]
I am wondering what the current(5.2.2) best practice is for uploading a self signed certificate for Android devices. After doing some research, it seems like there are a few different answers to solving the issue of adding self signed certificates to the Linphone Android App and I'm wondering what is the current process. From what I can gather, theres modifying files within the APK itself to point away from the rootca.pem file or the possibility of changing the config via remote provisioning. Any help would be greatly appriciated.

**Comment by Viish** [comment]
Hi @paff-9299,

I recommend you to rebuild our app with your own certificates in the rootca.pem, it's the easiest way.

Cheers,
