### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [BelledonneCommunications/linphone-android#2092]
Hi, could you please take a look? https://monitor.f-droid.org/builds/log/org.linphone/520031#site-footer Thanks!

**Comment by Viish** [comment]
Hi,

Indeed we have made a fix in the generated API that results in the build being broken.
I've just fixed it in fix/build (for master) and fix/build_5.2 (for release/5.2) branches, but it seems we have an issue with our gitlab so it won't be merged until tomorrow.

Thanks for reporting the issue!

Cheers,

**Comment by linsui** [comment]
Thanks! Will you tag a new release or we should bump the commit?

**Comment by Viish** [comment]
No It won't be tagged as another release.

**Comment by linsui** [comment]
Then please ping me when the fix is pushed. I'll update the metadta. :)

**Comment by Viish** [comment]
Hi @linsui,

Fix has been merged.

Cheers!

**Comment by linsui** [comment]
Thanks!
