### ISSUE TITLE
How to Enable and Retrieve Detailed SIP Traces in Linphone SDK?

### ISSUE THREAD

**Issue by Mahe2027** [BelledonneCommunications/linphone-android#2095]
Dear Linphone Developers,

I am currently integrating the Linphone SDK (version 5.2.107) into my Android application and I'm interested in obtaining detailed SIP traces for debugging and monitoring purposes. Specifically, I am looking to capture all SIP-related messages such as INVITE, RINGING, 200 OK, and BYE messages. These traces are crucial for understanding the SIP call flow and diagnosing any issues that may arise during call setup and termination.

Despite my efforts, I have been unable to find explicit documentation or instructions on how to enable this level of detailed logging within the Linphone SDK. Could you please provide guidance or point me to the relevant documentation on how to enable SIP trace logging in Linphone SDK for Android? Additionally, if there are specific configurations or code examples available for capturing these SIP messages, that would be greatly appreciated.

Thank you for your assistance and the incredible work on Linphone SDK. Looking forward to your response.

Best regards,
Mahee

**Comment by Viish** [comment]
HI @Mahe2027,

You can simply enable debug logs in our SDK, and then have them print in logcat tool:
```
Factory.instance().setLoggerDomain(appName)
Factory.instance().loggingService.setLogLevel(LogLevel.Message)
Factory.instance().enableLogcatLogs(corePreferences.printLogsInLogcat)
```
Call those methods at the soonest, the best is to do it before even creating the Core.

You can also upload collected logs to a file transfer server configured with `core.fileTransferServer = "https://domain.tld"` using `core.uploadLogCollection()`. You can find a sample file transfer server here: https://gitlab.linphone.org/BC/public/flexisip-http-file-transfer-server

Cheers,
