### ISSUE TITLE
ambiguous final menu when saving a contact is ambiguous (and doesn't seem to work anyway!)  (contact, phone book, address book)

### ISSUE THREAD

**Issue by UPBT** [BelledonneCommunications/linphone-android#2097]
linphone android f-droid 5.2.1 armeabi-v7a

In "app permissions" on my device, linphone has "No permissions denied" -- so not related to #688

The final step in saving a contact is to (apparently) tell linphone where to save it.

[There doesn't seem to be an easy way to embed images in a bug report.. I guess I attached a file with multiple attempts but I don't see it. It's a cropped screenshot of the dialog box I'm ranting about.]

The dialog says:

>"Choose where to save the contact"

and you get two choices (that don't necessarily look like choices. I mean the first option says "Linphone contacts" and is the same font, size and color as the "Choose where to save the contact" text. The second option doesn't look like a button either, appears to be in all caps, appears to be in a different font, and says "STORE LOCALLY" 

Setting the style of this dialog box aside for the moment...

1. The text _doesn't make sense._ One should clearly convey that the contact will go in the "global" contact list, and be accessible by any other app with the right permission; while the other option should make it clear that it will be stored in the Linphone folder only, and only be accessible by Linphone (barring an app running with root permissions of course)
2.  The choice doesn't work anyway. I've created two contacts, used one of the options for each, and both of them are able to be viewed and edited from the native phonebook app that shipped with the phone.

**Comment by Viish** [comment]
Hi @UPBT,

You'll be happy to know that this system is going to the trash with 6.0 release to come.
Instead of writing contacts created in linphone into the native addressbook, now they will be only stored in linphone.
This way we get rid of WRITE_CONTACTS permission, issues with contact saver that was bugged on some firmwares / custom Android, and the problem of asking where to save them.

Cheers,

**Comment by UPBT** [comment]
I'm a wee bit disappointed this was closed with  "completed" when there are only future plans to fix this issue.

There is a potential security risk here, because right now Linphone hints that a contact can be saved that will be exclusively accessible only by Linphone when this is not the case at all. 

You are given an illusionary choice as to how to save a contact, but the result is the same. Any app on the user's phone that has phone book access can read these private contacts.

**Comment by Viish** [comment]
Hi @UPBT,

The fix isn't in the future, it has already been developed and will be released very soon.

That being said, we never said that contact created within the app stays in the app.
As the contacts were exported, it was legitimate to ask the user in which public address book configured in their device they wanted to store it in.

**Comment by UPBT** [comment]
>As the contacts were exported, it was legitimate to ask the user in which public address book configured in their device they wanted to store it in.

Is there an actual functioning distinction between "Linphone contacts" and "STORE LOCALLY" ? 

I mean do these options do different things? Because no one commented on that when I first created the bug report. I did mention the options didn't look like buttons, had different fonts, different cases, and what I assumed each option should do (in the absence of any documentation) and no one corrected my interpretation.

>The fix isn't in the future, it has already been developed and will be released very soon.

I assumed there were options you could use to change a ticket status?

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by Viish** [comment]
Yes the current interface was far from being perfect, and yes it lacked documentation.

New interface to come has been created conjointly with UX experts specifically to improve that.

Linphone contacts is the local address book created by android and that's linked to our app, meaning that if you uninstall the app the contacts disappear with it, but it still is public.
Local contacts is the default address book of any device, and not related to any app.
If you have a synchronization app such as a carddav one, the address book would also be listed to allow for the newly created contact to be synchronized.

**Comment by Viish** [comment]
> I assumed there were options you could use to change a ticket status?

I can't do that as github isn't our primary repository hosting, it's merely a backup of our private gitlab instance.
