### ISSUE TITLE
Enhancement:  phone numbers that contain letters are still fairly common in the USA. A user should be able to dial them

### ISSUE THREAD

**Issue by UPBT** [BelledonneCommunications/linphone-android#2098]
An example: **1-800-AAA-HELP**

Try to paste this string into the dial dialog box and hit "dial" will give you a "call has been declined" message (as a "toaster" message)

Incidentally this is probably the wrong error message. The app should probably say something like "I don't know how to translate letters into digits" or something.

You may have noticed that many phones have letters printed on the buttons along with numbers. When I was stuck on the side of the road with a broken fan belt that cut the transmission coolant line, and needed to call 1-800-AAA-HELP I was fortunate that I had the ToneDef app also installed for the LOLs. I could use the ToneDef app to translate 1-800-AAA-HELP into 1-800-222-4357, which linphone allowed me to dial.  

Setting aside the removal of the letters on the linphone dial screen, the Android dialog for entering in characters (that pops up when you touch the "enter a number or an address" input area) is the "keyboard" one rather than the "dial" one (which is wrong too, If you can't "dial" letters like **"PEnnsylvania 6-5000"**, and you can't dial valid DTMF digits such as "A", "B", "C", or "D", then the alpha-numeric standard keyboard is only useful if you dial SIP numbers by hand. How often does that happen?)

I mean if I had to choose, I'd pick "letter to digit" translation over dialing SIP addresses from the keyboard, but maybe I shouldn't have to?

Maybe some kind of slider that: 

- defaults (position № 0) to digits and translates alpha to digits ( 1-800-AAA-HELP into 1-800-222-4357, like the original Blackberry phone did)
- slider position № 1 that allows you to dial SIP numbers 
- slider position  № 2 that allows you to dial all 16 DTMF digits (0-9ABCD (These are still regularly used by Amateur (Ham) Radio enthusiasts) plus standard AT commands like the comma (which is a delay before sending the next digit, useful for navigating a digital receptionist)

Position №1 and №2 could be enabled only by some obscure menu option. Some kind of "skins" could be used to change what the normal dial keyboard looks like, adding back a still relevant functionality. or allowing a customer to create a custom one for navigating voicemail menus or something?

**Comment by UPBT** [comment]
Option: interpret any "dial string" like so:

- With an "@" in the string: &nbsp; &nbsp; &nbsp; This is a SIP number
- Without an "@":  &nbsp; &nbsp; &nbsp; Translate letters into digits
- Prefixed with "ATDT":  &nbsp; &nbsp; &nbsp; A, B, C, D are valid DTMF digits, and a comma is a 3 second delay

This would keep you from having to add some kind of switch or slider, but I'm sure there will be edge cases I haven't thought of.

**Comment by UPBT** [comment]
https://en.wikipedia.org/wiki/Telephone_keypad

Most modern phone pads put Q and Z on the 7 and 9 keys, but I recall some early phones  putting them both on the 1 key was sometimes done. I don't know of any phone numbers in the USA that use Q or Z in the phone number "name". There is a standard, **ITU E.161** .

**Comment by Viish** [comment]
Hi @UPBT,

The dialer (currently the start screen in our app) is going to disappear in 6.0 release.
Please keep in mind our app is designed to primarily call SIP URIs, real world phone numbers are supported but only for accounts connected to proxy server that are connected to a PSTN gateway.
That being said it is possible we find a way to do what you desire in the 6.0 version to come, I'll think about it and discuss it with our product owner.

Cheers,

**Comment by Viish** [comment]
I'm closing this issue as we won't do it, it's too complicated to handle phone numbers with letters and SIP URIs.
