### ISSUE TITLE
Could not find org.linphone:linphone-sdk-android:5.2.110.

### ISSUE THREAD

**Issue by QuocDuc99** [BelledonneCommunications/linphone-android#2099]
Could not find org.linphone:linphone-sdk-android:5.2.110.

**Comment by Viish** [comment]
https://download.linphone.org/maven_repository/org/linphone/linphone-sdk-android/5.2.110/linphone-sdk-android-5.2.110.aar

**Comment by QuocDuc99** [comment]
thanks you

**Comment by shubham-jain2** [comment]
the linphone maven repository url is different than the one mentioned in the settings.gradle

try using url "https://download.linphone.org/maven_repository" instead of 
url "https://linphone.org/maven_repository"

**Comment by Viish** [comment]
`https://linphone.org/maven_repository` redirects to `https://download.linphone.org/maven_repository`, so for gradle it's the same thing.

**Comment by shubham-jain2** [comment]
> `https://linphone.org/maven_repository` redirects to `https://download.linphone.org/maven_repository`, so for gradle it's the same thing.

not for me, https://linphone.org/maven_repository doesn't work for me in gradle nor in browser. but https://download.linphone.org/maven_repository works in both. so I am able compile the app
