### ISSUE TITLE
User-agent in provisioning requests

### ISSUE THREAD

**Issue by lameventanas** [BelledonneCommunications/linphone-android#21]
Linphone should send a User-Agent in the HTTP provisioning requests with useful hardware and software information: app name, platform, version, mac address, device info, etc.

For example:
`User-Agent: linphone-android 3.2.4 CC3F6056809F; Samsung Galaxy S3`

CC3F6056809F would be the mac address of the used interface.

And something similar for the Iphone and desktop versions.
It gives flexibility when provisioning phones.

**Comment by Viish** [comment]
We are in the process of improving the information present in the user-agent, this will be done in the next release (4.1)
