### ISSUE TITLE
Android not playing native ringtone

### ISSUE THREAD

**Issue by basulle** [BelledonneCommunications/linphone-android#2101]
Hi, using org.linphone.no-video:linphone-sdk-android:5.1.73 for our application and for some reason Android native ringtone is not working.

When initializing the core calling these:
            this.core.setRing(null);
            this.core.setRingDuringIncomingEarlyMedia(true);
            this.core.setNativeRingingEnabled(true);

Another issue with our own ringtone, when we have the phone on Silent mode, the app plays the ringtone for 1 second and then its stops ringing.
In this case calling:
            this.core.setRing(absolutePath + "/incoming-call.wav");
            this.core.setRingDuringIncomingEarlyMedia(true);
            this.core.setNativeRingingEnabled(false);

**Comment by Viish** [comment]
Hi @basulle,

Please update your SDK to latest 5.3 version, some changes/fixes were made since 5.1 release.

Cheers,
