### ISSUE TITLE
How do I obtain the Body data sent from the freeswitch server

### ISSUE THREAD

**Issue by LoyaiHai** [BelledonneCommunications/linphone-android#2102]
Hello，
A message has now arrived from the freeswitch server in the location shown in the figure
![image](https://github.com/BelledonneCommunications/linphone-android/assets/32878163/5be537a3-dff2-445d-a20f-3623145d46ed)
![QQ截图20240221180929](https://github.com/BelledonneCommunications/linphone-android/assets/32878163/9c58d2cc-51e5-4f68-9502-33a5e1d18837)
Now the question is, is there any way for me to access this state using linphone after sending this message?

Thank you
@Viish

**Comment by Viish** [comment]
Hi @LoyaiHai,

If this is a chat message, simply iterate over it's contents and call content.getText() to retrieve your payload.

Cheers,

**Comment by Viish** [comment]
@LoyaiHai Sorry but I don't understand.
On one side you say this isn't a chat message, but using PJSIP you are relying on onInstantMesssage so it is a chat message.

That being said, you can do exactly the same as PJSIP using 

- https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/CoreListener.html#onMessageReceived(org.linphone.core.Core,org.linphone.core.ChatRoom,org.linphone.core.ChatMessage)
- https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/ChatMessage.html#getContents()
- https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Content.html#getType()
etc...

**Comment by LoyaiHai** [comment]
@Viish 
![image](https://github.com/BelledonneCommunications/linphone-android/assets/32878163/d9eaf3d8-6a35-47e8-afd0-f8e888f02a91)
When I send a message to the terminal on the PC side, I find that I do not see the corresponding message return in the callback interface, may I ask this case, which step is wrong, does it mean that I want to receive a message from someone, must subscribe first?
Thank you

**Comment by LoyaiHai** [comment]
![image](https://github.com/BelledonneCommunications/linphone-android/assets/32878163/93257307-f7c3-46a9-8a5b-9590a4f2e6f8)

**Comment by Viish** [comment]
Did you add the CoreListener to the Core?

**Comment by LoyaiHai** [comment]
Hi
@Viish 
I have set up core listening, as shown in the image below
![image](https://github.com/BelledonneCommunications/linphone-android/assets/32878163/c254d802-463f-4750-b00e-ca383e0b5f6d)
![image](https://github.com/BelledonneCommunications/linphone-android/assets/32878163/e38f7b40-b57c-4f94-a039-e764e4b1ef2c)
![image](https://github.com/BelledonneCommunications/linphone-android/assets/32878163/2b281203-7144-4bc7-91b5-5550a6e348c8)
