### ISSUE TITLE
Second SIP Account

### ISSUE THREAD

**Issue by roughnecks** [BelledonneCommunications/linphone-android#2104]
Hello,

How do I add a second sip account? If I try the assistant and fill in my credentials/domain, it fails to add the account.. Also after doing this, my primary account asks for the password again.

Thanks

**Comment by UPBT** [comment]
I've used **Assistant** :: **Use SIP Account** to add a total of three accounts without any issues beyond "fat finger" mistakes and undocumented issues with the _voip.ms_ website when you change your password multiple times in a short period of time (because you made some fat-finger mistakes.)

**Comment by Viish** [comment]
> Best of luck. The remote provisioning API seems to be undocumented -- on purpose -- as far as I can tell.

Not on purpose. It's actually the same configuration items as the one in our SDK available through the linphonerc, but we lack time to do an exhaustive list for now. We have plan to change the internal tool to have it create the full documentation automatically, but once again we lack time to do this right now.

**Comment by Viish** [comment]
So either look up configuration items you'd like in the SDK source code (most of them are in liblinphone/ submodule), or simply take a look at your existing linphonerc on your device for example to have a sample file to use for your remote configuration.
