### ISSUE TITLE
Bad pointer to CHANGELOG.md on F-Droid

### ISSUE THREAD

**Issue by UPBT** [BelledonneCommunications/linphone-android#2105]
F-Droid points me to this URL:

https://gitlab.linphone.org/BC/public/linphone-android/blob/HEAD/CHANGELOG.md

There is also a change log file on github:

https://github.com/BelledonneCommunications/linphone-android/blob/master/CHANGELOG.md

The correct, up to date change log file appears to be: 

https://gitlab.linphone.org/BC/public/linphone-android/-/blob/release/5.2/CHANGELOG.md

Is this a F-droid issue, or a mistake in configurations by Belledonne Communications?

**Comment by Viish** [comment]
Yes, the CHANGELOG in the master branch might not be as up-to-date as the one on the latest release branch, but we can't keep updating the F-Droid project changes URL link.
It's also because the master branch is currently inactive that it isn't up-to-date, and this doesn't happen very often.

**Comment by Viish** [comment]
I've updated master's branch CHANGELOG FYI.

**Comment by UPBT** [comment]
So I'm sorry to say that this is still broken. That is if the reason why F-droid links you to the change-log is because it allows you to review the changes to the version of the software that Belledonne wants you to install

Right now the f-droid app is pointing me to: 

https://gitlab.linphone.org/BC/public/linphone-android/blob/HEAD/CHANGELOG.md 

For the 5.2,5 release, however this only has change log entries up to the 5.2.3 release

https://gitlab.linphone.org/BC/public/linphone-android/-/blob/release/5.2/CHANGELOG.md

Has the changes for the 5.2,5 release

I don't know where the problem lies, but if they are writing change log notes somewhere prior to every f-droid release, (and that appears to be happening) then probably adding an `rsync` command into the release workflow should fix this issue for good.

**Comment by Viish** [comment]
Yes, I haven't updated the changelog on master's branch yet, but it will be up-to-date once I merge 6.0 release in the repository. Usually master's branch changelog is always up-to-date, but we in a specific scenario right now.

**Comment by Viish** [comment]
I've merged the updated CHANGELOG in master's branch.
