### ISSUE TITLE
Video black screen and audio is buggy

### ISSUE THREAD

**Issue by teravinesekiel** [BelledonneCommunications/linphone-android#2106]
Hi guys, i'm testing linphone on custom device with our application logic, it works on mainstream devices, but it doesn't work on our custom device which the results are video only showing blank screen and audio sounds like electric wave. any ideas why?

1. **Describe the bug** (mandatory)
Video shows black screen, and audio sounds like electric wave

2. **To Reproduce** (mandatory)

3. **Expected behavior** (mandatory)

Expected behavior video and audio should be working on mainstream device, which i already tested and it works.

4. **Please complete the following information** (mandatory)

 - Device: QBIC TD-1070
 - OS: Android 11
 - Version of the SDK: 5.3.9

5. **SDK logs** (mandatory)

The logs showing there's a "android.media.MediaCodec$CodecException: Error 0xfffffc0e" kindly check here for full logs:

[logs.zip](https://github.com/BelledonneCommunications/linphone-android/files/14399742/logs.zip)

**Comment by Viish** [comment]
Hi @teravinesekiel,

Indeed the exception causing `MediaCodecDecoder: configuration failure` will prevent your device to decode H264 video stream. Either switch to a software codec (such as AV1 or VP8) or have your device provider fix MediaCodec API in the firmware.

Regarding the audio everything looks fine in your logs.
If you need more help, please [contact our sales department](https://linphone.org/contact#content-bottom3) for a support contract quotation, we don't support "non-mainstream devices" as you call them in github tickets like this.

Cheers,
