### ISSUE TITLE
How to send SIP Notify message using linphone SDK

### ISSUE THREAD

**Issue by Mahe2027** [BelledonneCommunications/linphone-android#2112]
Hi,
Can we send SIP Notify Message from Android app using LinphoneSDK ?

Example -:

NOTIFY sip:3583@10.2.40.10:5062 SIP/2.0
Via: SIP/2.0/UDP 10.2.40.27:5063;branch=z9hG4bK4163876675
From: <sip:3586@10.2.1.48 > ;tag=2900480538
To: "3583" <sip:3583@10.2.1.48 > ;tag=490600926
Call-ID: 2923387519@10.2.40.10
CSeq: 4 NOTIFY
Contact: <sip:3586@10.2.40.27:5063 >
Max-Forwards: 70
User-Agent: Fanvil X6 1.12.5
Event: ACTIVE-URI
Content-Type: message/sipfrag
Content-Length: 6
key=OK

Thanks
Mahee

**Comment by Viish** [comment]
Hi @Mahe2027,

Take a look at https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Core.html#createNotify(org.linphone.core.Address,java.lang.String)

Cheers,

**Comment by Mahe2027** [comment]
Can we send SIP Notify messages without subscription?

**Comment by Viish** [comment]
Yes, that's why the documentation says it's `out of dialog`

**Comment by Viish** [comment]
Hi @Mahe2027,

Please take some time to search the documentation yourself, I'm not here to do that for you...
https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/CallParams.html#addCustomHeader(java.lang.String,java.lang.String)

**Comment by Mahe2027** [comment]
Thanks, I'll check it out.
