### ISSUE TITLE
Incoming call is on loudspeakers

### ISSUE THREAD

**Issue by Saphar** [BelledonneCommunications/linphone-android#2114]
Hello linphone developers,

1. **Describe the bug** (mandatory)
When I receive an incoming call and I answer it, the loudspeaker is on. It happens only on Cat S22 Flip phone, with Lineage 18. Not on any other phone.

Also, if applicable, **do you reproduce it with linphone-android latest release from the Play Store?**
I only have F-Droid releases.

2. **To Reproduce** (mandatory)
Receive incoming call, answer it.

3. **Expected behavior** (mandatory)
Should go to the regular speaker device and only turn on loudspeaker when we press the button.

4. **Please complete the following information** (mandatory)

 - Device: Cat S22 Flip
 - OS: Android 11
 - Version of the App 5.1.3
 - Version of the SDK 5.2.99
 - Where you did got it from F-Droid
 - Please tell us if your Android is a Lineage OS or another variant. Lineage OS 18

**Comment by Saphar** [comment]
In the Audio settings I have AAudio Speaker: Phh Treble vanilla, but it's the same on openSLES Speaker: Phh Treble vanilla.

Attached are the logs:
[65df5e550e844_2edbd25228ce745b68c0.gz](https://github.com/BelledonneCommunications/linphone-android/files/14438498/65df5e550e844_2edbd25228ce745b68c0.gz)

**Comment by Viish** [comment]
@Saphar do you see an earpiece device in the list? Is it the selected value?

**Comment by Viish** [comment]
I see in your screenshot that the default device is the speaker, that explains your issue. In the list, select the earpiece as default and you won't have the problem anymore.
