### ISSUE TITLE
dlopen failed: cannot locate symbol "__emutls_get_address" referenced by /base.apk!/lib/arm64-v8a/liblinphone.so"

### ISSUE THREAD

**Issue by basulle** [BelledonneCommunications/linphone-android#2115]
@Viish Hi again, hope you are good

Having some problems after ur suggestion to upgrade linphone sdk version.
Trying to upgrade it from 5.1.73 to 5.2.112  and getting issues while calling Factory.instance().createCore(absolutePath + "/linphonerc_default", absolutePath + "/linphonerc_factory", context);

Getting this issue: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/~~gcnuOVnXuPSr9DF_TmAGfw==/<app-name>-Dn5dg5F_H2_E9Uv34yokow==/base.apk!/lib/arm64-v8a/liblinphone.so"

Tried to clean the project, updated NDK to 26.2, nothing helps
Emulator on Tiramisu 13.0 arm64-v8a
maven repo: https://linphone.org/maven_repository/
debugImplementation "org.linphone.no-video:linphone-sdk-android-debug:5.2.112"
releaseImplementation "org.linphone.no-video:linphone-sdk-android:5.2.112"

Ty.

**Comment by Viish** [comment]
Hi @basulle,

This doesn't ring a bell.
Anyway you should update to 5.3 SDK instead of 5.2 as it is no longer supported.
Feel free to re-open if you still have the problem with latest release.

Cheers,

**Comment by basulle** [comment]
Installed 5.3.25 version by setting
    debugImplementation "org.linphone.no-video:linphone-sdk-android-debug:5.3.25"
    releaseImplementation "org.linphone.no-video:linphone-sdk-android:5.3.25"
    
Now facing issues with imports
<img width="478" alt="image" src="https://github.com/BelledonneCommunications/linphone-android/assets/65815876/3fb3b0ce-2dd7-4c41-a179-dfb22b9d0e58">

**Comment by longdevv** [comment]
@basulle Hello, I have the same problem, have you solved the problem？
