### ISSUE TITLE
Dynamic Display Name Change in Linphone SDK

### ISSUE THREAD

**Issue by Mahe2027** [BelledonneCommunications/linphone-android#2118]
Hii,

We are developing an alarm application that utilizes Linphone for making calls. One of the key features we're aiming to implement is the ability to dynamically change the display name of our SIP extension for each call. Our goal is to display the flat number of the alarm's origin at the remote device as the caller username.

To achieve this functionality, we've explored multiple APIs and methods within the Linphone SDK. However, despite our efforts, we haven't been successful in achieving the desired behavior. We've attempted to use [mention specific APIs or methods you've tried], but encountered challenges such as [describe the issues you faced, e.g., display name not updating, calls failing, etc.].

Given the critical nature of this feature for our alarm application, we would greatly appreciate any guidance or assistance you can provide in implementing dynamic display name changes effectively within Linphone SDK.

Thank you for your attention to this matter. We look forward to your response and assistance.

Thanks
Mahendra

**Comment by Viish** [comment]
HI Mahendra,

Simply set the display name on the SIP identity address of the local account you use to initiate/receive calls.
