### ISSUE TITLE
Custom ringtone issues with native silent mode

### ISSUE THREAD

**Issue by basulle** [BelledonneCommunications/linphone-android#2119]
Hi, @Viish 
I have updated linphone SDK to 5.3.25, but I still have issues with custom ringtone.

When I use native ringing enabled and put the phone on different modes (silent, default, only vibration) its behaves correctly
setRingDuringIncomingEarlyMedia(true);
core.setNativeRingingEnabled(true);

But, when i use my custom ringtone wav file, the phone rings on silent, not ringing on default and so on.
setRing(absolutePath + "/incoming-call.wav");
setRingDuringIncomingEarlyMedia(true);
setNativeRingingEnabled(false);

ty!

**Comment by Viish** [comment]
Hi @basulle,

You can use your own wav file and at the same time leaving native ringing enabled, it will fix your issue.

Cheers,
