### ISSUE TITLE
can't compile with SDK 5.3.35-pre.3+c72f95b

### ISSUE THREAD

**Issue by petervnv** [BelledonneCommunications/linphone-android#2120]
Hi,

I just tried compiling with SDK 5.3.35-pre.3+c72f95b and I now get the error:

'showForegroundServiceNotification' overrides nothing

Edit: I believe this [commit](https://github.com/BelledonneCommunications/liblinphone/commit/152a4debae26564a42b199529c37b38314e5e45d) broke compilation

**Comment by Viish** [comment]
Hi @petervnv,

Commit id dbd626f2 already fixes that issue (in release/5.2 branch).

Cheers,

**Comment by Viish** [comment]
Commit id is 3b121289 for master branch.
