### ISSUE TITLE
How do I obtain the status of the peer party when the peer party is offline during a call?

### ISSUE THREAD

**Issue by LoyaiHai** [BelledonneCommunications/linphone-android#2121]
Hi
@Viish 
Now when I am in a video call, when the other party does not have a network, I automatically hang up, and my current device only displays the remote video interface as stopped. Then how to know according to what interface, the other party has no network, we need to perform the function of hanging up operation?
Thank you

**Comment by Viish** [comment]
Hi @LoyaiHai,

There is no such possibility as if the device is offline it can't notify another device...
The only hint you may have is the call won't go to OutgoingRinging state, it will be stuck in OutgoingProgress.

Cheers,

**Comment by LoyaiHai** [comment]
@Viish
The situation I am talking about is as follows: Device A is in the middle of A conversation with device B, and device A's network is manually turned off. At this time, when my device B sees the screen of device A, it must be stopped, and what I want to know is whether device B can obtain the connection status of device A at this time? Because I figured if I knew that device A was offline, then I could just hang up on Device A
Cheers
