### ISSUE TITLE
The call ended early

### ISSUE THREAD

**Issue by Frasikn** [BelledonneCommunications/linphone-android#2122]
Hello！

1. **Describe the bug** （mandatory）

For outbound voice calls made or received, the call will always hang up automatically after about 30seconds; the minimum call duration is 28s, and the maximum duration is 45s.

2.**To Reproduce** （mandatory）

Make a call and then hang up without taking the initiative

3.**Expected behavior** （mandatory）

The call ends when one party clicks "hang up", or the call ends at a fixed time.

4.**Please complete the following information** (mandatory)

 - Device: Pixel 6 Pro
 - OS: Android API 29
 - Version of the App:5.1.4
 - Version of the SDK:5.2.110
 - Where you did got it from: F-Droid
 - Native Android system

**Comment by Viish** [comment]
Hi,

A call being ended after exactly 30 secs is often a symptom of a network issue (ACK not received, audio stream not received, etc...) but without logs I can't say for sure.
That being said, you are using a old SDK (latest is 5.3.34) and an old app (latest is 5.2.3), maybe updating will help you.
For information we do no support old releases.

Cheers,
