### ISSUE TITLE
Internet connection

### ISSUE THREAD

**Issue by CapsLk9** [BelledonneCommunications/linphone-android#2124]
Hi,
I noticed that the network connection of this application is not very stable. There is a logo prompting me whether it is connected to the network, but the status of this logo is not necessarily stable. Sometimes it shows "Connected", but I cannot send messages out or is to receive messages.
Thanks,

**Comment by Viish** [comment]
Hi @CapsLk9,

Please attach logs showing the issue, I can't help you with so little information.

Cheers,

**Comment by Viish** [comment]
Closed until logs are provided.
