### ISSUE TITLE
Program exception when calling back

### ISSUE THREAD

**Issue by Drizzta** [BelledonneCommunications/linphone-android#2125]
Hello guys,

After I mistakenly ended a call early, I wanted to call back immediately, but the call was not initiated, and "User hasn't been found" was prompted at the bottom of the interface. Since I just got off the phone with him, I don't think the procedure should be like this.

OS version
Google Pixel 6 Pro，API29

App version
5.1.0

thanks,

**Comment by Viish** [comment]
Hi @Drizzta,

It's likely the FROM header of the call you received was badly formatted.
Could you attach debug logs from the app so I can confirm?

Also note that 5.1.0 is a very old release, please update to 5.2.3.

Cheers,

**Comment by Viish** [comment]
Closed until logs are provided.
