### ISSUE TITLE
Unable to place outbound calls (Voip.ms)

### ISSUE THREAD

**Issue by vanostav61** [BelledonneCommunications/linphone-android#2131]
Unable to place outbound calls (Voip.ms)

Inbound calls work but outbound calls does not work.

Account shows registered...

**Comment by vanostav61** [comment]
[660423bfb966e_ec6303f050832978fb81.gz](https://github.com/BelledonneCommunications/linphone-android/files/14775848/660423bfb966e_ec6303f050832978fb81.gz)

**Comment by Viish** [comment]
Hi @vanostav61,

I don't know why but it's Voip.ms server that refuses the call:
```
2024-03-27 09:48:26:291 [org.linphone/belle-sip] MESSAGE channel [0x70bb0ea200]: received [428] new bytes from [UDP://atlanta2.voip.ms:5060]:
SIP/2.0 603 Declined
Via: SIP/2.0/UDP 192.168.30.169:5060;branch=z9hG4bK.0UxE9lGJX;received=68.189.149.69;rport=5060
From: "Voip.ms" <sip:264572@atlanta2.voip.ms>;tag=tgL71keAb
To: sip:9165954337@atlanta2.voip.ms;tag=as2820d97c
Call-ID: PWbLhTBN7a
CSeq: 21 INVITE
Server: voip.ms
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Content-Length: 0
```

You may want to contact them and ask them why this 603 Decline is being sent by their server, because it doesn't have any reason header so I can't say what is going wrong.

Cheers,

**Comment by vanostav61** [comment]
Thank you, I will try to get in touch with them tomorrow and see what they
say.

**Comment by vanostav61** [comment]
I forwarded the log that you gave me to Voip.ms and this is what they
replied:

"Unfortunately the log provided lacks some of the headers and extra info
that could provide insight to see what may be happening, so we'll need to
do some more troubleshooting. Are you using your Main or Sub Account for
use with Linphone?."

I told them I am using the main account.

**Comment by Viish** [comment]
Hi,

I'm a bit surprised by their answer, as the log you provided contains everything.
Also there is no "Main" or "Sub" account in Linphone, all accounts are the same.

I hope they'll be able to find a solution.
FYI, I know for a fact that some users of our application use Voip.ms service without any issue.

Cheers,

**Comment by Viish** [comment]
Hi @vanostav61,

Did you managed to make it work?

**Comment by vanostav61** [comment]
Hi Sylvain,
This is what they replied again:

"Apologies for the delay. The settings for the Main Account appear fine
overall
but unfortunately none of the attempts are registering on our CDR so it
appears
the app may not be sending them to our servers properly.


In this case I recommend joining us for a live chat session so we can
troubleshoot in real time by running a packet capture in order to see the
call
attempts and gather diagnostic information from that.


Regards,


Brendon Albury
VoIP.ms Customer Service Specialist  "

**Comment by Viish** [comment]
Hi @vanostav61,

Given their answer the problem probably lies somewhere in your network, between your device and their server.
You should follow up with them with the live chat session, they'll be more able to help you with that than myself.

Cheers,

**Comment by vanostav61** [comment]
I am having the same problem over my network and over LTE so I am sure this
is not the problem. In any case I am going to try and do a packet capture
for them just to satisfy their request.
Remain on the line :)

**Comment by Viish** [comment]
I'll be in vacations for almost two weeks starting tonight, but yes feel free to add new info here and I'll take a look when I'll be back.

**Comment by vanostav61** [comment]
Alright, have fun.

**Comment by vanostav61** [comment]
I have done a packet capture from my Android phone.
The app I used exported the log to a .bin file, which I have attached.
During the capture I tried to place outbound and inbound calls.
I have also switched between my WiFi network and 5G LTE

Let me know if you are able to read this file, I have also sent it to the
Voip.ms team.

**Comment by vanostav61** [comment]
Hey Sylvain, have you been able to look at the log capture? Any updates on
your side?

**Comment by Viish** [comment]
Hi @vanostav61,

No, but that's because you didn't attach the file.
Also it's not my area of expertise, it's really VoIP.ms that have to get a look at it.
As a remainder we do have users that can connect to VoIP.ms servers successfully.

Cheers,

**Comment by vanostav61** [comment]
This is interesting because the first time I contacted Voip.ms they told me
right away to download another app because Linphone is known to not work
properly with Voip.ms.


You guys keep pointing fingers at each other and I don't know what else to
do, I tried...

**Comment by Viish** [comment]
Also if Linphone is known to not work with their service, why do they have an article on how to configure it?
https://wiki.voip.ms/article/Linphone

Lastly, as they are selling you the service, the less they could do is take a look at your issue...

**Comment by Viish** [comment]
Hi @vanostav61,

Just resolved the same issue for another user, it was Bundle Mode toggle that needed to be toggled OFF (to have bundle mode enabled) in Account params to make it work.

Cheers,
