### ISSUE TITLE
AOS 5 versions missing from archives

### ISSUE THREAD

**Issue by bruceleerabbit** [BelledonneCommunications/linphone-android#2132]
Hi folks!

1. **Describe the bug** (mandatory)

I have Linphone version 4.3.1 which has this bug:

  https://github.com/BelledonneCommunications/linphone-android/issues/709

It was fixed 5 years ago. I am stuck running AOS 5.1 without Google access. All of the releases in f-droid are listed here:

http://fdroid.org/en/packages/org.linphone/index.html.en

They all require Android OS 6. Older versions seem to be missing from f-droid and the linphone.org website only seems to have the absolute latest APK file. When I click on “releases” in attempt to just determine which version I need, there is no information. If someone would please direct me to the archives of older versions and let me know which version was the last to support AOS 5.1 I would greatly appreciate it.

thanks!

**Comment by Viish** [comment]
Hi @bruceleerabbit,

4.3.X are the latest releases working on Android 5.
You can find every linphone-android release here, including 4.3.X (and even older ones): https://download.linphone.org/releases/android/

Cheers!
