### ISSUE TITLE
Louder Background Noise than the Voice and Echo at other End

### ISSUE THREAD

**Issue by shivbuyya** [BelledonneCommunications/linphone-android#2134]
Hello,

I am using the linphone-android app from the playstore in my Android device for voice call. My Android device is developed on custom hardware with Android 10. My device does not have in built echo canceller support.

The issue I am facing is that at the other end, user hear louder noise than my voice and also slight echo is noticed.

Kindly suggest how to resolve the noise issue, are there any parameters, which I can re-configure? or do I need to customise some part of the sdk code?

The same behaviour is noticed, when I compiled the source and run the application.

Please find the attached log.txt of app from the logcat.
[log.txt](https://github.com/BelledonneCommunications/linphone-android/files/14804251/log.txt)

Thank you in advance, kindly help to resolve the issue.

**Comment by Viish** [comment]
Hi,

As your device doesn't have a hardware echo canceller a software one is used, which is not as good.
However by default it is MSWebRTCAECM, but you could try using MSWebRTCAEC instead.

Regarding the sound, why do you use OpenSLES instead of AAudio?

Cheers,

**Comment by shivbuyya** [comment]
Thanks for the reply @Viish, as per your suggestion I have changed from  MSWebRTCAECM to MSWebRTCAEC. But still there is background noise(feeling of rain sound). 

1. I have tried to enable following flags, but still issue persists.
   stream->use_gc=TRUE;//FALSE;
   stream->use_agc=TRUE;//FALSE;
   stream->use_ng=TRUE;//FALSE; 

2. Also tried to change microphone gain from the App(0.0 to 0.1), I find slight reduction in the noise, but still noise persists.
3. Is there an option to change OpenSLES to AAudio in Linphone SDK source code? If yes how to change it please suggest.
4. Can you please suggest me, if any other option to fix noise. Any other modification do you suggest in the source code to fix the issue?

Please find attached logs: [logs.txt](https://github.com/BelledonneCommunications/linphone-android/files/14811964/logs.txt)

**Comment by Viish** [comment]
HI @shivbuyya,

AAudio is built by default unless you specify -DENABLE_AAUDIO=NO in cmake command line when building our SDK.
It should also be the default sound card used unless you force an OpenSLES one using core.set(Input/Output)AudioDevice().
It may be a firmware issue with your device, but I'd need the full logs from the start of the app to see why it doesn't load.

Could you attach a video of your device in call so we can hear the noise?

Cheers,

**Comment by Viish** [comment]
Closed until required info will be added.
