### ISSUE TITLE
Unable to not start CoreService while in background (Android 14+ crashes)

### ISSUE THREAD

**Issue by ParticleCore** [BelledonneCommunications/linphone-android#2135]
As of Android 14, apps are no longer allowed to start services from the background of certain types, including microphone and camera: https://developer.android.com/develop/background-work/services/foreground-services#wiu-restrictions

Even if the permission is granted, they no longer have the "always allow" permission, but "allow while in use", meaning the app must be in the foreground to have permission to launch a foreground service of those types.

If not, the following crash happens:

````
[Device Utils 34] Can't start service as foreground!java.lang.SecurityException:

Starting FGS with type microphone callerApp=ProcessRecord{db2e669 25583:com.app/u0a282} targetSDK=34

requires permissions: all of the permissions allOf=true
[android.permission.FOREGROUND_SERVICE_MICROPHONE]

any of the permissions allOf=false
[android.permission.CAPTURE_AUDIO_HOTWORD, 
android.permission.CAPTURE_AUDIO_OUTPUT, 
android.permission.CAPTURE_MEDIA_OUTPUT, 
android.permission.CAPTURE_TUNER_AUDIO_INPUT, 
android.permission.CAPTURE_VOICE_COMMUNICATION_OUTPUT, 
android.permission.RECORD_AUDIO] 

and the app must be in the eligible state/exemptions to access the foreground only permission
````

All permissions are granted, and the service works correctly, as long as the app is in the foreground. Attempting to launch the service while in the background violates that last line "the app must be in the eligible state/exemptions to access the foreground only permission" since it falls under this:

> In addition, if an app wants to launch a foreground service that needs while-in-use permissions (for example, body sensor, camera, microphone, or location permissions), it cannot create the service while the app is in the background, even if the app falls into one of the exemptions from background start restrictions.

However, `CoreManager` currently automatically launches the service, no matter what the state of the app is, meaning the app cannot operate correctly:

````java
 public void onFirstCallStarted(Core core) { 
     Log.i("[Core Manager] First call started"); 
     // Ensure Service is running. It will take care by itself to start as foreground. 
     try { 
         startService(); 
     } catch (IllegalStateException ise) { 
         Log.w("[Core Manager] Failed to start service: ", ise); 
     } 
 } 
````

https://github.com/BelledonneCommunications/liblinphone/blob/0e489e82858e0d4a42872f65dd932fc49458a9a7/wrappers/java/classes/org/linphone/core/tools/service/CoreManager.java#L279-L287

Ideally the following should be the norm for the above scenario:

1. If service cannot be started, only show the notification (with full screen intent, or just a call style notificaiton, that would be up to the developer)
2. Otherwise, go ahead with the service

Is there a way for us to dynamically control when the service can be started, or we have to completely scrap the `CoreService` implementation and use our own custom version? I checked the logic implemented in `CoreManager`, but seems like all it does is iterate through the services in the manifest and select whichever is the first match for a `CoreService` dependency.

**Comment by Viish** [comment]
Hi,

Our built-in service is merely there to provide a basis on which to build a proper solution.
You should create a class in your app that inherits the CoreService from our SDK and declare it in your Manifest, and in it override `createServiceNotification()`, `showForegroundServiceNotification(isVideoCall: Boolean)` and `hideForegroundServiceNotification()` to do the real job, as we do in our own app: https://gitlab.linphone.org/BC/public/linphone-android/-/blob/master/app/src/main/java/org/linphone/core/CoreService.kt#L81

Cheers,

**Comment by ParticleCore** [comment]
@Viish Thanks, but I already do that, the issue is not related to that. I am afraid you misunderstood the main problem reported here.

The problem is not controlling the notification attached to the foreground service, the problem is CoreManager starting the service when it shouldn't, and as far as I could find, there is no way to override CoreManager or its behavior.

**Comment by Viish** [comment]
So far I haven't met such situation, but anyway you can still disable it: simply do not declare our Service in your app's Manifest, and change your own Service implementation so it doesn't inherits ours.
This way you can control when your service is started.

**Comment by ParticleCore** [comment]
@Viish I see, so we can't leverage CoreManager any more in this case as I suspected.

If you want to replicate simply follow these steps:

Run a basic app with the sdk implemented on Android 14
Provide all permissions the app needs
Open the app and send it to the background
Ensure no foreground service is already running by default
Call that app
Phone rings and vibrates, but no notification is shown
The app logs in the logcat show the FGS error being thrown

I believe you've never encountered this yet because you're probably working with an always active foreground service notification that is always there regardless if the app is open or not. This issue is when there isn't a foreground service running all the time, only when a call comes in while the app is in the background.

**Comment by Viish** [comment]
> I believe you've never encountered this yet because you're probably working with an always active foreground service notification that is always there regardless if the app is open or not.

No, I don't have such permanent foreground service.
I simply create one when a call is being received using incoming call notification created by our app.
This works well whether the app is in background or killed and re-created by a push notification.

**Comment by ParticleCore** [comment]
@Viish I see why that is, this issue relies on either:

Not having push notification enable in the sip and not having an always active FGS when the app receives a call while it is in the background (not terminated nor killed)

Or has push notifications enabled, does not have an always active FGS when it is in the background (not terminated nor killed) when a call comes in while there is still a core connection to the sip server (meaning it does not yet depend on a push notification to wake up)

In either case I see that making use of CoreService will no longer be useful from Android 14+ so a custom solution is required to get it working properly.

Unfortunately I haven't been able to find where in the linphone app is the logic that ensures the app does not try to start the FGS while it is in the background, as far as I can see it also has the same issue as I described between the moment the app is sent to the background (no FGS active) and before the app is killed/terminated in order to rely on push notification.

**Comment by Viish** [comment]
In our app it's always one or the other: either you have a permanent foreground service or you have to receive a push notification to be waken up.
On all recent Android versions an app in background without a foreground service will be killed shortly after.

Anyway as of today it is not realistic to have a VoIP app that doesn't rely on push notifications.

**Comment by Viish** [comment]
Do you use TelecomManager APIs?
It may also solve your issue: https://developer.android.com/develop/connectivity/telecom/voip-app/telecom#foreground_support

**Comment by ParticleCore** [comment]
Unfortunately no, I did look at that some time ago, would have made things easier if I was using it, thanks for the heads up.

I will simply implement a dedicated logic to handle this scenario by showing a notification for any inbound calls and only starting the service when the user interacts with the notification (or on its own when using a full screen intent).

**Comment by struggle-to-settel** [comment]
Hello @ParticleCore ,

I am struggling with the same issue at my, if you have able to solve this problem can tell me how you were able to solve this issue.

At my end I am getting BackgroundServiceStartNotAllowedException:  because the core manager always tries to start background service.

**Comment by ParticleCore** [comment]
> Hello @ParticleCore ,
> 
> I am struggling with the same issue at my, if you have able to solve this problem can tell me how you were able to solve this issue.
> 
> At my end I am getting BackgroundServiceStartNotAllowedException: because the core manager always tries to start background service.

Simply do not use their service at all, create your own from scratch. That means not extending your service from theirs too, because the library looks up for a service that extends theirs in the manifest and uses it.
