### ISSUE TITLE
Why the app is using a foreground service to receive calls? Whatsapp never does it.

### ISSUE THREAD

**Issue by muhamzafarooqi** [BelledonneCommunications/linphone-android#2136]
If I want ping the app on a push notification, how will I manage the listener or connect with an incoming call?

**Comment by Viish** [comment]
Hi @muhamzafarooqi,

Indeed whats'app doesn't need it, and neither does Linphone as long as it is connected to a account for which push notifications are available.
By default only our own SIP service (sip.linphone.org) push notifications are configured inside the app, that's why for third party accounts we need to rely on a permanent foreground service notification so you can receive calls / messages at any time even without push (but that consumes more battery).
If you re-build linphone with your own push certificate, you'll be able to disable the foreground service.

Cheers,

**Comment by muhamzafarooqi** [comment]
@Viish Thanks for the clarification.
In response to **_If you re-build linphone with your own push certificate_**
I want to use Firebase Push notifications and I used your code (in my own app). When the app has been killed, I received a notification from firebase but I am not sure how can I connect the call as my core is not listening , should I first login to my sip on PUSH notification and start the core? But still the listener doesn't call so how can I get the remoteAddress?

**Comment by muhamzafarooqi** [comment]
@Viish How can i rebuild the app with my push certificate? What exactly do you mean by **_push certificate_**

**Comment by Viish** [comment]
Hi,

On Android the push certificate for apps is the google-serviceq.json file you can download from the Firebase console.

You also need to configure your server with the same id and the server key for it to work.

Cheers,

**Comment by Viish** [comment]
If the Core is correctly started when the push is received and the app woken up, it will register to the proxy.
All you have left to do is enable late forking on your proxy so it will send the invite to the newly registered device.

**Comment by muhamzafarooqi** [comment]
Thanks a bunch for your help so far.
I tried to enable late forking, but i don't see how can I do it. Maybe its already enabled but somehow, I am not able to receive call invite. "CallStateChange" listener is not getting executed. Do you think I am missing on something? @Viish

**Comment by muhamzafarooqi** [comment]
Just to let you know, I don't send any call data in my notification payload from the server. Notification is just for waking up the app.

**Comment by muhamzafarooqi** [comment]
This is what I did on "Linphone" app.

- login with my SIP credentials
- Called my number (Was able to receive the call on app)
- Now I killed and Forced stopped the app (Just to make sure nothing is running in the background, the service)
- Now I called on my number, and while the call was ringing, i launched the Linphone app just to make sure core has started. But I was not able to receive the call.

As the core was started already, and the call was ringing, I was not able to receive the call on linphone app

**Comment by muhamzafarooqi** [comment]
@Viish

**Comment by Viish** [comment]
@muhamzafarooqi if you are using Linphone app with your own SIP server it's expected the issue will be the same, as late call forking must be enabled in the server, not the client.

You can test on Linphone using two sip.linphone.org accounts (they are free), it will work as our proxy server does have late call forking.

If your proxy SIP server doesn't provide this late call forking feature you may want to consider switching to Flexisip (our open-source proxy server).

**Comment by muhamzafarooqi** [comment]
Thanks @Viish  for letting me know. Do you think if this method will help getCallByRemoteAddress2(remoteAddress) If somehow I am able to get the remote address of the caller?
I initialize the core and call this method simply to get and accept the call?

**Comment by Viish** [comment]
@muhamzafarooqi no, there is nothing to be done on the client side if the server doesn't send the INVITE.

**Comment by drodecker** [comment]
Hi Viish, I work with M Hamza and would like to add some color to this thread.
The SIP server is Twilio; are you familiar with any such forking setting available there?

**Comment by Viish** [comment]
Hi @drodecker,

No I'm not familiar with Twilio, as we have our own SIP server project we never have to install/configure or use any other proxy server except our own.

I suggest you open an issue on their bug tracker to have a solution on how to receive the call on a device that registered after the call was initiated.

Cheers,

**Comment by drodecker** [comment]
We're going to test implementing Flexisip to act as a proxy and connecting our client to that.
