### ISSUE TITLE
Numbers not replaced by names from address book

### ISSUE THREAD

**Issue by bearsh** [BelledonneCommunications/linphone-android#214]
please see https://github.com/BelledonneCommunications/linphone-iphone/issues/321 which describes the issue for iphone

**Comment by bearsh** [comment]
@Viish is this issue fixed? in which version?
just got the v4.0.1 update from the play store where the problem still exists.

**Comment by bearsh** [comment]
this *bug* is still relevant (v4.1), so can this please be reopened?

**Comment by Viish** [comment]
Do you phone numbers in your addressbook have a prefix like +X or +XX ?

**Comment by bearsh** [comment]
yes all my phone numbers in the address book have a country code in the form of +X/+XX but my sip providers doesn't prefix them if I receive domestic phone calls

**Comment by Viish** [comment]
In your account settings, have you set the prefix field to the prefix of your country ?

**Comment by bearsh** [comment]
I've just set it and checked it but it doesn't work. maybe because it's not a simple prefix as here in Switzerland all domestic numbers a prefixed with a 0. so the app should transform the following format `044 444 44 44` into `+41 44 444 44 44`

**Comment by Viish** [comment]
Try to restart the app to force the contact reload with the correct prefix info.
Don't worry about the 0 being replaced by the +41 prefix, it is handled.
If it still doesn't work after app restart, please send logs.

**Comment by bearsh** [comment]
how should I send the logs?

**Comment by Viish** [comment]
In Settings->Advanced, enable debug logs and reproduce issue if not done yet.
Then in About page use the send logs button. Finally download the logs using the link and copy/paste the relevant part of it here.

**Comment by bearsh** [comment]
I did that and skimmed through it but I couldn't figure out what parts are relevant :(
Can I also pm you the whole log?

**Comment by Viish** [comment]
Yes you can

**Comment by bearsh** [comment]
done

**Comment by bearsh** [comment]
@Viish could you find anything useful in my log?

**Comment by Viish** [comment]
@bearsh Where did you sent them ?

**Comment by bearsh** [comment]
to sylvain.berfini@linphone.org

**Comment by Viish** [comment]
I didn't received them. Send them to linphone-android@belledonne-communications.com please

**Comment by bearsh** [comment]
done, hope it works this time

**Comment by Viish** [comment]
Do you have a prefix set on your default proxy config ? Like 33 for France, etc...

**Comment by bearsh** [comment]
:see_no_evil: I always set the prefix to ``+41`` instead of only ``41`` grr, my mistake... not it works
sorry to bother you and thanks a lot for your help and responsiveness!!!

**Comment by Viish** [comment]
You're welcome :smiley:

**Comment by Viish** [comment]
I'll improve the prefix field to prevent this mistake from happening.
