### ISSUE TITLE
Does Linphone support Call Forward? 

### ISSUE THREAD

**Issue by shivbuyya** [BelledonneCommunications/linphone-android#2140]
Hi, 

I am trying to explore call forward feature in Linphone, but unfortunately I could not find it. 

Does Linphone support Call Forward? , if yes please suggest how to do it. 

Regards, 
ShivBuyya

**Comment by Viish** [comment]
Hi @shivbuyya,

You already opened this ticket and I moved it to the proper project.
Please do not open it again.
For questions you can also send a mail to our mailing list.

Cheers,

**Comment by shivbuyya** [comment]
Oh ok sorry, I thought question is deleted. 

I am planning to work on this feature in the app. If it works fine, will update here.
