### ISSUE TITLE
about Speaker

### ISSUE THREAD

**Issue by gaoruiqing187** [BelledonneCommunications/linphone-android#2141]
we userd audioManager.setSpeakerphoneOn(true) or audioManager.setSpeakerphoneOn(false) to setting speaker type, but it invalid，Can anyone help me？

**Comment by Viish** [comment]
See https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Audio%20devices/

**Comment by gaoruiqing187** [comment]
I read the wiki documentation, but I find that calling core.getAudioDevices returns 0; Calls to the core. GetExtendedAudioDevices returned only one element in the array, equipment type, type is unKnown. core.reloadSoundDevices(); I called the reload method before retrieving the device, but I still didn't get the device information
