### ISSUE TITLE
If the application is terminated/killed, incoming calls are not being received.

### ISSUE THREAD

**Issue by mobileteamt** [BelledonneCommunications/linphone-android#2143]
Hi,

**Description:**
 
When utilizing the Linphone SDK, we've encountered an issue where incoming calls are not received if the application is terminated or killed. This poses a significant usability concern as users may miss important calls.
 
**Steps to Reproduce:**

Start the application.
Receive an incoming call.
Terminate or kill the application.
Observe that the incoming call is not received.
 
**Expected Behavior:**

Incoming calls should still be received even if the application is terminated or killed, ensuring seamless communication for users.
 
**Actual Behavior:**

Incoming calls are not received when the application is terminated or killed, leading to missed communication opportunities.
 
**Additional Information:**

Platform: Android
Linphone SDK Version: 5.4+
Device : OnePlus Nord 2 (Android Version 13)
Priority: High

Thank you

**Comment by Viish** [comment]
Hi @mobileteamt,

This is expected as Android OS do not allow app or libraries to run full-time in background.
The only proper way to receive a call / message in a timely manner no matter the app state is using Firebase Push Notifications.
You can read how to set it up for our SDK here: https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Push%20notifications/

Cheers,
