### ISSUE TITLE
Bluetooth device connection not triggering onAudioDevicesListUpdated

### ISSUE THREAD

**Issue by basulle** [BelledonneCommunications/linphone-android#2144]
Hi, @Viish, hope you are good.
Using linphone-sdk-android:5.3.25 and facing a possible issue with listening to onAudioDevicesListUpdated.

I have read https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Audio%20devices/ and tried to capture bluetooth devices pairing and connection to change the output device, but its not triggering.

Calling core.getAudioDevices once onAudioDevicesListUpdated triggeres, but I am not seeing any bluetooth devices there.

onAudioDevicesListUpdated do trigger when i turning on and off the Bluetooth, but its not trigger when I pair or connect a bluetooth device.

I have also provided the BLUETOOTH_CONNECT permission.

Thank you!

**Comment by Viish** [comment]
Hi @basulle,

If you did grant the BLUETOOTH_CONNECT permission (declared it in the manifest and asked user for it at runtime) then please attach SDK verbose logs so I can see what happens with your device please.

Cheers,

**Comment by basulle** [comment]
Thank you @Viish , resolved.

**Comment by Viish** [comment]
Could you detail how you fixed it @basulle? It might interest other people landing here (in addition of satisfying my curiosity ;-)).

**Comment by basulle** [comment]
I have provided the permission, but didn't activate it -_-
Kind of a stupidness :D
