### ISSUE TITLE
how to debug native files

### ISSUE THREAD

**Issue by wall3001** [BelledonneCommunications/linphone-android#2145]
I build the local SDK use a remote VM. And then I want to debug the native files on android studio. I copy the source code to local path.
Then I set some breakpoints but show unreachable code.

**Comment by Viish** [comment]
Hi @wall3001,

Take a look at https://github.com/BelledonneCommunications/linphone-android?tab=readme-ov-file#native-debugging

Cheers,

**Comment by wall3001** [comment]
I did it according to that, but it didn't work.

**Comment by wall3001** [comment]
@Viish

**Comment by Viish** [comment]
Are you sure you are using your locally built SDK? (https://github.com/BelledonneCommunications/linphone-android?tab=readme-ov-file#building-a-local-sdk)
You can see in the build logs where the SDK is taken from (local or online maven repo).

**Comment by wall3001** [comment]
I build the SDK on ubuntu 20.0.04. And the run the android studio on windows 11. The android studio version is Iguana 2023.3.1.  I think I did something wrong, but I don't know how to correct it.

**Comment by wall3001** [comment]
The aar used is compiled from Ubuntu. I download it to the local pc. Does local compilation mean using the same device? I don't know how to use Android studio to directly compile linphone sdk.

**Comment by wall3001** [comment]
I'm sure that the SDK is taken from local  maven repo. I download the entire build output directory from the server. And then set the local "LinphoneSdkBuildDir" to the local path.

**Comment by wall3001** [comment]
@Viish

**Comment by Viish** [comment]
I'm not sure it will work that way.
You should install android studio on your Ubuntu computer and build both the SDK and app locally following README instructions.

**Comment by wall3001** [comment]
Now I can debug it on windows PC. LLDB Startup Commands  add the command   'settings set target.source-map /old/path /new/path '
