### ISSUE TITLE
Android foregroundService crash

### ISSUE THREAD

**Issue by basulle** [BelledonneCommunications/linphone-android#2149]
Hi, @Viish 
Emailed you several days ago with an issue, maybe you didn't notice. 

After migrating linphone-sdk from 5.1.73 to 5.3.25 I have a crash on Samsung devices (S21, S23 plus). Idk if that related to Samsungs or Android 14

The issue is after initializing the core and after some time (maybe ~30 seconds) the app crashes with this error:

ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground().

I was initializing my foreground service as you do, I assume.

Inherited my class from CoreService, overrides some methods:
onCreate, onStartCommand and createServiceNotification.

Thanks!

**Comment by Viish** [comment]
Hi,

First of all, you should use 5.3.32 at least as I have fixed an issue with foreground service types in it.
That being said, for Android 14 and higher, you'll have to set explicetily which type(s) your foreground service uses:
- In Manifest: https://gitlab.linphone.org/BC/public/linphone-android/-/blob/release/5.2/app/src/main/AndroidManifest.xml#L167
- When starting it as foreground: https://gitlab.linphone.org/BC/public/linphone-android/-/blob/release/5.2/app/src/main/java/org/linphone/compatibility/Api34Compatibility.kt#L54

See https://developer.android.com/about/versions/14/behavior-changes-14#fgs-types for more info.

Cheers,
