### ISSUE TITLE
Support for Configuring Duration of DTMF Tones in RFC 2833 with Linphone SDK

### ISSUE THREAD

**Issue by Mahe2027** [BelledonneCommunications/linphone-android#2150]
Hi,

I am currently developing features in an Android application using your SDK that require sending DTMF tones over the network during calls. While I can send DTMF tones using the sendDtmf() method, I find that I am unable to specify and control the duration of these tones, particularly to extend them to a specific length such as 500 ms.

Given that RFC 2833, which deals with the transmission of DTMF tones over IP networks, is supposed to support variable duration tones, I am wondering if there is a configuration option or method within the Linphone SDK that allows for this. My application needs to ensure that DTMF tones of specific lengths can be recognized accurately on the receiving end.

Could you please advise if there is a way to set the duration of DTMF tones sent using RFC 2833 standards in your SDK, or if there are any planned updates to support this functionality? Any alternative suggestions for achieving this within the current capabilities of the SDK would also be greatly appreciated.

Thnaks
Mahendra

**Comment by Viish** [comment]
Hi @Mahe2027,

Even if doc isn't really great regarding this method, you can use https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Core.html#playDtmf(char,int)

Cheers,

**Comment by Mahe2027** [comment]
Hi Viish

The doc is saying, its for playing in locally.
Does it follow RFC 2833 ?

If we play it locally then it will be going through same audio channel.

Thanks

**Comment by Viish** [comment]
That's what I said. The doc is wrong, it will send the DTMF in the call if there is one (in addition of playing it locally).

**Comment by Mahe2027** [comment]
Sorry for confusion, Can you clarify whether this is using RFC 2833 or not?

**Comment by Viish** [comment]
Yes, it uses RFC 2833 if you haven't disabled it in favor of SIP INFO.
