### ISSUE TITLE
Odd situation with DTMF type selection seems to be inverted

### ISSUE THREAD

**Issue by ParticleCore** [BelledonneCommunications/linphone-android#2153]
Hi, I've been debugging an issue with DTMF not being recognized in our internal system only to find out that the SDK might be inverting the logic internally.

Current scenario is our SIP system uses RFC 2833 for the DTMF, and I was able to confirm this today using MicroSip with the RFC 2833 method selected

![image](https://github.com/BelledonneCommunications/linphone-android/assets/9222661/fbb6ab89-4ee2-4765-af7f-b6d041c84106)

Testing it in our automated menu system confirmed the DTMF signals were being sent and received correctly, I was able to navigate the menu. If I switch to SIP Info then I am not able to navigate the menu, any signals sent are ignored.

However, when trying the exact same test using the Play Store and SDK, this did not work, any attempts were ignored and I was not able to navigate the menu.

Then I switched RFC 2833 off and turned SIP Info on and now I was able to send the signals correctly and navigate the menu

![image](https://github.com/BelledonneCommunications/linphone-android/assets/9222661/261dbecd-751c-41bc-a25d-480ea8dd51b0)

![image](https://github.com/BelledonneCommunications/linphone-android/assets/9222661/0cebe37f-ca57-4dc6-a2a6-3d04095ab82e)

This behavior was exactly the same between the SDK and the Play Store Linphone app 5.2.4

I tried inspecting the app code but I could not go past the setting being set in the UI, and any digging into the SDK ends at the native code which I cannot go past.

Is it possible that internally the SDK is sending the wrong tones? When SIP Info is enabled, it is actually sending RFC 2833 and vice versa? Because I cannot reach any other conclusion at this time.

**Comment by Viish** [comment]
Hi @ParticleCore,

Could you attach logs from a Linphone call sending DTMFs with SIP INFO enabled please?
I believe that your endpoint also accepts SIP INFO (that's why it works), but for some SIP offer/answer issue the RFC2833 doesn't get negociated properly.

Cheers,

**Comment by Viish** [comment]
Maybe your issue will be fixed by this: https://gitlab.linphone.org/BC/public/linphone-sdk/-/merge_requests/4262

**Comment by ParticleCore** [comment]
@Viish I've been waiting to see that included in a new release, but I couldn't see where it would mention that. Is there a version out already with that fix so I can test it out to see if this issue has been resolved as well?

**Comment by Viish** [comment]
Hi @ParticleCore,

Fix is part of 5.2.5 release currently published on Play Store.

Cheers,

**Comment by ParticleCore** [comment]
Hi @Viish thanks for the update, the linphone app now works when sending the tones while SIP INFO is off and RFC 2833 is enabled.

Is there any specific SDK version that has that fix included so I can test it on the local integration?

**Comment by Viish** [comment]
> the linphone app now works

Great!

> Is there any specific SDK version that has that fix included so I can test it on the local integration?

Fix was added in 5.3.45, latest SDK releaseis 5.3.47.

**Comment by ParticleCore** [comment]
@Viish thank you, just tested it on that version and it is working as well, much appreciated!
