### ISSUE TITLE
Are other URI protocols supported by Remote Provisioning?

### ISSUE THREAD

**Issue by aGrimRepoMan** [BelledonneCommunications/linphone-android#2154]
Hi,

Not an issue, just a question (apologies if questions should be posed elsewhere).

When I try to get Linphone Android's Assistant->RemoteProvisioning feature to process a locally stored (on-device) XML format config file , the GUI shows the error message: "Unknown URL format, can't download provisioning..."  Does the Remote Provisioning feature on Linphone Android support URI protocols like:

- _file://_
- _content://_

or only URLs?   I guess the answer is obvious from the error message, but asking just in case (noting that  Linphone Desktop supports _file://_ ).

If not, any plans to support _file_ or _content_ URI types in the future?

I tried variations such as _file:/_/, _file:///_, _content://_, _content:///_ without success. 

Android Device details:

- OS: Android 9
- App Version: 5.2.3
- SDK Version: 5.3.19
- App Origin: F-Droid

**Comment by Viish** [comment]
Hi @aGrimRepoMan,

Currently only web URLs are supported in mobile version because we rely on the `Patterns.WEB_URL.matcher` to validate user input.
If I have the time, I'll try to add `file://` it for the next release.

Cheers,

**Comment by nousername1** [comment]
Hi
Sorry for the stupid question how to do Remote Config for Android?
Does Android not Support Codec2? I would like use some Codeq who support by Astarisk for very poor Connections where the Sound Quality not Matter. I use PMR446 Digi Radio and I know how "bad" it can sound but on the other Hand with very very little Bandwith its possible to transmitt Sound. 
Thanks

**Comment by Viish** [comment]
Hi @nousername1,

You can find our documentation about remote config here: https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Remote%20Provisioning/

Yes, our SDK does support Codec2 audio codec, but it isn't build by default.
You'll have to build the SDK yourself adding `-DENABLE_CODEC2=ON` to cmake parameters list.

Note that Opus is the best audio codec we support and it is adaptive and thus works very well with low bandwidths.

Cheers,

**Comment by Viish** [comment]
file:// scheme is supported in 6.0.0 alpha now available in master branch.
