### ISSUE TITLE
Getting error during "cmake --build ." on linux system.

### ISSUE THREAD

**Issue by rksnachap333** [BelledonneCommunications/linphone-android#2155]
(1) Cloned code from = git clone https://gitlab.linphone.org/BC/public/linphone-sdk.git -- recursive

(2) Then updated this code from git.

(3) Then i run the command = cmake .. -DLINPHONESDK_PLATFORM:STRING=Android -DLINPHONESDK_ANDROID_ARCHS="arm64, armv7, x86_64, x86" -DENABLE_G729=YES -DENABLE_G729B_CNG=YES -DENABLE_VCARD=OFF -DENABLE_ILBC=OFF -DENABLE_SILK=OFF -DENABLE_ISAC=OFF -DENABLE_MKV=OFF -DENABLE_GSM=OFF -DENABLE_DOC=OFF -DENABLE_UNIT_TESTS=OFF -DENABLE_LIME=OFF -DENABLE_GPL_THIRD_PARTIES=YES -DENABLE_NON_FREE_CODECS=OFF -DENABLE_SOUND=NO
 
this command runs successfully .

(4) But this "cmake --build ." is throing error ,

error : 

../../../external/dav1d/meson.build:25:0: ERROR: Unknown compiler(s): [['x86_64-linux-android21-clang']]
The following exception(s) were encountered:
Running `x86_64-linux-android21-clang --version` gave "[Errno 2] No such file or directory: 'x86_64-linux-android21-clang'"

what could be the reason and possible solution.

**Comment by Viish** [comment]
Hi @rksnachap333,

Take a look at our README file: https://gitlab.linphone.org/BC/public/linphone-sdk#android-using-docker

You have to set the android preset to be able to build the master branch of our SDK.

Cheers,

**Comment by rksnachap333** [comment]
`cmake --preset=android-sdk -B build-android -DLINPHONESDK_ANDROID_ARCHS=arm64` this command throwing error File not found: /home/User/recursive/build/CMakePresets.json. (Building on Linux System)

**Comment by rksnachap333** [comment]
> `cmake --preset=android-sdk -B build-android -DLINPHONESDK_ANDROID_ARCHS=arm64` this command throwing error File not found: /home/User/recursive/build/CMakePresets.json. (Building on Linux System)

**Comment by Viish** [comment]
@rksnachap333 Check you are on master or release/5.3 branch and do a `git pull && git submodule update --recursive --init`

**Comment by Viish** [comment]
@rksnachap333 Simply clone again from scratch (seems better considering you aren't successful right now), and follow the steps in https://gitlab.linphone.org/BC/public/linphone-sdk#android-using-docker:

```
cmake --preset=android-sdk -B build-android -DLINPHONESDK_ANDROID_ARCHS=arm64 -DENABLE_G729=ON -DENABLE_GPL_THIRD_PARTIES=ON
cmake --build build-android --parallel 8
```

**Comment by rksnachap333** [comment]
After following all the steps in doc  i am getting this error : 

sudo docker run -it --volume=$PWD:/home/bc/linphone-sdk gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-android-r25b:20230706_add_deps_for_av1 /bin/bash -i
bc@3c96fe973056:~$ cmake --preset=android-sdk -B build-android -DLINPHONESDK_ANDROID_ARCHS=arm64 -DENABLE_G729=ON -DENABLE_GPL_THIRD_PARTIES=ON
CMake Error: Could not read presets from /home/bc: File not found
bc@3c96fe973056:~$

**Comment by rksnachap333** [comment]
> After following all the steps in doc i am getting this error :
> 
> sudo docker run -it --volume=$PWD:/home/bc/linphone-sdk gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-android-r25b:20230706_add_deps_for_av1 /bin/bash -i bc@3c96fe973056:~$ cmake --preset=android-sdk -B build-android -DLINPHONESDK_ANDROID_ARCHS=arm64 -DENABLE_G729=ON -DENABLE_GPL_THIRD_PARTIES=ON CMake Error: Could not read presets from /home/bc: File not found bc@3c96fe973056:~$

**Comment by Viish** [comment]
You have to be in the linphone-sdk root folder.

**Comment by rksnachap333** [comment]
> cmake --build build-android --parallel 8

Thank you so much..Finally I am able to build SDK.
