### ISSUE TITLE
[split_config.arm64_v8a.apk!liblinphone.so] LinphonePrivate::AndroidPlatformHelpers::AndroidPlatformHelpers(std::__ndk1::shared_ptr<LinphonePrivate::Core>, void*)

### ISSUE THREAD

**Issue by WilliamsV12** [BelledonneCommunications/linphone-android#2158]
Hi Team, recently we are facing more crash in play console in Android 14 version. We have tried with same device it was not reproducible. We have used linphone SDK version - 4.5.18.

Log:
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 13645 >>> com.celaccess <<<

backtrace:
  #00  pc 0x00000000000940a4  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164)
  #01  pc 0x000000000076fde0  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+904)
  #02  pc 0x00000000000357d0  /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_0::__invoke(char const*)+80)
  #03  pc 0x0000000000034d58  /apex/com.android.art/lib64/libbase.so (android::base::LogMessage::~LogMessage()+352)
  #04  pc 0x000000000025aa50  /apex/com.android.art/lib64/libart.so (art::ClassLinker::FindClass(art::Thread*, char const*, art::Handle<art::mirror::ClassLoader>)+8988)
  #05  pc 0x0000000000552edc  /apex/com.android.art/lib64/libart.so (art::JNI<false>::FindClass(_JNIEnv*, char const*)+696)
  #06  pc 0x0000000000716678  /data/app/~~tM2_wgqDZHhYvIqqWNFMPg==/com.celaccess-eiBPpgBvYfQ9Q7VcOFKoOA==/split_config.arm64_v8a.apk!liblinphone.so (LinphonePrivate::AndroidPlatformHelpers::AndroidPlatformHelpers(std::__ndk1::shared_ptr<LinphonePrivate::Core>, void*)+340) (BuildId: a6b116510fb0f50e6bfb9c19bb84e7b272157d63)
  #07  pc 0x0000000000718718  /data/app/~~tM2_wgqDZHhYvIqqWNFMPg==/com.celaccess-eiBPpgBvYfQ9Q7VcOFKoOA==/split_config.arm64_v8a.apk!liblinphone.so (LinphonePrivate::createAndroidPlatformHelpers(std::__ndk1::shared_ptr<LinphonePrivate::Core>, void*)+96) (BuildId: a6b116510fb0f50e6bfb9c19bb84e7b272157d63)
  #08  pc 0x00000000007472c8  /data/app/~~tM2_wgqDZHhYvIqqWNFMPg==/com.celaccess-eiBPpgBvYfQ9Q7VcOFKoOA==/split_config.arm64_v8a.apk!liblinphone.so (BuildId: a6b116510fb0f50e6bfb9c19bb84e7b272157d63)
  #09  pc 0x0000000000747dc0  /data/app/~~tM2_wgqDZHhYvIqqWNFMPg==/com.celaccess-eiBPpgBvYfQ9Q7VcOFKoOA==/split_config.arm64_v8a.apk!liblinphone.so (_linphone_core_new_with_config(_LinphoneCoreCbs*, _LpConfig*, void*, void*, unsigned char, unsigned char)+168) (BuildId: a6b116510fb0f50e6bfb9c19bb84e7b272157d63)
  #10  pc 0x0000000000657714  /data/app/~~tM2_wgqDZHhYvIqqWNFMPg==/com.celaccess-eiBPpgBvYfQ9Q7VcOFKoOA==/split_config.arm64_v8a.apk!liblinphone.so (LinphonePrivate::Factory::_createCore(_LinphoneCoreCbs*, char const*, char const*, void*, void*, unsigned char) const+88) (BuildId: a6b116510fb0f50e6bfb9c19bb84e7b272157d63)
  #11  pc 0x00000000007b99e4  /data/app/~~tM2_wgqDZHhYvIqqWNFMPg==/com.celaccess-eiBPpgBvYfQ9Q7VcOFKoOA==/split_config.arm64_v8a.apk!liblinphone.so (Java_org_linphone_core_FactoryImpl_createCore3+164) (BuildId: a6b116510fb0f50e6bfb9c19bb84e7b272157d63)
  #12  pc 0x000000000012c820  /data/app/~~tM2_wgqDZHhYvIqqWNFMPg==/com.celaccess-eiBPpgBvYfQ9Q7VcOFKoOA==/oat/arm64/base.odex (art_jni_trampoline+160)
  #13  pc 0x000000000056b00c  /data/app/~~tM2_wgqDZHhYvIqqWNFMPg==/com.celaccess-eiBPpgBvYfQ9Q7VcOFKoOA==/oat/arm64/base.odex (org.linphone.core.FactoryImpl.createCore+108)
  #14  pc 0x00000000005b9930  /apex/com.android.art/lib64/libart.so (nterp_helper+4016)
  #15  pc 0x000000000053f5a2  /data/app/~~tM2_wgqDZHhYvIqqWNFMPg==/com.celaccess-eiBPpgBvYfQ9Q7VcOFKoOA==/base.apk (w3.j.C+42)
  #16  pc 0x00000000002b04d4  /data/app/~~tM2_wgqDZHhYvIqqWNFMPg==/com.celaccess-eiBPpgBvYfQ9Q7VcOFKoOA==/oat/arm64/base.odex (w3.h.t+596)
  #17  pc 0x00000000005b9930  /apex/com.android.art/lib64/libart.so (nterp_helper+4016)
  #18  pc 0x00000000002bea24  /data/app/~~tM2_wgqDZHhYvIqqWNFMPg==/com.celaccess-eiBPpgBvYfQ9Q7VcOFKoOA==/base.apk (cellgate.com.cellgate.sip.LinphoneService.onStartCommand+176)
  #19  pc 0x000000000086356c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ActivityThread.handleServiceArgs+908)
  #20  pc 0x0000000000851e80  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ActivityThread.-$$Nest$mhandleServiceArgs+48)
  #21  pc 0x000000000085084c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ActivityThread$H.handleMessage+7228)
  #22  pc 0x0000000000b1b118  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Handler.dispatchMessage+168)
  #23  pc 0x0000000000b1f29c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Looper.loopOnce+1036)
  #24  pc 0x0000000000b1ede8  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Looper.loop+1112)
  #25  pc 0x0000000000868f2c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ActivityThread.main+2332)
  #26  pc 0x000000000033b680  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+640)
  #27  pc 0x000000000037cb18  /apex/com.android.art/lib64/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1556)
  #28  pc 0x000000000037c4f4  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*) (.__uniq.165753521025965369065708152063621506277)+32)
  #29  pc 0x00000000003955f8  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (art_jni_trampoline+120)
  #30  pc 0x0000000000eb4644  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+132)
  #31  pc 0x0000000000ec0ca4  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (com.android.internal.os.ZygoteInit.main+3604)
  #32  pc 0x000000000033b680  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+640)
  #33  pc 0x00000000004e2a90  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+728)
  #34  pc 0x000000000057ab18  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+156)
  #35  pc 0x00000000000deca8  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+104)
  #36  pc 0x00000000000eb5dc  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+860)
  #37  pc 0x000000000000256c  /system/bin/app_process64 (main+1292)
  #38  pc 0x000000000008c5b8  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+104)

**Comment by Viish** [comment]
Hi,

We don't do support on old releases, and yours is very very old (latest is 5.3).
Please update your SDK and re-open an issue with SDK debug logs if you reproduce it.
Your company (that doesn't seem to respect the GPLv3 by the way...) can also contact ours to purchase a proper support contract.

Cheers,
