### ISSUE TITLE
Linphone conference issue when default account is linphone server

### ISSUE THREAD

**Issue by Mahe2027** [BelledonneCommunications/linphone-android#2160]
Hi,

I'm developing an android app using Linphone SDK.

I'm getting an issue with creating a conference call when default account is linphone server account (domain-  sip.linphone.org) .

Getting this Log - RemoteConference::inviteAddresses() not implemented,

When creating conference using method - conf.inviteParticipants(arrayOf(address), callParams).

Single calls are working fine and conference is working fine when default account is not linphone account.

Thanks 
Mahee

**Comment by Viish** [comment]
Hi @Mahe2027,

When using a linphone account, conferences will be hosted on our (remote) conference server.
When you create a conference with an account that doesn't have an audioVideoConferenceFactoryUri set, conferences will be hosted by your device directly.

Our SDK doesn't indeed implement the `inviteAddresses()` method for remote conferences. Instead you should use `addParticipants()` (https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Conference.html#addParticipants(org.linphone.core.Address%5B%5D))

Cheers,
