### ISSUE TITLE
Questions regarding setting SIP port in Android app

### ISSUE THREAD

**Issue by ParticleCore** [BelledonneCommunications/linphone-android#2161]
Hi there,

While trying to understand how to use ports in SIP using the library I came about this logic here that got me confused:

https://github.com/BelledonneCommunications/linphone-android/blob/dad4af5c3432f4bb221bd55423cef3d2a75e962b/app/src/main/java/org/linphone/activities/main/settings/viewmodels/NetworkSettingsViewModel.kt#L68-L74

From my understanding, the Linphone Android app allows the listening port to either be random (-1) or any other value (default 5060). However, when setting the port for all 3 transport modes, the TLS is always being set to random (-1).

Questions regarding the above: is that intentional? and if so, why is it intentional?

As for the other question: I can set a port for the SIP address to connect using the Linphone SDK, but in the Linphone Android app I cannot seem to figure out where in the settings that can accomplished. Is there a reason for this, or am I not understanding how this should be done correctly?

Example:

````kotlin
val address = factory.createAddress(sipAddress)
address.port = 4000
````

It is my understanding that the transport ports are meant for listening purposes, but the address port is meant for registration purposes, so I am trying to correctly cover both aspects when it comes to port configuration so nothing is left behind in a configuration screen setup.

**Comment by Viish** [comment]
Hi @ParticleCore,

Indeed setTransportPort() method is for configuring the local port on which Linphone listens for incoming traffic (for peer to peer communications). TLS port is forced to -1 because it doesn't make sense to have a local TLS socket listening for traffic without a domain name and a certificate.

And of course port on address is indeed used for outgoing network connections.

Cheers,

**Comment by ParticleCore** [comment]
Thank you, much appreciated for the explanation!
