### ISSUE TITLE
Placing second call app freeze then crash.

### ISSUE THREAD

**Issue by basulle** [BelledonneCommunications/linphone-android#2162]
Hello @Viish, hope you are good. 

Facing an issue while using linphone-sdk 5.3.48.
When I am in a call and then placing a new call above of that, app freezes then crashes.
When I was using 5.3.25 it was working great. 

Seems like linphone was automatically placing the current call to pause and then placing the new one.
When I am manually place current call on pause and then place a new call - no issues (talking about 5.3.48).

Thank you!

**Comment by Viish** [comment]
Hi @basulle,

Thanks for the report, we'll look into it.
Could you attach logs & crash stack trace for the issue please?

Cheers,

**Comment by basulle** [comment]
@Viish unfortunately I can't provide logs for the moment.
Can you try to reproduce the issue and if it won't be reproducible for you then I will think how I can share the private logs?

**Comment by Viish** [comment]
Hi @basulle, no I don't have the resources to reproduce right now as we are working hard on the 6.0 release.

**Comment by Viish** [comment]
Closing due to lack of feedback, will re-open when logs will be added.
