### ISSUE TITLE
Incoming calls

### ISSUE THREAD

**Issue by basulle** [BelledonneCommunications/linphone-android#2165]
Hello, @Viish

I have some difficulties handling some stuff for Incoming calls:

1. If the initiator placing a call and almost immediately cancel it, the phone is receiving the call and rings until you decline it manually.
2. If the call answered on another device, it's still ringing on the rest devices.

Its reproducible more frequent on iOS, but maybe you can help me here.

Thank you!

**Comment by Viish** [comment]
Hi @basulle,

> If the initiator placing a call and almost immediately cancel it, the phone is receiving the call and rings until you decline it manually.

As always, please provide logs showing the issue.

> If the call answered on another device, it's still ringing on the rest devices.

That's a proxy server issue (probably a misconfiguration), not a client one.

Cheers,

**Comment by Viish** [comment]
Closing due to lack of feedback, will re-open when logs will be added.
