### ISSUE TITLE
change Speaker and Blue tooth

### ISSUE THREAD

**Issue by gaoruiqing187** [BelledonneCommunications/linphone-android#2167]
hi,I link the bluetooth headset, but at the core. The getExtendedAudioDevices and core getAudioDevices in equipment. If you want to switch speakers and there is no Speaker device, how do I get the audio device? The first device name I printed was just Android Sound card

**Comment by Viish** [comment]
Hi @gaoruiqing187,

To get list of available bluetooth devices for playback, use the following:
```
for (device in coreContext.core.audioDevices) {
    if (device.hasCapability(AudioDevice.Capabilities.CapabilityPlay)) {
        if (device.type == AudioDevice.Type.Bluetooth) {
            return device
        }
    }
}
```
For speakers, simply replace `AudioDevice.Type.Bluetooth` by `AudioDevice.Type.Speaker`.
If it returns nothing, it means our SDK didn't detected a sound card matching your expectations.

Cheers,
