### ISSUE TITLE
 I have a question about Offline

### ISSUE THREAD

**Issue by gaoruiqing187** [BelledonneCommunications/linphone-android#2168]
Is there a callback notification when the extension is disconnected? I want to reconnect the extension when it drops

**Comment by Viish** [comment]
https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/AccountListener.html#onRegistrationStateChanged(org.linphone.core.Account,org.linphone.core.RegistrationState,java.lang.String)
