### ISSUE TITLE
setDisplayName does not appear to work

### ISSUE THREAD

**Issue by ParticleCore** [BelledonneCommunications/linphone-android#2169]
Hi there, I have been trying to understand how to set a display name when registering a new account, but it appears that any attempt does not work, meaning when making a call to someone they do not see the display name I set, it only shows the username.

This is in regards to the Android SDK, and I tried to find in the tutorials how to do it, but there isn't anything there explaining how to do it.

I've set it as such:

````kotlin
core.defaultAccount?.contactAddress?.setDisplayName(displayName)
````

I also set it when creating the address, and I also tried to set it through the proxyConfig as per https://github.com/BelledonneCommunications/linphone-android/issues/497#issuecomment-469162076 , but all options are marked as deprecated:
![image](https://github.com/BelledonneCommunications/linphone-android/assets/9222661/cf727a12-333a-42f1-b55e-a459706df032)

Is there a way to set up the display name when registering the account in order to be displayed to the user when calling them? If so, how can we accomplish this?

I'm using SDK 5.3.47

**Comment by Viish** [comment]
Hi,

You were almost there. Display name must be set on identity address, not contact address.

All methods related to ProxyConfig object are deprecated as this object was replaced by AccountParams and Account objects, much easier to understand and use.

Cheers,
