### ISSUE TITLE
Call is terminated If no RTP packet is received within 30 seconds

### ISSUE THREAD

**Issue by allanwxm** [BelledonneCommunications/linphone-android#2172]
Hi, the IPPBX I am using provides a one-way broadcast function, where the callee can hear the caller's voice, but the caller cannot hear the callee's voice. That is, after the broadcast starts, IPPBX will not send RTP packets to the caller.
When using the latest version of the Linphone Android client as the caller, IPPBX does not send RTP packets to Linphone after the broadcast starts, and the call is hung up after 30 seconds. 
The Linphone log shows 'Session is going to be terminated because the media has been lost'. How can I solve this problem? Is there a way to configure Linphone to not hang up the call after receiving no RTP packets in 30 seconds? Thanks.

**Comment by Viish** [comment]
Hi @allanwxm,

> Is there a way to configure Linphone to not hang up the call after receiving no RTP packets in 30 seconds? 

Yes, there is.  First solution would be to have your IPPBX send RTCP packets even in broadcast mode.

Second solution is to change the NoRTP timeout in our SDK. 
For that either set it in your factory RC file like this:
```
[rtp]
nortp_timeout=0
```
or call https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Core.html#setNortpTimeout(int)
Expected value is in seconds (default is 30), and if you set 0 the feature is disabled.

Cheers,
