### ISSUE TITLE
Inquiry on Adding Codec Attributes to SIP INVITE in Linphone Android SDK

### ISSUE THREAD

**Issue by Mahe2027** [BelledonneCommunications/linphone-android#2173]
Hi,

I am currently working on an Android application using the Linphone SDK and I have a specific requirement to modify the SDP attributes directly, particularly for adding codec attributes such as rtpmap for PCMU G.711U in the SIP INVITE messages.

I understand that the LinphoneCore interface allows for enabling and configuring codecs, but I have not found a direct way in the SDK to manipulate the SDP attributes for codecs in the INVITE messages. Could you please advise if there is an existing API method that supports this functionality?

Additionally, if this feature is not available, could you provide guidance or recommend best practices for achieving this functionality, possibly through lower-level manipulations or any planned updates that might include this feature?

Thanks.
Mahee

**Comment by Viish** [comment]
Hi  @Mahe2027,

PayloadType object should already have everything necessary, such as https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/PayloadType.html#setRecvFmtp(java.lang.String)

Cheers,
