### ISSUE TITLE
How to turn on the sound when dialing a number?

### ISSUE THREAD

**Issue by ally9335** [BelledonneCommunications/linphone-android#2175]
I've searched for in the settings - nothing. How to turn on the sound when dialing a number?

**Comment by Viish** [comment]
Hi @ally9335,

We removed that option in a previous release, and with 6.0 to come the dialer as you know it will also disappear.

Cheers,

**Comment by ally9335** [comment]
@Viish why?

**Comment by Viish** [comment]
Dialer is only useful when calling numbers that aren't in your address book.
Most of our users use cases involve the address book or SIP URIs (like an email address) more than a phone number.
Also any smartphone keyboard can input numbers in a text field, no need for a dedicated interface for that.
Don't worry you'll still have a dialpad on the start call screen of the next UI, but it won't be the default page anymore.

**Comment by ally9335** [comment]
Well, almost no number that I call is in my address book.

> Don't worry you'll still have a dialpad on the start call screen of the next UI, but it won't be the default page anymore.

The question isn't about the presence of it, but the sound of  **entering** a number.

But will a checkbox  somewhere in the settings "turn on a sound" hurt? Why delete it?

**Comment by Viish** [comment]
Hi @ally9335, Could you explain why you need it?

FYI, back when we did played a tone on dialpad, we relied on the following Android OS property: [Settings.System.DTMF_TONE_WHEN_DIALING](https://developer.android.com/reference/android/provider/Settings.System#DTMF_TONE_WHEN_DIALING)
If I were to add it back, I would do it again like that.

**Comment by ally9335** [comment]
Sometimes when I press a button-digit, it accessidentally may not fire. I have to pay a close attention to whether a digit has really been entered, therefore.
Besides, it sounds right, as a phone.
@Viish 


Apart from this, the dialed digits, the input area, are too small, in my opinion.

**Comment by Viish** [comment]
Ok, I've added it back for the 6.0 release (as long as they are enabled at OS level they will be too in Linphone)

> Apart from this, the dialed digits, the input area, are too small, in my opinion.

There is already an issue for this: https://github.com/BelledonneCommunications/linphone-android/issues/2025

**Comment by ally9335** [comment]
Thanks
