### ISSUE TITLE
Configure SMS in Linphone-Android

### ISSUE THREAD

**Issue by stef204** [BelledonneCommunications/linphone-android#2176]
Running 5.25 with SDK 5.3.47 on Android 14

I have one sms-enabled DID from a SIP provider. 

How do I set up Linphone-Android to send and receive SMS messages on that number?

Cannot find instructions on how to do that.

Note: my SIP provider mentions "Send a webhook to this URL:" (insert webhook in field)

**Comment by SB2318** [comment]
I want to give it a try, maybe Linphone-Android currently doesn't have built-in functionality for sending and receiving SMS messages. While it can handle voice calls and SIP messaging, SMS support is not included. I want to prepare an analysis first.

Again, Thanks for the opportunity!

**Comment by Viish** [comment]
Hi,

It depends on the technology used by your provider for message exchange (it's not really SMS).
If it's based upon SIP SIMPLE (SIP messages) then we do support it.

Cheers,

**Comment by stef204** [comment]
So the reason my SIP provider mentions a webhook is that they use/support `https` and not `SIMPLE`.  I just checked with them.  Leaves receiving messages via `Linphone-android` out, I suppose.
