### ISSUE TITLE
Conflicts with whether linphone will run exosip?

### ISSUE THREAD

**Issue by LoyaiHai** [BelledonneCommunications/linphone-android#2177]
Hi
@Viish 
When I run the demo that contains only Exosip, the whole registration process is clear through the Wireshark tool: first 401, then add authentication information.
When I integrated both linphone and Exosip into the project, I noticed that the registration of Exosip was abnormal: 401, and then sending 3 registration requests, the first of which read: 1 binging; Second display: remove 1 binging;
here is the picture:
<img width="893" alt="抓包" src="https://github.com/BelledonneCommunications/linphone-android/assets/32878163/18b909e7-656b-4a1a-b847-2cdc360e4e77">

**Comment by Viish** [comment]
Hi @LoyaiHai,

What are you doing? Linphone no longer uses ExoSIP library for many years.
If you are doing some changes on your side, I can't help with that, and linphone-android repository is definitively not the right place for that.

Cheers,

**Comment by LoyaiHai** [comment]
@Viish 
I mean, my current project, I need to use the Exosip library and linphone modules. Since it's all about the sip protocol, the question I want to ask is: Is there a possibility of conflict when the two exist in the same project

**Comment by Viish** [comment]
> Is there a possibility of conflict when the two exist in the same project

Not that I know of, but we never tested it some it's possible.
Question is: why do you need ExoSIP library when you already have a SIP library in Linphone?
