### ISSUE TITLE
Questions about the IM receiving interface

### ISSUE THREAD

**Issue by LoyaiHai** [BelledonneCommunications/linphone-android#2179]
Hi
@Viish 
I'm in the CoreListener callback:
public void onMessagesReceived(@NonNull Core core, @NonNull ChatRoom chatRoom, @NonNull ChatMessage[] messages) 
and 
public void onMessageReceived(@NonNull Core core, @NonNull ChatRoom chatRoom, @NonNull ChatMessage message) 
These two interfaces, when another terminal sends an IM to me, 
public void onMessagesReceived(@NonNull Core core, @NonNull ChatRoom chatRoom, @NonNull ChatMessage[] messages) 
from this interface, I now do not understand the place: Why is it that a single instant message, Is not received in 
public void onMessageReceived(@NonNull Core core, @NonNull ChatRoom chatRoom, @NonNull ChatMessage message), 
public void onMessagesReceived(@NonNull Core core, @NonNull ChatRoom chatRoom, @NonNull ChatMessage[] messages) 
Received on this interface?
The other issue involved is how the two are sent, Can I receive a message in the 
public void onMessageReceived(@NonNull Core core, @NonNull ChatRoom chatRoom, @NonNull ChatMessage message) 
interface? Instead of going to 
public void onMessagesReceived(@NonNull Core core, @NonNull ChatRoom chatRoom, @NonNull ChatMessage[] messages)

Thank you 
cheers

**Comment by Viish** [comment]
Hi @LoyaiHai,

If you took time to read the documentation (https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/CoreListenerStub.html#onMessagesReceived(org.linphone.core.Core,org.linphone.core.ChatRoom,org.linphone.core.ChatMessage%5B%5D)), you'd see onMessagesReceived() is only called if aggegration feature is enabled in the Core, otherwise it's onMessageReceived() that is being called. It's one or the other, never the two of them.

Cheers,

**Comment by LoyaiHai** [comment]
@Viish 
i got it, but I want to know is that if I don't call the Core. The setChatMessagesAggregationEnabled (), the default is enabled or shut down?

**Comment by Viish** [comment]
By default aggregation isn't enabled, and if you do not enable it you will receive all messages on by one in onMessageReceived() callback.

**Comment by LoyaiHai** [comment]
@Viish 
Now the problem I encountered is the opposite of what you said, as can be seen from the figure, I did not set the global search, but received messages from:
public void onMessageReceived(@NonNull Core core, @NonNull ChatRoom chatRoom, @NonNull ChatMessage message)
Get the message, please ask if this is related to the version of SDK
