### ISSUE TITLE
Friend List cannot work after done publish, subscribe. 

### ISSUE THREAD

**Issue by ravi-nimavat128** [BelledonneCommunications/linphone-android#218]
Hello friends,

I am using linphone code, I am able to publish and subscribe to the server but can't work friendlist with my server.
let me know if anyone can help me.

thanks...

**Comment by wangpeng1** [comment]
@ravi-nimavat128 can you solve your problem

**Comment by ravi-nimavat128** [comment]
@wangpeng1  not now, I am facing same issues,
please let me know if you can help me.
-Thanks.
