### ISSUE TITLE
Linphone Android Issue Report - Sound Progress Indicator and Playback Speed Control

### ISSUE THREAD

**Issue by SB2318** [BelledonneCommunications/linphone-android#2180]
Hello Linphone developers Team,

Hope you are doing great.

1. **Describe the bug** (mandatory)

I am writing to report an issue with the sound progress indicator in the chat section of the Linphone-android app. While the current behavior might be functional, I believe it could be improved to provide a more intuitive user experience.

2. **Current Behavior:**

I've observed that the sound progress indicator does not necessarily reflect a strictly increasing or decreasing playback progress. This might be confusing for users accustomed to progress bars that follow a linear motion.

3. **Expected behavior:**

Ideally, the sound progress indicator should clearly represent the playback position of the audio message. This could be achieved by having the indicator smoothly progress from left to right during playback and vice versa during rewind

4. **Additional feature request (optional):**

If you allow me, I'd like to propose adding an option for users to control the playback speed of audio messages. This feature would allow users to:
* Existing Bug fix
* Increase playback speed for faster listening.
* Decrease playback speed for better comprehension of complex messages.

To ensure a smooth experience, a maximum playback speed limit could be implemented.

5. **To Reproduce**

* Play an audio message in the chat section of the Linphone-android app.
* Observe the behavior of the sound progress indicator.

6. **Please complete the following information** (mandatory)

 - Device: [REALME-C25Y]
 - OS: [ Android 11]
 - Version of the App [5.3.0]
 - Version of the SDK [5.4.0]
 - Where you did got it from ( local build)
 - Please tell us if your Android is a Lineage OS or another variant. (No)

---

 - Device: [REALME-C25Y]
 - OS: [ Android 11]
 - Version of the App [ 5.2.5]
 - Version of the SDK [ 5.3.47]
 - Where you did got it from ( Play store)
 - Please tell us if your Android is a Lineage OS or another variant. (No)

7. **SDK logs** (mandatory)

I will enable debug logs in the app settings, reproduce the issue, and then follow the instructions to provide the log link if necessary.

8. **Adb logcat logs** (mandatory if native crash)

Not applicable at this time as this is not a crash report.

8. **Screenshots** (optionnal)

https://github.com/BelledonneCommunications/linphone-android/assets/87614560/c1f0b22e-81e9-4037-90f4-e645565fd136

9. **Additional context** (optionnal)

I believe this improvement would enhance the user experience by providing a more intuitive playback progress indicator and offering greater control over audio message playback.

### Thank you in advance for considering this report!

Sincerely,

Susmita Bhattacharya

**Comment by Viish** [comment]
Hi @SB2318,

The progress bar for voice messages have been reworked in 6.0 release to come, it won't behave like that anymore.
I leave the issue opened with the enhancement flag for the possibility to do the playback at different speeds, but know it isn't on our roadmap for now.

Cheers,

**Comment by SB2318** [comment]
> Hi @SB2318,
> 
> The progress bar for voice messages have been reworked in 6.0 release to come, it won't behave like that anymore. I leave the issue opened with the enhancement flag for the possibility to do the playback at different speeds, but know it isn't on our roadmap for now.
> 
> Cheers,

Wow! Great to hear that. 
Thanks for your quick response. 😇

**Comment by SB2318** [comment]
> Hi @SB2318,
> 
> The progress bar for voice messages have been reworked in 6.0 release to come, it won't behave like that anymore. I leave the issue opened with the enhancement flag for the possibility to do the playback at different speeds, but know it isn't on our roadmap for now.
> 
> Cheers,

Please also count me in for the feature, If I can make a little contribution on it. 🙂

**Comment by Viish** [comment]
Fixed in 6.0.0 alpha now available in master branch.
