### ISSUE TITLE
linphone implements background video surveillance

### ISSUE THREAD

**Issue by LoyaiHai** [BelledonneCommunications/linphone-android#2181]
Hi
@Viish 
now I want to implement a background no-interface video surveillance. May I ask whether this function comes with linphone itself, or can it be realized by modifying the interface in the function of common video on both sides?
Such as
The server needs to tap down the rear camera of Terminal A without terminal A's knowledge to monitor the sound and camera data of terminal A. Meanwhile, Terminal A cannot hear the images and audio of the server

**Comment by Viish** [comment]
Hi @LoyaiHai,

First of all, you cannot capture video from a camera on Android without it being displayed to the user. This is a security at OS level to prevent app from spying...
That being said, you can do using our SDK a one way audio/video call (using early media for example) and do what you desire, as long as the UI of the device receiving this surveillance call displays the camera that is being recorded.

Cheers,

**Comment by LoyaiHai** [comment]
@Viish 

The one-way video feature is not appropriate, so is there a way for linphone to skip the sound when receiving a video request? When I use two-way video now, a voice comes out when I receive an incoming call

**Comment by Viish** [comment]
You can do one-way audio and two-way video, or you can simply mute one end's input.

**Comment by LoyaiHai** [comment]
@Viish 
I understand what you said, but as a video, the server is a switch that can control its own sound, and as a terminal, it should be a switch that can only passively accept the sound.
On the other hand, speaking of receiving the sound of a video call, I remember the sound is configurable, right? The idea is that when I receive a call, I call the interface to play the incoming call, and when I answer the call, I call the interface to cancel the sound, but I don't know if the linphone has such a custom interface

**Comment by Viish** [comment]
Such as that you mean?
https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Call.html#setMicrophoneMuted(boolean)

Please take time to read the documentation instead of directly asking me...

**Comment by LoyaiHai** [comment]
@Viish 
i got it,now I have one last question, which is the maximum number of routes that linphone can support, including calls and unsolicited calls
