### ISSUE TITLE
Enhancement: Show the DID / phone number an incoming call is calling in on - for users who are using Linphone with multiple lines

### ISSUE THREAD

**Issue by UPBT** [BelledonneCommunications/linphone-android#2182]
Hello

1. **Describe the bug** (mandatory)

I am using Linphone with multiple DIDs / phone numbers. I have no idea what number an incoming call is calling on

I am using F-droid release 5.2.5 armeabi-v7a

2. **To Reproduce** (mandatory)

- Add more than one phone line to Linphone, and test to see they both work.
- Have a helper randomly call you on one of the numbers
- Try to tell what line is being called using the information shown on the screen 

3. **Expected behavior** (mandatory)

When multiple SIP accounts are being used, have the phone number information display on the screen distinct from, but near to the incoming caller information

4. **Please complete the following information** (mandatory)

 - Device: LG Reflect (L555DL)
 - OS: Android 10
 - Version of the App: 5.2.5 armeabi-v7a
 - Version of the SDK: 29
 - Where you did got it from: F-Droid
 - Stock LG android firmware

If you are using a SDK that isn't the latest release, please update first as it's likely your issue is already solved.

**Comment by UPBT** [comment]
A "short name"  that could be shown instead of a phone number; such as; "Mega Lo Mart", "Strickland Propane", "Kwik-E-Mart" etc. might be a further enhancement, allowing a user to answer the phone in a distinct way depending on which line is called.

**Comment by Viish** [comment]
Hi @UPBT,

I believe such an issue has already been created in the past, and it's likely it's still opened with the enhancement flag.

This is what I'm doing with this issue as this matter was already handled in 6.0 release to come, I'll close it when it will be published since you don't like closed issues.
