### ISSUE TITLE
Problem with transferring photos over 10 mb.

### ISSUE THREAD

**Issue by Skretch1974** [BelledonneCommunications/linphone-android#2183]
Hi. I found a problem, when trying to transfer a photo with a size greater than 10 mb, the program crashes with an error. Other types of files are transferred without problems, but not more than 100 mb.
The problem with transferring photos appears on many different types of phones and it seems to be a bug in the program code.

**Comment by Viish** [comment]
Hi @Skretch1974,

Please attach debug logs showing the problem, and also a stack trace of the crash if possible.

Cheers,

**Comment by Skretch1974** [comment]
[777fdb8787fdd_5424f01af511ed42a8a4.txt](https://github.com/user-attachments/files/15863252/777fdb8787fdd_5424f01af511ed42a8a4.txt)

**Comment by Viish** [comment]
Thanks for the logs, but I can't see why it crashes in it (I don't even see the upload attempt).
Could you get the stack trace please?

**Comment by Viish** [comment]
> What sequence of actions should I do in order to trace?

Connect a device to your computer and run the "adb bugreport" command, then attach the created zip here please.

Regarding the max size for file transfer, the limit isn't set by the app but our file transfer server max_upload php value.
You can always host your own file transfer server and change that value, then change the file transfer server URL in the app.

**Comment by Skretch1974** [comment]
Another experiment conducted with an already open chat, tried to attach a photo file through a paper clip, the size of 14 mb. and the program immediately closed with an error!

**Comment by Skretch1974** [comment]
c:\Users\Home\Downloads\Mini_Adb>adb bugreport
=============================================================================
WARNING: Flat (text file, non-zipped) bugreports are deprecated.
WARNING: Please generate zipped bugreports instead.
WARNING: On the host use: adb bugreport filename.zip
WARNING: On the device use: bugreportz
WARNING: bugreportz will output the filename to use with adb pull.
=============================================================================

**Comment by Skretch1974** [comment]
That's all ADB gives on this command.

**Comment by Viish** [comment]
Then do `adb bugreport linphone.zip`

**Comment by Skretch1974** [comment]
It's still giving out something wrong...
[111.txt](https://github.com/user-attachments/files/15872773/111.txt)

**Comment by Viish** [comment]
Either it's your mini adb that's behaving weirdly, or it's because you are using a custom ROM on your device that do not respond to standard `adb bugreport` command...

**Comment by Viish** [comment]
You could also use `adb logcat` command, reproduce the issue while the device is plugged-in to your computer (and the previous command is running) and then send me the logs printed by previous command.

**Comment by Skretch1974** [comment]
[linphone.zip](https://github.com/user-attachments/files/15873429/linphone.zip)

**Comment by Viish** [comment]
Hi @Skretch1974,

Could you try again using 6.0.0-alpha from master branch please?

Thanks in advance.

**Comment by Viish** [comment]
I'm closing this issue due to lack of feedback and the fact I can't reproduce it.
Feel free to re-open with debug logs & crash stack trace if you still have it with 6.0.0 from master branch.
