### ISSUE TITLE
How do I set up two controls to display the front and rear cameras separately

### ISSUE THREAD

**Issue by LoyaiHai** [BelledonneCommunications/linphone-android#2185]
Hi
@Viish 

I am now testing the interface, left and right halves are divided into two parts, each of which corresponds to a control that displays the camera
Now what I do is I receive two calls, one on the left and one on the right, with the left control showing the front camera and the right control showing the back camera
Now my question is: in core, I see that core.setvideoDevice only sets the local front and rear cameras, but from the documentation, it seems that linphone can only set one camera at the same time
What if I want to have two controls, one showing the front camera and one showing the rear camera?
Thank you 
cheers

**Comment by Viish** [comment]
Hi @LoyaiHai,

You can't have two active calls at the same time.
If one is active, the other will be in Paused state, so you can't have two cameras open at the same time.

Cheers,

**Comment by LoyaiHai** [comment]
Hi
@Viish 
Do I understand that linphone only supports one active call, not two or more active calls?
Another question is active and suspended, is this state switched by your own bottom? Or do we need to manually modify this state?

**Comment by Viish** [comment]
> Do I understand that linphone only supports one active call, not two or more active calls?

Indeed, no more than one active call, unless you are in conference.

> Another question is active and pause, is this state switched by your own bottom?

An active call is automatically paused if you answer or initiate a new call.
