### ISSUE TITLE
Ringtone increase sound volume

### ISSUE THREAD

**Issue by basulle** [BelledonneCommunications/linphone-android#2189]
Hi, @Viish , hope you are good.
There is a minor question for you, is it possible to increase the volume of a custom ringtone file provided? I mean programmatically, not via phone's settings. 
Some people experiencing low volume of the ringtone using Samsung devices.

Thank you!

**Comment by Viish** [comment]
Hi @basulle,

No, this can't be done as the playback is made by Android OS.
You can increase the volume in the file directly using a tool such as Audacity.

Cheers,
