### ISSUE TITLE
cant reconnect on wifi roaming

### ISSUE THREAD

**Issue by krodelabestiole** [BelledonneCommunications/linphone-android#219]
Hello, I use linphone 3.3.2 on lineageos.
I'm connected to an Asterisk server and it works fine, except when I switch from a wifi access point to another (same network) or to another 3G/4G network : it doesn't reconnect automatically.
It keeps saying "connecting..." (or it might be "currently logging in..." : I don't have it in english) with the orange indicator, for hours. I have to change anything in the account settings so it reconnects (anything optional of course, not the password or the username).

I don't have this issue with the integrated android SIP (it reconnects very quickly) - and of course I don't use both at the same time.

I don't know where the issue comes from, and I don't know either if there's a log or any way to debug this so I could give more info.

Any help appreciated, thanks !

**Comment by Thucnv** [comment]
Hello, I'm not sure but I hope it helps you.
When you change network, Asterisk server send 1 message auth (401), you must resend authinfo with nonce from 401 message.

Overide public void authInfoRequested(LinphoneCore lc, String realm, String username, String domain)
 LinphoneAuthInfo old_info = lc.findAuthInfo(username, null, domain);
 if(old_info != null)
  lc.removeAuthInfo(old_info);
LinphoneAuthInfo authInfo = LinphoneCoreFactory.instance().createAuthInfo(username, userId, passWord, null, realm, domain);
 lc.addAuthInfo(authInfo);

**Comment by 111usman** [comment]
I have tried this but in vain...After all thanks
