### ISSUE TITLE
About audio coding failure

### ISSUE THREAD

**Issue by LoyaiHai** [BelledonneCommunications/linphone-android#2190]
Hi
@Viish 
When I am in a voice conference, if at this time, I in Android, open an audio encoding subthread: AudioRecord call, will find that the ffmpeg encoding passed to the underlying avcodec_send_frame, there will be initialization failure, please ask how to solve this problem?

**Comment by Viish** [comment]
Hi,

Sorry but I can't help with that, it's out of the scope of our project and my expertise.

Cheers,

**Comment by LoyaiHai** [comment]
Hi
@Viish 
Perhaps I should ask this question: When I am on a normal voice conference call, is there any way to get the raw audio data of the current conference through the interface or in byte[] audioData format

**Comment by Viish** [comment]
Not at application level, no.
But you could write your own mediastreamer2's filter and build it along with our SDK, that would work.

**Comment by LoyaiHai** [comment]
Hi
@Viish 
What you said is exactly what I want to ask, my idea is that if linphone can provide an interface, you can do: through the MdeiaCode audio encoding, the obtained byte[] data, into your audio interface, I think I will be better understanding.
But the problem now is that I don't quite understand what you mean by write mediastreamer2's filter. Is there any related link that I can learn?

**Comment by Viish** [comment]
We don't have documentation about that, but you can take a look at our filters: https://github.com/BelledonneCommunications/mediastreamer2/tree/master/src/videofilters

**Comment by LoyaiHai** [comment]
Hi
@Viish 
Or, can you tell me what encoding format you use for the underlying audio on the linphone? Does the microphone channel say which channel it's fixed on?
Thank you 
Cheers
