### ISSUE TITLE
Connect is not restored after rebooting the sip station.

### ISSUE THREAD

**Issue by adzmailru** [BelledonneCommunications/linphone-android#2191]
Hello!

1. Smart with screen lock -> reboot the sip station -> connect is not restored after rebooting the sip station.
2. Connect is restored after relogining only.

 - Device: [Huawei nova 3i]
 - Android 9
 - minimal linphone-sdk-android-5.3.58.aar, linphone-sdk-android-5.3.60.aar........
 - download.linphone.org

Thank you in advance!

**Comment by Viish** [comment]
Hi @adzmailru,

If by SIP station you mean your SIP proxy server, then I can't help you as it is the proxy's job to keep the registrations when it reboots. Nothing can be done on the client side to prevent that.

Cheers,
