### ISSUE TITLE
About the last parameter in the onCallStateChanged() callback interface: @NonNull String message, how is this parameter appended?

### ISSUE THREAD

**Issue by LoyaiHai** [BelledonneCommunications/linphone-android#2192]
Hi
@Viish 
@Override
        public void onCallStateChanged(@NonNull Core core, @NonNull Call call, Call.State state, @NonNull String message);
I want to know how the last parameter of the callback method above, @NonNull String message, is appended
Example: When device A calls device B, how device A constructs data when it sends a call invitation (message attached with: Hello) can make the onCallStateChanged() callback received in device B contain the content of the last parameter message at the time of receiving the call: Hello
Thank you 
Cheers

**Comment by Viish** [comment]
Hi,

message parameter of that callback is merely a text explaining the state (if needed). For example it may be a short phrase explaining why the call was terminated.
If you want to send/receive data along with INVITEs, you may want to add a custom header to the CallParams object.

Cheers,
