### ISSUE TITLE
Changing call output device while ringing

### ISSUE THREAD

**Issue by basulle** [BelledonneCommunications/linphone-android#2193]
Hello, @Viish 

Having some issues with output device and ringing on linphone-sdk:5.3.32.
When receiving a call and while its ringing changing the output device for the call on some devices its giving an interruption with following issues:
[AAudio Recorder] Hardware echo canceller object already created and not released!
[AAudio Player] aaudio_player_callback_error has result: -899 / AAUDIO_ERROR_DISCONNECTED

On other devices its affects the ring volume (the default output is earpiece, but when changing it to Speaker, its ringing louder). Why setOutputAudioDevice affects the setRingerDevices method?

Thank you!

**Comment by Viish** [comment]
Hi,

Depending on how you use our SDK, the ringing may be done by Android directly or by our SDK.
If it's done by our SDK, changing the output audio device while it rings will change the ringing playback device (and thus the volume).

Cheers,
