### ISSUE TITLE
Abnormal call status

### ISSUE THREAD

**Issue by lzb342999453** [BelledonneCommunications/linphone-android#2195]
hello:
The call status seems to be incorrect
I called the other party, but they refused the call. The status return on my end is Connected->StreamsRunning->End->Released.
Why does the other party refuse the call or return to the connect state? My understanding is that it should be directly End->Released
The same goes for version 5.3, If I need to send the log again, but I don't think it's necessary, it's easy to reproduce

Hope answer, thank you

**Comment by Viish** [comment]
Hi @lzb342999453,

Indeed this flow isn't right, but I can't reproduce it.
Please attach debug logs showing the issue (from the start of the app).

Thanks in advance.
Cheers,

**Comment by lzb342999453** [comment]
https://github.com/BelledonneCommunications/linphone-android/assets/20009725/e26c8b82-df8d-45f9-a6e8-368746a21a0e
Above is the recorded video.
Here is the phone log on the right side of the video.
[HUAWEI-SEA-AL10-Android-10_2024-07-02_153420.zip](https://github.com/user-attachments/files/16064357/HUAWEI-SEA-AL10-Android-10_2024-07-02_153420.zip)
Perhaps it's an issue with server settings? I don't know much about servers, I just built a temporary set of virtual machines

Thanks in advance.
Cheers,

**Comment by Viish** [comment]
Thanks for the logs & the video but the logs can't be read under that format.
Please capture only the logs using either adb logcat command or built-in log upload & share feature in advanced settings of Linphone app.

**Comment by lzb342999453** [comment]
https://www.linphone.org:444//tmp/6683ba27789ff_1c0e6bc4104975bb3c79.gz

I uploaded it using built-in logs. Before uploading, I cleared the logs and then restarted the app. I'm not sure if you can see the comprehensive logs

**Comment by Viish** [comment]
Thanks. Maybe this is a side effect because you are doing early media.
Could you add the logs from the other device as well (the one that denies the call) please?
I'll then forward the issue to our SDK team.

**Comment by lzb342999453** [comment]
https://www.linphone.org:444//tmp/6683cbb838889_de53cb8fcafdc300c955.gz
This is the log of denies the call.
The log status of rejecting calls is normal.
IncomingReceived->End->Released

Thanks.

**Comment by Viish** [comment]
Are you sure about the link? I get a 404 error when trying to download the log file.

**Comment by lzb342999453** [comment]
https://www.linphone.org:444//tmp/6683cbb838889_de53cb8fcafdc300c995.gz
Oh!My god!I'm sorry!
My mistake, the address is a wrong number. This address is acceptable

**Comment by Viish** [comment]
Thanks!
So with both logs I can tell you the issue isn't in Linphone but in your proxy (Freeswitch according to user-agent).
Linphone doesn't even asks/accept early media on the receiver side, so it is freeswitch that does it (probably using a back-to-back user-agent or B2BUA).
Check your proxy server config to disable that.
Cheers!

**Comment by lzb342999453** [comment]
Thanks!
Then I'll take a look at the server again, although I'm not very familiar with it.
Thank you for your answer
