### ISSUE TITLE
Early Media working in lock screen but not in foreground/background

### ISSUE THREAD

**Issue by Adnan-addi** [BelledonneCommunications/linphone-android#2196]
@Viish 
Hi . 
i am using latest android-linphone and i can see early media when my device is in lock screen and idle , but when i am using the app or app is in background early media doesnot popups, only incoming call notification is shown . 

is this meant to be like this or there is option to see early media when app is in background on foreground ?
Thanks

**Comment by Adnan-addi** [comment]
Any help in this regard please . ?

**Comment by Viish** [comment]
Hi,

You can't do what you want. Android's full screen intents work that way (full screen activity if the device is in idle mode, otherwise a notification) and there's no way around it.

Cheers,
