### ISSUE TITLE
After the call connection is successful, the audio payload type is null

### ISSUE THREAD

**Issue by LoyaiHai** [BelledonneCommunications/linphone-android#2199]
Hi 
@Viish 
I try to initiate a call, when I connect successfully, I want to use the call in the current callback to get the encoder of the audio information, but unfortunately, in the getUsedAudioPayloadType() method returned null, may I ask is I get the wrong place, or get the wrong way?
Here is the call location:
![image](https://github.com/BelledonneCommunications/linphone-android/assets/32878163/6e5096b4-84cb-489e-af35-b1e98a7fa9bd)

Thank you
Cheers

**Comment by LoyaiHai** [comment]
Hi
@Viish 
yes, I add a CallListenerStub to receive it.
Again, does linphone have an audio callback interface? I'd like to get the audio data for the current call line
Thank you

**Comment by Viish** [comment]
> Again, does linphone have an audio callback interface? I'd like to get the audio data for the current call line

Still no.

**Comment by LoyaiHai** [comment]
@Viish 
So the other question is: are the lines in the call, are the audio sources multiple or specific?
For example, if I initiate an audio call, this source is:
MediaRecorder.AudioSource.REMOTE_SUBMIX
MediaRecorder.AudioSource.RADIO_TUNER
MediaRecorder.AudioSource.VOICE_DOWNLINK
MediaRecorder.AudioSource.VOICE_UPLINK
MediaRecorder.AudioSource.VOICE_CALL
MediaRecorder.AudioSource.ECHO_REFERENCE
or 
MediaRecorder.AudioSource.DEFAULT
MediaRecorder.AudioSource.MIC
MediaRecorder.AudioSource.CAMCORDER
MediaRecorder.AudioSource.VOICE_RECOGNITION
MediaRecorder.AudioSource.VOICE_COMMUNICATION
MediaRecorder.AudioSource.UNPROCESSED
MediaRecorder.AudioSource.VOICE_PERFORMANCE

**Comment by LoyaiHai** [comment]
Hi
@Viish 
Maybe I should ask this: Is there an interface in the voice/video process of the call that can remove the current audio encoding and audio data transmission, and then also set the audio encoding again to send audio data again?
Thank you 
Cheers

**Comment by Viish** [comment]
> Maybe I should ask this: Is there an interface in the voice/video process of the call that can remove the current audio encoding and audio data transmission, and then also set the audio encoding again to send audio data again?

No, we don't offer any way for app developpers to alter the voice or video data that's being sent or received.

**Comment by LoyaiHai** [comment]
Hi
@Viish 
I was under the impression that callParam in call has a method, which can be set not to send audio or video of its own, so may I ask if I call this interface, in fact, just suspend the transmission of audio data, or directly clear and release the audio coding?
Thank you 
Cheers

**Comment by Viish** [comment]
Yes you can use https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/CallParams.html#setAudioEnabled(boolean) or https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/CallParams.html#setVideoEnabled(boolean) to disable a type de data from being sent & received.

**Comment by LoyaiHai** [comment]
Hi
@Viish 
I suddenly thought of a situation: May I ask about the underlying audio of linphone, do you collect audio data PCM first, and then convert it to AAC or G711 type? I now suspect that your bottom layer is also using PCM audio data first, and then processing
Thank you

**Comment by Viish** [comment]
Yes our SDK does use PCM audio data directly.

**Comment by LoyaiHai** [comment]
Hi
@Viish 
i got it, But at present, if I create an audio capture PCM data by myself, I would like to ask whether linphone supports custom audio data input, because this audio data is also needed in other places. If linphone does not have a method to support custom audio data input, I would like to ask that when I create a custom audio capture, the data will certainly fail to read, how to solve this situation?

**Comment by Viish** [comment]
> I would like to ask whether linphone supports custom audio data input

No, it doesn't.

> I would like to ask that when I create a custom audio capture, the data will certainly fail to read, how to solve this situation?

I don't know, sorry.
