### ISSUE TITLE
Friend's phone numbers multiply on each view

### ISSUE THREAD

**Issue by lameventanas** [BelledonneCommunications/linphone-android#22]
Using Linphone 3.2.4 on Android here.

My provisioned xml contains:
```
<section name="friend_0">
  <entry name="url">"My Buddy" &lt;sip:01@server.com&gt;</entry>
  <entry name="pol">deny</entry>
  <entry name="subscribe">0</entry>
</section>
```

The friend shows up in Linphone, but every time I open the friend (ie: to see call, see the info), a new contact url gets added.  That means if I open the friend 3 times, I will have `sip:01@server.com` 4 times.

**Comment by DatBewar** [comment]
Hello,
this problem is fixed on master and in Linphone 3.2.5
Best regards,
