### ISSUE TITLE
Respond to a SIP invite

### ISSUE THREAD

**Issue by basulle** [BelledonneCommunications/linphone-android#2200]
Hello, @Viish

Using linphone SDK version 5.3.61 and facing some mismatching with iOS.

When receiving a SIP invite, Android is responding to it with a 183 (Session progress), while iOS responding with 180 (Ringing).

Why iOS and Android behaves differently here? We have a web app which is built without linphone, and this 183 is causing the audio path to be established to the mobile handset even when we answer on Web.

Facing this when logged in to Web and Android using same account.

Thank you!

**Comment by Viish** [comment]
Hi,

> When receiving a SIP invite, Android is responding to it with a 183 (Session progress), while iOS responding with 180 (Ringing).

Did you checked the "accept early media" setting in Linphone Android's call settings?
183 means early media, 180 means classic ringing.

Cheers,

**Comment by basulle** [comment]
@Viish That made the trick, big thanks!
