### ISSUE TITLE
How to monitor the transfer status of the phone

### ISSUE THREAD

**Issue by happyfsyy** [BelledonneCommunications/linphone-android#2201]
Hello, how can I obtain the callback for monitoring the call transfer state?

For example, I currently have three phones with numbers 8001, 8002, and 8003. I initiate a call from phone 8001 to 8002, then from 8002 to 8003. After that, I transfer the first call on 8002 to 8003.

I have already set up the onTransferStateChanged() interface in CoreListenerStub, but I only receive the callback on phone 8002.

My requirement is that, after the transfer is successful, phone 8001 should display that it's now in a call with 8003, and phone 8003 should also display that it's in a call with 8001.

Thanks in advance

**Comment by Viish** [comment]
Hi @happyfsyy,

Try using https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/CoreListenerStub.html#onReferReceived(org.linphone.core.Core,java.lang.String).

Cheers,

**Comment by happyfsyy** [comment]
Hello, @Viish 
I have tried this, but when the call is transfered, the callback is not invoked.
Similarly, your Linphone-Android app does not have the function to update the number after transfe.

> Hi @happyfsyy,
> 
> Try using https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/CoreListenerStub.html#onReferReceived(org.linphone.core.Core,java.lang.String).
> 
> Cheers,
