### ISSUE TITLE
Why can't the other party hear the hold music?

### ISSUE THREAD

**Issue by happyfsyy** [BelledonneCommunications/linphone-android#2204]
Hello, I looked at the relevant api, called core.getPlayFile(), and got the following result:
/data/user/0/com.mypackage.mypackgename/files/share/sounds/linphone/dont_wait_too_long.mkv

Is it a problem with this mkv file?
Because according to the interface description, it is not a 16-bit linear wav file.

**Comment by Viish** [comment]
HI @happyfsyy,

Our Player object is able to play MKV files (containing Opus audio).

Cheers,
