### ISSUE TITLE
Direct call?? P2P??

### ISSUE THREAD

**Issue by AKC-Kang** [BelledonneCommunications/linphone-android#2205]
good morning. 

Using Linphone and sip server, phone function was implemented.

By the way, can I make a call directly from client App without going through the SIP server?

For example, make a direct call to 192.168.12.249 from an Android app.

**Comment by Viish** [comment]
Hi @AKC-Kang,

> can I make a call directly from client App without going through the SIP server?

Yes, you can.

Cheers,

**Comment by AKC-Kang** [comment]
can you explain to how to use?

**Comment by Viish** [comment]
Assuming you are listening to standard 5060 port, simply dial "test@192.168.12.249" (username doesn't matter).

**Comment by AKC-Kang** [comment]
https://www.linphone.org:444//tmp/668bb82420279_187412fd00c4cf5e4382.gz

sorry. can you find my mistake?? call does not connected.

**Comment by Viish** [comment]
The remote end of your call returns an error, you should check it's logs to understand what happens:
```
2024-07-08 16:56:26:355 [org.linphone.debug/belle-sip] MESSAGE channel [0x7957827400]: received [383] new bytes from [UDP://192.168.12.249:5060]:
SIP/2.0 500 Internal Server Error
Via: SIP/2.0/UDP 192.168.12.86:43048;branch=z9hG4bK.Emf~u3ZVZ;rport=43048
From: "Linphone Android" <sip:linphone.android@192.168.12.86>;tag=-cWNwbqLM
To: "11" <sip:100@192.168.12.249>;tag=1879010617
Call-ID: T4Dr5MpLbt
CSeq: 20 INVITE
Allow: INVITE, ACK, OPTIONS, BYE, CANCEL, REFER, NOTIFY, INFO, PRACK, UPDATE, MESSAGE
Content-Length: 0
```

**Comment by AKC-Kang** [comment]
client(app)       :  192.168.12.86
server(phone) : 192.168.12.249

can't connect to 192.168.12.249 by direct call. 
could you teach me about my mistake? 

https://github.com/BelledonneCommunications/linphone-android/assets/173016720/c65b15cb-43a4-4c0b-bfdd-2a5a661f7c2d

https://www.linphone.org:444//tmp/668df5091c124_f7ea2548947bf102e351.gz
