### ISSUE TITLE
AudioDirection is set to receive only invalid

### ISSUE THREAD

**Issue by LoyaiHai** [BelledonneCommunications/linphone-android#2207]
Hi
@Viish 
When I receive an incoming call request, after the automatic processing is answered, in the callback state of successful connection, the following parameters are set to change the audio direction:
CallParams callParams = currentCore.createCallParams(currentCall);
callParams.setAudioDirection(MediaDirection.RecvOnly);// MediaDirection.RecvOnly->2
int updateResult = currentCall.update(callParams);
the updateResult is return 0;
but when state == Call.State.Updating;
int currentDir = call.getParams().getAudioDirection().toInt();
the currentDir is MediaDirection.SendRecv

why?

**Comment by Viish** [comment]
Hi @LoyaiHai,

Please stop opening tickets in linphone-android repository when your questions are about our SDK behavior and APIs.

Cheers,

**Comment by LoyaiHai** [comment]
Hi
@Viish 
I'm not sure I understand what you mean
On the other hand, I integrate android's sdk, shouldn't I raise questions about Android in this current issue?

**Comment by LoyaiHai** [comment]
Hi
@Viish 
i got it, thank you
