### ISSUE TITLE
Telnyx SMS/MMS

### ISSUE THREAD

**Issue by bradlysnyder2021** [BelledonneCommunications/linphone-android#2208]
Hi so I'm new to Linphone but was trying to setup calls and messaging through my telnyx sip trunk via the linphone softphone app on my android phone, I got calling working but found that messaging doesn't work because telnyx requires a webhook or url where they can send inbound messages etc. But Linphone doesn't seem.to provide a webhook url or any other url that can be used by telnyx to send messages they receive to the softphone 

Is this just me ? Is this just telnyx that has this issue ? 
Would it be possible for the Linphone team or the community to add webhook into the linphone app please ?

**Comment by Viish** [comment]
Hi @bradlysnyder2021,

Sorry but we have no experience with Telnyx, but I can tell you I don't see why a webhook would be required to do messaging (we don't have one).

Cheers,

**Comment by bradlysnyder2021** [comment]
Many sip trunk providers need webhooks for sms/mms services to work
In my case they deliver all inbound sms/mms by sending to the webhook url

**Comment by Viish** [comment]
Sorry but we do not implement that at this time.
