### ISSUE TITLE
How to enable belle_sip_warning and belle_sip message loglevel enable?

### ISSUE THREAD

**Issue by leechul** [BelledonneCommunications/linphone-android#221]
How to enable belle_sip_warning and belle_sip message loglevel enable?

**Comment by manujay** [comment]
Hi, I had the same issue, when I tried to log SIP states to be shown in android logcat. If this is the issue you might have to use android log header with [this](https://stackoverflow.com/questions/12159316/logging-values-of-variables-in-android-native-ndk).
