### ISSUE TITLE
How we can know realtime connection status?

### ISSUE THREAD

**Issue by AKC-Kang** [BelledonneCommunications/linphone-android#2211]
![image](https://github.com/user-attachments/assets/6da5e84c-b753-4294-a1a6-a9ce025c79a0)

Connection status does not display by realtime. 
When i test this, it changed about 40 Sec~ 1 min.

How Can we get connection status by realtime??

**Comment by Viish** [comment]
Hi @AKC-Kang,

Status is displayed in realtime, giving the 200 OK for the REGISTER is sent in real time by your server.

Cheers,
