### ISSUE TITLE
Where is the group calling feature of Linphone Adroind 6.0.0?

### ISSUE THREAD

**Issue by samwell-ho** [BelledonneCommunications/linphone-android#2214]
Hi,

Does Linphone Android 6.0.0 still have group video conversation feature?

I don't find this feature in the new interface.

**Comment by Viish** [comment]
Hi @samwell-ho,

Group call feature is available in the calls screen: click on start call (floating action button) and then on the "start group call" label/button.

Cheers,

**Comment by samwell-ho** [comment]
I saw it, it is necessary to configure the URI for the Meeting feature to appear the interface allowing this function to be performed.

**Comment by Viish** [comment]
Yes, you need to set the audio-video-conference-factory-uri for both group calls and meetings (it's basically the same thing).

You can also merge multiple calls into one (locally), this doesn't require any server.
