### ISSUE TITLE
Use WiFi only doesn't work (regression, old issue appears again)

### ISSUE THREAD

**Issue by Norbert80** [BelledonneCommunications/linphone-android#2217]
Issue #587 again appears with version 5.2.5.

**Comment by Viish** [comment]
Hi @Norbert80,

Please explain "what doesn't work" and attach logs (as asked in the template that you removed...).

Thanks in advance.

**Comment by Norbert80** [comment]
@Viish it is ecatly like described in Issue https://github.com/BelledonneCommunications/linphone-android/issues/587

If that option is turned on and mobile data is used (wifi = off) Linphone stays connected to the SIP server and calls can be answered or placed. The option has no effect if turned on.

**Comment by Viish** [comment]
As I said, please attach logs showing the issue.

**Comment by Norbert80** [comment]
@Viish Sorry, I do not have logs. But you can reproduce it very easily.

**Comment by Viish** [comment]
Sorry but this can be due to different issues (type of network, VPN, android OS version, etc...) so I need logs to understand and fix the issue.

**Comment by Norbert80** [comment]
No VPN. One device is on Android 13. (The other one has an older Android version. I have no access to the second device at the moment.)

Did you try to reproduce it?

**Comment by Norbert80** [comment]
Sorry. The debug logs contain sensitive data. So I cannot provide one.

**Comment by Viish** [comment]
> Did you try to reproduce it?

No, I'm currently on vacation.

You can send the logs link to me by email (mention the issue number in the subject): sylvain.berfini@belledonne-communications.com

**Comment by Norbert80** [comment]
> > Did you try to reproduce it?
> 
> No, I'm currently on vacation.
> 
> You can send the logs link to me by email (mention the issue number in the subject): [sylvain.berfini@belledonne-communications.com](mailto:sylvain.berfini@belledonne-communications.com)

Done. Did you receive them?

**Comment by Viish** [comment]
> Did you receive them?

Yes thanks. Will take a look in two weeks when I'll be back to work.

**Comment by Norbert80** [comment]
> > Did you receive them?
> 
> Yes thanks. Will take a look in two weeks when I'll be back to work.

Thank you. Feel free to request a new one if you need call activity in the logs.

**Comment by Viish** [comment]
Hi,

I merged a fix for it in SDK's master branch (available in maven repo).
Thanks for reporting the issue!

Cheers,
