### ISSUE TITLE
 Using linphone aar crashes when a call is accepted

### ISSUE THREAD

**Issue by hieujames** [BelledonneCommunications/linphone-android#2218]
I am using aar file linphone sdk android novideo to create an app. 

I called the .so files into the project and put the classes into the project, everything started up fine until I made the call and received a response from the other side, my application stopped working. and report errors. 

I searched and read a lot but couldn't find a solution, please help me

Dialog [0xb400006f54f7910]: now updated by transaction [0xb400006f44€00cb0]. op [Oxb400006f4ff00] : setOrUpdateDialog() current=[0xb400006f54f7910] new=[0xb400006f54f7910]
0p [Oxb400006faff00] receiving call response [200], dialog is [Oxb400006f540f7910] in state [BELLE_SIP_DIALOG_CONFIRMED]
Could not load grammar sdp_grammar because the file could not be located.
Unable to load SDP grammar
Aborting
runtime.cc:691] Runtime aborting...
runtime.cc:691] Dumping all threads without mutator lock held runtime.cc:691] All threads:
runtime. cc:691] DALVIK THREADS (26):
runtine.cc.orl
"main" prio=10 tid=1 Runnable
runcine.cc.orl
group="" sCount=0 ucsCount=0 flags=0 obj=0x732ddf88 self=0xb400007014cfa7b0
runtime.cc.o?1
I sysTid=7337 nice=-10 cgrp=top-app sched=0/0 handle=0x7160d64500
runtime.cc:691]
I state=R schedstat=( 2136066439 293585180 2595 ) utm=184 stm=29 core=7 HZ=100
runtime.cc:691]
stack=ox/fr5509000-ox/trs50b000 stacksize=8188KB
runtime.cc:691]
I held mutexes= "abort lock" "mutator lock" (shared held)
runtime.cc:691]
native: #00 pc 004be294
/apex/com.android.art/lib64/Libart.so (art::DumpNativeStack+108) (BuildId: 5b1e3dce5abfbde
runtime. co:691]
native:
#01 pc 004afbac
/apex/com.android.art/lib64/libart.so (art::Thread::DumpStack const+388) (BuildId: 5b1e3dc
runtime. cc:691]
native:
#02 pc 004af4ec
/apex/com.android.art/lib64/Libart.so (art::DumpCheckpoint::Run+164) (BuildId: 5b1e3dce5ab
runtime. cc:691]
native:
#03 pc 003b129c
/apex/com.android.art/lib64/libart.so (art::ThreadList::RunCheckpoint+452) (BuildId: 5b1e3
runtime. ce:6911 native:
#04 pc 004c9400
/apex/com.android.art/lib64/libart.so (art::ThreadList::Dump+232) (BuildId: 5b1e3dce5abfbd
runtime. cc: 691]
native:
#05 pc 00770084
/apex/com.android.art/lib64/libart.so (art::Runtime::Abort+2156) (BuildId: 5b1e3dce5abfbdc
runtime. cc: 691]
native:
#06 pc 000357d0
/apex/com.android.art/lib64/libbase.so (android::base::SetAborter::$_0::__invoke+80) (Buil
runtime. cc: 691]
native:
#07 pc 00006e10
/system/lib64/liblog.so (__android_log_assert+308) (BuildId:

**Comment by Viish** [comment]
Hi @hieujames,

How do you import our SDK in your app? What version of our SDK are you using?
I'll also need debug logs from our SDK from the start of the app to the moment it crashes.

Cheers,

**Comment by hieujames** [comment]
Hi @Viish ,

I went to https://download.linphone.org/maven_repository/org/linphone/ and selected linphone-sdk-android-novide-5.2.110 and downloaded the aar package. 
Then I unzip and use the jni file in the project. 
When I run the application, it works fine, but when I make a call, I get this error.

Here is the entire error code. When I make an outgoing call, it's fine, but when I receive Accepted from the recipient, it crashes

[AttachLog.txt](https://github.com/user-attachments/files/16454544/AttachLog.txt)

**Comment by Viish** [comment]
> I went to https://download.linphone.org/maven_repository/org/linphone/ and selected linphone-sdk-android-novide-5.2.110 and downloaded the aar package.
Then I unzip and use the jni file in the project.

That's not how to do it.
First of all, our latest release is 5.3 (5.4 should be published before September), so you should always use the latest (we don't support old releases).

Second you must use the whole AAR if you want it to work, as there are files required, such as the grammar files.
The easiest is to configure our maven repository in your settings.gradle file like this:
```
maven {
            name "local linphone-sdk maven repository"
            url file(LinphoneSdkBuildDir + '/maven_repository/')
            content {
                includeGroup "org.linphone"
            }
        }
```
and then in your app/build.gradle file add the following line: `implementation 'org.linphone:linphone-sdk-android:5.3+'`

Cheers,
