### ISSUE TITLE
Ringing device when bluetooth connected.

### ISSUE THREAD

**Issue by basulle** [BelledonneCommunications/linphone-android#2219]
Hello @Viish 

Facing one thing and I don't know if this a bug.
Using linphone 5.3.61 and facing one thing, which I think by default should not behave like this.

When device is connected to some bluetooth headset and its receives and incoming call, device is ringing on speaker and headset at the same time. Should it be ringing only for bluetooth in this case?

It can be handled easily by our own, but maybe it should be added for you as well.

Thank you!

**Comment by Viish** [comment]
Hi @basulle,

This is the expected behavior on Android.
When a device is ringing, Android plays the ringtone on both the bluetooth and the device (it's not us that are doing the playback).

Cheers,
