### ISSUE TITLE
Publishing new version to Google Play

### ISSUE THREAD

**Issue by basulle** [BelledonneCommunications/linphone-android#2221]
Hi, @Viish, hope you are doing well.

Trying to publish a new version of the app and facing some unclear stuff.

Linphone using some permissions for Android 14, some of them are unclear.
<img width="521" alt="image" src="https://github.com/user-attachments/assets/fcd4ddf9-2d41-4c76-bf35-75782726b253">

<img width="906" alt="image" src="https://github.com/user-attachments/assets/1c1bbc5e-ee8c-4a85-82a9-b9e864ff229a">

These are clear:
FOREGROUND_SERVICE_MICROPHONE
FOREGROUND_SERVICE_PHONE_CALL

But these are not:
FOREGROUND_SERVICE_CAMERA
FOREGROUND_SERVICE_DATA_SYNC

We are using linphone-sdk-no-video, so why do we need for FOREGROUND_SERVICE_CAMERA?
And what about FOREGROUND_SERVICE_DATA_SYNC? 

Is there a way to remove them or describe for google why we are using them, if necessary? Google as well asking for a video, which demonstrates each of this permissions in action.

Big thanks!

**Comment by Viish** [comment]
Hi @basulle,

> We are using linphone-sdk-no-video, so why do we need for FOREGROUND_SERVICE_CAMERA?

You don't. In 5.4 SDK the permission was removed from Manifest for no-video SDK, but you can still remove it manually, see https://developermemos.com/posts/removing-unwanted-manifest-permissions

FOREGROUND_SERVICE_DATA_SYNC is required to correctly process incoming calls/messages push notifications in some cases.

Cheers,
