### ISSUE TITLE
The linphone's external speaker has a maximum sound limit

### ISSUE THREAD

**Issue by LoyaiHai** [BelledonneCommunications/linphone-android#2224]
Hi
@Viish 
When I use other apps, I set the speaker to be put out during the call, and the voice is very loud in the hands-free state
However, when I was talking on the linphone, I found that in the same configuration, the sound of the other device was about a third lower when placed outside the speaker, hands-free. Does this improve the sound?
Thank you
Cheers!

**Comment by Viish** [comment]
Hi,

What version of the SDK are you using?
Make sure the call stream volume is set to the max.
Also you can add software gain with API if needed.

Cheers,

**Comment by LoyaiHai** [comment]
5.2.99



---- Replied Message ----
| From | Sylvain ***@***.***> |
| Date | 08/05/2024 21:02 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [BelledonneCommunications/linphone-android] The linphone's external speaker has a maximum sound limit (Issue #2224) |

Hi,

What version of the SDK are you using?
Make sure the call stream volume is set to the max.
Also you can add software gain with API if needed.

Cheers,

**Comment by Viish** [comment]
Stop using old releases please. Use either latest 5.3 or 5.4.0-alpha, we don't support old releases.
