### ISSUE TITLE
Pause in Conference Call is not working

### ISSUE THREAD

**Issue by shivbuyya** [BelledonneCommunications/linphone-android#2225]
Hello,

Pause in Conference Call is not working. I have initiated the conference call with users A & B. I am pressing pause during the call, on press of pause the users A & B should get paused. But it is not happening. 

So I have tried to capture logs at my SIP server to analyse the issue. But i have noticed that on press of pause button no packet is received by server. 

Can you please suggest what could be the issue. 

Thanks, 
Shiv

**Comment by Viish** [comment]
Hi @shivbuyya,

This is expected as "pause" only means "local participant temporary leaves the conference", not "all participants are paused".

Cheers,

**Comment by shivbuyya** [comment]
Ok thank you so much @Viish for clarification.
