### ISSUE TITLE
Inbound call rejection issue

### ISSUE THREAD

**Issue by muhamzafarooqi** [BelledonneCommunications/linphone-android#2231]
Hi,

For inbound call when we reject call it does not reject call, call continues from other end only the call notification disappears. 
After 10-15 seconds incoming call notification for the same call again appears and this time call is rejected successfully.
I've been using SIP number "16162273253" with protocol "udp".

Steps to Reproduce

1 - Call to your linphone app from any other number
2 - Reject call
3 - Call will not be rejected from caller side
4 - After 10-15 seconds again incoming will be received
5 - This time call rejection works

Expected behaviour :  Call must be rejected on first time.

Device Details: 

 - Device: Samsung Galaxy A13 (I have tested on other devices too, this is not device specific issue)
 - OS: Android 14
 - Version of the App: 6.0.0
 - Version of the SDK:  can't find in about section off app (latest)
 - Where you did got it from: Google Play Store and local build

Other Details: I have tested the behaviour over Zoiper app and it works well there.

**Comment by Viish** [comment]
Hi @muhamzafarooqi,

First of all, it's likely your issue is due to your use of UDP protocol instead of TCP or TLS.

To be sure, could you please attach logs showing the issue from both end of the call?

Cheers,

**Comment by muhamzafarooqi** [comment]
Hi @Viish Here are the [logs](https://github.com/user-attachments/files/16640960/inbount_reject_issue.txt) from the receiver end. It includes logs of all 5 Steps as mentioned above.

**Comment by Viish** [comment]
Hi,

Thanks for the logs, it seems it's not related to UDP in contrary to what I initially thought.
The DECLINE is sent and less than 500ms later the ACK for it is received, so the packet hasn't been lost.

You should check in your SIP proxy logs for the explanation, it's not related to the Linphone client denying the call.

Cheers,

**Comment by muhamzafarooqi** [comment]
Thanks for looking into it @Viish 
I was just wondering how can the same scenerio works perfectly fine on Zoiper app having same SIP credentials. Do you think there is something else that is causing it apart from server configurations?

**Comment by Viish** [comment]
I seem to recall that Zooper redirects traffic to their servers sometimes, that may be why you don't have the issue with it.
You can try to use our sip.linphone.org server as an outbound proxy to test.
