### ISSUE TITLE
After IPv6 outgoing call failed and the request timed out

### ISSUE THREAD

**Issue by ax3726** [BelledonneCommunications/linphone-android#2232]
Hello

After IPv6 outgoing call failed and the request timed out

What is the reason for the successful call after IPv6 is disabled?

android version 5.0.0

**Comment by Viish** [comment]
Hi @ax3726,

First of all I'd need logs to properly answer you, but on top of my head I'd say your SIP proxy server doesn't support IPv6.

Cheers,
