### ISSUE TITLE
Service not starting properly on boottime

### ISSUE THREAD

**Issue by conracer** [BelledonneCommunications/linphone-android#2234]
Linphone seems not to start the background-service on boottime, if I deactivate the permanent notification to make my system look cleaner. This is my opinion because I can't reach my phonenumber I set up in Linphone in this scenario.
Now if I start the Linphone app after Android has booted up I can reach the number. But If I start it and immediately swipe the app up to terminate it - without calling the number - Linphone seems also to stop the service. I have to start Linphone, call the number to generate a missed call, then I can swipe the app up and after that I have a scenario where the service seems to run in the background (available for incoming calls). The swiped up app makes also my system look cleaner.
This must be a Linphone issue and not Android (Samsung Note 20 Ultra Exynos) because another app called FairEmail seems to start the service on boottime without needing to launch the app gui beforehand. It receives the E-Mails via push just like it is meant to be.
Good for you: this app is also open source!

**Comment by Viish** [comment]
Hi @conracer,

When you use a third party SIP service (so not sip.linphone.org) push notifications aren't available.
The only backup solution for that is to have a service permanently running to keep the app alive, and if you disable the notification the service isn't kept running by Android, so it is expected you won't receive anything in that scenario.

FYI email apps rely on JobManager to post tasks at repeated intervals (such as fetching emails) but that isn't possible for calls & IM that needs to be able to receive and display events in real-time.

What version do you use? If you build the master branch of our repository or if you subscribe to the public beta channel on the Play Store you'll have access to 6.0.0-beta version that makes the background service notification more discreet.

Cheers,

**Comment by conracer** [comment]
> When you use a third party SIP service (so not sip.linphone.org) push
> notifications aren't available.

It is OK.

> The only backup solution for that is to have a service permanently
> running to keep the app alive, and if you disable the notification the
> service isn't kept running by Android, so it is expected you won't
> receive anything in that scenario.

Try it for yourself how I managed to receive calls anyway. Maybe I can
show you in a call with screen share which switch I turned off.
It could be the fact, that FairEmail has a separate button implemented
to disable/enable the synchronization. It is located near screen
recorder/wifi/bluetooth turn on/off buttons. So this could be the reason
why Linphone service stops when disabling the permanent notification.
Maybe it IS a bug in Android and you have to program this kind of button
to work around it.

> FYI email apps rely on JobManager to post tasks at repeated intervals
> (such as fetching emails) but that isn't possible for calls & IM that
> needs to be able to receive and display events in real-time.

I disagree because I get E-Mails in the moment they got sent and not in
"repeated intervalls". It is called IMAP IDLE and keeps a permanent
connection to the server to accomplish this.

> What version do you use? If you build the master branch of our
> repository or if you subscribe to the public beta channel on the Play
> Store you'll have access to 6.0.0-beta version that makes the background
> service notification more discreet.

It is the Playstore version. I won't use the beta. It is just OK like
now, but could be better.

>
> Cheers,

**Comment by conracer** [comment]
Oh wait, I have a Jabber-Client, that doesn't have such a button implemented and seems to run in the background, from the beginning.

**Comment by Viish** [comment]
No, you don't understand.

On many devices apps can't run for long in background (see https://dontkillmyapp.com/ for example), and even if they did the DOZE mode of Android will prevent them from accessing the network, so there's no possibility to keep a socket connected to a server unless you use a foreground service (as we do) but for that the app MUST display a notification. 
If the notification channel used for it is disabled, there's no notification and thus the foreground service isn't started by Android, so it doesn't work.

The only way to have real-time notifications in an app is push notifications. If your email app (and the same is true for your Jabber client) does notify you in real-time, they are using push notifications (IMAP IDLE can't work without a foreground service as I explained above). We are working on a push gateway solution for third party SIP servers but it's not ready yet.

Cheers,

**Comment by conracer** [comment]
I don't understand where this is going. I knew already the thing with the permanent notification. But I am sure, that if I disable the notification it is just hidden. I think it was also FairEmail which claims not to use Firebase because of data protection. And it points out on first start to disable battery optimizations in system settings; from my experience this setting is in fact critical. Nevertheless I have to watch out a bit further because of the dontkillmyapp-site. But from my feeling my number set in Linphone is reachable even after the "3 days".

**Comment by conracer** [comment]
I have to add, that I just noticed, that FairEmail didn't start at boottime. I had to launch the app to get the service running. Maybe this is a singular case, but normally I hadn't to do this.

**Comment by conracer** [comment]
With current version (also new UI...) I don't have to start Linphone manually any more after booting Android. The initial problem therefore seems to be fixed. Or maybe the root cause was an Android-System-Update on my side?!

**Comment by Viish** [comment]
Hi @conracer,

6.0 release doesn't do anything new. If both "start at boot" and "keep app alive using a service" are enabled, it starts the app using a foreground service with a permanent notification.
What has changed is the notification channel ID used for this long running notification that you may had disable before.

Cheers,
