### ISSUE TITLE
How do I turn off the "beep beep" ringtone after a call terminate?

### ISSUE THREAD

**Issue by ax3726** [BelledonneCommunications/linphone-android#2235]
Hello!

How do I turn off the "beep beep" ringtone after a call terminate?

linphone version is 5.0.0

**Comment by Viish** [comment]
Hi @ax3726,

You can call `core.setTone(ToneID.CallEnd, null)`.

Cheers,

**Comment by ax3726** [comment]
The second input parameter of the core.setTone function audiofile is NonNull, I tried "LinphoneManager.getCore().setTone(ToneID.CallEnd,"") ", still can't solve  the "beep beep" ringtone after a call terminate

**Comment by ax3726** [comment]
![image](https://github.com/user-attachments/assets/d7c6acfb-d056-4f7a-8ff2-c9b584ffb6a3)

**Comment by ax3726** [comment]
> Hi @ax3726,
> 
> You can call `core.setTone(ToneID.CallEnd, null)`.
> 
> Cheers,
The second input parameter of the core.setTone function audiofile is NonNull, I tried "LinphoneManager.getCore().setTone(ToneID.CallEnd,"") ", still can't solve the "beep beep" ringtone after a call terminate

**Comment by Viish** [comment]
I just tried it with `core.setTone(ToneID.CallEnd, "")` and it works fine.
Make sure you call it right after Core is created.

**Comment by ax3726** [comment]
> I just tried it with `core.setTone(ToneID.CallEnd, "")` and it works fine. Make sure you call it right after Core is created.

![image](https://github.com/user-attachments/assets/c119f937-632e-455c-a417-ec0ebfe94044)
It still doesn't take effect after I set it, the code is as follows, is the timing of my setting incorrect?

**Comment by Viish** [comment]
Seems fine to me. Maybe it has been fixed in 5.4 SDK (the one I use).

**Comment by ax3726** [comment]
> 我觉得没问题。也许这个问题已经在 5.4 SDK（我使用的版本）中修复了。

I have to use SDK 5.0.0 now, is there any way to help me solve this?

**Comment by Viish** [comment]
We don't support 5.0 SDK, please update.
