### ISSUE TITLE
Native call puts the current call on pause

### ISSUE THREAD

**Issue by basulle** [BelledonneCommunications/linphone-android#2237]
Hi, @Viish 

When receiving a native call over the current SIP call, the sip call automatically putted on pause.
Is that handled on your side? If yes, is there a way to edit that (at least put the call on hold only when the native call is answer);

Best wishes!

**Comment by Viish** [comment]
Hi @basulle,

Yes this is done by our SDK automatically when the audio focus is lost (following Android's guidelines).
You can disable that behavior using the following config property but I don't recommend it:
```
[audio]
android_pause_calls_when_audio_focus_lost=0
```

Cheers,

**Comment by basulle** [comment]
@Viish Hi

I want to ask why you don't recommend it. Our users really want to remove that, but we care of what problems this can produce. Maybe some real cases of issues which you faced so you can share.

Thanks!

**Comment by Viish** [comment]
Here's the [official doc](https://developer.android.com/media/optimize/audio-focus#existing_audio_focus_behaviors):
```
Mute current audio playback for incoming phone calls

Some apps don't behave properly and continue playing audio during phone calls. This situation forces the user to find and mute or quit the offending app in order to hear their call. To prevent this, the system can mute audio from other apps while there is an incoming call. The system invokes this feature when an a incoming phone call is received and an app meets these conditions:

    The app has either the AudioAttributes.USAGE_MEDIA or AudioAttributes.USAGE_GAME usage attribute.
    The app successfully requested audio focus (any focus gain) and is playing audio.

If an app continues playing during the call, its playback is muted until the call ends. However, if an app starts playing during the call, that player is not muted on the assumption that the user started playback intentionally.
```

A problem might be that if you don't pause a VoIP call when a GSM one arrives and the user answers the GSM call, then the VoIP & GSM call will be able to hear other...

**Comment by basulle** [comment]
@Viish We have wrote a handler for that case via TelephonyManager, so when you pickup a native call, all VOIP calls turns to pause. Idk if that enough to cover this case :)

Thank you by the way!
