### ISSUE TITLE
Does Android LinPhone support multi-person video calls, and how do I turn it on? 

### ISSUE THREAD

**Issue by ax3726** [BelledonneCommunications/linphone-android#2238]
Hello!

Does Android LinPhone support multi-person video calls, and how do I turn it on? Please guide me

**Comment by Viish** [comment]
Hi @ax3726,

Yes it does, but you need to have configured a video conference server factory URI in your account params.
You can test it by creating sip.linphone.org accounts (it's free).

Cheers,

**Comment by ax3726** [comment]
> 你好@ax3726，
> 
> 是的，但您需要在账户参数中配置视频会议服务器工厂 URI。 您可以通过创建 sip.linphone.org 账户（免费）进行测试。
> 
> 干杯，


Tried version 5.3 as well, same issue
