### ISSUE TITLE
Time format of conversations in 6.0

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#2240]
Hi!

1. **Describe the bug** (mandatory)

In master (6.0-beta), when looking at the Conversations list, each conversation shows the time of the last message in the top right.  It's format is HHhMM though rather than a more familiar HH:MM.  Although perhaps this is locale specific.  At least in North America, and IMHO, HH:MM is more familiar as a particular timestamp and HHhMM is more typical of denoting "time since".  I.e. 10h53 means 10 hours and 53 minutes ago, not 53 minutes past 10 o'clock.

As an aside, what does the yellow lock icon (unlocked on all of my conversations which are all SIP SIMPLE SMS) on the right of a conversation mean?

**Comment by Viish** [comment]
Hi @brianjmurrell,

Currently time format depends on whether your device uses 12/24h format.
For areas using the 24h format it will be using the 'h' separator, for 12h format the ':' (and the AM/PM of course).

The open lock icon means the chat room isn't encrypted (expected for SIP SIMPLE).
If the chat room uses end-to-end encryption the lock is hidden.

Cheers,

**Comment by brianjmurrell** [comment]
Ahhh.  I guess this is also something that is locale specific.  Here (again in North America) 24h format is still typically HH:SS with HH ranging from 0-23.

Interesting to know about the lock icon.  Thanks!

**Comment by Viish** [comment]
I've found a better (it would seem) way to compute time labels according to locale, I've merged it into master branch with commit ID ed1cf58f.

**Comment by brianjmurrell** [comment]
> ed1cf58f

I guess that must be a commit in some other repo as that commit is a 404 here.

**Comment by Viish** [comment]
Indeed for some reason the mirroring didn't trigger...

**Comment by Viish** [comment]
It's now available on Github as well.

**Comment by brianjmurrell** [comment]
Yes, seems much better now.
