### ISSUE TITLE
Dear Linphone Development Team

### ISSUE THREAD

**Issue by Mahe2027** [BelledonneCommunications/linphone-android#2241]
Hi,

I am currently working on customizing the Linphone app for a project that requires tailored configurations beyond the standard provisioning parameters. I would like to understand the best practices and recommended methods for integrating custom parameters into the remote provisioning process.

Specifically, I am interested in:

    Adding Custom Parameters:
        How can I include custom parameters in the XML configuration file used for remote provisioning?
        Are there any specific naming conventions or structures I should follow to ensure compatibility with the Linphone provisioning parser?

    Extracting Custom Parameters in the App:
        Once the custom parameters are included in the provisioning file and downloaded by the Linphone client, what steps should I take to extract these parameters within the app?
        Is there existing functionality within the Linphone SDK to facilitate the extraction of non-standard provisioning parameters, or would this require modification to the source code?

    Best Practices:
        Are there any best practices or potential pitfalls in implementing custom parameter handling in Linphone that I should be aware of?
        Could you provide any examples or documentation that might assist in implementing this functionality?

I appreciate any guidance or resources you could provide that would assist in the successful integration of these custom parameters into our Linphone deployment.

Thank you for your assistance.

Regards
Mahee

**Comment by Viish** [comment]
Hi @Mahe2027,

You can set whater section and/or param name & value in your remote provisioning file, and then simply access those values through [Config](https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Config.html) object.

You have many examples in our app's CorePreferences class.

Cheers,
