### ISSUE TITLE
What is the latest version of the Linphone SDK?

### ISSUE THREAD

**Issue by fazilmuammar** [BelledonneCommunications/linphone-android#2244]
Hi I want to update sdk linphone. What is the latest version of the Linphone SDK? and where can i download new sdk for linphone? because for now i downloaded in here https://download.linphone.org/releases/maven_repository/org/linphone/linphone-sdk-android/

Thank you

**Comment by Viish** [comment]
Hi @fazilmuammar,

As you can see by clicking on the link the latest released version is 5.3.80 and the latest dev version is 5.4.0-alpha.364

Cheers,
