### ISSUE TITLE
[feauture request] allow backup using SeedVault

### ISSUE THREAD

**Issue by AnthillSudoku** [BelledonneCommunications/linphone-android#2245]
Hi,
it would be nice to

allow backup using SeedVault, which is always encrypted and so it will not be an issue for sensitive data (username, password)

 - Device: samung a52q
 - OS: eOS 2.3 (LineageOS fork)
 - Version of the App 5.2.5
 - Version of the SDK 5.3.47
 - Where you did get it from: F-Droid

**Comment by Viish** [comment]
Hi @AnthillSudoku,

It should work with 6.0.0 version (currently available on the Play Store beta channel) from our master branch.

Cheers,
