### ISSUE TITLE
Capture push token from device and include it in sip header

### ISSUE THREAD

**Issue by chillcollex** [BelledonneCommunications/linphone-android#2246]
Hi,

I've successfully obtained the device token from the logcat, and push notifications are working perfectly. Now, I'd like to capture the push token and include it in the SIP header (I'm using Asterisk Server). Is there a workaround for this?

Found similar issue here but the code has moved to sdk : 
https://github.com/BelledonneCommunications/linphone-android/issues/690

**Comment by Viish** [comment]
Hi @chillcollex,

You can use this method: https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Core.html#getPushNotificationConfig()

Cheers,

**Comment by chillcollex** [comment]
Hi @Viish , I’m wondering how calls work after I’ve killed the app, considering I’m using my own push certificate and Asterisk server. I also noticed that the app continues to run as a background service even after it’s killed. Are there any related documents or closed issues I can check out myself? Thank you for the replies



Found similar issues here
https://github.com/BelledonneCommunications/linphone-android/issues/2136
https://github.com/BelledonneCommunications/linphone-android/issues/1754

**Comment by Viish** [comment]
Hi @chillcollex,

You can disable the background service in advanced settings.
Once app is killed, you can try to call yourself (or send a message). If you receive it, then push are working.

Cheers,

**Comment by chillcollex** [comment]
Yes, @Viish , the push is working fine. However, how do I reconnect the call if the app is being killed? (send push after the call initiate or before the call initiate? ) It's not necessary to include the call ID in the push payload, right? Also, how long does the background service stay active if enabled? Is it permanent?

**Comment by Viish** [comment]
Hi @chillcollex,

Yes background service is permanent (at least we try) as it is the fallback mode for when push aren't available to be reachable at all times.
When your device will receive the push, Linphone will start and REGISTER to your Asterix. To be able to receive the call your SIP proxy has to fork the call to the newly registered device (it's called late-forking in our Flexisip, I don't know for Asterix).

Cheers,

**Comment by chillcollex** [comment]
Hi @Viish 
i have added this setting into both linphonerc_default and linphonerc_factory, but doesnt seem to work, any step i missed? 
I checked on the logcat, the push is working just that dosnt trigger the register event.
I've monitored on the sip server as well, no register event received.

I can add an push listener into core and trigger refreshRegisters() as another method right? If so which file should i edit?  

[Proxy_config_0]
force_register_on_push=1

Thank you for the replies

**Comment by Viish** [comment]
Hi @chillcollex,

`force_register_on_push=1` is the right way.
Could you attach logs please?

**Comment by chillcollex** [comment]
[linphone-push.txt](https://github.com/user-attachments/files/16991863/linphone-push.txt)
@Viish

**Comment by chillcollex** [comment]
@Viish here's the log
![image](https://github.com/user-attachments/assets/3a69eb69-c1b1-48a8-899c-4d08c4c64a7b)

**Comment by Viish** [comment]
Hi,

Maybe it's the capital "P" as the expected value is "proxy_config_0".
Maybe the way you set it is ignored, and you should do it in code after the Core is started.

Cheers,

**Comment by chillcollex** [comment]
Hi, I've solved it, thank you so much for your help.

Cheers
