### ISSUE TITLE
Place a call while some incoming call is ringing

### ISSUE THREAD

**Issue by basulle** [BelledonneCommunications/linphone-android#2247]
Hello, @Viish , I hope you are doing well.

Question, is it possible to place a call while you have an active incoming call ringing without declining or answering it?

Facing this issue while trying to do that: linphone_core_invite_address_with_params(): sound are locked by another call and they cannot be freed. Call attempt is rejected.

Using org.linphone.no-video:linphone-sdk-android:5.3.74

Thank you!

**Comment by Viish** [comment]
HI @basulle,

No, I don't think this is possible.

Cheers,
