### ISSUE TITLE
Displaying All Contacts from LDAP/CardDAV Server by Default

### ISSUE THREAD

**Issue by chillcollex** [BelledonneCommunications/linphone-android#2248]
Hi,
Is there a way to display all contacts retrieved from the LDAP/CardDAV server by default? I noticed that the contacts only appear when I enter search criteria. Even when I tick the filters "see SIP contacts" or "see all," nothing happens—it only shows the contacts stored on the phone. Thanks in advance for your help!

Cheers.

**Comment by chillcollex** [comment]
Hi @Viish 

just found a trick to show contacts list by default in LDAP.

min_chars=0

Cheers,

**Comment by chillcollex** [comment]
HI @Viish 
I found out i cant really remove account if it's registered through remote provisioning, once i delete the account and relaunch the app, it will auto register back, any idea? Here is my xml config. Thanks in advance for your help!

![image](https://github.com/user-attachments/assets/757251da-fcd8-4750-895c-39d8ea5fd9ca)

**Comment by Viish** [comment]
Hi @chillcollex,

Your remote provisioning isn't transient (it's set to 0 in above picture), so it will be fetched each time your app starts, adding back the account each time.
Set it to 1 to only fetch it and apply it once.

Cheers,
