### ISSUE TITLE
error after changing package name

### ISSUE THREAD

**Issue by chillcollex** [BelledonneCommunications/linphone-android#2250]
Hi, @Viish ,

sorry to bother you again, I followed the docs and changed the packageName value, and got this error, looks like the docs outdated? any idea? 

Activity class {org.linphone/org.linphone.ui.main.MainActivity} does not exist

related issue: 
https://github.com/BelledonneCommunications/linphone-android/issues/2060

**Comment by Viish** [comment]
Hi @chillcollex,

Where do you have this error message ?

**Comment by chillcollex** [comment]
Hi @Viish 

the error comes from here, the build is success just that it cant start the MainAcitivity
all i did was changing the packageName in build.gradle.kts and run the app. Tried clean and rebuild the project, not work.
(Checked google-services.json as well, the issue is not from there)

![image](https://github.com/user-attachments/assets/0449a7ed-7213-457e-9f39-d429b6b3a5fe)

**Comment by Viish** [comment]
Whats version do you use? I can't reproduce your issue.

**Comment by chillcollex** [comment]
master branch version 6.0.0

**Comment by chillcollex** [comment]
@Viish 
I got this new error after pulled and changed the packageName (latest master branch)

The application could not be installed: INSTALL_BASELINE_PROFILE_FAILED Installation failed due to: 'Baseline profile did not install: Error: Package not found: org.linphone ' List of apks: [0] 'C:\Users\Hp\Desktop\linphone-android\linphone-android-5.3\linphone-android\app\build\intermediates\apk\release\linphone-android-release-6.0.0-alpha.1333+0e451dcc8.apk'

**Comment by chillcollex** [comment]
@Viish 
fyi, I didnt not run linphone-sdk in my local, does it matter?

**Comment by Viish** [comment]
No, you shouldn't need to build the SDK yourself.

Are you trying to install the apk directly on your windows computer (emulator maybe?) or from a windows computer to a real device?
Make sure you haven't made any change to the project except for the package name variable.

**Comment by chillcollex** [comment]
from a windows computer to a real device. just made change on packageName variable only

**Comment by chillcollex** [comment]
It's weird, the issue gone after i upgrade the AGP to version 6, clean and rebuild the project.
