### ISSUE TITLE
Force all outbound calls through the default SIP gateway

### ISSUE THREAD

**Issue by prjcarr** [BelledonneCommunications/linphone-android#2251]
Hi,

Is it possible to force all outbound calls through the default domain/SIP gateway?

Currently if I dial a number manually, the correct gateway is used, however if I am returning a missed call Linphone uses the "from" address to return the call. 

Example

SIP address configured as sip:10102256@sip.provider.com
Missed call from 04123456789@103.152.36.21
Calling this back from this missed call list dials 04123456789@103.152.36.21

Expected behavior

Calling any outbound number should replace the domain/IP with @sip.provider.com, in this case it should call 04123456789@sip.provider.com instead of 04123456789@103.152.36.21

I tried with Zoiper and Microsip and they both handle this correctly, as above. Am I missing a setting with Linphone?

Thanks

**Comment by prjcarr** [comment]
Thanks @Viish 

> That being said, have you toggled ON the "outbound proxy" account setting?

Yes, unfortunately it makes no difference. 

As I don't have any control of this with my provider, I am keen to change the behaviour in Linphone.

Any pointers on where I would change this in code? I could probably fumble my way through it. I just want to use my default sip domain for all outgoing calls.

**Comment by Viish** [comment]
If you want to hack your way out of it, I suggest you do it here: https://gitlab.linphone.org/BC/public/linphone-android/-/blob/master/app/src/main/java/org/linphone/core/CoreContext.kt#L628

**Comment by T8868** [comment]
@Viish I was searching through the posts try to find a solution for the same issue. It would be a very useful function, to have a toggle somewhere to force all outbound calls going through the sip default domain. 
For the ones using third party SIP account, it would makes so much sense. I'm currently returning calls by re-typing the phone number again manually.
