### ISSUE TITLE
linphone 6 - remember input type selection (feature request)

### ISSUE THREAD

**Issue by corobin** [BelledonneCommunications/linphone-android#2253]
Hello,

1. **Describe the feature request** (mandatory)

On the make a new call page (and also new chat page? i will only refer to new call page here), there is a keyboard type selection, either the regular keyboard or a numpad keyboard. the numpad can be triggered by the button at the right of the input field (red circle in screenshot).

however, next time the make a call page is opened, it reverts to the regular full keyboard by default.

contrast: in v5, the default input is the numpad.

request: remember the input keyboard type when it is toggled, so that the make a new call page uses the previously selected keyboard type by default instead of always defaulting to the full standard keyboard

2. **To Reproduce** (mandatory)

on main page (showing call logs), press the orange phone+ button at bottom right corner

on new call page, click numpad toggle at right of input field

make a call or not

exit 

navigate back to the new call page

actual behaviour: input keyboard is standard keyboard again

3. **Expected behavior** (mandatory)

input keyboard should be numpad

4. **Please complete the following information** (mandatory)

 - Device: OnePlus Nord N10 5G
 - OS: Android 11
 - Version of the App/SDK: see screenshot
 - Where you did got it from: Play Store
 - Please tell us if your Android is a Lineage OS or another variant: no

7. **Screenshots** (optionnal)

new call page, toggle button circled in red
![Screenshot_20240926-210117](https://github.com/user-attachments/assets/284863fb-dc41-41ec-9a37-6ed5f2cb825d)

version info
![Screenshot_20240926-210101](https://github.com/user-attachments/assets/3024f989-33f7-4249-8b6d-e8b721a13ae0)

**Comment by Viish** [comment]
Hi @corobin,

The digits keypad isn't a keyboard layout, it's a custom view that we show instead of the keyboard.
When you open the view, if you click in the text field it will open the classic keyboard, if you click on the keypad option it will open the keypad, so you have a way to open the one you want in one click.

You have a "hidden" setting named `automaticallyShowDialpad` in `CorePreferences` to have the keypad automatically appear when the view is opened.

Cheers,

**Comment by corobin** [comment]
thanks for the explanation, a hidden option suits me just fine. world you mind explaining how to edit that? i see that linphone 6 has a button for showing the config file but i didn't see a way to edit it in the app. do i need to use something external to edit it?

**Comment by Viish** [comment]
You can either modify the setting default value and rebuild the app or use the remote provisioning to change the value (see https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Remote%20Provisioning/)

**Comment by corobin** [comment]
Hey thanks for the explanation. I will look into it

Given that Linphone 6 has added a viewer for the config file, would you be open to, at some point, adding rudimentary editing ability in-app? Even just something as simple as allowing arbitrary text editing in the config file viewer and a button to save the change would suffice, anyone wanting more functionality can continue to use those other methods you referred to.

If this is something that may potentially be considered in the future, i'm happy to make a new thread for it to track the request.

**Comment by Viish** [comment]
> Given that Linphone 6 has added a viewer for the config file, would you be open to, at some point, adding rudimentary editing ability in-app?

No, this is not currently planned.

**Comment by corobin** [comment]
> You have a "hidden" setting named `automaticallyShowDialpad` in `CorePreferences` to have the keypad automatically appear when the view is opened.

Hey @Viish, sorry to keep bothering you, i'm hoping to get your help on this:

i have now tried remote provisioning, it looks straightforward enough, i have two questions:

1. just to confirm my understanding: in linphone 6 there's a place to paste a link and download+apply a remote provisioning file. it only needs to be downloaded and applied once, not every time the app is launched, correct? I made an XML file and put the link in and pressed download+apply, and it said applied successfully. then if i don't touch that link, every time the app re-launches it gives another successfully applied message. once i clear the link field, it no longer says applied successfully. but the added preference still appears in the linphonerc config file shown in the app. so it seems like i only need to apply it once, and it will persist, and i do not need to constantly have a file hosted somewhere in order to keep the applied settings. just want to confirm my understanding.

2. I made an XML file based on what you wrote and now i can see in the config that there is an entry for this:

```
[CorePreferences]
automaticallyShowDialpad=1
```

however, when i open the dialing page, the numpad does not pop up automatically. nor when i press the input text box. the default phone keyboard still pops up when i focus on the input box.

did i do the config incorrectly?

happy to generate a log if this is a bug.

thanks!

**Comment by Viish** [comment]
Hi @corobin,

You can make your provisioning "transient" (meaning it will be only applied once) by setting the following in it:
```
<section name="misc">
<entry name="transient_provisioning">1</entry>
</section>
```
(it's in the documentation available [here](https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Remote%20Provisioning/) FYI)

Regarding the setting itself, you have put it in a `[CorePreferences]` section instead of `[ui]` (CorePreferences is merely the name of the class that holds the settings in the android app).

Cheers,

**Comment by corobin** [comment]
> You can make your provisioning "transient" (meaning it will be only applied once) by setting the following in it:

ah, so the default is apply-once-and-it-stays 👍

> Regarding the setting itself, you have put it in a `[CorePreferences]` section instead of `[ui]` (CorePreferences is merely the name of the class that holds the settings in the android app).

ooh, thanks for clarifying!

unfortunately, i've applied the setting in the `[ui]` section and it still isn't automatically opening :(

i can see in the `ui` section that it now shows:

```
[ui]
	enable_secure_mode=0
	automaticallyShowDialpad=1
```

is this what it's  supposed to say?

thanks again!

**Comment by corobin** [comment]
> the configuration key is `automatically_show_dialpad`

that worked! thanks for all your patience. 

I will also peruse the source you linked. is there documentation of these preferences or the source is the place to go?

Thanks again for your help!!

**Comment by Viish** [comment]
> is there documentation of these preferences or the source is the place to go?

No there is no complete doc with all supported settings. In the app they all are in CorePreferences class, but in the SDK they are scattered across all source files...

It's on our roadmap to improve that.

**Comment by corobin** [comment]
thank you very much @Viish
