### ISSUE TITLE
linphone 6 - ability to remove/clear suggestions (feature request)

### ISSUE THREAD

**Issue by corobin** [BelledonneCommunications/linphone-android#2254]
Greetings,

1. **Describe the feature request** (mandatory)

On the new call page (and also new chat page? i will only refer to new call page here), there does not seem to be a way to remove one or clear all of the suggested contacts.

request: a way to remove or clear suggestion

3. **To Reproduce** (mandatory)

on main page (showing call logs), press the orange phone+ button at bottom right corner

on new call page, try to delete a suggestion

actual behaviour: unable to remove a suggestion

4. **Expected behavior** (mandatory)

some way to remove a suggestion

5. **Please complete the following information** (mandatory)

 - Device: OnePlus Nord N10 5G
 - OS: Android 11
 - Version of the App/SDK: see screenshot
 - Where you did got it from: Play Store
 - Please tell us if your Android is a Lineage OS or another variant: no

7. **Screenshots** (optionnal)

new call page, suggestions circled in red
![Screenshot_20240926-210117](https://github.com/user-attachments/assets/31945c80-ec3b-40c9-bbe0-ab6636d65ccb)

version info
![Screenshot_20240926-210101](https://github.com/user-attachments/assets/3024f989-33f7-4249-8b6d-e8b721a13ae0)

**Comment by Viish** [comment]
Hi @corobin,

The suggestions list comes from our SDK that collects all SIP addresses not attached to a contact in the call logs & chat databases.
The only way to clear them is to remove the call log / conversation with that SIP address.

Cheers,

**Comment by corobin** [comment]
I figured out why I thought the suggestions couldn't be removed.

if i clear the call log and then immediately go to new call page, the suggestion is still there

however if i clear the call log, exit the app, then reopen the app and go to the new call page, there are no suggestions there

this seems like a trivial issue that does not need to be addressed.

thanks.
