### ISSUE TITLE
Crashlytics not capturing native crashes

### ISSUE THREAD

**Issue by ParticleCore** [BelledonneCommunications/linphone-android#2261]
Hi there,

Today I had a few issues with handling native crashes that have been sorted out, but later on I noticed that my Crashlytics was not capturing any of those crashes.

I looked at the documentation, but I could not find anything explaining how I could fix this limitation, and I also searched the repository, but found nothing.

Is there any configuration that can be done in order to allow Crashlytics to capture Linphone's library native crashes?

**Comment by Viish** [comment]
Hi @ParticleCore,

To have native stack traces on Crashlytics you have to upload our SDK debug libs to their server.
The easiest way for that is to build our SDK yourself, this way you have them ready in the build folder.

Once you have them, simply give the path to Crashlytics plugin in your gradle build file:
https://gitlab.linphone.org/BC/public/linphone-android/-/blob/master/app/build.gradle.kts#L158
And don't forget to call the upload symbols gradle task:
https://gitlab.linphone.org/BC/public/linphone-android/-/blob/master/app/build.gradle.kts#L260

Cheers,

**Comment by ParticleCore** [comment]
Ah ok, that sounds way more easy than what I was understanding initially, thanks!
