### ISSUE TITLE
Is Linphone provide Android auto(Car play) support ?

### ISSUE THREAD

**Issue by pp1137** [BelledonneCommunications/linphone-android#2268]
Hello Team,

I've downloaded latest android linphone app from play store but its not supported in android auto car play

Thank you in advance for filling bug reports properly!
<img width="800" alt="Screenshot 2024-10-22 at 4 33 46 PM" src="https://github.com/user-attachments/assets/e790c5aa-47f3-4321-b939-f22a69d20a69">

its showing like above screenshot so i need to integrate car play support like default dialer so how to add it in linphone based app ?

**Comment by Viish** [comment]
Hi @pp1137,

Linphone does support Android Auto but for chat messages notification only.
Call support is done in 6.0 version to come, but Google is currently not allowing apps to use it for now unless accepted in their beta program (in which we haven't been accepted yet).

Cheers,

**Comment by pp1137** [comment]
> Hi @pp1137,
> 
> Linphone does support Android Auto but for chat messages notification only. Call support is done in 6.0 version to come, but Google is currently not allowing apps to use it for now unless accepted in their beta program (in which we haven't been accepted yet).
> 
> Cheers,

Hello @Viish 

Is it updated in 6.0.0-alpha Tags code ? in Github

**Comment by Viish** [comment]
Hi @pp1137,

Yes it is in 6.0.0-alpha, but it's currently commented out because Google doesn't approve apps on the Play Store using those features for now. You can revert the commit ID e5c7fa07cc61657108d2b58de9a0c3979f95e57c to enable them back.
It only works on the desktop head unit simulator.

Cheers.
