### ISSUE TITLE
Can't build. Overload resolution ambiguity. All these functions match.

### ISSUE THREAD

**Issue by Cersin** [BelledonneCommunications/linphone-android#2270]
Can't build app, error in NotificationBroadcastReceiver.kt file

<html>Overload resolution ambiguity:<br/>public abstract fun searchChatRoom(params: ChatRoomParams?, localAddr: Address?, remoteAddr: Address?, participants: Array&lt;(out) Address!&gt;?): ChatRoom? defined in org.linphone.core.Core<br/>public abstract fun searchChatRoom(params: ConferenceParams?, localAddr: Address?, remoteAddr: Address?, participants: Array&lt;(out) Address!&gt;?): ChatRoom? defined in org.linphone.core.Core

**Comment by Viish** [comment]
Hi @Cersin,

It's because your SDK isn't up-to-date enough.
You need 5.4.0-alpha.430 or newer.

Cheers,

**Comment by Cersin** [comment]
> Hi @Cersin,
> 
> It's because your SDK isn't up-to-date enough. You need 5.4.0-alpha.430 or newer.
> 
> Cheers,

It's not the case
Linphone SDK used is 5.4.0-alpha.431+8a55cb96

Still
> Task :app:compileDebugKotlin FAILED
e: file:///Users/szymon/Documents/GitHub/linphone-android/app/src/main/java/org/linphone/notifications/NotificationBroadcastReceiver.kt:113:79 Cannot infer type for this parameter. Please specify it explicitly.
e: file:///Users/szymon/Documents/GitHub/linphone-android/app/src/main/java/org/linphone/notifications/NotificationBroadcastReceiver.kt:122:32 Unresolved reference 'createMessageFromUtf8'.
e: file:///Users/szymon/Documents/GitHub/linphone-android/app/src/main/java/org/linphone/notifications/NotificationBroadcastReceiver.kt:129:22 Unresolved reference 'markAsRead'.
e: file:///Users/szymon/Documents/GitHub/linphone-android/app/src/main/java/org/linphone/notifications/NotificationBroadcastReceiver.kt:130:79 Argument type mismatch: actual type is 'kotlin.Any', but 'org.linphone.core.ChatRoom' was expected.
e: file:///Users/szymon/Documents/GitHub/linphone-android/app/src/main/java/org/linphone/ui/main/chat/viewmodel/AbstractConversationViewModel.kt:156:21 Cannot infer type for this parameter. Please specify it explicitly.
e: file:///Users/szymon/Documents/GitHub/linphone-android/app/src/main/java/org/linphone/ui/main/chat/viewmodel/AbstractConversationViewModel.kt:167:36 Assignment type mismatch: actual type is 'kotlin.Any', but 'org.linphone.core.ChatRoom' was expected

**Comment by Viish** [comment]
How are you building? I don't have the issue, and neither does our CI.

**Comment by Cersin** [comment]
Either building debug on android studio emulator or building apk from build > build apk option

**Comment by Viish** [comment]
Also your line numbers do not correspond to anything in the latest version of the master branch. Would you mind pulling latest changes?

**Comment by Cersin** [comment]
> Also your line numbers do not correspond to anything in the latest version of the master branch. Would you mind pulling latest changes?

dunno what i should do, fresh clone of this repo on windows and same error

**Comment by Viish** [comment]
Try to clean your gradle cache, do a project clean/rebuild, etc...

There is no reason for the `Cannot infer type for this parameter. Please specify it explicitly.` as both core.searchChatRoom() methods return the same object type: a `ChatRoom`.

**Comment by Cersin** [comment]
Already tried clearing everything, issue still appears. Maybe there is a correlation with new version of android studio or something like that?

**Comment by Viish** [comment]
What version of Android Studio are you using? I'm on Ladybug.

**Comment by Cersin** [comment]
> Could you send the whole build logs please?

Its working now after your last commit

**Comment by Cersin** [comment]
Thanks

**Comment by chillcollex** [comment]
hi @Viish ,
i got the exact same error here. Any idea to solve this? the project was alright last time when i build.

Android Studio Meerkat | 2024.3.1 Patch 1
Build #AI-243.24978.46.2431.13208083, built on March 13, 2025
Runtime version: 21.0.5+-13047016-b750.29 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
openjdk-24
adroid gradle plugin version 8.9.1

![Image](https://github.com/user-attachments/assets/c7bab814-5867-444b-abb8-f0c4cd2de485)

**Comment by chillcollex** [comment]
nevermind, solved it
