### ISSUE TITLE
Whether the stream direction is controllable?

### ISSUE THREAD

**Issue by LoyaiHai** [BelledonneCommunications/linphone-android#2272]
Hi
@Viish 
When linhpone calls the other party: Connected->StreamsRunning, when the connection is successful, the stream starts to run, I want to know, is there any way to prohibit the receiving of the other party's stream, and also want to know what interface to prohibit its own stream to send to the other party?
Thank you
cheers

**Comment by Viish** [comment]
Hi @LoyaiHai,

You can use https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/CallParams.html#setAudioDirection(org.linphone.core.MediaDirection) and https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/CallParams.html#setVideoDirection(org.linphone.core.MediaDirection).

Cheers,

**Comment by LoyaiHai** [comment]
Hi
@Viish
I use this method: setAudioDirection(), but when I set it to SendOnly, the other party hears music. Why?
Is this related to the fact that I am using the linphone sdk version 5.2.99?
Thank you 
cheers

**Comment by Viish** [comment]
You hear the music because setting the audio to SendOnly is what we use to set a call on hold.
You can disable the hold music by setting a path to an empty file or a file that doesn't exists to disable it.

**Comment by LoyaiHai** [comment]
Hi
@Viish 
i got it,but I would like to know if the path is set to an empty file or non-existent file to disable hold music, is this modified by setting the configuration of core or by setting the file properties in assets?
Thank you 
cheers

**Comment by Viish** [comment]
You can do it both ways.

**Comment by LoyaiHai** [comment]
Hi
@Viish 
i got it,I'll try it now.I'll give you feedback later if I have any questions
Thank you 
cheers

**Comment by LoyaiHai** [comment]
Hi
@Viish 
I looked at the file in assets: assistant_default_values, assistant_linphone_default_values, linphonerc_default, linphonerc_factory, I don't see the path of relevant voice and music files in it. May I ask which configuration file and field should I modify in assets if I want to set the effect I want?
Thank you
cheers

**Comment by Viish** [comment]
Hi @LoyaiHai,

It's
```
[sound]
hold_music=
```

Cheers,

**Comment by LoyaiHai** [comment]
Hi
@Viish 
Whether this property is in the linphoneerc_factory, if so, my configuration here is:
[sound]
#remove this property for any application that is not Linphone public version itself
ec_calibrator_cool_tones=1
disable_ringing=1
If I don't have hold_music, does that default to empty, or does it default to a path that you wrote internally?
![QQ截图20241104172403](https://github.com/user-attachments/assets/18cb3405-db28-4f59-9650-bc8da9b45778)

Thank you 
cheers

**Comment by Viish** [comment]
If not set in the config file, it will default to our bundled music.
