### ISSUE TITLE
How to customize rtp push content ?

### ISSUE THREAD

**Issue by Heawill** [BelledonneCommunications/linphone-android#2273]
How to use the audio source during the call is an mp3 file, not a microphone.

**Comment by Viish** [comment]
Hi @Heawill,

Use https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Core.html#setUseFiles(boolean) and https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Core.html#setPlayFile(java.lang.String)

Next time please open such question in linphone-sdk repository, it has nothing to do with our Android app.

Cheers,

**Comment by Heawill** [comment]
> Hi @Heawill,
> 
> Use https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Core.html#setUseFiles(boolean) and https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Core.html#setPlayFile(java.lang.String)
> 
> Next time please open such question in linphone-sdk repository, it has nothing to do with our Android app.
> 
> Cheers,

Thanks
