### ISSUE TITLE
Question: How does one send arbitrary audio stream during call?

### ISSUE THREAD

**Issue by NuarkNoir** [BelledonneCommunications/linphone-android#2274]
Hello!

I am writing informator which will call numbers from pre-determined list and play user-recorded audio file (stored in for of raw PCM stream). 

Tried setting Core::useFiles to true and Core::playFile to file path to be played, but file is not played to the called device.
```kotlin
// sipEngine is getter for application-held object of type Core
sipEngine.useFiles = true
sipEngine.playFile = recording.recordingPath
```

Also call is configured as SendOnly:
```kotlin
val callAddr: Address = Factory.instance().createAddress(callAddrStr)!!
val callParams: CallParams = sipEngine.createCallParams(null)!!.apply {
  isVideoEnabled = false
  isAudioEnabled = true
  audioDirection = MediaDirection.SendOnly
}

val call = sipEngine.inviteAddressWithParams(callAddr, callParams)
```

Before linphone I tried using PortSIP SDK and it had function `startPlayingFileToRemote` (but PortSIP SDK is paid-only sollution, so no go).

Am I doing it wrong? I have dound no exaples of such use case.
Used liblinphone version is 5.3.94.

**Comment by Viish** [comment]
Hi @NuarkNoir,

In https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/Core.html#setPlayFile(java.lang.String) documentation it says the file has to be a wav, so raw PCM probably won't work.
If you still have issues, please attach debug logs.

Please open issues in linphone-sdk repository, this one is for issues related to our app only.

Cheers,

**Comment by NuarkNoir** [comment]
Okay, I resolved my issue by moving `sipEngine.useFiles = true` just before sending invite.

Thanks!
