### ISSUE TITLE
Linphone Android missing dialer letters

### ISSUE THREAD

**Issue by eshattow** [BelledonneCommunications/linphone-android#2276]
Hi, I was using Linphone today and the DTMF dial pad letters are missing. This made it difficult to navigate an automated assistant directory which asks to dial the first three letters of a person's last name for whom I am trying to look up their office extension.

The use of DTMF in-call is already two levels deep which is difficult and wastes my time everyday when accessing Voicemail, and now the letters are removed? I am not a genius that can remember these old standards without looking. Please make this easier and not so much more difficult. Thank you.

**Comment by Viish** [comment]
Hi @eshattow,

Fixed in commit id `31b9836c` on master branch.

Cheers,
