### ISSUE TITLE
No PQC ZRTP option upon building the APK.

### ISSUE THREAD

**Issue by prakharmishra03** [BelledonneCommunications/linphone-android#2277]
Hi, I have been trying to build the latest linphone 6.0 apk.
I wanted PQC ZRTP for encryption as it works fine on the older version (the play store version).

However, on building the apk and running it there is only ZRTP and not PQC ZRTP.
How do I enable it?
I have added the following lines to the linphone_rcdefault and linphone_rcfactory files:-
media_encryption=zrtp
enable_pqc=1
zrtp_key_agreements_suites=MS_ZRTP_KEY_AGREEMENT_K255_KYB512

under [sip] and also under [pqc] separately.

Still it gives only ZRTP option and not PQC ZRTP. Please help me enable PQC ZRTP!

**Comment by Viish** [comment]
Hi @prakharmishra03,

You have to build your own SDK and enable the post quantum encryption in cmake options.

Cheers,
