### ISSUE TITLE
Streaming call to a silent listener possible?

### ISSUE THREAD

**Issue by AlBundy33** [BelledonneCommunications/linphone-android#2280]
Hi, this is just a question and not a bug report.

I have a new colleague that will assist my team - we're calling customers everyday and now I'm looking for a solution that the new colleague can listen silently to the calls (preferably only if we invite him or share an url or something like this with him).

Has anyone and idea how we can achieve this?

Thanks for any ideas and hints

**Comment by Viish** [comment]
Hi @AlBundy33,

The only way I see to do that is for you to create a "local conference" which means having two calls merged locally on your device, bridging the two calls and yourself together.
This way your colleague will be able to listen to the call (he will have to mute it's microphone if he doesn't want to participate).

If that's not the kind of solution you seek, you can contact our sales department through our webiste contact page and we'll send you a quote to develop a mechanism that suits you better.

Cheers,
