### ISSUE TITLE
Toggle Camera button is disabled

### ISSUE THREAD

**Issue by dominhquang39** [BelledonneCommunications/linphone-android#2281]
Hi, i've tried running the tutorial for android kotlin. I found that i can't make a video call, only audio call works. When i clicked the toggle video button in outgoing call app, nothing happened and the toggle camera is always disabled. i use 1 emulator (with camera permission) for incoming call and another real physics phone for outgoing call.  when i see the log i got this: 
"Unable to find stream at index 1 because media description has 1 streams"
"Unable to find media transport capabilities for stream 1"
"Unable to find configurations for stream 0"

How can i enable the video call?
Thank you in advance for filling bug reports properly!

**Comment by Viish** [comment]
Hi @dominhquang39,

Are you talking about our tutorials repository on our gitlab?

Cheers;

**Comment by dominhquang39** [comment]
Yes, it's the tutorial for android/kotlin.
Thank you!

**Comment by Viish** [comment]
Sadly our tutorials are now a bit old, and we currently don't have the time to update them.

I recommend you to check the linphone-android app source code instead.

**Comment by dominhquang39** [comment]
Thank you!
