### ISSUE TITLE
Connecting a server using DNS SRV giving No SRV record found

### ISSUE THREAD

**Issue by mdhanif-simformsolutions** [BelledonneCommunications/linphone-android#2282]
Hello, I am trying to connect a server which has SRV records with it. But I keep getting No SRV records found in the logs and I am unable to connect on any server.

1. **Describe the bug** (mandatory)

Eg :- 
I have a url such as `abc.net` and with that SRV attached is `abc1.net` 

Now when I connect on abc.net it works as normal connection, but if I put `abc.net` in maintenance mode theoretically it should have a SRV lookup and  get `abc1.net` and should try to connect there but instead it just throw an error that connection failed and from the logs I can see is that SRV lookup failed.

I have enable SRV lookup in the code using :- 
`core.enableDnsSrv(true)`

I also tried setting DNS URL's using :- 
`core.setDnsServers()`

Both of this didn't work.

**Expected behavior**

- Should be able to connect on any other server which is available and found in the SRV records.

4. **Please complete the following information** (mandatory)

 - Device: Pixek 6
 - OS: Android 14
 - Version of the SDK :- 5.0.71

**Comment by Viish** [comment]
Hi @mdhanif-simformsolutions,

> Version of the SDK :- 5.0.71

This is way to old, we no longer support this SDK.
Please update to latest 5.3 or 5.4.0-alpha.

**Comment by Viish** [comment]
If issue persists, please attach logs.

Cheers,

**Comment by mdhanif-simformsolutions** [comment]
Hello, 
I did upgrade the SDK Version to `5.3.90`.

I find the issue where I was not able to find `SRV` records and that was because of wrong auth Info i had set now that's updated. 
Basically i was having my `realm` included in the `domain` because of which it was giving no `SRV` records. 

But I am still not able to connect to any other server if one of my server is down, seems like `Linphone` doesn't switch to any other server and I am missing some configurations to do that. 

I did set DnsSrvEnabled in core using :- `core.isDnsSrvEnabled = true` is there any other setting I am missing ?

**Comment by Viish** [comment]
> But I am still not able to connect to any other server if one of my server is down, seems like Linphone doesn't switch to any other server and I am missing some configurations to do that.

Please open an issue in linphone-sdk repository for that.
