### ISSUE TITLE
Linphone + Android on S24 Ultra Not Working

### ISSUE THREAD

**Issue by zlehnherr1** [BelledonneCommunications/linphone-android#2287]
Setting up Linphone (freshly installed from Play Store) with a voip.ms line doesn't seem to work.

I signed in using a sub account. (acct#_name)
Entered in the password
Used chicago4.voip.ms for server
TLS for transport

From there it showed the dialer and connected in the upper left.

I followed the guide found easily online and changed the following.

Expire - 300
Media Encryption - SRTP
Media Encryption mandatory - enabled
Use random ports - disabled
SIP port to use - 5081

When I try to place a call, I get a network/service error. The same settings worked on my S22 Ultra and currently work on my Pixel 9 Pro running GOS.
I tried on another person's S24 Ultra and same issue.

**Comment by zlehnherr1** [comment]
I can still attach logs if needed, however I believe I found the issue is in advanced > device name, my phone name was Z's S24 Ultra. removing the ' from the name, force stopping the app, and re-opening fixed the issue. Samsung by default names the device by doing "[first name]'s [device name]".

**Comment by Viish** [comment]
Thanks for the information!
I'll make sure we have a proper workaround for that in the 6.0.0 release to come.

**Comment by Viish** [comment]
Fixed it in master branch commit ID 49d83817, thanks a lot!

**Comment by zlehnherr1** [comment]
> Fixed it in master branch commit ID 49d83817, thanks a lot!

Glad to help!
