### ISSUE TITLE
Missed (or declined) calls not showing in call log

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#2288]
Hi @Viish.

1. **Describe the bug** (mandatory)
When a call is sent to linphone-android and it starts ringing, if the caller hangs up or callee declines the call in linphone-android, the missed call does not show up in the call log.

2. **To Reproduce** (mandatory)
1. Place call to linphone-android
2. On linphone-android, decline the call
3. Open the call history
4. Observe that the declined (or missed) call is not in the call history

5. **Expected behavior** (mandatory)
Call should show in the call history

6. **Please complete the following information** (mandatory)
 - Device: OnePlus 6
 - OS: [e.g. Android 14]
 - Version of the App: 6.0.0-alpha (8d78f2b69)
 - Version of the SDK:  5.4.0-alpha.476+0fde0abe
 - Where you did got it from: local build
 - Please tell us if your Android is a Lineage OS or another variant: Lineage OS

7. **SDK logs** (mandatory)
http://brian.interlinx.bc.ca/linphone-calls-missing-history.txt

**Comment by Viish** [comment]
Hi @brianjmurrell,

It's the same issue as you have/had for the chat: the headers do not contains your local account but your username @ your ip:
```
INVITE sip:my_sip_account@[2001:123:4567:0:c252:250b:d86e:a4]:38282;transport=tcp;pn-prid==[redacted];pn-provider=fcm;pn-param==[redacted];pn-silent=1;pn-timeout=0 SIP/2.0
From: "[redacted]" <sip:[redacted]@pbx.example.com>;tag=f186a8e1-26b1-4993-b1d7-e6d025afd766
To: <sip:my_sip_account@[2001:123:4567:0:c252:250b:d86e:a4];pn-prid==[redacted];pn-provider=fcm;pn-param==[redacted];pn-silent=1;pn-timeout=0>
```

You should have instead something like this:
```
INVITE sip:my_sip_account@pbx.example.com
From:  "[redacted]" <sip:[redacted]@pbx.example.com>
To:  <sip:my_sip_account@pbx.example.com>
```

Cheers,

**Comment by brianjmurrell** [comment]
But this same format `INVITE` headers works as expected on 5.2.5.

**Comment by brianjmurrell** [comment]
Ultimately this is a UX regression that you are going to get complaints about in just the same way as you have fielded complaints from a number of people about how this affects chat rooms.

**Comment by brianjmurrell** [comment]
To clarify, if just the `To:` header in the `INVITE` were formatted as `To:  <sip:my_sip_account@pbx.example.com>` does the ip address as the destination in `sip:my_sip_account@[2001:123:4567:0:c252:250b:d86e:a4]:38282` in the `INVITE` matter or will it also need to converted to `pbx.example.com`?

**Comment by Viish** [comment]
> To clarify, if just the To: header in the INVITE were formatted as To:  <sip:my_sip_account@pbx.example.com>

Yes TO header should be enough for a proper matching.

> Ultimately this is a UX regression that you are going to get complaints about in just the same way as you have fielded complaints from a number of people about how this affects chat rooms.

This is the same feature as for the chat rooms, it just wasn't properly done in our app.

**Comment by brianjmurrell** [comment]
So, according to Asterisk folks, what is being sent in the `To:` header in an `INVITE` is what Linphone is sending in the `Contact:` header of it's `REGISTER` and it seems that it's Linphone that is using an IP address rather than the domain from the account name:

```
REGISTER sip:example.com SIP/2.0
Via: SIP/2.0/TCP [2001:123:4567:0:59e0:7399:7811:1b27]:46574;alias;branch=z9hG4bK.ZLtnbDuf2;rport
From: "[redacted]" <sip:my_sip_account@example.com>;tag=fifqEDgvY
To: "[redacted]" <sip:my_sip_account@example.com>
CSeq: 20 REGISTER
Call-ID: m0fTjMP5Jv
Max-Forwards: 70
Supported: replaces, outbound, gruu, path, record-aware
Accept: application/sdp
Accept: text/plain
Accept: application/vnd.gsma.rcs-ft-http+xml
Contact: "[redacted]" <sip:my_sip_account@[2001:123:4567:0:59e0:7399:7811:1b27]:46574;pn-prid==[redacted];pn-provider=fcm;pn-param==[redacted];pn-silent=1;pn-timeout=0;transport=tcp>;+sip.instance="<urn:uuid:312eea04-3559-00ae-9920-aac6701fd648>";+org.linphone.specs="conference/2.0,ephemeral/1.1,groupchat/1.2,lime"
Expires: 31536000
User-Agent: MyLinphoneAndroid/6.0.0 (Redmi Note 4) LinphoneSDK/5.4.0-alpha.476+0fde0abe (pipelines/86360)
Content-Length: 0
```

So, if Linphone would instead send the account as it knows it as such:

```
Contact: "[redacted]" <sip:my_sip_account@example.com:46574;pn-prid==[redacted];pn-provider=fcm;pn-param==[redacted];pn-silent=1;pn-timeout=0;transport=tcp>;+sip.instance="<urn:uuid:312eea04-3559-00ae-9920-aac6701fd648>";+org.linphone.specs="conference/2.0,ephemeral/1.1,groupchat/1.2,lime"
```

Then Asterisk would send the correct account back in the `To:` of the `INVITE`.

**Comment by Viish** [comment]
@brianjmurrell,

No, it won't work. Contact value must be a SIP URI that identifies this device specifically as well as giving the proxy the means to reach it, aka the IP:port at which the socket listens.
This informations is then used by proxy server to route INVITE for example.

However when a device registers, it sets the FROM to the SIP identity (sip:username@domain.tld).
When someone calls you, unless they directly call your IP:port, they call your SIP identity by setting it in the TO header. Your proxy shouldn't modify that header and leave the SIP identity instead of replacing it by the Contact address.

**Comment by brianjmurrell** [comment]
I don't think Asterisk is considered a SIP Proxy.  It's not proxying calls.  It's receiving a call and then making a call and then bridging them.  Caller picks up their phone and dials an extension, 2018, say:

```
INVITE sip:2018@example.com SIP/2.0
Via: SIP/2.0/TCP [2001:123:4567:0:1032:3f83:54e9:639d]:45634;branch=z9hG4bK.EIjjoC5y4;rport
From: "[redacted]" <sip:my_sip_account3@example.com>;tag=44zg1tnW2
To: sip:2018@example.com
CSeq: 21 INVITE
Call-ID: Yxz1XZjwdu
Max-Forwards: 70
Supported: replaces, outbound, gruu, path, record-aware
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO, PRACK, UPDATE
Content-Type: application/sdp
Content-Length: 1322
Contact: <sip:my_sip_account3@[2001:123:4567:0:1032:3f83:54e9:639d]:45634;pn-prid==[redacted];pn-provider=fcm;pn-param==[redacted];pn-silent=1;pn-timeout=0;transport=tcp>;expires=31535999;+org.linphone.specs="conference/1.0,ephemeral/1.1,groupchat/1.2,lime"
User-Agent: MyLinphoneAndroid/5.2.5.23.1+b9d8a5d24 (FRD-L04) LinphoneSDK/5.3.47 (tags/5.3.47^0)
Authorization: :[redacted]
```

Asterisk receives that call and looks up what phone 2018 maps to and then places a call to that phone:

```
INVITE sip:my_sip_account2@[2001:123:4567:0:6589:8e62:cb10:5e4e]:48954;transport=tcp;pn-prid==[redacted];pn-provider=fcm;pn-param==[redacted];pn-silent=1;pn-timeout=0 SIP/2.0
Via: SIP/2.0/TCP [2001:123:4567::2]:5060;rport;branch=z9hG4bKPje9ed6aad-0b48-4c75-bfdf-827797867b41;alias
From: "[redacted]" <sip:2003@pbx.example.com>;tag=308fb44c-0ea8-4050-9b62-a0ba4717a4ea
To: <sip:my_sip_account2@[2001:123:4567:0:6589:8e62:cb10:5e4e];pn-prid==[redacted];pn-provider=fcm;pn-param==[redacted];pn-silent=1;pn-timeout=0>
Contact: <sip:asterisk@[2001:123:4567::2]:5060;transport=TCP>
Call-ID: a81392bc-2975-4fbd-847c-d542af61bf77
CSeq: 1721 INVITE
Allow: OPTIONS, REGISTER, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, MESSAGE, INFO, REFER
Supported: 100rel, timer, replaces, norefersub, histinfo
Session-Expires: 1800
Min-SE: 90
Max-Forwards: 70
User-Agent: Asterisk PBX 18.26.0
Content-Type: application/sdp
Content-Length:  1625
```

and then bridges the two calls together.  So the caller does not call the callee directly.  As such, there is no header _rewriting_ going on.  Each call is distinct and the outgoing call (the second `INVITE` above) has it's headers created from scratch.

**Comment by brianjmurrell** [comment]
Couldn't you use something else to match incoming calls to accounts, such as the `pn-prid` in the `To:`, where the SIP account doesn't match?

**Comment by Viish** [comment]
> Couldn't you use something else to match incoming calls to accounts, such as the pn-prid in the To:, where the SIP account doesn't match?

That wouldn't work as every account on the same app on a mobile device will have the same push notification information (prid, token, etc...).

**Comment by brianjmurrell** [comment]
> That wouldn't work as every account on the same app on a mobile device will have the same push notification information (prid, token, etc...).

Is that a requirement or just an implementation detail in this project?  IOW, could they be different, they just aren't at this point?  It does seem like a leak of information between account providers.  I haven't really considered what the security implications are if any.

But ultimately, given this broader issue, between you and the Asterisk developers both digging your heels in and insisting that your (respective) way is the right way, you are making linphone-android quite unusable for anyone using Asterisk.  Asterisk is certainly no niche product/project.

Just saying…

**Comment by Viish** [comment]
> Is that a requirement or just an implementation detail in this project? IOW, could they be different, they just aren't at this point?

It's the way Android & iOS work: an app is embedding at most a single client push certificate, so all accounts inside that app will have the same push information.

Regarding Asterisk, [we have this conversation since 2019](https://issues-archive.asterisk.org/ASTERISK-28513) and the solution remains the same, it seems there is a configuration item inside Asterisk to change the TO header: https://community.asterisk.org/t/manipulate-to-header-for-inbound-calls-on-chan-sip/95128/5

**Comment by brianjmurrell** [comment]
> Regarding Asterisk, [we have this conversation since 2019](https://issues-archive.asterisk.org/ASTERISK-28513)

That issue and solution only applies to SIP `MESSAGE`s, not `INVITE`s.

> it seems there is a configuration item inside Asterisk to change the TO header: https://community.asterisk.org/t/manipulate-to-header-for-inbound-calls-on-chan-sip/95128/5

That only works for the [deprecated and to be removed in Asterisk 21 `chan_sip`](https://www.asterisk.org/asterisk-21-module-removal-chan_sip/), one of the two SIP stacks in Asterisk.  The other, (and only in Asterisk 21 and onward) is `chan_pjsip`.  Here is the discussion of being able to do the same with it: https://community.asterisk.org/t/setting-address-or-domain-at-least-of-to-header-in-invite/105621.  Feel free to comment there if you wish.

As you can see, they feel they are doing the right thing with their `To:` header and have no plans to do otherwise.

**Comment by brianjmurrell** [comment]
Isn't all of this ultimately only an issue for people that register to multiple accounts?  If there is only one account, why can't it just be assumed that all calls coming in are for that one and only registered account?

What percentage of people actually use multiple accounts on an ongoing basis anyway?

Why not resolve this issue for the (vast?) majority of people -- the ones that are only using Linphone with a single account instead of breaking it for all of those people just to hold on to a principle?

**Comment by Viish** [comment]
> That issue and solution only applies to SIP MESSAGEs, not INVITEs.

This is exactly the same issue, and the solution would also be the same if they would allow it. As they already have an option to change TO header for messages, they should be able to do it for INVITEs too.

> As you can see, they feel they are doing the right thing with their To: header and have no plans to do otherwise.

That's sad. Note that this is the only software (that we know about) that is doing that...

> Isn't all of this ultimately only an issue for people that register to multiple accounts? If there is only one account, why can't it just be assumed that all calls coming in are for that one and only registered account?

Because calls that are directed to username@ip are 100% of the time (except for asterisk users) peer to peer calls, and most of the time they are spam calls issued by bots.

> Why not resolve this issue for the (vast?) majority of people -- the ones that are only using Linphone with a single account instead of breaking it for all of those people just to hold on to a principle?

The vast majority of people do not use Asterisk.

**Comment by brianjmurrell** [comment]
AFAIU, `MESSAGE` and `INVITE` are handled by different parts of the stack so the solution that was applied for `MESSAGE` is entirely separate to what would work with `INVITE`.  But I'm no Asterisk expert.

> That's sad. Note that this is the only software (that we know about) that is doing that...

Would you care to use your expertise of SIP and understanding of how Linphone applies it to try to work out a solution in the [discussion thread](https://community.asterisk.org/t/setting-address-or-domain-at-least-of-to-header-in-invite/105621)?  Surely it could only help.

> Because calls that are directed to username@ip are 100% of the time (except for asterisk users) peer to peer calls, and most of the time they are spam calls issued by bots.

Are spam/bot calls really a thing?  Are there bots that are war-dialing IP addresses on the SIP port in hopes that there is a SIP UA living there?  That's got to be a pretty low efficacy hit rate.  In any case spam/bot calls are not going to be able to supply valid push notification information on the `INVITE` so if you really did want to eliminate them you could simply refuse calls that do not provide the push metadata.

> The vast majority of people do not use Asterisk.

That's a strawman.  My statement was about the vast majority of SIP phone users only using a single account regardless of what SIP server/proxy they are connecting to.  So if the vast majority of SIP phone users are only using a single account, while it's a nice confirmation of which account the call is for by specifying username@domain, it's not really necessary and one can pretty safely (even against bots given the above explanation) assume the call is for the only account on the SIP phone.

Surely this is a win in being compatible with more SIP services without any negatives isn't it?

**Comment by brianjmurrell** [comment]
For anyone reading this issue, this has been resolved in the SDK and now calls (missed or otherwise) are logged in the 6.0 releases of linphone-android.
