### ISSUE TITLE
Stop ringing once user pressed changing volume buttons.

### ISSUE THREAD

**Issue by basulle** [BelledonneCommunications/linphone-android#2298]
@Viish Hi Sylvain, I hope you are doing well.

I need to ask you about one thing. The default behaviour of android when received a call and its ringing and once you press any of increase/decrease hardware buttons the ringtone stops playing. Currently in Linphone (SDK) when pressing these buttons it's not muting the ringtone, only changing the volume. 

Is there a way how this behaviour can be changed?

Cheers.

**Comment by Viish** [comment]
Hi @basulle,

You can set a volume buttons listener and call `linphone_core_stop_ringing` to stop the ringtone from playing.

Cheers,

**Comment by basulle** [comment]
Hi @Viish 
The problem here is that android requires an Activity to listen to buttons presses events. I am not sure if it's possible to achieve this behaviour when the app is in the background or totally terminated.

Maybe you have some ideas?

Thanks!

**Comment by Viish** [comment]
Hi,

I don't know as we do not use that method.
We use the notification channel directly to play the ringtone, so the behavior you describe is automatically handled by the OS.

Cheers,

**Comment by basulle** [comment]
If you receive a native call in Android it will terminate the ringtone once you press any of the volume buttons. In Linphone, it's increasing / decreasing the sound, not terminating the ringtone permanently. Some other VOIP applications respects that, such as Telegram. This differences confusing some users.

It would be nice if we can find a solution for this.

Cheers.

**Comment by Viish** [comment]
As I said, in linphone-android app we don't have this issue because we do not rely on our SDK to play the ringtone.

**Comment by basulle** [comment]
@Viish Hi, I hope you are good.

I have successfully implemented what we talked about to stop device ringing. Now there is another thing.
Is there a way to stop playing tones in a runtime? Talking about CallWaiting tone. Tried to pass null to setTone for CallWaiting in a runtime, but it was not doing anything. 

Maybe you have in plans to add something like stopTone as stopRinging?

Thank you!
