### ISSUE TITLE
Flexisip question

### ISSUE THREAD

**Issue by shixinglingguihua** [BelledonneCommunications/linphone-android#23]
**# **## hello,
I'm a novice.I had compiled Linphone-android project,
But it default connect to free sip "sip.linphone.org" .
I want to deploy an sip servcie at LAN, no relyon free service "sip.linphone.org".
Could I deploy  the Flexisip instance at LAN as an  sip service****

**Comment by DatBewar** [comment]
Hello,
Yes you can deploy your own instance of Flexisip on your own network.
If you want to connect on your server use assistant "Use SIP Account" and set your server informations.

**Comment by shixinglingguihua** [comment]
thank you sir  =^=
