### ISSUE TITLE
Green video screen on CPU ArmV8 

### ISSUE THREAD

**Issue by hieunc278** [BelledonneCommunications/linphone-android#230]
Dear Linphoner,

When I run test application of Linphone on Android device has CPU is Arm v8, I'm only see green background of remote video, in particular, I tested on Lenovo S1a40 phone. 

Could you show me why I met that error ? please see attachment for more information.

Best regards,

![img_1902](https://user-images.githubusercontent.com/37529941/37581675-7e0d9dc6-2b41-11e8-848f-81e9ccc2315c.JPG)

**Comment by arvinxian** [comment]
hi, i got the same issue, i run the old version of linphone  on the android TV box , and i found that this issue appear on the tv box  which Android version higher than 6.0. and the lower version  devices don't get this problem.

**Comment by Viish** [comment]
Which codec are you using ? Which version of the Android app ? Which display filter ?
Have you tried the latest release ?
You can also give a try to the feature/release-4.1 branch that is using a new display filter.
