### ISSUE TITLE
Liblinphone not able to parse ACK

### ISSUE THREAD

**Issue by zeeshansaiyed** [BelledonneCommunications/linphone-android#232]
We were facing an issue of one-way audio, and call disconnection after 30sec. We further found that liblinphone was not able to parse ACK and ultimately it ends up sending BYE to disconnect call. Please find the attached log for reference.

[linphone_debug_ack_log.txt](https://github.com/BelledonneCommunications/linphone-android/files/1841625/linphone_debug_ack_log.txt)

**Comment by msh-nayan** [comment]
hello @zeeshansaiyed, any solution of this ? I'm also stuck on this issue.

**Comment by Viish** [comment]
SDK issue, not Android
