### ISSUE TITLE
Linphone doesn't turn on screen when ringing

### ISSUE THREAD

**Issue by lameventanas** [BelledonneCommunications/linphone-android#24]
Running Linphone-android 3.2.4  on a Samsung Galaxy S4.

When Linphone rings, the screen in the cellphone doesn't turn on automatically (as when receiving a call from the cellphone operator), it remains dark.

**Comment by shixinglingguihua** [comment]
# **hello,
At Linphone-android initting,you could see a IO error dialog show.
It is  mean that Linphone  core can not surport this cellphone while vedio chatting**

**Comment by DatBewar** [comment]
I have try on different devices and its seem to work correctly
