### ISSUE TITLE
Error while updating submodules

### ISSUE THREAD

**Issue by AsfanUlla** [BelledonneCommunications/linphone-android#243]
fatal: clone of 'git://git.linphone.org/bv16-floatingpoint.git' into submodule path '/home/asfan/android-projects/hijacker/x/linphone-android/submodules/externals/bv16-floatingpoint' failed
Failed to clone 'submodules/externals/bv16-floatingpoint'. Retry scheduled
Cloning into '/home/asfan/android-projects/hijacker/x/linphone-android/submodules/externals/codec2'...
fatal: unable to connect to git.linphone.org:
git.linphone.org[0: 94.23.19.176]: errno=Connection timed out
git.linphone.org[1: 2001:41d0:2:14b0::2]: errno=Network is unreachable

fatal: clone of 'git://git.linphone.org/codec2' into submodule path '/home/asfan/android-projects/hijacker/x/linphone-android/submodules/externals/codec2' failed
Failed to clone 'submodules/externals/codec2'. Retry scheduled
Cloning into '/home/asfan/android-projects/hijacker/x/linphone-android/submodules/externals/ffmpeg'...
fatal: unable to connect to git.linphone.org:
git.linphone.org[0: 94.23.19.176]: errno=Connection timed out
git.linphone.org[1: 2001:41d0:2:14b0::2]: errno=Network is unreachable

fatal: clone of 'git://git.linphone.org/ffmpeg.git' into submodule path '/home/asfan/android-projects/hijacker/x/linphone-android/submodules/externals/ffmpeg' failed
Failed to clone 'submodules/externals/ffmpeg'. Retry scheduled
Cloning into '/home/asfan/android-projects/hijacker/x/linphone-android/submodules/externals/gsm'...
fatal: unable to connect to git.linphone.org:
git.linphone.org[0: 94.23.19.176]: errno=Connection timed out
git.linphone.org[1: 2001:41d0:2:14b0::2]: errno=Network is unreachable

fatal: clone of 'git://git.linphone.org/gsm.git' into submodule path '/home/asfan/android-projects/hijacker/x/linphone-android/submodules/externals/gsm' failed
Failed to clone 'submodules/externals/gsm'. Retry scheduled
Cloning into '/home/asfan/android-projects/hijacker/x/linphone-android/submodules/externals/libjpeg-turbo'...
fatal: unable to connect to git.linphone.org:
git.linphone.org[0: 94.23.19.176]: errno=Connection timed out
git.linphone.org[1: 2001:41d0:2:14b0::2]: errno=Network is unreachable

fatal: clone of 'git://git.linphone.org/libjpeg-turbo.git' into submodule path '/home/asfan/android-projects/hijacker/x/linphone-android/submodules/externals/libjpeg-turbo' failed
Failed to clone 'submodules/externals/libjpeg-turbo'. Retry scheduled
Cloning into '/home/asfan/android-projects/hijacker/x/linphone-android/submodules/externals/libupnp'...
fatal: unable to connect to git.linphone.org:
git.linphone.org[0: 94.23.19.176]: errno=Connection timed out
git.linphone.org[1: 2001:41d0:2:14b0::2]: errno=Network is unreachable

fatal: clone of 'git://git.linphone.org/libupnp.git' into submodule path '/home/asfan/android-projects/hijacker/x/linphone-android/submodules/externals/libupnp' failed
Failed to clone 'submodules/externals/libupnp'. Retry scheduled
Cloning into '/home/asfan/android-projects/hijacker/x/linphone-android/submodules/externals/libvpx'...
fatal: unable to connect to git.linphone.org:
git.linphone.org[0: 94.23.19.176]: errno=Connection timed out
git.linphone.org[1: 2001:41d0:2:14b0::2]: errno=Network is unreachable

**Comment by elangarika** [comment]
Not exactly the same problem but I get stuck when syncing the submodules...
When running:
git submodule sync && git submodule update --init --recursive
I get stuck on:
Cloning into 'submodules/bcg729'...

**Comment by bestMechanic** [comment]
I had similar issue. Try to connect from private network. Without firewall or proxy.
