### ISSUE TITLE
What is the difference between this source code and the sdk liblinphone-android-sdk.zip

### ISSUE THREAD

**Issue by regulusky** [BelledonneCommunications/linphone-android#247]
Would you mind to explain the difference between this source code and the SDK provided in the
https://www.linphone.org/technical-corner/liblinphone/downloads.

Do I also need to use ubuntu/ linux to build the SDK provided in the linphone.org?
Is it possible using windows machine on Android Studio to build app by using liplinphone SDK.

Thank you

**Comment by arifinreinaldo** [comment]
Hi, thank you for your response astuter.

Is there any example in using the linphone SDK for android studio in Windows?
I have search the tutorial in the internet unfortunately they seems to provide only for Ubuntu only
Thank you

**Comment by Viish** [comment]
Use the aar from http://linphone.org/releases/android/
