### ISSUE TITLE
Cannot Run Two Linphones with different Package Name 

### ISSUE THREAD

**Issue by Adnan-addi** [BelledonneCommunications/linphone-android#248]
hi , i have successfully compiled the linphone and changed its package name , but if than download orignal app from playstore they both get conflict and doesn't get installed . even i changed the package name and app is running. 

but it wont install the linphone from play store , can you help how to fix if i want run both linphones with different package name in one device .????

**Comment by wangpeng1** [comment]
you should modify many xml file,not only the package name

**Comment by Adnan-addi** [comment]
Can you tell which xml files are needed to be changed ? and what change do i need to make .? i edited everywhere where change package is mentioned ... kindly tell what needs to be changed in xml in order to accomplish my goal . Thanks

**Comment by syco** [comment]
There's no need to modify all org.linphone in AndroidManifest anymore.
I followed the documentation:

> You need to edit the build.gradle file:
> 
> look for the function named "getPackageName()" and change it value accordingly
> also update the values in the AndroidManifest file where the comment appears
> change the package name also in the files: res/xml/syncadapter.xml, res/xml/contacts.xml and res/values/non_localizable_custom where appears
> run again the Makefile script by calling "make"

after these steps, if you run your app with logcat you can see it crashes over "org.linphone.provider", so you need to open "src/android/org/linphone/chat/ChatEventsAdapter.java" and change it.

AFAIK this is the complete list of files to edit to run 2 instances:
> AndroidManifest.xml
> build.gradle
> res/values/non_localizable_custom.xml
> res/xml/contacts.xml
> res/xml/syncadapter.xml
> src/android/org/linphone/chat/ChatEventsAdapter.java
