### ISSUE TITLE
Must call startForeground on service

### ISSUE THREAD

**Issue by amadeu01** [BelledonneCommunications/linphone-android#255]
On Android 8, you must call startForeground until 5 seconds after call context.startForegroundService(intent);

The if before the `		if (displayServiceNotification()) {` should be related to the API, instead of related to should or not display the service notification, once the API 8 only accept the service be running in foreground.

https://github.com/BelledonneCommunications/linphone-android/blob/926712a704c30a6446c3d3b739886cc61158df3c/src/android/org/linphone/LinphoneService.java#L443

**Comment by wangpeng1** [comment]
@amadeu01  can you give your compiled version here?

**Comment by amadeu01** [comment]
@douya40 @wangpeng1 sorry, but you mean to send you the .apk app?

**Comment by Viish** [comment]
Binary app APK can be found at http://linphone.org/releases/android/
