### ISSUE TITLE
Linphone calling not working when app is cleared from recents?

### ISSUE THREAD

**Issue by Harshjain2094** [BelledonneCommunications/linphone-android#257]
Hey, I am facing an issue when I am trying to make a call when the app is in the background that is when the app is cleared from recents. Is there any way I could achieve it. As per the part of calling a user should receive a call when the app is in the foreground and also in the background.
It would be really helpful if you could suggest something I am stuck on it for days now.

Thanks in advance.

**Comment by dominic-p** [comment]
This could be related to #55.

**Comment by Viish** [comment]
There are push notifications for this. If you build the app yourself you won't get them because of the missing google-services.json file.
