### ISSUE TITLE
Application  send STUN meassage

### ISSUE THREAD

**Issue by Thucnv** [BelledonneCommunications/linphone-android#259]
Hi, I'm getting a issue with linphone
When call connected android application send message stun to server
![image](https://user-images.githubusercontent.com/20784964/39516429-26dcbd12-4e27-11e8-9cef-6d626bdd4f28.png)
 
P/s: StunServer is disabled.

Any help appreciated, thanks !

**Comment by Viish** [comment]
Disable stun at app level to prevent that.

**Comment by metallious** [comment]
Disabling stun at app level doesn't prevent that.
