### ISSUE TITLE
Implement auto answer and custom ringtones based on SIP headers

### ISSUE THREAD

**Issue by lameventanas** [BelledonneCommunications/linphone-android#26]
It would be great if Linphone used the Alert-Info and Call-Info SIP headers to implement custom ringtones and auto-answer.

I know Linphone allows auto-answer, but it's an all-or-nothing deal.

It would be better if (once the auto-answer config option is enabled), Linphone would answer the call based on this header:
`Call-Info=;answer-after=N`

Where N is the number of seconds to wait.  With N=0, there is no ring. The user can still reject the call before the timeout passes.

And Alert-Info can be used to use custom ringtones.  Unlike with Call-Info and auto-answer, it seems that there is no consensus on this header, but rfc 3261 has this example:
`Alert-Info: <http://www.example.com/sounds/moo.wav>`

**Comment by DatBewar** [comment]
Hello,
The delay for auto-anwser already exist on libLinphone but it's not yet implement to Linphone-Android.
Its a thing we can do for futur release.

For Alert-Info its a liblinphone issue, its not easy and without risky to implement new mechanism.
Best regards

**Comment by dominic-p** [comment]
+1 for custom ringtones based on Alert-Info. Does anyone know if an issue has been filed with liblinphone for this?

**Comment by DatBewar** [comment]
Auto answer with custom time have been add a little time ago

**Comment by lameventanas** [comment]
> Auto answer with custom time have been add a little time ago

Right, just not based on the SIP header.

**Comment by mightydok** [comment]
+1

**Comment by Viish** [comment]
SDK issue, not Android

**Comment by lameventanas** [comment]
> SDK issue, not Android

I think you didn't read the part that says **based on SIP headers** (eg: Alert-Info)

**Comment by Viish** [comment]
SIP headers are handled by the SDK, not the app itself.

**Comment by Viish** [comment]
Belle-sip is the parser, so no the issue should be opened in linphone

**Comment by dominic-p** [comment]
The Android app would still need to implement a UI to select custom ringtones based on the SIP headers, correct?
