### ISSUE TITLE
Do we have support of compact headers in liblinphone ?

### ISSUE THREAD

**Issue by zeeshansaiyed** [BelledonneCommunications/linphone-android#260]
Hello,

I'm using linphone android. When i subscribe for presence to my Freeswitch server in ipv6 it replies with compact headers (https://www.cs.columbia.edu/sip/compact.html).

Within my application log says "No event header in incoming SUBSCRIBE" & replies with 400 Bad Request

I found this behaviour when "Event" header is converted to "o"

I got the method called "expand_name" in message.c which was describing the compact headers mapping but i couldn't found in which conditions this is called

so my question is : Does liblinphone supports compact headers ? if yes then how to enable this functionality ?

let me attach my packet for reference.

```
NOTIFY sip:[2405:205:C92B:4DA4:CD75:7761:F807:892B]:47880;transport=udp;pb-pt=47880 SIP/2.0
Record-Route: <sip:[****:****:*:*:*:*:*:**];r2=on;lr>
Record-Route: <sip:***.***.***.***;r2=on;lr>
Via: SIP/2.0/UDP [2607:F900:1:1:0:0:0:10];branch=z9hG4bK966c.e48cd18cfad7a93f173d651fac1bb56d.0
v:SIP/2.0/UDP 10.100.147.205:5071;received=10.100.147.205;rport=5071;branch=z9hG4bK3ptDHry599DXK
Max-Forwards:70
f:sip:address@hidden;tag=0KWo7fUeCNnU
t:<sip:address@hidden>;tag=TzUqiY4Tw
i:RAi8DkMzBE
CSeq:550422005 NOTIFY
m:sip:address@hidden:5071
User-Agent:FreeSWITCH-mod_sofia/1.6.17~64bit
Supported: path, replaces
o:presence
Subscription-State:active;expires=300
c:application/pidf+xml
l:440

<?xml version="1.0" encoding="ISO-8859-1"?>
<presence xmlns='urn:ietf:params:xml:ns:pidf'
xmlns:dm='urn:ietf:params:xml:ns:pidf:data-model'
xmlns:rpid='urn:ietf:params:xml:ns:pidf:rpid'
xmlns:c='urn:ietf:params:xml:ns:pidf:cipid' entity='sip:address@hidden'>
 <tuple id='t6a5ed77e'>
  <status>
   <basic>open</basic>
  </status>
 </tuple>
 <dm:person id='p06360c4a'>
  <dm:note>Available</dm:note>
 </dm:person>
</presence>
```

Thanks in advanced, I'm looking forward to your positive response.

Thanks,
Zeeshan Saiyed

**Comment by Viish** [comment]
To my knowledge no we don't support compact headers.
