### ISSUE TITLE
Linphone Android Crash After Permission Deny in OREO 8.0 for sure ?

### ISSUE THREAD

**Issue by zeeshansaiyed** [BelledonneCommunications/linphone-android#263]
Hello Belledonne Communications,

It has been observed in Android Oreo that, 
1) allow each permission when asked.
2) Now go to settings -> Apps -> Linphone & change any permission to deny.
3) As soon as you deny go to Linphone App.

Observation : First time it works completely fine.

4) Repeat step 2) & 3) again app got crash.

I'm in such a miserable situation that it don't generates any logs in the system. Because when you deny any permission from the settings, existing Activity is reCreated() & log is not getting generated or somehow not captured.

Even I tried third party libs that capture Unhanded Exceptions. This issue is not being caught at all. That stats, there is something within native libs that's not compatible with Oreo.

**Comment by Viish** [comment]
This has been fixed.
