### ISSUE TITLE
H264 Video

### ISSUE THREAD

**Issue by KaanBoz** [BelledonneCommunications/linphone-android#264]
Hello,

I'm sorry if this is not the place for this but i'm in need of help.

I'm having the below problem

_Android NoTime app sending big size SIP INVITE packages which is more then 1500 bytes during video call. So because of package fragmentation sippy can not able send call to called side.
Action --> Kaan should update linphone SIP stack with removing unnecessary headers from SDP. I highlighted unnecessary fields of SDP in below trace. Preferred codecs for voice are PCMU,PCMA,GSM and for video H.264_

I have created the following class to set video codecs for my calls in linphone to set the codecs manually.

```
import org.linphone.core.PayloadType;

public class ComsticeH264 implements PayloadType {

    String recvFmtp;

    String sendFmtp;

    @Override
    public String getMime() {
        return "H264";
    }

    @Override
    public int getRate() {
        return 90000;
    }

    @Override
    public void setRecvFmtp(String s) {
        this.recvFmtp = s;
    }

    @Override
    public String getRecvFmtp() {
        return this.recvFmtp;
    }

    @Override
    public void setSendFmtp(String s) {
        this.sendFmtp = s;
    }

    @Override
    public String getSendFmtp() {
        return this.sendFmtp;
    }
}

```

Then i have used it like below;

```
ComsticeH264 h264 = new ComsticeH264();
PayloadType[] videoPayloads = new PayloadType[1];
videoPayloads[0] = h264;
mLinphoneCore.setVideoCodecs(videoPayloads);
```

but i'm having an error as 
java.lang.ClassCastException: com.comstice.notime.misc.ComsticeH264 cannot be cast to org.linphone.core.PayloadTypeImpl

I have tried to extend org.linphone.core.PayloadTypeImpl to get rid of the problem but Android studio gives me an error that PayloadTypeImpl is not public and i cannot extend.

Can you help me please?,
Thank you

**Comment by KaanBoz** [comment]
If anyone has the same problem i got the codes like this:

PayloadType[] videoCodecs = mLinphoneCore.getVideoCodecs();

then find H264, put it in a new array and set that. It seems to work.

**Comment by wangpeng1** [comment]
@KaanBoz   can you give more detail code? thank you

**Comment by tientham** [comment]
> @wangpeng1
> 
> PayloadType[] videoCodecs = mLinphoneCore.getVideoCodecs();
> 
> get the codecs like above, loop through it, find the h264 codec. then put it in a new array, then
> 
> mLinphoneCore.setVideoCodecs(videoCodecsNew);
> 
> you can set the new array like above.

I have 2 devices, 
My first device (android 7), videoCodecs return both VP8 and H264 codecs in the payload type list. 
My second device (android 5), videoCodecs return only VP8 codec, and it does not contain H264 in the payload type list.
Is it possible to manually create a H264 payload and add inside the payload type list?
Thanks,

**Comment by Viish** [comment]
@tientham that doesn't work like that.
A payload is available from the moment you have a decoder and an encoder for that codec.
On Android 5 there is no MediaCodec API which provides us the H264 encoder and decoder, so it is expected that you won't have a H264 payload type.

**Comment by tientham** [comment]
@Viish : Thank you for your answer. 
My problem is that my android 5 does not have video, it shows a black screen while in android 7, it is working well.
- On my android 7, I see this log:
[Linphone] Found payload H264/90000 fmtp=
- On my android 5, I see this log:
[Linphone] Found payload (null)/0 fmtp=
I have tried to check what video codecs are available on my android 5 with lc.getVideoCodecs(). The list contains only VP8 codec.
May I ask you how can I forcely set VP8 in my Android 5 device for a video call?
I have tried in several ways, for example: I add linphonerc_factory with
[video_codec_0]
mime=VP8
rate=90000
enabled=1
but it does not work.
Thank a lot.

**Comment by Viish** [comment]
You can't force VP8 if the call is incoming and the VP8 codec isn't in the SDP.
Same way, if you make an outgoing call VP8 will be in the SDP but if the remote end doesn't support it it won't work.
Best way to check if a codec is available / enabled is to go to the video settings page.

**Comment by tientham** [comment]
Hi @Viish , thank a lot for your explanation!
