### ISSUE TITLE
infamous 30 or 33 second call disconnect of incoming calls - linphone 

### ISSUE THREAD

**Issue by evuraan** [BelledonneCommunications/linphone-android#265]
Howdy!

https://community.asterisk.org/t/linphone-calls-drop-after-nearly-30-seconds/48910
https://github.com/BelledonneCommunications/linphone-android/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+30+seconds
https://lists.nongnu.org/archive/html/linphone-users/2017-01/msg00023.html

Had to leave Linphone for other S/w SIP clients  after a January 2018-ish or so update  introduced the infamous 30 second disconnect on incoming calls. I was hoping by now this gets  fixed,  unfortunately it is not, as I experienced today.  The issue still persists.  Users have reported this on many online avenues, including the Google Playstore. I have experienced firsthand these issues on Android and Iphones. 

Other sip clients can hit the ground and start running, I would love to  switch my userbase back to use linphone if this issue goes away. 

Could you please look into and do the needful? Thanks in advance.

**Comment by viet97** [comment]
having same issue here. can anyone helps ??

**Comment by viet97** [comment]
uncheck push notification will work. try it bro

**Comment by viet97** [comment]
it working for me

**Comment by leelai** [comment]
If I need notification, what should i do?

**Comment by sheepdestroyer** [comment]
From Linphone Android v4.3.1
Calling Linphone Desktop 4.2.5 

I always get disconnected after 33 seconds.
I tried to uncheck push notification but that does not help
