### ISSUE TITLE
Bluetooth on Pixel with Android P not working.

### ISSUE THREAD

**Issue by ShlomieRottenberg** [BelledonneCommunications/linphone-android#266]
I tried using a LG bluetooth device with the Linphone app on a Pixel (sailfish) with Android P. The app showed that the Bluetooth icon was selected, but the audio was coming from the earpiece. (When I downgraded to android 8.1 it worked fine)

**Comment by rolloaxel** [comment]
Hi,

I've got the same issue on Samsung S8 with the latest Android version (API 28, Android P)

**Comment by Viish** [comment]
Can you try with the beta on the store ?

**Comment by rolloaxel** [comment]
I tried between two devices with linphone from the store : 
The first device, Samsung S8 (API 28) with a bluetooth earpiece
The second device, Samsung S6 (API26) without any earpiece

When I launched the call, video, and audio was okay, but I received audio from the first device on the device speakers. I noticed a Bluetooth device to route audio to an earpiece, but when I click, some strange action appears (A Bluetooth icon on the middle top of the screen), but the audio did not route to Bluetooth...

Cdt

**Comment by Viish** [comment]
Did you try the latest release (4.0.1) or the beta (4.1) ?
You can check in the about page.

**Comment by rolloaxel** [comment]
It's the 4.0.1 released, where is located the beta on the store?

**Comment by Viish** [comment]
There should be a "Join beta" button at the bottom of the page.

**Comment by rolloaxel** [comment]
It seems to work with the beta. Just, audio route icons aren't very responsive (When I clicked, no visual action to tell the user option was checked).
Another problem detected: When I hang up, the other phone stay in communication.

**Comment by dongdongdong1** [comment]
The version is less than 4. When the Bluetooth headset is connected, the Bluetooth headset can hear when making a call. Why there is no sound when answering
