### ISSUE TITLE
A LinphoneCall in a Conference and in a "Paused" state still receive the audio stream

### ISSUE THREAD

**Issue by f-lolom** [BelledonneCommunications/linphone-android#271]
Hello,

I'm currently looking at different additionnal use cases with the conference and I'm currently facing an issue during its implementation.

In my LinphoneConference (composed by two LinphoneCall), I want to "pause" a participant without removing him from the Conference (I still want this user to appear as attached to the conference in my UI)

To achieve that, I'm using the API `LinphoneCore.pauseCall(LinphoneCall call)` on the call in the conference and I have the following result:
* The LinphoneCall is still attached to the conference (`LinphoneCall.isInConference()` returns true)
* `LinphoneCall.getState()` returns `Paused`
* On the other device,`LinphoneCall.getState()` returns `PausedByRemote`

From the API point of view, everything works as expected.
However, the other device in the state `PausedByRemote` is still receiving the audio stream from the conference, even if it is now in the paused state.
From my point of view, this is an unexpected behavior.

I have tested this on the last version available in master (73e803670ad0ac447dfbb6d00f0298e74646cbc1) and on the version tagged 3.3.2

This is probaly an issue on the linphone submodule, however I was able to test this and reproduce it only on android.

**Comment by Viish** [comment]
A PausedByRemote device will receive an audio stream but with the paused music, not the actual audio stream of the conference.
