### ISSUE TITLE
How to enable x264 on Android linphone

### ISSUE THREAD

**Issue by djkskqyr3** [BelledonneCommunications/linphone-android#276]
I am developing VOIP app for IOS/Android.
First time, I used H264 codec for video.
When I make video call, there is exist black video, as I see the log, there are many dropped packet so that first frame can not decode.
So I built IOS linphone library with x264 and it works well.
There is fast video after accept video call.
But still I can see the black screen on android because android used H264 yet.
I want to use x264 video codec on android linphone.
I used latest android linphone source code.
Here is my option.

./prepare.py -DENABLE_GPL_THIRD_PARTIES=NO  -DENABLE_NON_FREE_CODECS=ON -DENABLE_VPX=NO -DENABLE_VCARD=NO -DENABLE_DOC=NO -DENABLE_OPENH264=ON -DENABLE_X264=ON

**Comment by Viish** [comment]
X264 is deprecated, use either openH264 or mediacodec.
