### ISSUE TITLE
How to fix black screen when call is answered and loss packs on H264?

### ISSUE THREAD

**Issue by djkskqyr3** [BelledonneCommunications/linphone-android#277]
I am developing VOIP app using linphone IOS/Android library.
Basically I used OpenH264 video codec.
When call is answered, both side saw black screen.
After long time, both size can see the video each other.
When I see the log, there are many packets loss so that First frame can not be decoded.
At LinphoneCallStreamsRunning, I called FIR (linphone_call_send_vfu_request) request but not helped.
Is there any config for OpenH264 video codec?
I want to see the video as soon as accept call.
Thank you.

**Comment by jmimohsin** [comment]
Getting same error.

**Comment by azetor** [comment]
I have the same problem. Sometimes after some time the video appears and sometimes not.

**Comment by djkskqyr3** [comment]
https://stackoverflow.com/questions/50647236/how-to-fix-black-screen-when-call-is-answered-and-loss-packs-on-h264

**Comment by djkskqyr3** [comment]
I solved it myself using X264

**Comment by msh-nayan** [comment]
I'm also facing this problem. Using Linphone SDK(version 3.+). I checked Your solution on Stackoverflow. How can I change those ms2plugins.cmake, ffmpeg.cmake, CMakeLists.txt, x264.cmake, ffmpeg-priv.h ... using the SDK, I can't understand how to do those stuff. Can You please help.
