### ISSUE TITLE
Setting a custom header during ProxyConfig setting

### ISSUE THREAD

**Issue by Zlatinsz** [BelledonneCommunications/linphone-android#278]
Hello guys and gals,
I have the given problem: I am trying to REGISTER to a given VOIP server, for this I am using LinphoneProxyConfig and during the proxy config setup I pass a custom header using LinphoneProxyConfig::setCustomHeader(key, value). The problem is that I can't see the custom header anywhere in the registration request after setting it up.
A bit of help will be very appreciated.

**Comment by Viish** [comment]
SDK issue, not Android
