### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by abady711** [BelledonneCommunications/linphone-android#284]
Hi,
I followed all the steps mentioned on readme file
but I have errors when run "make", I'm using Ubuntu 18.04

====================================
loading initial cache file /home/abd/linphone-android/WORK/android-arm64//tmp/EP_linphone/EP_linphone-cache-RelWithDebInfo.cmake
-- Android: Targeting API '21' with architecture 'arm64', ABI 'arm64-v8a', and processor 'aarch64'
-- Android: Selected Clang toolchain 'aarch64-linux-android-clang' with GCC toolchain 'aarch64-linux-android-4.9'
-- The C compiler identification is Clang 6.0.2
-- The CXX compiler identification is Clang 6.0.2
-- Check for working C compiler: /home/abd/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
-- Check for working C compiler: /home/abd/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/abd/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
-- Check for working CXX compiler: /home/abd/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found XML2: /home/abd/linphone-android/liblinphone-sdk/android-arm64/include/libxml2  
-- Found XercesC: /home/abd/linphone-android/liblinphone-sdk/android-arm64/lib/libxerces-c.a (found version "3.1.4") 
-- Found LibXsd: /home/abd/linphone-android/liblinphone-sdk/android-arm64/include;/home/abd/linphone-android/liblinphone-sdk/android-arm64/include  
-- Soci found: Looking for plugins
--     * Plugin mysql not found.
--     * Plugin sqlite3 found /home/abd/linphone-android/liblinphone-sdk/android-arm64/lib/libsoci_sqlite3.a.
-- Found Soci: /home/abd/linphone-android/liblinphone-sdk/android-arm64/include  
-- Found Zlib: /home/abd/Android/Sdk/ndk-bundle/sysroot/usr/include  
-- Found Sqlite3: /home/abd/linphone-android/liblinphone-sdk/android-arm64/include  
-- Found PythonInterp: /usr/bin/python (found version "2.7.15") 
CMake Error at cmake/Tools.cmake:31 (message):
  'pystache' python module not found
Call Stack (most recent call first):
  CMakeLists.txt:178 (check_python_module)

-- Configuring incomplete, errors occurred!
See also "/home/abd/linphone-android/WORK/android-arm64/Build/linphone/CMakeFiles/CMakeOutput.log".
CMakeFiles/EP_linphone.dir/build.make:117: recipe for target '/home/abd/linphone-android/WORK/android-arm64/Stamp/EP_linphone/EP_linphone-configure' failed
make[3]: *** [/home/abd/linphone-android/WORK/android-arm64/Stamp/EP_linphone/EP_linphone-configure] Error 1
make[3]: Leaving directory '/home/abd/linphone-android/WORK/android-arm64/cmake'
CMakeFiles/Makefile2:77: recipe for target 'CMakeFiles/EP_linphone.dir/all' failed
make[2]: *** [CMakeFiles/EP_linphone.dir/all] Error 2
make[2]: Leaving directory '/home/abd/linphone-android/WORK/android-arm64/cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/abd/linphone-android/WORK/android-arm64/cmake'
Makefile:192: recipe for target 'arm64-build' failed
make: *** [arm64-build] Error 2

======================================
I already tried NDK16  & NDK17 "after your new readme update", I cannot find any solution in your website.

Please help to fix errors.

Thank you

**Comment by DatBewar** [comment]
Hello,
the answer is in the log:
'pystache' python module not found

you need to install pystache and some other python plugin to compile linphone.

Best regards

**Comment by abady711** [comment]
thank you so much, 
compiled successfully after adding missing python plugins.
