### ISSUE TITLE
Build Failing 

### ISSUE THREAD

**Issue by johnnavaj** [BelledonneCommunications/linphone-android#285]
-- 'six' python module found
-- Looking for include file libudev.h
-- Looking for include file libudev.h - not found
-- Found CpuFeatures: /home/john/John/Projects/AndroidProjects/linphone-android/liblinphone-sdk/android-arm64/lib/libcpufeatures.a  
-- Found Support: /home/john/John/Projects/AndroidProjects/linphone-android/liblinphone-sdk/android-arm64/lib/libsupport.a  
-- Performing Test SUGGEST_OVERRIDE
-- Performing Test SUGGEST_OVERRIDE - Failed
-- Found Java: /usr/bin/java (found version "1.8.0.171") found components:  Development 
-- Found Git: /usr/bin/git (found version "2.7.4") 
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Found Git: /usr/bin/git (found suitable version "2.7.4", minimum required is "1.7.1") 
-- Package file name is liblinphone-3.12.0-2403
-- Configuring done
-- Generating done
-- Build files have been written to: /home/john/John/Projects/AndroidProjects/linphone-android/WORK/android-arm64/Build/linphone
[ 98%] Forcing build for 'EP_linphone'
[ 99%] Performing build step for 'EP_linphone'
make[4]: Entering directory '/home/john/John/Projects/AndroidProjects/linphone-android/WORK/android-arm64/Build/linphone'
make[5]: Entering directory '/home/john/John/Projects/AndroidProjects/linphone-android/WORK/android-arm64/Build/linphone'
make[6]: Entering directory '/home/john/John/Projects/AndroidProjects/linphone-android/WORK/android-arm64/Build/linphone'
Scanning dependencies of target linphonej
make[6]: Leaving directory '/home/john/John/Projects/AndroidProjects/linphone-android/WORK/android-arm64/Build/linphone'
make[6]: Entering directory '/home/john/John/Projects/AndroidProjects/linphone-android/WORK/android-arm64/Build/linphone'
make[6]: *** No rule to make target '/home/john/John/Projects/AndroidProjects/linphone-android/submodules/linphone/wrappers/java/linphone-doc', needed by 'wrappers/java/src/linphone_jni.cc'.  Stop.
make[6]: Leaving directory '/home/john/John/Projects/AndroidProjects/linphone-android/WORK/android-arm64/Build/linphone'
CMakeFiles/Makefile2:153: recipe for target 'wrappers/java/CMakeFiles/linphonej.dir/all' failed
make[5]: *** [wrappers/java/CMakeFiles/linphonej.dir/all] Error 2
make[5]: Leaving directory '/home/john/John/Projects/AndroidProjects/linphone-android/WORK/android-arm64/Build/linphone'
Makefile:151: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/home/john/John/Projects/AndroidProjects/linphone-android/WORK/android-arm64/Build/linphone'
CMakeFiles/EP_linphone.dir/build.make:123: recipe for target '/home/john/John/Projects/AndroidProjects/linphone-android/WORK/android-arm64/Stamp/EP_linphone/EP_linphone-build' failed
make[3]: *** [/home/john/John/Projects/AndroidProjects/linphone-android/WORK/android-arm64/Stamp/EP_linphone/EP_linphone-build] Error 2
make[3]: Leaving directory '/home/john/John/Projects/AndroidProjects/linphone-android/WORK/android-arm64/cmake'
CMakeFiles/Makefile2:77: recipe for target 'CMakeFiles/EP_linphone.dir/all' failed
make[2]: *** [CMakeFiles/EP_linphone.dir/all] Error 2
make[2]: Leaving directory '/home/john/John/Projects/AndroidProjects/linphone-android/WORK/android-arm64/cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/john/John/Projects/AndroidProjects/linphone-android/WORK/android-arm64/cmake'
Makefile:192: recipe for target 'arm64-build' failed
make: *** [arm64-build] Error 2

**Comment by PriyankaThakkar612** [comment]
Hello,
To solve Could not find doxygen, you have to install doxygen by following command in Ubuntu:
sudo apt-get install doxygen

**Comment by johnnavaj** [comment]
Thanks Got it. There is a issue with the current gradle 3.1.0 , any idea how to downgrade this to an older version ?

**Comment by SarunyuPrasert** [comment]
I got an error too.

`-- Configuring incomplete, errors occurred!
See also "/Users/sarunyuprasert/Documents/Git_Sip_Linphone_Android/linphone-android/WORK/android-arm64/Build/linphone/CMakeFiles/CMakeOutput.log".
make[3]: *** [/Users/sarunyuprasert/Documents/Git_Sip_Linphone_Android/linphone-android/WORK/android-arm64/Stamp/EP_linphone/EP_linphone-configure] Error 1
make[2]: *** [CMakeFiles/EP_linphone.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [arm64-build] Error 2`

**Comment by PriyankaThakkar612** [comment]
@johnnavaj, 
To downgrade to an older version, change version manually in build.gradle of your project.

**Comment by johnnavaj** [comment]
@SarunyuPrasert you are likely missing one or more of these pacakges.
 1. Dot
2.Doxygen
3.pip-python
4.python-pystache
5.python-six

**Comment by SarunyuPrasert** [comment]
@johnnavaj Thank you for your advice. Now i can run command "make" but i want an SDK and i had a problem with command "make liblinphone-android-sdk" it shows me this error
"make: *** No rule to make target `liblinphone-android-sdk'.  Stop."

**Comment by johnnavaj** [comment]
@SarunyuPrasert you have moved this to a general thread so i am closing this issue
