### ISSUE TITLE
Make sdk Failed

### ISSUE THREAD

**Issue by SarunyuPrasert** [BelledonneCommunications/linphone-android#286]
After i use git to clone a project into my folder. 
I run command 
"./prepare.py -c" and "./prepare.py -DENABLE_NON_FREE_CODECS=ON -DENABLE_AMRWB=ON -DENABLE_EMBEDDED_OPENH264=ON -DENABLE_MPEG4=ON -DENABLE_BV16=ON -DENABLE_SILK=ON -DENABLE_AMRNB=ON" It's no error. 

But i want to make a sdk so i run command 
"make liblinphone-android-sdk". 
It shows me an error
"make: *** No rule to make target `liblinphone-android-sdk'.  Stop." How can i make a linphone sdk?

**Comment by johnnavaj** [comment]
@SarunyuPrasert did you do a git init and a submodule sync ?

**Comment by SarunyuPrasert** [comment]
@johnnavaj now i've got a new error after pulling that last git commit. It show me this error.

> Configure project :liblinphone-sdk
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation'.
It will be removed at the end of 2018

> Task :compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Warning: The rule `-keep public class *extends java.lang.annotation.Annotation {*;}` uses extends but actually matches implements.

> Task :validateSigningRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':validateSigningRelease'.
> Keystore file '/Users/sarunyuprasert/Documents/Git_Sip_Linphone_Android/linphone-android/""' not found for signing config 'release'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
48 actionable tasks: 28 executed, 20 up-to-date
make: *** [release] Error 1

Do you know how i can fix this

**Comment by johnnavaj** [comment]
@SarunyuPrasert which openjdk version are you using ? did you try the make on sudo ?

**Comment by SarunyuPrasert** [comment]
@johnnavaj i'm using jdk 1.8 and Yes. I've tried "sudo make liblinphone-android-sdk" but error is the same.

**Comment by johnnavaj** [comment]
@SarunyuPrasert try doing a git submodule init and submodule update and prepare the source again. can 
you tell me which branch you are using ?

**Comment by SarunyuPrasert** [comment]
@johnnavaj I'm using branch master. I delete a project and clone it again and run command "git submodule sync && git submodule update --init --recursive" following git suggestion and run command "./prepare.py -c && ./prepare.py -DENABLE_NON_FREE_CODECS=ON -DENABLE_AMRWB=ON -DENABLE_EMBEDDED_OPENH264=ON -DENABLE_MPEG4=ON -DENABLE_BV16=ON -DENABLE_SILK=ON -DENABLE_AMRNB=ON && make liblinphone-android-sdk" and the error is the same `> Task :validateSigningRelease FAILED`

**Comment by brillenheini** [comment]
I came across the same error when building tag 4.0.0 and worked around it by commenting out the release build type's signingConfig in build.gradle. It is not necessary when building the sdk's aar. This problem is new in 4.0.

**Comment by johnnavaj** [comment]
@brillenheini interesting

**Comment by SarunyuPrasert** [comment]
I can build sdk now with commenting out as @brillenheini suggestion but i don't know why i can't use any methods in sdk.

**Comment by Nik2505** [comment]
@SarunyuPrasert I am getting same release issue while **make liblinphone-android-sdk** I tried to commenting signingConfig. but then also I am getting same error.

**Comment by SarunyuPrasert** [comment]
I can use a sdk now. I'm closing this issue.

**Comment by jinyulei0710** [comment]
@SarunyuPrasert  do you know  about this issue?
-- Soci found: Looking for plugins
--     * Plugin mysql not found.
--     * Plugin sqlite3 found /Users/jinyulei/–recursive/liblinphone-sdk/android-arm64/lib/libsoci_sqlite3.so.
-- 'pystache' python module found
-- 'six' python module found
error: Cannot open file /Users/jinyulei/–recursive/WORK/android-arm64/Build/linphone/CMakeDoxyfile.tpl for writing
CMake Error at /usr/local/Cellar/cmake/3.11.4/share/cmake/Modules/FindDoxygen.cmake:665 (message):
  Unable to generate Doxyfile template: 1
Call Stack (most recent call first):
  coreapi/help/doc/doxygen/CMakeLists.txt:24 (find_package)

**Comment by SarunyuPrasert** [comment]
@jinyulei0710 Have you installed doxygen?

**Comment by jinyulei0710** [comment]
@SarunyuPrasert  I have already installed doxygen
loading initial cache file /Users/jinyulei/–recursive/WORK/android-arm64//tmp/EP_linphone/EP_linphone-cache-RelWithDebInfo.cmake
-- Soci found: Looking for plugins
--     * Plugin mysql not found.
--     * Plugin sqlite3 found /Users/jinyulei/–recursive/liblinphone-sdk/android-arm64/lib/libsoci_sqlite3.so.
-- 'pystache' python module found
-- 'six' python module found
error: Cannot open file /Users/jinyulei/–recursive/WORK/android-arm64/Build/linphone/CMakeDoxyfile.tpl for writing
CMake Error at /usr/local/Cellar/cmake/3.11.4/share/cmake/Modules/FindDoxygen.cmake:665 (message):
  Unable to generate Doxyfile template: 1
Call Stack (most recent call first):
  coreapi/help/doc/doxygen/CMakeLists.txt:24 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/jinyulei/–recursive/WORK/android-arm64/Build/linphone/CMakeFiles/CMakeOutput.log".
See also "/Users/jinyulei/–recursive/WORK/android-arm64/Build/linphone/CMakeFiles/CMakeError.log".
make[3]: *** [/Users/jinyulei/–recursive/WORK/android-arm64/Stamp/EP_linphone/EP_linphone-configure] Error 1
make[2]: *** [CMakeFiles/EP_linphone.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [arm64-build] Error 2

**Comment by shelterz** [comment]
Commenting signingConfig in bulid.gradle solve the problem when generate aar

**Comment by zartakk** [comment]
Hi   @shelterz 
I have problem with generating aar  files....  that is says could not find it .... 
  i run prepare.py successfully after it  run "MakeFile"  with make command   and in : ./gradlew assembleDebug  it fails    

following is   the error in my  **log** 

 Task :preDebugBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':debugCompileClasspath'.
> Could not find support-vector-drawable.aar (com.android.support:support-vector-drawable:27.1.1).
  Searched in the following locations:
      https://jcenter.bintray.com/com/android/support/support-vector-drawable/27.1.1/support-vector-drawable-27.1.1.aar
> Could not find livedata-core.aar (android.arch.lifecycle:livedata-core:1.1.0).
  Searched in the following locations:
      https://jcenter.bintray.com/android/arch/lifecycle/livedata-core/1.1.0/livedata-core-1.1.0.aar
> Could not find viewmodel.aar (android.arch.lifecycle:viewmodel:1.1.0).
  Searched in the following locations:
      https://jcenter.bintray.com/android/arch/lifecycle/viewmodel/1.1.0/viewmodel-1.1.0.aar
> Could not find runtime.aar (android.arch.core:runtime:1.1.0).
  Searched in the following locations:
      https://jcenter.bintray.com/android/arch/core/runtime/1.1.0/runtime-1.1.0.aar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
4 actionable tasks: 4 executed
Makefile:141: recipe for target 'generate-apk' failed
make: *** [generate-apk] Error 1



any help will appreciated.... commenting signingConfig doesn't help.... 
and I work with the version 4.0.0 linphone-android
