### ISSUE TITLE
Building an earlier version

### ISSUE THREAD

**Issue by Magus14** [BelledonneCommunications/linphone-android#295]
Hi,
Am trying to build version **3.99.1**  (**git checkout 3.99.1**) and i am getting the following error when i use 
**git submodule sync && git submodule update --init --recursive** 
fatal: reference is not a tree: 97dfa5b7af486a2730aa66ef4b2b04259c9ab21b
Unable to checkout '97dfa5b7af486a2730aa66ef4b2b04259c9ab21b' in submodule path 'submodules/externals/libxsd'

When i continue to make i get the following error 
**[ 89%] Performing configure step for 'EP_libxsd'
loading initial cache file /home/*/linphone-android/WORK/android-arm64//tmp/EP_libxsd/EP_libxsd-cache-RelWithDebInfo.cmake
CMake Error: The source directory "/home/*/linphone-android/submodules/externals/libxsd" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
CMakeFiles/EP_libxsd.dir/build.make:107: recipe for target '/home/*/linphone-android/WORK/android-arm64/Stamp/EP_libxsd/EP_libxsd-configure' failed
make[3]: *** [/home/*/linphone-android/WORK/android-arm64/Stamp/EP_libxsd/EP_libxsd-configure] Error 1
make[3]: Leaving directory '/home/*/linphone-android/WORK/android-arm64/cmake'
CMakeFiles/Makefile2:720: recipe for target 'CMakeFiles/EP_libxsd.dir/all' failed
make[2]: *** [CMakeFiles/EP_libxsd.dir/all] Error 2
make[2]: Leaving directory '/home/*/linphone-android/WORK/android-arm64/cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/*/linphone-android/WORK/android-arm64/cmake'
Makefile:205: recipe for target 'arm64-build' failed
make: *** [arm64-build] Error 2**

**Comment by BitCol** [comment]
Where you able to resolve this issue ? 
Thanks

**Comment by Magus14** [comment]
No not yet.

**Comment by Viish** [comment]
Use 4.0.1 tag or master branch.

**Comment by geoffrey-vl** [comment]
It seems libxsd's historie was rewritten during transition to gitlab...

To fix the problem first alter the url for libxsd in the .gitmodules file into `https://gitlab.linphone.org/BC/public/external/libxsd.git`. Next sync your git submodules. Next go into _submodules/external/libxsd_ folder and do `git checkout 3108405ad6edf1e98c9387348e77d2b3578a1bac`. This is the commit matching the one that got lost on git.linphone.org.
