### ISSUE TITLE
Registration i/o error on Android O 8.0.0 version

### ISSUE THREAD

**Issue by VaidyaSwanand** [BelledonneCommunications/linphone-android#297]
I am trying to do registration with source code provided in the tutorial. But In the Android O version, I am getting io Error. Is it Version specific? because other than Android O versions I am getting registration successful message. What changes are needed to make the registration successful on Android O version?

**Comment by VaidyaSwanand** [comment]
Any update on this??

**Comment by duxingzhe** [comment]
I encounter the same problem. I downgrade to version 23 and it works fine.

**Comment by duxingzhe** [comment]
The problem is that you use domain name to connect your server. Use IP address instead or change to newest liblinphone.
