### ISSUE TITLE
Is there a demo that can running fast in Android studio？

### ISSUE THREAD

**Issue by wk37** [BelledonneCommunications/linphone-android#300]
linphone is a good project! but it is not fridendly for android developers. we just want a demo which have  aar(or jar) , some activities and res, and we hope this demo  can run directly in Android studio. but now, the linphonewiki show us that we have to clone all linphone android source code,  the source code is too large( more then 1GB), and for android developers too many files we don't need and some files we actuall don't understand. This is a suggestion, I hope you can take it. thanks

**Comment by Viish** [comment]
You can download the AAR of the SDK or app's APK here http://linphone.org/releases/android/
