### ISSUE TITLE
Failed to update submodule on Jul 2's commit

### ISSUE THREAD

**Issue by zj299792458** [BelledonneCommunications/linphone-android#302]
Hi, I'm currently at commit:

commit 625fc3a697b7ff8315296d40cd92a1273bd0befa (HEAD -> master, origin/master, origin/HEAD)
Author: Erwan Croze <erwan.croze@belledonne-communications.com>
Date:   Mon Jul 2 17:17:54 2018 +0200

    Fix .gitmodules

when I tried to 'git submodule update --recursive --init', it says:

error: Server does not allow request for unadvertised object 852d23c72acd537b75e4b95af93b866925d31bda
Fetched in submodule path 'submodules/externals/openh264', but it did not contain 852d23c72acd537b75e4b95af93b866925d31bda. Direct fetching of that commit failed.

it seems the .gitmodules are not fixed 

Thank you.

**Comment by DatBewar** [comment]
Hi,
Go to 
"linphone-android/submodules/externals/openh264"
and run
"git remote set-url origin https://gitlab.linphone.org/BC/public/external/openh264.git"
It must be ok after.

**Comment by aureagle** [comment]
after you have updated the git repo,

git submodule sync

should do the trick, no need to reset/update remote url it is probably already set, just need a 'sync'ing
