### ISSUE TITLE
App crashes on LinphoneManager.java class when Launching

### ISSUE THREAD

**Issue by Nik2505** [BelledonneCommunications/linphone-android#303]
I followed process To build liblinphone for Android. After that I import linphone-android to Android studio. When I run project I am getting crash on LinphoneManager.java class 

```
private synchronized void startLibLinphone(Context c) {
		try {
			copyAssetsFromPackage();
			//traces alway start with traces enable to not missed first initialization
			**mLc = Factory.instance().createCore(mConfigFile, mLinphoneFactoryConfigFile, c);** // GETTING CRASH ON THIS LINE
			mLc.addListener(this);
			mLc.start();
			TimerTask lTask = new TimerTask() {
				@Override
				public void run() {
					LinphoneUtils.dispatchOnUIThread(new Runnable() {
						@Override
						public void run() {
							if (mLc != null) {
								mLc.iterate();
							}
						}
					});
				}
			};
			/*use schedule instead of scheduleAtFixedRate to avoid iterate from being call in burst after cpu wake up*/
			mTimer = new Timer("Linphone scheduler");
			mTimer.schedule(lTask, 0, 20);
		} catch (Exception e) {
			Log.e(e, "Cannot start linphone");
		}
	}
```

I am not getting any logs for crash.
Just getting this line in error : **07-04 12:17:55.294 29162-29162/? A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 29162 (org.linphone)**

**Comment by astuter** [comment]
I think I have the same issue. You can see the crash logs in following image: 

![crash](https://user-images.githubusercontent.com/12004314/42321247-e83668de-8075-11e8-9a08-68e9f9a312ec.png)

**Comment by Nik2505** [comment]
what will be solution?

**Comment by astuter** [comment]
I am also facing same error for release version 4.0.1
