### ISSUE TITLE
Which Linphone version is stable?

### ISSUE THREAD

**Issue by Gemberbirie** [BelledonneCommunications/linphone-android#307]
We want to employ Linphone in our organisation. However, in our testruns the application keeps crashing. Is there a setup which is stable?

**Comment by ahna92** [comment]
I'm not a linphone developer ,but i can tell you that the crashing in the application are not related to the linphone sdk , they are realted to UI 
if you want to get it to work try to register to the free sip service , it should work 
4.0.0 is kinda stable ,
4.0.1 has bugs as i have noticed specially with using other sip providers than linphone

as i said the sdk is stable and you can use it with your own UI

**Comment by Gemberbirie** [comment]
@ahna92 Thank you! We are aiming to use it with our own SIP server. I will try 4.0.0 and go downwards untill I find the most stable version 👍 .
