### ISSUE TITLE
Multicast call hangs up after 30 seconds

### ISSUE THREAD

**Issue by DjToMeK27** [BelledonneCommunications/linphone-android#311]
Hi!
I tried making multicast to work on 3.3.2 version and I don't know if this is a bug in linphone.
(If I make a normal call with this disabled below it works normally)

What I did was enabled, on Linphone service initialization
```
LinphoneManager.getLc().enableAudioMulticast(true);
LinphoneManager.getLc().setAudioMulticastAddr("224.0.0.100");
```
I make a call from
.4.12(IP) 102(PBX number)  to .4.26(IP) 116(PBX number) device
(On 102 I am calling SIP number 116)

Call then works normally, and if I check in Wireshark I see that
4.12 - Sending data over UDP to 224.0.0.100
4.26 - Starts sending STUN Binding Request after 15 seconds, and is sending it once each second till the call stops

This is all that is going on, and then after 30 seconds call just ends.

On receiving end, on 4.26, I also tried adding
`params.enableAudioMulticast(true);`

but nothing changes

Questions:
1. Why does this call drop after 30 seconds? Do I have to enable something else, because I don't see this anywhere in documentation
2. How can I make all devices, which are listening on 224.0.0.100 to receive the call? If I make a call from 102 - 116, how can for example device, which is registered on 120, has multicast enabled, also receive this call? Should I make a call somehow differently?

**Comment by Viish** [comment]
SDK issue, not Android
