### ISSUE TITLE
Error while receiving call in android sdk of Linphone.

### ISSUE THREAD

**Issue by Harshjain2094** [BelledonneCommunications/linphone-android#316]
I have been implementing VoIP Calling feature in an android app for a while now, most of the work is done but now what the problem arises is that when a user makes a call to another user through the app, most of the time same person is receiving the call from where it was initialized. For better understanding let's take up a simple example, There are two users with usernames **ABC** and **CBA**, when ABC makes a call to CBA it is done properly but when the case is reversed i.e when CBA makes a call to ABC, in the incoming method of the Linphone it receives the remote username as CBA only, which means that CBA is getting calls to itself which is not even the worst case scenario. Kindly suggest a way how to solve this problem and also if I m applying a method differently.

I have used the Linphone Calling SDK for Android completely not even changed the methods from it.
Kindly help with this been stuck for days now.

**Comment by ahna92** [comment]
if you post the log it would help to solve the problem .

**Comment by Harshjain2094** [comment]
Actually there is no Log for this, but ill show you this by the method which gives me this problem.
```
   private void onIncomingReceived2(LinphoneCall call) {
        android.util.Log.d("ServiceStarted",  "   VAlues "+  call.getRemoteAddress + call.getUserData());
        if (!name.equals(call.getRemoteAddress)) {
            Intent intent = new Intent(getApplicationContext(), TwilioIncomingCallActivity.class);
            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            startActivity(intent);
        }

    }
```
In the above code there is a LinphoneCall variable named call. When I use the default method I get the name from call.getRemoteAddress in the I ma getting the same name by which I have dialed the call to.

**Comment by ahna92** [comment]
linphone sdk logs every action it takes , you can activate the logging as following 


    Factory.instance().setDebugMode(true,  "debug_tag");
            Factory.instance().enableLogCollection(LogCollectionState.EnabledWithoutPreviousLogHandler);
            Factory.instance().getLoggingService().setListener(new LoggingServiceListener() {
                @Override
                public void onLogMessageWritten(LoggingService logService, String domain, LogLevel lev, String message) {
                    switch (lev) {
                        case Debug:
                            android.util.Log.d(domain, message);
                            break;
                        case Message:
                            android.util.Log.i(domain, message);
                            break;
                        case Warning:
                            android.util.Log.w(domain, message);
                            break;
                        case Error:
                            android.util.Log.e(domain, message);
                            break;
                        case Fatal:
                        default:
                            android.util.Log.wtf(domain, message);
                            break;
                    }
                }
            });
        }

And i don't think there is a problem , as i understated  `onIncomingReceived2` method is called on the receiver side of the call , and you are calling `getRemoteAddress` which will return the person is dialing from the other side of the call .

**Comment by Harshjain2094** [comment]
Thanks for the Logging this I'll surely use it. The method should be called on the receiver side but when I call it it is received on the same side I don't know why it is calling on the same side. On more thing, we have implemented the linphone server and made our own voip server which generates userid, deviceId, and callFlowId, is it because of something while using this. I m sorry if it sounds messy but I am totally confused about what's happening.

**Comment by ahna92** [comment]
if that is the case then in the logs the sip packets should tell is that party A is calling party A 
then this is a client side problem most likely because of wrong account address when calling `		core.inviteAddressWithParams(lAddress, params);
`
but if the logs shows that A is calling B then the problem is server side related

**Comment by Harshjain2094** [comment]
I m making a call from this method.
` LinphoneManager.getInstance().newOutgoingCall(to, null);`

So when I receive the call on the same device where it could be the problem. My app side or the server side?

**Comment by ahna92** [comment]
dear without the logs there is no way to predict the problem , 
one thing i'm sure of that the sdk is working (currently stable in our app) 
a possible error that you have a fixed account on both sides in the .linphonerc file .

**Comment by Harshjain2094** [comment]
Thanks for the help. I'll implement the logging code and try to figure it out from there. Again Thanks.
