### ISSUE TITLE
Ice with turn enabled facing not authorized 

### ISSUE THREAD

**Issue by ahna92** [BelledonneCommunications/linphone-android#317]
as i see that version 4.0.1 of linphone has a bug fix for turn feature , however i'm still facing a problem when my turn server credentials are different from my sip's 

I've noticed that in linpohne manger when setting the password for turn the following code is used : 
    
        public void setTurnPassword(String password) {
        NatPolicy nat = getOrCreateNatPolicy();
        AuthInfo authInfo = getLc().findAuthInfo(null, nat.getStunServerUsername(), null);

        if (authInfo != null) {
            AuthInfo cloneAuthInfo = authInfo.clone();
            getLc().removeAuthInfo(authInfo);
            cloneAuthInfo.setPassword(password);
            getLc().addAuthInfo(cloneAuthInfo);
        } else {
            authInfo = Factory.instance().createAuthInfo(nat.getStunServerUsername(), nat.getStunServerUsername(), password, null, null, null);
            getLc().addAuthInfo(authInfo);
        }
    }

wouldn't that mix between sip's account and turn's ?

and the log when connecting to the turn server : 

    ice: Send TURN allocate request: [::]:7076 --> 13.250.13.83:3478 [d089f8c206cec05cffffd502]
    ice: Recv error response: 10.0.8.1:7076 <-- 13.250.13.83:3478 [7354907ae1149df4cbbad51e]

i'm logging my outgoing packets on my phone and when connecting to the turn server i'm receiving not authorized (user name and password are correct)

**Comment by Viish** [comment]
SDK issue, not Android
