### ISSUE TITLE
 Unable to generate Doxyfile template

### ISSUE THREAD

**Issue by jinyulei0710** [BelledonneCommunications/linphone-android#318]
error: Cannot open file /Users/jinyulei/–recursive/WORK/android-arm64/Build/linphone/CMakeDoxyfile.tpl for writing
CMake Error at /usr/local/Cellar/cmake/3.11.4/share/cmake/Modules/FindDoxygen.cmake:665 (message):
  Unable to generate Doxyfile template: 1
Call Stack (most recent call first):
  coreapi/help/doc/doxygen/CMakeLists.txt:24 (find_package)

**Comment by johnnavaj** [comment]
sudo apt-get install graphviz

**Comment by jinyulei0710** [comment]
@johnnavaj does not make any sence

**Comment by jinyulei0710** [comment]
@johnnavaj  
this is the log, how to install dot
doxygen missing components:  dot
CMake Warning at coreapi/help/doc/doxygen/CMakeLists.txt:51 (message):
  The dot program is needed to generate the linphone documentation.  You can
  get it from http://www.graphviz.org/.

**Comment by jinyulei0710** [comment]
@johnnavaj thanks！
