### ISSUE TITLE
Duplication of messages 

### ISSUE THREAD

**Issue by AnirajParmar123** [BelledonneCommunications/linphone-android#319]
So here is the main issue I am facing with is that when i send message using DID which is without any prefix for example **4567892134** and when the receiver text me back it makes duplicate entry that is with prefix for example **(1)4567892134** so now there is two entry for same contact with and without prefix and using extension its working fine.

**Comment by RajanVindaloo** [comment]
While receiving a message, check for condition i.e. receiving a number is already exists in the message list. If yes, then use "receivingnumber.substring(3)" and then try to do further steps. This will probably solve your problem. 

OR

In your case, from a server side, it is adding "(1)" to your sending message. If possible then, try to remove it.
