### ISSUE TITLE
can not get object f58510c8ce6cd89dadff2b29574d03b05c6efcc9

### ISSUE THREAD

**Issue by ClockworkChen** [BelledonneCommunications/linphone-android#320]
error: 服务器不允许请求未公开的对象 f58510c8ce6cd89dadff2b29574d03b05c6efcc9
获取了子模组路径 'submodules/cmake-builder'，但是它没有包含 f58510c8ce6cd89dadff2b29574d03b05c6efcc9。直接获取该提交失败。

**Comment by shakeyin1998** [comment]
遇到了类似的问题

**Comment by 359025765** [comment]
看一下是不是子模块的分支不正确，push要分两次，一是子模块，并且子模块提交分支要正确，二是项目路径。

**Comment by Viish** [comment]
English please
