### ISSUE TITLE
make install is not working and giving error > Task :liblinphone-sdk:copyAssets FAILED

### ISSUE THREAD

**Issue by deepbhavsar** [BelledonneCommunications/linphone-android#321]
Hello,
I follow all given steps and install all necessary tools and set ndk path-sdk path  properly.
Run `./prepare.py` so it did some process on it.
Run `make`  so same it did some process
Run `make install` so it is giving below errors

> $ make install
> ./gradlew installDebug
> 
> > Configure project :
> [Push Notification] Firebase disabled
> 
> > Configure project :liblinphone-sdk
> WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation'.
> It will be removed at the end of 2018
> native sdk not ready yet
> 
> > Task :liblinphone-sdk:copyAssets FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> path may not be null or empty string. path=''
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1s
> 1 actionable task: 1 executed
> Makefile:146: recipe for target 'install-apk' failed
> make: *** [install-apk] Error 1
> 

What is the error and how to solved it? is something missing? I am trying from long time but can't setup it for further work.

I am using **Android studio 3.1.1** and **Ubantu 16.04 LTS**

Please help me and Thank you.

**Comment by Viish** [comment]
Your path is empty because it didn't find the Factory.java class for any architecture as it is said by the log "native sdk not ready yet".
Have you disabled the new Java wrapper ? Do you have a liblinphone-sdk/android-arm64/share/linphonej/ folder ?

**Comment by gintu** [comment]
I don't have liblinphone-sdk/android-arm64/share/linphonej/ folder. What have i done wrong?How can I create that folder?

**Comment by Viish** [comment]
Hi @gintu if you don't have this folder, the following can be the cause:
- You didn't build for arm64 architecture, but you'll have a similar folder in android-armv7 or android-x86
- You didn't build the new Java wrapper, either because you are on an old commit of linphone-android or you explicitely gave -DENABLE_JAVA_WRAPPER=NO to the prepare.py script
- You didn't execute the 'make' command after the prepare.py or there was an issue during the build

Cheers,

**Comment by gintu** [comment]
I am getting these errors while executing make

`make[6]: *** No rule to make target `/Users/gintu/linphone-android2/submodules/linphone/wrappers/java/linphone-doc', needed by `wrappers/java/src/linphone_jni.cc'.  Stop.
make[5]: *** [wrappers/java/CMakeFiles/linphonej.dir/all] Error 2
make[4]: *** [all] Error 2
make[3]: *** [/Users/gintu/linphone-android2/WORK/android-arm64/Stamp/EP_linphone/EP_linphone-build] Error 2
make[2]: *** [CMakeFiles/EP_linphone.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [arm64-build] Error 2
`

I am using mac if that make any change

**Comment by Viish** [comment]
@gintu Most probably you don't have doxygen & graphviz installed on your computer. They are required to be able to generate the wrapper.
Check out the README file in submodules/linphone

**Comment by gintu** [comment]
when i was trying to install bctools the following  errror showd up

`clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
Undefined symbols for architecture x86_64:\
  "_bctbx_clean", referenced from:\
      _bctbx_DestroyDHMContext in mbedtls.o\
ld: symbol(s) not found for architecture x86_64\
clang: error: linker command failed with exit code 1 (use -v to see invocation)\
make[2]: *** [libbctoolbox.la] Error 1\
make[1]: *** [all-recursive] Error 1\
make: *** [all] Error 2`

**Comment by Viish** [comment]
It's a submodule of linphone-android.
Check you have run 'git submodule update --recursive --init' first
And use latest NDK

**Comment by gintu** [comment]
I already have those submodules including bctoolbox.I was compiling and installing those submodules as per the readme present in submodules/linphone.but was stuck on this `cmake . -DCMAKE_INSTALL_PREFIX=<prefix> -DCMAKE_PREFIX_PATH=<search_prefixes>
` what do i have to fill in those <prefix>

**Comment by Viish** [comment]
You must not use cmake command directly to build the project for Android.
Simply run the ./prepare.py script and then make.

**Comment by gintu** [comment]
I fixed the whole issue by externally downloading the linphone sdk

**Comment by rasik1991** [comment]
i am facing same error i dont know how to fix it , and i dont know how to download  the linphone sdk externally,  i am using android studio in  macOS Sierra

**Comment by Viish** [comment]
You can get the SDK from our maven repository:
https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Getting%20started/Android/#HUseourmavenrepository
