### ISSUE TITLE
Unable to receive call.

### ISSUE THREAD

**Issue by anshulkabra** [BelledonneCommunications/linphone-android#323]
I have normally build the app from source. The app is able to connect to server, but once the call is received below error is coming up-
linphone E/ExtMediaPlayer-JNI: QCMediaPlayer could not be located....
07-19 03:30:00.509 32705-32705/org.linphone E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
07-19 03:30:00.510 32705-32705/org.linphone E/ExtMediaPlayer-JNI: QCMediaPlayer could not be located....
07-19 03:30:00.510 32705-32705/org.linphone E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0

=========================
Another device

================
07-19 13:16:19.759 12978-12984/org.linphone I/zygote64: Thread[3,tid=12984,WaitingInMainSignalCatcherLoop,Thread*=0x71bbac1400,peer=0x13b00088,"Signal Catcher"]: reacting to signal 3
07-19 13:16:19.760 12978-12984/org.linphone E/zygote64: # HandleSigQuit # DumpForSigQuit # before # pid=12978
07-19 13:16:19.908 12978-12984/org.linphone E/zygote64: # HandleSigQuit # DumpForSigQuit # after # pid=12978
07-19 13:16:19.920 12978-12984/org.linphone I/zygote64: Wrote stack traces to '/data/anr/traces.txt'
07-19 13:16:31.169 12978-12978/org.linphone I/AudioRecord: set(): inputSource 7, sampleRate 8000, format 0x1, channelMask 0x10, frameCount 640, notificationFrames 0, sessionId 0, transferType 0, flags 0, opPackageName org.linphone uid -1, pid -1
07-19 13:16:31.228 12978-12978/org.linphone I/libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x4, using default mask 0x1 based on channel count of 1)
07-19 13:16:31.228 12978-12978/org.linphone D/AudioTrack: set(): streamType 0, sampleRate 48000, format 0x1, channelMask 0x1, frameCount 0, flags #104, notificationFrames 4294967294, sessionId 74721, transferType 0, uid -1, pid -1, cbf 0
07-19 13:16:31.228 12978-12978/org.linphone I/AudioTrack: OPM,client expresses a preference for Fast!
07-19 13:16:31.299 12978-12978/org.linphone I/AudioTrack: AUDIO_OUTPUT_FLAG_FAST successful; frameCount 384 -> 384
07-19 13:16:31.299 12978-12978/org.linphone D/AudioTrack: Client defaulted notificationFrames to 192 for frameCount 384
07-19 13:16:32.119 12978-12983/org.linphone I/zygote64: Method exceeds compiler instruction limit: 25337 in void org.ccil.cowan.tagsoup.HTMLSchema.<init>()
07-19 13:16:33.847 12978-12983/org.linphone I/zygote64: Do full code cache collection, code=1007KB, data=732KB
07-19 13:16:33.849 12978-12983/org.linphone I/zygote64: After code cache collection, code=1007KB, data=584KB
07-19 13:16:34.858 12978-12983/org.linphone I/zygote64: Do partial code cache collection, code=1007KB, data=585KB
07-19 13:16:34.862 12978-12983/org.linphone I/zygote64: After code cache collection, code=1007KB, data=585KB
    Increasing code cache capacity to 3MB
07-19 13:17:02.153 12978-12978/org.linphone D/AudioTrack: stop() called with 1469952 frames delivered
07-19 13:17:02.181 12978-12978/org.linphone D/AudioManager: PPD setMode mode = 0
07-19 13:17:02.182 12978-12978/org.linphone V/AudioManager: Elem: dalvik.system.VMStack.getThreadStackTrace(Native Method)
    Elem: java.lang.Thread.getStackTrace(Thread.java:1536)
    Elem: android.media.AudioManager.setMode(AudioManager.java:1630)
    Elem: org.linphone.LinphoneManager.onCallStateChanged(LinphoneManager.java:1210)
    Elem: org.linphone.core.CoreImpl.terminateCall(Native Method)
    Elem: org.linphone.core.CoreImpl.terminateCall(Core.java:4955)
    Elem: org.linphone.call.CallActivity.hangUp(CallActivity.java:956)
    Elem: org.linphone.call.CallActivity.onClick(CallActivity.java:677)
    Elem: android.view.View.performClick(View.java:6303)
    Elem: android.view.View$PerformClick.run(View.java:24828)
    Elem: android.os.Handler.handleCallback(Handler.java:789)
    Elem: android.os.Handler.dispatchMessage(Handler.java:98)
    Elem: android.os.Looper.loop(Looper.java:164)
    Elem: android.app.ActivityThread.main(ActivityThread.java:6798)
    Elem: java.lang.reflect.Method.invoke(Native Method)
    Elem: com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    Elem: com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
07-19 13:17:02.230 12978-12978/org.linphone I/AudioManager: setSpeakerphoneOn false java.lang.Throwable
        at android.media.AudioManager.setSpeakerphoneOn(AudioManager.java:1235)
        at org.linphone.LinphoneManager.enableSpeaker(LinphoneManager.java:235)
        at org.linphone.LinphoneManager.routeAudioToSpeakerHelper(LinphoneManager.java:227)
        at org.linphone.LinphoneManager.routeAudioToReceiver(LinphoneManager.java:313)
        at org.linphone.LinphoneManager.onCallStateChanged(LinphoneManager.java:1212)
        at org.linphone.core.CoreImpl.terminateCall(Native Method)
        at org.linphone.core.CoreImpl.terminateCall(Core.java:4955)
        at org.linphone.call.CallActivity.hangUp(CallActivity.java:956)
        at org.linphone.call.CallActivity.onClick(CallActivity.java:677)
        at android.view.View.performClick(View.java:6303)
        at android.view.View$PerformClick.run(View.java:24828)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
07-19 13:17:02.562 12978-12978/org.linphone E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
07-19 13:17:03.734 12978-12978/org.linphone I/libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x4, using default mask 0x1 based on channel count of 1)
07-19 13:17:03.734 12978-12978/org.linphone D/AudioTrack: set(): streamType 0, sampleRate 48000, format 0x1, channelMask 0x1, frameCount 0, flags #104, notificationFrames 4294967294, sessionId 74785, transferType 0, uid -1, pid -1, cbf 0
07-19 13:17:03.734 12978-12978/org.linphone I/AudioTrack: OPM,client expresses a preference for Fast!
07-19 13:17:03.736 12978-12978/org.linphone I/AudioTrack: AUDIO_OUTPUT_FLAG_FAST successful; frameCount 384 -> 384
07-19 13:17:03.736 12978-12978/org.linphone D/AudioTrack: Client defaulted notificationFrames to 192 for frameCount 384
07-19 13:17:05.779 12978-12978/org.linphone D/AudioTrack: stop() called with 97152 frames delivered
07-19 13:17:05.811 12978-12978/org.linphone D/AudioManager: PPD setMode mode = 3
07-19 13:17:05.811 12978-12978/org.linphone V/AudioManager: Elem: dalvik.system.VMStack.getThreadStackTrace(Native Method)
07-19 13:17:05.812 12978-12978/org.linphone V/AudioManager: Elem: java.lang.Thread.getStackTrace(Thread.java:1536)
    Elem: android.media.AudioManager.setMode(AudioManager.java:1630)
    Elem: org.linphone.LinphoneManager.setAudioManagerInCallMode(LinphoneManager.java:1129)
    Elem: org.linphone.LinphoneManager.onCallStateChanged(LinphoneManager.java:1229)
    Elem: org.linphone.core.CoreImpl.inviteAddressWithParams(Native Method)
    Elem: org.linphone.core.CoreImpl.inviteAddressWithParams(Core.java:4577)
    Elem: org.linphone.call.CallManager.inviteAddress(CallManager.java:66)
    Elem: org.linphone.LinphoneManager.newOutgoingCall(LinphoneManager.java:448)
    Elem: org.linphone.LinphoneManager.newOutgoingCall(LinphoneManager.java:407)
    Elem: org.linphone.ui.CallButton.onClick(CallButton.java:55)
    Elem: android.view.View.performClick(View.java:6303)
    Elem: android.view.View$PerformClick.run(View.java:24828)
    Elem: android.os.Handler.handleCallback(Handler.java:789)
    Elem: android.os.Handler.dispatchMessage(Handler.java:98)
    Elem: android.os.Looper.loop(Looper.java:164)
    Elem: android.app.ActivityThread.main(ActivityThread.java:6798)
    Elem: java.lang.reflect.Method.invoke(Native Method)
    Elem: com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    Elem: com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
07-19 13:17:05.872 12978-12978/org.linphone W/AudioManager: Use of stream types is deprecated for operations other than volume control
    See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
07-19 13:17:06.622 12978-12978/org.linphone I/libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x4, using default mask 0x1 based on channel count of 1)
07-19 13:17:06.622 12978-12978/org.linphone D/AudioTrack: set(): streamType 0, sampleRate 48000, format 0x1, channelMask 0x1, frameCount 0, flags #104, notificationFrames 4294967294, sessionId 74793, transferType 0, uid -1, pid -1, cbf 0
07-19 13:17:06.622 12978-12978/org.linphone I/AudioTrack: OPM,client expresses a preference for Fast!
07-19 13:17:06.623 12978-12978/org.linphone I/AudioTrack: AUDIO_OUTPUT_FLAG_FAST successful; frameCount 384 -> 384
07-19 13:17:06.623 12978-12978/org.linphone D/AudioTrack: Client defaulted notificationFrames to 192 for frameCount 384
07-19 13:17:08.203 12978-12978/org.linphone D/AudioTrack: stop() called with 75648 frames delivered

**Comment by deepbhavsar** [comment]
@anshulkabra 
May it will help you. try below link and check the code.
https://github.com/treasure-lau/Linphone4Android

**Comment by Viish** [comment]
Can you attach the full logs please? I guess this is related to the device itself.
Have you tried just in case the latest version of our library ?
