### ISSUE TITLE
Failed to connect to gitlab.linphone.org port 443

### ISSUE THREAD

**Issue by deepbhavsar** [BelledonneCommunications/linphone-android#327]
Hello,

I have setup all in given step.
After I use `./prepare.py` 
after call `git submodule sync && git submodule update --init --recursive`
and it is giving below error after some process

> fatal: unable to access 'https://gitlab.linphone.org/BC/public/bcg729.git/': Failed to connect to gitlab.linphone.org port 443: Connection refused
> 
> fatal: clone of 'https://gitlab.linphone.org/BC/public/bcg729.git' into submodule path 'submodules/bcg729' failed

I checked personally in chrome and unable to open `https://gitlab.linphone.org/`

I am using Android studio 3.1.3

Anyone can help me?

**Comment by mfrlinux** [comment]
I have this problem now.
`fatal: unable to access 'https://gitlab.linphone.org/BC/public/bcg729.git/': Failed to connect to gitlab.linphone.org port 443`
But i can open in Browser.
Any suggestion?

**Comment by deepbhavsar** [comment]
@mfrlinux

**Comment by dmsherazi** [comment]
> Hello,
> 
> I have setup all in given step.
> After I use `./prepare.py`
> after call `git submodule sync && git submodule update --init --recursive`
> and it is giving below error after some process
> 
> > fatal: unable to access 'https://gitlab.linphone.org/BC/public/bcg729.git/': Failed to connect to gitlab.linphone.org port 443: Connection refused
> > fatal: clone of 'https://gitlab.linphone.org/BC/public/bcg729.git' into submodule path 'submodules/bcg729' failed
> 
> I checked personally in chrome and unable to open `https://gitlab.linphone.org/`
> 
> I am using Android studio 3.1.3
> 
> Anyone can help me?

I am having the same issue. The links for gitlab are not even opening in the browser

**Comment by dmsherazi** [comment]
The gitmodules file needs be update with proper links. 
replacing it with the one here https://gitlab.com/ashwanijanghu/linphone-android/blob/master/.gitmodules solves the issue
