### ISSUE TITLE
Building AAR from master

### ISSUE THREAD

**Issue by aquacode** [BelledonneCommunications/linphone-android#328]
Followed this instruction for getting an AAR:

(optional) To generate a liblinphone SDK zip containing a full jar and native libraries, run make liblinphone-android-sdk

However, it fails to vaildate release gradle task.

Seems release configs require release settings

Is there a way to create a debug AAR and if not, how can the release AAR be created successfully?

**Comment by aquacode** [comment]
If I comment out release configs in build.gradle the build succeeds however the AAR's classes.jar file is missing core .class files such as LinphoneCore.class

**Comment by Viish** [comment]
make liblinphone-android-sdk creates the aar
