### ISSUE TITLE
No incoming or outgoing sip call sound is heard on Android 8

### ISSUE THREAD

**Issue by bthsh2017** [BelledonneCommunications/linphone-android#329]
I connect to a sip server with udp. It is able to register and connect. 
I tried also when I receive a call, enable the speaker and I can hear. But if it is headset mode, no sound is heard. Other os version is fine.
I even download the latest (4.0.1) from play store and got the same result.

**Comment by astuter** [comment]
@bthsh2017: Me to having the same issue with 4.0.1 release.

**Comment by bthsh2017** [comment]
I check the log when a receive a call. Though it may related to xml of chipset msm8916 or whatever.


07-26 09:34:01.583 690-6104/? D/audio_hw_primary: enable_audio_route: apply mixer and update path: audio-ull-playback handset
07-26 09:34:01.584 690-6104/? E/audio_route: unable to find path 'audio-ull-playback handset'
07-26 09:34:01.584 690-6104/? D/audio_hw_primary: select_devices: done
07-26 09:34:01.588 690-6104/? E/audio_hw_primary: start_output_stream: pcm_prepare returned -1
07-26 09:34:01.594 690-6104/? D/audio_hw_primary: disable_audio_route: reset and update mixer path: audio-ull-playback handset
07-26 09:34:01.594 690-6104/? E/audio_route: unable to find path 'audio-ull-playback handset'
07-26 09:34:01.594 690-6104/? D/soundtrigger: audio_extn_sound_trigger_update_stream_status: uc_id 12 of type 0 for Event 2, with Raise=0
07-26 09:34:01.594 690-6104/? D/hardware_info: hw_info_append_hw_type : device_name = handset
07-26 09:34:01.594 690-6104/? D/audio_hw_primary: disable_snd_device: snd_device(1: handset)
07-26 09:34:01.594 690-6104/? D/msm8916_platform: platform_split_snd_device: snd_device(1) num devices(0) new_snd_devices(1364347215)
07-26 09:34:01.597 690-6104/? I/soundtrigger: audio_extn_sound_trigger_update_device_status: device 0x1 of type 0 for Event 0, with Raise=0
07-26 09:34:01.652 690-6104/? W/StreamHAL: Error from HAL stream in function get_presentation_position: Operation not permitted
07-26 09:34:01.652 690-6104/? D/audio_hw_primary: start_output_stream: enter: stream(0xf1c9a800)usecase(12: audio-ull-playback) devices(0x1)
07-26 09:34:01.653 690-6104/? D/audio_hw_primary: select_devices for use case (audio-ull-playback)
07-26 09:34:01.653 690-6104/? D/audio_hw_primary: select_devices: out_snd_device(1: handset) in_snd_device(0: )
07-26 09:34:01.653 690-6104/? I/msm8916_platform: platform_check_and_set_codec_backend_cfg:becf: afe: bitwidth 16, samplerate 48000 channels 2, backend_idx 0 usecase = 12 device (handset)
07-26 09:34:01.653 690-6104/? D/msm8916_platform: platform_split_snd_device: snd_device(1) num devices(1) new_snd_devices(0)
07-26 09:34:01.653 690-6104/? I/msm8916_platform: platform_check_and_set_codec_backend_cfg: becf: new_snd_devices[0] is handset
07-26 09:34:01.653 690-6104/? I/msm8916_platform: platform_check_codec_backend_cfg:becf: afe: Codec selected backend: 0 current bit width: 16 sample rate: 48000 channels: 2 usecase 12 device (handset)
07-26 09:34:01.653 690-6104/? D/msm8916_platform: platform_check_codec_backend_cfg:becf: afe: playback on codec device not supporting native playback set default Sample Rate(48k)
07-26 09:34:01.653 690-6104/? I/msm8916_platform: platform_check_codec_backend_cfg:becf: afe: Codec selected backend: 0 updated bit width: 16 sample rate: 48000 channels: 2
07-26 09:34:01.653 690-6104/? D/audio_hw_primary: check_usecases_codec_backend:becf: force routing 0
07-26 09:34:01.653 690-6104/? E/msm8916_platform: platform_check_backends_match: Invalid snd_device =

**Comment by astuter** [comment]
Try disabling AVPFMode. It worked for me.

**Comment by bthsh2017** [comment]
Unfortunately, it's not in my case
