### ISSUE TITLE
Error Compile : missing: SPEEXDSP_INCLUDE_DIRS SPEEXDSP_LIBRARIES   HAVE_SPEEX_SPEEX_RESAMPLER_H

### ISSUE THREAD

**Issue by vdharashive** [BelledonneCommunications/linphone-android#336]
Hi All,

Can any one help me the below error 

[ 66%] Completed 'EP_gsm'
make[3]: Leaving directory '/home/vertex/Download/linphone-android/WORK/android-armv7/cmake'
[ 69%] Built target EP_gsm
make[3]: Entering directory '/home/vertex/Download/linphone-android/WORK/android-armv7/cmake'
make[3]: Leaving directory '/home/vertex/Download/linphone-android/WORK/android-armv7/cmake'
make[3]: Entering directory '/home/vertex/Download/linphone-android/WORK/android-armv7/cmake'
[ 69%] Performing configure step for 'EP_ms2'
loading initial cache file /home/vertex/Download/linphone-android/WORK/android-armv7//tmp/EP_ms2/EP_ms2-cache-RelWithDebInfo.cmake
CMake Error at /usr/local/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find SpeexDsp (missing: SPEEXDSP_INCLUDE_DIRS SPEEXDSP_LIBRARIES
  HAVE_SPEEX_SPEEX_RESAMPLER_H)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSpeexDsp.cmake:42 (find_package_handle_standard_args)
  CMakeLists.txt:211 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/vertex/Download/linphone-android/WORK/android-armv7/Build/ms2/CMakeFiles/CMakeOutput.log".
CMakeFiles/EP_ms2.dir/build.make:115: recipe for target '/home/vertex/Download/linphone-android/WORK/android-armv7/Stamp/EP_ms2/EP_ms2-configure' failed
make[3]: *** [/home/vertex/Download/linphone-android/WORK/android-armv7/Stamp/EP_ms2/EP_ms2-configure] Error 1
make[3]: Leaving directory '/home/vertex/Download/linphone-android/WORK/android-armv7/cmake'
CMakeFiles/Makefile2:1006: recipe for target 'CMakeFiles/EP_ms2.dir/all' failed
make[2]: *** [CMakeFiles/EP_ms2.dir/all] Error 2
make[2]: Leaving directory '/home/vertex/Download/linphone-android/WORK/android-armv7/cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/vertex/Download/linphone-android/WORK/android-armv7/cmake'
Makefile:215: recipe for target 'armv7-build' failed
make: *** [armv7-build] Error 2

**Comment by aragon5956** [comment]
have you solve this problem ?
with this : `sudo apt-get install libspeexdsp-dev`
if you use `bash` have this inside : `export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
export LD_LIBRARY_PATH=$LIBDIR:$LD_LIBRARY_PATH
export LD_RUN_PATH=$LIB_DIR:$LD_RUN_PATH
` with no conflict in previous declarations ?
