### ISSUE TITLE
Cannot make project

### ISSUE THREAD

**Issue by yoki888** [BelledonneCommunications/linphone-android#340]
make[6]: *** No rule to make target `/Users/hunk/Downloads/linphone-android/submodules/linphone/wrappers/java/linphone-doc', needed by `wrappers/java/src/linphone_jni.cc'.  Stop.
make[5]: *** [wrappers/java/CMakeFiles/linphonej.dir/all] Error 2
make[4]: *** [all] Error 2
make[3]: *** [/Users/hunk/Downloads/linphone-android/WORK/android-arm64/Stamp/EP_linphone/EP_linphone-build] Error 2
make[2]: *** [CMakeFiles/EP_linphone.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [arm64-build] Error 2

**Comment by forcetu** [comment]
Maybe your problem is same as #285

**Comment by yoki888** [comment]
Sorry , I still have same problem
I had install 'doxygen' -> 1.8.14
Can you tell me how to do next

-- Soci found: Looking for plugins
--     * Plugin mysql not found.
--     * Plugin sqlite3 found /Users/hunk/Downloads/linphone-android/liblinphone-sdk/android-arm64/lib/libsoci_sqlite3.a.
-- 'pystache' python module found
-- 'six' python module found
-- Found Git: /usr/local/bin/git (found version "2.17.1") 
CMake Warning at coreapi/help/doc/doxygen/CMakeLists.txt:51 (message):
  The dot program is needed to generate the linphone documentation.  You can
  get it from http://www.graphviz.org/.

-- Found Git: /usr/local/bin/git (found suitable version "2.17.1", minimum required is "1.7.1") 
-- Package file name is liblinphone-3.12.0-2905
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/hunk/Downloads/linphone-android/WORK/android-arm64/Build/linphone
[ 96%] Forcing build for 'EP_linphone'
[ 97%] Performing build step for 'EP_linphone'
make[6]: *** No rule to make target `/Users/hunk/Downloads/linphone-android/submodules/linphone/wrappers/java/linphone-doc', needed by `wrappers/java/src/linphone_jni.cc'.  Stop.
make[5]: *** [wrappers/java/CMakeFiles/linphonej.dir/all] Error 2
make[4]: *** [all] Error 2
make[3]: *** [/Users/hunk/Downloads/linphone-android/WORK/android-arm64/Stamp/EP_linphone/EP_linphone-build] Error 2
make[2]: *** [CMakeFiles/EP_linphone.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [arm64-build] Error 2

**Comment by forcetu** [comment]
The dot program is needed to generate the linphone documentation. You can get it from http://www.graphviz.org/.

Maybe you can try the following command 
apt-get install graphviz

**Comment by yoki888** [comment]
Thanks, It's work!
