### ISSUE TITLE
latest version not available at F-Droid

### ISSUE THREAD

**Issue by jamtwister** [BelledonneCommunications/linphone-android#345]
you have done great work to put linphone on F-Droid #16 
But now there is not the current version 4.0.1 available.
The latest version available at F-Droid is 3.3.2.

There is already an issues at F-Droid
https://gitlab.com/fdroid/fdroiddata/issues/1179

At the linphone site at F-Droid 
https://f-droid.org/wiki/page/org.linphone
there is an interesting info:

> We don't have the current version of this app. (Check mode: Tags) (Auto-update mode: None)
> The current (recommended) version is 4.0.1 (version code 4002). 

PS:
You do really great work with linphone ;)

**Comment by baldurmen** [comment]
Yeah, this is sad, as linphone is the only real voip client on F-droid :(

**Comment by jamtwister** [comment]
https://gitlab.com/fdroid/fdroiddata/issues/1179 was fixed today

now at latest version (4.0.1) is available at f-droid.

Thanks very much. :smiley:
