### ISSUE TITLE
Error compiling EP_ffmpeg

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-android#347]
Looks like there is an issue compiling linphone with the ffmpeg option. I've upgraded to android ndk r17b and made sure to update cmake as well.

`[ 28%] Performing configure step for 'EP_ffmpeg'
/android/android-ndk-r17b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang is unable to create an executable file.
C compiler test failed.
`

The issue seems to be ld?
`WARNING: /android/android-ndk-r17b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/pkg-config not found, library detection may fail.
mktemp -u XXXXXX
LsZzYr
check_ld cc
check_cc
BEGIN /tmp/ffconf.b9fYtVxm.c
    1	int main(void){ return 0; }
END /tmp/ffconf.b9fYtVxm.c
/android/android-ndk-r17b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --sysroot=/android/android-ndk-r17b/sysroot -isysroot /android/android-ndk-r17b/sysroot -w --target=aarch64-none-linux-android --gcc-toolchain= -c -o /tmp/ffconf.gCDSYNPt.o /tmp/ffconf.b9fYtVxm.c
/android/android-ndk-r17b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=aarch64-none-linux-android --gcc-toolchain= --sysroot=/android/android-ndk-r17b/sysroot -isysroot /android/android-ndk-r17b/sysroot -o /tmp/ffconf.jWrAs83d /tmp/ffconf.gCDSYNPt.o
/usr/bin/ld: unrecognised emulation mode: aarch64linux
Supported emulations: elf_x86_64 elf32_x86_64 elf_i386 elf_iamcu i386linux elf_l1om elf_k1om i386pep i386pe
clang: error: linker command failed with exit code 1 (use -v to see invocation)
C compiler test failed.
`

Anyone who experienced the same?

**Comment by joyfun** [comment]
I have the same issue . and I change ndk to r16b  the error is the same

**Comment by athasamid** [comment]
I have the same issue, 
are U already found solution?

**Comment by driesken** [comment]
No I haven't. For now, I've just disabled ffmpeg since I don't need video at the moment.

**Comment by ianmustafa** [comment]
Changing the OS from Ubuntu to Debian didn't help. Has anybody tried using CentOS?

**Comment by narutokenan** [comment]
I have the same issue , Do someone resolve this issue?
