### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by developer--** [BelledonneCommunications/linphone-android#35]
**java.lang.UnsatisfiedLinkError: dlopen failed: library "./obj/local/armeabi-v7a/libffmpeg-linphone-arm.so" not found**
app crashes after api level change to 25 this is my gradle file

`apply plugin: 'com.android.application'

buildscript {
    repositories {
        jcenter()
        //mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.0'
        classpath 'com.google.gms:google-services:3.0.0'
    }
}
repositories {
    jcenter()
    mavenCentral()
}
android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "org.linphone"
        minSdkVersion 14
        targetSdkVersion 25
        versionCode 4
        versionName "1.0.0"
        multiDexEnabled true
    }
    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['submodules/linphone/mediastreamer2/java/src', 'submodules/linphone/java/j2se', 'submodules/linphone/java/common', 'submodules/linphone/java/impl', 'submodules/externals/axmlrpc/src/main/java', 'submodules/linphone/coreapi/help/java', 'src']
            resources.srcDirs = ['submodules/linphone/mediastreamer2/java/src', 'submodules/linphone/java/j2se', 'submodules/linphone/java/common', 'submodules/linphone/java/impl', 'submodules/externals/axmlrpc/src/main/java', 'submodules/linphone/coreapi/help/java', 'src']
            aidl.srcDirs = ['submodules/linphone/mediastreamer2/java/src', 'submodules/linphone/java/j2se', 'submodules/linphone/java/common', 'submodules/linphone/java/impl', 'submodules/externals/axmlrpc/src/main/java', 'submodules/linphone/coreapi/help/java', 'src']
            renderscript.srcDirs = ['submodules/linphone/mediastreamer2/java/src', 'submodules/linphone/java/j2se', 'submodules/linphone/java/common', 'submodules/linphone/java/impl', 'submodules/externals/axmlrpc/src/main/java', 'submodules/linphone/coreapi/help/java', 'src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            jniLibs.srcDir 'libs'

            java.exclude '**/mediastream/MediastreamerActivity.java'
        }

        instrumentTest.setRoot('tests')

        debug.setRoot('build-types/debug')
        release.setRoot('build-types/release')
    }
    buildTypes {
    }
}

dependencies {
    compile fileTree(include: '*.jar', dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:19.0.0'
    compile 'com.google.code.gson:gson:2.7'
    compile 'com.squareup.retrofit2:retrofit:2.1.0'
    compile 'com.squareup.retrofit2:converter-gson:2.1.0'
    compile 'com.squareup.okhttp3:okhttp:3.6.0'
    compile 'com.squareup.okhttp3:logging-interceptor:3.4.2'
    compile 'com.google.firebase:firebase-messaging:10.2.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
}

apply plugin: 'com.google.gms.google-services'`

**Comment by DatBewar** [comment]
Hello,
We doesn't use Ffmpeg anymore in Linphone-Android project so i can't say why it's not working for you.
Best regards,

**Comment by passiondroid** [comment]
I am also getting below error and app crashes when calling lc.resumeCall(call);

```
Unable to load optional library ffmpeg-linphone-armeabi-v7a: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.dyl.phone-1/base.apk"],nativeLibraryDirectories=[/data/app/com.dyl.phone-1/lib/arm, /data/app/com.dyl.phone-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libffmpeg-linphone-armeabi-v7a.so"
03-27 17:38:59.552 24421-24421/com.dyl.phone W/linker: /data/app/com.dyl.phone-1/lib/arm/libbctoolbox-armeabi-v7a.so: unused DT entry: type 0xf arg 0x5ac6
03-27 17:38:59.554 24421-24421/com.dyl.phone W/linker: /data/app/com.dyl.phone-1/lib/arm/libortp-armeabi-v7a.so: unused DT entry: type 0xf arg 0x3ffb
03-27 17:38:59.556 24421-24421/com.dyl.phone W/linker: /data/app/com.dyl.phone-1/lib/arm/libmediastreamer_base-armeabi-v7a.so: unused DT entry: type 0xf arg 0x230f
03-27 17:38:59.558 24421-24421/com.dyl.phone W/linker: /data/app/com.dyl.phone-1/lib/arm/libmediastreamer_voip-armeabi-v7a.so: unused DT entry: type 0xf arg 0x1dae1
03-27 17:38:59.567 24421-24421/com.dyl.phone W/linker: /data/app/com.dyl.phone-1/lib/arm/liblinphone-armeabi-v7a.so: unused DT entry: type 0xf arg 0x1cd2fd
```

**Comment by farrukh-obaid** [comment]
getting same error with latest 1 July 2017 build

07-02 02:13:46.891 17532-17532/fo.com.myapplication W/LinphoneCoreFactoryImpl: Unable to load optional library ffmpeg-linphone: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/fo.com.myapplication-1/base.apk", zip file "/data/app/fo.com.myapplication-1/split_lib_dependencies_apk.apk", zip file "/data/app/fo.com.myapplication-1/split_lib_slice_0_apk.apk", zip file "/data/app/fo.com.myapplication-1/split_lib_slice_1_apk.apk", zip file "/data/app/fo.com.myapplication-1/split_lib_slice_2_apk.apk", zip file "/data/app/fo.com.myapplication-1/split_lib_slice_3_apk.apk", zip file "/data/app/fo.com.myapplication-1/split_lib_slice_4_apk.apk", zip file "/data/app/fo.com.myapplication-1/split_lib_slice_5_apk.apk", zip file "/data/app/fo.com.myapplication-1/split_lib_slice_6_apk.apk", zip file "/data/app/fo.com.myapplication-1/split_lib_slice_7_apk.apk", zip file "/data/app/fo.com.myapplication-1/split_lib_slice_8_apk.apk", zip file "/data/app/fo.com.myapplication-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/fo.com.myapplication-1/lib/x86, /data/app/fo.com.myapplication-1/base.apk!/lib/x86, /data/app/fo.com.myapplication-1/split_lib_dependencies_apk.apk!/lib/x86, /data/app/fo.com.myapplication-1/split_lib_slice_0_apk.apk!/lib/x86, /data/app/fo.com.myapplication-1/split_lib_slice_1_apk.apk!/lib/x86, /data/app/fo.com.myapplication-1/split_lib_slice_2_apk.apk!/lib/x86, /data/app/fo.com.myapplication-1/split_lib_slice_3_apk.apk!/lib/x86, /data/app/fo.com.myapplication-1/split_lib_slice_4_apk.apk!/lib/x86, /data/app/fo.com.myapplication-1/split_lib_slice_5_apk.apk!/lib/x86, /data/app/fo.com.myapplication-1/split_lib_slice_6_apk.apk!/lib/x86, /data/app/fo.com.myapplication-1/split_lib_slice_7_apk.apk!/lib/x86, /data/app/fo.com.myapplication-1/split_lib_slice_8_apk.apk!/lib/x86, /data/app/fo.com.myapplication-1/split_lib_slice_9_apk.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libffmpeg-linphone.so"
07-02 02:13:46.901 17532-17532/fo.com.myapplication D/AndroidRuntime: Shutting down VM
07-02 02:13:46.901 17532-17532/fo.com.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: fo.com.myapplication, PID: 17532
                                                                      java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "ms_video_find_best_configuration_for_bitrate" referenced by "/data/app/fo.com.myapplication-1/lib/x86/libmediastreamer_voip.so"...
                                                                          at java.lang.Runtime.loadLibrary0(Runtime.java:989)
                                                                          at java.lang.System.loadLibrary(System.java:1530)
                                                                          at org.linphone.core.LinphoneCoreFactoryImpl.<clinit>(LinphoneCoreFactoryImpl.java:51)
                                                                          at java.lang.Class.classForName(Native Method)
                                                                          at java.lang.Class.forName(Class.java:400)
                                                                          at java.lang.Class.forName(Class.java:326)
                                                                          at org.linphone.core.LinphoneCoreFactory.instance(LinphoneCoreFactory.java:47)
                                                                          at fo.com.myapplication.MainActivity$1.onClick(MainActivity.java:22)
                                                                          at android.view.View.performClick(View.java:5637)
                                                                          at android.view.View$PerformClick.run(View.java:22429)
                                                                          at android.os.Handler.handleCallback(Handler.java:751)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by developer--** [comment]
I solved my problem, check this [https://medium.com/mobiwise-blog/unsatisfiedlinkerror-problem-on-some-android-devices-b77f2f83837d](url)

**Comment by rasik1010** [comment]
i have same issue , can anyone have solution ? please tell me  , thanks

**Comment by qiLingLingYi** [comment]
i have same issue , can anyone have solution ? please tell me , thanks~~~
