### ISSUE TITLE
'Fatal signal 11 (SIGSEGV)' Causing app crash

### ISSUE THREAD

**Issue by MeDeity** [BelledonneCommunications/linphone-android#354]
When I am using linphoneSDK 3.3.2 [liblinphone-android-sdk-nonfreecodecs-video-3.3.2.zip](https://www.linphone.org/releases/android/liblinphone-android-sdk-nonfreecodecs-video-3.3.2.zip) running on Android 4.4.4 kikat, I will encounter project crashes from time to time in the project. I know there is a version of 4.0.0 or 4.0.1. But it seems that the generation is very serious, I want to know if the problem has been resolved on the new version. This is my error stack:
`09-05 14:17:38.533 28230-28230/com.keytop.ppmo A/libc: Fatal signal 11 (SIGSEGV) at 0x00000004 (code=1), thread 28230 (com.keytop.ppmo)
09-05 14:17:38.633 87-87/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Build fingerprint: 'RYD/dg3188/dg3188:4.4.4/KTU84Q/eng.ronfull.20180608.121019:eng/test-keys'
    Revision: '0'
    pid: 28230, tid: 28230, name: com.keytop.ppmo  >>> com.keytop.ppmo <<<
    signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000004
09-05 14:17:38.753 87-87/? I/DEBUG:     r0 00000004  r1 672798f0  r2 400b70cb  r3 00000004
        r4 00000000  r5 bea1819c  r6 000000bc  r7 bea18190
        r8 00000001  r9 00000001  sl 67276eec  fp 00000001
        ip 400bef38  sp bea18180  lr 400b70d5  pc 40186558  cpsr 000d0010
        d0  0000000000000000  d1  0000000000000000
        d2  0000000000000000  d3  0000000000000000
        d4  5f72656e65747369  d5  6c5f6176616a4c32
        d6  697274535f676e61  d7  40000000325f676e
        d8  6e84b77d6e84b58d  d9  6e84bb9d6e84b999
        d10 6e84ba996e84b881  d11 6e84be1d6e84bce9
        d12 000000006e84b0dd  d13 6e84b1ed6e84b311
        d14 0000000000000000  d15 0000000000000000
        d16 efcdab8967452301  d17 1032547698badcfe
        d18 14e1fc91e513cb9a  d19 be72138e0facf4cd
        d20 be9268430fdc536a  d21 bf5681410e81a9a4
        d22 3e21df36098310b4  d23 3ff0000000000000
        d24 3fe621619b20dd11  d25 3fd3bd3cc9be45de
        d26 0000000000000000  d27 3f8fcf32d797aeef
        d28 3fe6a09e667f3bcd  d29 0000000000000000
        d30 0000000000000000  d31 c028000000000000
        scr 80000010
    backtrace:
        #00  pc 00003558  /system/lib/libcutils.so (android_atomic_inc+8)
        #01  pc 0000d0d1  /system/lib/libutils.so (android::RefBase::incStrong(void const*) const+6)
        #02  pc 000956c5  /data/app-lib/com.keytop.ppmo-2/libmediastreamer_voip.so (fake_android::sp<fake_android::AudioTrack>::assign(fake_android::AudioTrack*)+14)
        #03  pc 000995d3  /data/app-lib/com.keytop.ppmo-2/libmediastreamer_voip.so (fake_android::AudioTrackImpl::init(Library*)+262)
    stack:
             bea18140  00000001  
             bea18144  00000001  
             bea18148  67276eec  
             bea1814c  672798f0  
             bea18150  bea1819c  [stack]
             bea18154  000000bc  
             bea18158  bea18164  [stack]
             bea1815c  6e321e11  /data/app-lib/com.keytop.ppmo-2/libmediastreamer_voip.so
             bea18160  bea1816c  [stack]
             bea18164  bea18180  [stack]
             bea18168  6e321dc3  /data/app-lib/com.keytop.ppmo-2/libmediastreamer_voip.so (fake_android::RefBase::incStrong(void const*) const+42)
             bea1816c  68b174cc  
             bea18170  00007200  
             bea18174  60960072  /dev/ashmem/dalvik-mark-stack (deleted)
             bea18178  672798f0  
             bea1817c  bea1819c  [stack]
        #00  bea18180  672798f0  
             ........  ........
        #01  bea18180  672798f0  
             bea18184  6e31e6c9  /data/app-lib/com.keytop.ppmo-2/libmediastreamer_voip.so (fake_android::sp<fake_android::AudioTrack>::assign(fake_android::AudioTrack*)+18)
        #02  bea18188  00000000  
             bea1818c  672798f0  
             bea18190  bea181b0  [stack]
             bea18194  6e3225d7  /data/app-lib/com.keytop.ppmo-2/libmediastreamer_voip.so (fake_android::AudioTrackImpl::init(Library*)+266)
09-05 14:17:38.763 87-87/? I/DEBUG: memory near r1:
        672798d0 006c0046 0000001b 400b7289 400b70cb  
        672798e0 400b7173 400b7121 00000000 0000001b  
        672798f0 6e5782fc 672798d8 00000001 68c025b8  
        67279900 68b17410 0000001b 6289a9a0 0000001e  
        67279910 00000000 00000000 00000001 0000001b  
        67279920 628adbd0 000000aa 00000000 00000000  
        67279930 00000001 0000003b 00000000 40afbedd  
        67279940 40afb609 40afb301 00000000 40afb5a1  
        67279950 40afbb19 00000000 00000000 00000000  
        67279960 00000013 006f0001 006c0046 00000039  
        67279970 401dc1e0 401dc1e0 00000000 68b17410  
        67279980 67279938 00000021 67277a10 00000019  
        67279990 00000000 00000000 68b3a908 00000000  
        672799a0 00000038 0000002a 40290e0c 00000000  
        672799b0 732e6975 415adf68 1d30047a 40290e6c  
        672799c0 68a3b688 00000073 00000028 00000013  
    memory near r2:
        400b70a8 2000e926 46206060 bf00bd10 000078c4  
        400b70b8 4604b510 ffe2f7ff f7fd4620 4620e918  
        400b70c8 b510bd10 1d206844 ea2af7fd f7fd4620  
        400b70d8 f1b0ea28 d1085f80 f04f4621 f7fd4070  
        400b70e8 68a0ea26 68996803 bd104788 6844b510  
        400b70f8 f7fd1d20 4620ea16 ea12f7fd f1b0b138  
        400b7108 d1085f80 4070f04f f7fd4621 68a0ea10  
        400b7118 68996803 bd104788 68186843 30044770  
        400b7128 beb4f003 4604b538 460d3004 ea04f7fd  
        400b7138 d1192801 07d968e3 6823d409 5f80f1b3  
        400b7148 e00cd100 e8bd4620 f0034038 68a0bea7  
        400b7158 694a6801 47904629 07c268e0 68a0d504  
        400b7168 6801b110 4790684a b570bd38 68444605  
        400b7178 4620460e e9e0f7fd d10b2801 463168a0  
        400b7188 68da6803 68e04790 d40307c0 46286829  
        400b7198 4798684b 46314620 4070e8bd bfc2f7ff  
    memory near r5:
        bea1817c bea1819c 672798f0 6e31e6c9 00000000  
        bea1818c 672798f0 bea181b0 6e3225d7 672798d8  
        bea1819c 00000000 00000001 68ae4a68 6e5713dc  
        bea181ac 6e583c78 bea181d8 6e31d555 bea181c8  
        bea181bc 66580518 67276ec0 67276eec 68b55ab0  
        bea181cc 6e578174 68ae4a68 00000000 bea181f0  
        bea181dc 6e3023a9 00000001 6734f368 00000000  
        bea181ec 66580518 bea18208 6e302555 68b55ab0  
        bea181fc 67278aa8 00000000 e1300029 bea18268  
        bea1820c 6e8762db 00000000 67278aa8 00000000  
        bea1821c 00000000 00000000 00000000 00000000  
        bea1822c 00000000 00000000 00000000 00000000  
        bea1823c 00000000 00000000 00000000 5b8f7389  
        bea1824c e6300021 68ca8398 68beb158 a2f00019  
        bea1825c 68b55ab0 67279030 68af6800 bea18280  
        bea1826c 6e8641a3 a2f00019 400a4008 68b3b740  
    memory near r7:
        bea18170 00007200 60960072 672798f0 bea1819c  
        bea18180 672798f0 6e31e6c9 00000000 672798f0  
        bea18190 bea181b0 6e3225d7 672798d8 00000000  
        bea181a0 00000001 68ae4a68 6e5713dc 6e583c78  
        bea181b0 bea181d8 6e31d555 bea181c8 66580518  
        bea181c0 67276ec0 67276eec 68b55ab0 6e578174  
        bea181d0 68ae4a68 00000000 bea181f0 6e3023a9  
        bea181e0 00000001 6734f368 00000000 66580518  
        bea181f0 bea18208 6e302555 68b55ab0 67278aa8  
        bea18200 00000000 e1300029 bea18268 6e8762db  
        bea18210 00000000 67278aa8 00000000 00000000  
        bea18220 00000000 00000000 00000000 00000000  
        bea18230 00000000 00000000 00000000 00000000  
        bea18240 00000000 00000000 5b8f7389 e6300021  
        bea18250 68ca8398 68beb158 a2f00019 68b55ab0  
        bea18260 67279030 68af6800 bea18280 6e8641a3  
    memory near sl:
        67276ecc 00000000 00000000 00000000 00000000  
        67276edc 00000000 68bebe88 00000000 00000000  
        67276eec 689f74b8 00000001 68b55ab0 00000000  
        67276efc 00000000 00000000 00000000 00000000  
        67276f0c 00000000 00000000 00000000 00000000  
        67276f1c 00000000 00000000 00000000 00000000  
        67276f2c 00000000 00000000 00000000 00000000  
        67276f3c 00000000 00000000 00000000 00000000  
        67276f4c 00000000 00000000 00000000 00000000  
        67276f5c 00000000 00000000 00000000 00000000  
        67276f6c 00000000 00000000 00000000 00000000  
        67276f7c 00000000 00000000 00000000 00000000  
        67276f8c 00000000 00000000 00000000 00000000  
        67276f9c 00000000 00000000 00000000 00000000  
        67276fac 00000000 00000000 00000000 00000000  
        67276fbc 00000000 00000000 00000000 00000000  
    memory near ip:
        400bef18 401b96e5 401a014f 401a01b7 401b4561  
        400bef28 401b1634 401b07a0 401b79b1 401b90d9  
        400bef38 40186550 40186530 40186570 40186508  
        400bef48 401865b4 4019bce1 401c8523 401b0e29  
        400bef58 401b68dd 401b9659 401c82af 401b162b  
        400bef68 401bbaed 401ae448 401baed1 401a0d61  
        400bef78 401a0d89 401a0dd1 4019b2d0 401a0d7b  
        400bef88 4019c998 4019c894 401ae2cc 401ae1ac  
        400bef98 40187acd 401a10d9 401adfe4 401bad5f  
        400befa8 4019c670 4019cda4 4019cff0 4019d0dc  
        400befb8 4019cde4 4019cd20 4019ce00 401aef50  
        400befc8 4013c927 401aeb74 4013c919 401ae374  
        400befd8 4019b76c 4019d04c 4019b9b8 4019b9d8  
        400befe8 401ae394 401af7c8 401af7e8 401ae718  
        400beff8 401b9f99 401af7a8 400bf000 00001000  
        400bf008 00000001 0000002d 402360e9 00000000  
    memory near sp:
        bea18160 bea1816c bea18180 6e321dc3 68b174cc  
        bea18170 00007200 60960072 672798f0 bea1819c  
        bea18180 672798f0 6e31e6c9 00000000 672798f0  
        bea18190 bea181b0 6e3225d7 672798d8 00000000  
        bea181a0 00000001 68ae4a68 6e5713dc 6e583c78  
        bea181b0 bea181d8 6e31d555 bea181c8 66580518  
        bea181c0 67276ec0 67276eec 68b55ab0 6e578174  
        bea181d0 68ae4a68 00000000 bea181f0 6e3023a9  
        bea181e0 00000001 6734f368 00000000 66580518  
        bea181f0 bea18208 6e302555 68b55ab0 67278aa8  
        bea18200 00000000 e1300029 bea18268 6e8762db  
        bea18210 00000000 67278aa8 00000000 00000000  
        bea18220 00000000 00000000 00000000 00000000  
        bea18230 00000000 00000000 00000000 00000000  
        bea18240 00000000 00000000 5b8f7389 e6300021  
        bea18250 68ca8398 68beb158 a2f00019 68b55ab0  
    code around pc:
        40186538 e1910f9f e080c003 e1812f9c e3520000  
        40186548 1afffffa e12fff1e e1a03000 f57ff05f  
        40186558 e1930f9f e2801001 e1832f91 e3520000  
        40186568 1afffffa e12fff1e e1a03000 f57ff05f  
        40186578 e3e02000 e1930f9f e080c002 e1831f9c  
        40186588 e3510000 1afffffa e12fff1e e1a03000  
        40186598 f57ff05f e1910f9f e000c003 e1812f9c  
        401865a8 e3520000 1afffffa e12fff1e e1a03000  
        401865b8 f57ff05f e1910f9f e180c003 e1812f9c  
        401865c8 e3520000 1afffffa e12fff1e 6883b508  
        401865d8 47984608 2140ea6f ea801840 eb023290  
        401865e8 ea831302 bd082093 2203b5f8 46046943  
        401865f8 43726846 0f92ebb3 0076d923 46302104  
        40186608 ec50f7ff b1e04605 1e772200 6821e011  
        40186618 3022f851 6858e00a e00cf8d3 0c00ea07  
        40186628 102cf855 f84560d9 4673302c d1f22b00  
    code around lr:
        400b70b4 000078c4 4604b510 ffe2f7ff f7fd4620  
        400b70c4 4620e918 b510bd10 1d206844 ea2af7fd  
        400b70d4 f7fd4620 f1b0ea28 d1085f80 f04f4621  
        400b70e4 f7fd4070 68a0ea26 68996803 bd104788  
        400b70f4 6844b510 f7fd1d20 4620ea16 ea12f7fd  
        400b7104 f1b0b138 d1085f80 4070f04f f7fd4621  
        400b7114 68a0ea10 68996803 bd104788 68186843  
        400b7124 30044770 beb4f003 4604b538 460d3004  
        400b7134 ea04f7fd d1192801 07d968e3 6823d409  
        400b7144 5f80f1b3 e00cd100 e8bd4620 f0034038  
        400b7154 68a0bea7 694a6801 47904629 07c268e0  
        400b7164 68a0d504 6801b110 4790684a b570bd38  
        400b7174 68444605 4620460e e9e0f7fd d10b2801  
        400b7184 463168a0 68da6803 68e04790 d40307c0  
        400b7194 46286829 4798684b 46314620 4070e8bd  
        400b71a4 bfc2f7ff 4604b570 460e3004 e9baf7fd  
09-05 14:17:38.913 407-428/system_process I/BootReceiver: Copying /data/tombstones/tombstone_01 to DropBox (SYSTEM_TOMBSTONE)`

**Comment by Viish** [comment]
This issue has been solved in latest versions of linphone-android.

**Comment by Viish** [comment]
I believe the 4.0 doesn't have this issue.
