### ISSUE TITLE
get the "tag" of an address

### ISSUE THREAD

**Issue by ahna92** [BelledonneCommunications/linphone-android#357]
As the sip packet below show we have a `tag` in the `from` of the packet  , 

`From: Alice <sip:alice@atlanta.com>;tag=1928301774`

in the library I have tried number of functions to get it that none worked as following ; 

`call.getRemoteAddress().getHeader("tag")`
`call.getRemoteAddress().getParam("tag")`
`call.getRemoteAddress().asString()`

`INVITE sip:bob@biloxi.com SIP/2.0
      Via: SIP/2.0/UDP pc33.atlanta.com;branch=z9hG4bK776asdhds
      Max-Forwards: 70
      To: Bob <sip:bob@biloxi.com>
      From: Alice <sip:alice@atlanta.com>;tag=1928301774
      Call-ID: a84b4c76e66710@pc33.atlanta.com
      CSeq: 314159 INVITE
      Contact: <sip:alice@pc33.atlanta.com>
      Content-Type: application/sdp
      Content-Length: 142`

**Comment by Viish** [comment]
SDK issue, not Android
