### ISSUE TITLE
Multiple registration requests are sent to server

### ISSUE THREAD

**Issue by AndroidDeveloperGit** [BelledonneCommunications/linphone-android#358]
Hi all,

We have configured Linphone Library in our android application for audio calls. At the time of registration, the app is sending a huge number of register requests without waiting for a response and as a result, a lot of registrations for same sip_id are happening. Is there a way where we can send only one register request at a time and wait for a response before sending another request ?  The log traces are attached for a better understanding. Any kind of suggestions are welcomed. 

Thanks.

[log_trace.docx](https://github.com/BelledonneCommunications/linphone-android/files/2383342/log_trace.docx)

**Comment by Viish** [comment]
It looks like you have multiple proxy configs with the same account.
