### ISSUE TITLE
Can't Dial Out of Address Book

### ISSUE THREAD

**Issue by muellert** [BelledonneCommunications/linphone-android#360]
When I try to dial from an address book entry, Linphone displays

sip:tel:%2B01234...

and refuses to dial the "malformed" number, instead of just understanding that it should dial +01234...

Therefore, I always have to copy the number manually, then paste it into Linphone.

It would be much better if Linphone knew that it is supposed to dial +01234...

I am using Linphone 3.3.2.

**Comment by Viish** [comment]
I think the problem is your phone number starts with "tel:", because it works perfectly fine on all devices we tested.
Have you tried the latest version of linphone-android (4.0.1) ?

**Comment by muellert** [comment]
Thanks for the hint! For some odd reason, the Play store does not think that I can upgrade, and only offers me to uninstall or open the app, so I didn't notice there was a new version. Just a manual comparison between the entry in the "About" menu and the version displayed in the Play store indicates that I am running outdated software.
