### ISSUE TITLE
How to Capture Live Incoming Voice Stream ?

### ISSUE THREAD

**Issue by AhmadKhattak** [BelledonneCommunications/linphone-android#362]
Hi,

Does anybody know where in the code the incoming voice stream is being passed as a buffer to the speaker on the android phone ? So that I can capture the live incoming voice stream/buffer and record it to an audio file (.wav) for processing while the call is ongoing.

Thank you !

**Comment by Viish** [comment]
You should take a look at mediastreamer2 project.
