### ISSUE TITLE
Not receiving early media

### ISSUE THREAD

**Issue by lameventanas** [BelledonneCommunications/linphone-android#364]
I recently came across this:
http://www.belledonne-communications.com/uploads/images/Solutions-IntercomSystems.pdf

However, when testing linphone on android, it doesn't show the early media (video) from my application.
I'm not sure if this is not implemented, or not working correctly.

**Comment by Viish** [comment]
Indeed the library does support early media but the feature hasn't been implemented in the android app yet.

**Comment by Viish** [comment]
I've started doing it on the branch feature/release-4.1-early-media, but we've found some issues in the library. 
It will be properly done for the 4.1 release.
