### ISSUE TITLE
Cannot connect using a VPN

### ISSUE THREAD

**Issue by c904370** [BelledonneCommunications/linphone-android#366]
Hi guys,

Linphone cannot connect when I use a VPN. I guess it tries to use local DNS servers and not the VPN.
I have no issues with other applications (e.g. Signal, Viber and pretty much any other app including VoIP, messaging and general-purpose apps).

I've tested this on several devices with Android 5, 6 and 7 - the result is the same.
The VPN which I use is a custom OpenVPN server, but if I use a free ProtonVPN account - the result is the same (you can test it with free ProtonVPN account in order to reproduce it).

OpenVPN is set to not bypass the VPN for local networks.
ProtonVPN is set to prevent DNS leaks.

Unfortunately - not being able to work with VPN is a huge show-stopper. 
Hopefully you can try and resolve this issue.

**Comment by Dilbert66** [comment]
I use Linphone-Android with a VPN all the time. PIA, Openvpn, etc. No issues.  Currently I'm using the latest version from the Git repository.  You might want to give the developers more info such as the back end VOIP server you use, protocol, ports, etc.

**Comment by c904370** [comment]
Hi,

I use the Linphone sip server.

@Dilbert66, does your VPN prevent LAN connections?

I guess the issue is that the Linphone client tries to use the LAN DNS servers and not the servers pushed by the VPN client. As the VPN prevent traffic leakage - the local DNS servers are not reachable.

**Comment by Dilbert66** [comment]
Yes, my VPN prevents local LAN connections. (it's setable in the vpn app). Why do you think the client tries to use lan dns? That's a phone os issue, not the client.

**Comment by c904370** [comment]
Well, there are no DNS requests for linphone's SIP servers over VPN when I use a custom OpenVPN server. Also, when LAN connections are allowed - the client connects successfully. 

It is not an OS issue, ass every other app is working just fine with VPN - SIP clients, different messenger apps etc. They succesfully use the DNS servers, pushed by the VPN server.

**Comment by Viish** [comment]
Hi,
This should be fixed with a recent SDK.

**Comment by 2dengine** [comment]
I am also having trouble using Linphone alongside with my VPN. Linphone works fine when just one of my devices is using a VPN, but when both devices are using a VPN then a call/connection cannot be established. I understand that this may not be an issue with the application, but any ideas would be greatly appreciated.
Thank you for all of your hard work!

**Comment by Viish** [comment]
@2dengine, please open a new issue with SDK logs for both devices.
