### ISSUE TITLE
Inconsistent behaviour in Linphone 4.0.1 regarding retrying INVITEs which get a 302 response

### ISSUE THREAD

**Issue by ghrst** [BelledonneCommunications/linphone-android#369]
- In Linphone 3.3.0 when you send an INVITE message and server responds with 302, Linphone automatically retries the request with a new INVITE to the server that is specified in Contact header field of 302. It sends a completely new INVITE with no Proxy-Authorization.

- In Linphone 4.0.1 when Linphone retries the request (to a 302) it sends a Proxy-Authorization header which belongs to the previous INVITE and contains address and information of that server. This causes the server to respond with a 403 Not Relaying!

**Comment by Viish** [comment]
SDK issue, not Android
