### ISSUE TITLE
Removing Status Fragment

### ISSUE THREAD

**Issue by nigehban** [BelledonneCommunications/linphone-android#37]
Sorry to bother

Not sure that this is the right place to ask but anyway. I am trying to remove status fragment from everywhere except in side menu where you can check whether you're online or not. I could not figure out the correct way. Could you give me some clue ? Whenever I remove it from a layout and its activity related java file the whole android project crashes on the phone.

Thanks for your help.

**Comment by DatBewar** [comment]
Hello,
Status fragment is on somes other fragment on Linphone Android, so you need to remove all reference of Status fragment on others and it will be good.

Example here:
https://github.com/BelledonneCommunications/linphone-android/blob/master/src/org/linphone/LinphoneActivity.java#L330
