### ISSUE TITLE
Speaker don't work in second Call

### ISSUE THREAD

**Issue by Kadanza** [BelledonneCommunications/linphone-android#372]
Speaker don't work correctly. When i have  first call Speaker work correctly, but next calls don't have activated Speaker, only muted voice! If reload application first can  call work with Speaker.  I think problem in library linphone! 

Problem in method linphoneCore.enableSpeaker(bl);

I use last linphone SDK for Android 
http://linphone.org/releases/android/liblinphone-android-sdk-latest.zip

**Comment by Viish** [comment]
Hi,
What device do you have? Is it an Android GO version ?
Thanks in advance for the info.
