### ISSUE TITLE
Get Register Number Password

### ISSUE THREAD

**Issue by cardinaltm** [BelledonneCommunications/linphone-android#373]
Hello,
We have a our api service, and we need to get username and password for api authorize
how can i get user password?

this code get only username
`String username = this.username.getText().toString();`
`ProxyConfig lpc = LinphoneManager.getLc().createProxyConfig();`
`username = lpc.normalizePhoneNumber(username);`
`---->>> username.toLowerCase(Locale.getDefault());`

**Comment by Viish** [comment]
You can't get password from API, only ha1.
If you want to store it after user entered it, you have to do it yourself.
