### ISSUE TITLE
 Could not find multidex.jar (com.android.support:multidex:1.0.2)

### ISSUE THREAD

**Issue by vaiden** [BelledonneCommunications/linphone-android#381]
While running `make liblinphone-android-sdk` I get the following error:

> \* What went wrong:
> Could not resolve all files for configuration ':liblinphone-sdk:releaseCompileClasspath'.
> \> Could not find multidex.jar (com.android.support:multidex:1.0.2).
>   Searched in the following locations:
>       https://jcenter.bintray.com/com/android/support/multidex/1.0.2/multidex-1.0.2.jar

This happens on the 3.4.1 release as well as the current master.

**Comment by vaiden** [comment]
Well - apparently on the latest build tools, the Google maven repository has to appear first in each repository list on every build.gradle. 

I've created a PR:
https://github.com/BelledonneCommunications/linphone-android/pull/382

**Comment by Viish** [comment]
Hi @vaiden,
Where did you find the info about the google repository needed to be first ?
Thanks.

**Comment by vaiden** [comment]
@Viish here is one example: https://stackoverflow.com/a/50794342/606351

**Comment by Viish** [comment]
Problem has been solved in feature/release-4.1 branch
