### ISSUE TITLE
 Build failed with an exception.

### ISSUE THREAD

**Issue by attiqueullah** [BelledonneCommunications/linphone-android#383]
Hi , I am facing constantly this error and cant able to resolved please help me in this regard to resolve this issue 
FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type FileHasher using GradleUserHomeScopeServices.createCachingFileHasher().

**Comment by jfalexvijay** [comment]
I am getting the same issue...

@attiqueullah how did you fix this issue ?
