### ISSUE TITLE
git submodule update --init --recursive failed

### ISSUE THREAD

**Issue by cnscns** [BelledonneCommunications/linphone-android#385]
git submodule update --init --recursive
Initialized empty Git repository in /root/linphone-android/submodules/externals/speex/.git/
error: Failed connect to gitlab.linphone.org:443; Operation now in progress while accessing https://gitlab.linphone.org/BC/public/external/speex.git/info/refs

fatal: HTTP request failed
Clone of 'https://gitlab.linphone.org/BC/public/external/speex.git' into submodule path 'submodules/externals/speex' failed

Can mirror the dependent submodules repertory to github?

**Comment by DevFlagship** [comment]
try remove folder, then
`git://git.linphone.org/linphone-android.git --recursive`

**Comment by cnscns** [comment]
If mirroring all submodule s from git.linphone.org to github, I think the error will disappear:)
