### ISSUE TITLE
Build failed with an exception.  * What went wrong: path may not be null or empty string. path=''  

### ISSUE THREAD

**Issue by AhmadKhattak** [BelledonneCommunications/linphone-android#386]
Hi All,

I'm trying to run this linphone in android studio. I've downloaded the github code using git clone and then using Android Studio Opened an Existing Project, and the title is the error i'm facing.

Can anybody guide regarding the solution to this error ? (its a MacOS Environment)

**Comment by cnscns** [comment]
you must follow the steps


    Download the latest Android sdk with platform-tools and tools updated to latest revision, then add both 'tools' and 'platform-tools' folders in your path and the android-sdk folder to ANDROID_HOME environment variable.

    Download the latest Android NDK from google and add it to your path (no symlink !!!) and ANDROID_NDK environment variable.

    Install yasm, nasm (For OpenH224 support only), python, pkg_config, doxygen, graphviz and cmake(>=3.12).

    On 64 bits linux systems you'll need the ia32-libs package.
    With the latest Debian (multiarch), you need this:
        dpkg --add-architecture i386
        aptitude update
        aptitude install libstdc++6:i386 libgcc1:i386 zlib1g:i386 libncurses5:i386

    Run ./prepare.py in the top level directory. This will configure the build and generate a Makefile in the top level directory. Some options can be passed to choose what you want to include in the build and the platforms for which you want to build. Use ./prepare.py --help to see what these options are.

    Run the Makefile script in the top level directory, make.

**Comment by cnscns** [comment]
After making successfully using AndroidStudio open the project and build
