### ISSUE TITLE
videocall error

### ISSUE THREAD

**Issue by fachridjal** [BelledonneCommunications/linphone-android#388]
error on  callvideofragment.java
 LinphoneManager.getLc().setNativeVideoWindowId(mVideoView);
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285] Runtime aborting...
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285] Aborting thread:
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285] "main" prio=5 tid=1 Native
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   | group="" sCount=0 dsCount=0 obj=0x740b6f50 self=0xf411c000
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   | sysTid=22920 nice=0 cgrp=apps sched=0/0 handle=0xf7740160
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   | state=R schedstat=( 4712017375 1065648715 5748 ) utm=382 stm=89 core=1 HZ=100
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   | stack=0xff290000-0xff292000 stackSize=8MB
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   | held mutexes= "abort lock" "mutator lock"(shared held)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #00 pc 00005923  /system/lib/libbacktrace_libc++.so (_ZN13UnwindCurrent6UnwindEjP8ucontext+83)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #01 pc 00002e52  /system/lib/libbacktrace_libc++.so (_ZN9Backtrace6UnwindEjP8ucontext+34)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #02 pc 003c9f48  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiPKcPNS_6mirror9ArtMethodE+136)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #03 pc 00392f6d  /system/lib/libart.so (_ZNK3art6Thread4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+285)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #04 pc 003766b7  /system/lib/libart.so (_ZN3art10AbortState4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+1031)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #05 pc 00376a9e  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+126)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #06 pc 000eb3c4  /system/lib/libart.so (_ZN3art10LogMessageD1Ev+1668)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #07 pc 00100bd8  /system/lib/libart.so (_ZN3artL8JniAbortEPKcS1_+1656)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #08 pc 0010150f  /system/lib/libart.so (_ZN3art9JniAbortFEPKcS1_z+111)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #09 pc 001018f8  /system/lib/libart.so (_ZN3art11ScopedCheck18CheckVirtualMethodEP8_jobjectP10_jmethodID+408)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #10 pc 001126d0  /system/lib/libart.so (_ZN3art8CheckJNI14CallVoidMethodEP7_JNIEnvP8_jobjectP10_jmethodIDz+144)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #11 pc 000920a6  /data/app/org.arindo.phone-1/lib/x86/libmediastreamer_voip.so (???)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #12 pc 00009619  /data/app/org.arindo.phone-1/lib/x86/libmediastreamer_base.so (ms_filter_call_method+285)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #13 pc 0008d5c8  /data/app/org.arindo.phone-1/lib/x86/libmediastreamer_voip.so (video_stream_set_native_window_id+58)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #14 pc 007a1110  /data/app/org.arindo.phone-1/lib/x86/liblinphone.so (linphone_core_set_native_video_window_id+97)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #15 pc 007ed58a  /data/app/org.arindo.phone-1/lib/x86/liblinphone.so (Java_org_linphone_core_CoreImpl_setNativeVideoWindowId+130)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #16 pc 000e6651  /system/lib/libart.so (art_quick_generic_jni_trampoline+49)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #17 pc 000e3ff8  /system/lib/libart.so (art_quick_invoke_stub+72)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #18 pc 00309746  /system/lib/libart.so (_ZN3art6mirror9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+246)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #19 pc 0040991c  /system/lib/libart.so (artInterpreterToCompiledCodeBridge+124)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #20 pc 00245ad3  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_6mirror9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+467)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #21 pc 0043eda9  /system/lib/libart.so (_ZN3art11interpreterL8DoInvokeILNS_10InvokeTypeE1ELb0ELb0EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+201)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #22 pc 000c0453  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb0ELb0EEENS_6JValueEPNS_6ThreadERNS_12MethodHelperEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_+25203)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #23 pc 0022fb15  /system/lib/libart.so (artInterpreterToInterpreterBridge+245)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #24 pc 00245ad3  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_6mirror9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+467)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #25 pc 0043fb3e  /system/lib/libart.so (_ZN3art11interpreterL8DoInvokeILNS_10InvokeTypeE4ELb0ELb0EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+270)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #26 pc 000c016b  /system/lib/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb0ELb0EEENS_6JValueEPNS_6ThreadERNS_12MethodHelperEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_+24459)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #27 pc 0022f294  /system/lib/libart.so (_ZN3art11interpreter24EnterInterpreterFromStubEPNS_6ThreadERNS_12MethodHelperEPKNS_7DexFile8CodeItemERNS_11ShadowFrameE+196)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #28 pc 00435d48  /system/lib/libart.so (artQuickToInterpreterBridge+888)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #29 pc 000e66e2  /system/lib/libart.so (art_quick_to_interpreter_bridge+34)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   native: #30 pc 007eb4e1  /system/framework/x86/boot.oat (???)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   at org.linphone.core.CoreImpl.setNativeVideoWindowId(Native method)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   at org.linphone.core.CoreImpl.setNativeVideoWindowId(Core.java:3135)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   - locked <0x3dfa5e1f> (a org.linphone.core.CoreImpl)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   at org.linphone.call.CallVideoFragment.onCreateView(CallVideoFragment.java:76)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   at android.app.Fragment.performCreateView(Fragment.java:2053)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   at android.app.BackStackRecord.run(BackStackRecord.java:833)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   at android.os.Handler.handleCallback(Handler.java:739)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   at android.os.Handler.dispatchMessage(Handler.java:95)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   at android.os.Looper.loop(Looper.java:135)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   at android.app.ActivityThread.main(ActivityThread.java:5264)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   at java.lang.reflect.Method.invoke!(Native method)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   at java.lang.reflect.Method.invoke(Method.java:372)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
11-02 13:31:26.431 22920-22920/org.arindo.phone A/art: art/runtime/runtime.cc:285] Dumping all threads without appropriate locks held: thread list lock mutator lock

**Comment by Viish** [comment]
What object is mVideoView ? With latest linphone you must use a TextureView.
See https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Android%20TextureView%20Display/
