### ISSUE TITLE
error: cannot find symbol variable rootca

### ISSUE THREAD

**Issue by hadidez** [BelledonneCommunications/linphone-android#39]
hi, i clone the project from git clone git://git.linphone.org/linphone-android.git --recursive and just open android studio and syncthe project with no error. when try to run project it show me this error. thnks

**Comment by DatBewar** [comment]
Hello,
did you execute prepare.py script before trying to run project?

**Comment by hadidez** [comment]
thanks.it solved!

**Comment by deepak2503** [comment]
Hello,
I am facing some issue when using make for building linphone-android on mac can you plz help

I am getting this

4 errors generated.
make[6]: *** [src/CMakeFiles/bellesip-static.dir/belle_sip_resolver.c.o] Error 1
make[5]: *** [src/CMakeFiles/bellesip-static.dir/all] Error 2
make[4]: *** [all] Error 2
make[3]: *** [/Users/deep/Desktop/Projects/linphone-android/WORK/android-arm64/Stamp/EP_bellesip/EP_bellesip-build] Error 2
make[2]: *** [CMakeFiles/EP_bellesip.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [arm64-build] Error 2

on  running make after ./prepare.py

**Comment by qiLingLingYi** [comment]
hello，I clone the linphone-android using git://git.linphone.org/linphone-android.git --recursive, and then import the project to Android studio.  The following error occurred: error: cannot find symbol variable rootca. I have already execute prepare.py script before trying to run project, but it doesn't work, Does anyone know how to fix this? thanks~

**Comment by abdelkader-brahem** [comment]
how execute prepare.py sous windows
