### ISSUE TITLE
Sound Volume Low in Samsung A5 with Android 8.0

### ISSUE THREAD

**Issue by chih87s** [BelledonneCommunications/linphone-android#393]
4.0.1 version
the sound volume is pretty low and I almost cannot heard anything. Moreover, the echo is too loud. For other brand devices, no similar issue. And even, it never happened on Samsung A5 with Android 7.0

**Comment by msh-nayan** [comment]
Hello @chih87s
I'm using LinphoneSDK 3.2.1 on my app for SIP Video call. I'm testing my app on various devices. But for particular Samsung devices (a. Galaxy S5, Model Number : SM-G900K, Android version 6.0.1 b. Galaxy A5 Plus, Android version 8.0.) I can't see any video on my rendering view. Plus I can't hear any sound from the other end. Meanwhile if the other side of the phone (I've tested on Huawei), can hear my voice + see me on rendering view.

I've checked Linphone app from Play Store (version 4.0.1), I noticed the same issue. While video call, I can see my preview but can't see the video on rendering view (the other person of the call on opposite end). Did You encounter any problem ? Any solution ?

**Comment by Viish** [comment]
This looks like very specific to your device.
You can increase the playback gain (and mic gain) from the config file, in the [sound] section:
playback_gain_db=0
mic_gain_db=0

**Comment by sushilsolanki8875** [comment]
@Viish I'm still getting low volume in some Android Phones. I'm using the below sound settings.
```
[sound]
echocancellation=1
playback_gain_db=0
mic_gain_db=0
agc=1
mic_gain=1.0
```
is there any other setting?

**Comment by Viish** [comment]
No, those are the correct settings. However values are "wrong". If you want to increase the volume, don't set the value to 0 but higher (unit is decibels).

**Comment by sushilsolanki8875** [comment]
@Viish what is the best values? Can you please give me it?

**Comment by Viish** [comment]
There are no "best values". 0 means no gain, but if the output is too low you can increase the value 1 by 1 until it is ok for you.

**Comment by sushilsolanki8875** [comment]
Ok Thanks @Viish

**Comment by sushilsolanki8875** [comment]
Hi @Viish, I set the mic gain = 1.0 and playback_gain=8.0 but some Samsung devices still have low volume? any Idea to improve volume?
