### ISSUE TITLE
CoreListenerStub()

### ISSUE THREAD

**Issue by chih87s** [BelledonneCommunications/linphone-android#394]
The below is an example. I don't know why **onRegistrationStateChanged** doesn't work

private CoreListenerStub mListener;

mListener = new CoreListenerStub(){
            @Override
            public void onRegistrationStateChanged(Core lc, ProxyConfig cfg, RegistrationState cstate, String message) {
                Timber.d("---------");
            }
        };

**Comment by Viish** [comment]
Did you add the listener to the core using something like mCore.addListener(mListener) ?
