### ISSUE TITLE
Oreo adaptive icon shape

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [BelledonneCommunications/linphone-android#395]
Please add support for icon shape
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html
https://material.io/guidelines/style/icons.html

you should fix it to upload new version to google play
https://www.xda-developers.com/google-play-app-updates-must-target-android-8-0/

**Comment by Viish** [comment]
The adaptive icon isn't mandatory to target Android 8 and newer. By the way, we already target Android 8.
Anyway I've added the adaptive icon in commit b3a13690d72d5b002827ce1ce030a40a6ebb2dbb.
