### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by johnpiao305** [BelledonneCommunications/linphone-android#398]
Cause: path may not be null or empty string. path=''

**Comment by mehran22k** [comment]
did you run ./prepare.py and make ?

**Comment by johnpiao305** [comment]
how can i run this file ( ./prepare.py) ? can you explain ?
I just try to build in android studio.

**Comment by mehran22k** [comment]
just read the Readme.md file in your root folder of project. or you can see the instruction [here](https://github.com/BelledonneCommunications/linphone-android#readme)


consider this that you have to build it on linux. 



after build, then you can try to import it in Adnroid studio

**Comment by ezechinwa** [comment]
mehran22k, I am also having similar problems, importing a project should not be this difficult, and the setup process is too technical for beginners like me, is there a possibility to find the built version of this project that can be easily imported without following this approach? or can you link us to a video tutorial that shows the step by step process of setting this up on Android Studio, thanks?

**Comment by mehran22k** [comment]
Hi ezechinwa, there is no step by step tutorial to build or import it in android. however if you find the build version, then its not work or build again when you customize it...

the best step by step tutorial is Readme.md .

 cuz of there is some packages and library that you have to install on your machine (Linux like Ubuntu) then you can build it.
