### ISSUE TITLE
app crash on android lower than 6, or it seems to app not work with cpu armeabi-v7a

### ISSUE THREAD

**Issue by mehran22k** [BelledonneCommunications/linphone-android#399]
Hi
first i clone master branch successfully
then i change the version of gradle  to last:
distributionUrl=https\://services.gradle.org/distributions/**gradle-4.10.2-all**.zip

then run **./prepare.py all** and after that **make**
the project make successfully
then i import app in android studio (Linux - ubuntu) and run it with 3 real device:

1: andoid 6 , cpu ==> arm64-v8a :  **run successfully**  
2: tablet , android 4.4  ,cpu ==> armeabi-v7a : **app crashed** and not open 
2:  android 5.0  ,cpu ==>  armeabi-v7a : **app crashed** and not open 

it seems to my build not work with devices with  armeabi-v7a

what should i do
please help
thank you

**Comment by mehran22k** [comment]
here is my **debug** log  for android 5.1




11/11 23:57:08: Launching linphone-android
$ adb shell am start -n "org.linphone/org.linphone.activities.LinphoneLauncherActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Connecting to org.linphone
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/ActivityThread: Application org.linphone is waiting for the debugger on port 8100...
I/System.out: Sending WAIT chunk
I/art: Debugger is active
I/System.out: Debugger has connected
    waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
Connected to the target VM, address: 'localhost:8600', transport: 'socket'
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1402)
I/MultiDex: VM with version 2.1.0 has multidex support
    Installing application
    VM has multidex support, MultiDex support library is disabled.
I/InstantRun: starting instant run server: is main process
V/Monotype: SetAppTypeFace- try to flip, app = org.linphone
V/Monotype:     Typeface getFontPathFlipFont - systemFont = default#default
V/Monotype: SetAppTypeFace- try to flip, app = org.linphone
        Typeface getFontPathFlipFont - systemFont = default#default
D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
W/linker: libc++_shared.so: unused DT entry: type 0x6ffffffe arg 0x2b994
W/linker: libc++_shared.so: unused DT entry: type 0x6fffffff arg 0x2
W/FactoryImpl: Unable to load optional library ffmpeg-linphone: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.linphone-1/base.apk", zip file "/data/app/org.linphone-1/split_lib_dependencies_apk.apk", zip file "/data/app/org.linphone-1/split_lib_slice_0_apk.apk", zip file "/data/app/org.linphone-1/split_lib_slice_1_apk.apk", zip file "/data/app/org.linphone-1/split_lib_slice_2_apk.apk", zip file "/data/app/org.linphone-1/split_lib_slice_3_apk.apk", zip file "/data/app/org.linphone-1/split_lib_slice_4_apk.apk", zip file "/data/app/org.linphone-1/split_lib_slice_5_apk.apk", zip file "/data/app/org.linphone-1/split_lib_slice_6_apk.apk", zip file "/data/app/org.linphone-1/split_lib_slice_7_apk.apk", zip file "/data/app/org.linphone-1/split_lib_slice_8_apk.apk", zip file "/data/app/org.linphone-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/org.linphone-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libffmpeg-linphone.so"
W/linker: libbctoolbox.so: unused DT entry: type 0x6ffffffe arg 0x1045c
    libbctoolbox.so: unused DT entry: type 0x6fffffff arg 0x2
W/linker: libortp.so: unused DT entry: type 0x6ffffffe arg 0x849c
    libortp.so: unused DT entry: type 0x6fffffff arg 0x3
W/linker: libmediastreamer.so: unused DT entry: type 0x6ffffffe arg 0x47634
    libmediastreamer.so: unused DT entry: type 0x6fffffff arg 0x3
W/linker: liblinphone.so: unused DT entry: type 0x6ffffffe arg 0x5055a0
    liblinphone.so: unused DT entry: type 0x6fffffff arg 0x3
Disconnected from the target VM, address: 'localhost:8600', transport: 'socket'

**Comment by Viish** [comment]
Can you try again with commit f332bef5ed95961b6845d9ada93c34fa038df288 please ?

**Comment by mehran22k** [comment]
Hi, thanks a lot @Viish 
it work now
this commit save my time...
