### ISSUE TITLE
LIME V1 and V2 Build Error

### ISSUE THREAD

**Issue by AmrAshraf** [BelledonneCommunications/linphone-android#400]
Hello all,

When i tried to compile the linphone 4.1 with the submodules it brings me the following error: 

```
[ 96%] Performing configure step for 'EP_linphone'
...
 Lime V1 and V2 cannot be used simultaneously


-- Configuring incomplete, errors occurred!
See also "/home/user/LinphoneAndroid4.1/linphone-android/WORK/android-arm64/Build/linphone/CMakeFiles/CMakeOutput.log".
CMakeFiles/EP_linphone.dir/build.make:117: recipe for target '/home/user/LinphoneAndroid4.1/linphone-android/WORK/android-arm64/Stamp/EP_linphone/EP_linphone-configure' failed
make[3]: *** [/home/user/LinphoneAndroid4.1/linphone-android/WORK/android-arm64/Stamp/EP_linphone/EP_linphone-configure] Error 1
make[3]: Leaving directory '/home/user/LinphoneAndroid4.1/linphone-android/WORK/android-arm64/cmake'
CMakeFiles/Makefile2:77: recipe for target 'CMakeFiles/EP_linphone.dir/all' failed
make[2]: *** [CMakeFiles/EP_linphone.dir/all] Error 2
make[2]: Leaving directory '/home/user/LinphoneAndroid4.1/linphone-android/WORK/android-arm64/cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/user/LinphoneAndroid4.1/linphone-android/WORK/android-arm64/cmake'
Makefile:215: recipe for target 'arm64-build' failed
make: *** [arm64-build] Error 2
```
So how i can disable LIME V1 or V2 ?

**Comment by Viish** [comment]
Hi @AmrAshraf,
release/4.1 is a dev branch but if you want to compile it you have to give the following options to prepare.py (until we improve this): -DENABLE_LIME=OFF -DENABLE_LIME_X3DH=YES

**Comment by issamux** [comment]
> Hi @AmrAshraf,
> release/4.1 is a dev branch but if you want to compile it you have to give the following options to prepare.py (until we improve this): -DENABLE_LIME=OFF -DENABLE_LIME_X3DH=YES

can't build ...i have this error ...

Cloning into 'EP_lime'...
gitosis@git.linphone.org: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
-- Had to git clone more than once:
          3 times.
CMake Error at /Users/merrou/Workspaces/linphone-ws/linphone-android/WORK/android-x86/tmp/EP_lime/EP_lime-gitclone.cmake:66 (message):
  Failed to clone repository: 'gitosis@git.linphone.org:lime.git'

**Comment by issamux** [comment]
i don't know if this is correct but i ve replaced in EP_lime-gitclone.cmake 
`gitosis@git.linphone.org:lime.git`
by 
`https://gitlab.linphone.org/BC/public/lime.git`
