### ISSUE TITLE
LinphoneCoreListenerBase not response

### ISSUE THREAD

**Issue by dev-sachin** [BelledonneCommunications/linphone-android#403]
Hello,

I am trying to connect to my sip server with linphone SDK using the following code but after registration, it not responded any method in its LinphoneCoreListenerBase.

public void saveCreatedAccount(String username, String userid, String password, String displayname,
                                   String ha1, String prefix, String domain, LinphoneAddress.TransportType transport) {
        username = LinphoneUtils.getDisplayableUsernameFromAddress(username);
        domain = LinphoneUtils.getDisplayableUsernameFromAddress(domain);

        String identity = "sip:" + username + "@" + domain;
        Log.e("MainActivity", "Identity : " + identity);
        try {
            address = LinphoneCoreFactory.instance().createLinphoneAddress(identity);
        } catch (LinphoneCoreException e) {
            org.linphone.mediastream.Log.e(e);
        }

        LinphonePreferences.AccountBuilder builder = new LinphonePreferences.AccountBuilder(LinphoneManager.getLc())
                .setUsername(username)
                .setDomain(domain)
                .setHa1(ha1)
                .setUserId(userid)
                .setDisplayName(displayname)
                .setPassword(password);

        if (prefix != null) {
            builder.setPrefix(prefix);
        }

        String forcedProxy = "";
        if (!TextUtils.isEmpty(forcedProxy)) {
            builder.setProxy(forcedProxy)
                    .setOutboundProxyEnabled(true)
                    .setAvpfRRInterval(5);
        }
        if (transport != null) {
            builder.setTransport(transport);
        }

        try {
            builder.saveNewAccount();
            if (!newAccount) {
                Log.e("MainActivity","Registration Started");
                displayRegistrationInProgressDialog();
            }
            accountCreated = true;
        } catch (LinphoneCoreException e) {
            org.linphone.mediastream.Log.e(e);
        }
    }

mListener = new LinphoneCoreListenerBase() {
            @Override
            public void configuringStatus(LinphoneCore lc, final LinphoneCore.RemoteProvisioningState state, String message) {
                Log.e("MainActivity","Configuration Status");
            }

            @Override
            public void registrationState(LinphoneCore lc, LinphoneProxyConfig cfg, LinphoneCore.RegistrationState state, String smessage) {
                Log.e("MainActivity","Success Registration State " + state);
                if (state == LinphoneCore.RegistrationState.RegistrationOk) {
                    success();
                }
            }
        };

**Comment by dev-sachin** [comment]
Yes, I added the listener to the LinphoneCore.

**Comment by Viish** [comment]
Did you add the the proxy config to the core ? Did you enable the register on the proxy config ? Is the core started and called on it's iterate() method on a regular basis ?

**Comment by dev-sachin** [comment]
Yes,  i do it same as Linphone Demo

**Comment by Viish** [comment]
Does Linphone Demo works ?
