### ISSUE TITLE
build issue - libxml2 - android linphone

### ISSUE THREAD

**Issue by marcotessarotto** [BelledonneCommunications/linphone-android#404]
while building "master" branch,
on linux debian 9.5, x86_64, using android platform 28.0.3, ndk r18, all the dependencies installed.

./prepare succeeds,
make: starts building the submodule projects, but when it arrives at libxml2 it gives the following error (attaching complete log file of build):

...
[ 39%] Building C object CMakeFiles/xml2.dir/nanohttp.c.o
[ 41%] Building C object CMakeFiles/xml2.dir/parser.c.o
/home/marco/git/linphone-android/submodules/externals/libxml2/parser.c:90:10: fatal error: 'lzma.h' file not found
#include <lzma.h>
         ^~~~~~~~
1 error generated.

any clue on how to solve this issue?
do I need to build manually xz utils (which contains lzma) and put it in the ndk?

[build-error-android-linphone.txt](https://github.com/BelledonneCommunications/linphone-android/files/2599058/build-error-android-linphone.txt)

**Comment by mehran22k** [comment]
Hi
have you try this?  **git submodule update --init --recursive**

**Comment by marcotessarotto** [comment]
yes, I used this commands before prepare.py and make:

git submodule sync
git submodule update --init --recursive

**Comment by Viish** [comment]
Try to build linphone-sdk directly: https://gitlab.linphone.org/BC/public/linphone-sdk
