### ISSUE TITLE
build linphone-android error

### ISSUE THREAD

**Issue by fengsimon** [BelledonneCommunications/linphone-android#407]
Hello all,

I compile linphone-android error,please help:
****************************************
./gradlew assembleDebug

> Configure project :
[Push Notification] Firebase disabled

> Task :liblinphone-sdk:copyAssets
Syncing sdk assets into root dir /home/fengqz/linphone-android/liblinphone-sdk/bin/sdk-assets/assets/org.linphone.core
Syncing sdk asset share/sounds/linphone/dont_wait_too_long.mkv to share/sounds/linphone/dont_wait_too_long.mkv
Syncing sdk asset share/sounds/linphone/hello16000.wav to share/sounds/linphone/hello16000.wav
Syncing sdk asset share/sounds/linphone/hello8000.wav to share/sounds/linphone/hello8000.wav
Syncing sdk asset share/sounds/linphone/incoming_chat.wav to share/sounds/linphone/incoming_chat.wav
Syncing sdk asset share/sounds/linphone/toy-mono.wav to share/sounds/linphone/toy-mono.wav
Syncing sdk asset share/sounds/linphone/rings/oldphone-mono.wav to share/sounds/linphone/rings/oldphone-mono.wav
Syncing sdk asset share/sounds/linphone/rings/notes_of_the_optimistic.mkv to share/sounds/linphone/rings/notes_of_the_optimistic.mkv
Syncing sdk asset share/sounds/linphone/rings/soft_as_snow.mkv to share/sounds/linphone/rings/soft_as_snow.mkv
Syncing sdk asset share/sounds/linphone/rings/its_a_game.mkv to share/sounds/linphone/rings/its_a_game.mkv
Syncing sdk asset share/sounds/linphone/rings/house_keeping.mkv to share/sounds/linphone/rings/house_keeping.mkv
Syncing sdk asset share/sounds/linphone/rings/four_hands_together.mkv to share/sounds/linphone/rings/four_hands_together.mkv
Syncing sdk asset share/sounds/linphone/rings/leaving_dreams.mkv to share/sounds/linphone/rings/leaving_dreams.mkv
Syncing sdk asset share/sounds/linphone/ringback.wav to share/sounds/linphone/ringback.wav
Syncing sdk asset share/belr/grammars/cpim_grammar to share/belr/grammars/cpim_grammar
Syncing sdk asset share/belr/grammars/vcard_grammar to share/belr/grammars/vcard_grammar
Syncing sdk asset share/linphone/rootca.pem to share/linphone/rootca.pem

> Task :liblinphone-sdk:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :compileDebugJavaWithJavac FAILED
/home/fengqz/linphone-android/src/android/org/linphone/chat/GroupChatFragment.java:611: error: cannot find symbol
            mChatRoomSecurityLevel.setVisibility(View.GONE);
            ^
  symbol:   variable mChatRoomSecurityLevel
  location: class GroupChatFragment
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

thanks.

**Comment by fengsimon** [comment]
why prompt: 
CMake Error at /opt/cmake-3.12.2-Linux-x86_64/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Java (missing: Java_JAVAC_EXECUTABLE Java_JAR_EXECUTABLE
  Java_JAVADOC_EXECUTABLE Development) (found version "10.0.2")

**Comment by Viish** [comment]
Pull to the latest version, this issue has been solved.
