### ISSUE TITLE
Android code source format and code style

### ISSUE THREAD

**Issue by issamux** [BelledonneCommunications/linphone-android#408]
Hi Guys,

I've forked project to make some enhancements and was very surprised !!!! Why you don't follow some good code style and language rules.

Why not making a single commit with all code format and package optimization etc... then other contributors will do so , and we make this code great again :D 

Please please do something about this !!! it's a shame ...

some useful  link : 
- https://source.android.com/setup/contribute/code-style
- https://github.com/google/google-java-format

Or just use for example Android Studio default code formatting ... Please, it will help us a lot,
and you 'll get happy developers involved in your project.

Thanks,

**Comment by Viish** [comment]
Thanks, we'll do something for the next release (4.1)

**Comment by Viish** [comment]
This has been done in
commit 1f6d92b92aff07eba730a4160a7e600981462b8b
Author: Sylvain Berfini <sylvain.berfini@belledonne-communications.com>
Date:   Fri Nov 30 10:31:22 2018 +0100

    Huge code refactoring using google tool
