### ISSUE TITLE
Android app crashes on call pausing , Fatal signal 11 (SIGSEGV), code 1, fault addr 0x68

### ISSUE THREAD

**Issue by shashankkaroo** [BelledonneCommunications/linphone-android#41]
My android app crashes when i call
LinphoneCall call = LinphoneManager.getLc().getCurrentCall();
LinphoneCore lc = LinphoneManager.getLc();
if (call != null && call.getState() != State.Paused) {
lc.pauseCall(call);
} else if (call != null) {
if (call.getState() == State.Paused) {
lc.resumeCall(call);
}
}
}

I am getting a crash which says:

Fatal signal 11 (SIGSEGV), code 1, fault addr 0x68

**Comment by CrabeMan** [comment]
Hello,
Try by replacing your getCurrentCall() by getCalls()[0].

CrabeMan.

**Comment by shashankkaroo** [comment]
Hi CrabeMan.

This may help:

04-28 22:42:15.727 13755-13755/.... A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x68 in tid 13755 (..)
04-28 22:42:15.831 301-301/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-28 22:42:15.831 301-301/? I/DEBUG: Build fingerprint: 'motorola/condor_retaildsds/condor_umtsds:5.1/LPCS23.13-34.8-3/3:user/release-keys'
04-28 22:42:15.831 301-301/? I/DEBUG: Revision: 'p2b0'
04-28 22:42:15.831 301-301/? I/DEBUG: ABI: 'arm'
04-28 22:42:15.831 301-301/? I/DEBUG: pid: 13755, tid: 13755, name: ....
04-28 22:42:15.832 301-301/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x68
04-28 22:42:15.861 301-301/? I/DEBUG:     r0 00000000  r1 b91e36b0  r2 b924bd80  r3 b8da0000
04-28 22:42:15.862 301-301/? I/DEBUG:     r4 00000000  r5 b91e36b0  r6 00000000  r7 b925faf0
04-28 22:42:15.862 301-301/? I/DEBUG:     r8 b924bdb2  r9 b8de2040  sl b906bc80  fp b91503e0
04-28 22:42:15.863 301-301/? I/DEBUG:     ip a564bab8  sp beafdac8  lr a53322ac  pc a51d49ac  cpsr 200d0010
04-28 22:42:15.864 301-301/? I/DEBUG: backtrace:
04-28 22:42:15.865 301-301/? I/DEBUG:     #00 pc 003319ac  /data/app/....-2/lib/arm/liblinphone-armeabi-v7a.so (belle_sip_channel_queue_message+12)
04-28 22:42:15.865 301-301/? I/DEBUG:     #01 pc 0048f2a8  /data/app/......-2/lib/arm/liblinphone-armeabi-v7a.so
04-28 22:42:15.865 301-301/? I/DEBUG:     #02 pc 0032735c  /data/app/.....-2/lib/arm/liblinphone-armeabi-v7a.so (belle_sip_main_loop_run+1188)
04-28 22:42:15.865 301-301/? I/DEBUG:     #03 pc 003274d8  /data/app/....-2/lib/arm/liblinphone-armeabi-v7a.so (belle_sip_main_loop_sleep+64)
04-28 22:42:15.866 301-301/? I/DEBUG:     #04 pc 002aceb8  /data/app/.....-2/lib/arm/liblinphone-armeabi-v7a.so (sal_iterate+12)
04-28 22:42:15.866 301-301/? I/DEBUG:     #05 pc 002df544  /data/app/...../lib/arm/liblinphone-armeabi-v7a.so (linphone_core_iterate+888)
04-28 22:42:15.867 301-301/? I/DEBUG:     #06 pc 000a2fc1  /system/lib/libart.so (art_quick_generic_jni_trampoline+32)
04-28 22:42:15.867 301-301/? I/DEBUG:     #07 pc 001e923d  /system/lib/libart.so (art::mirror::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+152)
04-28 22:42:16.618 847-14464/? W/ActivityManager:   Force finishing activity 1 /.activity.CallOutgoingActivity
04-28 22:42:16.619 301-301/? I/DEBUG: Tombstone written to: /data/tombstones/tombstone_00
04-28 22:42:16.620 847-1123/? I/BootReceiver: Copying /data/tombstones/tombstone_00 to DropBox (SYSTEM_TOMBSTONE)
04-28 22:42:16.645 847-14465/? W/DropBoxManagerService: Dropping: data_app_native_crash (1598 > 0 bytes)
04-28 22:42:16.686 847-1216/? W/InputDispatcher: channel '22db9197 
HomeActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
04-28 22:42:16.687 847-1216/? E/InputDispatcher: channel '22db9197 
HomeActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
04-28 22:42:16.687 847-1216/? W/InputDispatcher: channel 'd54d325 
CallDetailActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
04-28 22:42:16.687 847-1216/? E/InputDispatcher: channel 'd54d325 
CallDetailActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
04-28 22:42:16.687 847-1216/? W/InputDispatcher: channel '3414d011 
CallOutgoingActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
04-28 22:42:16.687 847-1216/? E/InputDispatcher: channel '3414d011 
CallOutgoingActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
04-28 22:42:16.687 847-2631/? D/WifiService: releaseWifiLockLocked: WifiLock{linphonecore [3101532056] wifi-lock type=3 binder=android.os.BinderProxy@bd30c23}
04-28 22:42:16.687 847-5799/? W/AudioService: setMode() client died
04-28 22:42:16.688 847-1561/? E/WifiService: Multicaster binderDied
04-28 22:42:16.688 847-1014/? V/WindowManager: IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
04-28 22:42:16.688 847-1014/? V/WindowManager: IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
04-28 22:42:16.690 847-1123/? W/DropBoxManagerService: Dropping: SYSTEM_TOMBSTONE (10 > 0 bytes)
04-28 22:42:16.699 327-327/? I/Zygote: Process 13755 exited due to signal (11)

**Comment by astuter** [comment]
What was the resolution for this issue?

**Comment by shashankkaroo** [comment]
Hey astuter,
Still facing this issue, my app crashes on pause.

**Comment by swaponsust** [comment]
I got that error too 
The way I solved that error: 

Linphone somehow create two core  objects and when activity finished then this error occurred. 
Need to make sure this and I hope problem will be solved.
