### ISSUE TITLE
Cannot works in Android 8.0

### ISSUE THREAD

**Issue by chih87s** [BelledonneCommunications/linphone-android#411]
I installed app in Android 8.0 but I found the voice quality was pretty bad. But in Android 7.0 no issue. I compared two debug logs between 8.0 and 7.0. There are some differences. Any one could explain for me?

In android 7.0 log, I could see 
Supported codec speex/16000 fmtp=vbr=on automatically added to codec list.
                  Supported codec speex/8000 fmtp=vbr=on automatically added to codec list.
                  Supported codec PCMU/8000 fmtp= automatically added to codec list.
                  Supported codec PCMA/8000 fmtp= automatically added to codec list.
                  Supported codec GSM/8000 fmtp= automatically added to codec list.
                  Supported codec G722/8000 fmtp= automatically added to codec list.
                  
In android 8.0 log, I cannot see above details.

**Comment by chih87s** [comment]
In Android 8.0, the log also shows 

Codec SILK/16000 read from conf is not supported by mediastreamer2, ignored.
Codec iLBC/8000 read from conf is not supported by mediastreamer2, ignored.
Codec iSAC/16000 read from conf is not supported by mediastreamer2, ignored.
Codec SILK/8000 read from conf is not supported by mediastreamer2, ignored.
Codec SILK/12000 read from conf is not supported by mediastreamer2, ignored.
Codec SILK/24000 read from conf is not supported by mediastreamer2, ignored.

**Comment by Viish** [comment]
There is no correlation between the 2 logs you posted, and nothing that can explain why the quality is lower on your Android 8 device.
