### ISSUE TITLE
Build error on SILK

### ISSUE THREAD

**Issue by zilch33** [BelledonneCommunications/linphone-android#412]
Hi,

os:  CentOS Linux release 7.5.1804 (Core)
android build-tools: 28.0.3
platforms: android-28
platform-tools: 28.0.1
android ndk: r18b

execute:
./prepare.py armv7 -DENABLE_SILK=YES
make

I got error:
[ 98%] Building C object CMakeFiles/mssilk.dir/silk_dec.c.o
[ 99%] Building C object CMakeFiles/mssilk.dir/silk_enc.c.o
[100%] Linking C shared module libmssilk.so
/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/unwind-arm-common.inc:855: error: undefined reference to '__cxa_call_unexpected'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[6]: *** [libmssilk.so] Error 1
make[6]: Leaving directory '/usr/local/src/linphone-android/WORK/android-armv7/Build/mssilk' 
make[5]: *** [CMakeFiles/mssilk.dir/all] Error 2 
make[5]: Leaving directory '/usr/local/src/linphone-android/WORK/android-armv7/Build/mssilk' 
make[4]: *** [all] Error 2 
make[4]: Leaving directory '/usr/local/src/linphone-android/WORK/android-armv7/Build/mssilk' 
make[3]: *** [/usr/local/src/linphone-android/WORK/android-armv7/Stamp/EP_mssilk/EP_mssilk-build]  Error 2 
make[3]: Leaving directory '/usr/local/src/linphone-android/WORK/android-armv7/cmake' 
make[2]: *** [CMakeFiles/EP_mssilk.dir/all] Error 2 
make[2]: Leaving directory '/usr/local/src/linphone-android/WORK/android-armv7/cmake' 
make[1]: *** [all] Error 2 
make[1]: Leaving directory '/usr/local/src/linphone-android/WORK/android-armv7/cmake' 
make: *** [armv7-build] Error 2

Please help me to fix this. Thank you.

**Comment by udaykumarkrify** [comment]
usr/local/google/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/unwind-arm-common.inc:855: error: undefined reference to '__cxa_call_unexpected'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/mssilk.dir/build.make:1736: recipe for target 'libmssilk.so' failed
make[8]: *** [libmssilk.so] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/mssilk.dir/all' failed
make[7]: *** [CMakeFiles/mssilk.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make[6]: *** [all] Error 2



Build failed while enalbled silk.

**Comment by Viish** [comment]
Indeed but we haven't planned on fixing it.

**Comment by Viish** [comment]
By the way, just tested with NDK 20 on Fedora 31, compiles just fine.
