### ISSUE TITLE
Build error missing method enableWifiOnly(Boolean)

### ISSUE THREAD

**Issue by issamux** [BelledonneCommunications/linphone-android#413]
Can't build project due to missing method in core : wifiOnlyEnabled and enableWifiOnly 

Log 
`> Task :compileDebugJavaWithJavac FAILED
/Users/merrou/Workspaces/linphone-ws/linphone-android/src/android/org/linphone/LinphonePreferences.java:835: error: cannot find symbol
        return getLc().wifiOnlyEnabled();
                      ^
  symbol:   method wifiOnlyEnabled()
  location: interface Core
/Users/merrou/Workspaces/linphone-ws/linphone-android/src/android/org/linphone/LinphonePreferences.java:841: error: cannot find symbol
        getLc().enableWifiOnly(enable);
               ^
  symbol:   method enableWifiOnly(Boolean)
  location: interface Core
`

**Comment by Viish** [comment]
Simply update your submodules using git submodule update --recursive --init
