### ISSUE TITLE
Linphone calls are not working when app in background 

### ISSUE THREAD

**Issue by bharathikrify** [BelledonneCommunications/linphone-android#415]
Linphone calls are not working when app is in background . 
I am using push notiifcation but the method onMessageReceived() 
is not triggered when my app is in background. 
Any ideas? 
Thanks in advance

**Comment by Viish** [comment]
@bharathikrify Please don't duplicate issues... See my comment in #55

**Comment by MichaelHuy** [comment]
Same with me. Seem, the server is not using push notifications with token device. I using firebase messaging and test send push notification on Firebase console web, my app can receive push well, but not with linphone server
