### ISSUE TITLE
Android Linphone Unknown error - Incompatible, check codecs or security setting... 

### ISSUE THREAD

**Issue by OoChaosoO** [BelledonneCommunications/linphone-android#417]
I have phones and login app linphone with pbx.
case 1
Android to ios can't call phone 1 to phone 2 

case 2
android to android can't call phone 1 to phone 2

case 3
ios to ios can call phone 1 to phone 2

case 4
ios to android can call phone 1 to phone 2

case 1 and case 2 a problem.
Unknown error - Incompatible, check codecs or security setting...

**Comment by Viish** [comment]
Have you checked in the settings that the same codecs are enabled on both sides (at least one in common) ?
You can check the libs logs, it will tell you what the problem is in detail.

**Comment by OoChaosoO** [comment]
I have set the codecs to match and  check log.
Error SipUA_Library: Incompatible SDP answer received, need to abort the call

**Comment by Viish** [comment]
Attach the INVITE and 200 OK packets please.

**Comment by VasoVV** [comment]
I have the same issue. 
I can call successfully to another IP accounts. The issue appears with calls to subscribers that serves by old telephone exchange units of national telephone company.

Here is my log with some privacy replacements:
```
AAAAAAAAA       — my SIP login/phone number
LLL.LLL.LLL.LLL — android's LAN ip address
EEE.EEE.EEE.EEE — WAN ip address
+380512000000   — recipient
```


[linphone.log.gz](https://github.com/BelledonneCommunications/linphone-android/files/2759232/linphone.log.gz)

**Comment by Viish** [comment]
Enable PCMA/PCMU codecs in the audio settings.

**Comment by VasoVV** [comment]
> Enable PCMA/PCMU codecs in the audio settings.

Its enabled by default. Now a have all codecs enabled, but still no luck.
