### ISSUE TITLE
Need to build from source when using push notifications and flexisip?

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#418]
Looking at https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/Configuration/#HConfigureLinphoneAndroid it says:

Configure Linphone Android

Edit the "res/values/non_localizable_custom.xml" file in the Android project and replace the "push_sender_id" value by the <project_number>.

Is that implying that in order to use Linphone on Android with my own flexisip gateway, I need to build my own custom Android Linphone package and can't just use the one from the Google Play store?

**Comment by driesken** [comment]
That's correct. You need to do the same for iOS as well if you plan on rolling out Apple devices.

**Comment by brianjmurrell** [comment]
That seems like a pretty high bar to entry.  Is everyone expected to have and know how to use an Android development studio to build APKs?

Is it really impossible to have the firebase info as a "settings" input in the app?

Given that push notification is really the only workable path forward for VOIP apps, isn't this high bar to entry pretty much signalling the end of the viability of mobile (versions of) VOIP apps?

Maybe I am missing something here.

**Comment by driesken** [comment]
I don't think it's possible to implement the "push_sender_id" as a simple setting within Linphone as it's included in the AndroidManifest. It's also something that should be kept private. Your users could easily read Linphone's settings with adb and send push notifications with that value.

Yes, the compiling of Linphone isn't easy, but it allows you to keep full control of push notifications instead like other VOIP apps that require usage of their own 3rd party push services and charging money over it.

**Comment by Viish** [comment]
@brianjmurrell with the next release of linphone android (4.1) you will only need to push a single button to compile and deploy the app with your changes to your device.

**Comment by brianjmurrell** [comment]
@Viish "push a single button" after I have jumped through all of the hoops of setting up an Android development system?

**Comment by Viish** [comment]
@brianjmurrell Yeah but that is quite simple, simply install Android Studio through your package manager on download the binary from google. It ain't more difficult than using Flexisip.

**Comment by brianjmurrell** [comment]
Still, having to rebuild every release just to add the push notification stuff is a pain.  It's a completely out-of-band process to the normal Android package update process (i.e. Google Play Store -- automatically updating -- or at least prompting to update -- packages) and is going to tend to get lagged and/or forgotten completely to the point that people could have vulnerable software on their phones and no updates.
