### ISSUE TITLE
Fatal signal 11 (SIGSEGV) , code 1, fault addr

### ISSUE THREAD

**Issue by mohzaqout** [BelledonneCommunications/linphone-android#42]
Hi all , I faced this issue in incoming call , "Fatal signal 11 (SIGSEGV) , code 1, fault addr 0x18 in tid" , and the app crash . any help please ?

**Comment by gajicm93** [comment]
Are you running an untouched stock app, or some hybrid of your own? Cause I am making a hybrid, and this used to happen to me due to some bad code in LinphoneActivity.

**Comment by mohzaqout** [comment]
I am running untouched app. @gajicm93
