### ISSUE TITLE
The following binaries are missing: ndk-build. Please install them.

### ISSUE THREAD

**Issue by behzad27** [BelledonneCommunications/linphone-android#420]
try to install linphone and when exec ./prepare.py command get this error:

> The following binaries are missing: ndk-build. Please install them.
read this answer:
https://github.com/BelledonneCommunications/linphone-android/issues/179
and problem not solve to me,my bashrc content:
export path=${path}:/home/behzad/Android/Sdk/tools
export path=${path}:/home/behzad/Android/Sdk/platform-tools
export path=${path}:/home/behzad/Android/android-ndk-r10d
 
please help.

**Comment by mehran22k** [comment]
did you run ./prepare.py with sudo? you should not using sudo

this may solve your problem:  define export paths in **environment** file, not bashrc, 

here is my environment file content: (may help you)

PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt/Android/Sdk/tools:/opt/Android/Sdk/platform-tools:/opt/Android/Sdk/ndk-bundle:/home/mehran/bin"


JAVA_HOME=/usr/lib/jvm/jdk-11.0.1
ANDROID_HOME=/opt/Android/Sdk
ANDROID_NDK=/opt/Android/Sdk/ndk-bundle

**Comment by Viish** [comment]
Also don't use NDK r10, minimum is 16.
