### ISSUE TITLE
How to use linphone in my android app

### ISSUE THREAD

**Issue by roip890** [BelledonneCommunications/linphone-android#421]
Hi,

I want to use linphone in my android app.
I want to make a audio/video caller inside my application.

I imported the linphone sdk like it says in the documentation on your website:
```
        maven {
            url "https://gitlab.linphone.org/BC/public/maven_repository/raw/master"
        }

```

```
    releaseImplementation 'org.linphone:liblinphone-sdk:4.0.1'
    debugImplementation 'org.linphone:liblinphone-sdk:4.0.1-DEBUG'

```

How do I start? There is a documentation that I can look on for how to start integrate it with my app?

Thanks,
Roi.

**Comment by mehran22k** [comment]
Hi Roi
it seems to the best documentation you can find is [Linphone android source](https://github.com/BelledonneCommunications/linphone-android)

just take a look at source codes

**Comment by Viish** [comment]
Specifically the https://github.com/BelledonneCommunications/linphone-android/tree/master/tutorials folder.
