### ISSUE TITLE
A/libc: Fatal signal 11 (SIGSEGV) , app crash for android lower than 6 in version 4.1 

### ISSUE THREAD

**Issue by mehran22k** [BelledonneCommunications/linphone-android#422]
Hi guys

i try to use version 4.1  with local SDK build
i clone SDK and make it successfully
then build the project...

i like to use the 4.1 (I have no problem with master branch) 
please help...
the app work on android 6 correctly but in android 5 or 4.4 its crashed:
Error:
**A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdead4321 in tid 13628 (.linphone.debug)**
what can i do?

my debug log:

$ adb shell am start -n "org.linphone.debug/org.linphone.LinphoneLauncherActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Waiting for application to come online: org.linphone.debug | org.linphone.debug.test
Waiting for application to come online: org.linphone.debug | org.linphone.debug.test
Connecting to org.linphone.debug
Connected to the target VM, address: 'localhost:8600', transport: 'socket'
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/art: Late-enabling -Xcheck:jni
I/art: Debugger is no longer active
W/ActivityThread: Application org.linphone.debug is waiting for the debugger on port 8100...
I/System.out: Sending WAIT chunk
I/art: Debugger is active
I/System.out: Debugger has connected
    waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1476)
I/MultiDex: VM with version 2.1.0 has multidex support
    Installing application
I/MultiDex: VM has multidex support, MultiDex support library is disabled.
D/FirebaseApp: Default FirebaseApp failed to initialize because no default options were found. This usually means that com.google.gms:google-services was not applied to your gradle project.
I/FirebaseInitProvider: FirebaseApp initialization unsuccessful
I/InstantRun: starting instant run server: is main process
V/Monotype: SetAppTypeFace- try to flip, app = org.linphone.debug
V/Monotype:     Typeface getFontPathFlipFont - systemFont = default#default
V/Monotype: SetAppTypeFace- try to flip, app = org.linphone.debug
        Typeface getFontPathFlipFont - systemFont = default#default
D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
W/linker: libc++_shared.so: unused DT entry: type 0x6ffffffe arg 0x2af8c
    libc++_shared.so: unused DT entry: type 0x6fffffff arg 0x2
W/FactoryImpl: Unable to load optional library ffmpeg-linphone: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.linphone.debug-1/base.apk", zip file "/data/app/org.linphone.debug-1/split_lib_dependencies_apk.apk", zip file "/data/app/org.linphone.debug-1/split_lib_slice_0_apk.apk", zip file "/data/app/org.linphone.debug-1/split_lib_slice_1_apk.apk", zip file "/data/app/org.linphone.debug-1/split_lib_slice_2_apk.apk", zip file "/data/app/org.linphone.debug-1/split_lib_slice_3_apk.apk", zip file "/data/app/org.linphone.debug-1/split_lib_slice_4_apk.apk", zip file "/data/app/org.linphone.debug-1/split_lib_slice_5_apk.apk", zip file "/data/app/org.linphone.debug-1/split_lib_slice_6_apk.apk", zip file "/data/app/org.linphone.debug-1/split_lib_slice_7_apk.apk", zip file "/data/app/org.linphone.debug-1/split_lib_slice_8_apk.apk", zip file "/data/app/org.linphone.debug-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/org.linphone.debug-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libffmpeg-linphone.so"
W/linker: libbctoolbox.so: unused DT entry: type 0x6ffffffe arg 0x11e90
    libbctoolbox.so: unused DT entry: type 0x6fffffff arg 0x2
W/linker: libortp.so: unused DT entry: type 0x6ffffffe arg 0x849c
    libortp.so: unused DT entry: type 0x6fffffff arg 0x3
W/linker: libmediastreamer.so: unused DT entry: type 0x6ffffffe arg 0x4796c
    libmediastreamer.so: unused DT entry: type 0x6fffffff arg 0x3
W/linker: liblinphone.so: unused DT entry: type 0x6ffffffe arg 0x527e7c
W/linker: liblinphone.so: unused DT entry: type 0x6fffffff arg 0x3
**A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdead4321 in tid 13628 (.linphone.debug)**
Disconnected from the target VM, address: 'localhost:8600', transport: 'socket'

**Comment by Viish** [comment]
Try with SDK commit 6bcca8dfdd02007ec1349b50f28a364bdbef1aa1. It includes a liblinphone update that fixes a crash on armv7 devices.

**Comment by mehran22k** [comment]
Hi @Viish 
Thank you 
i looking for commit 6bcca8dfdd02007ec1349b50f28a364bdbef1aa1    in linphone sdk project but i could not fine this commit.

i checked [here](https://gitlab.linphone.org/BC/public/linphone-sdk/commits/master)


may you please help me to find  commit 6bcca8dfdd02007ec1349b50f28a364bdbef1aa1


Thank you so much
