### ISSUE TITLE
why can't set ENABLE_OPENH264=ON

### ISSUE THREAD

**Issue by fengsimon** [BelledonneCommunications/linphone-android#424]
Hi,

I run ./prepare.py -DENABLE_OPENH264=ON -DENABLE_NON_FREE_CODECS=ON
I see running information include:
OpenH264, H.264 video encoding/decoding support with the openh264 library (require license).
after running，
then run ./prepare.py --list-features
but:
ENABLE_NON_FREE_CODECS=OFF
	ENABLE_QRCODE=OFF
	ENABLE_TOOLS=OFF
	ENABLE_GTK_UI=OFF
	ENABLE_OPENH264=OFF
why are they not set ON.

**Comment by Viish** [comment]
Hi,
./prepare.py --list-features list features available and their default values. It doesn't mean it is not enabled in your build.
When your run ./prepare.py, it lists all features enabled and disabled, check there.
