### ISSUE TITLE
Make failed

### ISSUE THREAD

**Issue by dharmakpit** [BelledonneCommunications/linphone-android#428]
Hello
I cant make application

Logs:

[  5%] Building C object CMakeFiles/gsm.dir/src/add.c.o
/home/dharma/workspace/linphone-android/submodules/externals/gsm/src/add.c:16:10: fatal error: 
      'private.h' file not found
#include        "private.h"
                ^~~~~~~~~~~
1 error generated.
CMakeFiles/gsm.dir/build.make:62: recipe for target 'CMakeFiles/gsm.dir/src/add.c.o' failed
make[6]: *** [CMakeFiles/gsm.dir/src/add.c.o] Error 1
make[6]: Leaving directory '/home/dharma/workspace/linphone-android/WORK/android-arm64/Build/gsm'
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/gsm.dir/all' failed
make[5]: *** [CMakeFiles/gsm.dir/all] Error 2
make[5]: Leaving directory '/home/dharma/workspace/linphone-android/WORK/android-arm64/Build/gsm'
Makefile:129: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/home/dharma/workspace/linphone-android/WORK/android-arm64/Build/gsm'
CMakeFiles/EP_gsm.dir/build.make:112: recipe for target '/home/dharma/workspace/linphone-android/WORK/android-arm64/Stamp/EP_gsm/EP_gsm-build' failed
make[3]: *** [/home/dharma/workspace/linphone-android/WORK/android-arm64/Stamp/EP_gsm/EP_gsm-build] Error 2
make[3]: Leaving directory '/home/dharma/workspace/linphone-android/WORK/android-arm64/cmake'
CMakeFiles/Makefile2:1162: recipe for target 'CMakeFiles/EP_gsm.dir/all' failed
make[2]: *** [CMakeFiles/EP_gsm.dir/all] Error 2
make[2]: Leaving directory '/home/dharma/workspace/linphone-android/WORK/android-arm64/cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/dharma/workspace/linphone-android/WORK/android-arm64/cmake'
Makefile:215: recipe for target 'arm64-build' failed
make: *** [arm64-build] Error 2

**Comment by mehran22k** [comment]
Hi
How did you clone to your desktop? 

remove your project folder, then try this: (it may solve your peoblem)
git clone git://git.linphone.org/linphone-android.git --recursive

**Comment by alexvimodev** [comment]
I am getting following error in my Mac machine:

root# make
./gradlew clean

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type PluginResolutionStrategyInternal using BuildScopeServices.createPluginResolutionStrategy().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

**Comment by Viish** [comment]
What NDK do you have ?
