### ISSUE TITLE
Linphone requires storage permission to ring

### ISSUE THREAD

**Issue by daradib** [BelledonneCommunications/linphone-android#429]
If the storage permission is denied, the device ringtone will not play, but the screen will still turn on and display the incoming call. If the storage permission is removed and later added back, it is still necessary to re-enable "Use device ringtone" under Settings - Call.

This stack trace might be related:

    W System.err: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
    W System.err:    at org.linphone.fragments.StatusFragment$1.onNotifyReceived(StatusFragment.java:125)
    W System.err:    at org.linphone.core.CoreImpl.iterate(Native Method)
    W System.err:    at org.linphone.core.CoreImpl.iterate(Core.java:4591)
    W System.err:    at org.linphone.LinphoneManager$2$1.run(LinphoneManager.java:647)
    W System.err:    at android.os.Handler.handleCallback(Handler.java:873)
    W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
    W System.err:    at android.os.Looper.loop(Looper.java:193)
    W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6718)
    W System.err:    at java.lang.reflect.Method.invoke(Native Method)
    W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by Viish** [comment]
We do require the storage permission to be able to get the device ringtone.
I fixed an issue in feature/release4.1 branch for the default linphone ringtone not playing.
Anyway you will still have to re-enable the device ringtone setting after setting the storage permission (as it is used for other features and we can't change the user settings based solely on that).
For the crash you had, I also fixed it.
