### ISSUE TITLE
GUI Issue: Button obscures field value.

### ISSUE THREAD

**Issue by MichaelTiernan** [BelledonneCommunications/linphone-android#43]
When entering (acutally editing) a SIP field, in this one case, the button at the end of the field covers the values in the fields.

Annotated screenshot attatched.
![screenshot_2017-03-22-20-19-49](https://cloud.githubusercontent.com/assets/7912879/24454722/f56ee126-145a-11e7-81a8-bcf27f86de77.png)

**Comment by DatBewar** [comment]
Fixed with 46196c7f6f268966efc49627a021bc5afd3e3198
