### ISSUE TITLE
Android FOREGROUND permission missing (Android 9)

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-android#431]
It appears that when Linphone is removed from recent apps in Android 9 (even when it's running as a background service), it doesn't respond to an incoming call due to a missing permission. Would it be possible to add this to AndroidManifest.xml?

`12-17 09:35:06.936  2834  6353 W ActivityManager: Permission Denial: startForeground from pid=28347, uid=10249 requires android.permission.FOREGROUND_SERVICE`

**Comment by aeburriel** [comment]
I concur,

attached patch does the job for Android 9.


[Android9-manifest.patch.txt](https://github.com/BelledonneCommunications/linphone-android/files/2700469/Android9-manifest.patch.txt)

**Comment by Viish** [comment]
Foreground service permission has been added in AndroidManifest since this commit: dc170e357e00a5518fe2221a4803a37dacecb85d
