### ISSUE TITLE
how to get log message

### ISSUE THREAD

**Issue by fengsimon** [BelledonneCommunications/linphone-android#434]
Hi,

when I use common "adb logcat",why  can't I  get log message from Logging.d, or Log.d ,or printf.

thanks.

**Comment by fengsimon** [comment]
my linphone version is v4.0.1

**Comment by Viish** [comment]
If you use the logger in mediastreamer's Log class, they only appear in adb logcat if you enabled the debug logs. You can also use Android's logger.
