### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by jfalexvijay** [BelledonneCommunications/linphone-android#439]
I am getting following error in my Mac machine:

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type PluginResolutionStrategyInternal using BuildScopeServices.createPluginResolutionStrategy().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

I couldn't find any solution for this issue..

<b>CLOSED ISSUE:</b> https://github.com/BelledonneCommunications/linphone-android/issues/383

**Comment by mehran22k** [comment]
Hi
try this , may solve your problem: 
in your root folder find gradle>wrapper
then open gradle-wrapper.properties
Replace  distributionUrl with:
distributionUrl=https://services.gradle.org/distributions/gradle-4.10.2-all.zip

**Comment by jfalexvijay** [comment]
Hi, it is working fine..

Thank you so much for the solution...
