### ISSUE TITLE
tutorials code cannot be used

### ISSUE THREAD

**Issue by xvim** [BelledonneCommunications/linphone-android#440]
LinphoneLauncherActivity.java
		
/*if (getResources().getBoolean(R.bool.show_tutorials_instead_of_app)) {
			classToStart = TutorialLauncherActivity.class;
		} else */
This part of code is commented out and the api has been changed. the tutorials code is the best way  to understand linphone,  so anyone can fix it?

**Comment by Viish** [comment]
Until the tutorials are updated, here's the best way to get documentation on how to get started:
https://www.linphone.org/snapshots/docs/liblinphone/multilang/
https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Getting%20started/
