### ISSUE TITLE
Callee Video Picture Delay

### ISSUE THREAD

**Issue by fengsimon** [BelledonneCommunications/linphone-android#441]
Hi viish,

My linphone version is v4.0.1, When the calling party's video picture arrives at the called party, the delay of the video picture is about one second.
I tested a previous public version of the linphone APK (I don't know exactly what version it is). The delay was about 0.3 seconds.
How to modify the delay problem of v4.0.1 linphone with the expected delay of about 0.3 seconds。

thanks.

**Comment by Viish** [comment]
Do you have the same issue with the app on the google play store ?
