### ISSUE TITLE
dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "liblinphone.so"...

### ISSUE THREAD

**Issue by venkateshguddanti** [BelledonneCommunications/linphone-android#442]
I am using linphone SDK for SIP call .Every thing is working so far well as expected.Once after i have integrated with another library i got this error .Following are the changes i have made recently 

integrated current app with some other SDK which have video call and chat features in it. Initially i came up with below run time error 
"More than one file was found with OS independent path 'lib/armeabi-v7a/libc++_shared.so'"

For this i have changed my build.gradle Package options as fallows

 packagingOptions {
        exclude 'META-INF/rxjava.properties'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
    }
Now application run successfully but i come up with below error"

"dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "liblinphone.so"...

when i am calling 

LinphoneCoreFactory.instance().setLogCollectionPath(getFilesDir().getAbsolutePath());

When i debug inside LinphoneCoreFactory.instance() it returns

Method threw 'java.lang.UnsatisfiedLinkError' exception.

**Comment by venkateshguddanti** [comment]
Hi,
Am not sure about NDK version we are using ,there is no NDK path given in my android studio am just using following dependency in my gradle

 implementation 'liblinphone:android-sdk:0.0.7@aar'

**Comment by Viish** [comment]
What maven repository are you using ofr this aar ?
