### ISSUE TITLE
No implementation found for long LpConfigImpl

### ISSUE THREAD

**Issue by jfalexvijay** [BelledonneCommunications/linphone-android#443]
Hi,
I am getting an error when I try to config linphone: <pre>LinphoneCoreFactory.instance().createLpConfig(linphoneConfigFile);</pre>

<h3>Error:</h3>
E/art: No implementation found for long org.linphone.core.LpConfigImpl.newLpConfigImpl(java.lang.String) (tried Java_org_linphone_core_LpConfigImpl_newLpConfigImpl and Java_org_linphone_core_LpConfigImpl_newLpConfigImpl__Ljava_lang_String_2)

<h4>I have attached a screenshot for added available linphone library detail.</h4>
<img width="430" alt="screenshot 2018-12-27 at 12 37 35 pm" src="https://user-images.githubusercontent.com/462630/50469853-50832700-09d4-11e9-800f-f756e063ad3c.png">

<h3>More Info:</h3>
Mac OS (Mojave)<br>
Android Studio: 3.1.2<br>
Android Target SDK 28 (compile sdk)<br>
Min SDK 16<br>
Gradle version in Android studio : gradle:3.2.1<br>

<h4>I have verified this in following models: </h4>
1. LG G4 --> Android 6.0<br>
2. Samsung Galaxy S III --> Android 4.3

**Comment by Viish** [comment]
It looks like you are using the old API / wrapper.

I recommend you use the new one, the previous one isn't supported anymore and doesn't have all the latest features. With the new one, the following method works just fine:
Config config = Factory.instance().createConfig(factoryPath);

Anyway it should work just as fine with the old wrapper. Are you sure you build the native library ?

**Comment by jfalexvijay** [comment]
@Viish thank you so much for your reply.

I was trying to use Factory class.. but it is available only from org.linphone.mediastream.Factory. also there is no static method or <b>createConfig</b> method inside Factory class.

I have added all needed libraries.. Please check my attached screenshot.
![](https://user-images.githubusercontent.com/462630/50469853-50832700-09d4-11e9-800f-f756e063ad3c.png)

Is there anything I missed to add ?

**Comment by Viish** [comment]
Did you disable the JAVA wrapper option in the prepare.py command ?

**Comment by jfalexvijay** [comment]
I made one change because of https://github.com/BelledonneCommunications/linphone-android/issues/439 issue. I didn't make any other changes.

Do I need to do any changes?

**Comment by Viish** [comment]
You can use our generated SDK as AAR available there:  https://gitlab.linphone.org/BC/public/maven_repository/tree/master/org/linphone/liblinphone-sdk
