### ISSUE TITLE
fcm original server key

### ISSUE THREAD

**Issue by webjframework** [BelledonneCommunications/linphone-android#444]
I have a question for the community.I am using the play linphone with personal sip account in asterisk and with push notifications enabled.From Asterisk DB i can find the app-id and the device token pn-tok ...In order to send a message i need to know the original linphone fcm project server key ..Can you tell me where i can find it ??

Thanks in advance

**Comment by Viish** [comment]
Actually we can't share our private key for push notifications for security reasons.
But you can compile the app yourself and change the push notification key to match the one you configured in your asterisk. If you don't have one, you can create one for free in https://firebase.google.com/.

**Comment by Viish** [comment]
For changing the push notification key only an app update is required, and that can be done on windows.
You just have to use our SDK as AAR: https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Getting%20started/Android/

**Comment by AdnanNeeopal** [comment]
is there any link available to get _**linphone -sdk-android**_ **source code java** files instead **aar or Maven** dependency?
Please help me.
Thank you

**Comment by Viish** [comment]
You can download it there : https://github.com/BelledonneCommunications/linphone-sdk

**Comment by AdnanNeeopal** [comment]
@Viish how to create **linphone account in background in android** application for customize server other than **sip.linphone.org**. please guide me
Thanks
