### ISSUE TITLE
how to build linphone in android studio for windows ???Is it possible at all ? 

### ISSUE THREAD

**Issue by webjframework** [BelledonneCommunications/linphone-android#445]
emtpy path and other issues

**Comment by mehran22k** [comment]
Hi
No its not possible
but , in Linphone 4.1 if you try to use remote SDK you may build it in windows.
(The master branch is 4.0)

**Comment by Viish** [comment]
@webjframework if you just want to build the android app and not make changes in the library you can use our maven repository: https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Getting%20started/Android/
