### ISSUE TITLE
Dialog [0x9fb6d8c0] was not ACK'd within T1*64 seconds, it is going to be terminated.

### ISSUE THREAD

**Issue by msh-nayan** [BelledonneCommunications/linphone-android#446]
I'm using Linphone SDK. When can is dropped after 32 seconds, I got the following error. Any idea, how to fix this issue?

Dialog [0x9fb6d8c0] was not ACK'd within T1*64 seconds, it is going to be terminated.

**Comment by Viish** [comment]
You get this because your server didn't send an ACK package back to the client. Check in your server config.
