### ISSUE TITLE
Video call black screen

### ISSUE THREAD

**Issue by msh-nayan** [BelledonneCommunications/linphone-android#447]
while making a video call using Linphone SDK, sometimes black screen is shown instead of remote view. sometimes it works, sometimes black screen is shown. It mostly occurs on Samsung devices; I've tested on few Samsung devices (Samsung A5 Plus, Galaxy S5, Galaxy Note3). On Samsung A5 Plus, always black screen is shown. For Galaxy S5 & Note3, sometimes remote view is shown, sometimes black screen is shown. anyone having this same problem ? any idea how to fix it?

**Comment by Viish** [comment]
@msh-nayan First of all, please don't open tickets and reference it in other tickets or comment other tickets with the same text as here...
Regarding your issue this only means you have a network issue somewhere causing you not to receive what the other party sends. Check your network or try another one.

**Comment by msh-nayan** [comment]
hello @Viish, thanks for your reply. can u please clarify "try another one" ?

**Comment by Viish** [comment]
If you were on Wi-Fi try 4G or another Wi-Fi network or the other way around (if you are using our SIP server). If you have your own SIP server (or use another service than sip.linphone.org), then check your server.
