### ISSUE TITLE
SIP Register with nonce not sent, registration fails

### ISSUE THREAD

**Issue by calllib** [BelledonneCommunications/linphone-android#448]
### Expected Behaviour:
Upon recieving a "Register" request the SIP server responds with "401 Unauthorized" including a nonce value. The client would then send another "Register" request, now including that nonce value.

### Observed Behaviour:
Upon recieving a "Register" request the SIP server responds with "401 Unauthorized" including a nonce value. **And then Linphone doesn't do anything. Therefore no registration.**

### Client Info:
Linphone 4.0.1 on LineageOS 15.1

**Comment by Viish** [comment]
Hi,
Without logs it's hard to know exactly but I guess your problem is you don't have an auth info object on your core with your authentication informations.

**Comment by calllib** [comment]
> 
> 
> Hi,
> Without logs it's hard to know exactly but I guess your problem is you don't have an auth info object on your core with your authentication informations.

Can you please be so kind as to elaborate a little on this? What is my "core" and an "auth info object"? Please note that the authentication works from my PC in the same network against the very same SIP server.

Sorry for not including logs. I enabled "Debug" and "Use Java Logger" but couldn't find any logs. There is no /Android/data/org.linphone directory - although /Android/data has subdirectories for many other apps. How can I generate and find them?

**Comment by Viish** [comment]
Are you using the app on the store or a custom one based on ours ?

For the logs, once enabled, you can either use adb logcat on your computer or send them using the upload logs feature in the about page.

**Comment by calllib** [comment]
> 
> 
> Are you using the app on the store or a custom one based on ours ?
> 
> For the logs, once enabled, you can either use adb logcat on your computer or send them using the upload logs feature in the about page.

I installed Linphone from F-Droid. With which prameters would I use logcat to retrieve the Linphone logs?

**Comment by Viish** [comment]
Old issue, I'm closing it. Feel free to reopen if it still applies with version 4.2.

**Comment by Freaking1989** [comment]
> Old issue, I'm closing it. Feel free to reopen if it still applies with version 4.2.

I encountered the same problem，when I use android  client , the version is 4.3 ，How should I solve it

**Comment by calllib** [comment]
Strange. With my phone it now works. Using Linphone 4.2.3 from F-Droid.
