### ISSUE TITLE
Audio Call gets disconnected when android device switches from one network to another.

### ISSUE THREAD

**Issue by AndroidDeveloperGit** [BelledonneCommunications/linphone-android#449]
Hello all,

We are trying to make audio calls from one Android device to another using linphone and freeswitch server. If in the middle of the call, the device gets connected to Network B from Network A, then within 10 seconds, the call gets disconnected.  

On change of Network, I am re-registering over server with the new ip and calling linphoneCore.updateCall(call,params) [only if there is an ongoing call]. 

updateCall sends an INVITE (SDP) to server to continue the ongoing call. This INVITE contains the old ip address not the new one because of which the call gets disconnected (BYE received).

Any ideas on how to continue the call and media flow when the networks are changed ?

Thanks.

**Comment by Viish** [comment]
Hi,
Do you still have this issue with a recent SDK ?
