### ISSUE TITLE
Fetch Remote Configuration

### ISSUE THREAD

**Issue by RajanVindaloo** [BelledonneCommunications/linphone-android#454]
I am new to linphone. i am confused with fetch remote configuration, how it works ?
Is there any specific format to retrieve data from server. Is there any testing URL ?

**Comment by Viish** [comment]
Hi,
The remote config URL must point towards a xml file generated from a linphone rc file.
There are tools to generate them in linphone's repository : https://github.com/BelledonneCommunications/linphone/blob/master/tools/lpc2xml_jni.cc
Cheers,
