### ISSUE TITLE
UPDATE message is missing contact information in header

### ISSUE THREAD

**Issue by Tamas-Varga** [BelledonneCommunications/linphone-android#455]
If ICE support is turned on an UPDATE message is sent when ICE has finished its job:

<--- Received SIP request (1495 bytes) from UDP:myrouter.IP:43215 --->
UPDATE sip:myAsterixIP:5060 SIP/2.0
Via: SIP/2.0/UDP 192.168.8.107:43215;branch=z9hG4bK.OCN241Q44;rport
From: <sip:csongor@myAsterixIP>;tag=oYloxExI~
To: <sip:valid-number@myAsterixIP>;tag=69e87e03-1200-4454-a930-746f2efe9f2e
CSeq: 22 UPDATE
Call-ID: zhYmHJ2uBJ
Max-Forwards: 70
Subject: ICE processing concluded
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO, UPDATE
Content-Type: application/sdp
Content-Length: 689
User-Agent: LinphoneAndroid/4.0.1 (belle-sip/1.6.3)
...

This header part is missing the contact information and Asterisk 16.1 requires it:
<--- Transmitting SIP response (350 bytes) to UDP:myrouter.IP:43215 --->
SIP/2.0 400 Missing Contact header
Via: SIP/2.0/UDP 192.168.8.107:43215;rport=43215;received=myrouter.IP;branch=z9hG4bK.OCN241Q44
Call-ID: zhYmHJ2uBJ
From: <sip:csongor@myAsterixIP>;tag=oYloxExI~
To: <sip:valid-number@myAsterixIP>;tag=69e87e03-1200-4454-a930-746f2efe9f2e
CSeq: 22 UPDATE
Server: Asterisk PBX 16.1.1
Content-Length:  0

Probably because of this missing information when the called party answers the call, it is terminated immediately as the CSeq sequence is wrong and BYE message closes the call .
I see in  src/conference/session/call-session.cpp the function CallSessionPrivate::startUpdate
if (destProxy && destProxy->op) {
		/* Give a chance to update the contact address if connectivity has changed */
		op->set_contact_address(destProxy->op->get_contact_address());
	} else
		op->set_contact_address(nullptr);

Is that "nullptr" causes the contact information missing maybe?

**Comment by Viish** [comment]
Hi,
Thanks for the feedback.
Can you open the same ticket in the linphone repository bugtracker please? https://github.com/BelledonneCommunications/linphone/issues
Thanks.
