### ISSUE TITLE
Build Error with FFMPEG

### ISSUE THREAD

**Issue by minkwon14** [BelledonneCommunications/linphone-android#457]
Hi I was trying to enable MPEG4 codec on Android Linphone but I got an error.
Please help me to resolve this issue.

Command tried:
./prepare.py -c && ./prepare.py -DENABLE_NON_FREE_CODECS=ON -DENABLE_MPEG4=ON -DENABLE_H263P=ON -DENABLE_FFMPEG=ON && make

Logs:

WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation'.
It will be removed at the end of 2018
[Push Notification] Firebase enabled

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'New_Linphone_Android_Codec'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
 cmake /home/user/Downloads/New_Linphone_Android_Codec/submodules/cmake-builder -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_PREFIX_PATH=/home/user/Downloads/New_Linphone_Android_Codec/liblinphone-sdk/android-arm64 -DCMAKE_INSTALL_PREFIX=/home/user/Downloads/New_Linphone_Android_Codec/liblinphone-sdk/android-arm64 -DCMAKE_NO_SYSTEM_FROM_IMPORTED=YES -DLINPHONE_BUILDER_WORK_DIR=/home/user/Downloads/New_Linphone_Android_Codec/WORK/android-arm64 -DCMAKE_TOOLCHAIN_FILE=toolchains/toolchain-android-arm64.cmake -DCMAKE_INSTALL_MESSAGE=LAZY -DLINPHONE_BUILDER_CONFIG_FILE=configs/config-android.cmake -DLINPHONE_BUILDER_EXTERNAL_SOURCE_PATH=/home/user/Downloads/New_Linphone_Android_Codec/submodules -DLINPHONE_BUILDER_EXTERNAL_BUILDERS_PATH=/home/user/Downloads/New_Linphone_Android_Codec/cmake_builder -DENABLE_NON_FREE_CODECS=ON -DENABLE_MPEG4=ON -DENABLE_H263P=ON -DENABLE_FFMPEG=ON
-- Check for working C compiler: /home/user/Downloads/android-ndk-r18b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
-- Check for working C compiler: /home/user/Downloads/android-ndk-r18b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/user/Downloads/android-ndk-r18b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
-- Check for working CXX compiler: /home/user/Downloads/android-ndk-r18b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using toolchain file '/home/user/Downloads/New_Linphone_Android_Codec/submodules/cmake-builder/toolchains/toolchain-android-arm64.cmake'
-- Using configuration file '/home/user/Downloads/New_Linphone_Android_Codec/submodules/cmake-builder/configs/config-android.cmake'
-- Including external builders from /home/user/Downloads/New_Linphone_Android_Codec/cmake_builder
-- Found PythonInterp: /usr/bin/python (found version "2.7.15") 
-- Including builder linphone
-- Including builder bctoolbox
-- Including builder mbedtls
-- Including builder bcunit
-- Including builder bellesip
-- Including builder ortp
-- Including builder ms2
-- Including builder androidcpufeatures
-- Including builder androidsupport
-- Including builder gsm
-- Including builder opus
-- Including builder speex
-- Including builder bcg729
-- Including builder turbo-jpeg
-- Including builder ffmpegandroid
-- Including builder ffmpeg
-- Including builder vpx
-- Including builder matroska2
-- Including builder srtp
-- Including builder bzrtp
-- Including builder xml2
-- Including builder sqlite3
-- Including builder ms2plugins
-- Including builder mswebrtc
-- Including builder belr
-- Including builder libxsd
-- Including builder xerces
-- Including builder soci
-- Including builder belcard
-- Check for working C compiler: /home/user/Downloads/android-ndk-r18b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
-- Check for working C compiler: /home/user/Downloads/android-ndk-r18b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/user/Downloads/android-ndk-r18b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
-- Check for working CXX compiler: /home/user/Downloads/android-ndk-r18b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/Downloads/New_Linphone_Android_Codec/WORK/android-arm64/cmake/Autotools
CMake Error at /usr/share/cmake-3.10/Modules/ExternalProject.cmake:2474 (message):
  No download info given for 'EP_ffmpegandroid' and its source directory:

   /home/user/Downloads/New_Linphone_Android_Codec/WORK/android-arm64//Source/EP_ffmpegandroid

  is not an existing non-empty directory.  Please specify one of:

   * SOURCE_DIR with an existing non-empty directory
   * DOWNLOAD_COMMAND
   * URL
   * GIT_REPOSITORY
   * SVN_REPOSITORY
   * HG_REPOSITORY
   * CVS_REPOSITORY and CVS_MODULE
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/ExternalProject.cmake:3029 (_ep_add_download_command)
  cmake/CMakeLists.txt:829 (ExternalProject_Add)
  cmake/CMakeLists.txt:904 (linphone_builder_add_external_project)
  cmake/CMakeLists.txt:1050 (linphone_builder_add_external_projects)
  CMakeLists.txt:78 (linphone_builder_add_projects)

**Comment by Viish** [comment]
Indeed there is a compilation issue when trying to enable ffmpeg on Android.
We'll look at it, thanks.

**Comment by minkwon14** [comment]
@Viish Is there anyway that I can enable FFMPEG? It seems like I need FFMPEG enabled in order to enable MPEG4 and H263P.

These are other what I gets if I try to enabled FFMPEG.

[ 55%] Creating directories for 'EP_ffmpeg'
[ 55%] No download step for 'EP_ffmpeg'
[ 56%] No patch step for 'EP_ffmpeg'
[ 56%] No update step for 'EP_ffmpeg'
[ 56%] Performing configure step for 'EP_ffmpeg'
/home/user/Downloads/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.
CMakeFiles/EP_ffmpeg.dir/build.make:107: recipe for target '/home/user/Downloads/linphone-android/WORK/android-arm64/Stamp/EP_ffmpeg/EP_ffmpeg-configure' failed
make[3]: *** [/home/user/Downloads/linphone-android/WORK/android-arm64/Stamp/EP_ffmpeg/EP_ffmpeg-configure] Error 1
make[3]: Leaving directory '/home/user/Downloads/linphone-android/WORK/android-arm64/cmake'
CMakeFiles/Makefile2:766: recipe for target 'CMakeFiles/EP_ffmpeg.dir/all' failed
make[2]: *** [CMakeFiles/EP_ffmpeg.dir/all] Error 2
make[2]: Leaving directory '/home/user/Downloads/linphone-android/WORK/android-arm64/cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/user/Downloads/linphone-android/WORK/android-arm64/cmake'
Makefile:215: recipe for target 'arm64-build' failed
make: *** [arm64-build] Error 2

**Comment by Viish** [comment]
Like I said, there is an issue and I'll keep you updated when it will be solved.

**Comment by minkwon14** [comment]
@Viish Hi I am just wondering about the progress of this issue. In the meantime, do you have older version that works with FFMPEG so I can have test? Thank you.

**Comment by Viish** [comment]
Sorry we haven't got time yet to investigate this.
As for a version where FFMPEG works, try one of the 4.x releases

**Comment by minkwon14** [comment]
@Viish Hi I tried to enable FFMPEG on 4.0.1 version but ended up getting with error that it cannot find "errno.h" as followings

WARNING: /home/user/Downloads/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/pkg-config not found, library detection may fail.
[ 31%] Forcing build for 'EP_ffmpeg'
[ 31%] Performing build step for 'EP_ffmpeg'
make[4]: Entering directory '/home/user/Downloads/test_lin/linphone-android/WORK/android-arm64/Build/ffmpeg'
In file included from /home/user/Downloads/test_lin/linphone-android/submodules/externals/ffmpeg/libavcodec/allcodecs.c:28:
/home/user/Downloads/test_lin/linphone-android/submodules/externals/ffmpeg/libavcodec/avcodec.h:30:10: fatal error: 'errno.h' file not found
#include <errno.h>
         ^~~~~~~~~
1 error generated.
/home/user/Downloads/test_lin/linphone-android/submodules/externals/ffmpeg/common.mak:57: recipe for target 'libavcodec/allcodecs.o' failed
make[4]: *** [libavcodec/allcodecs.o] Error 1
make[4]: Leaving directory '/home/user/Downloads/test_lin/linphone-android/WORK/android-arm64/Build/ffmpeg'
CMakeFiles/EP_ffmpeg.dir/build.make:113: recipe for target '/home/user/Downloads/test_lin/linphone-android/WORK/android-arm64/Stamp/EP_ffmpeg/EP_ffmpeg-build' failed
make[3]: *** [/home/user/Downloads/test_lin/linphone-android/WORK/android-arm64/Stamp/EP_ffmpeg/EP_ffmpeg-build] Error 2
make[3]: Leaving directory '/home/user/Downloads/test_lin/linphone-android/WORK/android-arm64/cmake'
CMakeFiles/Makefile2:766: recipe for target 'CMakeFiles/EP_ffmpeg.dir/all' failed
make[2]: *** [CMakeFiles/EP_ffmpeg.dir/all] Error 2
make[2]: Leaving directory '/home/user/Downloads/test_lin/linphone-android/WORK/android-arm64/cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/user/Downloads/test_lin/linphone-android/WORK/android-arm64/cmake'
Makefile:190: recipe for target 'arm64-build' failed
make: *** [arm64-build] Error 2

**Comment by Viish** [comment]
We won't fix ffmpeg compilation on Android (at least it isn't planned).
