### ISSUE TITLE
Video call problems

### ISSUE THREAD

**Issue by SarunyuPrasert** [BelledonneCommunications/linphone-android#458]
I build a linphone library and use it in my project. I can make a video call but I always get this message 
"MediaCodecDecoder: waiting for key frame."
and then the remote video view is freeze, I have to wait for a while util message gone and I can see the remote video view moving again. 
Could someone help me to understand this message and solve it.
Thnak you.

**Comment by Viish** [comment]
This can be due to multiple reasons, hard to know without logs. Most probably your network is bad and you have packet losses. 
Otherwise have you tried with a software decoder or another codec ?

**Comment by SarunyuPrasert** [comment]
It was my internet connection at the office. If i switch to using 4G it work fine.
I'm closing this issue.
Thank you.
