### ISSUE TITLE
org.linphone.LinphoneService has leakedIntentReceiver org.linphone.core.tools.DozeReceiver

### ISSUE THREAD

**Issue by system32drivers** [BelledonneCommunications/linphone-android#462]
To replicate:
1. make sure device is connected via usb debugging and running: adb logcat | grep -i linphone
2. [Close All] apps in the Android phone
3. the last logs seen in the adb trace would be the unloading of the application:
01-31 20:18:00.957 17260 17260 E ActivityThread: Service org.linphone.LinphoneService has leaked IntentReceiver org.linphone.core.tools.DozeReceiver@6eb80cf that was originally registered here. Are you missing a call to unregisterReceiver()?
01-31 20:18:00.957 17260 17260 E ActivityThread: android.app.IntentReceiverLeaked: Service org.linphone.LinphoneService has leaked IntentReceiver org.linphone.core.tools.DozeReceiver@6eb80cf that was originally registered here. Are you missing a call to unregisterReceiver()?
01-31 20:18:00.957 17260 17260 E ActivityThread: 	at org.linphone.core.tools.AndroidPlatformHelper.onLinphoneCoreReady(AndroidPlatformHelper.java:161)
01-31 20:18:00.957 17260 17260 E ActivityThread: 	at org.linphone.core.CoreImpl.start(Native Method)
01-31 20:18:00.957 17260 17260 E ActivityThread: 	at org.linphone.core.CoreImpl.start(Core.java:4976)
01-31 20:18:00.957 17260 17260 E ActivityThread: 	at org.linphone.LinphoneManager.startLibLinphone(LinphoneManager.java:639)
01-31 20:18:00.957 17260 17260 E ActivityThread: 	at org.linphone.LinphoneManager.createAndStart(LinphoneManager.java:333)
01-31 20:18:00.957 17260 17260 E ActivityThread: 	at org.linphone.LinphoneService.onStartCommand(LinphoneService.java:326)

tried patching directly in LinphoneManager.java to unregister the doze but it seems to no effect.
mServiceContext.unregisterReceiver(mDozeReceiver); just right after the mNetworkReceiver.

**Comment by Viish** [comment]
Do you reproduce with the feature/release-4.1 branch ? I don't.

**Comment by SarunyuPrasert** [comment]
The problem still occur with master branch. What is version in master branch? release/4.0.1?
