### ISSUE TITLE
can't make call when push notification is allowed

### ISSUE THREAD

**Issue by minooei** [BelledonneCommunications/linphone-android#465]
I installed linphone from google play and tried to connect to my asterisk server. everything looks good and phone rings on receiving calls but I couldn't make any calls and then I tried to disable push notification in settings and now I can make calls.
I wonder what is the problem? Is it linphone or my server?

**Comment by Viish** [comment]
Disabling push notifications only remove push token from the contact header in the register.
I think the problem may come from your asterisk configuration.
