### ISSUE TITLE
How to pause linphone call if android system incoming call received? 

### ISSUE THREAD

**Issue by Miteshmakwana73** [BelledonneCommunications/linphone-android#467]
linphone is not going on hold if call is received in the phone

how do I implement this in linphone?

**Comment by Viish** [comment]
Take a look at the PhoneStateChangedReceiver class

**Comment by Miteshmakwana73** [comment]
this is my PhoneStateChangedReceiver class

public class PhoneStateChangedReceiver extends BroadcastReceiver {
	@Override
	public void onReceive(Context context, Intent intent) {
		final String extraState = intent.getStringExtra(TelephonyManager.EXTRA_STATE);

		if (TelephonyManager.EXTRA_STATE_RINGING.equals(extraState) || TelephonyManager.EXTRA_STATE_OFFHOOK.equals(extraState)) {
			LinphoneManager.setGsmIdle(false);
			if (!LinphoneManager.isInstanciated()) {
				return;
			}
			LinphoneManager.getLc().pauseAllCalls();
        } else if (TelephonyManager.EXTRA_STATE_IDLE.equals(extraState)) {
        	LinphoneManager.setGsmIdle(true);
        }
	}
}
