### ISSUE TITLE
build error on new android studio update 

### ISSUE THREAD

**Issue by S0U1SB4N3** [BelledonneCommunications/linphone-android#468]
im getting errors when I -DENABLE QRCODE = ON fails to build on sudo make on MAC zxing

**Comment by S0U1SB4N3** [comment]
if i comment out line 32 it goes further but still crashes 
[CMakeOutput.log](https://github.com/BelledonneCommunications/linphone-android/files/2848418/CMakeOutput.log)
<img width="693" alt="screen shot 2019-02-09 at 7 22 12 pm" src="https://user-images.githubusercontent.com/22788570/52527993-9a804d80-2ca0-11e9-97f2-d090b5bb369a.png">
<img width="1080" alt="screen shot 2019-02-09 at 7 21 53 pm" src="https://user-images.githubusercontent.com/22788570/52527997-a2d88880-2ca0-11e9-9004-73245719ce6d.png">

**Comment by S0U1SB4N3** [comment]
this is built on macos ndk r16b
sdk 28

**Comment by Viish** [comment]
@S0U1SB4N3 
As you can see in the logs, you don't have pystache installed.
sudo pip install pystache will fix that.

**Comment by S0U1SB4N3** [comment]
ive installed pystache and it will still fail when I upgrade grade to 4.1

**Comment by S0U1SB4N3** [comment]
ive fixed the above error on the arcade not installing by gnuC to 5

**Comment by Viish** [comment]
Attach your new error log

**Comment by S0U1SB4N3** [comment]
this was resolved with downloading your feature-4.1 but it still shows up on your 4.0.1 public release.
