### ISSUE TITLE
Linphone does......  nothing

### ISSUE THREAD

**Issue by dln949** [BelledonneCommunications/linphone-android#469]
Ubuntu 18.04.1, Gnome shell 3.28.3, Linphone 3.6.1.  I have Linphone set to use the TLS protocol on port 5060, which was the default setting.  (I do not know if I should be using TCL or UDP or TCP.)  

Also, Android 9, Linphone Android 4.0.1.  

In installed Linphone on both my Ubuntu desktop and on my Android device.  I also registered an account at linphone.org.  

1)  Using my desktop Ubuntu computer, when I go to the URL https://www.linphone.org/yhfnzsrxlw4uhvq5-call.html , it says that I can click on "this link" ( https://www.linphone.org/yhfnzsrxlw4uhvq5-docall?frombutt=askforhelp1&sipuri=bot@sip.linphone.org ) to start a demo call, is says that it will start Linphone.  However, clicking on that link does nothing.  I don't know what is wrong. I thought this would be a way to make a test call.   

2)  Further down on that same page there is a box for me to enter a phone number and make a call.  So, I entered bot@sip.linphone.org, and then clicked on the "Call" button.  Again, nothing happened.  

3)  On the Ubuntu desktop computer, I start Linphone, and in the "SIP address or phone number:" field I enter this:  <sip:bot@sip.linphone.org> .  Then I click on the call button, but I immediately get this error message:  "Call failed:  Duration" .  I don't know why, nor what I ought to be doing.  

4)  On the android device I start Linphone, and enter this SIP address:  bot@sip.linphone.org .  It spends the better part of a minute just saying there's an outgoing call in progress, but then fails.  

I am completely new to all this, so I don't know how to diagnose this, nor even what information may be important to share with you all.  I'm just a newbie who wants to abandon applications like Skype in favor of open source solutions, but as you can see, unlike Skype, sadly I can't simply install the Linphone software and get it to work.  

I hope someone can help, thanks in advance.

**Comment by Viish** [comment]
Hi,
I don't know where you found this information but sip:bot@sip.linphone.org is not special, it's a simple address that may point to someone or not.
If from your desktop you try to call the address of your android device or vice versa you should have a working call.
Best regards.

**Comment by dln949** [comment]
To answer your question about where I found sip:bot@sip.linphone.org, as you can see in my original posting, item #2 explains that I found that on the linphone.org web page https://www.linphone.org/yhfnzsrxlw4uhvq5-call.html , which is the linphone page to make a test call.  Are you saying that I am completely misunderstanding the purpose of that page?  

Addressing your second paragraph, I do not understand what your are suggesting.  The (sip) address of my android device is the same as the one on my desktop.  When I installed the android device, it asked me to link it to the address I already had at linphone.org, which ended up giving the phone the same address as that on the desktop.
