### ISSUE TITLE
 git submodule update --init  This error occurred

### ISSUE THREAD

**Issue by 850977164** [BelledonneCommunications/linphone-android#470]
error: 服务器不允许请求未公开的对象 f58510c8ce6cd89dadff2b29574d03b05c6efcc9
获取了子模组路径 'submodules/cmake-builder'，但是它没有包含 f58510c8ce6cd89dadff2b29574d03b05c6efcc9。直接获取该提交失败。

**Comment by 850977164** [comment]
I hope someone can help me solve this problem.

**Comment by Viish** [comment]
Please translate your error message to english
