### ISSUE TITLE
Register failed

### ISSUE THREAD

**Issue by MrZhangYang** [BelledonneCommunications/linphone-android#472]
version 4.0.1 
log：      
User-Agent: Unknown (belle-sip/1.6.3)
 Reason: SIP;cause=403;text="Setting Wrong (1003)"
Register refresher [403] reason [Forbidden] for proxy 

how to set the User-Agent ?

**Comment by MrZhangYang** [comment]
4.0.1 version

**Comment by Viish** [comment]
LinphoneCore.setUserAgent()
