### ISSUE TITLE
Build SDK with H264 error

### ISSUE THREAD

**Issue by SarunyuPrasert** [BelledonneCommunications/linphone-android#473]
Hi, I cloned a project on master branch and I got an error when using this command to build linphone sdk
"./prepare.py -c && ./prepare.py -DENABLE_NON_FREE_CODECS=ON -DENABLE_OPENH264=ON -DENABLE_BV16=ON -DENABLE_EMBEDDED_OPENH264=ON && make liblinphone-android-sdk"

Here is some error log.

Scanning dependencies of target EP_openh264
[ 78%] Creating directories for 'EP_openh264'
[ 78%] No download step for 'EP_openh264'
[ 79%] No patch step for 'EP_openh264'
[ 79%] No update step for 'EP_openh264'
[ 79%] Performing configure step for 'EP_openh264'
[ 79%] Forcing build for 'EP_openh264'
[ 80%] Performing build step for 'EP_openh264'
<instantiation>:4:1: error: unknown directive
.func WelsCopy8x8_AArch64_neon
^
../../../..//submodules/externals/openh264/codec/common/arm64/copy_mb_aarch64_neon.S:109:1: note: while in macro instantiation
WELS_ASM_AARCH64_FUNC_BEGIN WelsCopy8x8_AArch64_neon
^
<instantiation>:2:1: error: unknown directive
.endfunc
^
../../../..//submodules/externals/openh264/codec/common/arm64/copy_mb_aarch64_neon.S:120:1: note: while in macro instantiation
WELS_ASM_AARCH64_FUNC_END
^
<instantiation>:4:1: error: unknown directive
.func WelsCopy16x16_AArch64_neon
^
../../../..//submodules/externals/openh264/codec/common/arm64/copy_mb_aarch64_neon.S:123:1: note: while in macro instantiation
WELS_ASM_AARCH64_FUNC_BEGIN WelsCopy16x16_AArch64_neon
^
<instantiation>:2:1: error: unknown directive
.endfunc
^
../../../..//submodules/externals/openh264/codec/common/arm64/copy_mb_aarch64_neon.S:142:1: note: while in macro instantiation
WELS_ASM_AARCH64_FUNC_END
^
<instantiation>:4:1: error: unknown directive
.func WelsCopy16x16NotAligned_AArch64_neon
^
../../../..//submodules/externals/openh264/codec/common/arm64/copy_mb_aarch64_neon.S:145:1: note: while in macro instantiation
WELS_ASM_AARCH64_FUNC_BEGIN WelsCopy16x16NotAligned_AArch64_neon
^
<instantiation>:2:1: error: unknown directive
.endfunc
^
../../../..//submodules/externals/openh264/codec/common/arm64/copy_mb_aarch64_neon.S:164:1: note: while in macro instantiation
WELS_ASM_AARCH64_FUNC_END
^
<instantiation>:4:1: error: unknown directive
.func WelsCopy16x8NotAligned_AArch64_neon
^
../../../..//submodules/externals/openh264/codec/common/arm64/copy_mb_aarch64_neon.S:167:1: note: while in macro instantiation
WELS_ASM_AARCH64_FUNC_BEGIN WelsCopy16x8NotAligned_AArch64_neon
^
<instantiation>:2:1: error: unknown directive
.endfunc
^
../../../..//submodules/externals/openh264/codec/common/arm64/copy_mb_aarch64_neon.S:178:1: note: while in macro instantiation
WELS_ASM_AARCH64_FUNC_END
^
<instantiation>:4:1: error: unknown directive
.func WelsCopy8x16_AArch64_neon
^
../../../..//submodules/externals/openh264/codec/common/arm64/copy_mb_aarch64_neon.S:181:1: note: while in macro instantiation
WELS_ASM_AARCH64_FUNC_BEGIN WelsCopy8x16_AArch64_neon
^
<instantiation>:2:1: error: unknown directive
.endfunc
^
../../../..//submodules/externals/openh264/codec/common/arm64/copy_mb_aarch64_neon.S:200:1: note: while in macro instantiation
WELS_ASM_AARCH64_FUNC_END
^
make[4]: *** [codec/common/arm64/copy_mb_aarch64_neon.o] Error 1
make[3]: *** [/Users/sarunyuprasert/Documents/Git_Linphone_Android/linphone-android/WORK/android-arm64/Stamp/EP_openh264/EP_openh264-build] Error 2
make[2]: *** [CMakeFiles/EP_openh264.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [arm64-build] Error 2

I don't konw how to fix it. Please help me.
Thank you.

**Comment by Gurchello** [comment]
got exactly same error any info will be hellpfull.

**Comment by Gurchello** [comment]
i am trying to compile on MacOS with diff version of nasm without success

**Comment by SarunyuPrasert** [comment]
I've tested by removing this command "-DENABLE_OPENH264=ON" using only "-DENABLE_EMBEDDED_OPENH264=ON". It passed and codec openH264 was working fine in video call.

**Comment by Viish** [comment]
@SarunyuPrasert it would have work the same without "-DENABLE_EMBEDDED_OPENH264=ON" because Linphone supports H264 on Android 6+ through MediaCodec which doesn't require any compilation option to be available.
-DENABLE_OPENH264=ON is only to build support of OpenH264 which is a software decoder required to support H264 codec on Android < 6
