### ISSUE TITLE
During registration nothing happens using wifi

### ISSUE THREAD

**Issue by alexgrek96** [BelledonneCommunications/linphone-android#474]
Hello! My name is Alexandr, i am android developer and use your Android Liblinphone SDK version 4.0.1, downloaded by link: http://www.linphone.org/sites/default/files/liblinphone-android-sdk-no-nonfreecodecs-video-4.0.1.zip.

In total it great library,  but i faced with problem on several android device (such as Xiaomi MI A1 Android 9.0, Xiaomi Redmi Note 4 Android 7.0 ...) has problem with SIP registration only on WIFI connection. When i trying connect to SIP server nothing happens, occur infinit registration, but if i use 3G/4G the problem leave. All tests i make in the same wifi network. Also if i use Linphone downloaded from PlayStore registration working fine!

I added different log files from LinphoneCore in additional, where is succesful connections on one device ( Xiaomi Redmi Note 3 Pro Android 6.0.1) and failure connection on other device ( Android MI A1 Android 9.0).

Logs from both device and server:

https://drive.google.com/open?id=1s3q0kDRs6sGZKKcOh07MX4HsWW68RbUB

I noticed in the logs that some devices don't send a authorization header, but i set the AuthInfo object in my code and on most devices in the same wifi  network all work ( auth header present).

Also i added my code written on Java which is used to  login on my SIP server.

```
public class LinphoneSDK implements SipSDK {
    public static final String LOG_REG_EVENT = LinphoneSDK.class.getName() + ":reg_event";
    public static final String LOG_CALL_EVENT = LinphoneSDK.class.getName() + ":call_event";
    public static final String LOG_TOTAL = LinphoneSDK.class.getName() + ":total_event";

    private Context mContext;
    private Core mLc;
    private Timer mTimer;
    private SipEventListener sipStateListener;
    private final long TIME_UPDATE_STATE = 100;
    private CallParams globalCallParams;


    public LinphoneSDK(Context context) {
        mContext = context;

        Factory.instance().setDebugMode(true, this.getClass().getName());

        mLc = Factory.instance().createCore(null, null, mContext);

        mLc.addListener(baseEventListener);
        mLc.start();

        globalCallParams = mLc.createCallParams(null);
        globalCallParams.enableVideo(false);
    }

    private final LinphoneEventListenerImpl baseEventListener = new LinphoneEventListenerImpl() {
        @Override
        public void onRegistrationStateChanged(Core core, ProxyConfig proxyConfig, RegistrationState registrationState, String s) {
            super.onRegistrationStateChanged(core, proxyConfig, registrationState, s);

            String state = registrationState.toString();
       
        }

        @Override
        public void onCallStateChanged(Core core, Call call, Call.State state, String s) {
            super.onCallStateChanged(core, call, state, s);

          }
    };

    @Override
    public void login(String name, String password, String domain) {
        final String fromConfigStr = createSipFromID(name, domain);

        try {
            Address address = Factory.instance().createAddress(fromConfigStr);

            ProxyConfig proxyConfig = mLc.createProxyConfig();

            proxyConfig.edit();
            proxyConfig.setServerAddr(address.getDomain());
            proxyConfig.enableRegister(true);
            proxyConfig.setIdentityAddress(address);
            proxyConfig.done();
            AuthInfo linphoneAuthInfo = Factory.instance().createAuthInfo(name,
                    name,
                    password,
                    null,
                    proxyConfig.getRealm(),
                    proxyConfig.getDomain());

            mLc.addProxyConfig(proxyConfig);
            mLc.addAuthInfo(linphoneAuthInfo);
            mLc.setDefaultProxyConfig(proxyConfig);

            mTimer = new Timer(this.getClass().getName() + " Scheduler");
            mTimer.schedule(new TimerTask() {
                @Override
                public void run() {
                    new Handler(Looper.getMainLooper()).post(() -> mLc.iterate());
                }
            }, 0, TIME_UPDATE_STATE);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
 
```
Help me please with this problem

**Comment by alexgrek96** [comment]
logs: https://drive.google.com/open?id=1s3q0kDRs6sGZKKcOh07MX4HsWW68RbUB

**Comment by Viish** [comment]
Looks like a UDP problem on your WiFi network. Try to set transport (in proxy config server address) to TCP or even better TLS if your server supports it.

**Comment by tobiasguimaraes** [comment]
Same problem here, i can register without problems on 3g/4g network, but not on wifi..

And if i try to register, with a device with an older android, like a Samsung J5 Android 6.0.1, works fine, both 3g/4g and wifi..

But with android higher then 6, i cant..

my code is very similar to @alexgrek96 codes..

**Comment by alexgrek96** [comment]
> Looks like a UDP problem on your WiFi network. Try to set transport (in proxy config server address) to TCP or even better TLS if your server supports it.


I use UDP on all my test devices and only several of them have problem, but if i use Linphone application from PlayStore all devices work fine!

I tried  different Android OS (5/6/7/8/9) and problem is independent of version OS

**Comment by alexgrek96** [comment]
> Same problem here, i can register without problems on 3g/4g network, but not on wifi..
> 
> And if i try to register, with a device with an older android, like a Samsung J5 Android 6.0.1, works fine, both 3g/4g and wifi..
> 
> But with android higher then 6, i cant..
> 
> my code is very similar to @alexgrek96 codes..



> Looks like a UDP problem on your WiFi network. Try to set transport (in proxy config server address) to TCP or even better TLS if your server supports it.

I use UDP on all my test devices and only several of them have problem, but if i use Linphone application from PlayStore all devices work fine!

I tried different Android OS (5/6/7/8/9) and problem is independent of version OS

**Comment by tobiasguimaraes** [comment]
> I noticed in the logs that some devices don't send a authorization header, but i set the AuthInfo object in my code and on most devices in the same wifi network all work ( auth header present).
> 
Maybe this can be the cause that we cannot register ?

**Comment by Viish** [comment]
Authorization header will be added after server sends back 401 unauthorized, which will be sent after it receives the first register. However in your logs we only see the first one being retransmitted over and over because it hasn't been received.

**Comment by tobiasguimaraes** [comment]
> Authorization header will be added after server sends back 401 unauthorized, which will be sent after it receives the first register. However in your logs we only see the first one being retransmitted over and over because it hasn't been received.

Right!
im debugging here, and when the server responde with 401, the android app dont receive, and it continues sending register with same content..
i need to know why i cant receive now..

linphone do something different when the internet connection is from wifi or 3g ?

**Comment by Viish** [comment]
No there isn't any different treatment regarding the type of connection.
Have you tried a different WiFi network ? Maybe it's your router...

**Comment by tobiasguimaraes** [comment]
Yes, tried with 3 different internet providers and no one can register..
going to intercept all data that the mobile receive to see if the 401 is coming..

**Comment by alexgrek96** [comment]
> No there isn't any different treatment regarding the type of connection.
> Have you tried a different WiFi network ? Maybe it's your router...

I tried more than 5 a different wifi connection, and on all of them didn't work register on several devices, but working on the other devices, also all of them fine work on the linphone from playstore

**Comment by alexgrek96** [comment]
I suggested that the problem in my sip server and find three free voip sip services (IPtel,OnSIP,Linphone) and tried threir in  my application and linphone. The problem isn't my server, linphone success registed in all these account, but my application on same devices continue nothing make. The registation is infinite...

**Comment by tobiasguimaraes** [comment]
any news?

**Comment by Viish** [comment]
Sorry but as our app on the store works it means the issue is in your app.
I can't help much without your source code and even if I had it I don't have time to look at this in detail.
If you want you can contact our sales department to get a quotation for a official dev assist contract.

**Comment by alexgrek96** [comment]
Reason of problem is busy.
Solution :  `@Override
    public void login(String name, String password, String domain) {
        Log.d(LOG_ACTIONS, "login");

        mLc.setNetworkReachable(true);
        this.domain = domain;
        String identity = "sip:" + name + "@" + domain;
        String proxy = "sip:" + domain;

        try {
            Transports transports = mLc.getTransports();
            transports.setUdpPort(RANDOM_PORT);
            transports.setTcpPort(RANDOM_PORT);
            transports.setTlsPort(RANDOM_PORT);
            mLc.setTransports(transports);

            Address proxyAddr = Factory.instance().createAddress(proxy);
            Address identityAddr = Factory.instance().createAddress(identity);

            ProxyConfig proxyConfig = mLc.createProxyConfig();

            proxyConfig.edit();
            proxyConfig.setIdentityAddress(identityAddr);
            proxyConfig.setServerAddr(proxyAddr.asStringUriOnly());
            proxyConfig.enableRegister(true);
            proxyConfig.done();

            AuthInfo authInfo = Factory.instance().createAuthInfo(name,
                    name,
                    password,
                    null,
                    proxyConfig.getRealm(),
                    proxyConfig.getDomain());

            mLc.addProxyConfig(proxyConfig);
            mLc.addAuthInfo(authInfo);
            mLc.setDefaultProxyConfig(proxyConfig);

            mTimer = new Timer(this.getClass().getName() + " Scheduler");
            mTimer.schedule(new TimerTask() {
                @Override
                public void run() {
                    new Handler(Looper.getMainLooper()).post(() -> mLc.iterate());
                }
            }, 0, TIME_UPDATE_STATE);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }`


where RANDOM_PORT equals -1

**Comment by hotmule** [comment]
Thank you, with UDP and udpPort=-1 registration works properly
