### ISSUE TITLE
SDK build release apk failed to open program, where to find SDK confusion?

### ISSUE THREAD

**Issue by YunniWeng** [BelledonneCommunications/linphone-android#475]
error:
1	#00 pc 0000000000069e18 /system/lib64/libc.so (tgkill+8) [arm64-v8a]
2	#01 pc 000000000001df20 /system/lib64/libc.so (abort+88) [arm64-v8a]
3	#02 pc 000000000001d020 /data/app/com.wkop.xqwk-utLm_Yz5VMLG65t9a2Pebg==/lib/arm64/libbctoolbox.so (bctbx_logv+488) [arm64-v8a]
4	#03 pc 00000000007d13b0 /data/app/com.wkop.xqwk-utLm_Yz5VMLG65t9a2Pebg==/lib/arm64/liblinphone.so [arm64-v8a]
5	#04 pc 00000000007d111c /data/app/com.wkop.xqwk-utLm_Yz5VMLG65t9a2Pebg==/lib/arm64/liblinphone.so (LinphonePrivate::Logger::~Logger()+176) [arm64-v8a]
6	#05 pc 000000000084b4c4 /data/app/com.wkop.xqwk-utLm_Yz5VMLG65t9a2Pebg==/lib/arm64/liblinphone.so (LinphonePrivate::AndroidPlatformHelpers::AndroidPlatformHelpers(_LinphoneCore*, void*)+124) [arm64-v8a]
7	#06 pc 000000000084bf78 /data/app/com.wkop.xqwk-utLm_Yz5VMLG65t9a2Pebg==/lib/arm64/LinphonePrivate::createAndroidPlatformHelpers(_LinphoneCore*, void*)+44) [arm64-v8a]
8	#07 pc 000000000086b7e8 /data/app/com.wkop.xqwk-utLm_Yz5VMLG65t9a2Pebg==/lib/arm64/liblinphone.so (_linphone_core_new_with_config+640) [arm64-v8a]
9	#08 pc 000000000085f63c /data/app/com.wkop.xqwk-utLm_Yz5VMLG65t9a2Pebg==/lib/arm64/liblinphone.so [arm64-v8a]
10	#09 pc 00000000008b9e78 /data/app/com.wkop.xqwk-utLm_Yz5VMLG65t9a2Pebg==/lib/arm64/liblinphone.so (Java_org_linphone_core_FactoryImpl_createCore+156) [arm64-v8a]
11	#10 pc 000000000019b808 /data/app/com.wkop.xqwk-utLm_Yz5VMLG65t9a2Pebg==/oat/arm64/base.odex (oatexec+1243144) [arm64-v8a]

**Comment by Viish** [comment]
Please add description and full logs.

**Comment by YunniWeng** [comment]
My problem is solved
I forgot to add confusion in proguard-rules. Pro

-keep class org.linphone.** { *; }
-dontwarn org.linphone.**
