### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by licaon-kter** [BelledonneCommunications/linphone-android#478]
AOSP 9, 4.0.1 F-Droid or app from site

There's a 50% chance that the app will crash on start, even if I delete all the DATA so the app is in a clean state.

Not seen on Android 6.

Notice that the error seems to be the opposite of #477.

Logcat:
```
AndroidRuntime(12036): Shutting down VM
02-16 23:56:23.205 E/AndroidRuntime(12036): FATAL EXCEPTION: main
02-16 23:56:23.205 E/AndroidRuntime(12036): Process: org.linphone, PID: 12036
02-16 23:56:23.205 E/AndroidRuntime(12036): java.lang.RuntimeException: Unable to create service org.linphone.LinphoneService: java.lang.RuntimeException: Linphone Manager is already initialized
02-16 23:56:23.205 E/AndroidRuntime(12036): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3582)
02-16 23:56:23.205 E/AndroidRuntime(12036): 	at android.app.ActivityThread.access$1300(ActivityThread.java:200)
02-16 23:56:23.205 E/AndroidRuntime(12036): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
02-16 23:56:23.205 E/AndroidRuntime(12036): 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-16 23:56:23.205 E/AndroidRuntime(12036): 	at android.os.Looper.loop(Looper.java:193)
02-16 23:56:23.205 E/AndroidRuntime(12036): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
02-16 23:56:23.205 E/AndroidRuntime(12036): 	at java.lang.reflect.Method.invoke(Native Method)
02-16 23:56:23.205 E/AndroidRuntime(12036): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-16 23:56:23.205 E/AndroidRuntime(12036): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
02-16 23:56:23.205 E/AndroidRuntime(12036): Caused by: java.lang.RuntimeException: Linphone Manager is already initialized
02-16 23:56:23.205 E/AndroidRuntime(12036): 	at org.linphone.LinphoneManager.createAndStart(LinphoneManager.java:336)
02-16 23:56:23.205 E/AndroidRuntime(12036): 	at org.linphone.LinphoneService.onCreate(LinphoneService.java:356)
02-16 23:56:23.205 E/AndroidRuntime(12036): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3570)
02-16 23:56:23.205 E/AndroidRuntime(12036): 	... 8 more
```   

Also, before the crash this warning is logged too (when using the app from the site):
```
W FactoryImpl: Unable to load optional library ffmpeg-linphone: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.linphone-PXFN-ORdnbV-vzKRIA4WuQ==/base.apk"],nativeLibraryDirectories=[/data/app/org.linphone-PXFN-ORdnbV-vzKRIA4WuQ==/lib/arm64, /data/app/org.linphone-PXFN-ORdnbV-vzKRIA4WuQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libffmpeg-linphone.so"
```

**Comment by MrZhangYang** [comment]
> AOSP 9, 4.0.1 F-Droid or app from site
> 
> There's a 50% chance that the app will crash on start, even if I delete all the DATA so the app is in a clean state.
> 
> Not seen on Android 6.
> 
> Notice that the error seems to be the opposite of #477.
> 
> Logcat:
> 
> ```
> AndroidRuntime(12036): Shutting down VM
> 02-16 23:56:23.205 E/AndroidRuntime(12036): FATAL EXCEPTION: main
> 02-16 23:56:23.205 E/AndroidRuntime(12036): Process: org.linphone, PID: 12036
> 02-16 23:56:23.205 E/AndroidRuntime(12036): java.lang.RuntimeException: Unable to create service org.linphone.LinphoneService: java.lang.RuntimeException: Linphone Manager is already initialized
> 02-16 23:56:23.205 E/AndroidRuntime(12036): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3582)
> 02-16 23:56:23.205 E/AndroidRuntime(12036): 	at android.app.ActivityThread.access$1300(ActivityThread.java:200)
> 02-16 23:56:23.205 E/AndroidRuntime(12036): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
> 02-16 23:56:23.205 E/AndroidRuntime(12036): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 02-16 23:56:23.205 E/AndroidRuntime(12036): 	at android.os.Looper.loop(Looper.java:193)
> 02-16 23:56:23.205 E/AndroidRuntime(12036): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
> 02-16 23:56:23.205 E/AndroidRuntime(12036): 	at java.lang.reflect.Method.invoke(Native Method)
> 02-16 23:56:23.205 E/AndroidRuntime(12036): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> 02-16 23:56:23.205 E/AndroidRuntime(12036): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> 02-16 23:56:23.205 E/AndroidRuntime(12036): Caused by: java.lang.RuntimeException: Linphone Manager is already initialized
> 02-16 23:56:23.205 E/AndroidRuntime(12036): 	at org.linphone.LinphoneManager.createAndStart(LinphoneManager.java:336)
> 02-16 23:56:23.205 E/AndroidRuntime(12036): 	at org.linphone.LinphoneService.onCreate(LinphoneService.java:356)
> 02-16 23:56:23.205 E/AndroidRuntime(12036): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3570)
> 02-16 23:56:23.205 E/AndroidRuntime(12036): 	... 8 more
> ```
> Also, before the crash this warning is logged too (when using the app from the site):
> 
> ```
> W FactoryImpl: Unable to load optional library ffmpeg-linphone: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.linphone-PXFN-ORdnbV-vzKRIA4WuQ==/base.apk"],nativeLibraryDirectories=[/data/app/org.linphone-PXFN-ORdnbV-vzKRIA4WuQ==/lib/arm64, /data/app/org.linphone-PXFN-ORdnbV-vzKRIA4WuQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libffmpeg-linphone.so"
> ```

use release sdk is ok , you can try

**Comment by licaon-kter** [comment]
I did test the nightly builds and 4.0.1-503-g66e1e39d seems ok.

**Comment by MrZhangYang** [comment]
> I did test the nightly builds and 4.0.1-503-g66e1e39d seems ok.

ok，enjoy，haha

**Comment by Viish** [comment]
I confirm this issue has been fixed in master branch since the release and fix will be available in the next release.

**Comment by PainterHu** [comment]
@licaon-kter 

Hello sir, do you still have version 4.0.1-503-g66e1e39d? If so, could you please send me a copy? I'm encountering a similar problem, but I can't find this version on the Linphone website or GitHub.

Thank you very much!!!

**Comment by licaon-kter** [comment]
F-Droid, enable Archive for repo, update index, go to Linphone details, select repo Archive, expand Versions... scroll down

**Comment by PainterHu** [comment]
Hi @licaon-kter 

I can't find this version in the mvnrepository at all. The lowest version in the repository is 4.2-41-g26f71b5, and the lowest version on the linphone website is also 4.2-41-g26f71b5/. Could you please send me the link? Thank you so much!

**Comment by licaon-kter** [comment]
https://f-droid.org/archive/org.linphone_4002.apk @PainterHu

**Comment by PainterHu** [comment]
@licaon-kter Thank you so much!
