### ISSUE TITLE
How to import linphone-android in android studio in windows

### ISSUE THREAD

**Issue by abhijeetdhole** [BelledonneCommunications/linphone-android#48]
I have a clone copy of linphone-android and I have imported the project in android studio but I am getting following error to all native code. 
Cannot resolve corresponding JNI function.

I searched a lot but getting steps for linux or mac not for windows.
Can anyone help to compile this project in windows.

**Comment by DatBewar** [comment]
Hello, we don't have any way to build linphone android on windows currently.

**Comment by abhijeetdhole** [comment]
Thanks for your reply
But I have also tried to build linphone-android on Linux the project is not successfully built for the latest version 3.2.6.
So I have tried with serveral versions among them v3.0.0 is working fine.
Can you help me for the latest version. I am getting following error after "make" command

clang: /s/ndk-toolchain/src/llvm-3.5/llvm/tools/clang/lib/Sema/SemaChecking.cpp:5480: void {anonymous}::DiagnoseOutOfRangeComparison(clang::Sema&, clang::BinaryOperator*, clang::Expr*, clang::Expr*, llvm::APSInt, bool): Assertion `(OtherT->isIntegerType() && ConstantT->isIntegerType()) && "comparison with non-integer type"' failed.

**Comment by DatBewar** [comment]
Duplicate https://github.com/BelledonneCommunications/linphone-android/issues/53
