### ISSUE TITLE
QR Code button not showing up in android 

### ISSUE THREAD

**Issue by S0U1SB4N3** [BelledonneCommunications/linphone-android#480]
the enable_qrcode bool = on
but the qr code button does not show up anywhere, 
can you show me how to enable this 

I did -denable_qrcode=ON on the initial build 
@DatBewar @Viish

**Comment by Viish** [comment]
QR code is available in Assistant->Remote Configuration->QR Code in the app.

**Comment by S0U1SB4N3** [comment]
that button doesn't show up 
just the fetch and apply button

**Comment by Viish** [comment]
Try on the feature/release-4.1 branch

**Comment by S0U1SB4N3** [comment]
okay, ill git clone -b 4.1 and get back to you

**Comment by S0U1SB4N3** [comment]
the new build completed without error 
it loaded on the galaxy note 9 android 9 
assistant->fetch remote configuration-> there is still no qr code button. just fetch and apply button 
and a place to put the url for remote provisioning. 
@Viish 

please assist 
is there a field in the linphonerc that needs a bool to =1 ?

<img width="260" alt="screen shot 2019-02-27 at 11 49 34 am" src="https://user-images.githubusercontent.com/22788570/53507435-e34c4a80-3a85-11e9-9b8e-8bfc37bf5f75.png">
<img width="257" alt="screen shot 2019-02-27 at 11 50 07 am" src="https://user-images.githubusercontent.com/22788570/53507436-e3e4e100-3a85-11e9-9a1f-85d8abc12a05.png">


this screen shot is from the android studio but directly reflects the output on my galaxy note 9

**Comment by S0U1SB4N3** [comment]
axing framework is there the preview qrcode.xml is present, however nothing is here to activate it, camera and storage permissions are allowed on android hardware phone device @Viish @DatBewar @BelledonneComm

**Comment by S0U1SB4N3** [comment]
I have done this separately sudo git clone -b feature/release-4.1 https://github.com/BelledonneCommunications/linphone-android.git --recursive

and have a smaller file, how would I build this file or import these features into the main build ? @Viish

**Comment by S0U1SB4N3** [comment]
I loaded it and it built, there is a qr code button now, @Viish 

how do I unlock all codec on this build ?

**Comment by Viish** [comment]
Check out the README file, section "Building a local SDK"

**Comment by S0U1SB4N3** [comment]
okay I have gotten pretty far, however, when I add multiple sip accounts it does not re-write the proxy and registration fails, also looking at the code I've noticed the proxyconfig is commented out on the remote provisioning fragment. I tried blending this release 4.1 with the release 4.0.1 but I get 3 errors on how it handles the qr code when none is found or when the 3 flags aren't found. Ill rebuild the sdk on my AWS Linux machine and try again.

**Comment by S0U1SB4N3** [comment]
<img width="890" alt="screen shot 2019-03-08 at 10 28 11 am" src="https://user-images.githubusercontent.com/22788570/54038561-d4088380-418e-11e9-9804-10abad89c47d.png">
<img width="880" alt="screen shot 2019-03-08 at 10 27 23 am" src="https://user-images.githubusercontent.com/22788570/54038562-d4088380-418e-11e9-9260-b221b2e308bf.png">

**Comment by S0U1SB4N3** [comment]
this is what I get when I blended the 4.1 feature fragments with the 4.0.1 release. 
the qr code window opens for less than 1 second. 

any idea when you will release the feature in your regular linphone build ? 

I get no errors in android studio but the device doesn't work on the hardware phone. 

@Viish

**Comment by S0U1SB4N3** [comment]
im receiving an error when remote provisioning I use auth_info_0 and proxy_0, how do I set this name to use next available space instead of slot 0 
is there a wild card that I can use and it takes that and applies the next available number to it 

Proxy config does not refresh when changing accounts on release 4.0.1. 
@DatBewar @Viish @BelledonneComm
