### ISSUE TITLE
old version apk

### ISSUE THREAD

**Issue by webjframework** [BelledonneCommunications/linphone-android#483]
Today i update the version from playstore ...(11/feb/2019) version number 4.01 ..

I was using the previous version from playstore  jul/2018 with version number again 4.01...(??????)

The issue is that with the new version push notification not working so i was to trying to revert to the old one.
I downloaded the old version from linphone mirror but same issue..

what is wrong ??
why everyversion named 4.01 ???
How i can i found the previous right one from playstore ???

please help !

thanks in advance !

**Comment by Viish** [comment]
Hi,
Yeah we released a very minor update to the latest 4.0.1 version hence the version number not updated.
However the 4.1 release is coming soon.
Anyway you shouldn't have any new issue as we almost changed nothing except for a now forbidden permission in the Manifest we removed.
Can you attach push related logs ?

**Comment by webjframework** [comment]
Thank you for the quick respond ...

I have issue and till yesterday with the previous version everything was great..

How can i get the push logs ??

Please send me the previous official apk that was in the playstore for months now becouse i really use the linphone :)

**Comment by Viish** [comment]
I just found the issue with push notification in latest update.
New app update currently in deployment in Google Store, should be availble soon.

**Comment by webjframework** [comment]
ok i will wait ...

Since you are looking for the push ..
When someone calls you leave the app open and the service registered.It shoud act as viber ..only notification , the app in background and the service unregistered in order to avoice power consumption !

Regards John

webjframework.com
