### ISSUE TITLE
Trying to build 4.1 with the java wrapper fails because of new wrapper-less code

### ISSUE THREAD

**Issue by vaiden** [BelledonneCommunications/linphone-android#486]
Because of [#484 (comment)](https://github.com/BelledonneCommunications/linphone-android/issues/484#issuecomment-466419232) I'm trying to build 4.1 with the old java warpper.

```
cmake .. -DLINPHONESDK_PLATFORM=ANDROID -DENABLE_JAVA_WRAPPER=NO
cmake --build . --target sdk
```

I'm using the code from https://gitlab.linphone.org/BC/public/linphone-sdk/tree/4.1

This fails during build with the following errors:

> > Task :compileDebugJavaWithJavac FAILED
> /Users/vaiden/dev/projects/linphone/linphone-sdk4.1/linphone/wrappers/java/classes/tools/AndroidPlatformHelper.java:23: error: cannot find symbol
> import org.linphone.core.Core;
>                         ^
>   symbol:   class Core
>   location: package org.linphone.core
> /Users/vaiden/dev/projects/linphone/linphone-sdk4.1/linphone/wrappers/java/classes/tools/H264Helper.java:6: error: cannot find symbol
> import org.linphone.core.Core;
>                         ^
>   symbol:   class Core
>   location: package org.linphone.core
> /Users/vaiden/dev/projects/linphone/linphone-sdk4.1/linphone/wrappers/java/classes/tools/H264Helper.java:39: error: cannot find symbol
>     public static void setH264Mode(String mode, Core linphoneCore){
>                                                 ^
>   symbol:   class Core
>   location: class H264Helper
> /Users/vaiden/dev/projects/linphone/linphone-sdk4.1/linphone/wrappers/java/classes/Utils.java:24: error: cannot find symbol
> 		DialPlan[] dialPlans = Factory.instance().getDialPlans();
> 		^
>   symbol:   class DialPlan
>   location: class Utils
> /Users/vaiden/dev/projects/linphone/linphone-sdk4.1/linphone/wrappers/java/classes/Utils.java:24: error: cannot find symbol
> 		DialPlan[] dialPlans = Factory.instance().getDialPlans();
> 		                       ^
>   symbol:   variable Factory
>   location: class Utils
> /Users/vaiden/dev/projects/linphone/linphone-sdk4.1/linphone/wrappers/java/classes/Utils.java:25: error: cannot find symbol
> 		DialPlan dialPlan = dialPlans[0];
> 		^
>   symbol:   class DialPlan
>   location: class Utils
> /Users/vaiden/dev/projects/linphone/linphone-sdk4.1/linphone/wrappers/java/classes/Utils.java:30: error: cannot find symbol
> 		DialPlan[] dialPlans = Factory.instance().getDialPlans();
> 		^
>   symbol:   class DialPlan
>   location: class Utils
> /Users/vaiden/dev/projects/linphone/linphone-sdk4.1/linphone/wrappers/java/classes/Utils.java:30: error: cannot find symbol
> 		DialPlan[] dialPlans = Factory.instance().getDialPlans();
> 		                       ^
>   symbol:   variable Factory
>   location: class Utils
> /Users/vaiden/dev/projects/linphone/linphone-sdk4.1/linphone/wrappers/java/classes/Utils.java:31: error: cannot find symbol
> 		DialPlan dialPlan = dialPlans[0];
> 		^
>   symbol:   class DialPlan
>   location: class Utils
> Note: Some input files use or override a deprecated API.

This seems to fail because of code designed to work without the wrapper.
How can I produce a wrapper AAR of 4.1?

Thanks a lot

**Comment by Viish** [comment]
Hi,
Yes with the old java wrapper you can't use the H264Helper.java or Utils.java classes. The other ones should be fine even with the old wrapper (actually you need them for the library to work correctly).
But do not use the 4.1 branch of the linphone-sdk, instead use master.
Also note that using the old Java wrapper won't automatically produce an AAR, just the libs and you have to add to your classpath the java folder in linphone submodule.

**Comment by vaiden** [comment]
When you say - use master - do you mean for the java wrapper or generally when trying to use 4.1?

**Comment by Viish** [comment]
As the 4.1 isn't released yet, we are still making developments for it in the SDK, and thoses developments are in the master branch. So yes until we release a stable version of the SDK you're better off using master branch of linphone-sdk project.

**Comment by vaiden** [comment]
Should we ignore the 4.1 aars in https://gitlab.linphone.org/BC/public/maven_repository/tree/master/org/linphone/linphone-sdk-android? Or are they stable enough for use?

B.T.W. The reason we're so "fixated" at 4.1 is this: https://github.com/BelledonneCommunications/linphone-android/issues/378#issuecomment-456773065

**Comment by Viish** [comment]
You can use the 4.1-xxx AARs as they are the latest one and the one we use to build our next release, but there is no guarantee they are stable.
And all of them are built with the new Java wrapper.

**Comment by vaiden** [comment]
Thanks.
Any plans on releasing 3.4.x with the fixes for the crashes that were implemented in 4.1? 
How can we request this officially?

**Comment by Viish** [comment]
You can request that officially by contacting our sales departement and subscribing to a support contract. Our sales email address is sales@belledonne-communications.com

**Comment by vaiden** [comment]
Any plans on releasing further 3.4.x without the request or is it defendant solely on customer requests?

**Comment by Viish** [comment]
We do maintenance for our releases but 3.4.x is way too old.

**Comment by vaiden** [comment]
So no plans on releasing these fixes with the old Java wrapper?

**Comment by Viish** [comment]
No the old java wrapper has been deprecated for a while, and since it was a manual wrapper it is extremely costly for us to maintain it.
