### ISSUE TITLE
4.1 don't connect to *.linphone.org

### ISSUE THREAD

**Issue by licaon-kter** [BelledonneCommunications/linphone-android#488]
...unless one uses an actual linphone.org account.

Seeing connection attempts to
TCP6 sip-staging.linphone.org:8083
UDP6 sip6.linphone.org:5060
...while using my own hosted SIP accounts.

AOSP 9, 4.1 HEAD

**Comment by Viish** [comment]
Before configuring your own account, did you configure a sip.linphone.org account ?

**Comment by licaon-kter** [comment]
Never... I only configure my own, then after some minutes, seemingly at random, it starts trying to connecting to `linphone.org` domains.

**Comment by Viish** [comment]
Ok thanks for the information.
Because we only use linphone.org accounts internally we don't notice this kind of issue.
The connection you are seeing is made by linphone to our key server and is related to the new encryption feature that will be available in this release.

**Comment by Viish** [comment]
Starting with this commit it should be OK now: 1bebdfc64aa0a328bec2b93f4fb2e35a3af67ff1

**Comment by licaon-kter** [comment]
Please reopen, 4114 tries to connect to `TCP4/6 www.linphone.org:443`

**Comment by Viish** [comment]
Can you attach logs showing that please ?
This is our website and port 443 isn't used anywhere in the app (except for tunnel but it isn't part of public SDK or our public app).

**Comment by licaon-kter** [comment]
As blocked by [NetGuard](https://github.com/M66B/NetGuard):

![linphonenetguard](https://user-images.githubusercontent.com/2282799/53972976-8c3f1900-4108-11e9-8a1d-3dda13a1bece.jpg)

Note that I'm not visiting links or about or anything, just calling another device, from a personal SIP account. I can see this on both devices.

**Comment by Viish** [comment]
Can you enable logs in settings/advanced, make a call to your other device and then in the about page click on upload logs and send the mail please ?

**Comment by licaon-kter** [comment]
What link? There's the send button and then it tries to connect to :444

**Comment by Viish** [comment]
Yes this is our logs upload feature, allow it. After the log upload it will open your mailer with a preformated mail with the link to your uploaded logs.
Otherwise use adb logcat to capture logs and attach them here

**Comment by licaon-kter** [comment]
> 443 isn't used anywhere in the app

Well, the log says otherwise:
```
I lib[01;31m[Klinphone[m[K: Checking for new version at: https://www.linphone.org/releases/android/RELEASE
I [01;31m[Klinphone[m[K-android: [Platform Helper] Network is available
I belle-sip: channel [0x7acbd7cb40]: starting resolution of www.[01;31m[Klinphone[m[K.org
I belle-sip: www.[01;31m[Klinphone[m[K.org resolved to 5.135.31.160
I belle-sip: www.[01;31m[Klinphone[m[K.org resolved to 2001:41d0:303:3aee::1
```
_(ignore the log garbage that my ROM outputs)_

**Comment by licaon-kter** [comment]
Any news?

**Comment by Viish** [comment]
Sorry I forgot to answer you. 
Actually this is expected as well even when you are not using a linphone.org account. It simply checks if there is a new version available of the app to suggest you to update.

**Comment by licaon-kter** [comment]
What's the point? I'll just update from F-Droid, any update you'd push on your website will actually be incompatible! The user will download an APK that will fail to install? The user will be nagged to update albeit this will always fail? Why can't the user opt-out of this useless check?

Shouldn't you check what app was used to install Linphone and if it _wasn't_ F-Droid or Google Play store **THEN** check for updated versions on site?

What information is sent to the website? What does the website log? IP? Linphone version? For how long?

**Comment by Viish** [comment]
If you look at the code you'll see we simply do a HTTP GET on a page that includes the latest release number and the link to download it (on the play store). Once this check is done, if there is an update available, the library calls a callback. And this check can be disabled by setting to empty the parameter version_check_url_root in the [misc] section.
Here's our privacy policy: https://www.linphone.org/terms-and-privacy

**Comment by licaon-kter** [comment]
> And this check can be disabled by setting to empty the parameter version_check_url_root in the [misc] section.

Great, I;ll tweak the F-Droid metadata to do this. Thanks

**Comment by licaon-kter** [comment]
Please reopen

Even if I replace the "sharing server url" the app constantly tries to connect to `T4/T6 lime.linphone.org:443`

**Comment by Viish** [comment]
I think this is because you've had a previous version of the feature/release-4.1 app, at a time this url it was in the linphonerc_factory file.
Now it is only configured if you have a linphone.org account, either when you configure one (https://github.com/BelledonneCommunications/linphone-android/blob/feature/release-4.1/app/src/main/res/raw/linphone_assistant_create.rc#L35) or when you update from an older version (https://github.com/BelledonneCommunications/linphone-android/blob/feature/release-4.1/app/src/main/res/values/non_localizable_custom.xml#L9).
Please uninstall, install a fresh one and confirm you still have the issue.

**Comment by licaon-kter** [comment]
Nope, I've already did that, it's a clean install, no linphone.org accounts ever.

**Comment by Viish** [comment]
Ok I found the problem.
This time it should be ok: b2e904a6f9b68e313608b7fe144b682df27498db
