### ISSUE TITLE
App crashes with "has unexpected e_machine: 40" error

### ISSUE THREAD

**Issue by jfalexvijay** [BelledonneCommunications/linphone-android#49]
I am using linphone library in my Android app from 2015. I have updated the library last month. 
After the last update, I am getting below crashes only in few phones.

Phone Model : SM-G900F, GT-I9100
Android : 4.4.2

0	java.lang.ExceptionInInitializerError
1	at java.lang.Class.classForName(Class.java)
2	at java.lang.Class.forName(Class.java:251)
3	at java.lang.Class.forName(Class.java:216)
!4	at org.linphone.core.LinphoneCoreFactory.instance(LinphoneCoreFactory.java:47)
5	at com.MyApp.MyApp.sip.XXXXX.initSipLibrary(XXXXX.java:xxx)
6	at com.MyApp.MyApp.xxx.XXXXX.onCreate(XXXXX.java:xxx)
7	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2572)
8	at android.app.ActivityThread.access$1800(ActivityThread.java:135)
9	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
10	at android.os.Handler.dispatchMessage(Handler.java:102)
11	at android.os.Looper.loop(Looper.java:136)
12	at android.app.ActivityThread.main(ActivityThread.java:5021)
13	at java.lang.reflect.Method.invokeNative(Method.java)
14	at java.lang.reflect.Method.invoke(Method.java:515)
15	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827)
16	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643)
17	at dalvik.system.NativeStart.main(NativeStart.java)
18	Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app-lib/com.MyApp.MyApp-2/libbctoolbox-armeabi-v7a.so" has unexpected e_machine: 40
19	at org.linphone.core.LinphoneCoreFactoryImpl.<clinit>(LinphoneCoreFactoryImpl.java:71)
20	... 17 more
21	Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app-lib/com.MyApp.MyApp-2/libbctoolbox-armeabi-v7a.so" has unexpected e_machine: 40
22	at java.lang.Runtime.loadLibrary(Runtime.java:364)
23	at java.lang.System.loadLibrary(System.java:526)
24	at org.linphone.core.LinphoneCoreFactoryImpl.<clinit>(LinphoneCoreFactoryImpl.java:57)
25	... 17 more
26	java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app-lib/com.MyApp.MyApp-2/libbctoolbox-armeabi-v7a.so" has unexpected e_machine: 40
27	at org.linphone.core.LinphoneCoreFactoryImpl.<clinit>(LinphoneCoreFactoryImpl.java:71)
28	at java.lang.Class.classForName(Class.java)
29	at java.lang.Class.forName(Class.java:251)
30	at java.lang.Class.forName(Class.java:216)
31	at org.linphone.core.LinphoneCoreFactory.instance(LinphoneCoreFactory.java:47)
32	at com.MyApp.MyApp.sip.XXXXX.initSipLibrary(XXXXX.java:254)
33	at com.MyApp.MyApp.telephony.XXXXX.onCreate(XXXXX.java:26)
34	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2572)
35	at android.app.ActivityThread.access$1800(ActivityThread.java:135)
36	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
37	at android.os.Handler.dispatchMessage(Handler.java:102)
38	at android.os.Looper.loop(Looper.java:136)
39	at android.app.ActivityThread.main(ActivityThread.java:5021)
40	at java.lang.reflect.Method.invokeNative(Method.java)
41	at java.lang.reflect.Method.invoke(Method.java:515)
42	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827)
43	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643)
44	at dalvik.system.NativeStart.main(NativeStart.java)
45	Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app-lib/com.MyApp.MyApp-2/libbctoolbox-armeabi-v7a.so" has unexpected e_machine: 40
46	at java.lang.Runtime.loadLibrary(Runtime.java:364)
47	at java.lang.System.loadLibrary(System.java:526)
48	at org.linphone.core.LinphoneCoreFactoryImpl.<clinit>(LinphoneCoreFactoryImpl.java:57)
49	... 17 more
50	java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app-lib/com.MyApp.MyApp-2/libbctoolbox-armeabi-v7a.so" has unexpected e_machine: 40
51	at java.lang.Runtime.loadLibrary(Runtime.java:364)
52	at java.lang.System.loadLibrary(System.java:526)
53	at org.linphone.core.LinphoneCoreFactoryImpl.<clinit>(LinphoneCoreFactoryImpl.java:57)
54	at java.lang.Class.classForName(Class.java)
55	at java.lang.Class.forName(Class.java:251)
56	at java.lang.Class.forName(Class.java:216)
57	at org.linphone.core.LinphoneCoreFactory.instance(LinphoneCoreFactory.java:47)
58	at com.MyApp.MyApp.sip.XXXXX.initSipLibrary(XXXXX.java:254)
59	at com.MyApp.MyApp.telephony.XXXXX.onCreate(XXXXX.java:26)
60	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2572)
61	at android.app.ActivityThread.access$1800(ActivityThread.java:135)
62	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
63	at android.os.Handler.dispatchMessage(Handler.java:102)
64	at android.os.Looper.loop(Looper.java:136)
65	at android.app.ActivityThread.main(ActivityThread.java:5021)
66	at java.lang.reflect.Method.invokeNative(Method.java)
67	at java.lang.reflect.Method.invoke(Method.java:515)
68	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827)
69	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643)
70	at dalvik.system.NativeStart.main(NativeStart.java)

Any idea ?

**Comment by nhoxbypass** [comment]
I got same problem as you. Have you found a way to fix it?

**Comment by DatBewar** [comment]
Hello, how did you build you application?

**Comment by jfalexvijay** [comment]
Hi DatBewar,

I compiled the linphone source in Mac OS Version 10.12.x.

I used ```"./prepare.py -DENABLE_NON_FREE_CODECS=ON"``` and ```"make"``` to generate libraries for 2017 build. I did the same for 2016 build and it was fine. 

Last build I created on Feb-2017
Previous to previous build created on 2016 before Nov.

Now I got the updated linphone code and trying to compile it. It is giving ```"ERROR: You need at leat CMake version 3.7."``` 

When I try to update cmake it is giving another error like:
```jfalexvijay-iMac:linphone-android root# brew upgrade cmake
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Error: cmake 3.4.3 already installed
jfalexvijay-iMac:linphone-android root# 
```
I am checking what I missed to compile.

Still I am worried about the same crash again. Please help me about the crash ```"has unexpected e_machine: 40"```
