### ISSUE TITLE
DOUBLE MESSAGE ENTRY

### ISSUE THREAD

**Issue by RajanVindaloo** [BelledonneCommunications/linphone-android#491]
When I send a message(A-to-B), it will send with for eg. "sip:111@adf.cga.abc". On the other side, after replying from B to A, I found two entries on device A. When I put that into debug, I found that there are different entries, one is with "sip:111@123.321.123.21" and the other is with "sip:111@adf.cga.abc".

**Comment by AlessandroBagnoli** [comment]
I got the same exact problem (https://github.com/BelledonneCommunications/linphone-android/issues/107) still no solution.

**Comment by Viish** [comment]
I close this issue, no need to have two of them.

**Comment by RajanVindaloo** [comment]
You have closed issue. That's fine but, is there any solution for that
problem? Provide me a link for it.

**Comment by Viish** [comment]
Follow ticket https://github.com/BelledonneCommunications/linphone-android/issues/107
