### ISSUE TITLE
chat message database

### ISSUE THREAD

**Issue by rolloaxel** [BelledonneCommunications/linphone-android#492]
Hello,

I've got an issue on chat message from linphone. Is it possible to not allowed chat message to be retransmitted in case of network issues?

For now, delayed chat messages are stacked on the "linphone.db" file until i re open my app. The best way i found is to delete this file to avoid to send back all the delayed message...

Any better hidden method ?

**Comment by Viish** [comment]
Hi,
I don't understand your issue.
Messages are stored in db. Sent messages aren't retransmitted automatically if there was an sending issue, but they are stored so you will see that you tried to send them and failed.
Only the server can resend messages automatically to a recipient that hasn't receive them, but that supposes your message has been correctly sent.

**Comment by rolloaxel** [comment]
Oh ok, the issue i have isn't linked to the chat message also..

I will investigate about firebase events, 

thank you
