### ISSUE TITLE
How to implement logout and delete it's preference ?

### ISSUE THREAD

**Issue by Miteshmakwana73** [BelledonneCommunications/linphone-android#494]
I want to implement logout user functionality but I can't find the saved shared preference.

I have implemented this code it's working ok but still it's not transferring activity to AssistantActivity and it's calling LinphoneActivity without login of any user.

how can i completly remove account info so it's redirect to login like first launch.

```
LinphoneAuthInfo authInfo = getAuthInfo(n);
if (authInfo != null) {
       getLc().removeAuthInfo(authInfo);
}

LinphoneProxyConfig proxyCfg = getProxyConfig(n);
if (proxyCfg != null)
	getLc().removeProxyConfig(proxyCfg);
if (getLc().getProxyConfigList().length != 0) {
	resetDefaultProxyConfig();
} else {
	getLc().setDefaultProxyConfig(null);
}
getLc().refreshRegisters();
```

**Comment by Viish** [comment]
getLc().clearAllAuthInfo();
getLc().clearProxyConfig();
