### ISSUE TITLE
How to Solve the Problem of One Device Exhaling and Multiple Devices Receiving in a LAN

### ISSUE THREAD

**Issue by fengsimon** [BelledonneCommunications/linphone-android#495]
Hi,
My linphone is version4.0.1.
Now problem is as follows:
I set three devices in a LAN to the same short number 567，When another device calls 567，Of the three devices, only the smallest IP address devices has a ringtone, and the other two have not received an inviter. I see this information from the logs of the exhaled devices:
“linphone_core_invite_address_with_params(): sound is required for this call but another call is already locking the sound resource. Call attempt is rejected.”
how to slove this problem.

thanks.

**Comment by Viish** [comment]
Use a proxy server and register the three devices to it using the same account.
With peer to peer calls the first device to send a 200 OK to the caller INVITE will block the call for the others.

**Comment by Viish** [comment]
Use a proxy server and register the three devices to it using the same account.
With peer to peer calls the first device to send a 200 OK to the caller INVITE will block the call for the others.
