### ISSUE TITLE
Receiving Video Problems

### ISSUE THREAD

**Issue by fengsimon** [BelledonneCommunications/linphone-android#496]
Hi,
My linphone is version4.0.1.
I set two devices in a LAN to the same short number 555，When another device calls 555 with early media, all two devices ring, but only one device has video. how to make all two devices on the receiving end display video。

thanks.

**Comment by Viish** [comment]
First of all, the 4.0.1 version doesn't handle well early media. Instead use feature/release-4.1-early-media branch.
Secondly, like your other issue, you'll need a proxy that does the early media forking.
