### ISSUE TITLE
How to send custom data to the other side when I use call video and audio

### ISSUE THREAD

**Issue by chnng** [BelledonneCommunications/linphone-android#497]
Just like A calls to B, A sets custom org.linphone.core.Address#setDisplayName and org.linphone.core.Address#setUserData, when B received, org.linphone.core.Call#getRemoteAddress the address only has [Username: A, DisplayName: Extension A, Domain: 192.168.x.xxx], but cannot receive the custom data which A set.
What should I do?

**Comment by Viish** [comment]
The setDisplayName should be done on the Address in the proxyConfig you're using to make a call. If correctly set, the call recipient should be able to display it.
However the userData is just a local object for you to use if you want to store some object in one place of your app and retrieve it elsewhere in the same app with the same context, that's all.

**Comment by chnng** [comment]
> The setDisplayName should be done on the Address in the proxyConfig you're using to make a call. If correctly set, the call recipient should be able to display it.
> However the userData is just a local object for you to use if you want to store some object in one place of your app and retrieve it elsewhere in the same app with the same context, that's all.

Thank you for your response, I'd realized userData is a local object, I actually want to transfer some data like json or others, firstly I try setDisplayName in creating account (it's that correct?), and
Core#getDefaultProxyConfig#getIdentityAddress#setDisplayName,
it's still not received by the recipient, but show Extension XXX.
Then I use CallParams#addCustomHeader, but CallParams#getCustomHeader by recipient doesn't get the value, I found other solution like:
https://stackoverflow.com/questions/35793667/how-to-add-custom-header-with-sip-register-request
it can be valid? but I prefer want to use original api in linphone. What did I miss?

**Comment by chnng** [comment]
Oh! When I set the key "x-extraData" to addCustomHeader, it's any special? Because I used "test" as CustomHeader's key before and I got null. It's should be start with "x-"? I don't know, but it's work!
https://blog.csdn.net/yfloctar/article/details/78684535

**Comment by Viish** [comment]
Yes custom headers should start by "X-" because of the SIP grammar our parser won't parse your custom header unless it matches a standard header or a extension one ("X-").
If you want to send information you can also use a simple text message and parse it on the other side.

**Comment by Irfanulhaq1991** [comment]
@Viish  I have similar issue even I have set the header according to sip X parameter.  

Header Key: 
`const val PARTICIPANT_HEADER_KEY = "X-extraData"`

Updating parameter:
```
 private fun updateRemoteParticipants(participantAddress: String, isAdded: Boolean = true) {
        Log.d(TagConf,"updateRemoteParticipants ")
        val calls = core.calls
 calls.forEach {
            params?.addCustomHeader(PARTICIPANT_HEADER_KEY, "Linphone Custom header")
            it.update(params)
        }
 }
}
```
Getting parameter:

```
 val currentCall = core.currentCall ?: return

val participantJsonString =
            currentCall.remoteParams?.getCustomHeader(PARTICIPANT_HEADER_KEY)
        Log.d(TagConf, "participant added: ${participantJsonString}")
    
```

logcat output:
`participant added: null`


I have spent enough time on this but could not find the reason why it is returning null instead of the parameter.

**Comment by Viish** [comment]
If you try to get the param you set on the same device, don't use currentCall.remoteParams but currentCall.params or currentCall.currentParams.
