### ISSUE TITLE
chat is not working

### ISSUE THREAD

**Issue by Miteshmakwana73** [BelledonneCommunications/linphone-android#499]
I am trying to chat with other user but it shows message sent successful but the message is not delivered to another user.

in some user it's show message send failed but the other user get that message

it's only delivering the message when the message sending goes failed and when the second user tries to reply then its show messing sent but the first user not get the message.

if the user is able to send a message then that user is not able to receive any message and if user received the message then that user message not delivered. 

how do I give both functionality send and receive a message to the user?

I am using [this](https://github.com/BelledonneCommunications/linphone) linphone version project.

**Comment by Viish** [comment]
Hi,
Please attach logs from both sides showing the problem.
Thanks.

**Comment by Miteshmakwana73** [comment]
getting this logs on send button

```
2019-03-11 16:43:38.633 7461-7461/org.linphone W/IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
2019-03-11 16:43:38.640 7461-7461/org.linphone W/IInputConnectionWrapper: getSelectedText on inactive InputConnection
2019-03-11 16:43:38.653 7461-7461/org.linphone W/IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection
```

**Comment by Viish** [comment]
Enable linphone library logs please, can't do much without them.

**Comment by Miteshmakwana73** [comment]
How can I enable linphone library logs?

**Comment by Viish** [comment]
Go to settings->advanced->enable debug logs

**Comment by Miteshmakwana73** [comment]
Please help me, did't find and setting for enable debug logs

**Comment by Miteshmakwana73** [comment]
@Viish did you find any solution?

**Comment by Viish** [comment]
@Miteshmakwana73 It doesn't look like it is a library issue, more a server issue.
From the logs the message is correctly sent and your server aknowledges it's reception.
So check your server logs to see why the message isn't sent to the recipient.

**Comment by Miteshmakwana73** [comment]
thank you @Viish for your response but we are not using any server for chatting we are just using your [library](https://github.com/BelledonneCommunications/linphone) 

is the server is required for chatting? if yes then please suggest me what kind of server is required?

PLEASE SUGGEST ME

**Comment by Viish** [comment]
From the logs you are using a proxy which user-agent is "SWITCH", probably hosted on xyz.mydomain.com.

**Comment by Miteshmakwana73** [comment]
is there any extra kind of setup for a chat?

**Comment by Viish** [comment]
No there isn't. But in order to reach a recipient, either for call or chat the app needs a proxy server (the one you are using is the domain you give during login).
And for some reason this proxy server fails to forward chat messages. 
You can try with two sip.linphone.org accounts (you can create them for free).

**Comment by Miteshmakwana73** [comment]
is there any an app to install on server for chatting? because a call is working fine with this domain

**Comment by Viish** [comment]
Maybe your SIP account provider doesn't support chat. Maybe your account configuration isn't correct for this provider.
Which one are you using ?

**Comment by Miteshmakwana73** [comment]
we are using our custom sip server that doesn't support chat.
is it required chat support?

can you please share me open source chat server?

**Comment by Viish** [comment]
If your proxy server doesn't handle chat, it is expected that the app won't be able to use this feature...
You won't be able to use another proxy just for chat and the one you currently have for calls.
You can use our own proxy server named Flexisip, or almost any SIP proxy server like Asterix, Kamailio, etc...

**Comment by Miteshmakwana73** [comment]
We are using freeswitch server, is there any extra kind of configuration needed for chat? 

It something similar to Asterix

**Comment by Viish** [comment]
I'm no freeswitch expert, can't help you with that, sorry.

**Comment by Miteshmakwana73** [comment]
Okay @viish, Thank you for your help.
