### ISSUE TITLE
App crash on start Android

### ISSUE THREAD

**Issue by abhijeetdhole** [BelledonneCommunications/linphone-android#50]
After following the installation steps project imported successfully in android studio. But on app start getting following exception.

JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.ClassNotFoundException: Didn't find class "org.linphone.core.LinphoneCore$AuthMethod" on path: DexPathList[[zip file "/data/app/org.linphone-2/base.apk"],nativeLibraryDirectories=[/data/app/org.linphone-2/lib/arm, /data/app/org.linphone-2/base.apk!/lib/armeabi, /vendor/lib, /system/lib]]

  at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
04-13 20:36:45.166 14775-14775/org.linphone A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:511)
04-13 20:36:45.166 14775-14775/org.linphone A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:469)
04-13 20:36:45.166 14775-14775/org.linphone A/art: art/runtime/java_vm_ext.cc:410]   at long org.linphone.core.LinphoneCoreImpl.newLinphoneCore(org.linphone.core.LinphoneCoreListener, java.lang.String, java.lang.String, java.lang.Object) (LinphoneCoreImpl.java:-2)
04-13 20:36:45.166 14775-14775/org.linphone A/art: art/runtime/java_vm_ext.cc:410]   at void org.linphone.core.LinphoneCoreImpl.<init>(org.linphone.core.LinphoneCoreListener, java.io.File, java.io.File, java.lang.Object) (LinphoneCoreImpl.java:185)
04-13 20:36:45.166 14775-14775/org.linphone A/art: art/runtime/java_vm_ext.cc:410]   at org.linphone.core.LinphoneCore org.linphone.core.LinphoneCoreFactoryImpl.createLinphoneCore(org.linphone.core.LinphoneCoreListener, java.lang.String, java.lang.String, java.lang.Object, java.lang.Object) (LinphoneCoreFactoryImpl.java:104)
04-13 20:36:45.166 14775-14775/org.linphone A/art: art/runtime/java_vm_ext.cc:410]   at void org.linphone.LinphoneManager.startLibLinphone(android.content.Context) (LinphoneManager.java:589)
04-13 20:36:45.166 14775-14775/org.linphone A/art: art/runtime/java_vm_ext.cc:410]   at org.linphone.LinphoneManager org.linphone.LinphoneManager.createAndStart(android.content.Context) (LinphoneManager.java:235)
04-13 20:36:45.166 14775-14775/org.linphone A/art: art/runtime/java_vm_ext.cc:410]   at void org.linphone.LinphoneService.onCreate() (LinphoneService.java:160)
04-13 20:36:45.166 14775-14775/org.linphone A/art: art/runtime/java_vm_ext.cc:410]   at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:2884)
04-13 20:36:45.166 14775-14775/org.linphone A/art: art/runtime/java_vm_ext.cc:410]   at void android.app.ActivityThread.access$1900(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:153)
04-13 20:36:45.166 14775-14775/org.linphone A/art: art/runtime/java_vm_ext.cc:410]   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1434)
04-13 20:36:45.166 14775-14775/org.linphone A/art: art/runtime/java_vm_ext.cc:410]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
04-13 20:36:45.166 14775-14775/org.linphone A/art: art/runtime/java_vm_ext.cc:410]   at void android.os.Looper.loop() (Looper.java:148)
04-13 20:36:45.166 14775-14775/org.linphone A/art: art/runtime/java_vm_ext.cc:410]   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:5441)
04-13 20:36:45.166 14775-14775/org.linphone A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
04-13 20:36:45.166 14775-14775/org.linphone A/art: art/runtime/java_vm_ext.cc:410]   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:738)
04-13 20:36:45.166 14775-14775/org.linphone A/art: art/runtime/java_vm_ext.cc:410]   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:628)

Thanks in advance

**Comment by nhoxbypass** [comment]
Do you found a way to fix it? I have the same issues with you.

**Comment by DatBewar** [comment]
Hello, did you try our last release?
https://www.linphone.org/releases/android/linphone-latest.apk

**Comment by CrabeMan** [comment]
Hello,
Have you copy the Java interface into your projet and setup it into your app/build.gradle ?

Create a `srcLibs` folder into your `app` folder, and copy interface
```
cp -rf submodules/linphone/java/common/* ../app/srcLibs
cp -rf submodules/linphone/java/impl/* ../app/srcLibs
cp -rf submodules/linphone/java/j2me/* ../app/srcLibs
cp -rf submodules/linphone/java/j2se/* ../app/srcLibs
cp -rf submodules/linphone/mediastreamer2/java/src/* ../app/srcLibs
cp -rf submodules/externals/axmlrpc/src/main/java/* ../app/srcLibs
cp -rf submodules/linphone/coreapi/help/java/* ../app/srcLibs
```


Edit your `app/build.gradle ` to look like
```
    sourceSets {
        main {
            manifest.srcFile 'src/main/AndroidManifest.xml'
            java.srcDirs = ['src/main/java', 'srcLibs']
            resources.srcDirs = ['src/main/java', 'srcLibs']
            aidl.srcDirs = ['srcLibs']
            renderscript.srcDirs = ['src/main/java', 'srcLibs']
            res.srcDirs = ['src/main/res']
            assets.srcDirs = ['assets']
            jniLibs.srcDir 'jniLibs'

            java.exclude '**/mediastream/MediastreamerActivity.java'
        }
    }
```

Hope this will help you
CrabeMan.
