### ISSUE TITLE
Google pixel 2 &3 crash on load release v4.0.1

### ISSUE THREAD

**Issue by S0U1SB4N3** [BelledonneCommunications/linphone-android#502]
This has been an ongoing issue with the Google pixels I've tested on pixel 2 but your recent release to the play store crashes with the new pixel 3. Does any of your dev team own a pixel 2 or 3 they can test on and find a solution. It's with the address wifi and GSM channel is as far as ive been able to narrow it down to.  ISP connectivity issues

**Comment by Viish** [comment]
No we don't have a Pixel 2 or 3.
But you can enable library logs and send them along with the crash stacktrace, that should be enough for us to fix it.

**Comment by S0U1SB4N3** [comment]
thanks ill order one today to test on. it does not load on the android studio virtual device ... just fyi

**Comment by Viish** [comment]
Reopen this issue once you'll have logs, in the meantime I close it.
