### ISSUE TITLE
linphone-sdk-android - gradle AAR build ignores CMAKE_BUILD_TYPE=Release

### ISSUE THREAD

**Issue by licaon-kter** [BelledonneCommunications/linphone-android#503]
...and always builds the Debug version: https://gitlab.linphone.org/BC/public/linphone-sdk/blob/master/cmake/Android/GenerateSDK.cmake#L25

eg. `'s/assembleDebug/assembleRelease/g'` fixes it

**Comment by Viish** [comment]
Yes I also noticed that yesterday.
Fix is currently on linphone-sdk's fix/android_real_debug_and_release_aar branch but will be merged soon. Currently the "debug" AAR was in fact a release one except for the java wrapper minification.
