### ISSUE TITLE
How to obtain a copy of lft.php for debug logs to personal server

### ISSUE THREAD

**Issue by S0U1SB4N3** [BelledonneCommunications/linphone-android#506]
I need the lft.php script so I can test this on my personal AWS server

**Comment by S0U1SB4N3** [comment]
in iPhone we have the option to email the logs and the linphone.rc I want the same functionality on the android or at least to view the same logs I can on the iPhone

**Comment by S0U1SB4N3** [comment]
@Viish @DatBewar 
I have been using the feature4.1 qr code 
and it has errors merging several remote provisioning files, it doesn't appear to be overwriting appropriately and locks up on the proxyconfig entries. 
can you send an example of a blank or sample remote provisioning file with all available fields

**Comment by Viish** [comment]
Remote provisioning sample can be found at https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Remote%20Provisioning/
File transfer php script sample can be found at https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/File%20transfer/

**Comment by S0U1SB4N3** [comment]
I've ran your lft.php script, ill figure it out on my end. but the question still remains about the remove provisioning xml. 

the documentation does not show <section name="auth_info_0"> or <section name="proxy_0">
which are required for it to configure a sip account. I have generated a minimal one that works but are there any other options within this section. also how would I remote provision 2 accounts back to back (simultaneously) because the system seems to not switch accounts very well, it hangs up on the proxy config. 

as if the <section name="proxy_<number>"> section does not get rewritten, also the password parameter seems to be hit or miss because when I go back into the account settings it's missing. There are several re-write bugs with remote provisioning. on the overwrite sections. they are hanging in the software, I have to go into android settings -> app settings -> and remove all stored data. then remote provision one account. and it works again, but if I remote provision 2 accounts, it hangs up agin on the overwrite. I can produce a short video and send the link if you would like.

**Comment by S0U1SB4N3** [comment]
@Viish 
/data/data/org.linphone.debug/files/linphonerc

where are the accounts stored as this file does not contain any of the account auth information.

**Comment by Viish** [comment]
/data/data/org.linphone.debug/files/.linphonerc

**Comment by S0U1SB4N3** [comment]
thank you

**Comment by S0U1SB4N3** [comment]
<img width="723" alt="Screen Shot 2019-03-18 at 11 04 57 AM" src="https://user-images.githubusercontent.com/22788570/54540059-af21c680-496d-11e9-9c36-1b03d701e0d0.png">

this is all that is in the file even after I registered 2 accounts through remote provisioning. 
this is with your features4.1 build no editing from my end.

**Comment by Viish** [comment]
notice the . between the / and linphonerc
/files/linphonerc is the default one, /files/**.**linphonerc is the one with all the infos.
