### ISSUE TITLE
Keystore file '/opt/linphone-android/""' not found for signing config 'release'.

### ISSUE THREAD

**Issue by yuexiajiayan** [BelledonneCommunications/linphone-android#507]
run: make  liblinphone-android-sdk   have this .
make end is ok 

？？？？？？？？？？？？？？？
Warning: The rule `-keep public class *extends java.lang.annotation.Annotation {
  *;
}` uses extends but actually matches implements.

> Task :validateSigningRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':validateSigningRelease'.
> Keystore file '/opt/linphone-android/""' not found for signing config 'release'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
46 actionable tasks: 27 executed, 19 up-to-date
Makefile:152: recipe for target 'release' failed
make: *** [release] Error 1

**Comment by Viish** [comment]
Hi,
Yes this target does a "release" so it tries to sign it using a keystore which it doesn't find.
Instead use debug-sdk target.
