### ISSUE TITLE
Can use my own TURN server

### ISSUE THREAD

**Issue by tsuku** [BelledonneCommunications/linphone-android#508]
Version: Android Linphone 4.0.1(4004)

I use two *linphone.org* accounts and set my own TURN server in two devices. But in my router I monitor Linphone still use *linphone.org*'s relay ip. 

I have tried Android aTalk and Jitsi for Windows, both use XMPP account with adding TURN server, the relay call can use my TURN server. 

Can I set my TURN server with linphone.org's account ? Although I know there are some differences between SIP and XMPP, I also find Jitsi for Windows with SIP account don't support TURN server setting.

**Comment by licaon-kter** [comment]
I'm not seeing any TURN requests on 4.1 either, when setting it in account and general settings. STUN port is accessed though.

**Comment by tsuku** [comment]
@licaon-kter 
Do you try other Linphone versions or other SIP clients which support TURN server ?  I have not ever  succeed in SIP call with own TURN server. I'm not sure the SIP server or SIP proxy cause it.

I found a talk about SIP TURN setting in Jitsi. 
https://community.jitsi.org/t/jitsi-users-jitsi-sip-and-turn/4427/2
>The main reason is that most SIP servers are configured to provide
hosted NAT traversal. They would override the SDP that clients send
and put themselves in the media path for all calls.

**Comment by licaon-kter** [comment]
The SIP situation is kinda dire, at least open-source for Android.

Now I'm only testing Linphone (voice works, video never) and baresip (only voice).

**Comment by Viish** [comment]
Our TURN implementation in the library is young so it is very likely to have some issues depending on the server you are using. If you want to share your config and logs that can help us improve that.
However STUN is quite stable.

**Comment by Viish** [comment]
@licaon-kter Why do you say video never works for you ? If that's the case, please open a ticket with logs. Video is one of our strong suits and should work very well, even much if audio works.

**Comment by licaon-kter** [comment]
@Viish I intend to open, didn't get a chance to logcat it :)

Basically:
* Linphone<>Linphone, press video and the circle animation appears over the camera icon, never opening video transmission nor local preview (bath ends do this, Android 9 and Android 6.0.1)
* Linphone<>baresip, press video and see local preview and a black screen for remote, as expected since baresip doesn't do video (yet?)

Anyway. i'll open a proper issue for video when I capture the needed debug info.

**Comment by Viish** [comment]
Have you tried by setting the automatically start/accept video policy ?
Anyway I'll wait for your logs, this is the kind of issue that must be fixed before the release.

**Comment by licaon-kter** [comment]
@Viish I did :) 

I will

**Comment by tsuku** [comment]
@Viish Thanks for your reply.

I use apt install *coturn*, I only add the following lines to /etc/turnserver.conf, then run it with command *turnserver* in PuTTY.

coturn version: 4.5.0.5-1+deb9u1
```
listening-port=
tls-listening-port=
listening-ip=
relay-ip=
external-ip=
```
I didn't configure the TLS and  username password.
I am not familiar with TURN server configure. Is there any suggested server and configure which is compatible with Linphone?

**Comment by Viish** [comment]
@tsuku 
We also use coturn (4.5.0-3) for our tests.
Our configuration listen to the port 3479 and we have disabled tls.
Also lt-cred-mech, no-tcp, no-tls, no-dtls and no-tcp-relay are uncommented.
Finally we use a hard coded user/password in the config file.
