### ISSUE TITLE
unable to register after calling LinphoneManager.destroy() linphone 4.0.1

### ISSUE THREAD

**Issue by H4M3DR** [BelledonneCommunications/linphone-android#509]
hi
i'm getting registration failed after LinphoneManager.destroy() called, but when i kill the app in recent apps, i can register again. what's wrong here?

**Comment by Viish** [comment]
Hi,
If you destroy the LinphoneManager, it will destroy the Core which is the base object of our library. So it is expected that you can't do much after that.
If you kill the app from the recent tasks, it will finish to destroy what you haven't destroyed yet (like the service) and so the next start will re-create everything and it will work as expected.
The point is: do not destroy the Manager or the Core if you want the app to work (unless you are using push notifications, in that case destroy the Service).
