### ISSUE TITLE
What is the interface for sending REGISTER requests

### ISSUE THREAD

**Issue by fengsimon** [BelledonneCommunications/linphone-android#510]
Hi,
My linphone is 4.0.1.
To achieve login and heartbeat functions, i need to send REGISTER to a common SIP Server, just like as: 
REGISTER sip: sipproxy.aaa.com:25060 SIP/2.0.
.......................
With linphone, what API should I use to send REGISTER?
thanks.

**Comment by Viish** [comment]
Hi,
REGISTER is sent automatically, but you can force a refresh of the REGISTERs by calling core.refreshRegisters();
