### ISSUE TITLE
Dynamic remote provisioning request

### ISSUE THREAD

**Issue by S0U1SB4N3** [BelledonneCommunications/linphone-android#511]
as in #294 we are still having a remote provisioning overwrite error. 

my request is how can I get multiple remote provisioning accounts without knowing what number it is 

I know I can do the following 
 `<section name="auth_info_0"> `
`<section name="proxy_0">`
and 
 `<section name="auth_info_1">`
 `<section name="proxy_1">`

in a single remote provisioning file. however we need a wild card that just puts it next in line 

like the following 
a dynamic assigned number done by Linphone-android when it receives a remote provisioning file. 
 `<tsection name="auth_info_*">`
 `<section name="proxy_*">` 

it will automatically look in Linphonerc does proxy_0 exist 
if yes then 
does proxy_1 exist 
if yes then 
does proxy _2 exist
if no then 
take proxy_* and overwrite to proxy_2

sudocode @Viish @BelledonneComm @DatBewar

**Comment by Viish** [comment]
We don't have such mechanism.
What you can do is using a transient remote provisionning (so it is applied only once) and use proxy_1024 (or any other large number) so it will not override (and the core will use the correct next int value when saving the rc). However if you do remote provisioning more than once you will have duplicates.
