### ISSUE TITLE
App crash on background for Android 8.1

### ISSUE THREAD

**Issue by TestWts2017** [BelledonneCommunications/linphone-android#512]
W/linphone: Deletion of OpenSLES context [0xe5996880]
    
    --------- beginning of crash
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x1f4 in tid 11032 (package name), pid 11032 (package name)

I am testing it in Samsung J7 Prime with Android 8.1.0

**Comment by Viish** [comment]
Thanks but I'll need the logs that follow --------- beginning of crash to be able to do something.

**Comment by OwaisKhatri** [comment]
I got this log:
`A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x1f4 in tid 11032 (package name), pid 11032 (package name)`

When initiating any outgoing call.
