### ISSUE TITLE
Latest ndk is r19

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#516]
But `prepare.py` says it only works with r18.  r18 is not available for all practical purposes given that https://developer.android.com/ndk/downloads/older_releases.html completely obscures the pane that allows you to download older releases.

Can r19 really not be used?

**Comment by licaon-kter** [comment]
Works with 16 through 19b.

**Comment by Viish** [comment]
Indeed on the master and release/4.0.1 branches with their current submodules you can't build using a NDK r19 or r19b.
However on the feature/release-4.1 branch using the linphone-sdk repository, you can use any NDK between 16 and 19b.

**Comment by licaon-kter** [comment]
@brianjmurrell The old NDK page works ok for me. Try to disable your ads blocking extensions and such.

**Comment by brianjmurrell** [comment]
@licaon-kter Awesome!  That's exactly what I was looking for.

**Comment by licaon-kter** [comment]
@brianjmurrell bookmark this
https://gitlab.com/fdroid/fdroidserver/blob/master/makebuildserver#L173
