### ISSUE TITLE
FEATURE/RELEASE.4.1 Download remote provisioning file Fails android API 28 

### ISSUE THREAD

**Issue by S0U1SB4N3** [BelledonneCommunications/linphone-android#518]
as of 11:50 CST I downloaded your feature-release4.1 
I loaded it to my Note 9 and it fails to download remote provisioning files. 
this worked 2 weeks ago with this pull but todays was broken. 

ive tested and confirmed with any emulator build within android studio with API 28 (android 9 pie) fails to download remote provisioning file. 

the error message is "failed to download"

the stac is 

E/libc: Access denied finding property "net.dns1"
    Access denied finding property "net.dns2"
    Access denied finding property "net.dns3"

this works fine with an older test hardware running api 22. but not on the latest android os update. 

@Viish @DatBewar @BelledonneComm

**Comment by S0U1SB4N3** [comment]
D/ConnectivityManager: requestNetwork; CallingUid : 11105, CallingPid : 3774
E/libc: Access denied finding property "net.dns1"
    Access denied finding property "net.dns2"
    Access denied finding property "net.dns3"
    Access denied finding property "net.dns1"
    Access denied finding property "net.dns2"
    Access denied finding property "net.dns3"
D/ViewRootImpl@e4f7b4d[AssistantActivity]: dispatchDetachedFromWindow
    Surface release. android.view.ViewRootImpl.doDie:7931 android.view.ViewRootImpl.die:7899 android.view.WindowManagerGlobal.removeViewLocked:497 android.view.WindowManagerGlobal.removeView:435 android.view.WindowManagerImpl.removeViewImmediate:124 android.app.Dialog.dismissDialog:517 android.app.Dialog.dismiss:500 org.linphone.assistant.AssistantActivity$1.onConfiguringStatus:179 
D/InputTransport: Input channel destroyed: fd=123

**Comment by Viish** [comment]
Access denied finding property "net.dns2" is an expected error on recent Android
Attach full logs if you want help, otherwise please stop opening tickets.

**Comment by S0U1SB4N3** [comment]
[5c9532a50069e_44aba3c7690c3e8eb726.txt](https://github.com/BelledonneCommunications/linphone-android/files/2997956/5c9532a50069e_44aba3c7690c3e8eb726.txt)
@Viish

**Comment by S0U1SB4N3** [comment]
this is from the debug logs within the app from feature/release-4.1 that I downloaded at 11:50 CST today

**Comment by Viish** [comment]
From your logs, for some reason, it fails to use your mobile internet connection DNS to resolve your domain omnivoice.smartchoiceus.com
Have you tried on another network ?

**Comment by S0U1SB4N3** [comment]
yes both local wifi and 4gLTE cellular, however I fi went to my web browser it loaded the page requested just fine. any ideas on where the connection takes place in the code and I can take a look there.

**Comment by Viish** [comment]
I made changes regarding the Network Manager, use AAR 4.1-312-gbaecc61
