### ISSUE TITLE
Shows Not registered

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#519]
I'm using current [feature/release-4.1](https://github.com/BelledonneCommunications/linphone-android/tree/feature/release-4.1).  It's generally working, but currently as I look at the interface right now it says _Not registered_.

But if my PBX sends an `INVITE`, Linphone receives it and answers it.

How can Linphone not be registered if it's getting calls and why is it showing as _Not registered_?

**Comment by brianjmurrell** [comment]
Similarly, on some networks, like my mobile provider's network, I see _Registration in progress_ for a long time (forever maybe?).  Even though I am clearly registered as again, the phone receives calls from the SIP server.

**Comment by Viish** [comment]
With that much information I can't tell for sure.
One possibility is you have 2 proxy config, the default one is indeed not registered but you have a second one that is registered and receives the INVITE.

**Comment by brianjmurrell** [comment]
I am only configured to a single PBX through no proxies.

**Comment by Viish** [comment]
Then if you are not using a proxy it's expected to be "not registered".

**Comment by brianjmurrell** [comment]
Why would it be _Not registered_ if it's registered to a PBX directly, not via a proxy?

FWIW, Linphone does show registered most of the time, so this was very clearly an anomaly when it happened.

**Comment by Viish** [comment]
If the client sends a Register, then you are using a proxy server. If you do peer to peer, you're not using a proxy. And if sometimes the client says you are registered, you have configured a proxy config in your client.

**Comment by Viish** [comment]
And since you are using UDP, you can be unregistered because a packet has been lost, but you can still receive an INVITE packet that will be correctly handled.

**Comment by brianjmurrell** [comment]
> If the client sends a Register, then you are using a proxy server.

But a client can _register_ with a SIP server/PBX (i.e. Asterisk) directly, and indeed needs to register so that the PBX knows where to send the INVITE.

> If you do peer to peer, you're not using a proxy.

Is that what linphone registering to Asterisk is considered?  _Peer-to-peer_?  Just asking so that I use the correct nomenclature in the future.

> And if sometimes the client says you are registered, you have configured a proxy config in your client.

I did notice that the account that I configured for my Asterisk server does have an _Proxy_ configured as the same name as my Asterisk server, but that account also has _Outbound proxy_ disabled.

Does the _Outbound proxy_ being disabled mean that the _Proxy_ setting, even if an address is configured into it, is ignored?

**Comment by Viish** [comment]
You should read this: https://www.webopedia.com/TERM/S/SIP_proxy.html
Asterix is a proxy server.
Outbound proxy is just a configuration item to route your packets through another proxy server before reaching the one your configuration uses.

**Comment by brianjmurrell** [comment]
OK.  So in Linphone, _Proxy_ is what Linphone found as the destination for the domain (using SRV records, etc if applicable) and the selected _Transport_.

So, then, yes, I am using a _proxy_ to which I have to register and should be registered, which comes back to the original problem description that Linphone will show _Not registered_ when in fact I am registered as the proxy will forward INVITEs to Linphone.

As for blaming UDP's lossiness, first of all, at least in my case, it's not at all, anywhere near as unreliable as people around here like to make it out to be.  I watch this stuff on a packet sniffer all of the time and don't recall ever seeing a dropped UDP package.  And even if the odd UDP packet gets dropped (which should be happening very super rarely here, if it all) shouldn't Linphone retry the registration at least a few times before giving up?

Should this issue be re-opened given all of the above?
