### ISSUE TITLE
Fails to complete registration on multi-homed PBX

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#520]
My PBX is multi-homed, in that it has several IPv6 uplinks to the Internet each with their own prefix.

Linphone seems to fail to complete the registration process if the `OK` response to a `REGISTER` comes from a different IP address than the `REGISTER` went to.

Is this intentional and if so, what purpose does it serve?

**Comment by Viish** [comment]
I don't know if this is intentional or not, but anyway seems to me like a bad idea.

**Comment by brianjmurrell** [comment]
Meaning it's a bad idea to not accept SIP packets that don't come from the IP their queries went to?  If so, I agree.  Particularly with UDP there is no guarantee that packets will come from the same address you sent them to.

And before anyone does, please, let's not debate UDP vs. TCP here.

**Comment by Viish** [comment]
I guess this issue comes from your server configuration. Anyway this is not android-app related, at best it's belong on linphone's repository issues.

**Comment by brianjmurrell** [comment]
No, it's not server configuration.  If a server is multi-homed, with multiple source addresses, there is no guarantee that the same address will be used for incoming and outgoing UDP.  Clients need to be prepared for that and handle it.

> at best it's belong on linphone's repository issues.

But you can understand, for somebody who has not worked with and realised whole stack here, that may not be clear, yes?  So that would be https://gitlab.linphone.org/BC then?

**Comment by Viish** [comment]
Yes that or https://github.com/BelledonneCommunications/linphone

**Comment by brianjmurrell** [comment]
BelledonneCommunications/linphone#111
