### ISSUE TITLE
Doesn't re-register when switching networks

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#521]
When I switch networks from WiFi to mobile or back, Linphone doesn't detect this change and re-register to it's SIP server.

**Comment by Viish** [comment]
We had a lot of troubles lately with the network manager, the latest version that works the best in is linphone commit bb0bb01d6b6886ebd24f4278f25c96d7181deda2.

**Comment by brianjmurrell** [comment]
Where do I find bb0bb01d6b6886ebd24f4278f25c96d7181deda2?

**Comment by Viish** [comment]
In your linphone-sdk repository, in the linphone submodule.

**Comment by brianjmurrell** [comment]
Apologies.  I'm new at this so I don't yet understand the whole ecosystem.

In `~/linphone-android/linphone-sdk-android` I have:

```
-rw-rw-r--. 1 brian brian  433 Mar 22 14:24 build.gradle
-rw-r--r--. 1 brian brian 1068 Mar 22 14:40 linphone-sdk-android.iml
```

But I'm also understanding that the _feature/release-4.1_ branch is now building _linphone-android_ with an _AAR_.  Is that what _linphone-sdk_ builds?

Maybe to cut to the chase, is there an _AAR_ available with bb0bb01d6b6886ebd24f4278f25c96d7181deda2 in it?

**Comment by Viish** [comment]
Here's the link to the latest AAR: http://linphone.org/snapshots/maven_repository/org/linphone/linphone-sdk-android/4.1-312-gbaecc61/linphone-sdk-android-4.1-312-gbaecc61.aar

**Comment by Viish** [comment]
Anyway, here's the architecture: linphone-android is only the UI app.
It relies on our libraries (there are plenty of them), grouped as linphone-sdk repository which is using submodules for each.

**Comment by brianjmurrell** [comment]
And linphone-sdk is built as an _AAR_ and that is imported by _linphone-android_ if I understand correctly.

So how does one tell _linphone-android_ which AAR release/URL/etc. to use if one wants to use something other than what the branch is currently configured to use?

**Comment by Viish** [comment]
Everything is in the app/build.gradle file: the maven URL for the repository, the name of the AAR, it's version, etc...
I might be helpful for you to learn about all this before starting developing for Android: https://developer.android.com/studio/projects/android-library

**Comment by brianjmurrell** [comment]
> https://developer.android.com/studio/projects/android-library

Interesting.  But doesn't exactly cover everything.  I didn't see mention of versioning on that page.

Does the `+` at the end of the version strings:

https://github.com/BelledonneCommunications/linphone-android/blob/7cb275d0541883c41532e9e55ebe23616c00d668/app/build.gradle#L170-L171

mean to use the latest 4.1-* release at http://linphone.org/snapshots/maven_repository/org/linphone/linphone-sdk-android/ each time `./gradlew assembleDebug` is run to build a new release?

So if I just re-run `./gradlew assembleDebug` I should get the new SDK with bb0bb01d6b6886ebd24f4278f25c96d7181deda2 in it?

**Comment by Viish** [comment]
Actually the + means to take any version that starts by 4.1
The first time it will take the last one, but each time you build an APK to my understanding it will not try to get a newer one if available. You may have to clean your cache to force it to take a newer version of the available AAR.

**Comment by brianjmurrell** [comment]
> any version

Really, _any_ as in a random choice or should it always the newest, assuming nothing is cached?

> The first time it will take the last one

Seems to indicate that it actually is the newest, and not just any (random).

> You may have to clean your cache

So remove all of:

```
/home/brian/.gradle/caches/modules-2/files-2.1/org.linphone/linphone-sdk-android/4.1-307-gc40c8be/ffa1c93dca5209a0f43a9e13ca070553018d1380/linphone-sdk-android-4.1-307-gc40c8be.aar
/home/brian/.gradle/caches/modules-2/files-2.1/org.linphone/linphone-sdk-android-debug/4.1-307-gc40c8be/da2463ed6982b49c94449a6dbd5fc53caf9229f0/linphone-sdk-android-debug-4.1-307-gc40c8be.aar
/home/brian/.gradle/caches/transforms-1/files-1.1/linphone-sdk-android-4.1-307-gc40c8be.aar
/home/brian/.gradle/caches/transforms-1/files-1.1/linphone-sdk-android-4.1-307-gc40c8be.aar/c2fc0b5b38b47a330537d8a1a772a554/jetified-linphone-sdk-android-4.1-307-gc40c8be.aar
/home/brian/.gradle/caches/transforms-1/files-1.1/jetified-linphone-sdk-android-4.1-307-gc40c8be.aar
/home/brian/.gradle/caches/transforms-1/files-1.1/linphone-sdk-android-debug-4.1-307-gc40c8be.aar
/home/brian/.gradle/caches/transforms-1/files-1.1/linphone-sdk-android-debug-4.1-307-gc40c8be.aar/54158538c393a3fe103f34cfc173f866/jetified-linphone-sdk-android-debug-4.1-307-gc40c8be.aar
/home/brian/.gradle/caches/transforms-1/files-1.1/jetified-linphone-sdk-android-debug-4.1-307-gc40c8be.aar
```

Or just a subset?

**Comment by Viish** [comment]
Any means the latest at the time it checks
Yes to clean your cache you can rm ~/.gradle/caches/ directory or in Android Studio use the File->Invalidate Caches menu.

**Comment by brianjmurrell** [comment]
> you can rm ~/.gradle/caches/ directory

But surely that contains a lot of stuff that is only just going to get re-downloaded at the same version, no?

**Comment by Viish** [comment]
Maybe, maybe not. That depends on your app dependencies. And that will clean some unused dependencies in the process.

**Comment by brianjmurrell** [comment]
Can confirm that 4.1-312-gbaecc61 does resolve this.

**Comment by Viish** [comment]
Perfect :)
