### ISSUE TITLE
High battery consumption with proxies that don't support IMDN

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#522]
When configured to use a proxy that doesn't support IMDN (I.e. [Asterisk](https://www.asterisk.org/) AFAIK), _linphone-android_ will consume a lot of battery repeatedly sending IMDN messages to the proxy only to receive `SIP/2.0 415 Unsupported Media Type` responses.  This happens repeatedly, draining battery.

A work-around is to set `im_notif_policy=none` in the `[sip]` section of [`linphonerc`](https://github.com/BelledonneCommunications/linphone-android/blob/feature/release-4.1/app/src/main/res/raw/linphonerc_factory) and build a custom version of the app.

But for people using a version from a repository, this is not possible.  There are two solutions here:

1. Provide a UI element to disable IMDN
1. Don't repeatedly send IMDN messages after receiving a `SIP/2.0 415 Unsupported Media Type` response from a proxy.

The first solution of course requires the user to know that their proxy doesn't support IMDN and disable the option.  The second option is more automatic.

**Comment by Viish** [comment]
SDK issue, not Android.

**Comment by brianjmurrell** [comment]
Which project at https://github.com/BelledonneCommunications should this be filed with then?  There are no projects with **sdk** in the name even.

**Comment by Viish** [comment]
It's the top project of the SDK so yes you can open it there.
