### ISSUE TITLE
Trouble receiving calls

### ISSUE THREAD

**Issue by tobiasguimaraes** [BelledonneCommunications/linphone-android#524]
Hello!
Im having some troubles receiving calls,
i can originate without problems, but cant receive calls

Here is the full log:
[log_call.txt](https://github.com/BelledonneCommunications/linphone-android/files/3014345/log_call.txt)

Log from the moment that the call is received
[log_incoming_call.txt](https://github.com/BelledonneCommunications/linphone-android/files/3014359/log_incoming_call.txt)

All listeners are registered, i can call to it using zoiper..

Im using version 4.0.1
Android Moto g 6 Android version 9

Thank you!

**Comment by Viish** [comment]
Just one question: can you check your Core has reached GlobalOn state ?

**Comment by tobiasguimaraes** [comment]
now its reaching, i just forgot to call core.start()..
Thank you!
