### ISSUE TITLE
How to enable TLS accout using linphone-android with kamailio

### ISSUE THREAD

**Issue by SteaveMan22** [BelledonneCommunications/linphone-android#535]
I was installed kamailio server and tls module as a server and linphone as a client (it working with tcp or udp ) but with tls not working 

//tls.cfg file

[server:default]
method = TLSv1.2
verify_certificate = no
require_certificate = no
private_key = /etc/kamailio/kamailio-selfsigned.pem
certificate = /etc/kamailio/kamailio-selfsigned.pem
#ca_list = /etc/kamailio/tls/cacert.pem
#crl = /etc/kamailio/tls/crl.pem
.
.
.
[client:default]
#method = TLSv1
verify_certificate = no
require_certificate = no

**Comment by slegs** [comment]
You have to use a proper signed certificate like Letsencrypt

**Comment by Viish** [comment]
Or to add your custom certificate to the linphone-android root-ca file.

**Comment by SteaveMan22** [comment]
> Or to add your custom certificate to the linphone-android root-ca file.

Hi viish 
thank you for your answer 
how i can add my custom certificate to the linphone-android ??

**Comment by Viish** [comment]
In linphone-sdk project, add your cert to ./linphone/share/rootca.pem

**Comment by SteaveMan22** [comment]
I'm but  the rootca.pem in this path:
linphone-android/submodules/linphone/share/rootca.pem
are this operation want to rebuild ?

**Comment by Viish** [comment]
Yes that should do it.
Otherwise you have API in our library if you want to embed your cert in your app: core.setTlsCert or core.setTlsCertPath

**Comment by SteaveMan22** [comment]
I have some problems with it So
can you provide a tutorial about use TLS in linphone?
like add cert to rootca.pem and use core.setTlsCert and core.setTlsCertPath

**Comment by aliahmaed** [comment]
can you explain how to add tls certificate

**Comment by SteaveMan22** [comment]
Hi @aliahmaed 
I am done  it ^_^
1- generate cert by this 
openssl req -x509 -nodes -days 365 -newkey rsa:4096 -keyout /home/hplab/Desktop/closeSuorceSdk/linphone-android/app/src/main/res/raw/newreq.key -out /home/hplab/Desktop/closeSuorceSdk/linphone-android/app/src/main/res/raw/newreq1.pem

2- add it to linphonerc_default in this path 
linphone-android/app/src/main/res/raw/linphonerc_default
like this :
[sip]
verify_server_certs=0
client_cert_chain=/data/user/0/org.linphone.debug/files/res/raw/newreq1.pem
client_cert_key=/data/user/0/org.linphone.debug/files/raw/newreq.key

3-add the server cert to rootca.pem just the cert 
4-add to  linphonerc_factory in this path 
linphone-android/app/src/main/res/raw/linphonerc_factory
[sip]
verify_server_certs=0

now run the app and it will work In Shaa ALLAL
