### ISSUE TITLE
Enable service notification goes away after app closing

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#536]
Open app, Settings->Advanced->Enable service notification -> set check
Permanent notification appears.
Close app by swiping it out from the runned app list.
Permanent notification disappears.
Open app, Settings->Advanced->Enable service notification is not set

**Comment by Viish** [comment]
Already fixed in 2d2b55166334fb89abda3d80c89c22126b14df89 but thanks for reporting it.

**Comment by 532910** [comment]
It's not fixed.

**Comment by 532910** [comment]
Ok, really partially. The checkbox "Enable service notification" doesn't resets.
But every time I close the app the permanent notification disappears.

**Comment by Viish** [comment]
Yes if you quit using the quit button or kill it from the task manager it will rénové the notification anyway because the app would have been stopped.
The service notification is only there to prevent the OS to kill the service, but the user can still do it.
If You want, you can set to false the boolean kill_service_with_task in the non_localizable_custom xml file.

**Comment by 532910** [comment]
Source code and signature should be named browserpass-native-3.0.4 not just 3.0.4

**Comment by 532910** [comment]
sorry

**Comment by licaon-kter** [comment]
@Viish I find that I bit contrived, the service would mean, to my understanding, that you keep it running no matter what, but then you actually kill it on swipe?

I'd rather have "service" always running and that toggle actually control "kill_service_with_task" instead.

**Comment by Viish** [comment]
@licaon-kter you can't really prevent a user to kill the app if it asks to (which is the purpose of the swipe kill in task manager), or a least it the choice we made.
Our main objective is to rely on push as most as possible since it is the only repliable way to ensure 100% availability.

**Comment by 532910** [comment]
@Viish, could you say, where `non_localizable_custom.xml` file should be placed?
I've found in the wiki `res/values` path, but it's still unclear where should it be.

**Comment by Viish** [comment]
It already exists, it is in res/values/

**Comment by 532910** [comment]
But where the res/values are?

**Comment by Viish** [comment]
On master branch it is in the root directory, on feature/release-4.1 branch it is in app/src/main/

**Comment by 532910** [comment]
So it's compile-time configuration, and I can't change it in installed android app?

**Comment by Viish** [comment]
Indeed, but in the code nothing prevents you from doing it dynamically

**Comment by licaon-kter** [comment]
@532910 we do this for F-Droid
See https://gitlab.com/fdroid/fdroiddata/merge_requests/4524/diffs#23aceb5557460e6d4e4e613512f604e30759228b_445_464

**Comment by 532910** [comment]
It's really strange behavior:
I switch on `Background mode` and `Start at boot time` and after reboot I got service with permanent (unclearable) notification. There is no linphone in the app list.
Then I got incoming call and close linphone when call ends.
At this point I have no background service and I can't receive incoming calls more.

I appreciate your main objective to rely on push, but options like `enable service notification` are for making permanent network connection and are against push.

Pushes are good, but could you let people decide would they like to use it or not.

**Comment by 532910** [comment]
BTW, as I know, background service may work without permanent notification.
https://github.com/k9mail/k-9  and https://github.com/mosmetro-android/mosmetro-android
has no permanent notification but has permanently run processes as I've removed them from battery optimization.

**Comment by licaon-kter** [comment]
@532910 On Android Pie? Things have changed....even if you don't have the app notification you'll end up with a system one....

https://developer.android.com/about/versions/pie/power

**Comment by 532910** [comment]
LineageOS 16.9, Android 9

I have no permanent notification for k9, mosmetro-android, and AsteroidOS Sync, but I always see them in the 'Running services' list.
And I see no system notification.

**Comment by Viish** [comment]
@532910 Start at boot time will make the app automatically start when your device boots. Because of some OS restrictions, we can only do that if the service is started as a foreground service, hence the unclearable notification.
However, once the app is started (like a call is received or you click on the app icon), if the Service Notification setting is disabled we clear the foreground service (as it wasn't asked by the user). That explain why the notification disappear and why you don't receive calls if you don't have push also.
Background mode setting is merely to kill the app instantly if not enabled, but anyway without Service Notification or push notifications the app won't be reachable for long...

**Comment by 532910** [comment]
Sorry, I've mixed up `Background mode` with `Enable service notification` setting. (Could you say, what  `Background mode` is for?)
Really all three ( `Background mode`, `Enable service notification` and `Start at boot time` are on in my settings)

And the problem is when I close app service notification disappears even `Enable service notification` is on.

**Comment by Viish** [comment]
@532910 @licaon-kter 
Ok I admit this wasn't straightforward, I just refactored things a bit in commit 7241fc80b3d16b990c2091c85df5d177615a96c0.
Now the background mode & service notification as merged into one setting, and if enabled the service will keep on running even if swiped from task manager (but you can still stop it using the quit button inside the app).

**Comment by 532910** [comment]
Thank you! And sure, quit button should stop anything.

**Comment by 532910** [comment]
Just updated. Now I can use linphone instead of proprietary 'GS Wave' with my setup. Awesome!
