### ISSUE TITLE
Can't set udp port

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#537]
When I try to set the port of the SIP Proxy to connect to by changing the Proxy configuration item in the account to: `<sip:pbx.example.com:5061;transport=udp>` linphone still tries to connect to port 5060.

**Comment by Viish** [comment]
Do you have logs showing that ?

**Comment by brianjmurrell** [comment]
```
2019-04-01 07:20:52:096 [belle-sip] MESSAGE channel [0x7b1054c7c0]: message sent to [UDP://pbx.example.com:5060], size: [1230] bytes
REGISTER sip:pbx.example.com:5061 SIP/2.0
Via: SIP/2.0/UDP [2001:1234:5678:abcd:68bf:469a:5c42:3c48]:51267;branch=z9hG4bK.vd0wXcaN-;rport
From: <sip:brian_h8@pbx.example.com>;tag=q6afSYDPc
To: sip:brian_h8@pbx.example.com
CSeq: 82 REGISTER
Call-ID: 3bzlLya7h5
Max-Forwards: 70
Supported: replaces, outbound, gruu
Accept: application/sdp
Accept: text/plain
Accept: application/vnd.gsma.rcs-ft-http+xml
Contact: <sip:brian_h8@[2001:1234:5678:abcd:68bf:469a:5c42:3c48]:51267;app-id=755770037818;pn-type=firebase;pn-tok=[redacted];pn-silent=1;transport=udp>;+sip.instance="<urn:uuid:312eea04-3559-00ae-9920-aac6701fd648>";+org.linphone.specs="lime"
Expires: 172800
User-Agent: LinphoneAndroid/4.1-debug (FRD-L04) LinphoneSDK/4.1-312-gbaecc61-debug (master) (belle-sip/1.6.3)
Authorization: [redacted]
```

**Comment by Viish** [comment]
Have you checked the outbound proxy checkbox in the settings ?

**Comment by brianjmurrell** [comment]
Yes.

**Comment by brianjmurrell** [comment]
Is it possible here that a `SRV` record lookup result is overriding the setting in the Outbound Proxy configuration?

**Comment by Viish** [comment]
Yes, SRV is prioritary.

**Comment by brianjmurrell** [comment]
Will you please stop closing issues until they have reached a resolution?

It seems like setting an explicit port should override a SRV record.

**Comment by Viish** [comment]
Actually SRV is designed for this kind of use. If there is a SRV entry, why not use it ?
Anyway it's what the RFC says in section 4.2 : https://tools.ietf.org/html/rfc3263
