### ISSUE TITLE
Doesn't unregister when quitting

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#538]
When linphone-android (feature/release-4.1) is quitted (i.e. user quits, not it crashes) while registered, it doesn't unregister before exiting.

**Comment by Viish** [comment]
Yes that's because you have push notifications enabled that can wake up the app.
If you did unregister, the proxy would decline the INVITE because your app wouldn't be reachable.

**Comment by brianjmurrell** [comment]
Well, it would be great if that functionality worked, but it doesn't.  When I quit Linphone and then call the device, it does not ring.  I have to manually start Linphone before it will answer on that device again.

So since you closed this ticket so quickly I will open yet another one about this not working.  #542
