### ISSUE TITLE
Lib not working on Android 8+

### ISSUE THREAD

**Issue by svprdga** [BelledonneCommunications/linphone-android#539]
Hello, I've implemented the android lib in one of our projects. It's working fine in the majority of devices but when we execute the code in an android with version 8 or above, the log outputs the following error:

> Access denied finding property "net.dns3"

So it seems that from Android 8 this native method is no longer supported.

I am using version 4.0.1.

Thanks for the help.

**Comment by licaon-kter** [comment]
You should be using this branch: https://github.com/BelledonneCommunications/linphone-android/tree/feature/release-4.1 

Also duplicate of: https://github.com/BelledonneCommunications/linphone-android/issues/518 and https://github.com/BelledonneCommunications/linphone-android/issues/487 and https://github.com/BelledonneCommunications/linphone-android/issues/460

**Comment by Viish** [comment]
And by the way, even if this error log shows, the lib still works since at least the 4.0 release on Android 8+

**Comment by svprdga** [comment]
I've tried master branch of the repo you told me, also tried master branch of https://github.com/BelledonneCommunications/linphone-android

I followed the instructions in the README.md file to create the .aar file but the problem persists, is there anything special I must do?

**Comment by Viish** [comment]
Attach logs and I'll take a look

**Comment by svprdga** [comment]
Sure:

`Initializing gradle...                                              1.8s
Resolving dependencies...                                           7.7s
Stopping apps on SM G960F.
Deleting 'build/'.
Deleting '/home/dserrano/code/flutter/voice/.dart_tool/'.
Launching lib/main.dart on SM G960F in debug mode...
Initializing gradle...                                              1.0s
Resolving dependencies...                                           3.6s
Note: /home/dserrano/code/flutter/voice/android/app/src/main/java/com/whisbi/voice/linphone/LinphoneService.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        70.2s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                         6.4s
I/SimplePermission(21341): Requesting permission : android.permission.READ_EXTERNAL_STORAGE
D/ViewRootImpl@c962af3[BridgeActivity](21341): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(21341): prepareNavigationBarInfo() DecorView@7f883b0[BridgeActivity]
D/InputMethodManager(21341): getNavigationBarColor() -855310            
D/ViewRootImpl@c962af3[BridgeActivity](21341): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(21341): prepareNavigationBarInfo() DecorView@7f883b0[BridgeActivity]
D/InputMethodManager(21341): getNavigationBarColor() -855310            
I/SimplePermission(21341): Requesting permission status : 3             
D/ViewRootImpl@c962af3[BridgeActivity](21341): Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x1 surface={valid=true 499612176384} changed=false
D/ViewRootImpl@c962af3[BridgeActivity](21341): Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x1 surface={valid=true 499612176384} changed=false
I/SimplePermission(21341): Requesting permission : android.permission.RECORD_AUDIO
D/ViewRootImpl@c962af3[BridgeActivity](21341): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(21341): prepareNavigationBarInfo() DecorView@7f883b0[BridgeActivity]
D/InputMethodManager(21341): getNavigationBarColor() -855310            
I/SimplePermission(21341): Requesting permission status : 3             
D/ViewRootImpl@c962af3[BridgeActivity](21341): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(21341): prepareNavigationBarInfo() DecorView@7f883b0[BridgeActivity]
D/InputMethodManager(21341): getNavigationBarColor() -855310            
D/ViewRootImpl@c962af3[BridgeActivity](21341): Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x1 surface={valid=true 499612176384} changed=false
D/voice_bridge(21341): Native - INIT                                    
I/voice_bridge(21341): Bound to LinphoneService.                        
D/AudioManager(21341): setSpeakerphoneOn false                          
D/BluetoothHeadset(21341): BTStateChangeCB is registed (21341 @ com.whisbi.voice)
D/voice_bridge(21341): LinphoneService connected.                       
W/FactoryImpl(21341): Unable to load optional library ffmpeg-linphone: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.whisbi.voice-EU-Zs1k74Xc-tGWoH_TX-w==/base.apk"],nativeLibraryDirectories=[/data/app/com.whisbi.voice-EU-Zs1k74Xc-tGWoH_TX-w==/lib/arm64, /data/app/com.whisbi.voice-EU-Zs1k74Xc-tGWoH_TX-w==/base.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libffmpeg-linphone.so"
I/libcore (21341): Using (r/w) config information from /data/user/0/com.whisbi.voice/files/.linphonerc
I/libcore (21341): Reading config information from /data/user/0/com.whisbi.voice/files/linphonerc
I/libcore (21341): Initializing LinphoneCore 3.12.0-3111-gf83d6c4a7     
I/libcore (21341): Sal nat helper [enabled]                             
I/libcore (21341): [Device] hasLowLatencyFeature: true, hasProFeature: true
I/libcore (21341): [Device] Output frames per buffer: 192, output sample rates: 48000 for OpenSLES MS sound card.
I/libcore (21341): Starting copy from assets to application files directory
I/libcore (21341): Copy from assets done                                
I/libcore (21341): Starting copy from legacy  resources to application files directory
I/libcore (21341): App doesn't seem to embed resource cpim_grammarin it's res/raw/ directory. Make sure this file is either brought as an asset or a resource
I/libcore (21341): Resource identifier null for target [cpim_grammar]   
I/libcore (21341): App doesn't seem to embed resource vcard_grammarin it's res/raw/ directory. Make sure this file is either brought as an asset or a resource
I/libcore (21341): Resource identifier null for target [vcard_grammar]  
I/libcore (21341): App doesn't seem to embed resource notes_of_the_optimisticin it's res/raw/ directory. Make sure this file is either brought as an asset or a resource
I/libcore (21341): Resource identifier null for target [notes_of_the_optimistic.mkv]
I/libcore (21341): App doesn't seem to embed resource holdin it's res/raw/ directory. Make sure this file is either brought as an asset or a resource
I/libcore (21341): Resource identifier null for target [dont_wait_too_long.mkv]
I/libcore (21341): Copy from legacy resources done                      
I/libcore (21341): bellesip_wake_lock_init(): initialization succeed    
I/libcore (21341): AndroidPlatformHelpers is fully initialised.         
I/libcore (21341): Mediastreamer2 factory 2.16.1 (git: 2.16.1-477-g5de9bb40) initialized.
I/libcore (21341): CPU count set to 8                                   
I/libcore (21341): ms_factory_init() done: platform_tags=linux,android,x86,embedded
I/libcore (21341): srtp init                                            
I/libcore (21341): SDK version [28] detected                            
I/ACodec  (21341):  [] Now uninitialized                                
I/ACodec  (21341): [] onAllocateComponent                               
I/OMXClient(21341): IOmx service obtained                               
I/ACodec  (21341): [OMX.Exynos.AVC.Encoder] Now Loaded                  
I/libcore (21341): Codec video/avc successfully created.                
I/ACodec  (21341):  [OMX.Exynos.AVC.Encoder] Now uninitialized          
I/ACodec  (21341):  [] Now kWhatShutdownCompleted event : 8522          
I/MediaCodec(21341): Codec shutdown complete                            
I/ACodec  (21341):  [] Now uninitialized                                
I/ACodec  (21341): [] onAllocateComponent                               
I/OMXClient(21341): IOmx service obtained                               
I/ACodec  (21341): [OMX.Exynos.avc.dec] Now Loaded                      
I/libcore (21341): Codec video/avc successfully created.                
I/ACodec  (21341):  [OMX.Exynos.avc.dec] Now uninitialized              
I/ACodec  (21341):  [] Now kWhatShutdownCompleted event : 8522          
I/MediaCodec(21341): Codec shutdown complete                            
I/libcore (21341): MediaCodec: 'video/avc' format supported             
I/ACodec  (21341):  [] Now uninitialized                                
I/ACodec  (21341): [] onAllocateComponent                               
I/OMXClient(21341): IOmx service obtained                               
I/ACodec  (21341): [OMX.Exynos.HEVC.Encoder] Now Loaded                 
I/libcore (21341): Codec video/hevc successfully created.               
I/ACodec  (21341):  [OMX.Exynos.HEVC.Encoder] Now uninitialized         
I/ACodec  (21341):  [] Now kWhatShutdownCompleted event : 8522          
I/MediaCodec(21341): Codec shutdown complete                            
I/ACodec  (21341):  [] Now uninitialized                                
I/ACodec  (21341): [] onAllocateComponent                               
I/OMXClient(21341): IOmx service obtained                               
I/ACodec  (21341): [OMX.Exynos.hevc.dec] Now Loaded                     
I/libcore (21341): Codec video/hevc successfully created.               
I/ACodec  (21341):  [OMX.Exynos.hevc.dec] Now uninitialized             
I/ACodec  (21341):  [] Now kWhatShutdownCompleted event : 8522          
I/MediaCodec(21341): Codec shutdown complete                            
I/libcore (21341): MediaCodec: 'video/hevc' format supported            
I/libcore (21341): Registering all soundcard handlers                   
I/libcore (21341): SDK version [28] detected                            
I/libcore (21341): Native android sound support not tested on SDK [28], disabled.
I/libcore (21341): libOpenSLES correctly loaded, creating OpenSLES MS soundcard
I/libcore (21341): This device (samsung/SM-G960F/exynos5) declares it has a built-in echo canceller.
I/libcore (21341): No information available for [samsung/SM-G960F/exynos5],
I/libcore (21341): Sound device information for [samsung/SM-G960F/exynos5] is: builtin=[yes], delay=[0] ms
I/libcore (21341): This device (samsung/SM-G960F/exynos5) declares it has a built-in echo canceller.
I/libcore (21341): No information available for [samsung/SM-G960F/exynos5],
I/libcore (21341): Sound device information for [samsung/SM-G960F/exynos5] is: builtin=[yes], delay=[0] ms
W/libcore (21341): Removing MS_SND_CARD_CAP_CAPTURE flag from soundcard to use HAEC Java capture soundcard
I/libcore (21341): Card 'openSLES: android sound card' added with capabilities [playback]
I/libcore (21341): SDK version [28] detected                            
I/libcore (21341): This device (samsung/SM-G960F/exynos5) declares it has a built-in echo canceller.
I/libcore (21341): No information available for [samsung/SM-G960F/exynos5],
I/libcore (21341): Sound device information for [samsung/SM-G960F/exynos5] is: builtin=[yes], delay=[0] ms
I/libcore (21341): Card 'ANDROID SND (deprecated): Android Sound card' added with capabilities [capture, playback]
I/libcore (21341): Registering all webcam handlers                      
I/libcore (21341): Detecting Android VIDEO cards                        
I/libcore (21341): getHelperClassGlobalRef (env: 0x746c252300)          
I/libcore (21341): Android SDK version found is 28                      
I/CameraManagerGlobal(21341): Connecting to camera service              
D/VendorTagDescriptor(21341): addVendorDescriptor: vendor tag id 3854507339 added
I/libcore (21341): 2 cards detected                                     
I/libcore (21341): Android VIDEO capture filter cam init                
I/libcore (21341): Webcam Android0 added                                
I/libcore (21341): camera created: id=0 frontFacing=0 orientation=90 [msid:Android0]
I/libcore (21341): Android VIDEO capture filter cam init                
I/libcore (21341): Webcam Android1 added                                
I/libcore (21341): camera created: id=1 frontFacing=1 orientation=270 [msid:Android1]
I/libcore (21341): Detection of Android VIDEO cards done                
I/libcore (21341): Webcam StaticImage: Static picture added             
I/libcore (21341): MSAndroidDisplay registered.                         
I/libcore (21341): MSAndroidDisplay (OpenGL ES2) registered (id=80).    
I/libcore (21341): ms_factory_init_voip() done                          
I/libcore (21341): Loading ms plugins from [/data/app/com.whisbi.voice-EU-Zs1k74Xc-tGWoH_TX-w==/lib/arm64]
I/libcore (21341): Loading plugin /data/app/com.whisbi.voice-EU-Zs1k74Xc-tGWoH_TX-w==/lib/arm64/libmswebrtc.so...
I/libcore (21341): libmswebrtc 1.1.1 plugin loaded, iSAC codec version 3.6.0, iLBC codec version 1.1.1
I/libcore (21341): Plugin loaded (/data/app/com.whisbi.voice-EU-Zs1k74Xc-tGWoH_TX-w==/lib/arm64/libmswebrtc.so)
I/libcore (21341): Core callbacks [0x74533f0b00] registered on core [0x74530c1a00]
I/libcore (21341): oRTP-1.0.2 initialized.                              
I/libcore (21341): Codec opus/48000 fmtp=[useinbandfec=1] number=-1, default enablement: 16) added to the list of possible codecs.
I/libcore (21341): Codec SILK/16000 fmtp=[] number=-1, default enablement: 16) added to the list of possible codecs.
I/libcore (21341): Codec speex/16000 fmtp=[vbr=on] number=-1, default enablement: 16) added to the list of possible codecs.
I/libcore (21341): Codec speex/8000 fmtp=[vbr=on] number=-1, default enablement: 16) added to the list of possible codecs.
I/libcore (21341): Codec PCMU/8000 fmtp=[] number=0, default enablement: 16) added to the list of possible codecs.
I/libcore (21341): Codec PCMA/8000 fmtp=[] number=8, default enablement: 16) added to the list of possible codecs.
I/libcore (21341): Codec red/1000 fmtp=[] number=-1, default enablement: 16) added to the list of possible codecs.
I/libcore (21341): Codec t140/1000 fmtp=[] number=-1, default enablement: 16) added to the list of possible codecs.
I/libcore (21341): Codec GSM/8000 fmtp=[] number=3, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec G722/8000 fmtp=[] number=9, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec iLBC/8000 fmtp=[mode=30] number=-1, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec AMR/8000 fmtp=[octet-align=1] number=-1, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec AMR-WB/16000 fmtp=[octet-align=1] number=-1, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec G729/8000 fmtp=[annexb=yes] number=18, default enablement: 16) added to the list of possible codecs.
I/libcore (21341): Codec mpeg4-generic/16000 fmtp=[config=F8EE2000; constantDuration=512; indexDeltaLength=3; indexLength=3; mode=AAC-hbr; profile-level-id=76; sizeLength=13; streamType=5] number=-1, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec mpeg4-generic/22050 fmtp=[config=F8EE2000; constantDuration=512; indexDeltaLength=3; indexLength=3; mode=AAC-hbr; profile-level-id=76; sizeLength=13; streamType=5] number=-1, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec mpeg4-generic/32000 fmtp=[config=F8E82000; constantDuration=512; indexDeltaLength=3; indexLength=3; mode=AAC-hbr; profile-level-id=76; sizeLength=13; streamType=5] number=-1, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec mpeg4-generic/44100 fmtp=[config=F8E82000; constantDuration=512; indexDeltaLength=3; indexLength=3; mode=AAC-hbr; profile-level-id=76; sizeLength=13; streamType=5] number=-1, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec mpeg4-generic/48000 fmtp=[config=F8EE2000; constantDuration=512; indexDeltaLength=3; indexLength=3; mode=AAC-hbr; profile-level-id=76; sizeLength=13; streamType=5] number=-1, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec iSAC/16000 fmtp=[] number=-1, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec speex/32000 fmtp=[vbr=on] number=-1, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec SILK/8000 fmtp=[] number=-1, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec SILK/12000 fmtp=[] number=-1, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec SILK/24000 fmtp=[] number=-1, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec G726-16/8000 fmtp=[] number=-1, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec G726-24/8000 fmtp=[] number=-1, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec G726-32/8000 fmtp=[] number=-1, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec G726-40/8000 fmtp=[] number=-1, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec AAL2-G726-16/8000 fmtp=[] number=-1, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec AAL2-G726-24/8000 fmtp=[] number=-1, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec AAL2-G726-32/8000 fmtp=[] number=-1, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec AAL2-G726-40/8000 fmtp=[] number=-1, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec CODEC2/8000 fmtp=[] number=-1, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec BV16/8000 fmtp=[] number=-1, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec VP8/90000 fmtp=[] number=-1, default enablement: 16) added to the list of possible codecs.
I/libcore (21341): Codec H264/90000 fmtp=[profile-level-id=42801F] number=-1, default enablement: 16) added to the list of possible codecs.
I/libcore (21341): Codec H265/90000 fmtp=[] number=-1, default enablement: 16) added to the list of possible codecs.
I/libcore (21341): Codec MP4V-ES/90000 fmtp=[profile-level-id=3] number=-1, default enablement: 16) added to the list of possible codecs.
I/libcore (21341): Codec H263-1998/90000 fmtp=[CIF=1;QCIF=1] number=-1, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec H263/90000 fmtp=[] number=34, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec 1016/8000 fmtp=[] number=1, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec G723/8000 fmtp=[] number=4, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec LPC/8000 fmtp=[] number=7, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec L16/44100 fmtp=[] number=10, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec L16/44100 fmtp=[] number=11, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec CN/8000 fmtp=[] number=13, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec H261/90000 fmtp=[] number=31, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Codec MPV/90000 fmtp=[] number=32, default enablement: 0) added to the list of possible codecs.
I/libcore (21341): Root ca path set to /system/etc/security/cacerts     
I/libcore (21341): Root ca path set to /system/etc/security/cacerts     
E/libcore (21341): AndroidPlatformHelpers::setDnsServers() exception.   
I/libcore (21341): Cannot open directory ./lib/liblinphone/plugins: No such file or directory
W/libcore (21341): '/data/data/org.linphone/files/oldphone_mono.wav' ring file does not exist
I/libcore (21341): linphone_core_set_playback_gain_db(): no active call.
I/libcore (21341): linphone_core_set_mic_gain_db(): no active call.     
I/libcore (21341): Sal nat helper [enabled]                             
I/libcore (21341): Sal use rports [enabled]                             
I/libcore (21341): MTU is supposed to be 1300, rtp payload max size will be 1240
I/libcore (21341): Could not find encoder for SILK                      
I/libcore (21341): Could not find decoder for SILK                      
I/libcore (21341): Could not find encoder for AMR                       
I/libcore (21341): Could not find decoder for AMR                       
I/libcore (21341): Could not find encoder for AMR-WB                    
I/libcore (21341): Could not find decoder for AMR-WB                    
I/libcore (21341): Could not find encoder for mpeg4-generic             
I/libcore (21341): Could not find decoder for mpeg4-generic             
I/libcore (21341): Could not find encoder for mpeg4-generic             
I/libcore (21341): Could not find decoder for mpeg4-generic             
I/libcore (21341): Could not find encoder for mpeg4-generic             
I/libcore (21341): Could not find decoder for mpeg4-generic             
I/libcore (21341): Could not find encoder for mpeg4-generic             
I/libcore (21341): Could not find decoder for mpeg4-generic             
I/libcore (21341): Could not find encoder for mpeg4-generic             
I/libcore (21341): Could not find decoder for mpeg4-generic             
I/libcore (21341): Could not find encoder for SILK                      
I/libcore (21341): Could not find decoder for SILK                      
I/libcore (21341): Could not find encoder for SILK                      
I/libcore (21341): Could not find decoder for SILK                      
I/libcore (21341): Could not find encoder for SILK                      
I/libcore (21341): Could not find decoder for SILK                      
I/libcore (21341): Could not find encoder for G726-16                   
I/libcore (21341): Could not find decoder for G726-16                   
I/libcore (21341): Could not find encoder for G726-24                   
I/libcore (21341): Could not find decoder for G726-24                   
I/libcore (21341): Could not find encoder for G726-32                   
I/libcore (21341): Could not find decoder for G726-32                   
I/libcore (21341): Could not find encoder for G726-40                   
I/libcore (21341): Could not find decoder for G726-40                   
I/libcore (21341): Could not find encoder for AAL2-G726-16              
I/libcore (21341): Could not find decoder for AAL2-G726-16              
I/libcore (21341): Could not find encoder for AAL2-G726-24              
I/libcore (21341): Could not find decoder for AAL2-G726-24              
I/libcore (21341): Could not find encoder for AAL2-G726-32              
I/libcore (21341): Could not find decoder for AAL2-G726-32              
I/libcore (21341): Could not find encoder for AAL2-G726-40              
I/libcore (21341): Could not find decoder for AAL2-G726-40              
I/libcore (21341): Could not find encoder for CODEC2                    
I/libcore (21341): Could not find decoder for CODEC2                    
I/libcore (21341): Could not find encoder for BV16                      
I/libcore (21341): Could not find decoder for BV16                      
I/libcore (21341): Could not find encoder for 1016                      
I/libcore (21341): Could not find decoder for 1016                      
I/libcore (21341): Could not find encoder for G723                      
I/libcore (21341): Could not find decoder for G723                      
I/libcore (21341): Could not find encoder for LPC                       
I/libcore (21341): Could not find decoder for LPC                       
I/libcore (21341): Could not find encoder for CN                        
I/libcore (21341): Could not find decoder for CN                        
I/libcore (21341): Could not find encoder for MP4V-ES                   
I/libcore (21341): Could not find decoder for MP4V-ES                   
I/libcore (21341): Could not find encoder for H263-1998                 
I/libcore (21341): Could not find decoder for H263-1998                 
I/libcore (21341): Could not find encoder for H263                      
I/libcore (21341): Could not find decoder for H263                      
I/libcore (21341): Could not find encoder for H261                      
I/libcore (21341): Could not find decoder for H261                      
I/libcore (21341): Could not find encoder for MPV                       
I/libcore (21341): Could not find decoder for MPV                       
I/libcore (21341): Supported codec red/1000 fmtp= automatically added to codec list.
I/libcore (21341): Supported codec t140/1000 fmtp= automatically added to codec list.
I/libcore (21341): Sal use rports [enabled]                             
I/libcore (21341): Root ca path set to /data/user/0/com.whisbi.voice/files/share/linphone/rootca.pem
I/libcore (21341): Sal::unlistenPorts(): done                           
I/libcore (21341): Creating listening point [0x7452e86980] on [sip:0.0.0.0:5060;transport=TCP]
I/libcore (21341): linphone_proxy_config_is_server_config_changed : 0   
I/libcore (21341): Publish params have changed on proxy config [0x7439455680]
I/libcore (21341): linphone_proxy_config_is_server_config_changed : 0   
I/libcore (21341): Publish params have changed on proxy config [0x7439455380]
I/libcore (21341): Core callbacks [0x7414c29680] registered on core [0x74530c1a00]
D/linphone_service(21341): Core listener - Global State Changed: Starting up
I/libcore (21341): Linphone core [0x74530c1a00] notified [global_state_changed]
I/libcore (21341): Opening linphone database: /data/user/0/com.whisbi.voice/files/linphone.db
I/libcore (21341): Start measurement of [Get chat rooms.].              
I/libcore (21341): Start transaction 0x7ffea58b70 in MainDb::getChatRooms.
I/libcore (21341): Commit transaction 0x7ffea58b70 in MainDb::getChatRooms.
I/libcore (21341): Duration of [Get chat rooms.]: 0ms.                  
I/libcore (21341): Root ca path set to /data/user/0/com.whisbi.voice/files/share/linphone/rootca.pem
D/linphone_service(21341): Core listener - Global State Changed: Configuring
I/libcore (21341): Linphone core [0x74530c1a00] notified [global_state_changed]
D/linphone_service(21341): Core listener - On Configuring Status        
I/libcore (21341): Linphone core [0x74530c1a00] notified [configuring_status]
D/linphone_service(21341): Core listener - Global State Changed: Ready  
I/libcore (21341): Linphone core [0x74530c1a00] notified [global_state_changed]
I/libcore (21341): Root ca path set to /data/user/0/com.whisbi.voice/files/rootca.pem
D/voice_bridge(21341): Native - LOGIN with username: 934010001, password: Whisbi@test01, server: pbx401.whisbi.com
I/libcore (21341): linphone_proxy_config_is_server_config_changed : 0   
I/libcore (21341): Publish params have changed on proxy config [0x7439455800]
I/libcore (21341): LinphoneProxyConfig [0x7439455800] about to register (LinphoneCore version: 3.12.0-3111-gf83d6c4a7)
I/libcore (21341): Transport is not specified, using tcp because UDP is not available.
I/libcore (21341): get_jni_env(): thread successfuly attached           
I/libcore (21341): bellesip_wake_lock_acquire(): Android wake lock [belle-sip transaction(0x7414c352c0)] acquired [ref=0x2ed6]
I/libcore (21341): transaction [0x7414c352c0]: starting transaction background task with id=[2ed6].
I/libcore (21341): belle_sip_client_transaction_send_request(): waiting channel to be ready
I/libcore (21341): bellesip_wake_lock_acquire(): Android wake lock [belle-sip send channel] acquired [ref=0x2ef6]
I/libcore (21341): channel [0x7414d0eb40]: starting send background task with id=[2ef6].
I/libcore (21341): channel [0x7414d0eb40]: starting resolution of pbx401.whisbi.com
I/libcore (21341): channel 0x7414d0eb40: state RES_IN_PROGRESS          
I/libcore (21341): transaction [0x7414c352c0] channel state changed to [RES_IN_PROGRESS]
E/libc    (21341): Access denied finding property "net.dns1"            
E/libc    (21341): Access denied finding property "net.dns2"            
E/libc    (21341): Access denied finding property "net.dns3"            
E/libcore (21341): resconf dns_resconf_loadandroid error                
E/libcore (21341): Error loading dns server addresses.                  
I/libcore (21341): No SRV result for [_sip._tcp.pbx401.whisbi.com], trying A/AAAA.
E/libc    (21341): Access denied finding property "net.dns1"            
E/libc    (21341): Access denied finding property "net.dns2"            
E/libc    (21341): Access denied finding property "net.dns3"            
E/libcore (21341): resconf dns_resconf_loadandroid error                
E/libcore (21341): Error loading dns server addresses.                  
E/libcore (21341): channel_res_done: DNS resolution failed for pbx401.whisbi.com
I/libcore (21341): channel 0x7414d0eb40: state ERROR                    
I/libcore (21341): Neither Expires header nor corresponding Contact header found, checking from original request
I/libcore (21341): Refresher [0x7414c35080] takes ownership of transaction [0x7414c352c0]
I/libcore (21341): Proxy config [0x7439455800] for identity [sip:934010001@pbx401.whisbi.com] moving from state [LinphoneRegistrationNone] to [LinphoneRegistrationProgress] on core [0x74530c1a00]
D/linphone_service(21341): Core listener - On Registration State Changed: Registration in progress
D/voice_bridge(21341): Registration - IN PROGRESS...                    
I/libcore (21341): Linphone core [0x74530c1a00] notified [registration_state_changed]
I/libcore (21341): channel [0x7414d0eb40]: ending send background task with id=[2ef6].
I/libcore (21341): bellesip_wake_lock_release(): Android wake lock released [ref=0x2ef6]
I/libcore (21341): transaction [0x7414c352c0] channel state changed to [ERROR]
I/libcore (21341): Refresher[0x7414c35080]: scheduling next timer in 500 ms for purpose [retry]
I/libcore (21341): Register refresher [503] reason [io error] for proxy [sip:pbx401.whisbi.com]
I/libcore (21341): Proxy config [0x7439455800] for identity [sip:934010001@pbx401.whisbi.com] moving from state [LinphoneRegistrationProgress] to [LinphoneRegistrationFailed] on core [0x74530c1a00]
D/linphone_service(21341): Core listener - On Registration State Changed: io error
D/voice_bridge(21341): Registration - FAILED                            
I/libcore (21341): Linphone core [0x74530c1a00] notified [registration_state_changed]
I/libcore (21341): Changing [client] [REGISTER] transaction [0x7414c352c0], from state [INIT] to [TERMINATED]
I/libcore (21341): Client internal REGISTER transaction [0x7414c352c0] terminated
I/libcore (21341): transaction [0x7414c352c0]: ending transaction background task with id=[2ed6].
I/libcore (21341): bellesip_wake_lock_release(): Android wake lock released [ref=0x2ed6]
I/libcore (21341): Channel [0x7414d0eb40] destroyed                     
I/libcore (21341): bellesip_wake_lock_acquire(): Android wake lock [belle-sip transaction(0x7414c35140)] acquired [ref=0x2efa]
I/libcore (21341): transaction [0x7414c35140]: starting transaction background task with id=[2efa].
I/libcore (21341): belle_sip_client_transaction_send_request(): waiting channel to be ready
I/libcore (21341): bellesip_wake_lock_acquire(): Android wake lock [belle-sip send channel] acquired [ref=0x2f16]
I/libcore (21341): channel [0x74395a2140]: starting send background task with id=[2f16].
I/libcore (21341): channel [0x74395a2140]: starting resolution of pbx401.whisbi.com
I/libcore (21341): channel 0x74395a2140: state RES_IN_PROGRESS          
I/libcore (21341): transaction [0x7414c35140] channel state changed to [RES_IN_PROGRESS]
E/libc    (21341): Access denied finding property "net.dns1"            
E/libc    (21341): Access denied finding property "net.dns2"            
E/libc  I/libcore (21341): channel [0x74395a2140]: endiI/libcore (21341): Channel [0x74395a2140] destroyed                                                                                                                                                           Syncing files to device SM G960F...                              5,532ms (!)   `

**Comment by Viish** [comment]
Sorry but I can read anything like this. Either upload logs using the button in about page and attach the link of the file here or attach a file from your adb logcat output with line breaks.

**Comment by Viish** [comment]
Seems you have a DNS issue (not Access denied finding property "net.dns1"  but AndroidPlatformHelpers::setDnsServers() exception).
Try with one of our latest AAR in http://linphone.org/snapshots/maven_repository/ (make sure Core version is at least 3.12.0-3357) and ensure auto_net_state_mon in [sip] section of your linphonerc_factory or default is set to 1 (create the entry if it doesn't exist).

**Comment by svprdga** [comment]
It worked with the previous .aar only by changing auto_net_state_mon to 1.

Thanks.

**Comment by svprdga** [comment]
With https://gitlab.linphone.org/BC/public/linphone-android aar:

Now I can login and receive calls with an android 8 device, but I cannot hear the other talking. Tried in an android version 7 and works ok.

In the same device, I run oficial Linphone app and it has the same error, do you have it tracked?

**Comment by Viish** [comment]
Probably more a network issue than a android version problem.
Please open a new ticket with logs.
