### ISSUE TITLE
Background/push/boot settings are confusing

### ISSUE THREAD

**Issue by gdt** [BelledonneCommunications/linphone-android#545]
Linphone 4.0.1 from f-droid.

In Network, there is
  - "Enable push notifications", and a per-account Allow.

In Advanced, there is
 - Background mode
 - Enable service notification
 - Start at boot time

This is confusing, even to people that understand the Android power-saving rules and the Android app lifecycle model.  As I see it, there are behaviors that should be exposed in settings, which should drive mechanisms, to first order, with some user control of mechanisms.  Note that all of my detailed comments about what i observe are with all push settings disabled.

"Start at boot" seems ok, if it means that on boot linphone will end up in the same state it would have been had the user entered the app and then switched away.   I think it does that.

"Background mode" seems like it should mean if linphone should keep a service running to stay registered and enable incoming calls.  With background and enable service notification off, I find that an incoming call that arrives e.g. 10s after leaving linphone's activity and going back to home screen, or clicking power to turn off display, arrives and rings -- but I think it should not.   A few minutes after leaving linphone, an incoming call does not arrive.  I think there are two bugs here.  One is that it should probably be "Stay registered for calls" to convey that it's about staying registered and receiving calls when a linphone actiivity is not on the screen (ignoring fine points about aggressive power saving).  The second is that if it's not checked, then the background service that is obviously staying registered should be torn down fairly promptly when linphone leaves the screen.  Perhaps it is, for fairly promptly defined as 1 minute.

I understand that "enable service notification" is about being a foreground service, while running in the background, by following the Android rules about notifying the user that this is happening so they can intervene if they don't like it.  But I really doubt people who haven't studied Android API rules will understand that.  Given that power saving is getting more and more aggressive, I suggest removing this option and basically either not having a background service (if disabled), or if enabled, having it always be of foreground type with a notification.  Even as a user who understands, I like it that I can tell if the background service is running.  And really I would like the notification to have registration status, not just be de minimus to satisfy the API rules.

Finally, push is a bit tricky, since linphone seems not to implement the new IETF push approach yet (nobody does), and how push works with power saving that drops incoming packets is not clear.  And if incoming packets arrive and work, you don't need push.  But it seems clear that push is a subcase of "receive calls in background", and that if that's disabled it does not make sense.   There's a further nuance of keeping the background service around vs exiting it in favor of a restart from push, or if push is a belt and suspenders approach.

So, after that somewhat rambling analysis, this issue asks:
 - drop the "notification" menu item, and always have a notification to qualify for foreground treatment, when running a background service
 - call the "background" item "Stay registered for calls"
 - have the background service exit relatively promptly if "stay registered" is not enabled.

**Comment by Viish** [comment]
Hi,

Here's my point of view.
The "background mode" and "service notification" are both in the "advanced" section of the settings, meaning this is not to be changed by user that don't understand what it is and what it does. The default values are the best settings for most users (users with sip.linphone.org accounts and running non-rooted and non-custom ROMs).
Anyway, always having a foreground service has some disadvantages, like battery consumption and annoying notification in the status bar and lock screen.
The background mode is only for people that want an aggressive battery optimization to kill the service manually as soon as linphone is not in foreground anymore before the OS does it automatically.

I agree that some settings may benefit from a renaming, but we're in a release process and it's a bit late for that. The next release will have some design improvements, it's planned to have at that time a full rework of the settings.
Thanks for your input, we'll keep it for when the time comes where we will dedicate time for the settings. In the meantime as it isn't an "issue", I'll close it, it helps me keep a better understanding of the tickets.

Cheers,

**Comment by gdt** [comment]
Reading your comments, I'd say this needs even more work than I thought, because I'm left thinking I don't really understand what "background mode" does.

Also, you seem to be focusing solely on battery, whereas "I want my phone to unregister when I leave the app" is valid, and that doesn't seem to to be part of the thinking, even though that's what the background checkbox seems like it should mean.

**Comment by Viish** [comment]
If you don't have background mode and push settings enabled, the app will unregister after being killed.

**Comment by gdt** [comment]
I more or less understand that, but with 'background' unchecked, 'm seeing it stay registered for 5-15 minutes.   As a user, separately from mostly understanding Android rules, I expect it to unregister reasonably promptly (10s? 30s?) after leaving the app, if I have not configured it to stay registered.  You may be coming from the viewpoint that everybody wants to be registered to receive calls, and these settings are about how to organize this.  That's certainly many people, but I'm coming at it from the view that if I didn't ask to stay registered, it should not be registered.

**Comment by Viish** [comment]
That's weird because you should be unregistered right away.
When linphone core is destroyed, if network is reachable, it will send a REGISTER with expire set to 0.
This happens when you click quit in the side menu, remove the app from the recent panel or press the back button on the home screen.
