### ISSUE TITLE
How to know the incoming call is audio or video?

### ISSUE THREAD

**Issue by Miteshmakwana73** [BelledonneCommunications/linphone-android#550]
How to know the incoming call is audio or video?

I am trying to perform a task if it's an audio call on click of answer button and another task if the incoming call is video in CallIncomingActivity.

in CallIncomingActivity it always `startVideoActivity()` on answer button

**Comment by Viish** [comment]
When receiving a call, to know if the call is initiated with video, you can use call.getRemoteParams().videoEnabled()

**Comment by Miteshmakwana73** [comment]
it's shows cannot resolve method 'videoEnabled()'

**Comment by Viish** [comment]
If you use the old Java wrapper, the method is getVideoEnabled()

**Comment by Miteshmakwana73** [comment]
it's working now thank you
