### ISSUE TITLE
Registration storm after call termination with flexisip

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#552]
After receiving a call from flexisip (push-proxying for Asterisk) and terminating it, linphone goes into a registration storm with flexisip.

Here's a [log](http://brian.interlinx.bc.ca/linphone-registration-storm.txt) of it.

**Comment by Viish** [comment]
Duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/531

**Comment by brianjmurrell** [comment]
Are you sure?  This storm typically only lasts a short while while the activity loop in #531 can go on for hours and hours.
