### ISSUE TITLE
early media function

### ISSUE THREAD

**Issue by fengsimon** [BelledonneCommunications/linphone-android#556]
Dear Viish,

Thank you very much for your reply to the question #555，I'm not sure if you've reversed the caller and the callee in my question，maybe I didn't make it clear.
for example: A call out to B,  A is caller ,and B is callee . now A is based on linphone4.0.1, and B is not based on linphone, but also on SIP protocol。
when A call out to B, B is ringing, I think at this point A will pass the voice and video to B instead of waiting for B to receive them(it is early media function). How can A send video and audio to B when calling? 
thanks.

**Comment by Viish** [comment]
Actually you can't force the caller to send early media. It has to be the recipient that asks for it by sending a 183 EARLYMEDIA instead of a 180 RINGING.
