### ISSUE TITLE
After account creation, white screen and endless spinning

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#558]
After starting Linphone for the first time, I choose to enter a SIP account, which I do (name, password, domain, etc.) and then linphone registers to the SIP proxy and then a white screen comes up with a never-ending orange spinner.

Pressing back does nothing.  I have to hit the home button and then open Linphone again at which point I see I am registered and at the dialpad screen.

**Comment by Viish** [comment]
I believed I fixed that issue with commit 08a6375a654c7565256635922aecce7ba0d2d9da, can you confirm ?

**Comment by brianjmurrell** [comment]
Yes, this seems to be fixed in the latest feature/release-4.1

**Comment by Viish** [comment]
Great
