### ISSUE TITLE
Should skip new version check on custom builds

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#561]
If I build my own linphone, package, the resulting app shouldn't check for new "official" versions.

**Comment by Viish** [comment]
That's why I added the "check_for_update_when_app_starts" boolean option in values/non_localizable_custom.xml in commit 9ec269c85f1c5c35f3b7c5b220fced402474952d

**Comment by brianjmurrell** [comment]
This also makes it skip periodic update checks?  I.e. setting this to `false` skips all update checks, not just on start?

**Comment by Viish** [comment]
Yes this check is only at startup

**Comment by brianjmurrell** [comment]
Ahhh.  I thought I had seen this check being done periodically in the logs.  They must have been restarts.
