### ISSUE TITLE
Button text truncated at the bottom on About screen

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#562]
![Screenshot_Linphone_20190411-104637](https://user-images.githubusercontent.com/559317/55967256-fd15ab80-5c47-11e9-887f-3868629d84c2.png)

**Comment by Viish** [comment]
Thanks I'll fix that.

**Comment by Viish** [comment]
That should do the trick: cbc68f5a4b94efccb5eba59163bbf048bf202514

**Comment by brianjmurrell** [comment]
Confirmed, although I'm surprised I didn't get a scrollbar but just that the widgets all seem to fit into the screen size now.
