### ISSUE TITLE
Doesn't show UI when ringing

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#563]
On my Nexus 5 with LineageOS 15.x I have _Screen Saver_ enabled with _When to start_ set to _While charging or docked_.

This displays a floating clock on a dimmed screen when the phone is idle rather than powering the screen right down, but only while charging so battery drain of this feature is not a concern.  When in this mode, one can touch the screen to get the screen back into full wake up mode.

When in this mode however, Linphone does not wake the screen up when it's ringing so that one can choose to swipe red or green to [not] answer.  On hearing it ring, one has to touch the screen to see Linphone.

[Here is an article](https://trendblog.net/enable-screen-saver-android/) describing this mode.  Apparently it used to be called _Daydream Mode_.

**Comment by Viish** [comment]
This seems to fix it: df6f3461110632f2665102ab742a773e67002f60

**Comment by brianjmurrell** [comment]
Confirmed
