### ISSUE TITLE
rootca.pem ?

### ISSUE THREAD

**Issue by aliahmaed** [BelledonneCommunications/linphone-android#568]
what is rootca.pem used to in project 
how change it ?

**Comment by Viish** [comment]
It is generated at compilation time.
The best way to add a cert is to use the API on the Core: core.setTlsCert or core.setTlsCertPath

**Comment by aliahmaed** [comment]
can you explain about it 
rootca is public key or private key  ?
how i can add public and private key to create tls account

**Comment by aliahmaed** [comment]
please i need help i want to enable tls but is not working
