### ISSUE TITLE
call not showing when phone is lock

### ISSUE THREAD

**Issue by Miteshmakwana73** [BelledonneCommunications/linphone-android#569]
I am implementing linphone 4.1 and I am facing problem call is not coming if the phone is lock.

**Comment by Viish** [comment]
You have to set the flag SHOW_WHEN_LOCKED on the window or in the Manifest attributes of your activity.

**Comment by Miteshmakwana73** [comment]
SHOW_WHEN_LOCKED is already set in CallActivity, CallIncomingActivity, CallOutgoingActivity this files but it's not working

**Comment by Miteshmakwana73** [comment]
it's not working if battery saver is on

**Comment by Viish** [comment]
I believe the issue is you don't even receive the INVITE more than the view isn't showing

**Comment by Miteshmakwana73** [comment]
it's only not working if battery saver is on

**Comment by Miteshmakwana73** [comment]
@Viish it's also not playing pre-recorded audio in linphone

**Comment by Miteshmakwana73** [comment]
whats the problem in pre-recorded audio?

**Comment by Miteshmakwana73** [comment]
Like when user balance is low, We are playing "not have enough credit to call" but in linephone not able to listen audio file while on the other softphone like zoiper and twinkle can able to hear audio file voice.

**Comment by Viish** [comment]
I recommend you to contact our sales department (sales@belledonne-communications.com) to have a support or dev-assist contract.

**Comment by Miteshmakwana73** [comment]
what is the issue?

**Comment by Viish** [comment]
I don't understand what you are talking about, but anyway I'm not here to help you develop your own app. If you want this kind of help, contact our company.
