### ISSUE TITLE
long icon press shortcut

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#573]
Please add support for icon press shortcut
https://developer.android.com/guide/topics/ui/shortcuts/

Recent call must be in the shortcut list.

![image](https://user-images.githubusercontent.com/14617699/56234257-918b6e00-608d-11e9-928d-c1f53c7d695c.png)

![image](https://user-images.githubusercontent.com/14617699/56234287-a2d47a80-608d-11e9-884a-9a8538ccf0ad.png)

**Comment by Viish** [comment]
Done in a06ed1eef0558142e9978512eb89418b307ba5c9

**Comment by 532910** [comment]
4125 has no shortcuts.

**Comment by Viish** [comment]
This is expected, it will be in 4.2 version

**Comment by Viish** [comment]
Have you enable the setting in contacts section?
Also note this generate shortcuts from recent chatrooms only

**Comment by 532910** [comment]
1. I've not expected that it should be enabled, and it should be enabled by default.
2. Recent calls should also be used.

**Comment by Viish** [comment]
> Recent calls should also be used.

I agree but for the time being it is very troublesome to mix chat events with call events. When the SDK will have improved this I'll be able to mix the two correctly for the contacts shortcuts.

**Comment by 532910** [comment]
Should this issue be left opened to not to forget about this?
