### ISSUE TITLE
answer a call with bluetooht headset button

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#574]
Please add support to answer a call with bluetooht headset button.

**Comment by Viish** [comment]
We can't do that actually, the event of the bluetooth headset is specific to each headset and is handled by the OS, not forwarded to applications in most cases.

**Comment by 532910** [comment]
Hmm, I'm sure the event is standard for bluetooth profile (HFP/HSP)
Moreover, standard android dialer can handle it.

**Comment by Viish** [comment]
Standard Android apps including dialer can't be compared to a third party application.
We don't have access to the same APIs and to my knowledge there is no way to do that. A few years back we tried and we determined we couldn't do it.
If this has changed I'd be interested to see the documentation.

**Comment by 532910** [comment]
https://github.com/signalapp/Signal-Android/issues/7679
https://developer.android.com/guide/topics/media-apps/mediabuttons

**Comment by Viish** [comment]
Thanks for the links.
But we don't use MediaSession so we can't use the MediaButton solution.
And I see no solution either on the Signal's issue.

**Comment by Viish** [comment]
For information, we had developed a prototype of linphone-android using Android's TelecomManager, so the default dialer interface is used instead of our own CallIncomingActivity, and that makes the Bluetooth headset's answer button work with Linphone.

**Comment by 532910** [comment]
Is this
![image](https://user-images.githubusercontent.com/14617699/56440689-d401b480-62f2-11e9-83e8-8e42f205c945.png)
a TelecomManager?

So you can do that actually and this issue will be solved. It it better to leave it open untill?

**Comment by 532910** [comment]
Really there is an another similar issue: "to end the call by bluetooth button" as now it just transfers it to the phone. Is another issue should be opened or this one should be updated?

**Comment by DJCrashdummy** [comment]
> For information, we had developed a prototype of linphone-android using Android's TelecomManager, so the default dialer interface is used instead of our own CallIncomingActivity, and that makes the Bluetooth headset's answer button work with Linphone.

@Viish that sounds really cool! IIRC CSipSimple worked similar... :thinking:
