### ISSUE TITLE
ignores DND starred contatcs only setting

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#575]
When `DND` is `ON` and `Allow calls` is `From starred contatcs only` linphone will ring out loud.

**Comment by Viish** [comment]
I just tried and if I enable do not disturb mode, the app doesn't ring, even if the call comes from a contact.

**Comment by 532910** [comment]
Have you set `Allow calls` to `From starred contatcs only`?

**Comment by 532910** [comment]
Really I've lied a bit:
If `DND` is `ON` and `Allow calls` is `From starred contatcs only` linphone will ring out loud for all incoming calls.
LineageOS 16.0 / Android 9

**Comment by 532910** [comment]
There are no starred contats at all on my side.
If I set `Allow calls` to `None` it will not ring

**Comment by Viish** [comment]
This one depends if you use the device's ringtone or not

**Comment by 532910** [comment]
I use device's ringtone.

**Comment by Viish** [comment]
I've started the work, but even read access to DND policy in priority filtering mode needs an explicit permission grant from user...
commit 9f843d827ef5f240500dfb30f0d476bd04ada96d (HEAD -> feature/split_linphone_activity, origin/feature/split_linphone_activity)
Author: Sylvain Berfini <sylvain.berfini@belledonne-communications.com>
Date:   Thu May 2 14:30:24 2019 +0200
    Started code to check DND policy on incoming call
