### ISSUE TITLE
after removing account register fails

### ISSUE THREAD

**Issue by RajanVindaloo** [BelledonneCommunications/linphone-android#579]
After removing non default account, other accounts are not able to register. It gives "Registration failed" in status

**Comment by Viish** [comment]
Does your accounts share the same username / domain ?

**Comment by RajanVindaloo** [comment]
Yes, it does.

**Comment by Viish** [comment]
Ok. When you delete an account, you delete 2 things: a proxy config and an auth info.
If you share the auth info between proxy configs, yes the removal of the account will also remove the auth info, and that will broke the other proxy configs.

**Comment by RajanVindaloo** [comment]
So, what I should do? Please, can you tell me?

**Comment by Viish** [comment]
Don't remove the authInfo when the clickListener of the deleteAccount button is called

**Comment by RajanVindaloo** [comment]
Okay. Let my try and I'll get back to you soon.

**Comment by RajanVindaloo** [comment]
Thank you very much for the solution. Happy to talk to you.
