### ISSUE TITLE
how to change predefind codec settings ?

### ISSUE THREAD

**Issue by hadidez** [BelledonneCommunications/linphone-android#58]
hi, how can i change default codec settings? i just want to set opus codec enabled ...
i change coreapi/linphonecore.c but nothing has changed ...
thnks.

**Comment by CrabeMan** [comment]
Hello, it's what i do
```
for (PayloadType payloadType : linphoneCore.getAudioCodecs()) {
    linphoneCore.enablePayloadType(payloadType, payloadType.getMime().equalsIgnoreCase("opus"));
}
```

CrabeMan.

**Comment by hadidez** [comment]
thnks

**Comment by nhoxbypass** [comment]
Currently what is the default codec of Linphone?
