### ISSUE TITLE
how to change linphone ringtone and call back tone in outgoing call

### ISSUE THREAD

**Issue by Miteshmakwana73** [BelledonneCommunications/linphone-android#580]
I am trying to change ringtone if incoming call received and if I make any outgoing call now it's playing audio beep beep it looks like "call engaged" I want to play a ringing tone on the outgoing call how do I achieve this?

**Comment by Viish** [comment]
Ringback tone is sent by the remote end of the call, not chosen locally.
Ringtone if not device's one can be changed in LinphoneManager: mRingSoundFile

**Comment by Miteshmakwana73** [comment]
I tried with two or more softphone and it's playing the normal ringback USA ringing tone like tring tring but in linphone it's always playing bip sound

**Comment by Miteshmakwana73** [comment]
@Viish why it is working on other softphone

**Comment by Viish** [comment]
I don't know. Attach your logs.

**Comment by Miteshmakwana73** [comment]
[log.txt](https://github.com/BelledonneCommunications/linphone-android/files/3097019/log.txt)

this is my log file

**Comment by Miteshmakwana73** [comment]
@Viish did you find any solution?

**Comment by RONNIEANDERSON** [comment]
@Viish I am facing the same issue can you please elaborate

**Comment by daniebruwer** [comment]
@Viish also not working for me. I've tried a few options. I'm not getting any sort of dial tone.

 private void setRingTone()
    {
        Uri ringUri = Uri.parse("android.resource://" + getPackageName() + "/raw/" + "phone_ringing");
        lc.setRing( ringUri.toString()  );
        lc.setRemoteRingbackTone( ringUri.toString() );
    }

**Comment by sushilsolanki8875** [comment]
Any update on this?

**Comment by softerj** [comment]
This is not working for me either

**Comment by Charanmakkar** [comment]
hey guys, did any one of you got any solution to this?
