### ISSUE TITLE
The notification dot is always shown

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#588]
For my personal device all works fine:
1. `Background mode` is on
2. The permanent notification is shown
3. `Allow notification dot` is on in notifications settings for the app.
4. The dot/badge is shown only when I have a missed call or incoming message.

But for the second, exactly the same device (LineageOS 16.0 / Android 9, OP3T, Linphone 4.1 (4120)
the dot is shown permanently.

**Comment by Viish** [comment]
Can you attach a screenshot please ?

**Comment by 532910** [comment]
"bad" phone:
![image](https://user-images.githubusercontent.com/14617699/57166727-b6107580-6e03-11e9-9f40-37d15d63176d.png)

"good" phone:
![image](https://user-images.githubusercontent.com/14617699/57166747-c7f21880-6e03-11e9-864a-4ca8ee0637a5.png)

**Comment by 532910** [comment]
I've found the toggle that's responsible for this dot.

The `Linphone service notification` (and `Linphone instant messages notifications` on the screen below) is not just a checkmark, but also a submenu.

![image](https://user-images.githubusercontent.com/14617699/60478036-f0728380-9c89-11e9-9c6c-31b076afebce.png)


Under this submenu there is a toggle for service notification dot:
![image](https://user-images.githubusercontent.com/14617699/60477964-9c679f00-9c89-11e9-87f2-c27903498fdc.png)

Could you change the defaults and set it off by default?

**Comment by Viish** [comment]
I'll see what I can do

**Comment by Viish** [comment]
No I can't set a default value for this, this is user setting only.

**Comment by 532910** [comment]
Thank you for investigation.

**Comment by 532910** [comment]
In fact it's possible!

Check libretorrent and PlainUPnP as they were fixed this:

https://gitlab.com/proninyaroslav/libretorrent/-/issues/222
https://github.com/m3sv/PlainUPnP/issues/60

**Comment by Viish** [comment]
In the feature/kotlin_rewrite this is already implemented: no badge for service notification, only for IM & calls.

**Comment by 532910** [comment]
I confirm this is fixed.
