### ISSUE TITLE
changing login/password fails

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#589]
I have a configured, successfully connected account.
When I change login and password to another user it can't connect anymore.
tcpdump shows it receives Unauthorised reply with nonce from the server but it doesn't replies to it.
The only way is to delete account and create a new one.

**Comment by Viish** [comment]
Fixed in aa608f2e726f8bbdb0e98d8ea297891237bfa99e

**Comment by 532910** [comment]
doesn't work for me
4.2.0-beta.32+98add9b2
