### ISSUE TITLE
background service is not restated after update

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#592]
background service is not restated after the app update

**Comment by Viish** [comment]
It's too much of a hassle to handle this scenario, we won't fix it sorry.

**Comment by 532910** [comment]
It's a pity! For example [syncthing](https://github.com/syncthing/syncthing-android) handles this case.

**Comment by Viish** [comment]
We just don't use the background service enough. With the push notifications it only lives for a couple of minutes max.
If you want you can submit a PR.

**Comment by 532910** [comment]
While linphone.org service don't use the background service, it's used by other servers, without push notifications.

As I understand the fix is simple: `Start at boot time` setting should be called not only at boot time but also after update.

I'm not android developer, but looks like you just need to check `ACTION_MY_PACKAGE_REPLACED` in addition to `ACTION_BOOT_COMPLETED`:
https://github.com/syncthing/syncthing-android/blob/6c87f2fb44fac80baa60375596555dc6905acb4f/app/src/main/java/com/nutomic/syncthingandroid/receiver/BootReceiver.java#L17-L18

**Comment by 532910** [comment]
https://github.com/BelledonneCommunications/linphone-android/pull/807
