### ISSUE TITLE
change srtp encryption

### ISSUE THREAD

**Issue by aliahmaed** [BelledonneCommunications/linphone-android#593]
how to change srtp encryption to AES256/SHA256

**Comment by Viish** [comment]
Do you even search a bit the source code before opening a ticket here?
A simple grep would have found you your answer: There is a method linphone_core_get_srtp_crypto_suites in liblinphone that reads the srtp_crypto_suites item in [sip] section of the linphonerc file.

**Comment by gianks** [comment]
Viish i guess the question was how to do it without recompiling the entire software.
Would be nice to expose such setting in the GUI. In the same manner i wish linphone could allow me to set if to use encrypted media per each SIP account.

I guess these should be marked as enhancements/new features.

Best Regards
