### ISSUE TITLE
Where are the tutorials?

### ISSUE THREAD

**Issue by DroidPulkit** [BelledonneCommunications/linphone-android#594]
According to the wiki https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Getting%20started/Android/

It says under Using liblinphone API
that "take a look either at the LinphoneMini project in the sample/ folder or at the tutorials in the submodules/linphone/coreapi/help/java/org/linphone/core/tutorials/ folder."

Can anyone help please and point to the tutorials folder?

**Comment by Viish** [comment]
There are no longer tutorials inside the linphone-android project. There still is some examples in the linphone project in linphone/coreapi/help/examples/java/org/linphone/core/tutorials/ but there is a good chance they're outdated.
You can consult the documentation on our website https://linphone.org.

**Comment by DroidPulkit** [comment]
> There are no longer tutorials inside the linphone-android project. There still is some examples in the linphone project in linphone/coreapi/help/examples/java/org/linphone/core/tutorials/ but there is a good chance they're outdated.
> You can consult the documentation on our website https://linphone.org.

The documentation you are referring to is simply pointing to the above thing I just asked. 

 "take a look either at the LinphoneMini project in the sample/ folder or at the tutorials in the submodules/linphone/coreapi/help/java/org/linphone/core/tutorials/ folder."

So right now, I am in a recursion phase!!

**Comment by Viish** [comment]
Have you read the https://www.linphone.org/snapshots/docs/liblinphone/multilang/ documentation  ?

**Comment by Viish** [comment]
There are also documentation on our wiki : https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Getting%20started/

**Comment by Viish** [comment]
I've started to add again a sample application, it's available here: https://gitlab.linphone.org/BC/public/linphone-android/tree/feature/sample_app
