### ISSUE TITLE
video call preview is not displaying 

### ISSUE THREAD

**Issue by Miteshmakwana73** [BelledonneCommunications/linphone-android#595]
I am trying to video call using linphone 4.1 but I am facing problem it shows video call started but video preview not displaying on screen

I am getting blank screen instead of video black screen

I am getting this [logs](https://github.com/BelledonneCommunications/linphone-android/files/3119668/new.linphone.video.log)

**Comment by Viish** [comment]
The problem is your device doesn't receive any media packet (0 audio, 25 video which is as good as 0). Check the other end and/or your network.

**Comment by Miteshmakwana73** [comment]
from where you find I am getting this response in the log?

**Comment by Miteshmakwana73** [comment]
@vish how do I solve this issue?

**Comment by Viish** [comment]
You investigate why your client doesn't receive any/few packets when it shoudln't.
For that you might check your network, your SIP proxy and the remote end of the call logs.
