### ISSUE TITLE
OutgoingInit Call on WiFi

### ISSUE THREAD

**Issue by OwaisKhatri** [BelledonneCommunications/linphone-android#597]
Hi,

I am using below Linphone-Android SDK:
"org.linphone:linphone-sdk-android:4.1-367-gb11c8cb"

I am successfully able to init call and send IM, but only using Network Data. I am using Outbound Proxy.
When Initiating a call using WiFi, it gives an error of **403 Forbidden - You must register first to S-CSCF.**
Also, when party A is on Network Data and party B is on WiFi, call is initiated and properly working.
What should be the possible issue I am facing? If there is something more info required kindly ask, I will provide it.

Thanks,
Muhammad Awais.

**Comment by Viish** [comment]
> 403 Forbidden - You must register first to S-CSCF

This error is not part of our SDK or application, so either it comes from your network or our SIP proxy.

**Comment by im-ranu** [comment]
Check your router Configurations. It is because of SIP ALG is enabled in your router gateway.
