### ISSUE TITLE
Build LinPhone-Android Failed

### ISSUE THREAD

**Issue by WilfriedTIANI** [BelledonneCommunications/linphone-android#598]
I uploaded Linphone-Android from Git , with this command

_**git clone git://git.linphone.org/linphone-android.git --recursive**_

After it i loaded projet to AndroidStudio , all was fine . Now when tried to build and install on phone i have this error 

**_error: LinphoneManager is not abstract and does not override abstract method onMessageSent(Core,ChatRoom,ChatMessage) in CoreListener_**

PLease can you help me ?

**Comment by WilfriedTIANI** [comment]
PLease can you help me ?

**Comment by Viish** [comment]
Hi,
Indeed we added a new callback in the library that must be implemented in the LinphoneManager class of the app. The job is done but not yet merged on master branch, hence the compilation issue.
You can either use the feature/split_linphone_activity branch or implement this callback manually (Android Studio fixer will suggest it) and do nothing in it.

**Comment by WilfriedTIANI** [comment]
Tks 
Working fine i added 2 method 
onChatRoomRead
onMessageSent

**Comment by WilfriedTIANI** [comment]
Morning @Viish  
Je sais que le problème est déjà ferme(C'est moi qui ai ferme) mais je voulais juste faire un partage sur ce que j'ai eu comme retour en testant toutes les versions publiée.
 En fait je le problème d'authentification se pose lors du passage de la version 
**aa608f2e726f8bbdb0e98d8ea297891237bfa99e** du    24-04-2019 a  08h38  a la version
**5197d5b926aecb9e23424f3c5771da3f94859428** du    24-04-2019 a 10h18  

J'ai remarque après ce changement l'application ne se connecte plus au serveur.

Pour tester j'utilise un téléphone avec les caractéristiques suivantes :
Fabriquant : Xiaomi
Model : Remi Note 5 
Version Android : 8.1.0 -> OPM1.171019.011
Version MIUI : MIUI Global 10.2.1 Stable -> 10.2.2.0(OEIMIXM)
Nom Model : MEE7S
