### ISSUE TITLE
how to set new bitrate for codec ?

### ISSUE THREAD

**Issue by hadidez** [BelledonneCommunications/linphone-android#60]
hi, how can i set 8,16, ...  kHZ opus codec ? and where linphone load codecs from ?!
i want to make an optional opus bitrate list to select from 8 to 48 kHZ.

**Comment by DatBewar** [comment]
Hi, you can't do it directly in Linphone Android, you must do it in mediastreamer2.
This seems to be in https://github.com/BelledonneCommunications/mediastreamer2/blob/master/src/audiofilters/msopus.c maybe
