### ISSUE TITLE
After Successfully login in Linphone not able to hear IVR 

### ISSUE THREAD

**Issue by anujvats111** [BelledonneCommunications/linphone-android#602]
Hello,
I am using linphone from long time and i logged in with own sip details when i am trying to call it's directly called to end user no IVR no bell ring . And after dialing number when i press (enable and disable) mic button then got IVR and Ring both clearly but without enable and disable mic button not able to hear IVR and Ring. What is the actual issue and what will be the solution for that any explain?

**Comment by Viish** [comment]
Hi,
What's IVR ?

**Comment by anujvats111** [comment]
IVR like balance sound (remaining balance sound) and bell ring

**Comment by Viish** [comment]
Could you attach logs please?
