### ISSUE TITLE
ice: Failed ICE check list processing

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#603]
When registered to my linphone.org account and having a call forwarded to that account from my SIP server, ICE fails.  The call detail says ICE is in progress for a few 10s of seconds and then says ICE failed.

Here's the [log](http://brian.interlinx.bc.ca/linphone-ice-failure.txt).

**Comment by Viish** [comment]
Please open this ticket in linphone repository, it's not related to Android app.

**Comment by brianjmurrell** [comment]
BelledonneCommunications/linphone#118 for anyone interested.
