### ISSUE TITLE
support for separate incoming and outgoing proxies

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#604]
If I configure linphone to register to my linphone.org account, I cannot then also have that account use my own SIP proxy for outgoing calls.  Trying to change the outgoing proxy configuration to my own SIP proxy makes the connection to the linphone.org proxy fail.

My goal here is to register linphone to linphone.org so that I receive pushes for calls to that account and then forward calls destined for my phone on my SIP proxy to my linphone.org account.  This all works fine.  I can receive the calls at my linphone phone from my SIP proxy successfully.

What doesn't work is that I cannot use the dialpad on linphone to dial a phone number and have that call connected (authenticated of course!) through my own SIP proxy the way I can if I instead register linphone to my SIP proxy.

**Comment by Viish** [comment]
Why don't you create both your accounts (the sip.linphone.org one that will receive calls and the one from your own proxy)?
Set yours as default so it will be used for outgoing calls.

**Comment by brianjmurrell** [comment]
Because I only want to be registered to linphone.org so that I can compare battery life of linphone-android using the linphone.org proxy vs. using my own.  I.e. comply with https://github.com/BelledonneCommunications/linphone-android/issues/570#issuecomment-484037968.

But of course I still need to be able to make outgoing calls, but I don't want an ongoing registration with my own SIP proxy clouding battery life issues if they persist when using (only) linphone.org.

**Comment by brianjmurrell** [comment]
Any further thoughts on this?

I cannot see how a linphone.org account can be useful in the context of a mobile phone (wanting to make mobile calls with a SIP provider) without being able to have separate incoming and outgoing accounts.

Your suggestion of creating a separate account would work if I could configure it to be outgoing only and not register to the SIP server but rather just use it to make INVITEs with.

**Comment by brianjmurrell** [comment]
> Why don't you create both your accounts (the sip.linphone.org one that will receive calls and the one from your own proxy)?
Set yours as default so it will be used for outgoing calls.

This doesn't work for SIP MESSAGEs though.

If I configure my proxy to forward MESSAGEs to sip.linphone.org, my linphone receives them just fine on it's account registered to sip.linphone.org.  However when trying to reply to that message, because I have configured as you suggested above with my own proxy as the default, it rejects the MESSAGE because it's coming from <me>@sip.linphone.org.

I do have _Proxy_ set to `<sip:sip.linphone.org;transport=tls>` and _Outbound proxy_ enabled as it was configured by linphone when I created the linphone.org account.

**Comment by brianjmurrell** [comment]
Why did you close this?  Without even responding to the most recent comment describing how your suggested work-around simply cannot work.

How do you suggest that I can use linphone.org and be able to make calls **and** respond to SIP MESSAGEs?

**Comment by Viish** [comment]
I closed it because this isn't an issue and we won't create incoming only proxy and outgoing only proxy.
Regarding your configuration, this isn't an android app related issue, this has nothing to do here.
