### ISSUE TITLE
Multiple dialogues with the same contact 

### ISSUE THREAD

**Issue by mehran22k** [BelledonneCommunications/linphone-android#605]
Hi guys
i use version 4.1 (and also asterisk for my sip server)

when i send some messages to another , chat list show multiple contact with the same number (same sip address)

Now i Detect the problem:
when a new message received and its saved on phone, **LocalAddress** for each Rooms saved like this: "sip:123465@88.5.3.2" and this make a lot of problems. this Ip is Device's ip that changed some times and cuz d to show multiple dialogues with same sip address.

in fact **LocalAddress** for each rooms should save like "sip:123465@mydomain.com" 
now if i run  **room.getLocalAddress().asStringUriOnly()** its return sip address with ip ("sip:123465@88.5.3.2") but it should return something like "sip:123465@nydomain.com" 

(message (To and From address) from switch also come to phone like "sip:123465@mydomain.com" but i don't know ,where and why its converted to something like this:  "sip:123465@88.5.3.2" for **LocalAddress** of chatroom)

How can i solve it? i guess when a new message received, saving process run in  linphone sdk and i can't change it (i don't know how to).

Please Help me
thank you in advance

**Comment by Viish** [comment]
HI @mehran22k 

Actually this issue is caused by your Asterisk configuration, not the liblinphone in the Android app.
Our library simply uses the value in the FROM header in the message sent by your server, and there is nothing we can do to change that.

Cheers,

**Comment by mehran22k** [comment]
Hi @Viish 
Thanks for your answer
in fact i have this problem just with linphone 4.1
but not with 4.0.1

today i try android 4.0.1 and linphone-SDK 4.1 and then i see its make multiple dialogues.(i use maven repository Linphone SDK )
but when i try android 4.0.1 with linphone core 3.12.0... its work correctly( i clone version 4.01 and make Linphone SDK on ubuntu)

so i guess this problem is caused by linphone Sdk and not the App.
in 4.0.1 , in **OnMessageReceived** when i run **cr.getLocalAddress().asStringUriOnly()** it show me  something like this: **sip:12345@mydomain.com**
but in version 4.1 it show me  something like this **sip:12345@99.8.5.1**
i check and try all of the settings in app and my switch these days but i still have this problem with version 4.1)
please check it again.
Thank you in advance

**Comment by amit1576** [comment]
Hi @Viish 
I am also facing same problem with version 4.1. 
In **onMessageReceived** **cr.getPeerAddress().getDomain** returning device IP on Sender like **sip:9000@192.168.20.22**. It must be **sip:9000@sipserverdomain**...

Please check it.
Thanks in Advance...

**Comment by Viish** [comment]
Attach a capture of your logs showing a MESSAGE please.

**Comment by mehran22k** [comment]
Hi 
the log file is attached (when receiving message)
):   I had to replace IPs and domain name
so:
50.50.50.50  is my server ip
4.4.4.4 is Device IP (Message receiver device)
222 is sender
333 is receiver
=============
If you need, or if you don't have asterisk switch, i can provide asterisk switch and send to you its extension detail (by email) 
**Thank you so much**

[mylog.log](https://github.com/BelledonneCommunications/linphone-android/files/3179088/mylog.log)

**Comment by Viish** [comment]
Problem is your proxy configuration:
```
MESSAGE sip:333@4.4.4.4:64745;app-id=929724111839;pn-type=firebase;pn-timeout=0;pn-tok=dfC0GbHKL04:APA91bEQl55MQQMhmVls7rZ1455jf4BE0wdm-Z1917zS1oIre8Gkpv0b6ZEEqrVJAusNL1glvAqCziUpYeII7MVNvM182XCWnulWjaCYV9DW4QgERXFX9ictHycr4zR07v7BXxaA6sFj;pn-silent=1;transport=udp SIP/2.0
Via: SIP/2.0/UDP 50.50.50.50:5060;branch=z9hG4bK648291fa;rport
Max-Forwards: 70
From: "Unknown" <sip:4165486451@mydomain.com>;tag=as1d2bee06
To: <sip:333@4.4.4.4:64745;app-id=929724111839;pn-type=firebase;pn-timeout=0;pn-tok=dfC0GbHKL04:APA91bEQl55MQQMhmVls7rZ1455jf4BE0wdm-Z1917zS1oIre8Gkpv0b6ZEEqrVJAusNL1glvAqCziUpYeII7MVNvM182XCWnulWjaCYV9DW4QgERXFX9ictHycr4zR07v7BXxaA6sFj;pn-silent=1;transport=udp>
```
As you can see the TO header contains an IP, not a domain.

**Comment by amit1576** [comment]
Hi @Viish,

The Scenario is like this.
I have two sip user 909 & 821 registered by my sip server domain. When 909 send message to 821 the **From: <sip:909@sip.mydomain.com>;tag=-t6swksAt** & 
**To: sip:821@sip.mydomain.com** 


are absolutely fine and message is received by 821. 

**But when 821 reply the message then the FROM Header get changed from domain to local IP address. 
### From: <sip:821@192.168.20.160>;tag=zvX~2Rd0u
### To: sip:909@sip.mydomain.com. 
As the FROM Header changes, On message receiving the application create new chat room as peeraddress not matched with the already created chat room for sip user 821.  "onMessageReceived cr.getPeerAddress().getDomain".**

For your reference i have attached the IM.log file.

Please look into it.
Thanks in advance....

[IM.log](https://github.com/BelledonneCommunications/linphone-android/files/3185824/IM.log)

**Comment by Viish** [comment]
It would be interesting to see linphone logs.
Also make sure you do have a proxy config in linphone configured with the domain name and set by default.

**Comment by amit1576** [comment]
Hi @Viish,

May be it is our sip server configuration issue. As Header values got changed when message sent from our sip server to destination number.


Thanks,

**Comment by amit1576** [comment]
Hi @mehran22k ,

Any success !!!. Are you able to find out any solution.

Thanks,

**Comment by mehran22k** [comment]
Hi @amit1576 
Unfortunately no :(

**Comment by amit1576** [comment]
Hi @mehran22k ,

Actually my major concern is that it was working in 4.0.1 with our same sip server configuration**.(as mentioned in #628 also)** . Means linphone sdk 4.0.1 was handling itself this configuration issue or what :).

**Comment by mehran22k** [comment]
Hi @Viish
my question is: why we have this problem just with linphone-android-SDK newer than 4.0.1 ?
i mean we don't have this problem with 4.0.1 
i also check proxy configuration.
Do you have any idea?
Thanks for considering my request.

**Comment by mehran22k** [comment]
Hi @amit1576
How about you? Any success?

**Comment by brianjmurrell** [comment]
@Viish Can you please clarify?  In [this comment](https://github.com/BelledonneCommunications/linphone-android/issues/605#issuecomment-488981258) you said it's based on the `From:` header and in [this message](https://github.com/BelledonneCommunications/linphone-android/issues/605#issuecomment-492575872) you said it's the `To:` header.

Using the `From:` header seems to make the most sense to me, but I want to be sure before I invest time in correcting that.

Thanks.

**Comment by Viish** [comment]
Actually both are used to identify a chat room: the From and the To.
If one of the two changes, it will create a new chatroom.
The proxy shouldn't put IP in From and To header but the identity of the SIP account (user@domain.tld).

**Comment by brianjmurrell** [comment]
So the `From:` makes sense.

But given that the RHS of the `To:` address is the location (i.e. IP address, or domain-name of that IP address) of the client, it is only natural that that location is going to be transient and cause many chatrooms for the same sender to be created.

In what scenario is the RHS of the client address relevant?  I.e. what use-case can be made for considering the RHS of the client address?

A sip proxy writing the `To:` address with a RHS of itself is lying at best about where it intends the message to go and if it's actually using that same information to (i.e. IP) route the message to the client, it will just end up routing it to itself.

**Comment by Viish** [comment]
Here's an example of message my linphone-android receives correctly, sent by another linphone through flexisip:
```
2019-06-06 16:52:30.813 7323-7323/org.linphone.debug I/belle-sip: channel [0x14274cf140]: message sent to [TLS://sip.linphone.org:5223], size: [992] bytes
    MESSAGE sip:<me1>@sip.linphone.org SIP/2.0
    Via: SIP/2.0/TLS 10.39.109.193:38429;branch=z9hG4bK.2KKgV1xMx;rport
    From: <sip:<me2>@sip.linphone.org>;tag=h42p~4RRW
    To: sip:<me1>@sip.linphone.org
    CSeq: 20 MESSAGE
    Call-ID: vBlD-BKt1w
    Max-Forwards: 70
    Supported: replaces, outbound, gruu
    Date: Thu, 06 Jun 2019 14:52:30 GMT
    Content-Encoding: deflate
    Content-Type: message/imdn+xml
    Content-Length: 183
    Priority: non-urgent
    User-Agent: LinphoneAndroid/4.1-64-g05a440f2 (Blackberry) LinphoneSDK/4.2-44-gfe2b552 (master)
    Proxy-Authorization:  Digest realm="sip.linphone.org", nonce="KKej4AAAAAA6BbIrAACnBH4YM/MAAAAA", algorithm=MD5, opaque="+GNywA==", username="<me2>",  uri="sip:<me1>@sip.linphone.org", response="a6875ade84d7326a1dde30044af0d231", cnonce="psU6CjqVcAvH3Rc5", nc=00000004, qop=auth
    
    x... (first 810 bytes shown)
```

This is totaly valid in SIP, my IP is in the VIA header.

**Comment by brianjmurrell** [comment]
@Viish Do you really think it's entirely unreasonable that the To: header contain the actual [account and] ip address of the end node to which the proxy is sending the SIP MESSAGE and that every SIP proxy needs to conform to linphone rather than linphone being flexible with the interpretations and implementations of SIP proxies?

**Comment by brianjmurrell** [comment]
@Viish Can you point me to where in the code that the To: header is being used to categorise the message conversations at least.  Please.

**Comment by Viish** [comment]
Sure: https://github.com/BelledonneCommunications/linphone/blob/master/coreapi/chat.c#L192

**Comment by Viish** [comment]
@brianjmurrell From the SIP RFC 3261 (https://tools.ietf.org/html/rfc3261#section-8.1.1.2):

> The From header field indicates the logical identity of the initiator
   of the request, possibly the user's address-of-record.  Like the To
   header field, it contains a URI and optionally a display name.  It is
   used by SIP elements to determine which processing rules to apply to
   a request (for example, automatic call rejection).  As such, it is
   very important that the From URI not contain IP addresses or the FQDN
   of the host on which the UA is running, since these are not logical
   names.

**Comment by mehran22k** [comment]
I solve this 
I just replacing my domain name with sip address(Replace domain name with Ip) while Inserting Sip address to Database

**Comment by brianjmurrell** [comment]
@mehran22k How does this solve the problem when each Message thread is collated by both the sender address and the receiver address and the receiver address includes the IP address of the linphone client, which of course can roam across many networks when mobile?

**Comment by 532910** [comment]
#583

**Comment by LargePrime** [comment]
How do I goto my voip provider and tell them they are doing it wrong?
Can Linphone implement a setting to enable the logic 4.0.1 had, for voip providers that will not listen to my complaints?

**Comment by 532910** [comment]
Sylvain, yes, there are sip servers that don't conform RFC, and with flexisip all works fine. But what prevents to make a workaround for "bad" servers?

**Comment by brianjmurrell** [comment]
> How do I goto my voip provider and tell them they are doing it wrong?
> Can Linphone implement a setting to enable the logic 4.0.1 had, for voip providers that will not listen to my complaints?

Well they listen but then they say...
 
> Other Softphones do not seem to have trouble with this. And they probably do not care about standards.

So regardless of who is right and who is wrong, Linphone ends up being the outlier that _just doesn't work_ and the provider suggests a dozen other alternatives that their other customers are using without any problems.

Sometimes it doesn't matter if you are the one who is right.  Particularly if you are the only one (or one of a very few) who is right.  Sometimes you just need to [_go along to get along_](https://idioms.thefreedictionary.com/go+along+to+get+along).

**Comment by Viish** [comment]
> But what prevents to make a workaround for "bad" servers?

When a product says it follows a RFC, it must do it correctly. It's not our job to maintain hacks or workarounds (because this is what is needed here) for each product that does a bad job.
It is hard to test, to maintain and it makes the code less robust and more difficult to understand.
Also if we do workaround it, it will never be fixed upstream.
Finally, linphone is an open-source project so if you really need it fixed you can do it.

**Comment by zxpgo** [comment]
> I solve this
> I just replacing my domain name with sip address(Replace domain name with Ip) while Inserting Sip address to Database

How to solve the problem?  Can you explain in detail？ Thank you!

**Comment by waleedtalha** [comment]
> > I solve this
> > I just replacing my domain name with sip address(Replace domain name with Ip) while Inserting Sip address to Database
> 
> How to solve the problem? Can you explain in detail？ Thank you!

https://github.com/BelledonneCommunications/linphone-android/issues/583#issuecomment-536212528
