### ISSUE TITLE
Add/Enable G729 and G723 Codecs Without prepare.py

### ISSUE THREAD

**Issue by WilfriedTIANI** [BelledonneCommunications/linphone-android#606]
Morning all,

Please how to **add** or **enable** **_G729_** and **_G723_** codecs on LinPhone-Android.

After **prepare.py** removed, i don't saw how to do it 

Please can you help me ?

**Comment by Viish** [comment]
Hi,

Like you would have done with the prepare.py script, give the cmake.. command the options you want like -DENABLE_G729=ON.

Cheers,
