### ISSUE TITLE
App crash when decline incoming call

### ISSUE THREAD

**Issue by nhoxbypass** [BelledonneCommunications/linphone-android#61]
I use my custom SIP Account for using Linphone, when there is an incoming call, i swipe to decline the call, the app crashed with message "**Linphone has stopped**".

I think the main reason is the way you implement **decline()** method in **CallIncomingActivity**. May be change from **terminateCall()** to **declineCall()** can fix this problem. And it worked for me now.

**Comment by DatBewar** [comment]
Hello, **terminateCall** already call a decline if state of call are on _incomming_
https://github.com/BelledonneCommunications/linphone/blob/b75ff9c06c8d3a5e817075a92930f664c947f712/coreapi/linphonecall.c#L5300

Did you had log of your crash?

**Comment by nhoxbypass** [comment]
No. I try to find crash report from logcat. But there is nothing. But declineCall() worked for me now. Thanks for answer my issue :+1:
