### ISSUE TITLE
Not able to disable G722 and  SILK Codecs

### ISSUE THREAD

**Issue by anujvats111** [BelledonneCommunications/linphone-android#613]
Not able to disable G722 and SILK Codecs

Anyone can suggest how to do that i am trying many time but no luck

**Comment by DroidPulkit** [comment]
I think you need to rebuild linphone SDK and use Cmake GUI and untick SILK and G722 there

**Comment by anujvats111** [comment]
No other option instead of recompile ?

**Comment by Viish** [comment]
In the settings you can disable codecs you don't want.
However please note you can't "really" disable G722, to ensure compatibility the library will automatically add it to the INVITE.
