### ISSUE TITLE
Make task getGitVersion optional

### ISSUE THREAD

**Issue by DroidPulkit** [BelledonneCommunications/linphone-android#614]
Some new users, who download this project as ZIP and not git clone is facing issues with building the project.
It seems getGitVersion task is failing as it is not able to find .git folder in the downloaded folders. If we can make getGitVersion task optional and check if we don't have .git folder and do error handling based on that.

**Comment by Viish** [comment]
I'll see what I can do.

**Comment by Viish** [comment]
Fixed in 514c3f4e2b4dd40a443bed78ff5ef1313df6c333
