### ISSUE TITLE
Failed to answer call from linphone.org

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#616]
I just had several calls made to sip.linphone.org, where my linphone-android is registered fail to ring my device.

Here's the [linphone-android log](http://brian.interlinx.bc.ca/linphone-linphone.org-forward-failure.txt).

The calls were made at (times are EST):

May  7 10:46:08
May  7 10:46:55
May  7 10:48:55

**Comment by Viish** [comment]
Add the caller logs for that time please.

**Comment by brianjmurrell** [comment]
What kind of caller logs are you looking for exactly?

**Comment by brianjmurrell** [comment]
I don't keep a trace of every SIP transaction that goes through my SIP proxy because my proxy doesn't have a problem making calls.

I can (almost, because never say never) guarantee you that the calls that came in to my SIP proxy were properly forwarded to linphone.org and I did check the console of the SIP proxy when the calls were not forwarded to my phone and there were no failures in forwarding the call to linphone.org.

Given the timestamps above, I am sure you will find the calls being made from my SIP proxy to linphone.org's.  The account to which the calls were sent would be quite obvious I think.

Those time stamps in the original comment are EST, which I can see I failed to include in that comment.

**Comment by brianjmurrell** [comment]
Github glitch is showing [your comment](https://github.com/BelledonneCommunications/linphone-android/issues/616#issuecomment-490502932) as being 6 hours in the future, FWIW.

**Comment by brianjmurrell** [comment]
I had another occurrence of this problem.

The [linphone log](http://brian.interlinx.bc.ca/linphone-linphone.org-no-answer.txt) and the [SIP conversation](http://brian.interlinx.bc.ca/linphone-linphone.org-no-answer-sip.txt).

**Comment by Viish** [comment]
From our server logs we did received the INVITE and sent a push notification for it and we didn't received anything until the 408 Request Timeout 30 secs later.
Can you check your device logs for a received push notification around that time ?

**Comment by brianjmurrell** [comment]
If you mean looking in the `adb logcat` log, that won't be possible.  Too much time has passed since the most recent incident and the log doesn't go that far back now.

**Comment by Viish** [comment]
Then please check next time it happens.
