### ISSUE TITLE
Build fails for Android with FFMPEG=ON

### ISSUE THREAD

**Issue by DroidPulkit** [BelledonneCommunications/linphone-android#617]
Hey guys I am getting error for building on Android

Steps I followed :- 
`mkdir build && cd build`

`cmake .. -DLINPHONESDK_PLATFORM=Android -DENABLE_NON_FREE_CODECS=ON -DENABLE_MPEG4=ON -DENABLE_H263P=ON -DENABLE_FFMPEG=ON -DENABLE_GPL_THIRD_PARTIES=ON`

`cmake --build . --parallel 4`

**I got the following error (2 in Total)**

Scanning dependencies of target gradle-clean

> Configure project :
Old java wrapper detected, adding it to sources and removing some incompatible classes
AAR artefact group id will be: org.linphone

> Task :clean UP-TO-DATE

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 3s
1 actionable task: 1 up-to-date
[  0%] Built target gradle-clean
Scanning dependencies of target android-arm64
Scanning dependencies of target android-armv7
[ 10%] Creating directories for 'android-armv7'
[ 10%] Creating directories for 'android-arm64'
[ 20%] No download step for 'android-armv7'
[ 20%] No download step for 'android-arm64'
[ 40%] No patch step for 'android-arm64'
[ 40%] No update step for 'android-armv7'
[ 40%] No patch step for 'android-armv7'
[ 40%] No update step for 'android-arm64'
[ 50%] Performing configure step for 'android-arm64'
[ 50%] Performing configure step for 'android-armv7'
loading initial cache file /Users/enguser/Coding/SDK/test2/linphone-sdk/build/android-arm64-prefix/tmp/android-arm64-cache-RelWithDebInfo.cmake
loading initial cache file /Users/enguser/Coding/SDK/test2/linphone-sdk/build/android-armv7-prefix/tmp/android-armv7-cache-RelWithDebInfo.cmake
-- Check for working C compiler: /Users/enguser/Documents/android-ndk-r18/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
-- Check for working C compiler: /Users/enguser/Documents/android-ndk-r18/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
-- Check for working C compiler: /Users/enguser/Documents/android-ndk-r18/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -- works
-- Detecting C compiler ABI info
-- Check for working C compiler: /Users/enguser/Documents/android-ndk-r18/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Users/enguser/Documents/android-ndk-r18/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++
-- Detecting C compile features - done
-- Check for working CXX compiler: /Users/enguser/Documents/android-ndk-r18/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++
-- Check for working CXX compiler: /Users/enguser/Documents/android-ndk-r18/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Check for working CXX compiler: /Users/enguser/Documents/android-ndk-r18/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using toolchain file '/Users/enguser/Coding/SDK/test2/linphone-sdk/cmake-builder/toolchains/toolchain-android-arm64.cmake'
-- Using configuration file '/Users/enguser/Coding/SDK/test2/linphone-sdk/cmake-builder/configs/config-android.cmake'
-- Found PythonInterp: /usr/bin/python (found version "2.7.10") 
-- Including builder linphone
-- Including builder bctoolbox
-- Including builder mbedtls
-- Including builder decaf
-- Including builder bellesip
-- Detecting CXX compile features - done
-- Including builder ortp
-- Including builder ms2
-- Including builder androidcpufeatures
-- Including builder androidsupport
-- Including builder gsm
-- Including builder opus
-- Including builder speex
-- Including builder turbo-jpeg
-- Including builder zxing
-- Including builder ffmpegandroid
-- Using toolchain file '/Users/enguser/Coding/SDK/test2/linphone-sdk/cmake-builder/toolchains/toolchain-android-armv7.cmake'
-- Using configuration file '/Users/enguser/Coding/SDK/test2/linphone-sdk/cmake-builder/configs/config-android.cmake'
-- Including builder ffmpeg
-- Including builder vpx
-- Including builder matroska2
-- Including builder srtp
-- Including builder bzrtp
-- Including builder xml2
-- Including builder sqlite3
-- Including builder ms2plugins
-- Including builder mswebrtc
-- Including builder belr
-- Including builder libxsd
-- Including builder xerces
-- Including builder soci
-- Including builder belcard
-- Found PythonInterp: /usr/bin/python (found version "2.7.10") 
-- Including builder lime
-- Including builder linphone
-- Including builder bctoolbox
-- Including builder mbedtls
-- Including builder decaf
-- Including builder bellesip
-- Including builder ortp
-- Including builder ms2
-- Including builder androidcpufeatures
-- Including builder androidsupport
-- Including builder gsm
-- Including builder opus
-- Including builder speex
-- Including builder turbo-jpeg
-- Including builder zxing
-- Including builder ffmpegandroid
-- Including builder ffmpeg
-- Including builder vpx
-- Including builder matroska2
-- Including builder srtp
-- Including builder bzrtp
-- Including builder xml2
-- Including builder sqlite3
-- Including builder ms2plugins
-- Including builder mswebrtc
-- Including builder belr
-- Including builder libxsd
-- Including builder xerces
-- Including builder soci
-- Including builder belcard
-- Including builder lime
-- Check for working C compiler: /Users/enguser/Documents/android-ndk-r18/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
-- Check for working C compiler: /Users/enguser/Documents/android-ndk-r18/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
-- Check for working C compiler: /Users/enguser/Documents/android-ndk-r18/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -- works
-- Detecting C compiler ABI info
-- Check for working C compiler: /Users/enguser/Documents/android-ndk-r18/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Users/enguser/Documents/android-ndk-r18/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++
-- Detecting C compile features - done
-- Check for working CXX compiler: /Users/enguser/Documents/android-ndk-r18/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Check for working CXX compiler: /Users/enguser/Documents/android-ndk-r18/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Users/enguser/Documents/android-ndk-r18/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compile features
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/enguser/Coding/SDK/test2/linphone-sdk/build/android-arm64/Autotools
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/enguser/Coding/SDK/test2/linphone-sdk/build/android-armv7/Autotools
CMake Error at /usr/local/Cellar/cmake/3.14.3/share/cmake/Modules/ExternalProject.cmake:2628 (message):
  No download info given for 'EP_ffmpegandroid' and its source directory:

   /Users/enguser/Coding/SDK/test2/linphone-sdk/build/WORK/android-arm64//Source/EP_ffmpegandroid

  is not an existing non-empty directory.  Please specify one of:

   * SOURCE_DIR with an existing non-empty directory
   * DOWNLOAD_COMMAND
   * URL
   * GIT_REPOSITORY
   * SVN_REPOSITORY
   * HG_REPOSITORY
   * CVS_REPOSITORY and CVS_MODULE
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.14.3/share/cmake/Modules/ExternalProject.cmake:3211 (_ep_add_download_command)
  cmake/CMakeLists.txt:814 (ExternalProject_Add)
  cmake/CMakeLists.txt:889 (linphone_builder_add_external_project)
  cmake/CMakeLists.txt:1035 (linphone_builder_add_external_projects)
  CMakeLists.txt:79 (linphone_builder_add_projects)

CMake Error at /usr/local/Cellar/cmake/3.14.3/share/cmake/Modules/ExternalProject.cmake:2628 (message):
  No download info given for 'EP_ffmpegandroid' and its source directory:

   /Users/enguser/Coding/SDK/test2/linphone-sdk/build/WORK/android-armv7//Source/EP_ffmpegandroid

  is not an existing non-empty directory.  Please specify one of:

   * SOURCE_DIR with an existing non-empty directory
   * DOWNLOAD_COMMAND
   * URL
   * GIT_REPOSITORY
   * SVN_REPOSITORY
   * HG_REPOSITORY
   * CVS_REPOSITORY and CVS_MODULE
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.14.3/share/cmake/Modules/ExternalProject.cmake:3211 (_ep_add_download_command)
  cmake/CMakeLists.txt:814 (ExternalProject_Add)
  cmake/CMakeLists.txt:889 (linphone_builder_add_external_project)
  cmake/CMakeLists.txt:1035 (linphone_builder_add_external_projects)
  CMakeLists.txt:79 (linphone_builder_add_projects)

-- Enabled features:
 * Arch suffix, Append the android abi to shared libraries
 * Java wrapper, Build the Java wrapper from Liblinphone.
 * LIME X3DH, Enable Linphone IM Encryption version 2 support in  Liblinphone.
 * VCARD, Enable vCard 4 support in Linphone and Liblinphone.
 * Mbedtls, Crypto stack implementation based on mbeddtls.
 * GPL third parties, Usage of GPL third-party code (FFmpeg and x264).
 * Non free codecs, Allow inclusion of non-free codecs in the build.
 * SRTP, SRTP media encryption support.
 * ZRTP, ZRTP media encryption support.
 * WebRTC AEC, WebRTC echo canceller support.
 * WebRTC AECM, WebRTC echo canceller for mobile support.
 * GSM, GSM audio encoding/decoding support.
 * iLBC, iLBC audio encoding/decoding support.
 * ISAC, ISAC audio encoding/decoding support.
 * OPUS, OPUS audio encoding/decoding support.
 * Speex, Speex audio encoding/decoding support.
 * Video, Ability to capture and display video.
 * jpeg, JPEG support with libjpeg-turbo.
 * qrcode, QRCode support with zxing.
 * FFmpeg, Some video processing features via FFmpeg: JPEG encoding/decoding, video scaling, H264 decoding...
 * H263p, H263+ video encoding/decoding support (require license).
 * MKV, MKV playing and recording support.
 * MPEG4, MPEG4 video encoding/decoding support (require license).
 * VPX, VPX (VP8) video encoding/decoding support.

-- Disabled features:
 * Embedded OpenH264, Embed the openh264 library instead of downloading it from Cisco.
 * Unit tests, Enable unit tests support with BCUnit library.
 * Debug logs, Enable debug level logs in libinphone and mediastreamer2.
 * Doc, Enable documentation generation with Doxygen and Sphinx
 * Tools, Enable tools binary compilation.
 * unmaintained, Allow inclusion of unmaintained code in the build.
 * GTK UI, Enable the GTK user interface of Linphone.
 * CXX wrapper, Build the C++ wrapper for Liblinphone.
 * CSharp wrapper, Build the C# wrapper from Liblinphone.
 * LIME, Enable Linphone IM Encryption support in  Liblinphone.
 * NLS, Enable internationalization of Linphone and Liblinphone.
 * Update Check, Enable update check.
 * Relative prefix, liblinphone and mediastreamer will look for their respective ressources relatively to their location.
 * Polarssl, Crypto stack implementation based on polarssl.
 * Tunnel, Secure tunnel for SIP/RTP (require license).
 * RTP Map always in SDP, Always include rtpmap in SDP.
 * mDNS, Multicast DNS support
 * WASAPI, Windows Audio Session API (WASAPI) sound card support.
 * AMRNB, AMR narrow-band audio encoding/decoding support (require license).
 * AMRWB, AMR wide-band audio encoding/decoding support (require license).
 * Codec2, Codec2 audio encoding/decoding support.
 * G729, G.729 audio encoding/decoding support.
 * G729B CNG, G.729 annex B confort noise generation.
 * G726, G.726 audio encoding/decoding support.
 * Silk, Silk audio encoding/decoding support.
 * WebRTC VAD, WebRTC voice activation detector support.
 * BV16, BroadVoice 16 audio encoding/decoding support.
 * H263, H263 video encoding/decoding support (require license).
 * OpenH264, H.264 video encoding/decoding support with the openh264 library (require license).
 * X264, H.264 video encoding support with the x264 library (require license).
 * AAudio, AAudio Android sound card for Android 8+.
 * PCAP, PCAP support.

-- Configuring incomplete, errors occurred!
See also "/Users/enguser/Coding/SDK/test2/linphone-sdk/build/android-arm64/CMakeFiles/CMakeOutput.log".
make[2]: *** [android-arm64-prefix/src/android-arm64-stamp/android-arm64-configure] Error 1
make[1]: *** [CMakeFiles/android-arm64.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
-- Enabled features:
 * Arch suffix, Append the android abi to shared libraries
 * Java wrapper, Build the Java wrapper from Liblinphone.
 * LIME X3DH, Enable Linphone IM Encryption version 2 support in  Liblinphone.
 * VCARD, Enable vCard 4 support in Linphone and Liblinphone.
 * Mbedtls, Crypto stack implementation based on mbeddtls.
 * GPL third parties, Usage of GPL third-party code (FFmpeg and x264).
 * Non free codecs, Allow inclusion of non-free codecs in the build.
 * SRTP, SRTP media encryption support.
 * ZRTP, ZRTP media encryption support.
 * WebRTC AEC, WebRTC echo canceller support.
 * WebRTC AECM, WebRTC echo canceller for mobile support.
 * GSM, GSM audio encoding/decoding support.
 * iLBC, iLBC audio encoding/decoding support.
 * ISAC, ISAC audio encoding/decoding support.
 * OPUS, OPUS audio encoding/decoding support.
 * Speex, Speex audio encoding/decoding support.
 * Video, Ability to capture and display video.
 * jpeg, JPEG support with libjpeg-turbo.
 * qrcode, QRCode support with zxing.
 * FFmpeg, Some video processing features via FFmpeg: JPEG encoding/decoding, video scaling, H264 decoding...
 * H263p, H263+ video encoding/decoding support (require license).
 * MKV, MKV playing and recording support.
 * MPEG4, MPEG4 video encoding/decoding support (require license).
 * VPX, VPX (VP8) video encoding/decoding support.

-- Disabled features:
 * Embedded OpenH264, Embed the openh264 library instead of downloading it from Cisco.
 * Unit tests, Enable unit tests support with BCUnit library.
 * Debug logs, Enable debug level logs in libinphone and mediastreamer2.
 * Doc, Enable documentation generation with Doxygen and Sphinx
 * Tools, Enable tools binary compilation.
 * unmaintained, Allow inclusion of unmaintained code in the build.
 * GTK UI, Enable the GTK user interface of Linphone.
 * CXX wrapper, Build the C++ wrapper for Liblinphone.
 * CSharp wrapper, Build the C# wrapper from Liblinphone.
 * LIME, Enable Linphone IM Encryption support in  Liblinphone.
 * NLS, Enable internationalization of Linphone and Liblinphone.
 * Update Check, Enable update check.
 * Relative prefix, liblinphone and mediastreamer will look for their respective ressources relatively to their location.
 * Polarssl, Crypto stack implementation based on polarssl.
 * Tunnel, Secure tunnel for SIP/RTP (require license).
 * RTP Map always in SDP, Always include rtpmap in SDP.
 * mDNS, Multicast DNS support
 * WASAPI, Windows Audio Session API (WASAPI) sound card support.
 * AMRNB, AMR narrow-band audio encoding/decoding support (require license).
 * AMRWB, AMR wide-band audio encoding/decoding support (require license).
 * Codec2, Codec2 audio encoding/decoding support.
 * G729, G.729 audio encoding/decoding support.
 * G729B CNG, G.729 annex B confort noise generation.
 * G726, G.726 audio encoding/decoding support.
 * Silk, Silk audio encoding/decoding support.
 * WebRTC VAD, WebRTC voice activation detector support.
 * BV16, BroadVoice 16 audio encoding/decoding support.
 * H263, H263 video encoding/decoding support (require license).
 * OpenH264, H.264 video encoding/decoding support with the openh264 library (require license).
 * X264, H.264 video encoding support with the x264 library (require license).
 * AAudio, AAudio Android sound card for Android 8+.
 * PCAP, PCAP support.

-- Configuring incomplete, errors occurred!
See also "/Users/enguser/Coding/SDK/test2/linphone-sdk/build/android-armv7/CMakeFiles/CMakeOutput.log".
make[2]: *** [android-armv7-prefix/src/android-armv7-stamp/android-armv7-configure] Error 1
make[1]: *** [CMakeFiles/android-armv7.dir/all] Error 2
make: *** [all] Error 2

**Comment by Viish** [comment]
Yes we are aware of this compilation issue with FFMPEG.

**Comment by DroidPulkit** [comment]
Hi @Viish Can you please see the Pull Request referenced above. I have solved it locally on my machine, and have sent the solution to it via PR

**Comment by Viish** [comment]
Hi @DroidPulkit 
Yes I saw your PR but actually that doesn't suit us. Sadly I don't have time to work on it right now.
I recommend you to use your fork in the meantime.

**Comment by DroidPulkit** [comment]
Hi @Viish Any update on ffmpeg?

**Comment by Viish** [comment]
No, we probably won't fix it.
