### ISSUE TITLE
contacts are not loaded after reboot

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#620]
I have a contact with sip address in the phonebook provided by DAVx⁵.

After phone reboot untill the fist manual launch of linphone I see:
![image](https://user-images.githubusercontent.com/14617699/57400597-859e5200-71dc-11e9-8c6c-dcffa7cbddf2.png)

And after the fist manual launch of linphone I see:
![image](https://user-images.githubusercontent.com/14617699/57400742-d8780980-71dc-11e9-9a25-1be8733f663e.png)

**Comment by Viish** [comment]
This should fix it: 7f59bc2f955d0de85e196a4dd0e5913b6af58b2c

**Comment by 532910** [comment]
Not fixed in 4125, please reopen.

**Comment by Viish** [comment]
It is in master branch, will be part of 4.2 release.

**Comment by 532910** [comment]
Just for the note to check after 4.2 release.
The one more place where the sip display name is shown instead of phonebook's name after reboot:
![image](https://user-images.githubusercontent.com/14617699/60478195-6c6ccb80-9c8a-11e9-8b7a-727ddc278135.png)

**Comment by 532910** [comment]
I confirm it works fine now, thank you @Viish!
