### ISSUE TITLE
high battery consumption using linphone.org

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#621]
Hi.

I recall previously you said (although I am at a loss to find exactly where unfortunatley) that linphone with push should only use a very small amount of battery.  I recall the number was in the sub-1-2 percent range, particularly when using a linphone.org account.  Please correct me if I am wrong.

I have been using a linphone.org account exclusively for the past week or so and am still seeing battery usage in the 5-10% range.  My current [log](http://brian.interlinx.bc.ca/linphone-linphone.org-high-battery.txt).

**Comment by Viish** [comment]
Hi,
A percentage is relative to your use of the app itself and the other apps on your phone.
If you are only using one app, it is expected that it's battery use percentage will be higher, the same goes if you don't use it very often or you use other apps more.
Battery consumption will also be different depending on your use of the app. Doing video calls in 720P will consume more battery than sending a chat message from time to time.

**Comment by brianjmurrell** [comment]
This is true.  I should have provided some context.

I hardly use the app at all.  It sits idle all day and night long and rings a call or two (at most) a day, which I typically do not even answer (I answer on a different phone).  [No outgoing calls](https://github.com/BelledonneCommunications/linphone-android/issues/604) so really, I am not using it **at all**.

You might ask why I even have it installed but at this point I am still _testing_ it and trying to profile it's "idle" consumption to ensure that it's not going to be a battery pig on people's phones.

**Comment by brianjmurrell** [comment]
So, is 5-10% what you would expect for a(n for all intents and purposes) completely idle linphone-android?

That's a significant portion of a phone's battery just to sit idle waiting for something to do.

And frankly with a 31536000 second expiry, I cannot see why it should be using 5-10% simply to `REGISTER` to the (linphone.org) SIP proxy and then have to do nothing again for up to a year.  Except that's not what happens.  The log is a lot more busy than that.  It wakes up at least hourly and does a bunch of stuff.  Seems to be re-`REGISTER`ing among other things.
