### ISSUE TITLE
For sample app

### ISSUE THREAD

**Issue by Vivektilva** [BelledonneCommunications/linphone-android#622]
Not able to find any function or code to make call (under sample app), if you update with outgoing call functionality it would be grate help.

**Comment by Viish** [comment]
Hi,
Indeed the sample is currently quite simple.
I'll add the invite part soon. In the meantime, you can take a look at the CallManager class in the main project, in the method inviteAddress().

**Comment by Vivektilva** [comment]
Thanks for quick response . Sure i will look at CallManager class.

Indeed it is quite simple and very clean that is why i preferred that. looking forward for invite part .

Thanks .

**Comment by Viish** [comment]
Done in 81588d6906740e7b59e348335e9a83f01841c33f
