### ISSUE TITLE
When can I snap at earlymedia

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#623]
Hi,
I know to use takePreviewSnapshot for capturing local videos, and use takeVideoSnapshot for capturing videos sent by the other party. But when earlymedia calls, what are the conditions under which the caller and the callee are captured?  For example,  in the OutgoingEarlyMedia state, the caller can't snapshot, because it's too early . 
Before receiving the call, the caller and the called judge by what conditions to start Snapshot？

thanks,
Best Regards.

**Comment by Viish** [comment]
When you try to take a snapshot while in early media, do you see in the logs the following warning: "Cannot take snapshot: no currently running video stream on this call" or "Cannot take local snapshot: no currently running video stream on this call" ?

**Comment by fengqz627** [comment]
yes,
 Cannot take local snapshot: no currently running video stream on this call

**Comment by fengqz627** [comment]
On Android, what are the conditions under which the caller and the callee are snapshot?

thanks.

**Comment by Viish** [comment]
The only condition to be able to take a snapshot is to have a video stream with a jpeg writer on it.
Jpeg writer is automatically added, so this would mean you don't have a videostream in your call.

**Comment by fengqz627** [comment]
thank you very much.

**Comment by fengqz627** [comment]
You mean I couldn't snap at earlymedia.
