### ISSUE TITLE
Battery protected settings on Huawei Oreo

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#624]
In Settings->Network on a Huawei EMUI Oreo there is a _Battery protected apps settings_ item but clicking that goes to an Android screen that is not actually used in EMUI Oreo.  I think this is what was used on EMUI prior to Oreo to relax Huawei's app/battery management.

**Comment by Viish** [comment]
The main reason we did this is because some devices have a battery saver app that forces the user to manually whitelist app that would like to receive push notifications.
There is a good stackoverflow thread about that: https://stackoverflow.com/questions/31638986/protected-apps-setting-on-huawei-phones-and-how-to-handle-it
If our Intents list in DeviceUtils isn't correct or complete, feel free to suggest a fix.

**Comment by brianjmurrell** [comment]
Yes, I understand the reason for and function of the option.  But what I am telling you is that on Huawei Oreo, that option is taking the user to the wrong location to whitelist the linphone app.  It's a dead screen on Huawei Oreo.

**Comment by brianjmurrell** [comment]
Are you going to reopen this given the previous comment?

**Comment by Viish** [comment]
Can you attach a screenshot of said screen ?

**Comment by brianjmurrell** [comment]
![Screenshot_20190514-152825](https://user-images.githubusercontent.com/559317/57726382-4600bb80-765d-11e9-9a93-eb842006b44d.jpg)

There are no settings anywhere to get to that screen in Huawei's Oreo nor are there any settings to add any apps there.

I suspect you are looking for the _Battery_->_Launch_ screen which lets you choose on a per-app bases whether an app is managed automatically or manually.  If you choose the latter you can enable/disable each of:
- Auto-launch
- Secondary launch
- Run in background

**Comment by Viish** [comment]
How about with commit 011ac4aa9f482e23c197ef6a4a43398bcd9efa65 ?

**Comment by brianjmurrell** [comment]
Yes, that seems to work, on Oreo at least.  I don't have any other Huawei device other than my Oreo device.
