### ISSUE TITLE
Multiple dialogues with the same contact (#605)

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#627]
Hi guys,
I am using version 4.1  but facing **Multiple dialogues with the same contact.**

In **onMessageReceived** **cr.getPeerAddress().getDomain()** returning device IP of Sender like **sip:9000@192.168.20.22.** It must be **sip:9000@sipserverdomain...**

Please check it.
Thanks in Advance...

**Comment by Viish** [comment]
Duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/605
