### ISSUE TITLE
Sharing server is not used for log upload

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#629]
I was told previously that _Chat_->_Sharing server_ is used for uploading logs.

I have this item configured to use my own custom URL however when I did a _Send Logs_ the logs still went to the https://www.linphone.org:444/ server.

**Comment by Viish** [comment]
Indeed, the Chat->Sharing server setting configures the file_transfer_server_url setting in [misc] section of the linphonerc, but log collection server has it's own setting: log_collection_upload_server_url

**Comment by brianjmurrell** [comment]
That's not what you said in #570.

In this [comment](https://github.com/BelledonneCommunications/linphone-android/issues/570#issuecomment-484167343) you said:
> Log upload isn't enabled by default, the server to which they are uploaded is configurable

[To which](https://github.com/BelledonneCommunications/linphone-android/issues/570#issuecomment-484190774) I asked:
> I missed that configuration option. Where is it?

And [you replied](https://github.com/BelledonneCommunications/linphone-android/issues/570#issuecomment-484194877):
> In chat options, sharing server setting.

It really would be better if that setting were used for log uploads also.  Is there a reason it can't/shouldn't if the user configures their own sharing server?  Or at least a checkbox to choose to upload logs to the user-configured sharing server if they have configured their own?

**Comment by Viish** [comment]
Obviously I made a mistake.
I'll add a setting for that in the master branch.

**Comment by brianjmurrell** [comment]
> Obviously I made a mistake.

Well, that's not the only (obvious) explanation.  What you described could be the desired behaviour and it's a bug that it doesn't work that way, which is why I wanted to point out the conflict and get clarification of which one was correct.

> I'll add a setting for that in the master branch.

Excellent.  Thanks.  You do mean a setting exposed in the GUI's configuration options, yes?

**Comment by Viish** [comment]
> Excellent. Thanks. You do mean a setting exposed in the GUI's configuration options, yes?

Yes

**Comment by Viish** [comment]
Fixed in bfbd5c5eba986c5d44056c10ffbd7e38c950434d
