### ISSUE TITLE
long name issues

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#631]
1. Long name doesn't fit into line:
![image](https://user-images.githubusercontent.com/14617699/57791218-fbf30500-7744-11e9-94aa-faf129ba52c2.png)

2. And only name is shown in the detailed view:
![image](https://user-images.githubusercontent.com/14617699/57791264-15944c80-7745-11e9-93f9-883e7135ea36.png)

But the best way is to show name divied by new line:
```
Пантелеймон
Пантелеймонович
Пантелеймонов
```

**Comment by Viish** [comment]
Fixed in 121bafc8aa609791a45c2cb034b48552dba7eba2

**Comment by 532910** [comment]
![image](https://user-images.githubusercontent.com/14617699/69174932-dab80a80-0b13-11ea-9380-939e7160eb99.png)

Really I'd prefer `left` rather than `center` alignment. But it's much better than before.
Linphone is the first phone/contacts app that I know that shows such a long names fully! Thank you very much (:
