### ISSUE TITLE
Send note or message when invite call

### ISSUE THREAD

**Issue by nglelinh** [BelledonneCommunications/linphone-android#632]
How to send note or message when invite call?
And Incoming have get note or message.
Thanks,

**Comment by Viish** [comment]
By note you mean a text message ?
If yes, then check the chat package in app: you'll need to create a chatroom and send a chatmessage on it.

**Comment by nglelinh** [comment]
Thanks, But I want to send a code to Incoming handle

**Comment by Viish** [comment]
a DTMF ?

**Comment by nglelinh** [comment]
No, It is simply id.

**Comment by nglelinh** [comment]
I want to make a call And I want to send information (Id or text).
I can get it in status Incoming.

**Comment by Viish** [comment]
Use a custom header

**Comment by nglelinh** [comment]
is it addCustomHeader. Thanks you
