### ISSUE TITLE
"LinphoneService not instantiated yet" when using background mode.

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-android#633]
After compiling the latest linphone (about an hour ago), I get a crash right after the splashscreen. This is **without** any SIP settings and after enabling "Background mode". 
Clearing storage/cache allows running Linphone again.

> 05-16 13:56:40.931 30129 30129 I Linphone:  ==== Phone information dump ====
05-16 13:56:40.932 30129 30129 I Linphone: DEVICE=tissot_sprout
05-16 13:56:40.932 30129 30129 I Linphone: MODEL=Mi A1
05-16 13:56:40.932 30129 30129 I Linphone: MANUFACTURER=Xiaomi
05-16 13:56:40.932 30129 30129 I Linphone: SDK=28
05-16 13:56:40.932 30129 30129 I Linphone: Supported ABIs=arm64-v8a, armeabi-v7a, armeabi,
05-16 13:56:40.932 30129 30129 I Linphone: [Service] Linphone version is 5412968d (4124)
05-16 13:56:40.933 30129 30129 I Linphone: Using (r/w) config information from /data/user/0/org.linphone/files/.linphonerc
05-16 13:56:40.942 30129 30129 D skia    : --- Failed to create image decoder with message 'unimplemented'
05-16 13:56:40.945 30129 30129 I Linphone: Using (r/w) config information from /data/user/0/org.linphone/files/.linphonerc
05-16 13:56:40.946 30129 30129 D AndroidRuntime: Shutting down VM
05-16 13:56:40.947 30129 30129 E AndroidRuntime: FATAL EXCEPTION: main
05-16 13:56:40.947 30129 30129 E AndroidRuntime: Process: org.linphone, PID: 30129
05-16 13:56:40.947 30129 30129 E AndroidRuntime: java.lang.RuntimeException: Unable to start service org.linphone.LinphoneService@abe0ab8 with Intent { cmp=org.linphone/.LinphoneService }: java.lang.RuntimeException: LinphoneService not instantiated yet
05-16 13:56:40.947 30129 30129 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3698)
05-16 13:56:40.947 30129 30129 E AndroidRuntime:        at android.app.ActivityThread.access$1600(ActivityThread.java:200)
05-16 13:56:40.947 30129 30129 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1691)
05-16 13:56:40.947 30129 30129 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
05-16 13:56:40.947 30129 30129 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
05-16 13:56:40.947 30129 30129 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6762)
05-16 13:56:40.947 30129 30129 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-16 13:56:40.947 30129 30129 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-16 13:56:40.947 30129 30129 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
05-16 13:56:40.947 30129 30129 E AndroidRuntime: Caused by: java.lang.RuntimeException: LinphoneService not instantiated yet
05-16 13:56:40.947 30129 30129 E AndroidRuntime:        at org.linphone.LinphoneService.h(LinphoneService.java:2)
05-16 13:56:40.947 30129 30129 E AndroidRuntime:        at org.linphone.notifications.g.d(NotificationsManager.java:1)
05-16 13:56:40.947 30129 30129 E AndroidRuntime:        at org.linphone.notifications.g.<init>(NotificationsManager.java:21)
05-16 13:56:40.947 30129 30129 E AndroidRuntime:        at org.linphone.LinphoneService.onStartCommand(LinphoneService.java:6)
05-16 13:56:40.947 30129 30129 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3679)
05-16 13:56:40.947 30129 30129 E AndroidRuntime:        ... 8 more
05-16 13:56:40.950  2844  5548 W ActivityManager:   Force finishing activity org.linphone/.activities.LinphoneLauncherActivity
05-16 13:56:40.951  2844  5548 D ActivityTrigger: ActivityTrigger activityPauseTrigger
05-16 13:56:40.953  2844  5548 W ActivityManager:   Force finishing activity org.linphone/.activities.SplashScreenActivity
05-16 13:56:40.957  2844  2939 I ActivityManager: Showing crash dialog for package org.linphone u0

**Comment by Viish** [comment]
Thanks for noticing !
Fixed in f74f6e5911b2b6d9f1b451aac37902e8f17e7b4e

**Comment by driesken** [comment]
Sorry to re-open this, but I think there might be a similar error after swiping Linphone from the taskmanager (only push, no background enabled):

> 05-17 13:29:29.411  2844  6942 W ActivityManager: Stopping service due to app idle: u0a333 -4s823ms org.linphone/.LinphoneService
05-17 13:29:29.411  2844  6942 D CompatibilityInfo: mCompatibilityFlags - 0
05-17 13:29:29.411  2844  6942 D CompatibilityInfo: applicationDensity - 408
05-17 13:29:29.411  2844  6942 D CompatibilityInfo: applicationScale - 1.0
05-17 13:29:29.426  3690  3690 D KeyguardUpdateMonitor: received broadcast android.intent.action.BATTERY_CHANGED
05-17 13:29:29.428  3690  3690 D KeyguardUpdateMonitor: handleBatteryUpdate
05-17 13:29:29.459 21732 21732 I Perf    : Connecting to perf service.
05-17 13:29:29.473 21732 21732 D FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
05-17 13:29:29.474 21732 21732 D FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
05-17 13:29:29.474 21732 21732 D FirebaseApp: com.google.android.gms.measurement.AppMeasurement is not linked. Skipping initialization.
05-17 13:29:29.474 21732 21732 I FirebaseInitProvider: FirebaseApp initialization successful
05-17 13:29:29.480 21732 21732 I ActivityThread: handleStopService: token=android.os.BinderProxy@6f620e3 not found.
05-17 13:29:29.485 21732 21732 W FactoryImpl: Unable to load optional library ffmpeg-linphone: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.linphone-_GGhoglA_lgR0CVmYDLcsQ==/base.apk"],nativeLibraryDirectories=[/data/app/org.linphone-_GGhoglA_lgR0CVmYDLcsQ==/lib/arm64, /data/app/org.linphone-_GGhoglA_lgR0CVmYDLcsQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]] couldn't find "libffmpeg-linphone.so"
05-17 13:29:29.603 21732 21732 D AndroidRuntime: Shutting down VM
05-17 13:29:29.603 21732 21732 E AndroidRuntime: FATAL EXCEPTION: main
05-17 13:29:29.603 21732 21732 E AndroidRuntime: Process: org.linphone, PID: 21732
05-17 13:29:29.603 21732 21732 E AndroidRuntime: java.lang.RuntimeException: Unable to stop service org.linphone.LinphoneService@7635ae0: java.lang.RuntimeException: LinphoneService not instantiated yet
05-17 13:29:29.603 21732 21732 E AndroidRuntime:        at android.app.ActivityThread.handleStopService(ActivityThread.java:3729)
05-17 13:29:29.603 21732 21732 E AndroidRuntime:        at android.app.ActivityThread.access$1700(ActivityThread.java:200)
05-17 13:29:29.603 21732 21732 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
05-17 13:29:29.603 21732 21732 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
05-17 13:29:29.603 21732 21732 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
05-17 13:29:29.603 21732 21732 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6762)
05-17 13:29:29.603 21732 21732 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-17 13:29:29.603 21732 21732 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-17 13:29:29.603 21732 21732 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
05-17 13:29:29.603 21732 21732 E AndroidRuntime: Caused by: java.lang.RuntimeException: LinphoneService not instantiated yet
05-17 13:29:29.603 21732 21732 E AndroidRuntime:        at org.linphone.LinphoneService.h(LinphoneService.java:2)
05-17 13:29:29.603 21732 21732 E AndroidRuntime:        at org.linphone.l.j(LinphoneManager.java:2)
05-17 13:29:29.603 21732 21732 E AndroidRuntime:        at org.linphone.l.h(LinphoneManager.java:2)
05-17 13:29:29.603 21732 21732 E AndroidRuntime:        at org.linphone.LinphoneService.onDestroy(LinphoneService.java:6)
05-17 13:29:29.603 21732 21732 E AndroidRuntime:        at android.app.ActivityThread.handleStopService(ActivityThread.java:3709)
05-17 13:29:29.603 21732 21732 E AndroidRuntime:        ... 8 more
05-17 13:29:29.608  2844  2939 I ActivityManager: Showing crash dialog for package org.linphone u0

**Comment by Viish** [comment]
On which commit are you ? I fixed an issue like this one a few days ago.

**Comment by driesken** [comment]
I pulled the changes right after you fixed the issue above (f74f6e59).

Linphone Android ff84aeff
Linphone SDK 4.2-28-g9aa3f41

**Comment by Viish** [comment]
Can you attach a stacktrace that is not obfuscated ?

**Comment by driesken** [comment]
[stacktrace.txt](https://github.com/BelledonneCommunications/linphone-android/files/3191386/stacktrace.txt)
This is a stacktrace where I just swiped Linphone from taskmanager and Android's crash dialog popping up.

**Comment by Viish** [comment]
Still obfuscated.

**Comment by driesken** [comment]
With obfuscated, do you mean because of the following line?
> E AndroidRuntime: 	... 8 more

How can I make logcat show the full log? I've used the "logcat -d" option.

**Comment by Viish** [comment]
No, not that.
It's obfuscated because we see
```
05-17 14:06:18.854   674   674 E AndroidRuntime: 	at org.linphone.LinphoneService.h(LinphoneService.java:2)
05-17 14:06:18.854   674   674 E AndroidRuntime: 	at org.linphone.l.j(LinphoneManager.java:2)
05-17 14:06:18.854   674   674 E AndroidRuntime: 	at org.linphone.l.h(LinphoneManager.java:2)
05-17 14:06:18.854   674   674 E AndroidRuntime: 	at org.linphone.LinphoneService.onDestroy(LinphoneService.java:6)
```
Instead of the correct line numbers.

**Comment by driesken** [comment]
Is there any way I can make a better debug? Issue is still present in latest git.
