### ISSUE TITLE
Gradle sync failed: CreateProcess error=2, The system cannot find the file specified 

### ISSUE THREAD

**Issue by EMILIA91** [BelledonneCommunications/linphone-android#634]
hello
i can't build the project.
I clone by git clone command 

but i face : **"ERROR: CreateProcess error=2, The system cannot find the file specified"**

android studio version 3.4.1
![q1](https://user-images.githubusercontent.com/50590786/57876713-4484ee00-782b-11e9-9dab-e5b2a53a9400.JPG)

**Comment by Viish** [comment]
Hi,
I'm gonna need more info about the gradle error than just the screenshot.

**Comment by EMILIA91** [comment]
Hi @Viish 
it just show me this error after open project in android studio
i can't even run build 

last week i open this project using this android studio but now i can't

i' ll try to build it in another OS 
thank you

**Comment by YJWWZHANG** [comment]
> Hi,
> I'm gonna need more info about the gradle error than just the screenshot.

![error](https://user-images.githubusercontent.com/16797366/57920936-cbd76d80-78ce-11e9-8e98-17e30d2700a5.png)

**Comment by Viish** [comment]
Fixed in 77539422a11817e6cbd75cceb4119b5f84b5bfb7
