### ISSUE TITLE
run'make' error: *** [java-clean]  error 127

### ISSUE THREAD

**Issue by Seejun** [BelledonneCommunications/linphone-android#637]
I build the lately liblinphone(4.+) for Android
run './prepare.py',it works well
then run 'make',it does not work,and log:make: *** [java-clean]  error 127.
can everyone help me?thanks!

**Comment by Viish** [comment]
Starting 4.1, we don't use prepare.py anymore.
Check the README of the linphone-android project and the one in the linphone-sdk repository.
