### ISSUE TITLE
SIP point is not login

### ISSUE THREAD

**Issue by im-ranu** [BelledonneCommunications/linphone-android#638]
SIP Point with Capital letter included is not login and SIP point with small letter is login successfully.

SIP point with successful login:
chetan1024278092159007252

SIP point with unsuccessful login:
chuserRanjeetChouhan37630431974711516685766

successfully login with every sip those included small letters and numericals values but unable to login with capital letter included sip point.

same sip point with upper case letter is working fine on play store linphone app.

i'm using SDK v4.2+

**Comment by Viish** [comment]
Attach logs please.

**Comment by im-ranu** [comment]
Logs for Successful login SIP Point

 I/Linphone_demo: Via: SIP/2.0/UDP 192.168.1.124:38091;branch=z9hG4bK.ASoeQz6Yj;rport
 I/Linphone_demo: From: <sip:chetan1024278092159007252@phone.plivo.com>;tag=DN90LpdPf
 I/Linphone_demo: To: sip:chetan1024278092159007252@phone.plivo.com
 I/Linphone_demo: CSeq: 20 REGISTER
 I/Linphone_demo: Call-ID: JNFBSfGgnv
 I/Linphone_demo: Max-Forwards: 70
 I/Linphone_demo: Supported: replaces, outbound, gruu
 I/Linphone_demo: Accept: application/sdp
 I/Linphone_demo: Accept: text/plain
 I/Linphone_demo: Accept: application/vnd.gsma.rcs-ft-http+xml
 I/Linphone_demo: Contact: <sip:chetan1024278092159007252@192.168.1.124:38091;transport=udp>;+sip.instance="<urn:uuid:2e223400-2669-00a4-b1d6-edb1003420e1>"
 I/Linphone_demo: Expires: 3600
 I/Linphone_demo: User-Agent: Unknown (belle-sip/1.6.3)
 I/Linphone_demo: channel [0x710c5e68c0]: ending send background task with id=[3ea6].
 I/Linphone_demo: bellesip_wake_lock_release(): Android wake lock released [ref=0x3ea6]
 I/Linphone_demo: bellesip_wake_lock_acquire(): Android wake lock [belle-sip recv channel] acquired [ref=0x3ed2]
 I/Linphone_demo: channel [0x710c5e68c0]: starting recv background task with id=[3ed2].
I/Linphone_demo: channel [0x710c5e68c0]: received [455] new bytes from [UDP://phone.plivo.com:5060]:
 I/Linphone_demo: SIP/2.0 401 Unauthorized
 I/Linphone_demo: Via: SIP/2.0/UDP 192.168.1.124:38091;branch=z9hG4bK.ASoeQz6Yj;rport=38091;received=203.109.112.38
I/Linphone_demo: From: <sip:chetan1024278092159007252@phone.plivo.com>;tag=DN90LpdPf
 I/Linphone_demo: To: sip:chetan1024278092159007252@phone.plivo.com;tag=378adae1ddc71986618d85886edb3f8b.f04e
 I/Linphone_demo: CSeq: 20 REGISTER
I/Linphone_demo: Call-ID: JNFBSfGgnv
I/Linphone_demo: WWW-Authenticate: Digest realm="phone.plivo.com", nonce="XON701zjeqcWxu0SKOUOm2FeseE4Am8B"
I/Linphone_demo: Server: Plivo
I/Linphone_demo: Content-Length: 0
I/Linphone_demo: channel [0x710c5e68c0] [455] bytes parsed
I/Linphone_demo: channel [0x710c5e68c0]: discovered public ip and port are [203.109.112.38:38091]
I/Linphone_demo: Found transaction matching response.
 I/Linphone_demo: Changing [client] [REGISTER] transaction [0x710c5dd600], from state [TRYING] to [COMPLETED]
I/Linphone_demo: linphone_core_find_auth_info(): returning auth info username=chetan1024278092159007252, realm=
I/Linphone_demo: Auth info found for [chetan1024278092159007252] realm [phone.plivo.com]
I/Linphone_demo: bellesip_wake_lock_acquire(): Android wake lock [belle-sip transaction(0x710c1e0600)] acquired [ref=0x3f06]
I/Linphone_demo: transaction [0x710c1e0600]: starting transaction background task with id=[3f06].
I/Linphone_demo: Changing [client] [REGISTER] transaction [0x710c1e0600], from state [INIT] to [TRYING]
I/Linphone_demo: channel [0x710c5e68c0]: message sent to [UDP://phone.plivo.com:5060], size: [811] bytes
 I/Linphone_demo: REGISTER sip:phone.plivo.com SIP/2.0
 I/Linphone_demo: Via: SIP/2.0/UDP 192.168.1.124:38091;branch=z9hG4bK.ikjvaNpwS;rport
I/Linphone_demo: From: <sip:chetan1024278092159007252@phone.plivo.com>;tag=DN90LpdPf
I/Linphone_demo: To: sip:chetan1024278092159007252@phone.plivo.com
I/Linphone_demo: CSeq: 21 REGISTER
I/Linphone_demo: Call-ID: JNFBSfGgnv
I/Linphone_demo: Max-Forwards: 70
I/Linphone_demo: Supported: replaces, outbound, gruu
I/Linphone_demo: Accept: application/sdp
I/Linphone_demo: Accept: text/plain
I/Linphone_demo: Accept: application/vnd.gsma.rcs-ft-http+xml
I/Linphone_demo: Contact: <sip:chetan1024278092159007252@203.109.112.38:38091;transport=udp>;+sip.instance="<urn:uuid:2e223400-2669-00a4-b1d6-edb1003420e1>"
 I/Linphone_demo: Expires: 3600
 I/Linphone_demo: User-Agent: Unknown (belle-sip/1.6.3)
I/Linphone_demo: Authorization:  Digest realm="phone.plivo.com", nonce="XON701zjeqcWxu0SKOUOm2FeseE4Am8B", username="chetan1024278092159007252",  uri="sip:phone.plivo.com", response="0e02df7fbea5d31d2bbd8ffd5d63477d"
I/Linphone_demo: channel [0x710c5e68c0]: ending recv background task with id=[3ed2].
 I/Linphone_demo: bellesip_wake_lock_release(): Android wake lock released [ref=0x3ed2]
I/Linphone_demo: nict_on_timer_E: sending retransmission
I/Linphone_demo: channel [0x710c5e68c0]: message sent to [UDP://phone.plivo.com:5060], size: [811] bytes
I/Linphone_demo: REGISTER sip:phone.plivo.com SIP/2.0
I/Linphone_demo: Via: SIP/2.0/UDP 192.168.1.124:38091;branch=z9hG4bK.ikjvaNpwS;rport
 I/Linphone_demo: From: <sip:chetan1024278092159007252@phone.plivo.com>;tag=DN90LpdPf
I/Linphone_demo: To: sip:chetan1024278092159007252@phone.plivo.com
I/Linphone_demo: CSeq: 21 REGISTER
I/Linphone_demo: Call-ID: JNFBSfGgnv
 I/Linphone_demo: Max-Forwards: 70
 I/Linphone_demo: Supported: replaces, outbound, gruu
I/Linphone_demo: Accept: application/sdp
 I/Linphone_demo: Accept: text/plain
I/Linphone_demo: Accept: application/vnd.gsma.rcs-ft-http+xml
I/Linphone_demo: Contact: <sip:chetan1024278092159007252@203.109.112.38:38091;transport=udp>;+sip.instance="<urn:uuid:2e223400-2669-00a4-b1d6-edb1003420e1>"
I/Linphone_demo: Expires: 3600
 I/Linphone_demo: User-Agent: Unknown (belle-sip/1.6.3)
I/Linphone_demo: Authorization:  Digest realm="phone.plivo.com", nonce="XON701zjeqcWxu0SKOUOm2FeseE4Am8B", username="chetan1024278092159007252",  uri="sip:phone.plivo.com", response="0e02df7fbea5d31d2bbd8ffd5d63477d"
2019-05-21 I/Linphone_demo: bellesip_wake_lock_acquire(): Android wake lock [belle-sip recv channel] acquired [ref=0x3eda]
I/Linphone_demo: channel [0x710c5e68c0]: starting recv background task with id=[3eda].
I/Linphone_demo: channel [0x710c5e68c0]: received [507] new bytes from [UDP://phone.plivo.com:5060]:
I/Linphone_demo: SIP/2.0 200 OK
I/Linphone_demo: Via: SIP/2.0/UDP 192.168.1.124:38091;branch=z9hG4bK.ikjvaNpwS;rport=38091;received=203.109.112.38
I/Linphone_demo: From: <sip:chetan1024278092159007252@phone.plivo.com>;tag=DN90LpdPf
 I/Linphone_demo: To: sip:chetan1024278092159007252@phone.plivo.com;tag=378adae1ddc71986618d85886edb3f8b.7ad3
 I/Linphone_demo: CSeq: 21 REGISTER
I/Linphone_demo: Call-ID: JNFBSfGgnv
I/Linphone_demo: Contact: <sip:chetan1024278092159007252@203.109.112.38:38091;transport=udp>;expires=3600;+sip.instance="<urn:uuid:2e223400-2669-00a4-b1d6-edb1003420e1>"
 I/Linphone_demo: Server: Plivo
I/Linphone_demo: Content-Length: 0
I/Linphone_demo: channel [0x710c5e68c0] [507] bytes parsed
I/Linphone_demo: Found transaction matching response.
I/Linphone_demo: Changing [client] [REGISTER] transaction [0x710c1e0600], from state [TRYING] to [COMPLETED]
 I/Linphone_demo: Refresher [0x710c5dd3c0]:  has no contact for request [0x710c146700].
 I/Linphone_demo: Refresher[0x710c5dd3c0]: scheduling next timer in 3240000 ms for purpose [normal refresh]
I/Linphone_demo: Register refresher [200] reason [OK] for proxy [sip:phone.plivo.com]
I/Linphone_demo: Proxy config [0x7128243c00] for identity [sip:chetan1024278092159007252@phone.plivo.com] moving from state [LinphoneRegistrationProgress] to [LinphoneRegistrationOk] on core [0x711d877400]
 I/Linphone_demo: Updating friends for identity [sip:chetan1024278092159007252@phone.plivo.com] on core [0x711d877400]
E/Successful: Ok
I/Timeline: Timeline: Activity_launch_request time:117519537 intent:Intent { cmp=com.example.linphone_demo/.CallActivity


Here is log for unsuccessful login SIP Point

I/Linphone_demo: linphone_proxy_config_is_server_config_changed : 0
 I/Linphone_demo: Publish params have changed on proxy config [0x710bf6fc00]
 I/Linphone_demo: LinphoneProxyConfig [0x710bf6fc00] about to register (LinphoneCore version: 3.12.0-3403-g09d1da062)
I/Linphone_demo: get_jni_env(): thread successfuly attached
 I/Linphone_demo: bellesip_wake_lock_acquire(): Android wake lock [belle-sip transaction(0x710bfd4900)] acquired [ref=0x3e96]
 I/Linphone_demo: transaction [0x710bfd4900]: starting transaction background task with id=[3e96].
 I/Linphone_demo: belle_sip_client_transaction_send_request(): waiting channel to be ready
 I/Linphone_demo: bellesip_wake_lock_acquire(): Android wake lock [belle-sip send channel] acquired [ref=0x3eba]
 I/Linphone_demo: channel [0x710bfd7240]: starting send background task with id=[3eba].
 I/Linphone_demo: channel [0x710bfd7240]: starting resolution of phone.plivo.com
 I/Linphone_demo: channel 0x710bfd7240: state RES_IN_PROGRESS
 I/Linphone_demo: transaction [0x710bfd4900] channel state changed to [RES_IN_PROGRESS]
 I/Linphone_demo: resconf using application supplied dns server list.
 I/Linphone_demo: Resolver is using DNS server(s):
 I/Linphone_demo: 	192.168.1.1
 I/Linphone_demo: resolver_process_data dns_res_check() in progress
 I/Linphone_demo: DNS resolution awaiting response, queued to main loop
 I/Linphone_demo: Neither Expires header nor corresponding Contact header found, checking from original request
 I/Linphone_demo: Refresher [0x710bfd46c0] takes ownership of transaction [0x710bfd4900]
 I/Linphone_demo: Proxy config [0x710bf6fc00] for identity [sip:chuserranjeetchouhan37630431974711516685766@phone.plivo.com] moving from state [LinphoneRegistrationNone] to [LinphoneRegistrationProgress] on core [0x711d877400]
 I/Linphone_demo: Linphone core [0x711d877400] notified [registration_state_changed]
 I/Linphone_demo: SRV _sip._udp.phone.plivo.com resolved to [target:phone.plivo.com. port:5060 prio:0 weight:5]
 I/Linphone_demo: Starting A/AAAA query for srv result [phone.plivo.com]
 I/Linphone_demo: resconf using application supplied dns server list.
 I/Linphone_demo: Resolver is using DNS server(s):
 I/Linphone_demo: 	192.168.1.1
 I/Linphone_demo: resolver_process_data dns_res_check() in progress
 I/Linphone_demo: DNS resolution awaiting response, queued to main loop
 I/Linphone_demo: resconf using application supplied dns server list.
 I/Linphone_demo: Resolver is using DNS server(s):
 I/Linphone_demo: 	192.168.1.1
 I/Linphone_demo: resolver_process_data dns_res_check() in progress
 I/Linphone_demo: DNS resolution awaiting response, queued to main loop
 I/Linphone_demo: phone.plivo.com resolved to 52.9.254.127
 I/Linphone_demo: phone.plivo.com resolved to 52.9.254.123
 I/Linphone_demo: A query finished for srv result [phone.plivo.com]
 I/Linphone_demo: All A/AAAA results for combined resolution have arrived.
 I/Linphone_demo: channel[0x710bfd7240]: current peer hostname is [phone.plivo.com].
 I/Linphone_demo: channel 0x710bfd7240: state RES_DONE
 I/Linphone_demo: transaction [0x710bfd4900] channel state changed to [RES_DONE]
 I/Linphone_demo: channel 0x710bfd7240: state CONNECTING
 I/Linphone_demo: transaction [0x710bfd4900] channel state changed to [CONNECTING]
 I/Linphone_demo: Trying to connect to [UDP://::ffff:52.9.254.127:5060]
 I/Linphone_demo: Channel has local address 192.168.1.124:38630
 I/Linphone_demo: channel 0x710bfd7240: state READY
 I/Linphone_demo: transaction [0x710bfd4900] channel state changed to [READY]
 I/Linphone_demo: Changing [client] [REGISTER] transaction [0x710bfd4900], from state [INIT] to [TRYING]
 I/Linphone_demo: channel [0x710bfd7240]: message sent to [UDP://phone.plivo.com:5060], size: [663] bytes
 I/Linphone_demo: REGISTER sip:phone.plivo.com SIP/2.0
 I/Linphone_demo: Via: SIP/2.0/UDP 192.168.1.124:38630;branch=z9hG4bK.GBkN7QKiA;rport
I/Linphone_demo: From: <sip:chuserranjeetchouhan37630431974711516685766@phone.plivo.com>;tag=IjL3O2VcR
 I/Linphone_demo: To: sip:chuserranjeetchouhan37630431974711516685766@phone.plivo.com
 I/Linphone_demo: CSeq: 20 REGISTER
 I/Linphone_demo: Call-ID: RlnrEIQQbS
 I/Linphone_demo: Max-Forwards: 70
I/Linphone_demo: Supported: replaces, outbound, gruu
 I/Linphone_demo: Accept: application/sdp
I/Linphone_demo: Accept: text/plain
 I/Linphone_demo: Accept: application/vnd.gsma.rcs-ft-http+xml
I/Linphone_demo: Contact: <sip:chuserranjeetchouhan37630431974711516685766@192.168.1.124:38630;transport=udp>;+sip.instance="<urn:uuid:2e223400-2669-00a4-b1d6-edb1003420e1>"
I/Linphone_demo: Expires: 3600
 I/Linphone_demo: User-Agent: Unknown (belle-sip/1.6.3)
 I/Linphone_demo: channel [0x710bfd7240]: ending send background task with id=[3eba].
2019-05-21 10:14:58.039 30142-30142/com.example.linphone_demo I/Linphone_demo: bellesip_wake_lock_release(): Android wake lock released [ref=0x3eba]
 I/Linphone_demo: nict_on_timer_E: sending retransmission
 I/Linphone_demo: channel [0x710bfd7240]: message sent to [UDP://phone.plivo.com:5060], size: [663] bytes
 I/Linphone_demo: REGISTER sip:phone.plivo.com SIP/2.0
 I/Linphone_demo: Via: SIP/2.0/UDP 192.168.1.124:38630;branch=z9hG4bK.GBkN7QKiA;rport
 I/Linphone_demo: From: <sip:chuserranjeetchouhan37630431974711516685766@phone.plivo.com>;tag=IjL3O2VcR
 I/Linphone_demo: To: sip:chuserranjeetchouhan37630431974711516685766@phone.plivo.com
 I/Linphone_demo: CSeq: 20 REGISTER
 I/Linphone_demo: Call-ID: RlnrEIQQbS
I/Linphone_demo: Max-Forwards: 70
I/Linphone_demo: Supported: replaces, outbound, gruu
I/Linphone_demo: Accept: application/sdp
 I/Linphone_demo: Accept: text/plain
 I/Linphone_demo: Accept: application/vnd.gsma.rcs-ft-http+xml
I/Linphone_demo: Contact: <sip:chuserranjeetchouhan37630431974711516685766@192.168.1.124:38630;transport=udp>;+sip.instance="<urn:uuid:2e223400-2669-00a4-b1d6-edb1003420e1>"
I/Linphone_demo: Expires: 3600
 I/Linphone_demo: User-Agent: Unknown (belle-sip/1.6.3)
I/Linphone_demo: bellesip_wake_lock_acquire(): Android wake lock [belle-sip recv channel] acquired [ref=0x3ec2]
I/Linphone_demo: channel [0x710bfd7240]: starting recv background task with id=[3ec2].
/Linphone_demo: channel [0x710bfd7240]: received [491] new bytes from [UDP://phone.plivo.com:5060]:
 I/Linphone_demo: SIP/2.0 401 Unauthorized
 I/Linphone_demo: Via: SIP/2.0/UDP 192.168.1.124:38630;branch=z9hG4bK.GBkN7QKiA;rport=38630;received=203.109.112.38
I/Linphone_demo: From: <sip:chuserranjeetchouhan37630431974711516685766@phone.plivo.com>;tag=IjL3O2VcR
I/Linphone_demo: To: sip:chuserranjeetchouhan37630431974711516685766@phone.plivo.com;tag=378adae1ddc71986618d85886edb3f8b.3e16
I/Linphone_demo: CSeq: 20 REGISTER
 I/Linphone_demo: Call-ID: RlnrEIQQbS
 I/Linphone_demo: WWW-Authenticate: Digest realm="phone.plivo.com", nonce="XOODd1zjgks+OX1l6/NBbTYL41KsR0p7"
 I/Linphone_demo: Server: Plivo
 I/Linphone_demo: Content-Length: 0
 I/Linphone_demo: channel [0x710bfd7240] [491] bytes parsed
 I/Linphone_demo: channel [0x710bfd7240]: discovered public ip and port are [203.109.112.38:38630]
 I/Linphone_demo: Found transaction matching response.
 I/Linphone_demo: Changing [client] [REGISTER] transaction [0x710bfd4900], from state [TRYING] to [COMPLETED]
I/Linphone_demo: linphone_core_find_auth_info(): returning auth info username=chuserranjeetchouhan37630431974711516685766, realm=
 I/Linphone_demo: Auth info found for [chuserranjeetchouhan37630431974711516685766] realm [phone.plivo.com]
I/Linphone_demo: bellesip_wake_lock_acquire(): Android wake lock [belle-sip transaction(0x710bfd3400)] acquired [ref=0x3ee2]
 I/Linphone_demo: transaction [0x710bfd3400]: starting transaction background task with id=[3ee2].
I/Linphone_demo: Changing [client] [REGISTER] transaction [0x710bfd3400], from state [INIT] to [TRYING]
I/Linphone_demo: channel [0x710bfd7240]: message sent to [UDP://phone.plivo.com:5060], size: [883] bytes
 I/Linphone_demo: REGISTER sip:phone.plivo.com SIP/2.0
I/Linphone_demo: Via: SIP/2.0/UDP 192.168.1.124:38630;branch=z9hG4bK.daeArheNZ;rport
 I/Linphone_demo: From: <sip:chuserranjeetchouhan37630431974711516685766@phone.plivo.com>;tag=IjL3O2VcR
 I/Linphone_demo: To: sip:chuserranjeetchouhan37630431974711516685766@phone.plivo.com
I/Linphone_demo: CSeq: 21 REGISTER
I/Linphone_demo: Call-ID: RlnrEIQQbS
I/Linphone_demo: Max-Forwards: 70
I/Linphone_demo: Supported: replaces, outbound, gruu
I/Linphone_demo: Accept: application/sdp
 I/Linphone_demo: Accept: text/plain
 I/Linphone_demo: Accept: application/vnd.gsma.rcs-ft-http+xml
 I/Linphone_demo: Contact: <sip:chuserranjeetchouhan37630431974711516685766@203.109.112.38:38630;transport=udp>;+sip.instance="<urn:uuid:2e223400-2669-00a4-b1d6-edb1003420e1>"
I/Linphone_demo: Expires: 3600
I/Linphone_demo: User-Agent: Unknown (belle-sip/1.6.3)
 I/Linphone_demo: Authorization:  Digest realm="phone.plivo.com", nonce="XOODd1zjgks+OX1l6/NBbTYL41KsR0p7", username="chuserranjeetchouhan37630431974711516685766",  uri="sip:phone.plivo.com", response="ff109e5197b1125eb62f3e6c05138352"
 I/Linphone_demo: channel [0x710bfd7240]: ending recv background task with id=[3ec2].
I/Linphone_demo: bellesip_wake_lock_release(): Android wake lock released [ref=0x3ec2]
 I/Linphone_demo: bellesip_wake_lock_acquire(): Android wake lock [belle-sip recv channel] acquired [ref=0x3efa]
 I/Linphone_demo: channel [0x710bfd7240]: starting recv background task with id=[3efa].
I/Linphone_demo: channel [0x710bfd7240]: received [491] new bytes from [UDP://phone.plivo.com:5060]:
 I/Linphone_demo: SIP/2.0 401 Unauthorized
 I/Linphone_demo: Via: SIP/2.0/UDP 192.168.1.124:38630;branch=z9hG4bK.GBkN7QKiA;rport=38630;received=203.109.112.38
I/Linphone_demo: From: <sip:chuserranjeetchouhan37630431974711516685766@phone.plivo.com>;tag=IjL3O2VcR
 I/Linphone_demo: To: sip:chuserranjeetchouhan37630431974711516685766@phone.plivo.com;tag=378adae1ddc71986618d85886edb3f8b.3e16
 I/Linphone_demo: CSeq: 20 REGISTER
 I/Linphone_demo: Call-ID: RlnrEIQQbS
I/Linphone_demo: WWW-Authenticate: Digest realm="phone.plivo.com", nonce="XOODd1zjgks+OX1l6/NBbTYL41KsR0p7"
 I/Linphone_demo: Server: Plivo
I/Linphone_demo: Content-Length: 0
 I/Linphone_demo: channel [0x710bfd7240] [491] bytes parsed
 I/Linphone_demo: Found transaction matching response.
I/Linphone_demo: channel [0x710bfd7240]: ending recv background task with id=[3efa].
 I/Linphone_demo: bellesip_wake_lock_release(): Android wake lock released [ref=0x3efa]
 I/Linphone_demo: bellesip_wake_lock_acquire(): Android wake lock [belle-sip recv channel] acquired [ref=0x3f0a]
 I/Linphone_demo: channel [0x710bfd7240]: starting recv background task with id=[3f0a].
I/Linphone_demo: channel [0x710bfd7240]: received [491] new bytes from [UDP://phone.plivo.com:5060]:
I/Linphone_demo: SIP/2.0 401 Unauthorized
 I/Linphone_demo: Via: SIP/2.0/UDP 192.168.1.124:38630;branch=z9hG4bK.daeArheNZ;rport=38630;received=203.109.112.38
I/Linphone_demo: From: <sip:chuserranjeetchouhan37630431974711516685766@phone.plivo.com>;tag=IjL3O2VcR
I/Linphone_demo: To: sip:chuserranjeetchouhan37630431974711516685766@phone.plivo.com;tag=378adae1ddc71986618d85886edb3f8b.bf64
 I/Linphone_demo: CSeq: 21 REGISTER
 I/Linphone_demo: Call-ID: RlnrEIQQbS
 I/Linphone_demo: WWW-Authenticate: Digest realm="phone.plivo.com", nonce="XOODd1zjgks+OX1l6/NBbTYL41KsR0p7"
 I/Linphone_demo: Server: Plivo
 I/Linphone_demo: Content-Length: 0
 I/Linphone_demo: Found transaction matching response.
I/Linphone_demo: Changing [client] [REGISTER] transaction [0x710bfd3400], from state [TRYING] to [COMPLETED]
**W/Linphone_demo: Authentication is failing constantly, will retry later**
 I/Linphone_demo: Refresher[0x710bfd46c0]: scheduling next timer in 60000 ms for purpose [retry]
I/Linphone_demo: Register refresher [401] reason [Unauthorized] for proxy [sip:phone.plivo.com]
**I/Linphone_demo: Proxy config [0x710bf6fc00] for identity [sip:chuserranjeetchouhan37630431974711516685766@phone.plivo.com] moving from state [LinphoneRegistrationProgress] to [LinphoneRegistrationFailed] on core [0x711d877400]
 E/failed: Failed**                   //onRegistrationStateChanged Listener
 I/Linphone_demo: Linphone core [0x711d877400] notified [registration_state_changed]

**Comment by Viish** [comment]
Indeed in the logs your username is lowercase.
Which version of the app/SDK are you using ?

**Comment by im-ranu** [comment]
We're using version 4.2+
here it is mentioned
linphone-sdk-android-4.2-30-g82c5b01.aar

**Comment by Viish** [comment]
We don't change the case in the library, so I the problem is in your code.
How do you create the proxy config and auth info ?

**Comment by im-ranu** [comment]
mAccountCreator.setUsername(mUsername.getText().toString());
 mAccountCreator.setTransport(TransportType.Tls);
 mAccountCreator.setPassword(mPassword.getText().toString());
 mAccountCreator.setDomain("phone.plivo.com");

  ProxyConfig proxyConfig = mAccountCreator.createProxyConfig();

  LinphoneService.getCore().setDefaultProxyConfig(proxyConfig);

**Comment by Viish** [comment]
Ok issue is in our lib, just fixed it.
Will be available in tomorrow's AAR build.
