### ISSUE TITLE
Registration Issue

### ISSUE THREAD

**Issue by chandrasekhar109** [BelledonneCommunications/linphone-android#639]
Hi Team,
I have an issue while registering with sip details . Registration state always in progressing state.
I did n't get any response from server.same sip details are worked for ios platform.If i tried with another sip details in android phone login get success. i am using linphone 3.3.2 version.
Please tell me the issue and solution for this.

Thanks in advance

**Comment by Viish** [comment]
linphone 3.3.2 is way too old. Update to 4.1 and reopen a ticket with logs if the issue persists.
