### ISSUE TITLE
Auth userid does not take effect and disappears

### ISSUE THREAD

**Issue by juha-h** [BelledonneCommunications/linphone-android#64]
User's SIP URI is sip:+4487333456@example.com and authentication username in realm example.com is test.  I configured that SIP account in Linphone like this:

Username: +4487333456
Auth userid: test
Password: <password>
Domain: example.com
Display name: Test

Looks like Auth userid had no effect, since in REGISTER request username field of
Authorization header was +4487333456, not test.

I then restarted Linphone and Auth userid had become empty (as was Display name).

This test was made  using latest Linphone 3.2.7.

**Comment by etamme** [comment]
+1 on this - I've tested with a script to calculate the response for a digest auth and when auth user is different than user linphone fails to calculate the correct response.  When the user and auth user are the same the digest response is calculated correctly.

**Comment by DatBewar** [comment]
Hi, i made an another fix for this 31dd258e8c0ef2165c9f7ed86af7850e52a2c3cd
But when you forgot to add Auth userid, after adding this on Account preference, you need to re-enter your password.

**Comment by juha-h** [comment]
Erwan Croze writes:

> Hi, i made an another fix for this 31dd258e8c0ef2165c9f7ed86af7850e52a2c3cd
> But when you forgot to add Auth userid, after adding this on Account
> preference, you need to re-enter your password.

Thanks.  I'll try when new version of Android Linphone is available in
Play store.

-- Juha

**Comment by etamme** [comment]
i tried the latest nightly, and now it just closes after trying to edit a sip account - not sure if thats just a buggy nightly, or if the changes to the account fragments are causing issues in creating/editing the account.
