### ISSUE TITLE
4.2 SDK can be found in our releases maven repository : http://linphone.org/releases/maven_repository/org/linphone/linphone-sdk-android/

### ISSUE THREAD

**Issue by marksaitis** [BelledonneCommunications/linphone-android#640]
4.2 SDK can be found in our releases maven repository : http://linphone.org/releases/maven_repository/org/linphone/linphone-sdk-android/
4.2+ SDK can be found in our snapshots maven : http://linphone.org/snapshots/maven_repository/org/linphone/linphone-sdk-android/

_Originally posted by @Viish in https://github.com/BelledonneCommunications/linphone-android/issues/609#issuecomment-489520245_
---------------------
sdk 4.1, 4.2 and latest do not compile on stable ubuntu. It complains about not finding multiple .so files:
libbc++_shared.so, needed by ../src/libmediastreamer.so, not found (try using -rpath or -rpath-link)

**Comment by marksaitis** [comment]
Trying to build my aar. Tried ndk 18 and 19. 4.1 and latest master branch complains about 4 .so files and after them errors with reference issues and fails. I built anything below 4.1 before, but this new stuff is a no go. I been redoenloading, cleaning, trying from scratch... nothing.

**Comment by licaon-kter** [comment]
@marksaitis It should build fine as it builds on Debian Stretch for F-Droid.

What version is Ubuntu Stable exactly?

> not finding multiple .so files: libbc++_shared.so

How did you install the Android tools?

**Comment by marksaitis** [comment]
Ubuntu 18.04

Android - I have ndk in the PATH. Tried 18 and 19.
Android sdk - just downloaded it from official source and extracted. Then set env var for it.

**Comment by marksaitis** [comment]
ldd in ndk complains that it cant find these 4 files. Let me get full output in few minutes and paste here

**Comment by marksaitis** [comment]
So I just cloned latest sdk and tried to build it with ndk18. Below is the result. So it complains about 1 file. I think Another branch complained re 4 files or I had few extra options on during ccmake config. Will now again build 4.2 and 4.1 and post here if different issues exists.

2nd thing - there was an issue with doze related linphone crash, a leak and I know it was solved in 4.1. Is it also solved in latest branch?

----cut below----
[ 62%] Forcing build for 'EP_ms2'
[ 63%] Performing build step for 'EP_ms2'
[  0%] Built target ms2-yuv2rgb-fs-header
[  0%] Built target ms2-basedescs-header
[  0%] Built target ms2-git-version
[  0%] Built target ms2-yuv2rgb-vs-header
[  0%] Built target ms2-voipdescs-header
[ 87%] Built target mediastreamer
[ 87%] Linking C executable msaudiocmp
/home/ladmin/data/android-ndk-r18b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libc++_shared.so, needed by ../src/libmediastreamer.so, not found (try using -rpath or -rpath-link)
../src/libmediastreamer.so: undefined reference to `std::logic_error::logic_error(char const*)'
../src/libmediastreamer.so: undefined reference to `std::__ndk1::ctype<char>::id'
------after that undefined ref errors----

**Comment by marksaitis** [comment]
Above issue was for 4.2 and master. Below is for 4.1. Just reproduced.

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type PluginResolutionStrategyInternal using BuildScopeServices.createPluginResolutionStrategy().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
CMake Error at /home/ladmin/data/f-190517/linphone-sdk_41/cmake/Android/GradleClean.cmake:34 (message):
  Gradle clean failed


make[2]: *** [CMakeFiles/gradle-clean.dir/build.make:57: CMakeFiles/gradle-clean] Error 1
make[1]: *** [CMakeFiles/Makefile2:110: CMakeFiles/gradle-clean.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by Viish** [comment]
Can you check you do have the libc++ somewhere in your NDK ?
It should be in
toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/libc++_shared.so
or in
sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++_shared.so

**Comment by marksaitis** [comment]
ladmin@linux-f1:~/data/android-ndk-r18b$ find . -name libc++_shared.so
./sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++_shared.so
./sources/cxx-stl/llvm-libc++/libs/x86_64/libc++_shared.so
./sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libc++_shared.so
./sources/cxx-stl/llvm-libc++/libs/x86/libc++_shared.so
ladmin@linux-f1:~/data/android-ndk-r18b$ cd ../android-ndk-r19
android-ndk-r19b/ android-ndk-r19c/ 
ladmin@linux-f1:~/data/android-ndk-r18b$ cd ../android-ndk-r19c/
ladmin@linux-f1:~/data/android-ndk-r19c$ find . -name libc++_shared.so
./sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++_shared.so
./sources/cxx-stl/llvm-libc++/libs/x86_64/libc++_shared.so
./sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libc++_shared.so
./sources/cxx-stl/llvm-libc++/libs/x86/libc++_shared.so
./toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/libc++_shared.so
./toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/i686-linux-android/libc++_shared.so
./toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/x86_64-linux-android/libc++_shared.so
./toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/libc++_shared.so
-----------------

Do I need to add tools or platform tools to PATH? For now I only added the right ndk to path and set ANDROID_HOME var. Android sdk is up to date, via SDK manager. I got API 25 and 28. sdk build-tools is at it's latest revision. sdk platform tools and tools are at their latest. sdk and ndk dirs have been chowned to ensure no permission issue.

**Comment by Viish** [comment]
Here's my setup for reference:
```
export NDK_VERSION=17                                                                                                                                                                                                                         
export PATH=~/Tools/android-studio/bin/:~/Tools/android-ndk-r$NDK_VERSION:~/Tools/android-sdk/platform-tools:~/Tools/android-sdk/tools:$PATH                                              
export ANDROID_HOME=~/Tools/android-sdk
export ANDROID_NDK_HOME=~/Tools/android-ndk-r$NDK_VERSION/
```

**Comment by marksaitis** [comment]
I took your example and customised it to fit my environment. I use these vars now. Downloaded and using ndk17. Also I got 401 branch. Seems to compile - before it didn't. Had a linker issue. 

Now for 4.2 branch, still a fail:
`[ 87%] Linking C executable msaudiocmp
/home/ladmin/data/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libc++_shared.so, needed by ../src/libmediastreamer.so, not found (try using -rpath or -rpath-link)
../src/libmediastreamer.so: undefined reference to `std::logic_error::logic_error(char const*)'
../src/libmediastreamer.so: undefined reference to `std::__ndk1::ctype<char>::id'
---
---
---
../src/libmediastreamer.so: undefined reference to `typeinfo for std::invalid_argument'
../src/libmediastreamer.so: undefined reference to `vtable for __cxxabiv1::__vmi_class_type_info'
../src/libmediastreamer.so: undefined reference to `__cxa_free_exception'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[8]: *** [tools/CMakeFiles/msaudiocmp.dir/build.make:87: tools/msaudiocmp] Error 1
make[7]: *** [CMakeFiles/Makefile2:369: tools/CMakeFiles/msaudiocmp.dir/all] Error 2
make[6]: *** [Makefile:152: all] Error 2
make[5]: *** [CMakeFiles/EP_ms2.dir/build.make:126: /home/ladmin/data/f-190517/linphone-sdk_42/build/WORK/android-arm64/Stamp/EP_ms2/EP_ms2-build] Error 2
make[4]: *** [CMakeFiles/Makefile2:122: CMakeFiles/EP_ms2.dir/all] Error 2
make[3]: *** [Makefile:84: all] Error 2
make[2]: *** [CMakeFiles/android-arm64.dir/build.make:113: android-arm64-prefix/src/android-arm64-stamp/android-arm64-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/android-arm64.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
`

**Comment by Viish** [comment]
Can you show me how you compile ?

**Comment by marksaitis** [comment]
---To ensure env
export NDK_VERSION=17c                                                                                                                                                                                                                         
export PATH=~/data/android-studio/bin/:~/data/android-ndk-r$NDK_VERSION:~/data/Android/Sdk/platform-tools:~/data/Android/Sdk/tools:$PATH                                              
export ANDROID_HOME=/home/ladmin/data/Android/Sdk
export ANDROID_NDK_HOME=~/data/android-ndk-r$NDK_VERSION/

---I del build folder
rm -rf build

---Then I make it again, go inside and start building
mkdir build && cd build
cmake ..
ccmake .
# And I ensure here the target is Android. Do c and g
cmake --build . -j 4

---I double checked my env vars to be correct

**Comment by marksaitis** [comment]
Could it be that I am missing some emulations? I so a while ago in some other build issue of sdk. My supported emulations below.
```
GNU ld (GNU Binutils for Ubuntu) 2.31.1
  Supported emulations:
   elf_x86_64
   elf32_x86_64
   elf_i386
   elf_iamcu
   elf_l1om
   elf_k1om
   i386pep
   i386pe
```

**Comment by freeeyes** [comment]
@marksaitis  My problem is the same as yours.
I try to set （I guess so file path is must set LD_LIBARY_PATH）

LD_LIBARY_PATH=/root/Tools/linphone-sdk/build/WORK/android-arm64/Build/:/root/Tools/android-ndk-r19c/platforms/android-26/arch-arm:$LD_LIBRARY_PATH
export LD_LIBARY_PATH

-- build
mkdir build && cd build
cmake .. -DLINPHONESDK_PLATFORM=Android
cd ../
vi local.properties
sdk.dir=/root/Tools/android-sdk-linux/
ndk.dir=/root/Tools/android-ndk-r19c/
make

--build log
`[ 61%] Forcing build for 'EP_ms2'
[ 61%] Performing build step for 'EP_ms2'
[  0%] Built target ms2-yuv2rgb-vs-header
[  0%] Built target ms2-basedescs-header
[  0%] Built target ms2-git-version
[  0%] Built target ms2-voipdescs-header
[  0%] Built target ms2-yuv2rgb-fs-header
[ 87%] Built target mediastreamer
[ 88%] Linking C executable bench
/root/Tools/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libEGL.so, needed by ../src/libmediastreamer.so, not found (try using -rpath or -rpath-link)
/root/Tools/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libGLESv2.so, needed by ../src/libmediastreamer.so, not found (try using -rpath or -rpath-link)
/root/Tools/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libandroid.so, needed by ../src/libmediastreamer.so, not found (try using -rpath or -rpath-link)
/root/Tools/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libc++_shared.so, needed by ../src/libmediastreamer.so, not found (try using -rpath or -rpath-link)
../src/libmediastreamer.so: undefined reference to `std::logic_error::logic_error(char const*)'
../src/libmediastreamer.so: undefined reference to `glActiveTexture'
../src/libmediastreamer.so: undefined reference to `glGetProgramInfoLog'`

**Comment by marksaitis** [comment]
@freeeyes I can see your's can't find 4 libraries. I so the same happening to me, exactly the same. I think it was after I checked few more options in config. But yes, seems like same issue. What system you are using to build this? @Viish were you able to reproduce? Or I need to use debian to build this? I am unable to build SDK for this same issue

**Comment by freeeyes** [comment]
@marksaitis  
my Linux version
CentOS Linux release 7.4.1708 (Core)

**Comment by Viish** [comment]
Can you simply try:
```
mkdir build
cd build
cmake .. -DLINPHONESDK_PLATFORM=Android
make -j4
```

**Comment by freeeyes** [comment]
@Viish 
thanks

make -j4

--build log
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/lib/pkgconfig/belle-sip.pc
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/share/BelleSIP/cmake/BelleSIPTargets.cmake
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/share/BelleSIP/cmake/BelleSIPTargets-relwithdebinfo.cmake
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/share/BelleSIP/cmake/BelleSIPConfig.cmake
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/share/BelleSIP/cmake/BelleSIPConfigVersion.cmake
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/auth-helper.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/belle-sdp.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/belle-sip.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/bodyhandler.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/defs.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/dialog.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/dict.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/generic-uri.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/headers.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/http-listener.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/http-message.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/http-provider.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/list.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/listener.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/listeningpoint.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/mainloop.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/mdns_register.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/message.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/object.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/object++.hh
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/parameters.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/provider.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/refresher.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/resolver.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/sipstack.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/sip-uri.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/transaction.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/types.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/utils.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/include/belle-sip/wakelock.h
-- Installing: /root/Tools/linphone-sdk/build/linphone-sdk/android-armv7/lib/libbellesip.a
[ 81%] Completed 'EP_bellesip'
[ 81%] Built target EP_bellesip
make[3]: *** [all] Error 2
make[2]: *** [android-armv7-prefix/src/android-armv7-stamp/android-armv7-build] Error 2
make[1]: *** [CMakeFiles/android-armv7.dir/all] Error 2
make: *** [all] Error 2

**Comment by Viish** [comment]
I don't see the error, can you attach it ?
Also, which version of cmake are you using ?

**Comment by freeeyes** [comment]
@Viish 
I will recompile it the way you do it.

[root@iz8vb2jmt426v4a0ejuw40z build]# cmake --version
cmake version 3.14.4

--build 
mkdir build && cd build
cmake .. -DLINPHONESDK_PLATFORM=Android
vi local.properties
sdk.dir=/root/Tools/android-sdk-linux/
ndk.dir=/root/Tools/android-ndk-r19c/
make -j4

--build log
Scanning dependencies of target mkvstream
Scanning dependencies of target mtudiscover
/root/Tools/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/21/crtbegin_dynamic.o:crtbegin.c:function _start_main: error: undefined reference to 'main'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[8]: *** [tools/mediastream] Error 1
make[7]: *** [tools/CMakeFiles/mediastream.dir/all] Error 2
make[7]: *** Waiting for unfinished jobs....
[ 91%] Building C object tools/CMakeFiles/mtudiscover.dir/mtudiscover.c.o
[ 92%] Building C object tools/CMakeFiles/mkvstream.dir/mkvstream.c.o
[ 93%] Linking C executable mtudiscover
[ 94%] Linking C executable mkvstream
[ 94%] Built target mtudiscover
[ 94%] Built target mkvstream
make[6]: *** [all] Error 2
make[5]: *** [/root/Tools/linphone-sdk/build/WORK/android-armv7/Stamp/EP_ms2/EP_ms2-build] Error 2
make[4]: *** [CMakeFiles/EP_ms2.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
-- Detecting CXX compile features - done
-- Check for working C compiler: /root/Tools/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
-- Check for working C compiler: /root/Tools/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:48 (project):
  No CMAKE_Java_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "JAVA_COMPILER" or the CMake cache entry CMAKE_Java_COMPILER to
  the full path to the compiler, or to the compiler name if it is in the
  PATH.


-- Configuring incomplete, errors occurred!
See also "/root/Tools/linphone-sdk/build/WORK/android-armv7/Build/lime/CMakeFiles/CMakeOutput.log".
make[5]: *** [/root/Tools/linphone-sdk/build/WORK/android-armv7/Stamp/EP_lime/EP_lime-configure] Error 1
make[4]: *** [CMakeFiles/EP_lime.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [android-armv7-prefix/src/android-armv7-stamp/android-armv7-build] Error 2
make[1]: *** [CMakeFiles/android-armv7.dir/all] Error 2
make: *** [all] Error 2

**Comment by marksaitis** [comment]
@Viish 

> Can you simply try:
> 
> ```
> mkdir build
> cd build
> cmake .. -DLINPHONESDK_PLATFORM=Android
> make -j4
> ```

It has worked like this! Hooray! Why is that? And what if I want to specify some options via ccmake . instead? As thats the only part which is different.

**Comment by Viish** [comment]
You can apply your options using ccmake (or cmake-gui or give them directly to cmake .. using -D) after the first cmake call and before the make. But it is important that the first cmake call contains the platform target.

**Comment by zhanglj0507** [comment]
linphone will open camera when startup app or change network, please help, thx.
