### ISSUE TITLE
How to remove Toast on CoreListenerStub()?

### ISSUE THREAD

**Issue by Vivektilva** [BelledonneCommunications/linphone-android#641]
When we make any outgoing calls we are getting events in listener CoreListenerStub in method onCallStateChanged That is perfect but at that time we are also getting Toast messages of every state .

Is there any way to remove those Toast ??

**Comment by Viish** [comment]
I guess you are using the sample.
Remove the 
Toast.makeText(LinphoneService.this, message, Toast.LENGTH_SHORT).show();
line in sample/app/src/main/java/org/linphone/sample/LinphoneService.java, in the
@Override
            public void onCallStateChanged(Core core, Call call, Call.State state, String message) {
