### ISSUE TITLE
Address Book - Contacts no longer read by Linphone

### ISSUE THREAD

**Issue by stef204** [BelledonneCommunications/linphone-android#642]
I updated to Linphone Android 4.1 (4124), Linphone SDK 4.2 (tags 4.2^0) a few days ago (from F-Droid) and since then, only a few contacts from my address book show up in Linphone (most contacts are no longer shown where previous Linphone Android version showed all contacts and one could dial directly from Linphone.)
Called ID no longer works when receiving calls from contacts in Android address book (which is expected if the contacts are not shown in Linphone.)
Android 7.1.2.

**Comment by Viish** [comment]
Could you attach logs please ?

**Comment by stef204** [comment]
@Viish 
Thanks for quick response.
I've got the log but it's quite large 61528 lines for 5.8MB size file.
I would need to ONLY send you relevant parts or anonymize/redact the file.
What do I look for, to only get relevant parts?

Note: I do see a bunch of these but no idea if relevant:

` MESSAGE Refresher [0x6e64a1c0]:  has no contact for request [0x5e221300]`

**Comment by Viish** [comment]
@stef204 I'm looking for logs that start with "[Contacts Manager]" or "[Contact]",

**Comment by stef204** [comment]
@Viish  How's [this](https://paste.xinu.at/NfuU/)?
You have both when it worked March and when it doesn't (May).
Is this enough?  I can't seem to find much more than those sections.

**Comment by Viish** [comment]
No I'll need more logs from the device that doesn't work.
Also make sure you are using the latest version.

**Comment by stef204** [comment]
I am using the latest version from F-Droid: Linphone Android 4.1 (4124), Linphone SDK 4.2 (tags 4.2^0).

You need more logs: tell me exactly what you need.  I only have one log I obtained by enabling "Debug" and then "Send log".

I cannot really send you the whole file--it contains too much PII.

If you want the whole log, which seems to start in March 2019, I'll have to anonymize/redact the entire file, whichever portions containing PII.

In ny event, if I search through the file for "Contact" or "Contacts Manager", It seems that all I have is what I posted on the most recent link above.  You did see this new [link](https://paste.xinu.at/NfuU/), correct?

I do need this resolve as it is quite a regression from last version and almost a deal breaker for me.

What do you want me to do exactly?

**Comment by Viish** [comment]
Yes I did see your latest logs.
To reduce the size, you can clean the whole log file from your device in About page, restart the app to reproduce the issue and then capture new logs.

**Comment by stef204** [comment]
Can you give me a corporate email address so I can email the log to you?

**Comment by Viish** [comment]
You can send it linphone-android@belledonne-communications.com

**Comment by stef204** [comment]
Logs sent to email address.  Thanks.

**Comment by Viish** [comment]
I didn't received them. Can you send them again.
linphone-android@belledonne-communications.com

**Comment by Viish** [comment]
In your account settings, is the prefix field filled ?

**Comment by stef204** [comment]
No, but i have never inserted my prefix there,  that field has always been empty and until the last update, it has always worked.

incidentally, I have tried to insert the country code of the country of my SIP number (with a + sign, so for you in France it would be +33) but this has had no impact on the issue.

**Comment by Viish** [comment]
Do not insert the +, simply 33.

**Comment by stef204** [comment]
Already have tried that, as described above.  Nothing happens, no changes whatsoever.  Likely, the problem is unrelated--has to be a bug of some sort.

**Comment by stef204** [comment]
Any luck with this? Do you need more info from me?

**Comment by Viish** [comment]
We have found an issue in our library that may be the cause of your issue.
Are you using remote provisioning ?

**Comment by stef204** [comment]
Thanks for feedback.  NO, I am not using Remote Provisioning.

**Comment by Viish** [comment]
In the native contact app, do you have multiple accounts ?
In fact, do the 46 that appear share a common denominator that the others don't have ?

**Comment by stef204** [comment]
I believe I do have multiple account:

- Linphone
- OpenKeychain
- A messenger app

The 46 contacts do not appear to have anything different than the other contacts.

Basically, when I switched to this phone, I exported contacts I had to a vcf file (concatenated with all contacts) and imported this into Android's address book using the address book's own built-in function.  This was quite some time ago and created no problems whatsoever with any apps, including Linphone _previous_ versions.

I am not sure what the IN_VISIBLE_GROUP variable does; was not aware there could be different groups, etc.

**Comment by Viish** [comment]
As you said, you have contacts in some groups that still aren't in Linphone, so obviously the problem ins't being part of a group or not.
ContactsContract.Data.IN_VISIBLE_GROUP == 1 is simply used to not show in Linphone contacts you have hidden in the native contact app, that's all.

**Comment by stef204** [comment]
OK, please keep me posted and let me know if you need further info from me.

**Comment by Viish** [comment]
It would be helpful to have logs from your device running a master version of the app. Can you do that ?

**Comment by stef204** [comment]
I would have to 1) uninstall Linphone (F-Droid version) sue to signature.
Then compile master and install that.
I can do this, hopefully won't run into compiling errors.
I do want to keep the data so I guess it's:
`adb uninstall -k org.linphone`
Can you confirm?
Will master still use same data and cache is I use `-k` option as above?

**Comment by Viish** [comment]
Actually no.
If you build yourself a debug version from master branch, it's app it won't be the same, allowing you to have a stable release along with a dev version on the same device. :smile:

**Comment by Viish** [comment]
Otherwise you can use the APK at https://linphone.org/snapshots/android/linphone-android-debug-4.1-55-gfdfb66e1.apk, but in this case yes you would have to uninstall your current app first and data would be lost.

**Comment by stef204** [comment]
OK, so do not uninstall Linphone.
Just compile master and install that.
I'll have to go through the config again for the dev app.....
One question: after:
`./gradlew assembleDebug`
I don't get this:
`./gradlew installDebug`
What does this do exactly?
If I have the apk, I can just push it to device using `adb` and install from device or use `adb install nameofpackage`, incorrect?

**Comment by Viish** [comment]
./gradlew installDebug is the same as adb install <debugApk>

**Comment by stef204** [comment]
OK, compiling now....  Hoping for the best.  Stay tuned,

**Comment by Viish** [comment]
No you don't have to sign anything for a debug APK

**Comment by stef204** [comment]
Build successful and installed debug APK.
Linphone Android 4.1-56-g92c07011 (debug)
Linphone  SDK 4.2-33-g44c0e16 (master)

**Comment by Viish** [comment]
Ok I wasn't expecting anything else. However logs should me more verbose now. Can you attach them please ?

**Comment by stef204** [comment]
Sure; one quick question, logs are **not** sent directly to Linphone from the device, correct or incorrect? It requires manual intervention from me to download the file first, correct?

**Comment by Viish** [comment]
When you click "Upload logs" in the About page, it upload logs to our server and give you the link.
But without the link I can't have access to your logs.

**Comment by stef204** [comment]
OK, it's not great for privacy to have the logs un-redacted be uploaded on your server, url or not, the data is there, on your server, un-redacted.

Emailed you the log.

**Comment by Viish** [comment]
Thanks for the logs.
Indeed the problem comes from the cursor Android returns, it only contains 22 contacts.
I'll keep searching.

**Comment by stef204** [comment]
Thanks.  Let me know anything else I can do on my side.

**Comment by Viish** [comment]
Can you try by replacing IN_VISIBLE_GROUP by IN_DEFAULT_DIRECTORY in org.linphone.contacts.AsyncContactsLoader class line 85 please ?

**Comment by stef204** [comment]
yes, will do and recompile, install and resend logs.

**Comment by Viish** [comment]
Thanks. No need for logs if it fixes the issue though ;)

**Comment by stef204** [comment]
Nicely done!  Issue seems to be fixed.  All contacts are now shown in Linphone ;)
What now?

**Comment by Viish** [comment]
Great !
I've commited the change in master branch and release/4.1 as well, so next release will have it.
Thanks a lot for the bug report and the help fixing it.
