### ISSUE TITLE
when user is in video call if 1st user disabled video so screen will become black for  2nd user  so there is any callback in linphone to detect this scenario?

### ISSUE THREAD

**Issue by namanbansal161995** [BelledonneCommunications/linphone-android#643]
when user is in video call if 1st user disabled video so screen will become black for  2nd user  so there is any callback in linphone to detect this scenario

**Comment by Viish** [comment]
If a call participant removes video, you it should send a REINVITE and thus you should have the call state changed callback called with updatedByRemote state, and the new callParams shall reflect this change.

**Comment by namanbansal161995** [comment]
Thanks for replying, I am working on an app in which we have video disable or enable feature while in video call so when we disabled video it is not removing video it just making screen black

**Comment by Viish** [comment]
Then you have your answer: you can't have a callback for something purely UI you are doing in your app.
