### ISSUE TITLE
Not getting incoming calls

### ISSUE THREAD

**Issue by Vivektilva** [BelledonneCommunications/linphone-android#644]
I am using CoreListenerStub and in method onCallStateChanged i am getting state for every event of outgoing calls.

But in same method , if incoming call is there (not picked up yet) i am not getting any state in this method.

is there any other method or listener where i can get notified of get any state of incoming call ?

it would be very helpful if you provide some sample code for incoming call (like outgoing call) in Sample App.

**Comment by Viish** [comment]
Incoming calls works the same way. But maybe you receive it before the listener is set ?

**Comment by Vivektilva** [comment]
Listener is already set .

I made first an outgoing call and events were there for outgoing calls in listener and after that i made incoming call on that sip but no events for incoming calls in that same listener.

**Comment by Viish** [comment]
Are you sure you receive an Incoming call ?

**Comment by Vivektilva** [comment]
yes because at other end (from where i am making call) is ringing

**Comment by Vivektilva** [comment]
if it helps , will provide you logs for both outgoing and incoming calls . let me know if requires.

**Comment by Viish** [comment]
Yes please attach logs from linphone

**Comment by Vivektilva** [comment]
Both logs for outgoing call and incoming calls are attached 
first part is for outgoing call where i get proper events in listener and also received call at other end so outgoing call was successfully setup.

after that 12:42 i tried to make incoming call but no logs for that.
[Lp_logs.txt](https://github.com/BelledonneCommunications/linphone-android/files/3206086/Lp_logs.txt)

**Comment by Viish** [comment]
Hi,
From the logs I confirm you don't receive any call.
If you hear ringing on the other side maybe it's because you have another user-agent configured with the same account.
Also I strongly recommend you switching from UDP to TLS (or at least TCP), it will probably solve your incoming calls not being received issue.
You can create free accounts that supports TLS here: https://www.linphone.org/freesip/home

**Comment by Viish** [comment]
By the way, in sample app, incoming calls are automatically answered.

**Comment by Vivektilva** [comment]
in registration process I am already using TLS
mAccountCreator.setTransport(TransportType.Tls);

do i need to make change in this or any other changes ?

**Comment by Viish** [comment]
Actually there is an issue with the account creator not setting the transport in the library.
It has been fixed in linphone-sdk AAR version 4.2-33 (currently building, will be available soon)

**Comment by Vivektilva** [comment]
okay thanks.

**Comment by Viish** [comment]
https://linphone.org/snapshots/maven_repository/org/linphone/linphone-sdk-android/4.2-33-g44c0e16/

**Comment by ddavud-git** [comment]
> Incoming calls works the same way. But maybe you receive it before the listener is set ?
Hello I receive the incoming call messages before the listener is set what can i do for getting these messages ?

**Comment by Jtobyy** [comment]
Please Inbound calls  do not working when I use Linphone but works on Eyebeam.
