### ISSUE TITLE
how to set proxy?

### ISSUE THREAD

**Issue by mohtasham1988** [BelledonneCommunications/linphone-android#646]
Hi
I want to use a proxy for call and video.
 how can I set a proxy in linphon code 
tnk

**Comment by Viish** [comment]
https://www.linphone.org/snapshots/docs/liblinphone/multilang/reference/java/linphone_proxy_config.html

**Comment by Viish** [comment]
Or you can check the sample project in linphone-android repository, subdirectoy sample.
