### ISSUE TITLE
compatibility diff

### ISSUE THREAD

**Issue by wuxuan2811** [BelledonneCommunications/linphone-android#649]
I use sdk4.2 to develop my app，found compatibility diff, can you tell me why?
My:
I/spaceon ( 5815): Processing for stream 0
I/spaceon ( 5815): Doing offer/answer processing with specific provider for codec [opus]
I/spaceon ( 5815): Adding speex/16000 for compatibility, just in case.
I/spaceon ( 5815): Adding speex/8000 for compatibility, just in case.
I/spaceon ( 5815): Adding PCMU/8000 for compatibility, just in case.
I/spaceon ( 5815): Adding PCMA/8000 for compatibility, just in case.
I/spaceon ( 5815): Adding GSM/8000 for compatibility, just in case.
I/spaceon ( 5815): Adding G722/8000 for compatibility, just in case.
I/spaceon ( 5815): Adding iLBC/8000 for compatibility, just in case.
I/spaceon ( 5815): Adding iSAC/16000 for compatibility, just in case.
I/spaceon ( 5815): Adding speex/32000 for compatibility, just in case.
I/spaceon ( 5815): Adding L16/44100 for compatibility, just in case.
I/spaceon ( 5815): Adding L16/44100 for compatibility, just in case.
I/spaceon ( 5815): Adding telephone-event/16000 for compatibility, just in case.
I/spaceon ( 5815): Adding telephone-event/8000 for compatibility, just in case.
I/spaceon ( 5815): Adding telephone-event/32000 for compatibility, just in case.
I/spaceon ( 5815): Adding telephone-event/44100 for compatibility, just in case.
Normal example:
I/spaceon ( 4257): Doing offer/answer processing with specific provider for codec [opus]
I/spaceon ( 4257): Adding speex/16000 for compatibility, just in case.
I/spaceon ( 4257): Adding speex/8000 for compatibility, just in case.
I/spaceon ( 4257): Adding PCMU/8000 for compatibility, just in case.
I/spaceon ( 4257): Adding PCMA/8000 for compatibility, just in case.
I/spaceon ( 4257): Adding telephone-event/16000 for compatibility, just in case.
I/spaceon ( 4257): Adding telephone-event/8000 for compatibility, just in case.

**Comment by Viish** [comment]
Actually this list depends on which codecs are enabled on your device.
There was no change in 4.2 release about that, but probably you did change which codecs are enabled.

**Comment by wuxuan2811** [comment]
unfortunately, didn't change any codecs and any settings

**Comment by Viish** [comment]
That also depends on the codecs enabled for the person you call.

**Comment by wuxuan2811** [comment]
I must say that I call the same person. I have check the log, find the codec enabled at init, and nowhere use PayloadType.enable(boolean var1)

**Comment by Viish** [comment]
This log is present only if the caller has this codec enabled and the callee doesn't.

**Comment by wuxuan2811** [comment]
Can you tell me which determine the codec enabled at init period?

**Comment by Viish** [comment]
Codecs can be enabled/disabled either by the linphonerc or by calling PayloadType.enable().
