### ISSUE TITLE
Error:Cause: error=2, No such file or directory

### ISSUE THREAD

**Issue by Rohnit** [BelledonneCommunications/linphone-android#65]
Hi,

I downloaded linphone-android project using this command "git clone git://git.linphone.org/linphone-android.git --recursive". Then use these commands "./prepare.py" and then "make". It successfully build whole project. But when I open it in android studio, I face this error "Error:Cause: error=2, No such file or directory" at bottom messages tab. In terminal using make command project build successful. But In android-studio, it doesn't build. I used android-studio 2.3.2 version. Is there I missing or doing some thing wrong?

**Comment by DatBewar** [comment]
Hello, 
On which platform are you?
How do you open the Linphone project in android studio?

**Comment by Rohnit** [comment]
I am working on android project on "Ubuntu 16.04 LTS" OS. After build project using "prepare.py" and "make" command, I click on "Open an existing Android Studio Project" and select folder "linphone-android" and then opening project in android studio. when it opening, I face these error "Error:Cause: error=2, No such file or directory".

**Comment by DatBewar** [comment]
It's the only error message displayed?
Cause there are so many potential problem which cause this error.

**Comment by Rohnit** [comment]
See this screenshot.

![screenshot from 2017-05-24 17-55-17](https://cloud.githubusercontent.com/assets/17758388/26403158/d89ae550-40aa-11e7-860e-361590cf76d9.png)

 after gradle sync started this error generate.

**Comment by DatBewar** [comment]
Can you try to run on console, on your linphone-android workspace, this command:
./gradlew build

**Comment by Rohnit** [comment]
This is the terminal log after use ./gradlew command


ronit@ronit-HP-EliteBook-8460p:~/Desktop/linphone-android$ ./gradlew build
[Push Notification] Firebase disabled
error: no devices/emulators found
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:preDebugAndroidTestBuild UP-TO-DATE
:preReleaseBuild UP-TO-DATE
:prepareComAndroidSupportMultidex101Library
:prepareComAndroidSupportSupportCompat2600Alpha1Library
:prepareComAndroidSupportSupportCoreUi2600Alpha1Library
:prepareComAndroidSupportSupportCoreUtils2600Alpha1Library
:prepareComAndroidSupportSupportFragment2600Alpha1Library
:prepareComAndroidSupportSupportMediaCompat2600Alpha1Library
:prepareComAndroidSupportSupportV42600Alpha1Library
:prepareDebugDependencies
:compileDebugAidl UP-TO-DATE
:compileDebugRenderscript UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:generateDebugResValues UP-TO-DATE
:generateDebugResources UP-TO-DATE
:mergeDebugResources UP-TO-DATE
:processDebugManifest UP-TO-DATE
:processDebugResources UP-TO-DATE
:generateDebugSources UP-TO-DATE
:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:javaPreCompileDebug
:compileDebugJavaWithJavac UP-TO-DATE
:compileDebugNdk NO-SOURCE
:compileDebugSources UP-TO-DATE
:mergeDebugShaders UP-TO-DATE
:compileDebugShaders UP-TO-DATE
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets UP-TO-DATE
:transformClassesWithJarMergingForDebug UP-TO-DATE
:transformClassesWithMultidexlistForDebug UP-TO-DATE
:transformClassesWithDexForDebug UP-TO-DATE
:mergeDebugJniLibFolders UP-TO-DATE
:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
:transformNativeLibsWithStripDebugSymbolForDebug UP-TO-DATE
:processDebugJavaRes UP-TO-DATE
:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:validateSigningDebug
:packageDebug UP-TO-DATE
:assembleDebug UP-TO-DATE
:checkReleaseManifest
:prepareReleaseDependencies
:compileReleaseAidl UP-TO-DATE
:compileReleaseRenderscript UP-TO-DATE
:generateReleaseBuildConfig UP-TO-DATE
:generateReleaseResValues UP-TO-DATE
:generateReleaseResources UP-TO-DATE
:mergeReleaseResources UP-TO-DATE
:processReleaseManifest UP-TO-DATE
:processReleaseResources UP-TO-DATE
:generateReleaseSources UP-TO-DATE
:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:javaPreCompileRelease
:compileReleaseJavaWithJavac UP-TO-DATE
:compileReleaseNdk NO-SOURCE
:compileReleaseSources UP-TO-DATE
:mergeReleaseShaders UP-TO-DATE
:compileReleaseShaders UP-TO-DATE
:generateReleaseAssets UP-TO-DATE
:mergeReleaseAssets UP-TO-DATE
:transformClassesWithJarMergingForRelease UP-TO-DATE
:transformClassesWithMultidexlistForRelease UP-TO-DATE
:transformClassesWithDexForRelease UP-TO-DATE
:mergeReleaseJniLibFolders UP-TO-DATE
:transformNativeLibsWithMergeJniLibsForRelease UP-TO-DATE
:transformNativeLibsWithStripDebugSymbolForRelease UP-TO-DATE
:processReleaseJavaRes UP-TO-DATE
:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:validateSigningRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':validateSigningRelease'.
> Keystore file /home/ronit/Desktop/linphone-android/"" not found for signing config 'release'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.747 secs

**Comment by DatBewar** [comment]
Ok, can you try this command cause it's not the right error i thinks:
./gradlew assembleDebug

**Comment by Rohnit** [comment]
Now Project build successful. Project already build successful with make command. But Gradle sync is not complete. After gradle sync started, this error generate.

**Comment by DatBewar** [comment]
Did your Android Sdk are up to date?
In android-studio: Tools->Android->sdk manager->sdk tools

**Comment by Rohnit** [comment]
I am usig Android SDK Tools 26.0.2 and SDK Platform Tools 25.0.6

**Comment by DatBewar** [comment]
I'm sorry but i can't help you more for your problem with android-studio.
I don't know what can cause this bug.

**Comment by Rohnit** [comment]
Can you open project in android studio? Bcoz after following steps(Mention in ReadMe), project doesn't open in my android studio. Plz test and mention in readme when and how to open project in android studio.

Thanks for your co-operation

**Comment by DatBewar** [comment]
I work on Android-Studio and, i don't have any problems with gradle.
I found this but i don't know if it will be helpful:
http://blog.raceconditions.net/android-studio-error-on-64-bit-ubuntu/

**Comment by trevora-edge** [comment]
It appears that the issue is the `runApplication()` task in the `build.gradle` file. For some reason, Android Studio is attempting to run adb when performing a gradle sync and failing. Commenting out that task allows Android Studio to successfully load the project.

I don't know the impact of commenting out this task or enough about gradle to fix the issue. However, after commenting out the task I was able to successfully build the project and run it on an emulator from within Android Studio.

Hope this helps.

**Comment by Rohnit** [comment]
Yes, After commenting `runApplication()` task, project build successfully with android studio.

Thank you very much

**Comment by kanul** [comment]
If you find the message "Can not find the location of bazel", then you should edit tensorflow/examples/android/build.gradle". 

This is our edited version: on line 72: def bazelLocation = '/usr/bin/bazel'

**Comment by khaledBou** [comment]
fixed after updated sdk version in android studio

**Comment by luis-szn** [comment]
If you get this error while trying `assembleRelease`, you can solve this by select the right Gradle JDK.

type  `java --version` in terminal 

Go to Android Studio->settings->build,execution,deployment->build tools->gradle

In Gradle JDK, select the option that looks like the output of `java --version`
