### ISSUE TITLE
How to unregister (logout) SIP endpoints?

### ISSUE THREAD

**Issue by Vivektilva** [BelledonneCommunications/linphone-android#650]
To register my SIP endpoints i am using :
 // This will automatically create the proxy config and auth info and add them to the Core
        ProxyConfig cfg = mAccountCreator.configure();
        // Make sure the newly created one is the default
        LinphoneService.getCore().setDefaultProxyConfig(cfg);

to unregistered what should i use:
LinphoneService.getCore().clearProxyConfig(); or LinphoneService.getCore().setDefaultProxyConfig(null); ??

**Comment by Viish** [comment]
Here's how to unregister:
proxyConfig.edit();
proxyConfig.enableRegister(false);
proxyConfig.done();
