### ISSUE TITLE
keeps forgetting my proxy password

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#652]
I find that I have to keep re-entering my proxy account password.

A while later, it will be forgotten again and I have to re-enter it.

Somewhat related, it seems that when I am entering the password, ever character that I add, without pressing any kind of enter key or anything sends another registration attempt to my proxy presumably with the new character added, and of course they all fail until I add the last character.

This is really quite unnecessary and is going to have disastrous effects on installations that hacking mitigation in place to blacklist remotes that fail registration attempts too many times.  There is really no need to try the password until the user has backed out of the account screen.

**Comment by Viish** [comment]
I agree for the character by character saving of the changes.
Regarding the proxy password that disapeer this is weird and unexpected. Do you have a scenario that triggers it for sure ? Anyway please attach logs.

**Comment by Viish** [comment]
I fixed the char by char issue in the settings: 92c070117f35300fc5a1e57a5506238d7854c6b7

**Comment by brianjmurrell** [comment]
> Do you have a scenario that triggers it for sure ?

It could be when REGISTER fails due to proxy being unreachable perhaps.
