### ISSUE TITLE
Several Interface Questions

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#653]
Hi,

I use linphone4.0.1.
In caller, when State is StreamsRunning, I try to add these :
    mLc.setUseInfoForDtmf(true);
    mLc.setAudioDscp(100);
    mLc.setSipDscp(10);
    mLc.setUserData("aaaa");
In callee,when State is StreamsRunning, I can't  get the right value：
    mLc.getUseInfoForDtmf = false
    mLc.getAudioDscp = 46
    mLc.getSipDscp = 26
    mLc.getUserData = null
how to use these api?

thanks.

**Comment by Viish** [comment]
Hi,
Every setting on the Core are only for the local client, none of them are sent or synchronized to anything.
If you really want to pass information through a call, set a custom header before initiating it.
