### ISSUE TITLE
Is there any callback on receiver side when sender set linphoneManager.cameraEnable(false) ?

### ISSUE THREAD

**Issue by lucifer161995** [BelledonneCommunications/linphone-android#654]
when 1st user set linphoneManager.cameraEnable(false) , is there any callback on receiver side? I am working on video call if 1st user set linphoneManager.cameraEnable(false) so i have to show user a message that user disabled a video.

**Comment by Viish** [comment]
If you disable camera on one side of a call, you will get a updatedByRemote call state change on the other end, and the call currentParams will have changed.

**Comment by lucifer161995** [comment]
I have tried but there is no callback on onCallStateChange and updateByRemote

**Comment by Viish** [comment]
That means you only disable the camera locally, but not in the call.
Are you calling call.enableCamera(false); ?

**Comment by lucifer161995** [comment]
i have used linphoneManager.cameraEnabled(false) this disable camera locally?

**Comment by Viish** [comment]
I don't know what it does as it no longer exists on release 4.1.
