### ISSUE TITLE
how to set extra custom params when we setup outgoing call?

### ISSUE THREAD

**Issue by Vivektilva** [BelledonneCommunications/linphone-android#655]
To make outgoing call i am using 

Address address = core.interpretUrl(destination);
            core.inviteAddress(address);

and it is working perfectly .

Now i want to send some extra headers (params) while making this outgoing calls. any method for that or can you specify in which format i can send?

**Comment by Vivektilva** [comment]
I am using 
CallParams callParams;
            callParams = core.createCallParams(null);
            callParams.addCustomHeader("X-PH-Fromnumber","test");
            core.inviteAddressWithParams(address,callParams);

to set custom header , is this correct way?

**Comment by Viish** [comment]
Yes it's perfect.
