### ISSUE TITLE
4.1 make another account default after a deletion

### ISSUE THREAD

**Issue by licaon-kter** [BelledonneCommunications/linphone-android#656]
...and not end up as "Not connected" while other accounts are actually available and connected.

**Comment by Viish** [comment]
Hi,
I already fixed that in master branch commit dec9442a47a1641d3bd1b7f46ecf965437efe347
Thanks anyway for the report.

**Comment by Viish** [comment]
I cherry-picked in release/4.1 branch in commit 9ec717776d0508c75cb5375e3078202d56a9a1cc

**Comment by licaon-kter** [comment]
F-Droid won't rebuild, so it will be fixed in 4.2 I guess, but thanks anyway. :)
