### ISSUE TITLE
4.1 tries to connect to RFC1918 address

### ISSUE THREAD

**Issue by licaon-kter** [BelledonneCommunications/linphone-android#657]
...instead of using STUN/TURN/ICE

Steps:
* get [Netguard](https://github.com/m66b/netguard) on two devices
* turn on Netguard (enable logging in Settings Advanced)
* connect via mobile
* call eachother
* see that after pickup Netguard per app details log shows that Linphone tries (and fails) to connect to 10.x.x.x (local VPN address that you can customize in Netguard settings)
  

This is not #366 as DNS resolving works fine.

**Comment by Viish** [comment]
We'll take a look at it someday, but clearly won't be anytime soon.

**Comment by licaon-kter** [comment]
@Viish What does that mean exactly? Why would it choose to connect via non-public, non-routable IP?

**Comment by Viish** [comment]
I don't know, probably because of something Netguard does.
It will take time to investigate and clearly we don't have it right now.
As it happens only when our app is used with a third party app, it clearly isn't top priority for us.
Anyway if you could attach logs that would help us gain some time.

**Comment by licaon-kter** [comment]
No matter what NetGuard does (or what IP it has), it's Linphone deciding to what IP it should connect, and most of the time, it should not connect to one in RFC1918, right?

Eg. I've changed the VPN IP to 192.168.192.168 on one device and to 192.168.100.1 on another.
After pickup, first device wanted to connect to 192.168.100.1, while the second device wanted to connect to 192.168.192.168.

**Comment by licaon-kter** [comment]
@M66B Any thoughts? On 2.247, unchecking apply rules will let Linphone correctly connect.

Now pplying rules, but with Filtering disable, they'll connect ok, yet one device only sends data (voice) but can't receive, while the other receives that voice and says it sends its own.

@Viish I'll see about some logs later.

**Comment by M66B** [comment]
An app should not connect to the VPN address.

**Comment by Viish** [comment]
Hi,
Can you try with a recent SDK ? It should be fixed now.

**Comment by licaon-kter** [comment]
SDK HEAD and Linphone HEAD?

**Comment by Viish** [comment]
SDK at least 4.2-129-g74b992a, app doesn't matter but a recent one would be better.
