### ISSUE TITLE
No Audio For outgoing calls

### ISSUE THREAD

**Issue by Vivektilva** [BelledonneCommunications/linphone-android#658]
I am making outgoing using :
  Address address = core.interpretUrl("+"+input);
            core.inviteAddress(address);

but not able to hear anything while it's ringing or even after call is connected .

RECORD_AUDIO permission is already granted .

Please find logs .
[lp_audio_issue.txt](https://github.com/BelledonneCommunications/linphone-android/files/3211384/lp_audio_issue.txt)

**Comment by Viish** [comment]
From the logs you sent, your app is in OutgoingEarlyMedia.
This means call isn't connected, and your client simply sends audio.
Configure your remote to not use early-media or to answer the call directly and it will work fine.

**Comment by Vivektilva** [comment]
I checked with same sdk version in my other device (Redmi Note 5)  and audio was perfect for outgoing call. Issue i am facing is with Motorola G5 Device .

Here is log where i am able to hear audio loud and clear in Redmin Note 5 with same code without changing anything on remote side.
[lp_audio_issue_2.txt](https://github.com/BelledonneCommunications/linphone-android/files/3211685/lp_audio_issue_2.txt)


Please take a look
