### ISSUE TITLE
Audio issue for calling 

### ISSUE THREAD

**Issue by Vivektilva** [BelledonneCommunications/linphone-android#659]
No Audio For outgoing calls #658 adding to that ..
I checked with same sdk version in my other device (Redmi Note 5) and audio was perfect for outgoing call. Issue i am facing is with Motorola G5 Device .

Here is log where i am able to hear audio loud and clear in Redmin Note 5 with same code without changing anything on remote side.
[lp_audio_issue_2.txt](https://github.com/BelledonneCommunications/linphone-android/files/3211815/lp_audio_issue_2.txt)

Please take a look

**Comment by Viish** [comment]
From this log, your device does send and receive audio.
The problem is between this device and the remote part of the call.
Check the remote logs.
