### ISSUE TITLE
Failed to initialize video/hevc, error 0xfffffffe

### ISSUE THREAD

**Issue by wuxuan2811** [BelledonneCommunications/linphone-android#661]
I use flutter to call linphone through sdk, find error when init, but it didn't crash.
Then
public void onGlobalStateChanged(final Core lc, final GlobalState state, final String message) {
        Log.i("New global state [", state, "]");
        if (state == GlobalState.On) {
            try {
                initLiblinphone(lc);
            } catch (IllegalArgumentException iae) {
                Log.e("[Manager] Global State Changed Illegal Argument Exception: " + iae);
            }
        }
    }
didn't work.

The error information:
W/FactoryImpl(10790): Unable to load optional library ffmpeg-linphone: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.my.linphoneexample-RmI30kpg9HML2MF_nHvYAw==/base.apk"],nativeLibraryDirectories=[/data/app/com.my.linphoneexample-RmI30kpg9HML2MF_nHvYAw==/lib/arm64, /data/app/com.my.linphoneexample-RmI30kpg9HML2MF_nHvYAw==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libffmpeg-linphone.so"
V/AudioManager(10790): getProperty  key: android.media.property.OUTPUT_FRAMES_PER_BUFFER
V/AudioManager(10790): getProperty  key: android.media.property.OUTPUT_SAMPLE_RATE
I/HwCust  (10790): Constructor found for class android.net.HwCustConnectivityManagerImpl
D/HwCust  (10790): Create obj success use class android.net.HwCustConnectivityManagerImpl
I/OMXClient(10790): Treble IOmx obtained
I/ACodec  (10790): In onAllocateComponent create compenent, codec name: OMX.IMG.TOPAZ.VIDEO.Encoder
I/OMXClient(10790): Treble IOmx obtained
I/ACodec  (10790): In onAllocateComponent create compenent, codec name: OMX.IMG.MSVDX.Decoder.AVC
I/OMXClient(10790): Treble IOmx obtained
E/ACodec  (10790): Unable to instantiate a encoder for type 'video/hevc' with err 0xfffffffe.
E/ACodec  (10790): signalError(omxError 0xfffffffe, internalError -2)
E/MediaCodec(10790): Codec reported err 0xfffffffe, actionCode 0, while in state 1
W/MediaCodec-JNI(10790): try to release MediaCodec from JMediaCodec::~JMediaCodec()...
W/MediaCodec-JNI(10790): done releasing MediaCodec from JMediaCodec::~JMediaCodec().
W/System.err(10790): java.lang.IllegalArgumentException: Failed to initialize video/hevc, error 0xfffffffe
W/System.err(10790): 	at android.media.MediaCodec.native_setup(Native Method)
W/System.err(10790): 	at android.media.MediaCodec.<init>(MediaCodec.java:1793)
W/System.err(10790): 	at android.media.MediaCodec.createEncoderByType(MediaCodec.java:1759)
W/System.err(10790): 	at org.linphone.core.FactoryImpl.createCore3(Native Method)
W/System.err(10790): 	at org.linphone.core.FactoryImpl.createCore(Factory.java:491)
W/System.err(10790): 	at com.my.linphone.linphoneAndroid.linphone.LinphoneManager.startLibLinphone(LinphoneManager.java:94)
W/System.err(10790): 	at com.my.linphone.linphoneAndroid.linphone.LinphoneManager.createAndStart(LinphoneManager.java:57)
W/System.err(10790): 	at com.my.linphone.linphoneAndroid.service.LinphoneService.onStartCommand(LinphoneService.java:54)
W/System.err(10790): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4151)
W/System.err(10790): 	at android.app.ActivityThread.-wrap21(Unknown Source:0)
W/System.err(10790): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2119)
W/System.err(10790): 	at android.os.Handler.dispatchMessage(Handler.java:108)
W/System.err(10790): 	at android.os.Looper.loop(Looper.java:166)
W/System.err(10790): 	at android.app.ActivityThread.main(ActivityThread.java:7529)
W/System.err(10790): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(10790): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
W/System.err(10790): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by Viish** [comment]
Hi,
Yes don't worry about this.
The SDK tries to instantiate the H265 MediaCodec object to see if it is available for use in Linphone.
If it isn't, it produces this exception but it is already handled by the SDK.
You don't have to do anything.
