### ISSUE TITLE
# become to %23

### ISSUE THREAD

**Issue by wuxuan2811** [BelledonneCommunications/linphone-android#662]
Number"21#",then the server can't recognize the right code. # become to %23
Debug log:
I/spaceon: bellesip_wake_lock_acquire(): Android wake lock [belle-sip recv channel] acquired [ref=0x2f66]
    channel [0x77fcfa7340]: starting recv background task with id=[2f66].
    channel [0x77fcfa7340]: received [339] new bytes from [UDP://101.200.181.145:14170]:
    SIP/2.0 100 Trying
    Via: SIP/2.0/UDP 192.168.2.62:37720;branch=z9hG4bK.NC4WtckGm;rport=36474;received=118.114.237.144
    From: <sip:10006@101.200.181.145>;tag=QfP3CN6nZ
    To: <sip:21%23@101.200.181.145>
    Call-ID: b9woLbT7np
    CSeq: 21 INVITE
    User-Agent: FreeSWITCH-mod_sofia/1.6.18+git~20170612T211449Z~6e79667c0a~64bit
    Content-Length: 0
I/spaceon: channel [0x77fcfa7340] [339] bytes parsed
    Found transaction matching response.
    Changing [client] [INVITE] transaction [0x77fcfa07a0], from state [CALLING] to [PROCEEDING]
I/spaceon: op [0x780edfc000] : set_or_update_dialog() current=[0x0] new=[0x0]
    Op [0x780edfc000] receiving call response [100], dialog is [0x0] in state [BELLE_SIP_DIALOG_NULL]
    channel [0x77fcfa7340]: ending recv background task with id=[2f66].
I/spaceon: bellesip_wake_lock_release(): Android wake lock released [ref=0x2f66]
I/spaceon: bellesip_wake_lock_acquire(): Android wake lock [belle-sip recv channel] acquired [ref=0x2f46]
    channel [0x77fcfa7340]: starting recv background task with id=[2f46].
I/spaceon: channel [0x77fcfa7340]: received [865] new bytes from [UDP://101.200.181.145:14170]:
    SIP/2.0 480 Temporarily Unavailable
    Via: SIP/2.0/UDP 192.168.2.62:37720;branch=z9hG4bK.NC4WtckGm;rport=36474;received=118.114.237.144
    Max-Forwards: 69
    From: <sip:10006@101.200.181.145>;tag=QfP3CN6nZ
    To: <sip:21%23@101.200.181.145>;tag=0SHeQ4NUD6ggH
    Call-ID: b9woLbT7np
    CSeq: 21 INVITE
    User-Agent: FreeSWITCH-mod_sofia/1.6.18+git~20170612T211449Z~6e79667c0a~64bit
    Accept: application/sdp
    Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE
    Supported: timer, path, replaces
    Allow-Events: talk, hold, conference, presence, as-feature-event, dialog, line-seize, call-info, sla, include-session-description, presence.winfo, message-summary, refer
    Reason: Q.850;cause=16;text="NORMAL_CLEARING"
    Content-Length: 0
    Remote-Party-ID: "21#" <sip:21#@101.200.181.145>;party=calling;privacy=off;screen=no
I/spaceon: channel [0x77fcfa7340] [865] bytes parsed
    Found transaction matching response.
    Changing [client] [INVITE] transaction [0x77fcfa07a0], from state [PROCEEDING] to [COMPLETED]
    channel [0x77fcfa7340]: message sent to [UDP://101.200.181.145:14170], size: [403] bytes
    ACK sip:21%23@101.200.181.145:14170 SIP/2.0
    Via: SIP/2.0/UDP 192.168.2.62:37720;branch=z9hG4bK.NC4WtckGm;rport
    Call-ID: b9woLbT7np
    From: <sip:10006@101.200.181.145>;tag=QfP3CN6nZ
    To: <sip:21%23@101.200.181.145>;tag=0SHeQ4NUD6ggH
    Contact: <sip:10006@118.114.237.144:36474;transport=udp>;expires=3600;+sip.instance="<urn:uuid:2dc2538e-2bbf-0034-9e39-a83ed7e890fb>"
    Max-Forwards: 70
    CSeq: 21 ACK
    op [0x780edfc000] : set_or_update_dialog() current=[0x0] new=[0x0]
    Op [0x780edfc000] receiving call response [480], dialog is [0x0] in state [BELLE_SIP_DIALOG_NULL]
    CallSession [0x77ffd71d38] moving from state State::OutgoingProgress to State::Error
    Writing echo canceler state, 0 bytes

**Comment by Viish** [comment]
That's normal.
The RFC https://tools.ietf.org/html/rfc3986#section-4.1 says that a user-info can't contain the '#' directly, so we have to encode it with the format '% hexdigit hexdigit'.

**Comment by wuxuan2811** [comment]
Do you have a way to keep '#'? For example, To: sip:21#@xxx.xxx.xxx.xxx.

**Comment by Viish** [comment]
No I don't think so.

**Comment by wuxuan2811** [comment]
Have a error log :header_contact parser error for [Contact:<sip:#21#@192.168.1.5:5060>], so  the code can't decode the '#'?

**Comment by Viish** [comment]
Indeed. As I told you this isn't valid as per the SIP RFC, so our parser don't accept it.
