### ISSUE TITLE
Echo suppression does not work

### ISSUE THREAD

**Issue by DmytroArseniuk** [BelledonneCommunications/linphone-android#667]
I'm trying to suppress echo for case when one of the phone uses speakerphone on linphone sdk 4.0.1
I've enabled echo cancellation and echo limiter, but I still can hear echo.
mCore.enableEchoCancellation(true);
mCore.enableEchoLimiter(true);
Should I use echo canceller filter name for this? (setEchoCancellerFilterName) Where I can find  exact filter names (String constants) that I can pass into this method?

**Comment by Viish** [comment]
Don't use echoLimiter, simply enable echoCancellation(), but it has to be calibrated.
Check our assistant code: https://github.com/BelledonneCommunications/linphone-android/blob/master/app/src/main/java/org/linphone/assistant/AssistantActivity.java#L138

**Comment by tlaurion** [comment]
On i9300, calibration happens on the speakerphone, even if headphones are connected?

**Comment by sushilsolanki8875** [comment]
Hi @Viish, I'm using the below settings.
```
ec_calibrator_cool_tones=1
echocancellation=1
ec_delay=0
ec_tail_len=60
ec_frame_size=128
mic_gain=1.0
mic_gain_db=0.5
playback_gain_db=0.5
dtmf_player_amp=0.1
```

And I enabled the EchoCancellation using below code 

 ```
if (core.hasBuiltinEchoCanceller()) {
 core.enableEchoCancellation(false);
 } else {
 core.enableEchoCancellation(true);
}
```

But still receiving echo on some devices like Moto. it is working on Samsung j7 and Oneplus 6t. Can you please help where is the issue?
