### ISSUE TITLE
How to receive audio call ? accept call is showing deprecated .

### ISSUE THREAD

**Issue by Vivektilva** [BelledonneCommunications/linphone-android#668]
What is function to receive audio call (not video ) and what is to reject call and to hang up call?

**Comment by Vivektilva** [comment]
I am using  linphone-sdk-android-4.2-33-g44c0e16.aar
and in this all the function of Core to accept calls are showing as deprecated  . which function i need to use to receive incoming call?

**Comment by Viish** [comment]
Yes core.acceptCall is deprecated, the right way is call.accept().
To terminate a call, call.terminate() replaces core.terminateCall().
