### ISSUE TITLE
how to get extra headers for incoming call?

### ISSUE THREAD

**Issue by Vivektilva** [BelledonneCommunications/linphone-android#669]

**Comment by Vivektilva** [comment]
i can set extra header for outgoing calls , same way when i get incoming calls i want to get headers set, is there any way to do so?

**Comment by Vivektilva** [comment]
i have installed my app in two device . From device 1 i am making outgoing call and setup extra header with:
CallParams callParams;
                        callParams = core.createCallParams(null);
                        callParams.addCustomHeader("X-PH-Fromnumber","98989");
core.inviteAddressWithParams(address,callParams);

and in device 2 i am getting call but how to get value of my custom header ("X-PH-Fromnumber")?

**Comment by Viish** [comment]
On the other side, use call.getCurrentParams().getCustomHeader("X-PH-Fromnumber") or call.getRemoteParams().getCustomHeader("X-PH-Fromnumber")

**Comment by Irfanulhaq1991** [comment]
@Viish  I have followed your instruction but still getting null value.  You  can see the result in following screen shots.

![1](https://user-images.githubusercontent.com/56818303/147550650-13f92c7a-75e8-49f8-9d35-c4faed4866c2.PNG)
![2](https://user-images.githubusercontent.com/56818303/147550664-66c3d6b6-7bb7-42bc-a4a2-4e7420532365.PNG)
![3](https://user-images.githubusercontent.com/56818303/147550671-488beb6a-5e05-44e3-b985-d44ea96ca59a.PNG)

**Comment by ehsanmqn** [comment]
@Irfanulhaq1991 Maybe your added headers remove by the SIP server. If it is possible, get pcaps from the servers then analyze your SIP packed looking for added headers.

**Comment by abdoutech19** [comment]
@Viish same as @Irfanulhaq1991 I followed the exact same instructions but still getting null on the second device, any insights please? I really need your help as this is so important to us, thank you.
