### ISSUE TITLE
with usb microphone on  raspberry pi, linphone volume sound sending is very low

### ISSUE THREAD

**Issue by stackprogramer** [BelledonneCommunications/linphone-android#67]
hi, when i used usb mircophone,it can record audio with audacity,and arecord very good,
but when i used usb microphone and linphone it returns poor quality .
but this usb and linphone work with on windows and linux PC, in raspberry pi not good quality........

**Comment by CrabeMan** [comment]
Hello,
Have you try to set the [microphone gain](http://linphone.org/docs/liblinphone-javadoc/org/linphone/core/LinphoneCore.html#setMicrophoneGain(float)) ?

CrabeMan.

**Comment by stackprogramer** [comment]
yes, gain is max..

**Comment by DatBewar** [comment]
Hello,
You should ask this on Linphone repository, here it's only Android version.
