### ISSUE TITLE
how to set push notification for incoming callls?

### ISSUE THREAD

**Issue by Vivektilva** [BelledonneCommunications/linphone-android#670]
Is there any way , where we can setup our firebase token and when there is any incoming call we get notification for that call in Firebase service?

(will be helpful when app is in kill state)

**Comment by Viish** [comment]
Sending the push token to the server depends on the server. For flexisip, we add it in the contact params.
And when a push is received, you can do what you want. Our choice is to start the Service if it has been killed.

**Comment by Vivektilva** [comment]
I setup push notification from my server side so whenever there is incoming call i am getting push notification .

My app is in kill state and when i get notification i am opening my app and starting Linphoneservice which has listener but i am not getting any event for incoming calls in onCallStateChanged.

**Comment by Viish** [comment]
Have you looked in the logs for an INVITE that would be sent by your server after the REGISTER that follows the LinphoneService being started from the push ?

**Comment by Vivektilva** [comment]
once the service has been started after receiving push , i am getting onRegistrationStateChanged OK .

**Comment by Viish** [comment]
After that if you don't receive the INVITE again, it's a configuration issue of your server.
