### ISSUE TITLE
I got a 403 Forbidden when I register for belle-sip

### ISSUE THREAD

**Issue by ForLovelj** [BelledonneCommunications/linphone-android#673]
I/belle-sip: channel [0xd28a5840]: message sent to [UDP://27.155.66.12:5060], size: [832] bytes
                                                           REGISTER sip:27.155.66.12 SIP/2.0
                                                           Via: SIP/2.0/UDP 192.168.31.12:37486;branch=z9hG4bK.KiFKCRWct;rport
                                                           From: "80000009" <sip:80000009@27.155.66.12>;tag=xQ2CIjnUk
                                                           To: "80000009" <sip:80000009@27.155.66.12>
                                                           CSeq: 21 REGISTER
                                                           Call-ID: NwhN7oni5J
                                                           Max-Forwards: 70
                                                           Supported: replaces, outbound, gruu
                                                           Accept: application/sdp
                                                           Accept: text/plain
                                                           Accept: application/vnd.gsma.rcs-ft-http+xml
                                                           Contact: <sip:80000009@182.150.24.10:37486;transport=udp>;+sip.instance="<urn:uuid:b0d9bd54-46ac-00e0-9c31-f7ea00f787c0>"
                                                           Expires: 3600
                                                           User-Agent: LinphoneAndroid/1.0 (belle-sip/1.6.3)
                                                           Authorization:  Digest realm="27.155.66.12", nonce="e1c6b740-17ad-486c-b91c-5cce9e2cb54b", algorithm=MD5, username="80000009",  uri="sip:27.155.66.12", response="ba9e4bb9ffb0d57512628ac4db702e88", cnonce="2RaVsEzCgWG8mhVa", nc=00000001, qop=auth
 I/belle-sip: channel [0xd28a5840]: ending recv background task with id=[3116].
 I/belle-sip: bellesip_wake_lock_release(): Android wake lock released [ref=0x3116]
 I/belle-sip: bellesip_wake_lock_acquire(): Android wake lock [belle-sip recv channel] acquired [ref=0x314a]
 I/belle-sip: channel [0xd28a5840]: starting recv background task with id=[314a].
 I/belle-sip: channel [0xd28a5840]: received [518] new bytes from [UDP://27.155.66.12:5060]:
                                                           SIP/2.0 403 Forbidden
                                                           Via: SIP/2.0/UDP 192.168.1.7:37486;received=182.150.24.10;branch=z9hG4bK.qO4t7v8eI;rport=37486
                                                           From: "80000009" <sip:80000009@27.155.66.12>;tag=JnzsKzsLH
                                                           To: "80000009" <sip:80000009@27.155.66.12>;tag=a4814QtXveDpN
                                                           Call-ID: Jrjda2x1Wj
                                                           CSeq: 21 REGISTER
                                                           User-Agent: FreeSWITCH-mod_sofia/1.6.20+git~20180507T185611Z~43a9feb7f8~64bit
                                                           Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE
                                                           Supported: path, replaces
                                                           Content-Length: 0

**Comment by ForLovelj** [comment]
If I don't use VPN, everything works.
I access the Intranet server from the external network via VPN,It's inevitable.
If 403 Forbidden happens once, this can continue to happen even if I turn off my VPN and register the same account.

**Comment by Viish** [comment]
Hard to say with that little logs, but you probably will have all the relevant information in your server logs since you do receive an answer from it.
