### ISSUE TITLE
Build my own aar error.

### ISSUE THREAD

**Issue by Seejun** [BelledonneCommunications/linphone-android#675]
I down the latest android-sdk and follow the README.md to build my own sdk:

mkdir build && cd build
cmake .. -DLINPHONESDK_PLATFORM=Android
cmake --build . 
-------------------------------------------------------------------------
There is error when run 'cmake --build . '

-- Configuring done
-- Generating done
-- Build files have been written to: /home/fei/linphonedev/linphone-sdk/build
root@fei-VirtualBox:/home/fei/linphonedev/linphone-sdk/build# 
root@fei-VirtualBox:/home/fei/linphonedev/linphone-sdk/build# cmake --build . 
: No such file or directory
CMake Error at /home/fei/linphonedev/linphone-sdk/cmake/Android/GradleClean.cmake:34 (message):
  Gradle clean failed

make[2]: *** [CMakeFiles/gradle-clean] error 1
make[1]: *** [CMakeFiles/gradle-clean.dir/all] error 2
make: *** [all] error 2

------------------------------------------------------------------------
And my vir is
#-----------------jdk-----------------
export JAVA_HOME=/home/fei/linphonedev/jdk1.8.0_211
export JRE_HOME=/home/fei/linphonedev/jdk1.8.0_211/jre
export CLASSPATH=.:$JAVA_HOME/lib:$JRE_HOME/lib
export PATH=$PATH:$JAVA_HOME/bin:$JRE_HOME/bin
#---------------android sdk---------------
export ANDROID_HOME=/home/fei/linphonedev/android-sdk
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
#-----------------android ndk---------------
export ANDROID_NDK=/home/fei/linphonedev/android-ndk-r17c
export PATH=$PATH:$ANDROID_NDK:$ANDROID_NDK_HOME/build
#---------------android studio--------------
export PATH=$PATH:/home/fei/linphonedev/android-studio/bin
#-----------------cmake-----------------
export PATH=$PATH:/home/fei/linphonedev/cmake-3.10.1-Linux-x86_64/bin
#-----------------gradle-----------------
export PATH=$PATH:/home/fei/linphonedev/gradle-4.10.2/bin

**Comment by Viish** [comment]
Could you attach the whole output please ?

**Comment by Seejun** [comment]
> Could you attach the whole output please ?

sorry,the whole step and output is there:

root@fei-VirtualBox:/home/fei# cd linphonedev/linphone-sdk/
root@fei-VirtualBox:/home/fei/linphonedev/linphone-sdk# rm -rf build/
root@fei-VirtualBox:/home/fei/linphonedev/linphone-sdk# mkdir build
root@fei-VirtualBox:/home/fei/linphonedev/linphone-sdk# cd build
root@fei-VirtualBox:/home/fei/linphonedev/linphone-sdk/build# cmake .. -DLINPHONESDK_PLATFORM=Android
-- Found Git: /usr/bin/git (found suitable version "1.9.1", minimum required is "1.7.10") 
-- Enabled features:
 * Arch suffix, Append the android abi to shared libraries
 * Mbedtls, Crypto stack implementation based on mbeddtls.
 * SRTP, SRTP media encryption support.
 * ZRTP, ZRTP media encryption support.
 * WebRTC AEC, WebRTC echo canceller support.
 * WebRTC AECM, WebRTC echo canceller for mobile support.
 * GSM, GSM audio encoding/decoding support.
 * iLBC, iLBC audio encoding/decoding support.
 * ISAC, ISAC audio encoding/decoding support.
 * OPUS, OPUS audio encoding/decoding support.
 * Speex, Speex audio encoding/decoding support.
 * Video, Ability to capture and display video.
 * jpeg, JPEG support with libjpeg-turbo.
 * qrcode, QRCode support with zxing.
 * MKV, MKV playing and recording support.
 * VPX, VPX (VP8) video encoding/decoding support.
 * Java wrapper, Build the Java wrapper from Liblinphone.
 * LIME X3DH, Enable Linphone IM Encryption version 2 support in  Liblinphone.
 * VCARD, Enable vCard 4 support in Linphone and Liblinphone.

-- Disabled features:
 * Embedded OpenH264, Embed the openh264 library instead of downloading it from Cisco.
 * Unit tests, Enable unit tests support with BCUnit library.
 * Debug logs, Enable debug level logs in libinphone and mediastreamer2.
 * Doc, Enable documentation generation with Doxygen and Sphinx
 * Tools, Enable tools binary compilation.
 * unmaintained, Allow inclusion of unmaintained code in the build.
 * Polarssl, Crypto stack implementation based on polarssl.
 * Tunnel, Secure tunnel for SIP/RTP (require license).
 * RTP Map always in SDP, Always include rtpmap in SDP.
 * mDNS, Multicast DNS support
 * GPL third parties, Usage of GPL third-party code (FFmpeg and x264).
 * Non free codecs, Allow inclusion of non-free codecs in the build.
 * WASAPI, Windows Audio Session API (WASAPI) sound card support.
 * AMRNB, AMR narrow-band audio encoding/decoding support (require license).
 * AMRWB, AMR wide-band audio encoding/decoding support (require license).
 * Codec2, Codec2 audio encoding/decoding support.
 * G729, G.729 audio encoding/decoding support.
 * G729B CNG, G.729 annex B confort noise generation.
 * G726, G.726 audio encoding/decoding support.
 * Silk, Silk audio encoding/decoding support.
 * WebRTC VAD, WebRTC voice activation detector support.
 * BV16, BroadVoice 16 audio encoding/decoding support.
 * FFmpeg, Some video processing features via FFmpeg: JPEG encoding/decoding, video scaling, H264 decoding...
 * H263, H263 video encoding/decoding support (require license).
 * H263p, H263+ video encoding/decoding support (require license).
 * MPEG4, MPEG4 video encoding/decoding support (require license).
 * OpenH264, H.264 video encoding/decoding support with the openh264 library (require license).
 * X264, H.264 video encoding support with the x264 library (require license).
 * AAudio, AAudio Android sound card for Android 8+.
 * PCAP, PCAP support.
 * GTK UI, Enable the GTK user interface of Linphone.
 * CXX wrapper, Build the C++ wrapper for Liblinphone.
 * CSharp wrapper, Build the C# wrapper from Liblinphone.
 * LIME, Enable Linphone IM Encryption support in  Liblinphone.
 * NLS, Enable internationalization of Linphone and Liblinphone.
 * Update Check, Enable update check.
 * Relative prefix, liblinphone and mediastreamer will look for their respective ressources relatively to their location.

-- Setting build type to 'RelWithDebInfo' as none was specified
-- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
-- 'pystache' python module found
-- 'six' python module found

  ***************************************************************************
  ***************************************************************************
  ***** Linphone SDK without third party GPL software                   *****
  ***** If you acquired a proprietary license from Belledonne           *****
  ***** Communications, this SDK can be used to create                  *****
  ***** a proprietary Linphone-based application.                       *****
  ***************************************************************************
  ***************************************************************************
  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fei/linphonedev/linphone-sdk/build
root@fei-VirtualBox:/home/fei/linphonedev/linphone-sdk/build# cmake --build . 
Scanning dependencies of target gradle-clean
CMake Error at /home/fei/linphonedev/linphone-sdk/cmake/Android/GradleClean.cmake:34 (message):
  Gradle clean failed


make[2]: *** [CMakeFiles/gradle-clean] error 1
make[1]: *** [CMakeFiles/gradle-clean.dir/all] error 2
make: *** [all] error 2
root@fei-VirtualBox:/home/fei/linphonedev/linphone-sdk/build#

**Comment by Viish** [comment]
Do you have git installed ?
Can you run
`../cmake/Android/gradlew clean -i`
from the build directory ?

**Comment by Seejun** [comment]
> Do you have git installed ?
> Can you run
> `../cmake/Android/gradlew clean -i`
> from the build directory ?

I had already install git,and now I change my gradle version to 4.10.1 which is writen in  'cmake\Android\gradle\wrapper\gradle-wrapper.properties',and I can't run 'gradlew clean -i' from the build directory.

root@fei-VirtualBox:/home/fei/linphonedev/linphone-sdk/cmake/Android# git --version
git version 1.9.1
root@fei-VirtualBox:/home/fei/linphonedev/linphone-sdk/cmake/Android# gradle -version

------------------------------------------------------------
Gradle 4.10.1
------------------------------------------------------------

Build time:   2018-09-12 11:33:27 UTC
Revision:     76c9179ea9bddc32810f9125ad97c3315c544919

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_211 (Oracle Corporation 25.211-b12)
OS:           Linux 4.2.0-27-generic amd64

**Comment by Viish** [comment]
> and I can't run 'gradlew clean -i' from the build directory.

You have to specify the path like I mentioned:
`../cmake/Android/gradlew clean -i`

**Comment by Seejun** [comment]
Maybe is my fileformat's wrong,I try‘ :set ff=unix’.
I will close the issue,thanks.

**Comment by Freaking1989** [comment]
@Seejun Hi，I found this problem also，How can you solve this，can you help me to solve it?by the way,can you speak chinese?
