### ISSUE TITLE
Building failed after changing package name in method getPackageName()

### ISSUE THREAD

**Issue by ProudNoob** [BelledonneCommunications/linphone-android#676]
After editing the app/build.gradle file and change the value returned by method getPackageName() to 'new.package', Android studio can't build the app now and shows 
> "No matching client found for package name 'new.package.debug'". 

I have tried with ./gradlew assembleDebug but it returned:
> Execution failed for task ':app:processDebugGoogleServices'.
> No matching client found for package name 'new.package.debug'

**Comment by Viish** [comment]
Following https://stackoverflow.com/questions/34990479/no-matching-client-found-for-package-name-google-analytics-multiple-productf, have you updated the google-services.json ?

**Comment by ProudNoob** [comment]
Doesn't work. I already put the google-services.json file into app folder. Still the same error.

**Comment by ProudNoob** [comment]
FIXED: I just have to created a new directory named `debug` inside app directory and copied my google-services.json into there, then renamed package_name to `new.package.debug`. Now I can make debug build just fine.

**Comment by farhat97** [comment]
@ProudNoob , how did you change the package name in the first place? I have been trying to do this, but I've encountered both the "no matching client" error, as well as other problems with imports (specially with import org.linphone.R, this didn't change with all my attempts of changing the package name.
