### ISSUE TITLE
IPv6 regression

### ISSUE THREAD

**Issue by nivex** [BelledonneCommunications/linphone-android#677]
After upgrading to Linphone 4.1 (tried both Play Store and F-Droid versions) on my Android 5.1 device, I am no longer able to register to my Asterisk PBX account. I now only see "Connection in progress" in the status bar. It appears to be attempting to re-register extremely rapidly. The handset slows noticeably while this is happening.

On my Asterisk box I am seeing messages like these repeated:
[May  3 19:31:39] NOTICE[1213]: chan_sip.c:17169 check_auth: Correct auth, but based on stale nonce received from '<sip:aurora@pbx-int.home.nivex.net>;tag=JLw~N2UfL'

This is an account that was working fine pre-upgrade.

The problem also disappears when switching to an IPv4 endpoint.

**Comment by Viish** [comment]
Hi,

Thanks for the report. Could you attach logs with that issue please ?

Thanks.

**Comment by nivex** [comment]
I used Send Logs from within the app and got:
https://www.linphone.org:444//tmp/5cf7cf98161f1_170fbc361617594e5c9d.gz

**Comment by Viish** [comment]
Thanks, will forward it to our IPv6 expert.

**Comment by nivex** [comment]
What was the fix?

**Comment by Viish** [comment]
I actually don't know, I'm not in charge of that part.

**Comment by nivex** [comment]
I have just installed 4.2.0-beta from F-Droid and this issue is still present.
