### ISSUE TITLE
Unable to set stun/turn server username and password 

### ISSUE THREAD

**Issue by tahirjilani** [BelledonneCommunications/linphone-android#68]
I see the docs:
http://www.linphone.org/docs/liblinphone-javadoc/org/linphone/core/LinphoneNatPolicy.html#setStunServerUsername(java.lang.String)
but i don't find it in linphone-android. 

How to set these parameters in linphone android?

**Comment by DatBewar** [comment]
Hello,
you can find an example of use:
https://github.com/BelledonneCommunications/linphone-android/blob/master/src/android/org/linphone/LinphonePreferences.java#L1050-L1066

**Comment by tahirjilani** [comment]
Thanks for the information I have fetched latest master branch and tried using setting stun and turn user name and password. However it seems like when ICE is enabled turn information are not being used. For this i will create another issue.

**Comment by Happynico7504** [comment]
> Hello, you can find an example of use: https://github.com/BelledonneCommunications/linphone-android/blob/master/src/android/org/linphone/LinphonePreferences.java#L1050-L1066

The file doesn't even exist anymore...
