### ISSUE TITLE
Should re-register when IPv6 address changes

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#681]
How much testing does linphone-android get with IPv6?

One of the "features" of IPv6 is that the client can generate it's own IPv6 address, and regenerate new addresses periodically via [Privacy Extensions (rfc4941)](https://tools.ietf.org/html/rfc4941).

When a device does this, surely it needs to re-register with a SIP proxy to inform it of it's new IP address, yes?

Does linphone-android actually do this re-registration?

**Comment by Viish** [comment]
I don't know if the lib will detect the change automatically or not.
You can try and tell me ;)

**Comment by brianjmurrell** [comment]
I guess the answer to the first question is probably no or not much.  :-/

I don't think it is detecting the change and doing a REGISTER when it happens, which of course means the information at the SIP proxy is stale when it goes to do the INVITE.

This seems like a good use-case for #564.

**Comment by Viish** [comment]
SDK issue, not Android
