### ISSUE TITLE
How to use Group Chat on new Linphone SDK 4.2-41

### ISSUE THREAD

**Issue by mayjethva** [BelledonneCommunications/linphone-android#682]
Hi,

I am trying to use group chat after updating my version of Linphone from 3.x.  I have build the app through Android Studio and use my own SIP server.

When trying to create a group chat I am only able to select one contact before entering the chat room.  I am not sure how to get multiple people in the same chat.

I also noticed the Chat section of settings has changed and LIME is no longer an option.  Is LIME no longer being used in Linphone?

Thanks.

**Comment by Viish** [comment]
Hi,
Here's how to do it:
```
ChatRoomParams params = core.createDefaultChatRoomParams();
params.enableEncryption(false);
params.enableGroup(true);
Address[] participants = new Address[2];
[...]
ChatRoom room = core.createChatRoom(params, subject, participants);
```

If you enable encryption it will use LIME (the new one that is end-to-end and requires a server for key exchange).

**Comment by mayjethva** [comment]
In which file do I edit these lines?
