### ISSUE TITLE
Video capture frame rate is too small

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#683]
Hi，

Set the frame rate to 30fps in the settings, but in the file androidvideo.cpp:

static int video_capture_get_fps(MSFilter *f, void *arg){
	AndroidReaderContext* d = (AndroidReaderContext*) f->data;
	ms_message("get_fps=%f ",ms_average_fps_get(&d->averageFps));
	*((float*)arg) = ms_average_fps_get(&d->averageFps);
	return 0;
}

I  get frame rate 8fps or 9 fps, why?

Thanks
Best Regards.

**Comment by Viish** [comment]
Old issue I'm closing it, feel free to reopen with logs if it still happens with 4.2 release
