### ISSUE TITLE
issue in outgoing calls

### ISSUE THREAD

**Issue by Vivektilva** [BelledonneCommunications/linphone-android#684]
i am making outgoing calls with  core.inviteAddressWithParams(address,callParams);
and for 1st time it is working fine and in LinphoneService class i am getting events onCallStateChanged.

but after 8-10 mins i am making call again with same method and call is not going through. in this case in onCallStateChanged method , i am getting 'Error' in Call.State and 'Request timeout' in message .

Can you tell me when lib get this error message ?
and solution for that?

PS: in onRegistrationStateChanged last RegistrationState was 'OK'.

Attaching logs of CoreListenerStub if it helps .
[lp_log_1.txt](https://github.com/BelledonneCommunications/linphone-android/files/3280469/lp_log_1.txt)

**Comment by Viish** [comment]
As you can see there is 30 secs in which your request isn't answered:
```
06-12 14:13:07.970 13975-13975/com.callhippo.bueno.callhippo E/LinphoneService: call_state: OutgoingProgress message: Outgoing call in progress
06-12 14:13:39.996 13975-13975/com.callhippo.bueno.callhippo E/LinphoneService: call_state: Error message: Request timeout
```

Check the server logs to see why your call doesn't get an answer.

**Comment by Vivektilva** [comment]
I did not get any request at other end for call. 
And one strange thing i notice , if i off-on internet after this issue .  outgoing call is working .

When i do that i am getting onRegistrationStateChanged: OK and when i make call after that it is working fine .
