### ISSUE TITLE
Voice is not audible in some devices while it is working perfectly in incoming calls?

### ISSUE THREAD

**Issue by im-ranu** [BelledonneCommunications/linphone-android#686]
While making outgoing call i'm unable to hear early media as well as audio and while incoming it is working perfectly in some devices like redmi, vivo. Call is receiving on other end.

Using latest snapshot 4.2+ android

**Here is two logs with audio outgoing call when network is changed and with no audio outgoing call.**

[no_audio.txt](https://github.com/BelledonneCommunications/linphone-android/files/3297293/no_audio.txt)
[audio.txt](https://github.com/BelledonneCommunications/linphone-android/files/3297297/audio.txt)

**Comment by Viish** [comment]
Indeed you don't receive audio.
`2019-06-17 19:02:28.365 15681-15681/com.callhippo.bueno.callhippo I/CallHippo: received                                      0 packets`
Open an issue on linphone repository if need be.
