### ISSUE TITLE
(feature request) add a filter to increase voice pitch

### ISSUE THREAD

**Issue by bruceleerabbit** [BelledonneCommunications/linphone-android#687]
Sometimes I'm talking to someone with a low pitch muffled voice and it's quite hard to understand what they are saying. This problem is often with male voices and sometimes lousy equipment on the other end is part of the problem.  It could be resolved by a filter in the VOIP client that would increase the other person's voice pitch. Ideally it would be an on-demand control that could be adjusted mid-conversation.

**Comment by Viish** [comment]
Sorry we won't do that.
