### ISSUE TITLE
Local Contacts Creation

### ISSUE THREAD

**Issue by farhat97** [BelledonneCommunications/linphone-android#688]
Is there a way to create contacts within the Linphone platform, and not have them be added to the phone's phonebook? Because I have been using the method createContact() from LinphoneContact, however, I need contacts to remain to the application's phonebook only.

**Comment by Viish** [comment]
As you can see in the createContact method, if the write contact permission has been granted we create a native android contact.
If you don't want that, either don't grant the contact permission or edit the code to not do it.
