### ISSUE TITLE
How to add push notifications token

### ISSUE THREAD

**Issue by DroidPulkit** [BelledonneCommunications/linphone-android#690]
In order for app to connect with Kamilio server, I am using LinphoneAccountCreator, but when editing custom proxy and adding to the class above, it is not being added to the sip headers during registration. Does the server does not get any device token to send the push notification. Any work around?

**Comment by DroidPulkit** [comment]
Update:- If we edit proxy Config in LinphoneAccountCreator, it will not update the proxy at all and the default contact headers are sent. 
Other way is to add custom ProxyConfig and custom AuthInfo to the core

**Comment by Viish** [comment]
Check https://github.com/BelledonneCommunications/linphone-android/blob/master/app/src/main/java/org/linphone/settings/LinphonePreferences.java#L713

**Comment by uniruddh** [comment]
Hi @Viish With kotlin version the `FirebaseMessaging` has been moved into sdk and there is no method to get the push token. What would you suggest in this case if app need to get the device token?
