### ISSUE TITLE
LinphoneService has leaked IntentReceiver org.linphone.core.tools.InteractivityReceiver@bd98f98 that was originally registered here. Are you missing a call to unregisterReceiver()?

### ISSUE THREAD

**Issue by Vivektilva** [BelledonneCommunications/linphone-android#692]
whenever app goes into background state , after few minutes  it gives this error.
[New Text Document.txt](https://github.com/BelledonneCommunications/linphone-android/files/3324796/New.Text.Document.txt)

refere #479 

PS: using org.linphone:linphone-sdk-android:4.2-52-g2798f74'

**Comment by Viish** [comment]
That's because you don't call Core.stop() when the Service is destroyed.
