### ISSUE TITLE
incoming call to app  during cellular call 

### ISSUE THREAD

**Issue by bharathikrify** [BelledonneCommunications/linphone-android#693]
When a user is on Android cell call.  Not using app.
   Then app gets incoming call, the app is not aware
   that mobile call is in progress.
   The app takes away the audio, and interrupts the call.
   App should either go directly to missed call
   or App should act ask call waiting but not interfere
   with the cellular call.

**Comment by Viish** [comment]
Actually that is what we do.
However there was a bug with the phone state listener that was only registered while a call through the app was established, so if there was a previous GSM call it wouldn't know about it.
Fix is in 0c875fc4e998b0ede7843668808c5e0f2c8403b5
