### ISSUE TITLE
Call Hang-up Problem

### ISSUE THREAD

**Issue by farhat97** [BelledonneCommunications/linphone-android#696]
I recently found out that whenever I accept a call and the person calling me hangs up, the call remains active (with no sound since the person already hung up, of course) for about 20 seconds. However, if I am the one who started the call and the other person hangs up, it works with no problems.

Does anyone have an idea of where this problem could be?

Thank you!

**Comment by Seejun** [comment]
I meet the same problem too.But if accept the call,one of the person who try hung up,the call will hung up at once.

**Comment by Viish** [comment]
This is probably a network issue, the BYE packet not reaching the remote end.

**Comment by m-akopov** [comment]
I face the same exact problem. Could not fix it in any way
