### ISSUE TITLE
Phone number issue

### ISSUE THREAD

**Issue by bharathikrify** [BelledonneCommunications/linphone-android#697]
Hi Team ,
I am facing an issue as 
When trying to dial +65123456789 it is going call to +6523456789

**Comment by Viish** [comment]
Hi,
From which country is this phone number from ?

**Comment by bharathikrify** [comment]
india

**Comment by Viish** [comment]
India's prefix is +91, +65 would be Singapore.

**Comment by bharathikrify** [comment]
numbers are truncating basedon countrycode.Thank you
