### ISSUE TITLE
How to set up the loudspeaker in the latest version

### ISSUE THREAD

**Issue by 1191102363** [BelledonneCommunications/linphone-android#699]
mCore.enableSpeaker(true)   not found

**Comment by Viish** [comment]
You can't handle that with linphone, you have to use the Android AudioManager.
mAudioManager.setSpeakerphoneOn(true);

**Comment by 1191102363** [comment]
thanks 


------------------ 原始邮件 ------------------
发件人: "Sylvain Berfini"<notifications@github.com>;
发送时间: 2019年7月1日(星期一) 下午3:33
收件人: "BelledonneCommunications/linphone-android"<linphone-android@noreply.github.com>;
抄送: "edward"<1191102363@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [BelledonneCommunications/linphone-android] How to set up theloudspeaker in the latest version (#699)




You can't handle that with linphone, you have to use the Android AudioManager.
 mAudioManager.setSpeakerphoneOn(true);
