### ISSUE TITLE
resource no found

### ISSUE THREAD

**Issue by shixinglingguihua** [BelledonneCommunications/linphone-android#7]
at linphone-android project/res/raw/rootca is leak but at  class org.linphone.LinphoneManager this resource is used    "copyIfNotExist(R.raw.rootca, mLinphoneRootCaFile);"

**Comment by DatBewar** [comment]
Hello, the **rootca** is create when you execute **make**.
But yes, we should copy every time this **rootca**, if it was ever changed.

**Comment by DatBewar** [comment]
Fixed 798d472b46a64407288fcbdf9a1f3fd7b579d765

**Comment by DatBewar** [comment]
Fix an error in this commit.
25fc9e4445845ae0bc2ecfa65d6a4b0932c2ed3a

**Comment by shixinglingguihua** [comment]
ok thanks
