### ISSUE TITLE
SSL with my server 

### ISSUE THREAD

**Issue by fedesenmartin** [BelledonneCommunications/linphone-android#70]
**Hi 

Im trying to connect to a ssl server of my own ,and I get:**

@"_kCFStreamErrorCodeKey" : (int)-9802	

**here is my code:**
    NSURL *url = [NSURL URLWithString:url];

    AFHTTPSessionManager *manager = [[AFHTTPSessionManager alloc] initWithBaseURL:url ];
//    AFSecurityPolicy *securityPolicy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModePublicKey];

    manager.securityPolicy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModeCertificate];

    manager.securityPolicy.allowInvalidCertificates = YES;
    
    
    [manager GET:@"path" parameters:nil success:^(NSURLSessionDataTask *task, id responseObject)
    {
        // Success
        NSLog(@"Success: %@", responseObject);
    }failure:^(NSURLSessionDataTask *task, NSError *error)
    {
        // Failure
        NSLog(@"Failure: %@", error);
    }];

**I added the cer files to the bundle and also to linphone-Info this->**
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>

Thats the correct info.plist ?

Sorry to put on this ,but at afnetworking have no luck!

**Comment by DatBewar** [comment]
Hi, open this on the right repository
https://github.com/BelledonneCommunications/linphone-iphone
