### ISSUE TITLE
how to work with multiple SIP (provider)?

### ISSUE THREAD

**Issue by Vivektilva** [BelledonneCommunications/linphone-android#700]
Hi, 

Currently i have two provider and i want to get incoming calls to get on both SIP .

When i register in sdk , if i register with multiple username and password , is it possible to get incoming calls on both SIP?

**Comment by Viish** [comment]
Hi,
Yes you will receive calls for each account you configure.
Best regards.

**Comment by Vivektilva** [comment]
Thanks for info.

One more question , if i want to make outgoing call to one of them , how can i select account ?

**Comment by Viish** [comment]
If they are on different domains, the right one will be selected automatically.
If they are on the same domain, the default proxy config will be used.

**Comment by Vivektilva** [comment]
they are on different domain . i want to select manually to place outgoing call, any way for that?

**Comment by Viish** [comment]
Let's assume you have an account 101@domain1.tld and an account toto@domain2.tld.
No matter which one is the default, if you call someone that is on domain1.tld the first one will be used, if you call someone on domain2.tld the second one will be used, and if you call someone on any other domain the default one will be used.

**Comment by Vivektilva** [comment]
1st and 2nd case are understood.
Now question is in 3rd case , as you said default one will be user but i want to use based on domain , so is there any way in 3rd case where i can set proxy setting before making outgoing calls or change account setting before making outgoing calls?

if no , any changes in upcoming release for this kind of development ?

**Comment by Viish** [comment]
For the third case there is no other way than to change the default proxy config before making the call if you want to handle that yourself.
