### ISSUE TITLE
Move to android.telecom Connection for call handling

### ISSUE THREAD

**Issue by vpr1982** [BelledonneCommunications/linphone-android#704]
Are there any plans to migrate to iOS Callkit style Android call handling due to issues particularly with wear os which don't receive any notifications and ringing not being handled correctly?

**Comment by Viish** [comment]
Your WearOs device should receive the notifications correctly as the one we create are "standard".
Anyway if you want you can test our development branch on which we did integrate the "Android CallKit" named TelecomManager: feature/use_android_native_dialer
