### ISSUE TITLE
Incoming call drops at 30 second just after changing package name.

### ISSUE THREAD

**Issue by mehran22k** [BelledonneCommunications/linphone-android#705]
Hi there
When i change the package name  in android studio, calls terminated at 30 second.

I try to debug :

in, incoming call, i see this Error:

**Dialog [0xb8022820] was not ACK'd within T1*64 seconds, it is going to be terminated.**

But if I uncheck push notification then the problem solved but i don't want to disable push notification.

Im interested why its work perfectly when package name is "org.Linphone" but after changing the package name in gradle  I face this issue

Thanks for your attention.

**Comment by Viish** [comment]
This is not a package name issue.
You simply don't receive the ACK (which is also unrelated with the push notification).
It is most probably a network issue (I guess you are using UDP, switch to TCP or TLS and it will be solved).

**Comment by antun3s** [comment]
> This is not a package name issue.
> You simply don't receive the ACK (which is also unrelated with the push notification).
> It is most probably a network issue (I guess you are using UDP, switch to TCP or TLS and it will be solved).

Thank you a lot bro.
It worked!
