### ISSUE TITLE
can't find "push_sender_id" in non_localizable_custom.xml file for change to project id?

### ISSUE THREAD

**Issue by raviteja74** [BelledonneCommunications/linphone-android#706]

**Comment by Viish** [comment]
On master branch it has changed.
Now we use gcm_defaultSenderId string that is provided by the google-services.json directly.

**Comment by raviteja74** [comment]
Hii Viish but i am not getting push notifications with my own google_services.json file with my own package name...

**Comment by Viish** [comment]
Is your google-services.json correctly configured to match your server configuration ?
Note that you can't have push notifications with your own package while using our sip.linphone.org server.

**Comment by raviteja74** [comment]
Thanks for reply Viish...... And I changed Background mode value to true then i get a call when app even kill but after few minutes i didn't get any call..(It happens same in linphone app downloaded from playstore) 
 what happens after few minutes not getting notification call Please help me Viish ......
