### ISSUE TITLE
no work with reverse tethering (internet connection by pc)

### ISSUE THREAD

**Issue by hippokk** [BelledonneCommunications/linphone-android#709]
Hi,
linphone (4.1) no work when I use a pc for access internet by reverse tethering using gnirehtet
 program on linux pc (https://github.com/Genymobile/gnirehtet). Of course, I have internet on other apps and linphone work properly with wifi. On motorola x play, android 7.1.1. 

Thanks!

**Comment by Viish** [comment]
Hi,
Please try latest beta from play store (or build a version using a recent SDK) and tell me if you still have it, it should be fixed now.
