### ISSUE TITLE
Lib connection via TCP not working in Samsung Galaxy S6

### ISSUE THREAD

**Issue by svprdga** [BelledonneCommunications/linphone-android#710]
I am testing Linphone in one app, I connect with my server via TCP. In all the devices works everything ok but in a Samsung Galaxy S6 in which the lib is trying to connect to the server via UDP instead of TCP - I have UDP blocked, I strictly need TCP.

I force TCP connection setting the following transport values to the Core object:

`
Transports transports = mCore.getTransports();
 transports.setUdpPort(0);
 transports.setTlsPort(0);
 transports.setTcpPort(TCP_PORT);
 mCore.setTransports(transports);
`

I don't understand why this is working in all devices (including Samsung S5, S7, S9) but it's not working in a couple of S6 devices I have, the stacktrace:

> Launching lib/main.dart on SM G920F in debug mode...
> [{"event":"app.progress","params":{"appId":"c0d61638-d4b3-4ba1-9395-8d8a56a32943","id":"0","progressId":null,"message":"Initializing gradle..."}}]Initializing gradle...
> 
> [{"event":"app.progress","params":{"appId":"c0d61638-d4b3-4ba1-9395-8d8a56a32943","id":"1","progressId":null,"message":"Resolving dependencies..."}}]Resolving dependencies...
> 
> [{"event":"app.progress","params":{"appId":"c0d61638-d4b3-4ba1-9395-8d8a56a32943","id":"2","progressId":null,"message":"Running Gradle task 'assembleDebug'..."}}]Running Gradle task 'assembleDebug'...
> 
> Built build/app/outputs/apk/debug/app-debug.apk.
> [{"event":"app.progress","params":{"appId":"c0d61638-d4b3-4ba1-9395-8d8a56a32943","id":"3","progressId":null,"message":"Installing build/app/outputs/apk/app.apk..."}}]Installing build/app/outputs/apk/app.apk...
> 
> D/ViewRootImpl@32784fc[BridgeActivity](21641): Relayout returned: oldFrame=[0,0][1440,2560] newFrame=[0,0][1440,2560] result=0x1 surface={isValid=true 533335263232} surfaceGenerationChanged=false
> D/SurfaceView(21641): Relayout returned: oldFrame=[0,0][1440,2560] newFrame=[0,0][1440,2560] result=0x1 surface={Surface(name=null)/@0x48939da isValid=true 533335248896}
> D/ViewRootImpl@32784fc[BridgeActivity](21641): MSG_RESIZED_REPORT: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=1
> D/ViewRootImpl@32784fc[BridgeActivity](21641): MSG_WINDOW_FOCUS_CHANGED 1
> D/ViewRootImpl@32784fc[BridgeActivity](21641): mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true 533335263232}
> V/InputMethodManager(21641): Starting input: tba=android.view.inputmethod.EditorInfo@6aa3e0b nm : com.xxx.xxx ic=null
> I/InputMethodManager(21641): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
> D/InputTransport(21641): Input channel constructed: fd=90
> V/InputMethodManager(21641): Starting input: tba=android.view.inputmethod.EditorInfo@ce5f4e8 nm : com.xxx.xxx ic=null
> [{"event":"app.progress","params":{"appId":"c0d61638-d4b3-4ba1-9395-8d8a56a32943","id":"4","progressId":null,"message":"Syncing files to device SM G920F..."}}]Syncing files to device SM G920F...
> 
> I/SimplePermission(21641): Requesting permission : android.permission.READ_EXTERNAL_STORAGE
> D/ViewRootImpl@32784fc[BridgeActivity](21641): MSG_WINDOW_FOCUS_CHANGED 0
> D/ViewRootImpl@32784fc[BridgeActivity](21641): MSG_WINDOW_FOCUS_CHANGED 1
> D/ViewRootImpl@32784fc[BridgeActivity](21641): mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true 533335263232}
> I/SimplePermission(21641): Requesting permission status : 3
> D/ViewRootImpl@32784fc[BridgeActivity](21641): Relayout returned: oldFrame=[0,0][1440,2560] newFrame=[0,0][1440,2560] result=0x1 surface={isValid=true 533335263232} surfaceGenerationChanged=false
> D/ViewRootImpl@32784fc[BridgeActivity](21641): Relayout returned: oldFrame=[0,0][1440,2560] newFrame=[0,0][1440,2560] result=0x1 surface={isValid=true 533335263232} surfaceGenerationChanged=false
> I/SimplePermission(21641): Requesting permission : android.permission.RECORD_AUDIO
> D/ViewRootImpl@32784fc[BridgeActivity](21641): MSG_WINDOW_FOCUS_CHANGED 0
> D/ViewRootImpl@32784fc[BridgeActivity](21641): MSG_WINDOW_FOCUS_CHANGED 1
> D/ViewRootImpl@32784fc[BridgeActivity](21641): mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true 533335263232}
> I/SimplePermission(21641): Requesting permission status : 3
> D/ViewRootImpl@32784fc[BridgeActivity](21641): Relayout returned: oldFrame=[0,0][1440,2560] newFrame=[0,0][1440,2560] result=0x1 surface={isValid=true 533335263232} surfaceGenerationChanged=false
> D/xxx_bridge(21641): Native - INIT
> I/xxx_bridge(21641): Bound to LinphoneService.
> E/BluetoothHeadset(21641): BTStateChangeCB is registed
> D/xxx_bridge(21641): LinphoneService connected.
> W/FactoryImpl(21641): Unable to load optional library ffmpeg-linphone: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.xxx.xxx-2/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.xxx-2/lib/arm64, /data/app/com.xxx.xxx-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libffmpeg-linphone.so"
> I/libcore (21641): Using (r/w) config information from /data/user/0/com.xxx.xxx/files/.linphonerc
> I/libcore (21641): Reading config information from /data/user/0/com.xxx.xxx/files/linphonerc
> I/libcore (21641): Initializing LinphoneCore 3.12.0-3111-gf83d6c4a7
> I/libcore (21641): Sal nat helper [enabled]
> I/libcore (21641): [Device] hasLowLatencyFeature: false, hasProFeature: false
> I/libcore (21641): [Device] Output frames per buffer: 240, output sample rates: 48000 for OpenSLES MS sound card.
> I/libcore (21641): Starting copy from assets to application files directory
> I/libcore (21641): Copy from assets done
> I/libcore (21641): Starting copy from legacy  resources to application files directory
> I/libcore (21641): App doesn't seem to embed resource cpim_grammarin it's res/raw/ directory. Make sure this file is either brought as an asset or a resource
> I/libcore (21641): Resource identifier null for target [cpim_grammar]
> I/libcore (21641): App doesn't seem to embed resource vcard_grammarin it's res/raw/ directory. Make sure this file is either brought as an asset or a resource
> I/libcore (21641): Resource identifier null for target [vcard_grammar]
> I/libcore (21641): App doesn't seem to embed resource notes_of_the_optimisticin it's res/raw/ directory. Make sure this file is either brought as an asset or a resource
> I/libcore (21641): Resource identifier null for target [notes_of_the_optimistic.mkv]
> I/libcore (21641): App doesn't seem to embed resource holdin it's res/raw/ directory. Make sure this file is either brought as an asset or a resource
> I/libcore (21641): Resource identifier null for target [dont_wait_too_long.mkv]
> I/libcore (21641): Copy from legacy resources done
> I/libcore (21641): bellesip_wake_lock_init(): initialization succeed
> I/libcore (21641): AndroidPlatformHelpers is fully initialised.
> I/libcore (21641): Mediastreamer2 factory 2.16.1 (git: 2.16.1-477-g5de9bb40) initialized.
> I/libcore (21641): CPU count set to 8
> I/libcore (21641): ms_factory_init() done: platform_tags=linux,android,x86,embedded
> I/libcore (21641): srtp init
> I/libcore (21641): SDK version [24] detected
> I/ACodec  (21641):  [] Now uninitialized
> I/ACodec  (21641): [] onAllocateComponent
> I/OMXClient(21641): MuxOMX ctor
> I/ACodec  (21641): Set Google AAC Dec for aacProfile 0
> I/ACodec  (21641): [OMX.Exynos.AVC.Encoder] Now Loaded
> I/libcore (21641): Codec video/avc successfully created.
> I/ACodec  (21641):  [OMX.Exynos.AVC.Encoder] Now uninitialized
> I/ACodec  (21641):  [] Now kWhatShutdownCompleted event : 8438
> I/MediaCodec(21641): Codec shutdown complete
> I/ACodec  (21641):  [] Now uninitialized
> I/ACodec  (21641): [] onAllocateComponent
> I/OMXClient(21641): MuxOMX ctor
> I/ACodec  (21641): Set Google AAC Dec for aacProfile 0
> I/ACodec  (21641): [OMX.Exynos.avc.dec] Now Loaded
> I/libcore (21641): Codec video/avc successfully created.
> I/ACodec  (21641):  [OMX.Exynos.avc.dec] Now uninitialized
> I/ACodec  (21641):  [] Now kWhatShutdownCompleted event : 8438
> I/MediaCodec(21641): Codec shutdown complete
> I/libcore (21641): MediaCodec: 'video/avc' format supported
> I/ACodec  (21641):  [] Now uninitialized
> I/ACodec  (21641): [] onAllocateComponent
> I/OMXClient(21641): MuxOMX ctor
> I/ACodec  (21641): Set Google AAC Dec for aacProfile 0
> I/ACodec  (21641): [OMX.Exynos.HEVC.Encoder] Now Loaded
> I/libcore (21641): Codec video/hevc successfully created.
> I/ACodec  (21641):  [OMX.Exynos.HEVC.Encoder] Now uninitialized
> I/ACodec  (21641):  [] Now kWhatShutdownCompleted event : 8438
> I/MediaCodec(21641): Codec shutdown complete
> I/ACodec  (21641):  [] Now uninitialized
> I/ACodec  (21641): [] onAllocateComponent
> I/OMXClient(21641): MuxOMX ctor
> I/ACodec  (21641): Set Google AAC Dec for aacProfile 0
> I/ACodec  (21641): [OMX.Exynos.hevc.dec] Now Loaded
> I/libcore (21641): Codec video/hevc successfully created.
> I/ACodec  (21641):  [OMX.Exynos.hevc.dec] Now uninitialized
> I/ACodec  (21641):  [] Now kWhatShutdownCompleted event : 8438
> I/MediaCodec(21641): Codec shutdown complete
> I/libcore (21641): MediaCodec: 'video/hevc' format supported
> I/libcore (21641): Registering all soundcard handlers
> I/libcore (21641): SDK version [24] detected
> I/libcore (21641): Native android sound support not tested on SDK [24], disabled.
> I/libcore (21641): libOpenSLES correctly loaded, creating OpenSLES MS soundcard
> I/libcore (21641): This device (samsung/SM-G920F/exynos5) declares it has a built-in echo canceller.
> I/libcore (21641): Found information for [samsung/SM-G920F/exynos5] from internal table
> I/libcore (21641): Sound device information for [samsung/SM-G920F/exynos5] is: builtin=[yes], delay=[0] ms
> I/libcore (21641): This device (samsung/SM-G920F/exynos5) declares it has a built-in echo canceller.
> I/libcore (21641): Found information for [samsung/SM-G920F/exynos5] from internal table
> I/libcore (21641): Sound device information for [samsung/SM-G920F/exynos5] is: builtin=[yes], delay=[0] ms
> I/libcore (21641): Card 'openSLES: android sound card' added with capabilities [capture, playback]
> I/libcore (21641): SDK version [24] detected
> I/libcore (21641): This device (samsung/SM-G920F/exynos5) declares it has a built-in echo canceller.
> I/libcore (21641): Found information for [samsung/SM-G920F/exynos5] from internal table
> I/libcore (21641): Sound device information for [samsung/SM-G920F/exynos5] is: builtin=[yes], delay=[0] ms
> I/libcore (21641): Card 'ANDROID SND (deprecated): Android Sound card' added with capabilities [capture, playback]
> I/libcore (21641): Registering all webcam handlers
> I/libcore (21641): Detecting Android VIDEO cards
> I/libcore (21641): getHelperClassGlobalRef (env: 0x7c54a41000)
> I/libcore (21641): Android SDK version found is 24
> I/CameraManagerGlobal(21641): Connecting to camera service
> I/libcore (21641): 2 cards detected
> I/libcore (21641): Android VIDEO capture filter cam init
> I/libcore (21641): Webcam Android0 added
> I/libcore (21641): camera created: id=0 frontFacing=0 orientation=90 [msid:Android0]
> I/libcore (21641): Android VIDEO capture filter cam init
> I/libcore (21641): Webcam Android1 added
> I/libcore (21641): camera created: id=1 frontFacing=1 orientation=270 [msid:Android1]
> I/libcore (21641): Detection of Android VIDEO cards done
> I/libcore (21641): Webcam StaticImage: Static picture added
> I/libcore (21641): MSAndroidDisplay registered.
> I/libcore (21641): MSAndroidDisplay (OpenGL ES2) registered (id=80).
> I/libcore (21641): ms_factory_init_voip() done
> I/libcore (21641): Loading ms plugins from [/data/app/com.xxx.xxx-2/lib/arm64]
> I/libcore (21641): Loading plugin /data/app/com.xxx.xxx-2/lib/arm64/libmswebrtc.so...
> I/libcore (21641): libmswebrtc 1.1.1 plugin loaded, iSAC codec version 3.6.0, iLBC codec version 1.1.1
> I/libcore (21641): Plugin loaded (/data/app/com.xxx.xxx-2/lib/arm64/libmswebrtc.so)
> I/libcore (21641): Core callbacks [0x7c2a0731e0] registered on core [0x7c54bffa00]
> I/libcore (21641): oRTP-1.0.2 initialized.
> I/libcore (21641): Codec opus/48000 fmtp=[useinbandfec=1] number=-1, default enablement: 16) added to the list of possible codecs.
> I/libcore (21641): Codec SILK/16000 fmtp=[] number=-1, default enablement: 16) added to the list of possible codecs.
> I/libcore (21641): Codec speex/16000 fmtp=[vbr=on] number=-1, default enablement: 16) added to the list of possible codecs.
> I/libcore (21641): Codec speex/8000 fmtp=[vbr=on] number=-1, default enablement: 16) added to the list of possible codecs.
> I/libcore (21641): Codec PCMU/8000 fmtp=[] number=0, default enablement: 16) added to the list of possible codecs.
> I/libcore (21641): Codec PCMA/8000 fmtp=[] number=8, default enablement: 16) added to the list of possible codecs.
> I/libcore (21641): Codec red/1000 fmtp=[] number=-1, default enablement: 16) added to the list of possible codecs.
> I/libcore (21641): Codec t140/1000 fmtp=[] number=-1, default enablement: 16) added to the list of possible codecs.
> I/libcore (21641): Codec GSM/8000 fmtp=[] number=3, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec G722/8000 fmtp=[] number=9, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec iLBC/8000 fmtp=[mode=30] number=-1, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec AMR/8000 fmtp=[octet-align=1] number=-1, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec AMR-WB/16000 fmtp=[octet-align=1] number=-1, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec G729/8000 fmtp=[annexb=yes] number=18, default enablement: 16) added to the list of possible codecs.
> I/libcore (21641): Codec mpeg4-generic/16000 fmtp=[config=F8EE2000; constantDuration=512; indexDeltaLength=3; indexLength=3; mode=AAC-hbr; profile-level-id=76; sizeLength=13; streamType=5] number=-1, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec mpeg4-generic/22050 fmtp=[config=F8EE2000; constantDuration=512; indexDeltaLength=3; indexLength=3; mode=AAC-hbr; profile-level-id=76; sizeLength=13; streamType=5] number=-1, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec mpeg4-generic/32000 fmtp=[config=F8E82000; constantDuration=512; indexDeltaLength=3; indexLength=3; mode=AAC-hbr; profile-level-id=76; sizeLength=13; streamType=5] number=-1, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec mpeg4-generic/44100 fmtp=[config=F8E82000; constantDuration=512; indexDeltaLength=3; indexLength=3; mode=AAC-hbr; profile-level-id=76; sizeLength=13; streamType=5] number=-1, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec mpeg4-generic/48000 fmtp=[config=F8EE2000; constantDuration=512; indexDeltaLength=3; indexLength=3; mode=AAC-hbr; profile-level-id=76; sizeLength=13; streamType=5] number=-1, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec iSAC/16000 fmtp=[] number=-1, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec speex/32000 fmtp=[vbr=on] number=-1, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec SILK/8000 fmtp=[] number=-1, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec SILK/12000 fmtp=[] number=-1, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec SILK/24000 fmtp=[] number=-1, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec G726-16/8000 fmtp=[] number=-1, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec G726-24/8000 fmtp=[] number=-1, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec G726-32/8000 fmtp=[] number=-1, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec G726-40/8000 fmtp=[] number=-1, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec AAL2-G726-16/8000 fmtp=[] number=-1, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec AAL2-G726-24/8000 fmtp=[] number=-1, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec AAL2-G726-32/8000 fmtp=[] number=-1, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec AAL2-G726-40/8000 fmtp=[] number=-1, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec CODEC2/8000 fmtp=[] number=-1, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec BV16/8000 fmtp=[] number=-1, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec VP8/90000 fmtp=[] number=-1, default enablement: 16) added to the list of possible codecs.
> I/libcore (21641): Codec H264/90000 fmtp=[profile-level-id=42801F] number=-1, default enablement: 16) added to the list of possible codecs.
> I/libcore (21641): Codec H265/90000 fmtp=[] number=-1, default enablement: 16) added to the list of possible codecs.
> I/libcore (21641): Codec MP4V-ES/90000 fmtp=[profile-level-id=3] number=-1, default enablement: 16) added to the list of possible codecs.
> I/libcore (21641): Codec H263-1998/90000 fmtp=[CIF=1;QCIF=1] number=-1, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec H263/90000 fmtp=[] number=34, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec 1016/8000 fmtp=[] number=1, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec G723/8000 fmtp=[] number=4, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec LPC/8000 fmtp=[] number=7, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec L16/44100 fmtp=[] number=10, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec L16/44100 fmtp=[] number=11, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec CN/8000 fmtp=[] number=13, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec H261/90000 fmtp=[] number=31, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Codec MPV/90000 fmtp=[] number=32, default enablement: 0) added to the list of possible codecs.
> I/libcore (21641): Root ca path set to /system/etc/security/cacerts
> I/libcore (21641): Root ca path set to /system/etc/security/cacerts
> I/libcore (21641): getDnsServers() returning
> I/libcore (21641): AndroidPlatformHelpers found DNS server 192.168.10.1
> I/libcore (21641): AndroidPlatformHelpers found DNS server 192.168.24.25
> I/libcore (21641): Cannot open directory ./lib/liblinphone/plugins: No such file or directory
> W/libcore (21641): '/data/data/org.linphone/files/oldphone_mono.wav' ring file does not exist
> I/libcore (21641): linphone_core_set_playback_gain_db(): no active call.
> I/libcore (21641): linphone_core_set_mic_gain_db(): no active call.
> I/libcore (21641): Sal nat helper [enabled]
> I/libcore (21641): Sal use rports [enabled]
> I/libcore (21641): MTU is supposed to be 1300, rtp payload max size will be 1240
> I/libcore (21641): Could not find encoder for SILK
> I/libcore (21641): Could not find decoder for SILK
> I/libcore (21641): Could not find encoder for AMR
> I/libcore (21641): Could not find decoder for AMR
> I/libcore (21641): Could not find encoder for AMR-WB
> I/libcore (21641): Could not find decoder for AMR-WB
> I/libcore (21641): Could not find encoder for mpeg4-generic
> I/libcore (21641): Could not find decoder for mpeg4-generic
> I/libcore (21641): Could not find encoder for mpeg4-generic
> I/libcore (21641): Could not find decoder for mpeg4-generic
> I/libcore (21641): Could not find encoder for mpeg4-generic
> I/libcore (21641): Could not find decoder for mpeg4-generic
> I/libcore (21641): Could not find encoder for mpeg4-generic
> I/libcore (21641): Could not find decoder for mpeg4-generic
> I/libcore (21641): Could not find encoder for mpeg4-generic
> I/libcore (21641): Could not find decoder for mpeg4-generic
> I/libcore (21641): Could not find encoder for SILK
> I/libcore (21641): Could not find decoder for SILK
> I/libcore (21641): Could not find encoder for SILK
> I/libcore (21641): Could not find decoder for SILK
> I/libcore (21641): Could not find encoder for SILK
> I/libcore (21641): Could not find decoder for SILK
> I/libcore (21641): Could not find encoder for G726-16
> I/libcore (21641): Could not find decoder for G726-16
> I/libcore (21641): Could not find encoder for G726-24
> I/libcore (21641): Could not find decoder for G726-24
> I/libcore (21641): Could not find encoder for G726-32
> I/libcore (21641): Could not find decoder for G726-32
> I/libcore (21641): Could not find encoder for G726-40
> I/libcore (21641): Could not find decoder for G726-40
> I/libcore (21641): Could not find encoder for AAL2-G726-16
> I/libcore (21641): Could not find decoder for AAL2-G726-16
> I/libcore (21641): Could not find encoder for AAL2-G726-24
> I/libcore (21641): Could not find decoder for AAL2-G726-24
> I/libcore (21641): Could not find encoder for AAL2-G726-32
> I/libcore (21641): Could not find decoder for AAL2-G726-32
> I/libcore (21641): Could not find encoder for AAL2-G726-40
> I/libcore (21641): Could not find decoder for AAL2-G726-40
> I/libcore (21641): Could not find encoder for CODEC2
> I/libcore (21641): Could not find decoder for CODEC2
> I/libcore (21641): Could not find encoder for BV16
> I/libcore (21641): Could not find decoder for BV16
> I/libcore (21641): Could not find encoder for 1016
> I/libcore (21641): Could not find decoder for 1016
> I/libcore (21641): Could not find encoder for G723
> I/libcore (21641): Could not find decoder for G723
> I/libcore (21641): Could not find encoder for LPC
> I/libcore (21641): Could not find decoder for LPC
> I/libcore (21641): Could not find encoder for CN
> I/libcore (21641): Could not find decoder for CN
> I/libcore (21641): Could not find encoder for MP4V-ES
> I/libcore (21641): Could not find decoder for MP4V-ES
> I/libcore (21641): Could not find encoder for H263-1998
> I/libcore (21641): Could not find decoder for H263-1998
> I/libcore (21641): Could not find encoder for H263
> I/libcore (21641): Could not find decoder for H263
> I/libcore (21641): Could not find encoder for H261
> I/libcore (21641): Could not find decoder for H261
> I/libcore (21641): Could not find encoder for MPV
> I/libcore (21641): Could not find decoder for MPV
> I/libcore (21641): Supported codec red/1000 fmtp= automatically added to codec list.
> I/libcore (21641): Supported codec t140/1000 fmtp= automatically added to codec list.
> I/libcore (21641): Sal use rports [enabled]
> I/libcore (21641): Root ca path set to /data/user/0/com.xxx.xxx/files/share/linphone/rootca.pem
> I/libcore (21641): Sal::unlistenPorts(): done
> I/libcore (21641): Creating listening point [0x7c29df8a00] on [sip:0.0.0.0:5060;transport=TCP]
> E/libcore (21641): TCP listen() failed for 0.0.0.0 port 5060: Address already in use
> I/libcore (21641): Listening point [0x7c29df8a00] on [sip:0.0.0.0:5060;transport=TCP] destroyed
> I/libcore (21641): linphone_proxy_config_is_server_config_changed : 0
> I/libcore (21641): Publish params have changed on proxy config [0x7c54a44a80]
> I/libcore (21641): Core callbacks [0x7c437dbe50] registered on core [0x7c54bffa00]
> D/linphone_service(21641): Core listener - Global State Changed: Starting up
> I/libcore (21641): Linphone core [0x7c54bffa00] notified [global_state_changed]
> I/libcore (21641): Opening linphone database: /data/user/0/com.xxx.xxx/files/linphone.db
> I/libcore (21641): Start measurement of [Get chat rooms.].
> I/libcore (21641): Start transaction 0x7fe2506dd0 in MainDb::getChatRooms.
> I/libcore (21641): Commit transaction 0x7fe2506dd0 in MainDb::getChatRooms.
> I/libcore (21641): Duration of [Get chat rooms.]: 0ms.
> I/libcore (21641): Root ca path set to /data/user/0/com.xxx.xxx/files/share/linphone/rootca.pem
> D/linphone_service(21641): Core listener - Global State Changed: Configuring
> I/libcore (21641): Linphone core [0x7c54bffa00] notified [global_state_changed]
> D/linphone_service(21641): Core listener - On Configuring Status
> I/libcore (21641): Linphone core [0x7c54bffa00] notified [configuring_status]
> D/ConnectivityManager(21641): requestNetwork; CallingUid : 10213, CallingPid : 21641
> D/linphone_service(21641): Core listener - Global State Changed: Ready
> I/libcore (21641): Linphone core [0x7c54bffa00] notified [global_state_changed]
> I/libcore (21641): Root ca path set to /data/user/0/com.xxx.xxx/files/rootca.pem
> I/libcore (21641): SIP network reachability state is now [DOWN]
> I/libcore (21641): Reseting transports
> I/libcore (21641): Media network reachability state is now [DOWN]
> D/linphone_service(21641): Core listener - On Network Reachable
> I/libcore (21641): Linphone core [0x7c54bffa00] notified [network_reachable]
> I/libcore (21641): Connectivity has changed.
> I/libcore (21641): getDnsServers() returning
> I/libcore (21641): AndroidPlatformHelpers found DNS server 192.168.10.1
> I/libcore (21641): AndroidPlatformHelpers found DNS server 192.168.24.25
> I/libcore (21641): SIP network reachability state is now [UP]
> I/libcore (21641): Media network reachability state is now [UP]
> D/linphone_service(21641): Core listener - On Network Reachable
> I/libcore (21641): Linphone core [0x7c54bffa00] notified [network_reachable]
> D/xxx_bridge(21641): Native - LOGIN with username: 1007, password: xxx, server: pbx301.xxx.com
> I/libcore (21641): linphone_proxy_config_is_server_config_changed : 0
> I/libcore (21641): Publish params have changed on proxy config [0x7c54a44900]
> I/libcore (21641): LinphoneProxyConfig [0x7c54a44900] about to register (LinphoneCore version: 3.12.0-3111-gf83d6c4a7)
> I/libcore (21641): get_jni_env(): thread successfuly attached
> I/libcore (21641): bellesip_wake_lock_acquire(): Android wake lock [belle-sip transaction(0x7c2a1d2140)] acquired [ref=0x1009de]
> I/libcore (21641): transaction [0x7c2a1d2140]: starting transaction background task with id=[1009de].
> E/libcore (21641): No listening point matching for [udp://pbx301.xxx.com:5060]
> E/libcore (21641): belle_sip_client_transaction_send_request(): no channel available
> I/libcore (21641): Changing [client] [REGISTER] transaction [0x7c2a1d2140], from state [INIT] to [TERMINATED]
> I/libcore (21641): Client REGISTER transaction [0x7c2a1d2140] terminated
> I/libcore (21641): Unhandled transaction terminated [0x7c2a1d2140]
> I/libcore (21641): transaction [0x7c2a1d2140]: ending transaction background task with id=[1009de].
> I/libcore (21641): bellesip_wake_lock_release(): Android wake lock released [ref=0x1009de]
> I/libcore (21641): Proxy config [0x7c54a44900] for identity [sip:1007@pbx301.xxx.com] moving from state [LinphoneRegistrationNone] to [LinphoneRegistrationFailed] on core [0x7c54bffa00]
> D/linphone_service(21641): Core listener - On Registration State Changed: Registration failed
> D/xxx_bridge(21641): Registration - FAILED
> I/libcore (21641): Linphone core [0x7c54bffa00] notified [registration_state_changed]

**Comment by Viish** [comment]
What happens here is you try to create a TCP socket on port 5060. For some reason (probably another app) this port is already taken.
Unless you want to do peer to peer call on this port, use -1 as transport value instead of 5060 to use a random free port for the local socket.

**Comment by svprdga** [comment]
In the same device, with the same server, same credentials; I can connect via TCP using Linphone app. When I switch to my app (obviously disabling the linphone account) occurrs the error, how can another app using this port but in Linphone app works ok?

By the way, I have configured the VoIP server to allow only TCP connections via 5060, so it's impossible for the Linphone app to use another port.

**Comment by Viish** [comment]
You are mixing up two things: the local port of your socket in the phone and the port your server listen to.
Even if your server listen to 5060 (which is standard for SIP), you don't have to listen on this same port for the local socket (except if you intend to do peer to peer, in which case you must know the port you will send the call to).
As 5060 can be used by other SIP clients (when they could use another one), we strongly recommend you use a random one.
