### ISSUE TITLE
[2 bugs] Can't answer incoming call after navigation

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-android#712]
It appears that there is a bug that prevents answering incoming calls when navigated to the home screen first.

Steps to reproduce:
- Initiate an incoming call but **not do not answer it**.
- Navigate to the home screen by using Android's home button.
- Re-open Linphone. Keypad is displayed. Click the lower button to go to the active call.
--> **Bug 1:** linphone suggests that the call is accepted and speaker is enabled. Ringtone is still being played since we didn't actually answer the call.
--> **Bug 2:** afterwards if the next call is **outgoing**, it is in speaker mode.

Linphone is using SDK 4.2-66-g98c8593 (not latest but very recent).

**Comment by Viish** [comment]
Hi,
The Bug1 is fixed in commit: 6e8d2cf7dd47963d2dbac5238534a50e84aa5518
I believe Bug2 will disapear with it.
Cheers,
