### ISSUE TITLE
Not negotiating direct RTP streams using sip.linphone.org

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#714]
I have linphone 4.1 registered to sip.linphone.org and I have my SIP proxy/PBX forwarding calls to my linphone's local extension to sip.linphone.org.

It's all working fine except that even when an extension on the same local network as my linphone phone calls my linphone phone through my SIP proxy, the SIP session through sip.linphone.org works fine but the RTP between linphone and my SIP proxy, which are on the same local network is set up and routed through sip.linphone.org and not directly with each other.

I'd fully expect that linphone and my SIP proxy, through sip.linphone.org should be able to negotiate an RTP session that stays on the local network and gets sip.linphone.org out of the middle.  I do have ICE enabled on both my SIP proxy and linphone, so there should be lots of opportunity for them to find each other on the local network.

A [log](http://brian.interlinx.bc.ca/linphone-not-rtping-locally.txt) of such a call.

**Comment by Viish** [comment]
SDK issue, not Android
