### ISSUE TITLE
in DOZE MODE do not worked

### ISSUE THREAD

**Issue by wkg** [BelledonneCommunications/linphone-android#719]
optimize battery - turned OFF!
linphone service - turned ON!

i have not gapps, test in last version in "master"
BUT after hour idle, linphone disconnect from server:
```
07-20 19:31:01.649 15731 15731 I Linphone: [Platform Helper] Doze mode enabled: true
07-20 19:31:01.649 15731 15731 I Linphone: [Platform Helper] Device idle mode: true
07-20 19:31:01.649 15731 15731 I Linphone: [Platform Helper] Device in idle mode: shutting down network
07-20 19:31:01.653 15731 15731 I Linphone: SIP network reachability state is now [DOWN]
07-20 19:31:01.655 15731 15731 I Linphone: Refresher [0x7d07fd8e40] stopped.
07-20 19:31:01.655 15731 15731 I Linphone: Destroying op [0x7d1c15ac00] of type [SalOpRegister]
07-20 19:31:01.655 15731 15731 I Linphone: Refresher [0x7d07fd8e40] stopped.
07-20 19:31:01.655 15731 15731 I Linphone: Transaction [0x7d07aa1240] deleted
07-20 19:31:01.656 15731 15731 I Linphone: Transaction [0x7d07fd9080] deleted
07-20 19:31:01.656 15731 15731 I Linphone: Proxy config [0x7d1c06ee00] for identity [sip:@] moving from state [LinphoneRegistrationOk] to [LinphoneRegistrationNone] on core [0x7d1c0dd800]
07-20 19:31:01.657 15731 15731 I Linphone: [Manager] New registration state [None]
07-20 19:31:01.657 15731 15731 I Linphone: Linphone core [0x7d1c0dd800] notified [registration_state_changed]
07-20 19:31:01.657 15731 15731 I Linphone: Reseting transports
07-20 19:31:01.657 15731 15731 I Linphone: Listening point destroying [1] channels
07-20 19:31:01.657 15731 15731 I Linphone: channel 0x7d07cafec0: state DISCONNECTED
07-20 19:31:01.657 15731 15731 I Linphone: Channel [0x7d07cafec0] destroyed
07-20 19:31:01.658 15731 15731 I Linphone: Media network reachability state is now [DOWN]
07-20 19:31:01.658 15731 15731 I Linphone: Linphone core [0x7d1c0dd800] notified [network_reachable]
```

"Conversations"(xmpp), "k-9"(imap) -- normal work in Doze, linphone - not.

**Comment by Viish** [comment]
Actually this is expected.
When you are in doze mode, we prevent the app from connecting to the SIP server because it will fail anyway since it won't be able to use the network.
Your problem is we use push notifications to wake the app up if needed, and as you don't have gapps you won't have the push.

**Comment by wkg** [comment]
Why "Conversations" normal used network in Doze without push? And "k-9" normal used network without push? 
I can't used push!
but you can  linphone do not down network connection? optionally may be

**Comment by wkg** [comment]
In Doze apps can't use network IF they optimized for battery! Why do you forcibly disconnect yourself I do not understand.... apps CAN use network without battery optimized!

**Comment by wkg** [comment]
Sorry for my bad english, hope you understand me

**Comment by Viish** [comment]
That shall fix it: https://gitlab.linphone.org/BC/public/linphone/merge_requests/408

**Comment by wkg** [comment]
Thank you!

**Comment by wkg** [comment]
Builded SDK and APK with it fix, it work OK! Thank you again! Awaiting f-droid release with this fix.

**Comment by Viish** [comment]
You're very welcome :)
