### ISSUE TITLE
OpenH264 Codec support

### ISSUE THREAD

**Issue by shuiko1** [BelledonneCommunications/linphone-android#72]
I download the source code and success compile with the OpenH264 codec enabled. 
But when I install the APK to my device I can't see the OpenH264 codec option. 
Only has the vp8 codec. 
can you tell me why? Thanks

**Comment by DatBewar** [comment]
Hi,
you can find more information about H264 on our Wiki:
https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Codec%20H264%20on%20Android/

**Comment by shuiko1** [comment]
@DatBewar  Thanks I got it.
And I also want more help. It's about the server.
I use OpenSips + linphone. When I dial each other it can success at the first several times.
But after about one hour. It's easy to get this: When I dial the sip address. 
The courter number can't get the request though the register status show it's online. 
But I notice when I dial the number, the courter linphone just change the register statu from registered --> registering---> registered. just never get the request dialing. 
when I use the flexisip + linphone. through several test I never got the problem. so I thank it's just the server problem. or maybe the linphone didn't implement something.
can you tell me why? thanks.
I also working on it    -.-
