### ISSUE TITLE
Not adding IPv6 candidates to ICE negotiations

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#722]
When linphone-android is running on a device that has IPv6 addresses, and responding to an INVITE from Flexisip, the ICE negotiation that it's sending does not include IPv6 candidates.  This is a regression.  I know I have seen linphone-android doing that before.

A [log](http://brian.interlinx.bc.ca/linphone-not-using-ipv6-ice.txt) of such a call.

Of course, being able to use IPv6 is particularly important for SIP with all of the broken NAT that exists out there.

**Comment by Viish** [comment]
SDK issue, not Android
