### ISSUE TITLE
rootca.pem ignored in /res/raw

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-android#723]
It looks like in the latest releases, "rootca.pem" is ignored when present in app/src/main/res/raw/. Instead, a version from the sdk is taken instead?

After every "assembleRelease", "rootca.pem" is overwritten, so I was wondering how I can preserve this file? I was thinking of adding something like this to the app/build.gradle, but it's also overwritten:

```
task copyRootca(type: Copy) {
    from 'rootca.pem'
    into "build/intermediates/merged_assets/release/out/org.linphone.core/share/linphone/"
}

assembleRelease.dependsOn 'copyRootca'
```

Is there a better solution?

**Comment by Viish** [comment]
Hi,
Indeed we package a rootCA.pem file in our SDK.
If you want to use your own, package it and install it (with a different name) and set it either:
- in the rc_file in the root_ca property of the [sip] section
- call linphone_core_set_root_ca
Cheers,

**Comment by czaviar** [comment]
> If you want to use your own, package it and install it (with a different name) and set it either:
> 
> * in the rc_file in the root_ca property of the [sip] section
> * call linphone_core_set_root_ca

@Viish - if I understood correctly there is a third option:
* concatenate our own CA into rootca.pem in linphone-sdk/liblinphone/share and build our own SDK

I  did the third way, build the SDK under macOS  and the result is:  works under iOS and fails under Android.  Any idea why ? And what can I do do more in android to avoid declaring verify_server_certs=0 ?

**Comment by Viish** [comment]
I'm not familiar with that part but it is possible the build process updates the file (and thus overrides your changes) or takes it from somewhere else.
I checked and the file is overidden at each start of the app, so if changes are made they will be applied correctly.
That's why I still recommend you to embed your own certificate in a separated file and bundle it in your app.

**Comment by czaviar** [comment]
> If you want to use your own, package it and install it (with a different name) and set it either:
> 
> * in the rc_file in the root_ca property of the [sip] section

@Viish I have tried putting it in res/raw, unfortunately it doesn't work. Where exactly my-own-ca.pem shall be put and which file shall be edited linphonerc_factory or linphonerc_default ?

**Comment by Viish** [comment]
Put your cert file in res/raw, copy the file on the device (look at LinphonePreferences.copyFromPackage() method) and then set the path where you copied it to your config file or through the API (mCore.setUserCertificatesPath(mUserCertsPath);)

**Comment by czaviar** [comment]
@Viish thanks ! Now I get the idea.  But delivering 2 files (.apk and .pem) to end user makes everything more complicated. 

That is why the best option would be to concatenate my own CA during the SDK compilation. That's what I did it and it works on iOS, but not on Android.

**Comment by driesken** [comment]
Would be great if we could just supply the client cert and key within the xml during provisioning with the assistant (remote configuration). Would also prevent copying the pem files to another device.

**Comment by Viish** [comment]
Indeed this can't be done directly by the rc file, but you can do it in code using AuthInfo.setTlsCert() and AuthInfo.setTlsKey()
