### ISSUE TITLE
App crash when we use sdk

### ISSUE THREAD

**Issue by Vivektilva** [BelledonneCommunications/linphone-android#724]
We are using below sdk of linphone for our android app:
 implementation 'org.linphone:linphone-sdk-android:4.2-52-g2798f74'

We have approx 300 Active users and in our report we noticed 5-6 crash every day and here is the log of crash :

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List android.net.LinkProperties.getDnsServers()' on a null object reference
       at org.linphone.core.tools.AndroidPlatformHelper.storeDnsServers + 589(AndroidPlatformHelper.java:589)
       at org.linphone.core.tools.AndroidPlatformHelper.updateNetworkReachability + 646(AndroidPlatformHelper.java:646)
       at org.linphone.core.tools.NetworkManagerAbove26$1.onCapabilitiesChanged + 76(NetworkManagerAbove26.java:76)
       at android.net.ConnectivityManager$CallbackHandler.handleMessage + 3331(ConnectivityManager.java:3331)
       at android.os.Handler.dispatchMessage + 106(Handler.java:106)
       at android.os.Looper.loop + 214(Looper.java:214)
       at android.app.ActivityThread.main + 6990(ActivityThread.java:6990)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 493(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main + 1445(ZygoteInit.java:1445)

Can you provide a solution , looks like this is something related to sdk.

**Comment by Viish** [comment]
Hi,
Can you capture the logs from the library (enable them in advanced section of settings) and attach them here please ?
Thanks.

**Comment by Vivektilva** [comment]
I am not able to re-produce this issue in my system . i get this logs in firebase crash report .

**Comment by Viish** [comment]
At least do you have info like device name and Android version running ?

**Comment by Vivektilva** [comment]
yes i do have.

Brand: samsung
Model: Galaxy Note9
OS Version: 9
Rooted: No
RAM free: 2.09 GB
Orientation: Portrait

just FYI : this crash has been noticed in android version 7.1, 8.0 and 9. but in most case this is happening with Android 9.

**Comment by Viish** [comment]
I don't understand why this can happen.
Here's the code that crashes from your stacktrace:
`private synchronized void storeDnsServers(Network activeNetwork) {
		mDnsServers = null;

		if (activeNetwork == null || mConnectivityManager.getLinkProperties(activeNetwork) == null) {
			Log.e("[Platform Helper] Active network is null or we can't get it's link properties");
			return;
		}

		List<InetAddress> inetServers = null;
		inetServers = mConnectivityManager.getLinkProperties(activeNetwork).getDnsServers();
		updateDnsServers(inetServers);
	}`
As you can see there is a first check to know if mConnectivityManager.getLinkProperties(activeNetwork) is null or not, and if it is null we return.
I don't see how it could crash at this line
`inetServers = mConnectivityManager.getLinkProperties(activeNetwork).getDnsServers();`
because the getLinkProperties returned null...

**Comment by Vivektilva** [comment]
As per above code , it should not crash . but it still crashing as per firebase crash report .

Could be any other reason ? or any solution to avoid this?

**Comment by Viish** [comment]
Hi,
Can you try to build a linphone SDK on the branch fix/android_network_manager_crashes and tell me if it still happens please ?

**Comment by Vivektilva** [comment]
i am using 
org.linphone:linphone-sdk-android:4.2-52-g2798f74

is there update version with fix so i can implement and check ?

**Comment by Viish** [comment]
Try with 4.2-103-g321092b
