### ISSUE TITLE
build Error due to Windows

### ISSUE THREAD

**Issue by wuxuan2811** [BelledonneCommunications/linphone-android#726]
Build as README.md in Win7, then build error.Why can't build in Windows
-- Found PythonInterp: C:/Python27/python.exe (found version "2.7.15")
-- 'pystache' python module found
-- 'six' python module found
CMake Error at cmake/LinphoneSdkCheckBuildToolsAndroid.cmake:27 (message):
  You need to use a Linux or Mac OS X system to build for Android
Call Stack (most recent call first):
  cmake/LinphoneSdkPlatformAndroid.cmake:24 (include)
  CMakeLists.txt:70 (include)

**Comment by Viish** [comment]
Currently we don't support the build of Android SDK on Windows.
