### ISSUE TITLE
Bug in DialerActivity on Intent

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-android#727]
I'm using a modified version of DialerActivity which handles an extra ACTION_VIEW intent. This was working fine untill [this commit](https://github.com/BelledonneCommunications/linphone-android/commit/b9e14f1fa5d321af6ede9eabad56f2385f8d230a#diff-3afda59849904807872cab7a7bd5430f) where the onDestroy() was added.

It appears that onDestroy() sets mAddress to null and results in an error when receiving an intent in this block specifically (line 319):
`mAddress.setText(addressToCall);`

Error:
`java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.EditText.setText(java.lang.CharSequence)' on a null object reference`

**Comment by Viish** [comment]
Hi,
I guess your problem is the DialerActivity get's destroyed before the asynclayoutinflater finished.
Check your added intent handler to see why.
