### ISSUE TITLE
It doesn't uses the turn information when ICE is enabled

### ISSUE THREAD

**Issue by tahirjilani** [BelledonneCommunications/linphone-android#73]
@DatBewar 
It doesn't look like it uses the turn information when ICE is enabled. 

I am doing like below:
```
linphonePreferences.setStunServer(turnServerUrl);
linphonePreferences.setTurnPassword(turnPassword);
linphonePreferences.setTurnUsername(turnUserName);
linphonePreferences.setIceEnabled(true);
```

on the other hand if i enable stun like the following:
`linphonePreferences.setTurnEnabled(true); `
linphone stops sending ice candidates in sdp.

Will appreciate a quick lead.

**Comment by Viish** [comment]
Old issue, I'm closing it. Feel free to reopen if it still applies with version 4.2.
