### ISSUE TITLE
Can't choose a country and can't back out

### ISSUE THREAD

**Issue by schultzter** [BelledonneCommunications/linphone-android#731]
When trying to link a phone number to my SIP account (linphone.org or my VoIP provider) when I tap on the default country (American Samoa) to choose my actual country it gets stuck on the Choose a country screen, I can't choose the country and I pressing the back arrow at the top left or the back button on my phone doesn't do anything!?

Samsung Galaxy S8 running Android 9 and Linphone v.4.1.1

**Comment by Viish** [comment]
Hi,
I don't reproduce your issue (with latest master).
Could you try it (it's the public beta version on the Play Store) or attach logs please.

**Comment by schultzter** [comment]
Ok, I've joined the beta and tried it with VoIP provider account - it pre-populated my country and the device's mobile phone number. But when I click the **LINK ACCOUNT** button I get 
> **Error** 
> Unknown error

But it works perfectly when I link my Linphone account. 

I assume it's only supported on Linphone accounts? Perhaps the option should be greyed out or hidden completely on non-Linphone SIP accounts? 

Thanks.

**Comment by Viish** [comment]
Indeed you can't link a non-linphone account.
I'll see what I can do to prevent that mistake.
