### ISSUE TITLE
Can't activate four digit validation to link phone number to account

### ISSUE THREAD

**Issue by schultzter** [BelledonneCommunications/linphone-android#732]
I've tried linking my linphone account to my phone number, and I received the four digit validation code but after I entered it and tapped the Activate button nothing happens and I can't even back out - I have to kill the Linphone app and re-open it. The same thing happens when I try to link the SIP account from my VoIP provider to my phone number. 

Samsung Galaxy S8 running Android 9 and Linphone v.4.1.1

**Comment by schultzter** [comment]
Also note that I've tried to recover my password using my phone number (all three phone numbers I could have used) and in every case it says _Phone number not found_.

**Comment by Viish** [comment]
I close this issue as we don't support linking phone numbers with accounts that aren't sip.linphone.org.
