### ISSUE TITLE
Video is not working on H264 Codec on Android < 5.1

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#733]
I have latest linphone android code from git hub. But Video is not working on H264 Codec on Android < 5.1.

**Comment by Viish** [comment]
Yes that's because we use Android's media codec implementation of H264 and it isn't available before Android 5.1

**Comment by amit1576** [comment]
Dear @Viish ,

But in old Linphone application versioned **4.0.1**, the video calling is working fine on Android 5. Still the Android app available on your website is working(means Video Calling) on Android 5, whereas the latest apk available in google app store not working on Android 5.(video calling).
