### ISSUE TITLE
Outgoing call issue !

### ISSUE THREAD

**Issue by Vivektilva** [BelledonneCommunications/linphone-android#735]
Hi,

We had some issue in outgoing calls for iOS (in android it is working fine) , calls were not able to go through our provider which we are using , here is reply from our provider , it is related to codec , can you please help us.

Reply from Our provider:

" I checked the samples you have provided and I could observe few things in the calls which have failed.
The main reason for calls failing is because of the mismatch in codec negotiation.
Plivo accepts the call only on PCMU 0 and 8 ( g711).
The calling agent is sending an invite with the codec's 97 98 99 100 0 8 101.
But is missing to send the media attribute description for either 0 or 8, since the codec is not described our servers are rejecting the call.
To fix the issue you will have to send at least one of the codecs in the media attributes only then the calls will be processed"

It there any thing we can change in code to overcome this issue ?

**Comment by Viish** [comment]
Hi,
Have you tried to disable all codecs except for PCMU and PCMA ?

**Comment by Vivektilva** [comment]
Hi ,
How to disable codecs via code?
Can you help me with code ?

**Comment by Viish** [comment]
In our Android app we have a audio settings menu where you can do it.
Here's it's code:
https://github.com/BelledonneCommunications/linphone-android/blob/master/app/src/main/java/org/linphone/settings/AudioSettingsFragment.java#L214

**Comment by Vivektilva** [comment]
In android it is working fine(as mentioned in 1st comment ), i am having issue in iOS app .
Anything you can help with iOS code?

**Comment by Viish** [comment]
Sorry I haven't noticed that.
No I can't help much about iOS, please open the ticket in the iOS project.

**Comment by Vivektilva** [comment]
okay thanks for this info , already raised issue in iOS project but no reply 
anyway thanks.
