### ISSUE TITLE
Display name for chat message

### ISSUE THREAD

**Issue by atulsethi** [BelledonneCommunications/linphone-android#737]
Hi ,
Not able to fetch display name when i am receiving msg on
@override
public void onMessageReceived(Core lc, ChatRoom cr, ChatMessage message)

in above function i am getting sip url without display name
but in log, i am receiving that like below

From: "Atul" <sip:1234@abc.in>;tag=0be51040-30fb-4e98-889f-f853808c1053
To: <sip:234@122.123.123.123>

**Comment by Viish** [comment]
Hi,
What code do you use to try to get the display name in this callback ?

**Comment by atulsethi** [comment]
Hi ,
   Thanks for your reply .Please check below 

Address from = message.getFromAddress();
   String DisaplyName=  from.getDisplayName()

and i was trying to get display name from chat room object also 
 cr.getPeerAddress().getDisplayName()
     cr.getLocalAddress().getDisplayName()   

but did not get same as above.

**Comment by Viish** [comment]
That looks correct to me.
I'll see if I can reproduce the issue.

**Comment by Viish** [comment]
I don't reproduce it.
