### ISSUE TITLE
Will the Linphone SDK continually be open source?

### ISSUE THREAD

**Issue by zj299792458** [BelledonneCommunications/linphone-android#739]
I can see Linphone SDK source code is replaced by AAR lib from maven. Just wondering if I can find the complete source code and its compile script somewhere else? Thank you.

**Comment by licaon-kter** [comment]
The code is here: https://gitlab.linphone.org/BC/public/linphone-sdk build your own.

The maven repo is for devs that don't want to bother compiling.

**Comment by Viish** [comment]
Thanks @licaon-kter, I couldn't have said it better.
