### ISSUE TITLE
ICE candidates gathering does timeout ramdonly because Linphone does not reply to the TURN server

### ISSUE THREAD

**Issue by pacodesaroqueta** [BelledonneCommunications/linphone-android#74]
Hello,

linphone randomly does a burst a calls where it gets timeout negotiating turn candidates.  Then it recovers without doing anything. If we do a call from another device at same moment using the same SIP user it works OK. Any clue of what could be? 

According to the log we observe that it has no problem to connect with the TURN server, but the client stops a few seconds before answering. 

In attachment both logs, one with correct established call, and the other with a not established call.   Any recommendation on server side?   It is happening for both, Android and iOS.

[Succeeded call.txt](https://github.com/BelledonneCommunications/linphone-android/files/1059343/Succeeded.call.txt)
[Failed call.txt](https://github.com/BelledonneCommunications/linphone-android/files/1059345/Failed.call.txt)

Thanks a lot, your help will be very important.

**Comment by vitalikvoip** [comment]
Does it support TURN at all?
It looks like mediastreamer2 does support TURN, but I haven't found it in the GTK based linux application.

**Comment by Viish** [comment]
Old issue, I'm closing it. Feel free to reopen on SDK repository if it still applies with version 4.2.
