### ISSUE TITLE
Audio conference not working properly, Local gets audio from both calls but remote's dont get any.

### ISSUE THREAD

**Issue by armrs** [BelledonneCommunications/linphone-android#741]
I have 2 calls, one paused automatically by the system when LinphoneManager.getLc().invite() gets called, and the other is in the "StreamsRunning" State, then i try to add them both to a conference with 
```
LinphoneManager.getLc().addToConference(SecondCall);
LinphoneManager.getLc().addToConference(FirstCall);
```
[I have also tried with addAllToConference()].
And the result is 2 remote calls in StreamsRunning state not receiving any kind of audio but i can still hear them both in the local phone.

**Comment by Viish** [comment]
Hi,
Can you attach logs from the device that hosts the conference please ?
Cheers,
