### ISSUE TITLE
The Video is receiving only at QVGA(320*240). No matter sender sending video on higher Resolutions.

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#742]
Hi @Viish ,

**With Reference to Trailing issue #738 .**

As discussed with you earlier, linphone android app(Video Receiving) is not working on above mentioned android devices. For experiment i tried the same android app on **"Tinker board SBC"**, where i have the possibility to customize the android. I had found same video receiving problem on **"Tinker board SBC"** as well, then i found that Media Codec API was disabled by defaults, which causing Video receiving problem as linphone uses Media Codec API. As soon as i enabled them the Video Receiving problem got resolved on **"Tinker board SBC"**. I suspect my other device also has Media Codec Disabled.

**But now one another observation, The Video is receiving only at QVGA(320*240). No matter sender sending video on higher resolutions. Where as Android Mobile to Mobile no such issue ever observed.**

Request you to help me out.

For reference i have attached two file. First one is on Samsung Phone while Second one is on the **"Tinker board SBC"**.

![App on samsung mobile](https://user-images.githubusercontent.com/5437700/63211269-ab5bc100-c112-11e9-84dd-b89c4e30f456.jpg)

![App on Tinker board](https://user-images.githubusercontent.com/5437700/63211270-b0207500-c112-11e9-9868-45cf6859e5a2.jpg)

**Comment by Viish** [comment]
Attach logs from your device that says only receives 240x320 video please.

**Comment by amit1576** [comment]
Dear @Viish ,

Please find attached Logs. 

What happening is that When Sender turn his phone from portrait mode to landscape mode the Receiving Resolution got changed at Receiver end and the split screen issue start coming. But as soon as Sender again change his landscape mode from Landscape to Portrait the videos get perfect.

**One More issue Video Call is working only on 320*240 Resolution.**

Logs and video has been attached for the same.

[Message.txt](https://github.com/BelledonneCommunications/linphone-android/files/3525762/Message.txt)

**Video Format MP4, i am not able to attach. Kindly provide any email id where i can share the video.**

**Comment by amit1576** [comment]
[](url)

**Comment by amit1576** [comment]
Hi @Viish ,

Any suggestions.

**Comment by Viish** [comment]
The problem comes from the app on your phone.

Does it call correctly core.setDeviceRotation ?
https://github.com/BelledonneCommunications/linphone-android/blob/master/app/src/main/java/org/linphone/activities/LinphoneGenericActivity.java#L77

I've tried with linphone-android master branch, I don't have this issue even if I block the rotation of my device in portrait.

**Comment by amit1576** [comment]
Dear @Viish ,

I agree, If i block device rotation in portrait mode the above issue is handled in **linphone-android master branch**. But i had some devices where linphone application can be run only in landscape mode. On these devices i am still facing split screen issue as sender is in landscape mode.

Please suggest.

**Comment by Viish** [comment]
Do you have the problem with linphone-android master branch without the portrait lock ?

**Comment by amit1576** [comment]
Yes.

**Sender without portrait mode lock and sender in landscape mode both have same problem means Split screen at receiver end** as i send you in previous comments.

**Comment by amit1576** [comment]
Hi @Viish ,

Any Suggestion.

**Comment by amit1576** [comment]
Hi @Viish ,

Can you try this scenario with two tablet both in landscape mode. Hope you may be able to re-produce the issue.
