### ISSUE TITLE
How to restore the call when the device holds

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#748]
HI,

When device A invites device B and device C, then B and C have caller bells at the same time, but B has hold music, Now I let B answers, at the same time, I'll hang up C. but B also is hold status , and no audio, How to get A and B to talk normally when B answers。

thanks.

**Comment by fengqz627** [comment]
I also try "LinphoneManager.getLc().resumeCall(call); " when StreamsRunning, but resumeCall() can't use now.

**Comment by Viish** [comment]
Hi,
You can't resume a call that isn't Paused.
But if B is receiving a call but playing ringing music it means there is something wrong with it.
What is it's call state ?

**Comment by fengqz627** [comment]
Because A calls B and C in turn， B receives invite first, should be in HOLD, C  has not HOLD music, I try to delete Hold music, so B doesn't play HOLD music again.

private void copyAssetsFromPackage() throws IOException {
		Log.i("Starting copy from assets to application files directory");
		copyAssetsFromPackage(mContext, "org.linphone.core",".");
		Log.i("Copy from assets done");
		Log.i("Starting copy from legacy  resources to application files directory");
		/*legacy code for 3.X*/
		copyEvenIfExists(getResourceIdentifierFromName("cpim_grammar"), mGrammarCpimFile);
		copyEvenIfExists(getResourceIdentifierFromName("vcard_grammar"), mGrammarVcardFile);
		copyEvenIfExists(getResourceIdentifierFromName("rootca"), mLinphoneRootCaFile);
		copyEvenIfExists(getResourceIdentifierFromName("notes_of_the_optimistic"), mRingSoundFile);
		copyEvenIfExists(getResourceIdentifierFromName("ringback"), mRingbackSoundFile);
		// copyEvenIfExists(getResourceIdentifierFromName("hold"), mPauseSoundFile);
		copyEvenIfExists(getResourceIdentifierFromName("incoming_chat"), mErrorToneFile);

**Comment by fengqz627** [comment]
Now resumeCall() and pauseCall（） display Unusable Displays, My linphone is 4.0.1

**Comment by Viish** [comment]
If you have installed a version on B previously the hold music will be there even if you comment out the copy of the file.
Either delete the file from your phone or delete the app and install it again with the commented version.

**Comment by fengqz627** [comment]
Now the problem is that machine B with HOLD music answers and hangs up other receivers, but there is no sound on A and B talks. I think B is still in HOLD state, how to convert to normal call state？

**Comment by Viish** [comment]
First of all, you should wait for B to answer before calling C.
Second, you should update to the latest release instead of using an old one.
Finally, to resume a paused call you must call call.resume() in the client that paused the call.

**Comment by fengqz627** [comment]
thank you very much.
