### ISSUE TITLE
Add a custom function to linphonesdk with new java wrapper

### ISSUE THREAD

**Issue by balusreekanth** [BelledonneCommunications/linphone-android#749]
I added a  small function to  bellesip C code  and added related entry to linphonecore_jni.cc  and built linphone-android-sdk. On documentation page it said that wrapper will be generated automatically for native functions . But After building AAR and added  that to the linphone project I can not see my method  in Core methods .  I tried both -DENABLE_JAVA_WRAPPER=NO and -DENABLE_JAVA_WRAPPER=YES .

**Comment by Viish** [comment]
Hi,

Indeed the Java wrapper is generated automatically above C functions but with the following conditions:
- The C function must be in linphone project (not belle-sip so you have to create a function in linphone that calls yours in belle-sip)
- It must be correctly documented following doxygen standard in a public header file of the linphone library
- The Java wrapper must be enabled (-DENABLE_JAVA_WRAPPER=YES but by default on Android target).

The linphonecore_jni.cc is the old wrapper and I strongly don't recommend it. 

Cheers,
