### ISSUE TITLE
under version of android  5.0 ,it must be broken down

### ISSUE THREAD

**Issue by ouzhangyu** [BelledonneCommunications/linphone-android#75]
i'm just import linphoneSDK,and the app always broken down with no exception infomation.
this is the info when app broken down : 

> 06-09 11:43:24.811 1196-1689/? W/AudioPolicyManagerBase: getInput() could not find profile for device 80000004, samplingRate 44100, format 1,channelMask 0010
06-09 11:43:24.811 10908-10908/com.ozy.zjhb E/AudioRecord: Could not get audio input for record source 7
06-09 11:43:24.811 10908-10908/com.ozy.zjhb A/libc: Fatal signal 11 (SIGSEGV) at 0x00000008 (code=1), thread 10908 (com.ozy.zjhb)
06-09 11:43:24.911 1191-1191/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-09 11:43:24.911 1191-1191/? I/DEBUG: Build fingerprint: 'generic_x86/sdk_x86/generic_x86:4.4.2/KK/3462041:eng/test-keys'
06-09 11:43:24.911 1191-1191/? I/DEBUG: Revision: '0'
06-09 11:43:24.911 1191-1191/? I/DEBUG: pid: 10908, tid: 10908, name: com.ozy.zjhb  >>> com.ozy.zjhb <<<

**Comment by DatBewar** [comment]
Hi, i can't help you with no trace. The Sdk on android 5.0 correctly works on our device.

**Comment by ouzhangyu** [comment]
Thanks . I have solved it. The problem is that I didn't load H264 library on under version android 5.0
