### ISSUE TITLE
Received message but didn't post a notification

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#751]
I just had an occurrence of linphone successfully receiving a message and the message was there in linphone to be able to read but there was no notification posted to the notification bar.  The [log](http://brian.interlinx.bc.ca/linphone-didnt-post-notification.txt)

As you will (also) see in the log, it also takes almost 10s for linphone to start up and REGISTER from being killed.  That's **way** too long.  If this were a voice call, the caller would have hung up by now.  But this is probably a separate ticket.

**Comment by Viish** [comment]
Hi,
We are working hard on improving the start-up time after receiving a push notification.
In fact this is the one major improvement that will be in the next 4.2 version. Until the release you can test it from our master branch (both SDK and app).
For your notification issue the logs don't help much, all I can see is indeed you have received a message. I would be interested if you can reproduce this issue on master version.

**Comment by Viish** [comment]
Could it be possible you got the notification but you missed it in the 3 minutes the service was awake ?

**Comment by brianjmurrell** [comment]
The notification is persistent even after the app is killed isn't it?  Persistent until the user dismisses it.

**Comment by Viish** [comment]
It wasn't until last week when I fixed a bug about that.
