### ISSUE TITLE
change rtpmap value to h264

### ISSUE THREAD

**Issue by heroes801** [BelledonneCommunications/linphone-android#753]
Hello,
this is the log when i try to make a video call :

v=0
    o=201 699 3305 IN IP4 10.0.0.7
    s=Talk
    c=IN IP4 10.0.0.7
    t=0 0
    a=rtcp-xr:rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics
    m=audio 7078 RTP/AVP 96 97 98 0 8 18 101 99 100
    a=rtpmap:96 opus/48000/2
    a=fmtp:96 useinbandfec=1
    a=rtpmap:97 speex/16000
    a=fmtp:97 vbr=on
    a=rtpmap:98 speex/8000
    a=fmtp:98 vbr=on
    a=rtpmap:0 PCMU/8000
    a=rtpmap:8 PCMA/8000
    a=rtpmap:18 G729/8000
    a=fmtp:18 annexb=yes
    a=rtpmap:101 telephone-event/48000
    a=rtpmap:99 telephone-event/16000
    a=rtpmap:100 telephone-event/8000
    a=rtcp-fb:* trr-int 1000
    a=rtcp-fb:* ccm tmmbr
    m=video 9078 RTP/AVP 96 97
    a=rtpmap:96 VP8/90000
    **a=rtpmap:97 H264/90000**
    a=fmtp:97 profile-level-id=42801F
    a=rtcp-fb:* trr-int 1000
    a=rtcp-fb:* ccm tmmbr
    a=rtcp-fb:96 nack pli
    a=rtcp-fb:96 nack sli
    a=rtcp-fb:96 ack rpsi
    a=rtcp-fb:96 ccm fir
    a=rtcp-fb:97 nack pli
    a=rtcp-fb:97 ccm fir

I need to change the H264 rtpmap value from 97 to 96.  Is this possible? How can I do this?

Thks.

**Comment by Viish** [comment]
You shouldn't need to do that.
You can try using the linphone_core_set_payload_type_number function (even if it is deprecated) to set the numbers you want for each codec.
