### ISSUE TITLE
Building with options without prepare.py 

### ISSUE THREAD

**Issue by duracellh** [BelledonneCommunications/linphone-android#754]
Hello,

I noticed the readme doesn't cover this, and the other guides seem to reference using prepare.py to input options for the building, but since it is somewhat recently no longer included for some reason, how are options meant to be passed? I have seen in #606 that using cmake is suggested, but I'm not exactly sure how or if this is ideal or a workaround as there is no cmakelists.txt file on git so trying this by default results in it not working as cmake can't find any file and in general it doesn't seem to be documented anywhere.

**Comment by Viish** [comment]
Hi,
prepare.py was the old way of building the SDK, when it was a submodule in the linphone-android project.
Now the SDK isn't included anymore in the app git repository, so there is no longer a need for the prepare.py script.
You can checkout either master or release-4.2 branch of linphone-sdk and linphone-android project and follow the README instructions, they are up-to-date.
