### ISSUE TITLE
How to disable signal incoming call when there is established call

### ISSUE THREAD

**Issue by alexgrek96** [BelledonneCommunications/linphone-android#757]
Hello! My name is Alexandr, i am android developer and try use your Android Liblinphone SDK version 4.0.1, downloaded from official site;

It is great voip stack.
I faced with problem when there is established call and received new  incoming call  occur  strange signal 'piiip ... piiip'

Can you help me how disable/change this signal ?

**Comment by Viish** [comment]
Hi,
I don't know which sound you talk about. 
Are you sure it isn't played by the remote end of the call you paused ?
