### ISSUE TITLE
Destination unreachable 

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#758]
Hi,

I use linphone4.0.1, when device A sends invite to B, but B can't receive invite, I use wireshark tool to capture package, it displays "Destination unreachable (Port unreachable)", Why is that? How to Solve the Problem。

thanks.

**Comment by Viish** [comment]
Hi,
If B can't receive the INVITE, you will have information why in your proxy server logs.
I doubt the application is responsible.

**Comment by fengqz627** [comment]
Hi,
 I find no port to listen on SIP， I don't know why.

root@tulip-p2:/ # netstat -l
netstat -l
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:555             0.0.0.0:*               LISTEN
tcp        0      0 localhost:5037          0.0.0.0:*               LISTEN
tcp        0      0 :::49537                :::*                    LISTEN
tcp        0      0 :::59624                :::*                    LISTEN
tcp        0      0 :::http-alt             :::*                    LISTEN
udp        0      0 :::40924                :::*
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node Path
unix  2      [ ACC ]     STREAM     LISTENING       7421 /dev/socket/zygote_secondary
unix  2      [ ACC ]     STREAM     LISTENING       7174 /dev/socket/property_service
unix  2      [ ACC ]     STREAM     LISTENING       5164 /dev/socket/sayeye
unix  2      [ ACC ]     STREAM     LISTENING       5189 /dev/socket/installd
unix  2      [ ACC ]     STREAM     LISTENING       5203 /dev/socket/adbd
unix  2      [ ACC ]     STREAM     LISTENING       5808 /data/system/ndebugsocket
unix  2      [ ACC ]     SEQPACKET  LISTENING       6278 /dev/socket/logdr
unix  2      [ ACC ]     STREAM     LISTENING       6280 /dev/socket/logd
unix  2      [ ACC ]     STREAM     LISTENING       6287 /dev/socket/cryptd
unix  2      [ ACC ]     STREAM     LISTENING       6290 /dev/socket/vold
unix  2      [ ACC ]     STREAM     LISTENING       4540 @android:debuggerd
unix  2      [ ACC ]     STREAM     LISTENING       6315 /dev/socket/zygote
unix  2      [ ACC ]     STREAM     LISTENING       4572 @android:debuggerd32
unix  2      [ ACC ]     STREAM     LISTENING       6323 /dev/socket/fwmarkd
unix  2      [ ACC ]     STREAM     LISTENING       4534 /dev/socket/gemvary
unix  2      [ ACC ]     STREAM     LISTENING       6326 /dev/socket/mdns
unix  2      [ ACC ]     STREAM     LISTENING       6330 /dev/socket/dnsproxyd
unix  2      [ ACC ]     STREAM     LISTENING       6332 /dev/socket/netd
unix  2      [ ACC ]     STREAM     LISTENING       7441 @jdwp-control
unix  2      [ ACC ]     STREAM     LISTENING       8788 @/data/user/0/com.estrongs.android.pop/files/comm/tool_port
unix  2      [ ACC ]     SEQPACKET  LISTENING       7413 /dev/socket/lmkd
root@tulip-p2:/ #

**Comment by Viish** [comment]
Have you checked your linphone logs ?
Do you use random port feature ?

**Comment by fengqz627** [comment]
Hi，
I browse .linphonerc, random port is used, and I also find an extra "auto_start=1" in [app]. How to Solve the Problem？
[sip]
keepalive_period=30000
sip_port=-1
sip_tcp_port=-1
sip_tls_port=-1
guess_hostname=1
register_only_when_network_is_up=1
auto_net_state_mon=0
auto_answer_replacing_calls=1
ping_with_options=0
use_cpim=1
linphone_specs=groupchat
ipv6_migration_done=1
root_ca=/data/user/0/com.gemvary.outdoor/files/share/linphone/rootca.pem
verify_server_certs=1
verify_server_cn=1
media_encryption=none

[video]
size=720p
device=Android0
framerate=12.000000

[app]
tunnel=disabled
push_notification=1
auto_start=1
activation_code_length=4
prefer_basic_chat_room=1

**Comment by fengqz627** [comment]
Hi，
The problem has been solved. Thank you very much. 
Your reply always hit the nail on the head.
Most sincere admiration。
