### ISSUE TITLE
Call stats empty

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#759]
In the latest 4.1, the call stats display seems to be empty:

![missing stats](http://brian.interlinx.bc.ca/Screenshot_20190904-053258.jpg)

**Comment by Viish** [comment]
When you say latest 4.1, do you mean the release or master branch ?

**Comment by brianjmurrell** [comment]
I mean neither.  I mean release/4.1 branch.

**Comment by Viish** [comment]
It probably has been fixed on master branch already, I don't reproduce it.

**Comment by brianjmurrell** [comment]
Are bug fixes not being ported to the release branch for the next 4.1 release?

**Comment by Viish** [comment]
They usually are but not in case of 4.1 release, too much as changed in the app (I rewrote most of it).

**Comment by brianjmurrell** [comment]
So this bug will go unfixed on 4.1.x and remain unfixed until a new major version is cut from master?

If so, when will that be?

**Comment by Viish** [comment]
Indeed but 4.2 is scheduled for this month, maybe next month at worst.

**Comment by brianjmurrell** [comment]
Just so I am clear, this will be fixed in 4.2 which will come from master, scheduled this month but could delay until next month at worst?

**Comment by Viish** [comment]
This is already fixed in master branch that will be used for 4.2 release scheduled to be released soon, yes.
