### ISSUE TITLE
How to get internet speed during call?

### ISSUE THREAD

**Issue by Vivektilva** [BelledonneCommunications/linphone-android#760]
Hi ,

Is there any function in linphone sdk which returns the internet connection speed in kbps?
or any listner which can give speed at every second during call?

I want to show error message while internet speed is not upto mark during call . so if there any way can you please suggest ?

**Comment by Viish** [comment]
Hi,
You can see the current bandwidth usage for audio/video stream using the call stats.
In oRTP project we have a way to approximate the available bandwidth but it's internal only.
