### ISSUE TITLE
Contacts without phone numbers listed

### ISSUE THREAD

**Issue by Jamie-uni** [BelledonneCommunications/linphone-android#763]
Contacts are listed that contain no phone number. This means that all of my email contacts show up in the contacts list. Can this be easily fixed?
I'm using Linphone 4.1.1 (Fdroid) on Android 9.

**Comment by Viish** [comment]
Hi,
Thanks for reporting it !

I've fixed it in commit d3282648c3925b3e3c97356c8c1361f612bb6b69 (HEAD -> master, origin/master, origin/fix/empty_contact, origin/HEAD, fix/empty_contact)
Author: Sylvain Berfini <sylvain.berfini@belledonne-communications.com>
Date:   Mon Sep 9 10:59:08 2019 +0200
    Fixed contacts without phone or SIP address showing up in list

Best regards.

**Comment by Jamie-uni** [comment]
Thank you so much Viish!! I'm now using the latest build and the fix works beautifully!
All the best

**Comment by Viish** [comment]
You're very welcome :)
