### ISSUE TITLE
Bandwidth config lost after restart app

### ISSUE THREAD

**Issue by basncy** [BelledonneCommunications/linphone-android#764]
Reproduce steps: version 4.1.1
Goto Settings->Video, Set Video preset with "custom", Preferred FPS with "25", and Bandwidth limit in kbits/s with "3096", and press back to save these settings.
If I restart linphone app later, the configuration of Bandwidth limit in kbits/s with "3096" will be restore to "0".

**Comment by Viish** [comment]
Hi,
I confirm the issue, I'll fix it for the next release.
Best regards.

**Comment by basncy** [comment]
Hi,

Thank you. 

This issue also happens on iOS version if I restart the iOS system, and haven't test on other system yet..

BR.

**Comment by Viish** [comment]
Hi,
I fixed it in commit c8d5582ecc6e8ff8417b1de7a0238668e2cd3dbb.
Cheers,
