### ISSUE TITLE
Received SMS are not displayed in message view

### ISSUE THREAD

**Issue by eshattow** [BelledonneCommunications/linphone-android#765]
Received SMS via VoIP.ms service SIP account (with VoIP.ms account beta access enabled and TLS transport) are displayed as they arrive in notifications, but they are not displayed at all in message view after closing the reply view.

If I send a message from Linphone the messages I send will be listed in Linphone messages view but the received replies will not be displayed. This completely breaks message conversations using Linphone.

About screen version information:
Linphone Android 4.1-108-g7818ead2 (debug)
Linphone SDK 4.2-126-gf0497be (remotes/origin/fix/dns_vpn_issue_android)

**Comment by Viish** [comment]
Hi,

Can you enable debug logs in Settings->Advanced, send & receive a message then go in About page, click on upload logs button and copy/paste the link here please ?

Thanks.

**Comment by brianjmurrell** [comment]
@eshattow In case you didn't check, I've filed a duplicate in #766 with logs for @Viish, if you want to follow along there.

**Comment by Viish** [comment]
@eshattow By the way, did you made an update from a previous Linphone Android version or is it a clean install ?
I'd still like to see your logs to confirm it's the same issue as @brianjmurrell .

**Comment by 532910** [comment]
Looks like I've the same issue:
There are no messages at all displayed in messages list:
![image](https://user-images.githubusercontent.com/14617699/65224368-b5832d80-dacb-11e9-933d-eb71230811df.png)
But when I press send a message to a contact I see the thread:
![image](https://user-images.githubusercontent.com/14617699/65224726-6ab5e580-dacc-11e9-8da5-709578f3b789.png)
![image](https://user-images.githubusercontent.com/14617699/65224856-b1a3db00-dacc-11e9-9432-19ab0d281997.png)
![image](https://user-images.githubusercontent.com/14617699/65224863-b49ecb80-dacc-11e9-92ed-29ceadeccc8a.png)

**Comment by Viish** [comment]
Ok I think I know what happens.
Can one of you (or all of you) try to set in your linphonerc_factory the following:
[misc]
hide_chat_rooms_from_removed_proxies=0
Thanks.

**Comment by Viish** [comment]
You also can use linphone-android branch `feature/added_hidden_chat_rooms_settings`, I've added settings for this flag in Chat section.

**Comment by 532910** [comment]
Linphone removes `hide_chat_rooms_from_removed_proxies` from `/data/data/org.linphone/files/linphonerc` after start.
`/data/data/org.linphone/files/linphonerc_factory` is ignored.

**Comment by Viish** [comment]
Actually if you edit the file directly on your phone you must edit `/data/data/org.linphone/files/.linphonerc`.
Or you can edit the linphonerc_factory on your computer, build and install a new version.

**Comment by 532910** [comment]
setting `hide_chat_rooms_from_removed_proxies=0` in `/data/data/org.linphone/files/.linphonerc` make all messages visible!

**Comment by Viish** [comment]
Ok great.
So it's related to issue https://github.com/BelledonneCommunications/linphone-android/issues/605 and all others.

**Comment by brianjmurrell** [comment]
Interesting that #605 has other fallout.  Why not provide an option to only consider the LHS of the recipient address in linphone when collating SMS (SIP MESSAGE) chats then since this problem is growing in it's fallout?

**Comment by Viish** [comment]
Because our library and application are multi accounts, so we need to know to which account a message was sent to to be able to answer using the right account.
The real problem lies in badly configured SIP proxies that are using the IP as domain in the TO header and thus not following the spirit of the SIP RFC.

**Comment by brianjmurrell** [comment]
> The real problem lies in badly configured SIP proxies that are using the IP as domain in the TO header and thus not following the spirit of the SIP RFC.

As I have mentioned before, It's not a **configuration** issue.  It's just not possible to alter the TO in Asterisk to hide the final recipient delivery address behind the Asterisk delivery address.  So Asterisk sets the TO as the _recipients_name_@_receipients_registered_address_ (i.e. the address of the linphone instance) to which it's sending the message.  It frankly doesn't seem at all unreasonable to me TBH.  Asterisk is after-all sending the message TO me@my_linphone, no TO me@my_asterisk_server.  me@my_asterisk_server was the address used by the previous hop to get it to my PBX.  Why should Asterisk behave differently and not re-address the TO to where it's sending the message?

**Comment by brianjmurrell** [comment]
Setting `hide_chat_rooms_from_removed_proxies=0` does make the conversations visible.

But sending a message in one of them still fails to send with the small red circle with the white X in it to the bottom right of the message.

**Comment by Viish** [comment]
> As I have mentioned before, It's not a configuration issue. It's just not possible to alter the TO in Asterisk to hide the final recipient delivery address behind the Asterisk delivery address. So Asterisk sets the TO as the recipients_name@receipients_registered_address (i.e. the address of the linphone instance) to which it's sending the message. It frankly doesn't seem at all unreasonable to me TBH. Asterisk is after-all sending the message TO me@my_linphone, no TO me@my_asterisk_server. me@my_asterisk_server was the address used by the previous hop to get it to my PBX. Why should Asterisk behave differently and not re-address the TO to where it's sending the message?

Because this isn't what the [SIP RFC](https://tools.ietf.org/html/rfc3261#section-8.1.1.2) says.
The TO header like the FROM header must follow

> The To header field first and foremost specifies the desired
   "logical" recipient of the request, or the address-of-record of the
   user or resource that is the target of this request.

> The From header field indicates the logical identity of the initiator
   of the request, possibly the user's address-of-record.  Like the To
   header field, it contains a URI and optionally a display name.
   [...]
   As such, it is
   very important that the From URI not contain IP addresses or the FQDN
   of the host on which the UA is running, since these are not logical
   names.

**Comment by Viish** [comment]
> But sending a message in one of them still fails to send with the small red circle with the white X in it to the bottom right of the message.

Most probably you have 2 proxy config, and because of the IP it doesn't know which one to use so it uses the default one which can't reach the sender of the message.

**Comment by brianjmurrell** [comment]
> The To header field first and foremost specifies the desired
"logical" recipient of the request, or the address-of-record of the
user or resource that is the target of this request.

But I can argue that from Asterisk's perspective, that is me@my_linphone.  The AOR for my linphone "session" to Asterisk is:

```
contact              : sip:brian_h8@10.75.22.32:34282;transport=tcp;app-id=[redacted];pn-type=firebase;pn-timeout=0;pn-tok=[redacted];pn-silent=1
```

Perhaps the significance of this is that Asterisk is not merely a SIP proxy.  It's a full PBX with abilities to forward "extensions" to other PBXes, an so on.

**Comment by brianjmurrell** [comment]
> Most probably you have 2 proxy config, and because of the IP it doesn't know which one to use so it uses the default one which can't reach the sender of the message.

I do have multiple "accounts" configured in linphone but all but one -- the default one -- the one that it should be using to send the message -- are disabled.

**Comment by brianjmurrell** [comment]
> I do have multiple "accounts" configured in linphone but all but one -- the default one -- the one that it should be using to send the message -- are disabled.

Seems like the sending account issue is different and unrelated to this issue so I have opened #778 for that.

**Comment by brianjmurrell** [comment]
Noting the [new config option](https://github.com/BelledonneCommunications/linphone-android/commit/2ba9b1a8bbb0353a4d291b840fc1884e0d143c55) for this and thinking a bit more about it...

How can a message be considered from a missing (i.e. previously deleted) proxy config when I just received the message on a registered proxy config?  If I were to have disabled an account, and then the messages sent/received from **that** account were missing, I'd understand, but this is a case of a message I just received on my active account being missing.

**Comment by Viish** [comment]
It is still the same reason, your message was received with a TO header to an address that doesn't match any proxy config identity address, so the Core consider it was received on a proxy config that doesn't exists anymore, thus hiding the chat room to prevent the exact issue you have in #778, message that won't be sent and go to error state.

**Comment by 532910** [comment]
> The real problem lies in badly configured SIP proxies that are using the IP as domain in the TO header and thus not following the spirit of the SIP RFC.

#583

It's impossible to configure asterisk in a "correct" way

**Comment by brianjmurrell** [comment]
@532910 Well _correct_ as linphone wants it.  I've never had this problem with any other mobile SIP phone client such a Zoiper or Bria, so having the SIP *server* writing the `To:` to be the client's address can obviously be handled by a client written to work with SIP *server*s.

This just seems like an interop problem with linphone (that other clients don't have) and SIP servers to me.

**Comment by carchrae** [comment]
the failure to be able to reply to sms is a deal breaker for me.  i have the same situation as @brianjmurrell using voip.ms

it is a bit sad the response is to fix voip.ms because it doesn't implement the spirit of SIP RFC.

**Comment by jrobinson42** [comment]
A deal breaker for me as well; and I really, really want to be able to use a functional, open source SIP client.

FWIW, I'm a believe in The Robustness Principle, also known as Postel’s Law, that says: "be conservative in what you send and liberal in what you accept".

**Comment by jane8dow** [comment]
Hi, I'm unable to make changes to "setting hide_chat_rooms_from_removed_proxies=0 in /data/data/org.linphone/files/.linphonerc." 

The direcory "org.linphone" does not exist on my Pixel 4a phone. It is because my phone is not rooted? 

Is there another way to fix this? I'm using voip.ms service. TIA.

**Comment by assemsal** [comment]
I was able to fix this issue in the source code. It's kind of a hack right now but if anyone is interested, I can send a patch. I used latest source from git for this

**Comment by arkanoid87** [comment]
I'm experiencing same problem on ubuntu 20.04 linphone desktop edition running Linphone-4.2.5.AppImage

On android version I can see sent and received messages, but on desktop I only see notification. Asterisk in the middle says the message is sent OK

**Comment by jeffvfren** [comment]
I'm experiencing the same problem with the latest Windows desktop version
- Sent message appear in the main Windows - OK
- New incoming message got notification - OK
- New message didn't appear in main Windows - Not OK
- Clicking new message notification, main Windows switch to Home instead of Conversation - Not OK

**Comment by morciej** [comment]
That's right @arkanoid87 and the messages DO exist in the Sqlite database. The UI doesn't seem to bring them to the screen, that's all. This is on Linux Mint Una.

Only the first one is visible, it is the OUTGOING one. All the rest are replies from a cell phone to the desktop.
![Screenshot_2022-04-17_20-04-23](https://user-images.githubusercontent.com/17895139/163748142-90c590de-37cd-42ab-a300-fb3611e59b44.png)

Right now I went back to a paid version of Zoiper 5, because I have NO way otherwise to be kindly informed that someone is messaging me on my home number. I keep an eye on Linphone, just in case Belledonne decides SMS are in fact a legit use case. But I don't have big hopes.

**Comment by Viish** [comment]
I'll say it one last time: when messages are not displayed, it's because the SIP proxy has changed either the FROM or TO header to remove the domain name and replace with the IP, which isn't standard according to the RFC.
Still you can display them by toggling off in the chat parameters the `Hide chat rooms from removed proxy configs` setting.

**Comment by eshattow** [comment]
I tried the the chat parameters the `Hide chat rooms from removed proxy configs` setting, and it does not display the messages? Maybe is a different problem, but from UX seems like Linphone alternates between either showing SMS messages from VoIP.ms or not showing them. Which issue should I follow up on? Thanks.

**Comment by Viish** [comment]
Note that when disabling this setting, messages will be shown in a different "conversation".

**Comment by Viish** [comment]
If not, feel free to open a new issue with logs.

**Comment by eshattow** [comment]
I can open a new github issue with logs but it is the same issue as this issue #765 since year 2019 that I provide already logs for. It has been many versions of Linphone released now that make SMS messages with SIP MESSAGE totally unusable for VoIP.ms provider. I am not aware what are the technical standards reasons or as VoIP.ms customer what I should advocate for, if you have a suggestion of what to write them as a customer I can open a service ticket and ask for their input if you are thinking there is some perversion of the SIP standard. Thanks, I will open this same issue again as a new issue and repeat this process of installing a new snapshot build and also the logs.

**Comment by assemsal** [comment]
I do have a patch that I wrote to fix this issue for me, what is the proper
way to get this code reviewed?

**Comment by eshattow** [comment]
I just try Linphone Android snapshot for 2022-04-11 linphone-android-debug-4.7.0-alpha.125+4c83e823f.apk and cannot replicate the problem. It is usually like this, but I will wait until the problem happens again to file the issue. Thank you and have a nice day.

**Comment by Viish** [comment]
@eshattow from your logs it's indeed still the same issue, message is received with a wrong TO header:
```
2022-04-18 12:13:06:992 [org.linphone.debug/belle-sip] MESSAGE channel [0x91b30240]: received [529] new bytes from [TLS://denver1.voip.ms:5061]:
MESSAGE sip:172162_mobile@98.97.32.67:46288;transport=tls SIP/2.0
Via: SIP/2.0/TLS 208.100.60.32:5061;branch=z9hG4bK60178735;rport
Max-Forwards: 70
From: "7754640901" <sip:7754640901@denver1.voip.ms>;tag=as49872e50
To: <sip:172162_mobile@98.97.32.67:46288;transport=tls>
Contact: <sip:7754640901@208.100.60.32:5061;transport=TLS>
Call-ID: 4f51ea0441ba01796e547a5e74a5f68a@208.100.60.32:5060
CSeq: 102 MESSAGE
User-Agent: voip.ms
X-SMS-To: 5757428869
Content-Type: text/plain;charset=UTF-8
Content-Length: 8

DEAFBEEF
```
However if you disable the `Hide chat rooms from removed proxy configs` setting you should see a new conversation in your chat rooms list.

**Comment by eshattow** [comment]
> However if you disable the `Hide chat rooms from removed proxy configs` setting you should see a new conversation in your chat rooms list.

This setting as suggested works for any new conversations until the Linphone app reloads its UI and then there are no conversations visible anymore. It is not like I am saying the conversations are not where I expect them to be; there are none at all visible.

**Comment by morciej** [comment]
I messaged Voip.ms and asked them to have a look at this issue. But if there is no compromise, then all we will achieve is yet another piece of open source software that rightly or wrongly, is seen **by users** as broken, no matter how zealously it is trying to follow the standards.

**Comment by Viish** [comment]
@morciej You're right, but if we start to implement workarounds for every provider that doesn't follow the standard, they will never fix it. 
The standard is standard for a reason, and if they don't want to be compliant with it, it's not up to every client to implement workarounds for them, even if that means having an app that doesn't work well with this provider. 
There are a lot of other SIP providers, it's up to you (and other clients) to make pressure on them to fix it or simply leave them.
You can also use another app that doesn't stand for what's right, that's up to you.

**Comment by Viish** [comment]
> This setting as suggested works for any new conversations until the Linphone app reloads its UI and then there are no conversations visible anymore. It is not like I am saying the conversations are not where I expect them to be; there are none at all visible.

@eshattow thanks, there was indeed an issue with that, it's now fixed. You can try it with this APK (and all future ones): https://download.linphone.org/snapshots/android/linphone-android-debug-4.7.0-alpha.132+8f291145d.apk

**Comment by eshattow** [comment]
@Viish tested and confirmed, thank you!

**Comment by morciej** [comment]
Voip.ms requested a sample log, so I am sending one that I recorded. We'll see what they say.

**Comment by morciej** [comment]
Voip.ms support's response was:

>I have verified with our sys admin, and unfortunately there's not much we can do about that, because SIP messages are sent by our system based on the user's last known registration.

>Apologies for the inconvenience.

There you go. It's not critical to Belledonne's business interests that its open source side project "Linphone" does anything in particular for anyone. As long as it is doing some things, sometimes, Belledonne is happy. That's not the case with Voip.ms, which is actually providing a paid service, for the benefit of customers, in a competitive market, ruled by antiquated standards that are not practically usable in the mobile communication context.

You can afford to stand on principle. It costs you nothing.

**Comment by sysfu** [comment]
> @morciej You're right, but if we start to implement workarounds for every provider that doesn't follow the standard, they will never fix it. The standard is standard for a reason, and if they don't want to be compliant with it, it's not up to every client to implement workarounds for them, even if that means having an app that doesn't work well with this provider. There are a lot of other SIP providers, it's up to you (and other clients) to make pressure on them to fix it or simply leave them. You can also use another app that doesn't stand for what's right, that's up to you.

If you have any recommendations for voip.ms alternatives, please post. I'm trying to get some headway with their tech support getting SMS text messages working via SIP messages on the Linphone desktop client and getting nowhere. I guess the issues is voip.ms does not conform to the RFC and is using IP address is SIP messages instead of the domain name?

**Comment by morciej** [comment]
I am not going to change my provider who was serving me well for some 10 years. I use Zoiper. It works for calls and SMS with no problem at all. I gave up on Linphone and uninstalled it. Realize that Linphone is just one of many (MANY) SIP clients in Windows/Mac/Android world, so thios is only an issue because there is such a shortage of decent SIP clients for Linux.

**Comment by Viish** [comment]
> If you have any recommendations for voip.ms alternatives, please post.

If you are looking for a VoIP provider with PSTN capabilities, you can use OVH. Their only downside is they are only supporting UDP as transport protocol.

**Comment by eshattow** [comment]
Regarding the VoIP.ms support reply "unfortunately there's not much we can do about that, because SIP messages are sent by our system based on the user's last known registration" that sounds completely reasonable to me. How could they do better than that? If you are committed as a reference implementation of the standards specifications and no further, then what are the specific suggestions that we as VoIP.ms customers should make to VoIP.ms support team to interop better with your software?

**Comment by Viish** [comment]
@eshattow 

I already said in previous comment https://github.com/BelledonneCommunications/linphone-android/issues/765#issuecomment-533060113 how the RFC is made to handle such scenario. 

You can see if in the log piece I posted in comment https://github.com/BelledonneCommunications/linphone-android/issues/765#issuecomment-1102163451 : the IP is set in the MESSAGE header which is enough, however the TO header isn't right and doesn't need to contains the IP again.

**Comment by sysfu** [comment]
> > If you have any recommendations for voip.ms alternatives, please post.
> 
> If you are looking for a VoIP provider with PSTN capabilities, you can use OVH. Their only downside is they are only supporting UDP as transport protocol.

I could not find any USA telecom/voip service offerings from OVH, only web and VPS hosting.

I have been experimenting with telnyx.com

**Comment by morciej** [comment]
I am in Canada, and since Voip.ms is a Canadian company, I think I have good reasons to stay with them. So good luck, but I am not interested in this solution.

**Comment by Viish** [comment]
Hi,

You may want to test our 5.2.1 release, it uses 5.3.X SDK that embeds the following commit: https://gitlab.linphone.org/BC/public/liblinphone/-/commit/2bace457ff5941e95160d50fbad1cc0092e9e5d6

It may solve your problem as well.

Cheers,

**Comment by morciej** [comment]
Thank you Viish. I will certainly try it. Which version of AppImage will it appear in?

**Comment by Hate9** [comment]
I've tried 5.2.1 (or, I'm on 5.2.3, now), and the issue still persists. Also, it seems like the hide_chat_rooms_from_removed_proxies setting doesn't work on the desktop version for some reason (also on 5.2.3).

**Comment by robledochav** [comment]
> ```
> 
> However if you disable the `Hide chat rooms from removed proxy configs` setting you should see a new conversation in your chat rooms list.

Is this setting only available by editing the file? Is this setting available to toggle from 1 to 0, and vice-versa, from within the linphone app?

**Comment by robledochav** [comment]
> @eshattow
> 
> I already said in previous comment [#765 (comment)](https://github.com/BelledonneCommunications/linphone-android/issues/765#issuecomment-533060113) how the RFC is made to handle such scenario.
> 
> You can see if in the log piece I posted in comment [#765 (comment)](https://github.com/BelledonneCommunications/linphone-android/issues/765#issuecomment-1102163451) : the IP is set in the MESSAGE header which is enough, however the TO header isn't right and doesn't need to contains the IP again but the SIP identity instead.

Excellent work with the app. I totally understand that standards need to be followed, by definition. As a non-technical person trying to follow the reasoning, where IP addresses are used rather than logical/domain names, Is it possible for the linphone app to "resolve" domain/logical names to IP addresses, and then group messages based on that? Not sure if I'm making something up that is technically wrong. Thanks

**Comment by Viish** [comment]
Hi @robledochav,

Even if it doable, it would require a lot of work to do that, and even with that it would not be solving all scenarios in which this issue happens (what if a two domains are hosted on the same server with the same IP for example).

So no, I don't think it will be done any time soon, sorry.

Cheers,

**Comment by salman977** [comment]
What i did was change the statements for fetching  the chat_rooms
