### ISSUE TITLE
Incoming Calls Are Hung Up After 60 Seconds

### ISSUE THREAD

**Issue by muellert** [BelledonneCommunications/linphone-android#767]
I have Linphon 4.1.1, and when I am on 4G, incoming calls are forcefully hung up after 60(?) seconds. I have tried to change the variable "Settings | Call | Incoming Calls Hangup" to 0 in the hope it would then not hang up at all, but that did not work. Now I have this variable set to 7200, which means that I should be able to receive phone calls and conduct them without interruption for 2 hours in one go, but this setting seems to only work on wifi. On wifi, I regularly conduct phone calls which are longer than one hour. On 4G, it still hangs up after 60 seconds. This is really bad, because the bulk of my phone calls are incoming calls, several also anonymous, and everyone thinks I just hung up in the middle of the sentence. I want to have unlimited call time for incoming call, no matter whether I am on wifi or not.

Can I set "priority: high" for this issue?

**Comment by Viish** [comment]
Please attach logs showing the issue.
