### ISSUE TITLE
how to check is h265  is exist？

### ISSUE THREAD

**Issue by wangpeng1** [BelledonneCommunications/linphone-android#768]
hello,i have used linpone 3.4 version,but I dnot know  if my version have h265. But i know the linphone have trust it https://gitlab.linphone.org/BC/public/linphone-android/tree/feature/h265.
can give me some clue?

**Comment by Viish** [comment]
Hi,
H265 detection is done by the SDK, so if you use one that is recent enough (like 4.2) you will have it.
Best regards.

**Comment by wangpeng1** [comment]
@Viish  You mean 3.4 doesn't support h265，only 4.0?.

**Comment by wangpeng1** [comment]
@wangpeng1  can you tell me where is the h265 code at the sdk source code
