### ISSUE TITLE
[Bug/crash] Error inflating class org.linphone.core.tools.AutoFitTextureView

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-android#769]
This bug appears to be introduced since commit 7818ead. When an outgoing call/an incoming call is answered, opening Linphone and navigating to the call results in a crash.

> `--------- beginning of crash
09-11 12:35:00.201 22167 22167 E AndroidRuntime: FATAL EXCEPTION: main
09-11 12:35:00.201 22167 22167 E AndroidRuntime: Process: org.linphone, PID: 22167
09-11 12:35:00.201 22167 22167 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.linphone/org.linphone.call.CallActivity}: android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class org.linphone.core.tools.AutoFitTextureView
09-11 12:35:00.201 22167 22167 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3139)
09-11 12:35:00.201 22167 22167 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3282)
09-11 12:35:00.201 22167 22167 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
09-11 12:35:00.201 22167 22167 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
09-11 12:35:00.201 22167 22167 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
09-11 12:35:00.201 22167 22167 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1970)
09-11 12:35:00.201 22167 22167 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-11 12:35:00.201 22167 22167 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
09-11 12:35:00.201 22167 22167 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7156)
09-11 12:35:00.201 22167 22167 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-11 12:35:00.201 22167 22167 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
09-11 12:35:00.201 22167 22167 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
09-11 12:35:00.201 22167 22167 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class org.linphone.core.tools.AutoFitTextureView
09-11 12:35:00.201 22167 22167 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #23: Error inflating class org.linphone.core.tools.AutoFitTextureView
09-11 12:35:00.201 22167 22167 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.linphone.core.tools.AutoFitTextureView" on path: DexPathList[[zip file "/data/app/org.linphone-Wpz48wB3hpCxOm-_zEHhPw==/base.apk"],nativeLibraryDirectories=[/data/app/org.linphone-Wpz48wB3hpCxOm-_zEHhPw==/lib/arm64, /data/app/org.linphone-Wpz48wB3hpCxOm-_zEHhPw==/base.apk!/lib/arm64-v8a, /system/lib64]]`

**Comment by Viish** [comment]
As commit https://github.com/BelledonneCommunications/linphone-android/commit/7818ead291887282823f3280c8d65195a8f5bfb5 states it it it's message, you need a more recent SDK for the AutoFitTextureView to be available in it.
Don't get too much attach to it, it will soon disappear and be replaced by another class in a coming SDK update.
