### ISSUE TITLE
Linphone Video Orientation Display issue

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#773]
Hello All,

I am using latest linphone app 4.1.109-gd6d46e19 and Linphone SDK 4.2.126-g380c3ac. 
The problem i am facing is that while video calling when i change the Sender orientation the video get split at receiver end some time green screen. 

I have observed followings : 

a) Mobile phone to mobile phone there is no issue.
b) When sender party is mobile phone and receiver is a device or tablet who is configured to work in landscape mode only then at receiver end split screen appears and as soon as i rotate the sender mobile phone in portrait mode the video at receiver end works fine.
c) When both sender and receiver are tablet or device (other than portrait mode) the video get spitted at both ends.

For scenario **c** 

I have fix the rotation variable to 90 in **app/src/main/java/org/linphone/activities/LinphoneGenericActivity.java**. 

This will resolve the split screen issue but video comes at the angle of 90 degree and 270 degree on sender and receiver end respectively. 

Please suggest what can be done.

**Comment by Viish** [comment]
Hi,
I don't reproduce the issue.
Can you attach logs for both devices in your b or c scenario please ?
Also can you make a video of the problem ?
Thanks.

**Comment by amit1576** [comment]
Hi,

Please find attached video link and Receiving device logs from scenario B.

https://mega.nz/#!pHhkgARL!gKJCkJ3_DmRDLRIhzZthwSbSjnQEveHgV3hJ-Oe1J-A

Logs : 

[Message.txt](https://github.com/BelledonneCommunications/linphone-android/files/3609558/Message.txt)


For scenario i will update you soon.

**Comment by amit1576** [comment]
Hi,

Please find attached video link and Receiving device logs from scenario C.

Logs : Sender Device

[Message.txt](https://github.com/BelledonneCommunications/linphone-android/files/3609641/Message.txt)

Video Link : 

https://mega.nz/#!oeIE3SLA!WFWFYaiq00Ly3G7BG9GwuNDrygYeG7pd4fsk-BLUOdE

Please check and suggest.

Thanks..

**Comment by Viish** [comment]
Hi,
Please attach only linphone logs and also I need the logs from the start of the call to the end (I don't have any log related to INVITE, camera, rotation etc...).

**Comment by Viish** [comment]
By the way, your device has a terrible custom version of Android running, it says the camera is back facing (when it's obviously front from your video). 
Also the rotation information given to the library is wrong, that is causing the distorted image.
I'll be able to tell you exactly what information is wrong with full logs.

**Comment by amit1576** [comment]
Hello @Viish,

**Please find detailed Linphone logs of device for scenario B.**


[1568613594b9fbbdb8c3b29420758ca27652de0f4f.txt](https://github.com/BelledonneCommunications/linphone-android/files/3614891/1568613594b9fbbdb8c3b29420758ca27652de0f4f.txt)

Please check.

**Comment by amit1576** [comment]
Hi @Viish ,

**Also find attached Linphone detailed logs for device and tablet for scenario C.**.

**DEVICE**
[Device_1568614165ee54e3b8e3201640055acb4b5d824421.txt](https://github.com/BelledonneCommunications/linphone-android/files/3614908/Device_1568614165ee54e3b8e3201640055acb4b5d824421.txt)

**TABLET**

[tablet_1568614218e963bee119ad07822107f2569a903e88.txt](https://github.com/BelledonneCommunications/linphone-android/files/3614909/tablet_1568614218e963bee119ad07822107f2569a903e88.txt)

May these logs help you understand the real problem.

**Comment by Viish** [comment]
Hi,

Like I said, the problem lies in the Android OS version of your devices.
In the logs:
```
MESSAGE MediaCodecDecoder: new format:
{image-data=java.nio.ByteArrayBuffer[position=0,limit=80,capacity=80], mime=video/raw, crop-top=0, crop-right=351, slice-height=288, color-format=0, height=288, width=352, what=1869968451, crop-bottom=287, crop-left=0, stride=352}
```

You can try a workaround we have for this specific devices issues: locate the media-codec-h264-decoder.cpp file in mediastreamer2 (in the SDK), and inside the _tvDevices array add an entry for your device : 
`{"rockchip", "rk3288", "rk3288"},`

Rebuild the SDK and your app and it should work better.
Otherwise switch to VP8 codec which is completely software and thus doesn't depend on the Android version running on the device.

**Comment by amit1576** [comment]
Thanks @Viish ,

**it works on rk3288.**

But same thing not working for MODEL=rk3399-all. I had made entry like {"rockchip", "rk3399-all", "rk3399-all"},

**Comment by Viish** [comment]
Check the logs of your device to be sure it's the right name.
From one of the logs you attached:
`This device (rockchip/rk3399-all/rk3399) says it has no built-in echo canceller`
So the entry should be
 {"rockchip", "rk3399-all", "rk3399"},
