### ISSUE TITLE
Wifi not connecting to the proxy server

### ISSUE THREAD

**Issue by Whales1992** [BelledonneCommunications/linphone-android#774]
I'm not sure if this is an issue from Linphone-Android or not, I just notice that I could not connect to the proxy server when ever I'm on a wifi, but when I switched back to my mobile data, I get connected successfully.
I also notice that when I explicitly set the configurations to Wifi only, It doesn't have any effect regardless.
Thanks for creating this library and I would really love to contribute, basically on the documentations, there are no commenting or proper documentation that will make it easy to consume most of the functions.
Warm Regards.
Wale.

**Comment by Viish** [comment]
Hi,
Please attach logs showing your wifi issue.
