### ISSUE TITLE
Cant build linphone-sdk for android with G729 support 

### ISSUE THREAD

**Issue by TularJahaj** [BelledonneCommunications/linphone-android#776]
**I clone linphone-sdk by this command:**

$git clone https://gitlab.linphone.org/BC/public/linphone-sdk.git --recursive

**and build with this two command:**

$cmake -DLINPHONESDK_PLATFORM=Android -DLINPHONESDK_ANDROID_ARCHS=arm64 -DENABLE_VIDEO=NO -DENABLE_WEBRTC_AECM=NO -DENABLE_WEBRTC_AEC=NO -DENABLE_NON_FREE_CODECS=ON -DENABLE_SQLITE=OFF

$cmake --build . -- -j 25

**then after some minutes i got this error:******

-- Installing: /home/tularjahaj/Android/linphone-sdk/build/linphone-sdk/android-arm64/include/xercesc/xinclude/XIncludeUtils.hpp

-- Installing: /home/tularjahaj/Android/linphone-sdk/build/linphone-sdk/android-arm64/include/xercesc/util/Xerces_autoconf_config.hpp

[ 51%] Completed 'EP_xerces'

[ 51%] Built target EP_xerces

Makefile:83: recipe for target 'all' failed

make[3]: *** [all] Error 2

CMakeFiles/android-arm64.dir/build.make:112: recipe for target 'android-arm64-prefix/src/android-arm64-stamp/android-arm64-build' failed

make[2]: *** [android-arm64-prefix/src/android-arm64-stamp/android-arm64-build] Error 2

CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/android-arm64.dir/all' failed

make[1]: *** [CMakeFiles/android-arm64.dir/all] Error 2

Makefile:83: recipe for target 'all' failed

make: *** [all] Error 2

****can anyone tell me what is happening there?????********

**Comment by Viish** [comment]
Hi,
It is because of the -DENABLE_SQLITE=OFF. Don't set it or set it to true and the build will work.
SQLite3 is mandatory for the SDK for Android.
Cheers,

**Comment by TularJahaj** [comment]
If i enable  sqlite by removing this  -DENABLE_SQLITE=OFF  then another
problem rises:

Command:
$cmake   .. -DLINPHONESDK_PLATFORM=Android
-DLINPHONESDK_ANDROID_ARCHS=arm64  -DENABLE_VIDEO=NO
 -DENABLE_WEBRTC_AECM=NO -DENABLE_WEBRTC_AEC=NO -DENABLE_NON_FREE_CODECS=ON
-DENABLE_G729=ON

Error:

[ 50%] Completed 'EP_sqlite3'
[ 50%] Built target EP_sqlite3
Makefile:83: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/android-arm64.dir/build.make:112: recipe for target
'android-arm64-prefix/src/android-arm64-stamp/android-arm64-build' failed
make[2]: ***
[android-arm64-prefix/src/android-arm64-stamp/android-arm64-build] Error 2
CMakeFiles/Makefile2:178: recipe for target
'CMakeFiles/android-arm64.dir/all' failed
make[1]: *** [CMakeFiles/android-arm64.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Viish** [comment]
If you simply removed the -DENABLE_SQLITE=OFF without reconfiguring from scratch, the OFF value will still be in use.
You can use tools like cmake-gui to check what is enabled and what is not.
Either clean your build folder and start from scratch or add -DENABLE_SQLITE=ON

**Comment by TularJahaj** [comment]
I cleaned everything. reconfigured , but same issue .

**Comment by Viish** [comment]
Indeed there was an issue witrh G729 build.
It is fixed in branch fix/g729_build and will be soon on master branch as well.

**Comment by TularJahaj** [comment]
plz give me the link of the branch

**Comment by Viish** [comment]
https://gitlab.linphone.org/BC/public/linphone-sdk/tree/fix/g729_build ...

**Comment by TularJahaj** [comment]
It asking username and password when trying to clone it

**Comment by Viish** [comment]
You can clone like you already did:
git clone https://gitlab.linphone.org/BC/public/linphone-sdk.git --recursive -b fix/g729_build

**Comment by TularJahaj** [comment]
$ git clone https://gitlab.linphone.org/BC/public/linphone-sdk.git --recursive -b fix/g729_build
Cloning into 'linphone-sdk'...
fatal: Remote branch fix/g729_build not found in upstream origin

**Comment by Viish** [comment]
Yes in the meantime it was merged into master branch.
