### ISSUE TITLE
Messages not being sent

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#778]
After making the [required changes](https://github.com/BelledonneCommunications/linphone-android/issues/765#issuecomment-533026945) from #765, when I try to reply to a message in one of the chats that are now visible, it doesn't send but instead displays a small red bubble with a white X in it to the bottom right of the message I sent.

In #765 @Viish said:
> > Most probably you have 2 proxy config, and because of the IP it doesn't know which one to use so it uses the default one which can't reach the sender of the message.

To which I replied:
> I do have multiple "accounts" configured in linphone but all but one -- the default one -- the one that it should be using to send the message -- are disabled.

**Comment by Viish** [comment]
Please attach logs.

**Comment by brianjmurrell** [comment]
[log](http://brian.interlinx.bc.ca/linphone-failed-to-send-sms.txt]

Of note in the log:

```
2019-09-20 05:42:30:470 [belle-sip] MESSAGE Trying to connect to [TCP://10.75.22.8:5061]
```

That is nether an enabled nor default account.  Why is linphone trying to send on a disabled, non-default account?

**Comment by Viish** [comment]
It is because of this function: https://github.com/BelledonneCommunications/linphone/blob/master/coreapi/linphonecore.c#L3718
I will check if this is really necessary anymore.

**Comment by brianjmurrell** [comment]
The blame on that code looks pretty old.  Why would it just be causing an issue now?

**Comment by Viish** [comment]
Because of the bad TO header in the message you receive.
If you create the chatroom from your side (remove all others first) and send a message it should work fine.

**Comment by brianjmurrell** [comment]
But this is not an issue on, say, release/4.1.

And again, I would argue that the TO header is not "bad".  AFAIU, it's perfectly legal and works perfectly fine outside of the linphone context.  It's just not what you think it should be.

**Comment by Viish** [comment]
> And again, I would argue that the TO header is not "bad".

And again yes it is, it doesn't follow the RFC. Asterisk is the only one to do that that I know of. Kamalio works just fine.

**Comment by brianjmurrell** [comment]
Any update on this?  This used to work regardless of the TO header.

**Comment by brianjmurrell** [comment]
> I will check if this is really necessary anymore.

Did you have a chance to check?

**Comment by brianjmurrell** [comment]
I **believe** I have fixed my SIP server to send a `To: ` header the way linphone wants it:

```
MESSAGE sip:my_sip_account@10.75.22.32:51672;transport=tcp;app-id=755770037818;pn-type=firebase;pn-timeout=0;pn-tok==[redacted];pn-silent=1 SIP/2.0
Via: SIP/2.0/TCP 10.75.22.8:5060;rport;branch=z9hG4bKPjc805e6f7-88bb-4f6c-a38b-3fbac92a01d8;alias
From: <sip:pc@pbx.example.com>;tag=e198ad62-2327-442c-bb18-71d729d012e3
To: <sip:my_sip_account@example.com;app-id=755770037818;pn-type=firebase;pn-timeout=0;pn-tok==[redacted];pn-silent=1>
Contact: <sip:my_sip_account@10.75.22.8:5060;transport=TCP>
Call-ID: e674bc13-82f3-4ca8-93c8-6057d55fc221
CSeq: 61559 MESSAGE
Max-Forwards: 70
User-Agent: Asterisk PBX 13.28.1
Content-Type: text/plain
Content-Length:     4
```

but linphone still seems to be trying to send messages back to the wrong proxy:

```
2019-09-28 17:32:43:331 [belle-sip] MESSAGE Trying to connect to [TCP://10.75.22.8:5061]
2019-09-28 17:32:43:351 [belle-sip] ERROR Connection failed  for fd [88]: cause [Connection refused]
2019-09-28 17:32:43:351 [belle-sip] ERROR Cannot connect to [TCP://pbx.example.com:5061]
```

5061 is **NOT** the port configured for the account that the `MESSAGE`  was received on nor the port it the replied message should be sending to.

Here's the [log](http://brian.interlinx.bc.ca/linphone-fail-to-send-msg.txt)

**Comment by brianjmurrell** [comment]
This problem is ultimately because I have (had) two accounts using the same SIP server (address) at different ports.  5060 and 5061.  The latter account was disabled, but clearly being [mis-]used by linphone.

**Comment by Viish** [comment]
Was the disabled account also the default one ?

**Comment by brianjmurrell** [comment]
No.

**Comment by Viish** [comment]
Then I don't understand why this method doesn't work as expected : https://github.com/BelledonneCommunications/linphone/blob/master/coreapi/linphonecore.c#L3722
Maybe you have an idea ?

**Comment by brianjmurrell** [comment]
I don't have any idea.  I don't really know the linphone stack well enough to have an educated opinion.

But clearly there is a bug somewhere that is making it select the wrong account configuration.

**Comment by Viish** [comment]
Could you send me your linphonerc from your device please ? (you can send it to me via mail to sylvain.berfini@belledonne-communications.com).
I've tried to reproduce your issue with a unit test but so far I failed to reproduce your issue.

**Comment by brianjmurrell** [comment]
In order to (a) troubleshoot this issue and (b) get a working instance of Linphone-android, I have since deleted all but my one main account from Linphone-android.  Is my `linphonerc` still useful?

In any case, it was simply a second account that was a duplicate of the first (default) except that I changed the port from 5060 to 5061.

**Comment by Viish** [comment]
>  Is my linphonerc still useful?

No I don't need your rc file anymore.

> In any case, it was simply a second account that was a duplicate of the first (default) except that I changed the port from 5060 to 5061.

Yes but all the tests I can do with that setup (2 accounts not default with the same settings except for the port) are successful.

**Comment by Viish** [comment]
I believe this fix (https://gitlab.linphone.org/BC/public/linphone/merge_requests/472/diffs) shall fix the one you had.
