### ISSUE TITLE
Edit contact header in call invite

### ISSUE THREAD

**Issue by jarvisv4** [BelledonneCommunications/linphone-android#779]
**Currently my contact header during call invite is like:-**

`<sip:xyz@202.131.119.122:35440;transport=udp>;expires=3600;received="sip:202.131.119.122:35440";+sip.instance="<urn:uuid:46361104-6435-40f3-85eb-4633381181a7>";+org.linphone.specs=groupchat
`

**I need to edit and send it in the following manner:-**

`<sip:xyz@202.131.119.122:35440;transport=udp>`

I want to know if i can edit the contact header and if yes then how?

_Thanks in advance._

**Comment by Viish** [comment]
Why do you want to edit it ?
There is no way to "edit" it, but you can remove some parts like sip-instance by setting the following in your linphonerc_factory:
[misc]
uuid=0
