### ISSUE TITLE
Missed Calls are marked as Incoming Calls

### ISSUE THREAD

**Issue by antongavrilenkov** [BelledonneCommunications/linphone-android#78]
There are only Incoming and Outgoing calls stored in Calling History.
Missed Calls are Marked as Incoming Calls on the Emulator and Android Device.

Some older versions worked well but the latest doesn't work as well.

I did that:
git clone git://git.linphone.org/linphone-android.git
git submodule sync && git submodule update --init --recursive
./prepare.py
make
make install

Used SIP-account.

**Comment by DatBewar** [comment]
Fix on submodule Linphone
a2d79af

**Comment by driesken** [comment]
I'm also having this issue, even with latest builds.
Submodule path 'submodules/linphone': checked out '868c54118ff75fd8333d7727995794f639e658bd'

Missed calls are marked as incoming calls with no missed call notification at all.

**Comment by driesken** [comment]
It appears that missing calls are showed when the incoming call duration exceeds the "Incoming call hangup (in seconds)" value. 
When the caller hangs up before that value is reached, the missed call is displayed as an incoming call.
