### ISSUE TITLE
inform users about potential networking issues

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#780]
It would be useful I think to give people warnings/setting suggestions when certain failures conditions are detected.

For example, it seems that disabling of the IPv6 stack on mobile phones while the phone is in sleep state (whereas the IPv4 stack stays awake) is a fairly common situation.  Lots of reports of it in Google searches for example.  So this causes a problem of course in getting the phone to wake and be ready to receive a call in a timely manner.  Linphone-android could detect this state.  For example, when it receives a push it could do a "happy eyeballs" DNS resolution if both IPv4 and IPv6 resolvers are configured and compare the time to getting results from each.  If the IPv6 results are significantly longer it suggests that the IPv6 stack is lazy and prone to being put to sleep so pop up a dialog letting the user know this and suggesting to disable IPv6.  Although, frankly I think there are better work-arounds, but a suggestion dialog seems like the minimum Linphone could do.

Another situation -- on my phone at least -- is that the phone seems to think it can just not send out UDP packets while the phone is sleeping, however if my SIP connection is TCP instead, the SIP packets are sent even with the phone in the exact same sleep state as when it doesn't sent UDP packets.  Linphone-android of course knows when it's sending UDP packets and having to retry repeatedly and not getting responses.  This could be another case for popping up a dialog and suggesting TCP be used instead.

**Comment by Viish** [comment]
We won't do that, sorry.

**Comment by brianjmurrell** [comment]
So instead just leave users scratching their heads about why linphone-android is not working, having them come here generating issues, etc.?

That's really a rhetorical question.  I don't expect that I am going to change your mind.

**Comment by Viish** [comment]
There isn't much users that use linphone-android without sip.linphone.org accounts, and we use linphone-android as a base for client projects that don't want that either.
