### ISSUE TITLE
Ortp error

### ISSUE THREAD

**Issue by devjva** [BelledonneCommunications/linphone-android#781]
ortp-warning-Discarding stateless response [401].

<------------>
Scheduling destruction of SIP dialog '5PlKFxV0~P' in 32000 ms (Method: REGISTER)

<--- SIP read from UDP:20X.7X.1X8.1X5:5060 --->
REGISTER sip:192.168.15.53:5060 SIP/2.0
Via: SIP/2.0/UDP 192.168.100.49:5060;branch=z9hG4bK.VEs0uME17;rport
From: sip:123@2XX.X1.1X7.1XX;tag=jntkzs~1g
To: sip:123@2XX.X1.1X7.1XX
CSeq: 148 REGISTER
Call-ID: pQZYSAh-zj
Max-Forwards: 70
Supported: replaces, outbound
Accept: application/sdp
Accept: text/plain
Accept: application/vnd.gsma.rcs-ft-http+xml
Contact: sip:123@20X.7X.1X8.1X5;+sip.instance="urn:uuid:6c49640e-af95-47c5-945c-0c74130213ab"
Expires: 3600
User-Agent: (belle-sip/1.4.2)
Authorization: Digest realm="asterisk", nonce="5926fc86", algorithm=MD5, username="123", uri="sip:2XX.X1.1X7.1XX:5071", response="cc957578a69b44bc9faf4ad074cf43f5"

<------------->
--- (15 headers 0 lines) ---
Sending to 20X.7X.1X8.1X5:5060 (NAT)
[2019-09-25 12:59:01] NOTICE[2240]: chan_sip.c:17383 check_auth: Correct auth, but based on stale nonce received from 'sip:123@2XX.X1.1X7.1XX;tag=jntkzs~1g'

<--- Transmitting (NAT) to 20X.7X.1X8.1X5:5060 --->
SIP/2.0 401 Unauthorized
Via: SIP/2.0/UDP 192.168.100.49:5060;branch=z9hG4bK.VEs0uME17;received=20X.7X.1X8.1X5;rport=5060
From: sip:123@2XX.X1.1X7.1XX;tag=jntkzs~1g
To: sip:123@2XX.X1.1X7.1XX;tag=as105492ea
Call-ID: pQZYSAh-zj
CSeq: 148 REGISTER
Server: FPBX-14.0.13.4(15.7.3)
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
WWW-Authenticate: Digest algorithm=MD5, realm="asterisk", nonce="547fba89", stale=true
Content-Length: 0

<------------>

**Comment by Viish** [comment]
Please open this ticket on oRTP repository.

**Comment by devjva** [comment]
I can't open the ticket over there

**Comment by Viish** [comment]
Then open on our gitlab: https://gitlab.linphone.org/BC/public/ortp
