### ISSUE TITLE
Set codec H264 on Android

### ISSUE THREAD

**Issue by juandspy** [BelledonneCommunications/linphone-android#783]
Hi! I'm trying to edit the sample app and I'm facing some errors. When making a call from the sample app, my video is sent as a black screen whereas the receiver video, from another app, looks perfect. How can I change my video codec to H264? Thanks!

**Comment by Viish** [comment]
Hi,
Here's how to enable a particular video codec:
https://github.com/BelledonneCommunications/linphone-android/blob/master/app/src/main/java/org/linphone/settings/VideoSettingsFragment.java#L282
Cheers

**Comment by juandspy** [comment]
Thank you very much. And how is it possible to add it in windows version? It just show me VP8.

**Comment by Viish** [comment]
The desktop installer should have asked you if you wanted to install the OpenH264 plugin from Cisco. We can't have openh264 on desktop without that currently.

**Comment by juandspy** [comment]
Thanks! Now it works :D
