### ISSUE TITLE
SIGSEV crash when user leaves a conference

### ISSUE THREAD

**Issue by kelianClerc** [BelledonneCommunications/linphone-android#786]
Hello, 
I'm using version 4.1.
I noticed a native crash during a conference : 

`A` calls `B`
`A` calls `C`  <- at this point we have a conference between `A`, `B` and `C`
`B` hangs up the call 
`A` calls `B` again <- at this point we have a conference between `A`, `B` and `C`
`C` hangs up ths call
`A` crashs

[crashlogs.txt](https://github.com/BelledonneCommunications/linphone-android/files/3681918/crashlogs.txt)

**Comment by Viish** [comment]
Hi,
Do you reproduce using the beta version of the Google Play Store or this APK http://linphone.org/snapshots/android/linphone-android-debug-4.1-136-g0aa26259.apk ?
Thanks in advance.

**Comment by kelianClerc** [comment]
Hi, 
I use linphone in my app so it's neither in the play store version nor in the apk

**Comment by Viish** [comment]
Not what I ask.
Does our latest version behaves the same in this scenario ?

**Comment by kelianClerc** [comment]
I can't reproduce it anymore, I'll close the issue
