### ISSUE TITLE
Android crash libc++_shared.so (crash on run)

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-android#787]
After pulling latest master, Linphone crashes due to a missing libc++_shared.so

I believe this was introduced in: https://gitlab.linphone.org/BC/public/linphone-sdk/commit/d70e0c3f632940369263bb200a4bb9e9d4a48a42

> --------- beginning of crash
10-03 12:58:06.751 21364 21364 E AndroidRuntime: FATAL EXCEPTION: main
10-03 12:58:06.751 21364 21364 E AndroidRuntime: Process: be.uzgent.uzlinphone, PID: 21364
10-03 12:58:06.751 21364 21364 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/be.uzgent.uzlinphone-Jx18ZyPGlG3f_t4syeeSFQ==/base.apk"],nativeLibraryDirectories=[/data/app/be.uzgent.uzlinphone-Jx18ZyPGlG3f_t4syeeSFQ==/lib/arm64, /data/app/be.uzgent.uzlinphone-Jx18ZyPGlG3f_t4syeeSFQ==/base.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libc++_shared.so"
10-03 12:58:06.751 21364 21364 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
10-03 12:58:06.751 21364 21364 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1669)
10-03 12:58:06.751 21364 21364 E AndroidRuntime: 	at org.linphone.core.FactoryImpl.<clinit>(Factory.java:1)
10-03 12:58:06.751 21364 21364 E AndroidRuntime: 	at org.linphone.core.Factory.instance(Factory.java:2)
10-03 12:58:06.751 21364 21364 E AndroidRuntime: 	at org.linphone.a.<init>(LinphoneContext.java:8)
10-03 12:58:06.751 21364 21364 E AndroidRuntime: 	at org.linphone.LinphoneService.onCreate(LinphoneService.java:5)
10-03 12:58:06.751 21364 21364 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3781)
10-03 12:58:06.751 21364 21364 E AndroidRuntime: 	at android.app.ActivityThread.access$1400(ActivityThread.java:241)
10-03 12:58:06.751 21364 21364 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823)
10-03 12:58:06.751 21364 21364 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-03 12:58:06.751 21364 21364 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
10-03 12:58:06.751 21364 21364 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7156)
10-03 12:58:06.751 21364 21364 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-03 12:58:06.751 21364 21364 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
10-03 12:58:06.751 21364 21364 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

**Comment by driesken** [comment]
Missing CMAKE_ANDROID_NDK variable.

**Comment by driesken** [comment]
EDIT: I've set a new UNIX variable which points to my NDK folder. I can also see that the following file is present for my architecture:
/android/android-ndk-r20/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++_shared.so

However, Linphone still seems to crash? Are we sure that the COPY statement is executed successfully?

**Comment by Viish** [comment]
Yes, and that copy statement is just a backup, there is another copy.
You can check your build/libs/<arch>/ directory to see if the libc++_shared exists or not.
If it does, check your Android Studio does use your locally generated AAR.
Finally, check if the crash isn't another one.

**Comment by uniruddh** [comment]
Hi @Viish ,

I am still getting this crash for master branch fetched just now. Any clue or resolution?

**Comment by Viish** [comment]
Hi,
Yeah that happens sometimes, this is an issue with Android Studio.
Simply go to Build->Clean Project and rebuild again, it should work.

**Comment by iAnish** [comment]
In my case I had built the linphone SDK with arm64 while my device CPU was armv7. After rebuilding the SDK with correct target like below it worked for me
cmake .. -DLINPHONESDK_PLATFORM=Android -DLINPHONESDK_ANDROID_ARCHS=armv7

**Comment by jigarce007** [comment]
Is this issue resolved? i am facing the same issue withlatest from master. Can someone please help me how can i fix it?
