### ISSUE TITLE
need to add a new attribute to call history ?!

### ISSUE THREAD

**Issue by hadidez** [BelledonneCommunications/linphone-android#79]
hi all. i need to add a new attribute as cost to call history. i want to show every outgoing call cost in history but i dont know where i should to do !?
thanks in advanced

**Comment by hadidez** [comment]
any help ?! i just want to add a new method to LinphoneCallLog

**Comment by DatBewar** [comment]
Where are the cost information?
If it's from an other Fragment you can use Bundle to forward informations.
