### ISSUE TITLE
How to set the server port 

### ISSUE THREAD

**Issue by bharathikrify** [BelledonneCommunications/linphone-android#793]
Hi Team 
I want to set local port as random and need to set the server port as 7000 in TCP mode.
I am using the useRandomPort(false) to false and then set the sipport as 7000 but which is not reflecting back to server. Please help me out to solve the issue

**Comment by Viish** [comment]
Hi,
You can set random local port by setting -1 as port value for each transport you want.
For the server port, in the proxy config, set the server address (and route address is needed) with the port like
setServerAddress(Core.interpretUrl("sip:sip.example.org:7000"))

**Comment by bharathikrify** [comment]
Okay Thank you. 
I will check

**Comment by bharathikrify** [comment]
How to or where to set the   setServerAddress(). i didn't find the method

**Comment by bharathikrify** [comment]
I tried to set the address as prxCfg.setAddress(LinphoneManager.getLc().interpretUrl(identity+":7000"));
the registration is not completed
