### ISSUE TITLE
No audio in calls after toggling speaker mode

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-android#794]
I've pulled master a few days ago and it looks like there is some kind of bug with the new implementation of Aaudio. When I set-up a call and toggle the speaker, the following calls won't have any audio at all (even when toggling speaker again) untill I restart Linphone.

I've copy/pasted some logs:
https://pastebin.com/xt9uyGnT

**Comment by Viish** [comment]
Hi,
This issue has been fixed a few days ago, please update your SDK (or at least msaaudio submodule) to a newer version.
Thanks for reporting it anyway.
