### ISSUE TITLE
selinux denial reading net_dns_prop resulting in name resolution failure

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#797]
Looks like linphone is trying to read a file, perhaps to get resolvers and hitting an SELinux AVC in doing so, resulting in a failure to actually resolve names:

```
10-18 10:53:00.941 12313 12313 I MyLinphone: bellesip_wake_lock_acquire(): Android wake lock [belle-sip send channel] acquired [ref=0x308a]
10-18 10:53:00.941 12313 12313 I MyLinphone: bellesip_wake_lock_acquire(): cast long of wakelock 12426
10-18 10:53:00.941 12313 12313 I MyLinphone: channel [0x7bc4165c00]: starting send background task with id=[308a].
10-18 10:53:00.941 12313 12313 I MyLinphone: channel [0x7bc4165c00]: starting resolution of www.example.com
10-18 10:53:00.942 12313 12313 I MyLinphone: channel 0x7bc4165c00: state RES_IN_PROGRESS
10-18 10:53:00.929 12313 12313 W .linphone.debug: type=1400 audit(0.0:142018): avc: denied { read } for name="u:object_r:net_dns_prop:s0" dev="tmpfs" ino=2710 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:net_dns_prop:s0 tclass=file permissive=0
10-18 10:53:00.942 12313 12313 E MyLinphone: resconf dns_resconf_loadandroid error
10-18 10:53:00.942 12313 12313 E MyLinphone: Error loading dns server addresses.
10-18 10:53:00.942 12313 12313 E MyLinphone: resconf dns_resconf_loadandroid error
10-18 10:53:00.942 12313 12313 E MyLinphone: Error loading dns server addresses.
10-18 10:53:00.942 12313 12313 E MyLinphone: channel_res_done: DNS resolution failed for www.example.com
10-18 10:53:00.942 12313 12313 I MyLinphone: channel 0x7bc4165c00: state ERROR
10-18 10:53:00.943 12313 12313 I MyLinphone: channel [0x7bc4165c00]: ending send background task with id=[308a].
10-18 10:53:00.929 12313 12313 W .linphone.debug: type=1400 audit(0.0:142019): avc: denied { read } for name="u:object_r:net_dns_prop:s0" dev="tmpfs" ino=2710 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:net_dns_prop:s0 tclass=file permissive=0
10-18 10:53:00.929 12313 12313 I chatty  : uid=10025(u0_a25) org.linphone.debug identical 3 lines
10-18 10:53:00.929 12313 12313 W .linphone.debug: type=1400 audit(0.0:142023): avc: denied { read } for name="u:object_r:net_dns_prop:s0" dev="tmpfs" ino=2710 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:net_dns_prop:s0 tclass=file permissive=0
10-18 10:53:00.945 12313 12313 I MyLinphone: bellesip_wake_lock_release(): Android wake lock released [ref=0x308a]
10-18 10:53:00.946 12313 12313 E MyLinphone: I/O Error during log collection upload to https://www.example.com/cgi-bin/lft.php
10-18 10:53:00.946 12313 12313 I MyLinphone: Linphone core [0x7bd537f000] notified [log_collection_upload_state_changed]
10-18 10:53:00.946 12313 12313 I MyLinphone: channel [0x7bc4165c00] removed from http provider.
10-18 10:53:00.946 12313 12313 I MyLinphone: Channel [0x7bc4165c00] destroyed
10-18 10:53:02.609 12313 12313 W .linphone.debug: type=1400 audit(0.0:142024): avc: denied { read } for name="u:object_r:net_dns_prop:s0" dev="tmpfs" ino=2710 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:net_dns_prop:s0 tclass=file permissive=0
10-18 10:53:02.609 12313 12313 I chatty  : uid=10025(u0_a25) org.linphone.debug identical 4 lines
```

I'm using linphone-android master and SDK 4.3+.

**Comment by Viish** [comment]
Please attach full logs.
You shouldn't encounter this issue as this is an old fallback mechanism if no DNS is supplied by the Android Network API.

**Comment by brianjmurrell** [comment]
This seems reproducible.  Not on demand, but usually when the phone is sitting idle/dozing.  At some point it starts wanting to use this fallback DNS mechanism.

**Comment by brianjmurrell** [comment]
FWIW, this only started happening when I reverted this [patch](https://github.com/BelledonneCommunications/linphone-android/issues/788#issuecomment-541083999) and set my SIP server to follow the TCP state of the phone also.

**Comment by Viish** [comment]
Issue should be fixed in SDK 4.3.0-alpha.25+f810940

**Comment by brianjmurrell** [comment]
Don't really have any idea what this means:

```bash
$ git clean -dfx; ./gradlew installDebug
Removing .gradle/
Removing .project
Removing app/.project
Removing linphone-sdk-android/.project

> Configure project :app
Git version: 4.1.156+561ac902

FAILURE: Build failed with an exception.

* What went wrong:
Cannot create service of type TaskExecuter using ProjectExecutionServices.createTaskExecuter() as there is a problem with parameter #21 of type ReservedFileSystemLocationRegistry.
> Cannot create service of type ReservedFileSystemLocationRegistry using ProjectExecutionServices.createReservedFileLocationRegistry() as there is a problem with parameter #1 of type List<ReservedFileSystemLocation>.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 51s
```

I did do an `$ rm -rf /home/brian/.gradle/caches/` before the above.

**Comment by brianjmurrell** [comment]
Any idea what this error is?  Did the update of the SDK introduce it?

**Comment by Viish** [comment]
No this issue comes from your local environment.

**Comment by brianjmurrell** [comment]
Any idea in what way?  The only thing I did was clear my gradle cache and try to build.

**Comment by Viish** [comment]
Completely remove the project from your computer and clone it again. Also you can try to use AndroidStudio clean / invalidate cache feature.

**Comment by brianjmurrell** [comment]
Without doing any of the above, today, it just magically works again.  :-/

In any case, I have SDK 4.3.0-alpha.26 now.  We'll see how well that works.

**Comment by brianjmurrell** [comment]
With this new SDK update, Linphone seems to be forcing, or only using it's own built-in DNS servers:

```
10-22 06:15:58.244 19818 19818 I MyLinphone: Resolver is using DNS server(s):
10-22 06:15:58.244 19818 19818 I MyLinphone:    8.8.8.8
10-22 06:15:58.244 19818 19818 I MyLinphone:    208.67.222.222
```

and ignoring the DNS servers that the network specifies through DHCP.

I can't provide a full log because the log server address is resolved by the DNS servers of the local network and not available to the DNS servers on the Internet.

**Comment by Viish** [comment]
No this hasn't changed.
I just prevented the DNS list from the Network to be replaced by an empty list when the network is down. We don't have built-in DNS servers.

**Comment by brianjmurrell** [comment]
So where are 8.8.8.8 and 208.67.222.222 coming from?  I have not configured those into my phone in any way and a [network info app](https://play.google.com/store/apps/details?id=com.ulfdittmer.android.ping&hl=en) that shows network info shows my DNS server as the configured DNS server for the phone.

Linphone only started doing this since the latest SDK update.

**Comment by Viish** [comment]
You should see in the logs where that comes from

**Comment by brianjmurrell** [comment]
Hrm.  And now without anything meaningful happening, such as switching networks, etc. I am getting the correct DNS servers.

The [log](http://brian.interlinx.bc.ca/linphone-wrong-dns-servers.txt).

**Comment by Viish** [comment]
The previous DNS servers are given by your WiFI network:
2019-10-22 06:06:03:486 [linphone-android] MESSAGE [Platform Helper] [Network Manager 26] onLinkPropertiesChanged {InterfaceName: wlan0 LinkAddresses: [*]  Routes: [*] DnsAddresses: [8.8.8.8,208.67.222.222,] Domains: example.com ilinx MTU: 0 TcpBufferSizes: 524288,1048576,2097152,262144,524288,1048576}

**Comment by brianjmurrell** [comment]
Yes, I see what your debug output is saying, but I can assure you that my DHCP server knows nothing of those DNS servers either.

```
¯\_(ツ)_/¯
```
