### ISSUE TITLE
Linphone 4.1.1 Incoming calls hangsup after 30 seconds when LinphoneService Restarts.

### ISSUE THREAD

**Issue by Adnan-addi** [BelledonneCommunications/linphone-android#798]
Hi, 
i download linphone app from google play store registered to my domain , 
and received a call and everything goes well , no hangups .

i forced stopped the app and again started it and received the call but this time and onwards call gets hangup after 30 seconds . 
why is this happening when service is restarted ....

how can i solve this . this issue is with app or server side ..

i am confused if its server side than why call didn't hangup on the first registeration process and after restarting the service its getting hangup .

this scenario is runned on the app downloaded from playstore .

Your help will be much appreciated , how can i solve this incoming 30 sec call hangup when service is restarted .

Thank You .

**Comment by Viish** [comment]
There is no reason that after a restart it behaves differently.
Check the logs before/after to see what changed.
