### ISSUE TITLE
No voice on HTC U12

### ISSUE THREAD

**Issue by ajayld** [BelledonneCommunications/linphone-android#799]
Hi,

The remote caller cannot hear any voice when I call from my HTC U12 phone. I've used the Linphone 4.1.1 from PlayStore. 

Is this an open issue? If not, how to debug & fix the same?

Best regards,
Ajay

**Comment by yudhisthira123** [comment]
I am also facing this issue on Android Linphone library and on Linphone  app version 4.1.1.

**Comment by Viish** [comment]
Please try beta version on the play store.

**Comment by yudhisthira123** [comment]
> Please try beta version on the play store.

I tried but no luck. same issue.

**Comment by Viish** [comment]
Do you use sip.linphone.org account or one from another provider ? Do you have stun / ICE enabled ?

**Comment by yudhisthira123** [comment]
> Do you use sip.linphone.org account or one from another provider ? Do you have stun / ICE enabled ?

For the linphone official app I am using sip.linphone.org account. Which I created for testing.

**Comment by ajayld** [comment]
Issue is open on Beta version also. Only on that HTC U12 it has this issue...other phones (Moto G3, Play) it works.

**Comment by Viish** [comment]
Please attach full logs from the HTC U12

**Comment by yudhisthira123** [comment]
> Please attach full logs from the HTC U12

Do you need logs from liphone beta app from PlayStore or from our application which use linphone library?

**Comment by Viish** [comment]
If you reproduce with our public beta please attach logs from it.

**Comment by yudhisthira123** [comment]
[incoming.pdf](https://github.com/BelledonneCommunications/linphone-android/files/3761115/incoming.pdf)
[outgoing.pdf](https://github.com/BelledonneCommunications/linphone-android/files/3761116/outgoing.pdf)

**Comment by Viish** [comment]
You haven't enabled debug logs in the advanced settings so your files are useless.
Also you have a log upload feature on the About page, I don't want all logcat output of your device.

**Comment by yudhisthira123** [comment]
> You haven't enabled debug logs in the advanced settings so your files are useless.
> Also you have a log upload feature on the About page, I don't want all logcat output of your device.


https://www.linphone.org:444//tmp/5db01950e7a9b_738b27286281362c89df.gz
https://www.linphone.org:444//tmp/5db019a45aa09_f8972c3786dd1c94f8e9.gz

Please let me know if I have to send again.

**Comment by Viish** [comment]
From your logs both your calls do have two-way audio.

```
2019-10-23 14:39:49:625 [ortp] MESSAGE 
===========================================================
2019-10-23 14:39:49:625 [ortp] MESSAGE              AUDIO SESSION'S RTP STATISTICS                
2019-10-23 14:39:49:625 [ortp] MESSAGE -----------------------------------------------------------
2019-10-23 14:39:49:625 [ortp] MESSAGE sent                                        730 packets
2019-10-23 14:39:49:626 [ortp] MESSAGE                                               0 duplicated packets
2019-10-23 14:39:49:626 [ortp] MESSAGE                                           63283 bytes  
2019-10-23 14:39:49:626 [ortp] MESSAGE received                                    699 packets
2019-10-23 14:39:49:626 [ortp] MESSAGE                                               0 duplicated packets
2019-10-23 14:39:49:626 [ortp] MESSAGE                                           66592 bytes  
2019-10-23 14:39:49:626 [ortp] MESSAGE incoming delivered to the app             66496 bytes  
2019-10-23 14:39:49:626 [ortp] MESSAGE incoming cumulative lost                      0 packets
2019-10-23 14:39:49:626 [ortp] MESSAGE incoming received too late                    1 packets
2019-10-23 14:39:49:626 [ortp] MESSAGE incoming bad formatted                        0 packets
2019-10-23 14:39:49:626 [ortp] MESSAGE incoming discarded (queue overflow)           0 packets
2019-10-23 14:39:49:626 [ortp] MESSAGE sent rtcp                                     5 packets
2019-10-23 14:39:49:626 [ortp] MESSAGE received rtcp                                 6 packets
2019-10-23 14:39:49:626 [ortp] MESSAGE ===========================================================

2019-10-23 14:41:25:231 [ortp] MESSAGE ===========================================================
2019-10-23 14:41:25:231 [ortp] MESSAGE              AUDIO SESSION'S RTP STATISTICS                
2019-10-23 14:41:25:231 [ortp] MESSAGE -----------------------------------------------------------
2019-10-23 14:41:25:231 [ortp] MESSAGE sent                                        372 packets
2019-10-23 14:41:25:231 [ortp] MESSAGE                                               0 duplicated packets
2019-10-23 14:41:25:231 [ortp] MESSAGE                                           28811 bytes  
2019-10-23 14:41:25:231 [ortp] MESSAGE received                                    365 packets
2019-10-23 14:41:25:232 [ortp] MESSAGE                                               0 duplicated packets
2019-10-23 14:41:25:232 [ortp] MESSAGE                                           34331 bytes  
2019-10-23 14:41:25:232 [ortp] MESSAGE incoming delivered to the app             33006 bytes  
2019-10-23 14:41:25:232 [ortp] MESSAGE incoming cumulative lost                      2 packets
2019-10-23 14:41:25:232 [ortp] MESSAGE incoming received too late                    6 packets
2019-10-23 14:41:25:232 [ortp] MESSAGE incoming bad formatted                        0 packets
2019-10-23 14:41:25:232 [ortp] MESSAGE incoming discarded (queue overflow)           0 packets
2019-10-23 14:41:25:232 [ortp] MESSAGE sent rtcp                                     3 packets
2019-10-23 14:41:25:232 [ortp] MESSAGE received rtcp                                 3 packets
2019-10-23 14:41:25:232 [ortp] MESSAGE ===========================================================

```

**Comment by yudhisthira123** [comment]
> From your logs both your calls do have two-way audio.
> 
> ```
> 2019-10-23 14:39:49:625 [ortp] MESSAGE 
> ===========================================================
> 2019-10-23 14:39:49:625 [ortp] MESSAGE              AUDIO SESSION'S RTP STATISTICS                
> 2019-10-23 14:39:49:625 [ortp] MESSAGE -----------------------------------------------------------
> 2019-10-23 14:39:49:625 [ortp] MESSAGE sent                                        730 packets
> 2019-10-23 14:39:49:626 [ortp] MESSAGE                                               0 duplicated packets
> 2019-10-23 14:39:49:626 [ortp] MESSAGE                                           63283 bytes  
> 2019-10-23 14:39:49:626 [ortp] MESSAGE received                                    699 packets
> 2019-10-23 14:39:49:626 [ortp] MESSAGE                                               0 duplicated packets
> 2019-10-23 14:39:49:626 [ortp] MESSAGE                                           66592 bytes  
> 2019-10-23 14:39:49:626 [ortp] MESSAGE incoming delivered to the app             66496 bytes  
> 2019-10-23 14:39:49:626 [ortp] MESSAGE incoming cumulative lost                      0 packets
> 2019-10-23 14:39:49:626 [ortp] MESSAGE incoming received too late                    1 packets
> 2019-10-23 14:39:49:626 [ortp] MESSAGE incoming bad formatted                        0 packets
> 2019-10-23 14:39:49:626 [ortp] MESSAGE incoming discarded (queue overflow)           0 packets
> 2019-10-23 14:39:49:626 [ortp] MESSAGE sent rtcp                                     5 packets
> 2019-10-23 14:39:49:626 [ortp] MESSAGE received rtcp                                 6 packets
> 2019-10-23 14:39:49:626 [ortp] MESSAGE ===========================================================
> 
> 2019-10-23 14:41:25:231 [ortp] MESSAGE ===========================================================
> 2019-10-23 14:41:25:231 [ortp] MESSAGE              AUDIO SESSION'S RTP STATISTICS                
> 2019-10-23 14:41:25:231 [ortp] MESSAGE -----------------------------------------------------------
> 2019-10-23 14:41:25:231 [ortp] MESSAGE sent                                        372 packets
> 2019-10-23 14:41:25:231 [ortp] MESSAGE                                               0 duplicated packets
> 2019-10-23 14:41:25:231 [ortp] MESSAGE                                           28811 bytes  
> 2019-10-23 14:41:25:231 [ortp] MESSAGE received                                    365 packets
> 2019-10-23 14:41:25:232 [ortp] MESSAGE                                               0 duplicated packets
> 2019-10-23 14:41:25:232 [ortp] MESSAGE                                           34331 bytes  
> 2019-10-23 14:41:25:232 [ortp] MESSAGE incoming delivered to the app             33006 bytes  
> 2019-10-23 14:41:25:232 [ortp] MESSAGE incoming cumulative lost                      2 packets
> 2019-10-23 14:41:25:232 [ortp] MESSAGE incoming received too late                    6 packets
> 2019-10-23 14:41:25:232 [ortp] MESSAGE incoming bad formatted                        0 packets
> 2019-10-23 14:41:25:232 [ortp] MESSAGE incoming discarded (queue overflow)           0 packets
> 2019-10-23 14:41:25:232 [ortp] MESSAGE sent rtcp                                     3 packets
> 2019-10-23 14:41:25:232 [ortp] MESSAGE received rtcp                                 3 packets
> 2019-10-23 14:41:25:232 [ortp] MESSAGE ===========================================================
> ```

I really did not understand  anything about these logs. 

But this is true that I do not get any voice on my phone. And we have some more different devices where we are facing this issue.

At the same time we have checked other messengers like whatsApp and Skype, these works well with proper voice.

Please suggest me further steps to debug this issue.

**Comment by Viish** [comment]
Can you attach the logs from the device that doesn't receive audio ?

**Comment by yudhisthira123** [comment]
> Can you attach the logs from the device that doesn't receive audio ?

these logs were captured from the device which does not receive voice. 

Any way I am attaching again new logs.
https://www.linphone.org:444//tmp/5db03815e3a03_e2299461fd96bf29eb65.gz

**Comment by Viish** [comment]
Can you try with another codec than OPUS ?
What version of Android is your device running ?

**Comment by yudhisthira123** [comment]
> Can you try with another codec than OPUS ?
> What version of Android is your device running ?

I tried disabling OPUS but result is same. 

I am running on Android 9 device.

please find the attached screen shot of my default Audio codec list.
![CE5A7E66-702F-4D6D-BCED-C7449AEFE2DF](https://user-images.githubusercontent.com/19162874/67392362-051eb280-f5be-11e9-840c-ff0a7ab8a740.jpg)

Can you please tell me what are all codecs I have to disable? I have tried with disabling OPUS with no success.

**Comment by Viish** [comment]
When you receive a call, do you hear the ringtone (when the setting "Use device ringtone" is disabled) ?
Can you attach logs from the start of the app ? I'd like to know why your device doesn't support AAudio sound card.

**Comment by yudhisthira123** [comment]
> When you receive a call, do you hear the ringtone (when the setting "Use device ringtone" is disabled) ?
> Can you attach logs from the start of the app ? I'd like to know why your device doesn't support AAudio sound card.

yes, I can hear ringtone in both case either "Use device ringtone" is disabled or enabled. 

I have taken logs from the starting app to making calls.  ( Start of app means by launching app from taping on app icon )

https://www.linphone.org:444//tmp/5db04a6eb941d_4ad0cd4fbfca6613a7d2.gz

let me know if you need some more logs.

**Comment by Viish** [comment]
DId you built yourself either the app or the SDK ?

**Comment by yudhisthira123** [comment]
> DId you built yourself either the app or the SDK ?

I did not understand your question clearly. 

But for now I am using Android beta app from PlayStore. 

And I am developing my own app where I use linphone jar library in which I have same issue.

**Comment by Viish** [comment]
Ok I found an issue in our beta but that doesn't impact yours.

However if you are able to hear the ringtone it means the audio soundcard does work with your device. Is the remote end of the call really sending sound and not just blank audio ? Is the volume of your device for the "call" stream not 0 ?

**Comment by yudhisthira123** [comment]
> Ok I found an issue in our beta but that doesn't impact yours.
> 
> However if you are able to hear the ringtone it means the audio soundcard does work with your device. Is the remote end of the call really sending sound and not just blank audio ? Is the volume of your device for the "call" stream not 0 ?

I think remote end of the call is sending audio because I have tested with many different devices. 

I can make sure that device volume is not 0.

**Comment by yudhisthira123** [comment]
> > Ok I found an issue in our beta but that doesn't impact yours.
> > However if you are able to hear the ringtone it means the audio soundcard does work with your device. Is the remote end of the call really sending sound and not just blank audio ? Is the volume of your device for the "call" stream not 0 ?
> 
> I think remote end of the call is sending audio because I have tested with many different devices.
> 
> I can make sure that device volume is not 0.

Is there something which I can do for you find this issue?

**Comment by Viish** [comment]
I will publish a new beta between today and next monday and I'd like you to test it.
Otherwise you can send us your device and/or buy us a commercial support contract (contact sales@belledonne-communications.com).

**Comment by yudhisthira123** [comment]
> New beta was sent to Google, will be available soon.
> Look out for version 4.2.0-beta.2 with SDK 4.3.0-beta.3

I updated new beta version from Google play store but unfortunately I am facing same issue.

If you need I can send my HTC device to you for debugging.

**Comment by Viish** [comment]
Can you attach new logs with the latest beta please ? Maybe it will help.

**Comment by yudhisthira123** [comment]
> Can you attach new logs with the latest beta please ? Maybe it will help.

Please find the link for latest logs.

https://www.linphone.org:444//tmp/5db2e0d259eeb_f7f3cd29d2301c9136f4.gz

**Comment by Viish** [comment]
Do you hear the ringback tone when making an outgoing call while the remote end is ringing ?

**Comment by yudhisthira123** [comment]
> Do you hear the ringback tone when making an outgoing call while the remote end is ringing ?

No, I can not hear ringback tone. There is not ringback tone.

**Comment by Viish** [comment]
OK but you do hear the ringtone when "Use device ringtone" is disabled right ?

**Comment by yudhisthira123** [comment]
> OK but you do hear the ringtone on an incoming call when "Use device ringtone" setting is disabled right ?

yes.

**Comment by Viish** [comment]
Then your device as a specific issue with the IN_COMMUNICATION mode...
Can you capture and send me adb logcat from during a call, maybe there is a system error log that can be usefull ?

**Comment by yudhisthira123** [comment]
> Then your device as a specific issue with the IN_COMMUNICATION mode...
> Can you capture and send me adb logcat from during a call, maybe there is a system error log that can be usefull ?

logs are attached.

[linphone_log.txt](https://github.com/BelledonneCommunications/linphone-android/files/3771939/linphone_log.txt)

**Comment by Viish** [comment]
Thanks.
By the way, if you enable the speaker or connect a bluetooth device, does it work ?

**Comment by yudhisthira123** [comment]
> Thanks.
> By the way, if you enable the speaker or connect a bluetooth device, does it work ?

No nothing works. enabling speaker and bluetooth devices also does not work. 

But interesting thing is, i tried recording and it is able to record the audio. but recorded audio is hardly audible. Voice is very very low with lots of background noise.

**Comment by Viish** [comment]
Thanks for the info, that confirms the issue is with the sound not being played.
You said you had the issue on other devices too, can you make me a list please ?

**Comment by yudhisthira123** [comment]
> Thanks for the info, that confirms the issue is with the sound not being played.
> You said you had the issue on other devices too, can you make me a list please ?

sure. give me some time to find all device model. I will send you ASAP.

**Comment by Viish** [comment]
Thanks a lot.

**Comment by Viish** [comment]
Are you sure about the Samsung Note 10+ ?
I have one and I don't have any issue with it (at least with linphone-android master & release/4.2 branches).

**Comment by yudhisthira123** [comment]
> Are you sure about the Samsung Note 10+ ?
> I have one and I don't have any issue with it (at least with linphone-android master & release/4.2 branches).

Actually 4 users are reporting this issue from Samsung Note 10+ device. I personally do not have this device. I have HTC U12+ with me.

**Comment by yudhisthira123** [comment]
Hi,

Is there any update on this issue?

**Comment by Viish** [comment]
> Is there any update on this issue?

Sadly no, as it is most probably only happening on this specific device and we don't have it to reproduce.

**Comment by yudhisthira123** [comment]
> > Is there any update on this issue?
> 
> Sadly no, as it is most probably only happening on this specific device and we don't have it to reproduce.

we are based in Germany. 
I can send this device to you.

**Comment by Viish** [comment]
> I can send this device to you.

Then do so please. Our address is:
```
Belledonne Communications
Le Trident Bat A
34 avenue de l'Europe
38100 Grenoble
France
```

Thanks in advance.

**Comment by Viish** [comment]
Any update?
