### ISSUE TITLE
To build Liblinphone,I have some problems about optional feature.

### ISSUE THREAD

**Issue by Seejun** [BelledonneCommunications/linphone-android#80]
According to the ReadMe.md file,when i run ./prepare.py -lf,Shown here:
--------------------------------------------------------------------------------------
INFO: Searching for available features...
INFO: Here are available features:
	ENABLE_AMRNB=OFF
	ENABLE_H263=OFF
	ENABLE_CXX_WRAPPER=OFF
	ENABLE_AMRWB=OFF
	ENABLE_VCARD=ON
	ENABLE_MBEDTLS=ON
	ENABLE_ILBC=ON
	ENABLE_CSHARP_WRAPPER=OFF
	ENABLE_UNMAINTAINED=OFF
	ENABLE_SILK=ON
	ENABLE_H263P=OFF
	ENABLE_ARCH_SUFFIX=ON
	ENABLE_FFMPEG=OFF
	ENABLE_NON_FREE_CODECS=OFF
	ENABLE_TOOLS=OFF
	ENABLE_GTK_UI=OFF
	ENABLE_OPENH264=OFF
	ENABLE_BV16=OFF
	ENABLE_EMBEDDED_OPENH264=OFF
	ENABLE_ISAC=ON
	ENABLE_VPX=ON
	ENABLE_MKV=ON
	ENABLE_MPEG4=OFF
	ENABLE_G729B_CNG=OFF
	ENABLE_PCAP=OFF
	ENABLE_GSM=ON
	ENABLE_DEBUG_LOGS=OFF
	ENABLE_GPL_THIRD_PARTIES=ON
	ENABLE_OPUS=ON
	ENABLE_DOC=ON
	ENABLE_G726=OFF
	ENABLE_SRTP=ON
	ENABLE_G729=ON
	ENABLE_RELATIVE_PREFIX=OFF
	ENABLE_X264=OFF
	ENABLE_VIDEO=ON
	ENABLE_POLARSSL=OFF
	ENABLE_UNIT_TESTS=ON
	ENABLE_LIME=ON
	ENABLE_WEBRTC_AECM=ON
	ENABLE_ZRTP=ON
	ENABLE_CODEC2=OFF
	ENABLE_WEBRTC_AEC=OFF
	ENABLE_JPEG=ON
	ENABLE_SPEEX=ON
	ENABLE_NLS=NO
INFO: To enable some feature, please use -DENABLE_SOMEOPTION=ON (example: -DENABLE_OPUS=ON)
INFO: Similarly, to disable some feature, please use -DENABLE_SOMEOPTION=OFF (example: -DENABLE_OPUS=OFF)
------------------------------------------------------------------------------------------
The ReadMe file tells me to enable the x264 encoder give the "-DENABLE_X264=YES" to prepare.py,and the INFO tells me use "-DENABLE_X264=ON",then i try "./prepare.py -DENABLE_X264=YES && ./prepere.py -DENABLE_MPEG4=ON && ./prepare.py",but the both methods can not change the build feature!How can i change the build feature?And i run "make liblinphone-android-sdk && make",there is no liblinphone SDK zip and liblinphone.jar,how can i make liblinphone.jar?please.

**Comment by nikunjdhamat** [comment]
@Seejun , Can anyone help on this ? I am also having confusion on the same.

**Comment by CrabeMan** [comment]
Hello,
ReadMe is probably outdated, you can check available options with `./prepare.py --list-features` command

CrabeMan

**Comment by Seejun** [comment]
thanks,@CrabeMan.
when i run ./prepare.py  -DENABLE_FFMPEG=ON ,the codecs is not enable,
but when i run ./prepare.py  -DENABLE_VIDEO=ON -DENABLE_FFMPEG=ON ,the codecs is enable.

**Comment by CrabeMan** [comment]
Hello,
I'm glad to see that it works for you. Don't forget to close this issue if your problem is solve, thanks.

CrabeMan.
