### ISSUE TITLE
Doesn't authenticate after 401 REGISTER response

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#801]
I've found that I've had to have my proxy account configured twice in Linphone in order for it to response to a `401` from a `REGISTER`.  With just one account, it sends a single `REGISTER` and when it gets the `401` response, it just doesn't send an authenticated `REGISTER`.

The account definitely has the right password.  I even tried entering it again.  I do notice however if I edit the proxy account field, as soon as I leave the field linphone tries to register with it's new value.  But when I re-enter my password and leave that field, it does not try to re-`REGISTER`.  It doesn't even try to re-`REGISTER` when I leave the account configuration screen.

[Log](http://brian.interlinx.bc.ca/linphone-doesnt-answer-401.txt).

**Comment by Viish** [comment]
Can you do a adb shell run-as org.linphone.debug cat files/.linphonerc and check you do have an auth info along with the proxy config ?

**Comment by brianjmurrell** [comment]
I ended up deleting all accounts and re-creating one from scratch (i.e. before you added your comment here) and it seems to be functioning normally.  I suspect there is still a bug lurking there, but I am unable to tickle it any more.
