### ISSUE TITLE
Return message is IOError

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#804]
Hi,
I use linphone 4.0.1 ，release branch.
Sometimes there is no regular automatic hang up during a talking， in
“ private void callStateChanged(Core lc, Call call, Call.State state, String message)" , I find that the message returned is IOError。
what is the reason?
I have set:
useRandomPort(false);
setHttpProxyPortValue(0);
useIpv6(false);
I'm not sure if it's related to these three settings.

thanks,
Best Regards.

**Comment by Viish** [comment]
We don't support old version on github, please update to latest one.
