### ISSUE TITLE
SRV & TLS Certificate verification

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#806]
Domain `domain.tld` is served by two sip servers defined via `SRV` records:
```
_sips._tcp.domain.tld  SRV  10 0 5061 sipA.domain.tld.
_sips._tcp.domain.tld  SRV  20 0 5061 sipB.domain.tld.
```
Each sip server uses it's own personal certificate:
sipA.domain.tld -> `Subject: CN = sipA.domain.tld`
sipB.domain.tld -> `Subject: CN = sipB.domain.tld`

The linphone config is:
```
Username: username
Auth userid: undefined
Password: supersecret
Domain: domain.tld
Transport: TLS
```

If I set `Proxy` to `<sip:domain.tld;transport=tls>` it says: `Certificate verification failed`
If I set `Proxy` to `<sip:sipA.domain.tld;transport=tls>` all works fine but only for sipA.

Is this a bug and how `Proxy` should be configured?

**Comment by Viish** [comment]
Your sip servers configuration should use a sip.domain.tld certificate.

**Comment by nlvkevin** [comment]
I believe this is incorrect as detailed here:

The certificate common name or SubjectAltName.DNS should match the name that was originally given in the LDAP uri. RFC6125 in appendix B.3 (https://www.rfc-editor.org/rfc/rfc6125#appendix-B.3) says:

    3.6. Server Identity Check

    The client MUST check its understanding of the server's hostname
    against the server's identity as presented in the server's
    Certificate message, in order to prevent man-in-the-middle attacks.

    Matching is performed according to these rules:

    o The client MUST use the server hostname it used to open the LDAP connection as the value to compare against the server name as expressed in the server's certificate. The client MUST NOT use the server's canonical DNS name or any other derived form of name.

Note that the same logic applies for other protocols that use SRV records, like SIP. This is somewhat logic from a security standpoint. If only the host was checked, it would be easy to perform a man in middle attack by diverting the connection to nodes whose hostnames are unrelated to the domain name originally queried.


https://serverfault.com/questions/862898/what-names-for-tls-certificates-when-using-srv-records
