### ISSUE TITLE
Local loopback network only 

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#808]
Hi，

When device A calls device B， I occasionally find information in log ：
Local loopback network only !
<sip:linphone.android@127.0.0.1>
so device B can't answer, I don't know what will happen and how to avoid it.
The following interface shows ”local loopback network only!“：

static void update_primary_contact(LinphoneCore *lc){
	char *guessed=NULL;
	char tmp[LINPHONE_IPADDR_SIZE];
	int port;

	LinphoneAddress *url;
	if (lc->sip_conf.guessed_contact!=NULL){
		ms_free(lc->sip_conf.guessed_contact);
		lc->sip_conf.guessed_contact=NULL;
	}
	url=linphone_address_new(lc->sip_conf.contact);
	if (!url){
		ms_error("Could not parse identity contact !");
		url=linphone_address_new("sip:unknown@unkwownhost");
	}
	linphone_core_get_local_ip(lc, AF_UNSPEC, NULL, tmp);
	if (strcmp(tmp,"127.0.0.1")==0 || strcmp(tmp,"::1")==0 ){
		ms_warning("Local loopback network only !");
		lc->sip_conf.loopback_only=TRUE;
	}else lc->sip_conf.loopback_only=FALSE;
	linphone_address_set_domain(url,tmp);
	port = linphone_core_get_sip_port(lc);  
	if (port > 0) linphone_address_set_port(url, port); /*if there is no listening socket the primary contact is somewhat useless,
		it won't work. But we prefer to return something in all cases. It at least shows username and ip address.*/
	guessed=linphone_address_as_string(url);
	lc->sip_conf.guessed_contact=guessed;
	linphone_address_unref(url);
}

Thanks.

**Comment by Viish** [comment]
This means you are probably not connected to any network at the time this is called.
Anyway this won't change anything, you can have a primary contact with a localhost address. However if indeed you aren't connected to any network you won't be able to receive calls...
