### ISSUE TITLE
bluetooth status issues

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#809]
Sometimes it shows bluetooth icon:
![image](https://user-images.githubusercontent.com/14617699/67730791-268cfd80-fa07-11e9-9a26-c07e6a1398d8.png)

But pressing this button it shows the earphone is used:
![image](https://user-images.githubusercontent.com/14617699/67730821-458b8f80-fa07-11e9-9071-b4c0c615c2ba.png)

**Comment by Viish** [comment]
It's actually not a bug. When a bluetooth audio route is available, the toggle earpiece/speaker transforms into a list of audio routes. The symbol speaker-bluetooth just means that.
When you click on it, it shows all routes and the selected one in orange.

**Comment by 532910** [comment]
OK. I've updated the issue, plese reopen.

**Comment by Viish** [comment]
It's still not a bug, it was a choice of the design team.
I'll try to make things change for the next release.

**Comment by 532910** [comment]
Not a bug, yes, but feature request of improvement suggestion. Is it possible to discuss it with the design team. It's quite a strange solution.

**Comment by Viish** [comment]
It is to differenciate this mode from the toggle mode.

**Comment by 532910** [comment]
Just add the down arrow same way as native dialer does:
Tri-state:
![image](https://user-images.githubusercontent.com/14617699/67758206-501d4780-fa4e-11e9-960b-9fda3bc4a9d8.png)![image](https://user-images.githubusercontent.com/14617699/67758210-527fa180-fa4e-11e9-901b-186eb7a06bb7.png)![image](https://user-images.githubusercontent.com/14617699/67758212-53b0ce80-fa4e-11e9-9d7b-2e63d37880b0.png)

Toggle:
![image](https://user-images.githubusercontent.com/14617699/67758220-58758280-fa4e-11e9-8b7a-96cec5e1708d.png)![image](https://user-images.githubusercontent.com/14617699/67758225-59a6af80-fa4e-11e9-8225-7beba8f6101e.png)
