### ISSUE TITLE
sometimes it chashes

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#810]
2 different crashes in the same [logcat.log](https://github.com/BelledonneCommunications/linphone-android/files/3781377/logcat.log)

**Comment by Viish** [comment]
What version of the SDK are you using ?

**Comment by 532910** [comment]
![image](https://user-images.githubusercontent.com/14617699/67752630-5c040c00-fa44-11e9-8e86-bb4495b74def.png)

**Comment by 532910** [comment]
[logcat2.log](https://github.com/BelledonneCommunications/linphone-android/files/3785848/logcat2.log)

**Comment by 532910** [comment]
Same logcat taken with pidcat:
[pidcat.log](https://github.com/BelledonneCommunications/linphone-android/files/3785883/pidcat.log)
(contain colors, you need `less --RAW-CONTROL-CHARS pidcat.log` to see it)

**Comment by Viish** [comment]
Do you have a way to reproduce those crashes ? If yes can you attach matching library logs (or send them by mail to me) ?

**Comment by Viish** [comment]
Library logs is just debug logs enabled in the advanced settings and what is uploaded after you click on upload log button in about page.

**Comment by 532910** [comment]
Right now it crashes just I start it!
I cleared logcat, removed linphone's logs and tried to start it twice.

linphone log and logcat are sent by email.

**Comment by 532910** [comment]
I've nothing changed (have not rebooted the phone or not chaged the bluetooth state) and now it works fine.

**Comment by Viish** [comment]
It was a "race condition" on an incoming call.
Thanks for the logs, it has been fixed in 0c75dbd9dd8c4c90ac8e0805c35890efba0117ee.
