### ISSUE TITLE
Blocking Incoming Calls

### ISSUE THREAD

**Issue by stef204** [BelledonneCommunications/linphone-android#811]
Is there a way to block certain incoming calls such as all calls not originating from a number in Contacts database (Address Book)?

The idea here is to try to fight against incoming robocalls, which just cycle through spoofed numbers (caller id's) and just send barrage of calls within seconds, you decline one, call hangs up, but is instantly initiated again by originator, usually using a different spoofed originating number and cycling through that 15 or 20 times (that's 15 or 20 calls within a few seconds.)

Having a way of blocking that, perhaps using a feature such as "accept calls only if number is in Address Book" might help (as an toggle option.)

Interested to get your thoughts on that.  Thanks.

**Comment by Viish** [comment]
No there is no black/white list mechanism in either the app or the SDK.
However if you want to develop one that isn't very hard to in the app itself.

**Comment by JohnVeness** [comment]
I'd like this too. Has anything changed in the last few years?
