### ISSUE TITLE
Switching between SIP Accounts

### ISSUE THREAD

**Issue by stef204** [BelledonneCommunications/linphone-android#812]
I use 2 SIP accounts, both configured in Linphone Android.  And then select Account A as Default.
Both accounts are registered/logged in.
Incoming calls are received no matter which account is set to Default.
However, so make an outgoing call from Account B, I cannot find another was than giong into settings, then selecting Account B as Default account, then making the call, then setting Account A as Default account again.  It works but not ideal.. Am I missing something or this is the way to go, for now?

**Comment by Viish** [comment]
Hi,
Currently indeed this is the only way of doing that.
I hope we can improve that in the next release.
Cheers,

**Comment by hobbes** [comment]
> Hi,
> Currently indeed this is the only way of doing that.
> I hope we can improve that in the next release.
> Cheers,

why have you closed the ticket if it's not resolved and you hope you can work on it ??? I also would like such a feature :-)

**Comment by Viish** [comment]
It's not an issue, it's a missing feature. And even if we might fix it, I don't need to pollute the opened issues with it.

**Comment by SilentBob999** [comment]
Hi,
Maybe could you start to put labels and milestones on issues for feature as well.  
This way you can keep open everything that should not be close.
That will allow better communication, feedback, and tracking.

Like https://github.com/glpi-project/glpi/issues (https://github.com/glpi-project/glpi/labels) or https://github.com/PowerShell/PowerShell/issues

Thank you,

**Comment by hobbes** [comment]
yep, having that ticket open with a «feature request» tag and potential milestone would show that you consider the feature but have not implemented it (yet). It also would allow people to discuss it, present use cases,...

**Comment by m-git-s** [comment]
Just to say that easy switching between accounts for outgoing calls is a feature I too look forward to. An 'ask every time' option like the one I'm used to on my dual SIM phone would be ideal,

Thanks to the OP for raising the issue and the dev for responding; at least I know I'm not missing an option that I ought to be able to find!

**Comment by puvi7722** [comment]
+1

**Comment by AdamMiltonBarker** [comment]
Any update on this ?

**Comment by Viish** [comment]
There is an open issue for that: https://github.com/BelledonneCommunications/linphone-android/issues/1218

**Comment by gmaruzz** [comment]
+1

**Comment by ppacher** [comment]
Hey, thanks for this awesome project. +1 as well, I really need a quicker way to select which account to use when dialing
