### ISSUE TITLE
Several new nat policies created

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-android#813]
I'm wondering what the logic of the different nat_policy_refs in Linphone is.

I've tried provisioning STUN/ICE settings using remote provisioning (see xml below). I can see the STUN server ("stun.l.google.com:19302") filled in when I navigate to the "Network" settings. After navigating to the "Account " settings, the STUN server field there is empty. I've filled it in as a test. 

In the linphonerc I can see a several new "nat_policy" elements being created with a new nat_policy_ref. Is this normal behavior? How can I force this with the xml?

```
[nat_policy_1]
ref=dGyrWa2OCx6CUBg

[nat_policy_2]
ref=s-MmMd6wOoWf6ww
stun_server=blabla:1234
protocols=stun,ice

[nat_policy_3]
ref=sD15qZYwwhl3iyJ
stun_server=dummy:3789
protocols=ice
```

```
<config xmlns="http://www.linphone.org/xsds/lpconfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.linphone.org/xsds/lpconfig.xsd lpconfig.xsd">
  <section name="nat_policy_0">
    <entry name="stun_server" overwrite="true">stun.l.google.com:19302</entry>
    <entry name="protocols" overwrite="true">stun,ice</entry>
  </section>
  <section name="net">
    <entry name="firewall_policy" overwrite="true">ice</entry>
    <entry name="stun_server" overwrite="true">stun.l.google.com:19302</entry>
  </section>
  <section name="sip">
    <entry name="root_ca" overwrite="true">/sdcard/linphone/linphoneca.pem</entry>
  </section>
  <section name="auth_info_0">
    <entry name="username" overwrite="true">XXXXXX</entry>
    <entry name="userid" overwrite="true">obfuscated</entry>
    <entry name="algorithm" overwrite="true">MD5</entry>
    <entry name="ha1" overwrite="true">obfuscated</entry>
    <entry name="realm">uzgsip</entry>
    <entry name="domain" overwrite="true">obfuscated</entry>
    <entry name="client_cert_chain" overwrite="true">/sdcard/linphone/linphonecert.pem</entry>
    <entry name="client_cert_key" overwrite="true">/sdcard/linphone/linphonekey.pem</entry>
  </section>
  <section name="proxy_0">
    <entry name="reg_proxy" overwrite="true">&lt;sip:obfuscated;transport=tls&gt;</entry>
    <entry name="reg_identity" overwrite="true">sip:XXXXXX@obfuscated</entry>
    <entry name="reg_route" overwrite="true">&lt;sip:obfuscated;transport=tls&gt;</entry>
    <entry name="reg_expires">3600</entry>
    <entry name="reg_sendregister">1</entry>
    <entry name="publish">0</entry>
    <entry name="publish_expires">0</entry>
    <entry name="avpf">0</entry>
    <entry name="nat_policy_ref" overwrite="true">nat_policy_0</entry>
  </section>
</config>
```

**Comment by Viish** [comment]
One NAT policy should be enough.
Simply change
`<entry name="nat_policy_ref" overwrite="true">nat_policy_0</entry>`
to
`<entry name="nat_policy_ref" overwrite="true">dGyrWa2OCx6CUBg</entry>`
(or any NAT policy ref)

**Comment by driesken** [comment]
Thanks, figured it out. However, I don't think that remote provisioning seems like a foolproof way to configure STUN/ICE. I've noticed that when navigating to the account settings, a new nat policy is created, overriding the one I defined in the XML. I've commented that code as a workaround though.

Is there any way to delete a custom added section in the linphonerc? "Delete account" doesn't seem to restore the config back to linphonerc_default/factory values.

**Comment by driesken** [comment]
Sorry for the bump but I don't think this issue is resolved. I've noticed that when transient_provisioning=0, every time Linphone is started, another (in my case useless) nat_policy is made?

I've tried setting nat_policy_ref to a fixed value as you suggested, but this just throws a warning an creates a new policy instead:
`WARNING Failed to create nat policy from ref [dGyrWa2OCx6CUBg]`
