### ISSUE TITLE
Build linphone sdk error

### ISSUE THREAD

**Issue by SarunyuPrasert** [BelledonneCommunications/linphone-android#819]
I cloned a linphone sdk project on branch release/4.2 and when i build with enable codec2. I got this error

[ 61%] Forcing build for 'EP_mscodec2'
[ 62%] Performing build step for 'EP_mscodec2'
[ 50%] Linking C shared module libmscodec2.so
/Volumes/Android/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/unwind-arm-common.inc:855: error: undefined reference to '__cxa_call_unexpected'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[8]: *** [libmscodec2.so] Error 1
make[7]: *** [CMakeFiles/mscodec2.dir/all] Error 2
make[6]: *** [all] Error 2
make[5]: *** [/Users/sarunyuprasert/Documents/Git_Linphone_SDK_Android_new/linphone-sdk/build/WORK/android-armv7/Stamp/EP_mscodec2/EP_mscodec2-build] Error 2
make[4]: *** [CMakeFiles/EP_mscodec2.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [android-armv7-prefix/src/android-armv7-stamp/android-armv7-build] Error 2
make[1]: *** [CMakeFiles/android-armv7.dir/all] Error 2
make: *** [all] Error 2

**Comment by Viish** [comment]
What NDK are you using ?

**Comment by Viish** [comment]
I just tested (NDK 20 on Fedora 31), build is OK.

**Comment by SarunyuPrasert** [comment]
I'm using NDK r19c

Thank you. I'll try it

**Comment by SarunyuPrasert** [comment]
I'm struct at this point 

Scanning dependencies of target EP_openh264
[ 76%] Creating directories for 'EP_openh264'
[ 76%] No download step for 'EP_openh264'
[ 76%] No patch step for 'EP_openh264'
[ 77%] No update step for 'EP_openh264'
[ 77%] Performing configure step for 'EP_openh264'
[ 77%] Forcing build for 'EP_openh264'
[ 77%] Performing build step for 'EP_openh264'
../../../../..//external/openh264/build/platform-android.mk:54: *** Compiler not found, bad NDKROOT or ARCH?.  Stop.
make[5]: *** [/Users/sarunyuprasert/Documents/Git_Linphone_SDK_Android_4_3/linphone-sdk/build/WORK/android-armv7/Stamp/EP_openh264/EP_openh264-build] Error 2
make[4]: *** [CMakeFiles/EP_openh264.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [android-armv7-prefix/src/android-armv7-stamp/android-armv7-build] Error 2
make[1]: *** [CMakeFiles/android-armv7.dir/all] Error 2
make: *** [all] Error 2


This is my path 'echo $PATH'

/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Users/sarunyuprasert/Library/Android/sdk/platform-tools:/Users/sarunyuprasert/Library/Android/sdk/tools:/Users/sarunyuprasert/Library/Android/android-ndk-r20

**Comment by SarunyuPrasert** [comment]
I'll install Fedora 31 and try to build it again

**Comment by hpng6** [comment]
same problem also.

fatal: ambiguous argument '1.0.0..HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
-- Package file name is belr-1.0.0
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/NG6/linphone-sdk/build/WORK/android-arm64/Build/belr
[ 83%] Forcing build for 'EP_belr'
[ 83%] Performing build step for 'EP_belr'
[ 50%] Built target belr
[ 58%] Linking CXX executable belr-parse
/Users/NG6/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: liblog.so, needed by /Users/NG6/linphone-sdk/build/linphone-sdk/desktop/android-arm64/lib/libbctoolbox.so, not found (try using -rpath or -rpath-link)
/Users/NG6/linphone-sdk/build/linphone-sdk/desktop/android-arm64/lib/libbctoolbox.so: undefined reference to `__android_log_assert'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[8]: *** [tools/belr-parse] Error 1
make[7]: *** [tools/CMakeFiles/belr-parse.dir/all] Error 2
make[6]: *** [all] Error 2
make[5]: *** [/Users/NG6/linphone-sdk/build/WORK/android-arm64/Stamp/EP_belr/EP_belr-build] Error 2
make[4]: *** [CMakeFiles/EP_belr.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [android-arm64-prefix/src/android-arm64-stamp/android-arm64-build] Error 2
make[1]: *** [CMakeFiles/android-arm64.dir/all] Error 2
make: *** [all] Error 2
