### ISSUE TITLE
Bug on LIME Chat to send photo

### ISSUE THREAD

**Issue by p5panam** [BelledonneCommunications/linphone-android#82]
Hello,

I enable LIME Chat on android, and also on another testing device (iphone version of linphone).
I could receive OK pictures on Android, but when i try to send a picture from gallery (Lime enabled) it shows : "Application has stopped"

Any ideas to solve this bug?

regards,

**Comment by DatBewar** [comment]
Hello,
Currently LIME isn't stable on Android or IOS so there are maybe somes bugs.
Do you had some log about this crash?

Best regards
