### ISSUE TITLE
keypad overlays hold (pause) button

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#823]
The pause (hold) button looks ugly, when keypad is opened:
![image](https://user-images.githubusercontent.com/14617699/68523583-51f7ce00-02cc-11ea-9155-ba4018d40014.png)

**Comment by Viish** [comment]
Indeed this isn't very nice, but that depends on the screen resolution.
On all our devices here we don't have it...
What do you suggest ?

**Comment by 532910** [comment]
Expand it to full width, same as the native dialer does:

![image](https://user-images.githubusercontent.com/14617699/68654972-2a10a080-0540-11ea-8efb-cda8e25237c7.png)

**Comment by Viish** [comment]
Done in 5b5a08e00aa2088e7e5a6cfcf8cfb6f711241106

**Comment by 532910** [comment]
Looks better now, and "technically" the issue is fixed, but under "expand it to full width" I meant something like:
![image](https://user-images.githubusercontent.com/14617699/69094414-5d33c200-0a61-11ea-8ad8-c70d54548cc3.png)

**Comment by 532910** [comment]
Moreover, the pause button looks odd (as it is round comparing to other buttons). Possible it will be better to move it somewhere on the bottom panel and do not overlap with keyboard at all.

**Comment by Viish** [comment]
I hear you but I'm not in charge of the design.
Also note the record call and toggle camera buttons are also round like that.

**Comment by Viish** [comment]
And regarding the dialer I did it like that so it is the same as iOS version (and your solution is quite hard to implement considering the current layout file)
