### ISSUE TITLE
Incoming call screen - encryption status

### ISSUE THREAD

**Issue by SomeGeek** [BelledonneCommunications/linphone-android#827]
When Linphone is configured to use both TLS and mandatory media encryption, on the incoming call screen (not answered) the security padlock still displays an open padlock with a cross. This was confusing for me at first - as I thought my calls weren't encrypted and overlooked something in the config.

After some research I found out the cause:

https://github.com/BelledonneCommunications/linphone-android/blob/9a7baf96855b210b0e82f38015cf074d0cbdc987/app/src/main/java/org/linphone/call/CallStatusBarFragment.java#L303

During an incoming call that hasn't been answered yet, Linphone only checks the _media encryption_ status. As the call is not active yet, it returns _none_. However, it can still be considered secured as SIP over TLS is used - which is the only protocol used at that time.

I think this can easily be solved by adding a check to see:

- If a call is a call has not been answered yet, AND
- SIP transport is using TLS

The call initiation is secure.

**Comment by Viish** [comment]
Hi,
Actually it's not that simple.
In case of SRTP, the encryption is signaled via SIP, so we can know the media encryption will be OK or not.
But for ZRTP it will only be known when the stream connection initialize.
TLS isn't encryption for media (RTP streams), only for SIP, so it's not enough.

I made a change to always show the security ok icon on incoming call if media encryption mandatory is enabled. At worst when accepting the call if ZRTP fails there won't be any audio and the status icon will update correctly: f96239bcda822a67bb3650cdccaf24ce0817eccf

Cheers,
