### ISSUE TITLE
SRTP 256 bit Encryption & TLS Version

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#828]
Hi Viish.

Hope you doing good there. I need two information regarding security.

**1) How to set 256 bit encryption in case of SRTP call. Currently Linphone may support 128-bit encryption by default.

2. Which TLS Version Linphone uses. Can we implement TLS V 1.3  with Linphone.**

Please provide me this information.

Thanks in advance.

**Comment by Viish** [comment]
Hi @amit1576 ,
For SRTP crypto suite the default setting is the following ([sip] section, srtp_crypto_suites item):
`AES_CM_128_HMAC_SHA1_80, AES_CM_128_HMAC_SHA1_32, AES_256_CM_HMAC_SHA1_80, AES_256_CM_HMAC_SHA1_32`
If you only want 256 bits, set it in your linphonerc_factory like
```[sip]
srtp_crypto_suites=AES_256_CM_HMAC_SHA1_80,AES_256_CM_HMAC_SHA1_32```

Regarding TLS we rely on MbedTLS library which I believe doesn't supports TLS 1.3 yet.
