### ISSUE TITLE
Unable to start the second call while the first one is on hold.

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#829]
Steps to reproduce:
1. start a call
2. press pause button
3. press keypad button to start the second call
4. entered phone is not shown and there are not start call button (only end call buttons that ends the call that is on hold)
![image](https://user-images.githubusercontent.com/14617699/69095205-e5ff2d80-0a62-11ea-8bd7-86934d36a18d.png)

**Comment by Viish** [comment]
Yes this is normal because the dialer isn't meant for that, only to send DTMFs.
To do what you want use the add call button in the menu with the gear icon.

**Comment by 532910** [comment]
So it's another design issue. At least keypad should be disabled when the call is on hold as it does nothing.
