### ISSUE TITLE
When I change the C code, How can I make it ?

### ISSUE THREAD

**Issue by AimeeChen** [BelledonneCommunications/linphone-android#83]
I change your C code , and then make the project on the Ubuntu.  When I debug the C code, I find the result have no change, such as , I change
ms_message("ice: Select losing valid pair...");
to
ms_message("ice2: Select losing valid pair...");

The logcat message still is "ice: Select losing valid pair..."

**Comment by DatBewar** [comment]
Hi,
before rebuild your app, you need to run "make" on root project to rebuild linphone.

**Comment by AimeeChen** [comment]
Hi, I really run "make" on root project, and make successfully.

**Comment by AimeeChen** [comment]
Hi, I really run "make" on root project, and make successfully.

**Comment by DatBewar** [comment]
Did you edit the true file, there are sample code which are the same as submodule.
Example:
sample/submodules/mediastreamer2/src/voip/ice.c
and
submodules/mediastreamer2/src/voip/ice.c

**Comment by AimeeChen** [comment]
Thanks~ @DatBewar . We solve this problem. 
When we make the project successfully, we remove the project to another directory. We make the project again,  we find this problem. And then the project is moved back to the original directory. After rebuild the project, I  can see the message of  logcat ,which have "ice2: Select losing valid pair..."
