### ISSUE TITLE
Call declined be calle is not logged nor missed.

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#832]
Steps to reproduce:
1. start call from another sip phone to linphone
2. linphone starts ringing and shows an incoming call (as expected)
3. hangup on incoming sip phone
4. linphone stops ringing (as expected) but no missed call notification will be shown and will not be listed in the call log

**Comment by Viish** [comment]
Hi,
Indeed if you decline a call locally it won't be listed as missed, you won't have a missed call notification and the badge on the history button won't increase.
However you will see the call as incoming.

**Comment by 532910** [comment]
> Indeed if you decline a call locally it won't be listed as missed, you won't have a missed call notification and the badge on the history button won't increase.

Is it correct?


> However you will see the call as incoming.

Indeed, I see it as incoming, but if the call log is opened during such call I need to reload it (switch to contacts and back to call log) to see the incoming receord.

**Comment by Viish** [comment]
> Indeed, I see it as incoming, but if the call log is opened during such call I need to reload it (switch to contacts and back to call log) to see the incoming receord.

Fixed in 71efda66cea6e4ef3bea3b529b508caf33b2aa0e

**Comment by 532910** [comment]
4.2.0-beta.41+8f9aeecf still needs to be reloaded

**Comment by 532910** [comment]
> Indeed if you decline a call locally it won't be listed as missed, you won't have a missed call notification and the badge on the history button won't increase.

Grandstream GXP1620 shows such calls (declined by callee) as missed.

**Comment by 532910** [comment]
For clarity: this issue is about "calls terminated by the part who starts a call".

**Comment by Viish** [comment]
> For clarity: this issue is about "calls terminated by the part who starts a call".

Ok in this case yes the call should be missed.
A missed call is a call that was ringing on the device of the user and for which the user hasn't done any action.
But this works (at least on my phones). If not, please attach debug logs.

**Comment by 532910** [comment]
Sent.

**Comment by Viish** [comment]
Your app is on commit 8f9aeecf822bf2addcbb6d60b007f01bb0de3f5b but the fix is in commit 71efda66cea6e4ef3bea3b529b508caf33b2aa0e (two commits later).

**Comment by Viish** [comment]
Also for the status of the call that isn't missed, this is because of your SIP server.
The CANCEL message has a Reason header with Q.850 protocol and cause 0, which doesn't mean call has been missed.

**Comment by 532910** [comment]
> > Indeed, I see it as incoming, but if the call log is opened during such call I need to reload it (switch to contacts and back to call log) to see the incoming receord.
> 
> Fixed in [71efda6](https://github.com/BelledonneCommunications/linphone-android/commit/71efda66cea6e4ef3bea3b529b508caf33b2aa0e)

ack!

**Comment by 532910** [comment]
Just tested missed calls with kotlin rewrite.
In a difference with java version is shows

**Comment by 532910** [comment]
I'm not trying to say it should, just noted a differente behaviour.

**Comment by Viish** [comment]
commit 24ca86ff23640d15a80ea0c7b561a4df405aed86 (HEAD -> feature/kotlin_rewrite, origin/feature/kotlin_rewrite)
Author: Sylvain Berfini <sylvain.berfini@belledonne-communications.com>
Date:   Fri Oct 23 20:40:34 2020 +0200
    Fixed call log showed as missed in notification but not in call history list
