### ISSUE TITLE
three letters doesn't fit info user icon

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#834]
![image](https://user-images.githubusercontent.com/14617699/69175338-9da04800-0b14-11ea-8cdb-f0b61a2bd1d4.png)

**Comment by 532910** [comment]
![image](https://user-images.githubusercontent.com/14617699/69175602-1a332680-0b15-11ea-9614-e5c14e7d2ac0.png)

**Comment by Viish** [comment]
Fixed in 260d38669e34e981e7d4db33fb346833ee00137d (I limited the length to 2)

**Comment by 532910** [comment]
Nice, thank you!
