### ISSUE TITLE
keypad overlapps audio output and gear button menus

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#835]
It looks like "I press gear or speaker button, but nothing happens":
![image](https://user-images.githubusercontent.com/14617699/69182461-1d80df00-0b22-11ea-952d-7f36141665c9.png)

**Comment by Viish** [comment]
Fixed in 66f349ebd214a8c7b7497396360d919af911f671

**Comment by 532910** [comment]
I confirm it works, thank you!
