### ISSUE TITLE
sip account not going unreachable in background !

### ISSUE THREAD

**Issue by webjframework** [BelledonneCommunications/linphone-android#836]
Hi there ,

I am using Android 7 and latest linphone .( in settings the background mode is not checked) .

I have 2 accounts .One linphone and one with my asterisk server (for outgoing calls only).
I want the phone to wake up with the push of the linphone account witch does but when it goes to background i want the other account to go unreachable in order to avoid the battery drain.
In the previous version it was working like that and i think this is the meaning of not background mode.

Further more when you receive a missed call , its a good idea to not stay the pop up screen in foreground. You need only a notification of the missed call .

Thanks in advance

**Comment by Viish** [comment]
Hi,
Indeed in the event you have 2 accounts, one of which sip.linphone.org, it won't be unregistered when the app stops.
But don't worry it won't drain any battery as the app is off.
Cheers,

**Comment by webjframework** [comment]
i tried again with ONLY  one no linphone account and its have the same
behavior ..

it drain battery and data because asterisk send qualify to sip peer,
In the previous version worked right !

Cheers

**Comment by Viish** [comment]
If the app is killed how can Asterisk send packets to your account and drain the battery ?

**Comment by webjframework** [comment]
when i manually kill the app from the recent it the account is going
unreachable ...So the issue is that when i receive a call from push after
that is not killed ...

**Comment by Viish** [comment]
The push will wake up the app and all accounts will register, that's expected.
After that, either Android kills the app again (after a few minutes in background) and you won't have any battery drain, or the app stays and indeed that might happen. 
However how do you want the app to unregister an account just because it is in background ?

**Comment by webjframework** [comment]
the app never unregister the account the asterisk server do that
because the app is killed ...the issue is that the app not killed by
android at least in adnroid 7.

**Comment by Viish** [comment]
Sorry but I fail to see what the 4.1 version does differently about that. It doesn't kill itself in background either.

**Comment by webjframework** [comment]
I am not expecting from a app to kill itself

so explain to me what the background mode means ???

**Comment by Viish** [comment]
The background mode shows a notification in the top bar that tells Android not to kill the Service. It is not needed when using push notifications because the push will start the app if it is killed, but if you don't have push and if the Service is killed you will never receive a call or a message.

**Comment by webjframework** [comment]
so if the background mode is not checked the app must be killed by android
...right ??

because if its right it's not killed !!!

**Comment by Viish** [comment]
Yes without background mode Android will kill the app.
However depending on the Android version and the device manufacturer the time can be variable.

**Comment by webjframework** [comment]
the issue is that yesterday i was waiting 7 hours and it was not killed !!!

**Comment by Viish** [comment]
Have you checked the app battery settings in Android applications parameters and that you didn't allow it to run indefinitely ?

**Comment by Viish** [comment]
If you want you can try with branch feature/accelerate_service_killing_in_background, it will automatically stops the Service in background

**Comment by webjframework** [comment]
i set the linphone in restrict mode and i was waiting for 30 min ...no kill
of service

 branch??

you mean to download a linphone night version with that feature ??

and when you enable this feature it will still wake with the push ?

**Comment by Sikandar106** [comment]
hi i am developing and sip dialar app where i user transport tcp along with other information like domain and username and password but it kept on saying unauthorized error and when i try to login same extension with same tranport type in your devleoped linphone app so i am getting an error account does not exist but on the same time i login with grandstream wave i easily get inside wihtout any error kindly reslove this issue
