### ISSUE TITLE
Downgrading Linphone Wiped Everything

### ISSUE THREAD

**Issue by muellert** [BelledonneCommunications/linphone-android#839]
Trying to downgrade Linphone wiped everything. Now I have no account configured, and not any calling history. Linphone should have an option to keep data, and downgrades should just work.

**Comment by Viish** [comment]
Downgrading linphone is a very bad idea and we won't ever support this.
We have a database that keeps a lot of information and it's scheme is often updated when we add new features, so a downgraded app will never be able to read it.
