### ISSUE TITLE
bluetooth route doesn't hotplug during the call

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#842]
Steps to reproduce:
1. power bt headset off
2. start a call
3. power bt headset on -> it connects
4. linphone doesn't show bt as available output

**Comment by Viish** [comment]
Please attach logs for this issue too.

**Comment by 532910** [comment]
Would you like to say you can't reproduce it, or have no BT headset?

**Comment by Viish** [comment]
My bad I misread.
Should be fixed in 9a928fbb410362c948ca059e66e36e7f167ef8c0

**Comment by 532910** [comment]
Fixed, but not completely. Steps to reproduce:
1. switch the phone on with BT in the off state  (turn off BT on the phone and reboot it)
![image](https://user-images.githubusercontent.com/14617699/69893729-dfa46780-1326-11ea-9f73-cd1c8ebb8bfb.png)

2. open linphone and start a call
3. power BT on -> headphone connects
4. linphone doesn't show bt as available output

**Comment by 532910** [comment]
Could you confirm it?

**Comment by Viish** [comment]
As soon as my headset finish charging ;)

**Comment by Viish** [comment]
I confirm it.
Fixed in commit d20379a4846ba23ba6d4b9c32b9fee93569b6061, will be part of release 4.2

**Comment by 532910** [comment]
I confirm, fixed now.
