### ISSUE TITLE
Speaker-audio error

### ISSUE THREAD

**Issue by nzkar** [BelledonneCommunications/linphone-android#845]
I have linphone android version 4.1. When two linphone apps are in call (android 9.0) and one activates its speaker, it behaves like it is muted permanently (only one side faces this error, the other can activate/deactivate speaker and no problem with it). I have to remove and reinstall the application to fix it. I don't see this error with Android v5.1 (linphone 4.1). Also there is no error with linphone v4.2.0 beta with Android 9.0 phones. I checked your commits and merged my code however I still have this error. What did you change to fix this error?

**Comment by Viish** [comment]
HI,
I wasn't aware of the issue so it will be hard for me to tell you how I fixed it.
Are you sure it isn't in your own modifications ?
