### ISSUE TITLE
Camera permission issue 4.3.0-alpha

### ISSUE THREAD

**Issue by jfalexvijay** [BelledonneCommunications/linphone-android#847]
I compiled linphone SDK and tried to use libs in my Android app (4.3.0-alpha-8-g78c8c61c9). Calls and its audio is fine. But the the problem is; Video is not working in Android 6.0 and above versions. Also I have given the camera access. But I am seeing the below line in logcat:

<code>Linphone: [Camera2 Capture] No camera detected, check you have granted CAMERA permission !</code>

(I want to fix the above issue).

As per the detail in https://github.com/BelledonneCommunications/linphone-android/issues/803 link, I am unable to use the aar file in my project. (I am using linphone in my XXX app. I want to use XXX as module in different apps. So linphone aar file is working with XXX. But as a module it is not working in other app.)

Plz help me on this.

**Comment by Viish** [comment]
> (I want to fix the above issue).

Are you sure you granted the Camera permission ?
Also you should use the release/4.3 branch from the SDK, it contains many fixes that aren't on master branch yet.

> But as a module it is not working in other app.
I can't help you much with that, but if you want you can contact our sales department for a quotation : sales@belledonne-communications.com

**Comment by jfalexvijay** [comment]
@Viish, actually I want to fix the camera issue.. I have given all the needed permission.. Video call is working in Android 5.x and lower version.. but not working in 6.x and above.

**Comment by Viish** [comment]
Do you reproduce with linphone-android app?

**Comment by jfalexvijay** [comment]
I have not verified with linphone android app.. I will test and update you..

**Comment by jfalexvijay** [comment]
Today only I got the chance to test it.

I recently updated to MacOS Catalina, version 10.6). Android Studio 3.5. (I compiled linphone after the OS updates)

I am unable to import linphone Android project from linphone-sdk. it is giving multiple error while importing.

**Comment by jfalexvijay** [comment]
You commented on 25 Oct https://github.com/BelledonneCommunications/linphone-android/issues/803#issuecomment-546315947

<code>Yes you can use latest SDK 4.3.0-beta.3+b7cf317 but changes are also in the app version 4.2.0-beta.2+426262c3</code>

As per the issue no 803, video issue is there in older version.. but the fix is available only in beta?

**Comment by Viish** [comment]
We are in the process of releasing a new version of both our SDK and our mobile app.
For that we create a stabilization branch to prevent new developments to interfere with the quality and stability of the release.
So yes there are fixes on releases branch (tagged as beta) that will be merged into master branch (tagged as alpha) after the release.

**Comment by jfalexvijay** [comment]
@Viish Thank you for your quick reply..

Can you please guide me to get the source code to compile in my machine.

**Comment by Viish** [comment]
Simply checkout the release/4.2 branch of linphone-android repository and open it on Android Studio, nothing more.

**Comment by jfalexvijay** [comment]
@Viish looks like linphone-android is using already compiled linphone-sdk where G729 is not available.

Please help me on this

**Comment by Viish** [comment]
Indeed the prebuilt SDK doesn't include G729.
You can still build your own SDK with G729, simply follow the README instructions.

**Comment by jfalexvijay** [comment]
@Viish Now this is the issue.. please check my above comment https://github.com/BelledonneCommunications/linphone-android/issues/847#issuecomment-559707810

**Comment by Viish** [comment]
What are you errors ?

**Comment by jfalexvijay** [comment]
Issue: I have given all the needed permission.. Video call is working in Android 5.x and lower version.. but not working in 6.x and above.

https://github.com/BelledonneCommunications/linphone-android/issues/847#issuecomment-559126870

**Comment by Viish** [comment]
Do you reproduce with linphone-android app ?
Can you attach logs from the SDK ?

**Comment by jfalexvijay** [comment]
My issue is same as https://github.com/BelledonneCommunications/linphone-android/issues/803

**Comment by Viish** [comment]
If you want my help start by giving me the information I ask you for.

**Comment by jfalexvijay** [comment]
I have attached a log file here. Log is from receiving incoming call till disconnecting that call.

[log for linphone.txt](https://github.com/BelledonneCommunications/linphone-android/files/3959932/log.for.linphone.txt)

Please let me know if anything needed.

**Comment by Viish** [comment]
From your logs you are using the "static picture" camera so it is expected you don't have video.
Change the video capture source configured in the Core.
And please attach the logs of the start of the app so I can see the real cameras are correctly found.

**Comment by jfalexvijay** [comment]
@Viish I got the app log from 2 phones:

1. <code>Xiaomi Redmi 6 Pro - Android 8.1.0</code>
    App is receiving video from other end. But error for camera access.
[log_from_redmi_phone-2019-12-16.txt](https://github.com/BelledonneCommunications/linphone-android/files/3966925/log_from_redmi_phone-2019-12-16.txt)

2. <code>HMD Global TA - 1021 - Android 9.0</code>
    App is working as expected. Sending and receiving video. (no camera issue)
[log_from_sony_phone-2019-12-16.txt](https://github.com/BelledonneCommunications/linphone-android/files/3966928/log_from_sony_phone-2019-12-16.txt)

**Comment by Viish** [comment]
You are using an alpha version of 4.3 SDK. Please update to 4.3 release.
Also do you reproduce with linphone-android 4.2 version from the Store ? If yes please attach logs from linphone-android.

**Comment by jfalexvijay** [comment]
I used below commend to clone the source code.. 
<code>"git clone https://gitlab.linphone.org/BC/public/linphone-sdk.git --recursive"</code>

How do I get 4.3 release version?

I have not verified linphone-android 4.2 (PlayStore version).

**Comment by jfalexvijay** [comment]
Just I verified linphone-android 4.2 (PlayStore version). Video is working fine.
