### ISSUE TITLE
Problems after the creation of product flavors

### ISSUE THREAD

**Issue by Nicolo-sudo** [BelledonneCommunications/linphone-android#848]
Hi there!

I have added some product flavors with different applicationId, minSdkVersion ecc..
When I start the app some exception are thrown:

> 11-27 12:17:53.788 20373-20373/? I/art: Late-enabling -Xcheck:jni
> 11-27 12:17:53.888 20373-20392/com.linphone.debug E/HAL: load: id=gralloc != hmi->id=gralloc
> 11-27 12:17:53.969 20373-20373/com.linphone.debug I/FirebaseInitProvider: FirebaseApp initialization successful
> 11-27 12:17:53.998 20373-20373/com.linphone.debug I/HwCust: Constructor found for class android.app.HwCustHwWallpaperManagerImpl
> 11-27 12:17:54.019 20373-20373/com.linphone.debug I/HwSecImmHelper: mSecurityInputMethodService is null
> 11-27 12:17:54.055 20373-20373/com.linphone.debug W/FactoryImpl: Unable to load optional library ffmpeg-linphone: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.linphone.debug-1/base.apk"],nativeLibraryDirectories=[/data/app/com.linphone.debug-1/lib/arm64, /data/app/com.linphone.debug-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libffmpeg-linphone.so"
> 11-27 12:17:54.249 20373-20373/com.linphone.debug I/HwCust: Constructor found for class android.app.HwCustNotificationImpl
> 11-27 12:17:54.271 20373-20373/com.linphone.debug E/WifiManager: WifiServiceMessenger == null
> 11-27 12:17:54.496 20373-20428/com.linphone.debug I/OMXClient: Using client-side OMX mux.
> 11-27 12:17:54.510 20373-20434/com.linphone.debug I/OMXClient: Using client-side OMX mux.
> 11-27 12:17:54.516 20373-20438/com.linphone.debug I/OMXClient: Using client-side OMX mux.
> 11-27 12:17:54.516 20373-20438/com.linphone.debug E/ACodec: Unable to instantiate a encoder for type 'video/hevc' with err 0xfffffffe.
> 11-27 12:17:54.516 20373-20438/com.linphone.debug E/ACodec: signalError(omxError 0xfffffffe, internalError -2)
> 11-27 12:17:54.517 20373-20437/com.linphone.debug E/MediaCodec: Codec reported err 0xfffffffe, actionCode 0, while in state 1
> 11-27 12:17:54.517 20373-20373/com.linphone.debug W/MediaCodec-JNI: try to release MediaCodec from JMediaCodec::~JMediaCodec()...
> 11-27 12:17:54.517 20373-20373/com.linphone.debug W/MediaCodec-JNI: done releasing MediaCodec from JMediaCodec::~JMediaCodec().
> 11-27 12:17:54.518 20373-20373/com.linphone.debug W/System.err: java.lang.IllegalArgumentException: Failed to initialize video/hevc, error 0xfffffffe
> 11-27 12:17:54.518 20373-20373/com.linphone.debug W/System.err:     at android.media.MediaCodec.native_setup(Native Method)
> 11-27 12:17:54.518 20373-20373/com.linphone.debug W/System.err:     at android.media.MediaCodec.<init>(MediaCodec.java:1697)
> 11-27 12:17:54.518 20373-20373/com.linphone.debug W/System.err:     at android.media.MediaCodec.createEncoderByType(MediaCodec.java:1637)
> 11-27 12:17:54.518 20373-20373/com.linphone.debug W/System.err:     at org.linphone.core.FactoryImpl.createCore3(Native Method)
> 11-27 12:17:54.518 20373-20373/com.linphone.debug W/System.err:     at org.linphone.core.FactoryImpl.createCore(Factory.java:520)
> 11-27 12:17:54.518 20373-20373/com.linphone.debug W/System.err:     at org.linphone.LinphoneManager.startLibLinphone(LinphoneManager.java:443)
> 11-27 12:17:54.518 20373-20373/com.linphone.debug W/System.err:     at org.linphone.LinphoneContext.start(LinphoneContext.java:164)
> 11-27 12:17:54.518 20373-20373/com.linphone.debug W/System.err:     at org.linphone.LinphoneService.onStartCommand(LinphoneService.java:84)
> 11-27 12:17:54.518 20373-20373/com.linphone.debug W/System.err:     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3047)
> 11-27 12:17:54.518 20373-20373/com.linphone.debug W/System.err:     at android.app.ActivityThread.access$2200(ActivityThread.java:165)
> 11-27 12:17:54.518 20373-20373/com.linphone.debug W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
> 11-27 12:17:54.518 20373-20373/com.linphone.debug W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
> 11-27 12:17:54.518 20373-20373/com.linphone.debug W/System.err:     at android.os.Looper.loop(Looper.java:150)
> 11-27 12:17:54.518 20373-20373/com.linphone.debug W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5621)
> 11-27 12:17:54.518 20373-20373/com.linphone.debug W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
> 11-27 12:17:54.518 20373-20373/com.linphone.debug W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
> 11-27 12:17:54.518 20373-20373/com.linphone.debug W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
> 11-27 12:17:54.522 20373-20440/com.linphone.debug I/OMXClient: Using client-side OMX mux.
> 11-27 12:17:54.568 20373-20373/com.linphone.debug W/CameraBase: An error occurred while connecting to camera: 0
> 11-27 12:17:54.568 20373-20373/com.linphone.debug E/Camera-JNI: android_hardware_Camera_native_setup Error: -1 
> 11-27 12:17:54.568 20373-20373/com.linphone.debug E/Camera: Camera new cameraInitNormal:-1
> 11-27 12:17:54.569 20373-20373/com.linphone.debug W/System.err: java.lang.RuntimeException: Unknown camera error(-1)
> 11-27 12:17:54.569 20373-20373/com.linphone.debug W/System.err:     at android.hardware.Camera.<init>(Camera.java:562)
> 11-27 12:17:54.569 20373-20373/com.linphone.debug W/System.err:     at android.hardware.Camera.open(Camera.java:383)
> 11-27 12:17:54.569 20373-20373/com.linphone.debug W/System.err:     at org.linphone.mediastream.video.capture.hwconf.AndroidCameraConfigurationReader9.probeCameras(AndroidCameraConfigurationReader9.java:40)
> 11-27 12:17:54.569 20373-20373/com.linphone.debug W/System.err:     at org.linphone.mediastream.video.capture.hwconf.AndroidCameraConfiguration.probeCamerasSDK9(AndroidCameraConfiguration.java:82)
> 11-27 12:17:54.569 20373-20373/com.linphone.debug W/System.err:     at org.linphone.mediastream.video.capture.hwconf.AndroidCameraConfiguration.initCamerasCache(AndroidCameraConfiguration.java:67)
> 11-27 12:17:54.569 20373-20373/com.linphone.debug W/System.err:     at org.linphone.mediastream.video.capture.hwconf.AndroidCameraConfiguration.retrieveCameras(AndroidCameraConfiguration.java:35)
> 11-27 12:17:54.569 20373-20373/com.linphone.debug W/System.err:     at org.linphone.mediastream.video.capture.AndroidVideoApi5JniWrapper.detectCamerasCount(AndroidVideoApi5JniWrapper.java:46)
> 11-27 12:17:54.569 20373-20373/com.linphone.debug W/System.err:     at org.linphone.mediastream.video.capture.AndroidVideoApi9JniWrapper.detectCamerasCount(AndroidVideoApi9JniWrapper.java:37)
> 11-27 12:17:54.569 20373-20373/com.linphone.debug W/System.err:     at org.linphone.core.FactoryImpl.createCore3(Native Method)
> 11-27 12:17:54.569 20373-20373/com.linphone.debug W/System.err:     at org.linphone.core.FactoryImpl.createCore(Factory.java:520)
> 11-27 12:17:54.569 20373-20373/com.linphone.debug W/System.err:     at org.linphone.LinphoneManager.startLibLinphone(LinphoneManager.java:443)
> 11-27 12:17:54.569 20373-20373/com.linphone.debug W/System.err:     at org.linphone.LinphoneContext.start(LinphoneContext.java:164)
> 11-27 12:17:54.569 20373-20373/com.linphone.debug W/System.err:     at org.linphone.LinphoneService.onStartCommand(LinphoneService.java:84)
> 11-27 12:17:54.569 20373-20373/com.linphone.debug W/System.err:     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3047)
> 11-27 12:17:54.569 20373-20373/com.linphone.debug W/System.err:     at android.app.ActivityThread.access$2200(ActivityThread.java:165)
> 11-27 12:17:54.569 20373-20373/com.linphone.debug W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
> 11-27 12:17:54.569 20373-20373/com.linphone.debug W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
> 11-27 12:17:54.569 20373-20373/com.linphone.debug W/System.err:     at android.os.Looper.loop(Looper.java:150)
> 11-27 12:17:54.569 20373-20373/com.linphone.debug W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5621)
> 11-27 12:17:54.569 20373-20373/com.linphone.debug W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
> 11-27 12:17:54.569 20373-20373/com.linphone.debug W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
> 11-27 12:17:54.569 20373-20373/com.linphone.debug W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
> 11-27 12:17:54.573 20373-20373/com.linphone.debug W/CameraBase: An error occurred while connecting to camera: 0
> 11-27 12:17:54.573 20373-20373/com.linphone.debug E/Camera-JNI: android_hardware_Camera_native_setup Error: -1 
> 11-27 12:17:54.573 20373-20373/com.linphone.debug E/Camera: Camera new cameraInitNormal:-1
> 11-27 12:17:54.573 20373-20373/com.linphone.debug W/System.err: java.lang.RuntimeException: Unknown camera error(-1)
> 11-27 12:17:54.574 20373-20373/com.linphone.debug W/System.err:     at android.hardware.Camera.<init>(Camera.java:562)
> 11-27 12:17:54.574 20373-20373/com.linphone.debug W/System.err:     at android.hardware.Camera.open(Camera.java:383)
> 11-27 12:17:54.574 20373-20373/com.linphone.debug W/System.err:     at org.linphone.mediastream.video.capture.hwconf.AndroidCameraConfigurationReader9.probeCameras(AndroidCameraConfigurationReader9.java:40)
> 11-27 12:17:54.574 20373-20373/com.linphone.debug W/System.err:     at org.linphone.mediastream.video.capture.hwconf.AndroidCameraConfiguration.probeCamerasSDK9(AndroidCameraConfiguration.java:82)
> 11-27 12:17:54.574 20373-20373/com.linphone.debug W/System.err:     at org.linphone.mediastream.video.capture.hwconf.AndroidCameraConfiguration.initCamerasCache(AndroidCameraConfiguration.java:67)
> 11-27 12:17:54.574 20373-20373/com.linphone.debug W/System.err:     at org.linphone.mediastream.video.capture.hwconf.AndroidCameraConfiguration.retrieveCameras(AndroidCameraConfiguration.java:35)
> 11-27 12:17:54.574 20373-20373/com.linphone.debug W/System.err:     at org.linphone.mediastream.video.capture.AndroidVideoApi5JniWrapper.detectCameras(AndroidVideoApi5JniWrapper.java:52)
> 11-27 12:17:54.574 20373-20373/com.linphone.debug W/System.err:     at org.linphone.mediastream.video.capture.AndroidVideoApi9JniWrapper.detectCameras(AndroidVideoApi9JniWrapper.java:41)
> 11-27 12:17:54.574 20373-20373/com.linphone.debug W/System.err:     at org.linphone.core.FactoryImpl.createCore3(Native Method)
> 11-27 12:17:54.574 20373-20373/com.linphone.debug W/System.err:     at org.linphone.core.FactoryImpl.createCore(Factory.java:520)
> 11-27 12:17:54.574 20373-20373/com.linphone.debug W/System.err:     at org.linphone.LinphoneManager.startLibLinphone(LinphoneManager.java:443)
> 11-27 12:17:54.574 20373-20373/com.linphone.debug W/System.err:     at org.linphone.LinphoneContext.start(LinphoneContext.java:164)
> 11-27 12:17:54.574 20373-20373/com.linphone.debug W/System.err:     at org.linphone.LinphoneService.onStartCommand(LinphoneService.java:84)
> 11-27 12:17:54.574 20373-20373/com.linphone.debug W/System.err:     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3047)
> 11-27 12:17:54.574 20373-20373/com.linphone.debug W/System.err:     at android.app.ActivityThread.access$2200(ActivityThread.java:165)
> 11-27 12:17:54.574 20373-20373/com.linphone.debug W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
> 11-27 12:17:54.574 20373-20373/com.linphone.debug W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
> 11-27 12:17:54.574 20373-20373/com.linphone.debug W/System.err:     at android.os.Looper.loop(Looper.java:150)
> 11-27 12:17:54.574 20373-20373/com.linphone.debug W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5621)
> 11-27 12:17:54.574 20373-20373/com.linphone.debug W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
> 11-27 12:17:54.574 20373-20373/com.linphone.debug W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
> 11-27 12:17:54.574 20373-20373/com.linphone.debug W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
> 11-27 12:17:55.161 20373-20373/com.linphone.debug I/Choreographer: Skipped 67 frames!  The application may be doing too much work on its main thread.
> 11-27 12:17:55.192 20373-20406/com.linphone.debug E/HAL: load: id=gralloc != hmi->id=gralloc
> 11-27 12:17:55.192 20373-20406/com.linphone.debug I/OpenGLRenderer: Initialized EGL, version 1.4
> 11-27 12:17:55.394 20373-20373/com.linphone.debug I/HwSecImmHelper: mSecurityInputMethodService is null
> 11-27 12:17:55.395 20373-20373/com.linphone.debug W/InputMethodManager: Current bind isn't success!
> 11-27 12:17:55.512 20373-20373/com.linphone.debug W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
> 11-27 12:17:55.550 20373-20373/com.linphone.debug I/art: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>
> 11-27 12:17:55.551 20373-20373/com.linphone.debug I/art: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>
> 11-27 12:17:55.997 20373-20373/com.linphone.debug I/HwSecImmHelper: mSecurityInputMethodService is null
> 11-27 12:17:55.998 20373-20373/com.linphone.debug I/HwSecImmHelper: mSecurityInputMethodService is null
> 11-27 12:17:56.007 20373-20399/com.linphone.debug I/SendBroadcastPermission: action:com.google.firebase.MESSAGING_EVENT, mPermissionType:0
> 11-27 12:17:56.047 20373-20467/com.linphone.debug I/FirebaseIdService: [Push Notification] Refreshed token: cnV5EcL1YmM:APA91bH5NYTJueUpwwD8tkJJs9WqCAztpjX_PcIQGR5kUZ6-UV06lWD1KsB5tpMLTq-IeBTngBYl9HC6JrkNUBXSrUKuFhTpJ5OxwmCi5nsh5G4qV0ivaswl4rvqtPauriNLauHDpE6m
> 11-27 12:17:57.094 20373-20373/com.linphone.debug E/Dialog: show mWindowManager.addView RuntimeException
> 11-27 12:17:58.154 20373-20373/com.linphone.debug I/HwSecImmHelper: mSecurityInputMethodService is null
> 11-27 12:17:58.155 20373-20373/com.linphone.debug I/HwSecImmHelper: mSecurityInputMethodService is null
>

The application is running correctly but I wish to fix this errors.

Could cause some unexpected behaviours?

Thanks in advance

**Comment by Viish** [comment]
The mediacodec error is expected.
However your camera issue isn't. Did you granted the Camera permission to your app ?
