### ISSUE TITLE
Early media causes audio distortion

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#849]
Hi,

I use linphone4.0.1.  and I add early media function.
 when device A and device B are talking ,  the delay of audio will be very large, 
After a few seconds of talking, the voice will be distorted for a few seconds, and then it will be normal.
Why is that?
Can this be modified？

By the way, I'd like to recommend a linphone version with a relatively small audio and video delay and relatively stable early media.
thanks.

**Comment by Viish** [comment]
First of all, don't use linphone 4.0.1 but instead either the 4.1.1 or the next to come release 4.2, your issue is most probably already fixed.
