### ISSUE TITLE
Speaker-audio error #845

### ISSUE THREAD

**Issue by nzkar** [BelledonneCommunications/linphone-android#850]
Related to the closed issue Speaker-audio error #845, can you please try version 4.1 with Android 9. I checked my modifications many times but I believe that it may be related to the Android or Linphone SDK because the problem does not happen with Android versions 5.1 and 8.1. I face it only with my android 9 devices. So can you please verify if you see the problem with 4.1 on Android 9? If you don't then I will try to merge my code to linphone 4.2.

**Comment by Viish** [comment]
Sorry but I don't have time to investigate issues in previous releases when the latest one works fine.
