### ISSUE TITLE
Incoming Calls Issue

### ISSUE THREAD

**Issue by GB8994** [BelledonneCommunications/linphone-android#851]
I am just going through with your SDK and i am getting some issue on incoming calls in Android Version  9 and above when application was killed.

I found that FirebaseMessinging.java file not execute on Android Version 9 above , but i add all the respective dependencies.

I am also able to integrate it successfully and able to receive a call when the app is in the foreground. But issue occurred when the app is forced closed from Mobile recent tabs, I am not able to receive any call in-app. I have searched for it and also added my google-service.json file as well. and also try by setting the "kill_service_with_task_manager" flag to false in res/values/non_localizable_custom.xml file.

When application was killed, it destroy the Linphone Service .

I am getting this error when i kill the app
![meetme2](https://user-images.githubusercontent.com/57259742/69856182-117be680-12b3-11ea-81d9-8cadd2f376f9.PNG)

Please reply as soon as possible.

**Comment by Viish** [comment]
From your logs it looks like the Service crashed. Check for the crash log.
Also FirebaseMessaging does work well on Android 9+, check your push setup.
What version of the app are you using ?
If you want more help from me attach library logs (settings -> advanced -> debug logs).

**Comment by GB8994** [comment]
As per your response please check the respected debug log file.

[debuglog.txt](https://github.com/BelledonneCommunications/linphone-android/files/3909913/debuglog.txt)

**Comment by Viish** [comment]
Still no linphone logs in your file.

**Comment by Viish** [comment]
I'm closing this issue as it clearly is an issue in your own fork.
I'll give it a look again if you attach SDK logs.
