### ISSUE TITLE
Videocall sometimes crashes

### ISSUE THREAD

**Issue by Nicolo-sudo** [BelledonneCommunications/linphone-android#852]
Hi there, 
sometimes the videocall crashes without pressing the hangup button.

From my logs:

D/ACodec: [OMX.MTK.VIDEO.ENCODER.AVC] onInputBufferFilled ID 8 w/ time -1 eos 0 mode 0 err 0
    [OMX.MTK.VIDEO.ENCODER.AVC] onInputBufferFilled ID 9 w/ time -1 eos 0 mode 0 err 0
    [OMX.MTK.VIDEO.ENCODER.AVC] onInputBufferFilled ID 10 w/ time -1 eos 0 mode 0 err 0
D/ACodec: [OMX.MTK.VIDEO.ENCODER.AVC] onInputBufferFilled ID 11 w/ time -1 eos 0 mode 0 err 0
D/ACodec: [OMX.MTK.VIDEO.ENCODER.AVC] onInputBufferFilled ID 12 w/ time -1 eos 0 mode 0 err 0
I/ACodec: freeBuffersOnPort portIndex 0
I/ACodec: freeBuffersOnPort portIndex 1
D/ACodec: [OMX.MTK.VIDEO.ENCODER.AVC] Now Idle->Loaded
    [OMX.MTK.VIDEO.ENCODER.AVC] Now Loaded
I/MediaCodec: [onMessageReceived]line:1592 [OMX.MTK.VIDEO.ENCODER.AVC][what=kWhatShutdownCompleted][state 9][msg='AMessage(what = 'codc', target = 50) = {
      int32_t what = 1935896429
    }' ]
I/MediaCodec: [release]line:647 [OMX.MTK.VIDEO.ENCODER.AVC]+++
D/ACodec: Now uninitialized
    UninitializedState, mIsAudioBufferLogSwitchOn=0
    UninitializedState, mIsVideoBufferLogSwitchOn=0
I/MediaCodec: [onMessageReceived]line:1592 [OMX.MTK.VIDEO.ENCODER.AVC][what=kWhatShutdownCompleted][state 10][msg='AMessage(what = 'codc', target = 50) = {
      int32_t what = 1935896429
    }' ]
D/ACodec: ~ACodec
    Now uninitialized
    UninitializedState, mIsAudioBufferLogSwitchOn=0
    UninitializedState, mIsVideoBufferLogSwitchOn=0
I/MediaCodec: [onMessageReceived]line:1646 [][what=kWhatInit][state 0][msg='AMessage(what = 'init', target = 52) = {
      string name = "video/avc"
      int32_t nameIsType = 1
      int32_t encoder = 1
      RefBase *replyID = 0x7f679ed660
    }' ]
D/ACodec: onAllocateComponent
I/OMXClient: Using client-side OMX mux.
D/ACodec: mDeathNotifier is set
    onAllocateComponent mime=video/avc
    onAllocateComponent tmpMime=video/avc
D/ACodec: [SVP] onAllocateComponent, match size=2
    [SVP] msg=AMessage(what = 'allo', target = 51) = {
      string mime = "video/avc"
      int32_t encoder = 1
    }
D/ACodec: [OMX.MTK.VIDEO.ENCODER.AVC] Now Loaded
I/MediaCodec: [onMessageReceived]line:1232 [][what=kWhatComponentAllocated][state 1][msg='AMessage(what = 'codc', target = 52) = {
      int32_t what = 1665231980
      string componentName = "OMX.MTK.VIDEO.ENCODER.AVC"
      int32_t quirks = 40
    }' ]
I/MediaCodec: [release]line:647 [OMX.MTK.VIDEO.ENCODER.AVC]+++
D/Surface: Surface::disconnect(this=0x7f6afb2400,api=1)
I/BufferQueueProducer: [SurfaceTexture-0-4269-3](this:0x7f67b64400,id:3,api:1,p:-1,c:4269) disconnect(P): api 1
I/BufferQueueConsumer: [SurfaceTexture-0-4269-3](this:0x7f67b64400,id:3,api:1,p:-1,c:4269) getReleasedBuffers: returning mask 0xffffffffffffffff
D/GraphicBuffer: unregister, handle(0x7f6adf6c20) (w:720 h:1280 s:720 f:0x2 u:0x000300)
I/[MALI][Gralloc]: [-]r_hnd:0x7f6adf6c20, fd:63, ion_hnd(0x4), req_format(0x2), int_fmt(0x2)  byte_stride(2880), flags(0x4), usage(0x300), size(3686400), alloc_size(3686400) 720(720)X1280(1280) pid(4269)  sec (0)
D/ACodec: Now uninitialized
    UninitializedState, mIsAudioBufferLogSwitchOn=0
    UninitializedState, mIsVideoBufferLogSwitchOn=0
I/MediaCodec: [onMessageReceived]line:1592 [OMX.MTK.VIDEO.ENCODER.AVC][what=kWhatShutdownCompleted][state 10][msg='AMessage(what = 'codc', target = 52) = {
      int32_t what = 1935896429
    }' ]
I/MediaCodec: [~MediaCodec]line:312 [][mState 0]+++
D/Surface: Surface::disconnect(this=0x7f6afb2400,api=1)
I/BufferQueueProducer: [SurfaceTexture-0-4269-3](this:0x7f67b64400,id:3,api:1,p:-1,c:4269) disconnect(P): api 1
D/ACodec: ~ACodec
I/MediaCodec: [release]line:647 [OMX.MTK.VIDEO.DECODER.AVC]+++
D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] Executing::kWhatShutdown keepComponentAllocated 0
D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] Now Executing->Idle
    [OMX.MTK.VIDEO.DECODER.AVC] onInputBufferFilled ID 1 w/ time -1 eos 0 mode 0 err 0
    [OMX.MTK.VIDEO.DECODER.AVC] onInputBufferFilled ID 2 w/ time -1 eos 0 mode 0 err 0
    [OMX.MTK.VIDEO.DECODER.AVC] onInputBufferFilled ID 3 w/ time -1 eos 0 mode 0 err 0
    [OMX.MTK.VIDEO.DECODER.AVC] onInputBufferFilled ID 4 w/ time -1 eos 0 mode 0 err 0
    [OMX.MTK.VIDEO.DECODER.AVC] onInputBufferFilled ID 5 w/ time -1 eos 0 mode 0 err 0
I/ACodec: freeBuffersOnPort portIndex 0
I/ACodec: freeBuffersOnPort portIndex 1
D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] Now Idle->Loaded
    [OMX.MTK.VIDEO.DECODER.AVC] Now Loaded
D/ACodec: Now uninitialized
D/ACodec: UninitializedState, mIsAudioBufferLogSwitchOn=0
    UninitializedState, mIsVideoBufferLogSwitchOn=0
I/MediaCodec: [onMessageReceived]line:1592 [OMX.MTK.VIDEO.DECODER.AVC][what=kWhatShutdownCompleted][state 10][msg='AMessage(what = 'codc', target = 47) = {
      int32_t what = 1935896429
    }' ]
I/MediaCodec: [~MediaCodec]line:312 [][mState 0]+++
D/ACodec: ~ACodec
W/art: Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[26,tid=4484,Native,Thread*=0x7f6af2c000,peer=0x130d40a0,"Thread-265"]
D/libc-netbsd: [getaddrinfo]: hostname=192.168.0.30; servname=8000; netid=0; mark=0
    [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
    [getaddrinfo]: hostname=192.168.0.30; servname=8000; netid=0; mark=0
    [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
W/art: Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[24,tid=4485,Native,Thread*=0x7f7a1b3400,peer=0x1330f0a0,"Thread-263"]
D/AudioManager: setMode: mode = 0
D/AudioManager: setSpeakerphoneOn(false)
D/ActivityThread: ACT-AM_ON_PAUSE_CALLED ActivityRecord{fb6d254 token=android.os.BinderProxy@5e555fd {com.linphone.debug/org.linphone.call.CallActivity}}
D/ActivityThread: ACT-PAUSE_ACTIVITY_FINISHING handled : 0 / android.os.BinderProxy@5e555fd
D/GraphicBuffer: unregister, handle(0x7f6adf6180) (w:720 h:1280 s:720 f:0x2 u:0x000300)
I/[MALI][Gralloc]: [-]r_hnd:0x7f6adf6180, fd:51, ion_hnd(0x3), req_format(0x2), int_fmt(0x2)  byte_stride(2880), flags(0x4), usage(0x300), size(3686400), alloc_size(3686400) 720(720)X1280(1280) pid(4269)  sec (0)
V/ActivityThread: Performing resume of ActivityRecord{cf403e9 token=android.os.BinderProxy@c4cd86e {com.linphone.debug/org.linphone.home.HomeActivity}}
W/GooglePlayServicesUtil: Google Play Store is missing.
D/ActivityThread: ACT-AM_ON_RESUME_CALLED ActivityRecord{cf403e9 token=android.os.BinderProxy@c4cd86e {com.linphone.debug/org.linphone.home.HomeActivity}}
V/ActivityThread: Resume ActivityRecord{cf403e9 token=android.os.BinderProxy@c4cd86e {com.linphone.debug/org.linphone.home.HomeActivity}} started activity: false, hideForNow: false, finished: false
    Resuming ActivityRecord{cf403e9 token=android.os.BinderProxy@c4cd86e {com.linphone.debug/org.linphone.home.HomeActivity}} with isForward=false
V/PhoneWindow: DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{a372f52 com.linphone.debug/org.linphone.home.HomeActivity,ident = 1}, this =com.android.internal.policy.PhoneWindow$DecorView{ae0d1d2 V.E...... R.....ID 0,0-720,1280}
V/ActivityThread: Scheduling idle handler for ActivityRecord{cf403e9 token=android.os.BinderProxy@c4cd86e {com.linphone.debug/org.linphone.home.HomeActivity}}
D/ActivityThread: ACT-RESUME_ACTIVITY handled : 0 / android.os.BinderProxy@c4cd86e
D/Surface: Surface::allocateBuffers(this=0x7f6afad000)
D/OpenGLRenderer: CanvasContext() 0x7f8269f800 initialize window=0x7f6afad010, title=com.linphone.debug/org.linphone.home.HomeActivity
D/Surface: Surface::connect(this=0x7f6afad000,api=1)
W/libEGL: [ANDROID_RECORDABLE] format: 1
D/mali_winsys: new_window_surface returns 0x3000
V/InputMethodManager: onWindowFocus: androidx.drawerlayout.widget.DrawerLayout{61caae7 VFE...... .F....ID 0,73-720,1236 #7f080264 app:id/side_menu} softInputMode=32 first=true flags=#81810100
    START INPUT: androidx.drawerlayout.widget.DrawerLayout{61caae7 VFE...... .F....ID 0,73-720,1236 #7f080264 app:id/side_menu} ic=null tba=android.view.inputmethod.EditorInfo@41dedc4 controlFlags=#105
I/[MALI][Gralloc]: [+]r_hnd:0x7f6adf6180, fd:52, ion_hnd(0x3), req_format(0x1), int_fmt(0x1)  byte_stride(2880), flags(0x4), usage(0xb00), size(3686400), alloc_size(3686400) 720(720)X1280(1280) pid(4269)  sec (0)
D/GraphicBuffer: register, handle(0x7f6adf6180) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
D/Surface: Surface::disconnect(this=0x7f6afafa00,api=1)
D/GraphicBuffer: unregister, handle(0x7f7e7a1cc0) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
I/[MALI][Gralloc]: [-]r_hnd:0x7f7e7a1cc0, fd:80, ion_hnd(0x6), req_format(0x1), int_fmt(0x1)  byte_stride(2880), flags(0x4), usage(0xb00), size(3686400), alloc_size(3686400) 720(720)X1280(1280) pid(4269)  sec (0)
D/GraphicBuffer: unregister, handle(0x7f7e7a2300) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
I/[MALI][Gralloc]: [-]r_hnd:0x7f7e7a2300, fd:79, ion_hnd(0x7), req_format(0x1), int_fmt(0x1)  byte_stride(2880), flags(0x4), usage(0xb00), size(3686400), alloc_size(3686400) 720(720)X1280(1280) pid(4269)  sec (0)
D/GraphicBuffer: unregister, handle(0x7f6adf9a60) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
I/[MALI][Gralloc]: [-]r_hnd:0x7f6adf9a60, fd:49, ion_hnd(0x2), req_format(0x1), int_fmt(0x1)  byte_stride(2880), flags(0x4), usage(0xb00), size(3686400), alloc_size(3686400) 720(720)X1280(1280) pid(4269)  sec (0)
D/Surface: Surface::disconnect(this=0x7f6afafa00,api=1)
I/GLConsumer: [SurfaceTexture-0-4269-3] detachFromContext
I/BufferQueueConsumer: [SurfaceTexture-0-4269-3](this:0x7f67b64400,id:3,api:1,p:-1,c:-1) disconnect(C)
D/GraphicBuffer: unregister, handle(0x7f6adf7940) (w:720 h:1280 s:720 f:0x2 u:0x000300)
I/[MALI][Gralloc]: [-]r_hnd:0x7f6adf7940, fd:73, ion_hnd(0x5), req_format(0x2), int_fmt(0x2)  byte_stride(2880), flags(0x4), usage(0x300), size(3686400), alloc_size(3686400) 720(720)X1280(1280) pid(4269)  sec (0)
D/WindowClient: Remove from mViews: com.android.internal.policy.PhoneWindow$DecorView{8d461bb V.E...... R.....ID 0,0-720,1280}, this = android.view.WindowManagerGlobal@cf3a457
D/ActivityThread: ACT-DESTROY_ACTIVITY handled : 1 / android.os.BinderProxy@5e555fd
D/libc-netbsd: [getaddrinfo]: hostname=192.168.0.30; servname=5060; netid=0; mark=0
    [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=12; ai_family=10
D/libc-netbsd: [getaddrinfo]: hostname=192.168.0.30; servname=5060; netid=0; mark=0
    [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=12; ai_family=2
D/libc-netbsd: [getaddrinfo]: hostname=192.168.0.30; servname=5060; netid=0; mark=0
    [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=12; ai_family=10
    [getaddrinfo]: hostname=192.168.0.30; servname=5060; netid=0; mark=0
    [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=12; ai_family=2
D/libc-netbsd: [getaddrinfo]: hostname=192.168.0.30; servname=5060; netid=0; mark=0
    [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=12; ai_family=10
    [getaddrinfo]: hostname=192.168.0.30; servname=5060; netid=0; mark=0
    [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=12; ai_family=2

This never appen always but there is a way to fix this? 

I have tried the app on a device with play services and on a device with google play service, same result

Thanks in advance

**Comment by Viish** [comment]
Please enable debug logs (settings -> advanced), restart the app, reproduce the issue and attach logs here (either capture them through ADB or use the upload logs button in About fragment)

**Comment by Nicolo-sudo** [comment]
I have fixed it 

After spending hours to figure out what the problem was due , I discovered that the problem was related to my code modification. Now everything is working correctly
