### ISSUE TITLE
audio route icon

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#853]
Steps to reproduce:
1. Connect BT headset, start a call and press the audio route button, it will show:
![image](https://user-images.githubusercontent.com/14617699/69893811-f4cdc600-1327-11ea-8fa4-8cd2b5f29ce8.png)

2. Disconnect BT link (on the phone, or headset, it doesn't matter):
![image](https://user-images.githubusercontent.com/14617699/69893808-e2538c80-1327-11ea-8dfa-ad190bf3dc23.png)

**Comment by Viish** [comment]
Already fixed

**Comment by 532910** [comment]
Not fixed.
Linphone v4.2 (release) from GPlay

**Comment by Viish** [comment]
Indeed.
Fixed in fe2d8b16c2d123c7056825c71a4d4cd08d2593ee

**Comment by 532910** [comment]
Not fixed.
Linphone v4.2.2 (release) from GPlay

**Comment by 532910** [comment]
4.2.3.4230 still not fixed

**Comment by 532910** [comment]
Is any update here? Please reopen.

**Comment by Viish** [comment]
Fixed in feature/kotlin_rework

**Comment by 532910** [comment]
Nice! I have no android build env, but ready to test it when apk will become available.
