### ISSUE TITLE
How to add platform judgment

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#856]
Hi，

Linphone APK will be installed on different platforms. Some platforms use front cameras, while others use rear cameras. How can I achieve compatibility？

I try to add judgment in AndroidvideoAPI9jniwrapper.java, similar to getproperty ("ro. Board. Platform") or getproperty ("ro. Sys. Cputype"), but this one gets null.

thanks.

**Comment by Viish** [comment]
Hi,
You don't need to do that.
Starting SDK 4.3, camera devices are named by the orientation they have.
So if you get the list of video devices, you will have a list like
`BackFacingCamera0, FrontFacingCamera1`
Then you can do whatever logic you want. Note that if only one of the two exists, the SDK will always use the existing one even if configured to use another one.
