### ISSUE TITLE
Is there an API to get the microphone decibels

### ISSUE THREAD

**Issue by Roger1103** [BelledonneCommunications/linphone-android#857]
Is there an API to get the microphone decibels  Linphone-Android4.2

**Comment by Viish** [comment]
What do you mean ? Do you want to know the current volume at at given time to build a vue meter ? Or the current gain setting of the microphone ?

**Comment by Roger1103** [comment]
I want to know the volume of the live microphone input

**Comment by Roger1103** [comment]
> What do you mean ? Do you want to know the current volume at at given time to build a vue meter ? Or the current gain setting of the microphone ?

I want to know the volume of the live microphone input

**Comment by Viish** [comment]
You can use `call.getRecordVolume()`
