### ISSUE TITLE
DTMF selection bad design

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#858]
It should be a drop down list like `Media encryption`, rather than toggles that triggers each other and can't be switched on simultaneously.

![image](https://user-images.githubusercontent.com/14617699/70138791-16b9a680-16a2-11ea-8d43-03b36fa3761b.png)

**Comment by Viish** [comment]
That would indeed probably be better as more comprehensible by user, the current system is just the reflect of the existing APIs methods to control that.

**Comment by Viish** [comment]
Actually both of them can be enabled at the same time in the SDK (in which case each DTMF will be sent twice: one in each format).
If none is selected, RFC2833 is used.
I've made changes in the app to reflect that: e00b5f1369b98c67425f7242d8375abbcf0e9df9

**Comment by 532910** [comment]
Thank you, looks better now!
But I'm still for the down list.
