### ISSUE TITLE
sns crash

### ISSUE THREAD

**Issue by elileo1** [BelledonneCommunications/linphone-android#859]
when i send a msg, it crashes, sdk is 4.3.0
the proxy server log 

freeswitch@DESKTOP-64KOHCD> 2019-12-04 21:32:30.954749 [INFO] mod_sms.c:368 Processing text message 1002->1001 in context public
2019-12-04 21:32:30.954749 [INFO] mod_sms.c:495 CHANNEL_DATA:
Event-Name: [MESSAGE]
Core-UUID: [32514d9e-4bf1-496b-8a53-e8fc81f1a807]
FreeSWITCH-Hostname: [DESKTOP-64KOHCD]
FreeSWITCH-Switchname: [DESKTOP-64KOHCD]
FreeSWITCH-IPv4: [172.16.30.40]
FreeSWITCH-IPv6: [::1]
Event-Date-Local: [2019-12-04 21:32:30]
Event-Date-GMT: [Wed, 04 Dec 2019 13:32:30 GMT]
Event-Date-Timestamp: [1575466350954749]
Event-Calling-File: [sofia_presence.c]
Event-Calling-Function: [sofia_presence_handle_sip_i_message]
Event-Calling-Line-Number: [4882]
Event-Sequence: [815]
login: [sip:mod_sofia@103.84.139.98:5060]
proto: [sip]
to_proto: [sip]
from: [1002@172.16.30.40]
from_user: [1002]
from_host: [172.16.30.40]
to_user: [1001]
to_host: [172.16.30.40]
from_sip_ip: [172.16.211.18]
from_sip_port: [37897]
to: [1001@172.16.30.40]
subject: [SIMPLE MESSAGE]
context: [public]
type: [text/plain]
from_full: [<sip:1002@172.16.30.40>;tag=aMTWTtxUM]
sip_profile: [internal]
dest_proto: [sip]
max_forwards: [70]
DP_MATCH: [1001@172.16.30.40]
Content-Length: 4

1111
2019-12-04 21:32:31.134182 [INFO] mod_sms.c:368 Processing text message 1001->1002 in context public
2019-12-04 21:32:31.134182 [INFO] mod_sms.c:495 CHANNEL_DATA:
Event-Name: [MESSAGE]
Core-UUID: [32514d9e-4bf1-496b-8a53-e8fc81f1a807]
FreeSWITCH-Hostname: [DESKTOP-64KOHCD]
FreeSWITCH-Switchname: [DESKTOP-64KOHCD]
FreeSWITCH-IPv4: [172.16.30.40]
FreeSWITCH-IPv6: [::1]
Event-Date-Local: [2019-12-04 21:32:31]
Event-Date-GMT: [Wed, 04 Dec 2019 13:32:31 GMT]
Event-Date-Timestamp: [1575466351134182]
Event-Calling-File: [sofia_presence.c]
Event-Calling-Function: [sofia_presence_handle_sip_i_message]
Event-Calling-Line-Number: [4882]
Event-Sequence: [816]
login: [sip:mod_sofia@103.84.139.98:5060]
proto: [sip]
to_proto: [sip]
from: [1001@172.16.221.141]
from_user: [1001]
from_host: [172.16.221.141]
to_user: [1002]
to_host: [172.16.30.40]
from_sip_ip: [172.16.221.141]
from_sip_port: [47907]
to: [1002@172.16.30.40]
subject: [SIMPLE MESSAGE]
context: [public]
type: [message/imdn+xml]
from_full: [<sip:1001@172.16.221.141>;tag=SX5bPBQv8]
sip_profile: [internal]
dest_proto: [sip]
max_forwards: [70]
DP_MATCH: [1002@172.16.30.40]
Content-Length: 195

x渦徚?!D卲G`?J践頴o=?挕1齵癜f/{璚/┎荊^?讱
M\ogH緞D棄烵b蟉m@朆8q*?滿9?諌遃2    [4WX!W觕C占+苜尩?E
曶Q?鎉D1蝊Q斓虑?ㄨ椒驈`4l)?5烏謑3~`pISPi)&?q?o氟?こ??H蚪芙

**Comment by Viish** [comment]
Finally the log I was asking for in issue #854 ...
As you can see the issue here is the wrong content of the message.
Won't crash anymore starting SDK 4.3.0-beta-38-g923b67d.

**Comment by elileo1** [comment]
![image](https://user-images.githubusercontent.com/3015588/70147345-f956fd80-16de-11ea-9e77-14414f6482e8.png)
i send text msg

**Comment by elileo1** [comment]
the other device is no problem

2019-12-04 21:43:47.163400 [INFO] mod_sms.c:368 Processing text message 1001->1002 in context public
2019-12-04 21:43:47.163400 [INFO] mod_sms.c:495 CHANNEL_DATA:
Event-Name: [MESSAGE]
Core-UUID: [32514d9e-4bf1-496b-8a53-e8fc81f1a807]
FreeSWITCH-Hostname: [DESKTOP-64KOHCD]
FreeSWITCH-Switchname: [DESKTOP-64KOHCD]
FreeSWITCH-IPv4: [172.16.30.40]
FreeSWITCH-IPv6: [::1]
Event-Date-Local: [2019-12-04 21:43:47]
Event-Date-GMT: [Wed, 04 Dec 2019 13:43:47 GMT]
Event-Date-Timestamp: [1575467027163400]
Event-Calling-File: [sofia_presence.c]
Event-Calling-Function: [sofia_presence_handle_sip_i_message]
Event-Calling-Line-Number: [4882]
Event-Sequence: [961]
login: [sip:mod_sofia@103.84.139.98:5060]
proto: [sip]
to_proto: [sip]
from: [1001@172.16.221.141]
from_user: [1001]
from_host: [172.16.221.141]
to_user: [1002]
to_host: [172.16.30.40]
from_sip_ip: [172.16.221.141]
from_sip_port: [47907]
to: [1002@172.16.30.40]
subject: [SIMPLE MESSAGE]
context: [public]
type: [text/plain]
from_full: [<sip:1001@172.16.221.141>;tag=RIiCAZmft]
sip_profile: [internal]
dest_proto: [sip]
max_forwards: [70]
DP_MATCH: [1002@172.16.30.40]
Content-Length: 1

1

**Comment by Viish** [comment]
Problem isn't the message itself but the IMDN sent to acknowledge the message delivery.

**Comment by elileo1** [comment]
is it the proxy server need to config something to fix it?

**Comment by Viish** [comment]
That depends if the IMDN payload is corrupted by the proxy or if already corrupted when sent by the client.

**Comment by elileo1** [comment]
proxy how to set it and client also set it

**Comment by elileo1** [comment]
hi viish, now the proxy server 
2019-12-05 11:24:00.818883 [INFO] mod_sms.c:368 Processing text message 1001->1002 in context public
2019-12-05 11:24:00.818883 [INFO] mod_sms.c:495 CHANNEL_DATA:
Event-Name: [MESSAGE]
Core-UUID: [2776b54e-0362-45aa-bd05-6ba3751c8734]
FreeSWITCH-Hostname: [DESKTOP-64KOHCD]
FreeSWITCH-Switchname: [DESKTOP-64KOHCD]
FreeSWITCH-IPv4: [172.16.30.40]
FreeSWITCH-IPv6: [::1]
Event-Date-Local: [2019-12-05 11:24:00]
Event-Date-GMT: [Thu, 05 Dec 2019 03:24:00 GMT]
Event-Date-Timestamp: [1575516240818883]
Event-Calling-File: [sofia_presence.c]
Event-Calling-Function: [sofia_presence_handle_sip_i_message]
Event-Calling-Line-Number: [4882]
Event-Sequence: [895]
login: [sip:mod_sofia@103.84.139.98:5060]
proto: [sip]
to_proto: [sip]
from: [1001@172.16.30.40]
from_user: [1001]
from_host: [172.16.30.40]
to_user: [1002]
to_host: [172.16.30.40]
from_sip_ip: [172.16.211.18]
from_sip_port: [48244]
to: [1002@172.16.30.40]
subject: [SIMPLE MESSAGE]
context: [public]
type: [text/plain]
from_full: [<sip:1001@172.16.30.40>;tag=7XHuJ7yEs]
sip_profile: [internal]
dest_proto: [sip]
max_forwards: [70]
DP_MATCH: [1002@172.16.30.40]
Content-Length: 3

123


but i can‘t receiver msg

**Comment by Viish** [comment]
I don't know nothing about Freeswitch configuration, can't help you with that.
