### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by alfirus** [BelledonneCommunications/linphone-android#86]
I would like to rebrand this linphone. Is it possible? I don't know where to ask, so i ask here

**Comment by CrabeMan** [comment]
Hello,
You can find information on the [linphone website](http://linphone.org/)
Check too:
- [Wiki](https://wiki.linphone.org/xwiki/wiki/public/view/Lib/)
- [C Api Doc](http://linphone.org/docs/liblinphone/modules.html)
- [Javadoc](http://linphone.org/docs/liblinphone-javadoc/)
- The [Readme](https://github.com/BelledonneCommunications/linphone-android/blob/master/README.md) on this repo

CrabeMan.

**Comment by alfirus** [comment]
Hi,

can somone help to to setup my cpu environment remotely so i can compile? currently im dead stuck at prepare.py and it said.

"ERROR: The following binaries are missing: ndk-build. Please install them."

i'll pay for it. please contact me via skype "alfirus@gmail.com"

**Comment by CrabeMan** [comment]
Hello,
No need to pay for it. Just look at the Readme.
There is written
```
2.  Download the Android ndk (version r11c or 13b) from google and add it to your path (no symlink !!!) and ANDROID_NDK environment variable.
```

And you can find the Android NDK to [this link](https://developer.android.com/ndk/downloads/older_releases.html)

CrabeMan.
