### ISSUE TITLE
master or release/4.2

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#860]
I'm noticing that release/4.2 has [75 more commits](https://github.com/BelledonneCommunications/linphone-android/compare/master...release/4.2) than master, but the general advise here is to always use master.  Will (and when, if yes) master be caught up to release/4.2 so that the advise to use master can continue to be followed or should I switch to release/4.2 from current master?

**Comment by Viish** [comment]
As you can see master branch is tagged 4.2-alpha and release/4.2 is tagged 4.2-beta.
Release/4.2 branch is a stabilization branch for the next release (4.2). When we will publish the next release, this branch will be tagged 4.2 and merged into master. From there we will create a new release/4.2.x branch for support purposes and master branch will be tagged 4.3-alpha.

**Comment by brianjmurrell** [comment]
Hrm.  In my checkout, the `4.2-alpha` tag seems to be @ ccad7470c which doesn't seem to agree with https://github.com/BelledonneCommunications/linphone-android/commits/4.2.0-alpha.  Did that tag get _moved_ at some point?

But the question remains, what is the recommended branch to use currently?  release/4.2 or master?  is release/4.2 _unstable_?

**Comment by Viish** [comment]
> Did that tag get moved at some point?

Yes that is possible.

> But the question remains, what is the recommended branch to use currently? release/4.2 or master?

You better use release/4.2 as it will be the next release.
When the have finished the new features development on master branch, we branch to the release stabilization branch that only contains fixes. So release/4.2 is a lot more stable than master, but may still contains issues.

**Comment by brianjmurrell** [comment]
Yeah.  Deleting the tag locally and fetching again moved the tag from:

```
* ccad7470c - (tag: 4.2.0-alpha, origin/feature/semver) Updated build.gradle to use new semantic versioning (7 weeks ago) <Sylvain Berfini>
```
to

```
* 9b02b4886 - (tag: 4.2.0-alpha) Updated build.gradle to use new semantic versioning (7 weeks ago) <Sylvain Berfini>
```

I guess downstreams not getting this kind of tag moving activity is why it's generally discouraged to do upstream.

I'll move to release/4.2.
