### ISSUE TITLE
during ring for an incoming call screen is off (phone enters sleep mode)

### ISSUE THREAD

**Issue by wirelessmundi** [BelledonneCommunications/linphone-android#861]
Hi,
while receiving a incoming call and in ringing state the phone enters sleep mode. 
i found this commit:
https://gitlab.linphone.org/BC/public/linphone-android/commit/c122e5d2bc3bc420f877f396089b2583029ccfcd

But the problem is still present.
Using mi 8, android 10,i set sleep time to 15 seconds so i can reproduce the issue easily. 
Let me know if you need logs.

**Comment by Viish** [comment]
Fixed in 5bf110afb9ca54e4f66c952d6e9a38216b4bf29b
