### ISSUE TITLE
Field comment bad design

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#862]
The field prompt (red underlined) is excessive as it fully duplicates the field name.

![image](https://user-images.githubusercontent.com/14617699/70370991-4f45c400-18de-11ea-803f-bab59e20eb2f.png)
![image](https://user-images.githubusercontent.com/14617699/70370994-52d94b00-18de-11ea-8224-618bbc1ec77b.png)

**Comment by Viish** [comment]
Actually it's to help user understand where is the text field but I agree it could be better than just the title duplicate

**Comment by 532910** [comment]
It should look just like an empty input field.

**Comment by DroidPulkit** [comment]
Also, textinputlayout hint will help in this case. Which is something like this in the picture https://stackoverflow.com/questions/45453570/android-textinputlayout-hint-overlaps-edittext-hint

**Comment by Viish** [comment]
Fixed in feature/kotlin_rewrite branch

**Comment by DroidPulkit** [comment]
Hi, question about feature/kotlin_rewrite branch 
What SDK version are you using, it shows 
url file(LinphoneSdkBuildDir + '/maven_repository/')

And if I use the 4.3.0-beta SDK it doesn't work at all. Any idea, when the new SDK supporting this will be released

**Comment by Viish** [comment]
Currently it can only work with locally built SDK on branch feature/sdk_android_audio_focus.
