### ISSUE TITLE
Unable to join Linphone beta test

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#863]
Just reinstalled the app (to check the #833) and now it's not a beta version more.

Not sure if this a Linphone, AuroraStore or google bug.
https://gitlab.com/AuroraOSS/AuroraStore/issues/246

**Comment by 532910** [comment]
If it matters my google account e-mail is different and not the same as my primary e-mail.

**Comment by Viish** [comment]
Yes your Google email matters for beta inscriptions.
But even if you changed you should be able to subscribe to the beta with your other account as well

**Comment by 532910** [comment]
I've not changed my Google email, just reinstalled the app.
