### ISSUE TITLE
better F-Droid support

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#864]
I'd prefer to get betas from F-Droid. It should work automatically, but you need to release them as github tags.

**Comment by Viish** [comment]
Github.com is only a backup so we won't do that.

**Comment by 532910** [comment]
OK, my fault, not github, gitlab.linphone.org.
As I see F-Droid https://f-droid.org/packages/org.linphone/ uses it: https://gitlab.linphone.org/BC/public/linphone-android/tags

But gitlab.linphone.org is still outdated.

**Comment by Viish** [comment]
It's not outdated.
We tagged the release branch and the next tag will happen when we publish the release.

**Comment by Viish** [comment]
4.2 released has been published and tagged, it should be available on F-Droid later I guess.
