### ISSUE TITLE
Recording files not created using latest beta

### ISSUE THREAD

**Issue by jamorris** [BelledonneCommunications/linphone-android#865]
I'm able to initiate a call recording and it looks like the call is being recorded but no new recordings appear. I tested this on iOS and it works, so I believe I'm preforming the steps correctly. The file storage permission has been granted and I'm running Android 10. I've tried uninstalling and reinstalling along with clearing the cache and storage.

**Comment by Viish** [comment]
Thanks for the report.
Fixed in bb89582033240d290a56192ce2cbe044c843a4a7
