### ISSUE TITLE
How to integrate g729 in new build of linphone

### ISSUE THREAD

**Issue by chuckwhisler** [BelledonneCommunications/linphone-android#866]
Hey ! I am using android studio and gradle for the development of linphone . If anyone can tell how can i integrate bcg729 with it. As all the g729 problems are solved by old files like prepare.py ,make build-g729=1.kindly guide me through this ...

**Comment by KyronNextLevel** [comment]
Hi, you need to build the linphone-sdk with the following options
-DLINPHONESDK_PLATFORM=Android -DLINPHONESDK_ANDROID_ARCHS="[your needed archs, separeted by commas]" --DENABLE_G729=YES

and eventually -DENABLE_G729B_CNG=YES

You will then need to symlink the generated sdk aar, as described in the Readme
