### ISSUE TITLE
keypad sounds

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#867]
Pressing the keypad produces a tone, but from earpiece speaker rather than from loudspeaker.
![image](https://user-images.githubusercontent.com/14617699/70459844-16684380-1ac6-11ea-8bbe-19c69d9cafc4.png)

**Comment by Viish** [comment]
Yes, as does the native dialer.

**Comment by 532910** [comment]
No, native dialer produces a tone from loudspeaker!

**Comment by Viish** [comment]
Maybe yours then but not mine.
Anyway I don't think it's a good idea to use the speaker for tones.

**Comment by 532910** [comment]
you should use `STREAM_DTMF`
https://developer.android.com/reference/android/media/AudioManager#STREAM_DTMF
same as AOSP dialer does:
https://android.googlesource.com/platform/packages/apps/Dialer/+/refs/heads/master/java/com/android/dialer/dialpadview/DialpadFragment.java#131

**Comment by 532910** [comment]
Sylvain, you don't agree?

**Comment by Viish** [comment]
No I don't disagree.
Problem is DTMFs are generated and played by our SDK, and that neither openSLES or AAudio frameworks have this stream. And even if they did it would require us to have a dedicated sound card for DTMFs only.
So far I haven't found a nice solution at this issue.

**Comment by 532910** [comment]
Thank you for explanation!
