### ISSUE TITLE
proximity sensor should not turn off the screen for loudspeaker and bluetooth output

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#868]
The screen should not be dimmed by proximity sensor when audio route is loudspeaker or bluetooth. Only for earpiece speaker.

**Comment by sushilsolanki8875** [comment]
Any update on this?

**Comment by Viish** [comment]
Fixed in feature/kotlin_rewrite branch for 5.0 release.

**Comment by 532910** [comment]
I confirm this is fixed.
