### ISSUE TITLE
switch to bluetooth automatically

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#869]
Please add support to switch audio route to bluetooth on bluetooth headset connection.

**Comment by Viish** [comment]
The bluetooth route is already used when a call starts if the headset is connected at this time.
However it seems risky to automatically switch to a newly connected bluetooth device during a call, so I won't do that.

**Comment by 532910** [comment]
Why do you think this is risky?

**Comment by Viish** [comment]
Once a call has started I don't want the audio stream of my call to suddenly go loud let's say in my home because I entered  the room and my phone connected automatically to my Echo.

**Comment by 532910** [comment]
Hm, ok, I'm agree (:
