### ISSUE TITLE
 Is it possible to change the code to support android 2.3 version ?

### ISSUE THREAD

**Issue by zhuanghongji** [BelledonneCommunications/linphone-android#87]
I had tried to change the minSdkVersion to 10 , but when i install the apk on Android 2.3.7, the app is crash

**Comment by CrabeMan** [comment]
Hello,
I have no idea about why it doesn't work but you can find some information to this [link](https://stackoverflow.com/a/41079462)

CrabeMan.

**Comment by DatBewar** [comment]
Hello, we are supporting Android 4.1 to 7+, so we don't check anymore on Android < 4.1
