### ISSUE TITLE
Linphone not able to quit itself

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-android#871]
So I've pulled the latest commits (great work btw!) and I've noticed that the Quit button doesn't work as expected anymore. After hitting quit, I can see that Linphone only unregisters itself?

Linphone: Changing [client] [REGISTER] transaction [0x794aa19140], from state [COMPLETED] to [TERMINATED]

In background mode, the icon also remains in the notificationsbar. This also makes it impossible to swap between push <> background mode since a restart is then needed. Maybe it is an idea to restart the service after turning on push?

The only workaround looks like a force stop to allow linphone to restart completely?

**Comment by Viish** [comment]
Hi,
You can still stop the service by swapping the activity away in the task manager.
