### ISSUE TITLE
Can I call multiple accounts at the same time？

### ISSUE THREAD

**Issue by fanfan1009** [BelledonneCommunications/linphone-android#872]
That is, one account calls multiple accounts at the same time. When one account answers, other calls automatically hang up.

**Comment by Viish** [comment]
This is what is done if all the accounts you call have the same SIP account (username/domain)
If you want to call different SIP addresses you have to do the logic manually.

**Comment by fanfan1009** [comment]
Thanks for your reply,
Usually only one account is called like this:
LinphoneManager.getCallManager().newOutgoingCall("sip:12121@192.168.1.126:5060", "");
But I want to call multiple accounts at the same time. What should I do?

**Comment by Viish** [comment]
You can call newOutgoingCall multiple times

**Comment by fanfan1009** [comment]
But I only call the first one.
LinphoneManager.getCallManager().newOutgoingCall("sip:67063145524414@sipproxy.ucpaas.com:25060", "");
LinphoneManager.getCallManager().newOutgoingCall("sip:12121@192.168.1.126:5060", "");
