### ISSUE TITLE
G729A & G729AB Support in Linphone.

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#874]
Hello @Viish ,

Need one information, Does linphone support  G72 , G729A & G729AB. If it supports that how to add these codec in codec selection list.

Thanks,
Amit Sharma

**Comment by Viish** [comment]
Hi,
Yes our SDK does support G729, you simply have to build it using -DENABLE_G729=ON and eventually -DENABLE_G729_CNG=ON
Cheers,

**Comment by amit1576** [comment]
Hi,

**Means if i enable G729 then eventually it will support all three codec i.e G729A, G729B & G729AB.**

**Comment by Viish** [comment]
Yes: https://linphone.org/technical-corner/bcg729
