### ISSUE TITLE
Can we tweak hardware/software decoding Mediacodec While Streaming Linphone Call

### ISSUE THREAD

**Issue by mehulp89** [BelledonneCommunications/linphone-android#875]
I have searched a lot on hardware acceleration of video decoding but I couldn't find any information. I have looked at Mediacodec folder code to tweak but couldn't get success. Is there anything linphone SDK using hardware decoders? If so, how can I tweak?

**Comment by Viish** [comment]
Yes linphone SDK uses Mediacodec for hardware encoding/decoding for H264 and H265 codecs. VP8 is still software.
Code is in https://github.com/BelledonneCommunications/mediastreamer2 project, in src/voip/h26x/media-codec-* files

**Comment by mehulp89** [comment]
I want to force Mediacodec to use a software decoder for the H264 RTP stream. I am trying to use an H264 that works fine if software codecs are used verified it using the FFmpeg library. Using a hardware decoder is giving different results(errors in decoding) on different smartphones.

**Comment by Viish** [comment]
Indeed the media codec implementation on some devices is a bit broken depending on the remote side encoder...
You can use OpenH264 software decoder provided by Cisco.

**Comment by mehulp89** [comment]
Is there any referenced document that we can follow for integrating this decoder on both Android and iOS with lib-linphone. We are planning to use the library in our applications.

**Comment by Viish** [comment]
Simply build the SDK with -DENABLE_OPENH264=ON option.
