### ISSUE TITLE
transferee hears tones during transfer process

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#879]
If I am on a call on a linphone handset and want to transfer that call to another endpoint, I press the transfer button and then have to choose a party to transfer to.  I can enter digits using the dialpad and then press the transfer button at the bottom of the dialpad.

This has two problems.  It's annoying for a human at the other end to have to listen to and can mess up IVRs if transferring while on an IVR as it hears the tones and may act on any that are valid for the input it's waiting for.

Can the transferee be put on hold during the transfer process so that they do not hear the tones of the process?

**Comment by Viish** [comment]
Until I fix this you can use the edit text field on top of the numpad, it won't trigger any DTMF.

**Comment by Viish** [comment]
Fixed in feature/kotlin_rewrite branch
