### ISSUE TITLE
An error occurred while connecting to camera 1: Service not available

### ISSUE THREAD

**Issue by Rohnit** [BelledonneCommunications/linphone-android#88]
Hi, 

I am using Moto G5 device. I am facing this error on start video call. This is the error.

07-20 16:14:39.033 10642-10642/org.linphone W/CameraBase: An error occurred while connecting to camera 1: Service not available
07-20 16:14:39.033 10642-10642/org.linphone W/System.err: java.lang.RuntimeException: Fail to connect to camera service
07-20 16:14:39.034 10642-10642/org.linphone W/System.err:     at android.hardware.Camera.<init>(Camera.java:512)
07-20 16:14:39.034 10642-10642/org.linphone W/System.err:     at android.hardware.Camera.open(Camera.java:357)
07-20 16:14:39.034 10642-10642/org.linphone W/System.err:     at org.linphone.mediastream.video.capture.AndroidVideoApi9JniWrapper.startRecording(AndroidVideoApi9JniWrapper.java:58)
07-20 16:14:39.034 10642-10642/org.linphone W/System.err:     at org.linphone.core.LinphoneCoreImpl.iterate(Native Method)
07-20 16:14:39.034 10642-10642/org.linphone W/System.err:     at org.linphone.core.LinphoneCoreImpl.iterate(LinphoneCoreImpl.java:267)
07-20 16:14:39.034 10642-10642/org.linphone W/System.err:     at org.linphone.LinphoneManager$2$1.run(LinphoneManager.java:743)
07-20 16:14:39.034 10642-10642/org.linphone W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
07-20 16:14:39.034 10642-10642/org.linphone W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
07-20 16:14:39.034 10642-10642/org.linphone W/System.err:     at android.os.Looper.loop(Looper.java:154)
07-20 16:14:39.034 10642-10642/org.linphone W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6123)
07-20 16:14:39.034 10642-10642/org.linphone W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-20 16:14:39.034 10642-10642/org.linphone W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
07-20 16:14:39.034 10642-10642/org.linphone W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by pratimagauns** [comment]
Please can you pit down the reason why this issue was occurring?
