### ISSUE TITLE
Will the video conference be updated in the near future？

### ISSUE THREAD

**Issue by fanfan1009** [BelledonneCommunications/linphone-android#881]
Hi,Just want to ask, will the video conference be updated in the near future.

**Comment by Viish** [comment]
Some day we will have video conferencing, but I don't know if it will be in the "near future".
We are a company and we work first on developments funded by our customers, and so far none of them bought us the video conferencing.

**Comment by fanfan1009** [comment]
Thanks for your reply,Then I would like to ask, in addition to the meeting, can I call multiple accounts at the same time? If so, how do I implement it?

**Comment by Viish** [comment]
Here's a sample of code extracted from simple_conference_from_scratch test in linphone call_multi test suite:
```
conf_params = linphone_core_create_conference_params(marie->lc);
	linphone_conference_params_enable_video(conf_params, FALSE);
	conf = linphone_core_create_conference_with_params(marie->lc, conf_params);
	linphone_conference_params_unref(conf_params);

	participants = bctbx_list_append(participants, pauline->identity);
	participants = bctbx_list_append(participants, laure->identity);

	linphone_conference_invite_participants(conf, participants, NULL);
```
