### ISSUE TITLE
Call transfer method deprecated

### ISSUE THREAD

**Issue by Amrutha164** [BelledonneCommunications/linphone-android#889]
Hi Team,

I am facing an issue with linphone call transfer in attended call transfer functionality.
The actual method in the linphone manager is deprecated. I am unable to come out from the CallActivity when done with call transfer.
 i.e.,  LinphoneManager.getLc().transferCallToAnother(call1, call2);

Can you please help me out of this problem.
Thank you.

**Comment by Viish** [comment]
Use call1.transfer(call2)

**Comment by Tom3412** [comment]
This is my use case ..

- To use attended transfer, tap first on the Home button during the call. Then, by either dialing the number from the keypad or using History, Quickdial or your Contacts, call the person you want to transfer the call to (this will automatically put the first call on hold). Once you confirm they are ready for the transfer, select the first call from the list of calls. Take it off hold, tap on attended transfer, then select the second call and the transfer will be completed.
