### ISSUE TITLE
Chat message is blank 

### ISSUE THREAD

**Issue by gautamDev36** [BelledonneCommunications/linphone-android#89]
Hi
chat message is blank when  receive chat message.issue available in live play store application.
Please tell the solution for this.

**Comment by DatBewar** [comment]
Hello, how did you send message?

**Comment by gautamDev36** [comment]
I have two device on both audio call and video call is working fine . But in Chat when i send chat Message From Device A to Device B , B get blank message or vice versa.Tested on cross platform Also from Android it has issue in receiving and sending.
Play store version also have same issue.

**Comment by DatBewar** [comment]
I had check and i can't reproduce this issue
