### ISSUE TITLE
Exception during fetching contacts on first start

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-android#891]
There appears to be a problem in fetching the Android contacts during the first launch. 
**AndroidRuntime: java.lang.RuntimeException: Unable to pause activity {be.uzgent.uzlinphone/org.linphone.contacts.ContactsActivity}**

I know the log is a bit obfuscated, but I've been digging a little deeper and the problem seems to be in the onPause of ContactsFragment.

Besides the error, a restart of Linphone results in a loading icon of the contactlist until it is restarted a few times.

For now, I have this workaround in ContactsFragment.java

>    
    public void onPause() {
        try {
                if(ContactsManager.getInstance() != null){
                        ContactsManager.getInstance().removeContactsListener(this);
                }
        } catch (Exception e) {
                Log.e("[Contacts] onPause ContactsFragment exception: ", e);
        }
        super.onPause();
    }

> --------- beginning of crash
01-08 09:41:40.462 12743 12743 E AndroidRuntime: FATAL EXCEPTION: main
01-08 09:41:40.462 12743 12743 E AndroidRuntime: Process: be.uzgent.uzlinphone, PID: 12743
01-08 09:41:40.462 12743 12743 E AndroidRuntime: java.lang.RuntimeException: Unable to pause activity {be.uzgent.uzlinphone/org.linphone.contacts.ContactsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'org.linphone.contacts.j d.a.a.c()' on a null object reference
01-08 09:41:40.462 12743 12743 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4043)
01-08 09:41:40.462 12743 12743 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3998)
01-08 09:41:40.462 12743 12743 E AndroidRuntime: 	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3950)
01-08 09:41:40.462 12743 12743 E AndroidRuntime: 	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45)
01-08 09:41:40.462 12743 12743 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
01-08 09:41:40.462 12743 12743 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
01-08 09:41:40.462 12743 12743 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)
01-08 09:41:40.462 12743 12743 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-08 09:41:40.462 12743 12743 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
01-08 09:41:40.462 12743 12743 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6762)
01-08 09:41:40.462 12743 12743 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-08 09:41:40.462 12743 12743 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-08 09:41:40.462 12743 12743 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
01-08 09:41:40.462 12743 12743 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.linphone.contacts.j d.a.a.c()' on a null object reference
01-08 09:41:40.462 12743 12743 E AndroidRuntime: 	at org.linphone.contacts.j.m(ContactsManager.java:1)
01-08 09:41:40.462 12743 12743 E AndroidRuntime: 	at org.linphone.contacts.i.onPause(ContactsFragment.java:1)
01-08 09:41:40.462 12743 12743 E AndroidRuntime: 	at android.app.Fragment.performPause(Fragment.java:2723)
01-08 09:41:40.462 12743 12743 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1353)
01-08 09:41:40.462 12743 12743 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1576)
01-08 09:41:40.462 12743 12743 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1637)
01-08 09:41:40.462 12743 12743 E AndroidRuntime: 	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3046)
01-08 09:41:40.462 12743 12743 E AndroidRuntime: 	at android.app.FragmentManagerImpl.dispatchPause(FragmentManager.java:3012)
01-08 09:41:40.462 12743 12743 E AndroidRuntime: 	at android.app.FragmentController.dispatchPause(FragmentController.java:215)
01-08 09:41:40.462 12743 12743 E AndroidRuntime: 	at android.app.Activity.performPause(Activity.java:7327)
01-08 09:41:40.462 12743 12743 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1466)
01-08 09:41:40.462 12743 12743 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4033)
01-08 09:41:40.462 12743 12743 E AndroidRuntime: 	... 12 more

**Comment by Viish** [comment]
Hi,
Thanks for the report.
Fixed in 95849162dea3b20ab6954a32761daf3d4726a36e.
Cheers,
