### ISSUE TITLE
flexisip Push notification not received on some devices 

### ISSUE THREAD

**Issue by dipenpatel235** [BelledonneCommunications/linphone-android#892]
hello i have vivo V9 device and checked with many other device.
so some of device not received push notification due to some how background services was stoped or something else.
from flexisip push server to send successfully but not wakeup application.
Thanks

**Comment by Viish** [comment]
Have you checked battery optimizations ?
https://stackoverflow.com/questions/39256501/check-if-battery-optimization-is-enabled-or-not-for-an-app

**Comment by dipenpatel235** [comment]
batter is In "Normal Mode" not in power saving/optimization mode.

**Comment by Viish** [comment]
Can you add logs from the app please ?

**Comment by dipenpatel235** [comment]
in app not received push notification.
so we not get any log related push

**Comment by dipenpatel235** [comment]
but yes push server side getting error log. that i have posted on flexisip also.

https://github.com/BelledonneCommunications/flexisip/issues/83

**Comment by Viish** [comment]
> in app not received push notification.
so we not get any log related push

I don't care please attach logs from the app start

**Comment by dipenpatel235** [comment]
here attached app start log.
please look it and let me know if any more info u want.

https://pastebin.com/raw/i6di0NMH

Thanks
Dipen

**Comment by Viish** [comment]
Please enable debug logs from settings -> advanced

**Comment by dipenpatel235** [comment]
enabled debug log as per given steps and then i have pasted that log in below file.

https://pastebin.com/raw/rBeUB2AY

Thanks

**Comment by Viish** [comment]
From the logs everything looks fine.
Check your adb logcat output for any firebase log, that might help understand what is wrong.

**Comment by dipenpatel235** [comment]
Ok thanks
Let me try if I can figure it out or not.

**Comment by Viish** [comment]
Any update?

**Comment by dipenpatel235** [comment]
No. Not working on some devices like vivo,oooo,mi

**Comment by Viish** [comment]
Do you reproduce if you use an account from our service sip.linphone.org ?

**Comment by basncy** [comment]
Tips: Google services might not stable on chinese brand product by default for know issue.
Please ensure FCM service works well in your case, or keep linphone in backgroud.

**Comment by dipenpatel235** [comment]
Yes I am trying to keep linphone on background but some devices made by
china like opoo , vivo ,mi on background service is killed.

That's why it is not working push

**Comment by basncy** [comment]
Tips2: Some background apps might be killed to prevent the continues of connecting to google service which eats battery, this happens on some devices sold on china mainland, you can do some "hack" around.

**Comment by Viish** [comment]
I'm closing as we don't reproduce the issue.
