### ISSUE TITLE
Error to build when using own AAR

### ISSUE THREAD

**Issue by SJTU-Ysw** [BelledonneCommunications/linphone-android#893]
Hi~
I'm trying to build linphone-android using AAR generated by myself.
It seems that linphone-sdk build successfully, and aar for both release and debug are generated. But after linking them to linphone-android, there are errors when I try to build the project:

Executing tasks: [:app:assembleDebug] in project /home/yusw/Desktop/RTC/4.2/linphone-android
> Configure project :app
Git version: 4.2.6+1bacaf8

> Task :app:generateContactsXml UP-TO-DATE
> Task :app:getGitVersion UP-TO-DATE
> Task :app:spotlessJava UP-TO-DATE
> Task :app:spotlessJavaApply UP-TO-DATE
> Task :app:spotlessApply UP-TO-DATE
> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:checkDebugManifest UP-TO-DATE
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :app:mainApkListPersistenceDebug UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:processDebugGoogleServices UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugResources UP-TO-DATE

> Task :app:compileDebugJavaWithJavac
/home/yusw/Desktop/RTC/4.2/linphone-android/app/src/main/java/org/linphone/activities/MainActivity.java:203: error: method does not override or implement a method from a supertype
                    @Override
                    ^
/home/yusw/Desktop/RTC/4.2/linphone-android/app/src/main/java/org/linphone/contacts/LinphoneContact.java:408: error: cannot find symbol
        mFriend.remove();
               ^
  symbol:   method remove()
  location: variable mFriend of type Friend
/home/yusw/Desktop/RTC/4.2/linphone-android/app/src/main/java/org/linphone/firebase/FirebaseMessaging.java:46: error: cannot find symbol
                                core.ensureRegistered();
                                    ^
  symbol:   method ensureRegistered()
  location: variable core of type Core

......

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
23 errors

> Task :app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
13 actionable tasks: 1 executed, 12 up-to-date

 I tried in both V4.2 (for sdk and android) and master-branch. I am stuck in the same place. Is there something wrong in my AAR or somewhere else? Thanks a lot.

**Comment by SJTU-Ysw** [comment]
The last part of the sdk compilation log is as follows
----------------------------------------------------------------------
> Configure project :
AAR artefact group id will be: org.linphone

> Task :copyAssets
Syncing sdk assets into root dir /home/yusw/Desktop/RTC/4.2/linphone-sdk/build/linphone-sdk/bin/sdk-assets/assets/org.linphone.core
Syncing sdk asset share/linphone/rootca.pem to share/linphone/rootca.pem
Syncing sdk asset share/belr/grammars/cpim_grammar to share/belr/grammars/cpim_grammar
Syncing sdk asset share/belr/grammars/vcard_grammar to share/belr/grammars/vcard_grammar
Syncing sdk asset share/sounds/linphone/ringback.wav to share/sounds/linphone/ringback.wav
Syncing sdk asset share/sounds/linphone/hello16000.wav to share/sounds/linphone/hello16000.wav
Syncing sdk asset share/sounds/linphone/rings/house_keeping.mkv to share/sounds/linphone/rings/house_keeping.mkv
Syncing sdk asset share/sounds/linphone/rings/soft_as_snow.mkv to share/sounds/linphone/rings/soft_as_snow.mkv
Syncing sdk asset share/sounds/linphone/rings/its_a_game.mkv to share/sounds/linphone/rings/its_a_game.mkv
Syncing sdk asset share/sounds/linphone/rings/notes_of_the_optimistic.mkv to share/sounds/linphone/rings/notes_of_the_optimistic.mkv
Syncing sdk asset share/sounds/linphone/rings/oldphone-mono.wav to share/sounds/linphone/rings/oldphone-mono.wav
Syncing sdk asset share/sounds/linphone/rings/four_hands_together.mkv to share/sounds/linphone/rings/four_hands_together.mkv
Syncing sdk asset share/sounds/linphone/rings/leaving_dreams.mkv to share/sounds/linphone/rings/leaving_dreams.mkv
Syncing sdk asset share/sounds/linphone/toy-mono.wav to share/sounds/linphone/toy-mono.wav
Syncing sdk asset share/sounds/linphone/incoming_chat.wav to share/sounds/linphone/incoming_chat.wav
Syncing sdk asset share/sounds/linphone/dont_wait_too_long.mkv to share/sounds/linphone/dont_wait_too_long.mkv
Syncing sdk asset share/sounds/linphone/hello8000.wav to share/sounds/linphone/hello8000.wav

> Task :copyProguard

> Task :getGitVersion
Git branch: release/4.2

> Task :preBuild
> Task :preDebugBuild
> Task :compileDebugAidl NO-SOURCE
> Task :compileDebugRenderscript
> Task :checkDebugManifest
> Task :generateDebugBuildConfig
> Task :generateDebugResValues
> Task :generateDebugResources
> Task :packageDebugResources
> Task :processDebugManifest
> Task :generateDebugRFile
> Task :prepareLintJar UP-TO-DATE
> Task :generateDebugSources
> Task :javaPreCompileDebug

> Task :compileDebugJavaWithJavac

> Task :extractDebugAnnotations
> Task :mergeDebugConsumerProguardFiles
> Task :mergeDebugShaders
> Task :compileDebugShaders
> Task :generateDebugAssets
> Task :packageDebugAssets
> Task :packageDebugRenderscript NO-SOURCE
> Task :processDebugJavaRes NO-SOURCE
> Task :transformResourcesWithMergeJavaResForDebug
> Task :transformClassesAndResourcesWithSyncLibJarsForDebug
> Task :compileDebugNdk NO-SOURCE
> Task :mergeDebugJniLibFolders
> Task :transformNativeLibsWithMergeJniLibsForDebug
> Task :transformNativeLibsWithStripDebugSymbolForDebug
> Task :transformNativeLibsWithSyncJniLibsForDebug
> Task :bundleDebugAar
> Task :compileDebugSources
> Task :assembleDebug
> Task :preReleaseBuild
> Task :compileReleaseAidl NO-SOURCE
> Task :compileReleaseRenderscript
> Task :checkReleaseManifest
> Task :generateReleaseBuildConfig
> Task :generateReleaseResValues
> Task :generateReleaseResources
> Task :packageReleaseResources
> Task :processReleaseManifest
> Task :generateReleaseRFile
> Task :generateReleaseSources
> Task :javaPreCompileRelease

> Task :compileReleaseJavaWithJavac

> Task :extractReleaseAnnotations
> Task :mergeReleaseConsumerProguardFiles
> Task :mergeReleaseShaders
> Task :compileReleaseShaders
> Task :generateReleaseAssets
> Task :packageReleaseAssets
> Task :packageReleaseRenderscript NO-SOURCE
> Task :processReleaseJavaRes NO-SOURCE
> Task :transformResourcesWithMergeJavaResForRelease
> Task :transformClassesAndResourcesWithSyncLibJarsForRelease
> Task :compileReleaseNdk NO-SOURCE
> Task :mergeReleaseJniLibFolders
> Task :transformNativeLibsWithMergeJniLibsForRelease
> Task :transformNativeLibsWithStripDebugSymbolForRelease
> Task :transformNativeLibsWithSyncJniLibsForRelease
> Task :bundleReleaseAar
> Task :compileReleaseSources
> Task :mergeReleaseResources
> Task :verifyReleaseResources
> Task :assembleRelease
> Task :assemble

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 22s
48 actionable tasks: 47 executed, 1 up-to-date
AAR artefact group id will be: org.linphone
[100%] Built target sdk
--------------------------------------------------------------------------------------
linphone-sdk-android-debug.aar  95M
linphone-sdk-android-release.aar  22M
That's for release/4.2. But for the latest, they are only 1.4M and 453K in size. That's strange.

**Comment by Viish** [comment]
Hi,
First of all, if you are using linphone-android 4.2 version you must use SDK release/4.3 or master branch.
It will fix most of your issues.
Cheers,

**Comment by SJTU-Ysw** [comment]
Thanks for Viish's reply!

Error fixed when I choose master branch of SDK and build using 
`cmake -DLINPHONESDK_PLATFORM=Android -DLINPHONESDK_ANDROID_ARCHS=arm64 -DENABLE_VIDEO=ON -DENABLE_WEBRTC_AECM=NO -DENABLE_WEBRTC_AEC=NO -DENABLE_NON_FREE_CODECS=ON ..`
Previously I used cmake-gui and LINPHONESDK_ANDROID_ARCHS=armv7
