### ISSUE TITLE
The numpad does not appear during early media

### ISSUE THREAD

**Issue by luiz-telles** [BelledonneCommunications/linphone-android#894]
During the phase of early media (pre-answer) the numpad does not appear.

**Comment by Viish** [comment]
Indeed, as we use the incoming call screen to display early media.

**Comment by luiz-telles** [comment]
Viish,
We have simple IVR application in our PBX that the user must to interact during the early media.
Is it possible make this available in Linphone?

**Comment by Viish** [comment]
Sorry but not at the time, no. If you really need it, please contact our sales department for a quote: sales@belledonne-communications.com

With new Android requirements for notifications & incoming call screens we can't even know for sure there will be a visible UI when an incoming call is received (just a notification).
So I recommend you not to rely on user interaction during early media.
