### ISSUE TITLE
Enable debug mode in Liblinphone Android App

### ISSUE THREAD

**Issue by mehulp89** [BelledonneCommunications/linphone-android#895]
When I  can enable the option 'Debug', where are the log files typically stored?

Or are they only viewable with logcat?

**I'm mostly preferring to see that logs in Logcat in Android Studio.**

In iOS, we achieved by the below method in core.h class. 

>     linphone_core_set_log_level(BCTBX_LOG_DEBUG);

For reference I'm adding below code but unable to find to make it enable.

    

> Factory.instance().setDebugMode(isDebugEnabled, appName);
>     			Factory.instance().enableLogCollection(LogCollectionState.EnabledWithoutPreviousLogHandler);
>     			Factory.instance().getLoggingService().setListener(new LoggingServiceListener() {
>     				@Override
>     				public void onLogMessageWritten(LoggingService logService, String domain, LogLevel lev, String message) {
>     					switch (lev) {
>     						case Debug:
>     							android.util.Log.d(domain, message);
>     							break;
>     						case Message:
>     							android.util.Log.i(domain, message);
>     							break;
>     						case Warning:
>     							android.util.Log.w(domain, message);
>     							break;
>     						case Error:
>     							android.util.Log.e(domain, message);
>     							break;
>     						case Fatal:
>     						default:
>     							android.util.Log.wtf(domain, message);
>     							break;
>     					}
>     				}
>     			});
> 

Do let me know if you have any queries.

Kind Regards,

**Comment by Viish** [comment]
For Android, to enable debug logs from the lib (they will be visible in adb logcat):
`Factory.instance().setDebugMode(true, "Linphone or any other tag");`

**Comment by mehulp89** [comment]
Thank you. 

Cheers.
