### ISSUE TITLE
The call is audio, not video

### ISSUE THREAD

**Issue by fanfan1009** [BelledonneCommunications/linphone-android#896]
Call under LAN only audio no video
SDK:4.2
This is a log for audio and video calls：
SIP/2.0 200 Ok
Via: SIP/2.0/TCP 192.168.1.67:50826;branch=z9hG4bKPjb2122fa31c274cd58ac1d2de3bbaba71;alias;rport=50827
From: <sip:192.168.1.67>;tag=11150ee09c054c39bc3b485ae9b1e081
To: <sip:outdoor@192.168.1.161>;tag=6bFSUnB
Call-ID: 4e40f73b4faa4f79999830672027509c
CSeq: 27992 INVITE
User-Agent: LinphoneAndroid/4.1 (rk3288) LinphoneSDK/4.2-125-g46ea9b5 (master)
Supported: replaces, outbound, gruu
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO, UPDATE
Contact: "Outdoor" <sip:outdoor@192.168.1.161;transport=tcp>;+sip.instance="<urn:uuid:8bff4c98-27d6-00b5-9100-1d7297cd88e2>"
Content-Type: application/sdp
Content-Length: 274

v=0
o=outdoor 3410 3982 IN IP4 192.168.1.161
s=Talk
c=IN IP4 192.168.1.161
t=0 0
m=audio 7078 RTP/AVP 97 96
a=rtpmap:97 speex/8000
a=fmtp:97 vbr=on
a=rtpmap:96 telephone-event/8000
m=video 9078 RTP/AVP 97
a=rtpmap:97 H264/90000
a=fmtp:97 profile-level-id=42801F

This is an audio only log：
SIP/2.0 200 Ok
Via: SIP/2.0/TCP 192.168.1.67:50866;branch=z9hG4bKPjc384c4496c604e72b4e98946e28aeea9;alias;rport=50867
From: <sip:192.168.1.67>;tag=9059ec3b282841f796d85eedb0c6b628
To: <sip:outdoor@192.168.1.186>;tag=N~jR8Pk
Call-ID: edde1c0bd6314563b3857083342fdb30
CSeq: 15426 INVITE
User-Agent: LinphoneAndroid/4.1 (rk3288) LinphoneSDK/4.2-125-g46ea9b5 (master)
Supported: replaces, outbound, gruu
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO, UPDATE
Contact: "Outdoor" <sip:outdoor@192.168.1.186;transport=tcp>;+sip.instance="<urn:uuid:7f129334-2dd3-006b-9400-82cdc195d3cb>"
Content-Type: application/sdp
Content-Length: 237

v=0
o=outdoor 2172 3697 IN IP4 127.0.0.1
s=Talk
c=IN IP4 127.0.0.1
b=AS:20
t=0 0
m=audio 7078 RTP/AVP 97 96
a=rtpmap:97 speex/8000
a=fmtp:97 vbr=on
a=rtpmap:96 telephone-event/8000
a=ptime:100
m=video 0 RTP/AVP 0
a=inactive

**Comment by Viish** [comment]
As you can see in the audio only 200 OK the video is disabled:
```
m=video 0 RTP/AVP 0
a=inactive
```
Check the full logs from the start of the app to the 200 OK to see why.

**Comment by fanfan1009** [comment]
I have two network ports on my device. When I use the first port, I don't have this problem. But with the second port, you get this problem. So, I wonder if it's because only the first port is selected by default
