### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by shixinglingguihua** [BelledonneCommunications/linphone-android#9]
when I comile the linphone-android project(it from linphone) ,exec the python cmd "python ./prepare.py ",then I exec makefile cmd "make" ,the compile progress is broken .Linux terminal print some thing but I dont not nkown  how to resolve . could you help me? please
![Uploading problem.png…]()

here is the linux log
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /home/linguihua/lingugihua/projectFIle/linphone-android/liblinphone-sdk/android-arm64/lib/libsrtp.a
-- Installing: /home/linguihua/lingugihua/projectFIle/linphone-android/liblinphone-sdk/android-arm64/include/srtp/config.h
make[4]: Leaving directory '/home/linguihua/lingugihua/projectFIle/linphone-android/WORK/android-arm64/Build/srtp'
[ 62%] Completed 'EP_srtp'
make[3]: Leaving directory '/home/linguihua/lingugihua/projectFIle/linphone-android/WORK/android-arm64/cmake'
[ 62%] Built target EP_srtp
make[3]: Entering directory '/home/linguihua/lingugihua/projectFIle/linphone-android/WORK/android-arm64/cmake'
Scanning dependencies of target EP_vpx
make[3]: Leaving directory '/home/linguihua/lingugihua/projectFIle/linphone-android/WORK/android-arm64/cmake'
make[3]: Entering directory '/home/linguihua/lingugihua/projectFIle/linphone-android/WORK/android-arm64/cmake'
[ 62%] Creating directories for 'EP_vpx'
[ 63%] No download step for 'EP_vpx'
[ 63%] No patch step for 'EP_vpx'
[ 63%] No update step for 'EP_vpx'
[ 64%] Performing configure step for 'EP_vpx'
/bin/sh: 1: /home/linguihua/lingugihua/projectFIle/linphone-android/WORK/android-arm64/cmake/EP_vpx_configure.sh: Permission denied
CMakeFiles/EP_vpx.dir/build.make:106: recipe for target '/home/linguihua/lingugihua/projectFIle/linphone-android/WORK/android-arm64/Stamp/EP_vpx/EP_vpx-configure' failed
make[3]: *** [/home/linguihua/lingugihua/projectFIle/linphone-android/WORK/android-arm64/Stamp/EP_vpx/EP_vpx-configure] Error 126
make[3]: Leaving directory '/home/linguihua/lingugihua/projectFIle/linphone-android/WORK/android-arm64/cmake'
CMakeFiles/Makefile2:1276: recipe for target 'CMakeFiles/EP_vpx.dir/all' failed
make[2]: *** [CMakeFiles/EP_vpx.dir/all] Error 2
make[2]: Leaving directory '/home/linguihua/lingugihua/projectFIle/linphone-android/WORK/android-arm64/cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/linguihua/lingugihua/projectFIle/linphone-android/WORK/android-arm64/cmake'
Makefile:179: recipe for target 'arm64-build' failed
make: *** [arm64-build] Error 2

**Comment by DatBewar** [comment]
Hello,
it seems you have a permission issue when it's trying to execute this script:
`/bin/sh: 1: /home/linguihua/lingugihua/projectFIle/linphone-android/WORK/android-arm64/cmake/EP_vpx_configure.sh: Permission denied`
Maybe a problem in your Gnu/Linux user config.

**Comment by shixinglingguihua** [comment]
en, I try again,thanks.

**Comment by shixinglingguihua** [comment]
@DatBewar hello
i ask a question，can I compile linphone-android project in Linux where it run on VMware?

**Comment by DatBewar** [comment]
Yes there are no problem to do that.

**Comment by shixinglingguihua** [comment]
oh，maybe another question
