### ISSUE TITLE
An error with LinphoneCore

### ISSUE THREAD

**Issue by EjsBoy** [BelledonneCommunications/linphone-android#90]
Trying to implement Linphone into Ionic with using Cordova Plugin.

Error:
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception 'java.lang.SecurityException' thrown in unknown throw location
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]     in call to NewGlobalRef
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]     from java.lang.Object org.linphone.core.LinphoneCoreImpl.inviteAddressWithParams(long, long, long)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65] "JavaBridge" prio=7 tid=32 Runnable
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   | group="main" sCount=0 dsCount=0 obj=0x12e6a2b0 self=0xb88d7270
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   | sysTid=30686 nice=0 cgrp=apps sched=0/0 handle=0xb88d67d0
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   | state=R schedstat=( 571356937 43642851 776 ) utm=53 stm=4 core=0 HZ=100
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   | stack=0x9f9e9000-0x9f9eb000 stackSize=1036KB
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   | held mutexes= "mutator lock"(shared held)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   native: #00 pc 000045d4  /system/lib/libbacktrace_libc++.so (_ZN13UnwindCurrent6UnwindEjP8ucontext+23)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   native: #01 pc 00002e55  /system/lib/libbacktrace_libc++.so (_ZN9Backtrace6UnwindEjP8ucontext+8)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   native: #02 pc 002483f1  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiPKcPNS_6mirror9ArtMethodE+68)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   native: #03 pc 0022d12b  /system/lib/libart.so (_ZNK3art6Thread4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+146)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   native: #04 pc 000b193b  /system/lib/libart.so (_ZN3artL8JniAbortEPKcS1_+582)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   native: #05 pc 000b2075  /system/lib/libart.so (_ZN3art9JniAbortFEPKcS1_z+60)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   native: #06 pc 000b5185  /system/lib/libart.so (_ZN3art11ScopedCheckC2EP7_JNIEnviPKc+1284)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   native: #07 pc 000b63ed  /system/lib/libart.so (_ZN3art8CheckJNI12NewGlobalRefEP7_JNIEnvP8_jobject+20)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   native: #08 pc 003c23f9  /data/app/io.ionic.starter-1/lib/arm/liblinphone.so (wake_lock_acquire+104)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   native: #09 pc 00320c9f  /data/app/io.ionic.starter-1/lib/arm/liblinphone.so (???)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   native: #10 pc 003214d3  /data/app/io.ionic.starter-1/lib/arm/liblinphone.so (belle_sip_client_transaction_init+122)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   native: #11 pc 003c2889  /data/app/io.ionic.starter-1/lib/arm/liblinphone.so (belle_sip_ict_new+28)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   native: #12 pc 0031d3e1  /data/app/io.ionic.starter-1/lib/arm/liblinphone.so (belle_sip_provider_create_client_transaction+88)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   native: #13 pc 002b5cad  /data/app/io.ionic.starter-1/lib/arm/liblinphone.so (sal_op_send_request+524)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   native: #14 pc 002cfe69  /data/app/io.ionic.starter-1/lib/arm/liblinphone.so (linphone_call_start_invite+160)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   native: #15 pc 002d5833  /data/app/io.ionic.starter-1/lib/arm/liblinphone.so (linphone_core_invite_address_with_params+422)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   native: #16 pc 002f221d  /data/app/io.ionic.starter-1/lib/arm/liblinphone.so (Java_org_linphone_core_LinphoneCoreImpl_inviteAddressWithParams+14)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   native: #17 pc 00040b1f  /data/dalvik-cache/arm/data@app@io.ionic.starter-1@base.apk@classes.dex (Java_org_linphone_core_LinphoneCoreImpl_inviteAddressWithParams__JJJ+126)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   at org.linphone.core.LinphoneCoreImpl.inviteAddressWithParams(Native method)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   at org.linphone.core.LinphoneCoreImpl.inviteAddressWithParams(LinphoneCoreImpl.java:577)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   - locked <0x19ed35cf> (a org.linphone.core.LinphoneCoreImpl)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   at org.linphone.mini.CallMiniManager.inviteAddress(CallMiniManager.java:49)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   at org.linphone.mini.LinphoneMiniManager.newOutgoingCall(LinphoneMiniManager.java:480)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   at eu.nexwell.ionic.linphone.VidIPLinphone.startCall(VidIPLinphone.java:66)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   at eu.nexwell.ionic.linphone.VidIPLinphone.execute(VidIPLinphone.java:41)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native method)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:7)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   at android.os.Handler.dispatchMessage(Handler.java:102)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   at android.os.Looper.loop(Looper.java:135)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]   at android.os.HandlerThread.run(HandlerThread.java:61)
07-24 13:48:17.904 30599-30686/io.ionic.starter A/art: sart/runtime/check_jni.cc:65]

**Comment by DatBewar** [comment]
Hello, without more informations we can't help you

**Comment by EjsBoy** [comment]
My fault. I forgot to add permission - WAKE_LOCK.
It's fixed :)
