### ISSUE TITLE
app crashed in android 4.4

### ISSUE THREAD

**Issue by krv372** [BelledonneCommunications/linphone-android#901]
hi 
i used liblinphone 3.15 before, i update to latest version, on android version above 6 it works well but i in android 4.4 it faild and crashed: 
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "random" referenced by "libbctoolbox.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:371)
        at java.lang.System.loadLibrary(System.java:606)
        at org.linphone.core.FactoryImpl.<clinit>(Factory.java:297)
        at org.linphone.core.Factory.instance(Factory.java:44)

**Comment by Viish** [comment]
Hi,
What do you mean by latest version ?

**Comment by krv372** [comment]
liblinphone 4.3

**Comment by Viish** [comment]
Built by yourself ? Taken from our maven ?

**Comment by krv372** [comment]
> Hi,
> What do you mean by latest version ?

i update to from liblinphone 3.15 to liblinphone 4.3

**Comment by krv372** [comment]
> Built by yourself ? Taken from our maven ?

I build it myself

**Comment by Viish** [comment]
Which NDK version are you using ?

**Comment by krv372** [comment]
I'm using version NDK version 20

**Comment by Viish** [comment]
That's why.
You can't build an Android 4.4 compatible SDK using a NDK > 17

**Comment by krv372** [comment]
Thank you for your response
