### ISSUE TITLE
camera preview

### ISSUE THREAD

**Issue by krv372** [BelledonneCommunications/linphone-android#902]
hi , in my app when user clicked on video call button , In the background of the Call Activity  the front camera  is displayed (Similar to WhatsApp), for this i used the method **core.enableVideoPreview(true)**  , But the camera image is displayed for a few seconds and then the camera image is locked after a few seconds.
 What can I do to solve this problem?

**Comment by Viish** [comment]
Hi,
Please attach logs (don't forget to enable them by toggling on the debug switch in settings->advanced, restart the app and then reproduce the issue).
The upload logs button is in the About page.

**Comment by Viish** [comment]
It is very likely your issue will be fixed if you switch to a very recent SDK like 4.3.1-pre.17+c6a2c0a or newer.
We fixed an issue that looks a lot like yours.

**Comment by krv372** [comment]
thank you
