### ISSUE TITLE
Linphone Crashes Systematically in Call History Screen

### ISSUE THREAD

**Issue by stef204** [BelledonneCommunications/linphone-android#903]
Linphone Android 4.2.0-beta (F-Droid)
When going to Call Log (or History) screen, and clicking on the 3 dots to the right of any calls to get more details, the app crashes, every time.
This also seems to occur on the locally built branch: 4.3-alpha 5+777359e2

**Comment by Viish** [comment]
Hi,
Can you reproduce the issue with our latest version (4.2.1) from the store or this APK: http://linphone.org/releases/android/linphone-android-4.2.1.apk ?
If yes, please attach the stacktrace using adb logcat.

**Comment by stef204** [comment]
I need to apologize.  I checked again the 4.3-alpha 5+777359e2 and it does not crash there. Also I have the alpha version on a different phone (Samsung) and Android 9 as opposed to 7.1.2 for 4.2.0-beta.
Will try the 4.2.1 apk you linked to above.  But will need to uninstall F-Droid version due to signature. 
If 4.2.1 is an official release, can it be pushed to F-Droid?

**Comment by Viish** [comment]
Ok great.
For F-Droid you will have to check with them.
