### ISSUE TITLE
How the country code can be disabled by default ?

### ISSUE THREAD

**Issue by czaviar** [BelledonneCommunications/linphone-android#904]
Hi,

I have a annoying issue - each time when I configure new SIP account using the generic form there is a country code (prefix, e.g +1 for USA) added to configuration. Is there any chance to disable it ?

**Comment by Viish** [comment]
Hi,
You can remove the value in the Prefix field of the account settings.

**Comment by czaviar** [comment]
Well, of course :) But I would like to have it empty by default. 

Is there any flag in nonlocalizable_custom file (or any other xml) where I could disable it ?

**Comment by Viish** [comment]
No, it is done by the SDK, not the app.
From the moment you connect using a phone number the dial prefix will be set in the proxy config.

**Comment by czaviar** [comment]
If I use the phone number, that would be helpful, indeed.

But since I use 4 digit numbers on my own Flexisip serwer the automatic prefix is really annoying. Perhaps I should recompile the SDK. Where should I look for prefix disable in SDK ?

**Comment by Viish** [comment]
Make sure you don't go through the setDialPrefix method call in AssistantActivity also.
