### ISSUE TITLE
Problem after recompiling linphone-android-sdk

### ISSUE THREAD

**Issue by Nicolo-sudo** [BelledonneCommunications/linphone-android#907]
Hi there!

I have build my own version of the linphone sdk for android. I wanted to enable the H263 codec, so I recompiled the sdk by passing the -DENABLE_FFMPEG=ON and an .AAR file was built successfully.
So I have replaced the previous sdk with my own in the Linphone Android Project.
The problem is that in the video settings of the app there are only the H264, H265 and VP8 codecs.
Why there isn't the H263 codec?

Thanks in advance

**Comment by Viish** [comment]
Hi,
Please attach logs from the libs and I'll be able to tell you why.

**Comment by Nicolo-sudo** [comment]
Do you mean the logs of the shell? Because I lost them when I close the window.. 
I probably need to recompile the sdk again.

Thank you for your help

**Comment by Viish** [comment]
No I'd like the logs of the app. Go into settings->advanced and toggle Debug switch.
Then restart the app, go to the About page and click on Upload logs.

**Comment by Nicolo-sudo** [comment]
Alright, so tomorrow I will try and I will let you know!

Thank you again for your attention

**Comment by Nicolo-sudo** [comment]
Hi, I have attached the library logs.

[5e313218c5457_4f1a2a2572c73fe7c5f3.txt](https://github.com/BelledonneCommunications/linphone-android/files/4126702/5e313218c5457_4f1a2a2572c73fe7c5f3.txt)

What I have done:
- I built my own sdk with this options:

```
 -DLINPHONESDK_PLATFORM=Android -DENABLE_FFMPEG=ON 
-DENABLE_NON_FREE_CODECS=ON
```

- I created a symbolic link to the sdk by following this example: 

> ln -s <path to linphone-sdk>/linphone-sdk/build/linphone-sdk/bin/outputs/aar/linphone-sdk-android-release.aar linphone-sdk-android/linphone-sdk-android-release.aar

- I built the Linphone App with Android Studio
- I enabled the debug logs in settings of the Linphone app
- I sent logs

This procedure is correct or I have made some mistakes?

**Comment by Viish** [comment]
Yes this is perfectly right.
Did you also add to the cmake options -DENABLE_H263=ON ?

**Comment by Nicolo-sudo** [comment]
No, as said here (#821 ) i also add  -DENABLE_FFMPEG=ON.

I will try again to rebuild the sdk with this option

Thanks

**Comment by Nicolo-sudo** [comment]
Hi, nothing changed still no H263 codec

**Comment by Viish** [comment]
Can you add new logs ?

**Comment by Nicolo-sudo** [comment]
I have made few tests.

If I build with -DENABLE_H263= ON and -DENABLE_FFMPEG=ON the compilation fails after few seconds:

[crash_compiling.txt](https://github.com/BelledonneCommunications/linphone-android/files/4128236/crash_compiling.txt)

So I built the new sdk with this options: 

`cmake -DLINPHONESDK_PLATFORM=Android -DLINPHONESDK_ANDROID_ARCHS=arm64 -DENABLE_NON_FREE_CODECS=ON -DENABLE_H263=ON ..`

Unfortunatelly again there is no H263 feature in this new files:

[disabled_features.txt](https://github.com/BelledonneCommunications/linphone-android/files/4128436/disabled_features.txt)
[enabled_features.txt](https://github.com/BelledonneCommunications/linphone-android/files/4128437/enabled_features.txt)

This are the new logs:

[5e31943055483_ae1d5ba40fc5bb601392.txt](https://github.com/BelledonneCommunications/linphone-android/files/4128465/5e31943055483_ae1d5ba40fc5bb601392.txt)

No luck, unfortunately

**Comment by Viish** [comment]
You need all those params:
-DENABLE_NON_FREE_CODECS=ON -DENABLE_H263=ON -DENABLE_FFMPEG=ON

**Comment by Nicolo-sudo** [comment]
Okay but the compilation fails if I use all these options together

**Comment by Viish** [comment]
No, sadly you are in the current case where ffmpeg doesn't build anymore (I guess you have a recent NDK).
We have no plan to make it work again for now, but if you manage I'll gladly merge a patch.
