### ISSUE TITLE
Adding contact -- Android contact lists or private Linphone contact list?

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#911]
I'm confused about how Linphone handles adding contacts.

I can choose a contact to call that is my Android address book (i.e. Google Contacts, or any configured carddav server) but when I try to add a contact from Linphone, I don't see that contact in any address book using the Contacts app on the phone.

So where is this contact being added?

**Comment by Viish** [comment]
Hi,
We create a "sync account" named Linphone, and we store the contacts in it. In the Android settings, under "Accounts" you will see it.
The native contact app is capable of reading contacts from it (you might have to enable it manually).
There is already an issue opened to let users choose the account they want to add the contact to, I'll do it some day.

**Comment by brianjmurrell** [comment]
I see.

The feature to choose the account would be useful.  Looks like it's #590 for anyone who comes across this.
