### ISSUE TITLE
Call history detail pages only show outgoing calls, not incoming calls

### ISSUE THREAD

**Issue by djsquare5** [BelledonneCommunications/linphone-android#913]
Hi.  I am using Linphone Android 4.2 (release).  I noticed that on the call history tab, all my calls (both incoming and outgoing) show up fine.  However, when I click on the three dots to the right of one of the calls, which brings me to the call history detail page, all outgoing calls to that user are shown, but none of the incoming calls are shown.  Is this something you could fix please?

**Comment by Viish** [comment]
Hi,
I don't reproduce this issue.
Could you enable debug logs in settings->advanced, restart the app, go to history page and click on the three dots of an incoming call please? Then go to About page, upload the logs and put in the subject the number of this issue.
Thanks.
