### ISSUE TITLE
Linphone core problem

### ISSUE THREAD

**Issue by nzkar** [BelledonneCommunications/linphone-android#914]
Hi, I cannot build my linphone application today. It was ok on Friday but today it gives hundreds of "error: cannot find symbol class ..." errors. It cannot find linphone.core.Address, linphone.core.Call and many etc.

**Comment by nzkar** [comment]
I'm using version 4.3+

**Comment by nzkar** [comment]
I downloaded the latest master code with version 4.4+ and it works however obviously something has changed with version 4.3+

**Comment by Viish** [comment]
Indeed we had a brief issue with our AAR packaging Friday, it is ok now, newly uploaded AAR won't have the issue.
