### ISSUE TITLE
How to set up to reduce the bandwidth occupied by audio and video

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#916]
Hi,

There are several questions to ask:
1, How to set to reduce the bandwidth used in video transmission? I know  I can use a smaller resolution. For example, VGA occupies less bandwidth than 720p. Is there any other way?

2, How to set to reduce the bandwidth used in audio transmission? Now the default is opus 48000HZ. Can I reduce the bandwidth used in audio transmission by modifying the encoding method or sampling rate? Is there any other way?

3, The default bandwidth setting of the linphone should be 0?  Does this mean that it is adaptive? That is to say, how much bandwidth does it actually have, and how much is it used for audio and video?

thanks.
Best Regard.

**Comment by Viish** [comment]
Please open this issue in https://github.com/BelledonneCommunications/liblinphone project.
