### ISSUE TITLE
How to set the sampling rate of Opus 

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#918]
Hi,

Now the default sampling rate of opus is 48Khz. Can I set it to other sampling rates? such as 8Khz, 12Khz, 16Khz, 24Khz, If it can be set, how to set it? 

thanks.
Best Regards.

**Comment by Viish** [comment]
Hi,
Please open SDK related tickets to either linphone-sdk or liblinphone repositories.
Best regards,
