### ISSUE TITLE
sdp attribute rtcp has private ip even though stun is configured

### ISSUE THREAD

**Issue by rtreleaven** [BelledonneCommunications/linphone-android#92]
**version**
Linphone Android 3.2.7
Linphone Core 3.11.1-242-g9782bd388

**to reproduce**
configure a valid stun server "stun.freeswitch.org"
ensure ice is disabled
from a private ip network place a call to generate an invite

**observed**
the sdp in the invite looks like this
   v=0
   o=some_guy 406 3354 IN IP4 **$public_ip**
   s=Talk
   c=IN IP4 **$public_ip**
   b=AS:380
   t=0 0
   a=rtcp-xr:rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics
   m=audio 7076 RTP/AVP 96 0 8 9 101 97
   a=rtpmap:96 opus/48000/2
   a=fmtp:96 useinbandfec=1
   a=rtpmap:101 telephone-event/48000
   a=rtpmap:97 telephone-event/8000
   a=rtcp:7077 IN IP4 **$private_ip**
   a=rtcp-fb:* ccm tmmbr

**expected**
The rtcp attribute should have $public_ip instead of $private_ip

**Comment by rtreleaven** [comment]
Not even a comment?

**Comment by Viish** [comment]
Sorry. This has been fixed, hence the close.

**Comment by rtreleaven** [comment]
Thanks I will verify.
