### ISSUE TITLE
Mute/Unmute option does not work for "linphone-sdk-android:4.4+", but works for "linphone-sdk-android:4.3+"

### ISSUE THREAD

**Issue by GeorgeMina** [BelledonneCommunications/linphone-android#920]
My logs didn't show anything useful, but the command "mCore.enableMic(boolean)" did not work. I tried logging the boolean returned by micEnabled(), but it never changed. Is this an error of the sdk, or mine?

Edit: Actually, my issue seems to be resolved by refreshing or running gradle again, for some reason. I don't know the cause of the issue, though.

**Comment by nzkar** [comment]
Hi, this is still a problem after gradle sync with sdk 4.4+. Mic button is not working.

**Comment by GeorgeMina** [comment]
> Hi, this is still a problem after gradle sync with sdk 4.4+. Mic button is not working.

Okay, thanks nzkar, yes syncing back to 4.3 resolved my issue, so I will keep it there for now.

**Comment by Viish** [comment]
Mute issue has been fixed in liblinphone commit 50334609a348796876dfdb0af0724c5083c0c570

**Comment by Viish** [comment]
> I am still having this issue on Linphone SDK v5.0.40.

Try with 5.0.67

**Comment by rexhabitap** [comment]
> > I am still having this issue on Linphone SDK v5.0.40.
> 
> Try with 5.0.67

Does that version exist in https://linphone.org/maven_repository ?  I get this error:
```
Failed to resolve: org.linphone:linphone-sdk-android:5.0.67
```
