### ISSUE TITLE
Incoming call rings 2sec and  disconnects automatically in my linphone app logged with sip account

### ISSUE THREAD

**Issue by raviteja74** [BelledonneCommunications/linphone-android#922]
when I dialed from one account to another account number (Both are sip accounts) recipient caller got rings 2 or 3 seconds and disconnects automatically and gets a message "No active calls" So, could you please give a reply if Any problem with my sip account or any mistake I did.

**Comment by Viish** [comment]
Please attach logs from the library (in settings->advanced enable debug mode), restart the app, reproduce the issue then go to About page and click on Upload Logs.
