### ISSUE TITLE
4.4+ Mic. issue

### ISSUE THREAD

**Issue by nzkar** [BelledonneCommunications/linphone-android#923]
Hi, I have commented to the closed issue

**Comment by nzkar** [comment]
Mute/Unmute option does not work for "linphone-sdk-android:4.4+", but works for "linphone-sdk-android:4.3+" #920. It is a continuing problem with the latest version. Can you please check it?

**Comment by Viish** [comment]
It was fixed in liblinphone commit 50334609a348796876dfdb0af0724c5083c0c570 and SDK commit b75b05b492a375722e65861679746fa49e4c539d

**Comment by nzkar** [comment]
Aren't those commits integrated to linphone-android master version?

**Comment by Viish** [comment]
Linphone-android depends on liblinphone SDK provided by maven and uses by default the most recent one. However Android Studio doesn't check for new versions systematically, so you may have to manually ask it to update liblinphone SDK.

**Comment by nzkar** [comment]
Sorry but no idea, how do we manually ask it to update the SDK?

**Comment by Viish** [comment]
https://maxrohde.com/2014/09/08/force-android-studio-to-update-maven-snapshot-dependencies/

**Comment by nzkar** [comment]
Thank you, it solved the problem.
