### ISSUE TITLE
What is the best video codec for linphone?

### ISSUE THREAD

**Issue by djkskqyr3** [BelledonneCommunications/linphone-android#927]
Hello, 
You are doing great job and I like linphone sdk and I am using linphone sdk for 5 years.
Basically I used Opus codec for audio call,  (G729, Speech, PCMA, PCMU as well)
What I am asking is,  What is the best codec for video call.
I tried to use X264. H264, VP8 but no lucky. (even I used FFMPEG option too)
There are many issues like something packet drop, black screen, and so on.
Totally Bad video quality.
Please tell me what I have to use video codec, and what is the best configuration.
Thank you

**Comment by Viish** [comment]
Hi,
I'm glad you like it. What is your app name that uses Linphone ? (for my curiosity)
Regarding the video, we recommend H264 on devices with Media Codec or VP8.
Cheers,
