### ISSUE TITLE
Unable to set Custom Header

### ISSUE THREAD

**Issue by deepak2503** [BelledonneCommunications/linphone-android#928]
` @Override
                    public void onRegistrationStateChanged(
                            Core core,
                            ProxyConfig proxyConfig,
                            RegistrationState state,
                            String message) {
                        String firebasetokenis =
                                LinphonePreferences.instance().getPushNotificationRegistrationID();
                        mSideMenuFragment.displayAccountsInSideMenu();

                        if (state == RegistrationState.Ok) {

                            if (proxyConfig == null) {

                            } else {
                                proxyConfig.edit();

                                proxyConfig.setCustomHeader(
                                        "X-VOIPPUSHTOKEN", firebasetokenis); // deep

                                proxyConfig.done();

                                String toastString =
                                        "Header value for X-VOIPPUSHTOKEN = "
                                                + proxyConfig.getCustomHeader("X-VOIPPUSHTOKEN");

                                Toast.makeText(MainActivity.this, toastString, Toast.LENGTH_SHORT)
                                        .show();
                            }

                            // For push notifications to work on some devices,
                            // app must be in "protected mode" in battery settings...
                            // https://stackoverflow.com/questions/31638986/protected-apps-setting-on-huawei-phones-and-how-to-handle-it
                            DeviceUtils
                                    .displayDialogIfDeviceHasPowerManagerThatCouldPreventPushNotifications(
                                            MainActivity.this);

                            if (getResources().getBoolean(R.bool.use_phone_number_validation)) {
                                AuthInfo authInfo =
                                        core.findAuthInfo(
                                                proxyConfig.getRealm(),
                                                proxyConfig.getIdentityAddress().getUsername(),
                                                proxyConfig.getDomain());
                                if (authInfo != null
                                        && authInfo.getDomain()
                                                .equals(getString(R.string.default_domain))) {
                                    LinphoneManager.getInstance().isAccountWithAlias();
                                }
                            }

                            if (!Compatibility.isDoNotDisturbSettingsAccessGranted(
                                    MainActivity.this)) {
                                displayDNDSettingsDialog();
                            }
                        }
                    }`

Above is the code through which I am trying set a custom header. But when I am trying to check whether the custom header has set or not through proxyConfig.getCustomHeader(headername: "X-VOIPPUSHTOKEN") it providing a null value.

**Comment by Viish** [comment]
Hi,
Please open this ticket on [liblinphone](https://github.com/BelledonneCommunications/liblinphone)'s project repository.
Cheers,
