### ISSUE TITLE
Is it possible to change the database columns?

### ISSUE THREAD

**Issue by GeorgeMina** [BelledonneCommunications/linphone-android#929]
Specifically, I would like to add/remove columns in the generated file 'linphone-friends.db'. Is it possible to access the class which creates that db, and change the db/tables?

**Comment by Viish** [comment]
Not in the Android app directly, all the database stuff is handled by the SDK.

**Comment by GeorgeMina** [comment]
> Not in the Android app directly, all the database stuff is handled by the SDK.

Apologies, Viish - last question. Could you point me to where, inside "org.linphone.core.tools", the database creation is being handled?

**Comment by Viish** [comment]
It's not in org.linphone.core.tools package.
The SDK is mostly C++ code, wrapped in Java.
The database code is in src/db/maindb.cpp
