### ISSUE TITLE
No RTP traffic behind VPN when SRTP and/or TLS are selected 

### ISSUE THREAD

**Issue by nick879** [BelledonneCommunications/linphone-android#93]
Hi,

  I am trying to set up a Voip service behind VPN (openvpn 2.4.2) for android mobile users using linphone and kamailio 4.4.5 as the sip server. TLS transport and SRTP encryption are selected (however TCP transport is also used to facilitate debug from sip server side).

The android vpn client app is the "Openvpn for Android" one (ics-openvpn) and a default route through vpn directive is passed to the clients.

The network architecture has been validated and clients using linphone 3.2.7 and android version 5+ are registered (TLS) and speak (SRTP) to each other correctly and with high robusteness.

However, I face a problem concerning clients using Android 4.4.x (and probably older versions). 
What is happening is that although these clients are correctly registered with their VPN private IP, when a call is initiated from a 4.4.x client, the INVITE message includes both in Via header and in the sdp description either the public IP provided to the phone by the carrier or the local network address (if the phone is attached to a wlan). This results in a one-way audio phenomenon (specifically, the 5+ clients hears what 4.4.x client but not vice versa). As expected the 5+ clients are trying to communicate with the above mentioned IPs.

Contrarily when a call is initiated form an android 5+ client to a 4.4.x client the sip packets are as supposed to be and the call is performed flawlessly.

Moreover, when SRTP and TLS are removed (TCP and no encryption) every is created and performed well.

I have identified that a significant difference between 5+ and 4.4.x clients is the existence of a default gateway record on the latters (which is always the carrier or wlan IP).

As I see in other threads, linphone uses a clever algorithm to sense where is the sip server and route the traffic by the correct interface.

However, is this also true for SRTP and TLS related submodules?

Is there a way to modify the behavior of a related function (?) to always prefer the VPN (tun) interface?

Thank you very much in advance.

Nick

**Comment by Viish** [comment]
Old issue, I'm closing it. Feel free to reopen if it still applies with version 4.2.
