### ISSUE TITLE
Linphone Application Crashes while using H264 Codec On rockchip/rk3288-myzr/rk3288

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#930]
Hi @Viish ,
Hope you doing great there.

I am facing one problem in video calling, while using codec H264 on **rockchip/rk3288-myzr/rk3288**, as application crashing after two minutes. I have never faced this kind of issue but on ### **myzr rk3288** this is continuously coming.

Logs is attached.

Please let me know what is the issue.

[H264_SENDER.txt](https://github.com/BelledonneCommunications/linphone-android/files/4259545/H264_SENDER.txt)

[H264_Receiver.txt](https://github.com/BelledonneCommunications/linphone-android/files/4259547/H264_Receiver.txt)

**Comment by Viish** [comment]
Yes you aren't the first one to have issues with rockchip devices hardware encoder/decoder.
Please clone linphone-sdk, edit this file in mediastreamer2 https://github.com/BelledonneCommunications/mediastreamer2/blob/master/src/audiofilters/devices.c#L228 and add a line for your device (same as X9-LX and replace it by rk3288-myzr for example), build the SDK and the linphone-android app with this SDK (everything is explained in the READMEs) and tell me if it helps.
If yes, I'll commit the fix.

**Comment by Viish** [comment]
You can also simply edit the linphone-android project and use Mediastreamer's Factory java class (use `Core.getMsFactory()` to get it) to add the same hack at runtime (before starting the call) using `setDeviceInfo(String manufacturer, String model, String platform, int flags, int delay, int recommended_rate)` method.

**Comment by amit1576** [comment]
Hi @Viish ,

I have added 	**{	"rockchip",				"rk3288-myzr",			"rk3288",		DEVICE_USE_ANDROID_CAMCORDER, 0, 16000},** in devices.c file and build the sdk but no success.

Log file has been attached for the same.


[Sender_Myzr_H264.txt](https://github.com/BelledonneCommunications/linphone-android/files/4270235/Sender_Myzr_H264.txt)


Please suggest any other work around.

Thanks,

**Comment by Viish** [comment]
Hi,
Try to add your device in the following file:
https://github.com/BelledonneCommunications/mediastreamer2/blob/1a9e8dec369a65ed10db975f5b77b92dc999b096/src/voip/h26x/media-codec-h264-decoder.cpp#L205
Cheers,

**Comment by amit1576** [comment]
Hi @Viish ,

Actually I have already added **{"rockchip", "rk3288-myzr", "rk3288"}** in **media-codec-h264-decoder.cpp** file. 

This will resolve video orientation issue only.

**Comment by Viish** [comment]
Can you capture the crash stack trace with adb (or even better ndk-stack) and attach it here please?

**Comment by amit1576** [comment]
Hi @Viish ,

As suggested, I am attaching crash log. One is with H264 codec and one is with VP8 codec. Application getting crash with in minute with H264.


[myzr_h264_crash_debug_log.txt](https://github.com/BelledonneCommunications/linphone-android/files/4285455/myzr_h264_crash_debug_log.txt)

[myzr_VP8_debug_log.txt](https://github.com/BelledonneCommunications/linphone-android/files/4285456/myzr_VP8_debug_log.txt)

It seems to be memory leakage issue.

Thanks.

**Comment by Viish** [comment]
Hi Amit,
There is no crash in any of the logs you attached.
The following is simply a warning that happens on devices that don't support H265 through MediaCodec API:
`W/System.err: java.lang.IllegalArgumentException: Failed to initialize video/hevc, error 0xfffffffe
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:486)
        at android.media.MediaCodec.createEncoderByType(MediaCodec.java:456)
        at org.linphone.core.FactoryImpl.createCore3(Native Method)
        at org.linphone.core.FactoryImpl.createCore(Factory.java:520)
        at org.linphone.LinphoneManager.startLibLinphone(LinphoneManager.java:439)
        at org.linphone.LinphoneContext.start(LinphoneContext.java:161)
        at org.linphone.LinphoneService.onStartCommand(LinphoneService.java:84)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2914)
        at android.app.ActivityThread.access$2100(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5280)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)`

**Comment by amit1576** [comment]
Hi @Viish ,

Actually this is the last line captured in log.

**I/art: Background sticky concurrent mark sweep GC freed 36110(3MB) AllocSpace objects, 385(6MB) LOS objects, 37% free, 13MB/21MB, paused 623us total 265.160ms
Process 3589 terminated.**

After this the application relaunch itself. Mean ongoing call is there if i check other party and in my sip server, But on myzr board the application relaunch it self.

**Comment by Viish** [comment]
Ok but that doesn't help me at all.
Please attach the full output of `adb logcat` started before the begining of the call until the app restarts.

**Comment by amit1576** [comment]
Hi @Viish ,

Please find attached adb logcat. May be it will help you.

[adb_locat_error.txt](https://github.com/BelledonneCommunications/linphone-android/files/4291267/adb_locat_error.txt)

Please let me know is this log file enough to debug.


Thanks.

**Comment by Viish** [comment]
No it doesn't help.
Can you try with the latest version of the app (4.2.3) and SDK (4.3.3) just in case?

**Comment by amit1576** [comment]
Ok, 

I will check and let you know

**Comment by amit1576** [comment]
Hello @Viish,

Latest version of Code and SDK worked for me. H264 calls is working fine now on MYZR Board. Means it is SDK level bug?

Thanks for you prompt support as always .

**Comment by Viish** [comment]
Yes that mean it was an issue in our SDK that we fixed.
