### ISSUE TITLE
Question:  Forecast availability of Linphone version 4.2.2 from F-Droid?

### ISSUE THREAD

**Issue by aGrimRepoMan** [BelledonneCommunications/linphone-android#931]
I just started using linphone-android and like it - thanks for your work on this project.  

I want to ensure I'm using the latest version.  If I'm not mistaken, the latest released linphone-android version is 4.2.2:
  ref : https://play.google.com/store/apps/details?id=org.linphone 
   "Additional information
    Updated  February 26, 2020
    Current Version  4.2.2"

On F-Droid, I see the latest available version is 4.1.1.  For those not using the Play Store, is there a forecast availability for version 4.2.2 on F-Droid?

**Comment by Viish** [comment]
Hi,
I actually don't know as we aren't in charge of fdroid builds.
You will have to ask this question to them directly. 
Even if you don't use the Google play store you can find our release apk there: https://linphone.org/releases/android/
Cheers,

**Comment by aGrimRepoMan** [comment]
Understood - thanks for the quick reply.

**Comment by aGrimRepoMan** [comment]
Just FYI (and for others who might have the same question as I did), at time of writing, there seems to be a general process delay internal to F-Droid ... See for example: https://gitlab.com/fdroid/fdroiddata/issues/1937
