### ISSUE TITLE
call screen problem in MIUI

### ISSUE THREAD

**Issue by krv372** [BelledonneCommunications/linphone-android#933]
hi , in xiaomi phones whit Rom MIUI , Incoming Call Activity dont show when device's screen is off. 
i have used below code for wake lock, working in all devices except xiamoi devices `getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON | WindowManager.LayoutParams.FLAG_DISMISS_KEYGUARD | WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED | WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON);`
Do you have any ideas for solving this problem?

**Comment by Viish** [comment]
Do you reproduce with linphone app from the Play Store ?

**Comment by krv372** [comment]
No , i just use Linphone sdk in my app

**Comment by krv372** [comment]
![f6nUn](https://user-images.githubusercontent.com/9881569/75763143-0670a080-5d51-11ea-858f-fb951545d580.png)
![f6nUn](https://user-images.githubusercontent.com/9881569/75763150-0a9cbe00-5d51-11ea-81d0-06ae704b6db4.png)

**Comment by Viish** [comment]
Most probably it is because you don't ask for SYSTEM_ALERT_WINDOW permission.
Also on Android 10 you can't start activities from background, you must use FullscreenIntent.

**Comment by krv372** [comment]
No, it's not just for Xiaomi phones
