### ISSUE TITLE
Provide metadata and images for app stores

### ISSUE THREAD

**Issue by PanderMusubi** [BelledonneCommunications/linphone-android#935]
Please, provide metadata and images for app stores. These images such as screenshots and feature image will be shown automatically in for example the F-Droid client app. An example on how to do this is found at https://github.com/y20k/transistor/tree/master/metadata/en-US

PS Please, use screenshots without a mobile device frame around it. Simply the screen shot as is.

**Comment by Viish** [comment]
Sorry but we won't do that.

**Comment by PanderMusubi** [comment]
Any reason why not? There is no extra work when doing releases. I can create a metadata directory with these files for you in a PR. This will add a much better showcase in F-Droid website and F-Droid app. Perhaps @IzzySoft has some more compelling words.

**Comment by IzzySoft** [comment]
I might offer a compelling link: [Fastlane file structure](https://gitlab.com/snippets/1895688). And I fully agree with Pander here, @Viish – that would be a great help to better "show-case" Linphone. As the saying goes, "a picture speaks louder…" etc. Potential users are much more likely to give an app a try if that apps comes with a well formatted informative description *and* screenshots. Using Fastlane (or [Triple-T file structure](https://gitlab.com/snippets/1901490) if Fastlane cannot be used for some reason), you'd have it in your own hands what is shown and what not, can update it anytime by yourselves, etc.
