### ISSUE TITLE
Setting "kill_service_with_task_manager"=false does not have any effect on Android Oreo. Android 8 prevents Linphone REGISTER messages when screen is off. 

### ISSUE THREAD

**Issue by becklo** [BelledonneCommunications/linphone-android#937]
Setting "kill_service_with_task_manager"=false does not have any effect on Android Oreo. Android 8 prevents Linphone REGISTER messages when screen is off. The standby scenario is as following:
1. Once I make screen OFF, Linphone keep sending REGISTER messages during the first 1 hour (every 10 min when reg_expire=600). 
2. After first 1 hr the following message is being sent ca. 60 mins after.
3. After the 2hrs the following messages are sent every 6 hours.
4. Once I make screen ON, REGISTER is sent immediately.
5. When the phone is charging the REGISTER messages are sent every 10 mins no matter if the screen is ON or OFF.

_Originally posted by @czaviar in https://github.com/BelledonneCommunications/linphone-android/issues/55#issuecomment-392442105_

See https://developer.android.com/guide/topics/connectivity/wifi-scan#wifi-scan-throttling

Is it now impossible to keep application and accessing the network when it is not currently interacting with the user ?

**Comment by Viish** [comment]
You can if you use a Service with a foreground notification.

**Comment by becklo** [comment]
Thanks for your answer. I am indeed already using a Service with a foreground notification. 

Note that I am using here directly the linphone code.
Indeed I have in the onStartCommand() function in LinphoneService.java that does 

`
if (LinphonePreferences.instance().getServiceNotificationVisibility()
        || (Version.sdkAboveOrEqual(Version.API26_O_80)
                && intent != null
                && intent.getBooleanExtra("ForceStartForeground", false))) {
    Log.i("[Service] Background service mode enabled, displaying notification");
    // We need to call this asap after the Service can be accessed through it's singleton
    LinphoneContext.instance().getNotificationManager().startForeground();
}
`

Which call this function 
`public void startForeground() {
    if (LinphoneService.isReady()) {
        Log.i("[Notifications Manager] Starting Service as foreground");
        LinphoneService.instance().startForeground(SERVICE_NOTIF_ID, mServiceNotification);
        mCurrentForegroundServiceNotification = SERVICE_NOTIF_ID;
    }
}`

And in the logs I do see a message which state that the service is started as foreground. Then when I open another application apparently my application enters a background mode.  

> <<< log_count = 21 >>>
> [04-01 15:11:24.502 22913:22913 I/My-App]
> [Service] Created
> 
> [04-01 15:11:24.506 22913:22913 I/My-App]
> [Service] Background service mode enabled, displaying notification
> 
> [04-01 15:11:24.506 22913:22913 I/My-App]
> [Notifications Manager] Starting Service as foreground
> 
> [04-01 15:11:24.940 22913:22913 I/My-App]
> [Service] Started
> 
> [04-01 15:11:25.030 22913:22913 I/My-App]
> [Notifications Manager] Starting Service as foreground
> 
> [04-01 15:11:25.114 22913:22913 I/My-App]
> [Activity Monitor] Activity paused:org.linphone.activities.LinphoneLauncherActivity@b642d
> 
> [04-01 15:11:25.241 22913:22913 I/My-App]
> [Activity Monitor] Activity created:org.linphone.dialer.DialerActivity@3db1dae
> 
> [04-01 15:11:25.492 22913:22913 I/My-App]
> Activity started:org.linphone.dialer.DialerActivity@3db1dae
> 
> [04-01 15:11:25.516 22913:22913 I/My-App]
> [Activity Monitor] Activity resumed:org.linphone.dialer.DialerActivity@3db1dae
> 
> [04-01 15:11:25.516 22913:22913 I/My-App]
> [Activity Monitor] runningActivities=1
> 
> [04-01 15:11:25.516 22913:22913 I/My-App]
> [Activity Monitor] App has left background mode
> 
> [04-01 15:11:25.559 22913:22913 I/My-App]
> [Activity Monitor] Activity paused:org.linphone.dialer.DialerActivity@3db1dae
> 
> [04-01 15:11:25.559 22913:22913 I/My-App]
> [Activity Monitor] runningActivities=0
> 
> [04-01 15:11:25.850 22913:22913 I/My-App]
> [Activity Monitor] Activity resumed:org.linphone.dialer.DialerActivity@3db1dae
> 
> [04-01 15:11:25.850 22913:22913 I/My-App]
> [Activity Monitor] runningActivities=1
> 
> [04-01 15:11:26.065 22913:22913 I/My-App]
> [Activity Monitor] Activity stopped:org.linphone.activities.LinphoneLauncherActivity@b642d
> 
> [04-01 15:11:26.067 22913:22913 I/My-App]
> [Activity Monitor] Activity destroyed:org.linphone.activities.LinphoneLauncherActivity@b642d
> 
> [04-01 15:11:32.363 22913:22913 I/Elu-VoIP]
> [Activity Monitor] Activity paused:org.linphone.dialer.DialerActivity@3db1dae
> 
> [04-01 15:11:32.363 22913:22913 I/My-App]
> [Activity Monitor] runningActivities=0
> 
> [04-01 15:11:32.417 22913:22913 I/My-App]
> [Activity Monitor] Activity stopped:org.linphone.dialer.DialerActivity@3db1dae
> 
> [04-01 15:11:34.364 22913:22913 I/My-App]
> [Activity Monitor] App has entered background mode
