### ISSUE TITLE
Unable to make successful video calls

### ISSUE THREAD

**Issue by nzkar** [BelledonneCommunications/linphone-android#938]
Hi, I'm using linphone-android downloaded from Google Play. If I register two phones to sip.linphone.org, they can make successful video calls. However if I register them to my own sip server, the call is initiated but the devices cannot send audio/video to each other. When I captured their pcap with Wireshark, I see that inside sip message "Invite", sdp's connection ip is send as local ip even though my phone is not in the local network and it registers with its nat ip. And when I disable video and only make an audio call, the sdp's connection ip is send as real ip. Can you explain the reason behind this? Probably this is the reason why I cannot make successful video calls. Audio and video cannot be transferred to the real ip.

**Comment by Viish** [comment]
Hi,
Please open this ticket on linphone-sdk or liblinphone project.
Thanks.

**Comment by nzkar** [comment]
Hi, I opened the same ticket to both linphone-sdk and liblinphone projects however noone is replying. Since this issue effects the linphone-android version, can you connect with the developers on the sdk-side?
