### ISSUE TITLE
text threading seems broken.

### ISSUE THREAD

**Issue by LargePrime** [BelledonneCommunications/linphone-android#939]
Each new text shows a new person on the left side.

I would expect each text to be threaded with the prior conversations

please advise

**Comment by Viish** [comment]
Please attach some screenshot showing the issue

**Comment by LargePrime** [comment]
![edit](https://user-images.githubusercontent.com/3808065/76575355-1b011700-647c-11ea-8894-a04c314fe2ae.png)
the 3 black circles are text messages from and to the same person.

**Comment by Viish** [comment]
I guess you are using a SIP server which is an asterisk, am I right?
Please check this isn't a duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/605.
If not, please attach full library logs.
