### ISSUE TITLE
There are no notifications of an incoming call on the locked screen

### ISSUE THREAD

**Issue by cowanmax** [BelledonneCommunications/linphone-android#942]
Android 6.0.1 (Xiaomi Redmi Note 3 Pro) and Android 6.0.1 on a Xiaomi Redmi 4A.
The phones rings, but I need to unlock the screen for an answer. The situation is the same for two phones (one has a PIN code).
All permissions are set.
Linphone 4.2.3 reliase, SDK 4.3.3.

**Comment by Viish** [comment]
Take a look at this: https://stackoverflow.com/questions/52518910/xiaomi-device-does-not-dismiss-lockscreen-when-opening-activity-from-background

**Comment by cowanmax** [comment]
I have reinstalled app then checked and unchecked box to give it permission to access Lockscreen. Works well..
