### ISSUE TITLE
Fatal signal  fault addr 0x0 on receive call

### ISSUE THREAD

**Issue by linuxerigor** [BelledonneCommunications/linphone-android#943]
**A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 25090 (ipfoneapp.debug), pid 25090 (ipfoneapp.debug)**

part of debug code:

25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: channel [0x7058e3c180]: starting recv background task with id=[461a].
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: channel [0x7058e3c180]: received [1159] new bytes from [TLS://voip.mls.com.br:5061]:
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: INVITE sip:231234@201.17.66.52:12411;transport=tls SIP/2.0
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: Record-Route: <sip:200.152.127.2:5061;transport=tls;r2=on;lr=on;ftag=as156b1392;nat=yes;did=b6f.90e1ae92>
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: Record-Route: <sip:200.152.127.2;r2=on;lr=on;ftag=as156b1392;nat=yes;did=b6f.90e1ae92>
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: Via: SIP/2.0/TLS 200.152.127.2:5061;branch=z9hG4bK1e0b.e7311893.0
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: Via: SIP/2.0/UDP 200.152.127.2:5066;received=200.152.127.2;branch=z9hG4bK00ee4ac3;rport=5066
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: Max-Forwards: 70
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: From: "21981214140" <sip:21981214140@4004.mls.com.br>;tag=as156b1392
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: To: <sip:552139235944@200.152.127.2>
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: Contact: <sip:21981214140@200.152.127.2:5066>
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: Call-ID: 0e5ea04f3c2dba931d673df0287b035e@4004.mls.com.br
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: CSeq: 102 INVITE
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: User-Agent: MLS sip server
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: Date: Sun, 15 Mar 2020 15:41:33 GMT
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: Supported: replaces, timer
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: Content-Type: application/sdp
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: Content-Length: 272
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: v=0
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: o=root 172380172 172380172 IN IP4 200.152.127.2
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: s=MLS sip server
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: c=IN IP4 200.152.127.2
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: t=0 0
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: m=audio 56974 RTP/AVP 8 0 101
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: a=rtpmap:8 PCMA/8000
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: a=rtpmap:0 PCMU/8000
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: a=rtpmap:101 telephone-event/8000
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: a=fmtp:101 0-16
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: a=ptime:20
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: a=sendrecv
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: a=nortpproxy:yes
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: channel [0x7058e3c180] [887] bytes parsed
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: channel [0x7058e3c180] read [272] bytes of body from [voip.mls.com.br:5061]
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: bellesip_wake_lock_acquire(): Android wake lock [belle-sip transaction(0x7056562a40)] acquired [ref=0x4596]
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: bellesip_wake_lock_acquire(): cast long of wakelock 17814
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: transaction [0x7056562a40]: starting transaction background task with id=[4596].
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: Changing [server] [INVITE] transaction [0x7056562a40], from state [INIT] to [PROCEEDING]
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: channel [0x7058e3c180]: message sent to [TLS://voip.mls.com.br:5061], size: [385] bytes
    SIP/2.0 100 Trying
    Via: SIP/2.0/TLS 200.152.127.2:5061;branch=z9hG4bK1e0b.e7311893.0
    Via: SIP/2.0/UDP 200.152.127.2:5066;received=200.152.127.2;branch=z9hG4bK00ee4ac3;rport=5066
    From: "21981214140" <sip:21981214140@4004.mls.com.br>;tag=as156b1392
    To: sip:552139235944@200.152.127.2
    Call-ID: 0e5ea04f3c2dba931d673df0287b035e@4004.mls.com.br
    CSeq: 102 INVITE
    Content-Length: 0
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: New server dialog [0x705628d200] , local tag [0~WGMYj], remote tag [as156b1392]
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: op [0x7058ccb180] : set_or_update_dialog() current=[0x0] new=[0x705628d200]
25090-25090/br.com.mls.wipfoneapp.debug I/Linphone: New incoming call from ["21981214140" <sip:21981214140@4004.mls.com.br>] to [sip:552139235944@200.152.127.2]
25090-25090/br.com.mls.wipfoneapp.debug W/ipfoneapp.debu: 0xebadde09 skipped times: 0
    
    --------- beginning of crash
25090-25090/br.com.mls.wipfoneapp.debug A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 25090 (ipfoneapp.debug), pid 25090 (ipfoneapp.debug)
25667-25667/? E/crash_dump64: unknown process state: t
25667-25667/? I/crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
1255-1255/? I//system/bin/tombstoned: received crash request for pid 25090
25667-25667/? I/crash_dump64: performing dump of process 25090 (target tid = 25090)
25667-25667/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
25667-25667/? A/DEBUG: Build fingerprint: 'samsung/crownqltezh/crownqltechn:10/QP1A.190711.020/N9600ZHU4DTB2:user/release-keys'
25667-25667/? A/DEBUG: Revision: '11'
25667-25667/? A/DEBUG: ABI: 'arm64'
25667-25667/? A/DEBUG: Timestamp: 2020-03-15 13:14:35-0300
25667-25667/? A/DEBUG: pid: 25090, tid: 25090, name: ipfoneapp.debug  >>> br.com.mls.wipfoneapp.debug <<<
25667-25667/? A/DEBUG: uid: 10652
25667-25667/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
25667-25667/? A/DEBUG: Cause: null pointer dereference
25667-25667/? A/DEBUG:     x0  0000000000000000  x1  0000000000000032  x2  0000007057094d3c  x3  0000007057094b3c
25667-25667/? A/DEBUG:     x4  0000000000000358  x5  7325000000000000  x6  000000000080a5f3  x7  fefeff71646c6873
25667-25667/? A/DEBUG:     x8  00000000fffffff0  x9  000000714db489fd  x10 0000000000000043  x11 0000000000000063
25667-25667/? A/DEBUG:     x12 000000004589e590  x13 6f632e736c6d2e34  x14 000000714db42700  x15 0000000000000000
25667-25667/? A/DEBUG:     x16 00000070574e6fd0  x17 0000007056d59bf8  x18 0000000000000016  x19 0000000000000000
25667-25667/? A/DEBUG:     x20 0000007056562a40  x21 0000007152d3dd00  x22 0000007ffd27d098  x23 0000000000000000
25667-25667/? A/DEBUG:     x24 0000007ffd27cf61  x25 0000000000000000  x26 0000000000000030  x27 0000007152e7c020
25667-25667/? A/DEBUG:     x28 0000007152e7c020  x29 0000007ffd27cef0
25667-25667/? A/DEBUG:     sp  0000007ffd27cee0  lr  0000007056d4f15c  pc  0000007056d59c04
1462-2040/? D/TelephonyManager: getAllCellInfo : Caller (PID / UID / TID): 1462 / 1000 / 2040
1293-2104/? D/bauth_FPBAuthService: pcf : 0x1012, 0 ,2 ,0 ,0 ,0 ,2, 5.0.0.0
1293-2104/? D/bauth_FPBAuthService: thread id : 2, preenroll_flag : 0, nd cnt : 1, cso : 0, et : 0
1293-2104/? D/bauth_FPBAuthService: FPBAuthService, 10979
25667-25667/? A/DEBUG: backtrace:
25667-25667/? A/DEBUG:       #00 pc 0000000000774c04  /data/app/br.com.mls.wipfoneapp.debug-ATYstRiXjMvs-kjCBZjXOw==/lib/arm64/liblinphone.so (_belle_sip_object_is_instance_of+12) (BuildId: 62e2ce54d0175c1e361b3346232aff2e91243638)
25667-25667/? A/DEBUG:       #01 pc 000000000076a158  /data/app/br.com.mls.wipfoneapp.debug-ATYstRiXjMvs-kjCBZjXOw==/lib/arm64/liblinphone.so (belle_sip_header_get_unparsed_value+20) (BuildId: 62e2ce54d0175c1e361b3346232aff2e91243638)
25667-25667/? A/DEBUG:       #02 pc 000000000061d120  /data/app/br.com.mls.wipfoneapp.debug-ATYstRiXjMvs-kjCBZjXOw==/lib/arm64/liblinphone.so (LinphonePrivate::SalCallOp::processRequestEventCb(void*, belle_sip_request_event const*)+2308) (BuildId: 62e2ce54d0175c1e361b3346232aff2e91243638)
25667-25667/? A/DEBUG:       #03 pc 000000000062c4a4  /data/app/br.com.mls.wipfoneapp.debug-ATYstRiXjMvs-kjCBZjXOw==/lib/arm64/liblinphone.so (LinphonePrivate::Sal::processRequestEventCb(void*, belle_sip_request_event const*)+3756) (BuildId: 62e2ce54d0175c1e361b3346232aff2e91243638)
25667-25667/? A/DEBUG:       #04 pc 0000000000798528  /data/app/br.com.mls.wipfoneapp.debug-ATYstRiXjMvs-kjCBZjXOw==/lib/arm64/liblinphone.so (belle_sip_provider_dispatch_message+1676) (BuildId: 62e2ce54d0175c1e361b3346232aff2e91243638)
25667-25667/? A/DEBUG:       #05 pc 0000000000780178  /data/app/br.com.mls.wipfoneapp.debug-ATYstRiXjMvs-kjCBZjXOw==/lib/arm64/liblinphone.so (BuildId: 62e2ce54d0175c1e361b3346232aff2e91243638)
25667-25667/? A/DEBUG:       #06 pc 000000000077e6f8  /data/app/br.com.mls.wipfoneapp.debug-ATYstRiXjMvs-kjCBZjXOw==/lib/arm64/liblinphone.so (belle_sip_channel_process_data+344) (BuildId: 62e2ce54d0175c1e361b3346232aff2e91243638)
25667-25667/? A/DEBUG:       #07 pc 00000000007a2e78  /data/app/br.com.mls.wipfoneapp.debug-ATYstRiXjMvs-kjCBZjXOw==/lib/arm64/liblinphone.so (BuildId: 62e2ce54d0175c1e361b3346232aff2e91243638)
25667-25667/? A/DEBUG:       #08 pc 0000000000774780  /data/app/br.com.mls.wipfoneapp.debug-ATYstRiXjMvs-kjCBZjXOw==/lib/arm64/liblinphone.so (belle_sip_main_loop_run+876) (BuildId: 62e2ce54d0175c1e361b3346232aff2e91243638)
25667-25667/? A/DEBUG:       #09 pc 0000000000774a04  /data/app/br.com.mls.wipfoneapp.debug-ATYstRiXjMvs-kjCBZjXOw==/lib/arm64/liblinphone.so (belle_sip_main_loop_sleep+72) (BuildId: 62e2ce54d0175c1e361b3346232aff2e91243638)
25667-25667/? A/DEBUG:       #10 pc 00000000006f2128  /data/app/br.com.mls.wipfoneapp.debug-ATYstRiXjMvs-kjCBZjXOw==/lib/arm64/liblinphone.so (linphone_core_iterate+408) (BuildId: 62e2ce54d0175c1e361b3346232aff2e91243638)
25667-25667/? A/DEBUG:       #11 pc 00000000000493e4  /data/app/br.com.mls.wipfoneapp.debug-ATYstRiXjMvs-kjCBZjXOw==/oat/arm64/base.odex (art_jni_trampoline+132)
25667-25667/? A/DEBUG:       #12 pc 0000000002040c04  /memfd:/jit-cache (deleted) (org.linphone.core.CoreImpl.iterate+68)
25667-25667/? A/DEBUG:       #13 pc 0000000002041228  /memfd:/jit-cache (deleted) (org.linphone.LinphoneManager$4.run+120)
25667-25667/? A/DEBUG:       #14 pc 0000000002042064  /memfd:/jit-cache (deleted) (android.os.Handler.handleCallback+68)
25667-25667/? A/DEBUG:       #15 pc 0000000002042110  /memfd:/jit-cache (deleted) (android.os.Handler.dispatchMessage+64)
25667-25667/? A/DEBUG:       #16 pc 0000000002040430  /memfd:/jit-cache (deleted) (android.os.Looper.loop+1216)
25667-25667/? A/DEBUG:       #17 pc 000000000013763c  /apex/com.android.runtime/lib64/libart.so (art_quick_osr_stub+60) (BuildId: 8b778220783a67320d6362a29443c221)
25667-25667/? A/DEBUG:       #18 pc 00000000003386f4  /apex/com.android.runtime/lib64/libart.so (art::jit::Jit::MaybeDoOnStackReplacement(art::Thread*, art::ArtMethod*, unsigned int, int, art::JValue*)+1688) (BuildId: 8b778220783a67320d6362a29443c221)
25667-25667/? A/DEBUG:       #19 pc 00000000002ebe98  /apex/com.android.runtime/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false, false>(art::interpreter::SwitchImplContext*)+13136) (BuildId: 8b778220783a67320d6362a29443c221)
25667-25667/? A/DEBUG:       #20 pc 0000000000142bd8  /apex/com.android.runtime/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 8b778220783a67320d6362a29443c221)
25667-25667/? A/DEBUG:       #21 pc 000000000039afd8  /system/framework/framework.jar (android.os.Looper.loop)
25667-25667/? A/DEBUG:       #22 pc 00000000005a49b4  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+1192) (BuildId: 8b778220783a67320d6362a29443c221)
25667-25667/? A/DEBUG:       #23 pc 0000000000131994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: 8b778220783a67320d6362a29443c221)
25667-25667/? A/DEBUG:       #24 pc 00000000001a7a30  /system/framework/framework.jar (android.app.ActivityThread.main+208)
25667-25667/? A/DEBUG:       #25 pc 00000000002b5080  /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.7038959461964381116+240) (BuildId: 8b778220783a67320d6362a29443c221)
25667-25667/? A/DEBUG:       #26 pc 0000000000593114  /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+1032) (BuildId: 8b778220783a67320d6362a29443c221)
25667-25667/? A/DEBUG:       #27 pc 0000000000140468  /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 8b778220783a67320d6362a29443c221)
25667-25667/? A/DEBUG:       #28 pc 000000000014065c  /apex/com.android.runtime/lib64/libart.so (art_quick_instrumentation_entry+252) (BuildId: 8b778220783a67320d6362a29443c221)
25667-25667/? A/DEBUG:       #29 pc 00000000007fb4ac  [stack]

**Comment by Viish** [comment]
Which version of the SDK are you using?
Can you also attach the result of cat <stacktrace> | ndk-stack -sym <path to debug symbols> ?

**Comment by Viish** [comment]
I believe it was fixed on master branch of liblinphone.
