### ISSUE TITLE
ACK timeout causes FreeSwitch to drop call after 32 seconds

### ISSUE THREAD

**Issue by S-trace** [BelledonneCommunications/linphone-android#945]
Hello. 

I have a FreeSWITCH Version 1.10.2-release-14-f7bdd3845a~64bit (-release-14-f7bdd3845a 64bit) server in the LAN (no NAT is applied between server and clients), and FreeSwitch drops a call after 32 seconds with Reason: SIP;cause=408;text="ACK Timeout"

In a pcap file captured on the server I can see 11 "200 OK" messages from the server to the phone, and then call is dropped.
I'm using TCP transport, so there is no packet loss.

A pcap file with SIP traffic captured on the server is attached below.
The problem is present on the Google Play's version and on a self-built version based on tag 4.2 (commit 9a28a6273a92569c4bfb05995c93048034681509 )

Could you please check this and fix linphone for android?
This problem is definitely with linphone for android, because zoiper-zoiper calls do not drop in 32 seconds with same setup.
[linphone_sip.pcap.zip](https://github.com/BelledonneCommunications/linphone-android/files/4343533/linphone_sip.pcap.zip)

Thank you.

**Comment by Viish** [comment]
Can you attach library logs please?

**Comment by Viish** [comment]
Closed until asked information will be provided.
