### ISSUE TITLE
Call reached incorrect person

### ISSUE THREAD

**Issue by chih87s** [BelledonneCommunications/linphone-android#949]
For example, I have three different users. User A uses sip extension 100, User B use sip extension 200. The user B logout firstly. And then user C login with sip extension 200.  The user B login with sip extension 300. If the user A call user C (200) but the user B (300) received this call.  How does it happened? Anyone knows why it happened?

**Comment by Viish** [comment]
When you say B log outs, what do you mean? How do you do it?

**Comment by Viish** [comment]
Closed until asked information will be provided.
