### ISSUE TITLE
Build arm error

### ISSUE THREAD

**Issue by Errrorr** [BelledonneCommunications/linphone-android#95]
I build linphone with ./prepare.py -ac arm. 
But show the following error:
linphone-android/submodules/mediastreamer2/src/android/androidsound_opensles.cpp:927:12: error: 'int bytes_to_ms(OpenSLESOutputContext*, int)' defined but not used [-Werror=unused-function]
 static int bytes_to_ms(OpenSLESOutputContext *octx, int bytes){
            ^
cc1plus: error: unrecognized command line option "-Wno-format-truncation" [-Werror]
cc1plus: all warnings being treated as errors

**Comment by DatBewar** [comment]
Hello, we are trying to solve ARM build

**Comment by DatBewar** [comment]
It's normally ok now
