### ISSUE TITLE
No connected in a few hours

### ISSUE THREAD

**Issue by cowanmax** [BelledonneCommunications/linphone-android#950]
3 SIP accounts become offline in a few hours. 
The energy saving permissions are set to "Do not restricted". Android 6.0.1, Xiaomi Redmi Note 3 Pro and Redmi 4A. MIUI 10.
Expires set to 90, and I have set a "lock" for app. Any ideas?

**Comment by Viish** [comment]
I don't understand what your issue is.

**Comment by cowanmax** [comment]
I mean that after a few hours all SIP accounts becomes offline. And that I have set the power saving mode to "Do not restricted".

**Comment by Viish** [comment]
Did you enable the "background mode" setting in advanced section of preferences?
90 for expire is quite low, as soon as the app will be killed (if background mode is disabled), your account will be considered logged out by your server.

**Comment by Viish** [comment]
3600 is quite a short expire. 
On Android it is difficult to ensure the app is always running, that's why the best solution is to use push notification.

And please don't open new tickets, we can continue the discussion here.

**Comment by cowanmax** [comment]
Sorry, I just see that ticket was closed.

Do I need to switch on PUSH notification in settings?

**Comment by Viish** [comment]
That depends on your server. If your server supports push notifications and that you have rebuilt our app to embed your push configuration, then yes. Otherwise it won't help you.

**Comment by cowanmax** [comment]
Unfortunately no. I'm happy with your application. But this is a big problem (( Zoiper works good, but it does not have a video. I would like to believe that in the new version this will be fixed. I would even like to contribute to the development if possible.

 

 

 

 

Best regards,

Max.
