### ISSUE TITLE
Delete unused devices

### ISSUE THREAD

**Issue by goduck777** [BelledonneCommunications/linphone-android#952]
I am trying to send E2E message to a contact. Both of us have the latest linphone installed, with sip.linphone.org account. However, the option of sending the E2E message is always greyed.

After some more trying, I think this is due to the fact that bot of us have linphone uninstalled and reinstalled before, so there are multiple devices linked to the account (though those "devices" are just obsolete installations). I wonder if there is a way to remove those unused devices from my account.

**Comment by Viish** [comment]
We are in the process of publishing such feature in our freesip webpage.

**Comment by goduck777** [comment]
I see. I find that I can establish E2E chat today. But I couldn't get "2 starts" badge. I will wait for the new feature.

**Comment by Viish** [comment]
Ghost devices are also deleted after 1 year :)
