### ISSUE TITLE
Cannot link phone number previously used

### ISSUE THREAD

**Issue by goduck777** [BelledonneCommunications/linphone-android#953]
I want to link my sip.linphone.org account with my phone number. My phone number has been previously used to create another linphone account, so I logged into that account and deleted it. However, now I got an "Unknown Error" when trying to link account with this phone number.

**Comment by Viish** [comment]
What's your phone number ? I'll check the database.

**Comment by goduck777** [comment]
I don't want to post it on web. Can I send you a private message through linphone?

**Comment by Viish** [comment]
You can send it to linphone-android@belledonne-communications.com

**Comment by Viish** [comment]
I received your email.
Can you try again now please?

**Comment by goduck777** [comment]
It still says "Unknow Error".

**Comment by goduck777** [comment]
I think there may be some problems with my account. I tried other numbers and always get "Unknown error".

**Comment by Viish** [comment]
Can you attach the logs from the library ?

**Comment by goduck777** [comment]
Error message is like

2020-03-23 09:48:50:989 [belle-sip] ERROR stream connect failed Network is unreachable
2020-03-23 09:48:50:989 [belle-sip] ERROR Cannot connect to [TLS://subscribe.linphone.org:444]
2020-03-23 09:48:51:996 [linphone-android] ERROR [Phone Account Linking Assistant] linkAccount returned MissingArguments
2020-03-23 09:48:56:733 [linphone-android] ERROR [Phone Account Linking Assistant] linkAccount returned MissingArguments

**Comment by Viish** [comment]
Can you attach the full logs please?
It isn't expected to have the MissingArgs, but the reason why should be also in the logs.

**Comment by goduck777** [comment]
Here is the logo file in app data directory. Is there another log file that contains more info?

**Comment by Viish** [comment]
Actually you have to first enable debug logs (in advanced section of preferences).
Then restart the app, reproduce the issue, go into about fragment & click on upload log button to finally copy/paste the link here please.

**Comment by goduck777** [comment]
Ah I didn't know this trick. Here is the log url.

https://www.linphone.org:444//tmp/5e7a0b69e24fb_4f5cce803a921cf02c19.gz

Please check the end to see the error message from subscribe.linphone.org

**Comment by Viish** [comment]
It's an issue with the app, I just commited a fix for it.
Thanks for reporting it.
