### ISSUE TITLE
[Question] - How can I unregister sip from another Android phone

### ISSUE THREAD

**Issue by showgoodjiang** [BelledonneCommunications/linphone-android#954]
For the same sip account, I registered sip from Android phone A （using linphone-android sdk);  
Then, how can I unregister the same sip account from another Android phone B （using linphone-android sdk) without registration?
( In this case, DefaultProxyConfig is null, and ProxyConfigList are null on Android phone B).

**Comment by Viish** [comment]
On your B phone, on the proxy config, call edit() then enableRegister(false) then done() to unregister.

**Comment by showgoodjiang** [comment]
@Viish Thank you.

If I register sip on B, then I can unregister sip from server.

The case is:
The sip was registered by phone A;
On phone B, I haven't register SIP, so there is no proxy config yet. 
What I want: unregister sip from server on phone B directly, without registration.

**Comment by Viish** [comment]
If I understand correctly, you want to unregister A from B ?

**Comment by showgoodjiang** [comment]
Yes. For B, not registered, so there is no proxy config. Using the same sip account.

**Comment by Viish** [comment]
You can't unregister if you aren't registered first.

**Comment by showgoodjiang** [comment]
Viish,  got it. Thanks a lot.

**Comment by Irfanulhaq1991** [comment]
To register/unregister, I am adding/clearingAccounts which causing null pointer dereference issue . I came across this answer and found suitable for my case but the `proxyConfig `is deprecated now indicating to use Account instead.  How could your first comment be achieved with `Account Object `.

**Comment by Viish** [comment]
> How could your first comment be achieved with Account Object .

See the API reference:
https://download.linphone.org/releases/docs/liblinphone/5.0/java/org/linphone/core/AccountParams.html#setRegisterEnabled-boolean-

Or the Account tutorial:
https://gitlab.linphone.org/BC/public/tutorials/-/tree/master/android/kotlin/1-AccountLogin
