### ISSUE TITLE
Doesn't authenticate after 401 REGISTER response

### ISSUE THREAD

**Issue by stekkari** [BelledonneCommunications/linphone-android#955]
Probably same issue as unsolved, but closed #801.

Everything works fine with Linphone 4.1.1 using remote configuration.
(Linphone sends REGISTER -request with auth-info to proxy successfully).

But releases after that (4.2, 4.3) behaves differently.

First time when account is added (using remote configuration) register-flow works as intended.
1. Send REGISTER
2. Receive 401 Unauhorized (with WWW-authenticate Digest)
3. Send Register, with Authorization Digest
4. Receive Status 200 OK.

But after phone reboot / app restart / app killed etc.:
1. Send REGISTER
2. Receive 401 Unauhorized (with WWW-authenticate Digest)

Packet 1 and 2 is identical to successful flow, but packet 3 with Authorization is never sent by Linphone. So register fails officiously.

--------------

On both cases on new version, and on 4.1.1 configuration includes correct proxy and auth info,
checked from linphonerc.

Difference with linephonerc between versions is:

4.1.1 has following extra fields on proxy
contact_uri_parameters=<firebase related params>
quality_reporting_enabled=0
quality_reporting_interval=0
avpf_rr_interval=1
privacy=32768

linphonerc difference on 4.3 with success / failure cases:

Success:
auth_info_0 without passwd field.

Failure:
auth_info_0 contains passwd field.

**Comment by Viish** [comment]
Please open this ticket in liblinphone repository as it doesn't concern the Android app specifically.
