### ISSUE TITLE
setAudioDscp

### ISSUE THREAD

**Issue by mutengchen** [BelledonneCommunications/linphone-android#956]
i need to set dscp value to 0xb8,but no matter what value I set, the server receives 0x00.

LinphoneService.getCore().setAudioDscp(184) ;
LinphoneService.getCore().setAudioDscp(0xb8) ;

both of them we try it.but failed.

**Comment by Viish** [comment]
Please open this ticket in liblinphone repository as it doesn't concern the Android app specifically.

**Comment by mutengchen** [comment]
I need to use qos, and then set dscp value, but I use wireshark to grab the packet, it seems that setSipDscp method does not work
![image](https://user-images.githubusercontent.com/39668052/83318113-35b97f80-a264-11ea-8feb-494f5447360f.png)
