### ISSUE TITLE
Crash on launch app on different network 

### ISSUE THREAD

**Issue by linuxerigor** [BelledonneCommunications/linphone-android#959]
Opening the app when the network is different

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> br.com.mls.wipfoneapp <<<

backtrace:
  #00  pc 000000000001e7b4  /system/lib64/libc.so (strchr+112)
  #01  pc 00000000006fb510  /data/app/br.com.mls.wipfoneapp-41CTHVujULGknqYalLBg9Q==/split_config.arm64_v8a.apk (offset 0x1d1000)
  #02  pc 0000000000776418  /data/app/br.com.mls.wipfoneapp-41CTHVujULGknqYalLBg9Q==/split_config.arm64_v8a.apk (offset 0x1d1000)
  #03  pc 00000000007623c8  /data/app/br.com.mls.wipfoneapp-41CTHVujULGknqYalLBg9Q==/split_config.arm64_v8a.apk (offset 0x1d1000)
  #04  pc 0000000000760948  /data/app/br.com.mls.wipfoneapp-41CTHVujULGknqYalLBg9Q==/split_config.arm64_v8a.apk (offset 0x1d1000) (belle_sip_channel_process_data+344)
  #05  pc 00000000007823d8  /data/app/br.com.mls.wipfoneapp-41CTHVujULGknqYalLBg9Q==/split_config.arm64_v8a.apk (offset 0x1d1000)
  #06  pc 00000000007569d0  /data/app/br.com.mls.wipfoneapp-41CTHVujULGknqYalLBg9Q==/split_config.arm64_v8a.apk (offset 0x1d1000) (belle_sip_main_loop_run+876)
  #07  pc 0000000000756c54  /data/app/br.com.mls.wipfoneapp-41CTHVujULGknqYalLBg9Q==/split_config.arm64_v8a.apk (offset 0x1d1000) (belle_sip_main_loop_sleep+72)
  #08  pc 00000000006d74f4  /data/app/br.com.mls.wipfoneapp-41CTHVujULGknqYalLBg9Q==/split_config.arm64_v8a.apk (offset 0x1d1000) (linphone_core_iterate+552)
  #09  pc 00000000000123d4  /data/app/br.com.mls.wipfoneapp-41CTHVujULGknqYalLBg9Q==/oat/arm64/base.odex (offset 0x11000) (org.linphone.core.AccountCreatorImpl.reset [DEDUPED]+132)
  #10  pc 0000000000557388  /system/lib64/libart.so (art_quick_invoke_stub+584)
  #11  pc 00000000000cfcc8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
  #12  pc 0000000000280338  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
  #13  pc 000000000027a34c  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+968)
  #14  pc 0000000000527808  /system/lib64/libart.so (MterpInvokeDirect+296)
  #15  pc 0000000000549a94  /system/lib64/libart.so (ExecuteMterpImpl+14484)
  #16  pc 000000000014b926  /data/app/br.com.mls.wipfoneapp-41CTHVujULGknqYalLBg9Q==/oat/arm64/base.vdex (org.linphone.core.CoreImpl.iterate+6)
  #17  pc 0000000000254050  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.3557229793)+488)
  #18  pc 0000000000259b44  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
  #19  pc 000000000027a330  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
  #20  pc 0000000000527444  /system/lib64/libart.so (MterpInvokeInterface+1392)
  #21  pc 0000000000549b94  /system/lib64/libart.so (ExecuteMterpImpl+14740)
  #22  pc 000000000011c31a  /data/app/br.com.mls.wipfoneapp-41CTHVujULGknqYalLBg9Q==/oat/arm64/base.vdex (c.a.b$d.run+28)
  #23  pc 0000000000254050  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.3557229793)+488)
  #24  pc 0000000000516d7c  /system/lib64/libart.so (artQuickToInterpreterBridge+1020)
  #25  pc 00000000005604fc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
  #26  pc 000000000179b27c  /system/framework/arm64/boot-framework.oat (offset 0xa43000) (android.os.Handler.dispatchMessage+76)
  #27  pc 0000000001f7d758  /system/framework/arm64/boot-framework.oat (offset 0xa43000) (android.os.Looper.loop+1304)
  #28  pc 0000000000f27688  /system/framework/arm64/boot-framework.oat (offset 0xa43000) (android.app.ActivityThread.main+664)
  #29  pc 000000000055764c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
  #30  pc 00000000000cfce8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
  #31  pc 000000000045dd7c  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
  #32  pc 000000000045f7d0  /system/lib64/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1440)
  #33  pc 00000000003ef398  /system/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52)
  #34  pc 000000000078eed4  /system/framework/arm64/boot-core-oj.oat (offset 0x2dc000) (java.lang.Class.getDeclaredMethodInternal [DEDUPED]+180)
  #35  pc 000000000247c558  /system/framework/arm64/boot-framework.oat (offset 0xa43000) (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+136)
  #36  pc 00000000024888f8  /system/framework/arm64/boot-framework.oat (offset 0xa43000) (com.android.internal.os.ZygoteInit.main+2104)
  #37  pc 000000000055764c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
  #38  pc 00000000000cfce8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
  #39  pc 000000000045dd7c  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
  #40  pc 000000000045d9dc  /system/lib64/libart.so (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+424)
  #41  pc 0000000000362cd8  /system/lib64/libart.so (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+652)
  #42  pc 00000000000b2b74  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+116)
  #43  pc 00000000000b5710  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+924)
  #44  pc 0000000000002528  /system/bin/app_process64 (main+2012)
  #45  pc 00000000000c9270  /system/lib64/libc.so (__libc_init+88)

**Comment by Viish** [comment]
Hi,
Please attach the stacktrace with debug symbols (by using the debug libraries) and with the logs from before the crash.
Thanks.

**Comment by Viish** [comment]
Closed until asked information will be provided.
