### ISSUE TITLE
Connected Line functionality

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-android#96]
Hi,

Would it be possible to integrate some "Connected Line" functionality after setting up a call, so the display is updated with the name of the callee?

Asterisk is sending 2 parameters with could be interpreted:
P-Asserted-Identity: "NAME" <sip:EXT@SERVER>
Remote-Party-ID: "NAME" <sip:EXT@SERVER>;privacy=off;screen=no

**Comment by DatBewar** [comment]
Hello,
It could be, but not directly in Linphone-Android but in [LibLinphone](https://github.com/BelledonneCommunications/linphone)
