### ISSUE TITLE
Linphone crashes when network connection is lost.

### ISSUE THREAD

**Issue by liliangeorg** [BelledonneCommunications/linphone-android#961]
I use Linphone library for an application in order to exchange some information with a SIP server. Everything works fine, registration of the user is executed properly on the SIP server and messages (between SIP server and the app) are exchanged as they should. However when the device loses connection to the network (mobile data and Wi-Fi), the application crashes with the following logs:

I/myAppLyn: Changing [client] [REGISTER] transaction [0xc8574720], from state [COMPLETED] to [TERMINATED]
Client internal REGISTER transaction [0xc8574720] terminated
transaction [0xc8574720]: ending transaction background task with id=[2e62].
I/myAppLyn: bellesip_wake_lock_release(): Android wake lock released [ref=0x2e62]
I/27032020: No available network!
I/myAppLyn: [Platform Helper] [Network Manager 26] A network has been lost
I/myAppLyn: [Platform Helper] No connectivity: setting network unreachable
I/myAppLyn: SIP network reachability state is now [DOWN]
I/myAppLyn: Refresher [0xe17c0300] stopped.
Destroying op [0xc5160c80] of type [SalOpRegister]
Refresher [0xe17c0300] stopped.
Transaction [0xc8574720] deleted
I/myAppLyn: Transaction [0xc3cdb480] deleted
E/myAppLyn: Object [0xc3e0ad00] freed twice or corrupted !
Object type might be [belle_sip_header_address_t]
A/myAppLyn: Fatal object error encountered, aborting.
A/: Aborting
A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 22455 (ndroid.myApp), pid 22455 (ndroid.myApp)
Process 22455 terminated.

Please note that crash happens only when a registration to the SIP server has been executed before. Only one registration has happened (why object freed twice?). If no registration has been preceded and app loses connection to the network, there is no problem/crash (a dialog appears to inform that there is no connection to the network)...I have checked that the Library has the OnNetworkReachable method and I have tried to manually stop the execution of the Linphone library by setting 
core.setNetworkReachable(false); 
and then again manually set it to true when connection is restored. I also tried this with the android methods for Connectivity change listeners...but the problem remains...
Shall I destroy the core and recreate it after network is reachable?
Why does it seem to have allocated two objects?
Could you please provide some advice?

Thank you in advance for your help,

**Comment by Viish** [comment]
Hi,
What version of the SDK are you using ?

**Comment by liliangeorg** [comment]
> 
> 
> Hi,
> What version of the SDK are you using ?

Hi.
29.0.6

**Comment by Viish** [comment]
No I meant of our SDK (linphone-sdk).

**Comment by liliangeorg** [comment]
> 
> 
> No I meant of our SDK (linphone-sdk).

Hello again... Sorry! It is 4.3.

**Comment by Viish** [comment]
Ok make sure you are using the 4.3.3, reproduce the issue and send full library logs please.

**Comment by irfanismaya20** [comment]
![photo_2020-04-02_15-58-42](https://user-images.githubusercontent.com/12542123/78229952-e1f81780-74fa-11ea-8eb8-1fcc0fcd19f8.jpg)

I'm running linphone from android studio but not running.
if i install from playstore running very well.
@Viish can you help me?

**Comment by Viish** [comment]
The screenshot isn't helping. Please attach logs.

**Comment by Viish** [comment]
Closed until asked information will be provided.
