### ISSUE TITLE
swap local and remote video

### ISSUE THREAD

**Issue by jamin918** [BelledonneCommunications/linphone-android#962]
When I click local preview, I want to swap the location of the local preview and remote video, similar to WeChat video call. Could you offer me some advice? Thanks a lot.  
`<RelativeLayout
        android:id="@+id/rl_video_preview"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:visibility="gone">

        <TextureView
            android:id="@+id/remote_video_texture"
            android:layout_width="match_parent"
            android:layout_height="match_parent"/>

        <org.linphone.mediastream.video.capture.CaptureTextureView
            android:id="@+id/local_preview_texture"
            android:layout_width="200dp"
            android:layout_height="200dp"
            android:layout_alignParentRight="true"
            android:layout_alignParentBottom="true"/>

    </RelativeLayout>`

**Comment by Viish** [comment]
Try to have two layouts: one with the remote full screen textureview and the small capture texture view like the one you posted and one for the other scenario.
When you want to change, switch visibility between your layouts and call Core.setNativeVideoWindowId and Core.setNativePreviewWindowId with the new surfaces.

**Comment by jamin918** [comment]
`                                                                                                              

         mLocalPreview.setOnClickListener(new View.OnClickListener() {

            @Override
            public void onClick(View v) {
                ViewGroup.LayoutParams previewParams = v.getLayoutParams();
                previewParams.width = ViewGroup.LayoutParams.MATCH_PARENT;
                previewParams.height = ViewGroup.LayoutParams.MATCH_PARENT;
                v.setLayoutParams(previewParams);
                mLocalPreview.clearFocus();

                mRemoteVideo.setFocusable(true);
                mRemoteVideo.setFocusableInTouchMode(true);
                ViewGroup.LayoutParams videoLayoutParams = mRemoteVideo.getLayoutParams();
                videoLayoutParams.width = SizeUtils.dp2px(200);
                videoLayoutParams.height = SizeUtils.dp2px(200);
                mRemoteVideo.setLayoutParams(videoLayoutParams);
                mRemoteVideo.requestFocus();
                mRemoteVideo.bringToFront();
                mRemoteVideo.requestLayout();
                mRemoteVideo.invalidate();
            }
        });

        mRemoteVideo.setOnClickListener(new View.OnClickListener() {

            @Override
            public void onClick(View v) {
                ViewGroup.LayoutParams previewParams = v.getLayoutParams();
                previewParams.width = ViewGroup.LayoutParams.MATCH_PARENT;
                previewParams.height = ViewGroup.LayoutParams.MATCH_PARENT;
                v.setLayoutParams(previewParams);
                mRemoteVideo.clearFocus();

                ViewGroup.LayoutParams videoLayoutParams = mLocalPreview.getLayoutParams();
                videoLayoutParams.width = SizeUtils.dp2px(200);
                videoLayoutParams.height = SizeUtils.dp2px(200);
                mLocalPreview.setLayoutParams(videoLayoutParams);
                mLocalPreview.requestFocus();
                mLocalPreview.bringToFront();
                mLocalPreview.requestLayout();
                mLocalPreview.invalidate();
            }
        });

`

**Comment by jamin918** [comment]
The local preview is ok, now the problem is that when the remote video layout gets smaller, the remote video content doesn't shrink.

**Comment by jamin918** [comment]
`
                                                                  
        mRemoteVideo = (TextureView) findViewById(R.id.remote_video_texture);
        mLocalPreview = (TextureView) findViewById(R.id.local_preview_texture);
        
        mLocalPreview.setOnClickListener(new View.OnClickListener() {

            @Override
            public void onClick(View v) {
                ViewGroup.LayoutParams previewParams = v.getLayoutParams();
                previewParams.width = ViewGroup.LayoutParams.MATCH_PARENT;
                previewParams.height = ViewGroup.LayoutParams.MATCH_PARENT;
                v.setLayoutParams(previewParams);
                mLocalPreview.clearFocus();

                mRemoteVideo.setFocusable(true);
                mRemoteVideo.setFocusableInTouchMode(true);
                ViewGroup.LayoutParams remoteParams = mRemoteVideo.getLayoutParams();
                remoteParams.width = SizeUtils.dp2px(200);
                remoteParams.height = SizeUtils.dp2px(200);
                mRemoteVideo.setLayoutParams(remoteParams);
                mRemoteVideo.requestFocus();
                mRemoteVideo.bringToFront();
                mRemoteVideo.requestLayout();
                mRemoteVideo.invalidate();
                
            }
        });

        mRemoteVideo.setOnClickListener(new View.OnClickListener() {

            @Override
            public void onClick(View v) {
                ViewGroup.LayoutParams remoteParams = v.getLayoutParams();
                remoteParams.width = ViewGroup.LayoutParams.MATCH_PARENT;
                remoteParams.height = ViewGroup.LayoutParams.MATCH_PARENT;
                v.setLayoutParams(remoteParams);
                mRemoteVideo.clearFocus();

                ViewGroup.LayoutParams previewParams = mLocalPreview.getLayoutParams();
                previewParams.width = SizeUtils.dp2px(200);
                previewParams.height = SizeUtils.dp2px(200);
                mLocalPreview.setLayoutParams(previewParams);
                mLocalPreview.requestFocus();
                mLocalPreview.bringToFront();
                mLocalPreview.requestLayout();
                mLocalPreview.invalidate();
            }
        });
`

**Comment by Viish** [comment]
Yes, the remote video texture view isn't made for dynamic resizing. That's why I suggested you switch the textureview instead of resizing it.

**Comment by jamin918** [comment]
Yes, I implemented this function according to your advice, Thanks a lot.  ：）

**Comment by jamin918** [comment]
> Try to have two layouts: one with the remote full screen textureview and the small capture texture view like the one you posted and one for the other scenario.
> When you want to change, switch visibility between your layouts and call Core.setNativeVideoWindowId and Core.setNativePreviewWindowId with the new surfaces.

You also need to call LinphoneManager.getCallManager().acceptCallUpdate(true);
