### ISSUE TITLE
ChatMessages are always delivered and seen   

### ISSUE THREAD

**Issue by dekanako** [BelledonneCommunications/linphone-android#963]
Hello guys I dont know why but my chatMessages are always in delivered 
and when i'm mark the chatRoom as read it doesnt notify the user

**Comment by Viish** [comment]
Hi,
Delivered means the device has received the message.
In a group chat room, the message only becames read if all participants have read it.
In case of file attached, the read is sent only after download.
If you still think you have an issue, please attach logs.
Cheers,

**Comment by dekanako** [comment]
hey thanks for helping me out,
do you have an example of how to setup read and deliver features properly in java

**Comment by Viish** [comment]
You don't have to do anything except calling markAsRead() to send the read information.

**Comment by dekanako** [comment]
ok, so this is the problem there are sometime that I haven't marked it as read in the receiver side
but when I check it with isRead() method on the sender side it returns true

**Comment by Viish** [comment]
Yes, isRead() it doesn't work like that.
To check properly, call getState() and check if the value is Displayed.

**Comment by dekanako** [comment]
hey bro please if you have an example or something could you share it with me 

so Bro I've the Receiver and the sender when I'm registering a listener on the chatMessage from the sender side I get only the delivered state I don't get the Displayed state or the DeliveredToUser state 
thank you for your time man

**Comment by Viish** [comment]
Please attach your logs
