### ISSUE TITLE
A display bug

### ISSUE THREAD

**Issue by franklinbill** [BelledonneCommunications/linphone-android#965]
Dear developer
In the process of using, I found a bug in layout / display. The top text "assistant" of the home page is blocked in the lower part, which may be an adaptation problem.
App version is 4.2.3, my mobile phone is Google nexus 6, screen resolution setting is 1440 * 2560, font size is the largest, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply. 
Thank you!
![image](https://user-images.githubusercontent.com/18572115/78764610-61815d00-79b9-11ea-8643-7d133118fd92.png)

**Comment by Viish** [comment]
Hi,
It seems to be fixed in feature/kotlin_rework so will be part of next release.
Cheers,
