### ISSUE TITLE
Prefix Issue

### ISSUE THREAD

**Issue by anujvats111** [BelledonneCommunications/linphone-android#966]
Hello ,
App is  automatically get prefix of country 
Can please tell me why and how can empty prefix value empty ?

Thanks 
Anuj

**Comment by Viish** [comment]
Hi,
In your account settings, empty the prefix field.
Cheers,

**Comment by anujvats111** [comment]
Is there any chance to stop automatic getting prefix with changing from
settings menu ?

Thanks
Anuj

**Comment by Viish** [comment]
This is done automatically when the account is set up from the assistant.
If you want to change this behaviour, you'll have to fork the app.
