### ISSUE TITLE
Media encryption issue

### ISSUE THREAD

**Issue by nzkar** [BelledonneCommunications/linphone-android#967]
Hi, one of my devices is set as "media encryption=none" and "encryption not mandatory", the other set as "media encryption=srtp" and "encryption mandatory". There are two scenarios.
1. When the "encryption disabled app" calls the "encryption mandatory app" it gives an error as expected.
2. When the "encryption mandatory app" calls the "encryption disabled app" the call is accepted with srtp.
I don't understand the idea behind this. Shouldn't the second scenario also give an error message and refuse the invite message?

**Comment by Viish** [comment]
Hi,
Encryption mandatory is a local setting that isn't propagated during a call.
So you can refuse an incoming call if it doesn't match your encryption policy.
However a device without media encryption enabled by default can still use it if requested by the caller, hence the call being encrypted when you call out.
Cheers,
