### ISSUE TITLE
Linephone doesn't use the nic eth0

### ISSUE THREAD

**Issue by sjjh** [BelledonneCommunications/linphone-android#968]
I'm using a Fairphone 2, which I attached via an USB OTG dongle to a wired network. The terminal app Connectbot shows me, that I got a (correct) IP address by the DHCP server and I can use the network as normal (eg browsing the web with Firefox). Nevertheless Linphone does not connect to the network. This is independent from toggling "use only WiFi" in the settings.

Expected behaviour is, that Linphone recognizes the wired connection on eth0 and connects to the SIP server.

**Comment by Viish** [comment]
Hi,
Please attach the library logs.

**Comment by sjjh** [comment]
I enabled debug in app preferences and used logcat to receive attqached log file. Not sure if that was what you intended @Viish -- if not please tell me what to do. :)
[log.txt](https://github.com/BelledonneCommunications/linphone-android/files/4462523/log.txt)

**Comment by Viish** [comment]
There are some traces in the file you attached but not enough.
Stop the app with the task killer and start it again. Then go in about page and click on upload logs button. Finally copy/paste the link or the file here please.

**Comment by sjjh** [comment]
> There are some traces in the file you attached but not enough.
> Then go in about page and click on upload logs button. 

The button doesn't seem to work...? where can I find the log file on the phone?

btw, recognized that I didn't mention the version: Linphone Android 4.2.1; Linphone SDK 4.3.0

**Comment by Viish** [comment]
If the button doesn't work, you can still capture the logs through adb, but take all the logs from the start of the app to the moment you have the issue.

**Comment by sjjh** [comment]
I hope using CatLog works, as I currently don't know how to reach the phone via adb from my computer while the phone is connected to the Ethernet and not to the computer via USB.
Attached the log excerpt, beginning at the start of the app:
[2020-04-12-14-34-42.txt](https://github.com/BelledonneCommunications/linphone-android/files/4466329/2020-04-12-14-34-42.txt)

**Comment by Viish** [comment]
From your logs:
```
04-12 14:34:29.868 I/Linphone(22409): [Platform Helper] [Network Manager 24] A network is available: Ethernet, wifi only is enabled
04-12 14:34:29.868 I/Linphone(22409): [Platform Helper] [Network Manager 24] Network isn't wifi and wifi only mode is enabled
```
So it seems your issue is due to WiFi Only setting being enabled.

**Comment by sjjh** [comment]
Good catch -- sorry that I didn't noticed that. I can confirm, that with WiFi Only mode disable it does work using the wired connection. But as I was sure, that it didn't worked without the WiFi Only setting either, I tried to narrow it down. It seems, that toggling the WiFi Only mode doesn't (re)enable usage of the wired connection.

Steps to reproduce:
1. enable WiFi Only mode and force kill Linphone
2. attach eth0 and start Linphone
3. go to Linphone settings and disable WiFi Only mode
  expected: Linphone establishes a connection via eth0
  actual: Linphone status stays disconnected

See attached log file, at  line 961 I toggled WiFi only mode:
04-15 10:31:33.056 I/Linphone(10370): [Platform Helper] Wifi only mode is now disabled

[2020-04-15-10-31-46.txt](https://github.com/BelledonneCommunications/linphone-android/files/4480033/2020-04-15-10-31-46.txt)

*Side node:* I believe it's worth to discuss the intention of the WiFi Only mode; what shall it do? Enable  only a connection via WiFi or prevent mobile data usage? Or in other words, how to fulfil the user story of "I don't want to use mobile data (but don't care about WiFi and/or wired connection usage).", which IMHO might be more relevant than "I *only* want to use WiFi, but not eth0 or mobile data." out of a typical users perspective. But this is for sure a different discussion, than the issue named here that deactivating WiFi Only doesn't enable eth0 usage. Shall I open another issue to discuss it further?

**Comment by Viish** [comment]
Indeed there is a flaw in our NetworkManager that says network is still unreachable after toggling off wifionly mode.
And you are right, this mode has been created to prevent data on mobile connections, it should work on ethernet too.
I'll see what I can do.

**Comment by Viish** [comment]
Ok both issues should be fixed now.
However I made the fix on a dev branch that won't be merged into master until a few days, maybe end of April.
