### ISSUE TITLE
Linphone keep asking password

### ISSUE THREAD

**Issue by MembershipExcel** [BelledonneCommunications/linphone-android#969]
Hi
If i'm trying to call a mobile device or a sub account all seem good But if i call a tol-Free number, it keep asking for password. 

Sometime it accepted, most of the time it not accepted. If a remove the username in the box but add the password there more chance it accepted. 

There no section to enter the password, only to remove all password. 

And the app in the windows store doesn't have the call recording feature, but the tol-free number issue seem to be ok .

thanks 
![image](https://user-images.githubusercontent.com/48916916/79012045-5f430e00-7b33-11ea-8109-a256d808b223.png)

**Comment by Viish** [comment]
This has nothing to do on linphone-android repository.
Also from your screenshot this is from a desktop version 3.x, please update to 4.x
