### ISSUE TITLE
Streaming on SIP server on Android Project

### ISSUE THREAD

**Issue by Janos1977** [BelledonneCommunications/linphone-android#97]
I try to send a stream video to SIP server on Android project. It's possible to do this using Linphone Library?
Where I can find some tutorials for this use case?
Thanks

**Comment by nhoxbypass** [comment]
Yes, but your SIP server must support video streaming thought, cause I test with my SIP server and it did not work.

**Comment by Janos1977** [comment]
It supports. But calling inviteAddressWithParams(address, params) method, I always receive Linphone Mini: Error in connect: Network is unreachable. Anyone can help me?
Thx
