### ISSUE TITLE
How to stable call on background after 5-10 min?

### ISSUE THREAD

**Issue by RohitE2logy** [BelledonneCommunications/linphone-android#970]
calls are coming in the background but after 5-10 min calls are not coming.
an app is in the background state, background service is running, restart the app, then after, calls are not receiving. 
if restart my network/internet on/off then calls are receiving. 

so please help me with resolving the problem.

**Comment by Viish** [comment]
Please attach library logs.

**Comment by RohitE2logy** [comment]
@Viish 
Actually we have applied library code in the project based on my requirement.
which log do you want to form my side?

**Comment by Viish** [comment]
Enable debug logs in our library (using the Factory object) and either attach the adb logcat output or use the log upload feature (on Core object) and attach the link or the file here.
