### ISSUE TITLE
G729 issue

### ISSUE THREAD

**Issue by chuckwhisler** [BelledonneCommunications/linphone-android#971]
I have enabled Non free codecs,g729 and g729b in cmake settings.But i am unable to see the it in the audio codecs list.How can i enable it to be showed in the audio codecs list.

**Comment by chuckwhisler** [comment]
I am using Lastest Linphone sdk,Android 10,Developing on MAC Osx 10 Android Studio.

**Comment by Viish** [comment]
Most probably either you had a build issue and the AAR wasn't generated properly or the build number of the generated AAR is lower than our latest snapshot.
To ensure you are using your locally built AAR you can remove in the build.gradle our online maven repository and only keep the local one.

**Comment by Adnan-addi** [comment]
I also want to enable codec g729 on linphone version 4.3.0 
can you guide me how to enable codec g729 for latest version of linphone ,
CURRENTLY it does not Appear in under Audio Codecs.

**Comment by Viish** [comment]
G729 isn't enabled on our uploaded AARs.
You have to build one yourself to enable it.

**Comment by chuckwhisler** [comment]
I already build it with g729 . Btw thanks for your answer @Viish .
