### ISSUE TITLE
Video capture brightness control

### ISSUE THREAD

**Issue by sdh4** [BelledonneCommunications/linphone-android#972]
I am experiencing very dark video capture using the front facing camera on a Pixel 2 running the Android 10 AOSP with all the latest updates. 

Autoexposure functionality is working but only has an effect when pointed at a very bright light. The back-facing camera gives normal brightness. 

Having looked at the simplicity of the relevant code in mediastreamer2, I don't really see what could be going on.  Everything looks normal  

Obviously a video brightness slider in the settings would likely solve this problem. 

Since other apps don't seem to be affected, I would guess it is something about how the camera is being configured. It is possible the old camera api is no longer well supported.

**Comment by Viish** [comment]
Hi,
Can you attach adb logcat logs from when it happens please (with linphone debug logs enabled)?
Thanks.

**Comment by sdh4** [comment]
Logs attached
[linphone_darkscreen_adblog.txt](https://github.com/BelledonneCommunications/linphone-android/files/4490189/linphone_darkscreen_adblog.txt)

**Comment by Viish** [comment]
Hi,
Can you edit the android-camera2-capture.cpp file in linphone-sdk/msandroidcamera2/ and replace TEMPLATE_RECORD by TEMPLATE_PREVIEW, build again and test ?
Thanks in advance.

**Comment by Viish** [comment]
Can you try with msandroidcamera2 commit 25c4331897a97302b998c914fc31875bdaac45b4 please?
