### ISSUE TITLE
how to use linphone for screen share

### ISSUE THREAD

**Issue by ffyliu** [BelledonneCommunications/linphone-android#975]
Now I uses linphone to complete the function of voice conference. currently, I need to share the screen of the current device. android os has related functions of recording screen. please ask if there is any way to send the content of recording screen out in real time to complete the function of screen sharing. Thank you very much.
Looking forward to your reply.

**Comment by Viish** [comment]
Hi,
No currently we don't support screen sharing.
Cheers,

**Comment by avalanche15** [comment]
> Hi, No currently we don't support screen sharing. Cheers,

hey ，linphone-sdk 5.3 can use webrtc for sharing screen？

**Comment by avalanche15** [comment]
ok，When can version 5.4 be used， plz tell me





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sylvain ***@***.***&gt;; 
发送时间: 2024年8月1日(星期四) 下午5:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [BelledonneCommunications/linphone-android] how to use linphone for screen share (#975)














 
Screen sharing was added in 5.4 SDK, only for desktop platform for now.
 Regarding the WebRTC compatibility we haven't tested it out yet so I can't say.

**Comment by Viish** [comment]
@avalanche15, You can already use it, it's available on the master branch of linphone-sdk repository.

**Comment by avalanche15** [comment]
> @avalanche15, You can already use it, it's available on the master branch of linphone-sdk repository.

ok i will download it  thanks

**Comment by avalanche15** [comment]
hey，can u tell how to use conference part about video conference uri 。And if i want to use sharing screen i need do what？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sylvain ***@***.***&gt;; 
发送时间: 2024年8月1日(星期四) 下午5:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [BelledonneCommunications/linphone-android] how to use linphone for screen share (#975)














 
@avalanche15, You can already use it, it's available on the master branch of linphone-sdk repository.

**Comment by avalanche15** [comment]
> 

> @avalanche15, You can already use it, it's available on the master branch of linphone-sdk repository.



> @avalanche15, You can already use it, it's available on the master branch of linphone-sdk repository.

hey，i cant understand the conference uri how to set it，and if i want to use the function sharing screen，i need to use conference function？and if i want to use conference , i need Flexisip?what is Flexisip? it is a server?
