### ISSUE TITLE
Avatar in call log not updated when deleting items from call log

### ISSUE THREAD

**Issue by eshattow** [BelledonneCommunications/linphone-android#977]
I deleted two screen's worth of interspersed items from call log. After confirming the intended entries are gone, correctly so. However the Avatar images of the remaining call log items don't seem to line up to their correct phone numbers. Pictures of contacts I recognize next to phone numbers that are certainly not theirs.

Linphone Android 4.3-alpha.36+3e94feee (debug)
Linphone SDK 4.4.0-alpha.118+4468bd0 (remotes/origin/HEAD)

**Comment by Viish** [comment]
I don't understand your issue.
Can you attach some screenshots or a video of the issue please?

**Comment by eshattow** [comment]
Actually now I don't think this issue is about deleting items.

I'm not sure how to debug or show the issue without sharing private information.

One of my contacts "M" as listed in several Linphone Android call log entries with a contact photo. It is a Android merged contact from Google Account and also default DAVx5 Address book. The photo is part of the Google Account address book.

When I look to my Linphone Android call log listing "M" is seen on the call log list with their photo (where there would otherwise be a background flat color circle and text like initials, or a flat color person contact symbol silhouette), however some 10 or 11 days back in history on the log there are non-"M" call log entries shown with "M" photo.

If I tap the ellipsis '...' next to any call log item and return to call log '<--' then the call log changes to show correct "M" photo (or lack thereof) in the list for call log items. This is temporary fix and reverts to strange behavior when restarting or doing some operations on Linphone (for example changing to Search contacts view and then back to call log the wrong behavior is visible again). Not all the items are wrong Avatar images; The first 26 items over 10 days span are displayed correctly.

**Comment by Viish** [comment]
It probably simply is a scrolling issue with the avatar cache.
I can't reproduce it feature/kotlin_rewrite branch that will be used for next release.
