### ISSUE TITLE
Linphone sip registration failure using VPN 

### ISSUE THREAD

**Issue by Cullian2017** [BelledonneCommunications/linphone-android#978]
same sip account registration from two different internet connections has different results. if registration from normal internet connection, it is working properly, but if registration from VPN internet connection, Linphone  can not receive 401 Unauthorized from Softswitch (VOS3000). for both scenarios, Softswitch send the same response.

**log for registration from normal internet connection**

[0055558613337830632,117.62.182.227,1587110394|15:59:54.613054|EP>SERVER|117.62.182.227:12984|REGISTER|172.20.223.141:6060]
REGISTER sip:47.254.74.167:6060 SIP/2.0
Via: SIP/2.0/UDP 10.0.2.16:51875;branch=z9hG4bK.arX~Pq6Wj;rport
From: "123123" <sip:0055558613337830632@47.254.74.167>;tag=eIyW0sXZS
To: "123123" <sip:0055558613337830632@47.254.74.167>
CSeq: 20 REGISTER
Call-ID: lXcn9AeTc3
Max-Forwards: 70
Supported: replaces, outbound, gruu
Accept: application/sdp
Accept: text/plain
Accept: application/vnd.gsma.rcs-ft-http+xml
Contact: "123123" <sip:0055558613337830632@10.0.2.16:51875;transport=udp>;+sip.instance="<urn:uuid:5fdd5952-eeb4-003f-8346-3ab836c7a23f>"
Expires: 3600
User-Agent: LinphoneAndroid/4.2 (sdk_gphone_x86) LinphoneSDK/4.3-debug (tags/4.3^0)

[0055558613337830632,117.62.182.227,1587110394|15:59:54.613098|SERVER>EP|172.20.223.141:6060|Unauthorized|117.62.182.227:12984]
SIP/2.0 401 Unauthorized
Via: SIP/2.0/UDP 10.0.2.16:51875;branch=z9hG4bK.arX~Pq6Wj;received=117.62.182.227;rport=12984
From: "123123" <sip:0055558613337830632@47.254.74.167>;tag=eIyW0sXZS
To: "123123" <sip:0055558613337830632@47.254.74.167>
Call-ID: lXcn9AeTc3
CSeq: 20 REGISTER
WWW-Authenticate: Digest realm="172.20.223.141",nonce="4b53e3b63e7532b80160492a"

[0055558613337830632,117.62.182.227,1587110394|15:59:54.795561|EP>SERVER|117.62.182.227:12984|REGISTER|172.20.223.141:6060]
REGISTER sip:47.254.74.167:6060 SIP/2.0
Via: SIP/2.0/UDP 10.0.2.16:51875;branch=z9hG4bK.zOQchiRo8;rport
From: "123123" <sip:0055558613337830632@47.254.74.167>;tag=eIyW0sXZS
To: "123123" <sip:0055558613337830632@47.254.74.167>
CSeq: 21 REGISTER
Call-ID: lXcn9AeTc3
Max-Forwards: 70
Supported: replaces, outbound, gruu
Accept: application/sdp
Accept: text/plain
Accept: application/vnd.gsma.rcs-ft-http+xml
Contact: "123123" <sip:0055558613337830632@117.62.182.227:12984;transport=udp>;+sip.instance="<urn:uuid:5fdd5952-eeb4-003f-8346-3ab836c7a23f>"
Expires: 3600
User-Agent: LinphoneAndroid/4.2 (sdk_gphone_x86) LinphoneSDK/4.3-debug (tags/4.3^0)
Authorization:  Digest realm="172.20.223.141", nonce="4b53e3b63e7532b80160492a", username="0055558613337830632",  uri="sip:47.254.74.167:6060", response="1a8405205b6a82e2b43d0818aaca525f"

[0055558613337830632,117.62.182.227,1587110394|15:59:54.795604|SERVER>EP|172.20.223.141:6060|OK|117.62.182.227:12984]
SIP/2.0 200 OK
Via: SIP/2.0/UDP10.0.2.16:51875;branch=z9hG4bK.zOQchiRo8;received=117.62.182.227;rport=12984
From: "123123" <sip:0055558613337830632@47.254.74.167>;tag=eIyW0sXZS
To: "123123" <sip:0055558613337830632@47.254.74.167>
Call-ID: lXcn9AeTc3
CSeq: 21 REGISTER
Contact: <sip:0055558613337830632@117.62.182.227:12984;transport=udp>
Expires: 60

**log for registration using VPN internet connection**

[0055558613337830632,117.62.182.227,1587110755|16:05:55.984804|EP>SERVER|117.62.182.227:11032|REGISTER|172.20.223.141:6060]
REGISTER sip:47.254.74.167:6060 SIP/2.0
Via: SIP/2.0/UDP 10.0.2.16:47692;branch=z9hG4bK.fIIZHqoCn;rport
From: "wqeqwe " <sip:0055558613337830632@47.254.74.167>;tag=ZwDSo3GyQ
To: "wqeqwe " <sip:0055558613337830632@47.254.74.167>
CSeq: 20 REGISTER
Call-ID: 0qH46Std6E
Max-Forwards: 70
Supported: replaces, outbound, gruu
Accept: application/sdp
Accept: text/plain
Accept: application/vnd.gsma.rcs-ft-http+xml
Contact: "wqeqwe " <sip:0055558613337830632@10.0.2.16:47692;transport=udp>;+sip.instance="<urn:uuid:d37e4943-f79b-00ff-985c-f92197ea3bea>"
Expires: 3600
User-Agent: LinphoneAndroid/4.2 (sdk_gphone_x86) LinphoneSDK/4.3-debug (tags/4.3^0)

[0055558613337830632,117.62.182.227,1587110755|16:05:55.984848|SERVER>EP|172.20.223.141:6060|Unauthorized|117.62.182.227:11032]
SIP/2.0 401 Unauthorized
Via: SIP/2.0/UDP 10.0.2.16:47692;branch=z9hG4bK.fIIZHqoCn;received=117.62.182.227;rport=11032
From: "wqeqwe " <sip:0055558613337830632@47.254.74.167>;tag=ZwDSo3GyQ
To: "wqeqwe " <sip:0055558613337830632@47.254.74.167>
Call-ID: 0qH46Std6E
CSeq: 20 REGISTER
WWW-Authenticate: Digest realm="172.20.223.141",nonce="4b53e3b63e752b1801604a93"

**Comment by Viish** [comment]
Can you please attach the full library logs for the scenario that don't work please?

**Comment by Cullian2017** [comment]
Please check the attached files for details.

 

 

发件人: Sylvain Berfini [mailto:notifications@github.com] 
发送时间: 2020年4月18日 10:14
收件人: BelledonneCommunications/linphone-android
抄送: Cullian2017; Author
主题: Re: [BelledonneCommunications/linphone-android] Linphone sip registration failure using VPN (#978)

 

Can you please attach the full library logs for the scenario that don't work please?

**Comment by Cullian2017** [comment]
I compared with two register messages from Linphone log, the ip address for VIA and Contact parts is different fro two scenarios. for normal internet connection, it is using public IP address, while for vpn internet connection, it is using private ip address.

**Register request for normal internet connection**

[UDP://47.254.74.167:5060], size: [665] bytes
REGISTER sip:47.254.74.167 SIP/2.0
Via: SIP/2.0/UDP 192.168.100.5:38753;branch=z9hG4bK.FRwR3B0iu;rport
From: <sip:0055558613828839796@47.254.74.167>;tag=4qh3HjZe5
To: sip:0055558613828839796@47.254.74.167
CSeq: 20 REGISTER
Call-ID: ~g4ET5FKkR
Max-Forwards: 70
Supported: replaces, outbound, gruu
Accept: application/sdp
Accept: text/plain
Accept: application/vnd.gsma.rcs-ft-http+xml
Contact: <sip:0055558613828839796@192.168.100.5:38753;transport=udp>;+sip.instance="<urn:uuid:a86a7791-524f-00ff-a6b7-c7d7e3a2cb7f>";+org.linphone.specs="groupchat,lime"
Expires: 3600
User-Agent: LinphoneAndroid/4.2.3 (HUAWEI nova) LinphoneSDK/4.3.3 (tags/4.3.3^0)

**Register request for vpn internet connection**

[UDP://47.254.74.167:5060], size: [659] bytes
REGISTER sip:47.254.74.167 SIP/2.0
Via: SIP/2.0/UDP 172.19.0.1:42007;branch=z9hG4bK.UsXshsUJQ;rport
From: <sip:0055558613828839796@47.254.74.167>;tag=LZxJP~i-s
To: sip:0055558613828839796@47.254.74.167
CSeq: 20 REGISTER
Call-ID: eBwaJJM9yx
Max-Forwards: 70
Supported: replaces, outbound, gruu
Accept: application/sdp
Accept: text/plain
Accept: application/vnd.gsma.rcs-ft-http+xml
Contact: <sip:0055558613828839796@172.19.0.1:42007;transport=udp>;+sip.instance="<urn:uuid:a86a7791-524f-00ff-a6b7-c7d7e3a2cb7f>";+org.linphone.specs="groupchat,lime"
Expires: 3600
User-Agent: LinphoneAndroid/4.2.3 (HUAWEI nova) LinphoneSDK/4.3.3 (tags/4.3.3^0)

**Comment by Viish** [comment]
Please send the full logs.

**Comment by Cullian2017** [comment]
Dear Sylvain

 

I already attached the full logs in the previous email. I resend it again, please check the attached files for details.

 

Thanks & Regards

 

Jian Lu

 

发件人: Sylvain Berfini [mailto:notifications@github.com] 
发送时间: 2020年4月19日 17:56
收件人: BelledonneCommunications/linphone-android
抄送: Cullian2017; Author
主题: Re: [BelledonneCommunications/linphone-android] Linphone sip registration failure using VPN (#978)

 

Please send the full logs.

**Comment by Viish** [comment]
Sorry but there still aren't any log.
Attach them directly in a web browser instead of replying to the github email notification please.

**Comment by Cullian2017** [comment]
[registration from normal internet connection.txt](https://github.com/BelledonneCommunications/linphone-android/files/4502305/registration.from.normal.internet.connection.txt)
[registration from vpn internet connection.txt](https://github.com/BelledonneCommunications/linphone-android/files/4502306/registration.from.vpn.internet.connection.txt)

**Comment by Viish** [comment]
Please attach full library logs.
In the ones you attached I can only see the Register doesn't reach your server or the answer doesn't reach your device (quite common when using UDP, I strongly recommend you to switch to TCP or TLS).
