### ISSUE TITLE
Linphone SDK 4.2, register with tcp, after register, server is udp

### ISSUE THREAD

**Issue by showgoodjiang** [BelledonneCommunications/linphone-android#981]
Hi,

We use Linphone Android SDK 4.2 with Gradle:
https://linphone.org/releases/maven_repository/org/linphone/linphone-sdk-android/4.2-42-g838567e/

Here are the register code:

AccountCreator mAccountCreator = LinphoneService.getCore().createAccountCreator(null);

            String username = "aaa";
            String password = "bbb";
            String domain = "ccc";

            mAccountCreator.setUsername(userBean.getCcUserInfo().getExtensionNo());
            mAccountCreator.setDomain(userBean.getCcUserInfo().getDomain());
            mAccountCreator.setPassword(userBean.getCcUserInfo().getExtensionPassword());
            **mAccountCreator.setTransport(TransportType.Tcp);**

            ProxyConfig cfg = mAccountCreator.createProxyConfig();
            
            String sipAddressStr = "sip:" + username + '@' + domain;
            String proxyAddressStr = "sip:" + userBean.getCcServerProxy();
            
            int expire = 128;

            cfg.setIdentityAddress(LinphoneService.getCore().createAddress(sipAddressStr));
            cfg.setServerAddr(proxyAddressStr);
            cfg.setRoute(proxyAddressStr);
            cfg.enableRegister(true);
            cfg.setExpires(expire);

However, check server register info, is udp, not tcp.

While using Linphone apk:
https://www.linphone.org/releases/android/linphone-android-4.2.3.apk

Register with tcp in client, we can get tcp in server.

**Comment by Viish** [comment]
Hi,

This is normal. The transport you set in the account creator is overriden when you set the ServerAddr and the Route right after, as the transport information is stored in these fields.

Your proxyAddress should be: "<sip:username@domain;transport=tcp>".

The best way to fix that is to do the following:
`Address proxyAddress = Factory.createAddress(proxyAddressStr);
proxyAddress.setTransport(TransportType.Tcp);
cfg.setServerAddress(proxyAddress.asStringUriOnly();`

**Comment by showgoodjiang** [comment]
Viish,

      Work as expected now.
      Thank you. :)

Jeremy
