### ISSUE TITLE
Speech distortion

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#982]
Hi，

When a device calls another device, when the other party answers the call, it will feel voice distortion for about 4 seconds, and then it will be OK again. What's the reason and how to improve it?

thanks.

**Comment by Viish** [comment]
Hi,
Please attach library logs.

**Comment by fengqz627** [comment]
[indoor.txt](https://github.com/BelledonneCommunications/linphone-android/files/4508945/indoor.txt)
[outdoor.txt](https://github.com/BelledonneCommunications/linphone-android/files/4508948/outdoor.txt)

Outdoor calls into indoor. After indoor answers the call, it talks in indoor and listens in outdoor. It is found that the voice is distorted.
I called twice, and soon after the second answer, I heard a distorted voice

**Comment by Viish** [comment]
Can be a lot of things.
Try to disable video and/or echo canceller, also you can enable AVPF to see if it changes something.
Do you have the issue with other devices or in the other way?
Do you have the issue with our App from the store?

**Comment by fengqz627** [comment]
Hi，
1，Turn off the video. There seems to be no audio distortion
2，Turn off the  echo canceller, no effect
3，Our device doesn't need to go through SIP server. It calls directly. Doesn't it need to set AVPF? If so, how to set the parameter n in avpfenabled (int n)?
4, I don't have any other device. The device I have now has this problem of distorted sound
5，Apk is a linphone release SDK that I downloaded and compiled by myself
What is the cause of this problem? The distortion is only about 4 seconds, after which it returns to normal, and the distortion start time is uncertain, usually a few seconds after the call.

**Comment by Viish** [comment]
Hi,
This could mean your device has low hardware capacity and fails to properly encode or decode audio while processing video frames.
You can try another audio codec less CPU consuming than Opus, like GSM.

**Comment by fengqz627** [comment]
Hi,
It's changed to GSM, which seems to have no effect。
I feel that the voice distortion is that the sender suddenly sends a lot of voice, resulting in voice superimposition and distortion.  I want to try to lose the voice of the first 1 to 2 seconds and not send it in buf? How to change it?

**Comment by Viish** [comment]
For that you will need to alter the code of the audio filter you use, probably openSLES (which is in mediastreamer2/src/android/).
I will close the issue as it isn't related to the Android app but our SDK, so feel free to reopen it on linphone-sdk repository.

**Comment by fengqz627** [comment]
Hi Viish,
When it is connected (200ok), I want to delay sending voice to the receiver for one second. How to modify it?

**Comment by fengqz627** [comment]
That is to say, after the connection, it is delayed for 1 second before msrtpsend
