### ISSUE TITLE
How to adjust the video resolution?

### ISSUE THREAD

**Issue by Roger1103** [BelledonneCommunications/linphone-android#983]
Linphone-Android 4.4  
Video call USES h264 code, sending video resolution is 1080*720, but received video resolution is 240*320.What should I do?

**Comment by Viish** [comment]
Hi,
This means your correspondent is configured to send you this resolution.
Change the configuration on your correspondent's device.
Cheers,

**Comment by Roger1103** [comment]
![微信图片_20200424151752](https://user-images.githubusercontent.com/9368422/80185413-e073c800-863e-11ea-8088-da2e3e915d7a.jpg)
![微信图片_20200424151816](https://user-images.githubusercontent.com/9368422/80185419-e2d62200-863e-11ea-97f9-e23311c0835f.jpg)
![微信图片_20200424151822](https://user-images.githubusercontent.com/9368422/80185422-e36eb880-863e-11ea-99a1-adc6e9c7dcce.jpg)

**Comment by Roger1103** [comment]
This is the information of the video. I can use the VP8 encoding without any problem

**Comment by Roger1103** [comment]
> Hi,
> This means your correspondent is configured to send you this resolution.
> Change the configuration on your correspondent's device.
> Cheers,
This is the information of the video. I can use the VP8 encoding without any problem

**Comment by Roger1103** [comment]
This is the information of the video. I can use the VP8 encoding without any problem

**Comment by Viish** [comment]
Can you attach logs?
I would guess your device MediaCodec implementation is crappy if VP8 works fine but not H264.

**Comment by Roger1103** [comment]
[linphone1.log](https://github.com/BelledonneCommunications/linphone-android/files/4527469/linphone1.log)

**Comment by Roger1103** [comment]
This is a log

**Comment by bingoxo** [comment]
has this been solved ? please don't close the issue if it's not solved yet

**Comment by Viish** [comment]
Yes this is solved in 4.4.x releases and newer.
