### ISSUE TITLE
Speech distortion

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#985]
Hi Viish,
I'm sorry, I don't know how to reopen a closed Issue, this issue is a continuation of #982,  what I want to ask is:
When it is connected (200ok), I want to delay sending voice to the receiver for one second.  that is to say, after the connection, it is delayed for 1 second before msrtpsend, how to modify it?

thanks.

**Comment by fengqz627** [comment]
Hi，
After investigation, I think the reason for this problem is that after connecting, the sender establishes a call and starts to send a bunch of audio and video packets. The receiver needs to gradually speed up the processing of sound in a very short time. If it can't be processed in a short time, it will lead to sound superposition, and some voice frames fail to decode, thus distortion. So I think one of the ways is to delay the voice transmission by 1 second after coding at the sender , is this modified in msrtp. C? If so, how to control the upper application? Do you have any good solutions?

thanks.

**Comment by fengqz627** [comment]
Hi Viish,
Is there any interface in the Android upper layer that can control RTP to start sending and stop sending, or where and how to control?

**Comment by Viish** [comment]
Hi,
No there is no way to do that currently.
If you must, you can hack into the mediastreamer2 project.
