### ISSUE TITLE
Error reason: NotAnswered

### ISSUE THREAD

**Issue by Strikelon** [BelledonneCommunications/linphone-android#986]
Hello. It seldom happens that an error occurs during a call:Error reason: NotAnswered.
In Java doc https://www.linphone.org/snapshots/docs/liblinphone/multilang/reference/java/linphone_reason.html

I found the following information: **The call was not answered in time (request timeout)**

But I do not understand what this means. 
This does not exactly mean that the first subscriber called the second for a long time, while the second did not pick up the phone, because in this case the answering machine is turned on.
 
Can you reveal in more detail in what cases a similar error "NotAnswered" may come?

Thank you!

**Comment by Viish** [comment]
Hi,
This simply means that the person you tried to reach didn't answer the call.
Cheers,
