### ISSUE TITLE
Building Native Linphone-SDK for android giving Error while building SDK

### ISSUE THREAD

**Issue by Adnan-addi** [BelledonneCommunications/linphone-android#987]
i am compiling latest source from git clone https://gitlab.linphone.org/BC/public/linphone-sdk.git --recursive
i am using ubuntu terminal :
 1. Create and go inside a directory where the SDK will be built:
 `mkdir build && cd build`
 2. Execute CMake to configure the project:
 `cmake <SOME OPTIONS> ..`
 3. Build the SDK:
 `cmake --build . ` 
 or 
 `cmake --build . --parallel <number of jobs>` (which is faster).

followed these rules and having this error below :
please i need to build local native android linphone with bcg 729 enabled .?

-- Could NOT find ALSA (missing: ALSA_INCLUDE_DIRS ALSA_LIBRARIES HAVE_ALSA_ASOUNDLIB_H HAVE_SND_PCM_OPEN) 
-- Could NOT find PulseAudio (missing: PULSEAUDIO_INCLUDE_DIRS PULSEAUDIO_LIBRARIES HAVE_PULSE_PULSEAUDIO_H HAVE_PA_MAINLOOP_NEW) 
-- Found X11: /usr/include  
-- Could NOT find Xv (missing: HAVE_X11_EXTENSIONS_XVLIB_H HAVE_XV_CREATE_IMAGE) 
-- Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY OPENGL_INCLUDE_DIR) 
-- Could NOT find GLX (missing: GLX_INCLUDE_DIRS HAVE_GL_GL_H HAVE_GL_GLX_H GLX_LIBRARIES) 
-- Found VPX: /home/adnan/Desktop/lin3/linphone-sdk/linphone-sdk/desktop/include  
CMake Error at CMakeLists.txt:322 (message):
  Could not find a support sound driver API.  Use -DENABLE_SOUND=NO if you
  don't care about having sound.

-- Configuring incomplete, errors occurred!
See also "/home/adnan/Desktop/lin3/linphone-sdk/WORK/desktop/Build/ms2/CMakeFiles/CMakeOutput.log".
CMakeFiles/EP_ms2.dir/build.make:117: recipe for target '/home/adnan/Desktop/lin3/linphone-sdk/WORK/desktop/Stamp/EP_ms2/EP_ms2-configure' failed
make[5]: *** [/home/adnan/Desktop/lin3/linphone-sdk/WORK/desktop/Stamp/EP_ms2/EP_ms2-configure] Error 1
CMakeFiles/Makefile2:114: recipe for target 'CMakeFiles/EP_ms2.dir/all' failed
make[4]: *** [CMakeFiles/EP_ms2.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/sdk.dir/build.make:112: recipe for target 'sdk-prefix/src/sdk-stamp/sdk-build' failed
make[2]: *** [sdk-prefix/src/sdk-stamp/sdk-build] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/sdk.dir/all' failed
make[1]: *** [CMakeFiles/sdk.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Viish** [comment]
These are missing dependencies for desktop SDK.
Check you have set -DLINPHONESDK_PLATFORM=Android to your cmake options.

**Comment by Adnan-addi** [comment]
OK i tried your answer and it started to work but again ran into some critical errors....
i wonder why linphone doesnot use prepare.py method now . 
cmake method is really hard to understand.
Anyway my goal is to build linphone for android with audio codec g729 and than start it in android studio for customization . please help in this regard.... how i have to do it .

one other thing all commands work in root directory and in the build directory nothing happens ,...
what i am doin wrong ?

[ 97%] Building CXX object tester/CMakeFiles/linphonetester.dir/main-db-tester.cpp.o
[ 98%] Linking CXX shared library liblinphonetester.so
bionic/libc/include/bits/fortify/unistd.h:174: error: undefined reference to '__write_chk'
bionic/libc/include/bits/fortify/unistd.h:174: error: undefined reference to '__write_chk'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
tester/CMakeFiles/linphonetester.dir/build.make:760: recipe for target 'tester/liblinphonetester.so' failed
make[8]: *** [tester/liblinphonetester.so] Error 1
CMakeFiles/Makefile2:655: recipe for target 'tester/CMakeFiles/linphonetester.dir/all' failed
make[7]: *** [tester/CMakeFiles/linphonetester.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make[6]: *** [all] Error 2
CMakeFiles/EP_linphone.dir/build.make:145: recipe for target '/home/adnan/Desktop/test1/linphone-sdk/WORK/android-armv7/Stamp/EP_linphone/EP_linphone-build' failed
make[5]: *** [/home/adnan/Desktop/test1/linphone-sdk/WORK/android-armv7/Stamp/EP_linphone/EP_linphone-build] Error 2
CMakeFiles/Makefile2:166: recipe for target 'CMakeFiles/EP_linphone.dir/all' failed
make[4]: *** [CMakeFiles/EP_linphone.dir/all] Error 2
Makefile:103: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/android-armv7.dir/build.make:133: recipe for target 'android-armv7-prefix/src/android-armv7-stamp/android-armv7-build' failed
make[2]: *** [android-armv7-prefix/src/android-armv7-stamp/android-armv7-build] Error 2
CMakeFiles/Makefile2:158: recipe for target 'CMakeFiles/android-armv7.dir/all' failed
make[1]: *** [CMakeFiles/android-armv7.dir/all] Error 2
Makefile:103: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Adnan-addi** [comment]
all files generating in WORK folder

**Comment by Viish** [comment]
I don't know why but you have a build issue in the tester library. As it is not mandatory, you can try disable it. To do so, add the following to your cmake options: -DENABLE_UNIT_TESTS=NO

**Comment by Adnan-addi** [comment]
@Viish 
Thank You so much for the response ,
i am following each step and every new try brings some new error , 

kindly check this link :
https://github.com/BelledonneCommunications/linphone-android/issues/988
