### ISSUE TITLE
Building Local Linphone-SDK for android giving Error while building SDK for Andorid

### ISSUE THREAD

**Issue by Adnan-addi** [BelledonneCommunications/linphone-android#988]
OK i tried your answer and it started to work but again ran into some critical errors....
i wonder why linphone doesnot use prepare.py method now .
cmake method is really hard to understand.

However ! 
running cmake command with -DLINPHONESDK_PLATFORM=Android -DENABLE_G729=ON
command runs at root level , nothing happens in build directory and all files generate in WORK directory ,

Q2: how can i later use this in android studio for customization and ui changes ?

Anyway my goal is to build linphone for android with audio codec g729 and than start it in android studio for customization . please help in this regard.... how i have to do it .

one other thing all commands work in root directory and in the build directory nothing happens ,...
what i am doing wrong ?
Scanning dependencies of target belr-compiler
[ 58%] Building CXX object tools/CMakeFiles/belr-compiler.dir/belr-compiler.cc.o
[ 66%] Linking CXX executable belr-compiler
/home/adnan/Downloads/android-ndk-r21b-linux-x86_64/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: liblog.so, needed by /home/adnan/Desktop/test2/linphone-sdk/build/linphone-sdk/desktop/android-arm64/lib/libbctoolbox.so, not found (try using -rpath or -rpath-link)
/home/adnan/Desktop/test2/linphone-sdk/build/linphone-sdk/desktop/android-arm64/lib/libbctoolbox.so: undefined reference to `__android_log_assert'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
tools/CMakeFiles/belr-compiler.dir/build.make:105: recipe for target 'tools/belr-compiler' failed
make[8]: *** [tools/belr-compiler] Error 1
CMakeFiles/Makefile2:186: recipe for target 'tools/CMakeFiles/belr-compiler.dir/all' failed
make[7]: *** [tools/CMakeFiles/belr-compiler.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make[6]: *** [all] Error 2
CMakeFiles/EP_belr.dir/build.make:134: recipe for target '/home/adnan/Desktop/test2/linphone-sdk/build/WORK/android-arm64/Stamp/EP_belr/EP_belr-build' failed
make[5]: *** [/home/adnan/Desktop/test2/linphone-sdk/build/WORK/android-arm64/Stamp/EP_belr/EP_belr-build] Error 2
CMakeFiles/Makefile2:963: recipe for target 'CMakeFiles/EP_belr.dir/all' failed
make[4]: *** [CMakeFiles/EP_belr.dir/all] Error 2
Makefile:103: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/android-arm64.dir/build.make:133: recipe for target 'android-arm64-prefix/src/android-arm64-stamp/android-arm64-build' failed
make[2]: *** [android-arm64-prefix/src/android-arm64-stamp/android-arm64-build] Error 2
CMakeFiles/Makefile2:185: recipe for target 'CMakeFiles/android-arm64.dir/all' failed
make[1]: *** [CMakeFiles/android-arm64.dir/all] Error 2
Makefile:103: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Adnan-addi** [comment]
M i using the correct ndk version ?

**Comment by Adnan-addi** [comment]
@Viish please check above error i am following your instructions but after fixing that particular problem i ran into another error . kindly check the logs and suggest what mistake i am doing i shall be very thankful.

**Comment by Viish** [comment]
There is no need to open a new issue for that, we can continue our chat in a closed ticket.
Anyway, try using an older NDK (like 20, 19 or 17c).
Also please read the README file, it will answer all your questions.

**Comment by Adnan-addi** [comment]
ok thank you much , I have used android-ndk-r18b and it didmot showed that error , and i guess i am very near to success if this last one gets fix kindly check 

> Configure project :
Old java wrapper detected, adding it to sources and removing some incompatible classes

> Task :copyAssets NO-SOURCE
> Task :copyProguard NO-SOURCE
> Task :listPlugins UP-TO-DATE
> Task :preBuild UP-TO-DATE
> Task :preReleaseBuild UP-TO-DATE
> Task :compileReleaseAidl NO-SOURCE
> Transform commons-compress.jar (org.apache.commons:commons-compress:1.16.1) with IdentityTransform
> Transform annotations.jar (org.jetbrains:annotations:19.0.0) with IdentityTransform
> Transform objenesis.jar (org.objenesis:objenesis:2.6) with IdentityTransform
> Task :compileReleaseRenderscript
> Transform annotations.jar (org.jetbrains:annotations:19.0.0) with IdentityTransform
> Transform commons-compress.jar (org.apache.commons:commons-compress:1.16.1) with IdentityTransform
> Transform objenesis.jar (org.objenesis:objenesis:2.6) with IdentityTransform
> Task :checkReleaseManifest
> Task :generateReleaseBuildConfig
> Task :generateReleaseResValues
> Task :generateReleaseResources
> Task :packageReleaseResources
> Task :processReleaseManifest
> Task :generateReleaseRFile
> Task :prepareLintJar
> Task :generateReleaseSources
> Task :javaPreCompileRelease

> Task :compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :extractReleaseAnnotations
> Task :extractReleaseAnnotations FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':lintClassPath'.
> Could not resolve com.android.tools.lint:lint-gradle:26.3.2.
  Required by:
      project :
   > Could not resolve com.android.tools.lint:lint-gradle:26.3.2.
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle/26.3.2/lint-gradle-26.3.2.pom'.
         > Could not HEAD 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle/26.3.2/lint-gradle-26.3.2.pom'.
            > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 46s
11 actionable tasks: 11 executed
CMake Error at /home/adnan/Desktop/test3/linphone-sdk/cmake/Android/GenerateSDK.cmake:49 (message):
  Gradle assemble failed


CMakeFiles/sdk.dir/build.make:77: recipe for target 'CMakeFiles/sdk' failed
make[2]: *** [CMakeFiles/sdk] Error 1
CMakeFiles/Makefile2:131: recipe for target 'CMakeFiles/sdk.dir/all' failed
make[1]: *** [CMakeFiles/sdk.dir/all] Error 2
Makefile:103: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Adnan-addi** [comment]
is the project now is state where i can run in android studio and fix this lint error i have to cmake again ?

**Comment by Adnan-addi** [comment]
I tried importing the build into android studio and there after building i got success 
kindly check response:

Executing tasks: [:assembleDebug] in project /home/adnan/Desktop/test3/linphone-sdk/build


> Configure project :
Old java wrapper detected, adding it to sources and removing some incompatible classes

> Task :copyAssets NO-SOURCE
> Task :copyProguard NO-SOURCE
> Task :listPlugins UP-TO-DATE
> Task :preBuild UP-TO-DATE
> Task :preDebugBuild UP-TO-DATE
> Task :compileDebugAidl NO-SOURCE
> Task :compileDebugRenderscript
> Task :checkDebugManifest
> Task :generateDebugBuildConfig
> Task :generateDebugResValues
> Task :generateDebugResources
> Task :packageDebugResources
> Task :processDebugManifest
> Task :generateDebugRFile
> Task :prepareLintJar
> Task :generateDebugSources
> Task :javaPreCompileDebug

> Task :compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :extractDebugAnnotations
> Task :mergeDebugConsumerProguardFiles
> Task :mergeDebugShaders
> Task :compileDebugShaders
> Task :generateDebugAssets
> Task :packageDebugAssets
> Task :packageDebugRenderscript NO-SOURCE
> Task :processDebugJavaRes NO-SOURCE
> Task :transformResourcesWithMergeJavaResForDebug
> Task :transformClassesAndResourcesWithSyncLibJarsForDebug
> Task :compileDebugNdk NO-SOURCE
> Task :mergeDebugJniLibFolders
> Task :transformNativeLibsWithMergeJniLibsForDebug
> Task :transformNativeLibsWithSyncJniLibsForDebug
> Task :bundleDebugAar
> Task :compileDebugSources
> Task :assembleDebug

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 10s
21 actionable tasks: 21 executed


This response is from Android Studio ,

If this is al success than why I can't see all java and layout files , 
that brings me another question do i have to import this sdk into the source code with AAR build ?
will that bring g729 codec ?
please help ....

**Comment by Adnan-addi** [comment]
@Viish **Thank You**
I am successful enabling g729 codec on linphone android , 
your help is much appreciated .
and sdk is working perfect with g729 audio codec.

**Comment by Mukesh2310** [comment]
@Adnan-addi

Can you please help me out, How to enable G729 audio codec in linphone 4.3.0 SDK
please i am in trouble from a couple of days your help must need hope you understand?
