### ISSUE TITLE
Pushnotification Not Working in Linphone Playstore app also

### ISSUE THREAD

**Issue by hpng6** [BelledonneCommunications/linphone-android#989]
I have downloaded the the Linphone(4.2.3) from Playstore. i created two accounts In Linphone. then i Forcequit the the app in one divice, then i send message and call to 2nd device.

no message notification and call notification i see in Forcequit app device.

and also tested like screen off for for some time both devices.

**Comment by Viish** [comment]
Depending on your device, forcekill can prevent the reception of push notifications so you should never do that.
