### ISSUE TITLE
Cannot call Android phone from desktop using LAN sip address

### ISSUE THREAD

**Issue by eblanshey** [BelledonneCommunications/linphone-android#991]
On desktop, without creating any accounts there is a SIP address that uses a LAN IP. If I create a contact on my Android phone with the desktop's SIP address, it successfully initiates a video call over the LAN without needing any internet services. However, I cannot make the call in the other direction, from desktop to android phone. I use the same address that showed up on desktop when I initiated from Android, but not call is received. 

The notification saying "Linphone service" IS showing. Note that I don't actually see a way to check what my SIP address in the Android app -- I'm relying on the one I saw from desktop.

Is this a bug, or simply a missing feature (to use LAN without any external services?)

**Comment by Viish** [comment]
The main difference between your Android app and the desktop one is that on Android random port is enabled by default.
When you try to invite your desktop from the mobile app, the request is sent to port 5060 (standard SIP port) your desktop listen for.
However on mobiles the random port feature is enabled by default so it won't listen to port 5060.
Disable random port in settings and it should work.

**Comment by shodanx2** [comment]
Hi,
I am searching for this option to disable random port, I can not able to find it ?
Has it been removed ? 
I am using linphone 6.0.21 from f-droid on android 9
thanks !
