### ISSUE TITLE
i can call this number if i wake up phone manual... but if my phone sleep (doze idle) and i send push my phone. Linphone send to astrerisk epmty request 

### ISSUE THREAD

**Issue by bottookku** [BelledonneCommunications/linphone-android#996]
```
<--- SIP read from UDP:192.168.10.31:50967 --->


<------------->

```

and phone while not avialable from call, if i turn on it manual call is recieve normal.

but it not always...  infrequently after push notification linphone send normal register request and phone will avlailable.

linphone v. 4.2.3

sip.conf
```
[general]
bindport=5060                   ; UDP Port to bind to (SIP standard port is 5060)
bindaddr=0.0.0.0                ; IP address to bind to (0.0.0.0 binds to all)
context=default                 ; Default context for incoming calls

[authentication]

[123]
callerid=123
type=friend
secret=123
host=dynamic
permit=0.0.0.0/0
allow=alaw
allow=g729

[1234]
callerid=1234
type=friend
secret=1234
host=dynamic
permit=0.0.0.0/0
allow=alaw
allow=g729
```

**Comment by Viish** [comment]
Please attach library logs showing the issue.

**Comment by bottookku** [comment]
i not may it repeat because it take more time and doing repeat it only after unregistered in server side.
https://www.linphone.org:444//tmp/5eb04d2b73707_477c45997a6443a043b4.gz
2:12~ Time GMT +9

**Comment by bottookku** [comment]
https://www.linphone.org:444//tmp/5eb055e81cdd7_66096e6e4b31f738e40c.gz
+9 GMT 2:38-2:49 not recive push but last minutes linphone has been foreground, linphone registered and recieve push only after restart linphone

**Comment by bottookku** [comment]
https://www.linphone.org:444//tmp/5eb059241d839_8cdc81ae27d4075f8069.gz
phone has been in turn off screen. 
+9 GMT 3:00 i trying send push and call but linphone not  reaction calls and not send request sip headers on my asterisk.
~3:02 i turn on screen phone and open linphone in foreground but linphone not reaction on my calls and push.
~3:03 i restart linphone, and all be normal recieve calls and sip request on my asterisk when i send push.

**Comment by bottookku** [comment]
i can repeat it i send push and linprone send reempty request 
`<--- SIP read from UDP:192.168.10.31:64459 --->


<------------->
`
but i can't call to this linphone after push and recieve epmty sip request on my asterisk from linphone.

13:10~13:11 GMT+9
https://www.linphone.org:444//tmp/5eb0e7ee7cd71_66ea0fe447b8870a97e8.gz

**Comment by bottookku** [comment]
https://pastebin.com/vbwczc72
123 linphone 
1234 caller zoiper

**Comment by bottookku** [comment]
after last bugs i not touch phone not turn on screen. 
but 14:07 ~ 14:08 
he is on my push send register request and begin recieve calls.
https://www.linphone.org:444//tmp/5eb0f5bd1ceb4_11907db327a5d7dcecca.gz

**Comment by bottookku** [comment]
It seems to me that Asteriks sends an invitation request but the linphone does not respond

**Comment by Viish** [comment]
First of all I strongly recommend you to switch to a more reliable transport like TCP or TLS instead of UDP.
That being said, in your last log, I don't see any issue. The push is received, a REGISTER is sent and answered when needed. Your server doesn't send any request after that ir it get lost cause of UDP, that's all.

**Comment by bottookku** [comment]
yes is on my last log all work
