### ISSUE TITLE
The delay of voice in conversation is gradually reducing

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#997]
Hi，

1，When the caller and the called are connected, the sound delay on both sides becomes shorter and shorter, as if they are speeding up quickly. It'll be OK in a moment，What's the reason?
2，When the caller and the called are connected for the first time, the audio-video delay is relatively large. When they are connected later, the audio-video delay is relatively small. What's the reason?

thanks.

**Comment by Viish** [comment]
Hi,
Please open this ticket on linphone-sdk or mediastreamer2 repository.
