### ISSUE TITLE
connection issues on credentials update

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#998]
I changed username in asterisk pjsip, and than in linphone.

First time it works fine, but some time ago starts fail.

Asterisk says:
`WARNING[1802]: pjproject: <?>: 	                   SSL 6 [SSL_ERROR_ZERO_RETURN] (Read) ret: 0 len: 32000`

Linphone says:
`MESSAGE Register refresher [401] reason [Unauthorized] for proxy`

The only solution is to delete account and add a new one.

**Comment by Viish** [comment]
I can't help you for the asterisk part, but regarding the 401 that means the credentials configured on your device don't match the one asterisk expects.
Check the content of your .linphonerc file on your device.
